### ISSUE TITLE
Tab buttons are not shown in tabs with menu under android platform with version less than 5.

### ISSUE THREAD

**Issue by raceyi** [driftyco/ionic#8593] opened 2016-10-10 02:10 UTC
![2016-10-10-10-45-01](https://cloud.githubusercontent.com/assets/8307493/19225583/fb8c9f96-8ed9-11e6-96a1-34e3474ba81f.png)

Please check  https://github.com/raceyi/tabswithMenu for regeneration.  

It seems that tab buttons are hidden by tab page(.ion-page).
When I tab button area, button is shown but disappears right away.
I  changed z-index and opacity of tab buttons to show them up but failed.

This is quite urgent for me. Any workaround?

**Comment by jgw96** [comment] 2016-10-10 16:20
Hello, thanks for using Ionic! Are you using Ionic 2 RC0? Also, what version of Android are you seeing the issue on?

**Comment by raceyi** [comment] 2016-10-10 23:09
The github code is based on ionic2 RC0. Android version is 4.4.2. Please give me temporary solution.

**Comment by mayconjcm** [comment] 2016-10-11 21:37
Maybe you will have to use Crosswalk for Android < 5.0 ...

**Comment by raceyi** [comment] 2016-10-12 01:35
I had experienced the sam problem with second tabs in https://github.com/driftyco/ionic/issues/7837.
But it is fixed in RC0.

**Comment by jgw96** [comment] 2016-10-12 21:40
Hello @raceyi ! Unfortunately I cannot repro this issue on the Android 4.4.2 emulator. Are you trying this on an actual device or emulator?

**Comment by raceyi** [comment] 2016-10-12 22:54
I tested it on LG-F240S. hum... can you check the reason why #7837 happened and how it was fixed? I suppose that it comes from the same reason as their behaviors are exactly same.

**Comment by jgw96** [comment] 2016-10-17 16:17
Hmm, unfortunately I am still unable to reproduce this issue on the 4.4.2 emulator. @raceyi does using crosswalk fix this issue?

**Comment by raceyi** [comment] 2016-10-17 23:27
I found out a workaround solution. What I did is 

1. increase the height of ion-content more than screen height by add dummy div
    <ion-content #homeContent >

        <div class="dummy">
        </div>
    </ion-content>

    .dummy{
      height:70vh;
    }

2. configure the position of ion-header and ion-content  as relative
    ion-header {
         position: relative !important;
    }
    
    ion-content{
      position:relative !important;
    }

3. configure the length of scroll element of ion-content in ionViewDidEnter as below
    @ViewChild("homeContent") contentRef: Content;
    
     ionViewDidEnter(){
            let dimensions=this.contentRef.getContentDimensions();
            let height=this.contentRef.getNativeElement().parentElement.offsetHeight-dimensions.contentTop;
            this.contentRef.getScrollElement().setAttribute("style","height:"+height+"px;margin-top:0px;");
    }

    
I guess the problem comes from the wrong computation of height of elements related to ion-content.

**Comment by jgw96** [comment] 2016-10-18 18:39
Thanks for the debugging! Does this also happen when using crosswalk?

**Comment by raceyi** [comment] 2016-10-18 22:54
I had tried crosswalk to resolve #7837.  but crosswalk brought about other many issues.

**Comment by dig1234** [comment] 2016-10-21 15:26
the bug still exist when using sidemenu + tabs  combination on ionic 2.0.0

Cordova CLI: 6.3.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
OS:
Node Version: v6.8.1

 "dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/compiler-cli": "0.6.2",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "ionicons": "3.0.0",
    "rxjs": "5.0.0-beta.12",
    "@ionic/storage": "1.0.3",
    "ionic-angular": "2.0.0-rc.1",
    "ionic-native": "2.2.3",
    "ionicons": "3.0.0",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.21"
  },

**Comment by dig1234** [comment] 2016-10-21 15:37
and this trick works, copied from #7604 

ion-nav, ion-tab, ion-tabs {
z-index: -1;
}

**Comment by pskhodad** [comment] 2016-10-24 14:20
this issues seems to have been happening since beta.11. https://github.com/driftyco/ionic/commit/e4bbcc667a1c8f9a1aaade9a6c7ec79b8759ef67
might have caused it. since it happens on <5.0 android versions but not on crosswalk, it could be some problem related to transform not playing well with z-index.

**Comment by jgw96** [comment] 2016-10-25 15:32
Hello @pskhodad and @dig1234 are you all able to reproduce this issue with the android 4.4.2 emulator?

**Comment by pskhodad** [comment] 2016-10-26 03:06
Yes @jgw96 , it reproduces on android 4.4.2 emulator.

**Comment by jgw96** [comment] 2017-04-07 16:34
Hello all! I am going to close this issue as it has since been fixed.

**Closed by jgw96** 2017-04-07 16:34 UTC
Labels: v2
