### ISSUE TITLE
bug: Ionic 2 - Google Maps Native + Tabs issue

### ISSUE THREAD

**Issue by glaucomorais** [driftyco/ionic#7495] opened 2016-08-01 06:43 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>I have an app that have 2 tabs: Map and Friends.
The app starts in the Map tab with the Google Maps native. The maps shows normally.
When I change to the Friends tab, the transition occurs normally as expected. But, changing back to Map tab, the Friends tab still showing.
The only way to the map show again is destroying the map in the ionViewDidLeave function and rebuilding it in the ionViewWillEnter function, which is a extreme unproductive way to deal with it.</span>

Here is a video with the issue: https://youtu.be/SsdEmVBO4w8
<span is-issue-template></span>

**Comment by jgw96** [comment] 2016-08-01 13:05
Hello, thanks for opening an issue with us! I will be closing this issue as a duplicate of https://github.com/driftyco/ionic/issues/7260. Thanks for using Ionic!

**Closed by jgw96** 2016-08-01 13:05 UTC
Labels: platform:android, v2

**Comment by glaucomorais** [comment] 2016-08-02 21:27
Thanks for the advice. I'll take a look at it.
