### ISSUE TITLE
White artifact on navbar on page transition

### ISSUE THREAD

**Issue by RedEars** [driftyco/ionic#8189] opened 2016-09-23 15:11 UTC
#### Short description of the problem:
When navigating pages with push() on iOS version the page fade transition has a white artifact on the navbar. It looks like that this comes from the ion-content background. When changing it to the same color as navbar it works, but it's not a good fix, because then the content background will be in the same color. 

Just checkout this GIF to see the effect: http://g.recordit.co/GFSsmLTgnl.gif

#### What behavior are you expecting?
Same color as navbar on transitioning

**Steps to reproduce:**
Just navigate with push() on iOS Version (also on Browser)

**Which Ionic Version?** 
ionic 2 beta 11

#### Example GIF
http://g.recordit.co/GFSsmLTgnl.gif

**Comment by RedEars** [comment] 2016-09-26 16:11
Actually I just noticed that this is a duplicate of https://github.com/driftyco/ionic/issues/8060

**Comment by jgw96** [comment] 2016-09-29 14:18
Hello, thanks for opening an issue with us! I am going to be closing this as a duplicate of #8060

**Closed by jgw96** 2016-09-29 14:18 UTC
Labels: platform:ios, v2
