### ISSUE TITLE
Toast top overlaps statusbar in iOS

### ISSUE THREAD

**Issue by lujakob** [driftyco/ionic#11356] opened 2017-04-25 11:37 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[ x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The toast message container overlaps the statusbar in iOS devices. The css translateY value is set in Javascript hardcoded to 10px, which is too less.

**Expected behavior:**
Ideally this value could be set somehow. The default value should be bigger, e.g. 20px to be able to see the statusbar.

**Steps to reproduce:**
Present any statusbar in an iOS device.
**Related code:**
toast-transition.ts in line 16
```
wrapper.fromTo('translateY', '-100%', `${10}px`);
```

**Comment by jgw96** [comment] 2017-04-25 14:17
Hello, thanks for using Ionic! Could you post a screenshot of the issue your seeing?

**Comment by lujakob** [comment] 2017-04-26 11:36
![img_0192](https://cloud.githubusercontent.com/assets/886152/25432590/565d9474-2a85-11e7-89b6-5ac248aa649d.PNG)

**Comment by jgw96** [comment] 2017-05-02 15:01
Is cordova being loaded in this scenario?

**Comment by lujakob** [comment] 2017-05-03 08:14
This is a screenshot of my iPhone 5. All of the cordova plugins work as expected, so I guess yes. Or how can I verify your question?

**Comment by jgw96** [comment] 2017-05-18 18:11
Hello @lujakob , I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/8476.

**Closed by jgw96** 2017-05-18 18:11 UTC
Labels: needs info, v2
