### ISSUE TITLE
ionic 2 beta.11 ion-silides options, still present in Ionic 2 RC4

### ISSUE THREAD

**Issue by feifeiwoye** [driftyco/ionic#7595] opened 2016-08-08 02:27 UTC
open this page,First show the first page, and then jump to the second page
But I set second pages for the initial,beta.10 is Available

---

version: 2.0.0-beta.11

```
<ion-slides [options]="opts">
      <ion-slide>
    <h1>Slide 1</h1>
  </ion-slide>
  <ion-slide>
    <h1>Slide 2</h1>
  </ion-slide>
  <ion-slide>
    <h1>Slide 3</h1>
  </ion-slide>
</ion-slides>
```

---

```
export class test implements OnInit{
opts:any;
    ngOnInit() {
this.opts = {initialSlide: 2, pager: true}
}

}
```

**Comment by jgw96** [comment] 2016-08-08 17:33
Hello, thanks for opening an issue with us! Sorry, but i'm not understanding the issue fully. Would you mind creating a repo that i can use to test this issue? Thanks for using Ionic!

**Comment by feifeiwoye** [comment] 2016-08-09 01:12
@jgw96 

-------------------test.html----------------------------
```
<ion-content>
  <div>
    <ion-slides [options]="opts">
      <ion-slide *ngFor="let test of tests">{{test}}</ion-slide>
    </ion-slides>
  </div>
</ion-content>
```

-------------------test.ts----------------------------

```
@Component({
    templateUrl: 'build/pages/test/test.html',
})
export class TestPage implements OnInit{
    tests = [1,2,3];
    opts: any;
    constructor() {}
    ngOnInit() {
            this.opts = {initialSlide: 1, pager: true}
    }

}

```
--------------------------------------------------------
I have set {initialSlide: 1}.The initial index of second pages, but in version beta. 11 can see first display the first page, and then automatically jump to page second.In version beta.10,show second pages at once.

**Comment by szerner** [comment] 2016-08-09 06:38
I have that same issue with the `{ initialSlide = ...}` option. After the page with the slides has loaded, you can see (for a short time) the first of all slides and then the desired 'initialSlide'.

I tried to work around that issue and implemented a `slider.slideTo(initialSlide, 0, false)` statement within the various page cycle events (`ionViewLoaded`, `ionViewWillEnter`, `ionViewDidEnter`). Only within the `ionViewDidEnter `event the slideTo-statement works as expected and jumps to the 'initialSlide', but with the same tiny lag after showing the first of all slides. So no real workaround.

**Comment by petermm** [comment] 2016-10-06 20:47
still flashes first slide in rc0, before showing initialSlide: x

**Comment by axelauvinen** [comment] 2016-11-03 10:46
There are few bugs with initialSlide option:

1) Flickering of the view
2) After init with initialSlide option, you can't call getActiveIndex(), error: ORIGINAL EXCEPTION: Cannot read property 'activeIndex' of undefined.

I believe this is caused because the slide is changing to another one and ionDidChange is called

```
    this.horizontalSliderOptions = {
      loop: false,
      pager: false,
      direction: "horizontal",
      initialSlide: 1
    }

  (ionDidChange)="onSlideChanged()"

  onSlideChanged(e) {
    let activeHorizontal = this.horizontalSlider.getActiveIndex()
 }
```

**Comment by marteb** [comment] 2016-11-11 13:10
This bug is still present in Ionic 2 RC2.

**Comment by marteb** [comment] 2016-11-23 11:10
And in RC3 as well :-/

**Comment by AleFons** [comment] 2016-12-23 13:13
Still present on RC4; the shown slider is always the default at index 0 and then switches to whatever was set as initialSlide.

I have mentioned on another issue ( which I believe to be a duplicate of this one, [#9138](https://github.com/driftyco/ionic/issues/9138) ) and I've provided a repository to reproduce the issue that can be found [here](https://github.com/AleFons/sliderDemo).

**Comment by ericdude4** [comment] 2017-01-24 16:46
Has anyone tested this issue on RC5 ? I used a workaround on RC4 and it works but I'd rather have a stable solution...

**Comment by AleFons** [comment] 2017-01-24 18:29
@ericdude4 I'm using RC5 and while there are some slight differences in the implementation of ion-slides in it, it's working as intended. I believe the issue is now solved.

**Comment by brandyscarney** [comment] 2017-01-24 23:51
Thanks @AleFons. I am going to close this then, but please let me know if anyone sees the problem with RC6 and I will reopen. :)

**Closed by brandyscarney** 2017-01-24 23:51 UTC
Labels: v2

**Comment by miguelmchavez** [comment] 2017-02-09 14:26
Hey @ericdude4 can you post some example?

**Comment by ericdude4** [comment] 2017-02-10 08:26
@miguelmchavez would you like the solution that I found previously? **Recently I have updated to Ionic 2 stable release and the issue was resolved**, however, I would be more that happy to explain my fix.

**Comment by miguelmchavez** [comment] 2017-02-10 14:22
yes @ericdude4 , i like the solution that you found previously! Please.

**Comment by ericdude4** [comment] 2017-02-10 15:31
This was my solution on RC4, so if you are using an older one, the line where the code is may be different:

1) open node_modules > ionic-angular > components > slide > slide.js

2) locate the following (approx. line 262)

```javascript
setTimeout(function () {
     var swiper = new Swiper(_this.getNativeElement().children[0], options);
     _this.slider = swiper;
 }, 300);
```
3) replace this code with:

```javascript
setTimeout(function () {
     var swiper = new Swiper(_this.getNativeElement().children[0], options);
     _this.slider = swiper;
	
 });
 ```

**Comment by miguelmchavez** [comment] 2017-02-10 17:15
Great, can you post your final typescript page?

**Comment by miguelmchavez** [comment] 2017-02-10 17:16
@ericdude4 Great, can you post your final typescript page?

**Comment by ericdude4** [comment] 2017-02-15 07:40
@miguelmchavez the old typescript page you would have had with the initialSlide issue should work now. It will no longer flash the first slide before moving to the initialSlide.
