### ISSUE TITLE
bug: Scrollbar shown unnecessarily when content fits on page

### ISSUE THREAD

**Issue by FLHerne** [driftyco/ionic#4781] opened 2015-12-14 16:05 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>When native scrolling is enabled for an axis, 'overflow-y' (or -x) is set to 'scroll'. On desktop browsers at least, this forces the scrollbar to be displayed even if the content fits on the page and there's nothing to scroll through.

Using 'auto' rather than 'scroll' for these properties allows the scrollbar to be hidden in this case, which looks much nicer. Would this break in some case?
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-12-14 16:05
Greetings @FLHerne!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4781). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4781)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by FLHerne** [comment] 2015-12-14 16:26
Said form throws the error "Issue Update Error! Try again."

**Comment by mlynch** [comment] 2015-12-17 03:29
For now, we need to do it due to bug in safari with overflow touch scrolling. There's a solution for it that we can push later.  Duplicate of #4774

**Closed by mlynch** 2015-12-17 03:29 UTC
