### ISSUE TITLE
Ionic 2 FAB button disappear when switch between Tabs  on iOS 10.1.1

### ISSUE THREAD

**Issue by MrBokeh** [driftyco/ionic#9099] opened 2016-11-10 05:51 UTC
#### Short description of the problem:
Ionic 2 FAB button disappear when switch between Tabs  on iOS 10.1.1

#### What behavior are you expecting?
Ionic 2 FAB button don't disappear when switch between Tabs  on iOS 10.1.1

**Steps to reproduce:**
1. create a tabs project
2. add a FAB button on bottom right
3. switch to different tab and switch back

```
<ion-fab right bottom>
    <button ion-fab><ion-icon name="add"></ion-icon></button>
  </ion-fab>
```

**Which Ionic Version?** 2.0.0-rc.2

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan (it's actually the latest macOS Sierra 10.12.1 which it didn't pick up)
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62

**Comment by jgw96** [comment] 2017-05-02 16:42
Hello @MrBokeh , unfortunately, i cannot reproduce this issue. Are you still running into this issue with the latest version of Ionic?

**Comment by jgw96** [comment] 2017-05-05 18:18
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-05-05 18:18 UTC
Labels: needs info, v2
