### ISSUE TITLE
bug: $scope isn't disconnected from the $watch cycle

### ISSUE THREAD

**Issue by BetterTrader** [driftyco/ionic#3530] opened 2015-04-15 09:47 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Hi,
[This page](http://ionicframework.com/docs/api/directive/ionView/) says that when a view is navigated away from, the $scope is disconnected from the $watch cycle.
However, I have a tab that temporarily have a lot of watches (which slows down the app), and when I leave the tab - the apps stays slow, which means the watches are still being watched.

Is this a known bug?
Thank you</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-04-15 09:47
Greetings @BetterTrader!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3530). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3530)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by ajoslin** [comment] 2015-04-15 16:59
Do you have a reproduce case?

**Comment by Ionitron** [comment] 2015-04-15 19:33
Greetings @BetterTrader!

My sensors indicate that I require more information in order to assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this happen occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com), where many humans will be able to offer wisdom and advice.

Thank you for allowing me to assist you.

<span ionitron-needs-reply></span>

**Comment by BetterTrader** [comment] 2015-04-18 14:33
Hi, 
Sorry for the late response.
Here it is:
http://codepen.io/anon/pen/rVBweJ

Please open the console and watch what happens when you switch tabs.
Every entrance to "about" tab it prints the number of watches and adds another watch.
Every entrance to "contact" tab it only prints the number of watches.

I'm expecting to see that the number of watches when clicking the "contact" tab is not the same as in the "about" tab, the numbers shouldn't increase together, but they do.

Am I doing something wrong or is it really a bug?
Thank you

**Comment by camlough** [comment] 2015-07-02 08:06
+1 for this issue. still seeing this bug would love to see a solution!

**Comment by szuzul** [comment] 2015-09-28 11:54
looks like memory leak

**Comment by jgw96** [comment] 2016-04-29 18:24
Hello all! Are you still seeing this bug with the latest version of ionic 1? (1.3.0)

**Comment by jgw96** [comment] 2016-05-04 15:07
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-05-04 15:07 UTC
Labels: navigation, needs reply, v1
