### ISSUE TITLE
inset list header [color="dark"] background bug?

### ISSUE THREAD

**Issue by eidng8** [driftyco/ionic#8887] opened 2016-10-25 00:27 UTC
#### Short description of the problem:
    <ion-list inset no-lines>
      <ion-list-header no-padding color="dark">list header</ion-list-header>
      <ion-item color="dark">item 1</ion-item>
      <ion-item color="dark">item 2</ion-item>
      <ion-item color="dark">item 3</ion-item>
      <ion-item color="dark">item 4</ion-item>
    </ion-list>

Everything is fine, except the header background is in white.

#### What behavior are you expecting?

The header background color should be `dark`

 The [culprit](https://github.com/driftyco/ionic/blob/c1777c6d18390bc9fb66b067faca397a090c3a82/src/components/list/list.md.scss#L123-L125), is a hard coded background color applied to ion list headers, both `md` & `ios` modes.

**Which Ionic Version?** 1.x or 2.x
v2-rc.1

P.S. I've tried to create a rc1 plunker, but without success. Is there any good source?

**Comment by gigocabrera** [comment] 2016-10-25 14:47
The same issue is true for the `ion-item-divider`
```
<ion-item-divider color="dark">
     Title Here
</ion-item-divider>
```
The divider background color should be dark

**Comment by brandyscarney** [comment] 2016-10-25 14:52
Thanks for the issue! I'm going to close this as a duplicate of https://github.com/driftyco/ionic/issues/8376.

**Closed by brandyscarney** 2016-10-25 14:52 UTC
