### ISSUE TITLE
Error occurs while switching pages through <ion-menu>

### ISSUE THREAD

**Issue by ahunigel** [driftyco/ionic#7426] opened 2016-07-26 06:17 UTC
#### Short description of the problem:
Switch pages through `ion-menu` causes errors

#### What behavior are you expecting?
I put a `ion-menu` on a tabs page, which contains a `ion-refresher`, the code is almost like below:
```
<ion-menu [content]="content">
  <ion-toolbar>
    <ion-title>menu</ion-title>
  </ion-toolbar>

  <ion-content class="menu-content">
    <ion-refresher (ionRefresh)="doRefresh($event)">
      <ion-refresher-content
        pullingIcon="arrow-dropdown"
        [pullingText]=" 'refresher.pulling' | translate"
        refreshingSpinner="circles"
        refreshingText="{{'refresher.refreshingText' | translate}}">
      </ion-refresher-content>
    </ion-refresher>
  
    <ion-list>
      <button ion-item *ngFor="let p of pages" (click)="openPage(p)">
        {{p.title}}
      </button>
    </ion-list>
  </ion-content>
</ion-menu>

<ion-tabs #myTabs #content (ionChange)="onTabChange($event)" class="tabs-page">
  <ion-tab [root]="tab1Root" [rootParams]="tabParams" tabTitle="tab1" tabIcon="cube"></ion-tab>
  <ion-tab [root]="tab2Root" [rootParams]="tabParams" tabTitle="tab2" tabIcon="notifications"></ion-tab>
  <ion-tab [root]="tab3Root" [rootParams]="tabParams" tabTitle="tab3" tabIcon="settings"></ion-tab>
</ion-tabs>
```
When I tried to open 1 page through the page list, error occurs

> EXCEPTION: TypeError: Cannot read property 'style' of null at content.js:324 
Uncaught TypeError: Cannot read property 'style' of null
Content.setScrollElementStyle @ content.js:324
Refresher._setCss @ refresher.js:398
close @ refresher.js:381
ZoneDelegate.invokeTask @ zone.js:356
onInvokeTask @ ng_zone_impl.js:37
ZoneDelegate.invokeTask @ zone.js:355
Zone.runTask @ zone.js:256
ZoneTask.invoke @ zone.js:423

#### Which Ionic Version?
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
OS: Windows 7 SP1
Node Version: v6.2.2

**Comment by jgw96** [comment] 2016-07-26 14:11
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by ahunigel** [comment] 2016-07-27 01:24
I tried to create a [plunker](http://plnkr.co/edit/EaPiLcD5o1Bguvra32YF?p=preview), but I am not familiar with that, so it may not work. 
I can't see the `ion-menu` on the preview, and if I add constructor to TabsPage, the preview do not show up.

**Comment by jgw96** [comment] 2016-07-27 15:38
That is no problem. If you have a repo that i can use to reproduce this issue that will work too. Thanks!

**Comment by ahunigel** [comment] 2016-07-28 06:27
Please find the commit at 
ahunigel/Ionic2-tabs-and-menu@902e33012893f09ee12f147456d02022aa6a63db

**Comment by jgw96** [comment] 2016-08-09 19:09
Hello, thanks for opening an issue with us! So after thorough testing of this issue i can still not seem to reproduce it. Since i cannot reproduce the issue with the latest version of Ionic 2 in any of our tests or in my test apps, including your code, I am going to close this issue for now. Thanks for using Ionic!

**Closed by jgw96** 2016-08-09 19:09 UTC
Labels: v2
