### ISSUE TITLE
Tab navigation stack is cleared when tapping on tab without tab changing

### ISSUE THREAD

**Issue by anatoly-spb** [driftyco/ionic#9559] opened 2016-12-08 21:37 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I have main page with tabs. Each tab have several sub tabs (Tab -> SubTab -> SubSubTab). If I press the tab on SubSubTab, application clear current tab navigation stack and go to the root (the Tab page in my example).

**Expected behavior:**
I expect that pressing on tab page on [Sub]SubTab will not clear the current tab navigation stack.

**Steps to reproduce:**

http://plnkr.co/edit/pcAeUvQJDSDZ0M7wYcC5?p=preview

1. Press button "PUSH NEW PAGE" several times
2. Press tab with the heart icon

As you can see all pushed pages are cleared and application goes to the root

**Related code:**

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed
```

**Comment by manucorporat** [comment] 2016-12-08 23:06
That's the expected behavior of a native app.

**Comment by jgw96** [comment] 2016-12-09 15:17
Hello @anatoly-spb, thanks for opening an issue with us! So this is actually expected behavior. If you try a native app on your device you will notice that it implements the same behavior. Because this is expected behavior I am going to close this issue for now. Thanks again!

**Closed by jgw96** 2016-12-09 15:17 UTC
