### ISSUE TITLE
Ionic ion-content not adjusting properly when keyboard shows

### ISSUE THREAD

**Issue by induri** [driftyco/ionic#4889] opened 2016-01-02 10:55 UTC
Hi,

I've a simple view with textangular as an element. On Android(I tested), if the keyboard is opened, the view is not scrolling up to prevent the editor from getting behind the keyboard.
I installed the Keyboard plugin com.ionic.keyboard.

This is the structure of the page:
```html
<ion-view id="newblogview">
    <ion-nav-buttons side="left">
    ...
    </ion-nav-buttons>    
  <ion-content scroll="true" overflow-scroll="true" class="has-header" delegate-handle="mainScroll">  
     <iframe data-tap-disabled="true" style="width: 100%; min-height: 100%"  src="./templates/blog/html/blog-editor.html" name="blogeditor" id="blogeditor"></iframe>                
  </ion-content>
</ion-view>
```

it's not moving up when the keyboard is opened by focusing on the input.
I've tried android:windowSoftInputMode="adjustPan" and also "adjustResize"
And also I've tried native.keyboardshow event to call $ionicScrollDelegate.scrollBottom(true);

I think we've Keyboard attach directive for footer, but I can't place text editor in the footer.
Does ionic framework support adjusting ion content to keyboard show/hide? is this feature is not supported yet in framework or am I missing something.

Please help.
-Prakash.

**Comment by mlynch** [comment] 2016-01-02 13:52
Did you try 1.2.2 released two days ago? Should fix this

**Comment by mlynch** [comment] 2016-01-02 14:36
Closing because I'm guessing this is on an older version and is a duplicate of #4888. Please correct me if I'm wrong.

**Closed by mlynch** 2016-01-02 14:36 UTC

**Comment by induri** [comment] 2016-01-20 11:15
Hi Max,

I tried with latest ionic 1.2.2, I'm confused with keyboard thing.
What should I do to get ionic content/view shrink/adjust when keyboard is up.
My input editor is in ion content area not in footer.
Please guide me.
