### ISSUE TITLE
number format error on ios

### ISSUE THREAD

**Issue by wanna950312** [driftyco/ionic#7833] opened 2016-08-23 07:00 UTC
when I use the following code in template for format a number, 
on browers(chrome/safari) and android work fine, 
but error on IOS:
{{viewModel?.TeamInfo?.InvoiceInfo?.InvoiceFinishRate|percent:"1.0-2"}}

the error information in xcode:
"JSON.stringify()ing argument: TypeError: JSON.stringify cannot serialize cyclic structures."

it looks like when I run  "ionic platform add ios", the number format dependence library could not  generate.

ionic bata 9

**Comment by jgw96** [comment] 2016-08-23 14:11
Hello, thanks for opening an issue with us! Would you mind posting a repo i can use to reproduce this issue? Thanks!

**Comment by jgw96** [comment] 2016-08-29 13:35
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-08-29 13:35 UTC
Labels: needs reply, v2
