### ISSUE TITLE
bug: radio group checks all radios

### ISSUE THREAD

**Issue by mrameezraja** [driftyco/ionic#5158] opened 2016-01-23 14:57 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>While using radio group, when you click on any one item, it checks all items.

http://ionicframework.com/docs/v2/api/components/radio/RadioGroup/

Just click any item in demo you will see the results. I have also face this in my app.

i am using ionic2 latest build.</span>

<span is-issue-template></span>

**Comment by manucorporat** [comment] 2016-01-23 18:36
probably a duplicate of this: https://github.com/driftyco/ionic/issues/5033 ?

**Comment by brandyscarney** [comment] 2016-01-23 18:39
Yes, this is a duplicate of #5033

**Closed by brandyscarney** 2016-01-23 18:39 UTC
Labels: v2
