### ISSUE TITLE
Controller in ion-nav-back-button is initialized twice

### ISSUE THREAD

**Issue by hungdoan2** [driftyco/ionic#5499] opened 2016-02-18 08:30 UTC
Here is the sample code: 
http://codepen.io/anon/pen/eJooNg

````
 <ion-nav-bar class="bar-positive">
      <ion-nav-back-button>
        <button ng-controller="TestCtrl as testCtrl">TEST BUTTON</button>
      </ion-nav-back-button>
    </ion-nav-bar>
````

In this sample. TestCtrl  will be executed twice.

Is this a bug ?

**Comment by segersrobbert** [comment] 2016-04-05 08:32
I have the same issue, when I put a component in the ion-nav-bar, its constructor is initialized twice.

**Comment by jgw96** [comment] 2016-04-05 14:59
Thanks for opening an issue with us! As this bug is a duplicate of this issue: #3852 I will be closing this one, but please feel free to chime in on the other issue. Also as you can see from that issue, we have added it to the 1.3 milestone, so expect to see a fix for this issue in that release!

**Closed by jgw96** 2016-04-05 14:59 UTC
Labels: needs:devicetesting, v1
