### ISSUE TITLE
Swipe to go back issues

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#7930] opened 2016-08-31 20:49 UTC
#### Short description of the problem:
When swiping to go back, you're still to scroll the previous view.

https://youtu.be/jS-G19C6GZw

**Comment by jgw96** [comment] 2016-09-01 20:19
Closing this as a duplicate of https://github.com/driftyco/ionic/issues/7444.

**Closed by jgw96** 2016-09-01 20:19 UTC
Labels: navigation, v2
