### ISSUE TITLE
Slides doesn't work as expected on iOS

### ISSUE THREAD

**Issue by paweljurczynski** [driftyco/ionic#11404] opened 2017-04-27 11:21 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[ x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When I deploy my current state of application to iOS device the slider doesn't work as I expected. Slider is on the first page after application run. It seems to be free mode all the time without transition at all. On Android devices and browser everything works fine. This issue appears only on ios devices.

**Expected behavior:**
The slides should work as on android devices.

**Steps to reproduce:**
Copy from docs the slider and deploy to IOS Device. 
Try to swipe slider.

**Related code:**

```
<ion-slides>
    <ion-slide>
        <h1 style="color: red">Slide 1</h1>
    </ion-slide>
    <ion-slide>
        <h1 style="color: red">Slide 2</h1>
    </ion-slide>
    <ion-slide>
        <h1 style="color: red">Slide 3</h1>
    </ion-slide>
</ion-slides>
```

**Other information:**
Please look at this issue as soon as possible. I will be very appreciated.

**Comment by jgw96** [comment] 2017-04-27 14:36
Hello, thanks or using Ionic! Could you create a video that shows this issue? I am not able to reproduce this.

**Comment by paweljurczynski** [comment] 2017-04-28 06:16
Hey, thank you for a quick reply,

This is a video with issue: 
https://drive.google.com/file/d/0ByBY5oTSL9fITXNCUUpwOU1hMmc/view?usp=sharing

I think it can be something wrong with loading this slider, cause when I logout an app everything works as expected.

**Comment by wbhob** [comment] 2017-05-01 02:40
Maybe share some code? This may be something wrong with how your app handles async grabbing data. Look at console logs and stuff

**Comment by jgw96** [comment] 2017-05-01 17:26
Hmm thats interesting. This sounds like it could be some kind of race condition. Could you share a minimal repo that we could use to reproduce this issue?

**Comment by paweljurczynski** [comment] 2017-05-04 06:05
Just try create new project and add a slider to first page. Then you will see this issue, I hope.

**Comment by paweljurczynski** [comment] 2017-05-04 06:33
I tried start new app and add slider and this issue doesn't appear :/

**Comment by paweljurczynski** [comment] 2017-05-04 11:46
I solved this problem. I've added a hook and update it after enter:
```
    ionViewDidEnter() {
        this.slides.update();
    }
```

**Comment by jgw96** [comment] 2017-05-05 14:33
Awesome, as it seems you have fixed your issue, for now, I am going to close this issue. Thanks!

**Closed by jgw96** 2017-05-05 14:33 UTC
Labels: needs info, v2
