### ISSUE TITLE
iOS buttons stop working.

### ISSUE THREAD

**Issue by pjcjonas** [driftyco/ionic#9855] opened 2017-01-03 15:45 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X ] **2.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I have a settings page that has its buttons generated from a array of buttons:
```
<button ion-item full *ngFor="let p of settingsPages" (click)="onNavClicked(p.component)">
    <ion-icon name="{{p.icon}}" padding-right></ion-icon> {{p.title}}
</button>
```
At some point on ipad or iphone, these buttons including the buttons in the header like the nav button stop working. Tapping on any of them does nothing

**Expected behavior:**
The buttons should work by push a view so that I can change said settings

**Steps to reproduce:**
No steps
-->

**Related code:**
*Buttons*
```
<button ion-item full *ngFor="let p of settingsPages" (click)="onNavClicked(p.component)">
    <ion-icon name="{{p.icon}}" padding-right></ion-icon> {{p.title}}
</button>
```

**Other information:**
Android works fine...

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.9.2
Xcode version: Not installed
```

**Comment by jgw96** [comment] 2017-01-03 16:08
Hello, thanks for using Ionic! Unfortunately I cannot reproduce this issue on my iphone 5, do you have a demo app that i can try that shows an example of this issue? Also, do you have any specific repro steps you can share?

**Comment by wbhob** [comment] 2017-01-03 16:25
It looks like you have an ion-list, so try using `<a ion-item ...>` instead of button. You also used the `full` attribute, which is for buttons, and won't affect the actual item. Finally, since you have an icon, add `item-left` to your icon.

**Comment by jgw96** [comment] 2017-01-09 16:00
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-01-09 16:00 UTC
Labels: needs info, v2
