### ISSUE TITLE
ionic inside Iframe issue, keyboard not typing in IOS only 

### ISSUE THREAD

**Issue by ahmadfh** [driftyco/ionic#9794] opened 2016-12-26 10:02 UTC
**Ionic version:**  (check one with "x")
[x] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior**:
Hi, i am having a problem when i test the app on **IOS**, i am using an **Iframe** to load ionic template, and when i do so the text input stop working (when i tap on keyboard buttons nothing happens; the text input remains empty). And when i scroll the page the caret input start scrolling with the page and end up on some dummy position (not in the selected input). I tried the ionic template without the Iframe and everything works fine so it only happens when using **iframe**.
**P.S: This problem only on IOS.**

**Steps to reproduce:**
Use Iframe to load any ionic template and run in IOS.

**Comment by jgw96** [comment] 2017-01-10 22:15
Hey @ahmadfh , unfortunately we do not really support loading an entire Ionic app inside an Iframe. Iframes are very hard to style, do not interact with the main page by design and finally usually get rejected from the Google play store and the app store. Because of this I am going to close this issue for now. Thanks for using Ionic!

**Closed by jgw96** 2017-01-10 22:15 UTC
Labels: v2
