### ISSUE TITLE
ion-select style in rtl wrong

### ISSUE THREAD

**Issue by mohamedsharaf** [driftyco/ionic#9815] opened 2016-12-28 16:27 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

ion-select if the platform direction set to rtl it appear in wrong style
platform.setDir('rtl', true);
or if changed it in the html tag
<html lang="en" dir="rtl">
look at the screen shoot

**Expected behavior:**

style appear right way as most ionic components

**Steps to reproduce:**

**Related code:**

```
<html lang="en" dir="rtl">


</ion-label>
        <ion-select>
          <ion-option value="ar">Arabic</ion-option>
          <ion-option value="en">English</ion-option>
          <ion-option value="tr">Turkey</ion-option>
        </ion-select>
      </ion-item>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.47
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.2
Xcode version: Not installed
```

**Comment by mohamedsharaf** [comment] 2016-12-28 16:29
![ionic select rtl](https://cloud.githubusercontent.com/assets/895464/21526272/f5955734-cd33-11e6-90e9-d6a0f4296835.png)

**Comment by mohamedsharaf** [comment] 2016-12-30 04:48
@jgw96 i worked in a fix its in main.css for ionic
the main problem is the use of 
text-align in styling 
i am not sure where the file located or the scss to submit fix

**Comment by mohamedsharaf** [comment] 2017-01-02 08:03
<style>
        html[dir="rtl"] .alert-tappable {
            text-align: right;
        }

        html[dir="rtl"] .alert-md .alert-radio-icon {
            left: 0px;
            right: 13px;
        }
    </style>

**Comment by jgw96** [comment] 2017-04-07 14:06
Hello, thanks for using Ionic! We really appreciate this feedback on RTL support. This is not currently high priority for us at the moment, but we are tracking it in #5035. Because of this I am going to close this issue as a duplicate of that issue and ask that you put your feedback on that issue. Please know that by me closing this issue I am not saying that your feedback is not important, or that RTL support is not important, but I am simply closing this issue as we like to keep our issues as organized as possible so things do not get lost in the weeds (which is better said than done haha).

**Closed by jgw96** 2017-04-07 14:06 UTC
Labels: css, v2
