### ISSUE TITLE
RC4 iOS fullscreen webapp + list with virtualScroll = scrolling problems

### ISSUE THREAD

**Issue by pavimus** [driftyco/ionic#9665] opened 2016-12-16 08:43 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When you add webapp link to iOS homescreen and start it, scrolling on webview with virtualScroll is unusable (with non-virtualscroll list all is ok). When you swipe finger down, first you see bouncing gray rect, then view is scrolling. I seen this bug only on iOS and only in webapp mode. (On iOS in safari it works OK, on adroid works OK even in webapp mode).

**Expected behavior:**
Seamless scroll as in RC3

**Steps to reproduce:**

**Related code:**
There is my iOS webapp related metatags:
```
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="default">
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.3.1 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v4.2.6
Xcode version: Not installed
```

**Comment by MattDHill** [comment] 2016-12-17 23:27
I'm having a similar issue with virtual scroll on iOS (UIWebView) after updating to RC4. Attempting to scroll fails, causing the entire ion-content to pull down or up. See pics.
![photo_2016-12-17_16-26-16](https://cloud.githubusercontent.com/assets/9935159/21290383/98125e84-c475-11e6-8049-0d9a03beaf8b.jpg)
![photo_2016-12-17_16-26-21](https://cloud.githubusercontent.com/assets/9935159/21290384/981b1d12-c475-11e6-9fa9-be9dffff7066.jpg)

**Comment by MattDHill** [comment] 2016-12-28 23:50
I was able to resolve this by setting ```<preference name="DisallowOverscroll" value="true"/>``` in config.xml

**Comment by pavimus** [comment] 2016-12-31 09:04
I think your solution will not help me. Because i use it as webapp (application is compiled and html/css/js file uploaded to webserver and shortcut is placed on phone homescreen)

**Comment by jgw96** [comment] 2017-01-25 15:16
Hello all! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/9765 since it is caused by the same underlying issue with scroll events. Thanks!

**Closed by jgw96** 2017-01-25 15:16 UTC
Labels: v2
