### ISSUE TITLE
ion-tabs navigation behaves unexpectedly when using Android back button

### ISSUE THREAD

**Issue by rjv** [driftyco/ionic#7931] opened 2016-08-31 21:07 UTC
#### Short description of the problem:

Navigating between tabs with the `ion-tabs` component adds to the overall navigation history. Pressing the Android system back button navigates (in reverse) the entire history of how the user traversed through the tabs.

#### What behavior are you expecting?

If viewing the root page of a tab, I would expect the app to exit when pressing the Android back button.

**Steps to reproduce:**
1. Assume an Android app; root page has `<ion-tabs>` that contains 4 tabs and starts with _tab1_ (or you could use the _tabs_ starter project).
2. Tap on _tab2_, then on _tab3_, and finally on _tab4_.
3. Press the Android system back button; observe that you are taken to _tab3_.
4. Press the back button again; observe that you are taken to _tab2_.

**Other information:** 

Original forum post:  https://forum.ionicframework.com/t/switching-between-ion-tabs-on-android-keeps-a-nav-history-when-pressing-the-platforms-back-button/62222/1

**Which Ionic Version?** 

2.0.0-beta.11

**Run `ionic info` from terminal/cmd prompt:**

```
Cordova CLI: 6.3.0
Gulp version:  CLI version 1.2.2
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.36
Ionic App Lib Version: 2.0.0-beta.19
OS:
Node Version: v6.3.1
```

**Comment by jgw96** [comment] 2016-09-01 14:43
Hello, thanks for opening an issue with us! I am going to be closing this issue as a duplicate of https://github.com/driftyco/ionic/issues/7611. Thanks for using Ionic!

**Closed by jgw96** 2016-09-01 14:43 UTC
Labels: navigation, platform:android
