### ISSUE TITLE
bug: PopUp  ng-model refresh

### ISSUE THREAD

**Issue by videmort** [driftyco/ionic#5182] opened 2016-01-25 11:40 UTC
When you open one popUp with one input or textarea binding to one ng-model, if you have got one event listener who changes that ng-model, it never change but if you close and open the popUp, the view has been reloaded and it show the updated value.

Real example:

You open one popUp and receive one SMS with some data, in your event listener you bind that data with the ng-model in the input. As result you don't see the change but... if closes and open the view you see the data in your input.

**Comment by jgw96** [comment] 2016-03-14 16:12
Hello! Thanks for opening an issue with us, we just need a little more info from you so that we can better help you with your issue. Would you mind posting a code sample, plunkr or codepen that we can use to reproduce your issue? Also, would you mind running `ionic info` and posting the output? Thanks again!

**Comment by jgw96** [comment] 2016-03-21 16:59
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!

**Closed by jgw96** 2016-03-21 16:59 UTC
Labels: popover, v1
