### ISSUE TITLE
bug: Tap on list item returning earlier list item when

### ISSUE THREAD

**Issue by persyval** [driftyco/ionic#5726] opened 2016-03-05 06:27 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>When tapping on a list item on an iOS device while scrolling it returns an earlier list item and not the one you are currently tapping.

This happens only if you set the ionicconfigprovider as follow:
    $ionicConfigProvider.scrolling.jsScrolling(false);
If you don't set any option for the jsScrolling property (so don't include this line in your config section), it works as expected.

But according to the documentation of ionicconfigprovider this should be the default value.
http://ionicframework.com/docs/api/provider/$ionicConfigProvider/
So setting the value to the default value has an other outcome then not providing the value at all.</span>

<span is-issue-template></span>

**Comment by persyval** [comment] 2016-03-05 06:27
As some added informationi am using ionic 1.2.4, the latest build as of now.

**Comment by leschirmeur** [comment] 2016-03-24 09:00
Experiencing the same issue, on both iOS 8 and 9. we see this as a high priority issue as users are really getting confused if the app doesn't behave as intended.

**Comment by leschirmeur** [comment] 2016-04-07 12:52
May I kindly ask if there is anyone looking into this? We have more and more users complaining as this is leading to unwanted results when using our app.

**Comment by persyval** [comment] 2016-04-07 12:59
It seems to be hard to get any response from the team.
I tried the forums, slack, gitter and an official bug report.
At this moment am not even looking for a fix but merely just someone looking at the bug.

One workaround you could try is giving the parent container of the scroll container a style of position=relative and set data-tap-disabled = "true" on the same parent container.
Like this:
<div class="parent-scroll-container" style="position: relative" data-tap-disabled="true">
It seems to have a positive effect on our app, but your mileage may vary.

**Comment by danbucholtz** [comment] 2016-04-12 15:43
Hi @leschirmeur, @persyval,

I am starting to look into this issue.

Thanks,
Dan

**Comment by persyval** [comment] 2016-04-13 11:42
Hi Dan,

Thank you.
If you need any clarification please let me know.

Peter

**Comment by leschirmeur** [comment] 2016-04-13 15:38
Thanks @danbucholtz

**Comment by danbucholtz** [comment] 2016-04-13 16:22
Hi @persyval and @leschirmeur - in the spirit of full disclosure, this isn't looking good.  The scroll events in UIWebView on iOS are not functioning as one would expect.  The answer is to use WKWebView, but there are challenges associated with that as well.  Do you two have any ideas or thoughts of how we could get around this?  I am not seeing anything immediately obvious unfortunately.  I am going to close this issue - but will re-open if you wish.

The best bet is going to be to use JS Scrolling for now.  You can do that by setting `overflow-scroll="false"` on the particular ion-content.

Thanks,
Dan

**Closed by danbucholtz** 2016-04-13 16:22 UTC
Labels: platform:ios, scroll, tap/click, v1

**Comment by persyval** [comment] 2016-04-19 11:44
Hi Dan,
Thank you for your response.
Unfortunately setting overflow-scroll="false" on the view has other unwanted side effects.
In my case specically [this](https://github.com/driftyco/ionic/issues/5341#issuecomment-196204709) bug.
And somehow I can't get wkwebview to work on iOS as well.

But the workaround I mentioned earlier about setting the 'position:relative' on the parent element fixes this enough for us to not let it be a problem.

**Comment by danbucholtz** [comment] 2016-04-19 15:33
Hi @persyval That other bug you linked to is on my todos for 1.3.1.  Hopefully we can get it squared away shortly.

Thanks,
Dan

**Comment by quiply** [comment] 2016-04-19 19:31
@persyval I only realized now that you posted a workaround which works for you with position relative and data-tap-disabled. Will try that out. In a modal where ion-content has a parent of ion-modal-view, would you set ion-modal-view to relative and data-tap-disabled = "true" as well?

@danbucholtz You mentioned 1.3.1 - I am not sure, are you referring to Ionic 1.3.1? If yes, is there a roadmap for upcoming Ionic release versions available?

**Comment by leschirmeur** [comment] 2016-04-19 19:32
Uh, it seems my last post went out from our company's account...

**Comment by danbucholtz** [comment] 2016-04-19 19:48
We are planning to release Ionic 1.3 this Thursday.  As far as what's next after that, I am not entirely sure.  1.3 is basically Angular 1.5 + a few bugs fixes and PRs.  1.3.1 will likely be mostly bug fixes and PRs in my opinion at this time.

**Comment by leschirmeur** [comment] 2016-04-19 20:44
Sounds great, thx very much for your reply! And good luck for the release :-)

**Comment by danbucholtz** [comment] 2016-04-20 03:11
@leschirmeur, @persyval, what sort of use cases does your app have?  If you aren't using file urls, or even if you are, you could give WKWebView a shot.  Telerik makes a solid cordova plugin that might help.

https://github.com/Telerik-Verified-Plugins/WKWebView

There is also an Apache one but it is newer and not as well received yet.  It is probably the better bet long term, though.
https://github.com/apache/cordova-plugin-wkwebview-engine

**Comment by michaelnatkin** [comment] 2016-05-06 20:38
@danbucholtz we had a try at using WKWebView; i don't remember all the problems but it didn't go well. This bug is really plaguing us, we'd desperately love a solution that works with UIWebView. Do we have any hope?

**Comment by danbucholtz** [comment] 2016-05-06 20:52
Hi @michaelnatkin,

What didn't work out with WKWebView?  That + Ionic 2 is definitely the future of Ionic.

As for a fix with this, it really just comes down to what my bosses consider to be the priority or if someone wants to take a crack at a well-tested PR.

**Comment by michaelnatkin** [comment] 2016-05-07 00:58
@danbucholtz if I remember right the big deal breaker for us was getting file:// urls to work. Seemed like it was going to take adding a local server to the app, ugh. ``` However, you are still not able to use XHR from the file:// protocol without CORS enabled on your server.```

**Comment by danbucholtz** [comment] 2016-05-07 03:30
There are some plugins that help with that, but I agree it is not ideal.  We are going to keep pounding the pavement on WKWebView because it is very important to Ionic going forward.  We'll keep you posted!
