### ISSUE TITLE
bug: Erratic content scroll when textarea has focus

### ISSUE THREAD

**Issue by bassettsj** [driftyco/ionic#2901] opened 2015-01-08 17:28 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>browser</span>

<span ionic-description>
### Steps to reproduce:

- focus on textarea element
- while focused touch and drag outside of the element and watch the weird scrolling

[Example codepen sandbox](http://codepen.io/bassettsj/debug/EaZmmz)</span>
[Screencast of the behaviour](http://youtu.be/8LuKpgFICME?hd=1)
<span is-issue-template></span>

**Comment by callmephilip** [comment] 2015-02-17 13:37
I am seeing the same issue with both textarea and input[type="text"]
Platform: Cordova on iOS 8

**Comment by clickonchris** [comment] 2015-03-24 13:27
+1  We are also seeing this for both text areas and input[type="text"] elements on IOS 8.

**Comment by Fayozjon** [comment] 2015-03-24 16:55
Christopher

http://lilwall.ca/robot_strategii

24.03.2015, 16:28, "Christopher G Johnson" <notifications@github.com>:+1  We are also seeing this for both text areas and input[type="text"] elements on IOS 8.

**Comment by tprinty** [comment] 2015-04-13 15:35
I too am seeing this issue.  If there are two textareas on the screen the app scrolls to the second one.

**Comment by tlancina** [comment] 2015-04-20 19:54
Hey I'm unable to reproduce using the provided codepen, can anyone test out the latest nightly and tell me if this is still happening?

**Comment by bassettsj** [comment] 2015-05-01 20:24
@tlancina  Sorry for the delayed response... updating to the nightly in code pen and will see if it is reproducible, if not will close straight away.

**Comment by bassettsj** [comment] 2015-05-01 20:32
@tlancina I am able to reproduce the bug. I have uploaded a [screencast reproducing the issue to youtube](https://youtu.be/21ndwPvdeKM). (I wish I could show where my finger was on the screen in this. 

It happens when the `textarea` is focused, I attempt to scroll the screen, then I get strange scrolling behavior.

**Comment by bassettsj** [comment] 2015-05-01 22:19
There is obviously a lot going on with the scroll view with things like:

[scrollView.js:802](https://github.com/driftyco/ionic/blob/master/js/views/scrollView.js#L802)

```js
  self.touchMove = function(e) {
     if (self.options.freeze || !self.__isDown ||
        (!self.__isDown && e.defaultPrevented) ||
        (e.target.tagName === 'TEXTAREA' && e.target.parentElement.querySelector(':focus')) ) {
        return;
      }

      if ( !self.__hasStarted && ( ionic.tap.containsOrIsTextInput(e.target) || e.target.tagName === 'SELECT' ) ) {
        // the target is a text input and scroll has started
        // since the text input doesn't start on touchStart, do it here
        self.__hasStarted = true;
        self.doTouchStart(getEventTouches(e), e.timeStamp);
        e.preventDefault();
        return;
      }
 ....
 }
```

I would like to try to help create a test for this issue, but not sure where the best place would be. Looking at the `scrollView.unit.js`, it seems like the place to start, but this is a relatively difficult condition to test. Any recommendations on where you think it would be good to start?

**Comment by oriodesign** [comment] 2015-06-04 14:21
@bassettsj did you find a solution? I have the same problem with textarea on ionic v1.0.0. When a textarea has focus on touch move (only on the textarea) the whole webview scrolls (tested on iPhone5 iOS 8.3).

**Comment by bassettsj** [comment] 2015-06-04 19:32
Within our applicantion we have a workaround, but not really a great one. It would be best to look into the source scrollview code...

**Comment by jgw96** [comment] 2016-04-27 18:33
Hello all! Is this still an issue with the latest version of ionic: 1.3.0 ?

**Comment by jgw96** [comment] 2016-05-03 15:13
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-05-03 15:13 UTC
Labels: needs reply, v1
