### ISSUE TITLE
the header in iPhone not take the correct height

### ISSUE THREAD

**Issue by javico2609** [driftyco/ionic#10741] opened 2017-03-11 20:39 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

i tested this behavior on a real iphone, am i  see the same problem like see on my local ionic lab

![image](https://cloud.githubusercontent.com/assets/12940555/23826704/d57c3cde-0680-11e7-8c1f-adeccc48f6af.png)

![image](https://cloud.githubusercontent.com/assets/12940555/23826710/ea9b16ee-0680-11e7-9851-5f1a2fbf0dbb.png)

**Expected behavior:**

the header take the correct height

**Steps to reproduce:**

**Related code:**

```
@Component({
    selector: 'icbanking-header-navbar, [icbanking-header-navbar]',
    template: `
        <ion-navbar>
            <button ion-button menuToggle>
                <ion-icon name="menu"></ion-icon>
            </button>
            <div class="logo"></div>
            <ion-title class="ion-title-with-logo">{{_menuTitle}}</ion-title>
        </ion-navbar>   
    `
})
export class ICBankingHeaderNavbarComponent implements OnInit {

@Input()
    get title(): string {
        return this._menuTitle;
    }
    set title(val: string) {
        this._menuTitle = val;
  }

  // some logic here
}

////// Home Component

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  constructor(public navCtrl: NavController, public navParams: NavParams) { }

  ionViewDidLoad() {
    console.log('ionViewDidLoad HomePage');
  }
}

/// Home html
<ion-header>
  <icbanking-header-navbar title="{{ 'HomePage' | translate }}"></icbanking-header-navbar>
</ion-header>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here

ordova CLI: 6.5.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.4.0
Xcode version: Not installed
```

**Comment by jgw96** [comment] 2017-03-13 11:37
Hello, thanks for opening an issue with us. We will look into this.

**Comment by jgw96** [comment] 2017-05-18 18:42
Hello, because I cannot reproduce this issue anymore in the latest release of Ionic I am going to close this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-05-18 18:42 UTC
Labels: css, platform:ios, v2

**Comment by javico2609** [comment] 2017-05-18 19:47
Hi, this bug still exists in the last version of ionic, I shared a repo so they could try
