### ISSUE TITLE
Transition Error: Cannot read property 'getTransitionName' of null

### ISSUE THREAD

**Issue by dheran** [driftyco/ionic#8881] opened 2016-10-24 17:09 UTC
Ionic 2, IOS issue. Reproducible in desktop browser too.

Steps:
First I need to navigate more than 2 levels, then come back by pressing back instantly (regular speed) and you will get empty black screen in desktop browser or white screen in ios app.

Error stack:
nav-controller-base.js:289 Uncaught TypeError: Cannot read property 'getTransitionName' of null
    at NavControllerBase._postViewInit (nav-controller-base.js:289)
    at NavControllerBase._viewTest (nav-controller-base.js:348)
    at NavControllerBase._nextTrns (nav-controller-base.js:192)
    at ti.resolve (nav-controller-base.js:142)
    at NavControllerBase._trnsFinish (nav-controller-base.js:462)
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (ng_zone.js:236)
    at t.invoke (polyfills.js:3)
    at e.run (polyfills.js:3)
    at NgZone.run (ng_zone.js:126)

**Comment by manucorporat** [comment] 2016-10-24 20:02
@dheran can you test if the problem persist in nightly?
```
npm install ionic@nightly --save
```

**Comment by curtisblanchette** [comment] 2016-10-25 19:28
@manucorporat I've never seen this stack trace when the black screen occurs in reference to .  I'm able to reproduce this in the browser and on iOS [#8885](https://github.com/driftyco/ionic/issues/8885)

Testing ionic-angular@nightly now

**Comment by boye** [comment] 2016-10-25 20:24
I ran into this issue as well. However, as @curtisblanchette points out, after upgrading to `ionic-angular@nightly`, the problem doesn't occur anymore.

I will keep monitoring it...

**Comment by manucorporat** [comment] 2016-10-26 08:38
I will close this issue for the moment. please feel free to reopen it.

**Comment by YevhenStienin** [comment] 2016-10-26 11:27
I installed ionic-angular@nightly module. But to me it does not work, the problem persists. What could I do wrong?

**Comment by boye** [comment] 2016-10-26 19:47
Alas, the problem persists indeed. I applied a different work-around for now.

**Comment by apparition47** [comment] 2016-10-26 20:27
I was getting a similar issue too with the same stack trace on `rc.1`. Seems to be fixed with `nightly` so far.

**Comment by TongeJie** [comment] 2016-10-30 03:22
Hi Ionites,Did this fix the problem?
 I installed ionic-angular@nightly module ,the problem persists in my project .
I want this problem to be definitely fixed!!!

**Comment by apparition47** [comment] 2016-10-30 03:26
Odd because it works for me using `ionic-angular@2.0.0-rc.1-201610241941` but not the normal rc.1 release when I nav in and out of my views. Not sure why.

**Comment by manucorporat** [comment] 2016-10-30 15:15
@TongeJie thanks for the repo! I will check it out this week! Reopening!!

**Comment by manucorporat** [comment] 2016-10-30 15:34
@TongeJie I was able to reproduce the problem with your repo, then noticed it does not use nightly:
```
    "ionic-angular": "2.0.0-rc.1",
```

**Comment by jgw96** [comment] 2016-11-01 15:37
After some testing with the conference app running the latest nightly I also cannot reproduce this issue anymore. Because of this I am going to close this issue for now. Thanks everyone!

**Closed by jgw96** 2016-11-01 15:37 UTC

**Comment by webprofusion-chrisc** [comment] 2016-12-10 08:19
Hi, I'm currently getting this error (rc3), I suspects it's some sort of race condition where using Loading.

Runtime Error
Cannot read property 'getTransitionName' of null
Stack
TypeError: Cannot read property 'getTransitionName' of null
    at OverlayPortal.NavControllerBase._postViewInit (http://localhost:8100/build/main.js:25387:67)
    at OverlayPortal.NavControllerBase._viewTest (http://localhost:8100/build/main.js:25460:18)
    at OverlayPortal.NavControllerBase._nextTrns (http://localhost:8100/build/main.js:25283:25)
    at ti.resolve (http://localhost:8100/build/main.js:25230:19)
    at OverlayPortal.NavControllerBase._trnsFinish (http://localhost:8100/build/main.js:25574:9)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:13422)
    at Object.onInvoke (http://localhost:8100/build/main.js:32618:37)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:13373)
    at e.run (http://localhost:8100/build/polyfills.js:3:10809)
    at NgZone.run (http://localhost:8100/build/main.js:32508:62)
Ionic Framework: 2.0.0-rc.3
Ionic Native: 2.2.6
Ionic App Scripts: 0.0.46
Angular Core: 2.1.1
Angular Compiler CLI: 2.1.1
Node: 6.9.1
OS Platform: Windows 10
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36
