### ISSUE TITLE
Side menu ionic 2- unable to close with a swipe. Android Samsung 4.4.2

### ISSUE THREAD

**Issue by mainakanyi** [driftyco/ionic#10091] opened 2017-01-18 12:30 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by mpaland** [comment] 2017-01-18 12:56
Please try this with the actual ionic-conference-app using latest RC5 on your Samsung phone.
I've tested your issue on a Moto G2 and I can close the menu with a swipe. No problem.

**Comment by mainakanyi** [comment] 2017-01-18 13:03
Hi Mpaland. Let me try. Thanks

**Comment by mainakanyi** [comment] 2017-01-18 13:27
Hi mpaland. why am I getting this error?


npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "ionic:build" "--"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! ionic-conference-app@ ionic:build: `ionic-app-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic-conference-app@ ionic:build script 'ionic-app-scripts build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-conference-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-conference-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic-conference-app
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     C:\xampp\htdocs\ionic-conference-app-master\ionic-conference-app-master\npm-debug.log

**Comment by mpaland** [comment] 2017-01-18 16:01
As it says: Try upgrading your npm. Actual npm is 4.1.1

**Comment by mainakanyi** [comment] 2017-01-19 09:57
still not working. Have just done ionic start james --sidemenu --v2

**Comment by jgw96** [comment] 2017-01-19 15:54
Hello @mainakanyi would you mind opening an issue [here](https://github.com/driftyco/ionic-cli) about your cli issues. On the original issue, i can unfortunately not reproduce this issue on the Android 4.4.2 simulator. Would you be able to post a repo I could use to reproduce this?

**Comment by mainakanyi** [comment] 2017-01-20 08:10
Hi Justin Willis, I solved the cli issue. Now, the main problem that I have is swiping back the ionic 2 sidemenu in sumsung 4.4.2. Please help. Thanks

**Comment by mpaland** [comment] 2017-01-20 12:08
You have to provide some version information, and what exactly you do...
Have you tried bundling crosswalk to run your app on 4.4?

**Comment by jgw96** [comment] 2017-01-24 15:32
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-01-24 15:32 UTC
Labels: needs reply, v2

**Comment by sharkoman** [comment] 2017-04-27 08:31
I have the same problem swipe side menu in LG device running android 4.4.2 doesn't work
