### ISSUE TITLE
Overlay components not presenting

### ISSUE THREAD

**Issue by samhcorney** [driftyco/ionic#8126] opened 2016-09-19 16:00 UTC
#### Short description of the problem:

Overlay components are not firing from ionic lifecycle events ( ionViewWillEnter, ionViewDidEnter etc ) or a page's constructor.

#### What behavior are you expecting?

An overlay component to present itself when called using the present() function from within an ionic lifecycle event.

**Steps to reproduce:**

1. In the [Ionic Conference App](https://github.com/driftyco/ionic-conference-app) add a loading component to the schedule page's ionViewDidEnter function.
2. Open the app as normal and skip through to the page.

The loading component is only fired when navigating to the schedule page using the tabs at the bottom. When coming from either the side menu or straight from the tutorial the loading component isn't fired.

```
    ionViewDidEnter() {
        let loading = this.loadingController.create({
            content: "Please wait..."
        });
        loading.present();
    }
```

Bug raised as a result of [this](https://forum.ionicframework.com/t/cant-use-loadingcontroller-in-ionviewwillenter-sample-source-in-github-repository/63804) forum post.

Ionic Version: 2.0.0-beta.11

**Comment by kelvindart** [comment] 2016-09-19 16:09
I believe this will be fixed in ionic@2.0.0-beta.12. The Ionic team have been working hard to overhaul navigation in the latest release so I understand.

In the interim, I have had a similar issue and @jgw96 very kindly suggested I use:

    loading.fireOtherLifecycles = false;

Which should get around your issue?

**Comment by samhcorney** [comment] 2016-09-19 16:34
Thanks for the suggestion, unfortunately fireOtherLifecycles isn't fixing the issue. I tried this code...

````
ionViewDidEnter() {
    let loading = this.loadingController.create({
        content: "Please wait..."
    });
    loading.fireOtherLifecycles = false;
    loading.present();
}
````

**Comment by jgw96** [comment] 2016-09-20 18:58
Hello, thanks for opening an issue with us! This has actually already been fixed and will be in the beta.12 release. This was caused by overlay components (like the loading component) not being able to find the correct component to be presented from when fired from inside `ionViewDidEnter`. Thanks for using Ionic!

**Closed by jgw96** 2016-09-20 18:58 UTC
Labels: menus, v2

**Comment by samhcorney** [comment] 2016-09-20 19:03
Awesome! Look forward to beta 12. Thanks.
