### ISSUE TITLE
ionic2 - bug(overlays) - Overlays seem to dismiss themselves

### ISSUE THREAD

**Issue by zakton5** [driftyco/ionic#8088] opened 2016-09-15 15:03 UTC
#### Short description of the problem:
When I present an overlay, whether it be an Alert, Select, DateTime picker, or whatever, sometimes it auto dismisses itself. This can happen very soon after it was presented or something like 10 seconds later. I get no errors in the console.

This is happens on Chrome for sure. And it is also happening on iOS. Not sure about any other platforms.

#### What behavior are you expecting?
I expect overlays to remain visible if I do not dismiss them.

**Steps to reproduce:**
Yeah...this is random, so I don't know what to say here lol I'm sorry but I can't reproduce this consistently.

**Which Ionic Version?** 2.0@beta-11

**Comment by aggarwalankush** [comment] 2016-09-15 15:33
I'm also facing the same problem. Sometimes when I open Alert, Modal... it auto dismiss in like 2-3 seconds without any error. It's random that's why I didn't open an issue. 

Hopefully, beta 12 has many fixes on overlays will fix it.

**Comment by jgw96** [comment] 2016-09-15 16:35
Hello, thanks for opening an issue with us! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/8066 . Thanks for using Ionic!

**Closed by jgw96** 2016-09-15 16:35 UTC
Labels: alert, platform:ios, v2

**Comment by zakton5** [comment] 2016-09-15 16:40
I'm not so sure that is the same issue. I am not using a toast when this happens. But hopefully that will fix it.

**Comment by jgw96** [comment] 2016-09-15 17:05
@zakton5 Although it does involve different components the underlying issue is the same. Sorry for any confusion there. Thanks!
