### ISSUE TITLE
Input seems to have delay (300ms) with or without tappable.

### ISSUE THREAD

**Issue by Julieng50** [driftyco/ionic#10595] opened 2017-02-28 16:53 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
On floating input, the delay seems very long before the animation start on ios (like a clickable element without being a "button" / an "a" or tappable), even with tappable directive. I did not try on Android.

**Expected behavior:**
Working like a clickable DIV element : without tappable : 300ms delay, and with : no delay.

**Steps to reproduce:**
To reproduce, add this :
    
       _<ion-list>
          <ion-item tappable>
            <ion-label floating>Email</ion-label>
            <ion-input type="text" [(ngModel)]="email"></ion-input>
          </ion-item>
          <ion-item>
            <ion-label floating>Password</ion-label>
            <ion-input type="password"></ion-input>
          </ion-item>
          <ion-item style="display: none;"></ion-item>
        </ion-list>_

And try tapping on it throw IonicVIEW.
And you will see that the delay with tappable is as long as without... around 300ms.

Any workaround ?

Thanks.

**Comment by jgw96** [comment] 2017-02-28 17:11
Hello, thanks for opening an issue with us. Are you only seeing this in ionic view or does it happen with the app actually installed on your iphone too?

**Comment by Julieng50** [comment] 2017-02-28 17:44
Hello @jgw96, my app is not installed on my iphone (I am building it). 
In firefox dev tool, when i activate the touch mode, I reproduce the bug (without the touch mode there is no delay).

**Comment by Julieng50** [comment] 2017-03-02 13:10
I still have delay on input tap (also on textarea / select and others...).
"Tappable" attribute seems to work with select element but not input or textarea.

**Comment by jgw96** [comment] 2017-03-06 15:04
Unfortunately I cannot reproduce this issue. What device are you testing this with? Could you post a repo that i can use to reproduce this? Also, could you possibly post a video of the delay happening?

**Comment by Julieng50** [comment] 2017-03-06 16:59
I am using an iPhone 7, but i reproduce it in Firefox Dev Tools (it simulates iPhones' gestures).
This is a gif **with** the touch mode activated for iPhone 6 on Firefox :
![gif1](https://cloud.githubusercontent.com/assets/10415193/23620184/5112fa7a-0296-11e7-98cc-92406deedd2c.gif)
This is a gif **without** the touch mode activated for iPhone 6 on Firefox :
![gif2](https://cloud.githubusercontent.com/assets/10415193/23620186/5136d68e-0296-11e7-9963-472d9d837c0e.gif)

No need to post any code because it only works on iPhone with touch gesture with any input.

**Comment by jgw96** [comment] 2017-03-27 07:20
Hello. Unfortunately we cannot reproduce this on any of our devices or the simulator. Because of this I am going to close this issue for now. Thanks for using Ionic.

**Closed by jgw96** 2017-03-27 07:20 UTC
Labels: needs info, v2
