### ISSUE TITLE
bug: Options buttons don't close with collection-repeat

### ISSUE THREAD

**Issue by anzovin-brian** [driftyco/ionic#4362] opened 2015-09-15 21:32 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When using ion-option-buttons on a list of ion-items that are generated using collection-repeat, the option buttons don't disappear when the ion-item is removed.

For example, when pressing an option button for archiving or deleting an item that removes the item from the list used in the collection-repeat, the next item below it will move up a spot, but the option buttons will remain open on this item.

Compare to the behavior when using ng-repeat. In this case, removing the items causes the option buttons to disappear.</span>

<span is-issue-template></span>

**Comment by KaipiYann** [comment] 2015-10-30 12:55
Any info about this bug ?

**Comment by yesnoj** [comment] 2016-01-16 15:21
i have also this problem...but with ng-repeat...

**Comment by jgw96** [comment] 2016-03-15 16:49
Hello! Thanks for opening an issue with us, we just need a little more info from you so that we can better help you with your issue. Would you mind posting a code sample, plunkr or codepen that we can use to reproduce your issue? Also, would you mind running `ionic info` and posting the output? Thanks again!

**Comment by jgw96** [comment] 2016-03-23 19:23
Hello! Thanks for opening this issue with us! As it has been a little while since there was any activity on this issue I will be closing it for now, please feel free to reply if you are still experiencing this issue though!

**Closed by jgw96** 2016-03-23 19:23 UTC
Labels: collection-repeat, v1
