### ISSUE TITLE
ionic2 RC.0, Interface does not export

### ISSUE THREAD

**Issue by masatada** [driftyco/ionic#8632] opened 2016-10-11 09:53 UTC
1.Make interface .ts file. (./src/app/test.ts)
```typescript
export interface Test {
  id: number;
}
```
2.Import interface on app.component.ts.
```typescript
import { Component, Input } from '@angular/core';

import { Platform } from 'ionic-angular';
import { StatusBar } from 'ionic-native';

import { TabsPage } from '../pages/tabs/tabs';
import { Test } from './test';

@Component({
  template: `<ion-nav [root]="rootPage"></ion-nav>`
})
export class MyApp {
  
  // interface call 
  @Input() test: Test;

  rootPage = TabsPage;

  constructor(platform: Platform) {
    platform.ready().then(() => {
      StatusBar.styleDefault();
    });
  }
}
```
3.run `ionic serve`,  it gives me an error:
```
[18:39:34]  bundle dev failed:  Module /Users/test/Documents/develop/unk/src/app/test.ts does not export Test (imported by /Users/test/Documents/develop/unk/src/app/app.component.ts)

[18:39:34]  Error: Module /Users/test/Documents/develop/unk/src/app/test.ts does not export Test (imported by /Users/test/Documents/develop/unk/src/app/app.component.ts)
    at Module.trace (/Users/test/Documents/develop/unk/node_modules/rollup/dist/rollup.js:7706:29)
    at ModuleScope.findDeclaration (/Users/test/Documents/develop/unk/node_modules/rollup/dist/rollup.js:7329:22)
    at Scope.findDeclaration (/Users/test/Documents/develop/unk/node_modules/rollup/dist/rollup.js:5349:39)
    at Identifier.bind (/Users/test/Documents/develop/unk/node_modules/rollup/dist/rollup.js:6497:29)
    at /Users/test/Documents/develop/unk/node_modules/rollup/dist/rollup.js:5149:50
    at UnaryExpression.eachChild (/Users/test/Documents/develop/unk/node_modules/rollup/dist/rollup.js:5166:5)
    at UnaryExpression.bind (/Users/test/Documents/develop/unk/node_modules/rollup/dist/rollup.js:5149:7)
    at UnaryExpression.bind (/Users/test/Documents/develop/unk/node_modules/rollup/dist/rollup.js:6893:53)
    at /Users/test/Documents/develop/unk/node_modules/rollup/dist/rollup.js:5149:50
    at BinaryExpression.eachChild (/Users/test/Documents/develop/unk/node_modules/rollup/dist/rollup.js:5166:5)
```

The problem same probably:
https://forum.ionicframework.com/t/interface-does-not-export-bundle-dev-failed/66225

**Comment by Manduro** [comment] 2016-10-11 13:13
This is probably the same problem as this one: https://github.com/driftyco/ionic-app-scripts/issues/105

**Comment by jgw96** [comment] 2016-10-11 16:14
Hello all! Thanks for opening an issue with us! I am going to go ahead and close this as a duplicate to the issue @Manduro linked to in the above comment as it does seem to be the same issue, or at least caused by the same root issue.

**Closed by jgw96** 2016-10-11 16:14 UTC
