### ISSUE TITLE
feat: ability to conditionally remove ion-reorder from ion-item

### ISSUE THREAD

**Issue by aperezbaena-csc** [driftyco/ionic#9065] opened 2016-11-07 13:07 UTC
**Type:** feat

**Ionic Version:** 2.x

**Platform:** all

`ion-item` includes `ion-reorder` element in the DOM regardless of `reorder="true"` is set in the list, or even if it's not included in any `ion-list` or `ion-item-group`.

Having an option to prevent this item to be present in the DOM would lead to a cleaner and more performing output.

**Comment by manucorporat** [comment] 2016-11-08 00:21
Have you noticed any performance problem caused by having `ion-reorder` in each item?

`ion-reorder` should be `display: none` when reorder is disabled, so it should not affect the layout or performance.

**Comment by aperezbaena-csc** [comment] 2016-11-08 09:37
As you say the whole `ion-reorder` element is hidden with `display: none` so it has no impact either in the layout or rendering. However all that unused markup must be parsed by the browser and kept in memory.

![image](https://cloud.githubusercontent.com/assets/8512164/20093821/aed33ef4-a59e-11e6-976b-6f5e5479e34c.png)

Couldn't measure up yet, and only a few items so far but it could have an impact with many items. 

Besides for the sake of a cleaner DOM, what's the point yo have elements you know you're not going to use (ever)?

**Comment by manucorporat** [comment] 2016-11-08 12:23
@aperezbaena-csc will be fixed in next release!

**Closed** 2016-11-08 12:22 UTC

**Comment by aperezbaena-csc** [comment] 2016-11-08 12:25
@manucorporat awesome!!
