### ISSUE TITLE
bug: Maps and marker clicks on iOS 9

### ISSUE THREAD

**Issue by MarcBT** [driftyco/ionic#4506] opened 2015-10-12 14:14 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>native hybrid app</span>

<span ionic-description>Hello,

I am directly copying/pasting a post from ionic forum (http://bit.ly/1G94nkr) as it perfectly describes the issue:

> After updating my device to iOS 9, I am having problems with detecting marker click events on maps, which was working perfectly when my device was on iOS 8. The clicks are detected at first, but after some events are performed, clicks no longer fire.

> I have tried both Google Maps and Leaflet. While I have not yet found a fully deterministic path to reproducing precisely at what point do the marker clicks no longer fire, I have noticed some patterns:

> - On Google Maps, the first 4-6 clicks are detected, and none thereafter.
> - On Leaflet, all clicks are detected in the first instance of the map view. When moving into another view and back into the map view, the clicks no longer fire. Usually 2 or 3 iterations of cycling out and in of the map view is needed before the clicks stop firing. Double clicks and other events are unaffected.
The map is always wrapped with data-tap-disabled="true".

> Is anyone else having similar problems?

Here is another post describing the issue (http://bit.ly/1LgshYe) with a codepen available (http://codepen.io/ionic/pen/uzngt).</span>

<span is-issue-template></span>

**Comment by mhartington** [comment] 2015-10-12 19:05
Hmm, are you adding `data-tap-disabled="true"` to the map?

**Comment by MarcBT** [comment] 2015-10-13 07:06
Hi @mhartington, thanks for your answer. 
Yes, I confirm that we are using ```data-tap-disabled="true"``` as indicated in ionic's doc.

The app works perfectly on iOS 8 and Android. Described issue occurs only on iOS 9 devices. 

Please note that we are using telerik WKWebview plugin (http://bit.ly/1L8R8PU) to activate WKWebview.
  - We have upgraded it to its latest version but it does not solve the issue.
  - We also tried to remove it and use UIWebview with angular-ios9-uiwebview.patch.js but it does not solve this issue.
Thus, this plugin does not seem to cause the issue.

Finally, in addition to previous's message codepen, we have created a cordova sample app with an index.html file (http://bit.ly/1Pqvh9D) without angular and without ionic dependencies. It loads a simple GMap with some markers and displays alert when click events are triggered. In this case, issue does not occur.

**Comment by Daveloose** [comment] 2015-10-15 13:58
I can confirm this error. It is very strange, because it works for the first clicks.
But after some random time, it stops working.

**Comment by devilop3rz** [comment] 2015-10-15 14:23
Hi, had the same problem using a leaflet-map. I found out that the error is caused by ionics 'isElementTapDisabled()' function. Its somehow gets stuck in the while loop.

I've replaced it with a small jQuery function and now everything seems to work well.
```javascript
isElementTapDisabled: function(ele) {

    if (ele && ele.nodeType === 1) {
      var element = ele;
      
      if ($(element).parents('[data-tap-disabled]').length) {
        return true;	
      }
     /*
      while (element) {
        if ((element.dataset ? element.dataset.tapDisabled : element.getAttribute('data-tap-disabled')) == 'true') {
        	
          return true;
        }
        element = element.parentElement;
      }*/
    }
    return false;
  },
```

**Comment by pranavrajs** [comment] 2015-10-16 11:58
I also have the same issue. I tried the above fix by Ernst and it is working.

**Comment by MarcBT** [comment] 2015-10-19 09:43
Hi there, 
be careful with ```$parents()```'s method from jQuery. It indeed solves the not responding markers/map issue but also breaks the scrollView (at least in my case).

I tried to dig deep around this issue last days. As mentioned by @devilop3rz, the ```while``` loop inside ```isElementTapDisabled``` is buggy on iOS9.

Problem occurs more precisely with the ```if``` condition. Indeed, after few interactions, for a reason I can't understand, the ```if``` block is not executed anymore even if its condition is evaluated to ```true``` (when ```data-tap-disabled```attribute is detected)...

![ionic- 4506-ios9-if-condition-skipped](https://cloud.githubusercontent.com/assets/3440947/10574355/d45f4146-7655-11e5-83ec-e81646e32ce1.png)

**Comment by MarcBT** [comment] 2015-10-19 10:09
Moreover, ```$parents()``` method does not pass tests as it does not detect if ```data-tap-disabled``` attribute is present on the touched element.

**Comment by mcasaje** [comment] 2015-10-27 21:42
I've had the same issue using and finally solved it by refactoring the if statement in the 'isElementTapDisabled' function.

```
if( element.getAttribute('data-tap-disabled') == 'true' || element.dataset.tapDisabled == 'true' ) {
```

Here's the full 'isElementTapDisabled' function:

```
  isElementTapDisabled: function(ele) {
    if(ele && ele.nodeType === 1) {
      var element = ele;
      while(element) {
        if( element.getAttribute('data-tap-disabled') == 'true' || element.dataset.tapDisabled == 'true' ) {
          return true;
        }
        element = element.parentElement;
      }
    }
    return false;
  },
```

If you're curious, here's what the original if statement was:

```
if( (element.dataset ? element.dataset.tapDisabled : element.getAttribute('data-tap-disabled')) == 'true' ) {
```

**Comment by MarcBT** [comment] 2015-10-28 12:58
For your info, we have deployed patch #4538 on our production app and are not experiencing anymore this bug.

@mhartington can you please review eitheir PR #4538 or @mcasaje changes ?

**Comment by jfcisternasm** [comment] 2015-10-30 15:14
@mcasaje It works for me, Thanks!

**Comment by mlynch** [comment] 2015-12-06 17:51
Can you see if the recently merged PR #4589 fixes this for you? Going to close since I believe this is a duplicate solved by that.

**Closed by mlynch** 2015-12-06 17:51 UTC

**Comment by MarcBT** [comment] 2015-12-07 18:21
@mlynch. 
Sure will check and let you know.

**Comment by shamid** [comment] 2016-01-07 06:54
Hey this still didn't work for me on Ionic 1.2.1, so I used the patch by mcasaje and it fixed the problem for me on iOS 9.

**Comment by MarcBT** [comment] 2016-01-07 07:35
@shamid Thanks for giving feedback on this. I did not have time yet to upgrade and check on my own if ionic 1.2.1 fixed the issue.
@mlynch Can you please review @mcasaje solution or PR #4538 and add one of them to the project ?
Thanks in advance.

**Comment by itamair** [comment] 2016-01-26 14:57
@mcasaje It works for me too, Thanks!

**Comment by tieum** [comment] 2016-01-30 15:47
@mlynch I can confirm PR #4589 did not fix the issue, but @mcasaje change did

 can you reopen the issue?

Thanks

**Comment by bianchimro** [comment] 2016-02-06 12:25
same problem here, on ios 9.2
with leaflet 0.7.7 and angular-leaflet-directive + ionic 1.2.4
@mcasaje patch works for me

**Comment by hungtrinh** [comment] 2016-04-02 14:05
same problem on ios 9.3
@mcasaje patch works for me

`isElementTapDisabled: function(ele) {
    if(ele && ele.nodeType === 1) {
      var element = ele;
      while(element) {
        if( element.getAttribute('data-tap-disabled') == 'true' || element.dataset.tapDisabled == 'true' ) {
          return true;
        }
        element = element.parentElement;
      }
    }
    return false;
  },`

**Comment by johntomcy** [comment] 2016-04-13 14:57
Same with me as well... the fix provided @mcasaje works fine for me as well...
Will this be available in next ionic build?

**Comment by jmterminator** [comment] 2016-04-27 15:24
The provided fix works for me as well. This issue needs to be reopened and the provided fix should be used as the patch.

**Comment by bar3bon3** [comment] 2016-05-11 15:33
Same problem for me: 
- iOS 9.3.1
- Telerik cordova WKWebView Polyfill Plugin 0.6.9 
- leaflet 0.7.7
- angular-leaflet-directive 0.10.0
- ionic 1.3.0

@mcasaje fix works like a charm, thank you so much!

**Comment by MarcBT** [comment] 2016-05-12 05:26
Hi all,
sounds like this has been finally fixed for the next release ! See commit 88b37772.
Have a good day.

**Comment by itaibs** [comment] 2016-05-24 03:53
Hi,
Anybody knows if this fix is already available also in the MeteorJS ionic package? (https://atmospherejs.com/driftyco/ionic).

I'm experiencing this issue there, and I'm not able to update to a newer version of the package.

**Comment by De-Lac** [comment] 2016-06-10 12:00
I still have the same issue.... the tap on the map's markers sometimes works, sometimes not. 
In my app I have multiple maps (in different views). It seems that when I show another map, the tap stops working. I have this error just with **cordova-plugin-wkwebview-engine**, before it worked.
Unfortunately I really need the wkwebview otherwise map performance are very poor. 
I should have everything up-to-date

```
$ ionic lib
Local Ionic version: 1.3.1  (/Users/danielefani/Sites/epoi/eppoi_app/www/lib/ionic/version.json)
Latest Ionic version: 1.3.1  (released 2016-05-12)
 * Local version up to date
```

```
$ionic info

Your system information:

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 1.7.15
Ionic App Lib Version: 0.7.2
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.5.0
Xcode version: Xcode 7.3 Build version 7D175 
```


```
$ cordova --version
6.2.0
```
