### ISSUE TITLE
Scroll bug with tap event inside content

### ISSUE THREAD

**Issue by jonatasfreitasv** [driftyco/ionic#11366] opened 2017-04-26 05:30 UTC
**Ionic version:**  (check one with "x")
[ X] **3.x**

**I'm submitting a ...**  (check one with "x")
[ X] bug report

**Current behavior:**
When have tap event inside scroll content.

**Related code:**

```
<ion-content padding>

    <ion-list class='animated slideInDown' text-wrap>

        <ion-item-sliding #item *ngFor='let notification of notifications_cache'>

            <button ion-item (tap)='openMap(notification)'>Any</button>

            <ion-item-options side="right">
                <button (tap)='deleteFromCache(notification)' ion-button>
                    <ion-icon class='animated fadeIn' name="md-trash"></ion-icon>
                </button>
            </ion-item-options>

        </ion-item-sliding>

    </ion-list>

</ion-content>
```

**Ionic info:**:

```
Cordova CLI: 6.5.0
    Ionic Framework Version: 3.0.0
    Ionic CLI Version: 3.0.0-beta7
    ios-deploy version: 1.9.1
    ios-sim version: 5.0.13
    OS: macOS Sierra
    Node Version: v7.5.0
    Xcode version: Xcode 8.2 Build version 8C38
```

**Comment by jgw96** [comment] 2017-04-26 17:32
Hello! Thanks for opening an issue with us. I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/11112

**Closed by jgw96** 2017-04-26 17:32 UTC

**Comment by jonatasfreitasv** [comment] 2017-04-27 22:11
Ok! Sorry @jgw96
