### ISSUE TITLE
Navigator Controller - Object Unsubscribed

### ISSUE THREAD

**Issue by genesisoft** [driftyco/ionic#9892] opened 2017-01-05 19:25 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Has a problem using Navigator Controller, because I noticed when used conditions like ngIf or ngSwicht to alter an item by ion-list, ion-card and ion-grid, when I click in the back button on navigator is showing a error message Object Unsubscribed and stop the navigator controller. 

**Expected behavior:**
In Ionic 1 this problem not exist, I'm starting use the latest version by ionic 2, I don't know if that this error exists in old version.

**Steps to reproduce:**
<img width="326" alt="screen shot 2017-01-03 at 09 56 03" src="https://cloud.githubusercontent.com/assets/16091280/21694194/2209e22a-d36b-11e6-88ee-6ebfbb9aec1a.png">

Complete Error Message: 
[note.pdf](https://github.com/driftyco/ionic/files/688148/note.pdf)

**Comment by jgw96** [comment] 2017-01-05 20:53
Hello! Thanks for using Ionic! We are actually working on fixing this issue now and you can expect it to be fixed in the next release.

**Comment by jgw96** [comment] 2017-01-05 20:57
Ill update this issue when i can confirm that it is fixed.

**Comment by brandyscarney** [comment] 2017-01-05 23:19
This issue should be fixed in the nightly release, to update:

```
npm install ionic-angular@nightly --save --save-exact
```

It will also be in the 2.0.0-rc.5 release. Please let me know if you still have an issue, thanks!

**Closed by brandyscarney** 2017-01-05 23:19 UTC
Labels: v2

**Comment by genesisoft** [comment] 2017-01-06 18:57
@brandyscarney Thank you!!! Now worked very well

**Comment by jsayol** [comment] 2017-01-06 19:16
Hey @brandyscarney, sorry to say I just run into this error again on the latest nightly (2.0.0-rc.4-201701052314). I'm looking into it, I'll see if I can reproduce it in a minimal example.

**Comment by brandyscarney** [comment] 2017-01-06 19:34
Thanks @jsayol! Let me know when you do. I'll leave this issue closed and the other issue (#9751) open since this use case was fixed.

**Comment by jsayol** [comment] 2017-01-06 19:35
Oops, actually meant to comment on the other one.

**Comment by mariohmol** [comment] 2017-03-20 16:11
Hi there, i'm having this issue with 2.2.0, is that fix in this release?

```
Your system information:

Cordova CLI: 6.5.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 0.0.36
ios-deploy version: 1.9.1
ios-sim version: 3.1.1
OS: macOS Sierra
Node Version: v6.3.1
Xcode version: Xcode 8.2.1 Build version 8C1002
```

```
"ObjectUnsubscribedError: object unsubscribed↵    at new ObjectUnsubscribedError 
(http://localhost:8100/build/main.js:6908:26)↵    at Subject.next 
(http://localhost:8100/build/main.js:7009:19)↵    at ScrollView.scrollEnd [as _endTmr] 
(http://localhost:8100/build/main.js:51888:32)↵    at ScrollView.destroy 
(http://localhost:8100/build/main.js:52180:30)↵    at Content.ngOnDestroy 
(http://localhost:8100/build/main.js:57070:38)↵    at Wrapper_Content.ngOnDestroy 
(/IonicModule/Content/wrapper.ngfactory.js:15:16)↵    at 
CompiledTemplate.proxyViewClass.View_EncontradoPage0.destroyInternal 
(/AppModule/EncontradoPage/component.ngfactory.js:281:22)↵    at 
CompiledTemplate.proxyViewClass.AppView.destroy 
(http://localhost:8100/build/main.js:10834:14)↵    at CompiledTemplate.proxyViewClass.DebugAppView.destroy 
(http://localhost:8100/build/main.js:11062:38)↵    at CompiledTemplate.proxyViewClass.View_EncontradoPage_Host0.destroyInternal 
(/AppModule/EncontradoPage/host.ngfactory.js:39:19)"

__p 
```

**Comment by skol-pro** [comment] 2017-04-09 13:16
Getting the same issue too...
