### ISSUE TITLE
bug: ng-repeat is not working anymore with ion-tab

### ISSUE THREAD

**Issue by cuin** [driftyco/ionic#3066] opened 2015-02-09 21:52 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Your test case for demonstrating repeated tabs does not work anymore with Beta 14.
https://github.com/driftyco/ionic/blob/master/test/html/tabs-repeat.html</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-02-09 21:52
Greetings @cuin!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3066). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3066)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by rsfurlan90** [comment] 2015-03-16 01:29
Pretty sure there is a bug on this. Based on the test case provided by cuin, I have made this Codepen to help you to reproduce it using the nightly build:

http://codepen.io/rsfurlan90/pen/Kwrgzo

There is also something wrong with the tabs content: you can only see it correctly when you select the tab you want for the very first time, otherwise it seems to mess up their contents as you navigate between them.

**Comment by giorgiofellipe** [comment] 2015-06-01 01:23
+1

**Comment by Ionitron** [comment] 2015-08-30 01:53
Greetings @cuin!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-08-30 01:53 UTC
Labels: ionitron:closed
