### ISSUE TITLE
bug: Ion-tabs when scrolling down the screen does not hiding navbar in iOS Safari

### ISSUE THREAD

**Issue by rubinchyk** [driftyco/ionic#4686] opened 2015-11-30 13:31 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>browser</span>

<span ionic-description>HTML structure is as follows:

ion-view
ion-content
ion-tabs
ion-tab ...

The problem is that the project is necessary when scrolling down to hide the upper and lower standard panels Safari. But they did not hide, as I believe is happening inside the tab scrolling and Safari does not understand what is happening to scroll the screen, thereby hiding the standard browser panel. Perhaps someone faced with this problem?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-11-30 13:31
Greetings @rubinchyk!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4686). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4686)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by jgw96** [comment] 2016-03-14 20:10
Hello! Thanks for opening an issue with us, we just need a little more info from you so that we can better help you with your issue. Would you mind posting a code sample, plunkr or codepen that we can use to reproduce your issue? Also, would you mind running `ionic info` and posting the output? Thanks again!

**Comment by jgw96** [comment] 2016-03-21 19:50
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!

**Closed by jgw96** 2016-03-21 19:50 UTC
Labels: scroll, v1
