### ISSUE TITLE
bug: infdig Infinite $digest Loop

### ISSUE THREAD

**Issue by appwrx** [driftyco/ionic#4082] opened 2015-07-14 14:10 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>I tried my app on iOS9 Beta and always receive this error, when i click something (e.g. a tab):

angularjs exception: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []
caused by "undefined js stack:</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-07-14 14:10
Greetings @appwrx!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4082). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4082)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment] 2015-07-14 18:20
I've seen this as well. Since it's beta software, I wouldn't worry too much.

**Comment by appwrx** [comment] 2015-07-15 08:09
That's right. I hope it will be fixed soon. i recognized that ionic inherited this bug from angular. 
https://github.com/angular/angular.js/issues/12241

**Comment by mhartington** [comment] 2015-07-15 17:00
Alright, closing this since it's not really an issue with ionic, but ios9 and angular.

**Comment by appwrx** [comment] 2015-08-14 07:50
CleverCoder posted a fix. It is possible to include this fix to ionic?
https://github.com/angular/angular.js/issues/12241#issuecomment-130744518

**Comment by abrahamrkj** [comment] 2015-08-15 00:42
@mhartington  So how to update the fix in ionic ? any steps?

**Comment by abrahamrkj** [comment] 2015-08-31 05:33
@mhartington Now the ionic got the new angular update ?

**Comment by aderowbotham** [comment] 2015-09-06 12:31
It *is* an iOS9-specific issue but that is due to be released imminently. Should ionic not urgently adopt a patched version of Angular to create a workable interim solution for iOS9? (e.g. like this https://github.com/angular/angular.js/issues/12241#issuecomment-130744518 ).

The Angular team is unlikely to change anything because Angular doesn't officially support uiWebView. And I think waiting to Apple to \*maybe\* fix this is it extremely risky as this is a ticking timebomb that affects thousands of apps in the wild. And uiWebView is deprecated so why would they care?

The other way out of this problem (which to me is a business-critical show stopper) is if cordova-ios 4.0 gets released with WKWebView used in place of uiWebView, and ionic adopts that.

Even though ionic isn't directly the cause, the upshot is that ionic is fundamentally broken in iOS9. I'd rather be pessimistic about it being fixed elsewhere and be proven wrong than just sit and wait.

**Comment by pawurb** [comment] 2015-09-09 19:36
Release of IOS9 is in one week. Is there any update on this bug ?

**Comment by mhartington** [comment] 2015-09-09 19:43
We're talking to the angular team, where the issue is originating from.
Just an observation. This issue isn't breaking anything, everytime I've see the error the app still works fine.

**Comment by aderowbotham** [comment] 2015-09-09 20:09
My app has a tab navigation where each tab's class is bound (indirectly) to the `$location`. An `active` class indicates which is the active section (kind of like `ng-class="{ 'active': thisTab.active }"`) where each tab's `active` property is based on a comparison to the location). In iOS9 the icons kind of flicker and don't reliably update as you navigate. Two tabs will appear to be 'active' at the same time. 

Speculatively: maybe `$scope.$apply()` is not being called due to the `infinite digest` error.

Also, sometimes tapping on the tabs (standard `<a href=`> tags) has no effect first time around, so the new location apparently doesn't get registered by ui-router.

It's completely solid in iOS8.X

**Comment by zarko-tg** [comment] 2015-09-09 20:23
@mhartington if you wish to experience the usability issues caused by this just follow the steps I provided in #4151. Choosing side menu items is now and then broken, the navigation seeming very off. You just have to see it to get a feeling for the problem.
Given the age of the seemingly Angular issue and the slow app approval process at Apple I worry it might be too late to do anything about it just now.
Quite disappointing case handling if you ask me, even if it's a pure root cause within WebKit. I could not see any official response from the Angular people.

**Comment by mlynch** [comment] 2015-09-09 20:37
Hey everyone, we are looking into this and will make sure we get it fixed for release, even if we have to hack Angular to make it work. Sorry for the lack of movement on this. We will also push on the angular side to get it fixed if we can.

**Comment by zarko-tg** [comment] 2015-09-09 21:25
Small update: It seems the issue is still there in the latest iOS 9 (GM, build 13A340). I could simply experience the problem(s) while using an app that's already in production / app store.

The aforementioned iOS build is the one going out to everyone one week from now.

**Comment by perrygovier** [comment] 2015-09-10 00:20
We're working on a fix right now. Does this help? http://driftyco.github.io/ionic-code/patch/ios9-$browser-patch.js

**Comment by adamdbradley** [comment] 2015-09-10 00:28
We have a work in progress branch which can be found here: https://github.com/driftyco/ionic/blob/ios9-patch/js/angular/service/decorators/ios9-browser-fix.js

It decorates `$browser` and applies [this patch](https://github.com/angular/angular.js/issues/12241#issuecomment-130744518).

We also placed the patch on our CDN. I don't recommend using the CDN file for production, it's only there so it's easier to test with right now. http://code.ionicframework.com/patch/ios9-$browser-patch.js

 Please test it out and let us know how it goes, thanks.

**Comment by perrygovier** [comment] 2015-09-10 00:35
To clarify, this can be added in a script tag immediately after your ionic bundle, so:
```html
<script src="lib/ionic/js/ionic.bundle.js"></script>
<script src="http://driftyco.github.io/ionic-code/patch/ios9-$browser-patch.js"></script>
```

**Comment by Kira2** [comment] 2015-09-10 06:04
Hi !

Thank you to work so fast on a solution. I tested your script and everything's work fine with my application, except I had to replace "forEach" declarations with "angular.forEach" to avoid this error when the application launches:

"ReferenceError: Can't find variable: forEach, http://192.168.0.49:8101/lib/ionic/js/ionic.bundle.js, Line: 12976"

versions:
- Ionic v1.0.1
- Angular v1.3.13

Thank you.

**Comment by zarko-tg** [comment] 2015-09-10 08:56
@adamdbradley 
One possible integration is the following:
```
    ...
    <script src="lib/ionic/js/ionic.bundle.min.js"></script>
    <script>
      // iOS9 patch, see https://github.com/driftyco/ionic/issues/4082
      if ( ionic.Platform.isIOS() && ionic.Platform.version().toString()[ 0 ] === '9' ) {
        var patch = document.createElement( 'script' );
        patch.src = 'lib/ionic/js/ios9-$browser-patch.js';
        document.head.appendChild( patch );
      }
    </script>
    ...
```
I'd rather not include the current patch script at all when running on iOS version < 9.

**Comment by mhartington** [comment] 2015-09-10 09:07
I will note, that so far the patch hasn't created any issues on android or older iOS 

Mike Hartington

**Comment by sidlauskaslukas** [comment] 2015-09-10 09:11
Looks like the patch fixed all the issues we had with transitions.

**Comment by outlog** [comment] 2015-09-10 09:41
thanks, patch seems to work great.

is there a rdar:// we can reference as we push this through to the app store?

**Comment by aderowbotham** [comment] 2015-09-10 11:50
@zarko-tg Yes - I just realised the same thing. For some reason if the script is added that way the module does not load.

Is there a workable way of only loading the script in iOS9? Or, if not, is there any harm in this patch running on iOS8?

**Comment by zarko-tg** [comment] 2015-09-10 11:55
@aderowbotham They might address that need directly within the script as you can already see some commented-out lines in it / unfinished business.
In meantime I suggest we listen to @mhartington (see his last comment).

**Comment by perrygovier** [comment] 2015-09-10 12:31
@aderowbotham this is the root issue https://openradar.appspot.com/22186109

**Comment by perrygovier** [comment] 2015-09-10 12:34
Was anyone seeing their app actually break in a way that we can reproduce? We've seen lots of nasty console.errors, but in the apps we have for testing and a short list of Ionic apps already on the marketplace all still behaved well.

**Comment by zarko-tg** [comment] 2015-09-10 12:41
@perrygovier at the risk of repeating myself more than needed, have a look at https://github.com/driftyco/ionic/issues/4151
At the same time I'd like to thank you/team for taking charge.

**Comment by aderowbotham** [comment] 2015-09-10 12:54
@perrygovier Yes, it's very broken. And fixed by the patch. However it's complicated and not easy to reproduce (been in development for > 2 years). Maybe once I've got a version tested and with Apple I'll have time to produce a stripped down reproducible error.

**Comment by adamdbradley** [comment] 2015-09-10 13:57
I just updated the script to using `angular.forEach`, thanks @Kira2 for pointing that out.
https://github.com/driftyco/ionic/commit/c8da2754b907cc1d17858b64547c66615423a044

**Comment by jyc66** [comment] 2015-09-10 14:41
Won't your OS version check break Ionic apps on 9.1 which is coming out very soon as well?

**Comment by JeremyPlease** [comment] 2015-09-10 17:45
@jyc66, yes the patch doesn't handle iOS version 9.1. I think the hope is that Apple will patch the issue on their side for 9.1. It's not clear if this patch will break other things when Apple fixes things though... Follow the discussion here:
https://github.com/angular/angular.js/issues/12241#issuecomment-139316812

**Comment by mahnuh** [comment] 2015-09-10 18:02
The fix does break the side menu in my apps. The menu closes, but the view does not change. Anybody with an idea to fix that or am I missing something here?

**Comment by mhartington** [comment] 2015-09-10 18:05
@mahnuh can you comment this block on line 50837 in ionic.bundle.js or line 10 in the patch file.

```
  var isIOS9 = (navigator.userAgent.indexOf('Version/9.') != -1) && (navigator.appVersion.indexOf('9_0') != -1);
  if (!isIOS9) {
    // do not patch if not iOS9 UIWebView
    return $browser;
  }
```

**Comment by mahnuh** [comment] 2015-09-10 18:12
Weather I comment this block out or not, it does not make any difference

**Comment by mhartington** [comment] 2015-09-10 18:19
is there any code on your end we can look at? Maybe a repo? All of our tests so far have worked with sidemenu

**Comment by mahnuh** [comment] 2015-09-10 18:38
I had to update my apps to Ionic 1.1.0, side menu is working now. But thanks anyway!

**Comment by aderowbotham** [comment] 2015-09-10 18:58
Big props to the team for this patch, a real life-saver. Thank you!

Regarding that user-agent detect, the above is giving me `isIOS9 = false`

But this is working for me:

    var isIOS9 = (navigator.userAgent.indexOf('iPhone OS 9_') != -1);
    if (!isIOS9) {
       console.log("not ios 9!");
       // do not patch if not iOS9 UIWebView
       return $browser;
    }


On iOS 9.0 GM the value of `navigator.userAgent` is:
`Mozilla/5.0 (iPhone; CPU iPhone OS 9_0 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13A340 (4913920384) (ios9-$browser-patch.js, line 11)`

So checking for the substring `'iPhone OS 9_'` works here, and should continue to work for 9.1 (assuming they keep the same format).

**Comment by mhartington** [comment] 2015-09-10 19:01
Yeah, we're working with the angular team to get a proper fix in angular. 
The user agent has changed, so once we have a good fix, we'll update our info.

**Comment by harangue** [comment] 2015-09-10 19:07
When can we expect these things to be resolved on Apple's end?

**Comment by jyc66** [comment] 2015-09-10 19:09
Some time between a few months to never.

**Comment by mhartington** [comment] 2015-09-10 19:16
@jyc66 ehh, no

@harangue you can follow the progress here
https://github.com/IgorMinar/angular.js/commit/99f0e4d304be39bf26f800a261a6e87b4c031800

**Comment by harangue** [comment] 2015-09-10 19:27
Thanks so much for your updates and thorough damage control. You guys are the best. :)

**Comment by jyc66** [comment] 2015-09-10 19:29
Thats great news.  It's too bad it made it into the gold master meaning we will have to support it for years.

**Comment by mhartington** [comment] 2015-09-10 19:32
Not really, ios upgrades tend to move pretty fast. Hopefully, 9.1 will be out before the new iphone. Got to be optimistic here

**Comment by sean-hill** [comment] 2015-09-10 20:29
Hey guys, my tabs are all funked up (the icons bounce up and down) even when using the patch script. Is this still a problem? Also switching between the tabs sometimes doesn't work. It just flashes back to the current state. Here's a [video](https://dl.dropboxusercontent.com/u/97539058/Bugs/fail.mov).

**Comment by sean-hill** [comment] 2015-09-10 20:33
Also, the Keyboard plugin doesn't work anymore.

    $cordovaKeyboard.hideAccessoryBar(true);
    $cordovaKeyboard.disableScroll(true);

The accessory bar is no longer hidden, and the views bounce when inputs for focused.

**Comment by mhartington** [comment] 2015-09-10 20:38
@sean-hill is there anyway you could share some code with me? If you want to shoot me an email?

**Comment by sean-hill** [comment] 2015-09-10 20:39
@mhartington no problem! What code would be helpful. Our app is huge, so narrowing down it down would be helpful.

**Comment by perrygovier** [comment] 2015-09-10 20:40
Also @sean-hill, try this https://www.dropbox.com/s/qsp3dgydsz775h6/ionic.bundle.js?dl=0

**Comment by sean-hill** [comment] 2015-09-10 20:41
Thanks @perrygovier I'll give it shot. Here's where I disable the scroll to prevent the keyboard from bouncing in iOS 8.

    .run(...) {

    	$ionicPlatform.ready(function() {

            if (ionic.Platform.isWebView()) {

                $cordovaKeyboard.hideAccessoryBar(true);
                $cordovaKeyboard.disableScroll(true);

            }
            if (ionic.Platform.isAndroid()) {
               ionic.Platform.isFullScreen = true;
            }     

        });   

    });

**Comment by sean-hill** [comment] 2015-09-10 20:41
Here's my tabs navigation:

    <ion-nav-bar class="bar-dark">
        <ion-nav-back-button>
        </ion-nav-back-button>
    </ion-nav-bar>
    <ion-tabs class="tabs-dark tabs-icon-top">

        
        <ion-tab title="Activity" icon-on="ion-ios-bolt" icon-off="ion-ios-bolt-outline" ui-sref="app.activity">
            <ion-nav-view name="app-activity"></ion-nav-view>
        </ion-tab>

        
        <ion-tab title="Roommates" icon-on="ion-ios-people" icon-off="ion-ios-people-outline" ui-sref="app.roommates">
            <ion-nav-view name="app-roommates"></ion-nav-view>
        </ion-tab>

        
        <ion-tab title="Bills" icon-on="ion-ios-paper" icon-off="ion-ios-paper-outline" ui-sref="app.billers">
            <ion-nav-view name="app-billers"></ion-nav-view>
        </ion-tab>

        
        <ion-tab title="Profile" icon-on="ion-ios-person" icon-off="ion-ios-person-outline" ui-sref="app.profile">
            <ion-nav-view name="app-profile"></ion-nav-view>
        </ion-tab>

    </ion-tabs>

**Comment by mhartington** [comment] 2015-09-10 20:44
@sean-hill just tested the keyboard stuff with the bundle perry sent you, looks good to me. 

I've been testing with a tabs based app, haven't seen anything that looks like that.

**Comment by sean-hill** [comment] 2015-09-10 20:48
Hey @mhartington and @perrygovier, the bundle fixed the tab problems! Woot. Take a look at [this video](https://dl.dropboxusercontent.com/u/97539058/Bugs/fail2.mov), it shows how it bounces.

**Comment by mhartington** [comment] 2015-09-10 20:51
Hmm, what version of the plugin do you have? the latest is 1.0.4

**Comment by sean-hill** [comment] 2015-09-10 20:52
@mhartington I'm using version 1.0.5.

**Comment by mhartington** [comment] 2015-09-10 20:56
Hmm, alright. 

Just pulled the latest version, still not getting the bouncing. 
Are you seeing the same thing using the non-ngcordova api? 

```
if (window.cordova && window.cordova.plugins && window.cordova.plugins.Keyboard) {
      cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
      cordova.plugins.Keyboard.disableScroll(true);

    }
```

**Comment by sean-hill** [comment] 2015-09-10 21:00
Let me try a blank starter Ionic project and see what it does :)

**Comment by sean-hill** [comment] 2015-09-10 21:09
Curses, a blank tabs starter doesn't bounce. Let me see if you're solution without using ngcordova works.

**Comment by sean-hill** [comment] 2015-09-10 21:12
Dang that doesn't fix it either. I guess this is my problem, just switching over to iOS 9 started it.

**Comment by mhartington** [comment] 2015-09-10 21:16
@sean-hill alright. Feel free to shoot me an email if you want. I'll see what I can do.

**Comment by sean-hill** [comment] 2015-09-10 21:38
Thanks @mhartington, I shot an email over to your gmail.

**Comment by sean-hill** [comment] 2015-09-10 22:12
I found out that my problem with iOS 9 and the keyboard plugin is related to a custom plugin and not with Ionic. I'm not sure which plugin yet, but Ionic is not the problem.

**Comment by IgorMinar** [comment] 2015-09-11 03:54
Hi folks, can you please test this patch: https://gist.github.com/IgorMinar/863acd413e3925bf282c

It should work with Angular 1.2 – 1.4.5 and doesn't require any Angular updates. Instructions on how to apply this to your app are in the gist.

We are going to have a proper fix in Angular 1.4.6, but in the meantime this standalone patch is meant to ease the implementation and deployment of a fix so that you can roll it out quickly.

**Comment by sean-hill** [comment] 2015-09-11 04:09
Hi Igor, does this patch replace the one given by the Ionic Admins? Found [here](https://code.ionicframework.com/patch/ios9-$browser-patch.js).

**Comment by perrygovier** [comment] 2015-09-11 04:33
Thanks @IgorMinar! 
With this patch I do still occasionally see a flicker when switching between tabs. The console error is gone however. With the patch I linked to [here](https://github.com/driftyco/ionic/issues/4082#issuecomment-139372747) based on your team's work I was unable to reproduce a flicker. 

Whether it flickers or not is intermittent about once every 5-10 times. Possible race condition?

**Comment by rajatrocks** [comment] 2015-09-11 04:39
HI @perrygovier - since I'm running beta-14 still, I don't think I can use the new ionic bundle file: https://www.dropbox.com/s/qsp3dgydsz775h6/ionic.bundle.js?dl=0
Is this basically the same thing? http://code.ionicframework.com/patch/ios9-%24browser-patch.js

**Comment by IgorMinar** [comment] 2015-09-11 04:56
@perrygovier two questions:

1/ how can I reproduce the flicker? (can you provide an app + steps)?
2/  which change caused the flicker to go away? 

@sean-hill yes. the goal is to replace that patch with something more light-weight and more reliable.

**Comment by streetkid** [comment] 2015-09-11 05:24
i've installed it using Angular 1.4.3 But I don't see the patch happening. I've put in console logs  around the code and conditions and it's not triggered at all. I've added it in the list of angular.module  injection but it's not seeming to trigger. How else do I trace this GRRR.

My app is under review at the moment, wondering if I'll get rejected because of this.

**Comment by rajatrocks** [comment] 2015-09-11 05:49
Hi @IgorMinar - I installed your patch into my app (Angular 1.3, Ionic beta-14). Sometimes when I change tabs the new state shows, then the old one flashes back for a second, then the new one comes back again. I made a quick video that shows this: https://www.dropbox.com/s/o1dbvxb1ehr1mjn/flashback.mov?dl=0 - you can see what I'm talking about in there.

**Comment by IgorMinar** [comment] 2015-09-11 07:39
@rajatrocks yeah, that doesn't look right. is there any chance you could reduce to a minimalistic example and share it with me?

**Comment by EpoX44** [comment] 2015-09-11 12:39
Hey guys.
I have iOS 9.1 (13B5110e) on an iPad Air 2 installed and tried all fixes that are available but none of them worked. Still get the following error message every time i click on something (e.g. an tab or an item in a list)
I use Ionic 1.0.0-rc.1 and Angular v1.3.13.

Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []

Also the views flicker every then and now when i click an item to open the details of it. That means the detail-view opens but the content and ion-nav-buttons flicker first. Then the content loads but the ion-nav-buttons and the back-button are vanished.

**Comment by perrygovier** [comment] 2015-09-11 13:11
Hey @IgorMinar, I haven't changed anything since last night but I don't see the flicker anymore. Did you update the script? Either way, here's the default Ionic Tabs app with your patch applied. 
https://www.dropbox.com/s/ukxdlgjf143y3cp/test.zip?dl=0

**Comment by JeremyPlease** [comment] 2015-09-11 14:55
@IgorMinar, your patch works great on iOS 9 iPhone UIWebView, but there are some issues with the user agent detection.

iOS 9 iPhone user agent in UIWebView:
`Mozilla/5.0 (iPhone; CPU iPhone OS 9_0 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13A340`

iOS 9 iPhone user agent in Safari:
`Mozilla/5.0 (iPhone; CPU iPhone OS 9_0 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13A340 Safari/601.1`

iOS 9 iPad user agent in UIWebView:
`Mozilla/5.0 (iPad; CPU OS 9_0 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13A340`

iOS 9 iPad user agent in Safari:
`Mozilla/5.0 (iPad; CPU OS 9_0 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13A340 Safari/601.1`

The regex that will reliably match all of these is:
````
function isIOS9UIWebView(userAgent) {
    return /(iPhone|iPad|iPod);.*OS 9_\d/.test(userAgent);
}
````

I've forked @IgorMinar's gist and made the changes here: https://gist.github.com/JeremyPlease/72cb3bf98279fefed4e3

**Comment by sean-hill** [comment] 2015-09-11 15:09
@perrygovier, yesterday you gave me an updated `ionic.bundle.js`. With @IgorMinar's recent patch, should I return to ionic's latest `ionic.bundle.js` and simple use his patch?

**Comment by sean-hill** [comment] 2015-09-11 15:10
@perrygovier, yesterday you gave me an updated `ionic.bundle.js`. With @IgorMinar's recent patch, should I return to ionic's latest `ionic.bundle.js` and simply use his patch?

**Comment by JeremyPlease** [comment] 2015-09-11 15:16
I realized this is just an issue in UIWebView, so I've updated my gist to not apply when in Safari:
````
function isIOS9UIWebView(userAgent) {
    return /(iPhone|iPad|iPod);.*OS 9_\d/.test(userAgent) && !/Version\/9\./.test(userAgent);
}
````

**Comment by perrygovier** [comment] 2015-09-11 15:23
@sean-hill, I'm still running the patch through a bunch of test apps, but so far it looks good. If you're on the latest version, they shouldn't be any practical difference, but Igor's patch works with older versions of Ionic as well. So if you're up to date, it's probably not necessary, but doesn't hurt. If you're not current, definitely use Igor's.

**Comment by sean-hill** [comment] 2015-09-11 16:00
Hey @IgorMinar and @perrygovier, the patch given by @IgorMinar seems to work great with my app! Switching tabs does not goes any flashing as we've discussed above. Thanks.

**Comment by andreground** [comment] 2015-09-11 17:37
@EpoX44 I do have the flashing and flickering issues too, even using the latest @IgorMinar fix (1.0.3).
I'm on Ionic 1.0.1.
Any hint?

**Comment by sean-hill** [comment] 2015-09-11 17:39
Hey @andreground try `ionic lib update`, it'll replace your `ionic.bundle.js` with version `1.1.0`, that worked for me.

**Comment by sloops77** [comment] 2015-09-11 17:47
Hi all im having many problems. I've tried both Igor latest gist (#3) on top of 1.0.1 & the latest fix from https://github.com/driftyco/ionic/master#b7e1878e6f27e36746dbdeb2f6ddb54b8d6cf977. 

I use trigger.io for my framework not cordova but i dont see why that should be an issue for transition behaviour (it's never been in the past).  I disable caching.

I've been testing on an iphone 6plus -> here is a vid of my issues: I have overlays, flashing and even the back button disappearing on occasion. https://www.dropbox.com/s/xqjiaggjcv4mz5t/TransitionIssues.mov?dl=0

**Comment by andreground** [comment] 2015-09-11 18:15
@sean-hill ionic lib update does not upgrade to 1.1.0
I'll update it manually and let you know how it goes!

$ ionic lib update
bower ionic#1.0.1               cached git://github.com/driftyco/ionic-bower.git#1.0.1
bower ionic#1.0.1             validate 1.0.1 against git://github.com/driftyco/ionic-bower.git#1.0.1

**Comment by perrygovier** [comment] 2015-09-11 18:29
@sloops77, do you have a code sample you can share? Does it help to upgrade to 1.1?

**Comment by sean-hill** [comment] 2015-09-11 19:14
Hey everyone, so the shim fixed my tabs flashing and such, but the `hide-nav-bar="true"` seems to not work as well. If I'm on a tab view with `hide-nav-bar="true"` and then switch to another tab view where I display the navbar, scroll a bit, go back to the tab view without the navbar, then go back, the navbar stays hidden. Below is a video:

https://dl.dropboxusercontent.com/u/97539058/Bugs/fail5.mov
In this video you can also notice that the Status Bar flickers a bunch, but that's a separate problem.

**Comment by IgorMinar** [comment] 2015-09-11 22:51
I've just pushed v1.1.0 of the patch: https://gist.github.com/IgorMinar/863acd413e3925bf282c

Together with the ionic team, we are no longer able to repro any flicker with this version of the patch.

Please upgrade and let us know if you see any more issues. (also make sure you are not using any other patches for this issue in addition to the v1.1.0 of the patch).

We'll land a fix in the angular master next week, so that Angular v1.4.6 doesn't need to be patched any more.

**Comment by perrygovier** [comment] 2015-09-11 22:53
Thank @IgorMinar, this appears to fix the few remaining navigation issues people were seeing. 

Thank you all for your patience with this. [Max has updated his blog post explaining the issue.](http://blog.ionic.io/ios-9-potential-breaking-change/)

Adam has also [added the patch to Ionic's nightly build](c2822e7e3e2a6d8d056428718be71a74506cc272) and it should be included automatically in projects that use it.

**Comment by sean-hill** [comment] 2015-09-11 23:30
Thanks @IgorMinar! I confirm with @perrygovier that this has resolved all my issues.

**Comment by sloops77** [comment] 2015-09-12 06:50
All good with @IgorMinar's 1.1 - thanks fellas!

**Comment by andreground** [comment] 2015-09-12 14:05
I can confirm that @IgorMinar 1.1 fixes all animation and transition issues we had!

Hint for those with navigation issues (eg. views getting back to home instead of target), remove ANY reference in your html code using the tag href="#". That's what was broking navigation in our case!

Thanks a lot for your effort guys!

**Comment by sean-hill** [comment] 2015-09-12 16:55
Just wanted to let you fellas know that my app is now "Waiting for Review". Thanks for all the hard work that went into this patch. I really appreciate it.

**Comment by mhartington** [comment] 2015-09-12 17:44
Alright since the fix is in master....I'm going to close this.
Please, if there are issue, ping us so we can take a look.

**Closed by mhartington** 2015-09-12 17:44 UTC

**Comment by 5amfung** [comment] 2015-09-12 21:13
When Angularjs 1.4.6 is out, should we update Angularjs version independent of ionic or should we wait for a new ionic version to be bundled with 1.4.6?

**Comment by mhartington** [comment] 2015-09-12 21:30
When 1.4.6 is released, we will probably look at what it takes to update ionic to work with it. I don't suspect there will any breaking changes, but I wouldn't suggest upgrading the angular version that gets bundled with ionic. Stuff may break and that would be bad :smile:

**Comment by EpoX44** [comment] 2015-09-14 10:05
I tried the fix of @IgorMinar but my problems are still there. When i click on something i still get the error message and everywhere i use $state.go sometimes the content and ion-nav-buttons flicker and then the content loads but the ion-nav-buttons and back-button are vanished.

**Comment by Delagen** [comment] 2015-09-14 11:59
@EpoX44 +1

**Comment by mhartington** [comment] 2015-09-14 12:33
@EpoX44 are you sure you have the latest patch? What version of ionic are you using?

**Comment by EpoX44** [comment] 2015-09-14 12:59
@mhartington I use 
Ionic Version: 1.0.0-rc.1
AngularJS: v1.3.13

and tried this patch https://gist.github.com/IgorMinar/863acd413e3925bf282c

What I find a little bit curious is the fact that the strange loading of a view only appears randomly. Sometimes it works and sometimes not, but I always get the error message. When the forward view loads normal i get 2 console entries of the error messages and when it loads strange (like described) I get 8.

**Comment by mhartington** [comment] 2015-09-14 13:03
Can you update to the latest 1.1 version of ionic?

**Comment by EpoX44** [comment] 2015-09-14 13:08
Yeah i'll update it and try it again. :)

**Comment by EpoX44** [comment] 2015-09-14 14:33
@mhartington so I found out why it didn't worked. I just had to remove and add the iOS platform. Now everything works fine.

Anyway thanks for the help.

**Comment by jsappme** [comment] 2015-09-17 17:48
Hello guys,

I am experiencing weird issues after upgrading to iOS9 and Xcode7. I posted this question on the forum:
http://forum.ionicframework.com/t/problem-compiling-with-xcode7-and-ios9/32644

What am I doing wrong?

Hervé

**Comment by mhartington** [comment] 2015-09-17 17:51
Did you try the comment from before? 
> I just had to remove and add the iOS platform. Now everything works fine.

**Comment by jsappme** [comment] 2015-09-17 17:54
Yes I did remove and add the iOS platform.

**Comment by jsappme** [comment] 2015-09-17 18:06
Xcode compiles and gives me this error:

```
2015-09-17 12:04:01.963 Tree The World[395:70721] App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure. Temporary exceptions can be configured via your app's Info.plist file.
2015-09-17 12:04:01.983 Tree The World[395:70553] Failed to load webpage with error: The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.```

**Comment by rajatrocks** [comment] 2015-09-17 18:09
That's a separate iOS9 issue, unrelated to this. You need to make a change to your iOS app's plist: http://ste.vn/2015/06/10/configuring-app-transport-security-ios-9-osx-10-11/

**Comment by jsappme** [comment] 2015-09-17 21:31
@rajatrocks thanks for the tip. I edit my myapp-Info.plist and it's working. But the app feels slower for some reasons.

**Comment by rajatrocks** [comment] 2015-09-17 21:41
I think the issue that caused this thread's problem is because of a delay in in iOS9's UIWebView correctly reporting the current href, and that was breaking parts of angular. I believe the fix makes the app wait until it's correctly reported. So that would make your app feel slower. Or it could be iOS 9, or Xcode 7, or any of a number of other things. 

I ended up embedding the newer WKWebView in my app using https://github.com/Telerik-Verified-Plugins/WKWebView and it works great on iOS8 and 9.

**Comment by jsappme** [comment] 2015-09-17 22:08
@rajatrocks I installed the WKWebView and remove the calls for the patch. The app compiles and starts but it gives me that blank page again.

**Comment by rajatrocks** [comment] 2015-09-17 22:37
You need to install v0.6.0, don't know if that's the current one. Beyond that, I can't really help you. 
cordova plugin add https://github.com/icenium/cordova-plugin-webserver.git
cordova plugin add https://github.com/Telerik-Verified-Plugins/WKWebView.git#0.6.0

**Comment by jsappme** [comment] 2015-09-17 23:02
@rajatrocks I followed your instructions and the apps worked very good and very fast the first time I launched it. But something very weird happen after. Every time I tried to run the app again (from Xcode or Ionic run command) I keep getting the error message "ERROR: Start Page at 'http://192.168.0.100:8100' was not found." and the app does not work again. Any idea why?

**Comment by rajatrocks** [comment] 2015-09-17 23:05
Sorry, no idea...

**Comment by eplicanic** [comment] 2015-09-18 01:59
@jsappme did you try editing your config.xml so this line looks like this: <access origin="*"/>

**Comment by jsappme** [comment] 2015-09-18 18:21
@eplicanic yes my config.xml is good.
