### ISSUE TITLE
Ionic v2 - Tutorial App - Uncaught (in promise) TypeError: object is not a constructor

### ISSUE THREAD

**Issue by tonyawad88** [driftyco/ionic#5848] opened 2016-03-15 15:08 UTC
#### Short description of the problem:
There is an uncaught error that started showing up in Chrome Version 49.0.2623.87 m. Not sure where the source of the error is coming from. The app still runs normally.

Uncaught (in promise) TypeError: object is not a constructor(…)                      undefined:1

#### What behavior are you expecting?
No console errors.

**Steps to reproduce:**
1. ionic start ProjectName tutorial --v2 --ts
2. cd ProjectName
3. ionic serve

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 Uncaught (in promise) TypeError: object is not a constructor(…)                      undefined:1

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
```
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
OS: Windows 7 SP1
Node Version: v4.2.4
```

**Comment by iignatov** [comment] 2016-03-15 18:03
This is a duplicate of issue #5175.

**Comment by jgw96** [comment] 2016-03-15 20:11
Hello @tonyawad88 ! I would recommend checking out #5175 for more info on this issue! Since that issue is a duplicate of this one i will be closing this issue. Please reopen it if need be!

**Closed by jgw96** 2016-03-15 20:11 UTC
Labels: v2
