### ISSUE TITLE
bug: Datetime min property needs max to work properly

### ISSUE THREAD

**Issue by ThibaultBrugg** [driftyco/ionic#10502] opened 2017-02-20 11:16 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>http://codepen.io/anon/pen/wgLXPa

When max is not added the minimum date is not set to the 20th of February but to the 20th of January.
Even with 2017-03-20 or any other month, the minimum date is set to the  20th of January

when a max date is added it starts to work properly

PS: I tested this in Chrome console with an Android emulater, iPhone emulator and Windows emulator</span>

<span is-issue-template></span>

**Comment by jgw96** [comment] 2017-02-21 20:37
Thanks, we will look into this.

**Comment by topalavlad** [comment] 2017-02-27 20:38
This is happening because if max is not set, the default value is current year and null for all other values (month, day, ...)
This ends up evaluating (datetime.ts.calcMinMax(...)):
```
if (min.month > max.month) { //true if max.month is null
    min.month = 1;
```
and forcing the min.month to 1.

This should be easy to fix by feeding an actual date instead of year.toString() both for min and max values. 

My only question is if using the current year for max is something chosen on purpose or it should be current date + 100 years (similar to minimum which is current - 100 years)

**Comment by manucorporat** [comment] 2017-03-06 23:46
@topalavlad  can you provide a `<ion-datetime>` that reproduces the issue? please explain what you would expect instead.

**Comment by topalavlad** [comment] 2017-03-07 07:29
Not sure if I'm following, but the codepen in the initial comment does reproduce the issue:

> Even with 2017-03-20 or any other month, the minimum date is set to the 20th of January

The month is always set to January if max.year is missing.

**Comment by manucorporat** [comment] 2017-03-16 17:44
I made a lot of improvements to datetime, I think it is fixed now, but without your PR... that's a lot anyway. We expect to release next week, please let me know if the problem was finally resolved.

**Closed by manucorporat** 2017-03-16 17:44 UTC
Labels: v2
