### ISSUE TITLE
Infinite scroll with tap events dose't working. Android.

### ISSUE THREAD

**Issue by klochko7** [driftyco/ionic#11354] opened 2017-04-25 09:48 UTC
Hi all ! Could someone suggest please .. how to fix this ?

```
<ion-content padding>
  <ion-list class="list_models">
    <button ion-item *ngFor="let model of models;let i = index;" (click)="clickModel(model.external_id,model.description)" id={{model.external_id}} (press)="tapEvent($event,model.external_id)>
      <ion-label>{{model.description}}</ion-label>
      <ion-icon name="arrow-forward" item-right></ion-icon>
      <ion-icon name="build" item-left><span class="count_models">{{i+1}}</span></ion-icon>
      <ion-icon *ngIf="model.zip==0" name="download" item-left></ion-icon>
    </button>
  </ion-list>
  <ion-infinite-scroll *ngIf="hasMoreData" (ionInfinite)="doInfinite($event)">
    <ion-infinite-scroll-content
      loadingSpinner="bubbles"
      loadingText="Loading more data...">
    </ion-infinite-scroll-content>
  </ion-infinite-scroll>
</ion-content>
```

**Comment by jeromeXoo** [comment] 2017-04-25 12:20
Similar to #11112 

scroll not working with gesture events

**Comment by jgw96** [comment] 2017-04-25 14:16
Hello all! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/11112.

**Closed by jgw96** 2017-04-25 14:16 UTC
