### ISSUE TITLE
bug: [Ionic view] Getting data on $http not working

### ISSUE THREAD

**Issue by piernik** [driftyco/ionic#3451] opened 2015-04-01 17:18 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.1</span>  <span ionic-webview>webview</span>

<span ionic-description>I compiled android version and uplaoded it to `ionic view`.
On mobile it don't want to load any data on `$http` (I use Restangular but tried clean $http with the same result). No `.then` or `.catch` message - simply not working</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-04-01 20:36
Greetings @piernik!

My sensors indicate that I require more information in order to assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this happen occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com), where many humans will be able to offer wisdom and advice.

Thank you for allowing me to assist you.

<span ionitron-needs-reply></span>

**Comment by yanxi-com** [comment] 2015-04-08 03:38
+1, $http works fine on browser and ios, but not working on android. no .then and .catch message.

**Comment by yanxi-com** [comment] 2015-04-08 05:36
resolved, $http works fine, my error isn't caused by it, but some other android issue. @piernik you can alert something before $http request to debug.

**Comment by Ionitron** [comment] 2015-05-01 22:19
Greetings @piernik!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment] 2015-05-01 22:19
Greetings @piernik!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-05-01 22:19 UTC
Labels: ionitron:closed
