### ISSUE TITLE
bug: ion-slide set initialSlide not work immediately

### ISSUE THREAD

**Issue by ghost** [driftyco/ionic#9138] opened 2016-11-13 13:32 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>On this issue, perhaps I did not describe very clearly。
When I want to change initialSlide in the constructor, but it's still default value, then change to value what I set.

home.ts
```ts
export class HomePage {
  images = IMAGES;
  constructor(public navCtrl: NavController) { }
  selectImg(index){
    this.navCtrl.push(SlidesPage,{selectImgIndex:index},{animate:false})
  }
}
export const IMAGES = [
    {url:'assets/img/1.jpg'},
    {url:'assets/img/2.jpg'},
    {url:'assets/img/3.jpg'},
    {url:'assets/img/4.jpg'},
    {url:'assets/img/5.jpg'},
    {url:'assets/img/6.jpg'},
]

home.html

<ion-header>
  <ion-navbar>
    <ion-title>Home</ion-title>
  </ion-navbar>
</ion-header>
<ion-content padding>
  <ion-grid >
    <ion-row wrap>
      <ion-col width-33 *ngFor="let image of images let i=index" >
          <img [src]="image.url" (click)="selectImg(i)">
      </ion-col>
    </ion-row>
  </ion-grid>
</ion-content>

slides.ts

export class SlidesPage {

  slides = [];
  mySlideOptions = {
	initialSlide:0,
	pager:true,
	spaceBetween:10,
  };

  constructor(public navCtrl: NavController,params:NavParams) {
    let index = params.get("selectImgIndex");
	this.slides = IMAGES;
	this.mySlideOptions.initialSlide = index;
  }
  goBack(){
    this.navCtrl.pop({animate:false});
  }
}
```
slides.html
```html
<ion-content class="img-slide" padding>
  <ion-slides #mySlider [options]="mySlideOptions" (click)="goBack()">
    <ion-slide *ngFor="let slide of slides">
      <img [src]="slide.url" class="slide-image" />
    </ion-slide>
  </ion-slides>
</ion-content>
```
Forgive my poor English</span>

<span is-issue-template></span>

**Comment by AleFons** [comment] 2016-12-23 11:08
I'm on RC4 and I can confirm that this bug exists; when you set a specific initialSlide in the options, the slides load the slide at index 0 and then switches to the slide at the index set on initialSlide.

I made a post about it on the forums [here](https://forum.ionicframework.com/t/ion-slides-starts-at-index-0-then-swaps-to-initialslide-slide/74128/1) which contains an example repo with the bug happening.

**Comment by brandyscarney** [comment] 2017-02-24 20:38
I'm going to close this since it's a duplicate of #7595 and that has been fixed, but please let me know if you're still having the issue and I'll reopen. Thanks!

**Closed by brandyscarney** 2017-02-24 20:38 UTC
Labels: v2

**Comment by ravi-pandit14** [comment] 2017-11-24 05:17
initialSlide=1  is not showing in my code 
and if i use <ion-slides #mySlider [options]="mySlideOptions" > then its throw error
{error:  Template parse errors:
Can't bind to 'options' since it isn't a known property of 'ion-slides'.
1. If 'ion-slides' is an Angular component and it has 'options' input, then verify that it is part of this module.}
