### ISSUE TITLE
Uncaught TypeError: undefined is not a function from item-sliding-gesture.js

### ISSUE THREAD

**Issue by stalniy** [driftyco/ionic#9851] opened 2017-01-03 13:39 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Exception is thrown on Android 5. And item sliding doesn't work

**Expected behavior:**
item sliding doesn't works 

**Steps to reproduce:**
1. Create ion-list with ion-item-sliding inside
2. Run build on Android 5

**Other information:**
The issue due to usage of DOM `closest` method which is not available in that version of Android: http://caniuse.com/#feat=element-closest

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: OS X El Capitan
Node Version: v6.2.1
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment] 2017-01-03 15:28
Hello, thanks for opening an issue with us! Could you post the exception that gets thrown? In Android 5.0 the webview is chrome is updated just like chrome the browser on that device. This means that the webview is running the latest stable version of chrome (55) which does support the `closest` dom method.

**Comment by stalniy** [comment] 2017-01-03 19:15
Strange, I will recheck information on Android device tomorrow and will post more info about it. But the issue is definitely in `closest` method. When I added polyfill, the issue disappeared

**Comment by jgw96** [comment] 2017-01-03 22:39
@stalniy sounds good. Also, would you mind checking that your loading in `polyfills.js` in your index.html? Thanks!

**Comment by stalniy** [comment] 2017-01-04 11:00
yes, the issue is that I was not aware that I need to include `polyfill.dom.js` file for ionic. Is this mentioned somewhere?

**Comment by jgw96** [comment] 2017-01-09 16:03
Hey @stalniy, polyfills.dom.js is included by default in polyfills.js. Would you be able to  post a repo i can reproduce this issue with? Unfortunately i cannot reproduce this issue on any of my devices.

**Comment by jgw96** [comment] 2017-01-24 15:47
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-01-24 15:47 UTC
Labels: needs reply, v2
