### ISSUE TITLE
bug: jquery prevent the collection-repeat scroll inertia

### ISSUE THREAD

**Issue by KNedelec** [driftyco/ionic#3060] opened 2015-02-09 14:29 UTC
jQuery loaded before ionic make the scroll to loose its inertia. If loaded after, the scroll is great :)

I forked the collection-repeat codepen and just included jquery: http://codepen.io/KNedelec/pen/gbXEPy

**Comment by Ionitron** [comment] 2015-02-09 14:29
Greetings @KNedelec!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3060). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3060)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by adamdbradley** [comment] 2015-02-10 13:41
Duplicate of https://github.com/driftyco/ionic/issues/2297

**Closed by adamdbradley** 2015-02-10 13:41 UTC
