### ISSUE TITLE
iframe BUG

### ISSUE THREAD

**Issue by gitHubLie** [driftyco/ionic#5727] opened 2016-03-05 06:54 UTC
#### Short description of the problem:
    Use iframe click a label after scroll automatic to top  fro ios 9.2?
 help me !!!!

#### What behavior are you expecting?

.iframe-wrapper {
   position: fixed;
    -webkit-overflow-scrolling: touch;
    overflow: scroll;

    iframe {
      height: 100%;
      width: 100%;
    }
 }

  <ion-content scroll="true" overflow-scroll="true" class="iframe-wrapper">
     <iframe id="targetFrame" data-tap-disabled="true" ng-src="{{myURL}}" style="opacity:0"></iframe>
  </ion-content>

**Steps to reproduce:**
1. 
2. 
3. 

```
insert any relevant code between the above and below backticks
```

**Ionic Version**: 1.x / 2.x

**Browser & Operating System**: iOS / Android / Chrome

**Run `ionic info` from terminal/cmd prompt:**

```
paste output from `ionic info` here
```

**Comment by rogercorrea** [comment] 2016-03-10 23:31
Don't work for me.

Your system information:

Cordova CLI: 6.0.0
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS: Distributor ID:	Debian Description:	Debian GNU/Linux 8.3 (jessie) 
Node Version: v0.12.10

iOs 9.2.1 with Ionic View

**Comment by jgw96** [comment] 2016-03-29 14:56
Hello! Thanks for opening an issue with us! Are you still experiencing this issue?

**Comment by rogercorrea** [comment] 2016-04-01 02:07
Yes.
I tested using Ionic View but I saw after that he don't support some plugins.
But I also tested on Android emulator and the iframe bug continued.

The iframe back to the beginning or even crashes when I touch on the page to scroll the screen.
Also not open this link inside the iframe page.

**Comment by jgw96** [comment] 2016-04-04 19:10
Hey @rogercorrea ! Sorry, been thinking on this issue and i have a question. Is your iframe taking up the whole viewport?

**Comment by gitHubLie** [comment] 2016-04-10 08:41
this is IONIC BUG ?  i will crazy.

**Comment by jgw96** [comment] 2016-04-11 14:22
@gitHubLie Would you mind creating a plunker we can use to reproduce your issue? Also what version of ionic are you using?

**Comment by gitHubLie** [comment] 2016-04-12 06:18
1.7.10

**Comment by gitHubLie** [comment] 2016-04-12 06:20
@jgw96  ok ,you want close just new question?

**Comment by gitHubLie** [comment] 2016-04-12 06:20
@jgw96     INOIC  1.7.10

**Comment by jgw96** [comment] 2016-05-05 17:10
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment] 2016-05-10 14:06
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-05-10 14:06 UTC
Labels: needs reply, platform:android, platform:ios, v1
