### ISSUE TITLE
Hang on ionic serve with ionic-app-scripts 0.0.37-2

### ISSUE THREAD

**Issue by morrisonbrett** [driftyco/ionic#8920] opened 2016-10-26 18:49 UTC
Hang on ionic serve with ionic-app-scripts 0.0.37-2.

Using recommended package.json but with 0.0.37-2

Output from ionic serve:

```
D:\dev\mckissock\mckissock-mobile>npm run watch

> mckissockmobile@ watch D:\dev\mckissock\mckissock-mobile
> ionic-app-scripts watch

[11:45:01]  ionic-app-scripts 0.0.37-2
[11:45:01]  watch started ...
[11:45:01]  build dev started ...
[11:45:01]  clean started ...
[11:45:01]  clean finished in 7 ms
[11:45:01]  copy started ...
[11:45:01]  transpile started ...
[11:45:02]  lint started ...
[11:45:06]  lint finished in 4.05 s
[11:45:07]  transpile finished in 5.84 s
[11:45:07]  webpack started ...
[11:45:07]  copy finished in 6.06 s
[11:45:19]  webpack finished in 12.10 s
[11:45:19]  sass started ...
[11:45:22]  sass finished in 2.80 s
[11:45:22]  build dev finished in 20.79 s
```

Hangs and doesn't return.

Running on Windows 10

```
D:\dev\mckissock\mckissock-mobile>ionic info
--------------------------------
--------------------------------

Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 1.2.2
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.37-2
OS:
Node Version: v6.9.1


--------------------------------

D:\dev\mckissock\mckissock-mobile>
```

**Comment by morrisonbrett** [comment] 2016-10-26 22:12
Also hangs on Ubuntu 16.04.1.  Here's the output:

```
morrison@vm-ubuntu:~/dev/mckissock-mobile$ ionic info
--------------------------------
--------------------------------

Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.37-2
OS: Distributor ID:     Ubuntu Description:     Ubuntu 16.04.1 LTS 
Node Version: v6.9.1


--------------------------------
morrison@vm-ubuntu:~/dev/mckissock-mobile$ ionic serve

Running 'serve:before' npm script before serve

> mckissockmobile@ watch /home/morrison/dev/mckissock-mobile
> ionic-app-scripts watch

[15:11:10]  ionic-app-scripts 0.0.37-2 
[15:11:10]  watch started ... 
[15:11:10]  build dev started ... 
[15:11:10]  clean started ... 
[15:11:10]  clean finished in 6 ms 
[15:11:10]  copy started ... 
[15:11:10]  transpile started ... 
[15:11:11]  lint started ... 
[15:11:14]  lint finished in 3.17 s 
[15:11:15]  transpile finished in 4.79 s 
[15:11:15]  webpack started ... 
[15:11:15]  copy finished in 5.00 s 
[15:11:28]  webpack finished in 12.53 s 
[15:11:28]  sass started ... 
[15:11:30]  sass finished in 2.32 s 
[15:11:30]  build dev finished in 19.66 s 

```

**Comment by morrisonbrett** [comment] 2016-10-26 23:02
Just tried on macOS, and it works.  0.0.37-2 does not hang on macOS.

```
vm-osx:mckissock-mobile morrison$ ionic info 
--------------------------------
--------------------------------

Your system information:

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.37-2
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X Yosemite
Node Version: v6.9.1
Xcode version: Xcode 7.0 Build version 7A220 


--------------------------------
******************************************************
 Dependency warning - for the CLI to run correctly,      
 it is highly recommended to install/upgrade the following:     

 Install ios-sim to deploy iOS applications.`npm install -g ios-sim` (may require sudo)
 Install ios-deploy to deploy iOS applications to devices.  `npm install -g ios-deploy` (may require sudo)

******************************************************
vm-osx:mckissock-mobile morrison$ ionic serve

Running 'serve:before' npm script before serve

> mckissockmobile@ watch /Users/morrison/dev/mckissock-mobile
> ionic-app-scripts watch

[16:01:22]  ionic-app-scripts 0.0.37-2 
[16:01:22]  watch started ... 
[16:01:22]  build dev started ... 
[16:01:22]  clean started ... 
[16:01:22]  clean finished in 7 ms 
[16:01:22]  copy started ... 
[16:01:22]  transpile started ... 
[16:01:23]  lint started ... 
[16:01:26]  lint finished in 3.01 s 
[16:01:27]  transpile finished in 5.17 s 
[16:01:27]  webpack started ... 
[16:01:28]  copy finished in 5.51 s 
[16:01:42]  webpack finished in 14.70 s 
[16:01:42]  sass started ... 
[16:01:44]  sass finished in 2.16 s 
[16:01:44]  build dev finished in 22.06 s 
[16:01:46]  watch ready in 23.89 s 
Running live reload server: http://192.168.198.128:35729
Watching: www/**/*, !www/lib/**/*, !www/**/*.map
âˆš Running dev server:  http://192.168.198.128:8100
Ionic server commands, enter:
  restart or r to restart the client app from the root
  goto or g and a url to have the app navigate to the given url
  consolelogs or c to enable/disable console log output
  serverlogs or s to enable/disable server log output
  quit or q to shutdown the server and exit

ionic $ q
vm-osx:mckissock-mobile morrison$ 

```

**Comment by cleever** [comment] 2016-10-27 11:12
Until this issue https://github.com/driftyco/ionic-app-scripts/issues/246 get fixed. You should verify if you have a manifest.json file inside your src/foder. If not, you must create the file.

**Comment by jgw96** [comment] 2016-10-27 18:17
Hello, thanks for opening an issue with us! I am going to close this issue as a duplicate of the app-scripts issue linked above.

**Closed by jgw96** 2016-10-27 18:17 UTC

**Comment by morrisonbrett** [comment] 2016-10-27 19:05
I moved manifest.json from where I had it to the root of src and can confirm no longer hanging on 0.0.37-2.
