### ISSUE TITLE
bug: ion-nav-title does not work properly

### ISSUE THREAD

**Issue by aelx311** [driftyco/ionic#3464] opened 2015-04-02 20:57 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>I need to update view title dynamically. Say I am using the same view for New and Edit a contact. So I would like to show 'New Contact' and 'Edit Contact' depending on the condition.

I am using <b><ion-nav-title>{{viewTitle}}</ion-nav-title></b> and it is tied to <b>$scope.viewTitle</b> in my controller.

In iOS, view title is stacked on the left nav buttons
![stackviewtitle1](https://cloud.githubusercontent.com/assets/3267257/6973527/15f01ff6-d951-11e4-82b4-4a2d9c7a7138.PNG)

 and when going back to the same view for second time, the view title disappears.
![stackviewtitle2](https://cloud.githubusercontent.com/assets/3267257/6973533/1db8c01c-d951-11e4-90a9-f7d0f812d324.PNG)

 I tried to update the value when receiving <b>$ionicView.beforeEnter</b>, <b>$ionicViewEnter</b> and <b>$ionicView.loaded</b> events but it is still the same.
</span>

<span is-issue-template></span>

**Comment by mhartington** [comment] 2015-04-03 15:42
Anyway you could replicate this in a simplified codepen?

**Comment by aelx311** [comment] 2015-04-06 14:45
@mhartington 
http://codepen.io/anon/pen/PwvpNx

I am using Google Chrome in device mode. The issue only appears when I choose Apple devices. Not sure how to do that in codepen.

**Comment by aelx311** [comment] 2015-04-06 20:35
@mhartington I comment out css[ionic.CSS.TRANSFORM] for 'back-text' and 'title' in provider.transitions.navBar.ios. Not sure what are the side effects but it is behaving correctly.

**Comment by nativeapps** [comment] 2015-04-08 22:02
@aelx311 can you explain what you did please. thank you

**Comment by aelx311** [comment] 2015-04-09 15:51
@nativeapps I comment out these two lines in ionic.bundle.js
![image](https://cloud.githubusercontent.com/assets/3267257/7070726/59203432-dea6-11e4-9f68-001e03f18374.png)

**Comment by mhartington** [comment] 2015-04-10 16:41
Not seeing this in the nightly builds. Wasn't seeing it either in the codepen emulating ios

**Comment by aelx311** [comment] 2015-04-10 19:06
@mhartington 
As you can see, when I click '+' button at the top right, 'New Contact' does not show up. When clicking the back button, it seems that 'New Contact' appears for a very short time before the transition is completed.

In another case, when I click 'Edit' button, 'Edit Contact' is stacked with the back button on the left. When clicking the back button, again there is an animation going on before the transition is completed.

I tested these with nightly builds.
![screencapture_4-10-2015_1](https://cloud.githubusercontent.com/assets/3267257/7094795/4b9b21b6-df8a-11e4-93f6-8007d09719dc.gif)

**Comment by mhartington** [comment] 2015-04-10 19:11
Can you shoot me an email, mike at drifty dot com? 
I'd like to look at the project and see what the issue is.

**Comment by JoeKomputer** [comment] 2015-05-05 15:49
I've had a similar problem but it seemed to only apply when using $ionicConfig.views.transition('android'); When you use $ionicConfig.views.transition('ios'); the problem was fixed.

**Comment by Ionitron** [comment] 2015-05-14 00:19
Greetings @aelx311!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment] 2015-05-14 00:19
Greetings @aelx311!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-05-14 00:19 UTC
Labels: ionitron:closed
