### ISSUE TITLE
Sidemenu Gray Square

### ISSUE THREAD

**Issue by jbw91** [driftyco/ionic#8923] opened 2016-10-27 06:37 UTC
#### Short description of the problem:

When you open up the sidemenu then close it, a gray square appears in the upper-left corner. Here's a screenshot of the issue: 

![screenshot_20161027-001921](https://cloud.githubusercontent.com/assets/5883616/19756755/1a02aa92-9bdc-11e6-9273-79bec3ef2d5d.png)

This issue was reported on #6416 but was closed on Aug 22. Despite multiple comments over the course of two months it's still a problem, the issue remains closed and not looked at.

#### What behavior are you expecting?

I'm expecting to not have that gray box there when you toggle the menu. It makes the app look non-native, which hurts the case for Ionic.

**Steps to reproduce:**
1. Start the tutorial project.
```shell
$ ionic start MyIonic2Project tutorial --v2
```
2. Run it on a device using `ionic run android --device`.
3. Navigate to the My First List page and notice the gray square in the upper-left corner. 

**Which Ionic Version?** 1.x or 2.x

Ionic 2

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.3.1
Gulp version:  CLI version 1.2.2
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.36
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X Sierra
Node Version: v6.7.0
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by hdsnet** [comment] 2016-10-27 07:40
+1 Same here, it's still there.

**Comment by manueltaber** [comment] 2016-10-27 10:03
+1 Same here

**Comment by MartineNavara** [comment] 2016-10-27 12:49
+1 same here

**Comment by jgw96** [comment] 2016-10-27 18:20
Hello, thanks for using Ionic! I am going to close this one as a duplicate of https://github.com/driftyco/ionic/issues/6416.

**Closed by jgw96** 2016-10-27 18:20 UTC
