### ISSUE TITLE
swipe to go back in a view that has <ion-input> does not work correctly.

### ISSUE THREAD

**Issue by luisbahamonde** [driftyco/ionic#11506] opened 2017-05-04 07:07 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
If we make the swipe to go back in a view with <ion-input> it stays stopped as soon as you release and the transition from one view to another does not end.
This only happens when we start the gesture from the <ion-input>, if we swipe from the same view but from a point that we do not touch the <ion-input> works correctly.

**Expected behavior:**
When we make swipe to go back should change from one view to another and not stay in the middle.

**Steps to reproduce:**
Enter a view that has <ion-input> and swipe to go back, but you have to do it right from the <ion-input>

**Other information:**

![ezgif-2-d7cd4d9375](https://cloud.githubusercontent.com/assets/7839458/25693104/82264cd6-30a7-11e7-9ee8-1a0f7a5f0b3c.gif)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 3.1.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.1
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: macOS Sierra
Node Version: v4.4.2
Xcode version: Xcode 8.3.2 Build version 8E2002
```

**Comment by jgw96** [comment] 2017-05-04 15:08
Hello, thanks for opening an issue with us. Would you be able to make a minimal repo we can use to reproduce this issue?

**Comment by jgw96** [comment] 2017-05-09 18:12
Hello! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-05-09 18:12 UTC
Labels: needs info, v2
