### ISSUE TITLE
Ion-tabs not displaying in Android 4.4 kitkat

### ISSUE THREAD

**Issue by Ghayyas** [driftyco/ionic#7604] opened 2016-08-08 12:49 UTC
Hello, recently I just Upgrade my Ionic 2 project from beta 10 to beta 11. But Its having problem with its tabs.. 
I Have tabs on bottom.. On browser It Display tabs and Samasung Galxy s5 (Android 5.0) but It not showing tabs on my android 4.4 kitkat.. When I click on my tab I navigates me to that page but is Shows white blank screen on tabs bar..

**Comment by shamrozwarraich** [comment] 2016-08-08 18:06
samee :/ update to beta 11 and tab hide ... bt it work white area appear at tab places...

**Comment by bushev** [comment] 2016-08-08 19:51
The same for me.

**Comment by shamrozwarraich** [comment] 2016-08-09 13:41
any soluction....  @bushev  @Ghayyas  ??/

**Comment by jgw96** [comment] 2016-08-09 13:51
Hello all! Would you all mind telling me exactly which version of Android the tabs are not showing on?

**Comment by bushev** [comment] 2016-08-09 13:55
@jgw96 Hello! I have tested Android **4.4.4**

I'm not sure, related that or not, but I have found one more problem with UI: https://github.com/driftyco/ionic-conference-app/issues/223

**Comment by Ghayyas** [comment] 2016-08-09 13:56
Hi Im having this issue on android 4.4 kitkat.

**Comment by jgw96** [comment] 2016-08-09 13:58
@Ghayyas @bushev thanks! @Ghayyas is it 4.4.4 or 4.4.2?

**Comment by Ghayyas** [comment] 2016-08-09 14:04
@jgw96 I have android 4.4.2

**Comment by pskhodad** [comment] 2016-08-09 15:19
Same here on 4.4, I could see it happening when I have side-menu + tabs, similar to that in conference app

**Comment by danbucholtz** [comment] 2016-08-09 15:57
Hello all,

I am not seeing this issue.  Can you try running the following command and seeing if it resolves the issue:

`ionic plugin add cordova-plugin-crosswalk-webview`

Thanks,
Dan

**Comment by bushev** [comment] 2016-08-09 18:47
@danbucholtz Hello! As for me it doesn't work with my app, crosswalk make the app 6 times bigger but now I can't see any icon or text inside my app:

![image](https://cloud.githubusercontent.com/assets/7535766/17529134/c9c6db00-5e7a-11e6-8fbc-1807c24219f4.png)

**Comment by bushev** [comment] 2016-08-09 19:08
@danbucholtz the same for conference app.

Steps to reproduce:

1. Check out ionic-conference-app
2. `ionic plugin add cordova-plugin-crosswalk-webview`
3. `ionic build android --release`
5. Sing app and upload to Samsung Galaxy S5 - 4.4.4 - API 19 - Genymotion.
6. See only blank (white) screen after splash

**Comment by danbucholtz** [comment] 2016-08-09 19:55
I can't speak to your apps, but I can recreate this issue by removing crosswalk from the conference app.

Assigning to beta 12.

Thanks,
Dan

**Comment by jgw96** [comment] 2016-08-09 20:45
Hello all! So we have tested this with crosswalk on a moto g running android 4.4.2 and cannot reproduce the issue. I would recommend re-cloning the conference app, running `npm install`, add crosswalk with `ionic plugin add cordova-plugin-crosswalk-webview`  and then run `ionic run android`. Also, make sure you completely uninstall the app from your device too. @bushev i would also recommend testing with a real device if possible and not genymotion. Thanks evereyone!

**Comment by bushev** [comment] 2016-08-09 21:28
@jgw96 

So, Android 4.4.2 (4.4.4) is supported with crosswalk only? That means all apps that use tabs should include crosswalk and be ~30mb in size?

**Comment by jgw96** [comment] 2016-08-09 21:38
@bushev could you try my above steps but without crosswalk please? Thanks!

**Comment by bushev** [comment] 2016-08-09 22:26
@jgw96 

Okay, my test results:

### Latest ionic-conference-app
1. git clone https://github.com/driftyco/ionic-conference-app.git && cd ionic-conference-app
2. npm i && ionic run android


**Result:** I can see the white screen only


### ionic-conference-app with beta10 (https://github.com/driftyco/ionic-conference-app/commit/5ec378dbc58c611160e3522505de4ac99a331697) 
1. git checkout 5ec378dbc58c611160e3522505de4ac99a331697 .
2. Strict ionic beta version to 10 (remove "^")
3. rm -rf node_modules && npm i && ionic run android


**Result:** Application works great

**Comment by bushev** [comment] 2016-08-09 22:55
2 builds attached.



[android-debug-10.apk.zip](https://github.com/driftyco/ionic/files/410026/android-debug-10.apk.zip)
[android-debug-11.apk.zip](https://github.com/driftyco/ionic/files/410025/android-debug-11.apk.zip)

**Comment by Ghayyas** [comment] 2016-08-10 13:07
I have Android 4.4... When i login it show tabs. when I select any tab it hides the tab and shows white blank screen on tabs.. It only happens in Android 4.4, I have tested in browser and  Android 5.0 and Iphone.. I works fine but not in my android 4.4 :(

**Comment by shamrozwarraich** [comment] 2016-08-11 11:30
@ghayyas @bushev hiii
tab work for me 
 am removing the platform android and update it to 5.2.1 and then add the platform and run its working tabs shown ...
4.4kitkat

**Comment by jgw96** [comment] 2016-08-11 14:24
Hello @Ghayyas and @bushev ! We are still having trouble reproducing this issue. Would you mind checking what version of Cordova your project is using? `ionic info` should tell you. Thanks!

**Comment by Ghayyas** [comment] 2016-08-11 14:31
Your system information:

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.35
Ionic App Lib Version: 2.0.0-beta.19
ios-deploy version: Not installed
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.4.5
Xcode version: Xcode 7.3 Build version 7D175

**Comment by Ghayyas** [comment] 2016-08-11 14:34
Also It someTimes Blinks Loading.. LoadingCtrl

**Comment by bushev** [comment] 2016-08-12 08:08
@jgw96 Hello! I have tested latest Cordova and Android platform 5.2.1

Unfortunately with the same result.

There is a short video demonstrates how it was: https://youtu.be/5a1j-CRBUFA

**Comment by oliviercherrier** [comment] 2016-08-20 07:54
Hello,

I have got the same issue on Android 4.4 (Samsung Galaxy S3 and Galaxy Tab)

Ionic Info:
Cordova CLI: 6.3.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
OS: Windows 7 SP1
Node Version: v4.4.7

Can you give us update about the resolution of this issue?

Thank you for your help,
Olivier.

**Comment by F1ow** [comment] 2016-08-23 10:25
Hi, I'm having the same issue on iOS 8.x

Ionic Info:
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v4.4.5
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by guidux** [comment] 2016-08-23 21:20
Hi, I am having the same issue on Android 4.4.2 (samsung s5 mini) and 4.4.4 (genymotion).

I downloaded the latest code of ionic-conference-app and after playing with its css attributes I was able to display the tab by changing the inline css attribute of "ion-tabbar"  bottom: 0; to a 2px but when changing to another tab the tab bar vanishes again till go back. I spent many hours to try to find out the root cause and a possible work around. but I couldn't. 

I also upload a [youtube video](https://www.youtube.com/watch?v=-THH2nr5xZ4) to show the behaviour.

Additionally I left my ionic info: 

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: Not installed
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.12.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by st1s** [comment] 2016-09-03 23:26
same here

Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
OS:
Node Version: v4.4.3

**Comment by st1s** [comment] 2016-09-04 00:38
[Conference App](https://github.com/driftyco/ionic-conference-app/tree/436b18f9651c87370f15ff047d708ec0bb3cc763)  - Android 4.4.2 - samsung galaxy s4 mini

tabs doesn't appear 

![14218068_1208967615834129_410809317_n](https://cloud.githubusercontent.com/assets/719763/18228286/468b1f6e-721e-11e6-987a-0644003f14bb.png)


but appears in detail 

![14159210_1208967542500803_1565410163_n](https://cloud.githubusercontent.com/assets/719763/18228284/32e841bc-721e-11e6-964e-3d8a375fd971.png)

**Comment by rigobertomolina** [comment] 2016-09-16 02:13
Any reason for why this isn't working? It's pretty weird.

**Comment by jgw96** [comment] 2016-09-17 06:47
Happy to say that after testing of beta.12 today this issue seems to be fixed. Tabs are working perfectly on Android 4.4.2 and up. Thanks everyone for using Ionic!

**Comment by AbuHani** [comment] 2016-10-09 21:54
still have the same issue in the latest release v2.0.0-rc.0 ! when using tabs with side menu.

**Comment by AbuHani** [comment] 2016-10-09 22:29
i fix it by set z-index: -1;

```
ion-nav, ion-tab, ion-tabs {
z-index: -1;
}
```

**Comment by johnofkorea** [comment] 2016-10-10 04:46
@AbuHani Thank you so much!! You are my hero!! 

I don't understand why setting z-index to -1, not 1 solves this problem.

However, I cannot thank you enough. Thank you so much!!!

**Comment by shamrozwarraich** [comment] 2016-10-10 04:56
i which componets are file u add this  @johnofkorea  @AbuHani 
```
ion-nav, ion-tab, ion-tabs {
z-index: -1;
}
```

**Comment by johnofkorea** [comment] 2016-10-10 05:46
@shamrozwarraich 
In my case, app/theme/variables.scss didn't work. (which is weird, though..)
The right target is in the very first page the tabs shows.
Let's say tabs shows pageA, pageB, pageC, and pageD.
If the very first page the tabs shows is pageA,
then you can add this at the bottom of "page-a.scss"

Or, to make things safe, you can add this to the bottom of all the scss files you find. :-)
Good luck, @shamrozwarraich !

**Comment by pskhodad** [comment] 2016-10-21 06:30
This seems to be regression due to https://github.com/driftyco/ionic/commit/e4bbcc667a1c8f9a1aaade9a6c7ec79b8759ef67
Reverting the change there renders the tabs just fine. 
Since issue on that commit was specific to iOS and this issue is specific to Android 4.4, we need to have solution which addresses issue on both.

**Comment by pskhodad** [comment] 2016-10-21 07:08
can this issue be re-opened so we get proper fix.

**Comment by dumparun** [comment] 2016-10-24 14:05
Appreciate a fix for this please. I do have the same problem. +1

**Comment by thendokhae** [comment] 2016-11-29 09:08
@shamrozwarraich

your solution worked for me as well, thanks

**Comment by priyeshn** [comment] 2016-11-29 17:44
it did not work for me.. Which scss file we need to put in this code

**Comment by pbreuss** [comment] 2016-12-01 15:01
I added 

ion-nav, ion-tab, ion-tabs {
z-index: -1;
}

to the file src/app/app.scss and it worked right away: tabs are showing!

Tested on:
Android 4.4.4 (Sony Xperia)

Cordova CLI: 6.3.1 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: OS X El Capitan
Node Version: v4.6.0
Xcode version: Xcode 8.1 Build version 8B62

**Comment by jgw96** [comment] 2016-12-29 21:33
Hello all! Does this still happen in rc4 ?

**Comment by cesarandreslopez** [comment] 2017-01-04 12:44
@jgw96 it does here.

**Comment by cesarandreslopez** [comment] 2017-01-04 12:48
Still a problem in rc4.

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.47
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v7.3.0
Xcode version: Not installed

@jgw96

**Comment by cesarandreslopez** [comment] 2017-01-04 15:03
Just checked rc4 in Kitkat and seems to work ok from my side.

**Comment by pbreuss** [comment] 2017-01-09 10:01
I had this issue as well on my old Android 4.4.4 test device, and now I tested it again with RC4 and the problem does not seem to happen anymore. So no fix is needed to display the tabs on Android 4.4.4.

Here is my platform:
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: OS X El Capitan
Node Version: v6.9.4
Xcode version: Xcode 8.2.1 Build version 8C1002

PS: Ionic is wonderful!

**Comment by jgw96** [comment] 2017-01-19 17:08
Hello all! Since this seems to be fixed now (you guys cannot repro and i cannot repro) I am going to close this issue for now. Thanks for using Ionic! (:

**Closed by jgw96** 2017-01-19 17:08 UTC
Labels: platform:android, v2

**Comment by wivancic** [comment] 2017-03-16 20:13
I had one page where the tab wasn't showing on Android 4.4.4

This addition fixed the problem.
Was using Ionic Framework Version: 2.0.0-rc.2


ion-nav, ion-tab, ion-tabs {
z-index: -1;
}
