### ISSUE TITLE
bug: ion-tabs getting null object reference in iOS

### ISSUE THREAD

**Issue by gdjennings** [driftyco/ionic#3207] opened 2015-03-01 09:32 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Error: null is not an object (evaluating 'tabsCtrl.$element.append')
tabSelected@http://localhost:12344/bower_components/ionic/release/js/ionic-angular.js:11052:32
$digest@http://localhost:12344/bower_components/angular/angular.js:14243:31
$apply@http://localhost:12344/bower_components/angular/angular.js:14506:31
http://localhost:12344/bower_components/angular/angular.js:11364:30
eventHandler@http://localhost:12344/bower_components/angular/angular.js:3014:25
dispatchEvent@[native code]
triggerMouseEvent@http://localhost:12344/bower_components/ionic/release/js/ionic.js:2804:20
tapClick@http://localhost:12344/bower_components/ionic/release/js/ionic.js:2793:20
tapTouchEnd@http://localhost:12344/bower_components/ionic/release/js/ionic.js:2911:13

This is blowing up my tabs on iOS build. Not predictable at the moment. I will try and isolate and reproduce or someone will tell me I am doing something stupid.</span>

<span is-issue-template></span>

**Comment by gdjennings** [comment] 2015-03-01 12:10
Not reproducible in safari. Happens in cordova using WKWebView plugin.

**Comment by gdjennings** [comment] 2015-03-03 22:27
I have got this the wrong way around. My tabs are disappearing and then tapping a link triggers this. Makes sense, but somehow, ion-tabs are being destroyed randomly.

**Comment by Ionitron** [comment] 2015-03-04 17:30
Greetings @gdjennings!

My sensors indicate that I require more information in order to assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this happen occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com), where many humans will be able to offer wisdom and advice.

Thank you for allowing me to assist you.

<span ionitron-needs-reply></span>

**Comment by Ionitron** [comment] 2015-04-03 19:58
Greetings @gdjennings!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-04-03 19:58 UTC
Labels: ionitron:closed
