### ISSUE TITLE
Navigate inside Modal cuts off Navbar on iOS

### ISSUE THREAD

**Issue by manuelroth** [driftyco/ionic#8631] opened 2016-10-11 09:47 UTC
#### Short description of the problem:

When opening a modal and navigating to a different page inside this modal the navbar gets cut off on iOS.

![Navbar cut off](https://cloud.githubusercontent.com/assets/1810384/19265834/429fa0d6-8fa7-11e6-9e75-eff1615b930c.gif)

The component which has a cut off navbar uses the ion-navbar component. I have also tried with the ion-toolbar component but the header was also cut off
```html
<ion-header>
  <ion-navbar color="primary">
    <ion-title>Umweltbedingungen</ion-title>
  </ion-navbar>
</ion-header>

<ion-content>
</ion-content>
```

#### What behavior are you expecting?

I am expecting that the navbar has the same height as on the first page. 

**Steps to reproduce:**
1. Create a modal
2. Inside the modal component navigate to a different page (push page on the navigation stack)
3. Navbar of the pushed page is cut off on iOS

**Other information:**

This problem only appears on iOS (only tested on iOS10)

**Which Ionic Version?** 1.x or 2.x
ionic2 RC0

**Comment by comfortme** [comment] 2016-10-11 11:51
duplicate of https://github.com/driftyco/ionic/issues/8151

**Comment by jgw96** [comment] 2016-10-11 16:01
Hello, thanks for opening an issue with us! I am going to close this issue as a duplicate of #8151 . Thanks!

**Closed by jgw96** 2016-10-11 16:01 UTC
