### ISSUE TITLE
Virtual Scroll redraw issue

### ISSUE THREAD

**Issue by hiroyachiba** [driftyco/ionic#6766] opened 2016-06-05 04:25 UTC
#### Short description of the problem:

When scrolling virtualScroll list on PC, part of the list remains empty.

#### What behavior are you expecting?

**Steps to reproduce:**
1. Run the plunker on PC browser.
2. Scroll down with mouse wheel rapidly.  (The issue doesn't happen when you scroll slowly.)
3. Part of the list remains empty.  When you scroll a little bit with mouse wheel, the list is drawn correctly.

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x

2.0.0-beta.7

#### Plunker that shows an example of your issue

http://plnkr.co/edit/gMQeiJE8iguDiQyKjC5T?p=preview

The items should be shown until 999, but they're not redrawn.  The items are drawn correctly if I scroll a little bit.
<img width="510" alt="sc1" src="https://cloud.githubusercontent.com/assets/6658346/15804887/5e9ecd06-2b53-11e6-9f3e-3ba4e715aa8d.png">

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.7
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v5.7.1
Xcode version: Xcode 7.3 Build version 7D175

**Comment by mpaland** [comment] 2016-06-06 20:14
I can confirm this.
Happens especially when you move the browser scroller to a certain position.

**Comment by mpaland** [comment] 2016-06-17 09:23
v2beta9 tested on desktop browsers (Edge/FF47).

Redraw is slightly better but has unfortunately still issues:
Listview is empty (not redrawn) if the browser scroll thumb is moved fast to a new position.
I guess there is a big jump in the item index then, which is not handled correctly. Moving the scroll wheel afterwards redraws the list immediately.

Please add label 'desktop' to this item.

**Comment by jgw96** [comment] 2016-06-27 21:53
Hello all! Thanks for opening an issue with us! I am going to close this issue as a duplicate of #6999 . Thanks for using Ionic!

**Closed by jgw96** 2016-06-27 21:53 UTC
Labels: v2, virtualscroll
