### ISSUE TITLE
SearchBar/navBar strange behavior!

### ISSUE THREAD

**Issue by jbertrand992** [driftyco/ionic#10776] opened 2017-03-14 21:37 UTC
[**Ionic](url) version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When I click on the "Cancel" button of "searchBar", I see the navBar (ion-tabs) in the middle of screen before keyboard closes.

**Expected behavior:**
navBar should be in the footer of screen and must be stil there during the closing of keyboard

**Steps to reproduce:**
 I illustrate this behavior with 3 pictures (3 steps) and i small movie.

For Ionic 1 issues - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=previ
<img width="294" alt="screen shot 2017-03-14 at 10 21 45 pm" src="https://cloud.githubusercontent.com/assets/26419410/23923272/4bc329b6-0906-11e7-933c-b081e569ee00.png">
<img width="322" alt="screen shot 2017-03-14 at 10 22 14 pm" src="https://cloud.githubusercontent.com/assets/26419410/23923273/4beeeaf6-0906-11e7-86bd-006b5ba9883e.png">
<img width="312" alt="screen shot 2017-03-14 at 10 22 36 pm" src="https://cloud.githubusercontent.com/assets/26419410/23923274/4bf27310-0906-11e7-9740-ce3ac3f78c37.png">

[AYQL0069.m4v.zip](https://github.com/driftyco/ionic/files/842675/AYQL0069.m4v.zip)

ew

For Ionic 2 issues - http://plnkr.co/edit/z0DzVL?p=preview
-->

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jbertrand992** [comment] 2017-03-14 21:44
the codes of this issu are:

code HTML:
-----for searchBar----
<ion-searchbar
        [(ngModel)]="searchKey"
        cancelButtonText="cancel"
        showCancelButton="true"
        (ionInput)="getItems()"
        (ionCancel)="onCancel()"
        placeholder="Que faire?"
        mode="ios"
        debounce="0"
        >
    </ion-searchbar>

---for ion-tabs----

<ion-tabs>
  <ion-tab [root]="alarm" tabIcon="md-alarm"></ion-tab>
  <ion-tab [root]="mail" tabIcon="md-mail"></ion-tab>
  <ion-tab [root]="alert" tabIcon="md-alert"></ion-tab>
  <ion-tab [root]="msg" tabIcon="md-text"></ion-tab>
  <ion-tab [root]="apps" tabIcon="md-apps"></ion-tab>
</ion-tabs>
-----------------------------------------------------------------
code .TS:

  onCancel(event){
    console.log("ok")
  }

  onInput(event) {
    console.log(this.searchKey)
  }

**Comment by metz0r** [comment] 2017-03-15 11:53
I also experienced this issue but after switching to WKWebView the problem is gone: http://blog.ionic.io/cordova-ios-performance-improvements-drop-in-speed-with-wkwebview/

**Comment by jgw96** [comment] 2017-03-15 14:02
Hello all! Closing this issue as a duplicate of https://github.com/driftyco/ionic/issues/10552. Also, as @metz0r mentions above this is an issue related to a bug in UiWebView and switching to our WkWebView cordova plugin will fix the issue. We are working on making WkWebView the default for all Ionic applications shipped to iOS devices which will solve this issue for good. Thanks for using Ionic!

**Closed by jgw96** 2017-03-15 14:02 UTC

**Comment by jbertrand992** [comment] 2017-03-15 17:36
Thanks you guys it works :)
