### ISSUE TITLE
bug: ion-refresher & scrolling broken in 1.2.0

### ISSUE THREAD

**Issue by PerfectionCSGO** [driftyco/ionic#4808] opened 2015-12-17 13:01 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>After upgrading from 1.1.1 to 1.2.0 the following problems arise. These feature work when reverting back to 1.1.1.

- ion-refresher directive is completely non-functional in windows 8.1 (Lumia).
- ion-refresher on-refresh sometimes doesn't work correctly on iOS 9.1 (iPad)
- Pulling down ion-refresher on iOS 9.1 (iPad) sometimes doesn't pull the view and instead pulls the entire App down. This isn't always the case. 7 out of 10 times I encounter this.
- ion-refresher spinner freezes on android 5.x (High end samsung device)
- In ripple browser there shouldn't be native scrolling? (Chrome)

Enabling jscroll in configProvider does the following:

- In ripple browser scrolling issues are solved but ion-refresher spinner is frozen. Shows a bit awkward behavior for some unknown reason.
- iOS 9.1 Device, Android 5.x Device and Windows 8.1 Device behavior seems normal and as expected.
- iOS 9.1 Device: ion-refresher spinner is frozen. Once it's been frozen it is always frozen.

Adding
        ```<preference name="DisallowOverscroll" value="true" />```
To my cordova project's config.xml seems to fix the spinner issue. I can't say for sure but I can no longer reproduce the problems I was having after adding it. Will test this with iOS native.

Now when back on native, it seems to work until I switch to another view. (Which also has an ion-refresher). And then on both views the spinner and loading spinner seems to be frozen. pull-to-refresh seems to be working fine now.

Notably, using native scrolling on Windows Phone results in immense performance gains when scrolling down longer views would be nice to have this solved.</span>

<span is-issue-template></span>

**Comment by mlynch** [comment] 2015-12-17 17:56
Did just fix some of the iOS issues in a recent commit. WP8 might work, still testing though we don't support it

**Comment by PerfectionCSGO** [comment] 2015-12-18 08:02
Cheers, keep up the god work.

**Comment by beat-at-hartwig** [comment] 2016-01-19 11:17
I am also facing the problem with a frozen ion-spinner. Platform currently tested is Android 5.1.1 on a Nexus 4. Ionic version 1.2.4 !! Once I triggered ion-refresher all other ion-spinner seem to be frozen.

**Comment by slzr** [comment] 2016-02-29 15:07
@beat-at-hartwig i don't know why, but if i use a `spinner = crescent` the spinner animation is more fluid and doesn't freeze, this is in a android app of course

**Comment by amilino** [comment] 2016-03-30 21:30
Doesn't work with crescent or DisallowOverscroll = true...

**Comment by amilino** [comment] 2016-05-22 07:40
Any news on this?

I think it is related to something about SMIL and javascript animations.
http://ionicframework.com/docs/api/directive/ionSpinner/

Android spinner icon is using javascript, so my question is, are you planning to swith all icons to SWG with SMIL animations? Or is there any workaround for Android spinning icon?

**Comment by jgw96** [comment] 2016-05-23 08:09
Hello @amilino ! Unfortunately i can't seem to reproduce this with the latest version of ionic. There was a bug in the chrome webview for a little while that caused this issue, but that has since been resolved by the chrome team. What version of Android are you testing with?

**Comment by amilino** [comment] 2016-05-23 08:40
Version 6.0.1 on Nexus 5, with Ionic 1.2.4.

**Comment by amilino** [comment] 2016-05-23 09:14
I can confirm that it's working with latest version of Ionic (1.3.1).

Thank you!

**Comment by jgw96** [comment] 2016-05-23 15:20
Awesome! Glad its working for you now!

**Closed by jgw96** 2016-05-23 15:20 UTC
Labels: needs reply, v1

**Comment by jayzyaj** [comment] 2018-07-18 07:02
Hello there. I am having an issue using `ion-slides` link [link](https://github.com/ionic-team/ionic/issues/14796)
