### ISSUE TITLE
bug(slides): custom class not being applied

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic#6277] opened 2016-04-22 07:37 UTC
#### Short description of the problem:
I have an `ion-slides` element that I wish to have buttons outside of the element underneath the slider. However the class I have created and set on the `ion-slides` component is not being applied:

SCSS
```
    .has-bottom-buttons {
        height: calc(100% - 45px);
    }
```

HTML
```
   <ion-slides pager class='has-bottom-buttons' [options]='options'>
```

Note that this worked in beta 4. If I inspect the HTML, the has-bottom-buttons class is not applied to the element. If I manually add the class, the functionality works as expected.

Custom classes should be applied to ion-slides.

**Which Ionic Version?** 2.x

#### Plunker that shows an example of your issue

http://plnkr.co/edit/1Jd0EldWishtLdG0T6qL?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.1.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
OS:
Node Version: v5.10.1

**Comment by dylanvdmerwe** [comment] 2016-04-22 07:38
Also discussed: https://github.com/driftyco/ionic/issues/6275

**Comment by jgw96** [comment] 2016-04-22 15:59
Hey @dylanvdmerwe ! Thanks for opening this issue! So im gonna go ahead and close this as a dupe of #6275 but please feel free to chime in on that issue. Thanks!

**Closed by jgw96** 2016-04-22 15:59 UTC
Labels: range, slidebox
