### ISSUE TITLE
Incorrect documentation Usage examples

### ISSUE THREAD

**Issue by tones411** [driftyco/ionic#7165] opened 2016-07-02 03:49 UTC
#### Short description of the problem:
Incorrect documentation at http://ionicframework.com/docs/v2/api/components/modal/ModalController/
and http://ionicframework.com/docs/v2/api/components/popover/PopoverController/

#### What behavior are you expecting?
The Usage example at the URLs above says to include ModalController and present it by calling myModal.present(). However, I found that I had to include Modal instead, and present it by calling this.nav.present(MyController).

I think the same problems probably exist with the PopoverController documentation in the "Usage" example.

**Which Ionic Version?** 1.x or 2.x
2 beta 10

**Comment by manucorporat** [comment] 2016-07-02 10:21
`myModal.present()` is the proper way to present a modal in beta10. Can you verify which version of ionic 2 are you using? Run `ionic info`.

I am going to close this, but please feel free to reopen it if you think the issue persist

**Closed by manucorporat** 2016-07-02 10:21 UTC
Labels: modals, popover

**Comment by tones411** [comment] 2016-07-02 13:45
Here is my ionic info:
```
Cordova CLI: Not installed
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.5 
ios-sim version: 3.1.1 
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.3.1 Build version 7D1014 
```

If I use the concept based on the example at: http://ionicframework.com/docs/v2/api/components/modal/ModalController/
then...

The following line shows this error: "[ts] Module '"(...)/node_modules/ionic-angular/index"' has no exported member 'ModalController'."
```import { ModalController, ViewController } from 'ionic-angular';```

If I import Modal instead of ModalController, then the following line shows this error: "[ts] Property 'create' does not exist on type 'Modal'. any"
```let profileModal = this.modalCtrl.create(Categories, {});```

I tried running the following command, but it didn't resolve it:
```tsd install ionic cordova --save```

**Comment by brainlid** [comment] 2016-07-18 13:54
This problem has also bit me. This should still be **Open**.

The issue is the ModalController code is on master (which the docs represent) but creating a new project pins to beta 10 version. There are no later tags than beta 10. Sounds like a beta 11 is needed? 

My specific problem: I can see no way to get the result of a modal operation passed back to the caller except by using a modal controller.
