### ISSUE TITLE
bug: Touch content unmatch display content on scroll

### ISSUE THREAD

**Issue by leechunhoe** [driftyco/ionic#6722] opened 2016-06-01 13:39 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.3</span>  <span ionic-webview>webview</span>

<span ionic-description>On Samsung Galaxy Note 2, the touch content shifted below display content after scrolling.

For example, after I scrolled down a page, when I intend to click a button located at e.g. 45px from top, instead of directly clicking on it I have to click on 85px from top (at same x position) in order to do so.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment] 2016-06-01 15:55
Hello! Thanks for opening an issue with us! Are you using Crosswalk? Our Android support for Ionic 2 is Android 4.1 to 4.4 with Crosswalk only and 4.4 and up with no Crosswalk requirement. Thanks for using Ionic!

**Comment by leechunhoe** [comment] 2016-06-01 16:24
This issue happens with and without Crosswalk.

**Comment by leechunhoe** [comment] 2016-06-01 16:39
As far as I know, It happens only in Samsung Galaxy Note 2 real device.

I have tested with HTC One M7 and iPhone and no such issue. Button and input box clicks are in place.

**Comment by jgw96** [comment] 2016-06-02 17:06
Thanks for the info! As i cant seem to reproduce with any of my devices (Nexus 6 running the Android N dev preview, Nexus 7 running 6.0.1, Moto X 2014 running Android 5.1.1 and an Iphone 5) and it only seems to happen with a Note 2 specifically, I am going to close this issue for now as unfortunately there is not much i can do if i cannot reproduce it. I also flashed my Nexus 7 to 4.4.4 and could not reproduce with that version of Android either. If you can reproduce it with any other device and get a reproducible example that i can test, feel free to comment here and i will happily reopen this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-06-02 17:06 UTC
Labels: platform:android, v2
