### ISSUE TITLE
[beta.11] Alert buttons do not dismiss or call their handlers when a loading component is also showing

### ISSUE THREAD

**Issue by jasonwaters** [driftyco/ionic#7568] opened 2016-08-06 05:02 UTC
see https://forum.ionicframework.com/t/beta-11-button-handler-in-alerts-does-not-get-called/59691/2

#### Short description of the problem:
In my application, an alert is sometimes displayed on top of a loading component.  But when that happens the buttons do not respond to clicks.

#### What behavior are you expecting?
I was expecting the buttons to work regardless.

**Steps to reproduce:**
1.  create and display a Loading component
2. create and display an alert
3. try to click the alert button

**Diagnosis:**
When a loading component is showing, for whatever reason, it prevents the `ionViewDidEnter` event from being fired on the alert component.  `ionViewDidEnter` is what sets the `enabled` property to true.  Since `enabled` never gets set, the button clicks are short circuited in that event handler.

**Which Ionic Version?** 2.0.0beta11

**Comment by Kobzol** [comment] 2016-08-06 10:00
I have the same issue #7565.

**Comment by haydenJogs92** [comment] 2016-08-08 02:23
+1

**Comment by jgw96** [comment] 2016-08-08 05:03
Hello! Thanks for opening an issue with us! I am going to be closing this issue as a duplicate of https://github.com/driftyco/ionic/issues/7565. Thanks for using Ionic!

**Closed by jgw96** 2016-08-08 05:03 UTC
Labels: alert
