### ISSUE TITLE
bug: Navigation Title won't update after HTTP request

### ISSUE THREAD

**Issue by sean-hill** [driftyco/ionic#2900] opened 2015-01-08 17:25 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>If you issue a `http` request when a controller is loaded, and then try to update the navigation title to the response of the request, it will not update.

Check out the `FactsCtrl` controller and associated view in this pen to see what I'm talking about. Click on the `Scientific Facts` button.

http://codepen.io/anon/pen/JoENJP</span>

<span is-issue-template></span>

**Comment by pulakb** [comment] 2015-01-09 15:31
$http.get is an asynchronous call and before the response comes the template is getting rendered and hence while rendering the value of `factsTitle` is empty.

@sean-hill this is my assumption though.

**Comment by sean-hill** [comment] 2015-01-09 15:34
@pulakb thanks for the response. I tested it with $timeout after a second of waiting and the title updated fine. I wonder if $timeout is asynchronous too.

**Comment by pulakb** [comment] 2015-01-09 15:39
@sean-hill your assumption seems correct as $timeout is asynchronous. Please have look in the [$timeout documentation link](https://docs.angularjs.org/api/ng/service/$timeout)

**Comment by stianjensen** [comment] 2015-01-13 14:40
Could this be because the http request is fired on a $ionicView.beforeEnter event?

https://github.com/driftyco/ionic/issues/2755

**Comment by sean-hill** [comment] 2015-01-13 15:23
@stianjensen that is when I'm firing the http request. I'd like to load the data as the view slides in ya know?

**Comment by stianjensen** [comment] 2015-01-13 15:31
I totally agree, that bug is quite annoying.
A work-around could be to fire the request on beforeEnter, but somehow update the title on the enter event.
But this is really a duplicate of #2755

**Comment by kkiernan** [comment] 2015-02-25 22:24
Yeah this is strange. I've never had this problem before. I have an app where this works perfectly fine (Ionic v1.0.0-beta.9). I don't see anything different in that app's controllers or services though. I'll put up a codepen tonight if I can.

**Comment by Ionitron** [comment] 2015-03-11 02:42
You need to be using the lifecycle events as of beta14: http://ionicframework.com/docs/api/directive/ionView/

**Closed by Ionitron** 2015-03-11 02:42 UTC
Labels: ionitron:closed

**Comment by sean-hill** [comment] 2015-03-11 16:04
@Ionitron I believe this is not closed. I refactored my example using lifecycle events

http://codepen.io/anon/pen/raqjjd

Check out the facts ctrl code / comments

**Comment by petarov** [comment] 2015-05-27 19:00
@sean-hill is right.

Actually, I managed to wrap up sthg. like a fix using:

```javascript
$scope.$on('$ionicView.afterEnter', function() {
   $http.get(...)
   $scope.viewTitle = '<new value>';
});
```

This, however, doesn't look so nice visually. The title change is kind of jumpy.
