### ISSUE TITLE
bug: Can't use gulp hooks; package.json contains script

### ISSUE THREAD

**Issue by silkimen** [driftyco/ionic#8492] opened 2016-10-04 22:23 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I can't use gulp hooks (e.g. "serve:before" task) if there is a "scripts" section defined in package.json. I don't know whether this is a bug, but I need to define scripts in package.json because I am using the npm "pre-commit" module and I'd like to use the new style of ionic hooks.</span>

<span is-issue-template></span>

**Comment by danbucholtz** [comment] 2016-10-05 21:09
Could you provide a minimal example or some more details? I'm not sure what you mean.

Thanks,
Dan

**Comment by ovitrif** [comment] 2016-10-06 08:00
This is not a bug :/

**Comment by jgw96** [comment] 2016-10-07 13:53
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-10-07 13:53 UTC
Labels: needs reply

**Comment by silkimen** [comment] 2016-10-07 20:07
Hi all! Sorry, I've been busy the last days. My problem is that I'd like to use some of the ionic hooks you can define in the gulp file, but it's not working in combination with the npm module "pre-commit". The reason is that my "serve:before" task in gulp is not executed, when I define a script in the "scripts" section of "package.json".

**Steps to reproduce**

- create a new ionic project `ionic start test`
- add a "serve:before" task in `gulpfile.js`
```
gulp.task('serve:before', () => {
  console.log('I\'m a hook!');
});
```

- start dev server `ionic serve` --> hook is executed
```
Running 'serve:before' gulp task before serve
[21:54:40] Starting 'serve:before'...
I'm a hook!
[21:54:40] Finished 'serve:before' after 301 μs
```

- add a script in `package.json`
```
  "scripts": {
    "lint": "echo I will do some linting stuff!"
  }
```

- run `ionic serve` again --> hook is not executed

I know that I could use old fashioned hooks in package.json, but I'd prefer using gulp hooks. And I do also think that this is indeed a bug.

**Comment by silkimen** [comment] 2016-10-17 22:11
I'm still experiencing this problem. Can someone check it?

**Comment by danbucholtz** [comment] 2016-10-18 02:45
@jthoms1,

Can you take a look at this?

Thanks,
Dan
