### ISSUE TITLE
ios: tabsHideOnSubPages should default to true

### ISSUE THREAD

**Issue by joekukish** [driftyco/ionic#7584] opened 2016-08-07 09:14 UTC
#### Short description of the problem:
Currently ``tabsHideOnSubPages`` defaults to true in iOS. 

#### What behavior are you expecting?
After inspecting native iOS applications, the bottom tabs always go away when a another page is loaded.

**Which Ionic Version?** 1.x or 2.x
2.x

#### Plunker that shows an example of your issue

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.36
Ionic App Lib Version: 2.0.0-beta.19
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v6.3.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by joekukish** [comment] 2016-08-07 09:14
It is a default behavior issue so I don't provide an example. If it is still necessary please let me know.

**Comment by brandyscarney** [comment] 2016-08-08 16:09
`tabsHideOnSubPages` defaults to `false` for iOS: https://github.com/driftyco/ionic/blob/master/src/config/modes.ts#L42

I'm not able to reproduce this in our local tests. Could you provide a plunker that shows this? Thanks!

**Comment by joekukish** [comment] 2016-08-08 19:45
@brandyscarney my point is that it should default to ``true`` instead of false. Personally I was surprised to see that the tabs would not go away once a page is pushed. Initially I though it was a bug then then I realized it is following the default configuration. It gets really confusing if you have for example 2 tabs, and then one items leads to a deeper page. Then you click on "Tab 2", and then go back to "Tab 1". I would expect it to show the root of "Tab 1" but instead it kept the state.

http://plnkr.co/edit/OjaOQC?p=preview

**Comment by jgw96** [comment] 2016-08-08 20:15
Hello @joekukish . Would you mind pointing us to an example of a native ios app that hides tabs when a new page is navigated too? Thanks!

**Comment by jgw96** [comment] 2016-08-11 15:26
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-08-11 15:26 UTC
Labels: platform:ios, v2

**Comment by joekukish** [comment] 2016-08-11 17:24
@jgw96 i don't have an iOS device at hand to be able to provide you an example. If you do have one I encourage you to check how the toolbar behaves. From what I'm used to, it normally goes away hence the change for the default.

**Comment by brandyscarney** [comment] 2016-08-11 17:58
In which app? Looking at the WWDC app (which is an Apple app) and the App Store app this is how they both behave. If you navigate to a subpage inside of a tab and then click the tab again it will navigate back to the root page of the tab, if you click between tabs it keeps track of where you are in the navigation stack of each one, and it always shows the tabs on subpages.
