### ISSUE TITLE
bug: Input element in popup receives event that was fired before popup was open

### ISSUE THREAD

**Issue by stefanmdt** [driftyco/ionic#3411] opened 2015-03-26 09:58 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>These are dependencies that probably lead to the bug: 
* popup is opened by clicking/tapping on list item / button on the same position where the input appears
* ion-list / button is inside ion-tab
* ion-content uses overflow-scroll="true" (removing overflow solves the problem)
* app MUST run on mobile device (tested on iOS), on mobile browser the problem does not appear

The bug is very hard to reproduce, so I created an example repository: https://github.com/stefanmdt/ionic-popup-bug

You can also use the emulator to reproduce. It is important that you click on an area where the input element in the popup will appear afterwards.

I also created a plunker that shows, that it does not appear on mobile browsers: http://plnkr.co/edit/vNbSccMlGSGgfczWrZdV

This is the corresponding forum post: http://forum.ionicframework.com/t/popup-receives-previous-tap-event/18637/3

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-03-26 09:58
Greetings @stefanmdt!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3411). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3411)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment] 2015-04-17 19:52
Are you still seeing this with the nightly builds?

**Comment by stefanmdt** [comment] 2015-04-20 08:45
I've updated the git project. Now it uses ionic-bower#master. And unfortunately the bug is still there. Here is a video: https://www.dropbox.com/s/wme6xfe399mjopy/ionic-popup-bug.mov?dl=0

**Comment by mhartington** [comment] 2015-04-20 19:40
Alright, will pass this to @tlancina

**Comment by jamesmcb** [comment] 2015-05-27 01:00
So I am also experience this problem in my sidemenu when I am calling toggleLeft.  Here are some of my debugging notes:

* Occurs on the iPhone 5s and not iPhone 6
* Currently using 1.0.0 of ionic
* When adding an "alert" before toggleLeft in my side menu, the issue is resolved
* When delaying 1000ms with a setTimeout before calling toggleLeft, the issue is resolved
* When delaying 100ms with a setTimeout, the issue is not resolved
* When changing self.openPercentage(0) in self.toggleLeft in ionic.bundle.js to self.openPercentage(1), the issue is resolved

**Comment by nickcmaynard** [comment] 2015-05-29 14:30
We're also seeing this problem on iPhone 6 & iPad Air 2.  Both on iOS 8.3.

**Comment by nickcmaynard** [comment] 2015-05-31 09:06
Specifically, we're seeing the sidemenu issue described by @jamesmcb.

**Comment by nickcmaynard** [comment] 2015-07-16 17:22
@tlancina Please could you let us know your thoughts on when you will be able to take a look at this?

**Comment by nickcmaynard** [comment] 2015-07-16 17:35
A video of the issue we are seeing:
https://dl.dropboxusercontent.com/u/845142/Reflector%20Recording.mp4

This is the result of a single press on the "search" (magnifying glass) button in the top-right of the screen.

### Expected/desired outcome
The side menu opens, the keyboard is **not** shown.

### Actual outcome
The side menu opens, the keyboard is shown. Input to the keyboard has no effect on the "Search" field.

**Comment by tlancina** [comment] 2015-07-16 19:31
@nickcmaynard thanks for the ping. It appears to be the same ghost click issue as https://github.com/driftyco/ionic/issues/3649.  If you inject `$ionicClickBlock` and call `$ionicClickBlock.show(600)` on sidemenu open does it prevent the keyboard from going up? That fixed the issue with modals if I recall, although it doesn't seem to work in the example repo posted above.

**Comment by nickcmaynard** [comment] 2015-07-16 20:28
@tlancina Thank you!  That appears to have worked around the problem for now.

For the record, `$ionicClickBlock.show(450)` was enough.  The side effect is of course that legitimate clicks are blocked, but I think that's a relatively less important issue.

I'll continue to follow this issue to see what comes of your work on #3649, etc.

**Comment by mellinas** [comment] 2015-07-17 16:44
I noticed a strange behaviour on Android maybe linked to this issue

Platform : Android and only with Native Scroll

When you focus an input in a Popup and then focus out it breaks the Sidemenu scrolling

It seems ele.blur() in tapFocusOutActive() breaks my sidemenu scrolling (but don't know what is called after that can stop the scroller with native scrolling)

**Comment by FuzzyTree** [comment] 2016-01-24 10:49
This is also happening for me on android running v1.2.4.

If the position of the element that opens the popup coincides with the position of a clickable element in the popup, the popup element is automatically clicked (in my case it's a select drop down and the ok/cancel buttons).

Running $ionicClickBlock.show(450) before popup.show() didn't solve the issue for me

**Comment by jgw96** [comment] 2016-04-12 18:41
@nickcmaynard Are you still experiencing this issue? It looks to me as if it was fixed but just want to make sure! (: Also, @cmellinas would you mind opening a new bug with your issue please, thanks!

**Comment by jgw96** [comment] 2016-04-19 05:00
Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to respond back if your still having the issue!

**Closed by jgw96** 2016-04-19 05:00 UTC
Labels: keyboard, needs reply, tap/click
