### ISSUE TITLE
bug: Nav title set via ion-nav-title is not full width

### ISSUE THREAD

**Issue by DavidFrahm** [driftyco/ionic#2945] opened 2015-01-15 23:34 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>When I update my app to use the new (beta 14) ion-nav-title directive, the longer titles are intermittently styled to a very short width.

It appears that the CSS applied inline on that element is calculating very large values for 'right', so the header text only takes up about half the available space.

The code I changed start out like this:

    <ion-view title="{{equipment.name}}">

And I changed it to this after updating to beta 14:

    <ion-view>
        <ion-nav-title>{{equipment.name}}</ion-nav-title></span>

As a reliable workaround, I was able to stay with beta 14 and just go back to the title attribute method of setting the title.

<span is-issue-template></span>

**Comment by davidfrahm** [comment] 2015-01-15 23:46
The issue occurs for me in the browser, including the 'lab' (but only on the iOS side), and in the iOS simulator and devices.

Here's a screenshot of it in the browser with dev tools open; notice the very large value of "right", which is 209.127075195313px:

![ion-nav-title-css-bug](https://cloud.githubusercontent.com/assets/889791/5769217/29155be6-9cde-11e4-9182-a9536b61a406.png)

**Comment by akreienbring** [comment] 2015-02-04 13:06
Hello,
I can confirm that this happens on Android 44.2 as well. What was your exact workaround? Use 
```
<ion-view title="{{equipment.name}}">
```
instead? 
And is the closing '</ span>' a typo?

**Comment by DavidFrahm** [comment] 2015-02-05 02:15
Yes, that is my workaround.  Also yes, that closing span was just a typo here in my comments.

**Comment by zerahs** [comment] 2015-02-06 15:59
Any news on this ?

I also have this problem in iOS using the code below.

This doesn't work :
<code>
<span ng-if="condition">Long title 1</span>
<span ng-if="!condition">Long title 2</span>
</code>

Interesting thing is the width is fine without using ng-if. I can either use a single <span> without condition, or even replace the ng-if by ng-show. The "right" value is calculated without taking into account what's inside the ng-if element.

This works :
<code>
<span ng-show="condition">Long title 1</span>
<span ng-show="!condition">Long title 2</span>
</code>

**Comment by JWGmeligMeyling** [comment] 2015-02-21 12:47
I can confirm this issue :cry:

**Comment by javiercr** [comment] 2015-03-11 15:43
I think this other bug is the same thing: #2881

**Comment by mhartington** [comment] 2015-04-16 21:38
Could you please provide a codepen

**Comment by JWGmeligMeyling** [comment] 2015-04-16 21:51
This is a duplicate of this issue: https://github.com/driftyco/ionic/issues/2881
It has a codepen:  http://codepen.io/anon/pen/OPbKxy

**Comment by mhartington** [comment] 2015-04-27 18:31
closing as a duplicate

**Closed by mhartington** 2015-04-27 18:31 UTC

**Comment by akreienbring** [comment] 2015-07-15 18:10
I still have this issue! :-(
No matter if I use 1.0.0 or 1.0.1
My code:
```
    <ion-nav-title>
      	<p>someTitle
	      	<a class="icon" ng-class="someCondition ? 'ion-happy' : 'ion-sad'"></a>
	  		<a class="icon ion-wineglass" ng-show="someCondition"></a>
		</p>
    </ion-nav-title>
```
still is displayed cropped and none of the workarounds mentioned in 
https://github.com/driftyco/ionic/issues/2881 or
https://github.com/driftyco/ionic/issues/2615
did help!

Does anybody now a reliable solution?

**Comment by avbapat** [comment] 2017-06-03 07:27
Same issue here, Need an update soon.. thanks
