### ISSUE TITLE
bug: SVG's SMIL animations (<animate>, <set>, etc.) are deprecated and will be removed.

### ISSUE THREAD

**Issue by fairsayan** [driftyco/ionic#4316] opened 2015-09-04 23:27 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>On every page I'm getting this alert message on Chrome using driftyco/ionic-bower#1.1.0

SVG's SMIL animations (<animate>, <set>, etc.) are deprecated and will be removed. Please use CSS 
animations or Web animations instead.
at ionic.bundle.js:12005

and after I click somewhere I also obtain:

'webkitMovementX' is deprecated. Please use 'movementX' instead.
at ionic.bundle.js:1162
'webkitMovementY' is deprecated. Please use 'movementY' instead.
at ionic.bundle.js:1162</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-09-04 23:27
Greetings @fairsayan!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4316). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4316)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by vicheanak** [comment] 2015-09-07 07:17
I got the same issues, how to fix it?

**Comment by atans2468** [comment] 2015-09-07 23:44
This just started happening to me as well, any idea as to what is causing this? I haven't made any changes to ionic.bundle.js so I'm unsure what would cause this suddenly

**Comment by agupta1989** [comment] 2015-09-08 06:30
+1, Yes. for ionic version: 1.1.0 and cordova 5.2.0

**Comment by sidlauskaslukas** [comment] 2015-09-08 06:33
Got same issue. Ionic version 1.0.0

**Comment by agupta1989** [comment] 2015-09-08 06:35
Is it because of new updated version of Google Chrome version ?

**Comment by atans2468** [comment] 2015-09-08 06:42
I don't believe so, I'm still getting errors when I run an emulator and check the console log

**Comment by mhartington** [comment] 2015-09-08 13:15
Duplicate of  #4259 
Moving conversation of there.

**Closed by mhartington** 2015-09-08 13:15 UTC

**Comment by x252618759** [comment] 2015-11-02 08:28
我也碰到这样的问题，有没有人知道怎么解决呢？

**Comment by 0077cc** [comment] 2015-11-10 17:16
mhartington I can not see any solution on #4316, #4259,
SO
whats is the solution for:

SVG's SMIL animations (<animate>, <set>, etc.) are deprecated and will be removed. Please use CSS animations or Web animations instead.

'webkitMovementX' is deprecated. Please use 'movementX' instead. ionic.bundle.js:1162
'webkitMovementY' is deprecated. Please use 'movementY' instead. ionic.bundle.js:1162
