### ISSUE TITLE
bug: When deep linking between tabs, unable to click on tab to get to tab root

### ISSUE THREAD

**Issue by rahulbpatel** [driftyco/ionic#3688] opened 2015-05-08 20:15 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>This codepen highlights the issue:
http://codepen.io/anon/pen/RPrGvX

The tab/nav structure is:
* `Home`
* `About`
* `About > Tab Nav Stack`

If you click the "Tab Nav Stack" link from `Home` you will be taken to `About > Tab Nav Stack`.  If you then click on the "About" tab nothing happens.  I would expect it to take me to `About`.

However, if you click on "About" and then click on "Tab Nav Stack" it takes you back to `About` as expected.

It looks like a potential fix might be to modify controller method `$ionicTabs.select` to go to previous tab history only when navigating between tabs
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-05-08 20:15
Greetings @rahulbpatel!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3688). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3688)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment] 2015-05-11 16:23
This misunderstands the how tab's navigational histories work. In Ionic, as well as iOS and Android native SDKs, the tabs are a means of switching between parallel history stacks. Clicking on a given tab, simply changes which timeline you're on. If you deep-link a ways in, clicking on the currently active tab does nothing because you're already on that history stack. This is the Tabs directive working as intended. 

If you don't want this behavior, I'd suggest using divs with the appropriate CSS classes rather than the directives themselves.

**Closed by perrygovier** 2015-05-11 16:23 UTC

**Comment by rahulbpatel** [comment] 2015-05-11 16:44
In case anyone wants a second click on the tab to go back to the tab "root", this is the work around we went with:

**tabs.html**
```
<ion-tab title="{{'Me' | translate }}" icon-off="ion-ios-person-outline" icon-on="ion-ios-person"
  ng-click="selectTabWithIndex(1)" href="#/me">
    <ion-nav-view name="menuContent-me"></ion-nav-view>
 </ion-tab>
```

**tabsController.js**
```
$scope.selectTabWithIndex = function(index) {

  // Hack for issue when deep linking between
  // tabs and not being able to click on tab to see the root
  // see https://github.com/driftyco/ionic/issues/3688
  if (index === $ionicTabsDelegate.selectedIndex()) {
    // Clicked on link for current tab

    // Browse to path for this tab
    $location.path(this.href.substr(1));
   } else {
     // Switching tabs, use ionic delegate to select tab
     $ionicTabsDelegate.select(index);
   }
}
```
