### ISSUE TITLE
VirtualScroll last element at top in v2

### ISSUE THREAD

**Issue by lain-me** [driftyco/ionic#6961] opened 2016-06-18 21:55 UTC
When list with virtual scroll is loaded last element is on top (if scrolled to bottom it disappears).

[Plnkr here ](http://plnkr.co/edit/iDoqSUX4zFsbuBhLEI7p?p=preview)

**Comment by mpaland** [comment] 2016-06-19 11:32
I can confirm this. I just haven't had this problem yet, cause I was always using a sliding item, like:
```html
    <ion-item-sliding *virtualItem="let item">
      <ion-item>
        <ion-row class="item-row">
          <ion-col class="item-title" width-80>
            {{item.title}}
          </ion-col>
          <ion-col class="item-time" width-20>
            {{item.date}}
          </ion-col>
        </ion-row>
      </ion-item>
    </ion-item-sliding>
```
which is working fine.
So problem must be in virtual scroll together with a normal ```<ion-item>```.

**Comment by jjmax75** [comment] 2016-07-26 03:25
Following from @Ritzlgrmft on issue #7059 I have used this CSS to overcome this bug

```
ion-list > .item:first-child {
    z-index: 1;
  }
```

Works on web view and Android

**Comment by adamdbradley** [comment] 2016-11-19 22:12
Looks like this has been fixed in recent versions:
http://plnkr.co/edit/LjGFzBWPcD6j5sHtaVId?p=preview

And it probably comes down to the CSS wasn't being getting applied (by the framework, nothing developers were doing wrong). Thanks for the report!

**Closed by adamdbradley** 2016-11-19 22:12 UTC
Labels: v2, virtualscroll
