### ISSUE TITLE
Ionic v2 Virtual scroll doesn't work on ios

### ISSUE THREAD

**Issue by aspitrine** [driftyco/ionic#7375] opened 2016-07-20 09:30 UTC
#### Short description of the problem:
Virtual scroll doesn't work correctly. When i scroll, i see blank line.

**Steps to reproduce:**
1. Put a virtual scroll

**Other information:** 
 
![bug virtual scroll](https://cloud.githubusercontent.com/assets/3731837/16981539/4844cf5c-4e6b-11e6-9fb6-6e6f3a66c305.gif)

**Which Ionic Version?**
Ionic v2 beta 10

**Comment by mpaland** [comment] 2016-07-20 10:19
Is already an (unfortunately unfixed) issue.
See here #6766 and here #6999

**Comment by jgw96** [comment] 2016-07-20 14:37
Hello, thanks for opening an issue with us! I will be closing this issue as a duplicate of #6999 . Thanks for using Ionic!

**Closed by jgw96** 2016-07-20 14:37 UTC
Labels: platform:ios, v2, virtualscroll
