### ISSUE TITLE
Extra padding when ion-card inside ion-content with padding

### ISSUE THREAD

**Issue by e9li** [driftyco/ionic#11102] opened 2017-04-06 19:56 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
After updating to 3.0 there is an extra padding when using ion-card inside a `<ion-content>`. 
Removing the padding corrects the padding left an right but top and bottom has no padding anymore.
Happens on all iOS Devices and iSimulator with iOS 10.3 and on Android emulator with Android 7.1.1
![bildschirmfoto 2017-04-06 um 22 25 54](https://cloud.githubusercontent.com/assets/1247727/24772337/969d32b8-1b19-11e7-921c-e681c5210ea0.png)
![bildschirmfoto 2017-04-06 um 22 42 49](https://cloud.githubusercontent.com/assets/1247727/24772768/45a8f278-1b1b-11e7-8fd7-ddc1a2fe65e3.png)
![bildschirmfoto 2017-04-06 um 22 53 03](https://cloud.githubusercontent.com/assets/1247727/24773001/1f7cf436-1b1c-11e7-83e0-4e9b07adbb44.png)

**Expected behavior:**
Shoud look like before in 2.3
![bildschirmfoto 2017-04-06 um 22 24 16](https://cloud.githubusercontent.com/assets/1247727/24772322/8a423680-1b19-11e7-80c8-a0593246c7f9.png)
![bildschirmfoto 2017-04-06 um 22 46 47](https://cloud.githubusercontent.com/assets/1247727/24772780/4d21f770-1b1b-11e7-8fe3-88d153df79ba.png)

**Steps to reproduce:**
Put an ion-card in a ion-content with padding

**Related code:**
```
<ion-content padding>
    <ion-card>
    </ion-card>
</ion-content>
```

**Other information:**
I could fix this problem by removing the padding on ion-content and adding some scss to app.scss
```
<ion-content>
<ion-card>
</ion-card>
</ion-content>
```

```
ion-content.content {
  .scroll-content {
    padding-top: 1px;
    padding-bottom: 1px;
  }
}
```

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.6.0
Xcode version: Xcode 8.3 Build version 8E162
```

**Comment by brandyscarney** [comment] 2017-04-06 21:13
Thanks for the issue! I'm not able to see any differences in `padding` with a card. It looks like you have a lot of custom CSS, could this be causing it? Here is what I see when placing a single card in the conference app:

<img width="435" alt="screen shot 2017-04-06 at 5 10 53 pm" src="https://cloud.githubusercontent.com/assets/6577830/24775804/5b91bb76-1aec-11e7-9323-7400c5c0d091.png">

Could you provide a minimal repository that reproduces it, or see if you can reproduce it in the conference app? https://github.com/driftyco/ionic-conference-app

Thanks 🙂

**Comment by anveo** [comment] 2017-04-06 22:40
I observed this as well, appears to be fixed with `ionic-angular@3.0.1`.

**Comment by brandyscarney** [comment] 2017-04-06 22:42
@anveo That may be why I couldn't reproduce it in my testing. Thanks for the info. :)

**Comment by e9li** [comment] 2017-04-07 05:32
@brandyscarney I didn't use a lot custom CSS, it's out of the box like that, even with a fresh project.

**Comment by e9li** [comment] 2017-04-07 08:05
`ionic-angular@3.0.1` solves the problem

**Comment by AmitMY** [comment] 2017-04-07 12:08
@e9li Anything else, or close?

**Closed** 2017-04-07 12:21 UTC
Labels: css, needs reply, v3

**Comment by rohit-pathak** [comment] 2017-10-05 04:51
I'm seeing this issue with Ionic 3.12.0 ("ionic-angular": "3.7.1"). I have `ion-card` with a list (from the documentation) inside `ion-content`.
<img width="355" alt="screen shot 2017-10-05 at 12 49 56 am" src="https://user-images.githubusercontent.com/2214355/31211459-2d1c43a6-a967-11e7-8b20-f9fac9f91299.png">

**Comment by groupsvkg** [comment] 2017-11-29 15:35
Ionic 3.19.0("ionic-angular": "3.9.2"). I am not able to remove spaces to the right of ion-card inside ion-content.
![image](https://user-images.githubusercontent.com/366335/33383270-e45c8780-d548-11e7-9194-d191742c4dbd.png)

![image](https://user-images.githubusercontent.com/366335/33383332-0a588538-d549-11e7-8791-be815947029d.png)

**Comment by brandyscarney** [comment] 2017-11-29 15:43
@groupsvkg The card takes up `100%` width minus the margin. If you want it to have no margin and take up the full width you will need to set `width: 100%`.
