### ISSUE TITLE
Modals not calling onPageWillEnter() in Ionic 2 beta 7

### ISSUE THREAD

**Issue by FdezRomero** [driftyco/ionic#6650] opened 2016-05-25 14:11 UTC
#### Short description of the problem:
Calling a `@Page` as a modal using `this.nav.present()` instead of as a standard page with `this.nav.push()`, causes the `@Page` not to call its `onPageWillEnter()` function.

#### What behavior are you expecting?
`NavController` should always run the [lifecycle event functions](http://ionicframework.com/docs/v2/api/components/nav/NavController/#lifecycle-events) defined in `@Page`, regardless of being called as a standard page or modal.

**Steps to reproduce:**
1. Define a `onPageWillEnter()` function inside a `@Page`:
```typescript
import {Page, NavController, NavParams, ViewController} from 'ionic-angular';

@Page({
  templateUrl: 'build/pages/some/some.html'
})
export class SomePage {

  constructor(public nav: NavController, private navParams: NavParams, private view: ViewController) {}

  private onPageWillEnter() {
    console.log('onPageWillEnter called');
  }

}
```
2. Call the page as a modal from the parent page / app:
```typescript
openModal() {
  let someModal = Modal.create(SomePage);
  this.nav.present(someModal);
}
```
3. The `console.log` is never displayed.

**Which Ionic Version?**
ionic-angular@2.0.0-beta.7

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Your system information:

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.7
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment] 2016-05-25 14:33
Hello, thanks for opening an issue with us! This is a known issue and we are working on fixing it now. Once it is fixed we plan on releasing a nightly that has those fixes and i will update this issue when we do that. Thanks for using Ionic!

**Comment by brandyscarney** [comment] 2016-05-25 14:43
Closing as a duplicate of #6597. This will be in the `beta 8` release and it is in the nightly version if you need it sooner:

```
npm install --save 2.0.0-beta.7-201605211713
```

Thanks!

**Closed by brandyscarney** 2016-05-25 14:43 UTC
Labels: modals, platform:ios, v2

**Comment by FdezRomero** [comment] 2016-05-25 15:44
Thanks @jgw96 @brandyscarney! I looked for existing issues and somehow I missed this one.
