### ISSUE TITLE
Problem with ion-select and Alert in the same page

### ISSUE THREAD

**Issue by agasbzj** [driftyco/ionic#7969] opened 2016-09-05 02:43 UTC
#### Short description of the problem:
It doesn't work if you have a ion-select in page and show Alert or Toast in the same page.
You can tap the ion-select which shows an alert first and it works fine, then let something show another alert or toast, after closing that, if you tap the first ion-select again, you can't use that ion-select component any more.
#### What behavior are you expecting?
Hope any alert or toast works well with an ion-select in the same page.

**Steps to reproduce:**
1. Open a ion-select, select something in it and close it.
2. Show a Loading, close it after some time.
3. Open another Alert or Toast, and close it.
4. Tap the ion-select, something strange will happen.

**Which Ionic Version?** 1.x or 2.x
2.0.0-rc.4

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

```
ViewWrappedException {_wrapperMessage: "Error in ./AppRoot class AppRoot_Host - inline template:0:0", _originalException: ExpressionChangedAfterItHasBeenCheckedException, _originalStack: "Error: Expression has changed after it was checked…//localhost:8100/build/js/app.bundle.js:27364:42)", _context: DebugContext, _wrapperStack: "Error: Error in ./AppRoot class AppRoot_Host - inl…e (http://localhost:8100/build/js/zone.js:323:29)"}_context: DebugContext_nodeIndex: 0_staticNodeInfo: (...)_tplCol: 0_tplRow: 0_view: _View_AppRoot_Host0component: (...)componentRenderElement: (...)context: (...)injector: (...)providerTokens: (...)references: (...)renderNode: (...)source: (...)__proto__: Object_originalException: ExpressionChangedAfterItHasBeenCheckedExceptionmessage: "Expression has changed after it was checked. Previous value: 'false'. Current value: 'true'"stack: "Error: Expression has changed after it was checked. Previous value: 'false'. Current value: 'true'
at ExpressionChangedAfterItHasBeenCheckedException.BaseException [as constructor] (http://localhost:8100/build/js/app.bundle.js:3537:23)
 at new ExpressionChangedAfterItHasBeenCheckedException (http://localhost:8100/build/js/app.bundle.js:32890:16)
 at checkBinding (http://localhost:8100/build/js/app.bundle.js:34043:19)
at DebugAppView._View_AppRoot_Host0.detectChangesInternal (AppRoot.template.js:33:7)
    at DebugAppView.AppView.detectChanges (http://localhost:8100/build/js/app.bundle.js:33419:14)
    at DebugAppView.detectChanges (http://localhost:8100/build/js/app.bundle.js:33524:44)
    at ViewRef_.checkNoChanges (http://localhost:8100/build/js/app.bundle.js:33877:66)
    at http://localhost:8100/build/js/app.bundle.js:27364:88
    at Array.forEach (native)
    at ApplicationRef_.tick (http://localhost:8100/build/js/app.bundle.js:27364:42)"__proto__: BaseException_originalStack: "Error: Expression has changed after it was checked. Previous value: 'false'. Current value: 'true'
    at ExpressionChangedAfterItHasBeenCheckedException.BaseException [as constructor] (http://localhost:8100/build/js/app.bundle.js:3537:23)
    at new ExpressionChangedAfterItHasBeenCheckedException (http://localhost:8100/build/js/app.bundle.js:32890:16)
    at checkBinding (http://localhost:8100/build/js/app.bundle.js:34043:19)
    at DebugAppView._View_AppRoot_Host0.detectChangesInternal (AppRoot.template.js:33:7)
    at DebugAppView.AppView.detectChanges (http://localhost:8100/build/js/app.bundle.js:33419:14)    at DebugAppView.detectChanges (http://localhost:8100/build/js/app.bundle.js:33524:44)
    at ViewRef_.checkNoChanges (http://localhost:8100/build/js/app.bundle.js:33877:66)
    at http://localhost:8100/build/js/app.bundle.js:27364:88
    at Array.forEach (native)↵    at ApplicationRef_.tick (http://localhost:8100/build/js/app.bundle.js:27364:42)"_wrapperMessage: "Error in ./AppRoot class AppRoot_Host - inline template:0:0"_wrapperStack: "Error: Error in ./AppRoot class AppRoot_Host - inline template:0:0
    at ViewWrappedException.WrappedException [as constructor] (http://localhost:8100/build/js/app.bundle.js:3555:31)
    at new ViewWrappedException (http://localhost:8100/build/js/app.bundle.js:32906:16)
    at DebugAppView._rethrowWithContext (http://localhost:8100/build/js/app.bundle.js:33541:23)
    at DebugAppView.detectChanges (http://localhost:8100/build/js/app.bundle.js:33527:18)
    at ViewRef_.checkNoChanges (http://localhost:8100/build/js/app.bundle.js:33877:66)
    at http://localhost:8100/build/js/app.bundle.js:27364:88
    at Array.forEach (native)
    at ApplicationRef_.tick (http://localhost:8100/build/js/app.bundle.js:27364:42)
    at http://localhost:8100/build/js/app.bundle.js:27266:125
    at ZoneDelegate.invoke (http://localhost:8100/build/js/zone.js:323:29)"context: (...)message: (...)originalException: (...)originalStack: (...)wrapperMessage: (...)wrapperStack: (...)__proto__: WrappedExceptionconsoleError @ zone.js:463drainMicroTaskQueue @ zone.js:477ZoneTask.invoke @ zone.js:426
protocols.ts:33 Response headers: {"Content-Type":["application/json;charset=UTF-8"]}, body:{
  "result" : {
    "count" : 0,
    "companies" : null
  },
  "status" : "ok",
  "error_code" : "0"
}
```

**Comment by jgw96** [comment] 2016-09-15 16:54
Hello, thanks for opening an issue with us! I am going to be closing this issue as a duplicate of https://github.com/driftyco/ionic/issues/8066. Thanks for using Ionic!

**Closed by jgw96** 2016-09-15 16:54 UTC
Labels: v2
