### ISSUE TITLE
Border/Shadow/Scrollbar appear on Content/Menu right side after clicking on Button/Item

### ISSUE THREAD

**Issue by chakhedik** [driftyco/ionic#8975] opened 2016-11-01 11:41 UTC
#### Short description of the problem:
1. Border/Shadow/Scrollbar appear on Content/Menu right side after clicking on Button/Item
2. Only appear on real device
3. Android only

**Steps to reproduce:**
1. Start a sidemenu project
2. Add a button with no action
3. Build apk and click on button running on device

**Which Ionic Version?** 1.x or 2.x
2.rc1

#### Plunker that shows an example of your issue
Since this is only happen on real device, here's the screen recording: http://gifyu.com/image/S26Q

![image](https://cloud.githubusercontent.com/assets/540466/19888637/efe7f1ca-a06a-11e6-8b6e-98495f6d38a6.png)

![image](https://cloud.githubusercontent.com/assets/540466/19888641/f5c2acca-a06a-11e6-97cd-80c86a385b65.png)

![image](https://cloud.githubusercontent.com/assets/540466/19888652/fa9ca246-a06a-11e6-8765-8013db9e97e9.png)

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.38
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v6.9.1
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by jgw96** [comment] 2016-11-01 15:18
Hello, thanks for using Ionic! Unfortunately I am not seeing this on any of my Android devices. What version of Android are you testing with?

**Comment by chakhedik** [comment] 2016-11-01 23:44
Hi, I'm testing it on Android 6.0.1, facing the same issue on ionic v1 but it goes away when I set `$ionicConfigProvider.views.transition('platform');` in `app.js` but no luck with v2 when I set `pageTransition: 'platform'` in `app.module.ts`. I did try and error with 'ios', 'android', 'md' but no luck either.

**Comment by jgw96** [comment] 2017-01-25 19:33
Hello. After further research it looks like this issue is a duplicate of https://github.com/driftyco/ionic/issues/6416. Because of this I am going to be closing this issue for now. Thanks!

**Closed by jgw96** 2017-01-25 19:33 UTC
Labels: needs reply, v2
