### ISSUE TITLE
Sliding list sliding items not working in RTL

### ISSUE THREAD

**Issue by theunreal** [driftyco/ionic#10219] opened 2017-01-28 09:35 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Sliding list don't show the sliding buttons correctly and few issues with the display.
Before sliding:
![image](https://cloud.githubusercontent.com/assets/6171883/22395671/94791b48-e54d-11e6-8ded-e7388bc3a06c.png)
After sliding left:

![image](https://cloud.githubusercontent.com/assets/6171883/22395673/a4a96392-e54d-11e6-9d0a-a41a6838008d.png)

After sliding right:
![image](https://cloud.githubusercontent.com/assets/6171883/22395675/b14256a4-e54d-11e6-8874-fddbe40e9262.png)

After sliding more and more right:

![image](https://cloud.githubusercontent.com/assets/6171883/22395676/c2848838-e54d-11e6-969a-13790f0073c0.png)

**Expected behavior:**
- Sliding list should work and show the sliding buttons when trying to slide.
- the ion lines should not be displayed under the buttons
- Buttons should appeaer from the right side

**Steps to reproduce:**
Use ion sliding list in any RTL app

**Related code:**

```
<ion-list>
  <ion-item-sliding>
<ion-item *ngFor="let message of chatMessages | async">
    <h2>test 1</h2>
    <p>test 2</p>
</ion-item>
<ion-item-options side="right">
      <button ion-button color="primary">
        <ion-icon name="text"></ion-icon>
        Button 1
      </button>
    </ion-item-options>
    <ion-item-options side="left">
      <button ion-button color="primary">
        <ion-icon name="remove-circle"></ion-icon>
        Button 2
      </button>
          <button ion-button color="primary">
            <ion-icon name="trash"></ion-icon>
            Button 3
          </button>
        </ion-item-options>
  </ion-item-sliding>
</ion-list>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.2
Xcode version: Not installed
```

**Comment by Abderrahmane-H** [comment] 2017-01-28 12:47
I used to have problems with ionic 2 sliding items when using RC versions, try to update ionic to final and the problem will be solved.

**Comment by theunreal** [comment] 2017-01-28 14:54
@Abderrahmane-H It solves the problem only if style="direction:ltr" is set, RTL is same - not working correctly.

**Comment by Abderrahmane-H** [comment] 2017-01-28 15:34
yes you are right , well there is a workaround until there is a fix :
    -set the ion-item-sliding direction to ltr, dir="ltr" or by using sass
    -set the ion-item direction to rtl,
this is one solved that issue for a blank app set to 'rtl' edited to have sliding items .

**Comment by theunreal** [comment] 2017-01-28 15:36
@Abderrahmane-H This is just about my previouso comment... it is a workaround but this issue still need to be fixed

**Comment by jgw96** [comment] 2017-01-30 15:38
Hello, thanks for using Ionic! We will take a look at this!

**Comment by jgw96** [comment] 2017-01-30 15:39
Hello, thanks for opening an issue with us! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/8107.

**Closed by jgw96** 2017-01-30 15:39 UTC
Labels: v2
