### ISSUE TITLE
Ionic2 segment scroll behaviour (scroll 1 segment, other non-active segments also scroll)

### ISSUE THREAD

**Issue by ghenry22** [driftyco/ionic#7022] opened 2016-06-23 06:55 UTC
#### Short description of the problem:
When scrolling in 1 segment the content in all other segments in a component also scroll

Same behaviour in all platforms and browser

#### What behavior are you expecting?
Only the content in the active/visible segment scrolls

**Steps to reproduce:**
1. create a simple starter app with more items than fit on the screen so scroll can be used
2. cut and paste the example segment code from the docs
3. scroll down on segment 1
4. switch to segment 2.  Note that it has also scrolled down to the same position as segment 1

you can see it easily in the attached plunker, just have to have lists long enough to scroll under the more than 1 segment.

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x
2.0beta9

#### Plunker that shows an example of your issue

http://plnkr.co/edit/7zaGMoXcfTZOcdSr3nfa?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.30
Ionic App Lib Version: 2.0.0-beta.16
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.11.1
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment] 2016-06-23 20:20
Hello @ghenry22 this is actually expected behavior. If you would like to scroll to the top whenever you change the segment you can just do something like im doing here in this plunker http://plnkr.co/edit/jSaeo3WemjWYMoCmEnwK?p=preview. Thanks for using Ionic! I am going to close this issue, but if you have any questions about the plunker feel free to comment.

**Closed by jgw96** 2016-06-23 20:20 UTC
Labels: platform:ios, v2

**Comment by ghenry22** [comment] 2016-06-24 04:43
@jgw96 that works for now thanks.

I guess this is because scroll is tied to the ion-content and there is only 1 ion-content to scroll?

Isn't it weird though that content on an inactive segment also scrolls when the active one scrolls?  Is it possible to move ion-content within a segment so you have a seperate ion-content, and hence scroll position for each segment?

**Comment by jgw96** [comment] 2016-06-24 16:06
Good question! So its expected behavior because it is the same `ion-content` for each segment, the content of it just changes. I would not suggest having two `ion-content`'s on one page, but feel free to give it a try. After discussing it with my team yesterday we decided that the cleanest solution is using `scrollToTop`. We could add something like this to the framework so you do not have to handle it yourself, but we are trying to keep things more minimal in Ionic 2 to give users a very solid base to build custom functionality off of. Hope all this makes sense!

**Comment by ghenry22** [comment] 2016-06-24 23:38
Yes that makes sense.  I guess the alternative is tabs where each tab has its own content.  I saw there was an issue to make tabs style able to work like a segment, how about make an option for segment style appearance to work like tabs? Ie each segment is a seperate component.

This is still really minimal and gives users an option based on the behaviour they expect to see.

**Comment by biesbjerg** [comment] 2016-07-23 02:26
I think we should be able to switch between segments and have it remember the scroll position for each segment container just like in native platforms.

I thought I could maybe wrap my segment content in `<ion-scroll>`s to achieve this, but I don't see any content at all in my page when I do that. Maybe I did not understand how to use `<ion-scroll>`.

Can we re-open this issue to find a solution? Might be nice for the docs since the use case seems pretty normal.

**Comment by dimitri320** [comment] 2018-02-02 09:35
Any updates on this matter?

**Comment by dimitri320** [comment] 2018-04-18 12:48
This works but badly, because you don't want the user to see how the First Segment content scrolls (animated) down to the old position, it should just be there when you switch back from the Second to the First Segment. 

Also, this solution doesn't work with Infinite Scroll, as it triggers it if in the First Segment you've previously triggered Infinite Scroll, breaking up the solution.

Any other ideas? Anyone?

**Comment by prathyushp1** [comment] 2018-08-31 17:48
if you change to the next segment it shows the top of the segment

segment scroll not save/ if you go back to a scrolled segment it shows top or starting point
```
<div [ngSwitch]="selectedType">
	<div *ngSwitchCase="'recent'" class="scroll-content2">
       ...... items to show....
        </div>
	<div *ngSwitchCase="'recent'" class="scroll-content2">
       ...... items to show....
        </div>
</div>
```


```
.scroll-content2{
		left: 0;
		right: 0;
		top: 0;
		bottom: 0;
		position: absolute;
		z-index: 1;
		display: block;
		overflow-x: hidden;
		overflow-y: scroll;
		will-change: scroll-position;
		contain: size style layout;
	}
```
