### ISSUE TITLE
Floating input labels not displaying/animating correctly

### ISSUE THREAD

**Issue by jimitndiaye** [driftyco/ionic#6434] opened 2016-05-04 16:39 UTC
**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
When using the following markup in a custom component, floating labels do not move above the input when it has focus causing clashing text when you type into it:
```html
  <ion-list *ngIf="isDesignTime" >
    <ion-item>
      <ion-label floating>Input 1</ion-label>
      <ion-input type="text" placeholder="Enter a value"></ion-input>
    </ion-item>
    <ion-item>
      <ion-label floating>Input 2</ion-label>
      <ion-input type="password" placeholder="Enter your password"></ion-input>
    </ion-item>
  </ion-list>
```
As a result you get [this behaviour](http://imgur.com/D74DHN4)
You'll also notice that floating labels and placeholders clash.
#### What behavior are you expecting?
That floating labels animate above the target input as they do in the demos.

**Steps to reproduce:**
1. See plunkr below.
2. 
3. 

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x
2.0.0-beta.6

#### Plunker that shows an example of your issue

Closest I've come to reproducing it is this [plunkr](http://plnkr.co/edit/qXyywTLCcwG8TsygIgAD?p=preview) which shows the clashing between floating label and placeholder but unable to illustrate the floating labels not animating. Analyzing it in Chrome it seems the ```input-has-focus``` class which triggers the animation is not being applied when you click on the input field.

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by jgw96** [comment] 2016-05-04 16:55
Hello! Thanks for opening an issue with us! I am having a hard time reproducing the floating labels not animating. On the latest chrome canary and Android 5.1.1, Android 6.0.1 and Android N dev preview 2 it seems to animate fine. Also we do not recommend using Placeholders with floating label inputs. Is there a reason you are wanting to use both placeholders and a label? We do have a "placeholder input": http://ionicframework.com/docs/v2/components/#placeholder-labels that works with placeholders that you could use, but i would love to hear why you are wanting to use both a placeholder and a label (:

**Comment by jimitndiaye** [comment] 2016-05-05 13:04
Regarding floating labels use in conjunction with placeholders - we tend to use them for slightly different purposes. We use labels for short, identifying text to diffferentiate betweeen different inputs and we use placeholders for slightly longer descriptive/instructional text about the input.

As for the animation problem: it happens consistently in different parts of our app, all using markup similar to what I included above. Wasn't able to reproduce in plunkr, however. In all cases it seems the ```input-has-focus``` class is not being applied on focus.

**Comment by jgw96** [comment] 2016-05-05 15:08
Hmmm, so i did some testing with some of my apps and im having a hard time reproducing on Android 6.0.1, Android 5.1.1 and the Android N dev preview 2. If you remove the placeholders can you still repro the issue?

**Comment by jgw96** [comment] 2016-05-10 14:09
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by jimitndiaye** [comment] 2016-05-10 16:09
I'll try remove the placeholders and see if it makes a difference

**Closed** 2016-06-06 19:48 UTC
Labels: animation, v2
