### ISSUE TITLE
bug: Page header overlaps with iOS status bar

### ISSUE THREAD

**Issue by ThorConzales** [driftyco/ionic#8477] opened 2016-10-04 13:51 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.0.0 RC0</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>On iOS when a page is pushed in from the pop over then the page header overlaps with iOS status bar. Pushed in from outside of pop over seems to function normally.</span>

Code that is pushing in the page:
`
this._navController.push(Page).then(() => this._viewController.dismiss());
`

<span is-issue-template></span>

**Comment by ThorConzales** [comment] 2016-10-04 14:01
And when pushed in by first dismissing the action sheet and then pushing in the page results in same behavior but in that case back button is also missing.

**Comment by ThorConzales** [comment] 2016-10-04 14:32
I found a workaround which is to use navController reference acquired in root page rather than in action sheet page. This issue is also related to #8467.

**Comment by jgw96** [comment] 2016-10-07 17:07
Hello, thanks for opening an issue with us! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/8556 as that issue points to the bug that causes this issue.

**Closed by jgw96** 2016-10-07 17:07 UTC
Labels: v2
