### ISSUE TITLE
On-hold does not suppress on-click (ONLY on android)

### ISSUE THREAD

**Issue by sueess** [driftyco/ionic#7228] opened 2016-07-07 15:16 UTC
#### Short description of the problem:
on-hold directive does not suppress click-event or in other words: on-click directive executes after on-hold. I use Crosswalk!

#### What behavior are you expecting?
The would expect the behavior like in desktop-chrome or in iOS, where no click-event is fired after on-hold.

**Steps to reproduce:**
1. long click on a element with click and hold event (see below)

```
        <div ng-click="ctrl.onclick()" on-hold="ctrl.onhold()">CLICK</div>
```

**Which Ionic Version?** 1.x or 2.x
1.3.0
cordova-plugin-crosswalk-webview 1.7.2 / Crosswalk 18+

**Comment by jgw96** [comment] 2016-07-07 15:58
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by sueess** [comment] 2016-07-11 10:16
Here we go: https://plnkr.co/edit/XAdmpv
It will work in a normal browser, try it on Android!

**Comment by sschoeb** [comment] 2016-07-26 08:19
Problem occures mainly on Samsung devices. 

We can reproduce this on:
Samsung Galaxy Tab E (SM-T113NU) (Android 4.4.4)
Samsung Galaxy S6  (SM-G920F) (Android 6.0.1)

Works as expected:
Nexus 5X (Android 6.0.1)

**Comment by jgw96** [comment] 2016-07-26 14:25
@sueess would you mind trying the beta channel of crosswalk? I cannot seem to reproduce on my Nexus 6 running the final beta of Android N or my Nexus 7 running Android 6.0.1. Thanks!

**Comment by sueess** [comment] 2016-07-27 06:59
@jgw96 It's not a crosswalk problem. You can try my plunker on a SAMSUNG device using the on-device browser and the same issue occurs.

**Comment by jgw96** [comment] 2016-07-27 14:50
Hello @sueess unfortunately i can't seem to reproduce this issue on either a galaxy nexus running 4.2.2 or a tab running 4.4.4. Could you try putting on-hold before the ng-click and see if that fixes it for you? Thanks!

**Comment by jgw96** [comment] 2016-08-02 14:52
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-08-02 14:52 UTC
Labels: needs reply, v1

**Comment by sueess** [comment] 2016-08-05 09:27
First: A issue is not fixed by no activity, but I guess that is Ionic issue-management-process 2.0 :)?
Second: A NEXUS is not a SAMSUNG. It works on NEXUS devices, I DOES NOT on SAMSUNG.
Thirdly: The order of the directives doesen't change anything

**Comment by jgw96** [comment] 2016-08-05 19:14
Hello @sueess! Sorry that you are still having this issue. I tested this issue on a samsung tab running 4.4.4 and unfortunately could not reproduce this issue with that device. Have you gotten a chance to try the beta channel of crosswalk? Unfortunately samsung has a bad habit of not updating their browser or webview which can sometimes lead to weird issues such as this one, but normally that is solved by using crosswalk as crosswalk gives you a nexus like, completely stock chrome webview. Thanks for using Ionic!

**Comment by arthur791004** [comment] 2016-08-08 08:32
Hi,

I have the same issue.

I use the ng-click and on-hold on the same element, and then the click event would be trigger after the on-hold event.

It can reproduce by using chrome-dev tools with device toolbar

after tracing release/js/ionic.js, I think it trigger tapMouseDown but tapEnabledTouchEvents had been set to false due to tapMouseResetTimer

However, I don't know why it happens.

Thanks

**Comment by flexxis** [comment] 2016-09-11 08:50
I also can reproduce this issue on Samsung Galaxy S3 Neo with an ion-item element with on-hold, ng-click and on-release handlers. The order of fired events on the item is as follows : 1) on-hold , 2) on-clicked , 3) on-release.
event.preventDefault() and event.stopPropagation() on the on-hold $event does not seem to suppress the ng-click

**Comment by huanjiayang** [comment] 2016-11-09 15:15
I can replicate this issue on Galaxy S5 Android 6.0.1 on img elements: ng-click gets fired after on-hold......very annoying
