### ISSUE TITLE
ion refresher running continiosly and get this error

### ISSUE THREAD

**Issue by abmnukmr** [driftyco/ionic#10827] opened 2017-03-17 20:21 UTC
TypeError: Cannot read property 'nativeElement' of null
    at LoadingWpPopIn.init (http://localhost:8100/build/main.js:118046:46)
    at OverlayPortal.NavControllerBase._trnsStart (http://localhost:8100/build/main.js:32021:20)
    at LoadingWpPopIn._trnsStart (http://localhost:8100/build/main.js:31987:19)
    at LoadingWpPopIn.Transition.start (http://localhost:8100/build/main.js:15904:33)
    at OverlayPortal.NavControllerBase._transition (http://localhost:8100/build/main.js:32004:24)
    at OverlayPortal.NavControllerBase._postViewInit (http://localhost:8100/build/main.js:31866:18)
    at OverlayPortal.NavControllerBase._viewTest (http://localhost:8100/build/main.js:31953:25)
    at OverlayPortal.NavControllerBase._nextTrns (http://localhost:8100/build/main.js:31725:25)
    at OverlayPortal.NavControllerBase._queueTrns (http://localhost:8100/build/main.js:31689:14)
    at OverlayPortal.NavControllerBase.insertPages

myionic info:-

**Comment by manucorporat** [comment] 2017-03-18 11:53
@abmnukmr  I can't reproduce this problem, can you provide some source code that triggers this crash?

**Comment by jgw96** [comment] 2017-03-22 19:57
Hello! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-03-22 19:57 UTC
