### ISSUE TITLE
Side Menu type reveal not Working in iOS 9.1 and above

### ISSUE THREAD

**Issue by chandanch** [driftyco/ionic#7036] opened 2016-06-24 07:40 UTC
#### Short description of the problem:
Side menu type reveal does not come up in iOS 9.1 and above versions. However, If go back to the previous page then the sidemenu overlaps on that page. But, If the sidemenu type is set to overlay than it works perfectly in iOS. 
#### What behavior are you expecting?
The sidemenu of type reveal should come up on clicking the menu icon in iOS.

**Steps to reproduce:**
1. Create a side menu 
2. create or build the iOS version
3. Launch the app on iphone with iOS version 9.1 and above
4. Sidemenu doesn't come up.
5. Go back to the previous page, The sidemenu overlaps with this page. 

Here is my code snippet:

**page.html**
```
<ion-navbar *navbar >
        <ion-title>
           Cars List
        </ion-title>
        <ion-buttons end>
            <button   (click)="openMenu()"><ion-icon name="menu"></ion-icon></button>
        </ion-buttons>
    </ion-navbar>
<ion-menu [content]="content" primary  side="right" id="appListMenu">
        <ion-toolbar primary>
            <ion-title>Menu</ion-title>
        </ion-toolbar>
        <ion-content>
            <ion-list>
                <ion-item >
                    <ion-icon name="cog" item-left></ion-icon>
                    Settings
                </ion-item>
                <ion-item >
                    <ion-icon name="information-circle" item-left></ion-icon>
                    About US
                </ion-item>
                <ion-item (click)="logout()">
                    <ion-icon name="power" item-left></ion-icon>
                    Logout
                </ion-item>
            </ion-list>
        </ion-content>
   </ion-menu>
  <ion-nav  #content [root]="rootPage"></ion-nav>

```
**page.ts**
.......
```
export class Page {
    constructor(public menu : MenuController){
         this.menu = menu;
    }
    openMenu() {
        this.menu.toggle();
    }
}

```
**Which Ionic Version?** 
**ionic-angualar2.0.0.beta9**

Cordova CLI: Not installed
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic CLI Version: 2.0.0-beta.31
Ionic App Lib Version: 2.0.0-beta.17
ios-deploy version: Not installed
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.4.5
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by chandanch** [comment] 2016-06-24 07:46
Also set the type as reveal it doesn't work in Android version 5.0 and above, 

code snippet:

```
<ion-navbar *navbar >
        <ion-title>
           Cars List
        </ion-title>
        <ion-buttons end>
            <button   (click)="openMenu()"><ion-icon name="menu"></ion-icon></button>
        </ion-buttons>
    </ion-navbar>
<ion-menu [content]="content" primary  side="right" id="appListMenu" type="reveal">
        <ion-toolbar primary>
            <ion-title>Menu</ion-title>
        </ion-toolbar>
        <ion-content>
            <ion-list>
                <ion-item >
                    <ion-icon name="cog" item-left></ion-icon>
                    Settings
                </ion-item>
                <ion-item >
                    <ion-icon name="information-circle" item-left></ion-icon>
                    About US
                </ion-item>
                <ion-item (click)="logout()">
                    <ion-icon name="power" item-left></ion-icon>
                    Logout
                </ion-item>
            </ion-list>
        </ion-content>
   </ion-menu>
  <ion-nav  #content [root]="rootPage"></ion-nav>
```

**Comment by jgw96** [comment] 2016-06-24 14:41
Hello, thanks for opening an issue with us! Are you testing with beta.9? There were some fixes in that release for the ios sidemenu. Thanks for using Ionic!

**Comment by chandanch** [comment] 2016-06-25 05:10
Yes, I tested with **ionic-angular2.0.0.beta9**, It works fine in ionic-angular2.0.0.beta5.
Are you able to reproduce the problem?

**Comment by jgw96** [comment] 2016-06-27 14:41
@chandanch I can not, if you could make a plunker that demonstrates this issue that would be great!

**Comment by chandanch** [comment] 2016-06-28 06:59
Here is the plunkr. Run it in full screen mode and turn on the device emulation to iphone 6 or 5 the sidemenu does not open

https://plnkr.co/edit/roNYTz

**Comment by jgw96** [comment] 2016-06-28 18:36
Helo @chandanch unfortunately it looks like your plunker is using an outdated version of Ionic 2 and seems to just show a white screen for me. Would you mind creating a plunker from this plunker template? http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview

**Comment by chandanch** [comment] 2016-06-29 05:14
Here is the updated plunkr link: 

http://plnkr.co/edit/GgEvHK?p=preview

Run it in full screen mode and turn on the device emulation to iphone 6 or 5 the sidemenu does not open

**Comment by chandanch** [comment] 2016-07-22 13:18
Any updates on this?

**Comment by jgw96** [comment] 2016-08-16 18:21
Hello! Sorry for the delay on this! Unfortunately I still cant seem to reproduce this issue with your plunker on chrome and safari, or on real apps running on my Iphone 5, moto x, Nexus 6 and Nexus 7. Because of this i am going to close this issue for now. Thanks for using Ionic!

**Closed by jgw96** 2016-08-16 18:21 UTC
Labels: menus, platform:ios, v2
