### ISSUE TITLE
Modal Dialog Scroll not working correctly when Keyboard is Visible

### ISSUE THREAD

**Issue by afterxleep** [driftyco/ionic#2212] opened 2014-09-15 14:29 UTC
Hey guys.

This is a visual bug that appears to happen in iPad.

When you have a long form, that appears in a modal dialog, and the keyboard pops up the scrolling area goes out of the modal dialog boundaries as you will see in the attached screenshot.

How to repeat on the iPad:   
1. Present a long form in a modal dialog
2. Touch a field so the keyboard pops up
3. While the keyboard is up, scroll the form

![img_0004](https://cloud.githubusercontent.com/assets/1156669/4272708/b6a23114-3ce4-11e4-804d-e78cec1cb36c.PNG)

**Comment by sharky101** [comment] 2015-03-03 16:06
Any updates/workarounds for this?

**Comment by tlancina** [comment] 2015-04-13 17:43
Was caused by overflow: visible on modals, should be fixed with https://github.com/driftyco/ionic/commit/1a4e36bcdcc395dbb395b7c72e7332dab330df15.

**Closed by tlancina** 2015-04-13 17:43 UTC
Labels: css, modals

**Comment by davegroff** [comment] 2015-05-29 04:04
Deleting overflow: visible; didn't work for me.  I just changes to overflow: auto; and it works fine now.

**Comment by snehasis** [comment] 2016-05-27 19:13
I am also getting the same issue while Making a Scrollable Lists inside a ionModal 

Is there any fix for this ?

**Comment by davegroff** [comment] 2016-05-27 19:15
Try overflow: auto;
