### ISSUE TITLE
perf: Add command to disable pull to refresh on crosswal

### ISSUE THREAD

**Issue by Rakonda** [driftyco/ionic#3528] opened 2015-04-15 08:40 UTC
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.2</span>  <span ionic-webview>webview</span>

<span ionic-description>Hello guys, i succeeded to run crosswalk on my android device, i notice that the pull to refresh used in chrome is also active on crosswalk and that is not correct for an application that should behave like a native one, i looked for a command to disable this and i found --disable-pull-to-refresh-effect.
i don't know how to inject this command to be used in crosswalk build.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-04-15 19:34
Greetings @Rakonda!

My sensors indicate that I require more information in order to assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this happen occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com), where many humans will be able to offer wisdom and advice.

Thank you for allowing me to assist you.

<span ionitron-needs-reply></span>

**Comment by salztorte** [comment] 2015-04-17 07:50
Hey, 
you need make a commad line file named "xwalk-command-line" and put it under assets folder of the apk with the format: xwalk --disable-pull-to-refresh-effect

**Comment by Ionitron** [comment] 2015-05-16 00:22
Greetings @Rakonda!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-05-16 00:22 UTC
Labels: ionitron:closed
