### ISSUE TITLE
bug: bug: select text is getting cut off

### ISSUE THREAD

**Issue by hypery2k** [driftyco/ionic#3541] opened 2015-04-17 07:26 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Select text is cut with rc3:
![options](https://cloud.githubusercontent.com/assets/979121/7197634/7fb3af82-e4e3-11e4-889e-66bd13f9aca9.png)
Have to use this
```
.item-select select {
  padding: 14px 48px 8px 16px;
}
```</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-04-17 07:26
Greetings @hypery2k!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3541). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3541)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by adamdbradley** [comment] 2015-04-17 15:08
Did you change the height of the item row? If so I think having to add custom css is fine here.

**Comment by hypery2k** [comment] 2015-04-17 16:31
No, no custom height. It works with rc0

**Comment by emilyemorehouse** [comment] 2015-06-09 12:54
Any reason why this was closed? I'm having the same issue with a select box. Worked fine with rc0, but the descender is cut off after upgrading to 1.0.0.

Side note: the padding applied is the same between the two versions, it's the actual height of the element that differs. I couldn't track down what was causing this.

**Comment by vzdevopstraining** [comment] 2015-08-10 20:27
I am with @emilyemorehouse as I am still having issues with the select boxes. I used bower and got this version ```driftyco/ionic-bower#v1.0.0"```.

Even when I look at the examples site ( http://ionicframework.com/docs/components/#select ) I see the issue. (See attached image...)

![Select Issue](https://cloud.githubusercontent.com/assets/10342761/9183345/8a40e5ca-3f7c-11e5-93af-3cb0d133eefb.PNG)

**Comment by itomaldonado** [comment] 2015-08-10 20:29
I am with @emilyemorehouse as I am still having issues with the select boxes. I used bower and got this version driftyco/ionic-bower#v1.0.0".

Even when I look at the examples site ( http://ionicframework.com/docs/components/#select ) I see the issue. (See attached image...)

![Select Issue](https://cloud.githubusercontent.com/assets/8411264/9183418/ed7f7796-3f7c-11e5-80f7-1e5ea5400d63.PNG)

**Comment by mhartington** [comment] 2015-08-10 20:34
I see what the issue is, will take a look at it in the AM.

**Comment by itomaldonado** [comment] 2015-08-10 20:37
Cool, thanks @mhartington. let use know~

**Comment by mhartington** [comment] 2015-08-11 16:18
Should be fixed in master

**Closed** 2015-08-11 16:18 UTC

**Comment by itomaldonado** [comment] 2015-08-11 18:29
Hey preliminary tests seem to work. Before this change the CSS padding was: ```padding: 16px 48px 16px 16px;``` now I have ```padding: 0 48px 0 16px;``` and I don't see the letters being cut. I'll test as soon as I get home. Thanks @mhartington!

**Comment by zhouhao27** [comment] 2016-02-04 12:28
Still have the problem in  latest ionic.

**Comment by mhartington** [comment] 2016-02-04 14:25
@zhouhao27 can you provide a demo of this?
