### ISSUE TITLE
bugs:$state.go not located on the top floor [v1.21]

### ISSUE THREAD

**Issue by fanspace** [driftyco/ionic#4845] opened 2015-12-22 08:56 UTC
it's worked normally with v1.1,  but when update to v1.2
use $state.go  like that
: var objpara = { imgurl: data };
  $state.go("capture", objpara);
it noting to happend ,but when i use back button, i found
the activity 'capture' is behind the current activity
finally  i found  it happend when  click button with in a modal
with v1.1  the modal will  close and goto next state
v1.2  the modal will not close automatically

**Comment by Ionitron** [comment] 2015-12-22 08:56
Greetings @fanspace!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4845). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4845)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by jgw96** [comment] 2016-03-14 18:57
Hello! Thanks for opening an issue with us, we just need a little more info from you so that we can better help you with your issue. Would you mind posting a code sample, plunkr or codepen that we can use to reproduce your issue? Also, would you mind running `ionic info` and posting the output? Thanks again!

**Comment by jgw96** [comment] 2016-04-14 17:05
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to respond back if your still having the issue! Thanks again!

**Closed by jgw96** 2016-04-14 17:05 UTC
Labels: navigation, v1
