### ISSUE TITLE
bug: listView._startDrag - Uncaught TypeError: Cannot read property 'freeze' of null

### ISSUE THREAD

**Issue by nantunes** [driftyco/ionic#3926] opened 2015-06-11 23:11 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Issue open as requested by @mhartington in https://github.com/driftyco/ionic/issues/3174#issuecomment-110443650.

PR #3837 

Can you provide a detailed description of this issue?
The error ''Uncaught TypeError: Cannot read property 'freeze' of null" appears in the console when dragging an element inside a ion-list item.

How would a robot go about replicating this issue?
I have created a codepen that reproduces the error: http://codepen.io/nantunes/pen/LVLmRJ

Steps to reproduce:
Open the dev tools console and just drag one of the images to the left.

On which platform does this happen occur? (iOS, Android, all, etc.)
On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
Tested in Chrome, but probably occurs in all platforms, given the related issue #3174.

Is this an issue with the Ionic Framework or Ionic CLI?
Ionic Framework.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-06-11 23:11
Greetings @nantunes!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3926). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3926)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment] 2015-06-16 20:27
So the issue is because you do not have an ion-content wrapping the list. 
If you wrap the ion-list with the ion-content, the error goes away.
http://codepen.io/mhartington/pen/aOyjYZ

Why this is happening. 
This happens because the swipe buttons should prevent scrolling when they are being swiped. So the call a method on the $ionicScrollDelegate. The issue here is that there is no ion-content/$ionicScrollDelegate. So it throws an error.

Your app won't break, but it will just have an error.

**Closed by mhartington** 2015-06-16 20:27 UTC

**Comment by nantunes** [comment] 2015-06-17 16:21
Thanks @mhartington, that solves my problem without keeping a private patch.

But it seems the directive's $ionicScroll require is marked as optional (https://github.com/driftyco/ionic/blob/6c9bc15b2996ae9183624c84a2709fd33f80d20b/js/angular/directive/list.js#L90) and I didn't notice such dependency referred in the docs.

Is it necessary/recommended to always wrap the ion-list or only when enabling swipe?

**Comment by nantunes** [comment] 2015-07-23 15:30
Ok, closed PR #3837.
