### ISSUE TITLE
searchbar can't enter chinese characters at ios

### ISSUE THREAD

**Issue by wangzailong** [driftyco/ionic#11744] opened 2017-05-22 03:05 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[ ] **2.x**
[ x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

when i use seachbar at ios,it can't enter Chinese characters
**Related code:**

```
insert any relevant code here
![65823092352236116](https://cloud.githubusercontent.com/assets/23051171/26291027/15f9ae0a-3ede-11e7-90f3-6f7d4629f3bd.jpg)

```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by CloverEc** [comment] 2017-05-22 03:46
Me, too. Japanese same

**Comment by jgw96** [comment] 2017-05-22 14:59
Hello, thanks for opening an issue with us. I am going to close this as a duplicate of https://github.com/driftyco/ionic/issues/11566.

**Closed by jgw96** 2017-05-22 14:59 UTC
