### ISSUE TITLE
bug: When using popToRoot can't use Bar buttons

### ISSUE THREAD

**Issue by MatanYed** [driftyco/ionic#7957] opened 2016-09-02 19:23 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>After using navCtrl.popToRoot() or navCtrl.setRoot(HomePage), the buttons on the root bar not clickable (click won't run the (click) function, and there is no pointer cursor)

Video to understand:
https://drive.google.com/file/d/0B_2AM8ZhXhE9YjR0VGNnSXhycTQ/view</span>

<span is-issue-template></span>

**UPDATE**
It's not only the Bar stuck, it's the whole app, I can't click anything or even scroll...

**Comment by jgw96** [comment] 2016-09-02 19:39
Hello, thanks for opening an issue with us! Would you mind posting a repo that I can use to reproduce this issue? Thanks!

**Comment by MatanYed** [comment] 2016-09-02 19:42
@jgw96 I am sorry it's kinda private repo... Just create new project with 3 pages:
From first page go to second page, than to third page, than try to popRoot, popTo, or setRoot, this 3 functions will lock your bar buttons...

**Comment by MatanYed** [comment] 2016-09-02 19:42
I am very thankful for your listening and help!

**Comment by MatanYed** [comment] 2016-09-03 05:48
**UPDATE**
It's not only the Bar stuck, it's the whole app, I can't click anything or even scroll...

**Comment by jgw96** [comment] 2016-09-06 14:11
Hello @MatanYed unfortunately I cannot seem to reproduce this issue. Would you mind creating a minimal example in a repo that I could use to reproduce this issue?

**Comment by MatanYed** [comment] 2016-09-06 14:15
@jgw96 i cant do it right now, only in 3 days i would
Can you try add toast before popToRoot? Maybe there is the problem

**Comment by devarg** [comment] 2016-09-07 23:09
@MatanYed  I found out that the ionic toast (ToastController from ionic-angular) interferes with the presentation of other overlays such as loading (LoadingController), I would try to dismiss the toast before going on transitions of this kind, but I bet there's something going on.

**Comment by jgw96** [comment] 2016-09-08 16:17
Hello! So after looking at this issue if your are displaying a toast before doing `popToRoot` it is going to cause the app to "freeze" in beta.11. This issue has actually already been fixed on master and will be in the beta.12 release. @MatanYed Would you mind removing the toast or closing it before doing `popToRoot` and seeing if you can still reproduce the issue?  Thanks!

**Comment by jgw96** [comment] 2016-09-12 15:58
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-09-12 15:58 UTC
Labels: needs reply, v2

**Comment by MatanYed** [comment] 2016-09-13 17:43
@jgw96 Without the toast it's ok. Waiting for beta.12
