### ISSUE TITLE
Keyboard Hiding Inputs Problem

### ISSUE THREAD

**Issue by calendee** [driftyco/ionic#365] opened 2014-01-06 17:50 UTC
See this post on the forums.

http://forum.ionicframework.com/t/scroll-to-the-focused-item-input-when-the-keyboard-is-up/422

**Comment by tinhNOIS** [comment] 2015-02-26 02:34
Hi, I have problem keyboard on Android. Its is covering the textbox
![43f9a210-9cce-11e4-9cd8-c551f27a6253](https://cloud.githubusercontent.com/assets/8913872/6385306/9723908a-bd9a-11e4-9c9f-2db792830bc2.png)

**Comment by samuelcastro** [comment] 2015-04-11 02:29
I have the same problem, I tried every things but not working yet.

**Comment by akonya** [comment] 2015-04-25 21:48
Having same problem as well.  Tabs move up to top of keyboard when clicking an input field.

**Comment by dscx** [comment] 2015-05-12 22:55
@akonya assuming you have the ionic keyboard plugin, try adding an event listener for when the input is selected / focused, and call `cordova.plugins.Keyboard.disableScroll(true);`

**Comment by shahswapnil** [comment] 2015-05-28 09:41
Hi guys 
 i know this issue is closed but still i am getting this problem

this is are my version what i am using

ionic info
Cordova CLI: 5.0.0
Ionic CLI Version: 1.4.5
Ionic App Lib Version: 0.0.22
OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.2 LTS 
Node Version: v0.12.3

ionic plugin ls
Updated the hooks directory to have execute permissions
com.ionic.keyboard 1.0.4 "Keyboard"
cordova-plugin-crosswalk-webview 1.2.0 "Crosswalk WebView Engine"
cordova-plugin-inappbrowser 1.0.1-dev "InAppBrowser"
cordova-plugin-legacy-whitelist 1.0.0 "Legacy Whitelist"
cordova-plugin-whitelist 1.0.0 "Whitelist"
org.apache.cordova.device 0.3.0 "Device"
org.apache.cordova.splashscreen 1.0.0 "Splashscreen"

**Comment by zapnap** [comment] 2015-06-24 14:51
I'm still seeing this issue as well, using Ionic 1.0.0, on Android.

**Comment by grantgumina** [comment] 2015-06-25 01:26
I'm also experiencing this issue. Any updates?

**Comment by saurabhgupta050890** [comment] 2015-06-26 14:26
Still this issue in Ionic 1.0.0

**Comment by ResuRRectorX** [comment] 2015-06-29 11:28
Keyboard is pushing the content upwards..

**Comment by tlancina** [comment] 2015-06-30 14:06
For people having issues with the keyboard, take a look at the docs for
some tricks for iOS and Android:
https://ionicframework.com/docs/nightly/api/page/keyboard/

**Comment by zapnap** [comment] 2015-06-30 23:26
hide-on-keyboard-open is not a solution to this. And I can't imagine the vast majority of people want their apps to be fullscreen (no status bar). Am I missing something else there?

**Comment by tlancina** [comment] 2015-06-30 23:57
@zapnap do you have adjustResize in your AndroidManifest.xml?

Feel free to post a codepen that reproduces the issue, along with what device and version of Android you're using and we can take a look.

**Comment by JerryBels** [comment] 2015-07-29 09:07
Just a quick note, if it can help narrow down the issue : it can be linked to the native scrolling. If you defined : 

    $ionicConfigProvider.scrolling.jsScrolling(false);

for Android, try without and report here.

**Comment by seyuf** [comment] 2015-07-31 14:39
Thanks, @JerryBels this solved the issue for me. But i was using the native scrolling by default because the ionic one was too slow. Any ideas on how to solve that?

**Comment by seyuf** [comment] 2015-07-31 14:44
Oh after reading the merges above i found the solution. When using the native scrolling, you have to double tap the input field in order to have the right behavour (no hidden fields).

**Comment by seyuf** [comment] 2015-07-31 15:04
This issue have been fixed in the leatest release v1.0.1, we now use native scroll with the keyboard!

**Comment by JerryBels** [comment] 2015-08-02 19:45
Nice ! I will upgrade :)

**Comment by seyuf** [comment] 2015-08-03 11:51
@JerryBels, i forgot to mention, there is a bug in the v1.0.1. The scrolling is not working in natively under android v4 Lol, hopefully this will be fixed soon (T-T).

**Comment by JerryBels** [comment] 2015-08-03 11:57
@seyuf Awww :/ There is a thread about this bug ?

**Comment by seyuf** [comment] 2015-08-03 12:18
@JerryBels  Yep #4064

**Comment by ssharmass** [comment] 2015-10-16 12:37
Hi All,
    I followed your doc to get task of appear textarea over keyboard which is inside ion-footer ,but it is not working , any one has something related that, please let me know.


Thanks

**Comment by vko-online** [comment] 2015-10-23 17:02
This is still an important issue though. Any workaround?

**Comment by alexszilagyi** [comment] 2015-10-29 13:10
@vko-online : somehow I've managed to find a possible workaround but I must admit that there are some cases that the keyboard shows up.

Here's my config:
**app.js file**
```javascript
angular.module('coraxApp', ['ionic', 'ngStorage', 'ngCordova', 'ngAnimate'])
  .run(function($ionicPlatform, $cordovaFile) {
    $ionicPlatform.ready(function() {
      ionic.Platform.isFullScreen = false;
})
.config(['$localStorageProvider', '$stateProvider', '$httpProvider', '$urlRouterProvider', '$locationProvider', '$compileProvider', '$ionicConfigProvider', function($localStorageProvider, $stateProvider, $httpProvider, $urlRouterProvider, $locationProvider, $compileProvider, $ionicConfigProvider) {
    $ionicConfigProvider.scrolling.jsScrolling(false);
}]);
```
**config.xml file**
```xml
  <preference name="android-windowSoftInputMode" value="adjustPan|stateAlwaysHidden" />
  <preference name="Fullscreen" value="false" />
  <preference name="KeyboardDisplayRequiresUserAction" value="true" />
```

**Comment by mrft** [comment] 2016-01-09 14:34
Here is a description of my problem: https://forum.ionicframework.com/t/inputs-scrolling-and-the-onscreen-keyboard-on-android/40730

I have tried about every suggestion I found here, on stackoverflow, in the ionic forums etc.
It still doesn't work, and honestly, I don't understand why it doesn't 'just work' when you create a new skeleton app using the ionic cli and when using some simple ionic directives.

If I put everything in a simple div, it looks horrible, and I don't have a header-bar etc. but at least on the phone, the keyboard simply works as you'd expect. Now it would be nice if I could make it a bit more pleasing to the eye.

**Comment by mlynch** [comment] 2016-01-09 16:07
@mrft I'm digging in here. Did you just create the project, of was it a few weeks ago? 1.2.4 did address some issues.

Can you try with this markup for the form input: 

```html
<ion-input>
  <ion-label>label</ion-label>
  <input...
</ion-input>

**Comment by mrft** [comment] 2016-01-09 17:51
@mlynch I created a [github repository](https://github.com/mrft/ionicApp_ContentScrollKeyboardInputTest) that contains an example of my problem.

Maybe this can help improve things, and if I check your fork, I can check what the differences are between your and my version.

**Comment by mlynch** [comment] 2016-01-10 03:28
Hey @mrft, I'm testing that template (couldn't get your demo to build and run, unfortunately), and I'm not seeing the issue. Here's a video of me testing in an emulator: http://ionic-io-assets.s3.amazonaws.com/keyboardtest.mov

So, a few things. Can you verify that what you're seeing in my video is good behavior, and that you're seeing something else in your running? Also, can you verify you're using the most recent version of Ionic to test? There were some issues in 1.2.x before 1.2.4, unfortunately.

If so, I might need to get a real device matching yours to test on, and make sure my emulator is running the right version of Android to trigger it. Or, it might have been resolved and we can go on our merry way :) Thanks so much for the help!

**Comment by mrft** [comment] 2016-01-10 11:28
Yep I am definitely seeing something else.

Here is a [video that shows the behaviour I experience](https://drive.google.com/file/d/0Bzvvytzvs12fVXFQOENrb1oyVkk/view?usp=sharing)

As you can see in my repo, I did update the bower.json file to use 1.2.4, renamed ionic under www.lib, and did a bower install, so afaik I am using ionic 1.2.4.

Don't hesitate to create a ticket describing your problem with building that project, because I have read so many things that could potentially influence the behaviour that if you just use the same template, we don't know if everything else is the same (ionic.project, bower.json, angular.module('myApp').run, angular.module('myApp').config, ... )

I also tested it on a more recent Motorola E running Android 5.0.2, and everything actually did work as expected.

*I couldn't get an emulator to run 4.0.3 (it's still 'Booting up emulator (this may take a while)' after > 30 minutes, the Android 5 emulator I tried before did work).*

**Comment by mlynch** [comment] 2016-01-10 16:02
@mrft thanks so much for the video that really helps. If you set `<ion-content overflow-scroll="false"` do you still see that behavior?

Also, would be really interesting to see if crosswalk helps with that device version. Any chance of trying that?

**Comment by mlynch** [comment] 2016-01-10 16:04
Also, being pragmatic...that version of Android as about 2% worldwide usage, so it might very well be an issue with that version specifically but won't really impact users (as you say, this doesn't happen on newer versions of Android):

<img width="789" alt="screenshot 2016-01-10 10 03 00" src="https://cloud.githubusercontent.com/assets/11214/12222418/7a96c7f2-b781-11e5-9434-48e960f7b9ed.png">

**Comment by mrft** [comment] 2016-01-10 16:29
@mlynch Yeah I saw that pie chart today, so I realized that maybe it is not that important, but this happened to be a smartphone that I had lying around, so my first experiences with Ionic weren't making me too happy :)

overflow-scroll="false" makes it more predictable, in that I seem to be able to tap (select) the right field always, but the blue-line surrounded input field that appears and should perfectly overlay the text to allow editing (and show the user which field he is editing) is still way off (too low, most of the time hidden behind the keyboard), so you don't know that selecting that field for editing actually worked.

I had to lookup what crosswalk was (have to do some more reading).
How is it related to Ionic?

**Comment by mrft** [comment] 2016-01-10 16:45
@mlynch Yes I saw that pie chart today, so probably it is not that important, but since I had that phone lying around, and used it for my first-ever test with ionic, you can imagine that my first experience wasn't making me too happy, let alone confident that ionic was the way to go :)

Anyway, <code>overflow-scroll="false"</code> did make it more predictable, because wherever I tapped the screen seemed to actually match the field underneath it, but the blue-line input field that appears as a result of that, to show the user which field he is editing still was way off (almost always hidden behind the keyboard so you don't even know it's there). So if you type, you can only assume to which field the input will go. So, better, less frustrating, but not working 100%.

Had to google what crosswalk is, and need to do some more reading about it. How is it related to Ionic?

Thanks for your help so far!

**Comment by mlynch** [comment] 2016-01-10 16:56
@mrft totally get that, and I hate that this was your first experience and it sucked :(

Unfortunately, the older 4.0.x phones were really inconsistent and the browser shipped with them had a number of odd issues. Thankfully, those have been addressed.

Crosswalk is basically modern chrome for web views and mobile web apps. You can see how to use it here: http://ionicframework.com/docs/cli/browsers.html

I'm going to close this for now since I can't reproduce on a supported device platform, but I'll keep tracking this in case you have more info and I'll try to get my 4.0 emulator to load (I had the same issue you had with it not booting or loading an app).

**Closed by mlynch** 2016-01-10 16:56 UTC
Labels: in progress, keyboard/focus

**Comment by leopiazzoli** [comment] 2016-03-24 18:38
Thank's @mlynch - RESOLVED
```
<ion-input>
  <ion-label>label</ion-label>
  <input...
</ion-input>
```

**Comment by Hypher** [comment] 2016-05-12 00:07
Got keyboard hiding fields issue on Android 4.2.2, ionic 1.7.14 in a form in a scrollable $ionicModal.

`ionic.Platform.isFullScreen = true;` did something, but still way from perfect (take 3 whole seconds to get in the right position, and sometimes scroll up the content too much showing a white rectangle between the keyboard and the content).
Can post screens if asked.

Note that in this very same modal I display 2 forms. The first is short enough to fit in the screen (no scroll) and the problem appears. The second make the content to scroll, and there is no problem, even with the bottom fields.
I added a blank div under my form to make the content able to scroll (at least the user could scroll to see the hidden inputs, which it could not do either), and it fixed the problem.

The 3 seconds delay is still an issue.

**Comment by rahul-sdei** [comment] 2016-06-29 11:12
Where do i put ionic.Platform.isFullScreen = false; in meteor + ionic

**Comment by blacksmith77** [comment] 2017-05-31 11:28
Found a solution here: https://stackoverflow.com/questions/32730171/ionic-footer-input-field-being-hidden-by-keyboard-in-chat-app

set "fullscreen" property to "false" in config.xml

> This goes out out to anyone that's had a similar problem with the ionic footer and inputs in cordova build. If you have this preference in config.xml
> 
>  <preference name="fullscreen" value="true" /> 
> 
> The keyboard will hide the input when it's activated. If you absolutely need to see that input when typing (that was a joke) than just set it to false and it should solve the problem.
>

**Comment by manikandan07081995** [comment] 2018-02-23 09:44
I need virtual keyboard for ionic browser application.Can any one help me.I am using typescript for ionic development.

**Comment by sreekanth-karini** [comment] 2018-07-30 13:19
Just add this properties to your ionicModule in app.module.ts. works for me.
```
IonicModule.forRoot(MyApp, {
      scrollAssist: false, 
      autoFocusAssist: false
    })
```
