### ISSUE TITLE
bug: onDidDismiss on Alert not called

### ISSUE THREAD

**Issue by ThorConzales** [driftyco/ionic#7814] opened 2016-08-22 08:21 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>6.0</span>  <span ionic-webview>webview</span>

<span ionic-description>On android when hardware back button is pressed to dismiss the Alert then onDidDismiss and onWillDismiss is not called. Expected behavior is to listen to that event when Alert gets dismissed whatever means available.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment] 2016-08-22 16:28
Hello! Thanks for opening an issue with us! I will be closing this issue as a duplicate of https://github.com/driftyco/ionic/issues/7224. Thanks for using Ionic!

**Closed by jgw96** 2016-08-22 16:28 UTC
Labels: alert, platform:android, v2
