### ISSUE TITLE
Scrolling inside Slide

### ISSUE THREAD

**Issue by raul07kry** [driftyco/ionic#10960] opened 2017-03-29 10:48 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Hello, I have slides with vertical sliding direction. Inside one of the slides I have the list with the scroll. When I try to scroll the list, the whole slide slides to the next slide. In previous version of slides, I've added noSwipingClass to my list and everything worked like a charm. Now I can't do such thing because of the new uber-crippled slides. Is there any solution to this or do I have to throw away my whole project?

**Expected behavior:**
Scrolling list inside slide instead of swiping to the next slider.

**Steps to reproduce:**
Put a list inside slider. Same scrolling direction for the list and slider.

**Comment by jgw96** [comment] 2017-03-29 14:16
Hello, thanks for opening an issue with us and sorry slides are not working like they should, we will look into this. Is this happening in 2.3.0? @manucorporat is this possibly happening because of the scroll events issues in 2.3.0?

**Comment by jgw96** [comment] 2017-04-07 16:06
Hello, thanks for using Ionic. After further review I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/6301.

**Closed by jgw96** 2017-04-07 16:06 UTC
Labels: v2
