### ISSUE TITLE
SwipeBackEnabled on modals Ionic 2

### ISSUE THREAD

**Issue by denkomanceski** [driftyco/ionic#6099] opened 2016-04-09 15:13 UTC
Hi, is there any way how to disable swipe-back on specific page in Ionic 2 ? I have Modal that goes down when swiping to go back which is annoying. Help ?
I tried both:
```
swipe-back-enabled="false"
can-swipe-back="false"
```

but doesnt work. I tried going through the code but I am not able to find how to fix this.. if i set swipe-back-enabled to false it works for normal pages (nav.push), but it doesnt for modals

**Comment by danielcrk-cn** [comment] 2016-04-10 11:19
I'm wondering the same thing, the swipe-back function is a bit buggy right now (e.g. the page that it beiing swiped away is still scrollable) so I'd like to be able to disable it globally.

**Comment by thiphariel** [comment] 2016-04-11 12:36
Seems this one and #6117 are pretty much related... :)

**Comment by manucorporat** [comment] 2016-04-11 15:55
@denkomanceski @danielcrk-cn the correct attribute is `swipeBackEnabled`.

```html
<ion-nav id="nav" [root]="root" #content swipeBackEnabled="false"></ion-nav>
``

**Comment by macav** [comment] 2016-04-26 14:48
For me the swiping back freezes a lot, is this related?
![img_2016-04-26 16 47 04](https://cloud.githubusercontent.com/assets/3784696/14822353/a21e2f6c-0bce-11e6-9497-6c4ec22951d2.jpg)

**Comment by macav** [comment] 2016-04-26 14:50
for me the swiping freezes a lot, is this related?
<img width="372" alt="screen shot 2016-04-26 at 16 49 24" src="https://cloud.githubusercontent.com/assets/3784696/14822415/ea21b734-0bce-11e6-875b-46aac5ea8b0a.png">

**Comment by danielcrk-cn** [comment] 2016-05-03 11:02
@manucorporat unfortunately swipeBackEnabled="false" does not work for me, swipeBack is still enabled. Have you successfully managed to disable it?

My ion-nav-component looks like this:
<ion-nav id="nav" [root]="rootPage" swipeBackEnabled="false"></ion-nav>

**Comment by iaguilera14** [comment] 2016-06-15 14:26
Does anyone have a solution to disable swipe to go back entirely? Even if it is a temporary one. Having a map on a page does not play well with this feature. Ill even edit the ionic.js file if I need to. I just don't know where to look. 

I can confirm that the below code does not work:
`<ion-nav id="nav" [root]="rootPage" swipeBackEnabled="false"></ion-nav>`

**Comment by manucorporat** [comment] 2016-06-15 14:46
hi @iaguilera14 can you make a plunker demonstrating that swipeBackEnabled does not work?
I am very busy fixing some issues for next release and it would really help me!

You can start from the template: http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview

**Comment by iaguilera14** [comment] 2016-06-15 15:26
No problem @manucorporat . I was able to reproduce it simply by switching the application to a tabs setup. I used the suppled tabs.ts and tabs.html. It seems that the swipeBackEnabled works when not using tabs, but is overridden when using tabs. Perhaps because tabs have their own navigation stack?

[http://plnkr.co/edit/fB3VofAwyYoFcEF009Co](http://plnkr.co/edit/fB3VofAwyYoFcEF009Co)

Note: I was using mobile safari on an iPhone to test this plunker. Let me know if there is a way around this for now. I can't seem to find one. I tried adding swipeBackEnabled to the actual tabs component and that didn't seem to work either.

**Comment by manucorporat** [comment] 2016-06-16 09:51
@iaguilera14 fixed: https://github.com/driftyco/ionic/pull/6934

**Comment by iaguilera14** [comment] 2016-06-16 14:07
Awesome! Thanks!

**Comment by jgw96** [comment] 2016-06-16 15:06
Hello all, since it looks like this was fixed by @manucorporat i will be closing this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-06-16 15:06 UTC
Labels: navigation, v2
