### ISSUE TITLE
bug: Cannot turn off navbar animation

### ISSUE THREAD

**Issue by wlingke** [driftyco/ionic#3112] opened 2015-02-14 00:35 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>How do you turn off animations in the navbar as a result from 'ng-hide' and 'ng-show'? I have set $ionicConfigProvider.navBar.transition('none') but this doesn't solve the problem.

My current hack is to use ng-if</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-02-16 14:18
Greetings @wlingke!

My sensors indicate that I require more information in order to assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this happen occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com), where many humans will be able to offer wisdom and advice.

Thank you for allowing me to assist you.

<span ionitron-needs-reply></span>

**Comment by Ionitron** [comment] 2015-03-18 15:59
Greetings @wlingke!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment] 2015-03-18 15:59
Greetings @wlingke!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-03-18 15:59 UTC
Labels: ionitron:closed
