### ISSUE TITLE
Wrong width of text-input for iOS (in modal)

### ISSUE THREAD

**Issue by adam-sokolowski** [driftyco/ionic#7388] opened 2016-07-21 07:01 UTC
`ionic/src/components/input/input.ios.scss`

For wider screens with iOS (iPad) text-input field does not stretch to the width of parent container (fills only about a half of the width).

.text-input class width is calculated the following way:
`width: calc(100% - #{$text-input-ios-margin-right} - #{$text-input-ios-margin-left});`

However, the default value for `$text-input-ios-margin-left` is 0 - and this is actually causing the problem. Lets assume, that `$text-input-ios-margin-right` equals 8px. 

The result is: 
`width: calc(100% - 8px - 0);` - which is invalid property value. 

Solution - replacing:
`$text-input-ios-margin-left:               0 !default;`
by
`$text-input-ios-margin-left:               0px !default;`

Expected result: 
Text-input field filling all available space of parent container (minus paddings)

Ionic : 2.0.0-beta.10
Platform: iOS

**Comment by brandyscarney** [comment] 2016-07-21 18:17
Thanks for the issue! Could you paste some sample html markup that I can use to reproduce this? Thanks. :smile:

**Comment by adam-sokolowski** [comment] 2016-07-22 05:48
yes, sure . here is the plunker:
http://embed.plnkr.co/yaqTLbYZ8JtF9J7kVa7K/
![ios_text_input_1](https://cloud.githubusercontent.com/assets/14870604/17047705/b54aff42-4fe0-11e6-8d2e-f3e028d3368f.jpg)

**Comment by jgw96** [comment] 2016-08-09 20:56
Hello @adam-sokolowski ! Is this still an issue with beta.11? Thanks!

**Comment by jgw96** [comment] 2016-08-14 05:27
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by adam-sokolowski** [comment] 2016-08-16 13:51
Yes, this still an issue.

**Closed** 2016-10-24 21:54 UTC
Labels: v2
