### ISSUE TITLE
range slider doesn't work as expected in app on iOS

### ISSUE THREAD

**Issue by tingrisch** [driftyco/ionic#8777] opened 2016-10-18 15:42 UTC
There are two input text fields and a range slider on our page (screenshot below). First time the range slider is working well. If you click into the textfield most of the elements will be hide (ng-if) and a textfield with a suggest is showing. Then you close the suggest textfield view. Then the same view like in the screenshot below will be shown. But now you **can't change the slider** anymore.

![screenshot](https://cloud.githubusercontent.com/assets/569025/19483758/bf9d0fca-9555-11e6-9a06-08fa7a6e600e.png)

It's the same case as described above in the screenshot below (In this case it's a modal view.):

![screenshot1](https://cloud.githubusercontent.com/assets/569025/19484435/e2b826d2-9557-11e6-8818-d53a8b2f9d56.png)

This issue **only happens** in the **iOS app**. Android app and browser are ok.

Below is the code of the range slider:
```
<!-- Distance Search -->
<div ng-if="search.showWhatInputField && search.showWhereInputField"
	 class="jam-dist-slider">
	<span class="input-label jam-label-text jam-top-margin">
		Umkreis
	</span>

	<div class="item range">
		<input type="range"
			   name="distance"
			   min="0"
			   max="70"
			   value="30"
			   ng-model="search.distSlider"
			   ng-change="search.sliderChanged()"
			   on-release="search.trackSliderChange()">
		<div class="jam-distance"
			 ng-if="search.searchInput.dist == 0.5">
			{{ search.searchInput.dist * 1000 }} {{ search.distSliderUnit }}
		</div>
		<div class="jam-distance"
			 ng-if="search.searchInput.dist != 0.5">
			{{ search.searchInput.dist }} {{ search.distSliderUnit }}
		</div>
	</div>
	<!-- /Distance Search -->

	<button type="button" class="button button-block jam-search-button"
			ng-click="search.search()">
		Suchen
	</button>
</div>
```

I use the following:

- Cordova CLI: 6.3.1
- Ionic Framework Version: 1.2.4-nightly-1917
- Ionic CLI Version: 1.7.16
- Ionic App Lib Version: 0.7.3

Maybe it has to do with this issue: [https://github.com/driftyco/ionic/issues/4628](url)???

**Comment by jgw96** [comment] 2016-10-18 18:23
Hello, thanks for opening an issue with us! Would you mind posting a repo we can use to reproduce this issue?

**Comment by jgw96** [comment] 2016-10-25 15:28
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-10-25 15:28 UTC
Labels: needs reply, v2
