### ISSUE TITLE
bug: Select element in Windows 10 doesn't works in Remote Machine

### ISSUE THREAD

**Issue by jdnichollsc** [driftyco/ionic#4612] opened 2015-11-09 04:31 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi guys,

The "select" element doesn't works in my tablet with Windows 10, so I created the following directive:
http://codepen.io/jdnichollsc/pen/meKXQY

PD: any suggestions to the collection-repeat works well in Windows 10?

Regards, Nicholls</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-11-09 04:31
Greetings @jdnichollsc!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4612). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4612)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by jgw96** [comment] 2016-03-14 21:36
Hello! Thanks for opening an issue with us! Since this is a duplicate of https://github.com/driftyco/ionic/issues/4803 I will be closing this issue for now, but if it needs to be reopened feel free to do so!

**Closed by jgw96** 2016-03-14 21:36 UTC
Labels: platform:windows
