### ISSUE TITLE
iOS native scrolling PTR

### ISSUE THREAD

**Issue by perrygovier** [driftyco/ionic#4753] opened 2015-12-10 19:39 UTC
Pull to refresh with native scrolling on iOS does not currently work consistently when the view is large enough to be scrollable. 

Here's what I know after spending some time looking in to it. 
Immediately, [`canOverscroll` on line 73](https://github.com/driftyco/ionic/blob/master/js/angular/controller/refresherController.js#L73) is not false when it should be. This is because in [handleScroll](https://github.com/driftyco/ionic/blob/master/js/angular/controller/refresherController.js#L73) the `scrollTop` value during iOS's native overscrolling can be negative, equating to false.

Setting negative scroll top values to equate the same way as a `0` value would on lines 91, 108, and 139 gets further, but the `deltaY - dragOffset <= 0` part of the evaluation [on line 91](https://github.com/driftyco/ionic/blob/master/js/angular/controller/refresherController.js#L91) now calculates incorrectly too. This means overscrolling wont start until the user has dragged more than half the distance above `scrollTop` 0. `dragOffset` is not getting a correct value, which I believe is what causes this, but I have not yet investigated why. 

And down the rabbit hole we go :)

**Comment by mlynch** [comment] 2015-12-15 01:06
Hey @perrygovier, I'm not seeing the issue, do you have more info or a codepen that shows the issue?

**Comment by mlynch** [comment] 2015-12-15 01:10
Also, are you sure you aren't just seeing the whole browser frame scrolling and the PTR trying to also react to that?

**Comment by mlynch** [comment] 2015-12-15 01:11
![image](https://files.slack.com/files-pri/T024WJZKU-F0GKZMJ5U/slack_for_ios_upload.png)

**Comment by tomkelsey** [comment] 2015-12-15 10:21
Hi @mlynch,

I hope this helps!

Here is a repo that is basically the starter tabs demo with a longer chat list and pull to refresh added: https://github.com/tomkelsey/ionic-ptr-bug

Here is a video of the bug: https://www.youtube.com/watch?v=Z6zIQWBG-aU&feature=youtu.be

**Comment by perrygovier** [comment] 2015-12-16 15:50
@mlynch, @tomkelsey's video and code sample is what I'm seeing. The view pulling will only happen in the browser. Also, the browser uses WKWebView, which will fire scroll events differently. The bug still happens, but I believe the fix will require consideration of both kinds of scroll events.

**Comment by mlynch** [comment] 2015-12-17 01:24
Okay, so it occasionally isn't rendering on pull. Right?

**Comment by tomkelsey** [comment] 2015-12-17 11:10
@mlynch yes, at least that's what I'm experiencing - in the example I posted it actually doesn't work more often than it does.

I had a look using Safari's debugger and it seems as if the ion-refresher is incorrectly stuck with the `invisible` class.

**Comment by mlynch** [comment] 2015-12-17 15:22
k I can reproduce. Thanks

**Comment by mlynch** [comment] 2015-12-17 15:54
Should be fixed now. Mind trying master?

**Closed** 2015-12-17 15:54 UTC
Labels: iOS, pull-to-refresh, ready, scroll

**Comment by tomkelsey** [comment] 2015-12-18 09:41
@mlynch looks like you've nailed it - can't get it to bug anymore. Thanks!
