### ISSUE TITLE
sometimes `drag right` operation make app unresponsive in ios

### ISSUE THREAD

**Issue by izee** [driftyco/ionic#9632] opened 2016-12-14 08:57 UTC
**Ionic version:** 
Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: OS X El Caption
Node Version: v6.5.0
Xcode version: Xcode 7.3.1 Build version 701014

**I'm submitting a ...** 
bug report

**Steps to reproduce:**
1. `drag right` to make page back transit
2. sometimes no back transit happened, and then app unresponsive.

**Comment by izee** [comment] 2016-12-14 09:33
Drag quickly will reproduce

**Comment by jgw96** [comment] 2016-12-14 23:07
Hello, thanks for opening an issue with us! Would you be able to provide a [plunker](http://plnkr.co/edit/GJte2b?p=preview) or a repo that demonstrates this issue? Thanks for using Ionic!

**Comment by izee** [comment] 2016-12-15 01:15
@jgw96 no plunker needed,all back-able pages has this issue.

**Comment by jgw96** [comment] 2017-01-25 15:19
Hello all? I am going to close this issue for now as I cannot reproduce with rc5. Thanks!

**Closed by jgw96** 2017-01-25 15:19 UTC
Labels: v2
