### ISSUE TITLE
Feature: ion-select using ion-picker-cmp

### ISSUE THREAD

**Issue by alan-agius4** [driftyco/ionic#8347] opened 2016-09-30 08:55 UTC
Would be nice to have the `ion-select` displaying the options in `ion-picker-cmp`, similar to the `ion-datetime` and similar to `native` 

Ie: Display the options of a select like; 
 
![image](https://cloud.githubusercontent.com/assets/17563226/18986258/5ff0d230-86fc-11e6-885b-c54e606fd3d6.png)

**Which Ionic Version?** 2

**Comment by jgw96** [comment] 2016-09-30 17:17
Hello! Thanks for using Ionic. I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/5424.

**Closed by jgw96** 2016-09-30 17:17 UTC
