### ISSUE TITLE
Display flex is not working on button in firefox

### ISSUE THREAD

**Issue by d691maurya** [driftyco/ionic#5978] opened 2016-03-29 08:32 UTC
I am developing a web app which should at least support all latest browsers. But sidemenu is looking different on firefox.

![screen shot 2016-03-29 at 1 53 41 pm](https://cloud.githubusercontent.com/assets/12238760/14102146/6fdaa32e-f5b6-11e5-95b3-e3ea3a696e11.png)
![screen shot 2016-03-29 at 1 55 35 pm](https://cloud.githubusercontent.com/assets/12238760/14102145/6fd8d512-f5b6-11e5-8e84-dedc47d88112.png)

Please see the issue at https://bugzilla.mozilla.org/show_bug.cgi?id=984869#c2. Is there any workaround/fix for this?

**Comment by manucorporat** [comment] 2016-03-29 12:47
@d691maurya please, run `ionic info` from terminal

**Comment by jgw96** [comment] 2016-03-29 14:30
Thanks for opening an issue with us! As stated above if you could post the output of `ionic info` that would be great!

**Comment by brandyscarney** [comment] 2016-03-29 22:37
Assuming that you are using v2. This was also reported here: https://github.com/driftyco/ionic/issues/5622

You may be able to use an `a` tag instead of a `button`, but this is something we need to fix internally.

**Comment by d691maurya** [comment] 2016-03-31 09:55
Here's the `ionic info`:

```
Your system information:

Cordova CLI: 6.0.0
Ionic Version: 2.0.0-beta.2
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
ios-deploy version: 1.8.5 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.4.1
Xcode version: Xcode 7.1.1 Build version 7B1005 
```

**Comment by jgw96** [comment] 2016-03-31 14:25
Hello @d691maurya ! Since this issue has already been reported in the issue brandy mentioned above I will be closing this one. As brandy said this is something we are currently working on and is caused by differences in Mozilla's implementation of Flexbox compared to other browsers. Thanks for using Ionic !

**Closed by jgw96** 2016-03-31 14:25 UTC
Labels: css, menus

**Comment by d691maurya** [comment] 2016-04-02 07:46
Thank you too.
