### ISSUE TITLE
ionicons folder not in assets when creating the project

### ISSUE THREAD

**Issue by Bandito11** [driftyco/ionic#8851] opened 2016-10-22 07:29 UTC
#### Short description of the problem:
I can't use all the icons that are in shown in the website here:
[http://ionicframework.com/docs/v2/ionicons/](url)
like the icon 'windows' for example. I use the same syntax as in the document but with no luck, 

Aside from that sometimes the font folder don't copy to the www folder. When that happens I can't see my icons on the screen. 

**Steps to reproduce:**
1. ionic start oroject --v2
2. ionic serve
3. no icons in the assets folder in the www folder. 

**Which Ionic Version?** 2

**Comment by Bandito11** [comment] 2016-10-22 07:34
I can't see all the icons in the app like the Windows icon :(

**Comment by jgw96** [comment] 2016-10-24 15:35
Hello, thanks for using Ionic! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic-app-scripts/issues/43.

**Closed by jgw96** 2016-10-24 15:35 UTC
