### ISSUE TITLE
Modal close not firing lifecycle events

### ISSUE THREAD

**Issue by aggarwalankush** [driftyco/ionic#8543] opened 2016-10-06 15:45 UTC
#### Short description of the problem:
I'm showing a modal from my page. In beta 11, when I close modal, it used to fire ionViewWillEnter/ionViewDidEnter events of parent page but in rc0, it's not.

#### What behavior are you expecting?
Is it expected behavior?

**Steps to reproduce:**
Show modal from a page with lifecycle events 

**Which Ionic Version?** 1.x or 2.x
Ionic 2 rc0

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.7.0
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by jgw96** [comment] 2016-10-07 14:53
Hello, thanks for opening an issue with us! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/8414.

**Comment by aggarwalankush** [comment] 2016-10-07 15:15
@jgw96 seems like in https://github.com/driftyco/ionic/issues/8414 ionViewDidLoad of Modal page is not called, but in my case, parent page events are not called when modal is closed.

**Comment by manucorporat** [comment] 2016-10-12 16:41
Fixes

**Closed by manucorporat** 2016-10-12 16:41 UTC
