### ISSUE TITLE
bug: Closing select dialog triggers onPageWillEnter

### ISSUE THREAD

**Issue by danbucholtz** [driftyco/ionic#5516] opened 2016-02-18 22:16 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I have an @Page component with a form.  I am using the ion-select component.  After I make my selection and close the dialogue, it calls onPageWillEnter again.  This seems like a bug to me.

It is very easy to reproduce.  If you need code I can give you code.  This is with beta1 npm module.</span>

<span is-issue-template></span>

**Comment by alexbainbridge** [comment] 2016-02-18 23:06
On a similar point, I have onPageWillEnter firing after closing an alert. Not sure if that is as designed, caught me out for a while

**Comment by adamdbradley** [comment] 2016-02-19 15:23
Ok, I think I see the problem, where when a modal/alert/actionsheet is technically another page that loaded in the nav stack, and when it's removed then the page before it "entered" again. For sure the ion-select probably shouldn't do this, since conceptually it's apart of the page. That's also debatable for alert and actionsheet. However, for modal the previous page should onPageWillEnter. I'll add it to beta2 and take a look, thanks.

**Comment by danbucholtz** [comment] 2016-02-19 15:57
From my perspective, an Alert is just an alert, not a page.

I guess I view it as fundamentally different than a Modal, where my Modal *does* take a Page component as a parameter and display that.  When I close a Modal, I would expect the underlying page's onPageWillEnter to be called.

It's interesting though - I am not so sure I would feel that way in a master/detail view, so iPad or decent sized browser.  It may be worth looking at what Cocoa Touch does and when it calls viewWillAppear.

**Comment by alexbainbridge** [comment] 2016-02-19 16:24
If not too onerous, that leads to a thought - perhaps have onViewWillEnter for a view entry event (including after closing alerts, actionsheets, selects), and onPageWillEnter for where its a page, with a page constructor (i.e. excluding alerts, actionsheets, selects)

**Comment by adamdbradley** [comment] 2016-02-19 18:07
Awesome thanks for the issue, I think this is a good update. So now alerts, actionsheets and ion-selects, won't fire the active page's lifecycle events. Thanks!

**Closed by adamdbradley** 2016-02-19 18:07 UTC
Labels: navigation, select, v2
