### ISSUE TITLE
[2.0.0-rc.1] Menu gestures seem to interfere with menu toggle button for overlay menus.

### ISSUE THREAD

**Issue by JustinPierce** [driftyco/ionic#8778] opened 2016-10-18 16:29 UTC
#### Short description of the problem:

When using an overlay-style menu (Android default), the slide-to-open gesture interferes with the proper operation of the menu toggle button. In a browser (I haven't made it to a device, yet), clicking the menu toggle flashes the screen gray. The toggle only functions correctly on its very right edge, where the gesture interpreter does not cover it.
#### What behavior are you expecting?

Clicking the menu toggle button should open the menu.

**Steps to reproduce:**
1. Start a sidemenu project (`ionic start menu-test sidemenu --v2`).
2. Run it.
3. Click the center of the menu toggle. The menu should not open.
4. Click the very right edge of the menu toggle (the HTML padding). The menu should open as expected.

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
I did some light debugging on this to try to find the source of the issue, and found that the breakpoints that I set in `ionic-angular/components/menu/menu-gestures.js` were being tripped when I clicked on the menu toggle, but the `toggle` function in `menu-toggle.js` was not.

I have reproduced this problem in the `sidemenu` starter without any modifications.

**Which Ionic Version?** 1.x or 2.x

2.0.0-rc.1
#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

**For Ionic 2 issues** - http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

```
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS:
Node Version: v5.12.0
```

**Comment by jgw96** [comment] 2016-10-18 18:34
Hello, thanks for opening an issue with us! Unfortunately I am not able to reproduce this issue with the sidemenu starter. What browser or device are you able to reproduce this on?

**Comment by JustinPierce** [comment] 2016-10-18 18:42
@jgw96 Chrome 54.0.2840.59 m (64-bit) on Windows. I updated it this morning, but I only did that because I was having the issue on the previous version. When I run `ionic serve --lab`, the menus have issues on both the Android and Windows screens.

With a little bit of poking, I've also found that I cannot reproduce the issue if I enable device emulation in the Chrome dev tools -- it only happens when I use Chrome as a normal browser. It also doesn't happen in Edge, so it's likely localized to Chrome somehow.

**Comment by manueltaber** [comment] 2016-10-19 12:26
I have a similar issue. Only reproducable sometimes with Chrome. Edge works as expected...

**Comment by Tiuser4567** [comment] 2016-10-20 09:47
The slide out gesture edge can be controlled by maxEdgeStart attribute in ion-menu, I made it a little bit smaller (20, default is 50). Not sure if this would help.

**Comment by jgw96** [comment] 2016-10-25 15:27
Hello all! After testing on the latest stable version of chrome on macOS (54.0.2840.71) I am still unfortunately unable to reproduce this issue. I am using the sidemenu starter with both `ionic serve` and `ionic serve --lab` and can confirm that I cannot reproduce in either scenario. Because of this I am starting to think this is a bug in the windows version of chrome. @manucorporat are you able to repro this on either macOS or windows?

**Comment by JustinPierce** [comment] 2016-10-25 15:41
@jgw96 I apologize for not following up on this. A couple of days after reporting this, I could no longer reproduce it. I did not make any relevant changes to my app, and obviously Ionic didn't change. If I had to guess, it's probably some janky window scaling math on Windows. I would not cry if you closed this.

**Comment by jgw96** [comment] 2016-10-31 15:30
@JustinPierce thanks for the info! WIndows does have some "weird" scaling that I have seen cause some interesting issues with chrome. I am going to close this for now as it is not easily reproducible, but if anyone is able to reproduce this issue and has a test case we can use to repro it feel free to comment and i will gladly reopen. Thanks!

**Closed by jgw96** 2016-10-31 15:30 UTC
Labels: needs reply, v2
