### ISSUE TITLE
ion-refresher pull down is blank in v2

### ISSUE THREAD

**Issue by Barathwaja** [driftyco/ionic#7914] opened 2016-08-30 16:34 UTC
In ionic 2 beta 11 , pull to refresh icon and text are not visible sometimes.. why ?? please check the below attachments as proof.. 
below image is the output comparison .. works sometimes and sometimes it doesn't..

![refresher](https://cloud.githubusercontent.com/assets/5066436/18098002/fcb4e9d8-6efd-11e6-95c2-598e75b112f1.png)

In this below image, left side is the HTML code and right side is the TS code.

![code](https://cloud.githubusercontent.com/assets/5066436/18097883/73f6457e-6efd-11e6-8762-4a4627930261.png)

**Comment by Barathwaja** [comment] 2016-08-31 04:56
tested in device - Android  (Moto E2)
**With refresh icons at one time.**

![with refresh](https://cloud.githubusercontent.com/assets/5066436/18116409/1811016e-6f65-11e6-8b9d-ef11cd9e94bd.jpeg)

**No icons after switching tabs and refreshing again.**

![without refresh](https://cloud.githubusercontent.com/assets/5066436/18116410/1a98c9e4-6f65-11e6-8c68-0906383b5170.jpeg)

**Comment by Manduro** [comment] 2016-08-31 21:31
I can confirm this issue. It's happening in the browser (chrome) here as well. In a tab with an ion-list, refresher and infinite scroll.

**Comment by Barathwaja** [comment] 2016-09-01 04:48
@Manduro the above picture is taken from real device not in chrome device toolbar. Soo... ?? !!!

**Comment by Manduro** [comment] 2016-09-01 05:20
So it's also happening in the browser, not only on a real device. That makes the issue easier to debug.

**Comment by jabas06** [comment] 2016-09-01 16:56
I've the same issue. My first tab has a refresher and an infinite scroll. When navigating to second tab and going back to the first one, both refresher and infinite scroll containers got blank.

**Comment by Barathwaja** [comment] 2016-09-01 17:21
@Manduro my functionality works actually :P .,. oly in UI its not coming.. @jabas06 hmm yep i dont know why.. @mhartington can u check this out ?? even jabas06 has this issue..

**Comment by mhartington** [comment] 2016-09-01 17:30
This was asked in slack the other day and I was unable to reproduce. Tested on ios/android/browser. I was unable to reproduce

**Comment by Manduro** [comment] 2016-09-01 17:30
Yes it's functioning for me as well. Just not visible most of the time.

**Comment by jgw96** [comment] 2016-09-01 19:05
Hello all! Unfortunately I am having an issue reproducing this issue. Would anybody be able to post a repo with a minimal example of this issue? Thanks!

**Comment by ibcooley** [comment] 2016-09-01 19:35
able to produce a (minor) fix on my local builds by adding the following css:

```
ion-refresher:not([style]) {
    top: 56px;
}
```

Maybe this helps someone else?

also, able to consistently reproduce on a page (before dragging down) by doing the following:

```
@ViewChild(Refresher) refresher: Refresher;

ionViewDidEnter() {
   (<any>this.refresher)._beginRefresh();
}
```

maybe helps someone else.

**Comment by jabas06** [comment] 2016-09-01 20:41
I created this plunker to reproduce the issue. The problem arises only if I display a loader on the second tab. 
[http://plnkr.co/edit/T5rOxVBdC0Z7vd4EECGC?p=preview]

Steps:

1. Test refresher and infinite scroll. Everything works well
2. Navigate to second tab
3. Wait for the loader to dismiss 
4. Go back to first tab
5. Test refresher and infinite scroll. Containers got blank :(

**Comment by Barathwaja** [comment] 2016-09-05 03:32
@jgw96 anything ??

**Comment by Manduro** [comment] 2016-09-16 12:31
It seems to me the `ion-refresher-content[state]` does not update in some cases.

**Comment by Manduro** [comment] 2016-10-14 10:55
Still seeing this in RC.1.

**Comment by maxtuzz** [comment] 2016-10-19 02:48
Also having this issue.

**Comment by Manduro** [comment] 2016-12-23 10:20
Related? #9486 

Are any of you using `OnPush` while having this issue?

**Comment by jgw96** [comment] 2016-12-29 21:36
Hello all, is this still an issue in rc4? I cannot seem to reproduce this issue with any of my RC4 test apps. Thanks!

**Comment by cleitonjar** [comment] 2017-04-08 03:29
@ibcooley  The "top" stayed dynamic now. android/ios/browser.
your-page.ts
  @ViewChild(Refresher) refresher: Refresher;
  @ViewChild("header") header: any;

ionViewDidLoad() {
      (<any>this.refresher)._top = this.header.nativeElement.clientHeight + "px";
      (<any>this.refresher)._beginRefresh();    
}

your-page.html
<ion-header #header>....
<ion-content>...
<ion-refresher (ionRefresh)="onRefresh($event)">....

Thanks!

**Comment by vikramkakar** [comment] 2017-05-12 08:10
Hi i have issue with ionRefresh 
If i have more then 6 or 7 data in list ion refersher is not working fine.

my html code is this 

<ion-content no-padding mdoc-gray class="doc-list-parent">
	<ion-searchbar showCancelButton="true" [(ngModel)]="query" (ionInput)="filter($event)" debounce="500" placeholder="Name or Mobile Number"
	 padding></ion-searchbar>
	<ion-refresher (ionRefresh)="fetchAgain($event)">
		<ion-refresher-content></ion-refresher-content>
	</ion-refresher>
	<div *ngIf="loading" text-center margin-vertical>
		<ion-spinner name="dots"></ion-spinner>
	</div>

	<div *ngIf="!loading">
		<div *ngIf="!doctors.length" padding text-center>No doctors</div>
		<ion-card *ngFor="let doctor of doctors" (click)="goToDoctorDetail(doctor.uid)" no-padding no-margin margin-bottom>
			<ion-card-content *ngIf="doctor">

Thanks

**Comment by jgw96** [comment] 2017-05-18 17:01
Hello, all! I am going to close this as I cannot duplicate this issue in the latest version of Ionic. Thanks, everyone!

**Closed by jgw96** 2017-05-18 17:01 UTC
Labels: refresher, v2
