### ISSUE TITLE
Ionic 2.0.0 ion-select loses buttons on phone in landscape orientation

### ISSUE THREAD

**Issue by thomaswb** [driftyco/ionic#10276] opened 2017-02-01 20:26 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

In a phone in landscape mode, the select cancel/OK buttons are off the bottom of the screen and can't be used. I tried using CSS to reduce the size of the scrolling list so the buttons were on the screen, but then the list of options doesn't scroll.

The same problem occurs in a web browser when you reduce the height of the window.

**Expected behavior:**

The select dialog, including buttons, should fit in the screen and the options should scroll.

**Steps to reproduce:**

Open an ion-select on a phone in landscape mode, or in a web browser with small height.

**Other information:**

Same problem described here:

https://forum.ionicframework.com/t/ion-select-in-landscape-orientation-mode/75868

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.8.3 
ios-sim version: 5.0.4 
OS: macOS Sierra
Node Version: v6.7.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment] 2017-02-02 15:51
Hello, thanks for using Ionic! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/8440

**Closed by jgw96** 2017-02-02 15:51 UTC
