### ISSUE TITLE
bug: Duration in loadingCtrl.create affects alert

### ISSUE THREAD

**Issue by vanjiminster** [driftyco/ionic#7881] opened 2016-08-26 15:22 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Setting the duration option when calling loadingCtrl.create causes subsequent alert to auto-dismiss. The alert is created after the promise returned by loader.dismiss() is resolved. This alert will disappear without any input from the user.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment] 2016-08-26 15:59
Hello, thanks for opening an issue with us! Would you mind sharing a code snippet or repo i can use to reproduce this issue?

**Comment by jgw96** [comment] 2016-08-29 13:35
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by vanjiminster** [comment] 2016-08-29 14:11
Sorry for the late response. To reproduce this error, I created a blank Ionic 2 project 

`ionic start MyIonic2Project tutorial --v2`

Then, modified hello-ionic.ts to have the following content

```
import {Component} from '@angular/core';
import { AlertController, LoadingController } from 'ionic-angular';

@Component({
  templateUrl: 'build/pages/hello-ionic/hello-ionic.html'
})
export class HelloIonicPage {
  
  constructor(public loadingCtrl: LoadingController, public alertCtrl: AlertController) {
  }
  
  ionViewDidEnter() {
    let loader = this.loadingCtrl.create({
      content: "Please wait...",
      duration: 3000
    });
    var loading_promise = loader.present();
    loading_promise.then(
      loading_started => {
        return loader.dismiss()
      }
    ).then(
      loading_ended => {
        let alert = this.alertCtrl.create({
          title: 'New Friend!',
          subTitle: 'Your friend, Obi wan Kenobi, just accepted your friend request!',
          buttons: ['OK']
        });
        alert.present();
      }
    )
    
  }
}
```

And I see that the alert will close itself without any user interaction.

**Comment by jgw96** [comment] 2016-08-29 14:49
Hello! Thanks for the code sample! So the reason this issue is happening is because `dismiss()` is being called once by the duration ending and then once when you manually call `dismiss()`. I would recommend removing the duration or using `loader.onDidDismiss()` instead of promises. Thanks for using Ionic!

**Comment by vanjiminster** [comment] 2016-08-29 15:46
One of the patterns I'm currently using is: Start a loader that will last at most 8 seconds. Make an Http request. When the response is received and processed, cancel the loader. If some kind of error occurs, and the app never gets to cancel the loader, then the loader will go away at most 8 seconds later. This is why it is useful to have the above code.

I did some experiments and it seems to me that calling dismiss more than once is not exactly the problem. The following code works as expected.

```
ionViewDidEnter() {
    let loader = this.loadingCtrl.create({
      content: "Please wait...",
    });
    var loading_promise = loader.present();
    loading_promise.then(
      loading_started => {
        return loader.dismiss()
      }
    ).then(
      loading_ended => {
        loader.dismiss();
        loader.dismiss();
        loader.dismiss();
        loader.dismiss();
        loader.dismiss();
        let alert = this.alertCtrl.create({
          title: 'New Friend!',
          subTitle: 'Your friend, Obi wan Kenobi, just accepted your friend request!',
          buttons: ['OK']
        });
        alert.present();
        loader.dismiss();
        loader.dismiss();
        loader.dismiss();
        loader.dismiss();
        loader.dismiss();
      }
    )
  }
```

The alert box stays open. Calling dismiss multiple times doesn't cause any problems. The problem only occurs when I use the duration property.

Currently I'm getting around the problem by using setTimeout to dismiss the loading, rather than relying on the duration property.

Generally I feel that the interaction between loading and alert is very misleading - it took us a long time to realize the loading was affecting the alert. It would be great if these two features don't affect each other.

**Comment by jgw96** [comment] 2017-04-26 18:59
Hello @vanjiminster is this still an issue?

**Comment by vanjiminster** [comment] 2017-04-26 19:52
I have been using the workaround I described for rc.2. I haven't gotten around to trying newer versions of ionic, so I'm not sure.

**Comment by jgw96** [comment] 2017-04-27 15:00
Thanks for getting back to me. I am going to close this issue for now as stale, but feel free to open another issue if you run into any problems. Thanks for using Ionic!

**Closed by jgw96** 2017-04-27 15:00 UTC
Labels: needs info, v2
