### ISSUE TITLE
UI jumps when focusing input field

### ISSUE THREAD

**Issue by Tyler-Darby** [driftyco/ionic#10932] opened 2017-03-27 15:49 UTC
When focusing an input field in my app, the UI jumps around and appears very glitchy. This has been an issue since way back in the betas, but I never got around to worrying about it much. 

I have the keyboard plugin installed and `disableScroll(true)` is set. 

Here is a video of the behavior:
[Behavior](https://i.gyazo.com/757e3134a2d6733985a1ff2db7dcd515.mp4)

**Ionic info:**

```
    Cordova CLI: 6.4.0 
    Ionic Framework Version: 2.3.0
    Ionic CLI Version: 3.0.0-beta.4
    ios-deploy version: 1.9.0 
    ios-sim version: 5.0.6 
    OS: macOS Sierra
    Node Version: v6.9.2
    Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment] 2017-03-27 20:45
Hello, thanks for opening an issue with us. I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/10218.

**Closed by jgw96** 2017-03-27 20:45 UTC
