### ISSUE TITLE
Bug - Any `<ion-*` tag does not work anymore with `ngModel` !

### ISSUE THREAD

**Issue by HamzaLJ** [driftyco/ionic#7715] opened 2016-08-14 15:09 UTC
I've tested it for many hours and discovered that any `<ion-*` tag does not work anymore with `ngModel` 
I was working with that before Beta 11; however, after the update everything stopped working!

Can anyone from the IONIC team reply about this matter?

Your system information:

Cordova CLI: 6.3.0
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.4.7
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by q-depot** [comment] 2016-08-14 16:44
I had the same problem which seems related to the "angular/forms 0.3.0, downgrade to 0.2.0 seems to fix it.

**Comment by HamzaLJ** [comment] 2016-08-14 17:21
I already downgraded to 0.2.0 and didn't work too, the bug is related to ionic itself as the issue appears only when using ionic tags, specifically any tag starting with `ion-*`

**Comment by jgw96** [comment] 2016-08-15 14:42
Hello all! Thanks for using Ionic! I am going to be closing this issue as a duplicate of https://github.com/driftyco/ionic/issues/7707. Thanks!

**Closed by jgw96** 2016-08-15 14:42 UTC
Labels: platform:ios
