### ISSUE TITLE
Feature request: Programmatically call DateTime

### ISSUE THREAD

**Issue by seiyria** [driftyco/ionic#8719] opened 2016-10-15 14:29 UTC
#### Short description of the problem:
Currently it does not appear to be possible to programmatically call a datetime picker, and it only appears to be possible using `ion-datetime`. I confirmed this with mike in slack.

My use case is as follows: I have a swipe menu on an ion-item that allows users to set a reminder for the item in the list. So, I have them swipe, hit a "remind me" button, and it would ideally allow them to set a reminder using a date/time picker (which then gets pushed back to them via notification when the time comes).

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 
[DateTime docs](http://ionicframework.com/docs/v2/api/components/datetime/DateTime/) - no mention of being able to do this.
[Picker docs](http://ionicframework.com/docs/v2/api/components/picker/Picker/) are kinda empty.
[PickerController docs](http://ionicframework.com/docs/v2/api/components/picker/PickerController/) even more empty! 

[Roadmap](https://docs.google.com/document/d/1Qlc5X2eJyOB0izkFlH7KJ5BmMi0MeXUZRHJHt3hS6Wo/edit#heading=h.9xfkc8a5s03u) -- possibly this is already planned under the beta-- milestone, see this bit:
* Date/time input
   * Embeddable anywhere
   * Similar to new event in calendar on iOS

but it's hard to know for sure what that means.

If I were to implement this myself, it looks like it would just be a lot of copy/paste from `ion-datetime`.

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: not installed
ios-sim version: 3.1.1
OS: El Capitan
Node: 6.5.0
Xcode: 7.3.1

**Comment by jgw96** [comment] 2016-10-16 21:55
Hello, thanks for opening an issue with us! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/6799.

**Closed by jgw96** 2016-10-16 21:55 UTC

**Comment by seiyria** [comment] 2016-10-17 00:32
Thanks! Sorry, I looked but couldn't find something close to what I was at.
