### ISSUE TITLE
Cannot click button v2

### ISSUE THREAD

**Issue by mokrea** [driftyco/ionic#10160] opened 2017-01-25 01:24 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

I created a tab application...

at beginning, in tabs.ts, the app test if user is logged (Facebook native login)
```
Facebook.getLoginStatus().then(
      function() {
        console.log("it's ok");
      }
    ).catch(
      function() {
        console.log("logging");
        let modal = modalCtrl.create(LoginPage);
        modal.present();
      }
    ) ;
```

the LoginPage appears but I cannot click the buttons (only close button works) when app runs on device or emulators.. on web browser works.
my login.html page

```
<!--
  Generated template for the Login page.

  See http://ionicframework.com/docs/v2/components/#navigation for more info on
  Ionic pages and navigation.
-->
<ion-header>

  <ion-navbar>
    <ion-title>login</ion-title>
    <ion-buttons end>
      <button (click)="dismiss()" ion-button icon-only>
        <ion-icon name="close-circle"></ion-icon>
      </button>
    </ion-buttons>
    <button icon-left (click)="Flogin()" full>
      <ion-icon name="logo-facebook"></ion-icon>
      Login com Facebook
    </button>
  </ion-navbar>


</ion-header>


<ion-content >
  <button (click)="veja('teste')" ion-button>Button</button>

  <button ion-button icon-left (click)="Flogin()" full>
    <ion-icon name="logo-facebook"></ion-icon>
    Login com Facebook
  </button>
</ion-content>
```
login.ts code

```
import { Component } from '@angular/core';
import { NavController, NavParams, ViewController } from 'ionic-angular';
import { Facebook } from 'ionic-native';

/*
  Generated class for the Login page.

  See http://ionicframework.com/docs/v2/components/#navigation for more info on
  Ionic pages and navigation.
*/
@Component({
  selector: 'page-login',
  templateUrl: 'login.html'
})
export class LoginPage {

  private faceBookToken: string;
  private faceBookUserId: string;

  constructor(public navCtrl: NavController,public viewCtrl: ViewController, public navParams: NavParams) {}

  ionViewDidLoad() {
    console.log('ionViewDidLoad LoginPage');
  }

  teste() {
    console.log("TESTE");
  }

  Flogin() {
    console.log("login LoginPage");
    // Facebook.browserInit(375328372830084);
    // Facebook.login(["public_profile"]).then(data=> {
    //   this.faceBookToken=data.authResponse.accessToken;
    //   this.faceBookUserId=data.authResponse.userID;
    //   Facebook.api(this.faceBookUserId+"/?fields=name,email,birthday,gender",['public_profile']).then(data=>{
    //     alert(JSON.stringify(data));
    //   });
    // });

  }
  dismiss() {
        this.viewCtrl.dismiss();
  }

  public veja(t: string) {
    console.log(t);
  }

}
```

$ ionic info

Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.9.0 
ios-sim version: 5.0.4 
OS: macOS Sierra
Node Version: v4.2.4
Xcode version: Xcode 8.2 Build version 8C38

**Comment by jgw96** [comment] 2017-01-25 14:51
Hello, thanks for opening an issue with us! Do you get any errors in the console?

**Comment by mokrea** [comment] 2017-01-25 20:52
hi!

no errors, no warnings.. :/

**Comment by jgw96** [comment] 2017-01-30 20:44
Hello, unfortunately with no repro case and no errors there is not much we can do unfortunately. Would you mind posting a repo we can use to reproduce this issue?

**Comment by jgw96** [comment] 2017-02-09 17:33
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-02-09 17:33 UTC
Labels: needs reply, v2

**Comment by zuekegreen** [comment] 2018-01-10 17:19
I have the same problem , i use inappbrowser plugin , when i click the button that will open the browser , the button is not working.. how to fix this ?
