### ISSUE TITLE
Tabs change() fired on input blur | Ionic 2

### ISSUE THREAD

**Issue by nrcrabbe** [driftyco/ionic#5827] opened 2016-03-13 21:05 UTC
#### Short description of the problem:
Change the value of, then blur an input on a page under a tab and it fires a Tabs change() event.

Ref: https://forum.ionicframework.com/t/tabs-change-fired-on-input-blur/45972

#### What behavior are you expecting?
Should not fire Tabs change()

**Steps to reproduce:**
See a Codepen [here](http://codepen.io/nrcrabbe/pen/aNNPEE) based on tabs starter.

**`ionic info`:**
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Version: ~~2.0.0-beta.2~~ 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
OS: Distributor ID:	LinuxMint Description:	Linux Mint 17.3 Rosa 
Node Version: ~~v4.3.2~~ 4.4.0

UPDATE: updated ionic to beta 3, issue remains

**Comment by brandyscarney** [comment] 2016-05-18 17:23
So this is actually being caused by the input's `change` event bubbling up and the tab's `change` event catching it. After discussing this, we are going to rename all of the Ionic custom events to prepend `ion` to them. I created a new issue which will fix this issue, as well. I am going to close this issue to fix as part of #6568. Thank you for the issue!

**Closed by brandyscarney** 2016-05-18 17:23 UTC
Labels: v2
