### ISSUE TITLE
bug: Searchbar cancel event is execute input function

### ISSUE THREAD

**Issue by MatanYed** [driftyco/ionic#6382] opened 2016-04-29 15:31 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When there is no text in searchbar and you click on cancel button, the searchbar is execute the (input) function `(input)="loadItems($event)"`.

It's should execute the function only if there is text in search and than clicking cancel.

Look here my example here:
https://drive.google.com/file/d/0B_2AM8ZhXhE9U3RGdEJtRF82Ujg/view

I wish you understood the problem...

<span is-issue-template></span>

**Comment by jgw96** [comment] 2016-04-29 16:01
Hello @MatanYed ! Thanks for opening an issue with us! I cant seem to see your example, it looks like the url is incorrect, would you mind reposting it?

**Comment by MatanYed** [comment] 2016-04-29 16:09
@jgw96 oh, oops, i added it now.

**Comment by jgw96** [comment] 2016-04-29 16:20
@MatanYed Thanks, i can see the example now. Would you be able to provide a minimal code example that i can use to reproduce this? Thanks

**Comment by MatanYed** [comment] 2016-04-29 16:24
@jgw96 Sure.

HTML:
```
<ion-toolbar class="slider" dark [class.closed]="!searchbarVisible">
	<ion-searchbar [(ngModel)]="searchQuery" (input)="loadSearchedPosts($event)"></ion-searchbar>
</ion-toolbar>
```

Typescript:
```
loadSearchedPosts(searchbar?) {
	this.posts = [];
	this.postsLoaded = false;
	
	this.feed.fetch(this.searchQuery).then(posts => {
		this.posts = posts;
		this.postsLoaded = true;
	});
}
```

**Comment by brandyscarney** [comment] 2016-04-29 21:17
So this is because the input is cleared when clicking on the cancel button (and the input event gets emitted on the clear function. We could add a check that the input has a value prior to clearing it and only emit the `input` event when there is.

https://github.com/driftyco/ionic/blob/2.0/ionic/components/searchbar/searchbar.ts#L313

**Comment by brandyscarney** [comment] 2016-06-09 23:49
Thanks for the issue. This will be fixed in the `beta 9` release!

**Closed by brandyscarney** 2016-06-09 23:49 UTC
Labels: v2
