### ISSUE TITLE
IOS ItemSliding should disable scroll when slide occure

### ISSUE THREAD

**Issue by Yimiprod** [driftyco/ionic#9549] opened 2016-12-08 11:26 UTC
[x] **2.0 rc3**
[x] feature request

**Current behavior:**
When sliding an itemSliding in a list, we can scroll the list.

**Expected behavior:**
In native environment, a sliding item in a list should disable the scroll during slide.
By the way, the the `no-bounce` attribute doesn't work.

**Steps to reproduce:**
Set a long list of item, set each one slidable, try on ios.

**Comment by mhartington** [comment] 2016-12-09 21:34
I am unable to reproduce using the latest nightly.
Please share some example code that causes this for you, as stated in the issue template.


Also, `no-bounce` does not exist in V2 since this is not JS-scrolling.

**Comment by Yimiprod** [comment] 2016-12-12 10:45
### With RC3
**pagelist.ts**
```ts
@Component({
  templateUrl: 'template.html'
})
export class ListPage {
  public items:any = [];
    
  controller() {
    for (let i = 0; i <= 15; i++) {
      this.items.push({
        id: i,
        name: `Item ${ i }`
      });
    }
    navToItem(item) {
      console.log(item);
    }
    rmItem(listItem: ItemSliding, item) {
      listItem.close();
      alert(`Removing ${ item.name }`)
    }
  }
}
```
**template.html**
```html
<ion-content no-bounce>
  <ion-list>
    <ion-item-sliding #listitem *ngFor="let item of items;">
      <button ion-item detail-none (click)="navToItem(item)">{{ item.name }}</button>
      <ion-item-options (ionSwipe)="rmItem(listitem, item)">
        <button ion-button icon-only expandable (click)="rmItem(listitem, item)">
          <ion-icon name="trash"></ion-icon>
        </button>
      </ion-item-options>
    </ion-item-sliding>
  </ion-list>
</ion-content>
```

**Comment by mhartington** [comment] 2017-01-09 17:31
Appears to be fixed in the nightly release.

**Closed by mhartington** 2017-01-09 17:31 UTC
Labels: v2
