### ISSUE TITLE
bug: $ionicConfig setting back button text is not applied globally

### ISSUE THREAD

**Issue by rsweny** [driftyco/ionic#3531] opened 2015-04-15 13:05 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>

**Platform Versions**: <span ionic-platform>all</span>

<span ionic-description>Using $ionicConfigProvider I can set the Back button text to a custom string and this takes effect globally on every screen:

$ionicConfigProvider.platform.ios.backButton.previousTitleText(false).text(backText).icon('ion-ios-arrow-back');

However if the user later changes their language, $ionicConfigProvider can no longer be used since it is broken when accessed from within a controller. Instead I have used $ionicConfig like this:

$ionicConfig.platform.ios.backButton.previousTitleText(false).text(backText).icon('ion-ios-arrow-back');

This will change the back text on the current screen, but all other screens will still have the old text. I would like changes to $ionicConfig to take places globally like they do for $ionicConfigProvider. Or just fix $ionicConfigProvider so it can be used from a controller.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-04-15 13:05
Greetings @rsweny!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3531). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3531)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment] 2015-04-15 19:32
Greetings @rsweny!

My sensors indicate that I require more information in order to assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this happen occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com), where many humans will be able to offer wisdom and advice.

Thank you for allowing me to assist you.

<span ionitron-needs-reply></span>

**Comment by rsweny** [comment] 2015-04-15 21:07
http://codepen.io/anon/pen/ogKaLq

1) Click "Scientific Facts". Note the Back text is "Backk".
2) Click Change Language. The Back text should be "Retour".
3) Click "Scientific Facts". Note the Back text is not "Retour".

**Comment by rsweny** [comment] 2015-04-15 21:23
duplicate of #3531

**Closed** 2015-04-15 21:23 UTC

**Comment by rsweny** [comment] 2015-04-15 21:26
duplicate of #3281
