### ISSUE TITLE
NavController do not delete previous page when using remove but does with pages before

### ISSUE THREAD

**Issue by speedfl** [driftyco/ionic#9139] opened 2016-11-13 13:40 UTC
#### Short description of the problem:

Remove in navController does not work for previous page (work for other before)

#### What behavior are you expecting?

Previous parge remove

**Steps to reproduce:**
0. Be on root page
1.  nav.push(firstPage)
2. nav.push(secondPage)
3. nav.push(firstPage)
4. nav.remove(this.viewCtrl.index - 1) => must delete second page but does not. When use backbutton arrive on second page

When I am doing this on nav.remove(this.viewCtrl.index - 2) when I do previous ( I arrived on SecondPage) the previous I arrive on root so it is working for all the previous pages before the last one before

```
// on first page

// do not send it from page root to page 1
if(this.params.get("choice")){
      this.cards.pop();
      var backIndex = this.viewCtrl.index;
      this.nav.remove(backIndex - 1).then(() => {
        console.debug('Successfully removed' + (backIndex - 1));
      });
    }

// on second page 
this.nav.push(Accepttransfer, {'choice' : true});
```

I cannot use pop because I need to do some post treatment on first page if something happened on second page

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x

"ionic-angular": "^2.0.0-rc.0",

**Comment by jgw96** [comment] 2016-11-14 16:53
Hello, thanks for opening an issue with us! I am unfortunately not able to reproduce this locally. Would you mind making a [plunker]( http://plnkr.co/edit/GJte2b?p=preview) that shows this issue? Thanks!

**Comment by speedfl** [comment] 2016-11-15 08:00
Hello I don't know how to do a plunkr so I created a sample project:

https://github.com/speedfl/issue-history

However it seems that with rc3 we do not have the issue anymore. So I will try to migrate my project

**Comment by manucorporat** [comment] 2016-11-26 15:08
@speedfl I am going to close this issue, since it appears to work in RC3. Please feel free to reopen it if you verify this is still an issue in the latest version of the framework!

**Closed by manucorporat** 2016-11-26 15:08 UTC
Labels: needs reply, v2
