### ISSUE TITLE
bug: ion-refresher immediately disappearing

### ISSUE THREAD

**Issue by sb8244** [driftyco/ionic#5456] opened 2016-02-15 06:26 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>A refresher exists like:

```
  <ion-refresher (refresh)="refresh($event, refresher)" [refreshingText]="'Getting Fresh'" [pullingText]="'Freshen it up'">
  </ion-refresher>
```

which subscribes to an Observable that is just a glorified Http wrapper:

```
  refresh(refresher) {
    this.todoist.load().subscribe(() => refresher.complete());
  }
```

load is defined as:

```
  load() {
    return this.http.get(this._todoistUrl())
      .retry(3)
      .delay(2000)
      .map(res => res.json().Items.map(item => new TodoItem(item)))
      .map((items: Array<TodoItem>) => {
        this.dueItems = orderByDueDate(Array.from(items.filter(item => item.overdue)));
        this.futureItems = orderByDueDate(Array.from(items.filter(item => !item.overdue)));
        return items;
      });
  }
```

However, the ion-refresher immediately disappears after pulling. I don't believe there is anything missing from implementation according to docs.</span>

<span is-issue-template></span>

**Comment by sb8244** [comment] 2016-02-15 06:30
It also appears that (starting) is not firing

**Comment by brandyscarney** [comment] 2016-02-16 16:21
Thanks for the issue! Closing this issue as a duplicate of: https://github.com/driftyco/ionic/issues/5207

**Closed by brandyscarney** 2016-02-16 16:21 UTC
Labels: v2
