### ISSUE TITLE
bug: ion-checkbox observe do not work correctly

### ISSUE THREAD

**Issue by do-web** [driftyco/ionic#3109] opened 2015-02-13 16:58 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>if i click the button the first time the checkbox will be selected, if i then klick on the checkbox (unchecked) and click the button again, the checkbox is not updated (checked).

$scope.pushEnabled = false;              
$scope.enable = function(e) {
                $scope.pushEnabled = true;
            };  

<button class="button button-block bar-light" ng-click="enable()">
            Enable checkbox
            </button>
            <ion-checkbox

                          ng-model="pushEnabled"
                          ng-checked="pushEnabled"
                    >
               Text
            </ion-checkbox></span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-02-13 16:58
Greetings @do-web!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3109). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3109)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by yanivefraim** [comment] 2015-02-23 22:29
Hey,
As far as I can tell from your example this is not a bug - it is a typical Angula.js/Javascript prototype scope inheritance problem. If you put your properties directly on $scope, when child $scope changes a value it is "shadowing" this property's value, and "breaks" the chain. In order to fix this you should use an object attached to $scope and apply this property to the object. 

Take a look at this pen (with the problem): http://codepen.io/yanivefraim/pen/bNMoaR

And this is the fix: http://codepen.io/yanivefraim/pen/ByxwVZ

You can take a look at a deeper look at this problem/situation in the following post:
http://jimhoskins.com/2012/12/14/nested-scopes-in-angularjs.html

Hope that helps!

**Comment by Ionitron** [comment] 2015-05-26 16:01
Greetings @do-web!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-05-26 16:01 UTC
Labels: ionitron:closed
