### ISSUE TITLE
this.nav.pop() stops responding and displays a black screen

### ISSUE THREAD

**Issue by gigocabrera** [driftyco/ionic#6677] opened 2016-05-27 11:18 UTC
#### Short description of the problem:

I have a simple app with a `HomePage` that calls a child `PickPage` with a list of 3 pick items. When you tap on a selection it fires a function called `pickPreference(item)` and all it does is return to the parent page with `this.nav.pop()`. If you go back and forth several times between the parent and the child, it stops working and displays a black screen

#### What behavior are you expecting?

I should be able to go back and forth between the Homepage and PickPage without any errors

**Steps to reproduce:**

The key is to go back and forth between the parent and child pages as fast as possible.

Below is the sample code that I'm using to reproduce this issue, but you can download a sample app that demonstrates this issue [in this github repo](https://github.com/gigocabrera/ionic2_navpopissue)

```
**home.html**

    <button ion-item (click)="pickDefaultDate()">
      <ion-label floating primary>Default Date</ion-label>
      <ion-input type="text" [(ngModel)]="settings.defaultdatedisplay" readonly></ion-input>
    </button>

**home.ts**

    import {PickPage} from '../pick/pick';

    pickDefaultDate() {
        this.nav.push(PickPage);
    }

**pick.html**

    <ion-list radio-group>
      <ion-item *ngFor="let item of defaultitems">
          <ion-label>{{item.text}}</ion-label>
          <ion-radio [value]="item.value" (click)="pickPreference(item)" ></ion-radio>
      </ion-item>
    </ion-list>

**pick.ts**

constructor(private nav: NavController) {
    
    this.defaultitems = [
          { text: 'No default date', value: 'none' },
          { text: 'Todays date', value: 'today' },
          { text: 'Last date used', value: 'last' }];
      }
  
    dismiss() {
      this.nav.pop();
    }
  
    pickPreference(item) {
      this.nav.pop();
    }
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 
This is the black screen that I get but there are no errors on the console

![ionic_nav_pop_issue](https://cloud.githubusercontent.com/assets/6364855/15606404/079db0c4-23da-11e6-8b21-481e6383f55f.png)

**Which Ionic Version?**  2.x

#### Github Sample App that shows an example of my issue

https://github.com/gigocabrera/ionic2_navpopissue

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Your system information:
```
Cordova CLI: 5.4.1
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.7
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS:
Node Version: v5.10.1
```

**Comment by Daforest** [comment] 2016-05-29 08:34
This may be related to [](https://github.com/driftyco/ionic/issues/6540) ?

**Comment by gigocabrera** [comment] 2016-05-29 15:37
@daforest I concur. Your issue and mine are basically the same issue. And it is reproducible with any 'Back' button in ionic.

**Comment by gigocabrera** [comment] 2016-05-29 23:29
Closed by mistake. Sorry

**Comment by Daforest** [comment] 2016-05-30 11:27
I find it strange that this one is not added to the Beta 8-milestone. This could potensionally break any Ionic 2 app.

**Comment by jgw96** [comment] 2016-06-01 21:46
Hello @Daforest ! Sorry for the delay on this one (: Which platforms are you observing this on?

**Comment by jgw96** [comment] 2016-06-01 22:00
Hello! So i am having trouble getting your demo running for some reason. But after creating my own demo app to try and reproduce this i cant seem to be able to. Could you post a plunker that i could use to reproduce this issue? Thanks!

**Comment by Daforest** [comment] 2016-06-02 03:56
@jgw96 I am not the owner of this post. My issue is similar, and is described here [#6540](https://github.com/driftyco/ionic/issues/6540). This should be an easy task to reproduce.

**Comment by gigocabrera** [comment] 2016-06-02 11:48
Hello @jgw96 I don't know how to create a plunker to reproduce but as Daforest stated, this should be easy to reproduce. If you have your own demo, the key to reproduce is to go back and forth between the parent and child pages as fast as possible so when you're on the child page you tap on the Back button to go back (again as fast as you can, several times)

**Comment by gigocabrera** [comment] 2016-06-02 11:52
**I FORGOT TO MENTION**

On the child page you need something like below to go back to the parent

```
GoBack() {
    this.nav.pop();
}
```

**Comment by jgw96** [comment] 2016-06-02 17:01
@gigocabrera hmmm, i am still having troubles reproducing. I am back and forth between my child page and home page as fast as i can and it seems to be working fine. What platforms are you seeing this issue on? Im testing on a Nexus 6 running the Android N beta dev preview, a Nexus 7 running Android 6.0.1 and a Moto X 2014 running Android 5.1.1. Also, would you mind testing with our ionic conf demo app? (https://github.com/driftyco/ionic-conference-app) The schedule page is a list of items that open pages, so its pretty easy to test with.

**Comment by Daforest** [comment] 2016-06-02 17:43
@jgw96 I don't know about this issue, but [#6540](https://github.com/driftyco/ionic/issues/6540) is iOS only.

**Comment by gigocabrera** [comment] 2016-06-03 20:35
@jgw96 I was able to reproduce using the ionic-confererence-app. Here are the steps:

- Make the `AboutPage` the `rootPage` in `app.ts` (yes, I'm using the typescript version in all my apps)
- Open the `About.html` page and add the following markup before the `</ion-content>` tag
```
<button ion-item (click)="goToChild()">
      <ion-label floating primary>Default Date</ion-label>
      <ion-input type="text" readonly></ion-input>
</button>
```
- Open the `About.ts` page and add the following
```
goToChild() {
    this.nav.push(ChildPage);
}
```
- Add a new page called ChildPage (it can be a blank page)
- Run `ionic serve`
- Click on the new button you added on the about page. This will take you to the new child page. Tap really fast on the Back button in the top navigation to go back to the parent page. Here's where the issue appears.

I am using a Windows 10 PC and I am running this app in chrome with iPhone 6 device mode. I also installed in iOS 9.3.1 iphone 6 device and I was able to reproduce it

**Comment by jgw96** [comment] 2016-06-03 20:41
Thanks for the info @gigocabrera so it looks to be isolated to the ios mode. I was finally able to reproduce this issue with an unmodified version of the ionic-conference app.

**Comment by gigocabrera** [comment] 2016-06-03 21:12
That's awesome @jgw96 and as @Daforest mentioned, his issue #6540 is also an iOS issue

**Comment by Daforest** [comment] 2016-06-07 09:38
@jgw96 Will this be a part of milestone beta.9?

**Comment by jgw96** [comment] 2016-06-07 14:10
Hello @Daforest i have added this to our beta.9 milestone (:

**Comment by danbucholtz** [comment] 2016-06-13 17:06
Hi @gigocabrera,

I cannot recreate with the latest version of Ionic.  Can you try doing this from your project root and letting me know if you can?

```
rm -rf node_modules/ionic-angular
rm -rf www/build
npm install ionic-angular@nightly
```

Thanks,
Dan

**Comment by danbucholtz** [comment] 2016-06-13 18:02
I am going to close this because I think we indirectly fixed this.  If you're still having the issue, I will re-open.

Thanks,
Dan

**Closed by danbucholtz** 2016-06-13 18:02 UTC
Labels: needs reply, radio, v2

**Comment by gigocabrera** [comment] 2016-06-13 21:00
@danbucholtz this question my sound stupid but please pardon my ignorance: 
When I try to run `rm -rf node_modules/ionic-angular` I get 
'rm' is not recognized as an internal or external command, operable program or batch file. I'm using a Windows based PC

**Comment by danbucholtz** [comment] 2016-06-13 21:03
Ahhh okay, just delete your node_modules/ionic-angular directory.  `rm -rf` is recursive delete.

**Comment by jgw96** [comment] 2016-06-13 21:04
Hey @gigocabrera sorry about that. The unix command `rm` is not supported on windows. Were all mac or linux users here so were used to giving out that command. You can simply go into your apps directory and delete the `node_modules` folder and then run `npm install` again.

**Comment by gigocabrera** [comment] 2016-06-13 21:34
@danbucholtz @jgw96 
After installing the nightly version I no longer experience the issue. However, it doesn't feel **"native"** enough as I find myself tapping twice to go back. Can the 700ms be adjusted for a better experience?

`KEYBOARD_DURATION_PADDING = 700;`

**Comment by danbucholtz** [comment] 2016-06-13 21:48
I did lower it to 600ms.  Ultimately, it doesn't matter what that value is because as soon as the transition is over, the app activates again.  Besides, that value is only used when the keyboard is showing.

We use bezier-curves for most of our transitions, and may need to revisit the values of them.  Right now sometimes it feels like transitions are done when they are not truly done.  Just my $0.02 on the matter.

Thanks,
Dan

**Comment by chack** [comment] 2016-08-07 21:57
I experience this behavior in Beta 11, see #7564

**Comment by xx0r** [comment] 2016-10-22 08:11
would you mind opening this issue for RC1? :)

I am pretty sure, that the cause is seemingly innocous directive **no-border** on **ion-navbar** 

OS: Win10 x64

1. ionic start sidemenu.starter --ts --v2 --teplate sidemenu
2. **ionic info**
```
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.36
OS:
Node Version: v6.6.0
```
3. edit **page2.html**
` <ion-navbar **no-border**>`

4. `ionic serve`

5. click couple of times on the items

6. click rapidly back

7. the screen goes black / white as soon as you reach the root page and click on the left icon

I'll try to attach a video

**Comment by manikandan07081995** [comment] 2018-01-17 13:31
same issue happen for me. While change menu i have loading list of data.Its showing block color screen in between loading data.How to solve this problem ?
I tried .scroll-content overflow:auto ,
I tried npm npm install ionic-angular@nightly

Nothing works for me can any one help me 
@jgw96
