### ISSUE TITLE
Custom component: Can't bind to '[custom property name]' since it isn't a known property of '[custom component name]' since an upgrade from Beta 11 to RC.

### ISSUE THREAD

**Issue by infinnie** [driftyco/ionic#8335] opened 2016-09-30 06:00 UTC
To implement a TreeView, I used a custom component to represent a tree node and referenced it in a higher-level component by custom tag and attribute names. It worked fine back in Ionic 2 Beta 10 and 11, but after migration to RC0 according to the guide, it stopped working and errors got reported to the console like the one shown in the title. What can I do now?

I have added all the component classes to the `declarations` field in the parameter passed to `@NgModule()`. I wonder what I might have missed.

**Comment by jgw96** [comment] 2016-09-30 17:06
Hello, thanks for using Ionic! Would you mind sharing a repo that I can use to reproduce this issue? Thanks!

**Comment by jgw96** [comment] 2016-10-03 01:13
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-10-03 01:13 UTC
Labels: needs reply, v2

**Comment by infinnie** [comment] 2016-10-06 00:09
@jgw96 I wish you could somewhere demonstrate how to use nested custom components via markup in Ionic 2 RC for us to better migrate Ionic 2 Beta projects to RC.
