### ISSUE TITLE
(ionSelect) not invoked on ion-option in ion-select

### ISSUE THREAD

**Issue by miloslavskacel** [driftyco/ionic#7497] opened 2016-08-01 08:28 UTC
I'd like to react on ion-option selection change, i.e. to react before user closes ion-select, being inspired by ionic-preview-app:
    https://github.com/driftyco/ionic-preview-app/blob/master/app/pages/selects/basic/template.html#L47-L55

```
  <ion-select [(ngModel)]="music">
        <ion-option value="SP">Smashing Pumpkins</ion-option>
        <ion-option value="SG">Soundgarden</ion-option>
        <ion-option value="STP" (ionSelect)="stpSelect()">Stone Temple Pilots</ion-option>
  </ion-select>
```
```
  stpSelect() {
    console.log('STP selected');
  }
```

Note that select event from ionic-preview-app  was replaced by ionSelect in above code. 

Issue is that ionSelect is never emitted.
https://github.com/driftyco/ionic/blob/2.0/src/components/option/option.ts#L22

I asked already on 
https://forum.ionicframework.com/t/ion-option-select-stpselect-select-not-invoked-in-beta-10/59095

> ionic info
> 
> Cordova CLI: 6.1.1
> Gulp version:  CLI version 3.9.1
> Gulp local:   Local version 3.9.1
> Ionic Version: 2.0.0-beta.10
> Ionic CLI Version: 2.0.0-beta.23
> Ionic App Lib Version: 2.0.0-beta.13
> ios-deploy version: 1.8.6 
> ios-sim version: 5.0.6 
> OS: Mac OS X El Capitan
> Node Version: v5.8.0
> Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by brandyscarney** [comment] 2016-08-02 04:28
Thanks for the issue! This is a duplicate of https://github.com/driftyco/ionic/issues/6711 so I am going to close this issue. Please add any feedback on that issue. :)

**Closed by brandyscarney** 2016-08-02 04:28 UTC
Labels: platform:ios, select, v2
