### ISSUE TITLE
bug: Can no longer debug TypeScript in Chrome

### ISSUE THREAD

**Issue by pjc2007** [driftyco/ionic#9494] opened 2016-12-05 11:55 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>This appears to be some sort of build problem.

I have just updated to version 2.1.14 (after a short while away from playing with Ionic). After creating a stock project (ionic start test --v2), and then running via ionic serve, there is just no TypeScript anywhere to be found in the Chrome debug tools. I have tried this on two machines with the same result.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment] 2016-12-05 16:00
Hello, thanks for opening an issue with us! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic-app-scripts/issues/431 as it will be solved as part of that issue.

**Closed by jgw96** 2016-12-05 16:00 UTC
Labels: v2
