### ISSUE TITLE
bug: Slide Box showing double items when using ng-repeat

### ISSUE THREAD

**Issue by brunodb3** [driftyco/ionic#3683] opened 2015-05-08 14:42 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>I'm having an issue using the directive ion-slide-box, where i have an array of 2 values, and want to do a ng-repeat on this array. When i do so, there are 4 slides shown in the screen. Here is a bit of my code:

```html
  <ion-slide-box
  	 does-continue="true"
  	 show-pager="true">
    <ion-slide ng-show="revenda" ng-repeat="produto in revenda.produtos">
	    <div class="card" style="text-align:center;">
	      <div class="item item-text-wrap">
	        <img src="img/ionic.png">
	        <br /><br />
	        <b>{{produto.title}}</b>
	        <br /><br />
	        <b>{{produto.price | currency}}</b>
	        <br /><br />
	      </div>
	    </div>
    </ion-slide>
  </ion-slide-box>
```

My array is 'revenda.produtos', wich has 2 items in it.

In my app's screen, i see 4 slides (or dots underneath the slides). It may be something in the directive itself, or in my code (i am not an expert on Javascript nor AngularJS).

I have a post that describes this issue too on [Ionic Forums](http://forum.ionicframework.com/t/ionic-slide-box-showing-double-the-items-on-pager/17952).</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-05-08 14:42
Greetings @brunodb3!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3683). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3683)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment] 2015-05-08 16:15
Thanks, this looks like a dupe of #3609, please continue the discussion there

**Closed by perrygovier** 2015-05-08 16:15 UTC

**Comment by Khez** [comment] 2015-10-29 12:03
We had similar issues, that were actually caused by [a bug in ngAnimate making ngRepeat to show stale items](https://github.com/angular/angular.js/issues/3613)

The solution was to add in `app.config`

    $animateProvider.classNameFilter(/^((?!(no-animate)).)*$/);

And then to add the `no-animate` class on the `ion-slide` elements that had `ng-repeat`
