### ISSUE TITLE
bug: cached views doesn't maintain scroll position when

### ISSUE THREAD

**Issue by mkoosej** [driftyco/ionic#3256] opened 2015-03-09 09:12 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>On the beginning of the transition the scroll view of the parent is set to zero for some reason.
The code was so simple I didn't create a codepen.

Parent View:

```
<ion-view view-title="HOME" hide-tabs>
<ion-content
            id="Dashboard"
            ng-controller="HomeController"
            has-header="true"
            overflow-scroll="true"
            >
Content

</ion-content>
</ion-view>
```

Child View:

```
<ion-view cache-view="false" view-title="{{view_title}}" hide-tabs>
    <ion-content scroll='false'>
    Some More Content
   </ion-content>
</ion-view>
```</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-03-09 09:12
Greetings @mkoosej!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3256). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3256)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment] 2015-03-13 21:36
Can you please provide a demo of this in a codepen

**Comment by tmaximini** [comment] 2015-04-08 11:04
I am having the same problem since updating from beta14 to 1.0.0-rc2.
It is only noticeable when turning off transitions `$ionicConfigProvider.views.transition('none');`
The cached view jumps each time back from top to the previous scroll position.

**Comment by tmaximini** [comment] 2015-04-09 08:56
Okay, so I did more testing in my app: There is definitely some change happening with cached views between 1.0.0-beta.14 and 1.0.0-rc2. While in beta 14 going back to a cached view with transition('none') is smooth like butter it is super noticable jumpy in rc2.
I tried to create a pen but could not reproduce it with a simple view. It definitely has something to do with nested directives, e.g.:

My main view has a directive, this directive renders a long ng-repeated list. I leave this view and go back, it jumps from scrollTop 0 to the last position in rc2 (wasn't in beta14). I also notice a little jump when leaving this view. 
@mhartington Is there an easy way to scaffold ionic codepens or is it done mostly manually?

**Comment by tmaximini** [comment] 2015-04-09 10:36
Sorry, it was not the fault of rc2 - in my case I had a directive re-rendered through an event which caused the jumpy. it works now.

**Comment by Ionitron** [comment] 2015-04-12 22:32
Greetings @mkoosej!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment] 2015-04-12 22:32
Greetings @mkoosej!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-04-12 22:32 UTC
Labels: ionitron:closed
