### ISSUE TITLE
Ion-tab makes scroll bug

### ISSUE THREAD

**Issue by danielptn** [driftyco/ionic#4918] opened 2016-01-06 19:28 UTC
Hello, i got a curious bug when i try to use the Ion Tabs..

When i click in some tab, they show all your content, but when i click in other tab button, the height of the old tab still unitl the scroll bar disappear, then back to normal.

This is very boring .. because when I'm on a tab that content is small, and go for a tab that content is big, the content is cut, then I have to wait about 2 seconds to scroll disappear and adjust the height.

Someone know how to fix it?

PS: I remove the ''height: 100% of the class .pane,.view {height: 100%}, in line. 3553 of ionic.css, because before that, even though I expected, not readjust.

**Comment by danielptn** [comment] 2016-01-07 23:57
hello? =(

**Comment by Ionitron** [comment] 2016-01-08 01:23
Greetings @danielptn!

My sensors indicate that I require more information in order to assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this happen occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using Ionic, I recommended visiting [the forum](http://forum.ionicframework.com), where many humans will be able to offer wisdom and advice.

Thank you for allowing me to assist you.

<span ionitron-needs-reply></span>

**Comment by danielptn** [comment] 2016-01-08 02:34
This happens on all plataforms.. I try in browse, in iOS and Android..
When i click in tabs, i got a problem with resize.. I need wait some time to the scroll bar ''resize'', and it takes 2 seconds nearly... Understand?

Probably this is a Ionic Framework issue.

Thanks

**Comment by mhartington** [comment] 2016-01-08 02:45
Please provide a demo of this.

**Comment by Ionitron** [comment] 2016-02-07 13:06
Greetings @danielptn!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2016-02-07 13:06 UTC
Labels: ionitron:closed
