### ISSUE TITLE
bug: $ionicSlideBoxDelegate.next() causing an exception after upgrading to 1.0.0

### ISSUE THREAD

**Issue by ericraio** [driftyco/ionic#3807] opened 2015-05-22 05:46 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>I just upgraded to 1.0.0 yay me but this is the only thing I can't figure out.

When calling any function that moves to the next slide such as this one
```
$ionicSlideBoxDelegate.next()
```

This is the exception that I get...

```
TypeError: Cannot read property 'length' of undefined
    at circle (http://localhost:8100/vendor/ionic/js/ionic.bundle.js:8050:21)
    at slide (http://localhost:8100/vendor/ionic/js/ionic.bundle.js:8079:14)
    at ionic.views.Slider.ionic.views.View.inherit.initialize.slide.select (http://localhost:8100/vendor/ionic/js/ionic.bundle.js:8432:7)
    at http://localhost:8100/vendor/ionic/js/ionic.bundle.js:105:46
    at Array.forEach (native)
```

when diving into the code, the slides variable gets undefined.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-05-22 05:46
Greetings @ericraio!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3807). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3807)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment] 2015-05-22 19:41
Could you demonstrate this in a codepen?

**Comment by hur0n** [comment] 2015-06-16 06:06
I have exactly the same problem since I upgraded to 1.0.0 with `$ionicSlideBoxDelegate.next()` and `$ionicSlideBoxDelegate.slide(to)`

**Comment by dellheng** [comment] 2015-06-16 10:12
+1

**Comment by hur0n** [comment] 2015-06-16 18:06
@dellheng 
Your codepen is working!? I dont see the TypeError in your example? I am also struggling to reproduce this in a codepen example, however, I can confirm that I get the "undefined slides" after rc3.

**Comment by dellheng** [comment] 2015-06-17 03:59
Sorry I didn't say how to click button,It's very strange。
You didn't see error in this order:
1. click "Show images from start" button
2. click "Show second imagen"

You will see error in this order:
1. click "Show second imagen"
2. click "Show images from start" button

and the error only appear in first time ,you click again，the error won't appear

**Comment by dellheng** [comment] 2015-06-17 04:07
This is rc3 demo 
http://codepen.io/dellheng/pen/mJMzvR

**Comment by Ionitron** [comment] 2015-06-21 22:45
Greetings @ericraio!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment] 2015-06-21 22:45
Greetings @ericraio!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-06-21 22:45 UTC
Labels: ionitron:closed

**Comment by Elsioufy** [comment] 2015-06-28 11:02
+1 
I have the same issue when I upgraded to ionic 1.0.0

trying to call: 

    $ionicSlideBoxDelegate.next()

It gives an exception:

    TypeError: Cannot read property 'length' of undefined
      at next (http://192.168.1.132:8100/lib/ionic/release/js/ionic.bundle.js:8043:30)
      at next (http://192.168.1.132:8100/lib/ionic/release/js/ionic.bundle.js:8446:7)
      at http://192.168.1.132:8100/lib/ionic/release/js/ionic.bundle.js:105:46
      at Array.forEach (native)
      at DelegateInstance.caller [as next] (http://192.168.1.132:8100/lib/ionic/release/js/ionic.bundle.js:102:27)

**Comment by karthikiyengar** [comment] 2015-06-28 15:05
+1, breaks on next(), previous(), slide().

**Comment by JavierMartinz** [comment] 2015-07-05 15:47
+1 breaks with slide() on 1.0.1

**Comment by karthikiyengar** [comment] 2015-07-06 04:47
Reopened as #4041

**Comment by stephanbarrett** [comment] 2015-08-17 19:49
+1 

I'm having the same issue and myself and my team can't figure out how to fix this. Anyone have an example of how to get around this bug in 1.0.1/1.1? 

Thanks!

**Comment by JunkMyFunk** [comment] 2015-09-08 10:30
I get the same issue using `$ionicSlideBoxDelegate.next();`. It seems that adding `delegate-handle="slider"` to the `<ion-slide-box>` in the template and referencing it using `$ionicSlideBoxDelegate.$getByHandle('slider').next();` and `$ionicSlideBoxDelegate.$getByHandle('slider').previous();` work reliably in 1.1.0 though

**Comment by karthikiyengar** [comment] 2015-10-02 13:36
JunkMyFunk - your solution does not seem to work for me, although I found an ugly-hack way to fix it using a timeout.
```
$timeout(function() {
                $ionicSlideBoxDelegate.$getByHandle('photos').slide(index);
            },   100);
```

**Comment by RameshJhajharia** [comment] 2015-10-06 08:46
Getting same issue at  `$ionicSlideBoxDelegate.next();`. The strange thing is that it is working at one place in my app but not working in another app.

**Comment by rajeshwarpatlolla** [comment] 2016-01-04 17:19
+1

**Comment by marlonmantilla** [comment] 2016-10-24 20:19
Having same issue here too, neither of the solutions above worked for me.
