### ISSUE TITLE
Ionic deployed on mobile website doesn't hide address bar when scrolling down

### ISSUE THREAD

**Issue by yosikal** [driftyco/ionic#6168] opened 2016-04-14 12:51 UTC
This issues concerns deploying Ionic as mobile website. When scrolling down a long <ion-content> item the Safari/Chrome address bar does not hide.

**Comment by jgw96** [comment] 2016-04-14 14:50
Hello! Thanks for opening an issue with us! I have been able to confirm this issue and will now look further into it.

**Comment by michaelgeorgeattard** [comment] 2016-10-07 13:39
Any updates on this please?

**Comment by alexmgrant** [comment] 2017-05-02 03:53
I believe the issue is caused by how ionic handles scrolling. It's within an absolute position dom element so the native browser chrome does not know the user has in fact scrolled down. This is me testing on latest ios safari & ionic 2.

**Comment by jgw96** [comment] 2017-05-02 15:59
Hello, all! As this would require significant changes to our `ion-content` element for what would be little gain I am going to close this issue for now as a `not fix`. Thanks for using Ionic everyone!

**Closed by jgw96** 2017-05-02 15:59 UTC
Labels: css, v2

**Comment by osamasoliman** [comment] 2017-05-08 05:14
I have the same problem on chrome mobile browser with my ionic app as a PWA here:

[Dawaey Ionic PWA](http://dawaey.com/app)

**Comment by alexmgrant** [comment] 2017-05-09 05:16
Since there is no fix incoming, can anyone suggest fix that has dealt with this?

**Comment by shahas1** [comment] 2017-10-05 06:07
Hello, any updates on this?

**Comment by LeonardoGuimaraes** [comment] 2017-10-13 19:12
Any update?

**Comment by NativeDigitalLab** [comment] 2018-01-24 20:49
Any Update? Or a workaround to achieve this?

**Comment by NativeDigitalLab** [comment] 2018-01-24 20:51
We use on our project Ionic for apps and mobile web. It would be very helpful if we could achieve this with a workaround.

**Comment by brandoncorbin** [comment] 2018-07-24 00:07
I don't have a solution - The address bar only hides when the body is scrolled - since ion-content if fixed and handles scrolling  the body never gets scrolled. I wonder if you could tap into the ion-content scroll event, and trigger some body scrolling...
