### ISSUE TITLE
"menu-close" should not close the menu when large screen and expose-aside-when="large"

### ISSUE THREAD

**Issue by vevisystems** [driftyco/ionic#2852] opened 2015-01-04 15:33 UTC
When having side menus, it is common to add each link inside the menu the directive "menu-close", so that the menu hides automatically when the user navigates to a different view.

This works fine except when you add  expose-aside-when="large" option. The expected behaviour is to keep the menu always visible if you are on a large screen. When the menu is on the left, it works ok, but with the menu on the right, "menu-close" items close the menu and left an empty space on the screen.

(This may be related to #2767)

**Comment by Ionitron** [comment] 2015-03-30 23:30
Greetings @vevisystems!

My sensors indicate that I require more information in order to assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this happen occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com), where many humans will be able to offer wisdom and advice.

Thank you for allowing me to assist you.

<span ionitron-needs-reply></span>

**Comment by Ionitron** [comment] 2015-04-30 07:16
Greetings @vevisystems!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment] 2015-04-30 07:16
Greetings @vevisystems!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-04-30 07:16 UTC
Labels: ionitron:closed
