### ISSUE TITLE
Getting a blank page on quick navigation

### ISSUE THREAD

**Issue by akagr** [driftyco/ionic#8097] opened 2016-09-16 10:09 UTC
#### Short description of the problem:
Let's say I have two pages A and B where A is the root or first page in history stack. If I go to B and then quickly go back to A by hitting the button in header bar, I get a blank page. It may need a few tries to replicate.

I also found that when I do get a blank page, there are no console errors and the page A is actually being deleted from DOM. I guess it's the issue with cache deletion happening a little too late.

![image](https://cloud.githubusercontent.com/assets/2797603/18582544/4e57ee16-7c23-11e6-8041-068bde8ea2d6.png)

#### What behavior are you expecting?
The previous page should always show up and cache should be deleted properly.

**Steps to reproduce:**
1. Have at least two pages in the app
2. Quickly go back and forth between them
3. May have to do this repeatedly for this to replicate

**Other information:** There was a bug in ionic 1 which sounds like this one https://github.com/driftyco/ionic/issues/4369

**Which Ionic Version?** 2.0.0-beta.11

```
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v5.5.0
Xcode version: Xcode 7.3.1 Build version 7D1014
```

**Comment by herbzi** [comment] 2016-09-16 11:32
Yea i had the same problem. I hacked in an extra 200ms of clickblock because If I pressed back very quickly it would break the app. This is currently my biggest gripe with ionic, the navigation system is so unbelievably flimsy right now.

**Comment by akagr** [comment] 2016-09-16 11:39
@herbzi yeah insufficient clickblock was the main problem. I found this to be the cause as well. What I've done to make it work is that I've exposed a wrapper service on NavController. Since our app has only one main ion-nav, I router all the push and pops through this wrapper.

This wrapper in turn makes use of promises returned from push and pop methods to queue them up so everything happens sequentially. Still testing this out but so far it looks promising.

**Comment by herbzi** [comment] 2016-09-16 11:46
I'm not quite as sophisticated, i just overrode the "setEnabled" method in the navcontroller prototype with a wrapper method that adds 200ms to the time. I use a bunch of cheap hacks to make sure the navigation system doesn't break down. My app was rejected twice because of navigation issues like these.

**Comment by herbzi** [comment] 2016-09-16 12:17
Yea I wasn't quite a sophisticated, I just overrode the setEnabled method of the navcontroller prototype with a wrapper method that adds 200ms to the time. My app contains a bunch of cheap hacks to fix issues like these.  My app was rejected twice because of navigation issues.

**Comment by jgw96** [comment] 2016-09-16 14:59
Hello all! This should be fixed in beta.12 as we did a complete overhaul of the internals of navigation which includes getting rid of alot of the async things happening internally on each transition. I will confirm with testing once we get to that stage internally (should be extremely soon, like within a few days (: )

**Comment by jgw96** [comment] 2016-09-20 18:33
Hello all! After testing with beta.12 I cannot seem to reproduce this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-09-20 18:33 UTC
Labels: navigation, needs reply, v2

**Comment by 1BJK903** [comment] 2017-11-11 18:08
@jgw96: I still have this issue, though. How to solve this?
