### ISSUE TITLE
Ion tabs bug

### ISSUE THREAD

**Issue by samuelmrp** [driftyco/ionic#4922] opened 2016-01-07 17:34 UTC
I am learning Ionic and found this tutorial https://devdactic.com/user-auth-angularjs-ionic/

I didn't want to CTRL+C CTRL+V then I did all the steps by myself. When I launch the application through 'ionic serve' and try to access the forbbiden tab (admin) then the tab item css switch to 'tab-item-active' but this place is forbidden so my application show an alert and then switch back to dashboard tab, but the tab item class doesn't switch in this versions.

if you download this example and run, everything will run smothly, its because the ionic version is 1.0.0-rc.5 and I did tested on 1.2.1 and 1.2.4.

Its a little bug, I am learning angular too so I can't figure out by myself any workarround.

Regards,
 Samuel

**Comment by jgw96** [comment] 2016-03-14 18:30
Hello! Thanks for opening an issue with us, we just need a little more info from you so that we can better help you with your issue. Would you mind posting a code sample, plunkr or codepen that we can use to reproduce your issue? Also, would you mind running `ionic info` and posting the output? Thanks again!

**Comment by jgw96** [comment] 2016-03-21 19:16
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!

**Closed by jgw96** 2016-03-21 19:16 UTC
Labels: tabs, v1
