### ISSUE TITLE
StatusBar hide not hiding the statusbar but instead just covering it with my header color.

### ISSUE THREAD

**Issue by rhuldip** [driftyco/ionic#7936] opened 2016-09-01 06:38 UTC
**Note: If you are having problems formatting your issue please refer to this article on using markdown in Github:**

https://guides.github.com/features/mastering-markdown/

**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### What behavior are you expecting?

**Steps to reproduce:**
1. 
2. 
3. 

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x

#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

**For Ionic 2 issues** - http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by rhuldip** [comment] 2016-09-01 06:39
i tried using StatusBar.hide().

**Comment by jgw96** [comment] 2016-09-01 18:48
Hello, thanks for opening an issue with us! Would you mind posting a little more info about your issue and a repo that i can use to reproduce this issue? Thanks for using Ionic!

**Comment by jgw96** [comment] 2016-09-06 12:48
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-09-06 12:48 UTC
Labels: header, needs reply, v2
