### ISSUE TITLE
bug: In one tab state.go can not work to go to another tab?

### ISSUE THREAD

**Issue by jackgray1983** [driftyco/ionic#4607] opened 2015-11-06 12:55 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>browser</span>

<span ionic-description>I have a tab view with four tabs named welcome, news, tasks, user respectively. now I want to click one label in the tab of user to jump to the tab of tasks, but state.go didn't work. However when I click the tab of tasks it shows, so what is the reason?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-11-06 12:56
Greetings @jackgray1983!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4607). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4607)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by jgw96** [comment] 2016-03-14 21:41
Hello! Thanks for opening an issue with us, we just need a little more info from you so that we can better help you with your issue. Would you mind posting a code sample, plunkr or codepen that we can use to reproduce your issue? Also, would you mind running `ionic info` and posting the output? Thanks again!

**Comment by jgw96** [comment] 2016-03-21 19:53
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!

**Closed by jgw96** 2016-03-21 19:53 UTC
Labels: navigation, tabs, v1
