### ISSUE TITLE
ionic serve --lab crashes frequently

### ISSUE THREAD

**Issue by Michael77** [driftyco/ionic#8415] opened 2016-10-03 03:06 UTC
#### Short description of the problem:

Every few minutes 'ionic serve --lab' will crash with this error:
```
<--- Last few GCs --->
  531479 ms: Mark-sweep 1270.0 (1434.9) -> 1270.0 (1434.9) MB, 1394.6 / 0.0 ms [allocation failure] [GC in old space requested].
  532927 ms: Mark-sweep 1270.0 (1434.9) -> 1270.0 (1434.9) MB, 1447.8 / 0.0 ms [allocation failure] [GC in old space requested].
  534428 ms: Mark-sweep 1270.0 (1434.9) -> 1279.2 (1404.9) MB, 1499.1 / 0.0 ms [last resort gc].
  535875 ms: Mark-sweep 1279.2 (1404.9) -> 1288.4 (1404.9) MB, 1446.7 / 0.0 ms [last resort gc].
<--- JS stacktrace --->
==== JS stack trace =========================================
Security context: 0x35386adcfb51 <JS Object>
    1: map [native array.js:~994] [pc=0x2ec9fa976e12] (this=0x9c9414818f9 <JS Array[95192]>,bq=0x3a323562009 <JS Function (SharedFunctionInfo 0x38cacaa04f71)>,br=0x35386ad04381 <undefined>)
    2: arguments adaptor frame: 1->2
    3: encode(aka encode) [/path/to/node_modules/rollup/dist/rollup.js:375] [pc=0x2ec9f97446ae] (this=0x35386ad04381 <undefined>,decode...
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0xd6a4ac [node]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewRawOneByteString(int, v8::internal::PretenureFlag) [node]
 6: v8::internal::Factory::NewStringFromOneByte(v8::internal::Vector<unsigned char const>, v8::internal::PretenureFlag) [node]
7: v8::internal::Factory::NumberToString(v8::internal::Handle<v8::internal::Object>, bool) [node]
 8: v8::internal::Object::ToString(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>) [node]
 9: v8::internal::Object::ConvertToName(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>) [node]
10: v8::internal::Runtime_HasProperty(int, v8::internal::Object**, v8::internal::Isolate*) [node]
11: 0x2ec9f97092a7
```

**Steps to reproduce:**
1. run 'ionic serve --lab' 
2. make code changes
3. sometimes it will crash, every 5 minutes or so 

Cordova CLI: 6.3.0
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Distributor ID:	Arch Description:	Arch Linux 
Node Version: v6.7.0

**Comment by NoNameProvided** [comment] 2016-10-03 13:40
Happening from me as well, without the `--lab` flag. Its related to a memory leak what Node complain about every time when `ionic serve` re-compile the source files.

**Comment by jgw96** [comment] 2016-10-03 14:10
Hello all! Thanks for opening an issue with us! I am going to be closing this issue as a duplicate of https://github.com/driftyco/ionic-app-scripts/issues/62. Thanks for using Ionic!

**Closed by jgw96** 2016-10-03 14:10 UTC
