### ISSUE TITLE
bug: PopOver issue in Android 4.4.4 Device

### ISSUE THREAD

**Issue by Purus** [driftyco/ionic#3036] opened 2015-02-05 16:53 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>When iOS style is forced for the PopOver in real Android device, there seems to be an issue. In all browsers it looks and works fine.

But in the actual device, a empty area is introduced above the nav bar. Also the popover hides the menu button instead of showing it below the menu button.

Also, when we touch the menu item inside popover, coloring is not down as it happens in browser. In browser, a grey background is shown after the click or touch which is expected in real device also. Without this the user does not get the feel of touching the menu.

```javascript
module.config(function($cordovaAppRateProvider) {
    /*document.body.classList.remove('platform-ios');
    document.body.classList.remove('platform-android');
    document.body.classList.remove('platform-ionic');*/
    document.body.classList.add('platform-ios');
});
```

<img src="http://ionic-forum-uploads.s3.amazonaws.com/8893c22f5fa5ca46debbf9f902a61150bc31aebfa934.png"/></span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-02-05 16:53
Greetings @Purus!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3036). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3036)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Purus** [comment] 2015-02-06 09:34
The issue occurs even in Android 5 device.

1) An empty space is introduced at the top.
2) When an item is touched in the popover, the item is not highlighted.
3) The entrie popover area is filled with the menu items in browser. But in actual device, there are empty space at the bottom.
4) Horizontal lines are not present beween the items as its in browser

**Comment by Purus** [comment] 2015-02-08 14:23
Can some experts show some love for this issue? I am holding my app release for this.

Thanks in advance.

**Comment by mhartington** [comment] 2015-02-09 18:41
Can you provide a codepen demo for this please

**Comment by Purus** [comment] 2015-02-09 18:44
As mentioned, any browser based demo works fine. this issue occurs only in real device.

In browsers, they all work as expected. so with codepen demo you will not be able to see this issue.

Please deploy a sample popup app in your device and you can see this. Please let me know if you need any other inputs on this.

**Comment by mhartington** [comment] 2015-02-09 23:00
So basically it's all a conflict for between iOS specific classes and android specific classes. 
When you inspect the device through chrome, you can see a bunch of classes getting applied.

```
class="platform-android platform-cordova platform-webview platform-ios grade-a platform-android4 platform-android4_4 platform-ready popover-open"
````

So even though you're adding `platform-ios`, you are going to get `platform-android` as well, and since [android styles](https://github.com/driftyco/ionic/blob/master/scss/_popover.scss#L120) for popover comes after ios, they will still get applied.

So you need to change the css for the list items as well and the scroll content on android as well. 
Not an issue with ionic, but some custom css needs to done.

**Closed by mhartington** 2015-02-09 23:00 UTC
Labels: popover

**Comment by Purus** [comment] 2015-02-10 14:07
Ok, Thanks.

What about the issue of adding empty area at the top?

**Comment by mhartington** [comment] 2015-02-10 14:12
Its some margin that is specific to iOS.

**Comment by Purus** [comment] 2015-02-10 17:21
Thanks @mhartington .

Again, even if we use default Android styling in Android devices, the popover covers the header button, which should be an issue.

**Comment by Purus** [comment] 2015-02-10 17:22
What I don't understand is that even if it happens as you say, why does it work correctly in browsers when forcing iOS style?

**Comment by Purus** [comment] 2015-02-10 17:25
Also why does not the lines between lines show and why does not it highlight during touch action? Users are not sure whether they have clicked the item without the color changes.

**Comment by mhartington** [comment] 2015-02-10 21:48
Popover Covering header: This is by design.

Buttons not showing clicks: By design. 
Even in the demo, when you toggle android, there is no high light color.

http://codepen.io/ionic/pen/GpCst

If you have any other concerns, please open a new issue.
