### ISSUE TITLE
Ion-Input with clearInput set to True, tabbing out of the field sets focus on hidden button

### ISSUE THREAD

**Issue by tonyawad88** [driftyco/ionic#11288] opened 2017-04-20 10:50 UTC
**Ionic version:**  (check one with "x")
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report

**Current behavior:**
If we have an ion-input with its "clearInput" attribute set to true, when we try to tab out of the input field, the next field doesn't get focused / highlighted. I believe the tabIndex of the clear button should be set to -1 ? The "clear button" doesn't even show up when the tab key on the keyboard is hit. It's kind of an invisible focus, in order to get to the next input field, you need to tab twice.
```
  <ion-item>
      <ion-label color="primary" fixed>blabla</ion-label>
      <ion-input type="text" required="" maxLength="5" [disabled]="modify" clearInput="true" 
              [(ngModel)]="myModel" name="myModel"></ion-input>
  </ion-item>
```

**Expected behavior:**
Tabbing out of a field should bring you to the next field.

**Steps to reproduce:**
1. Set the clearInput to true on an ion-input
2. Have another ion-input after it and watch how it doesn't get focused until you hit tab key again.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: macOS Sierra
Node Version: v7.6.0
Xcode version: Xcode 8.0 Build version 8A218a
```

**Comment by jgw96** [comment] 2017-04-27 14:56
Hello, thanks for using Ionic! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/9699.

**Closed by jgw96** 2017-04-27 14:56 UTC
