### ISSUE TITLE
perf: Ionic 2 app on real device looking weird

### ISSUE THREAD

**Issue by praveens96** [driftyco/ionic#7928] opened 2016-08-31 17:40 UTC
**Type**: <span ionic-type>perf</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>i have started building a ionic 2 app. in browser and simulator it was looking nice. but after placing it in real device i.e. iPhone 6 and 6 Plus the UI is completely damaged. looking very weird. all the text is zoomed by 50%. space was left for battery, time and signal at the top, it ate some space. overall the UI is very bad. its not at all as shown in the browser. with Ionic 1 UI used to be very good but with ionic 2 UI is completely disappointing. Even the keyboard is not the one you get in messaging.

is anybody facing similar issue? can someone help me in improvising the UI.</span>

<span is-issue-template></span>

**Comment by astec** [comment] 2016-09-01 09:58
- Do you use latest beta?
- Can you add screenshots and provide a plunker?

**Comment by rhuldip** [comment] 2016-09-01 13:15
Hi Astec... i have added the screenshots.
You can see difference between view in ionic-lab and real device.
Everything seems so zoomed.
![image](https://cloud.githubusercontent.com/assets/12796087/18168642/4eb46930-7074-11e6-8716-2381705e500b.png)

**Comment by rhuldip** [comment] 2016-09-01 13:16
![image](https://cloud.githubusercontent.com/assets/12796087/18168659/60a2c18c-7074-11e6-8b55-36076824bd51.png)

**Comment by rhuldip** [comment] 2016-09-01 13:17
The first image is through ionic-lab and the second one through simulator.

**Comment by rhuldip** [comment] 2016-09-01 13:23
The first screenshot is taken from ionic-lab which is the required UI,but once i run it in simulator everything seemed so zoomed.
![simulator screen shot 01-sep-2016 6 50 09 pm](https://cloud.githubusercontent.com/assets/12796087/18168821/262c62c8-7075-11e6-8de0-ff154cb70c5d.png)
![screen shot 2016-09-01 at 6 38 05 pm](https://cloud.githubusercontent.com/assets/12796087/18168828/30c2b188-7075-11e6-9225-f901502a2191.png)

**Comment by jgw96** [comment] 2016-09-01 13:54
Hello! Could you provide a repo that I could reproduce this issue with? Also, are you seeing this on actual devices, or the ios sim? Do you also see this issue on Android? Thanks!

**Comment by jgw96** [comment] 2016-09-01 21:36
Hello, because i cannot seem to reproduce this issue with any of our test apps on either the ios sim or on a real device (iphone 5) i am going to be closing this issue for now. Most likely this is caused by settings on your ios simulator and not an Ionic issue. Thanks for using Ionic!

**Closed by jgw96** 2016-09-01 21:36 UTC
Labels: needs reply, v2

**Comment by praveens96** [comment] 2016-09-02 14:56
yes, i confirm the issue is not with ionic. while building the app the Launch Screen was empty and after selecting .xib it was all good. thank you.
