### ISSUE TITLE
bug: multiple views rendered if rubbing on multiple buttons

### ISSUE THREAD

**Issue by hsdk123** [driftyco/ionic#4828] opened 2015-12-20 09:08 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi, I'm noticing that if I have a couple of buttons (a) that each lead to different views (hrefs), if I rub my finger against both of them back and forth, I realise that both of them get rendered at the same time (whereas I am expecting only the first button that got touched to have it's href triggered).

Platform: ios9</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-12-20 09:08
Greetings @hsdk123!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4828). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4828)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by RubbingButtons** [comment] 2015-12-20 15:44
@hsdk123 How quickly do you rub these buttons back and forth? Exactly where do you rub them? Please explain your method. I find it difficult enough to get a single button to trigger, let alone two at once. And that's ngIf if can get it to ngShow. This sounds like a feature, not a bug.

Are you using one finger or is this multi-touch? I've been told not to Hammerjs too much. And there is a bug with the double tap and long press anyway. https://github.com/hammerjs/hammer.js/issues/86

How did you even get these buttons together in the same view? Did you uninstall Sass? Maybe you just used Less.

Please post a link to the directive you used. When I have a model in my view, I find it difficult to controller.

Does this bug relate to the multiple spinners issue? https://github.com/driftyco/ionic/issues/4819

Are your buttons in a form with any other inputs? Does the form action change when it goes from ngPristine to ngDirty?

Did you decorate their properties with CSS, or are they bare? Tell me about their attributes. Details please.

Did you use a recursive function or did you exit immediately? I hope you didn't return null. Whichever way, I'd be worried about an early software release.

**Comment by jgw96** [comment] 2016-03-14 19:16
haha, nice issue guys!

**Closed by jgw96** 2016-03-14 19:16 UTC
