### ISSUE TITLE
NavController LoadPage silently fails if the target page can't resolve all parameters

### ISSUE THREAD

**Issue by hannesthorwork** [driftyco/ionic#7608] opened 2016-08-08 18:28 UTC
#### Short description of the problem:
NavController LoadPage silently fails if the target page can't resolve all parameters.

#### Plunker that shows an example of your issue
http://plnkr.co/edit/ztfocIG4wggtMVreZd3a?p=preview

#### What behavior are you expecting?
I'm expecting to see an error in the console.

**Steps to reproduce:**
1. Create a page with an untyped parameter in the constructor
2. Try to transition to the page from another

    NavController.prototype.loadPage = function (view, viewport, opts, done) {
        var _this = this;
        if (!viewport || !view.componentType) {
            return;
        }
        // TEMPORARY: automatically set selector w/ dah reflector
        // TODO: use componentFactory.create once fixed
        bootstrap_1.addSelector(view.componentType, 'ion-page');
        this._compiler.resolveComponent(view.componentType).then(function (componentFactory) {
...
       })
        .catch(function (error) {
            console.log(error);  //<<<<<<<<<<<<<<<<<<<<<<<<<< THIS IS MISSING IN IONIC 2
        });

**Which Ionic Version?** 
2.0.0-beta.10

**Comment by jgw96** [comment] 2016-08-09 17:10
Hello! Thanks for using Ionic! Unfortunately I cannot reproduce this issue. I can confirm that i am getting an error in the console as seen here:
![screen shot 2016-08-09 at 12 08 23 pm](https://cloud.githubusercontent.com/assets/8823093/17525837/2227d8f4-5e2a-11e6-95f4-a850193034d7.png)
Since I cannot reproduce this issue in any tests or on the plunker i will be closing this issue for now. Thanks for using Ionic!

**Closed by jgw96** 2016-08-09 17:10 UTC
Labels: enhancement, v2
