### ISSUE TITLE
bug: Range slider prevents smooth vertical scrolling

### ISSUE THREAD

**Issue by AntonKL** [driftyco/ionic#4172] opened 2015-07-31 14:32 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>When using several range slider on top of each other scrolling is very hard. You need to touch outside of the range slider to be able to scroll.

Demo (try in phone to see problem - not present on a computer without touch-screen) http://embed.plnkr.co/OGy8c9haGJOIkc9awBVn/preview

A possible solution would be to only prevent vertical scrolling when the range circle is pressed. That would also copy the behavior of a native range slider.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-07-31 14:32
Greetings @AntonKL!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4172). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4172)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment] 2015-07-31 16:08
Confirmed. It may be time make a range directive. 
Another option in the mean time is to use native scrolling. 

```
 <ion-content overflow-scroll="true">
      <ion-list>
          <div class="item range range-positive" ng-repeat="item in items">
            <i class="icon ion-ios-sunny-outline"></i>
            <input type="range" name="volume" min="0" max="100" value="33">
            <i class="icon ion-ios-sunny"></i>
          </div>
      </ion-list>
  </ion-content>
```

**Comment by Ionitron** [comment] 2015-10-29 19:13
Greetings @AntonKL!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-10-29 19:13 UTC
Labels: feature, ionitron:closed
