### ISSUE TITLE
bug: IonRouterOutlet | Type '{ children: Element[]; }' is missing the following properties from type 'Pick<IonRouterOutlet & { basePath?: string | undefined; ref?: Ref<any> | undefined; ionPage?: boolean | undefined; } & IonicReactProps & Omit<...>, keyof IonicReactProps | ... 253 more ... | "ionPage">': onPointerEnterCapture, 

### ISSUE THREAD

**Issue by DunhamGitHub** [driftyco/ionic#29180] opened 2024-03-19 09:45 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Following the vanilla starter tutorial with 0 modification to code: https://ionicframework.com/docs/react/quickstart

```
npm install -g @ionic/cli
ionic start myApp blank --type=react
cd myApp
```

<img width="833" alt="Screenshot 2024-03-19 at 16 37 57" src="https://github.com/ionic-team/ionic-framework/assets/6884752/16600de4-6243-418f-b630-ef53098c3d49">

### Expected Behavior

No error after creating a new project from scratch.

### Steps to Reproduce

1. Goto https://ionicframework.com/docs/react/quickstart
2. Follow the first 2 steps (until myApp is created)
3. Open App.tsx

### Code Reproduction URL

1

### Ionic Info

```
[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module
       '@capacitor/ios/package.json'
       
       Require stack:
       - /usr/local/lib/node_modules/@ionic/cli/lib/project/index.js
       - /usr/local/lib/node_modules/@ionic/cli/lib/index.js
       - /usr/local/lib/node_modules/@ionic/cli/index.js
       - /usr/local/lib/node_modules/@ionic/cli/bin/ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module
       '@capacitor/android/package.json'
       
       Require stack:
       - /usr/local/lib/node_modules/@ionic/cli/lib/project/index.js
       - /usr/local/lib/node_modules/@ionic/cli/lib/index.js
       - /usr/local/lib/node_modules/@ionic/cli/index.js
       - /usr/local/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI       : 7.2.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 7.8.0

Capacitor:

   Capacitor CLI      : 5.7.3
   @capacitor/android : not installed
   @capacitor/core    : 5.7.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.1

System:

   NodeJS : v20.11.1 (/usr/local/Cellar/node@20/20.11.1/bin/node)
   npm    : 10.2.4
   OS     : macOS Unknown
```

**Comment by liamdebeasi** [comment] 2024-03-19 13:16
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/29178.

**Closed as not planned by liamdebeasi** 2024-03-19 13:16 UTC
Labels: triage
