### ISSUE TITLE
ion-tab with DeepLinker not working?

### ISSUE THREAD

**Issue by zhengmin4516** [driftyco/ionic#9831] opened 2016-12-30 06:31 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Related code:**

```
IonicModule.forRoot(MyApp,{},{
      links: [
        { component: HomePage, name: 'Home', segment: 'home' },
        { component: UserPage, name: 'User', segment: 'user/:id' }
      ]
    })
```

**Other information:**
![image](https://cloud.githubusercontent.com/assets/12004034/21560593/87336ed8-ce9c-11e6-8a41-60db098b5dfd.png)

`cmd + R` 
![image](https://cloud.githubusercontent.com/assets/12004034/21560596/8d1e1ea6-ce9c-11e6-95e4-08f68f6852e4.png)

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment] 2017-01-03 15:07
Hello, thanks for opening an issue with us! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/9183.

**Closed by jgw96** 2017-01-03 15:07 UTC
