### ISSUE TITLE
ion-infinite-scroll is broken

### ISSUE THREAD

**Issue by kumaresan-cgvak** [driftyco/ionic#10889] opened 2017-03-23 13:30 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

If we include ```ion-infinite-scroll``` in a Page, then the page content height is broken.
A blank white space is added at bottom of the page.

**Expected behavior:**

if a n user scroll to teh end it should triger the `ionInfinite` event.

**Steps to reproduce:**

**Related code:**

```
  <ion-infinite-scroll (ionInfinite)="getMoreArticles($event)">
     <ion-infinite-scroll-content loadingSpinner="bubbles" loadingText="Loading...">
     </ion-infinite-scroll-content>
 </ion-infinite-scroll>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.0 
ios-sim version: 5.0.12 
OS: macOS Sierra
Node Version: v7.2.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment] 2017-03-23 14:10
Hello, thanks for opening an issue with us. I cant seem to reproduce this issue locally, any chance you could provide a repo i could use to reproduce this?

**Comment by kumaresan-cgvak** [comment] 2017-03-23 15:00
`ion-content` shoudl have dynamic content. Where based on conditions, the content inside the `ion-content` is changed between `ion-grid ` and  `ion-list`.

Also this happens After updating the `ionic-angular` to `2.3.0`

**Comment by NoNameProvided** [comment] 2017-03-23 15:39
Do you use refresher also? They cannot play nicely together.

**Comment by kumaresan-cgvak** [comment] 2017-03-23 16:26
@NoNameProvided NO

**Comment by mattlin4567** [comment] 2017-03-23 16:28
I have same issue after upgrading to 2.3.0
my ionic info:

```
    Cordova CLI: 6.5.0 
    Ionic Framework Version: 2.3.0
    Ionic CLI Version: 3.0.0-beta.4
    ios-deploy version: 1.9.0 
    ios-sim version: 5.0.8 
    OS: macOS Sierra
    Node Version: v6.9.1
    Xcode version: Xcode 8.1 Build version 8B62
```

it works when the initial list is short(all in one page), but if the list is longer than on page, ionInfinite won't fire when reach the bottom of page.

**Comment by anphu7492** [comment] 2017-03-23 23:30
I experienced the same issue but with reversed infinite scroll. It triggers the function when scrolling to the top but automatically change the state from `disabled` to `enabled` after a while (about 20 seconds) or when change view and then come back.

Related code: 

```
//*.html
<ion-infinite-scroll (ionInfinite)="loadMoreMessages($event)"
                       position="top"
                       [enabled]="shouldEnableScrolling">
    <ion-infinite-scroll-content
      loadingSpinner="bubbles"
      loadingText="Loading more data...">
    </ion-infinite-scroll-content>
  </ion-infinite-scroll>
```

``` 
//*.ts
loadMoreMessages(infiniteScroll?) {
       this.getMessages()
       .subscribe(messages => {
         this.shouldEnableScrolling = messages.length >= this.fetchLimit;
         ...
         if (infiniteScroll) {
           infiniteScroll.complete();
         }
       });
     }
```

**Comment by dmastag** [comment] 2017-03-26 14:44
I have a similar issue that I think is related.
Since upgrading to 2.3.0 ion-infinite is not working, but on iOS only.

Steps to reproduce:

1. Create new ionic project ``ionic start testinfinite blank --v2``
2. Use exact code as per [this guide](http://ionicframework.com/docs/v2/api/components/infinite-scroll/InfiniteScroll/#usage)
3. Build and run with xcode

This are the scenarios I have tested and passed is represented by a check mark:

- [x] ionic serve on Windows
- [x] ionic serve on Sierra MacOS
- [x] run on android device (Asus Zenfone 3)
- [ ] run on iOS device (iPhone SE)

**Comment by TLockcuff** [comment] 2017-03-27 00:12
I'm experiencing this issue as well. The `ion-infinite-scroll` works fine in chrome, but not on an iOS device.

iOS: 10.2.1
Ionic Framework: 2.3.0

When scrolling to the bottom of `ion-content`, there's a blank section of 84 pixels. I assuming this is where the ion-infinite spinner would normally show. 

I tried adding/removing the `enabled` property on the `ion-infinite-scroll` input. This had no effect.

**Comment by ramoncarreras** [comment] 2017-03-27 09:36
Yes, same problem here. Ion-infinite is not working on iOS emulator or real device.

> Cordova CLI: 6.5.0
> Ionic Framework Version: 2.3.0
> Ionic CLI Version: 2.2.1
> Ionic App Lib Version: 2.2.0
> Ionic App Scripts Version: 1.1.4
> ios-deploy version: 1.9.0
> ios-sim version: 5.0.11
> OS: macOS Sierra
> Node Version: v7.1.0
> Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by lukezona** [comment] 2017-03-27 11:31
Same problem here. 

I'm using infinite scroll in a ion-grid element and it works everywhere except for iOS.

The strange thing is that after editing threshold and paddings it works on the first scroll and then stops working.

`Cordova CLI: 6.5.0 
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.0 
ios-sim version: 5.0.12 
OS: macOS Sierra
Node Version: v6.0.0
Xcode version: Xcode 8.2.1 Build version 8C1002`

**Comment by KennedyIhe** [comment] 2017-03-28 01:10
I have the same issue after upgrading to 2.3.0. downgrading fixes the issue

**Comment by danielabbatt** [comment] 2017-03-28 14:39
My issue wasn't in an ion-grid element, but same problem. Works fine on 2.2.0, simply rolled back in package.json, no other changes required.

**Comment by emersonjsouza** [comment] 2017-03-28 23:15
@danielabbatt version 2.2.0 works fine, thank you !

**Comment by tscislo-lingaro** [comment] 2017-03-30 12:21
The same in here:

Cordova CLI: 6.5.0
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.9.5
Xcode version: Not installed

Any chance for a fix to this?

**Comment by jgw96** [comment] 2017-03-31 15:05
Hello, thanks for opening an issue with us! This issue was caused by a regression related to scroll events in ionic 2.3.0. This has since been fixed and will be in the 3.0 release. Sorry about the hassle!

**Closed by jgw96** 2017-03-31 15:05 UTC
Labels: needs info, v2

**Comment by dmastag** [comment] 2017-04-01 05:15
@jgw96 does this mean that we have to choose to either use 2.2.0 or wait until 3 is released?

**Comment by HamzaLJ** [comment] 2017-04-01 16:25
Same here!!! It does not work on iOS

**Comment by tscislo-lingaro** [comment] 2017-04-02 17:44
@jgw96 how much breaking change 3.0.0 going to be?

**Comment by shinta5150** [comment] 2017-04-03 06:05
Also experiencing this issue.

**Comment by corran2go** [comment] 2017-04-04 15:05
@jgw96 what about a 2.3.1 with this fix?

**Comment by wodka** [comment] 2017-04-05 12:03
there should clearly be a bugfix in the 2.3.x series...

**Comment by NoNameProvided** [comment] 2017-04-05 15:50
Ionic 3.0 is released today, so you can start use it.

**Comment by dmastag** [comment] 2017-04-05 16:01
Yes, just saw the release an hour ago and am in the process of upgrading using the migration guide.
Will hopefully be able to put the result i get here.

**Comment by dmastag** [comment] 2017-04-05 16:38
Updated App to ionic3, sadly problem is still happening

**Comment by dmastag** [comment] 2017-04-05 16:57
Again tried exactly my steps as per [my previous comment](https://github.com/driftyco/ionic/issues/10889#issuecomment-289288796) (new app with ionic3 and add ion-infinite) and its still not working.

Does anyone have a hack for this?

**Comment by NoNameProvided** [comment] 2017-04-05 18:11
Lets mention @jgw96 then

**Comment by dmastag** [comment] 2017-04-05 18:17
@NoNameProvided not sure if that works. Since I think that closed issues are not checked frequently and I believe that he received tons of notifications.

Since he mentioned something about scroll events so I checked for any similar issues and found #10938. Then tried to do a new app with

    <ion-content (ionScroll)="doSomething()">

Indeed that one is also not working on iOS. I guess those issues are connected.

**Comment by xx0r** [comment] 2017-04-05 20:49
I can confirm, that upgrading from 2.3.0 to 3.0.0. doesn't fix this issue for iOS

**Comment by djereg** [comment] 2017-04-05 23:00
````typescript
export class MyPage {
  @ViewChild('container') container: Container;

  ionViewDidLoad() {
    this.container.enableScrollListener();
  }
}
````

This worked for me, but tested only on Android.

**Comment by dmastag** [comment] 2017-04-06 01:35
Got some advise from North McCormick on Slack to use wkwebview
https://github.com/driftyco/cordova-plugin-wkwebview-engine#installation-instructions

And can confirm that its working as a temporary workaround

**Comment by BatMen** [comment] 2017-04-06 14:58
I can confirm the issue. Fresh last ionic version.

**Comment by ryaa** [comment] 2017-04-10 17:10
ion-refresher and ion-inifinite-scroll stopped working after upgrade to 2.3.0. Downgrading to 2.2.0 fixed the problem

**Comment by BatMen** [comment] 2017-04-11 06:27
@ryaa 

It's working again in last release 
https://github.com/driftyco/ionic/releases/tag/v3.0.1

The only upgrade is package.json and this line in app.module.ts

`import { BrowserModule } from '@angular/platform-browser';`

and

`    BrowserModule,
     IonicModule.forRoot(MyApp)`

package.json looks like this : 

`"dependencies": {
    "@angular/common": "4.0.0",
    "@angular/compiler": "4.0.0",
    "@angular/compiler-cli": "4.0.0",
    "@angular/core": "4.0.0",
    "@angular/forms": "4.0.0",
    "@angular/http": "4.0.0",
    "@angular/platform-browser": "4.0.0",
    "@angular/platform-browser-dynamic": "4.0.0",
    "@ionic-native/core": "3.4.2",
    "@ionic-native/splash-screen": "3.4.2",
    "@ionic-native/status-bar": "3.4.2",
    "@ionic/storage": "2.0.1",
    "ionic-angular": "3.0.1",
    "ionicons": "3.0.0",
    "rxjs": "5.1.1",
    "sw-toolbox": "3.4.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.3.0",
    "typescript": "~2.2.1"
  },`

**Comment by yaozuwang** [comment] 2017-10-06 05:55
same problem ionic framework: ionic-angular 3.6.0

**Comment by akashmahale** [comment] 2018-04-17 08:52
i have the same issue. infinite scroll fires multiple events

**Comment by alonetech** [comment] 2018-06-21 12:46
ion-infinite-scroll issue event is not fired

I am getting 10 data per pagination but after 2 pages event is not working in function.

<ion-infinite-scroll (ionInfinite)="loadMore($event)">
   <ion-infinite-scroll-content loadingSpinner="bubbles" loadingText="Loading 
      Feed..."></ion-infinite-scroll-content>
</ion-infinite-scroll>
