### ISSUE TITLE
'nav-decor' hides GoogleMap on multiple tabs 

### ISSUE THREAD

**Issue by infinitysky** [driftyco/ionic#7710] opened 2016-08-14 03:53 UTC
Hi all, this problem still affect on my project.
This strange problem happens on both of Android and iOS.
I am using ionic 2 and cordova google map plugin now

Here is my development environment:
Cordova CLI: 6.3.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.8.6 
ios-sim version: 3.1.1 
OS: Mac OS X El Capitan
Node Version: v4.4.3
Xcode version: Xcode 7.3 Build version 7D175 

I have to enable the scss code for `nav-decor`
```css
ion-app._gmaps_cdv_ .nav-decor{
  background-color: transparent !important;
}
```

I have to say yes it works for me temporarily. However, on my project, I have got multiple tabs then it cause the following problem:
After I boot up the application, It looks OK.
![snip20160814_4](https://cloud.githubusercontent.com/assets/1997572/17646832/29a750da-621e-11e6-9c84-09728724b885.png)

However, once I am going to other tab and back. It shows me this screen.

Other screen:
![snip20160814_5](https://cloud.githubusercontent.com/assets/1997572/17646834/5cb16812-621e-11e6-8cd4-7a516d76ca1d.png)

back to map:
![snip20160814_6](https://cloud.githubusercontent.com/assets/1997572/17646835/6a3defd2-621e-11e6-9023-e7e9608dc938.png)

These two screens have been puts together, and the google map is missing....

Anybody have ideas to help me gets out of this "hole" please? 

there is my code for map:
```typescript

import {Component} from "@angular/core";
import {NavController, Platform} from 'ionic-angular';
import {GoogleMap, GoogleMapsEvent, GoogleMapsLatLng, GoogleMapsMarkerOptions,Geolocation} from 'ionic-native';

@Component({
  templateUrl: 'build/pages/maps/maps.html'
})

export class MapsPage {
  private map: GoogleMap;

  constructor(private _navController: NavController,private platform: Platform) {
    this.platform.ready().then(() => this.onPlatformReady());
  }
  private onPlatformReady(): void {
    GoogleMap.isAvailable().then(() => {
      this.map = new GoogleMap('map_canvas');
      this.map.one(GoogleMapsEvent.MAP_READY).then((data: any) => {
        let myPosition = new GoogleMapsLatLng(38.9072, -77.0369);
        console.log("My position is", myPosition);
      });
      this.map.setBackgroundColor("white");
      this.map.setMyLocationEnabled(true);
    });
  }
}


```

html : 
```html
<ion-header>
  <ion-navbar>
    <ion-title>
      Maps View
    </ion-title>
  </ion-navbar>
</ion-header>

<ion-content>
  <h2>hihi</h2>
    <div id="map_canvas">

    </div>
</ion-content>


```

scss file
```scss

.maps {

}
ion-app._gmaps_cdv_ .nav-decor{
  background-color: transparent !important;
}

```

**Comment by jgw96** [comment] 2016-08-15 15:25
Hello! Thanks for opening an issue with us! I will be closing this issue as a duplicate of https://github.com/driftyco/ionic/issues/7260. Thanks for using Ionic!

**Closed by jgw96** 2016-08-15 15:25 UTC
Labels: v2
