### ISSUE TITLE
Events - "eventData" passed to Events.publish() gets wrapped in an array before being passed to Events.subscribe()'s handler function.

### ISSUE THREAD

**Issue by scunningham777** [driftyco/ionic#6350] opened 2016-04-27 20:58 UTC
#### Short description of the problem:
The `Events` class's [`publish()` method](https://github.com/driftyco/ionic/blob/2.0/ionic/util/events.ts#L90) uses Typescript's ["Rest Parameter"](http://www.typescriptlang.org/docs/handbook/functions.html#rest-parameters) syntax for the `eventData` parameter, so all matching arguments get wrapped in an array.

This means that the `handler` function that is passed to the `Events` class's `subscribe()` method will be passed an array as it's only argument, regardless of how many arguments were passed to `publish()`

This behavior isn't necessarily bad, but it could definitely be unexpected, and the [current documentation](http://ionicframework.com/docs/v2/api/util/Events/) is a bit deceiving. For example, the current sample code shows the following:
```
// first page (publish an event when a user is created)
function createUser(user) {
  console.log('User created!')
  events.publish('user:created', user);
}

// second page (listen for the user created event)
events.subscribe('user:created', (user) => {
  console.log('Welcome', user);
});
```

Presumably, `user` is an object in the first function, but it would in fact be an array containing that object by the time it gets passed to the handler lambda function passed to `events.subscribe()`.

#### What behavior are you expecting?
I know Typescript's "Rest Parameter" always results in an array, but maybe this array could be extracted back into its constituent members before being passed to the handler function. 

Ideally, the handler function should receive things in the same format as they are passed into `events.publish()` - if you publish an event along with two `eventData` arguments, the subscribing function should get two arguments, not an array with two members; if you call `events.publish('eventTopic', [1, 2, 3])`, the subscribing function should probably get an array with three members, not an array containing an array with three members.

Alternatively, the `publish()` method's signature could be adjusted to simply take two parameters, the event name and the data to be published with the event. If more than one object needs to be passed, then the publishing function can choose to use an array, so that both the publisher and subscriber are dealing with the same thing. The "Rest Parameter" actually seems a bit redundant.

**Which Ionic Version?** 2.0.0beta6

#### Plunker that shows an example of your issue

http://plnkr.co/edit/b2lLzjw1P2cigSMzVKbH?p=preview

Click the "Go to Page1" button, then click the "Trigger the Event!" button. Check the browser console for illustration.

**Comment by jgw96** [comment] 2016-04-27 21:05
Hello! Thanks for opening an issue with us! I am going to close this issue as a dupe of https://github.com/driftyco/ionic-site/issues/544 as it has already been discussed there. Feel free to comment on that issue!

**Closed by jgw96** 2016-04-27 21:05 UTC

**Comment by scunningham777** [comment] 2016-04-27 21:48
Dangit! I promise I tried to search for existing issues first!

**Comment by jgw96** [comment] 2016-04-28 16:12
@scunningham777 haha no problem!

**Comment by Anindo94** [comment] 2017-11-24 06:38
method should be inside the constructor or not
