### ISSUE TITLE
issue in auto scroll feature added in RC3

### ISSUE THREAD

**Issue by PrithiviRajG** [driftyco/ionic#9227] opened 2016-11-18 09:32 UTC
#### Short description of the problem:
In RC3 version, screen automatically gets scrolled when we are changing the focus from one field to the another.  it might be nice for longer forms, but I have only two fields (Login and Registration) when I focus to password field, user Id field is scrolled up and only the password field is visible. Before it was working fine. PFB the screen print

#### What behavior are you expecting?
No need to scroll for smaller forms or Ionic can scroll such that the focus text box can be little above the keypad.

**Steps to reproduce:**
can run any form and test it on android device

```
<form [formGroup]="loginForm" (ngSubmit)="signIn()">
                <ion-list class="login-data">
                    <ion-item [class.error]="!userId.valid && userId.touched">
                        <ion-label fixed icon-only>
                            <ion-icon name="person"></ion-icon>
                        </ion-label>
                        <!--<ion-label floating>Username</ion-label>-->
                        <ion-input type="text" placeholder="Username" formControlName="userId" value="ab"></ion-input>
                    </ion-item>

                    <ion-item [class.error]="!password.valid && password.touched">
                        <ion-label fixed icon-only>
                            <ion-icon name="lock"></ion-icon>
                        </ion-label>
                        <!--<ion-label floating>Password</ion-label>-->
                        <ion-input type=password placeholder="Password" formControlName="password"
                                   value="abd12"></ion-input>
                    </ion-item>
                </ion-list>
            </form>
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
https://forum.ionicframework.com/t/ion-input-auto-scrolls-on-focus-in-rc3/70571

[screenshot_2016-11-18-14-47-46](https://cloud.githubusercontent.com/assets/10797126/20425041/c17d6db0-ad9e-11e6-94dd-a1f21f1ca4a2.png)
 

**Which Ionic Version?** 2.0.0-rc.3

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Windows 7 SP1
Node Version: v6.7.0

**Comment by AishApp** [comment] 2016-11-18 09:38
I am facing the same issue in RC3. Is there any way to stop the auto scrolling of ion-input.

**Comment by cleever** [comment] 2016-11-18 11:46
I think ion-input should have an option to disable auto scroll

Something like that:

`<ion-input no-auto-scroll></ion-input>`

**Comment by adamdbradley** [comment] 2016-11-18 22:04
Scrolling under the header should be fixed from what's in master. We'll keep this open and keep testing it, thanks. cc @jgw96

**Comment by jtushar53** [comment] 2016-11-19 08:21
@adamdbradley my form contain username and password field but the password goes way too up below the header , are you referencing the same issue.

steps to reproduce

- click on username -keyboard will show up 
- click on password - pass will go up to the header.

**Comment by jgw96** [comment] 2016-12-01 15:45
Hello @jtushar53 would you mind trying the latest nightly (`npm install ionic-angular@nightly --save`) and seeing if that fixes the issue for you? Thanks!

**Comment by jtushar53** [comment] 2016-12-01 17:11
hi @jgw96 , yes working perfect on chrome desktop dev tools but different behaviour on dev tools and device 
current behaviour on 2.0.0-rc.3-201611302233 on chrome dev tools
1. click on first field (Username) - page scrolls up
2. click on second field (Password) - page doesn't scroll and justifies above keyboard.

current behaviour on 2.0.0-rc.3-201611302233 on device
1. click on first field (Username) - page scrolls up
2. click on second field (Password) - page scroll gently which is also not close from header

**Comment by jgw96** [comment] 2016-12-09 21:19
Hello @jtushar53 ! Unfortunately I cannot reproduce this issue. Could you post a screenshot of the issue you are seeing?

**Comment by jgw96** [comment] 2016-12-15 22:49
Hey @jtushar53 ! Thanks for opening an issue with us! We just released [RC4 today](https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#200-rc4-2016-12-15), would you mind updating and trying that?

**Comment by PrithiviRajG** [comment] 2016-12-26 11:21
hi @jgw96 in RC4 also we are facing the same issue, I updated my App to RC4 and I am able to the same problem, on focus of text fields, they automatically scrolling up and give very poor look and feel.
Please find below the screen print

[screen print 1](https://cloud.githubusercontent.com/assets/10797126/21481206/f843eaea-cb8a-11e6-9326-8aaf8d1bb9be.png)
[screen print 2](https://cloud.githubusercontent.com/assets/10797126/21481215/15f0187a-cb8b-11e6-8a00-db56b2a01e80.png)
[screen print 3](https://cloud.githubusercontent.com/assets/10797126/21481217/1a1e1aaa-cb8b-11e6-89f8-cbc9258b686b.png)

Ionic Info:
```
 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.47
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.7.0
Xcode version: Not installed
```

**Comment by datencia** [comment] 2017-01-13 07:04
Hi!, I'm facing the same issue on RC5.

Ionic Info:
```
 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 8.1
Node Version: v6.9.4
Xcode version: Not installed
```

**Comment by AishApp** [comment] 2017-01-13 10:06
one solution that worked for me is to add  below lines of code in **app.module.ts**. But i am not sure that this is the proper solution as there is no documentation found on this.
```
imports: [
    IonicModule.forRoot(MyApp, {
      scrollAssist: false
    })
  ],
```

**Comment by gadld** [comment] 2017-01-23 04:50
Facing the same issue, scrollAssist: false did help

**Comment by jgw96** [comment] 2017-01-25 19:29
Hello all! So scrollAssist is on by default to help with issues around inputs being hidden and not popping into the view until you start typing. We are constantly working on making this better, in fact 2.0 stable that was released today has a fix related to this. If you prefer the older behavior of inputs behind hidden and then popping into view when you start typing you can set scrollAssist to false as @AishApp mentioned above. Thanks for using Ionic!

**Closed by jgw96** 2017-01-25 19:29 UTC
Labels: needs reply, v2
