### ISSUE TITLE
Keyboard pushes the whole interface up and it's seen on ionCancel (iOS)

### ISSUE THREAD

**Issue by Bouzmine** [driftyco/ionic#7055] opened 2016-06-26 02:03 UTC
#### Short description of the problem:
The whole view is pushed up by the keyboard and it's seen when the keyboard goes down. 

Video : [http://sendvid.com/wrgu72ai](http://sendvid.com/wrgu72ai)

#### What behavior are you expecting?
The view not to lag on keyboard hide.

**Steps to reproduce:**
1. Open an `ion-searchbar`.
2. Cancel it using cancel button.
3. See view getting back in place.

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.6
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v5.0.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment] 2016-06-27 14:52
Hello, thanks for opening an issue with us! I will be closing this issue as a duplicate of https://github.com/driftyco/ionic/issues/5432. Thanks for using Ionic!

**Closed by jgw96** 2016-06-27 14:52 UTC
Labels: keyboard, platform:ios, v2
