### ISSUE TITLE
Ionic 2 Menu doesn't always work

### ISSUE THREAD

**Issue by ncapito** [driftyco/ionic#9292] opened 2016-11-22 21:13 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Having some consistency issues when clicking the "hamburger menu."  As you can see here

![Example](https://media.giphy.com/media/3o7TKp8qTt9VrwgasM/giphy.gif)

So what happens is you will click the menu and sometimes it will work sometimes it doesn't.  In my app first click always gets swallowed.  After that it looks like it randomly registers the click to open the menu.

**Expected behavior:**
Every time I click the "hamburger" the menu opens.

**Steps to reproduce:**
1.   gulp e2e.serve
2.  navigate to http://localhost:8000/dist/e2e/menu/basic/ 
3.  click the hamburger
4. click navbar 2 times
5. click hamburger

It's not 100% consistent but you will be able to replicate it. 

**Other information:**
Console from when you click and it doesn't open: 

```
menu gesture, onSlideBeforeStart left
ionic.system.js:12690 keyboard close()
ionic.system.js:23510 menu gesture, onSlideEnd left distance 0 delta 0 velocity 0 min 0 max 304 shouldCompleteLeft false shouldCompleteRight false currentStepValue 0
ionic.system.js:2045 Animation, progressEnd, shouldComplete false currentStepValue 0
ionic.system.js:24166 menu, swipeEnd left
app-module.js:97 Menu is closed true
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.3.1
Gulp version:  CLI version 1.2.2
Gulp local:
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X Sierra
Node Version: v6.2.1
Xcode version: Xcode 8.1 Build version 8B62

```

**Comment by ncapito** [comment] 2016-11-22 21:46
My guess is somehow gestures are stealing the click.  I'm looking into it now.

**Comment by jgw96** [comment] 2016-11-23 17:45
Hello, thanks for using Ionic! Would you mind trying with the latest nightly? I am not able to repro this issue on that nightly. To install the Ionic 2 nightly you can run `npm install ionic-angular@nightly --save`.

**Comment by wumpusWelt** [comment] 2016-11-28 11:58
Hello, I have the same problem only by iOS version. (and I use swipeBackEnabled="false")

**Comment by ncapito** [comment] 2016-11-28 15:23
@jgw96  Just tested and I'm having the same issue.  I'm assuming "nightly" is the same as pulling down the latest master branch.

**Comment by brandyscarney** [comment] 2017-01-24 21:40
@ncapito I'm not abel to reproduce this using latest. Are you still seeing this issue?

**Comment by jgw96** [comment] 2017-01-30 20:45
Hello all! As it seems it has been a while since there was any activity on this issue and we are not able to reproduce this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-01-30 20:45 UTC
Labels: needs reply, v2
