### ISSUE TITLE
Slidemenu Broken during Orientation

### ISSUE THREAD

**Issue by kumaresan-cgvak** [driftyco/ionic#11083] opened 2017-04-06 08:48 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
if an user change to Landscape from Portrait keeping the Slidemenu open breaks the interface (Slidemenu). This happens in vice versa as well.

**Expected behavior:**

Right Menu should be open and with a proper UI.

**Related code:**

```
<ion-menu [content]="content" side="right">
  <ion-header>
    <ion-toolbar>
      <ion-title>Menu</ion-title>
    </ion-toolbar>
  </ion-header>

  <ion-content>
    <!--Staff Name-->
    <ion-item>
        <ion-icon name="contact" item-left></ion-icon>
        <p>Kumaresan</p>
      </ion-item>
    <ion-list>
      <ion-item menuClose>
       Home
        <ion-icon name="home" item-right ></ion-icon>
      </ion-item>
 <ion-item menuClose>
       About
        <ion-icon name="home" item-right ></ion-icon>
      </ion-item>
 <ion-item menuClose>
       Contact US
        <ion-icon name="home" item-right ></ion-icon>
      </ion-item>
    </ion-list>
    <!--Application Version number and Build Number-->
    <p text-center>1.1</p>
  </ion-content>

</ion-menu>

<!-- Disable swipe-to-go-back because it's poor UX to combine STGB with side menus -->
<ion-nav [root]="rootPage" #content swipeBackEnabled="false"></ion-nav>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.12 
OS: macOS Sierra
Node Version: v7.2.0
Xcode version: Xcode 8.3 Build version 8E162
```

**Comment by kumaresan-cgvak** [comment] 2017-04-07 07:10
Issue exist in Ionic Framework Version: 3.0.1 as well.

````
Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.12 
OS: macOS Sierra
Node Version: v7.2.0
Xcode version: Xcode 8.3 Build version 8E162
````

**Comment by jgw96** [comment] 2017-04-08 10:50
Hello, thanks for using Ionic! I am going to close this as a duplicate of https://github.com/driftyco/ionic/issues/9885

**Closed by jgw96** 2017-04-08 10:50 UTC
