### ISSUE TITLE
bug: Overlap of refresher on iPad

### ISSUE THREAD

**Issue by aeharding** [driftyco/ionic#28438] opened 2023-10-31 13:33 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

The pull-to-refresh doesn't render properly on iPad:

It looks like the page that's being pulled down is overlapping the spinner. For some reason this only happens on iPads.

https://github.com/ionic-team/ionic-framework/assets/2166114/ac34f475-28a9-4f10-aafe-e65c01cab9b5

### Expected Behavior

Should render like iPhone

### Steps to Reproduce

1. Open https://docs-demo.ionic.io/component/refresher on iPad
2. Pull to refresh, observe shown behavior
3. Also observe it works fine on iPhone

### Ionic Info

Just running against https://docs-demo.ionic.io/component/refresher

But I'm also experiencing this issue in an up-to-date Ionic project

### Additional Information

Running iPad 17.1

**Comment by liamdebeasi** [comment] 2023-10-31 15:13
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/18714.

**Closed as not planned by liamdebeasi** 2023-10-31 15:13 UTC
Labels: triage
