### ISSUE TITLE
bug: Scroll callbacks not fired during inertial scrolling iOS8

### ISSUE THREAD

**Issue by mrtomrichy** [driftyco/ionic#4242] opened 2015-08-17 15:21 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>During inertial scrolling on iOS8 no scroll callbacks are fired. This may be contributing to a larger issue where, during inertial scrolling, touch positions are not updated.

Initially reported https://github.com/driftyco/ionic/issues/4008 after implementing iOS8 scroll fix.

Video highlighting the issue: https://vimeo.com/136085384
Sample project: https://github.com/mrtomrichy/Ionic-iOS8-Scroll-Issue</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-08-17 15:21
Greetings @mrtomrichy!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4242). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4242)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by cnnrmtthws** [comment] 2015-09-01 17:04
I am also having an issue with this. Any update or workaround?

**Comment by mrtomrichy** [comment] 2015-09-06 18:49
@cnnrmtthws After more investigation I think it could be an iOS8 bug with` -webkit-overflow-scrolling: touch;` and I haven't managed to find a workaround.

Did you get a chance to look into this @mhartington?

Thanks

**Comment by cnnrmtthws** [comment] 2015-09-06 19:17
Thanks @mrtomrichy 
The app is usable despite this issue but it does result in some really confusing behaviour for users, i.e. click on an item in a moving list and a different item is actually selected.

**Comment by mhartington** [comment] 2015-09-06 21:47
I took a look at the project, there was some stuff in there that could have been effecting it, so I used a blank project and built a similar example to yours @mrtomrichy 

I was unable to reproduce the issue.
If you have any more info, I could take a look, but on a real device (ios and android), I'm not seeing it.

**Comment by mrtomrichy** [comment] 2015-09-06 22:27
@mhartington Do you know what could have been affecting it?

**Comment by mhartington** [comment] 2015-09-06 22:30
It may have something to do with that scrollfix in your code.
Or the upgrade to angular 1.4. 
Would you mind trying the latest ionic code?

**Comment by mrtomrichy** [comment] 2015-09-07 08:35
@mhartington I am using Ionic 1.1.0 and I have removed the scroll fix. The good news is that I can scroll (that was the reason the scroll fix was implemented) however the issue where touch areas do not update still persists.

I believe the scroll fix was merged into master last week? 
https://github.com/jarjee/ionic/commit/44b2583ae7dafa2dbcb476ed6b398f9828d51590

**Comment by mhartington** [comment] 2015-09-07 23:21
Hmm, I'm still not able to replicate it on my end. Could you give the list codepen a try and see if that works?

**Comment by mrtomrichy** [comment] 2015-09-08 10:05
@mhartington I tried the list codepen and that did not suffer from this issue. When I tapped during scrolling it stopped the scrolling and did not fire a click event unlike what I am seeing in my example application.

I have managed to recreate the issue on multiple iOS devices running iOS8.

**Comment by persyval** [comment] 2016-03-01 02:12
Has there been any progress in this issue?
I'm having the eaxct same behaviour.
When the list is scrolling the tap does not stop the list but goes to the item the user started the scroll on, which is really confusing because that's not the item the user is currently clicking on.

**Comment by jgw96** [comment] 2016-03-23 19:19
Hello! Are you still experiencing this issue?

**Comment by persyval** [comment] 2016-03-24 02:31
Yes I am, but i narrowed it down to the exact situation.
I entered this bug:
https://github.com/driftyco/ionic/issues/5726

**Comment by jgw96** [comment] 2016-03-24 06:22
Thanks for getting back to me! As you opened a new issue for the latest version of ionic i will be closing this one. Thanks again!

**Closed by jgw96** 2016-03-24 06:22 UTC
Labels: needs reply, scroll, v1
