### ISSUE TITLE
Ionic 2 beta 11 navigation not working

### ISSUE THREAD

**Issue by ferminmoli** [driftyco/ionic#7625] opened 2016-08-09 14:40 UTC
#### Short description of the problem:

NavController is not working properly

#### What behavior are you expecting?
NavController redirects to a blank page after doing this.nav.popToRoot() or this.nav.setRoot()

**Steps to reproduce:**
1. Set some page as a root one
2. Navigate between diferent pages
3. On some action call this.nav.popToRoot() or this.nav.setRoot()

```
import {NavController} from 'ionic-angular';

@Component({
  templateUrl: 'some-component.html',
})
export class SomeComponent {
 constructor(private nav: NavController) {
  }

 someAction(){
    this.nav.setRoot(LoginComponent);
  }
 otherSomeAction(){
   this.nav.popToRoot();
  }
}
```

**Which Ionic Version?**  2.0.0-beta.11

**Comment by jgw96** [comment] 2016-08-09 15:07
Hello! Thanks for opening an issue with us! Would you mind taking a look at [this](https://github.com/jgw96/popToRoot) repo i made and giving it a try? Just click on the push new page button and it will cycle through pushing two pages and then popping to root. Unfortunately, I cannot seem to reproduce with this example. Also, our current sidemenu starter uses `setRoot` and i can not currently reproduce the issue their either. If you wouldnt mind, could you make a repo with a minimal example i can use to reproduce this issue? Thanks for using Ionic!

**Comment by jgw96** [comment] 2016-08-09 17:16
Hello after further review I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/7564. Thanks!

**Closed by jgw96** 2016-08-09 17:16 UTC
Labels: navigation, v2

**Comment by ferminmoli** [comment] 2016-08-09 20:50
Hi, we could reproduce the issue. It appers when you add LoadingController and an Ajax call.

You can download the code from here: [https://github.com/ferminmoli/Ionic-popToRoot](url)

**Comment by nachofregeiro** [comment] 2016-08-10 15:49
It looks like the LoadingController is overriding the app nav, and it's loosing the navigation stack.
