### ISSUE TITLE
feat: Back when menu open not close the menu

### ISSUE THREAD

**Issue by MatanYed** [driftyco/ionic#7941] opened 2016-09-01 13:33 UTC
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When i am on root page and menu open, I click hardware back button and app closed.
Its should close the menu and not the app.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment] 2016-09-01 14:39
Hello, thanks for opening an issue with us! I am going to be closing this issue as a duplicate of https://github.com/driftyco/ionic/issues/7611. Thanks for using Ionic!

**Closed by jgw96** 2016-09-01 14:39 UTC
Labels: feature, menus, v2
