### ISSUE TITLE
bug: bug: collection-repeat card width overflow when used with item-height

### ISSUE THREAD

**Issue by vlad-bezden** [driftyco/ionic#3357] opened 2015-03-19 21:10 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>When I use collection-repeat and my item is card and I specify item-height right side of the card will go beyond the content size. Without item-height it works properly. In my case I have to specify item-height and it creates issue.

```` HTML
  <ion-content>
    <ion-list>
      <div class="card list" collection-repeat="item in main.items" item-height="50">
        <h1 style="background-color: red">{{item}}</h1>
      </div>
    </ion-list>
  </ion-content>
````
I created example so you can take a look at it
http://codepen.io/vlad-bezden/pen/LEMxXX

Thank you.</span>

<span is-issue-template></span>
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-03-19 21:10
Greetings @vlad-bezden!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3357). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3357)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mattchue** [comment] 2015-03-20 22:14
#3352

**Comment by Alkashi** [comment] 2015-03-22 10:31
Are you sure the car class is important ?
I have the same bug without the card class and on iOS 8 :/

**Comment by vlad-bezden** [comment] 2015-03-22 11:12
I found to me it only happened when I used card. Items work fine for me. However I can't comment about IOS, since I using and testing it in Chrome and Android.

**Comment by mattchue** [comment] 2015-03-23 16:07
I can confirm that this does indeed happen when running on the iPad, so it seems to be a universal issue.

**Comment by perrygovier** [comment] 2015-03-24 20:02
I believe @mattchue is correct in saying this is related to his issue, but I can't correct it with a `$ionicScrollDelegate.resize();`.

**Comment by ajoslin** [comment] 2015-04-06 23:46
Those damn margins.

**Closed** 2015-04-07 00:23 UTC
Labels: list
