### ISSUE TITLE
bug: Swiping in menu closes the menu

### ISSUE THREAD

**Issue by lordgreg** [driftyco/ionic#5511] opened 2016-02-18 20:37 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Steps to reproduce:
1. Create simple app with menu (on the left)
2. Open menu
3. ON MENU swipe from left to right. It will close the menu.
4. ON MENU swipe diagonally from left to right. It will close the menu.
5. Fin.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment] 2016-02-21 07:08
Did some research on this issue, it seems to be caused by the SlideEdgeGesture not actually detecting the direction of the slide, therefore closing the menu even if the slide gesture is not going in the "close" direction.

**Comment by manucorporat** [comment] 2016-06-09 10:12
@lordgreg I am working right now in a PR to fix this, and it will include several additional improvements as well.

**Closed** 2016-06-09 12:57 UTC
Labels: menus, v2
