### ISSUE TITLE
Ion-tabs are only highlighted/active once on click. 

### ISSUE THREAD

**Issue by RickePicke** [driftyco/ionic#11021] opened 2017-04-02 21:28 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[] feature request
[x] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Im My root page is a log in page where you can either chose to log in whit email/password or facebock via firebase. 

When you are authenticated, the TabsPage is pushed like this:
```
 firebase.auth().onAuthStateChanged((user)=>{
      if(user) {
        this.navCtrl.push(TabsPage);
      }
    });
```
tabs.html
```
<ion-tabs #mainTabs>
  <ion-tab [root]="tab1Root" tabTitle="title1" tabIcon="any-logo" ></ion-tab>
  <ion-tab [root]="tab2Root" tabTitle="title2" tabIcon="any-logo"></ion-tab>
  <ion-tab [root]="tab3Root" tabTitle="title3" tabIcon="any-logo"></ion-tab>
</ion-tabs>
```
tabs.ts
```
import { Component, ViewChild } from '@angular/core';
import { Tabs } from "ionic-angular"
import { FirstPage } from '../first/first';
import { SecondPage } from '../second/second';
import { ThirdPage } from '../third/third';

@Component({
  templateUrl: 'tabs.html'
})
export class TabsPage {
  tab1Root: any = FirstPage;
  tab2Root: any = SecondPage;
  tab3Root: any = ThirdPage;
  @ViewChild('mainTabs') mainTabs: Tabs;
  constructor() {}
  ionViewDidEnter() {
    //..
  }
}
```

.. and everything seems OK. The navigation is perfect, but... The tabs can only be highligted/active/selected the first time they are selected. The second time you click on the tab, navigating from another tab, the tab that is clicked stays unselected. 

**Other information:**
When i check the DOM-elements while navigating i around i can see that "aria-selected"-property of the <a class"tab-button">-element is unchanged. But when i manually change the value, true or false, the tab b selected becomes selected accordingly.

The problem disappears if any other page is loaded before the tabPage:
```
this.navCtrl.push(OtherPage); // loading other page here
this.navCtrl.push(TabsPage);
```
I did accutually mange to work around this problem by loading the TabsPage in the constructor of the OtherPage. But thats so ugly.

Am I doing anything wrong or is this a built in bug?

**Comment by jgw96** [comment] 2017-04-03 18:52
Hello, thanks for opening an issue with us. Would you mind sharing a repo we can use to reproduce this issue?

**Comment by jgw96** [comment] 2017-04-07 06:50
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-04-07 06:50 UTC
Labels: needs info, v2

**Comment by tech-eng** [comment] 2018-04-10 20:54
Hi
I have sam problem
