### ISSUE TITLE
bug: Bug Ionic 1.1.0 Cannot call method 'contains' of undefined

### ISSUE THREAD

**Issue by jleyva** [driftyco/ionic#4618] opened 2015-11-10 09:17 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>This is a followup of #3295
The error happens in other ares of the code:

This error happens sometimes in our app using Ionic 1.0.1. It happens at the line 23 of the minified version. I looked at it and I found 2 possible candidates:

1- Line 3179 of ionic.bundle.js version 1.1.0
```javascript
if (ele.classList.contains('button')) {  
```
2- Line 5046 of ionic.bundle.js version 1.1.0
```javascript
var isModal = container.parentNode.classList.contains('modal');
```
3 - Line 7189 in ionic.bundle.js version 1.1.0:
```javascript
var isModal = container.parentNode.classList.contains('modal');
```
Hope this helps!</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-11-10 09:17
Greetings @jleyva!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4618). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4618)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by PerfectionCSGO** [comment] 2015-12-17 10:05
You can fix it by changing  

          if (ele.classList.contains('button')) {
            eleToActivate = ele;
            break;
          }

to 

          if (ele.classList && ele.classList.contains('button')) {
            eleToActivate = ele;
            break;
          }

I had this issue using the highchart plugin on windows phone. I believe this is a thing on older versions of windows phone but I can't say because I know nothing.
This is line 3230 in ionic.bundle 1.2.0.

Correct me if there is a better way of fixing this.

**Comment by nrcrabbe** [comment] 2016-01-07 08:43
I can confirm I experience the same issue on L3179 of 1.1.0.

Platforms affected are Android 4.2.2 and 4.3.

**Comment by maksad** [comment] 2016-02-10 10:44
+1 
The issue appears on IE10/IE11

**Comment by jgw96** [comment] 2016-03-14 21:32
Hello! Thanks for opening an issue with us! Are you guys still experiencing this issue with the latest version of ionic?

**Comment by maksad** [comment] 2016-03-21 12:08
Hi @jgw96 
Good to point that out. I am using `1.2.0v`. Will inform as it is upgraded to the latest version

**Comment by jgw96** [comment] 2016-03-21 14:03
@maksad aweseom, cant wait to hear the results

**Comment by jgw96** [comment] 2016-04-01 19:20
As it has been a little while since there was any activity on this issue I will be closing it for now, please feel free to reply if you are still experiencing this issue though!

**Closed by jgw96** 2016-04-01 19:20 UTC
Labels: v1
