### ISSUE TITLE
Toast issue

### ISSUE THREAD

**Issue by BugsBunnyBR** [driftyco/ionic#7578] opened 2016-08-07 02:16 UTC
I am using v2 beta11 and if you show a toast in a child page and press the back button, when the toast dismiss the following error happens.
<img width="754" alt="captura de tela 2016-08-06 as 23 12 46" src="https://cloud.githubusercontent.com/assets/70573/17460055/6af4db82-5c2b-11e6-9878-f1c733aefb6d.png">

**Comment by BugsBunnyBR** [comment] 2016-08-07 02:32
Using `dismissOnPageChange: true` in the creation of the Toast avoids the issue.

**Comment by alexbainbridge** [comment] 2016-08-07 15:39
Similar issue on beta 11

`let toast = this.toast.create({
                            message: 'Saved successfully',
                            dismissOnPageChange : true,
                            duration: 1500
                        });`

With duration set, if you go back button BEFORE the duration is elapsed, then you do move to the previous page (back) but you are now stuck in a loop with the toast showing / hiding constantly, without user interaction (and UI is locked up)

If you go back button AFTER duration is up, then all is OK

**Comment by alexbainbridge** [comment] 2016-08-07 16:33
Likewise, on same code as above, if you present a modal while a duration set toast is showing, then you end up with the same UI lockup issue

**Comment by jgw96** [comment] 2016-08-08 05:04
Hello, thanks for opening an issue with us! I am going to be closing this issue as a duplicate of https://github.com/driftyco/ionic/issues/7565. Thanks for using Ionic!

**Closed by jgw96** 2016-08-08 05:04 UTC
Labels: v2

**Comment by alexbainbridge** [comment] 2016-08-08 07:52
OK @jgw96 ! (But if so, could you add more tags to the other issue, so its more than actionsheet)
