### ISSUE TITLE
Searchbar doesn't fire blur event. Reopen #7158

### ISSUE THREAD

**Issue by alexdruk** [driftyco/ionic#9166] opened 2016-11-15 09:44 UTC
Keyboard does not hide when searchbar is out of focus. Exactly like described in ussue 7158.
Testing on iPhone 4s. 
System info:
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.43
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: OS X El Capitan
Node Version: v6.7.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by biesbjerg** [comment] 2016-11-15 13:48
Duplicate of https://github.com/driftyco/ionic/issues/8933

**Comment by brandyscarney** [comment] 2016-11-18 19:35
Thanks for the issue, going to close as a duplicate of #8933. Thanks @biesbjerg!

**Closed by brandyscarney** 2016-11-18 19:35 UTC
