### ISSUE TITLE
Syntax errors in HTML files silently cause page to fail to load

### ISSUE THREAD

**Issue by Gaelan** [driftyco/ionic#6259] opened 2016-04-21 05:59 UTC
#### Short description of the problem:
If the HTML file for a page has a syntax error (a simple one to test is a mismatched closing tag), the page silently fails to appear.

#### What behavior are you expecting?
A syntax error in the console giving me a hint as to what is wrong.

**Steps to reproduce:**
1. `ionic start Foo --v2`
2. Replace `app/pages/page2.html` with the code below (mismatched `<h1></p>`)
3. `ionic serve`
4. Try to select Tab 2.
5. Notice that no error message appears, and that the content does not appear.

```
<ion-navbar *navbar>
  <ion-title>
    Tab 2
  </ion-title>
</ion-navbar>

<ion-content class="page2">
  <h1></p>
</ion-content>
```

**Other information:** Plunker handles this properly–syntax errors in templates appear in the console. 
 

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:**
```
Your system information:

Cordova CLI: Not installed
Ionic Framework Version: 2.0.0-beta.4
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v5.1.1
Xcode version: Not installed


******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`
 Install ios-sim to deploy iOS applications. `npm install -g ios-sim` (may require sudo)
 Install ios-deploy to deploy iOS applications to devices. `npm install -g ios-deploy` (may require sudo)

******************************************************
```

**Comment by wli** [comment] 2016-04-21 18:12
I've encountered this too (and filed https://github.com/driftyco/ionic/issues/6253) - looks like the same root cause. I couldn't repro in plunkr so I thought it was just some quirk of my environment, but it looks like it affects others too.

**Comment by jgw96** [comment] 2016-05-06 19:16
Hello! Would you mind upgrading to beta.6? This issue was fixed in that release! Also, as this issue was fixed in beta.6 i am going to close this issue for now. Thanks!

**Closed by jgw96** 2016-05-06 19:16 UTC
Labels: platform:ios, v2
