### ISSUE TITLE
Watch task only watches the www/ directory for RC.0

### ISSUE THREAD

**Issue by b12f** [driftyco/ionic#8289] opened 2016-09-29 10:40 UTC
#### Short description of the problem:
Whenever I run `ionic run android -l` the watch task will only watch the `www/` folder:

    Watching: www/**/*, !www/lib/**/*, !www/**/*.map

Which is pretty much useless, since almost all development is going on in the `src/` directory.

#### What behavior are you expecting?
I'd like to be able to watch at least the `src/` directory, best would be to be able to set the watch settings by hand.

**Steps to reproduce:**
1. Generate a new ionic app and start the livereload dev build
```
ionic start --v2 myApp
cd myApp
ionic run android -l
```
2. Modify a file within the `src/` directory
3. The watcher does not pick this up, neither the css nor the html or js is getting updated when files change.

**Other information:**
Custom config files are allowed for most but not all tasks (see [ionic-app-scripts](https://github.com/driftyco/ionic-app-scripts) ), so I suggest either allowing a custom config file for the watch task or having sane defaults. (e.g. watching `src/`)

**Which Ionic Version?** 1.x or 2.x
2.0 RC 0

**Run `ionic info` from terminal/cmd prompt:**

```
Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 1.0.0
Gulp local:  
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.5 LTS 
Node Version: v4.5.0
```

**Comment by jgw96** [comment] 2016-09-29 18:51
Hello! Thanks for opening an issue with us! Unfortunately I am not able to reproduce this issue. When running `ionic serve` everything is working fine on my end. Would you be able to post a repo that i can use to reproduce this issue? Thanks!

**Comment by Manduro** [comment] 2016-09-29 20:11
The Ionic CLI is correct to watch only the `www` folder. The Ionic App Scripts are watching your `src` folder and build any changes to the `www` folder which is then picked up by the Ionic CLI livereload.

**Comment by b12f** [comment] 2016-09-30 08:16
The repository would be https://github.com/driftyco/ionic2-starter-tabs

#8314 appears to be part of the same problem, and after running `npm run watch` in a separate terminal as recommended in that thread, all seems to work fine except for livereloading. This happens both with `ionic serve` and `ionic run android -l`.

**Comment by brettatoms** [comment] 2016-10-03 09:52
This happens to me for files named `index.html` because of this line:       https://github.com/driftyco/ionic-app-scripts/blob/579d54dd1905f8e6749ae2baa7bd4491896e1524/config/watch.config.js#L24

**Comment by jgw96** [comment] 2016-10-07 13:42
Hello all! Thanks for the info. I am going to close this issue as a duplicate of https://github.com/driftyco/ionic-app-scripts/issues/93. Thanks!

**Closed by jgw96** 2016-10-07 13:42 UTC
Labels: needs reply, v2
