### ISSUE TITLE
Performance degrade on Windows 10 (app or MS Edge)

### ISSUE THREAD

**Issue by nghiacc** [driftyco/ionic#11047] opened 2017-04-04 13:13 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When building an app for Windows 10, noticeable performance degrade was observed. When running the app built for Windows 10, or using MS Edge browser, the performance when clicking on items, radiobutton much slower than using Chrome or Opera (in my example, I was using Opera). It takes more than one second delay for the click event to be registered to the component

**Expected behavior:**

There is no delay between click, the performance should be comparable to iOS / Android build or on Chrome browser

**Steps to reproduce:**

**Related code:**
the code is cloned from 
https://github.com/driftyco/ionic-conference-app

**Other information:**

Here the link to the similar thread on ionic forum:
https://forum.ionicframework.com/t/ionic2-very-slow-on-windows-phone-10/76051/22

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Cordova CLI: 6.3.1 
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v6.5.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment] 2017-04-04 15:01
Hello, thanks for opening an issue with us! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/10009.

**Closed by jgw96** 2017-04-04 15:01 UTC

**Comment by nghiacc** [comment] 2017-04-05 02:55
Thought this was different with #10009 because it was reported on Windows 10 Phone. Anyway I have posted a comment there to make sure it covers Windows 10 desktop as well.
Kind regards,
