### ISSUE TITLE
div footer   not in bottom of UC

### ISSUE THREAD

**Issue by ivantree** [driftyco/ionic#3171] opened 2015-02-24 16:28 UTC
android UC Ver：20150210 
ionic Ver：Ionic, v1.0.0-beta.14
web app 
![20150225002308](https://cloud.githubusercontent.com/assets/9014680/6353510/c4050bb8-bc84-11e4-90ac-84e6232e65b2.jpg)

**Comment by Ionitron** [comment] 2015-02-24 16:28
Greetings @ivantree!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3171). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3171)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment] 2015-02-24 21:16
This is not a bug, but a design choice for android. Tabs should appear on top as part of the platform specific tweaks.

This can be changed via the `$ionicConfigProvider`

http://ionicframework.com/docs/api/provider/$ionicConfigProvider/

**Closed by mhartington** 2015-02-24 21:16 UTC

**Comment by ivantree** [comment] 2015-02-25 09:02
Ths!
