### ISSUE TITLE
Trigger events when Menu toggles

### ISSUE THREAD

**Issue by jgog** [driftyco/ionic#5603] opened 2016-02-25 10:02 UTC
#### Short description of the problem:
Currently the Menu can be operated by either of the directives `menuToggle` and `menuClose` which work well. Although, it can also be closed when the users taps on the content area or the backdrop in case of a overlay Menu.
Can we have events triggers like `sidemenu-toggled` so then we can listen for it and do relevant actions?

**Ionic Version**: 2.x

**Comment by brandyscarney** [comment] 2016-02-26 22:23
Hey, thanks for the issue! This is a duplicate of: https://github.com/driftyco/ionic/issues/5163 so I'm going to close this one. :smile:

**Closed by brandyscarney** 2016-02-26 22:23 UTC
Labels: menus, v2

**Comment by jgog** [comment] 2016-02-27 07:26
Sorry, didn't find that issue.
