### ISSUE TITLE
Collection-repeat rendering problem

### ISSUE THREAD

**Issue by hansi96** [driftyco/ionic#6403] opened 2016-05-02 16:25 UTC
Hello,
i will make a plunkr later.
My problem is, that i have a directive, wrapped in a collection-repeat. This works well.
After i get my data, i save it into the localStorage and i want to load it at the next start.
This works, but only with ng-repeat. With collection-repeat, there is a render problem. All my list items are on top of the page. They haven't the css styles width, height and transform. I guess this is the problem.

Thanks!

**Comment by jgw96** [comment] 2016-05-04 15:52
Hello! Thanks for opening an issue with us! Would love to see that Plunker when you get a chance so that we can reproduce this!

**Comment by jgw96** [comment] 2016-06-06 19:50
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-06-06 19:50 UTC
Labels: collection-repeat, v1

**Comment by playtogga** [comment] 2016-06-14 18:49
I'm having an issue similar to this, where I'm using $compile to append a collection-repeat element to a slidebox.

**Comment by jdnichollsc** [comment] 2016-07-13 15:53
+1

**Comment by jdnichollsc** [comment] 2016-07-13 15:55
@jgw96 Please, reopen this issue! We need to solve the issue when the collection-repeat is added dinamically (The scroll doesn't work on Mobile - Android)
