### ISSUE TITLE
bug: Fab button ripple is square and out of the button

### ISSUE THREAD

**Issue by mikkokam** [driftyco/ionic#5148] opened 2016-01-22 16:02 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>browser</span>

<span ionic-description>Fab button ripple is a square (seen outside of the round button) on Android.

Can be seen on the demo page as well - http://ionicframework.com/docs/v2/components/#icon-buttons 
 - test fab buttons using Android style; the upper ones get this square ripple.

The one below is OK - seems it has inline style promoting the z-index of it, and the ripple is functioning as it should. (Although barely seen, as it is a dark button, but tested this with other colors, too.)

Seems this will fix things:

    .button-fab{
        z-index: 999;
    }

<span is-issue-template></span>

**Comment by brandyscarney** [comment] 2016-01-22 16:15
This is a duplicate of https://github.com/driftyco/ionic/issues/5074 but I'm actually going to implement your fix so I'll keep this open. Thanks for finding a fix!

**Comment by brandyscarney** [comment] 2016-01-22 16:40
Added `z-index: 0` to all buttons (since the user can change the border-radius of any button) and confirmed this fixes it. I didn't see any issues with it in my tests, but let me know if you notice any problems.

There should be a release today with this fix in.

**Closed by brandyscarney** 2016-01-22 16:40 UTC
Labels: v2
