### ISSUE TITLE
Error: undefined is not an object (evaluating 'viewHistory.currentView.index')

### ISSUE THREAD

**Issue by kntmrkm** [driftyco/ionic#5481] opened 2016-02-17 10:18 UTC
Hi, I'm using ionic below version.

```
Your system information:

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic CLI Version: 1.7.13
Ionic App Lib Version: 0.6.5
ios-deploy version: 1.8.4
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v5.3.0
Xcode version: Xcode 7.2.1 Build version 7C1002
```

Subject's error sometime's happen, In other words, I don't know how to reproduce.
Operate app randomry. then the error appears.

This error occuers in real device. (I can't see log. yes. but same action with error (cloud not state change.)).

```
48    094045   error    Error: undefined is not an object (evaluating 'viewHistory.currentView.index')
register@http://localhost:8100/lib/ionic/js/ionic.bundle.js:51373:44
register@http://localhost:8100/lib/ionic/js/ionic.bundle.js:56692:46
updateView@http://localhost:8100/lib/ionic/js/ionic.bundle.js:62357:31
http://localhost:8100/lib/ionic/js/ionic.bundle.js:62334:21
$broadcast@http://localhost:8100/lib/ionic/js/ionic.bundle.js:29477:33
http://localhost:8100/lib/ionic/js/ionic.bundle.js:49321:32
processQueue@http://localhost:8100/lib/ionic/js/ionic.bundle.js:27879:30
http://localhost:8100/lib/ionic/js/ionic.bundle.js:27895:39
$eval@http://localhost:8100/lib/ionic/js/ionic.bundle.js:29158:28
$digest@http://localhost:8100/lib/ionic/js/ionic.bundle.js:28969:36
$apply@http://localhost:8100/lib/ionic/js/ionic.bundle.js:29263:31
http://localhost:8100/lib/ionic/js/ionic.bundle.js:25398:30
eventHandler@http://localhost:8100/lib/ionic/js/ionic.bundle.js:16583:25
dispatchEvent@[native code]
triggerMouseEvent@http://localhost:8100/lib/ionic/js/ionic.bundle.js:2948:20
tapClick@http://localhost:8100/lib/ionic/js/ionic.bundle.js:2937:20
tapTouchEnd@http://localhost:8100/lib/ionic/js/ionic.bundle.js:3064:13
```

after above error. can not proceed operation.
Then, another error occuer.

```
197   426038   error    Error: undefined is not an object (evaluating 'hist.stack[hist.cursor].stateId')
register@http://localhost:8100/lib/ionic/js/ionic.bundle.js:51218:40
register@http://localhost:8100/lib/ionic/js/ionic.bundle.js:56692:46
updateView@http://localhost:8100/lib/ionic/js/ionic.bundle.js:62357:31
http://localhost:8100/lib/ionic/js/ionic.bundle.js:62334:21
$broadcast@http://localhost:8100/lib/ionic/js/ionic.bundle.js:29477:33
http://localhost:8100/lib/ionic/js/ionic.bundle.js:49321:32
processQueue@http://localhost:8100/lib/ionic/js/ionic.bundle.js:27879:30
http://localhost:8100/lib/ionic/js/ionic.bundle.js:27895:39
$eval@http://localhost:8100/lib/ionic/js/ionic.bundle.js:29158:28
$digest@http://localhost:8100/lib/ionic/js/ionic.bundle.js:28969:36
$apply@http://localhost:8100/lib/ionic/js/ionic.bundle.js:29263:31
http://localhost:8100/lib/ionic/js/ionic.bundle.js:25398:30
eventHandler@http://localhost:8100/lib/ionic/js/ionic.bundle.js:16583:25
dispatchEvent@[native code]
triggerMouseEvent@http://localhost:8100/lib/ionic/js/ionic.bundle.js:2948:20
tapClick@http://localhost:8100/lib/ionic/js/ionic.bundle.js:2937:20
tapTouchEnd@http://localhost:8100/lib/ionic/js/ionic.bundle.js:3064:13
```

My routing code is ...

```
.config(function($stateProvider, $urlRouterProvider) {
  $urlRouterProvider.otherwise('/app/home');

  $stateProvider

  .state('app', {
    url: '/app',
    abstract: true,
    templateUrl: 'templates/menu.html',
    controller: 'AppCtrl as app'

  })
  .state('app.home', {
    cache: false,
    url: '/home',
    parent: 'app',
    isLoginRequired: false,
    views: {
      'menuContent': {
        templateUrl: 'templates/home.html'
      }
    }
  })
  .state('app.webview', {
    cache: false,
    url: '/webview',
    parent: 'app',
    isLoginRequired: true,
    views: {
      'menuContent': {
        templateUrl: 'templates/webview.html'
      }
    }
  })
  .state('app.iframe', {
    cache: false,
    url: '/iframe',
    parent: 'app',
    isLoginRequired: true,
    views: {
      'menuContent': {
        templateUrl: 'templates/iframe.html'
      }
    }
  })
  .state('app.intro', {
    cache: true,
    url: '/intro',
    parent: 'app',
    isLoginRequired: false,
    views: {
      'menuContent': {
        templateUrl: 'templates/intro.html'
      }
    }
  })
  .state('app.help', {
    cache: true,
    url: '/help',
    parent: 'app',
    isLoginRequired: false,
    views: {
      'menuContent': {
        templateUrl: 'templates/help.html'
      }
    }
  })
  .state('app.styleguide', {
    url: '/styleguide',
    parent: 'app',
    views: {
      'menuContent': {
        templateUrl: 'templates/styleguide.html'
      }
    }
  })
})
// profile controller
.config(function($stateProvider) {
  $stateProvider

  .state('profile', {
    url: '/profile',
    abstract: true,
    templateUrl: 'templates/menu.html',
    controller: 'AppProfileCtrl as app_profile',
    resolve: {
      profile: function(API) {
        return API.getProfile();
      },
      relationship_types: function(API) {
        return API.getRelationshipTypes();
      },
      prefectures: function(API) {
        return API.getPrefectures();
      }
    }
  })
  .state('profile.show', {
    cache: true,
    url: '/show',
    parent: 'profile',
    isLoginRequired: true,
    views: {
      'menuContent': {
        templateUrl: 'templates/profile.html'
      }
    }
  })
})
// news controller
.config(function($stateProvider) {
  $stateProvider

  .state('news', {
    url: '/news',
    abstract: true,
    templateUrl: 'templates/menu.html',
    controller: 'AppNewsCtrl as app_news',
    resolve: {
      articles: function (API) {
        return API.getNews();
      }
    }
  })
  .state('news.index', {
    cache: false,
    url: '/index',
    parent: 'news',
    isLoginRequired: false,
    views: {
      'menuContent': {
        templateUrl: 'templates/news.html'
      }
    }
  })
})
// auth controller
.config(function($stateProvider) {
  $stateProvider

  .state('auth', {
    url: '/auth',
    abstract: true,
    templateUrl: 'templates/menu.html',
    controller: 'AuthCtrl as auth'
  })
  .state('auth.home', {
    url: '/home',
    parent: 'auth',
    views: {
      'menuContent': {
        templateUrl: 'templates/auth/home.html'
      }
    }
  })
  .state('auth.login', {
    url: '/login',
    parent: 'auth',
    views: {
      'menuContent': {
        templateUrl: 'templates/auth/login.html'
      }
    }
  })
  .state('auth.logout', {
    //cache: false,
    url: '/logout',
    parent: 'auth',
    views: {
      'menuContent': {
        templateUrl: 'templates/auth/logout.html'
      }
    }
  })
})
```

**Comment by jgw96** [comment] 2016-03-18 15:30
Hello @kntmrkm ! Are you still having this issue?

**Comment by kntmrkm** [comment] 2016-03-19 01:15
I think so. I do nothing for this.

**Comment by jgw96** [comment] 2016-08-10 16:12
Hello! Unfortunately i cannot reproduce this issue anymore with Ionic 1.3.1. Because of this i will be closing this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-08-10 16:12 UTC
Labels: navigation, v1
