### ISSUE TITLE
Grey square appears when opening side-menu.

### ISSUE THREAD

**Issue by Kiszko** [driftyco/ionic#8363] opened 2016-09-30 15:52 UTC
I can see this was fixed for io2 #6416 

But not for io1 :(

io 2.1.0
android 5.2.2
ios 4.1.1
cordova 6.3.1

**Comment by jgw96** [comment] 2016-09-30 17:05
Hello! Can you provide an Ionic 1 repo that I can use to reproduce this issue? Thanks!

**Comment by jgw96** [comment] 2016-10-04 15:09
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-10-04 15:09 UTC
Labels: needs reply, v1

**Comment by Kiszko** [comment] 2016-10-11 10:09
Sorry didn't get around to this, here you go.

https://github.com/Kiszko/ionic_grey_square

Screenshots:
- [Screenshot 01 ](https://s11.postimg.org/s5pe9ezpf/Screenshot_2016_10_11_10_44_02.png)
- [Screenshot 02](https://s11.postimg.org/eq2djyr7n/Screenshot_2016_10_11_10_44_08.png)

Device:
ONE E1003

Android:
5.1.1

Let me know if you need anything else.

**Comment by jgw96** [comment] 2016-10-11 16:49
Thanks @Kiszko ! Can you confirm that your android device is updated to the latest chrome webview? Since your running Android 5.1.1 the chrome webview updates independent of Android itself. To check this you can just open the google play store, slide out the side menu and tap "my apps".

**Comment by Kiszko** [comment] 2016-10-11 18:27
Hey. By 'webview' you mean Chrome Browser? In that case I'm running 4.2

**Comment by Kiszko** [comment] 2016-10-17 09:45
Pretty sure I'm on the latest WebView, realise this isn't quite high priority - but is awfully annoying. Nothing detectable from within the DOM either, this is some type of graphical glitch. Can anyone recreate this? Seems to be a problem with android only.

**Comment by gregvis** [comment] 2016-11-09 15:42
I also have this issue. It appears when the left side menu is opened. I'm running Android System Webview 54.0.2840.85 (which i believe to be the latest).

**Comment by gregvis** [comment] 2016-11-09 16:03
`.scroll-content{ overflow-y: auto; }`

this appears to fix it, but i'm not sure if there are any adverse effects to this.
