### ISSUE TITLE
ion-navbar buttons can overlap ion-title

### ISSUE THREAD

**Issue by biesbjerg** [driftyco/ionic#9534] opened 2016-12-07 13:11 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
If you have a long `iontitle' , and a (semi-)long button text, it will overlap with the ' ion-title' 

![image](https://cloud.githubusercontent.com/assets/230182/20968785/62c962a0-bc86-11e6-8852-77eeff25c1c3.png)

**Expected behavior:**
`ion-buttons` in `ion-navbar` should probably have a max width and be truncated/ellipsed, just like `ion-title` is.

**Steps to reproduce:**
Repo: https://github.com/biesbjerg/6228-ionic-keyboard-issues
Don't mind the repo name - just reusing it from a previous issue that are now fixed :-)

**Related code:**

```
<ion-header>
	<ion-navbar>
		<ion-title>This is a the greatest song in the world... tribute</ion-title>
		<ion-buttons left>
			<button ion-button icon-left>
				<ion-icon name="list"></ion-icon>
				Back
			</button>
		</ion-buttons>
		<ion-buttons right>
			<button ion-button icon-left>
				<ion-icon name="list"></ion-icon>
				Go to Playlist
			</button>
		</ion-buttons>
	</ion-navbar>
</ion-header>
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3-201612021933 (also tested 20161206xxxx)
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.9.0
ios-sim version: 5.0.12
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by jgw96** [comment] 2016-12-07 17:05
Hello, thanks for opening an issue with u! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/5036.

**Closed by jgw96** 2016-12-07 17:05 UTC
