### ISSUE TITLE
Popover and Modals interfering, body classes do not get removed - bug newly introduced with 1.3.2

### ISSUE THREAD

**Issue by leschirmeur** [driftyco/ionic#9069] opened 2016-11-07 15:43 UTC
#### Short description of the problem:
Commit https://github.com/driftyco/ionic/commit/6ed725325987559371450bedfed9ed74f9f153cd introduces a bug that the "popover-open" class is not removed from body if a modal is open at the same time.

#### What behavior are you expecting?
Removing a popover must remove the "popover-open" class from body element, even though a modal is open at the same time.

**Steps to reproduce:**
1. open a modal
2. open a popover
3. close the popover (modal still open)
--> class "popover-open" not removed from body element

```
// if condition was newly introduced
if (!modalStack.length) {
     $ionicBody.removeClass(self.viewType + '-open');
}
```

As modalStack can contain both modals and popovers, the newly introduced if-condition must take the entry type into consideration, i.e. "modal" or "popover". Otherwise, a "popover-open" class is not removed if modalStack contains any modals and vice versa for class "modal-open". 

**Which Ionic Version?** 1.x or 2.x
1.3.2

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.4.0
Gulp version:  CLI version 1.2.2
Gulp local:   Local version 3.9.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.9.0
ios-sim version: 5.0.10
OS: Mac OS X El Capitan
Node Version: v4.6.0
Xcode version: Xcode 8.1 Build version 8B62

**Comment by cBevilaqua** [comment] 2016-11-08 01:13
Already happened with me. Yesterday i updated to version 1.3.2 and after i opened a modal from a popover, for the second time, the screen has freezed and i see the "popover-open" in the body that is causing this issue.

**Comment by leschirmeur** [comment] 2016-11-08 06:33
Well, yes, it seems I forgot to mention this crucial fact: The screen freezes after opening a modal from a popover and then closing the modal. No screen interaction is possible anymore then.

**Comment by leschirmeur** [comment] 2016-11-10 02:46
@brandyscarney this is v1 not v2

**Comment by brandyscarney** [comment] 2016-11-10 02:56
@leschirmeur Oops, sorry about that. I must have been trigger happy selecting issues to label. :)

**Comment by leschirmeur** [comment] 2016-11-10 06:35
@brandyscarney :-)

**Comment by alaa-alshamy** [comment] 2016-11-21 09:35
and this bug makes the app freez in this scinario: 
1- open a popover
2- open a modal from that popover without closing the popover
3- then close the modal and popover 
and then the app got freez

and that's because the "modal-open" class doesn't remove if u closed the modal and there's a popover open and that class preventing any action on the page

**Comment by alaa-alshamy** [comment] 2016-11-21 09:44
sorry i didn't saw that u r mentioned that scenario above in the comments guys :)

**Comment by TomSeldon** [comment] 2016-11-23 14:51
Hi guys, I've just run into the same issue.

Although this appears to be a regression in 1.3.2, it's easy enough to work around.

In my case I was doing something that boiled down to:

```javascript
myPopover.show();

// on clicking an item in the popover

myPopover.hide();

$ionicModal.fromTemplateUrl('foo.html', { scope: $scope })
    .then(modal => {
        modal.show();
    });
``` 

This used to work, but now hits the issue reported here.

However, by waiting for the popover to hide **before** showing the modal, then the `popover-open` class is removed from `body` correctly.

So, the above changes to:

```javascript
myPopover.show();

// on clicking an item in the popover

myPopover.hide()
    .then(() => {
        // Popover is hidden, so now open the modal
        $ionicModal.fromTemplateUrl('foo.html', { scope: $scope })
            .then(modal => {
                modal.show();
            });
    });
```

**Comment by alaa-alshamy** [comment] 2016-11-23 16:03
i noticed that the problem not with popover only , it's happened if there's any tow of popup active together

so it's happened if there's any tow of those together : modal - alert - popover - confirm and i think even loading 

any tow of those i mentioned above active together when close one of them the class will not remove

**Comment by ps1dr3x** [comment] 2016-12-05 12:02
+1

**Comment by VinceOPS** [comment] 2016-12-09 14:31
Hi. As referenced a few minutes ago, I created an issue for the same bug: https://github.com/driftyco/ionic/issues/9538.

I wrote a fix (didn't take the pain to create a proper pull request as I don't know if the team is still working on v1...).

Find:
```
if (!modalStack.length) {
```

And replace by:

```
var otherSibling = false;

for (var i = 0; i < modalStack.length; ++i) {
  if (modalStack[i].viewType === self.viewType) {
    // there are other modal (or popover, depending on viewType)
    otherSibling = true;
    break;
  }
}

if (!otherSibling) {
```

Enjoy

**Comment by TomSeldon** [comment] 2016-12-09 14:56
Hi @VinceOPS,

I was under the impression that whilst there won't be new features for v1, bug fixes are still going to be addressed. 

If you can, I'd definitely create a PR with the fix! :)

**Comment by jgw96** [comment] 2017-01-13 21:45
This issue was moved to driftyco/ionic-v1#71

**Closed by jgw96** 2017-01-13 21:45 UTC
Labels: v1
