### ISSUE TITLE
bug: IOS9-Beta

### ISSUE THREAD

**Issue by ajaybeniwal** [driftyco/ionic#4247] opened 2015-08-18 08:13 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>I'm running my ionic app on the iOS 9 beta, it runs ok - but randomly when I click a button to take me to the next view, it will go to the new view and then take me back to the previous view. Sometimes when I click the back button in the header, it will take me to the previous view and then forward again.
App is going crazy on IOS9</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-08-18 08:13
Greetings @ajaybeniwal!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4247). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4247)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by zarko-tg** [comment] 2015-08-20 12:28
duplicate of #4082 / https://github.com/angular/angular.js/issues/12241

**Comment by mhartington** [comment] 2015-08-20 15:13
Closing as it is a duplicate. 
From the looks of things, it seems to be an issue on apples end, hence beta software.

**Comment by ekscrypto** [comment] 2015-09-10 19:10
this does not look like the same issue as the issue reported in Angular is reporting an exception, which does not seem to occur when the view transition gets screwed up.  This may be related but is definitely a source of concern for our team at the moment. +1

**Comment by mhartington** [comment] 2015-09-10 19:15
Codepen or example to test against?

**Comment by romanrast** [comment] 2015-10-20 18:20
Seeing the same issue with my apps.Running iOS 9.0.2 and ionic v1.1.0 "xenon-xerus". Is there a fix for this?

**Comment by mhartington** [comment] 2015-10-20 19:46
@romanrast 
>Codepen or example to test against?

**Comment by mlynch** [comment] 2015-12-06 07:11
Try 1.1.1 it should be fixed.

**Closed by mlynch** 2015-12-06 07:11 UTC
