### ISSUE TITLE
iOS - ionic view. Keyboard accessory bar not appearing

### ISSUE THREAD

**Issue by wdoyle** [driftyco/ionic#8525] opened 2016-10-06 08:14 UTC
Hey there,

I am using the Ionic View mode (ionic upload) to preview my app on iOS. When testing my app, I do not get the accessory bar for my inputs to allow me to go NEXT, PREV or DONE.

Can you provide any advise on why this is not working.

> Ionic.Platform.ready(() => {
    if (Keyboard) {
        Keyboard.hideKeyboardAccessoryBar(false);
        Keyboard.disableScroll(true);
    }
    if (window.cordova && window.cordova.plugins.Keyboard) {
        window.cordova.plugins.Keyboard.hideKeyboardAccessoryBar(false);
        cordova.plugins.Keyboard.hideKeyboardAccessoryBar(false);
    }
});`

I also have a directive for all my inputs that does the following:

> element.bind('touchstart', (e) => {
            if (!scope.onTouchstart) return;
  $Keyboard.hideAccessoryBar(false);
this.$timeout(() => {
                scope.onTouchstart();
            });
        });
   element.bind('blur', (e) => {
            if (!scope.onBlur) return;
  $Keyboard.hideAccessoryBar(false);
  this.$timeout(() => {
                scope.onBlur();
            });
        });

>
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Windows 7 SP1
Node Version: v5.6.0

**Comment by patrickmcd** [comment] 2016-10-06 14:44
Any time you think you have a bug using Ionic View, I suggest trying it on an actual device. Ionic View can get you most of the way there, but there are some capabilities it just doesn't have. I think this is one of them. I've given up on Ionic View altogether and only test in the browser and on devices because of this.

**Comment by jgw96** [comment] 2016-10-07 16:07
Hello, thanks for opening an issue with us! I am going to close this issue as a dupe of https://github.com/driftyco/ionic-view-issues/issues/183.

**Closed by jgw96** 2016-10-07 16:07 UTC

**Comment by fvsaddam** [comment] 2017-01-12 21:44
@jgw96 please cek this out [https://github.com/driftyco/ionic-view-issues/issues/203](203)
the input field hide by keyboard, not autoscroll.

thanks for advance.
