### ISSUE TITLE
bug: Can't open right side-menu when left side-menu has expose-aside-when set

### ISSUE THREAD

**Issue by JoeKomputer** [driftyco/ionic#3184] opened 2015-02-25 22:25 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Currently I have two side menus, the left side menu contains the attr expose-aside-when="large". When the view is larger then 768px the left menu is exposed, but this also causes the right menu to become disabled. </span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-02-25 22:25
Greetings @JoeKomputer!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3184). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3184)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by calebhaye** [comment] 2015-02-27 20:40
+1 I'm seeing this too

**Comment by calebhaye** [comment] 2015-02-27 20:44
It appears to be an issue inside of the `$ionicSideMenuDelegate`'s `toggleRight()` method, as calling that directly produces the same buggy behavior

**Comment by calebhaye** [comment] 2015-02-27 21:38
I've implemented a "fix" on my end, seems to be working well, but I'm not exactly clear on how to run tests and generate a new ionic bundle for testing.  I'm going to figure that out soon and then push the fix.

**Comment by belliAndrea** [comment] 2015-03-03 08:22
+1 i'm seeing this. Calebhay tried your solution but it doesn't semms to work :/

**Comment by calebhaye** [comment] 2015-03-03 19:08
There's another piece... I add the following code to the main app delegate

		$scope.toggleRight = function() {
		    $ionicSideMenuDelegate.toggleRight();
		};

... then invoke it directly from the view/menu:

		<ion-nav-buttons side="right">
		  <button class="button button-icon button-clear ion-navicon" ng-click="toggleRight()" >
		  </button>
		</ion-nav-buttons>

**Comment by calebhaye** [comment] 2015-03-09 08:28
Just to be clear, this is not a good fix.  If it were, I would fork and yadda yadda.  It is however, a viable hack if you need it.  I feel your pain, so I want to share what I can to help.

What I did was make the following modifications to the `ionic.bundle.js` file:
- Comment out the following code on or near line 47667:
`if (isAsideExposed || !self.right.isEnabled) return;` 

- Comment out the following code on or near line 47667:
`if (isAsideExposed || !self.right.isEnabled) return;`

That, along with the calling directly via ng-click as aforementioned, did the trick

**Comment by animungo** [comment] 2015-05-13 08:58
+1

**Comment by ericraio** [comment] 2015-05-17 02:08
I really don't want to have to modify the ionic bundle, is there a permanent fix?

**Comment by mlynch** [comment] 2015-12-07 01:17
Duplicate of #2328 which is now fixed and will be in 1.2

**Closed by mlynch** 2015-12-07 01:17 UTC
