### ISSUE TITLE
ionic 3 starter super master error

### ISSUE THREAD

**Issue by adirzoari** [driftyco/ionic#11236] opened 2017-04-16 14:31 UTC
Ionic version:
[ **3.x**

I'm submitting a bug report.
[ ] feature request

I updated to ionic 3 and i download ionic starter super master, I get this error (after i installed npm install)
  **

> Couldn't find ionic.config.json file. Are you in an Ionic project?

**Comment by peterennis** [comment] 2017-04-17 02:53
Have a look at this:
https://github.com/driftyco/ionic-starter-super/pull/95
It needs some more TLC from ionic

**Comment by jgw96** [comment] 2017-04-17 14:51
Hello, thanks for opening an issue with us. I am going to close this issue as a duplicate of https://github.com/driftyco/ionic-starter-super/issues/86

**Closed by jgw96** 2017-04-17 14:51 UTC
