### ISSUE TITLE
nested ion-side-menus disable interaction altogether

### ISSUE THREAD

**Issue by Ivshti** [driftyco/ionic#5159] opened 2016-01-23 19:14 UTC
When using nested ion-side-menus, a class ``menu-open`` is added to the top-level (body), which disables all interaction on ALL ``ion-side-menu-content``'s. Which means that the bottom-level ``ion-side-menus`` lose all kind of interaction because they're under a ``ion-side-menu-content``.

The fix would be to add the ``menu-open`` class to the closest ``ion-side-menus`` rather than on the ``body``.

The use case is if you have multiple tabs, all with their own side menu, but you want to keep the side menu code within the tab template and within it's angular scope.

**Comment by jgw96** [comment] 2016-03-14 16:26
Hello! Thanks for opening an issue with us, we just need a little more info from you so that we can better help you with your issue. Would you mind posting a code sample, plunkr or codepen that we can use to reproduce your issue? Also, would you mind running `ionic info` and posting the output? Thanks again!

**Comment by jgw96** [comment] 2016-03-21 17:00
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!

**Closed by jgw96** 2016-03-21 17:00 UTC
Labels: menus
