### ISSUE TITLE
main.js.map not found in prod build

### ISSUE THREAD

**Issue by abomadi** [driftyco/ionic#10981] opened 2017-03-30 15:36 UTC
hi i have posted this issue there, any idea ?
https://github.com/driftyco/ionic-app-scripts/issues/805

**Comment by jgw96** [comment] 2017-03-30 16:58
Hello, thanks for using Ionic! We do not generate source maps in a prod build as they would add to the size of the app and therefore have a negative impact on performance. I am going to close this one as a duplicate of driftyco/ionic-app-scripts#805.

**Closed by jgw96** 2017-03-30 16:58 UTC

**Comment by abomadi** [comment] 2017-04-02 09:53
This is the issue!, that on my prod build the app do not initialize and when debugging on console it says 
`file:///var/containers/Bundle/Application/39C211E1-ACD2-4798-96FF-8909F63DB55A/TestApp.app/www/build/main.js.map Failed to load resource: The requested URL was not found on this server.`

i know prod builds should not produce map sources and thats why im reporting this case !

Thanks

**Comment by expcapitaldev** [comment] 2017-04-14 15:14
workaround:

package.json:
"ionic_uglifyjs": "./...../uglifyjs.config.js"
add "sourceMapUrl: false" to your uglifyjs.config.js

in node_modules/@ionic/app-scripts/dist/uglifyjs.js line 58
add "sourceMapUrl: uglifyJsConfig.sourceMapUrl"
