### ISSUE TITLE
Disabled attribute with ion-input not working

### ISSUE THREAD

**Issue by antoine92190** [driftyco/ionic#10095] opened 2017-01-18 20:15 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When I use the disabled attribute on ion-input or ion-textarea, the text is not disabled.

**Expected behavior:**

I should not be able to modify the text inside an ion-input or ion-textarea when disabled.
The text opacity should also be modified.

**Ionic info:**

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: macOS Sierra
Node Version: v6.9.2
Xcode version: Xcode 8.2 Build version 8C38

**Comment by rapropos** [comment] 2017-01-18 21:36
Perhaps a dupe of #6408?

**Comment by jgw96** [comment] 2017-01-19 15:49
Hello @antoine92190 ! Thanks for opening an issue with us. Unfortunately i cannot reproduce this issue. What devices are you seeing this issue on?

**Comment by antoine92190** [comment] 2017-01-19 23:23
Hi @jgw96 
I'm using an iPhone 5s for my development testing.
I created a fresh new ionic project and did 'ionic serve', but I still experience the issue.
I tried things as:

`<ion-input disabled></ion-input>`
`<ion-input [disabled]="true"></ion-input>`
`<ion-input disabled="true"></ion-input>`

But none is working...

**Comment by ChuanTS** [comment] 2017-01-20 06:46
I have come across to the same problem

**Comment by brandyscarney** [comment] 2017-01-21 00:43
@antoine92190 Can you please try with the latest nightly and let me know if you're still seeing this:

```
npm install --save --save-exact ionic-angular@2.0.0-rc.5-201701201813
```

If you are - are you adding anything else or is it just an `ion-input` inside of an `ion-content`? Is it wrapped in a `formGroup`? Any logs in the console?

**Comment by antoine92190** [comment] 2017-01-21 12:47
Yes, it works perfectly in the nightly!
Should I wait for the rc6 release or can I use this nightly in my app?

**Comment by brandyscarney** [comment] 2017-01-24 21:47
@antoine92190 Sorry, you could have used the nightly, but rc.6 has been released now. :) I'm going to close this, thanks!

**Closed by brandyscarney** 2017-01-24 21:47 UTC
Labels: needs reply, v2

**Comment by HOLADIMEJI** [comment] 2017-08-30 15:49
Ionic 2:
Static property: 
<ion-input disabled="true" type="text"></ion-input>

Dynamically:<ion-input disabled="{{isDisabled}}" type="text"></ion-input>

After in the component(.ts file):private isInputDisabled:boolean=false;
