### ISSUE TITLE
ion-content fullscreen="true" blocks tab click event

### ISSUE THREAD

**Issue by liamdebeasi** [driftyco/ionic#10675] opened 2017-03-07 04:48 UTC
**Ionic version:** 
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Adding fullscreen="true" to ion-content causes the content to interfere with tabbar click events. When scrolling the content and then tapping a tab icon while the content is still moving, the scrolling halts, but the tab does not switch. This can cause for frustrating experience, forcing users to tap a tab icon more than once.

**Expected behavior:**
When scrolling the content and then tapping a tab icon while the content is still moving, the scrolling should halt and the tab should switch.

**Steps to reproduce:**
I have created a GitHub repo showcasing the bug here: https://github.com/liamdebeasi/ionic2-fullscreen-content

1. Clone repo and run 
```
npm install
```
2. Start up server with
```
ionic serve
```
3. Open page on a mobile phone (this issue is easier to see on an iOS device because of the rubber band scrolling)

4. Fling the Home page content

5. While the Home page content is still scrolling, tap either the "About" or "Contact" tabs. The scrolling will stop, but the tab will not switch

6. Optionally, you can set fullscreen="false" in src/pages/home/home.html and try again to see the expected result when tapping a tab.

**Other information:**

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.1.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.3
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.2.1
Xcode version: Xcode 8.2 Build version 8C38
```

**Comment by jgw96** [comment] 2017-03-08 17:46
Closing this as a duplicate of https://github.com/driftyco/ionic/issues/9644. Thanks for using Ionic!

**Closed by jgw96** 2017-03-08 17:46 UTC
