### ISSUE TITLE
bug: menu icon rendered wrong in FF

### ISSUE THREAD

**Issue by mpaland** [driftyco/ionic#5622] opened 2016-02-26 11:31 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Tested with the ionic2-starter-sidemenu demo on FF 44 and latest ionic2-beta.
The list icon is rendered in the middle of the list instead of left.
Second: The middle line of the menu symbol icon is too thin. This is an issue of the `.bar-button-menutoggle ion-icon { font-size: 2.8rem; }` which seems to be too small. Is font-size necessary here?</span>

<span is-issue-template></span>

Screenshot in FF 44:
![starter-sidemenu on ff 44](https://cloud.githubusercontent.com/assets/763140/13351143/eebbfc74-dc84-11e5-8a21-9772389bf2d7.PNG)

Screenshot in Edge (correct):
![starter-sidemenu on edge](https://cloud.githubusercontent.com/assets/763140/13351161/11ac4f18-dc85-11e5-99b4-26a58c67f2f7.PNG)

**Comment by brandyscarney** [comment] 2016-03-09 23:31
I'm not seeing any issues with the icon in FF 45. Are you still seeing this with the latest beta (2.0.0-beta.3)? 

The list display is likely caused by this issue: https://bugzilla.mozilla.org/show_bug.cgi?id=984869
So we'll have to decide how to handle this.

**Comment by mpaland** [comment] 2016-03-10 08:52
Brandy, thanks for taking care of this.
Unfortunately FF45 and beta.3 didn't change anything.
All looks exactly like the screenshot of FF44 above.

![capture](https://cloud.githubusercontent.com/assets/763140/13664121/b662835e-e6a5-11e5-9cb0-ee3584a31e70.PNG)

Version now is:

```
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
OS:
Node Version: v5.6.0

```
If you don't see it, what's the difference?

**Comment by brandyscarney** [comment] 2016-03-17 19:16
I've tried reproducing the menu icon bug on Firefox 45 on Windows 7, Windows 10 and Mac OS X El Capitan. Are you by chance viewing it on a high-density display?

**Comment by mpaland** [comment] 2016-03-18 14:11
First issue (misplaced list icons)
I had a look in the code of the ionic2-starter-sidemenu. As far as I can see, there's a bug in the code.
It should be <**ion-icon** ion-item ...
```
<ion-list>
    <ion-icon ion-item *ngFor="#item of items" (click)="itemTapped($event, item)">
```
and not <**button** ion-item  ... in list.html
Changed this and the list icons work fine.

Second issue (blue menu icon):
I don't have any high res displays here, sorry. When I change the Windows display scaling, it has no effect in FF.
When I change the zoom level in FF to 110% icon get's better, but even when on 200% the 3 menu lines get a different thickness.

I can observe this issue in your docs http://ionicframework.com/docs/v2/components/#menus as well - for ios and Windows platform. Android is okay! All my FF (rendering settings) are absolute standard. Running FF 45 on Windows 10.

I tested on my notebook, running Windows 7 and having a standard display, too.
Testing with the docs, I can see the menu icon for ios and Android okay, but Windows platform has still the problem.

I assume it's some kind of aliasing effect when scaling/rendering the Ionicons font to a fractional size.

**Comment by jgw96** [comment] 2016-03-18 14:18
Update: did a little more testing of this myself last night. On both osx el Capitan and Ubuntu 15.04 using both Firefox 45 and Firefox nightly I can't seem to repro the issue. Also tried on Firefox 45 on my Nexus 6 and couldn't repro it. My Mac has a retina display and the Ubuntu machine is just a standard 1080p display.

**Comment by mpaland** [comment] 2016-03-20 23:06
This is how it is rendered on a Surface Pro 3 (High DPI display). Upper line is too thin.
![capture](https://cloud.githubusercontent.com/assets/763140/13907904/b7a7bb84-eef8-11e5-98c9-9a28342c7f88.PNG)

**Comment by brandyscarney** [comment] 2016-04-18 20:36
I'm going to remove this from a milestone because the bug has been reopened by firefox as something they need to resolve: https://bugzilla.mozilla.org/show_bug.cgi?id=984869#c24.

**Comment by btsiders** [comment] 2016-07-01 17:59
For anyone needing to continue on while we wait for the Mozilla Firefox fix, this is my SCSS workaround specific to the button display:flex issue in my sidebar menu:

```
.platform-core {
	ion-list button.item {
		display: block; // override flex setting
		ion-icon[item-left] + .item-inner {
			padding-left: 24px; // spacing between icon and text
			margin-top: -43px; // negative item height
		}
	}
}
```

You may need to tweak the padding and margin numbers for your specific case. **This is just a workaround.** Using flex really is the better long-term solution.

**Comment by mpaland** [comment] 2016-07-03 10:36
One known workaround for the button flex "problem" in FF is to have a child div with ```display:flex```.
But I haven't tried this for menu rendering yet.

```html
<button>
  <div style="display: flex">
    <ion-icon> ... </ion-icon>
    Item Text
  </div>
</button>
```

**Comment by jgw96** [comment] 2016-08-23 16:52
Just tested this in the latest firefox and cannot seem to reproduce anymore. Thanks for using Ionic everyone!

**Comment by mpaland** [comment] 2016-11-09 18:58
FYI: I can still reproduce this button flex issue with FF 49.0.2 on Windows 10 with the ionic-conference-app menu.

**Comment by webprofusion-chrisc** [comment] 2016-11-28 03:55
@jgw96 I can confirm this bug is still happening on FF50.0 - Windows 10 - perhaps it's Windows only which is why you're not seeing it?

**Comment by jgw96** [comment] 2017-04-07 20:49
Hello all, I cannot reproduce this issue with firefox 52. Because of this I am going to close this issue for now. If its still happening for you guys please feel free to comment and we will reopen this issue.

**Closed by jgw96** 2017-04-07 20:49 UTC
Labels: menus, v2
