### ISSUE TITLE
perf: ion-refresher animation "laggy",  slow - ng-repeated list

### ISSUE THREAD

**Issue by Elvistelefon** [driftyco/ionic#3306] opened 2015-03-12 22:31 UTC
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>With rc.0 the ion-refresher animation is very laggy when pulling down a ng-repeated list with some text and images. The animation is also slow and laggy after the refresh finished and the view comes up again. Its reproducible on iOS on an iPhone4, 5 and 6. On the browser there is no problem at all.

On beta.14 everything works like a charm even on iOS. The animation and scrolling is very smooth here. 
The entire list isn't as smooth as with the beta.14

This issue is maybe related with #2395

Maybe I will create a video to show you what it is about. For the meantime the video by @danicomas shows nearly the same problem I have with ion-refrehser on rc.0: https://www.dropbox.com/s/jhb9xx1zyvremf4/IMG_0223.MOV?dl=0</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-03-12 22:31
Greetings @Elvistelefon!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3306). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3306)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by sluchznak** [comment] 2015-04-22 09:56
Hi. I have the same problem. how to solve this?

**Comment by Elvistelefon** [comment] 2015-04-22 10:28
I'm still using beta.14 where it works perfectly. Have you tested the rc4? Maybe it has been fixed here.

**Comment by sluchznak** [comment] 2015-04-22 10:51
I`m not sure what version i use, but `ionic -v` showed me version 1.3.19

**Comment by Elvistelefon** [comment] 2015-04-22 10:57
This is the cli-version. You should look into your bower.json file check the ionic entry of your devDependencies.

**Comment by sluchznak** [comment] 2015-04-22 11:04
Thanks for the tip. I`m using rc3 version. Later I'll try the new version.

**Comment by grandpalacko** [comment] 2015-04-22 15:37
I tried rc4, but the animation is still laggy.

**Comment by Elvistelefon** [comment] 2015-04-22 21:05
Have you tried beta.14? just to check if you notice the same performance boost as I did.

**Comment by ckahle33** [comment] 2015-05-11 17:26
I too am using a custom font icon for this and rotating it with CSS. I am using it in conjunction with  and infinite scroll and collection repeat for largely improved performance. Thanks.

**Comment by abeninskibede** [comment] 2015-05-26 17:18
Reproducing in version 1.0 (latest). Any way to disable animation? Problem occurs when using ng-repeat. Does not appear with collection repeat but I want to use native scrolling.

**Comment by rodolphomaia** [comment] 2015-07-09 09:34
Hi guys, a little bit late but I found the solution somewhere else. I'm posting here if anyone new comes.
Use ionic's "collection-repeat" instead "ng-repeat".

**Comment by jgw96** [comment] 2016-03-23 19:00
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!

**Closed by jgw96** 2016-03-23 19:00 UTC
