### ISSUE TITLE
Events RC1

### ISSUE THREAD

**Issue by kodeine** [driftyco/ionic#8909] opened 2016-10-26 05:35 UTC
I had been using events in beta 11 and passed objects as data. It was working fine in beta 11 but now in RC1 it seems like i can pass the strings but not the objects. 
`events.subscribe('network', (err) => {... }` i can `console.log` strings only.

If i pass object, subscription do give me data array of empty object.
![screenshot from 2016-10-26 00-35-03](https://cloud.githubusercontent.com/assets/8620059/19714471/0d7d07d6-9b14-11e6-98b5-69e78539aa0b.png)

**Comment by manucorporat** [comment] 2016-10-29 16:16
@kodeine please, follow the provided issue template! :) so I can help you better

Also, can you provide some code to reproduce the issue?

**Comment by jgw96** [comment] 2016-11-18 21:28
Hello all! As it seems it has been a while since there was any activity on this issue and I cannot reproduce i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-11-18 21:28 UTC
Labels: v2
