### ISSUE TITLE
*ngIf doesn't work with two or more conditions inside ion-slide element

### ISSUE THREAD

**Issue by robgaleano** [driftyco/ionic#9414] opened 2016-11-29 21:35 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
*ngIf not working with two or more conditions inside an `<ion-slide>` element but inside any other element it works.
it does not throw an error just does not hide the component that im trying to hide with the directive

**Expected behavior:**
That *ngIf works with 2 or more conditions inside `<ion-slide>` element.

**Steps to reproduce & Related Code:**
Just need to apply 2 conditions to an *ngIf inside an `<ion-slide element>`

For example this doesn't work:
```
<ion-slide no-padding *ngIf="typeOfPost!=0 || typeOfPost!=3">
</ion-slide>
```
But with one condition like this it works:
```
<ion-slide no-padding *ngIf="typeOfPost!=0">
</ion-slide>
```
And for example this with two conditions inside an ion-searchbar also works:

```
<ion-searchbar *ngIf="currentIndex == 0 && typeOfPost !=3"></ion-searchbar>
```

So i could think that the problem is related to the component itself

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
ios-deploy version: 1.9.0
ios-sim version: 5.0.8
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 7.3.1 Build version 7D1014
```

**Comment by brandyscarney** [comment] 2017-01-24 20:00
I'm going to close this issue since I am not able to reproduce it and we've made several changes to slides. I'm not sure if your logic here was just an example of two conditions but this will always evaluate to true: `*ngIf="typeOfPost!=0 || typeOfPost!=3"` so that could have been causing you issues. If you're still seeing problems please open a new issue with a way for us to reproduce. Thanks!

**Closed by brandyscarney** 2017-01-24 20:00 UTC
Labels: needs reply, v2
