### ISSUE TITLE
input bug for rc3

### ISSUE THREAD

**Issue by yozman** [driftyco/ionic#9219] opened 2016-11-18 05:26 UTC
there is a bug at rc3.
when I focus the input
there will be auto scroll
it's a good feature

but then I scroll with the focus status
input will be duplicated

could you tell me how to make it works well?

**Comment by yozman** [comment] 2016-11-18 06:02
I got the answer,
ion-input should must use with ion-list & ion-item

**Comment by PrithiviRajG** [comment] 2016-11-18 09:24
It didn't worked for me... I have only two fields user Id and password, when I focus to password field, user Id field is scrolled up and only the password field is visible. Before it was working fine

![screenshot_2016-11-18-14-47-46](https://cloud.githubusercontent.com/assets/10797126/20425041/c17d6db0-ad9e-11e6-94dd-a1f21f1ca4a2.png)

**Comment by jgw96** [comment] 2016-11-18 20:04
Hello all! I am going to close this as a duplicate of https://github.com/driftyco/ionic/issues/9227. Thanks!

**Closed by jgw96** 2016-11-18 20:04 UTC
Labels: v2
