### ISSUE TITLE
IonicPage with ion-tabs

### ISSUE THREAD

**Issue by viveksinha9** [driftyco/ionic#11766] opened 2017-05-24 07:41 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I am using IonicPage decorator with some of my pages. When I run project in browser using ionic serve each page URL is correctly shown in url bar. But when I open any url directly, it take me to root page. I am using tabs at my home page & want to open inner pages.

**Expected behavior:**
Page should open directly.

**Steps to reproduce:**
1. Create an app with 2 tabs. (say a and b) 
2. create a page (say a_1) which will be navigated when click a button in root page of tab 'a'.
3. Try to open page a_1 directly with URL.

**Comment by jgw96** [comment] 2017-05-24 17:44
Hello, thanks for using Ionic! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/11703.

**Closed by jgw96** 2017-05-24 17:44 UTC
