### ISSUE TITLE
bug: Content getDimensions, gives parentElement is null in second call

### ISSUE THREAD

**Issue by utopiafx** [driftyco/ionic#9302] opened 2016-11-23 08:00 UTC
**Ionic version:** 
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...** 
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When I create an new modal and in that window I could use scroll to bottom in the content.
When I close this windows and open it again it will then say after I call the function getDimensions:
EXCEPTION: Cannot read property 'parentElement' of null

**Expected behavior:**
The parentElement shouldn't be null. It works in the first place, but second call to the same modal gives this error. I expected to open a new modal everytime and after that call my getDimensions without getting error.

**Relevant code:**
Here is the setup:

Home.ts

```
import {ModalController} from 'ionic-angular';
import { Chatt } from '../chatt/chatt';
...
@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class Home {
...
constructor(..., public modalCtrl: ModalController,....) {

}
...
// This is being call when I want to open the new modal for chatt everytime
openChatt() {
 let modal = this.modalCtrl.create(Chatt);
 modal.present();
}
..
}

```

Chatt.ts

```
import { NavController,.......,Content } from 'ionic-angular';
...

@Component({
  selector: 'page-chatt',
  templateUrl: 'chatt.html'
})
export class Chatt {
@ViewChild(Content) content: Content;

constructor(public navCtrl: NavController,.......) {
....
}

// Notice it doesn't matter if you doing this ngAfterViewInit() either!
ionViewDidLoad() {
 // First round works well (not perfect accurate height dimensions), second round gives the error here!
// this is used for scrolling down to the bottom of the content (see possible error taking place in ionic2 code below)
let dimensions = this.content.getContentDimensions();

}

// Also important to notice how i close the window here
public goBack() {

// This gives the same behaviour as above
this.navCtrl.pop();

// Notice: It doesn't matter either if you using dismiss with ViewController here

}
...
}
```

-----------------------------------
snapshot from ionic/src/components/content/content.ts

```
getContentDimensions(): ContentDimensions {
    const scrollEle = this._scrollEle;
    const parentElement = scrollEle.parentElement;  // <-- null here ?

    return {
      contentHeight: parentElement.offsetHeight - this.contentTop - this.contentBottom,
      contentTop: this.contentTop,
      contentBottom: this.contentBottom,

      contentWidth: parentElement.offsetWidth,
      contentLeft: parentElement.offsetLeft,

      scrollHeight: scrollEle.scrollHeight,
      scrollTop: scrollEle.scrollTop,

      scrollWidth: scrollEle.scrollWidth,
      scrollLeft: scrollEle.scrollLeft,
    };
  }
```

**Setup package Info**

Cordova CLI: 6.3.1 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.9.0 
ios-sim version: Not installed
OS: OS X Yosemite
Node Version: v6.7.0
Xcode version: Xcode 7.2.1 Build version 7C1002

**Comment by designmobile** [comment] 2016-12-02 12:16
I solve the problem, it was not a bug. I hasn't anything todo with ionic2 core. 
But it was inflected it, when it crash.

Firstly I was connected to the firebase and the problem  when I first create an instance to an firebase  object directly after creating an modal windo.  Because when i create and listener i also forget to detach the listener refrence to the same firebase object when closing the chatt modal window. So next time the instance was already there, but it was casting an firebase error message when i wrote something to my firebase object and after that came also the suit of null instance with bottomscroll, so it looks like it was some bug with the ionic2, but it wasn't. It was always the missing part of detaching the reference of the firebase object.

Maby there are some better explanations here.

**Closed** 2016-12-02 12:22 UTC
Labels: v2
