### ISSUE TITLE
Unable to push a Page using NavigationController in ionic2

### ISSUE THREAD

**Issue by shikhahanda** [driftyco/ionic#9375] opened 2016-11-28 04:13 UTC
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed

I'm very new to Ionic2 and Typescript. I'm trying to develop a simple To Do Application.  I have a Home Page which lists the dummy todo items. I have also added a new Page called AddPage that should be displayed on clicking the Add button on the home page. Now when I use this.navctrl.push(AddPage) in the addItem() function in home.ts, it just displays the blank page. Please see below the html page and script code.

However whenever i comment the   this.navCtrl.push(AddPage); in addItem() function, it displays the contents of the HomePage.

Please advise how I can fix the issue.

Home.Html

```html
<ion-header>
  <ion-navbar color="secondary">
    <ion-title >
      My Todos!!
    </ion-title>
	<ion-buttons end>
	<button ion-button icon-only (click)="addItem()"><ion-icon name="add-circle"></ion-icon></button>
	</ion-buttons>
  </ion-navbar>
</ion-header>

<ion-content padding>
  <ion-list>
    <ion-item *ngFor="let item of items" (click)="viewItem()">{{item.title}}</ion-item>
  </ion-list>
  
</ion-content>
```

Home.ts
```ts
import { Component } from '@angular/core';

import {  NavController} from 'ionic-angular';
import { AddPage } from '../pages/add/add';



@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

   items = [];
  
  constructor(public navCtrl: NavController) {
    this.navCtrl=navCtrl;
	
	 this.items = [
      {title: 'hi1', description: 'test1'},
      {title: 'hi2', description: 'test2'},
      {title: 'hi3', description: 'test3'}
    ];
  }
  

   viewItem(){
   //this.navCtrl.push(AddPage);
   }
 addItem(){
 console.log("Test");
// this.navCtrl.pop(HomePage);
  this.navCtrl.push(AddPage);
  
  }
	
 
}
```
 
Add. HTML:

```html
<ion-content>
    <ion-list>
 
      <ion-item>
        <ion-label floating>Title</ion-label>
        <ion-input type="text" [(ngModel)]="title"></ion-input>
      </ion-item>
 
      <ion-item>
        <ion-label floating>Description</ion-label>
        <ion-input type="text" [(ngModel)]="description"></ion-input>
      </ion-item>
 
    </ion-list>
   <ion-buttons end>
            <button (click)="saveItem()">Save</button> 
        </ion-buttons>
</ion-content>
```

Add.Ts

```ts
import { Component } from '@angular/core';
import { NavController, NavParams } from 'ionic-angular';

/*
  Generated class for the Add page.

  See http://ionicframework.com/docs/v2/components/#navigation for more info on
  Ionic pages and navigation.
*/
@Component({
  selector: 'page-add',
  templateUrl: 'add.html'
})
export class AddPage {

  public title;
  public description;
  
  constructor(public navCtrl: NavController, public navParams: NavParams) {
	this.navCtrl=navCtrl;
	this.navParams=navParams;
	this.title="";
	this.description="";
  }

  saveItem(){
 
    let newItem = {
      title: this.title,
      description: this.description
    }
	this.navParams.get('HomePage').saveItem(newItem);
	this.navCtrl.pop();
	
	
	
  }
close()
{

}
  
}
```

Refer to the template and

**Comment by fahimshekaib** [comment] 2016-11-28 11:42
On importing it there is no error:
import { NavController } from 'ionic-angular';

But, when I add it in the constructor:
constructor(public nav: NavController) 

It is giving me this error: No provider for NavController!
If the constructor is empty. The page renders fine, but I need to navigate to another page.

Platform details:
Ionic Framework: 2.0.0-rc.3
Ionic Native: 2.2.3
Ionic App Scripts: 0.0.45
Angular Core: 2.1.1
Angular Compiler CLI: 2.1.1
Node: 7.2.0
OS Platform: OS X El Capitan
Navigator Platform: MacIntel
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36

**Comment by rapropos** [comment] 2016-11-29 21:59
This looks more like a support question than a bug report to me.

**Comment by manucorporat** [comment] 2016-11-30 11:24
does it throw any error? I can't reproduce your issue.
can your provide a minimum plunker that reproduces your issue?
http://plnkr.co/edit/GJte2b?p=preview

**Comment by jgw96** [comment] 2017-01-25 15:26
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-01-25 15:26 UTC
Labels: v2
