### ISSUE TITLE
bug: ionic emulate android -l not working

### ISSUE THREAD

**Issue by bastiss** [driftyco/ionic#8615] opened 2016-10-10 15:00 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>6.0</span>  <span ionic-webview>webview</span>

<span ionic-description>ionic emulate android -l

Livereload doesn't work on device or emulator. Code / template changes get not automatically reloaded.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment] 2016-10-10 18:01
Hello, thanks for using Ionic! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic-cli/issues/1425.

**Closed by jgw96** 2016-10-10 18:01 UTC
