### ISSUE TITLE
TypeError: Cannot read property 'codeGen' of undefined 

### ISSUE THREAD

**Issue by apolishch** [driftyco/ionic#11420] opened 2017-04-27 21:42 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

The project builds succesfully

**Steps to reproduce:**

**Related code:**
By debugging it would seem that the problem is that 

```var compiler_cli_1 = require("@angular/compiler-cli");``` no longer has a ```__NGTOOLS_PRIVATE_API_2```

**Other information:**

``` ionic-app-scripts build --prod

[18:53:05]  ionic-app-scripts 1.3.5 
[18:53:05]  build prod started ... 
[18:53:05]  clean started ... 
[18:53:05]  clean finished in 1 ms 
[18:53:05]  copy started ... 
[18:53:05]  ngc started ... 
[18:53:06]  ionic-app-script task: "build" 
[18:53:06]  TypeError: Cannot read property 'codeGen' of undefined 
TypeError: Cannot read property 'codeGen' of undefined
    at Object.doCodegen (/Users/abrahampolishchuk/github/flock/flock-app-client/node_modules/@ionic/app-scripts/dist/aot/codegen.js:6:50)
    at /Users/abrahampolishchuk/github/flock/flock-app-client/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:42:30```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.5
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.10.2
Xcode version: Xcode 8.3.1 Build version 8E1000a
```

**Comment by rapropos** [comment] 2017-04-28 00:15
Looks like a dupe of [app-scripts #918](https://github.com/driftyco/ionic-app-scripts/issues/918) to me.

**Comment by jgw96** [comment] 2017-04-28 14:36
Hello all! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic-app-scripts/issues/918

**Closed by jgw96** 2017-04-28 14:36 UTC
