### ISSUE TITLE
datetime - Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Daskus1** [driftyco/ionic#11447] opened 2017-04-30 12:52 UTC
**Ionic version:**  (check one with "x")
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
Since I upgraded to Ionic 3.1.1 all ion-datetime in my app do not work anymore.
I can select a date one time, but as soon as I select another date I get the following error:
```
RangeError: Maximum call stack size exceeded
    at callWithDebugContext (http://localhost:8100/build/main.js:13377:15)
    at Object.debugHandleEvent [as handleEvent] (http://localhost:8100/build/main.js:12954:12)
    at dispatchEvent (http://localhost:8100/build/main.js:9133:21)
    at http://localhost:8100/build/main.js:10997:38
    at SafeSubscriber.schedulerFn [as _next] (http://localhost:8100/build/main.js:4193:36)
    at SafeSubscriber.__tryOrUnsub (http://localhost:8100/build/main.js:19195:16)
    at SafeSubscriber.next (http://localhost:8100/build/main.js:19144:22)
    at Subscriber._next (http://localhost:8100/build/main.js:19086:26)
    at Subscriber.next (http://localhost:8100/build/main.js:19050:18)
    at EventEmitter.Subject.next (http://localhost:8100/build/main.js:41303:25)
    at EventEmitter.emit (http://localhost:8100/build/main.js:4167:76)
    at TimeoutDebouncer.<anonymous> (http://localhost:8100/build/main.js:39357:33)
    at TimeoutDebouncer.schedule (http://localhost:8100/build/main.js:86890:18)
    at TimeoutDebouncer.debounce (http://localhost:8100/build/main.js:86882:14)
    at DateTime.BaseInput._fireIonChange (http://localhost:8100/build/main.js:39355:29)
```

I build my forms using Angulars reactive forms.
When `ionChange` fires I use `patchValue` to set the value in my form.
Before upgrading to Ionic 3.1.x everything worked as expected.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 3.1.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.6.0
Xcode version: Not installed
```

**Comment by manucorporat** [comment] 2017-04-30 15:35
can you provide a template + code that reproduces the issue? I think the stack loop is in your code

**Comment by jgw96** [comment] 2017-05-04 15:20
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-05-04 15:20 UTC
Labels: needs info, v2
