### ISSUE TITLE
Ionic2 ion-item with ion-select  lost className ng-*

### ISSUE THREAD

**Issue by anrip** [driftyco/ionic#8082] opened 2016-09-14 16:13 UTC
here, the ion-item have not include the className "ng-valid ng-touched ng-dirty".

```
<ion-item class="item item-select">
    <div class="item-inner">
      <div class="input-wrapper">
        <ion-select class="ng-valid ng-touched ng-dirty">
         .........
        </ion-select>
      </div>
    </div>
</ion-item>
```

howerver, i think we shoude do it like the ion-input.

```
<ion-item class="item item-input ng-pristine ng-invalid ng-touched">
    <div class="item-inner">
      <div class="input-wrapper">
        <ion-input name="password" class="ng-pristine ng-invalid ng-touched">
        </ion-input>
        ........
      </div>
    </div>
</ion-item>
```

**Comment by jgw96** [comment] 2016-09-15 18:15
Hello, thanks for opening an issue with us! Unfortunately, I am not fully understanding the issue here. Are you saying that `ion-select` is not getting the correct classes? From your code snippet it seems like it is? Thanks!

**Comment by anrip** [comment] 2016-09-15 18:35
Yes, the ion-select do not sync the ng-* to the <ion-select> tag from <ion-item>.

when `<ion-select ng-reflect-model="m" class="ng-valid ng-touched ng-dirty">`, 
then `<ion-item class="item item-select ng-valid ng-touched ng-dirty">`

**Comment by brandyscarney** [comment] 2016-09-19 22:05
Closing as a duplicate of https://github.com/driftyco/ionic/issues/6040. Thanks!

**Closed by brandyscarney** 2016-09-19 22:05 UTC
Labels: select, v2
