### ISSUE TITLE
Object.prototype.xx is conflict with ionic

### ISSUE THREAD

**Issue by dingdong-io** [driftyco/ionic#8873] opened 2016-10-24 10:28 UTC
#### Short description of the problem:

I want to make a common method to all Object link this

``` js
Object.prototype.getValue = function (keychain) {
    var tree = keychain.replace(/[\]\"\']/g, '').split(/[\[\.]/),
        result = this;
    tree.forEach(function (child) {
        if(child){
            result = result[child]
        }
    })
    return result
}
//test
var obj = {city:{school:{student1:'dingding',student2:'dongdong'}}}
console.log(obj.getValue('city["school"].student1'))  //dingding
```

It makes get value easier with no sure length of property,also support variable like

``` js
var student= 'student2'
console.log(obj.getValue('["city"].school[' + student+ ']')) //dongdong
```

It works well independent,but in ionic workspace,throw error,seem happend when DOM object event,I can't find the reason.

> Cannot read property 'nodeType' of undefined
> or
> Failed to execute 'setAttribute' on 'Element': 'function (keychain){ ..

How to solve this problem?

**Which Ionic Version?** 1.0

**Comment by jgw96** [comment] 2016-10-24 15:56
Hello, thanks for using Ionic! Would you mind making a plunker or codepen I can use to reproduce this issue?

**Comment by dingdong-io** [comment] 2016-10-25 02:38
@jgw96 
I build the [plunker](https://plnkr.co/edit/SSOnOwODhrpTKZZKXg5a)

**Comment by jgw96** [comment] 2016-10-27 18:53
Thanks @dingdong-io ! So just to confirm, this works in a plain Angular 1 project right?

**Comment by dingdong-io** [comment] 2016-10-28 06:47
To @jgw96 :Yes,I used angular 1. I have a [try](https://plnkr.co/edit/YxsoQo),without ionic,just angular and ui-router,no conflict happened,seems conflict with ionic's code.

**Comment by dingdong-io** [comment] 2016-11-01 03:49
@jgw96 : Has any progress?

**Comment by jgw96** [comment] 2016-11-01 15:47
Hello, sorry for the delay! So after reviewing this issue I am going to point you towards our [forum](https://forum.ionicframework.com/). Since this is custom behavior you are writing to work with Ionic 1 and is not really a bug in Ionic 1 but simply a difference with Angular 1 I am going to close this issue for now. Thanks!

**Closed by jgw96** 2016-11-01 15:47 UTC
Labels: v1

**Comment by dingdong-io** [comment] 2016-11-07 02:00
In this case,what shall I do if I want realize Object.protype.xx with ionic
