### ISSUE TITLE
bug: sidemenu button not showing on all page headers

### ISSUE THREAD

**Issue by unnibethur** [driftyco/ionic#3444] opened 2015-03-31 12:01 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>i need to get side menu button in all pages in my app, so  i put the button on nav-bar at the index page as below the back button.  then button will showing all pages but i getting issue that  i mentioned below

Error: sideMenuCtrl is undefined .link/<@http://localhost/HybridApp/Kinoto/App/www/lib/ionic/js/ionic.bundle.js:51782:15 $RootScopeProvider/this.$get</Scope.prototype.$broadcast@http://localhost/HybridApp/Kinoto/App/www/lib/ionic/js/ionic.bundle.js:22645:15 self.beforeEnter@http://localhost/HybridApp/Kinoto/App/www/lib/ionic/js/ionic.bundle.js:46049:5 self.transition@http://localhost/HybridApp/Kinoto/App/www/lib/ionic/js/ionic.bundle.js:46861:5 self.update@http://localhost/HybridApp/Kinoto/App/www/lib/ionic/js/ionic.bundle.js:46849:5 self.beforeEnter@http://localhost/HybridApp/Kinoto/App/www/lib/ionic/js/ionic.bundle.js:47251:1 self.beforeEnter@http://localhost/HybridApp/Kinoto/App/www/lib/ionic/js/ionic.bundle.js:49145:1 $RootScopeProvider/this.$get</Scope.prototype.$emit@http://localhost/HybridApp/Kinoto/App/www/lib/ionic/js/ionic.bundle.js:22572:15 ionicViewSwitcher.create/switcher.emit@http://localhost/HybridApp/Kinoto/App/www/lib/ionic/js/ionic.bundle.js:45784:13 ionicViewSwitcher.create/switcher.transition@http://localhost/HybridApp/Kinoto/App/www/lib/ionic/js/ionic.bundle.js:45657:13 self.render/<@http://localhost/HybridApp/Kinoto/App/www/lib/ionic/js/ionic.bundle.js:47237:1 ionicViewSwitcher.create/switcher.init/<@http://localhost/HybridApp/Kinoto/App/www/lib/ionic/js/ionic.bundle.js:45535:25 ionicViewSwitcher.create/switcher.render@http://localhost/HybridApp/Kinoto/App/www/lib/ionic/js/ionic.bundle.js:45624:23 ionicViewSwitcher.create/switcher.init@http://localhost/HybridApp/Kinoto/App/www/lib/ionic/js/ionic.bundle.js:45534:11 self.render@http://localhost/HybridApp/Kinoto/App/www/lib/ionic/js/ionic.bundle.js:47231:5 self.register@http://localhost/HybridApp/Kinoto/App/www/lib/ionic/js/ionic.bundle.js:47189:5 updateView@http://localhost/HybridApp/Kinoto/App/www/lib/ionic/js/ionic.bundle.js:52439:11 .compile/</<@http://localhost/HybridApp/Kinoto/App/www/lib/ionic/js/ionic.bundle.js:52416:11 $RootScopeProvider/this.$get</Scope.prototype.$broadcast@http://localhost/HybridApp/Kinoto/App/www/lib/ionic/js/ionic.bundle.js:22645:15 transitionTo/$state.transition<@http://localhost/HybridApp/Kinoto/App/www/lib/ionic/js/ionic.bundle.js:40115:11 processQueue@http://localhost/HybridApp/Kinoto/App/www/lib/ionic/js/ionic.bundle.js:21114:27 scheduleProcessQueue/<@http://localhost/HybridApp/Kinoto/App/www/lib/ionic/js/ionic.bundle.js:21130:27 $RootScopeProvider/this.$get</Scope.prototype.$eval@http://localhost/HybridApp/Kinoto/App/www/lib/ionic/js/ionic.bundle.js:22326:16 $RootScopeProvider/this.$get</Scope.prototype.$digest@http://localhost/HybridApp/Kinoto/App/www/lib/ionic/js/ionic.bundle.js:22142:15 $RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost/HybridApp/Kinoto/App/www/lib/ionic/js/ionic.bundle.js:22431:13 timeout/timeoutId<@http://localhost/HybridApp/Kinoto/App/www/lib/ionic/js/ionic.bundle.js:24157:25 completeOutstandingRequest@http://localhost/HybridApp/Kinoto/App/www/lib/ionic/js/ionic.bundle.js:12830:7 Browser/self.defer/timeoutId<@http://localhost/HybridApp/Kinoto/App/www/lib/ionic/js/ionic.bundle.js:13210:7

please help</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-03-31 19:55
Greetings @unnibethur!

My sensors indicate that I require more information in order to assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this happen occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com), where many humans will be able to offer wisdom and advice.

Thank you for allowing me to assist you.

<span ionitron-needs-reply></span>

**Comment by Ionitron** [comment] 2015-04-30 22:56
Greetings @unnibethur!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment] 2015-04-30 22:56
Greetings @unnibethur!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-04-30 22:56 UTC
Labels: ionitron:closed
