### ISSUE TITLE
Bug when trying to add more than fourteen named colors in variables.scss file

### ISSUE THREAD

**Issue by csguedes** [driftyco/ionic#10924] opened 2017-03-26 23:27 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When I add more than fourteen named colors in variables.scss file and create a production build with --prod switch (ionic run android --prod), all screens get blank after splash screen. Sometimes the position also matters (adding the new named colors at the end of list or just under "primary" named color).

**Expected behavior:**
We should be able to add as many named colors as needed. Also position shouldn't matter.

**Steps to reproduce:**

**Related code:**

```
Add the following named colors just under the "dark" named color in variables.scss file. 
Then run the app in real device with --prod switch:

  C117CC0:      #117CC0,
  C2a4296:       #2a4296,
  CFF0000:       #FF0000,
  CF01E00:       #F01E00,
  CFF6600:       #FF6600,
  CF66B17:       #F66B17,
  CFF9400:       #FF9400, 
  CFEC500:       #FEC500,
  CFFFF00:       #FFFF00,
  C8CC700:       #8CC700,
  C0FAD00:       #0FAD00,
  C00A3C7:       #00A3C7,
  C0064B5:       #0064B5,
  C0010A5:       #0010A5,
  C6300A5:       #6300A5,
  CC5007C:       #C5007C,
  C000000:       #000,
  CFFFFFF:       #FFF,
  CCCCCCC:       #CCC,
  CDCDCDC:       #DCDCDC
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.2.2
Xcode version: Not installed

I have also tried to add more than fourteen named colors to variables.scss file in the latest 2.3.0 version (same results).
```

**Comment by jgw96** [comment] 2017-03-27 07:07
Hello, thanks for opening an issue with us! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/9465.

**Closed by jgw96** 2017-03-27 07:07 UTC
