### ISSUE TITLE
bug: --prod fails with page module

### ISSUE THREAD

**Issue by sebastianovide** [driftyco/ionic#11400] opened 2017-04-27 08:39 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>npm install -g cordova ionic
ionic start myApp tabs
cd myApp/
npm install
ionic g page deleteme
npm run build --prod</span>

<span is-issue-template></span>

**Comment by nicobytes** [comment] 2017-04-27 08:44
The same error

**Comment by aggarwalankush** [comment] 2017-04-27 09:02
Might be related to this - https://github.com/driftyco/ionic-app-scripts/issues/920#issuecomment-297227194

**Comment by jgw96** [comment] 2017-04-27 14:21
Hello, all! Closing this issue as a duplicate of https://github.com/driftyco/ionic/issues/11388

**Closed by jgw96** 2017-04-27 14:21 UTC
