### ISSUE TITLE
nav error with ionic 3.0.0-beta.3

### ISSUE THREAD

**Issue by yozman** [driftyco/ionic#10958] opened 2017-03-29 08:11 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.0.0-beta.3**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

```
nav-controller-base.js:88
Failed to navigate:  Cannot find module '..pagespage-twopage-two.module'.
```
can not `nav.push` with `string`
I think the reason is
the atomatic loadChildren generate from name use IonicPage is making trouble.

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by AmitMY** [comment] 2017-03-29 09:21
Duplicate of: https://github.com/driftyco/ionic/issues/10946
`'..pagespage-twopage-two.module'.` is the problem, somehow it removes slashes, and does not do:
'..pages/page-two/page-two.module'.

**Comment by jgw96** [comment] 2017-03-29 14:07
Hello, thanks for opening an issue with us. After reviewing this issue I am going to close this as a duplicate of #10946

**Closed by jgw96** 2017-03-29 14:07 UTC
