### ISSUE TITLE
Error: No provider for TransitionController!

### ISSUE THREAD

**Issue by emmanuelroussel** [driftyco/ionic#10264] opened 2017-02-01 06:09 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I set up unit testing with Jasmine and Karma following [this tutorial](http://lathonez.github.io/2017/ionic-2-unit-testing/). When I try to run a test for a component containing tabs, it crashes with `Error: No provider for DeepLinker!`. I was able to get passed that by adding a few providers to `test.ts`, but then got `Error: No provider for TransitionController!`. However, I can't import it because it is not exported in `node_modules/ionic-angular/index`. (original error and more info [here](http://stackoverflow.com/questions/41773526/error-no-provider-for-deeplinker-while-unit-testing-components))

**Expected behavior:**
Be able to import TransitionController (or I might not be using providers in the right way).

**Other information:**
Original error: http://stackoverflow.com/questions/41773526/error-no-provider-for-deeplinker-while-unit-testing-components. I was able to add the appropriate providers, but then got blocked with TransitionController.

Potential fix: Add `export { TransitionController } from './transitions/transition-controller';` in `ionic/src/index.ts`.

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.1.0
Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by jgw96** [comment] 2017-02-02 15:20
Hello, thanks for using Ionic! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/5331 as this issue is part of the underlying issue there.

**Closed by jgw96** 2017-02-02 15:20 UTC
