### ISSUE TITLE
error generate ionic g page 

### ISSUE THREAD

**Issue by gbelmm** [driftyco/ionic#11094] opened 2017-04-06 15:21 UTC
![captura de pantalla 2017-04-06 a las 12 19 14](https://cloud.githubusercontent.com/assets/731936/24762028/7d0a50ca-1ac3-11e7-8a94-1db6daf6b10e.png)

![captura de pantalla 2017-04-06 a las 12 19 45](https://cloud.githubusercontent.com/assets/731936/24762032/81cf79b4-1ac3-11e7-8e34-4c86c45e7424.png)
![captura de pantalla 2017-04-06 a las 12 20 03](https://cloud.githubusercontent.com/assets/731936/24762049/8fe69d84-1ac3-11e7-9a16-0cc74165bf5d.png)

**Comment by rapropos** [comment] 2017-04-06 18:37
Dupe of #11076.

**Comment by brandyscarney** [comment] 2017-04-06 21:47
Thanks for the issue! Closing this as a duplicate of #11076 which was moved to https://github.com/driftyco/ionic-cli/issues/2070.

**Closed by brandyscarney** 2017-04-06 21:47 UTC
