### ISSUE TITLE
bug: no $ionicSideMenuOpen and $ionicSideMenuClose events when open side menu by sliding content

### ISSUE THREAD

**Issue by aszmyd** [driftyco/ionic#4874] opened 2015-12-28 13:30 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When open side menu with an hamburger icon, the events get fired (notice close event being called 3 times, not sure why but its not such issue for me at least).
Problem is when we open side menu by slide content area from left to right. The menu appears but events are not fired.

![image](https://cloud.githubusercontent.com/assets/3050805/12019356/800bf890-ad6f-11e5-8aff-2ced823dc557.png)

Pen: http://codepen.io/anon/pen/ZQBExy</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-12-28 13:30
Greetings @aszmyd!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4874). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4874)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by kaikcreator** [comment] 2016-01-28 10:30
Yes, it would be nice to fire the **$ionicSideMenuOpen** event when menu is opened by dragging.

I think it would be only add $rootScope.emit("$ionicSideMenuOpen") at **$ionicSideMenus.snapToRest** method, and similar with $ionicSideMenuClose. However, maybe some checks about if the menu was already open or closed should be performed.

**Comment by jgw96** [comment] 2016-03-14 18:50
Hello! Thanks for opening an issue with us, we just need a little more info from you so that we can better help you with your issue. Would you mind posting a code sample, plunkr or codepen that we can use to reproduce your issue? Also, would you mind running `ionic info` and posting the output? Thanks again!

**Comment by jgw96** [comment] 2016-05-12 20:29
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-05-12 20:29 UTC
Labels: menus, v1
