### ISSUE TITLE
Searchbar doesn't fire blur event.

### ISSUE THREAD

**Issue by viniciusgandrade** [driftyco/ionic#7158] opened 2016-07-01 14:32 UTC
#### Short description of the problem:
When tap a searchbar, keyboard shows up. When focusing out or scrolling the list, the keyboard doesn't hide.

#### What behavior are you expecting?
I suppose that the correct behaviour, like in native apps, is to hide the keyboard when tap the list or out of the searchbar.

**A possible solution is something like the input-native solution. In a older version of ionic, the problem was the same:**
```
@Component({
    selector: 'ion-searchbar',
    host: {
        '[class.searchbar-has-value]': '_value',
        '[class.searchbar-active]': '_isActive',
        '[class.searchbar-show-cancel]': 'showCancelButton',
        '[class.searchbar-left-aligned]': 'shouldAlignLeft()'
    },
    directives: [NativeInput],
    template:
    '<div class="searchbar-input-container">' +
    '<button (click)="cancelSearchbar($event)" (mousedown)="cancelSearchbar($event)" ' +
    'clear dark class="searchbar-md-cancel">' +
    '<ion-icon name="arrow-back"></ion-icon>' +
    '</button>' +
    '<div #searchbarIcon class="searchbar-search-icon"></div>' +
    '<input #searchbarInput [(ngModel)]="_value" [attr.placeholder]="placeholder" ' +
    '(input)="inputChanged($event)" (blur)="inputBlurred($event)" (focus)="inputFocused($event)" ' +
    'class="searchbar-input text-input">' +
    '<button clear class="searchbar-clear-icon" (click)="clearInput($event)" ' +
    '(mousedown)="clearInput($event)"></button>' +
    '</div>' +
    '<button #cancelButton [tabindex]="_isActive ? 1 : -1" clear (click)="cancelSearchbar($event)" ' +
    '(mousedown)="cancelSearchbar($event)" class="searchbar-ios-cancel">{{cancelButtonText}}</button>',
    encapsulation: ViewEncapsulation.None
})
```
**I'm just add the class text-input to the <input> tag and it's works.**

**Comment by jgw96** [comment] 2016-07-22 18:55
Hello, thanks for opening an issue with us! Are you still having this issue with beta.10? I cant seem to reproduce on my iphone or any of my Android devices. Thanks!

**Comment by jgw96** [comment] 2016-07-27 16:13
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-07-27 16:13 UTC
Labels: keyboard, needs reply, platform:ios, v2

**Comment by alexandrzavalii** [comment] 2016-10-31 12:44
I have the same issue on iphone 5. I have tested on android and it works fine. 
does anyone have a fix?

**Comment by biesbjerg** [comment] 2016-11-15 13:49
@alexandrzavalii There's a workaround in https://github.com/driftyco/ionic/issues/8933
