### ISSUE TITLE
Scroll doesn't work with tap event (v2)

### ISSUE THREAD

**Issue by sfabriece** [driftyco/ionic#7012] opened 2016-06-22 06:42 UTC
with the following code scrolling works: 
```
<ion-list>
     <div tappable (click)="openPage()"></div>
</ion-list>
```
when I change the event to tap, scrolling doesn't work.
```
<ion-list>
     <div tappable (tap)="openPage()"></div>
</ion-list>
```

**Comment by jgw96** [comment] 2016-06-22 18:26
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by sfabriece** [comment] 2016-06-22 19:40
I'm finding it hard to reproduce in plunker because of lack of gestures. What happens when running on a device is that a fling down doesn't work with tap event.

**Comment by jeromeXoo** [comment] 2016-06-23 12:28
Hi,

Same as https://github.com/driftyco/ionic/issues/6897

**Comment by jgw96** [comment] 2016-07-22 19:07
Hello! I will be closing this issue as a duplicate of #6897 Thanks for using Ionic!

**Closed by jgw96** 2016-07-22 19:07 UTC
Labels: v2
