### ISSUE TITLE
service worker does not work on device

### ISSUE THREAD

**Issue by rolandjitsu** [driftyco/ionic#9977] opened 2017-01-12 06:40 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I have just enabled the service worker and it seems to be working just fine in the browser, but after I deployed to an Android device, I see the following:
```
DOMException: Failed to register a ServiceWorker: The URL protocol of the current origin ('file://') is not supported.
```
**Expected behavior:**

Service worker should work on a device.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by brandyscarney** [comment] 2017-01-12 15:36
Thanks for the issue! We'll look into this soon.

Note to team: see #9990 for more info.

**Comment by mhartington** [comment] 2017-01-12 15:45
This is actually by design. Chrome/Android blocks service workers from http or file protocols

https://github.com/electron/electron/issues/2831
https://bugreports.qt.io/browse/QTBUG-56169


https://www.w3.org/TR/2015/WD-service-workers-20150625/#security-considerations

**Comment by rolandjitsu** [comment] 2017-01-12 15:49
@mhartington Ok, so this means that it can only work in the browser? Or is there a way to make service workers work when the app is on a device?

I did read before that they only work with HTTPS protocols due to security concerns. But I also found some info about allowing to set a trusted origin (e.g. for chrome extensions).

**Comment by rolandjitsu** [comment] 2017-01-12 15:49
Or does Ionic also provide some API for adding trusted origins such as `registerURLSchemeAsAllowingServiceWorkers()`?

**Comment by mhartington** [comment] 2017-01-12 15:53
At the moment, service workers will only work in the browser, and through https.

`registerURLSchemeAsAllowingServiceWorkers` is a low level method when building a browser, so not something ionic is in charge of.

**Comment by rolandjitsu** [comment] 2017-01-12 15:55
I see. So apps cannot take advantage of this. That's quite unfortunate :|

**Comment by rolandjitsu** [comment] 2017-01-12 15:56
Yes, but maybe there is cordova plugin that can do this or ionic native plugin? That is what I mean.

**Comment by mhartington** [comment] 2017-01-12 16:02
it is something that has been brought up before in cordova talks. 
Not sure if a plugin would work, but maybe modifying the crosswalk webview could....

Either way, it's something that is known and cannot be handled by the framework.
Closing for now.

**Comment by remster** [comment] 2017-01-12 16:02
But isn't Ionic about mobile devices first and foremost?
Ionic advertises its support for service workers and with some pride: http://blog.ionic.io/tag/service-workers/
I've spent most of the day yesterday setting it all app for what turns out to be a disappointment.
Could Ionic make this clear somehow - as the comms are arguably misleading?
Service Workers are a very desirable feature - built with mobile devices in mind. I think it is in cordova's and Ionic (leading players in the field) to pursue this feature and bring it to the platform?

As a stopgap - and correct me if i'm wrong - service workers should work in ionic/cordova hosted app - where the app's code is served from a server on install (and possibly/smartly cached - with service workers).  Perhaps Ionic could provide a bootstrap setup (similar to https://ionicframework.com/getting-started/) for a hosted app where service workers can actually be taken advantage of..? Just an idea

**Closed by mhartington** 2017-01-12 16:02 UTC
Labels: v2

**Comment by rolandjitsu** [comment] 2017-01-12 16:06
I agree with @remster. That is the only reason I opened this issue, because it was advertised in blog posts. It could help to specify somewhere in the docs that currently, it is only supported in desktop browsers that support service workers.

**Comment by mhartington** [comment] 2017-01-12 16:10
@remster The service worker will work when running in chrome and as a web app. 

>Ionic advertises its support for service workers 

Yes because Ionic is just web technology, and there for can integrate service worker.
As for adding integration, I have noted in my last comment that it "may" be possible with crosswalk, but this issue is not the place to discuss that. 

We will add a note to the docs about how service worker is https only.

**Comment by remster** [comment] 2017-01-12 16:20
Thanks @mhartington , i would suggest adding a disclaimer to the generated code so it's plain and obvious, like this: ``<!-- un-comment this code to enable service worker (Note: doesn't work on mobile devices!'`

With respect to Ionic being just web technology. Ionic's [landing page](https://ionicframework.com/) says:

> The top open source framework for building amazing mobile apps.
Ionic is the beautiful, free and open source mobile SDK for developing native and progressive web apps with ease.

I'd like to add that service workers + hosted code have a potential of becoming the first class citizen as they open a very neat, single channel upgrade channel that bypasses app stores. Perhaps that serves to support my suggestion for a hosted app bootstrap/tutorial for a hosted app.

**Comment by mhartington** [comment] 2017-01-12 16:22
Will make a note of it!

**Comment by pavankumarkatakam** [comment] 2017-01-23 10:04
Im just thinking is it really necessary to implement service workers in ionic?

 What are the uses of service worker?
   1. Push notification.
   2. Network cache
   3. Background sync

 Ans:
   1. There is already native push notification plugin which can be more performant and styles than the web push protocol.
   2. I think we can create a wrapper around angular2 HTTP service to act as network cache like storing the requests and responses in the local storage and then use it if the app is online
   3. I don't know is there any implementation of background sync which will  be used to re play the requests that are stored in local storage.


But im looking for is there any framework or plugin to store the request and responses that are done automatically and use them when the app is offline.

**Comment by pavankumarkatakam** [comment] 2017-01-23 11:58
Continuation to my previous comment:-
  For point3, actually we can use this plugin http://ionicframework.com/docs/v2/native/network/ and handle the network connection and write a custom code for synchronize the requests/responses to server. But will the plugin work when the app is not in foreground.
