### ISSUE TITLE
Create test showcase/tutorial

### ISSUE THREAD

**Issue by godzsa** [driftyco/ionic#10126] opened 2017-01-21 14:09 UTC
**Ionic version:** 
[ x ] **2.x**

**I'm submitting a ...** 
[ x] feature request

Create a tutorial and a showcase on how to set up a testing environment for Ionic2 for both unit and E2E tests.

**Comment by brandyscarney** [comment] 2017-01-24 21:51
Thanks for the issue! I'm going to close this as a duplicate of #5331

**Closed by brandyscarney** 2017-01-24 21:51 UTC
