### ISSUE TITLE
bug: Scroll zooming still not working

### ISSUE THREAD

**Issue by ThorConzales** [driftyco/ionic#6788] opened 2016-06-07 11:11 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi,

I opened a issue long time ago #5707 regarding zooming not working for scroll component. Both of the issues related to that are closed and as of beta 8 it is still not working.</span>

<span is-issue-template></span>

**Comment by rachelxi** [comment] 2016-07-07 04:04
Still not working on beta 10 released on 27/06

**Comment by jgw96** [comment] 2017-05-02 16:07
Hello all, thanks for using Ionic! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/5701

**Closed by jgw96** 2017-05-02 16:07 UTC
Labels: v2

**Comment by KevRyan2** [comment] 2017-05-10 03:05
@jgw96 it doesn't look like there's a resolution to this issue in #5701 , can you please provide some clarification on the solution for this?
