### ISSUE TITLE
bug: ion-tab with ng-repeat

### ISSUE THREAD

**Issue by pablozandona** [driftyco/ionic#3915] opened 2015-06-10 17:37 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description> In my controller I have a array to create the tabs on view:

```
    $scope.categorys = [{
      name: 'fragrances',
      icon: 'ion-star'
    }, {
      name: 'skincare',
      icon: 'ion-star'
    }, {
      name: 'hair',
      icon: 'ion-star'
    }];

```

And ion-tab with ng-repeat of categorys:

```
  <ion-tabs class="tabs-striped tabs-top tabs-background-dark tabs-color-light">
    <ion-tab ng-repeat="(i, tab) in categorys" icon-on="{{tab.icon}}" icon-off="ion-star">
      test - {{tab}} - {{i}}
    </ion-tab>
  </ion-tabs>
```

It render 3 tabs, ok. But in the test it ever print the first element of array and doesn't change the content when a new tab is selected.

 </span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-06-10 17:37
Greetings @pablozandona!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3915). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3915)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment] 2015-06-10 17:50
Greetings @pablozandona!

My sensors indicate that I require more information in order to assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this happen occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com), where many humans will be able to offer wisdom and advice.

Thank you for allowing me to assist you.

<span ionitron-needs-reply></span>

**Comment by giorgiofellipe** [comment] 2015-06-14 16:08
+1
The same happens to me, maybe there could be a workaround but I didn't find one.

What I've got: http://play.ionic.io/app/9e00611b9072
Expected: http://play.ionic.io/app/74b75e0e9a9a

Navigate between tabs to see that the content isn't displayed correctly.

**Comment by zodiacsoulmate** [comment] 2015-07-07 03:49
I'm having the same problem... i have to hard code all tab view to avoid it right now, not sure if there is any work around...
Shor problem description : The ng-repeat inside ion-tab will multiply randomly, and previous tab will become a complete white page(no content nothing) after switching to other tab can navigate back.

**Comment by Ionitron** [comment] 2015-07-10 19:01
Greetings @pablozandona!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment] 2015-07-10 19:01
Greetings @pablozandona!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-07-10 19:01 UTC
Labels: ionitron:closed

**Comment by jslag** [comment] 2015-09-02 21:51
I'm seeing what appears to be the same problem.

**Comment by mhartington** [comment] 2015-09-02 22:12
It makes sense why. Since the tabs need to go through ng-repeat to get created, they miss being selected. 

Work around is to manually select the tabs in the controller.

http://play.ionic.io/app/d3fdb264cb54

This is probably something though that we won't fix. Just a heads up.

**Comment by jslag** [comment] 2015-09-02 22:28
is that sample supposed to be working properly with the added `$ionicTabsDelegate.select(0);`? I'm still seeing the same buggy behavior.

Looks like there are a number of people running into this. If it's not fixable, would it make sense for the ion-tabs doc to get a warning that the tabs have to be defined statically?

**Comment by mhartington** [comment] 2015-09-03 14:13
Ahh, alright, I see what you mean. Yeah, this is a tough one. I though it was just the tab not being selected, but it's a bit more than that. While the tabs are repeated with ng-repeat, the actual content the inside is not. That's where the issue is. 

It comes down to how tabs get rendered, which would require a big change to fix. At the moment, I don't think we'd be able to fix this. I'll add a note to the docs.

**Comment by jslag** [comment] 2015-09-03 14:18
That should help. Thanks!

**Comment by fantasybei** [comment] 2015-09-11 03:48
meet exact the same problem. +1

**Comment by gregor-srdic** [comment] 2016-01-05 07:52
+1

**Comment by vinaylakkam** [comment] 2016-01-05 14:00
+1

**Comment by webinfopro** [comment] 2016-01-15 15:04
+1

**Comment by forest2087** [comment] 2016-02-06 04:20
+1

**Comment by julio-coelho** [comment] 2016-02-29 18:20
+1

**Comment by digows** [comment] 2016-03-02 00:19
+1 please!
