### ISSUE TITLE
[version 1.2.4] $ionicScrollDelegate not work on android #5629

### ISSUE THREAD

**Issue by njleonzhang** [driftyco/ionic#5896] opened 2016-03-21 08:51 UTC
#### Short description of the problem:
$ionicScrollDelegate.resize does not work on android

#### What behavior are you expecting?
I have a directive which can change the height a lot, in this situation,  $ionicScrollDelegate.resize() is needed. it can work with ios with ionic 1.1.1, but if I update ionic to version after 1.1.1. it can not work on android.

I can not reproduce this issue in web browser, so I can not provide a reproduce codepen.
So I will post my reproduce steps as clear as possible:

## 1. create a ionic project with blank template. 
```
ionic start test blank
```
## 2. create a directive with following template and js.

Directive html:
```
<style>
  .arrow-container {
    border-top: solid 1px #e9e9e9;
    border-bottom: solid 1px #e9e9e9;
  }

  .arrow-container p {
    margin-bottom: 0;
  }

  .arrow_up {
    height: 20px;
    width: 20px;
    background-image: url("./img/arrow_up.png");
    background-size: contain;
    background-repeat: no-repeat;
  }

  .arrow_down {
    height: 20px;
    width: 20px;
    background-image: url("./img/arrow_down.png");
    background-size: contain;
    background-repeat: no-repeat;
  }

  .card_button {
    width: auto;
    float: right;
    margin: 5px;
    font-size: 14px;
  }

  .item-list-title:before, .item-list-title:after {
    content: '';
    height: 1px;
    background-color: #E9E9E9;
    -webkit-box-flex: 1;
    -webkit-flex: 1;
    -moz-box-flex: 1;
    -moz-flex: 1;
    -ms-flex: 1;
    flex: 1;
    display: block;
    -webkit-align-self: center;
    -moz-align-self: center;
    -ms-flex-item-align: center;
    align-self: center;
    width: 100%;
    -webkit-box-flex: 0;
    -webkit-flex: 0 0 40%;
    -moz-box-flex: 0;
    -moz-flex: 0 0 40%;
    -ms-flex: 0 0 40%;
    flex: 0 0 40%;
    max-width: 40%;
  }

  .product-list {
    padding-bottom: 0;
  }

  .product-list-item {
    border-bottom: 1px #E9E9E9 solid;
  }

  .product-list div:last-child {
    border-bottom: 0;
  }

  .p5 {
    padding: 5px;
  }

</style>

<div class="card">
  <div class="item item-divider">
    <span>install</span>
  </div>

  <div class="row row-top">
    <div class="col col-35 col-top">
      <span>name</span>
    </div>
    <div class="col col-top">
      <span>{{ job.customer_name }}</span>
    </div>
  </div>

  <div class="row row-top">
    <div class="col col-35 col-top">
      <span>tel</span>
    </div>
    <div class="col col-top">
      <a href="tel:{{ job.customer_phone }}">{{ job.customer_phone }}</a>
    </div>
  </div>

  <div class="row row-top">
    <div class="col col-35 col-top">
      <span>address</span>
    </div>
    <div class="col col-top">
      <span>{{ job.district }}/{{ job.customer_address }}</span>
    </div>
  </div>

  <div class="row row-top" ng-if="job.flow_type !== 'sale'">
    <div class="col col-35 col-top">
      <span>model</span>
    </div>
    <div class="col col-top">
      <span>{{ job.product_info }}</span>
    </div>
  </div>

  <div ng-if="data.showDetail">

      <div class="row row-top">
        <div class="col col-top col-35">appointment_date</div>
        <div class="col col-top">
          <span id="appointment_date">{{ job.appointment_date }}</span>
        </div>
      </div>
      <div class="row row-top">
        <div class="col col-top col-35">assigner</div>
        <div class="col col-top">
          <span>{{ job.assigner }}</span>
        </div>
      </div>
      <div class="row row-top">
        <div class="col col-top col-35">assign_time</div>
        <div class="col col-top">
          <span>{{ job.assign_time }}</span>
        </div>
      </div>

    <div class="row row-top">
      <div class="col col-top col-35">remark</div>
      <div class="col col-top">
        <span>{{ job.remark }}</span>
      </div>
    </div>

    <div class="row row-top">
      <div class="col col-top col-35">state</div>
      <div class="col col-top">
        <span id="state">{{ job.state }}</span>
      </div>
    </div>

      <div class="items-container p5">
        <div class="item-list-title row row-center">
          <p class="col content-center p-without-margin">list</p>
        </div>

        <div class="product-list p5">
          <div class="product-list-item"
               ng-repeat="item in job.items">
            <div class="row row-top">
              <div class="col col-top col-20">name</div>
              <div class="col col-top">
                <span id="state">{{ item.item.name }}</span>
              </div>
            </div>
            <div class="row row-top">
              <div class="col col-top col-20">count</div>
              <div class="col col-top">
                <span id="state">{{ item.count }}</span>
              </div>
            </div>
          </div>
        </div>
      </div>
  </div>

  <div class="content-center arrow-container" ng-click="jobCardToggle()">
    <div class="be-center arrow"
         ng-class="{'arrow_down': !data.showDetail, 'arrow_up': data.showDetail}"></div>
    <p class="text-center">{{arrowTip}}</p>
  </div>

  <div class="button_container">
      <button class="button button-small button-positive card_button"
              ng-if="!job.can_accept" ng-click="handle(job)">
        handle
      </button>
  </div>
</div>
```

Directive js:

```
angular.module('jobCard', [])

  .directive('jobCard', function ($ionicScrollDelegate, $timeout) {
    return {
      restrict: 'AE',

      scope: {
        job: '=',
      },

      templateUrl: 'js/jobCard/jobCard.html',

      link: function (scope, elem, attr) {

        scope.data = {};
        scope.data.showDetail = false;
        scope.arrowTip = 'show';

        scope.jobCardToggle = function () {
          scope.data.showDetail = !scope.data.showDetail;
          if (scope.data.showDetail) {
            scope.arrowTip = 'hide';
          } else {
            scope.arrowTip = 'show';
          }

          $timeout(function () {
            $ionicScrollDelegate.resize();
          }, 0);
        };
      }
    }
  });
```
## 3.  add following code to index.html 

```
<body ng-app="test">

<ion-content class="has-header">
  <job-card></job-card>
  <job-card></job-card>
  <job-card></job-card>
  <job-card></job-card>
</ion-content>
```

## 4. add android project and run the app in Genymotion simulation "Motorola Moto X - 4.3".
Click one of the "show" button in the cards, which will make the card become higher.

##expected result: The height of scroll bar should updated correctly. 
##real result: The height of scroll bar doesn't update.
 
PS: 
1. if I roll back ionic to 1.1.1, the issue can not reproduce.
2. if I change android version to 4.2 or 6.0, the issue can not reproduce.

A strange issue, I am not sure if I have described clearly, if not, please let me know.

**Comment by danbucholtz** [comment] 2016-04-07 15:05
@njleonzhang, are you able to use crosswalk?  That might resolve the issue.

**Comment by njleonzhang** [comment] 2016-04-11 05:51
@danbucholtz, we can not use crosswalk, it is too heavy for us.
Can you reproduce our issue according to my description？

**Comment by danbucholtz** [comment] 2016-04-11 22:03
@njleonzhang, everything seems to be working fine for me with Android 4.4 and the latest Ionic.  I am running your app/code but I don't see any issues with scrolling.  I am clicking the show buttons to resize the app.

Can you check if this is still any issue with the latest Ionic?  Can you provide a codepen that I can observe this issue in?

Thanks,
Dan

**Comment by njleonzhang** [comment] 2016-04-13 08:38
@danbucholtz, I have claimed:

1. issue occur when I run the app in Genymotion simulation "Motorola Moto X - 4.3". 
2. The ionic I uses is 1.2.4. If I roll back ionic to 1.1.1, the issue can not reproduce.
3. If I change android version to 4.2 or 6.0, the issue can not reproduce.

I can also reproduce this issue on a physical device whose OS is android 4.3. so it seems the issue only occur on android 4.3 with ionic higher than 1.1.1

**Comment by jgw96** [comment] 2016-04-13 15:17
Hello! So I have tested on my Android devices to see if I can reproduce on any other versions of Android. I tested on a Nexus 7 running 6.0.1, a Nexus 6 running the Android N dev preview and a moto x 2014 running Android 5.1. And was not able to reproduce this issue. It seems as if the issue only happens on a single version of Android, 4.3. Is the reason you didn't want to use crosswalk because it made your apk's bigger? I definitely understand that concern but I think that the better html5 support, the consistency it provides on older versions of Android like 4.3, and the pretty massive performance increases it gives you on older versions of Android outweight the increase in apk size. I'd love to hear your thoughts on this (: thanks

**Comment by njleonzhang** [comment] 2016-04-14 08:12
@jgw96 Yeah, it seems a issue only on android 4.3 with ionic after 1.1.1. 
As you mentioned, the size increasing brought by crosswalk is our concern. 
Our APK is about 4Mb, but if we use crosswalk, it may become about 25Mb(I forget the precise value), it is too big for us. 
"better html5 support, the consistency and pretty massive performance", hummmm, sounds great. we will consider it. but currently, it is better if you can fix this issue. 
I think you should be able to reproduce this issue following the steps I described.
use "Genymotion simulation "Motorola Moto X - 4.3" to run the app.

**Comment by jgw96** [comment] 2016-04-21 16:22
@njleonzhang Hello! So unfortunately because this issue only happens on a certain older version of android (4.3) and cannot be reproduced on any version of android that is newer i do not think this is a fix that we can put into the framework as it may break something with newer versions of Android. We do recommend that our users use crosswalk for any version of android before 4.4.4 as the android webview before 4.4.4 is very fragmented. I understand fully that this can be frustrating, but the good thing is that android 4.3 only has a 3% (http://developer.android.com/about/dashboards/index.html) market share at this point (in fact, the moto x device you are emulating with in Genymotion received updates all the way to Android 5.1.1 if im not mistaken) and this will only get better as newer android devices and newer versions of Android come out. Thanks for using Ionic! And feel free to continue to open issues with us in the future! I am going to close this issue, but please feel free to comment back.

**Closed by jgw96** 2016-04-21 16:22 UTC
Labels: header, platform:android, v1

**Comment by njleonzhang** [comment] 2016-04-22 05:52
@jgw96 I am sorry to get this response. Anyway, thanks to your effort. In addition, if possible, would you please add this issue to your known issue list, so that other developers can be aware of it.
