### ISSUE TITLE
Inconsistent behaviour for ngModelChange and ion-list 

### ISSUE THREAD

**Issue by urshofer** [driftyco/ionic#11026] opened 2017-04-03 10:41 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

    <ion-list (ngModelChange)="func()">
      <ion-item>
       <ion-input [(ngModel)]="value" value="value"></ion-input>
      </ion-item>
      <ion-item>
       <ion-input [(ngModel)]="value2" value="value2"></ion-input>
      </ion-item>
    <ion-list>

**Expected behavior:**

`func()` should be called  on model changes of all child elements.

While this happens in chrome, in safari it does not...

**Comment by jgw96** [comment] 2017-04-03 19:00
Hello, thanks for using Ionic! Does this also happen with a plain angular app? Are there any errors thrown? Also, would you mind sharing a repo we can use to reproduce this issue?

**Comment by jgw96** [comment] 2017-04-14 15:35
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-04-14 15:35 UTC
Labels: needs info, v2
