### ISSUE TITLE
Android soft keyboard hides the input field in bottom screen

### ISSUE THREAD

**Issue by dheran** [driftyco/ionic#6054] opened 2016-04-06 10:59 UTC
** Ionic v2 **

Android soft keyboard hides the input filed in the bottom of the screen. Need to scroll to bottom manually. But when I commented the `app.bundle.js` like below, It works fine and last input field automatically pulled up when I focus it.

```
<body>

  <!-- this Ionic's root component and where the app will load -->
  <!--<ion-app></ion-app>-->
  
  <div style="height:40px"><input type="text"/></div>
  <div style="height:40px"><input type="text"/></div>
  <div style="height:40px"><input type="text"/></div>
  <div style="height:40px"><input type="text"/></div>
  <div style="height:40px"><input type="text"/></div>
  <div style="height:40px"><input type="text"/></div>
  <div style="height:40px"><input type="text"/></div>
  <div style="height:40px"><input type="text"/></div>
  <div style="height:40px"><input type="text"/></div>
  <div style="height:40px"><input type="text"/></div>
  <div style="height:40px"><input type="text"/></div>
  <div style="height:40px"><input type="text"/></div>
  <div style="height:40px"><input type="text"/></div>

  <script src="cordova.js"></script>
  <!--<script src="build/js/app.bundle.js"></script>-->
</body>
```

**Comment by jgw96** [comment] 2016-04-06 14:21
Hello! Thanks for opening an issue with us! So, I'm a little confused on your issue. If you comment out that app.bundle.js script then your Ionic app isn't going to work at all, as that JavaScript file has all your components and everything built into it, so when you loaded your app it would just be a blank white screen. By chance, would you be able to provide a codepen that I can use to repro the issue? That would be easier because then I would be able to see the issue with my own eyes. Thanks again!

**Comment by dheeran1** [comment] 2016-04-06 15:16
Actually real issue is, I add a html `<textarea> `in my template, which is in the bottom of all.
When I tap into the `textarea `from android browser, the keyboard hides the `textarea` which is not the default behavior of android chrome. When I build the same page with raw html and javascript, page pops up as expected. 
It seems issue with ionic library.

**Comment by adamdbradley** [comment] 2016-04-06 15:28
Can you use ion-textarea instead? Additionally, all of ionic's markup should be within templates that ng2 will insert into ion-app. So there shouldn't be any HTML written outside of ion-app in the index.html file.

**Comment by dheeran1** [comment] 2016-04-07 05:15
Forget about the above snippet.

I opted `<textarea>` instead of `<ion-textarea>` because of this issue (https://github.com/driftyco/ionic/issues/6052)

**Comment by jgw96** [comment] 2016-05-09 21:50
Hello @dheran ! Are you still having this issue? If so can your provide a plunker that i can use to reproduce this issue with please? Thanks!

**Comment by JumBay** [comment] 2016-05-10 02:07
I can confirm the issue. When an input get focused, the keyboard shows up and hide a part of the view. If your input is part of it, the user will have to scroll to it as you can see: 

![ionic_bug_input](https://cloud.githubusercontent.com/assets/216573/15133458/32f9601a-16a6-11e6-970a-ed954044cb65.gif)

The best behavior should be like natives app do, i.e. move the entire page like that: 

![ionic_normal_keyboard_behavior](https://cloud.githubusercontent.com/assets/216573/15133557/37438e6a-16a7-11e6-8dc6-9140db1f3e68.gif)

**Comment by matheo** [comment] 2016-06-04 18:23
+1
This issue is bothering us too :(

**Comment by mpaland** [comment] 2016-06-10 21:02
+1
Seeing the same issue on Moto G2 Android 6.0 device. Tried different things (see my [forum post](https://forum.ionicframework.com/t/android-virtual-keyboard-problems-any-best-practices/54482?u=mpaland)) but no luck.
Virtual keyboard seems a bugging issue on both ios and Android.

**Comment by Ionitron** [comment] 2016-06-10 21:02
Greetings @dheran!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment] 2016-06-10 21:02
Greetings @dheran!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by jgw96** [comment] 2016-08-09 16:10
Hello all! Closing this as a duplicate of https://github.com/driftyco/ionic/issues/5432. Thanks for using Ionic!

**Closed by jgw96** 2016-08-09 16:10 UTC
Labels: ionitron:closed, keyboard, platform:android, v2

**Comment by mokupindia** [comment] 2017-10-05 06:28
Still facing this issue in Ionic 3.7 (Android) as defined in animated gif by @JumBay was there a solution for it?

**Comment by ATakaSKY** [comment] 2017-10-25 19:14
I am having the same issue on android. @ghost

**Comment by husnaingoldev** [comment] 2017-11-30 05:57
I am having the same issue still on Android
@ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

cordova (Cordova CLI) : 7.1.0 

@ionic/app-scripts : 3.1.0
    Cordova Platforms  : android 6.3.0 ios 4.5.3
    Ionic Framework    : ionic-angular 3.9.2

Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    ios-sim           : 5.0.13 
    Node              : v6.11.0
    npm               : 5.5.1 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.0 Build version 9A235

**Comment by hmsoftware** [comment] 2017-12-01 14:20
+1

**Comment by teju24** [comment] 2017-12-15 06:25
i m facing same issue. any solution??

**Comment by kennedymca** [comment] 2017-12-18 13:17
i am facing the same issue

**Comment by manikandan07081995** [comment] 2018-02-23 09:44
I need virtual keyboard for ionic browser application.Can any one help me.I am using typescript for ionic development.

**Comment by manikandan07081995** [comment] 2018-02-23 09:45
For kiosk mode

**Comment by mat90c** [comment] 2018-03-01 09:10
+1
ionic: 3.19.1
