### ISSUE TITLE
bug: ion-side-menu-content does not adjust switching portrait/landscape mode

### ISSUE THREAD

**Issue by beatgrabe** [driftyco/ionic#5214] opened 2016-01-27 16:06 UTC
My application does not adjust the `ion-side-menu-content` while switching between portrait and landscape mode. I could observe this issue running the application on an iPad with `expose-aside-when="large"` with an permanent open `ion-side-menu`. So starting the application in landscape keeps my content `width` on portrait mode, but it should be decreased. Starting in portrait mode and switching to landscape should increase the `width` of `ion-side-menu-content`. Apparently it does not work!

Futher information:
**ionic**: 1.2.4.
**cordova**: 5.4.1
**cordova-ios**: 3.9.2

**Viewport:**

```
<meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width"/>
```

**Comment by lordgreg** [comment] 2016-01-27 22:25
I'm having the same issue. What I'll currently do is, watch on resize or rotation event, and manually recalucalte ion-content where I find ion-side-menu-content.

**Comment by beat-at-hartwig** [comment] 2016-01-28 12:03
Nice hint! That's what i have done so far:

    window.addEventListener( "orientationchange", recalculateWidth );
    function recalculateWidth( event ) {
        var amount = parseInt( angular.element( "ion-side-menu" )[ 0 ].style.width, 10 );
        var total = parseInt( window.innerWidth, 10 );
        angular.element( "ion-side-menu-content" )[ 0 ].style.width = total - amount + "px";
    }

**Comment by lordgreg** [comment] 2016-02-01 13:05
@beat-at-hartwig - just updated your code a bit. When switching different sites with such a content, you can have more than one ion-side-menu-content. That's why I suggest you create .length variable and use the for loop and update the width of all occurrences of ion-side-menu-content that you find.

:+1:

**Comment by EzheG** [comment] 2016-02-19 12:15
+1

**Comment by leonardobazico** [comment] 2016-03-30 23:19
+1

**Comment by leonardobazico** [comment] 2016-03-31 00:16
+1

**Comment by GenesioValois** [comment] 2016-04-07 14:08
+1

**Comment by felly** [comment] 2016-04-07 19:43
Maybe a duplicate of #4898?

**Comment by beat-at-hartwig** [comment] 2016-04-08 07:08
Good to know. Have not seen it yet. Thanks. I will give it a try!

**Comment by beatgrabe** [comment] 2016-07-21 07:44
Can be closed due to fixes and merges in  [#4908](https://github.com/driftyco/ionic/pull/4908) and [#4898](https://github.com/driftyco/ionic/issues/4898)!

**Closed** 2016-07-21 14:08 UTC
Labels: css, menus, v1
