### ISSUE TITLE
bug: Bug: When using side menu the statusbar pushed the header bar down

### ISSUE THREAD

**Issue by ramshengale** [driftyco/ionic#4731] opened 2015-12-07 13:02 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>When I'm using side menu setup with tabs at bottom, the status bar pushes the header bar down.

See the images below:

<img src="https://cloud.githubusercontent.com/assets/7523464/11627452/5a20005a-9d10-11e5-841f-8666f8764832.PNG" width="200">

On inspecting the HTML I found the following CSS code to be the culprit:

.platform-ios.platform-cordova:not(.fullscreen) .bar-header:not(.bar-subheader)>*{
margin-top: 20px;
}

It's giving the top margin to everything including the two active and cached "nav-bar-block" divs. I was able to solve it by adding the following custom CSS:

.platform-ios.platform-cordova:not(.fullscreen) .bar-header:not(.bar-subheader) > div.nav-bar-block{
margin-top: 0px;
}

<img src="https://cloud.githubusercontent.com/assets/7523464/11627451/5a1fbd20-9d10-11e5-9666-3b1ece5c5f8c.PNG" width="200">

Please let me know if this is a correct way to do it and this was a bug or if I did something wrong somewhere else that's pushing the header bar down?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-12-07 13:02
Greetings @ramshengale!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4731). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4731)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by jgw96** [comment] 2016-03-14 20:06
Hello! Thanks for opening an issue with us, we just need a little more info from you so that we can better help you with your issue. Would you mind posting a code sample, plunkr or codepen that we can use to reproduce your issue? Also, would you mind running `ionic info` and posting the output? Thanks again!

**Comment by jgw96** [comment] 2016-03-21 19:49
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!

**Closed by jgw96** 2016-03-21 19:49 UTC
Labels: css, v1

**Comment by barocsi** [comment] 2016-04-01 15:14
Still a bug.
