### ISSUE TITLE
ion-range doesn't display unless within ion-item (as a custom component)

### ISSUE THREAD

**Issue by gslender** [driftyco/ionic#11734] opened 2017-05-20 07:51 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[ ] **2.x**
[X ] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I'm creating a custom component that has a special handling for ion-range, but when nested inside a component it won't display unless I include the ion-item to surround the ion-range.

**Expected behavior:**
I expected that I could include a ion-range like a button, or ion-card inside a component without needing a special item to wrap/contain the ion-range - this means my implementation of the component needs to not be inside a ion-item when I use my component (which is odd compared to other ion-xyz items)

**Steps to reproduce:**
Bit involved to include a plunker type snippet - how would I do that for component bugs??

**Related code:**
```
none
```

**Other information:**
none

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.1.2
    Ionic CLI        : 3.1.2

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-ionic-angular : 1.1.2
    Ionic Framework                 : ionic-angular 3.2.1

System:

    Node       : v6.9.2
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 

```

**Comment by gslender** [comment] 2017-05-20 07:54
might be related to this bug #10599

**Comment by gslender** [comment] 2017-05-20 07:55
this bug/issue seems almost exactly related, but not sure ?? #9080

**Comment by jgw96** [comment] 2017-05-22 15:10
Hello, thanks for using Ionic! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/10599.

**Closed by jgw96** 2017-05-22 15:10 UTC
