### ISSUE TITLE
console undefined in prod

### ISSUE THREAD

**Issue by frankkoenigstein** [driftyco/ionic#11269] opened 2017-04-19 11:49 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
`console` is undefined in production mode.

**Expected behavior:**
`console` should not be `undefined`.

**Steps to reproduce:**

I have an angular provider from a library for logging that I want to configure:
```ts
import { InjectionToken } from "@angular/core";
import { ILogger, LoggingService, Logtype } from "somelib";

export const LOG_CONFIG = new InjectionToken<ILoggingConfig>("log.token");
export interface ILoggingConfig {
  logger: ILogger;
  loglevel?: Logtype;
}

export function loggingServiceFactory(config: ILoggingConfig) {
  return new LoggingService(config.logger, [], config.loglevel);
};

export const loggingServiceProvider = {
  deps: [LOG_CONFIG],
  provide: LoggingService,
  useFactory: loggingServiceFactory
};
```

This lib is added via `npm i somelib` and configured in my app module:
```ts
import { IDB_LOG_CONFIG, ILoggingConfig } from "somelib";

export const LOG_DI_CONFIG: ILoggingConfig = {
    logger: console
};

@NgModule({
    bootstrap: [IonicApp],
    imports: [
        IonicModule.forRoot(App),
        BrowserModule,
        FormsModule,
        HttpModule,
        SomelibModule
    ],
    providers: [
        {provide: LOG_CONFIG, useValue: LOG_DI_CONFIG}
    ]
})
export class AppModule {
}
```

When I run `ionic run android --prod` `console` is `undefined` in my logging service.
Whereas when I configure
```ts
export const LOG_DI_CONFIG: ILoggingConfig = {
    logger: "foobar"
};
```

*foobar* is injected into my service.

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.3
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.10.1
Xcode version: Not installed

```

**Comment by AmitMY** [comment] 2017-04-19 12:02
Might be the same as: https://github.com/angular/angular/issues/15833
can you constantly reproduce?

**Comment by frankkoenigstein** [comment] 2017-04-19 12:36
Looks quite similar. I can constantly reproduce.

**Comment by jgw96** [comment] 2017-04-24 16:28
Hello, all! As this seems like more of an Angular issue I am going to close this issue as a duplicate of the one @AmitMY linked to above for the moment.

**Closed by jgw96** 2017-04-24 16:28 UTC
Labels: v2
