### ISSUE TITLE
bug: ion-tabs + static content + maxCache(0) => blank tab

### ISSUE THREAD

**Issue by jossef** [driftyco/ionic#3612] opened 2015-04-25 06:20 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

### http://codepen.io/Jossef/pen/aOzzQo?editors=101

![proff](https://cloud.githubusercontent.com/assets/1287098/7331870/f3fd997c-eb2b-11e4-9155-6134b0a7bd4a.gif)

```js
.config(function ($ionicConfigProvider) {
    $ionicConfigProvider.views.maxCache(0);
  })
```

```
<script id="templates/tabs.html" type="text/ng-template">
      <ion-tabs class="tabs-icon-top tabs-positive">
        
        <ion-tab title="About" icon="ion-ios-information" href="#/tab/about">
          <ion-nav-view name="about-tab"></ion-nav-view>
        </ion-tab>


        <ion-tab title="static-ion-view" icon-on="ion-ios-home" icon-off="ion-ios-home-outline">
          <ion-view view-title="Tab 3: Page 1">
            <ion-content padding="true">
              <h2>Tab 3: Page 1</h2>
              <p>Hello. I am static content nto wrapped with an ion-nav-view.</p>
            </ion-content>
          </ion-view>
        </ion-tab>
        
        <ion-tab title="Contact" icon="ion-ios-world" ui-sref="tabs.contact">
          <ion-nav-view name="contact-tab"></ion-nav-view>
        </ion-tab>

      </ion-tabs>
    </script>
```

**Comment by Ionitron** [comment] 2015-04-25 06:20
Greetings @Jossef!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3612). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3612)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by philinheaven** [comment] 2015-06-08 14:14
is this bug fixed? or i can fix this?

**Comment by Jossef** [comment] 2015-06-08 18:36
Nope. Please do

**Comment by samoka** [comment] 2015-06-09 10:30
@philinheaven  Please can you post the fix?

**Comment by philinheaven** [comment] 2015-06-10 15:52
Do You want to have the maxcache config?

**Comment by samoka** [comment] 2015-06-10 16:41
I want to use maxCache(0).

**Comment by samoka** [comment] 2015-06-18 17:56
Any update on this yet? still can't use maxCache(0).

**Comment by dsenatore** [comment] 2015-07-10 12:16
Same problem here! Maybe worse... i have an app with side menu and many pages. Two of these are "tabs pages". If I enable the cache, the first tab view that i visit remains cached and from then, even if i navigate to another "tabs page" the app visualizes the cached one (please note that the url is correct). Even worse, $stateParams is cached too and in event $ionicView.enter i have ever the same value (the parameter cached with the first view). The problem is related with: https://github.com/driftyco/ionic/issues/3884

Please fix it as soon as possible because it is really a show stopper!

**Comment by fairsayan** [comment] 2015-08-09 22:53
I found a workaround: instead of
```javascript
<ion-tabs class="tabs-icon-only tabs-balanced">
  <ion-tab title="info" icon="ion-information-circled" ng-href="#/group/{{id}}/info">
    <ion-nav-view name="info"></ion-nav-view>
  </ion-tab>

  <ion-tab title="members" icon="ion-ios-people" ng-href="#/group/{{id}}/info">
    <ion-nav-view name="members"></ion-nav-view>
  </ion-tab>

  <ion-tab title="schedule" icon="ion-calendar" ng-href="#/group/{{id}}/info">
    <ion-nav-view name="schedule"></ion-nav-view>
  </ion-tab>

  <ion-tab title="categories" icon="ion-ios-list-outline" ng-href="#/group/{{id}}/info">
    <ion-nav-view name="resourceCategories"></ion-nav-view>
  </ion-tab>
  
</ion-tabs>
```

I write:
```javascript
<ion-tabs class="tabs-icon-only tabs-balanced">
  <ion-tab title="info" icon="ion-information-circled" ng-click="goTab('info')">
    <ion-nav-view name="info"></ion-nav-view>
  </ion-tab>

  <ion-tab title="members" icon="ion-ios-people" ng-click="goTab('members')">
    <ion-nav-view name="members"></ion-nav-view>
  </ion-tab>

  <ion-tab title="schedule" icon="ion-calendar" ng-click="goTab('schedule')">
    <ion-nav-view name="schedule"></ion-nav-view>
  </ion-tab>

  <ion-tab title="categories" icon="ion-ios-list-outline" ng-click="goTab('resourceCategories')">
    <ion-nav-view name="resourceCategories"></ion-nav-view>
  </ion-tab>
  
</ion-tabs>
```

I kept the usual config:
```javascript
  .state('groupTabs', {
    parent: 'leftMenu',
    url: "/group/:id",
    controller: 'GroupTabsCtrl',
    abstract: true,
    templateUrl: "templates/groupTabs.html"
  })

  .state('groupTabs.info', {
    url: "/info",
    views: {
      'info': {
        controller: 'GroupInfoCtrl',
        templateUrl: "templates/groupInfo.html"
      }
    }
  })

  .state('groupTabs.members', {
    url: "/members",
    views: {
      'members': {
        controller: 'GroupMembersCtrl',
        templateUrl: "templates/groupMembers.html"
      }
    }
  })

  .state('groupTabs.schedule', {
    url: "/schedule",
    views: {
      'schedule': {
        controller: 'GroupScheduleCtrl',
        templateUrl: "templates/groupSchedule.html"
      }
    }
  })

  .state('groupTabs.resourceCategories', {
    url: "/resourceCategories",
    views: {
      'schedule': {
        controller: 'GroupResourceCategoriesCtrl',
        templateUrl: "templates/groupResourceCategories.html"
      }
    }
  })
```

I defined the goTab method as:
```javascript
GroupModule.controller('GroupTabsCtrl', function ($scope, $stateParams, $state) {
  $scope.id = $stateParams.id;
  $scope.goTab = function (el) {
    $state.go('groupTabs.' + el, $stateParams);
  };
});
```

**Comment by s2young** [comment] 2015-08-18 20:36
+1

**Comment by s2young** [comment] 2015-08-18 20:50
Though I did solve my immediate issue by just setting maxCache(1).  It allows the tabbed view to work, while not caching the previous view.

**Comment by samoka** [comment] 2015-10-20 13:25
So i'm guessing there's still no fix for this?

**Comment by mlynch** [comment] 2015-12-10 00:21
Will be fixed in v2

**Closed** 2016-04-21 17:26 UTC
Labels: navigation

**Comment by azachar** [comment] 2017-01-31 12:20
Hey Guys, how about project that are already written in ionic 1, do you think it is easy to migrate them? 
This bug really makes e2e testing terrible hard. I am unhappy how many bugs it has... really said.
