### ISSUE TITLE
perf: UI gets stuck between 2 views when pressing the back button

### ISSUE THREAD

**Issue by sclearion** [driftyco/ionic#4734] opened 2015-12-07 19:49 UTC
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Having issue where the ui gets stuck between 2 views when pressing the back button. Any idea what could be causing this. Im not connecting to any DB and only using static json sample data to layout this app, no special mods to ionic. It only happens on ipod and iphones. see image. sorry or the orientation
![20151207_134427](https://cloud.githubusercontent.com/assets/10091131/11637796/3562452e-9ce9-11e5-9d9d-204268cfcdfc.jpg)

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-12-07 19:49
Greetings @sclearion!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4734). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4734)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Stephenradams** [comment] 2015-12-09 13:02
I also have this problem on an app I'm working on. I think the problem is related to a digest issue with the Angular code I've written in the view where this issue occurs.

**Comment by crouti** [comment] 2015-12-14 15:22
Same here, also, quite often, pressing Back or switching to another view from menu displays the wrong view, like if a stack was not acting correctly, and after 2 or 3 tries, the correct view displays... Any idea ?
thank you

**Comment by jgw96** [comment] 2016-03-14 20:05
Hello! Thanks for opening an issue with us, we just need a little more info from you so that we can better help you with your issue. Would you mind posting a code sample, plunkr or codepen that we can use to reproduce your issue? Also, would you mind running `ionic info` and posting the output? Thanks again!

**Comment by jgw96** [comment] 2016-03-21 19:48
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!

**Closed by jgw96** 2016-03-21 19:48 UTC
Labels: navigation, v1

**Comment by crouti** [comment] 2016-03-22 08:11
yes sure, thank you

2016-03-21 20:50 GMT+01:00 Justin Willis <notifications@github.com>:

> Hello! Thanks for opening an issue with us! Since it has been a little
> while since there was any activity on this issue i will be closing it, but
> feel free to reopen this issue if needed!
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ionic/issues/4734#issuecomment-199446425>
>



-- 
Max UNGER
06.66.13.16.26

www.termel.fr
