### ISSUE TITLE
Super lag when switching between tabs, pages and segments on iOS

### ISSUE THREAD

**Issue by MrBokeh** [driftyco/ionic#5772] opened 2016-03-09 00:35 UTC
#### Short description of the problem:
Super lag when switching between tabs, segments and pages on iOS

#### What behavior are you expecting?
Zero lag when switching between tabs, segments and pages on iOS

**Steps to reproduce:**
1. install the v2 tabs template (5 tabs and 2 segments on each tab)
2. ionic build ios
3. ionic emulate ios

```
ionic emulate ios
```

**Ionic Version**: 2.0.0-beta.2 (btw the 2.0.0-beta.3 is not on npm yet so no one can update it so far)

**Browser & Operating System**: iOS

**Run `ionic info` from terminal/cmd prompt:**

```
Cordova CLI: 6.0.0
Ionic Version: 2.0.0-beta.2
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
ios-deploy version: 1.8.5 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v4.3.2
Xcode version: Xcode 7.2.1 Build version 7C1002 
```

**Comment by adamdbradley** [comment] 2016-03-09 21:03
The npm module has moved to `ionic-angular`: https://www.npmjs.com/package/ionic-angular
https://github.com/driftyco/ionic/blob/2.0/CHANGELOG.md#breaking-changes-1

Can you describe more about the lag your seeing? What's the delay?

**Comment by jgw96** [comment] 2016-03-11 18:57
Thanks for submitting an issue! Would you be able to provide us with a codepen or a repo so that we can have some code to test ourself?

**Comment by jgw96** [comment] 2016-03-16 15:49
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!

**Comment by MrBokeh** [comment] 2016-03-18 02:20
Sorry for the delay, here is the code:

I generated a page which the generator generated the name doubled up with the second world search-page become search page page. The generator still doesn't take the -ts command yet. Also I still can't see the update of the new ionic 2 packages. This code below is running super slow.

`
<ion-navbar *navbar hideBackButton> 

    <button menuToggle="menu1" side="left">
        <ion-icon side="left" name='search'></ion-icon>
    </button>

<ion-title>Search</ion-title>

  <ion-buttons end>
      <button (click)="openFiltersModal()">
        <ion-icon name="options"></ion-icon>
      </button>
    </ion-buttons>


</ion-navbar>


<ion-toolbar>
  <ion-segment [(ngModel)]="segment">
    <ion-segment-button value="s1">
      s1
    </ion-segment-button>
    <ion-segment-button value="s2">
      s2
    </ion-segment-button>
    <ion-segment-button value="s3">
      s3
    </ion-segment-button>
  </ion-segment>
</ion-toolbar>

<ion-content class="search-page">


  
  <div [ngSwitch]="segment">
    <ion-list *ngSwitchWhen="'s1'">
      <ion-item>
        <ion-thumbnail item-left>
          <img src="img/thumbnail-puppy-1.jpg">
        </ion-thumbnail>
        <h2>Ruby</h2>
      </ion-item>
      <ion-item>
        <ion-thumbnail item-left>
          <img src="img/thumbnail-puppy-2.jpg">
        </ion-thumbnail>
        <h2>Oscar</h2>
      </ion-item>
      <ion-item>
        <ion-thumbnail item-left>
          <img src="img/thumbnail-puppy-4.jpg">
        </ion-thumbnail>
        <h2>Zoey</h2>
      </ion-item>
      <ion-item>
        <ion-thumbnail item-left>
          <img src="img/thumbnail-puppy-3.jpg">
        </ion-thumbnail>
        <h2>Otto</h2>
      </ion-item>
    </ion-list>

    <ion-list *ngSwitchWhen="'s2'">
      <ion-item>
        <ion-thumbnail item-left>
          <img src="img/thumbnail-kitten-1.jpg">
        </ion-thumbnail>
        <h2>Luna</h2>
      </ion-item>
      <ion-item>
        <ion-thumbnail item-left>
          <img src="img/thumbnail-kitten-3.jpg">
        </ion-thumbnail>
        <h2>Milo</h2>
      </ion-item>
      <ion-item>
        <ion-thumbnail item-left>
          <img src="img/thumbnail-kitten-4.jpg">
        </ion-thumbnail>
        <h2>Bandit</h2>
      </ion-item>
      <ion-item>
        <ion-thumbnail item-left>
          <img src="img/thumbnail-kitten-2.jpg">
        </ion-thumbnail>
        <h2>Nala</h2>
      </ion-item>
    </ion-list>

    <ion-list *ngSwitchWhen="'s3'">
      <ion-item>
        <ion-thumbnail item-left>
          <img src="img/thumbnail-duckling-1.jpg">
        </ion-thumbnail>
        <h2>Daffy</h2>
      </ion-item>
      <ion-item>
        <ion-thumbnail item-left>
          <img src="img/thumbnail-duckling-2.jpg">
        </ion-thumbnail>
        <h2>Huey</h2>
      </ion-item>
      <ion-item>
        <ion-thumbnail item-left>
          <img src="img/thumbnail-duckling-3.jpg">
        </ion-thumbnail>
        <h2>Dewey</h2>
      </ion-item>
      <ion-item>
        <ion-thumbnail item-left>
          <img src="img/thumbnail-duckling-4.jpg">
        </ion-thumbnail>
        <h2>Louie</h2>
      </ion-item>
    </ion-list>
  </div>
</ion-content>
`

**Comment by brandyscarney** [comment] 2016-04-02 17:46
Hey @MrBokeh, could you please update to the latest CLI: `npm install -g ionic@beta` (may require sudo) and then rename your framework package from `ionic-framework` to `ionic-angular` (see https://www.npmjs.com/package/ionic-angular), you can do this by running 

```
npm install ionic-angular@latest --save
```

inside of your project folder, and then you can remove the line that includes `ionic-framework` from your `package.json` file:

```
"ionic-framework": "2.0.0-beta.2",
```

please refer to our changelog for any breaking changes that may affect your project: https://github.com/driftyco/ionic/blob/2.0/CHANGELOG.md#200-beta3-2016-03-07

and refer to the app-base project for any config/gulp changes: https://github.com/driftyco/ionic2-app-base

I'm not able to reproduce this using a new project using the tabs template and the code in your codepen. Could you see if updating fixes it and if not could you provide more information on the emulator you're using? Thanks!

**Comment by jgw96** [comment] 2016-04-29 20:54
Hello! I am going to close this issue since it has been a while since there was any activity. Thanks for using Ionic and feel free to comment if your still having the issue!

**Closed by jgw96** 2016-04-29 20:54 UTC
Labels: platform:ios, v2
