### ISSUE TITLE
Ionic 2 - LocationStrategy "cannot GET /my-page"

### ISSUE THREAD

**Issue by theunreal** [driftyco/ionic#11041] opened 2017-04-04 07:50 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When the `locationStrategy` is set in the `Config` to `path` it's impossible to access the page when refreshing.
For Example: Navigating from "http://localhost:8100" to "http://localhost:8100/my-page" works, but after refreshing in my-page I get the following error: `Cannot GET /new-deck`

**Expected behavior:**
The browser should dsplay my-page instead of an error

**Steps to reproduce + **Related code:**:**
1. Set: ```
IonicModule.forRoot(MyApp, {
      locationStrategy: 'path',
    }
```
2. Modify base URL in index.html: `<base href="/" />`

3. Try to access a page, then refresh. You will get `cannot GET /page-name` error.


**Other information:**
 ordova CLI: 6.5.0
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.2.2
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.2
Xcode version: Not installed

**Comment by jgw96** [comment] 2017-04-04 14:52
Hello, thanks for opening an issue with us. We will look into this.

**Comment by jgw96** [comment] 2017-04-05 16:54
Hello, I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/10565

**Closed by jgw96** 2017-04-05 16:54 UTC
Labels: v2
