### ISSUE TITLE
[ContentComponent] `content.resize()` should work in inactive views

### ISSUE THREAD

**Issue by biesbjerg** [driftyco/ionic#11301] opened 2017-04-20 21:34 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
1. List view: User clicks an item in list and goes to a Detail view
2. Detail view: User performs an action that adds a toolbar for Detail view + List view, then clicks "Back"-button and goes to List view.
3. Even after calling `content.resize()` on the inactive view's `Content` component, it is not resized taking the added toolbar into account.

**Expected behavior:**
I think it should be possible to add a toolbar globally in the app, calling `content.resize()` on all views' `Content` components and have them resize, even when the views are inactive.

What do you think?

**Steps to reproduce:**

**Related code:**
I'm doing the resizing from my custom component, that get passed in a reference of `ion-content`.

```ts
import { Component, AfterViewInit, Input } from '@angular/core';

import { Content } from 'ionic-angular';
import { Observable } from 'rxjs/Observable';

@Component({
	selector: 'toolbar-player',
	templateUrl: 'toolbar-player.html'
})
export class ToolbarPlayerComponent implements ngAfterViewInit {

	@Input() public content: Content;

	// Imagine an external Observable responsible for determining if toolbar should show
	public showToolbar$: Observable<boolean>;

	public ngAfterViewInit(): void {
		this.showToolbar$
			.subscribe(isVisible => {
				if (this.content) {
					this.content.resize();
				}
			});
	}

}
```

```html
<ion-content #content>
...
</ion-content>
<ion-footer>
    <toolbar-player [content]="content"></toolbar-player>
</ion-footer>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.4
ios-deploy version: 1.9.1
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.3.1 Build version 8E1000a
```

**Comment by jgw96** [comment] 2017-04-21 15:01
Hello, thanks for opening an issue with us! Could you share a repo we could use to reproduce this?

**Comment by jgw96** [comment] 2017-04-26 18:25
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-04-26 18:25 UTC
Labels: needs info, v2

**Comment by biesbjerg** [comment] 2017-04-26 18:28
Hi,

This is of course still an issue, since nothing has been done to change the behavior, but unfortunately I don't currently have a repo to share with you and little time to create one at the moment, I'm afraid.

Do you agree that it should be possible to resize `ion-content` even if it's not currently active? 
I don't want to go through the trouble of creating a repo for you if this will be closed as "works as intended" etc.

**Comment by biesbjerg** [comment] 2017-04-27 22:42
Bump?
