### ISSUE TITLE
ionic2 - Popover - Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by virtualit786** [driftyco/ionic#7330] opened 2016-07-15 15:18 UTC
Plunker with issue in action is at http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview
Simply tried Popover code from ionic2 documentation and got the following RangeError in both web browser and iOS simulator ,  when clicking any of the buttons. 

 "ionic-angular": "2.0.0-beta.10"
  "ionic-native": "1.3.2",

RangeError: Maximum call stack size exceeded.

Here is the stacktrace from the browser:-
```
EXCEPTION: Error in ./MyPopover class MyPopover - inline template:6:23
browser_adapter.js:77 EXCEPTION: Error in ./MyPopover class MyPopover - inline template:6:23BrowserDomAdapter.logError @ browser_adapter.js:77BrowserDomAdapter.logGroup @ browser_adapter.js:87ExceptionHandler.call @ exception_handler.js:58(anonymous function) @ application_ref.js:317schedulerFn @ async.js:132SafeSubscriber.__tryOrUnsub @ Subscriber.js:225SafeSubscriber.next @ Subscriber.js:174Subscriber._next @ Subscriber.js:124Subscriber.next @ Subscriber.js:88Subject._finalNext @ Subject.js:128Subject._next @ Subject.js:120Subject.next @ Subject.js:77EventEmitter.emit @ async.js:120onError @ ng_zone.js:117onHandleError @ ng_zone_impl.js:67e.handleError @ zone.min.js:1e.runGuarded @ zone.min.js:1NgZoneImpl.runInnerGuarded @ ng_zone_impl.js:79NgZone.runGuarded @ ng_zone.js:233outsideHandler @ dom_events.js:20e.invokeTask @ zone.min.js:1e.runTask @ zone.min.js:1invoke @ zone.min.js:1
browser_adapter.js:77 ORIGINAL EXCEPTION: RangeError: Maximum call stack size exceededBrowserDomAdapter.logError @ browser_adapter.js:77ExceptionHandler.call @ exception_handler.js:67(anonymous function) @ application_ref.js:317schedulerFn @ async.js:132SafeSubscriber.__tryOrUnsub @ Subscriber.js:225SafeSubscriber.next @ Subscriber.js:174Subscriber._next @ Subscriber.js:124Subscriber.next @ Subscriber.js:88Subject._finalNext @ Subject.js:128Subject._next @ Subject.js:120Subject.next @ Subject.js:77EventEmitter.emit @ async.js:120onError @ ng_zone.js:117onHandleError @ ng_zone_impl.js:67e.handleError @ zone.min.js:1e.runGuarded @ zone.min.js:1NgZoneImpl.runInnerGuarded @ ng_zone_impl.js:79NgZone.runGuarded @ ng_zone.js:233outsideHandler @ dom_events.js:20e.invokeTask @ zone.min.js:1e.runTask @ zone.min.js:1invoke @ zone.min.js:1
browser_adapter.js:77 ORIGINAL STACKTRACE:BrowserDomAdapter.logError @ browser_adapter.js:77ExceptionHandler.call @ exception_handler.js:70(anonymous function) @ application_ref.js:317schedulerFn @ async.js:132SafeSubscriber.__tryOrUnsub @ Subscriber.js:225SafeSubscriber.next @ Subscriber.js:174Subscriber._next @ Subscriber.js:124Subscriber.next @ Subscriber.js:88Subject._finalNext @ Subject.js:128Subject._next @ Subject.js:120Subject.next @ Subject.js:77EventEmitter.emit @ async.js:120onError @ ng_zone.js:117onHandleError @ ng_zone_impl.js:67e.handleError @ zone.min.js:1e.runGuarded @ zone.min.js:1NgZoneImpl.runInnerGuarded @ ng_zone_impl.js:79NgZone.runGuarded @ ng_zone.js:233outsideHandler @ dom_events.js:20e.invokeTask @ zone.min.js:1e.runTask @ zone.min.js:1invoke @ zone.min.js:1
browser_adapter.js:77 RangeError: Maximum call stack size exceeded
    at _baseExtend (util.js:47)
    at _baseExtend (util.js:59)
    at _baseExtend (util.js:59)
    at _baseExtend (util.js:59)
    at _baseExtend (util.js:59)
    at _baseExtend (util.js:59)
    at _baseExtend (util.js:59)
    at _baseExtend (util.js:59)
    at _baseExtend (util.js:59)
    at _baseExtend (util.js:59)BrowserDomAdapter.logError @ browser_adapter.js:77ExceptionHandler.call @ exception_handler.js:71(anonymous function) @ application_ref.js:317schedulerFn @ async.js:132SafeSubscriber.__tryOrUnsub @ Subscriber.js:225SafeSubscriber.next @ Subscriber.js:174Subscriber._next @ Subscriber.js:124Subscriber.next @ Subscriber.js:88Subject._finalNext @ Subject.js:128Subject._next @ Subject.js:120Subject.next @ Subject.js:77EventEmitter.emit @ async.js:120onError @ ng_zone.js:117onHandleError @ ng_zone_impl.js:67e.handleError @ zone.min.js:1e.runGuarded @ zone.min.js:1NgZoneImpl.runInnerGuarded @ ng_zone_impl.js:79NgZone.runGuarded @ ng_zone.js:233outsideHandler @ dom_events.js:20e.invokeTask @ zone.min.js:1e.runTask @ zone.min.js:1invoke @ zone.min.js:1
browser_adapter.js:77 ERROR CONTEXT:BrowserDomAdapter.logError @ browser_adapter.js:77ExceptionHandler.call @ exception_handler.js:74(anonymous function) @ application_ref.js:317schedulerFn @ async.js:132SafeSubscriber.__tryOrUnsub @ Subscriber.js:225SafeSubscriber.next @ Subscriber.js:174Subscriber._next @ Subscriber.js:124Subscriber.next @ Subscriber.js:88Subject._finalNext @ Subject.js:128Subject._next @ Subject.js:120Subject.next @ Subject.js:77EventEmitter.emit @ async.js:120onError @ ng_zone.js:117onHandleError @ ng_zone_impl.js:67e.handleError @ zone.min.js:1e.runGuarded @ zone.min.js:1NgZoneImpl.runInnerGuarded @ ng_zone_impl.js:79NgZone.runGuarded @ ng_zone.js:233outsideHandler @ dom_events.js:20e.invokeTask @ zone.min.js:1e.runTask @ zone.min.js:1invoke @ zone.min.js:1
browser_adapter.js:77 DebugContext {_view: _View_MyPopover0, _nodeIndex: 15, _tplRow: 6, _tplCol: 23}BrowserDomAdapter.logError @ browser_adapter.js:77ExceptionHandler.call @ exception_handler.js:75(anonymous function) @ application_ref.js:317schedulerFn @ async.js:132SafeSubscriber.__tryOrUnsub @ Subscriber.js:225SafeSubscriber.next @ Subscriber.js:174Subscriber._next @ Subscriber.js:124Subscriber.next @ Subscriber.js:88Subject._finalNext @ Subject.js:128Subject._next @ Subject.js:120Subject.next @ Subject.js:77EventEmitter.emit @ async.js:120onError @ ng_zone.js:117onHandleError @ ng_zone_impl.js:67e.handleError @ zone.min.js:1e.runGuarded @ zone.min.js:1NgZoneImpl.runInnerGuarded @ ng_zone_impl.js:79NgZone.runGuarded @ ng_zone.js:233outsideHandler @ dom_events.js:20e.invokeTask @ zone.min.js:1e.runTask @ zone.min.js:1invoke @ zone.min.js:1
zone.min.js:1 Uncaught EXCEPTION: Error in ./MyPopover class MyPopover - inline template:6:23
ORIGINAL EXCEPTION: RangeError: Maximum call stack size exceeded
ORIGINAL STACKTRACE:
RangeError: Maximum call stack size exceeded
    at _baseExtend (http://localhost:8100/build/js/app.bundle.js:75863:21)
    at _baseExtend (http://localhost:8100/build/js/app.bundle.js:75875:17)
    at _baseExtend (http://localhost:8100/build/js/app.bundle.js:75875:17)
    at _baseExtend (http://localhost:8100/build/js/app.bundle.js:75875:17)
    at _baseExtend (http://localhost:8100/build/js/app.bundle.js:75875:17)
    at _baseExtend (http://localhost:8100/build/js/app.bundle.js:75875:17)
    at _baseExtend (http://localhost:8100/build/js/app.bundle.js:75875:17)
    at _baseExtend (http://localhost:8100/build/js/app.bundle.js:75875:17)
    at _baseExtend (http://localhost:8100/build/js/app.bundle.js:75875:17)
    at _baseExtend (http://localhost:8100/build/js/app.bundle.js:75875:17)
ERROR CONTEXT:
[object Object]e.runTask @ zone.min.js:1invoke @ zone.min.js:1
```

Here is the relevant code 

```
import {Component} from '@angular/core';
import {ViewController,NavController,NavParams,Popover} from 'ionic-angular';
import {PressDirective} from './press.gesture.directive';

@Component({
  template: `
    <ion-list>
      <ion-list-header>Ionic</ion-list-header>
      <button ion-item (click)="close()">Learn Ionic</button>
      <button ion-item (click)="close()">Documentation</button>
      <button ion-item (click)="close()">Showcase</button>
      <button ion-item (click)="close()">GitHub Repo</button>
    </ion-list>
  `
})

export class MyPopover {
  constructor(private viewCtrl:ViewController) {
  }
  close() {
    this.viewCtrl.dismiss();
  }
}

@Component({
  templateUrl: 'build/pages/chat/chat-detail.html'
  , directives: [PressDirective]

})
export class ChatDetailsPage {
  constructor(private navParams:NavParams, private navController:NavController) {  }
  onLongPress($event) {
    let popover = Popover.create(MyPopover);
    this.navController.present(popover, {
      ev: $event
    });
  }
}

```

And the PressGesture directive code used is below :-
```
import {Directive, ElementRef, OnInit, OnDestroy, Output, EventEmitter} from '@angular/core';
import {Gesture} from 'ionic-angular/gestures/gesture';

@Directive({
  selector: '[longPress]'
})
export class PressDirective implements OnInit, OnDestroy {
  el: HTMLElement;
  pressGesture: Gesture;

  @Output()
      longPress: EventEmitter<any> = new EventEmitter<any>();

  constructor(el: ElementRef) {
    this.el = el.nativeElement;
  }

  ngOnInit() {
    this.pressGesture = new Gesture(this.el);
    this.pressGesture.listen();
    this.pressGesture.on('press', e => {
      console.log('PressDirective::pressed!!');
      this.longPress.emit(e);
    });
    this.pressGesture.on('tap', e => {
      console.log('PressDirective::tapped!');
    });
  }

  ngOnDestroy() {
![screen shot 2016-07-15 at 8 29 08 pm](https://cloud.githubusercontent.com/assets/2112745/16879929/2dd5116a-4acc-11e6-8d7b-d67424ca6ec7.png)

    this.pressGesture.destroy();
  }
}
```
Relavant HTML is
```
<ion-header>
</ion-header>

<ion-content class="detail" (click)="dismissPopup($event)">
  <div  padding>
    <ion-input type="text" value="Long Press" (longPress)="onLongPress($event)"></ion-input>
  </div>
</ion-content>

```

**Comment by jgw96** [comment] 2016-07-15 15:26
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by virtualit786** [comment] 2016-07-15 15:39
@jgw96 I have updated the issue description and added the code! Please see if it helps !

**Comment by virtualit786** [comment] 2016-07-15 15:54
@jgw96 Here is the plunker with the issue in action http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview

**Comment by jgw96** [comment] 2016-07-15 16:03
Hello, thanks for getting me the plunker (: After looking at this it looks to be a duplicate of https://github.com/driftyco/ionic/issues/6918 so i will be closing this issue for now. Thanks for using Ionic!

**Closed by jgw96** 2016-07-15 16:03 UTC
Labels: actionsheet, v2

**Comment by virtualit786** [comment] 2016-07-15 16:24
@jgw96 But is not for android only ! I am experiencing it in browser and as well as iOS!
