### ISSUE TITLE
bug: the  scroll  has some strange features;

### ISSUE THREAD

**Issue by hxzAugustinus** [driftyco/ionic#4617] opened 2015-11-10 09:09 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>browser</span>

<span ionic-description>This is first example <a  href='http://codepen.io/hxz/pen/wKQGzp'  >click</a>, please notice the  scroll  height . then i  delete the span element ,just like the second example   <a  href='http://codepen.io/hxz/pen/yYQOVQ'  >click</a>, please notice that the  scroll's  height  has  change  too much .
      I don't  know that  the ion-content's  first element  which  has   margin/padding-top  will make the scroll  change so much.</span>

<span is-issue-template></span>

**Comment by petehouston** [comment] 2015-11-25 17:38
I don't see anything strange on scroll. Could you capture images to show the differences?

**Comment by hxzAugustinus** [comment] 2015-11-30 04:02
@petehouston    when you scroll the content to the bottom ,you will find that  the second example has a extra Blank，however the first example doesn't has the blank

**Comment by jgw96** [comment] 2016-03-14 21:33
Hello! Thanks for opening an issue with us, we just need a little more info from you so that we can better help you with your issue. Would you mind posting a code sample, plunkr or codepen that we can use to reproduce your issue? Also, would you mind running `ionic info` and posting the output? Thanks again!

**Comment by jgw96** [comment] 2016-03-21 19:52
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!

**Closed by jgw96** 2016-03-21 19:52 UTC
Labels: scroll, v1
