### ISSUE TITLE
Navigation Pop inside an event handler stops event listeners working on page

### ISSUE THREAD

**Issue by Rambatino** [driftyco/ionic#7965] opened 2016-09-04 14:04 UTC
#### Short description of the problem:

I have an alert in a pushed page, and when a button is pressed, I pop back to a previous page, however, none of my event listeners will fire (e.g. on a button)

If I don't call pop from inside the handler of the button, it works as expected

#### What behavior are you expecting?

The event listeners to not stop working

**Steps to reproduce:**
1.  Create a page
2. Push a page
3.  Call pop from an alert view after pressing a button
4. Event listeners stop working

My pop logic:
``` typescript
    throwAlert(title: string, subtitle: string): void {
            this._alert.create({
                    title: title,
                    subTitle: subtitle,
                    buttons: [
                        {
                            text: 'No'
                        }, {
                            text: 'Yes',
                            handler: () => {
                                this._nav.remove(2, 2)
                                this._nav.pop()
                            }
                        }]
                }).present()
   }
```

#### Plunker that shows an example of your issue

I created a plunker with the correct code: 
http://plnkr.co/edit/aBsS4Iu1Qbk31BUGWzPx?p=preview

However, I couldn't get it to run as it was set to beta 10 and i need beta 11 and when I changed the index.js it broke. Hmm how do I create a beta 11 plunkr? Alerntatively, if you ammend the issue, it should demonstrate my problem.

Thanks!

``` bash
Your system information:

Cordova CLI: 5.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.5
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v6.3.1
Xcode version: Xcode 7.3.1 Build version 7D1014
```

**Comment by manucorporat** [comment] 2016-10-01 00:20
@Rambatino I don't understand exactly what this issue is about

**Comment by jgw96** [comment] 2016-10-04 15:29
Hello @Rambatino would you mind posting a repo that we can use to reproduce your issue? Thanks!

**Comment by jgw96** [comment] 2016-10-07 13:40
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-10-07 13:40 UTC
Labels: needs reply, v2
