### ISSUE TITLE
bug: View flickers when opening left-hand navigation using native scrolling (iOS9)

### ISSUE THREAD

**Issue by guntherhoppe** [driftyco/ionic#4427] opened 2015-09-25 14:38 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>Maybe similiar to #4394; iOS9-only (With iOS 8.x it did not occur)
Happens only when using native scrolling.

Scenario:
- App template w/ left-hand nav menu
- JS scrolling deactivated using $ionicConfigProvider.scrolling.jsScrolling(false)
- View with a list and a few list items (so that can be scrolled)

Reproduce:
- Open the view from nav (so that menu is closed)
- Open menu again --> Right-hand view flickers (seems it is hiding and showing again)
- Note: When you slide the menu to open, no flickering occurs until you remove your finger from the screen

Env:
- Tested on iOS 9 (iPhone)
- Ionic v1.1.0 (incl. Patch from #4082)  / Angular v1.3.13</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-09-25 14:38
Greetings @guntherhoppe!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4427). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4427)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment] 2015-10-02 17:47
Duplicate of #4427

**Closed by mhartington** 2015-10-02 17:47 UTC

**Comment by guntherhoppe** [comment] 2015-10-20 05:52
Hi,
I don't think this is duplicated to #4426. 

#4426 points to list scrolling behaviour and also occurs on iOS 8.x whereas this problem points to side menu.

Not fixed! Please reopen.
