### ISSUE TITLE
docs: The demo for Modals is broken.

### ISSUE THREAD

**Issue by tonyawad88** [driftyco/ionic#5472] opened 2016-02-16 17:32 UTC
**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>The demo for Modals on the ionic 2 demo site is broken. Link for the demo: http://ionicframework.com/docs/v2/api/components/modal/Modal/ . 
You guys have done a great jobs on this. Keep it going :)</span>

<span is-issue-template></span>

**Comment by brandyscarney** [comment] 2016-02-16 17:57
Thanks! Which part is broken? I am seeing the demo working as expected.

**Comment by tonyawad88** [comment] 2016-02-16 18:08
@brandyscarney I am not sure how I broke it before... It is fine after I reloaded the page. Here's my screenshot from before. Hope it helps. 
![basicmodalexception1](https://cloud.githubusercontent.com/assets/3638322/13085846/3c9dcbcc-d4ae-11e5-964a-b2d86191719e.JPG)

**Comment by brandyscarney** [comment] 2016-02-16 18:14
@tonyawad88 hmm that's strange. I'm not sure how that happened. I'm going to close this but if you're able to reproduce it again, please let me know!

**Closed by brandyscarney** 2016-02-16 18:14 UTC
Labels: docs, v2

**Comment by tonyawad88** [comment] 2016-02-16 18:26
@brandyscarney I am able to replicate now, it seems random. It seems that if I click on "OpenBasicModal" before some events are bound to the button, I get the errors. Not a biggie. 

I attached the stack below if needed. 
-------------------------------------------------------
EXCEPTION: Error during evaluation of "click"
bundle.js:34126 EXCEPTION: Error during evaluation of "click"BrowserDomAdapter.logError @ bundle.js:34126BrowserDomAdapter.logGroup @ bundle.js:34136ExceptionHandler.call @ bundle.js:7892(anonymous function) @ bundle.js:17072NgZone._notifyOnError @ bundle.js:17731collection_1.StringMapWrapper.merge.onError @ bundle.js:17626Zone.run @ bundle.js:2263(anonymous function) @ bundle.js:17644NgZone.run @ bundle.js:17592outsideHandler @ bundle.js:32860Zone.run @ bundle.js:2259zoneBoundFn @ bundle.js:2236
bundle.js:34126 ORIGINAL EXCEPTION: TypeError: l_context.openBasicModal is not a functionBrowserDomAdapter.logError @ bundle.js:34126ExceptionHandler.call @ bundle.js:7901(anonymous function) @ bundle.js:17072NgZone._notifyOnError @ bundle.js:17731collection_1.StringMapWrapper.merge.onError @ bundle.js:17626Zone.run @ bundle.js:2263(anonymous function) @ bundle.js:17644NgZone.run @ bundle.js:17592outsideHandler @ bundle.js:32860Zone.run @ bundle.js:2259zoneBoundFn @ bundle.js:2236
bundle.js:34126 ORIGINAL STACKTRACE:BrowserDomAdapter.logError @ bundle.js:34126ExceptionHandler.call @ bundle.js:7904(anonymous function) @ bundle.js:17072NgZone._notifyOnError @ bundle.js:17731collection_1.StringMapWrapper.merge.onError @ bundle.js:17626Zone.run @ bundle.js:2263(anonymous function) @ bundle.js:17644NgZone.run @ bundle.js:17592outsideHandler @ bundle.js:32860Zone.run @ bundle.js:2259zoneBoundFn @ bundle.js:2236
bundle.js:34126 TypeError: l_context.openBasicModal is not a function
    at AbstractChangeDetector.ChangeDetector_InitialPage_0.handleEventInternal (viewFactory_InitialPage:446)
    at AbstractChangeDetector.handleEvent (bundle.js:14093)
    at AppView.triggerEventHandlers (bundle.js:18400)
    at eval (viewFactory_InitialPage:786)
    at bundle.js:33483
    at bundle.js:32860
    at Zone.run (bundle.js:2259)
    at Zone.run (bundle.js:17644)
    at NgZone.run (bundle.js:17592)
    at HTMLButtonElement.outsideHandler (bundle.js:32860)BrowserDomAdapter.logError @ bundle.js:34126ExceptionHandler.call @ bundle.js:7905(anonymous function) @ bundle.js:17072NgZone._notifyOnError @ bundle.js:17731collection_1.StringMapWrapper.merge.onError @ bundle.js:17626Zone.run @ bundle.js:2263(anonymous function) @ bundle.js:17644NgZone.run @ bundle.js:17592outsideHandler @ bundle.js:32860Zone.run @ bundle.js:2259zoneBoundFn @ bundle.js:2236
bundle.js:34126 ERROR CONTEXT:BrowserDomAdapter.logError @ bundle.js:34126ExceptionHandler.call @ bundle.js:7908(anonymous function) @ bundle.js:17072NgZone._notifyOnError @ bundle.js:17731collection_1.StringMapWrapper.merge.onError @ bundle.js:17626Zone.run @ bundle.js:2263(anonymous function) @ bundle.js:17644NgZone.run @ bundle.js:17592outsideHandler @ bundle.js:32860Zone.run @ bundle.js:2259zoneBoundFn @ bundle.js:2236
bundle.js:34126 EventEvaluationErrorContext {element: button.disable-hover.button.button-default.button-block.activated, componentElement: ion-page.initial-page.show-page, context: InitialPage, locals: Object, injector: Injector}BrowserDomAdapter.logError @ bundle.js:34126ExceptionHandler.call @ bundle.js:7909(anonymous function) @ bundle.js:17072NgZone._notifyOnError @ bundle.js:17731collection_1.StringMapWrapper.merge.onError @ bundle.js:17626Zone.run @ bundle.js:2263(anonymous function) @ bundle.js:17644NgZone.run @ bundle.js:17592outsideHandler @ bundle.js:32860Zone.run @ bundle.js:2259zoneBoundFn @ bundle.js:2236
bundle.js:2266 Uncaught EXCEPTION: Error during evaluation of "click"
ORIGINAL EXCEPTION: TypeError: l_context.openBasicModal is not a function
ORIGINAL STACKTRACE:
TypeError: l_context.openBasicModal is not a function
    at AbstractChangeDetector.ChangeDetector_InitialPage_0.handleEventInternal (viewFactory_InitialPage:446:39)
    at AbstractChangeDetector.handleEvent (http://ionicframework.com/docs/v2/demos/modal/bundle.js:14093:30)
    at AppView.triggerEventHandlers (http://ionicframework.com/docs/v2/demos/modal/bundle.js:18400:37)
    at eval (viewFactory_InitialPage:786:110)
    at http://ionicframework.com/docs/v2/demos/modal/bundle.js:33483:37
    at http://ionicframework.com/docs/v2/demos/modal/bundle.js:32860:87
    at Zone.run (http://ionicframework.com/docs/v2/demos/modal/bundle.js:2259:25)
    at Zone.run (http://ionicframework.com/docs/v2/demos/modal/bundle.js:17644:43)
    at NgZone.run (http://ionicframework.com/docs/v2/demos/modal/bundle.js:17592:41)
    at HTMLButtonElement.outsideHandler (http://ionicframework.com/docs/v2/demos/modal/bundle.js:32860:62)
ERROR CONTEXT:
[object Object]

**Comment by brandyscarney** [comment] 2016-02-16 18:46
@tonyawad88 what version is your browser?

**Comment by tonyawad88** [comment] 2016-02-16 19:40
@brandyscarney It's Google Chrome. Version 48.0.2564.109 m

**Comment by brandyscarney** [comment] 2016-02-16 19:48
@tonyawad88 I updated my browser to the exact same version and I still can't reproduce it. :disappointed: @drewrygh can you see if you can reproduce this?
