### ISSUE TITLE
bug: Unable to register service worker

### ISSUE THREAD

**Issue by remster** [driftyco/ionic#9990] opened 2017-01-12 14:15 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>Ionic advertises its support for service workers: http://blog.ionic.io/tag/service-workers/

The staple app template as generated by https://ionicframework.com/getting-started/

Produces this section:
``

However, un-commenting it and running on Android causes this:
`
Error DOMException: Failed to register a ServiceWorker: The URL protocol of the current origin ('file://') is not supported.
`

I have missed a configuration step or Ionic - understood as hybrid app dev framework with Android and iOS being core - does not support service workers as advertised.

Please help</span>

<span is-issue-template></span>

**Comment by brandyscarney** [comment] 2017-01-12 15:35
Thanks for the issue, I am going to close this as a duplicate of #9977. :)

**Closed by brandyscarney** 2017-01-12 15:35 UTC
