### ISSUE TITLE
bug: Native overflow not working on ios 8.2

### ISSUE THREAD

**Issue by loicfavory** [driftyco/ionic#3267] opened 2015-03-10 09:56 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>To reproduce it :
create a new app :

ionic start myApp tabs
cd myApp/
ionic platform add ios

Edit file www/templates/tab-dash.html and duplicate content to have scroll

Edit ion-content to add overflow-scroll property.

Run on Ipad mini, with iOS 8.2

Scroll is not working.

Seems it's working when removing -webkit-overflow-scrolling: touch on overflow-scroll class, but the scroll is not perfect.

Thanks for your help,
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-03-10 09:56
Greetings @loicfavory!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3267). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3267)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment] 2015-03-11 18:38
I see this too, but I'm having trouble debugging it. As best I can tell, it's a webkit bug.  When I remove `cordova.js` from my `index.html` scrolling works fine.  I suspect this is from how Cordova uses iFrames to communicate.  Are you able to confirm this?

**Comment by loicfavory** [comment] 2015-03-11 19:15
Don't have an iOs platform right now, but it seems it's related to iOs rather than webkit : http://stackoverflow.com/questions/26046373/iframe-scrolling-ios-8.
Will give you a feedback of my iPad tomorrow.

Did you test it on older iOs versions ?

**Comment by loicfavory** [comment] 2015-03-24 08:57
@perrygovier Sorry for the delay, I did the test by removing cordova.js from index.html, I confirm it works fine. Did you find a solution ?

**Comment by Fayozjon** [comment] 2015-03-24 17:11
loicfavory

http://bonjoursalon.kz/frontstocks_optionbit

24.03.2015, 11:57, "loicfavory" <notifications@github.com>: Sorry for the delay, I did the test by removing cordova.js from index.html, I confirm it works fine. Did you find a solution ?

**Comment by krik** [comment] 2015-03-27 14:07
I see this too on my iOS 8.2 device. Happens in simulator for other versions of iOS too. Cordova 3.8 and 3.7 platforms.

**Comment by Rautec** [comment] 2015-03-29 15:44
We have the same problem in our iOS App since laste Xcode update - overflow-scroll="true" does not work in the views anymore. 

The curious thing is that native scrolling in the modals works fine. Any idea how to quick fix this for now?

**Comment by loicfavory** [comment] 2015-03-30 12:49
No more problem for me.
I updated Cordova (to 4.2.0) & ionic to rc.1-nightly-1155.
Xcode 6.2 (6C131e)

**Comment by krik** [comment] 2015-03-30 13:14
Thanks @loicfavory! Can confirm this works with Cordova iOS 3.8 and v1.0.0-rc.1-nightly-1154

**Comment by Rautec** [comment] 2015-03-30 18:26
Thanks for the help. Update to nightly build helped.

**Comment by b3na** [comment] 2015-10-20 17:54
Hello, I'm having this same issue, this is only happening on iOS. I am currently on ionic 1.1.0 and cordova 5.0.0. If I remove the cordova.js script, the app scrolls normally. Does someone have another possible fix?

**Comment by stambe** [comment] 2015-12-15 13:52
I am having the same problem, I have Xcode 7 and cordova 5.3.3? Is there any quick fix for this?

**Comment by peterpan666** [comment] 2016-02-02 10:28
Same issue here, XCode 7.2 Cordova 6 and Ionic 1.7.14.

Any solution?

**Comment by peterpan666** [comment] 2016-02-02 10:32
The scroll bar does appear though.

When the cordova.js file in included, the content moves by just 1 pixel and the scroll bar appears too.

**Comment by jgw96** [comment] 2016-06-14 14:52
Hello all, thanks for opening an issue with us! I am going to close this for now as I cannot reproduce this on ios 9.3.2. it looks as if this was an iOS 8 WebKit bug. If you can still reproduce on ios 9 then feel free to comment and I will happily reopen.

**Closed by jgw96** 2016-06-14 14:52 UTC
Labels: scroll, v1
