### ISSUE TITLE
bug: ion-slides with form inputs

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic#5744] opened 2016-03-07 07:46 UTC
#### Short description of the problem:

On a device, when there is an ion-input, the ion-list scrolling behaviour does not work.
#### What behavior are you expecting?

On a device when inputting information, the keyboard opens up and the ion-list scrolls so that the keyboard does not cover the input fields. When the user closes the keyboard, the ion-list then scrolls back to it's original position. 

If input is required in an ion-slides component (maybe as part of a wizard), the scrolling behaviour does not work as expected. The form's inputs move off the screen and the content cannot be seen. When the keyboard is closed, the content does not move back into focus.

The following simple input form works perfectly. The keyboard shows and the inputs are scrolled so that they are visible with the keyboard. 

```
<ion-content class='register-page'>
            <ion-list>
                <img padding src='img/logo.png' style='max-width:100%'>
                <p>What course are you studying?</p>
                    <ion-item class='register-select'>
                        <ion-label hidden>Course</ion-label>
                        <ion-input placeholder='Enter your course' [ngModel]="courseInfo" (ngModelChange)="onCourseEntered($event)"></ion-input>
                    </ion-item>
                    <button clear (click)="continuePressed()" [disabled]='!courseInfoEntered'>Continue</button>
            </ion-list>
</ion-content>
```

If this exact same code was inside of an <ion-slide>, the scrolling behaviour does not work. 

A screenshot of all the content completely off screen with the keyboard open:
![capture](https://cloud.githubusercontent.com/assets/2852839/13563324/7adc4b8e-e449-11e5-8507-fc03df848a84.PNG)

**Ionic Version**: 2.x

**Browser & Operating System**: iOS / Android

**Run `ionic info` from terminal/cmd prompt:**

```
Cordova CLI: 6.0.0
Ionic Version: 2.0.0-beta.2
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
OS:
Node Version: v5.7.0
```

**Comment by EvanWillms** [comment] 2016-04-10 22:00
With ion-slides getting pushed around by the keyboard, this sounds very similar to #5571 and is likely another symptom of #5432.

**Comment by adamdbradley** [comment] 2016-04-12 15:50
Related: https://github.com/driftyco/ionic/issues/6133

**Comment by jgw96** [comment] 2016-06-20 16:43
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment] 2016-06-24 14:53
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. There were a couple of fixes for the keyboard and scrolling in an earlier release so this should be fixed now. Thanks for using Ionic!

**Comment by RonCan** [comment] 2016-07-18 09:49
I'm still facing this issue

**Comment by Bouzmine** [comment] 2016-09-20 01:32
@jgw96 Could you reopen this issue? I facing it using the latest version of ionic (beta.11).

**Comment by Chuckv01** [comment] 2016-10-04 18:22
This is still happening with RC0.

**Comment by jamesgroat** [comment] 2016-10-10 21:30
@manucorporat I'm seeing this as well. (also FYI this issue is assigned to a closed milestone)

**Comment by ivanmayes** [comment] 2016-10-11 19:45
Happening in Ionic 1 with ion-slides as well.

**Comment by kazigais** [comment] 2016-11-20 20:50
Any workaround?

**Comment by jgw96** [comment] 2016-12-14 18:32
Hello all! I am going to close this issue as a duplicate of #9553 as they are caused by the same issue.

**Closed by jgw96** 2016-12-14 18:32 UTC
Labels: keyboard, platform:android, platform:ios, v2

**Comment by LiveListMobile** [comment] 2017-04-30 18:22
Just to chime in here on 04/30/17. I have am experiencing this issue as well. The inputs on the form jump around and/or disappear from the screen altogether making the slides completely unusable.

**Comment by juanpmarengo** [comment] 2017-08-03 13:32
I am also experiencing this issue.

**Ionic info:**

cli packages: (/home/juanpmarengo/Projects/mydoc-ionic/node_modules)

    @ionic/cli-plugin-cordova       : 1.6.1
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.0
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.5.3

System:

    Android SDK Tools : 26.0.1
    Node              : v8.0.0
    OS                : Linux 4.10
    npm               : 5.3.0

**Comment by edzillion** [comment] 2017-08-08 08:48
Still getting this bug with latest:

cli packages: (E:\dev\circles_testnet_v2\node_modules)

    @ionic/cli-plugin-cordova       : 1.6.2
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-plugin-proxy         : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3 browser 4.1.0 ios 4.4.0
    Ionic Framework    : ionic-angular 3.5.3

System:

    Node : v6.11.2
    OS   : Windows 8.1
    npm  : 4.1.2

**Comment by wowkucko** [comment] 2018-01-31 08:54
Have you ever found an actual working solution for this? I don't want to put all my input fields into one page, i guess slides are my only option.

**Comment by edzillion** [comment] 2018-01-31 21:56
Not I @wowkucko

**Comment by migueltsobong7** [comment] 2018-02-13 03:57
getting this too

**Comment by yohoprashant** [comment] 2018-03-22 08:47
same with me.. and I am stuck in the middle of a project.

    "@angular/cli": "^1.7.2",
    "@ionic/app-scripts": "^3.1.8",
    "typescript": "2.7.2"

**Comment by shehrazjazib** [comment] 2018-05-18 23:34
I am facing still this issue when keyboard open, my slides go up and didn't show, until keyboard hide.

**Comment by jdnichollsc** [comment] 2018-05-30 15:25
any solution?

**Comment by yohoprashant** [comment] 2018-07-10 13:35
I had same problem. But I was surprised when It worked after adding a div tag around ion-slide.

**Comment by madsheep** [comment] 2018-07-11 16:32
@yohoprashant could you please provide your html? I'm getting the same issue now.
