### ISSUE TITLE
bug: Strange flickering of tab icons when changing tabs (using directive tabNav)

### ISSUE THREAD

**Issue by carlosbaraza** [driftyco/ionic#4770] opened 2015-12-13 23:59 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>This is an example of the exact flickering moment I talk about:

<img width="1364" alt="screen shot 2015-12-14 at 12 01 36 am" src="https://cloud.githubusercontent.com/assets/1270425/11770422/ac1612e0-a1fd-11e5-944d-fa7239a1f7c8.png">

I have already found a fix and I will soon submit a PR.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-12-13 23:59
Greetings @carlosbaraza!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4770). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4770)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment] 2015-12-14 15:58
Thanks, looking forward to the PR. Doesn't seem like a 1.2 regression so if it gets in for 1.2.1 that's great otherwise we can push to 1.3

**Comment by carlosbaraza** [comment] 2015-12-14 16:40
Hi @mlynch, I already submitted the PR #4771 :)

**Comment by mlynch** [comment] 2015-12-17 01:14
Thanks @carlosbaraza. I'm confused why we're just seeing this issue now. The data-ng-animate looks suspect, are you doing anything custom in your app?

**Comment by carlosbaraza** [comment] 2015-12-17 02:21
Well, I am using Meteor and it so I do not use any of the Ionic CLIs. Maybe this has something to do. Otherwise, I don't think I have anything more custom.

I think in the end I will stop using the tab directives because currently they bring more troubles than they actually solve.

**Comment by lance-anderson** [comment] 2016-01-07 00:55
+1

**Comment by violet7** [comment] 2016-01-12 16:40
+1

**Comment by carlosbaraza** [comment] 2016-01-18 21:55
Hi @mlynch, any plans regarding this issue?

Thanks.

**Comment by jgw96** [comment] 2016-05-17 15:19
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment] 2016-05-23 20:46
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-05-23 20:46 UTC
Labels: needs reply, tabs, v1
