### ISSUE TITLE
Wrong modal opacity on app.md.css

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#7475] opened 2016-07-29 17:57 UTC
_From @zefrench on July 10, 2016 15:46_

Hi,
The opacity of the modal on Android is .01.
So, the modal is totally transparent.

To fix it go to line 6736 of the file build/css/app.md.css
and replace the opacity '.01'  by '1' 

_Copied from original issue: driftyco/ionic-site#690_

**Comment by mhartington** [comment] 2016-07-29 17:57
_From @brandyscarney on July 11, 2016 19:57_

I don't understand this issue. Which modal is transparent? Is this an Ionic app or is this somewhere in the documentation? Thanks!

**Comment by mhartington** [comment] 2016-07-29 17:57
_From @zefrench on July 11, 2016 19:59_

There is a error in the file build/css/app.md.css
The line 6736 says the modal has .01 opacity, so if you test a modal in the ionic app 2 beta 10, the modal will be transparent.

**Comment by mhartington** [comment] 2016-07-29 17:57
_From @brandyscarney on July 11, 2016 20:1_

The opacity is added to the element when it animates open. I'm not seeing any issues with the modal transparency on the conference app: https://github.com/driftyco/ionic-conference-app

Do you have a plunker or github repo where we can reproduce this?

**Comment by mhartington** [comment] 2016-07-29 17:57
_From @zefrench on July 11, 2016 20:4_

No I don't but on the app I'm develop under this new beta I got the problem.
So I changed it directly in the app.md.scss file on the theming folder.

`modal-wrapper {
  opacity: 1;
  -webkit-transform: translate3d(0, 40px, 0);
  transform: translate3d(0, 40px, 0); }`

**Comment by brandyscarney** [comment] 2016-07-29 18:28
The only way I can reproduce this is by setting the mode directly in the url using `ionicMode=md` and setting the device to an iPad in Chrome. Are you doing something similar to this @zefrench?

**Comment by zefrench** [comment] 2016-07-29 19:47
Yes it is.

**Comment by brandyscarney** [comment] 2016-07-30 18:48
Ok I'm going to close this as a duplicate of https://github.com/driftyco/ionic/issues/7391 then. As a workaround you can use `ionicPlatform=android` or set the mode directly in the config:

```
ionicBootstrap(ConferenceApp, [ConferenceData, UserData], {
  mode: 'md' 
});
```

Could you add your use case for this on that issue? Thanks!

**Closed by brandyscarney** 2016-07-30 18:48 UTC
Labels: modals, platform:android
