### ISSUE TITLE
ionic2: Modal - Custom Providers are missing

### ISSUE THREAD

**Issue by graphefruit** [driftyco/ionic#7901] opened 2016-08-29 13:37 UTC
#### Short description of the problem:
If you create a modal overlay, which needs custom added providers, the providers are missing (import order was done).

#### What behavior are you expecting?
The providers exist, like in standard pages, after the import order.

**Steps to reproduce:**
1. Create custom provider
```
@Injectable()
export class UIService
```
2. Create Modal window: 
```
import {UIService} from '../../services/uiservice';
@Page({
  templateUrl: 'build/modals/rating/rating.html',
})
export class RateModal
```
3. Call modal window:
```
 let rateModal = this.modalCtrl.create(RateModal,{});
 rateModal.present();
```
**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 2.0.0-beta.37

**Occuring error:**
ORIGINAL EXCEPTION: No provider for UIService!

> browser_adapter.js:84 Error: Uncaught (in promise): EXCEPTION: Error in ./RateModal class RateModal_Host - inline template:0:0
ORIGINAL EXCEPTION: No provider for UIService!
ORIGINAL STACKTRACE:
Error: DI Exception
    at NoProviderError.BaseException [as constructor] (http://localhost:8100/build/js/app.bundle.js:5172:23)
    at NoProviderError.AbstractProviderError [as constructor] (http://localhost:8100/build/js/app.bundle.js:31828:16)
    at new NoProviderError (http://localhost:8100/build/js/app.bundle.js:31865:16)
    at ReflectiveInjector_._throwOrNull (http://localhost:8100/build/js/app.bundle.js:32862:19)
    at ReflectiveInjector_._getByKeyDefault (http://localhost:8100/build/js/app.bundle.js:32890:25)
    at ReflectiveInjector_._getByKey (http://localhost:8100/build/js/app.bundle.js:32853:25)
    at ReflectiveInjector_.get (http://localhost:8100/build/js/app.bundle.js:32662:21)
    at ElementInjector.get (http://localhost:8100/build/js/app.bundle.js:34433:48)
    at ReflectiveInjector_._getByKeyDefault (http://localhost:8100/build/js/app.bundle.js:32887:24)
    at ReflectiveInjector_._getByKey (http://localhost:8100/build/js/app.bundle.js:32853:25)
    at ReflectiveInjector_.get (http://localhost:8100/build/js/app.bundle.js:32662:21)
    at ElementInjector.get (http://localhost:8100/build/js/app.bundle.js:34433:48)
ERROR CONTEXT:
[object Object]
    at resolvePromise (http://localhost:8100/build/js/zone.js:538:32)
    at http://localhost:8100/build/js/zone.js:574:18
    at ZoneDelegate.invokeTask (http://localhost:8100/build/js/zone.js:356:38)
    at Object.onInvokeTask (http://localhost:8100/build/js/app.bundle.js:40544:41)
    at ZoneDelegate.invokeTask (http://localhost:8100/build/js/zone.js:355:43)
    at Zone.runTask (http://localhost:8100/build/js/zone.js:256:48)
    at drainMicroTaskQueue (http://localhost:8100/build/js/zone.js:474:36)

If you declare your modal as a "Component" and add the providers yourself everything works fine:
```
@Component({
  templateUrl: 'build/modals/rating/rating.html',
  providers: [UIService]
})
```
Greetings & Thanks in advance
Graphefruit

**Comment by jgw96** [comment] 2016-08-29 13:40
Hello! Thanks for using Ionic! As this issue is a duplicate of https://github.com/driftyco/ionic/issues/7160 I will be closing this issue for now.

**Closed by jgw96** 2016-08-29 13:40 UTC
Labels: modals, v2

**Comment by glaucocustodio** [comment] 2016-09-14 22:40
It's still happening, this is my `ionic info`:

Cordova CLI: Not installed
Gulp version:  CLI version 1.2.2
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X Yosemite
Node Version: v5.2.0
Xcode version: Xcode 7.2 Build version 7C68
