### ISSUE TITLE
Ng-model data binding does not work with ion-items

### ISSUE THREAD

**Issue by LookLikeAPro** [driftyco/ionic#3201] opened 2015-02-28 16:31 UTC
Data binding works properly with range slider when written like this.
```
<div class="range">
        <input type="range" ng-model="data">
</div>
```
But it does not work when it is not a div
```
<ion-item class="range">
        <input type="range" ng-model="data">
</ion-item>
```

**Comment by Ionitron** [comment] 2015-02-28 16:31
Greetings @LookLikeAPro!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3201). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3201)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by jmcenteno** [comment] 2015-03-21 22:39
Greetings,

I was having the same issue with select menus in versions rc.0 and rc.1. If the select menu is inside an ion-item directive, the value of its model won't change when an option is selected. 

Not sure if you have found a solution by now, but I solved my problem by setting ng-model to "$parent.data" instead of just "data". See example below.

http://codepen.io/anon/pen/XJoxzJ

**Comment by Ionitron** [comment] 2015-06-22 22:20
Greetings @LookLikeAPro!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-06-22 22:20 UTC
Labels: ionitron:closed

**Comment by rocco** [comment] 2016-02-12 00:05
the issue is still there in 1.2.4. not an ionic issue really, more an angular thing:
the ion-item directive uses its own child scope.
just use `$parent.data` as mentioned above by @jmcenteno

**Comment by mariano-aguero** [comment] 2016-10-05 16:53
I have version 1.3.0 and i have the same problem but i can solved thanks to @jmcenteno 

The example to solve the problem

`    <ion-content class="padding">
            <ion-list class="list-bordered">
                <label class="item item-input">
                    <span class="input-label">{{ "services:filter_by_date:input:from" | translate }}</span>
                    <input type="date" ng-model="$parent.dateFrom" ng-Required="true" return />
                </label>
                <label class="item item-input">
                    <span class="input-label">{{ "services:filter_by_date:input:to" | translate }}</span>
                    <input type="date" ng-model="$parent.dateTo" ng-Required="true" return />
                </label>
            </ion-list>
    </ion-content>
    <ion-footer-bar class="bottom-buttons-bar bottom-buttons-bar-with-bg" ng-if="!serviceDone">
        <button class="button button-block button-positive nm" ng-click="filterByDate($parent)">
            {{ "services:filter_by_date:button" | translate }}
        </button>
    </ion-footer-bar>
`
