### ISSUE TITLE
Application state in restoring from foreground

### ISSUE THREAD

**Issue by jafaripur** [driftyco/ionic#8392] opened 2016-10-01 21:19 UTC
#### Short description of the problem:

After open new application and restoring ionic2 app from foreground the state of the app not restored and again bootstarap from startup.

#### What behavior are you expecting?

This is normal in cordova or ionic2 application or not, the application state not restored when app comming from foreground.

I used in android.

**Steps to reproduce:**
1.  Open application
2.  Navigate to pages.
3.  Open another app or press to home button to application go to foreground
4- Restore application from foreground
5- Application start from bootstrap not from last state.

**Which Ionic Version?** 1.x or 2.x

2

**Comment by jgw96** [comment] 2016-10-03 00:59
Hello! Thanks for using Ionic! I unfortunately cannot reproduce this on my devices but do know exactly why this is happening. When putting an app in the background in Android (or any other mobile operating system) the app state is stored in memory. When you have a few apps open and in the background at a time (especially games), and are doing actions on the device these apps begin to take up a good bit of memory. Once a certain threshold is reached the operating system will begin to shut down apps in the background to relinquish memory to the device. This happens with any kind of app, native or hybrid. Since this is not an Ionic issue but is instead just normal behavior I will be closing this issue for now. Thanks for using Ionic!

**Closed by jgw96** 2016-10-03 00:59 UTC
Labels: v2
