### ISSUE TITLE
bug: Issues with forms in the `ion-slide-box`

### ISSUE THREAD

**Issue by rajeshwarpatlolla** [driftyco/ionic#4346] opened 2015-09-10 11:17 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>I have a modal, in which i have an `ion-slide-box`. Each of the `ion-slide` in inside the `ion-slide-box` has forms. When i am i the last form field in the first slide, and if i click on the `>` button in the keyboard accessory bar then the complete view is misplacing.
When we are in the last input field of the first slide, then `>` should automatically disable. This is happening if we don't use the slide box. I have searched the ionic forum, where few other people are also looking for a solution for this issue.

Please check these links for screenshots.
[Before i press > button](https://lh3.googleusercontent.com/3yK5NCDpMU6A_GIKceGiOx1_1spoKVJdoebpEDce0OZbkG4lbTSe9pLWtl1agkxgWwhYXBA36v1yCZaFaOvLH6_1KRSZi3k7hBi3H9Pnw0jYVjovHt5IKNhiWdLuXEI0bZTtiZbFDySoB5YSP0TJ7LYrRKGBxmBZrEQ_kP8gxTvocmIhBdxZZLGlHKpIMwfRjKzld9aWiUSy35-EZRait5QV2FV1RKEln3NFS8Prn-jx7lWvk6JEelTSgqZ0aL8CSwEqKoHfLOHs-ANHeQcQMwgOVy0lYDH6K9PuCqGpMLCOt3z4X5Co5E8Krj5I3uZG_3zHxcvmGZkC_6V-rDc3-5ylD7UwdAStWQNUQC-lHOpCQOvcNoXO6WQKGfGsQrygedXNQPb8CvF_rIEBkUL2Wx0yqD1RkxIKCVGYQ6p5QZRZEzP1U4ftko8A6I74HoVzKIcy5tro7MOlzfO_xuvnSq-07ac-RTFD13pA5FUhHDxReb-UHBOuvV-1MAsUkhtMNjwhfVagxb6I1RnCiXdhmcg=w382-h678-no)
[After i press > button](https://lh3.googleusercontent.com/m1PrFtPg8lCkn5d9CsEZDAa7A0O6h8XX1ecUuwtwxz5SMicebA7HYEa_9EBiAMVS_yUx0pJ1y4rxH-Wb45yTyMRs9yVUfK-ARPpe6VmoH7B3BOORL-VaYKqht2QVjUjl0aqS_vwDL2qOOtr1Vob6OMjcNJk-gg38UPZtPYOsjoiJ9S39pvLMzoM6cJknMJ7lYt1sm9Fm92MA8ohzuMFdK46A7a6IYbfM4a6yuWVlJdpehIKglXZVJgSUTj878J_Vhp5s9bSBBTvnclb61bFI2DoZa2b5tUbiZWxmHfOP9kLUT7jqiYKP_KP5LOBLIrG3uFvDEQywxyA3JVxcEHT4loqABLOXfvPTBCxWHAD5wgQLkZtsP-WEa029rjM-miYqBwouT4SjiBm1WT5nwB8Xpo5_tQXrSqSm1cGta7LhpGWw8yNX2TG7UM4oeSD6R4hS4Y3gyQoCgOaiWDZFd4fMRZ0SCXUWvmGReCH9VD2SJ4j8OnaU-wT_0PfQrFYRKBsCzh_7_1JInOcoQAWlBgds4jg=w382-h678-no)</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment] 2015-09-15 22:35
webkit will navigate through all form fields not hidden or disabled. Because of how slidebox works, they're not hidden or disabled, simply off screen. You'll want to disable those fields when you navigate to the next page. 

Are these the images you meant to link to? Could you reproduce this in a codepen to help us have something to test against?

**Comment by rajeshwar-fissionhq** [comment] 2015-09-16 04:01
So the `ion-slide-box` will refer to all the input fields, including the fields in the second `ionc-slide`?

**Comment by rajeshwarpatlolla** [comment] 2015-09-16 04:02
So the `ion-slide-box` will refer to all the input fields, including the fields in the second `ionc-slide`?

**Comment by niyando** [comment] 2015-10-12 05:33
@rajeshwarpatlolla were you able to find a wrokaround for this? I am facing a similar issue.

**Comment by rajeshwarpatlolla** [comment] 2015-10-12 05:35
Not exactly. We are just using the keyboard plugin to handle this scenario. Like, when the user is in the last text box in slide, we are hiding the keyboard accessory bar. It's kind of dirty solution.

**Comment by niyando** [comment] 2015-10-12 10:44
As @perrygovier said,
I was able to fix this by hiding content of inactive slides. Its also good to hide content of inactive slides to reduce memory footprint. Something that can become a concern when you have large number of slides.
Thanks!

**Comment by mlynch** [comment] 2015-12-09 01:41
Hey everyone, we just landed a new slider component that solves this issue. It's in master and will be in 1.2 To use it today, do this:

Will be back porting the delegate to work with it soon, but going to close since this should be solved now.

```html
<ion-slides options="options" slider="data.slider">
  <ion-slide-page>
    <form>
    </form>
  </ion-slide-page>
</ion-slides>
```

**Closed by mlynch** 2015-12-09 01:41 UTC
