### ISSUE TITLE
Input text/placeholder invisible on iOS 8.x/9.x (nightly)

### ISSUE THREAD

**Issue by biesbjerg** [driftyco/ionic#9501] opened 2016-12-05 17:04 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Input placeholder and text is invisible in iOS 8/9

![invisible-input](https://cloud.githubusercontent.com/assets/230182/20894381/74a2727c-bb15-11e6-989d-41e07cfce3ff.gif)

**Expected behavior:**
The text to be visible :)

**Steps to reproduce:**
Run the following repo on iOS 8.x/9.x:
https://github.com/biesbjerg/6228-ionic-keyboard-issues

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3-201612021933
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.9.0
ios-sim version: 5.0.12
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by biesbjerg** [comment] 2016-12-05 17:09
Playing around in safari (connected to simulator) it seems this is the culprit:
input.text-input.text-input-ios.ng-valid.ng-dirty.ng-touched {
  -webkit-transform: translate3d(-9999px, -177px, 0);
}

If I comment it out it works. Any idea why it is there?

**Comment by jgw96** [comment] 2016-12-05 22:54
Good find @biesbjerg and thanks for all the testing! Looks like this is a safari 8/9 bug with big transforms. Cant repro on chrome or safari 10.

**Comment by jgw96** [comment] 2016-12-06 16:12
Hello! Happy to report that this was just fixed in master with this commit https://github.com/driftyco/ionic/commit/eba2862e70340f4882e2584bd86183e859cb30d1. The basics of the issue is that we were not adding prefixes when we should have for the transform, which was still prefixed in iOS 8. Thanks!

**Closed by jgw96** 2016-12-06 16:12 UTC
Labels: v2
