### ISSUE TITLE
bug: quick click back button, will occur blank screen .

### ISSUE THREAD

**Issue by TongeJie** [driftyco/ionic#8891] opened 2016-10-25 06:11 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>when push three page , then quick click back button, will occur blank screen .
issue reproduce : https://github.com/TongeJie/ionic2-push-issue</span>

<span is-issue-template></span>

**Comment by manucorporat** [comment] 2016-10-25 10:12
Can you try against nightly?

```
npm install ionic-angular@nightly --save
```

**Comment by ShawnXu** [comment] 2016-10-25 15:05
Same here. "double tapping" the back button leads to blank screen.

**Comment by jgw96** [comment] 2016-10-25 19:15
Hello, thanks for using Ionic! I am going to close this issue as duplicate of https://github.com/driftyco/ionic/issues/8881.

**Closed by jgw96** 2016-10-25 19:15 UTC
