### ISSUE TITLE
hideWhen/showWhen not working on toolbar (CSS issue)

### ISSUE THREAD

**Issue by daviddk** [driftyco/ionic#6524] opened 2016-05-13 13:13 UTC
When using the hideWhen or showWhen directive, toolbar isn't hidden.

```
<ion-toolbar showWhen="android">
</ion-toolbar>

<ion-toolbar hideWhen="iOs">
</ion-toolbar>
```

I can see the CSS class being applied using dev tools, but the class gets overwritten by other CSS lines that are appended to the app.ios.css file later on in the build.

ios.app.css line 987:
.hidden-show-when {
    display: none;
}

ios.app.css line 7349: 
.toolbar {
    display: flex;
}

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.6
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v6.1.0
Xcode version: Xcode 7.3 Build version 7D175

**Comment by brandyscarney** [comment] 2016-05-13 17:48
Thanks for the issue! This is a duplicate of #6270 and will be fixed in the next release. There's a work around in this comment: https://github.com/driftyco/ionic/issues/6270#issuecomment-213097125 :smile:

**Closed by brandyscarney** 2016-05-13 17:48 UTC
Labels: platform:android, platform:ios, v2

**Comment by brandyscarney** [comment] 2016-05-13 17:49
Ah! I read the issue wrong, it isn't a duplicate, but it should still be fixed by the fix in that issue.
