### ISSUE TITLE
iOS 8 location warning status bar removes tabs from app

### ISSUE THREAD

**Issue by dijiadu** [driftyco/ionic#8574] opened 2016-10-08 07:43 UTC
#### Short description of the problem:
In iOS 8, when an app is using your location in the background, such as Google Maps, the status bar expands to 2 lines and displays a warning message.

If you have an app built with ionic2 and using tabs, when you switch to the ionic app whilst this status bar is displayed and then the status bar is removed by iOS, the tabs in your app will disappear.

#### What behavior are you expecting?

I expect the app to resize accordingly and the tabs to remain in the app.

**Steps to reproduce:**
1. Create an app using the tabs starter.
2. Install on a device running iOS 8 or later.
3. Run the app.
4. Switch to Google Maps and start navigation to a destination.
5. Switch back to the ionic tabs app.
6. Tabs will disappear.

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

Information about this feature
https://9to5mac.com/2014/06/04/apple-improves-location-services-in-ios-8-with-when-in-use-mode-visit-monitoring/

**Which Ionic Version?** 1.x or 2.x
2.0 beta 11

#### Plunker that shows an example of your issue
N/A

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 1.2.2
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.12.0
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by jgw96** [comment] 2016-10-10 15:34
Hello, thanks for using Ionic! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/6475.

**Closed by jgw96** 2016-10-10 15:34 UTC

**Comment by dijiadu** [comment] 2016-10-13 20:16
That ticket is about hiding the status bar and this is about tabs disappearing. Don't quite understand the connection there, so perhaps you can elaborate?
