### ISSUE TITLE
[bug]: `[no-padding]` gets override 

### ISSUE THREAD

**Issue by diosney** [driftyco/ionic#9484] opened 2016-12-04 17:22 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When adding `[no-padding]` to several elements, it gets overridden for other styles.

**Expected behavior:**

 This should not happen since when someone adds such attribute it really wants to be enforced. Maybe using `!important` in this case is allowed?

**Comment by brandyscarney** [comment] 2016-12-05 15:32
Can you test the latest nightly and see if this is still an issue? I made some changes here that should have fixed it: https://github.com/driftyco/ionic/issues/8765

```
npm install --save ionic-angular@nightly
````

**Comment by brandyscarney** [comment] 2017-01-24 19:45
I'm going to close this since it's been awhile since there was a reply and it should be fixed in latest. Please let me know if it's still an issue and include steps to reproduce if so. Thanks!

**Closed by brandyscarney** 2017-01-24 19:45 UTC
Labels: needs reply, v2
