### ISSUE TITLE
big bug on RC4

### ISSUE THREAD

**Issue by yozman** [driftyco/ionic#9741] opened 2016-12-21 05:12 UTC
there is a promise bug at RC4

when I use option `{ dismissOnPageChange: true }`

**Comment by infinnie** [comment] 2016-12-21 06:04
#9659

**Comment by brandyscarney** [comment] 2016-12-21 17:41
Thanks for the issue, this is a duplicate of https://github.com/driftyco/ionic/issues/9589 and it has been fixed in the latest nightly. Please see the last comment on that issue for how to install the nightly version. Thanks!

**Closed by brandyscarney** 2016-12-21 17:41 UTC
