### ISSUE TITLE
iOS 10 back animation easing got refined  

### ISSUE THREAD

**Issue by jrencz** [driftyco/ionic#7887] opened 2016-08-27 09:15 UTC
#### Short description of the problem:
I recently updated my iPhone to iOS 10 beta 7 and I noticed that back view animation got a little bit different easing

#### What behavior are you expecting?
I'd expect for Ionic app to have easing similar to native on iOS 10

**Steps to reproduce:**
1. Prepare 2 devices: one with iOS 9 and one with iOS 10
2. Open any native app in both, compare back view animation easing. On 10 it's a bit more ease-out than on 9
3. Open Ionic app. Easing is the same (I checked on Ionic 1.x)

**Which Ionic Version?** 1.x or 2.x
1.x but I found no trace of different handling of iOS 10 in either version

**Comment by jrencz** [comment] 2016-08-27 09:16
I'm not sure in what version of iOS 10 beta it got different. Beta 7 is the first I installed

**Comment by jgw96** [comment] 2016-08-29 13:34
Hello! Thanks for opening an issue with us! I am going to be closing this issue as a duplicate of https://github.com/driftyco/ionic/issues/6901 since that is the tracking issue for iOS10 issues. Would you mind posting your issue on that issue? Thanks!

**Closed by jgw96** 2016-08-29 13:34 UTC
Labels: animation, platform:ios, v1
