### ISSUE TITLE
if a  slidebox is be cached and then open  a modal in a new state,the original  slidebox's width becames 0px

### ISSUE THREAD

**Issue by chenjiale** [driftyco/ionic#2978] opened 2015-01-22 11:02 UTC
if a  slidebox is be cached and then open  a modal in a new state,the original  slidebox's width becames 0px 
it was like this https://github.com/driftyco/ionic/issues/360
version Ionic, v1.0.0-beta.14
forget my poor English :(

**Comment by Chuckv01** [comment] 2015-01-30 23:04
I was running into the same issue. Set the cache to be disabled on the slider by adding cache: false to the state. Seemed to get around the problem for now.

**Comment by chenjiale** [comment] 2015-01-31 09:42
@Chuckv01  Set cache false to the satae  is a way,but  i want use  the cache :(

**Comment by MartinMa** [comment] 2015-02-04 10:20
This issue is a duplicate of #2817.

**Comment by adamdbradley** [comment] 2015-04-13 20:35
This should be fixed now: https://github.com/driftyco/ionic/commit/040dabf2c9a8a6c3fd154e4e27391299c5978939

**Closed by adamdbradley** 2015-04-13 20:35 UTC
