### ISSUE TITLE
tab Page reloading every time there is a navigation to another page

### ISSUE THREAD

**Issue by Abderrahmane-H** [driftyco/ionic#11123] opened 2017-04-07 17:13 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I have an application updated from ionic 2 to ionic 3 following the given instructoins in changelogs,
after the update everything is working fine expect the navigation, every time the app navigate from 
a  page (source) to another page (destination), the source page reloads. Maybe it has something to do with the lazy loading.

**Comment by jgw96** [comment] 2017-04-07 18:42
Hello, thanks for opening an issue with us. Would you mind sharing a repo that we can use to reproduce this issue?

**Comment by Daskus1** [comment] 2017-04-07 19:15
I think this is related to #11015. 
@jgw96 there I provided a repo where you can reproduce the issue. I added a `console.log` in `ionViewDidLoad()` of every page and it logs out every time a tab is clicked the first time and also if it is clicked two times consecutively.

**Comment by soumak77** [comment] 2017-04-08 22:21
This might be resolved by https://github.com/driftyco/ionic/pull/11084

**Comment by youssmak** [comment] 2017-04-09 17:11
Your PR fix it

**Comment by jgw96** [comment] 2017-04-13 21:25
Hello all, after further review I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/11015.

**Closed by jgw96** 2017-04-13 21:25 UTC
Labels: needs info, v3
