### ISSUE TITLE
[v2] Ion-infinite-scroll error when leaving page

### ISSUE THREAD

**Issue by jboothe** [driftyco/ionic#5760] opened 2016-03-07 19:51 UTC
Just wanted to bring to your attention the following error when leaving a page that uses `ion-infinite-scroll`:

`EXCEPTION: TypeError: Cannot read property 'removeEventListener' of null`

      <ion-infinite-scroll (infinite)="doInfiniteScroll($event)">
        <ion-infinite-scroll-content></ion-infinite-scroll-content>
      </ion-infinite-scroll>

Reproduce by:

1. Add the above code to a list page
2. Navigate to that page
3. Navigate to another page
4. View console output

My system information:
```
Cordova CLI: 6.0.0
Ionic Version: 2.0.0-beta.2
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
ios-deploy version: 1.8.5
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v4.3.1
Xcode version: Xcode 7.2.1 Build version 7C1002
```

Not positive, but this could also be related to [this similar issue](https://forum.ionicframework.com/t/ion-refresher-typeerror-cannot-read-property-removeeventlistener-of-null/45298).

**Comment by adamdbradley** [comment] 2016-03-07 22:41
I updated this test to have the ion-infinite-scroll within a nav, but I'm not getting an error when going to and from the page: https://github.com/driftyco/ionic/tree/2.0/ionic/components/infinite-scroll/test/basic

What do I need to update so I can replicate that error? Thanks

**Comment by jboothe** [comment] 2016-03-08 03:32
Thanks, Adam for taking a look at this. Here are the steps to reproduce. 

`> ionic start tut tutorial --v2 --ts`
`> cd tut`

Add the following code:
```
// list.html
...
</ion-list>

  <ion-infinite-scroll (infinite)="doInfiniteScroll($event)">
    <ion-infinite-scroll-content></ion-infinite-scroll-content>
  </ion-infinite-scroll>

  <div *ngIf="selectedItem" padding>
```
then... 

```
// list.ts
...
doInfiniteScroll(infiniteScroll) {
    console.log('Begin async operation');
  }
```
then...
`> ionic serve`

Click menu > My First List
Click menu > Hello Ionic

This error is thrown twice:
`EXCEPTION: TypeError: Cannot read property 'removeEventListener' of null`

![screen shot 2016-03-07 at 10 28 43 pm](https://cloud.githubusercontent.com/assets/3723481/13591167/09bbc91e-e4b4-11e5-8a7f-ce94e93857f5.png)

**Comment by jboothe** [comment] 2016-03-08 18:31
I noticed something that may help zero in on the issue. If you do this, **no error** is thrown:

Click menu > My First List
Click a list item
Click the Back arrow

However, clicking *menu > My First List*, then *menu > Hello Ionic*, the error **is** thrown.

**Comment by BugsBunnyBR** [comment] 2016-03-08 20:39
It seems to happen with the ion-refresher too.
![bug1](https://cloud.githubusercontent.com/assets/70573/13615544/96edf8c0-e554-11e5-84b1-0c1f718c3a56.png)

**Comment by mebibou** [comment] 2016-03-11 08:45
Yep confirming I have the same problem since I put the `<ion-refresher>` on my page, and leaving the page I always get this error

**Comment by iignatov** [comment] 2016-03-13 19:27
I can confirm that the bug still exists in `beta.3`. As @jboothe mentioned, the exception is thrown when leaving the page that contains `<ion-infinite-scroll>` component. Also, as pointed out by the others, the bug affects also the `<ion-refresher>` component.

**Steps to reproduce:**
1. Open: https://plnkr.co/edit/qh5So0FetPKKzjYu3CYf?p=preview
2. Follow the instructions in the demo environment.

**Other information:**
I did some debugging and realized that the exception is thrown when the `InfiniteScroll` component tries to remove an event-handler after the element to which the handler is attached is already removed by `Content.ngOnDestroy()`. The removal procedure is triggered by `InfiniteScroll.ngOnDestroy()`, which for some reason is called after `Content.ngOnDestroy()` (InfiniteScroll's host component) has been already completed. A null-check in the function returned by `Content._addListener()` should fix the problem but I'm not sure if the remaining handler will be removed automatically. In theory when the component's `ngOnDestroy()` is called before the one of its host component has completed, everything should work fine, but I have no idea why in practice it's called after. I guess that it might be either async by design (without a guarantee which is called first) or due to a bug in Angular 2.

```ts
export class Content extends Ion {
  // ...
  private _addListener(type: string, handler: any): Function {
    if (!this.scrollElement) { return; }

    // ensure we're not creating duplicates
    this.scrollElement.removeEventListener(type, handler);
    this.scrollElement.addEventListener(type, handler);

    return () => {
      // NOTE: The exception is thrown here, this.scrollElement is NULL.
      // NOTE: Triggered by InfiniteScroll._setListeners(false) after Content.ngOnDestroy().
      // this.scrollElement && // <- this should fix the problem, but what about the remaining handler?
      this.scrollElement.removeEventListener(type, handler);
    }
  }
  // ...
  // NOTE: Executed and completes before the one of its nested component.
  ngOnDestroy() {
    this._scLsn && this._scLsn();
    // NOTE: The scrollElement is destroyed before InfiniteScroll removes the handler.
    this.scrollElement = this._scLsn = null;
  }
  // ...
}
```

```ts
export class InfiniteScroll {
  // ...
  // NOTE: Executed later than Content.ngOnDestroy().
  ngOnDestroy() {
    // NOTE: This triggers the remove function returned by Content._addListener().
    this._setListeners(false);
  }
}
```

**Which Ionic Version?** 2.x


**Run `ionic info` from terminal/cmd prompt:**

```
Your system information:

Cordova CLI: 6.0.0
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
OS: Windows 8.1
Node Version: v5.8.0
```

**Comment by thiphariel** [comment] 2016-03-18 09:50
Confirming same bug on <code>ion-refresher</code> too. Back button & swipe back throws the error.

**Comment by apat183** [comment] 2016-03-19 12:54
Confirmed same for me when adding `ion-refresher`.

`
Your system information:

Cordova CLI: 6.0.0
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
ios-deploy version: 1.8.5 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v5.4.0
Xcode version: Xcode 7.2 Build version 7C68 
`

**Comment by tuongaz** [comment] 2016-03-22 05:15
I got the same issue

**Comment by wangtiantian2016** [comment] 2016-03-25 08:21
I got the same issue.

Your system information:

Cordova CLI: 6.0.0
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
OS: Windows 7 SP1
Node Version: v4.3.1

**Comment by cperez1087** [comment] 2016-03-30 19:01
Experiencing same problem. 

My system info:
Cordova CLI: 6.1.0 (cordova-lib@undefined)
Gulp version: CLI version 3.9.1
Gulp local: Local version 3.9.1
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.23
Ionic App Lib Version: 2.0.0-beta.13
Node Version: v5.9.1

**Comment by Artfloriani** [comment] 2016-04-03 13:54
@warner-pinz I guess we have to wait til beta.4

**Comment by iignatov** [comment] 2016-04-03 21:25
@warner-pinz You could apply the [fix](https://github.com/trongrg/ionic/commit/05823f9e62fe80f7156ada830d2399a76a2ac52a) directly in your project:

0. From inside of your project's folder open the following path:
`node_modules/ionic-angular/components/content/content.js`

0. Search for this string:
`_this.scrollElement.removeEventListener(type, handler);`

0. Add a new line right before it and there paste the following:
`if (!_this.scrollElement) { return; }`

0. Save the file.

0. The problem should be fixed.

**Comment by denkomanceski** [comment] 2016-04-04 11:16
Yep, I have the same problem.

**Comment by adamdbradley** [comment] 2016-04-11 03:24
Is this still an issue with beta4?

**Comment by thiphariel** [comment] 2016-04-11 07:32
@adamdbradley Hey, I tried, and the problem is solved form me, but with <code>ion-refresher</code> as mentionned (https://github.com/driftyco/ionic/issues/5760#issuecomment-198284301)
So it's probably solved for <code>ion-infinite-scroll</code> too.

Waiting for confirmation :)

Thanks !

**Comment by perdjurner** [comment] 2016-04-11 07:55
Fixed for me.

**Comment by adamdbradley** [comment] 2016-04-11 20:41
Great thanks!

**Closed by adamdbradley** 2016-04-11 20:41 UTC
Labels: infinitescroll, platform:ios, refresher, v2

**Comment by iignatov** [comment] 2016-04-11 20:55
I updated the [demo plunker environment](https://plnkr.co/edit/h7gBiz9TCRfx3LDeXBzs?p=preview) to `beta.4` and can confirm that the problem is fixed for both `<ion-infinite-scroll>` and `<ion-refresher>`.

**Comment by prathyushp1** [comment] 2016-05-25 11:15
thanks problem fixed....thankyou IIgnatov...
