### ISSUE TITLE
bug: White flash appearing when switching between tabs on Android

### ISSUE THREAD

**Issue by wonderdogone** [driftyco/ionic#3907] opened 2015-06-09 08:42 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>when switching between tabs ONLY on Android platform, the app show a white flash. This is in 1.0.0 stable. Not using crosswalk.
Forum post http://forum.ionicframework.com/t/white-flash-appearing-when-switching-between-tabs-on-android-in-1-0-0-stable/24774</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-06-09 08:42
Greetings @wonderdogone!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3907). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3907)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by ispieter** [comment] 2015-07-13 12:29
Any word about the status of this issue?

**Comment by GentryRiggen** [comment] 2015-08-26 22:40
Having same issue. Any updates?

**Comment by hadar111** [comment] 2015-09-14 14:06
+1

**Comment by mhartington** [comment] 2015-09-14 14:08
Please provide a minimal example that has this issue.

**Comment by hadar111** [comment] 2015-09-14 14:13
Just create a new ionic app (tabs template) change the background to any color either then white. build and run on android device (4.4, i'm tested on nexus 5) and you will notice that there is a white flick for few millis on every tab change.

**Comment by GentryRiggen** [comment] 2015-09-14 14:14
I have found that this is due to ion-header-bar being redefined in each view. I moved ion-header-bar to my main layout template and no longer see the flicker. I believe the default generated project puts the header bar in each view which is why you see it there as well.

**Comment by hadar111** [comment] 2015-09-14 14:21
the 'ion-header-bar's is automatically generated for me, where (and how) you manually use it ?

**Comment by mhartington** [comment] 2015-09-14 14:22
So @GentryRiggen you mean the ion-nav-bar?

**Comment by GentryRiggen** [comment] 2015-09-14 14:26
@mhartington I am using ion-side-menu with a ion-tabs inside of the ion-side-menu-content. 
```
<ion-side-menus>
  <ion-side-menu side="left" class="left-side-menu">
    <ion-content drag-content="false" overflow-scroll="false" direction="y" delegate-handle="leftMenu">
      <div class="list">
        <a menu-close class="item item-icon-left" >Something</a>
        <a menu-close class="item item-icon-left" >Something</a>
        <a menu-close class="item item-icon-left" >Something</a>
      </div>
    </ion-content>
  </ion-side-menu>

  <ion-side-menu-content>
    <ion-header-bar align-title="center" class="bar-positive">
      <button class="button button-icon icon ion-navicon" menu-toggle="left"></button>
      <div class="titles">
            <h>TITLE</h1>
      </div>
    </ion-header-bar>

    <ion-tabs class="tabs-positive tabs-icon-only dark-background">
      <ion-tab>
        <ion-nav-view name="tab-1"></ion-nav-view>
      </ion-tab>

      <ion-tab>
        <ion-nav-view name="tab-2"></ion-nav-view>
      </ion-tab>

      <ion-tab>
        <ion-nav-view name="tab-3"></ion-nav-view>
      </ion-tab>
    </ion-tabs>
  </ion-side-menu-content>

</ion-side-menus>
```

**Comment by mhartington** [comment] 2015-09-14 14:28
Don't use the ion-header-bar for that, use the ion-nav-bar.

**Comment by hadar111** [comment] 2015-09-14 20:46
@mhartington Im using the 'ion-nav-bar' and the screen flickering (while moving between tabs)...
so how do you suggest to fix it ?

**Comment by wonderdogone** [comment] 2015-09-14 22:32
the simple tabs "starter" from ionic built for android shows the flash between navigating and that i believe uses ion-nav-bar.

**Comment by mhartington** [comment] 2015-09-14 23:33
Hmm, I'm not seeing it in my tests.

https://youtu.be/_ja8a08iSPE

**Comment by hadar111** [comment] 2015-09-15 11:08
You can see it in the video .. It's the white screen flash when you change tabs.. It appears for just few milliseconds... If you want the see that more clearly change the background color to red, blue or any dark color .

**Comment by mhartington** [comment] 2015-09-15 13:32
Are you talking about the fading nav bar

**Comment by didbarbosa** [comment] 2015-09-17 17:26
He is talking about the full white screen that briefly appears when you switch tabs.
You can clearly see it in your video when you switch the first time from  "Status" to "Chats". But it actually appears every time.

**Comment by hadar111** [comment] 2015-09-20 21:51
@mhartington I attached a video form my app (slow motion) you can clearly see it append there.
I would like to take a action and help you guys to solve that issue, but I need at least a start point from you.. where should I start ? 

youtube link : https://youtu.be/TTuNPlL6Fmg

Thanks.

**Comment by didbarbosa** [comment] 2015-09-21 23:14
I've looked at the code and to me the error is in the tabSelected function (ionTab directive)
It seems to hide the previous tab before showing the new one.

This dirty hack i've made seem to work. But I'd love to see a proper fix.
Just add a timeout around $ionicViewSwitcher.viewEleIsActive(childElement, false);

Line 55025 of ionic.bundle.js
```javascript
$timeout(function () {
 $ionicViewSwitcher.viewEleIsActive(childElement, false);
}, 100);
```

**Comment by lloy0076** [comment] 2015-09-25 12:34
This is happening to me with:

*  Ionic, v1.0.1
*  Cordova 5.3.3

I'm running Android 5.1.1 on a Nexus 4.

To reproduce it, I just simply make a "tabs" starter app, change the colour of the navbar to blue (e.g. by changing -stable to -positive) and the flickering becomes obvious. It does actually flicker with the white navbar but you can't see white on white flickering.

I have attempted to add styles to force the transition-time to 0ms on Android and verified that the app has applied these styles to any header item by checking with an attached chrome inspector and inspecting the computed CSS values. I double checked by removing the styles and verifying they went from 0ms to some other number (0.2ms or 0.5ms - and actually about as fast as the flashing effect).

I tried doing @didbarbosa fix but Chrome on the browser and the phone app both complained that $timeout was not defined. When I logged the value of $timeout, it was indeed not defined.

**Comment by didbarbosa** [comment] 2015-09-25 12:42
@lloy0076 you need to inject it into the directive

```javascript
IonicModule
.directive('ionTab', [
  '$compile',
  '$ionicConfig',
  '$ionicBind',
  '$ionicViewSwitcher',
  '$timeout',
function($compile, $ionicConfig, $ionicBind, $ionicViewSwitcher,$timeout) {
```

**Comment by lloy0076** [comment] 2015-09-25 12:57
@didbarbosa - Actually I just noticed that my version of Ionic isn't the latest release; thus I changed my "bower.json" to read:

  {
    "name": "HelloIonic",
    "private": "true",
    "devDependencies": {
      "ionic": "driftyco/ionic-bower#~1",
      "platform.js": "platform#~1.3.0"

...and would you believe it theres no flickering even without the $timeout solution...

Maybe if you tried the same with the CSS transition solution it might just "fix" itself - although I hate problems that magically fix themselves like that.

**Comment by didbarbosa** [comment] 2015-09-25 13:15
Yes it seems to be disapeared with the nightly release.
Good news :)

**Comment by didbarbosa** [comment] 2015-09-25 13:57
Actually it is not fixed for me.

**Comment by hadar111** [comment] 2015-09-26 11:20
not fixed for me 2 :\

**Comment by rollback91** [comment] 2015-10-06 13:29
Any news about this issue?

**Comment by harryzun** [comment] 2015-10-07 06:40
I have this issue on iOS as well.

**Comment by simplesmiler** [comment] 2015-10-07 17:05
@harryzun regarding iOS please see https://github.com/driftyco/ionic/issues/4395

**Comment by Zorgatone** [comment] 2015-10-09 07:55
On iOS it's not the same issue

**Comment by gentlemanjohn** [comment] 2015-10-13 15:27
I just started noticing this on Android too sometime after I upgraded to v1.1.  Not sure when it started though.

**Comment by wonderdogone** [comment] 2015-10-14 10:44
it started around v1

**Comment by arenddeboer** [comment] 2015-10-25 17:38
If anyone has a (temporary) fix, I would love to hear it.

**Comment by capellmarcos** [comment] 2015-10-29 22:06
I'm the same bug... anybody have more info?? :octopus:

**Comment by EnSabanNur** [comment] 2015-11-03 01:48
Probably not related, but I had a similar issue earlier, and for some bizarre reason deleting `cache: false` from my state definition for the offending sibling tab state cleared the issue for us. I have zero idea why, as we're using this same pattern, with the same controller+template combo, in 3 other places in our tab setup with out issue.

**Comment by andreialecu** [comment] 2015-11-21 15:22
I tracked this down to this line:
https://github.com/driftyco/ionic/blob/af1bfef327e685585244c6051c4d38b98aa6c62a/js/angular/service/viewSwitcher.js#L194

```javascript
 if (renderStart && renderEnd) {
            // CSS "auto" transitioned, not manually transitioned
            // wait a frame so the styles apply before auto transitioning
            $timeout(onReflow, 16);

          } else if (!renderEnd) {
```

It's the cause there's a one frame flicker when tabs are switched, because the new tab is not set to visible until 16 ms later. 

I'm not sure what the point of that line is when tabs are involved, but if you replace the `$timeout` call with a simple method call of `onReflow()`, perceived performance is greatly improved and there is no more flicker. Not even in the tab bar.

@mhartington any thoughts regarding this? Perhaps it should be made configurable at the very least.

**Comment by andreialecu** [comment] 2015-11-21 17:13
Opened PR https://github.com/driftyco/ionic/pull/4654

**Comment by didbarbosa** [comment] 2015-11-21 17:57
Very well done!
Fixes the issue to me.

Thanks a lot mate.

**Comment by Requiescat** [comment] 2015-12-01 03:15
Didn't work for me... I've updated my ionic-angular.j file but I see no change even if I'm increasing the initial timeout value. Am I missing something? 
For the nav bar flickering I used this fix https://forum.ionicframework.com/t/flickering-when-navigating-via-tabs-on-android/27281 but now content is it flickering.

**Comment by Requiescat** [comment] 2015-12-01 09:26
Finally it's working but it's still flickering once the first time for each tab, any idea why?

**Comment by fdu-axiometrics** [comment] 2015-12-10 16:02
Is there any release plan on this issue? 1.2 or 1.3 ?

**Comment by ispieter** [comment] 2015-12-10 20:51
It's included in the recent 1.2 release.

**Comment by FreezeSoul** [comment] 2015-12-31 13:22
+1 , is there any other solutions?

**Comment by wonderdogone** [comment] 2016-01-02 21:07
wow this is still going on.eh..Was figuring the core team would have a good idea what this wasAnyone have a good pointer to source code we might start experimenting with?

**Comment by mlynch** [comment] 2016-01-02 21:15
Did 1.2 fix this? There was a commit in there that should have addressed this issue.

**Comment by chooseapp** [comment] 2016-01-04 09:09
The bug is still here on 1.2 to 1.2.2

**Comment by chooseapp** [comment] 2016-01-04 22:56
I tried again and it is solved if you put : 
```
ionic.requestAnimationFrame(onReflow);  
```
as he said, and not : 
```
$timeout(function() {
              ionic.requestAnimationFrame(onReflow);
            });
```
Obviously, $timeout is doing something

**Comment by andreialecu** [comment] 2016-01-04 23:00
@mlynch maybe you remember what this was for? https://github.com/driftyco/ionic/commit/d0246cf975bb4022eb890d3b0c28964e3065644c#diff-e25bdd32bda2f4f00f01c823ec86b1f3

Seems to have broken it again.

**Comment by chooseapp** [comment] 2016-01-04 23:08
Maybe this is why : 

> if code is queued using $timeout, it should run after the DOM has been manipulated by Angular, and after the browser renders (which may cause flicker in some cases)

**Comment by mlynch** [comment] 2016-01-05 01:38
Reviewing for 1.2.5

**Comment by mlynch** [comment] 2016-01-05 01:43
Unfortunately, this broke #4782 which caused the back view to sometimes not animate correctly. Removing `$timeout` is probably too simplistic of a solution for this.

**Comment by AdrienDC** [comment] 2016-01-08 05:08
still have the issue even when I remove the timeout..

**Comment by luco** [comment] 2016-01-14 19:01
+1

**Comment by brentoneill** [comment] 2016-01-16 16:18
Have this issues as well...

**Comment by balicekt** [comment] 2016-01-18 01:13
+1

**Comment by feliksalbright** [comment] 2016-01-18 22:39
+1

**Comment by feliksalbright** [comment] 2016-01-18 22:46
note, updating your bower.json helps (correct highlighting), but there is a slight delay as mentioned

{
  "name": "HelloIonic",
  "private": "true",
  "devDependencies": {
    "ionic": "driftyco/ionic-bower#1.7.12", //HERE, MAKE SURE IT'S UPDATED
    "aws-sdk-js": "~2.0.9",
    "bootstrap": "~3.2.0",
    "platform.js": "platform#~1.3.1"
  }
}

Anyway, the slight flash is only on android, and it's just a fraction of a second.

**Comment by sean-hill** [comment] 2016-01-19 20:38
Can anyone confirm that `1.2.3 "copenhagen"` fixes this issue?

**Comment by sean-hill** [comment] 2016-01-19 21:10
@mhartington @mlynch I can confirm this is still not working property with version 1.2.3. Take a look at these sequence of screenshots.

I'm first starting on my Bills tab like this:
![screen shot 2016-01-19 at 2 05 26 pm](https://cloud.githubusercontent.com/assets/1205866/12432036/155a8d2e-beb6-11e5-8766-3e968bf86e8f.png)

I then tap on my Roommates tab and the following steps occur (which causes the blink):

1. App says "Bills" for title but showing the cached "Roommates" tab
![screen shot 2016-01-19 at 2 05 38 pm](https://cloud.githubusercontent.com/assets/1205866/12432051/252b97a2-beb6-11e5-8cb6-f929ed5d32cc.png)

2. App then removes all content, but still shows "Bills" title
![screen shot 2016-01-19 at 2 05 48 pm](https://cloud.githubusercontent.com/assets/1205866/12432065/40878ba0-beb6-11e5-9e96-4e549db5286d.png)

3. App shows "Roommates" content
![screen shot 2016-01-19 at 2 05 59 pm](https://cloud.githubusercontent.com/assets/1205866/12432076/4f963466-beb6-11e5-9bea-d2b90bf484ed.png)

4. App fades in "Roommates" title
![screen shot 2016-01-19 at 2 06 15 pm](https://cloud.githubusercontent.com/assets/1205866/12432084/57bfed76-beb6-11e5-8e28-18ba639cd2fd.png)

With all of these steps combined it creates a hideous flicker when switching tabs.

**Comment by sean-hill** [comment] 2016-01-19 22:36
Hey I realized that my bug was an issue with using SQLite in my application. Sorry for the confusion.

**Comment by mitiaptest** [comment] 2016-01-28 17:09
+1

**Comment by iReal** [comment] 2016-01-29 06:22
+1

**Comment by princefr** [comment] 2016-02-04 11:11
+1

**Comment by mitiaptest** [comment] 2016-02-04 11:54
Its seems like issue with timeout

**Comment by princefr** [comment] 2016-02-04 23:17
the issue just vanished for me! the issue was related to the way i had built my tabs!
make sure that you build it in the good way, navigation inside tabs too. take care about controllers parents ==> child 

no more white flash

**Comment by ilyastam** [comment] 2016-02-07 01:45
@princefr could you plz elaborate?

**Comment by casper123** [comment] 2016-02-10 11:28
For iOS, I had to replace css[ionic.CSS.TRANSITION_DURATION] with css.WebkitTransition in ionic.bundle.js line 47715 and 47750

`// iOS Transitions
  // -----------------------
  provider.transitions.views.ios = function(enteringEle, leavingEle, direction, shouldAnimate) {

    function setStyles(ele, opacity, x, boxShadowOpacity) {
      var css = {};
      css.WebkitTransition = d.shouldAnimate ? '' : 0;
      css.opacity = opacity;
      if (boxShadowOpacity > -1) {
        css.boxShadow = '0 0 10px rgba(0,0,0,' + (d.shouldAnimate ? boxShadowOpacity * 0.45 : 0.3) + ')';
      }
      css[ionic.CSS.TRANSFORM] = 'translate3d(' + x + '%,0,0)';
      ionic.DomUtil.cachedStyles(ele, css);
    }

    var d = {
      run: function(step) {
        if (direction == 'forward') {
          setStyles(enteringEle, 1, (1 - step) * 99, 1 - step); // starting at 98% prevents a flicker
          setStyles(leavingEle, (1 - 0.1 * step), step * -33, -1);

        } else if (direction == 'back') {
          setStyles(enteringEle, (1 - 0.1 * (1 - step)), (1 - step) * -33, -1);
          setStyles(leavingEle, 1, step * 100, 1 - step);

        } else {
          // swap, enter, exit
          setStyles(enteringEle, 1, 0, -1);
          setStyles(leavingEle, 0, 0, -1);
        }
      },
      shouldAnimate: shouldAnimate && (direction == 'forward' || direction == 'back')
    };

    return d;
  };

  provider.transitions.navBar.ios = function(enteringHeaderBar, leavingHeaderBar, direction, shouldAnimate) {

    function setStyles(ctrl, opacity, titleX, backTextX) {
      var css = {};
      css.WebkitTransition = d.shouldAnimate ? '' : '0ms';
      css.opacity = opacity === 1 ? '' : opacity;

      ctrl.setCss('buttons-left', css);
      ctrl.setCss('buttons-right', css);
      ctrl.setCss('back-button', css);

      css[ionic.CSS.TRANSFORM] = 'translate3d(' + backTextX + 'px,0,0)';
      ctrl.setCss('back-text', css);

      css[ionic.CSS.TRANSFORM] = 'translate3d(' + titleX + 'px,0,0)';
      ctrl.setCss('title', css);
    }

    function enter(ctrlA, ctrlB, step) {
      if (!ctrlA || !ctrlB) return;
      var titleX = (ctrlA.titleTextX() + ctrlA.titleWidth()) * (1 - step);
      var backTextX = (ctrlB && (ctrlB.titleTextX() - ctrlA.backButtonTextLeft()) * (1 - step)) || 0;
      setStyles(ctrlA, step, titleX, backTextX);
    }

    function leave(ctrlA, ctrlB, step) {
      if (!ctrlA || !ctrlB) return;
      var titleX = (-(ctrlA.titleTextX() - ctrlB.backButtonTextLeft()) - (ctrlA.titleLeftRight())) * step;
      setStyles(ctrlA, 1 - step, titleX, 0);
    }

    var d = {
      run: function(step) {
        var enteringHeaderCtrl = enteringHeaderBar.controller();
        var leavingHeaderCtrl = leavingHeaderBar && leavingHeaderBar.controller();
        if (d.direction == 'back') {
          leave(enteringHeaderCtrl, leavingHeaderCtrl, 1 - step);
          enter(leavingHeaderCtrl, enteringHeaderCtrl, 1 - step);
        } else {
          enter(enteringHeaderCtrl, leavingHeaderCtrl, step);
          leave(leavingHeaderCtrl, enteringHeaderCtrl, step);
        }
      },
      direction: direction,
      shouldAnimate: shouldAnimate && (direction == 'forward' || direction == 'back')
    };

    return d;
  };`

**Comment by iReal** [comment] 2016-02-10 15:01
Seems to be fixed for me when I changed this line https://github.com/driftyco/ionic/blob/master/js/angular/service/viewSwitcher.js#L142 to be:
```js
callback && ionic.requestAnimationFrame(callback);
```
Not sure if it's a correct way to fix this though.

**Comment by lloy0076** [comment] 2016-02-10 21:53
Does this occur on some releases of iOS too (remembering that the report is on Android releases)?

**Comment by AhsanAyaz** [comment] 2016-02-11 19:41
+1 
flashes on android..

**Comment by pavei** [comment] 2016-02-12 23:35
1+

**Comment by brentoneill** [comment] 2016-02-13 15:28
+1

**Comment by Harish-here** [comment] 2016-02-15 06:37
guys just "**cache : true**" in your "**state**" so that your page been cached before extract and render goes smoothly

**Comment by mitiaptest** [comment] 2016-02-15 07:20
@Harish-here What about first time ?

**Comment by tgensol** [comment] 2016-02-15 09:17
Yeah, it is really not a good idea to use cache: true only for these purpose

**Comment by AhsanAyaz** [comment] 2016-02-15 09:31
@Harish-here . . I have an app that uses the same state for different pages. I.e. it is a detail view which takes some $state params. Since its the same view with different content, I can't use cache:false :) 
And it doesn't seem to be a good idea for this particular problem either

**Comment by robertorebollo** [comment] 2016-02-25 12:21
Still the same problem here running 1.2.4-nightly-1917

**Comment by alexissusset** [comment] 2016-02-27 22:40
+1

**Comment by brentoneill** [comment] 2016-03-03 21:45
@princefr - yes, please elaborate on what the proper markup would be for the tabs to alleviate this issue

**Comment by saqueib** [comment] 2016-03-16 14:34
@princefr please if you can elaborate on the tab structure

**Comment by joelbowen** [comment] 2016-03-22 20:27
This is still an issue for me and quite frustrating. Is there any movement, or any understood resolution?

**Comment by alysdal** [comment] 2016-03-22 20:32
+1

**Comment by tgensol** [comment] 2016-03-22 20:33
+1

**Comment by mhartington** [comment] 2016-03-22 22:12
Looking into this tomorrow folks! :grin:

**Comment by jgw96** [comment] 2016-03-22 23:18
There is a related issue with iOS that I will link here later tonight. I was able to repro it.

**Comment by ispieter** [comment] 2016-03-23 09:13
Thank you @mhartington!

**Comment by joelbowen** [comment] 2016-03-23 12:14
To add some more context, in my situation I found the bug to be present with the following:

**Index.html**
`<ion-nav-view></ion-nav-view>`

**view-1.html**
`<ANY ELEMENT>Something</ANY ELEMENT><ion-nav-view></ion-nav-view>`

**sub-view-1.html**
`<ANY></ANY>`

But NOT present when I removed the `<ANY ELEMENT>` from view-1.html.

So it is, in my case, that I am unable to achieve the desired effect of showing a child-state inside of a parent state, without completely replacing the parent state content.

I tried ALL manner of ui-view/ion-view/ion-nav-view/ion-tabs/ion-pane/etc. Absolutely nothing worked.

**Comment by jgw96** [comment] 2016-03-23 14:07
This issue is describing the same bug but on iOS https://github.com/driftyco/ionic/issues/5888

**Comment by jgw96** [comment] 2016-03-23 14:26
@mhartington can you test with the conference app? Me and @brandy were both able to repro some slight flash when switching through the tabs. This was using the emulator and not an actual device.

**Comment by andreialecu** [comment] 2016-03-23 14:26
The bug in #5888 is for ionic2 though, I'm not sure the code bases are similar enough for it to be the same bug.

**Comment by mhartington** [comment] 2016-03-23 14:29
hey yall, thanks for being patient on this one, really appreciate it :smile: 

So looking over things, this should be effecting both iOS and Android with ionic 1.2.4, correct?

Also, has anyone been able to recreate this with the tabs starter app?

**Comment by andreialecu** [comment] 2016-03-23 14:33
@mhartington it's there in the tabs starter app, you just need to be very observant. Also, I fixed this in https://github.com/driftyco/ionic/pull/4654 but apparently that broke something else, and then when it got fixed this was again broken.

You can see it in the video you posted: https://www.youtube.com/watch?v=_ja8a08iSPE&feature=youtu.be Just notice how instead of the new tab appearing, there's a very brief white flash (1 frame, it's very quick).

**Comment by mhartington** [comment] 2016-03-23 14:40
@andreialecu alright, seeing it as well, 

https://youtu.be/R5EafRKTst0

Same clip, just slowed down a lot

Looking at the PR, going to see what can be done and keep it from breaking other things :grin:

**Comment by mhartington** [comment] 2016-03-24 17:42
Hey all! So I think I've been able to make some head way on this. I've opened a PR that looks good in my tests, but would love to hear some feedback from you first.

The changes have been made to viewFlicker branch

https://github.com/driftyco/ionic/pull/5937

If you wouldn't mind pulling down the code, building Ionic from source, and testing out the changes in your app, we can see if this fixes things and nip this bug :shipit:

**Comment by ctcampbell** [comment] 2016-03-24 17:57
Awesome. Is this an android specific fox or will iOS also look better?

**Comment by mhartington** [comment] 2016-03-24 18:00
@ctcampbell android ATM. In my tests, I wasn't able to cause a flicker on iOS

**Comment by mhartington** [comment] 2016-03-24 18:38
Here's a quick video demoing the PR 

https://youtu.be/nWSuocu64FU

**Comment by jordantomax** [comment] 2016-03-24 19:32
+1

**Comment by mhartington** [comment] 2016-03-24 19:44
@jordantomax does this mean that the PR works well for you? :grin:

**Comment by jordantomax** [comment] 2016-03-24 19:48
Whoops, no sorry. Just subscribing to the feed. I can test it out though. Do I need to compile something in order to use, I see that the release wasn't touched by your commit.

**Comment by mhartington** [comment] 2016-03-24 19:54
Ahh

You can follow these steps.

```
git clone https://github.com/driftyco/ionic.git
cd ionic 
git checkout viewFlicker
npm install
gulp build
```

And you should have the compiled code in `dist/js/ionic.bundle.js`
You should be able to just copy/paste that code into a test project and try it out.

**Comment by jordantomax** [comment] 2016-03-24 20:12
Seems to be working well in the test tabs application. I'm still having problems with flashing in my app though. I'm using tabs and menu, but tabs only appear on certain pages. I want to take a video to show you, how do I go about doing that?

**Comment by mhartington** [comment] 2016-03-24 20:15
Would you instead be able to create a minimal codepen or git repo that I could clone and test out? 
Just a similar set up of your app

**Comment by jordantomax** [comment] 2016-03-24 20:17
Good idea. I will try to do that tonight or tomorrow morning. Thanks for your help.

**Comment by andreialecu** [comment] 2016-03-24 20:44
@mhartington I just tested it in my app and the flicker seems to be gone. :+1:

**Comment by jgw96** [comment] 2016-03-24 20:56
I have tested the fix using the tabs starter on a Nexus 6 running the Android N preview, a Nexus 7 2013 running 6.0.1, a Moto X 2014 running 5.1 and a Nexus 7 2013 running 4.4.4 and did not see any flashing on any of those devices. Awesome !

**Comment by mhartington** [comment] 2016-03-25 17:59
@jordantomax any luck on getting that example together?

**Comment by jordantomax** [comment] 2016-03-25 18:59
@mhartington sorry, have been totally swamped! I hope to work on it on Sunday.

**Comment by cenderin** [comment] 2016-03-28 23:57
@mhartington I just tested this on my app i'm building and android and iPhone seem to be fixed with #5937.

**Comment by danbucholtz** [comment] 2016-04-06 01:34
@jordantomax, have you had a chance to put together an example?

Thanks,
Dan

**Comment by tgensol** [comment] 2016-04-06 02:33
Hi there,

This fix works well, but it looks the native-page-transitions is then not working properly... transitions are doing crazy things after I put this fix. Do you think it is linked ?

**Comment by AdrienDC** [comment] 2016-04-06 07:23
@tgensol Use default parameters for this plugins, it works well with this fix !

**Comment by jgw96** [comment] 2016-04-06 14:59
Hello all! As it seems through my testing and you guys testing the fix seems to be working I'm gonna go ahead and close this issue for now. @jordantomax if you get a chance to throw that test together feel free to post and I'll gladly reopen (:. Also @tgensol if the above solution does not fix your issue would you mind opening a separate issue on the bug hour having? Thanks everyone!

**Closed by jgw96** 2016-04-06 14:59 UTC

**Comment by ladmerc** [comment] 2016-06-25 21:59
With the breaking changes in ionic repo, how do we compile and build this

**Comment by danbucholtz** [comment] 2016-06-27 04:15
`1.x` branch is now Ionic `1.3.1`.  If you clone the repo and checkout the branch, you should be able to run `gulp build` to generate the distributable files.

**Comment by ladmerc** [comment] 2016-06-27 09:31
Thanks. already downloaded the dist manually :D

**Comment by lesserenterpriser** [comment] 2016-07-03 02:50
+1

**Comment by smcreator** [comment] 2016-08-13 14:06
I have fixed this. This happens related to ionic view update ionic bar bevavior: new bar created on before enter and hides old bar (current) an it blinks. Solution is defer hiding current bar to after enter event. Please write to me if you have some questions.

**Comment by ericmachine88** [comment] 2016-08-19 04:08
@smcreator could you share the code snippets?

**Comment by shrijan** [comment] 2016-12-13 10:13
I still got same problem .... any code snippets Thanks

**Comment by ladmerc** [comment] 2016-12-13 12:59
I think this issue is fixed in recent ionic versions.

**Comment by davebcn87** [comment] 2017-04-06 13:44
I had the same problem and the response from @princefr was the key. I had multiple navigation bars over the views. While adding the `ion-nav-bar` only on the top of my `tabs.html` file I fixed the problem:

```
<ion-nav-bar class="my-custom-bar">
  <ion-nav-back-button class="button-clear">
    <i  class="button button-icon ion-android-arrow-back" ng-click="vm.goBack()"></i>
  </ion-nav-back-button>
</ion-nav-bar>

<ion-tabs>
....
</ion-tabs>
```
