### ISSUE TITLE
Radio/Checkbox alert height too tall for Landscape orientation

### ISSUE THREAD

**Issue by MichaelMarner** [driftyco/ionic#8835] opened 2016-10-21 06:47 UTC
#### Short description of the problem:

Radio and checkbox alerts are rendered too tall for landscape orientation. Using Radio or Checkbox alerts as described in the [documentation](http://ionicframework.com/docs/v2/components/#alert-radio) means that the dialogs are too tall and the rendering of action buttons is cropped:

This issue exists on iOS and Android, did not test Windows phone.

Screenshots: http://imgur.com/a/IQmkn

#### What behavior are you expecting?

Radio/checkbox alerts should be usable in both landscape and portrait orientation, when used as documented.

The height of the alert content should be reduced depending on the available screen height. We worked around this issue with some custom scss:

    @media(max-height: 480px) {
        .alert-radio-group {
            max-height: 180px;
        }
    }

But it would be good to have this fixed in Ionic itself.

**Steps to reproduce:**

Render any checkbox/radio alert with more than 4 items in landscape mode. I have created a simple app to demonstrate this issue, which is basically a copy of the demo source from the documentation website:

https://github.com/MichaelMarner/ionic-radio-alert-test

**Which Ionic Version?** 1.x or 2.x

2.1.0

**Comment by MichaelMarner** [comment] 2016-10-21 06:59
Looking around the source code, the issue is `alert-[platform]-content-max-height` being used as the max-height value for `.alert-radio-group` and `.alert-checkbox-group`.

This should either be changed depending on the display height, or set to a smaller value (180px worked well for us).

**Comment by jgw96** [comment] 2016-10-21 12:04
Hello, thanks for using Ionic and thanks for the debugging! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/6326.

**Closed by jgw96** 2016-10-21 12:04 UTC

**Comment by morrisonbrett** [comment] 2016-12-29 00:33
I had to also add `height`.  Here's mine:

```
@media(max-height: 480px) {
  .alert-radio-group {
    max-height: 120px;
    height: 120px;
  }
}
```
