### ISSUE TITLE
The back button was lost!!! why????

### ISSUE THREAD

**Issue by shangliyang** [driftyco/ionic#7832] opened 2016-08-23 06:13 UTC
example:  take examples of website 
Please click the following steps, there will be a bug:

step 1: enter the  http://ionicframework.com/docs/api/directive/ionTabs/
we can see a mobile phone interface
step 2:  click  "scientific facts>" button.
step 3: click "<home"  back button.
step 4: click "about" tab.
step 5: click "tabs nav stack>" button.
step 6: click "<about" back button.
step 7: click "home" tab.
step 8:  click  "scientific facts>" button.
step 9: click "<home"  back button.
step 10: click "about" tab.
# **step 11: click "tabs nav stack>" button.**   The "<about" back button was lost.  why? should be needed!!!!!!!!

**Comment by shangliyang** [comment] 2016-08-23 06:29
#6875.  There's no I want to answer
i use the version is v1.3.1
could you tell me the problem still exists on  the future version

**Comment by jgw96** [comment] 2016-08-23 14:15
Hello, thanks for opening an issue with us! I will be closing this issue as a duplicate of #6875 . Unfortunately I do not have a good answer at the moment for when this will be fixed. Thanks for using Ionic!

**Closed by jgw96** 2016-08-23 14:15 UTC
