### ISSUE TITLE
Ionic 2 RC5 - ion-input disabled option not work any more 

### ISSUE THREAD

**Issue by ChuanTS** [driftyco/ionic#10108] opened 2017-01-20 06:41 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
```
  <ion-item>
    <ion-input type="text" placeholder="Username" value="Chuan" [disabled]="true"></ion-input>
  </ion-item>
```
code above used to work before RC5, but now the disabled option does not work

**Related code:**
```
  <ion-list>

  <ion-item>
    <ion-input type="text" placeholder="Username" value="Chuan" [disabled]="true"></ion-input>
  </ion-item>

  <ion-item>
    <ion-input type="password" placeholder="Password"></ion-input>
  </ion-item>

</ion-list>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.4.0
Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by mmolle-nelo** [comment] 2017-01-20 09:53
Same here, none of the both variants are disabling the input:

```
  <ion-input [disabled]="isDisbled"></ion-input>
  <ion-input disabled="{{isDisbled}}"></ion-input>
```

Your system information:

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0
ios-sim version: 5.0.13
OS: OS X El Capitan
Node Version: v7.4.0
Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by jgw96** [comment] 2017-01-20 15:42
Hello, thanks for using Ionic! Would you all mind trying the latest nightly (npm install ionic-angular@nightly --save) and trying this? I cannot seem to repro this issue in our e2e tests.

**Comment by ChuanTS** [comment] 2017-01-20 17:00
Hi jgw96, I tried to ionic-angular@nightly, but it does not pass the compile, saying Slides is missing ` Module '"/Users/Chuan/Documents/Baiwang/XiaoBao/node_modules/ionic-angular/index"' has no exported member 
            'Slides'. `
the ionic-angular version is  "ionic-angular": "^2.0.0-rc.5-201701192302",

**Comment by patrickmcd** [comment] 2017-01-20 18:15
I had the issue as well, but nightly looks good to me.

I'm setting it explicitly (`disabled="true"`), rather than with interpolation or template expression, if that matters.

**Comment by brandyscarney** [comment] 2017-01-21 00:40
Can you try the latest nightly and let me know if you still have a problem with it?

```
npm install --save --save-exact ionic-angular@2.0.0-rc.5-201701201813
```

There was a weird nightly released yesterday that may be causing the issues with Slides.

**Comment by brandyscarney** [comment] 2017-01-21 00:42
I'm going to close this as a duplicate of #10095. Please put any further comments over there. :)

**Closed by brandyscarney** 2017-01-21 00:42 UTC
Labels: needs reply, v2
