### ISSUE TITLE
bug: Side menu triggered when using swipe navigation

### ISSUE THREAD

**Issue by joshdover** [driftyco/ionic#3376] opened 2015-03-23 04:31 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Surprisingly, I haven't been able to find anyone having issues with this. 

I upgraded to rc0 (also tried rc1) to get the swipe-to-go-back navigation (which I was super pumped about). However, about half the time I try to use it, I also trigger the side menu (even though I have enable-menu-with-back-views="false") at the same time. When I let go of my swipe, there is a bunch of content flicker (even some huge black regions in the view) and then I return to the screen I was trying to back from. At the point, the back button is completely unresponsive and I can no longer swipe to go back.

As far as I can tell I don't have some strange structuring of my ion-nav-view, ion-pane, or ion-side-menus. Everything seems to match the ionic-starter-side-menu example (although that hasn't been updated for rc0/rc1). Let me know if posting my templates would be helpful.</span>

<span is-issue-template></span>

**Comment by CedNet** [comment] 2015-03-23 09:07
I've created a sort of event handler in the AppCtrl for swipe to go back that "if menu is open" while the swipe go back feature is requested, it cancels swipe to go back. That way both are not fired. Then you have to fine tune the edge threshold for where the menu should start open. Mine pretty close to the default of 25, I think I've set it to 20 to ensure swipe to go back has presedence over the menu.

**Comment by Ionitron** [comment] 2015-03-24 18:02
Greetings @joshdover!

My sensors indicate that I require more information in order to assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this happen occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com), where many humans will be able to offer wisdom and advice.

Thank you for allowing me to assist you.

<span ionitron-needs-reply></span>

**Comment by Ionitron** [comment] 2015-04-23 20:22
Greetings @joshdover!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment] 2015-04-23 20:22
Greetings @joshdover!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-04-23 20:22 UTC
