### ISSUE TITLE
Bug: ionic 2 dismiss alert from code breaks navigation 

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic#4968] opened 2016-01-14 22:22 UTC
I have a component with an improvised busy indicator, i have to close the alert upon navigation to next component or the alert will be stuck there until we go back to the component and close it manually, if i dismiss it too late it shows a black screen where it should be the animation, if too soon most of the time it won't even transition to next component, next i show three steps in the app when it does transition:
1. stage 1, starting point:
![start](https://cloud.githubusercontent.com/assets/9698639/12339389/df0ae9e8-bae2-11e5-8c97-e288dbd27156.png)
2. stage 2, a black screen shows between the animation:
![some_times](https://cloud.githubusercontent.com/assets/9698639/12339425/0222dbac-bae3-11e5-8000-f1b8e77b7a8f.png)
3. stage 3, next component
![nextcomponent](https://cloud.githubusercontent.com/assets/9698639/12339437/15399aa0-bae3-11e5-81c0-4bcb38635251.png)

**Comment by Luchillo** [comment] 2016-01-14 22:26
Aaand some times i gets stuck in stage 2, a black screen that i fix either reloading or sliding to show the sidemenu and navigating to the same component (basically seting root to that component):
![stuck](https://cloud.githubusercontent.com/assets/9698639/12339601/e0d9eaa2-bae3-11e5-8a57-7ca8402f3721.png)

**Comment by Daforest** [comment] 2016-02-03 21:49
+1

**Comment by mauricionarcizo** [comment] 2016-02-15 15:54
+1

**Comment by Luchillo** [comment] 2016-02-15 16:43
@adamdbradley how will ionic face this issue as is related to the time it takes to the component to transition? my workaround for now is a custom element that just resemble the Alert component but that is always present in the app.html side by side with the nav-component, relate to my gist:
https://gist.github.com/Luchillo/fc3d01f29580d5067541

**Comment by privetr** [comment] 2016-03-07 08:11
+1

**Comment by adamdbradley** [comment] 2016-03-12 09:26
Please see https://github.com/driftyco/ionic/issues/5095#issuecomment-195700251

**Comment by jgw96** [comment] 2016-04-21 15:56
Hey! I am going to close this issue as a duplicate of #5095 . Please feel free to comment back if you feel this one should be reopened. Thanks!

**Closed by jgw96** 2016-04-21 15:56 UTC
Labels: v2
