### ISSUE TITLE
back button disappears with tab views

### ISSUE THREAD

**Issue by jjw123** [driftyco/ionic#7913] opened 2016-08-30 15:19 UTC
Hi there,

I have a quite strange issue that I wondered if anyone could help me with.

I have a tab view with 5 tabs, if i perform a series of view changes, the back button randomly disappears.

The issue also happens on this codepen. https://codepen.io/ionic/pen/VLwLOG

If you perform the following steps, it can be reproduced
tab 1 -> subview -> back
tab 2 -> subview -> back
tab 1 -> subview -> back
tab 2 -> subview

On this subview, there is no back button.

**Comment by jgw96** [comment] 2016-08-30 20:52
Hello! Thanks for opening an issue with us! Since this issue is a duplicate of https://github.com/driftyco/ionic/issues/5351 I am going to be closing this issue for now. Thanks!

**Closed by jgw96** 2016-08-30 20:52 UTC
Labels: range
