### ISSUE TITLE
bug: $ionicActionSheet from ionic 1.0.0-rc0 not rendering  well on android 

### ISSUE THREAD

**Issue by spotsoft** [driftyco/ionic#3252] opened 2015-03-07 20:09 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.2</span>  <span ionic-webview>webview</span>

<span ionic-description>![screenshot_2015-03-07-21-57-33](https://cloud.githubusercontent.com/assets/11368197/6543085/3bd78690-c516-11e4-9e78-c8c0352cc856.png)

$ionicActionSheet is not rendering well on Android (currently checked only on 4.2.2). The button text appears small at left side. In crome (ionic serve) it looks good. </span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-03-07 20:09
Greetings @spotsoft!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3252). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3252)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by adamdbradley** [comment] 2015-03-11 02:18
This is by design, as that's how Android actionsheets look.

**Closed by adamdbradley** 2015-03-11 02:18 UTC
