### ISSUE TITLE
Bug@ionic2: ion-select doesn't clear the `checked` attribute when clearing the model

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5002] opened 2016-01-18 20:53 UTC
_From @Luchillo on January 18, 2016 19:57_

Hi, i'm using the ion-select with ngModel, when at start it will have the value undefined, after checking one and setting some values i make some processing with it and then set back the variable to `undefined`, when i was using standard html5 selects this would remove the checked value from option, but with the `ion-select` the option doesn't reset, even if the value is undefined.

_Copied from original issue: driftyco/ionic2#948_

**Comment by brandyscarney** [comment] 2016-02-04 15:48
Duplicate of https://github.com/driftyco/ionic/issues/5288

**Closed by brandyscarney** 2016-02-04 15:48 UTC
Labels: v2

**Comment by Luchillo** [comment] 2016-02-04 19:07
Yes it is, i forgot this one and that was after digging the code that i understood the error.
