### ISSUE TITLE
bug: SVG's SMIL animations are deprecated and will be removed. - ion-spinner directive - Chrome 45

### ISSUE THREAD

**Issue by tabrindle** [driftyco/ionic#4308] opened 2015-09-01 21:23 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>In [Chrome 45](http://blog.chromium.org/2015/07/chrome-45-beta-new-es2015-features.html) (45.0.2454.85) there is a deprecation warning concerning ion-spinner

According to the warning:

```
SVG's SMIL animations (<animate>, <set>, etc.) are deprecated and will be removed. 
Please use CSS animations or Web animations instead.
```

This deprecation warning is visible in the dev console right from the [ion-spinner api docs](http://ionicframework.com/docs/api/directive/ionSpinner/).

A possible solution might be to implement SVG animation in JavaScript using Web Animations, like this [Github repo](https://github.com/ericwilligers/svg-animation) by @ericwilligers.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-09-01 21:23
Greetings @tabrindle!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4308). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4308)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by randallbpotter15** [comment] 2015-09-12 07:51
I get the same thing.

**Comment by mhartington** [comment] 2015-09-12 14:23
Duplicate of #4259
Let's keep the conversation of there.
Thanks

**Closed by mhartington** 2015-09-12 14:23 UTC

**Comment by mhortaliza** [comment] 2016-02-04 11:07
Any rewrite solution to make it works again?
