### ISSUE TITLE
Tab Inside an ion-nav-view Does Not Update Title

### ISSUE THREAD

**Issue by RangerRick** [driftyco/ionic#2847] opened 2015-01-03 23:01 UTC
I'm doing a sidebar-navigation in my app.  One of my views contains a tabbar.  It updates the title correctly if you switch between the tabs, but if you switch to another view and then back to the tab view sometimes it doesn't update the title.

codepen here: http://codepen.io/RangerRick/pen/NPbrLP/

Switch to "Other" and then back to "Events" and (usually) it does not update the title.

**Comment by matheusrocha89** [comment] 2015-01-04 00:02
On all my templates I use the `ion-nav-bar` with `ion-nav-title inside`, works for me

**Comment by jianwu** [comment] 2015-01-06 01:23
I faced the same issue when title is updated asynchronously. The work around by using ion-nav-title does work.

**Comment by toddhalfpenny** [comment] 2015-05-02 21:52
Here's a codepen showing the issue http://codepen.io/toddhalfpenny/pen/MwwzoK
I tried several ways of reproducing this and the only way was using JS promises.

**Comment by boboldehampsink** [comment] 2015-07-07 11:43
Workaround using ion-nav-title worked for me too

**Comment by robsn** [comment] 2015-07-21 14:09
I'm using the workaround as well.

**Comment by matheuscas** [comment] 2016-03-12 05:20
@cfjedimaster pointed this out some months ago. It did make sense to me what he said, but this is still odd to me. See here: http://www.raymondcamden.com/2015/12/18/is-your-ionic-view-title-not-updating/
And like he said, my memory is worthless and I keep crashing on it.

**Comment by jgw96** [comment] 2016-03-23 18:48
Hello! Are you all still experiencing this issue with the latest version of ionic? I just tried the codepen myself and couldn't reproduce it. Thanks for providing the codepen by the way!

**Comment by matheuscas** [comment] 2016-03-23 19:23
Yes, I do. I still had to use the solution pointed out by @cfjedimaster.

**Comment by jgw96** [comment] 2016-06-30 16:22
Hello all! Since there is a well documented workaround for this (thanks @cfjedimaster !) and we do not plan on making any big changes to how navigation works in Ionic 1 i will be closing this issue for now. Thanks for using Ionic everyone!

**Closed by jgw96** 2016-06-30 16:22 UTC
Labels: navigation, v1
