### ISSUE TITLE
Ionic2 RC.0 - polyfill errors everywhere.

### ISSUE THREAD

**Issue by zakton5** [driftyco/ionic#8315] opened 2016-09-29 18:22 UTC
#### Short description of the problem:
Pretty much any page I navigate to on my app now results in a polyfill error, which freezes the app. I have no idea what is causing or how to provide more information.

<pre>
error_handler.js:51 Error: Uncaught (in promise): undefined
    at s (polyfills.js:3)
    at s (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (ng_zone_impl.js:34)
    at t.invokeTask (polyfills.js:3)
    at e.runTask (polyfills.js:3)
    at i (polyfills.js:3)
    at HTMLButtonElement.invoke (polyfills.js:3)
</pre>

**Comment by jgw96** [comment] 2016-09-29 19:09
Hello, thanks for using Ionic! Did you follow our [changelog](https://github.com/driftyco/ionic/blob/master/CHANGELOG.md) when updating your app?

**Comment by zakton5** [comment] 2016-09-29 19:12
Yes, step by step. I just checked again and I have done everything on there.

**Comment by jgw96** [comment] 2016-10-03 01:13
Hello, would you mind posting a repo that i can use to reproduce this issue? Thanks!

**Comment by jgw96** [comment] 2016-10-04 15:09
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-10-04 15:09 UTC
Labels: needs reply, v2

**Comment by zakton5** [comment] 2016-10-06 21:47
Somehow mysteriously disappeared. It may have been the fact that I was using eval in some places. I'll report back later when I've confirmed that
