### ISSUE TITLE
bug: Swipe back and hide-nav-bar

### ISSUE THREAD

**Issue by rossmartin** [driftyco/ionic#3363] opened 2015-03-20 17:33 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>all</span>  <span ionic-webview>webview</span>

<span ionic-description>I've found an issue with the new swipe back functionality when a "back" view has an `ion-view` with `hide-nav-bar="true"`.  The `ion-nav-bar` will disappear when starting a swipe back (and stay hidden even if the swipe back gesture is not completed).

Here is a CodePen that illustrates the issue- http://codepen.io/rossmartin/pen/jEXYvz

To replicate the issue in this CodePen do the following:
- Click on the Scientific Facts button.
- Now swipe back on this view but don't complete the gesture.  The `ion-nav-bar` disappears on the Facts view.

Let me know if there is a way to solve this without requiring the `ion-nav-bar` or `ion-header-bar` for each view.  Thanks!</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-03-20 17:33
Greetings @rossmartin!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3363). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3363)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by jasonwinshell-br** [comment] 2015-04-01 06:46
I think I've found a variation on this issue in IOS . I'm using v1.0.0-rc.1.

When swiping right on iOS8 to navigate back to the preview view, if the gesture is not competed (i) the current view's nav bar will get the title of the back view. The nav bar loses it's controls as well.

In the absence of a fix, is there a way to disable the iOS swipe to navigate feature?

**Comment by stianjensen** [comment] 2015-04-01 11:43
You can disable it with

```
$ionicConfigProvider.views.swipeBackEnabled(false);
```

**Comment by adamdbradley** [comment] 2015-04-06 15:09
https://github.com/driftyco/ionic/commit/0936f78c307e284da9525a56634d5b5bb416d746

**Closed by adamdbradley** 2015-04-06 15:09 UTC
Labels: animation, navigation

**Comment by ajwinter** [comment] 2015-08-07 14:28
In 1.0.1, I'm seeing the nav bar re-appear correctly, but the top part of the content is stuck under the nav bar after that. It looks like it needs to refresh scroll position after making the nav bar re-appear.

**Comment by acurrieclark** [comment] 2015-08-21 21:47
I am still seeing this on 1.1. The new file is definitely present in my code. Am I missing something?

**Comment by pesimeao** [comment] 2015-10-01 13:31
I have the same issue with version 1.1.0.

**Comment by dgproductions88** [comment] 2015-10-15 10:19
I'm having the same issue with latest version... :S

**Comment by acurrieclark** [comment] 2015-10-15 10:40
I see the difference now between the original issue and mine. The nav bar itself is still there when the swipe back is started, but its content (title, buttons etc) disappear and do not reappear if the swipe movement it cancelled. @adamdbradley should i raise this as a separate issue?

**Comment by acurrieclark** [comment] 2015-10-22 21:18
I don't know whether this will help anyone else, but I was using a separate <ion-nav-bar> element in each of my views. I did a bit of playing and found that by putting one <ion-nav-bar> element in the top level index.html and then setting the properties with the view (<ion-nav-title> etc) this problem is solved.

**Comment by malwatte** [comment] 2016-04-27 05:15
This bug still exists in 1.3.0. Any workarounds?

**Comment by tomoki7** [comment] 2016-07-03 07:23
+1 with above

**Comment by detinho** [comment] 2016-07-28 12:32
I can confirm both the bug and the workaround sugested by @stianjensen, BUT I'm not using hide-nav-bar="true".
Tested on iOS 9.3 iPhone 6 both device and emulator.
Ionic v1.3.1

**Comment by arturalkaim** [comment] 2017-03-17 10:40
Hi,
I'm having a similar issue with unfinished swipeback.
The footer is hidden when I start swiping back and it doesn't shows up if I cancel.

Any way to fix this issue?

Thanks,
Artur

++++++++++++++++++++++++++++++++++++

Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.0 
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.2.1 Build version 8C1002
