### ISSUE TITLE
Tap while already scrolling the content shouldn't trigger the tap/click on an element in the content at all.

### ISSUE THREAD

**Issue by tmvnk** [driftyco/ionic#10171] opened 2017-01-25 21:44 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment] 2017-01-25 22:29
Hello, thanks for using Ionic! Could you please add the info requested in the issue template?

**Comment by AndreasGassmann** [comment] 2017-01-25 22:48
I guess this is related to my issue from over 2 weeks ago. https://github.com/driftyco/ionic/issues/9945

**Comment by jgw96** [comment] 2017-01-26 15:29
Hello, thanks for the heads up @AndreasGassmann ! I am going to close this issue as a duplicate of #9945 .

**Closed by jgw96** 2017-01-26 15:29 UTC
Labels: needs reply, v2
