### ISSUE TITLE
Sass import module resolution of ~ fails

### ISSUE THREAD

**Issue by Maccodonaldo** [driftyco/ionic#10931] opened 2017-03-27 13:58 UTC
#### Bug Report
When importing, an external ngModule, [CovalentCoreModule](https://github.com/Teradata/covalent) ,the sass import module resolution does not work correctly.

```
sass: node_modules/@covalent/core/chips/_chips-theme.scss, line: 1 
            File to import not found or unreadable: ~@angular/material/core/theming/theming. Parent style sheet: 
            /home/user/project/node_modules/@covalent/core/chips/_chips-theme.scss 

       L1:  @import '~@angular/material/core/theming/theming';
       L2:  @import '~@angular/material/core/style/variables';

 sass failed 
```
##### Other information
THis is most likely a webpack configuration issue, 
could be resolved by replacing `~` with `node_modules/`

**Comment by lgleim** [comment] 2017-03-27 15:48
This is most likely a gereal issue of the ionic-app-scripts. I created a corresponding bug report at https://github.com/driftyco/ionic-app-scripts/issues/847

**Comment by brandyscarney** [comment] 2017-03-27 17:41
Thanks for the issue! Closing as a duplicate of https://github.com/driftyco/ionic-app-scripts/issues/847.

**Closed by brandyscarney** 2017-03-27 17:41 UTC
