### ISSUE TITLE
registerBackButtonAction  is not a function

### ISSUE THREAD

**Issue by kunalmestri9** [driftyco/ionic#7557] opened 2016-08-05 12:21 UTC
Hello When I try to use platform for registering hardware back button event. I am getting follwing error in IONIC 2 beta

Error: Uncaught (in promise): TypeError: _this.platform.registerBackButtonAction is not a function

Details about IONIC version : 
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.8
Ionic CLI Version: 2.0.0-beta.30
Ionic App Lib Version: 2.0.0-beta.16
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v0.12.5
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment] 2016-08-05 19:05
Hello, thanks for opening an issue with us! Would you be able to provide a [plunker](http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview) that demonstrates this issue? Thanks for using Ionic!

**Comment by kunalmestri9** [comment] 2016-08-06 04:43
Here is the [plunker](http://plnkr.co/edit/kci6bLTd4Vsc3LXMjSkv?p=preview) . But I am not sure how to reproduce the same issue in browser. 
I am facing this issue in Android Platform.

**Comment by jgw96** [comment] 2016-08-09 17:02
Hello, would you mind trying this with beta.11? I am unfortunately not able to reproduce this issue. Thanks!

**Comment by jgw96** [comment] 2016-08-14 05:27
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-08-14 05:27 UTC
Labels: needs reply, platform:ios, v2
