### ISSUE TITLE
Please add VirtualScroll for Slides 

### ISSUE THREAD

**Issue by panuganti** [driftyco/ionic#6315] opened 2016-04-25 19:04 UTC
**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
Virtual Scroll is great. However, it works only with ion-list. 
Can you please add this feature to ion-slides ?

**Comment by brandyscarney** [comment] 2016-05-12 20:06
Closing as a duplicate of https://github.com/driftyco/ionic/issues/6343

**Closed by brandyscarney** 2016-05-12 20:06 UTC
Labels: feature, v2, virtualscroll
