### ISSUE TITLE
ion-input with type="number" does not set model property as a number

### ISSUE THREAD

**Issue by zakton5** [driftyco/ionic#6570] opened 2016-05-18 19:09 UTC
#### Short description of the problem:
An ion-input of type="number" tied to a property via ngModel sets the model as text. For example, if I type 1234 in the number input, the model property is set to "1234".

#### What behavior are you expecting?
When I type 1234 into the number input, I expect my model property to have a value of 1234, NOT "1234".

```
<ion-input type="number" [(ngModel)]="someProperty"></ion-input>
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
A regular input works fine, it is only ion-input that is not working (shown in the plunk below)
 
**Which Ionic Version?** 2.x beta 6

#### Plunker that shows an example of your issue
http://plnkr.co/edit/outfAuJkvguE0tD3aLGf?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.4 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v4.4.4
Xcode version: Xcode 7.3 Build version 7D175

**Comment by jgw96** [comment] 2016-08-09 20:11
Hello! Thanks for opening an issue with us!  I am going to be closing this issue as a duplicate of https://github.com/driftyco/ionic/issues/7121. Thanks for using Ionic!

**Closed by jgw96** 2016-08-09 20:11 UTC
Labels: platform:ios, v2
