### ISSUE TITLE
Ionic 2 Badges space issue (RTL)

### ISSUE THREAD

**Issue by theunreal** [driftyco/ionic#10077] opened 2017-01-17 18:39 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Wrong padding/space when using ion-badges in RTL layout Ionic 2 apps:

![image](https://cloud.githubusercontent.com/assets/6171883/22034391/cf758d8c-dcf4-11e6-9c2a-c5f92cda6b8e.png)

**Expected behavior:**
Correct the padding/spacing in RTL layouts, to work as excepted:
![image](https://cloud.githubusercontent.com/assets/6171883/22034411/e0925ee2-dcf4-11e6-884f-770c1a028ada.png)

**Steps to reproduce:**
Using <ion-badge> in RTL Ionic 2 apps

**Related code:**

```
<ion-item style="direction:rtl">
  <ion-icon name="checkmark" item-left></ion-icon>
  TOTAL
  <ion-badge item-right>1</ion-badge>
</ion-item>
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.2
Xcode version: Not installed
```

**Comment by jgw96** [comment] 2017-04-07 14:07
Hello, thanks for using Ionic! We really appreciate this feedback on RTL support. This is not currently high priority for us at the moment, but we are tracking it in #5035. Because of this I am going to close this issue as a duplicate of that issue and ask that you put your feedback on that issue. Please know that by me closing this issue I am not saying that your feedback is not important, or that RTL support is not important, but I am simply closing this issue as we like to keep our issues as organized as possible so things do not get lost in the weeds (which is better said than done haha).

**Closed by jgw96** 2017-04-07 14:07 UTC
Labels: v2
