### ISSUE TITLE
Month column missing in DateTime picker

### ISSUE THREAD

**Issue by ogoguel** [driftyco/ionic#7932] opened 2016-08-31 21:30 UTC
#### Short description of the problem:

DateTime picker displays an empty month column when using a min attribute, whose year is not the current year 
#### What behavior are you expecting?

DateTime picker should always display a valid date when opened without defined value

**Steps to reproduce:**
1. Create a minimal ion-datetime component such as : 
   `<ion-datetime max="1998"></ion-datetime>`  
2. Open it : month is missing :(

**Which Ionic Version?** Ionic2 Beta 11
#### Plunker that shows an example of your issue

http://plnkr.co/edit/KZBREK7iEFACKVULt0lG?p=preview

**Run `ionic info` from terminal/cmd prompt:**

Cordova CLI: Not installed
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X Yosemite
Node Version: v4.5.0
Xcode version: Xcode 7.2 Build version 7C68

**Comment by aurbina83** [comment] 2016-09-30 01:20
I'm surprised this wasn't fixed in the recent RC. Wish it were.

**Comment by brandyscarney** [comment] 2017-01-24 23:56
Thanks for the issue! I'm not able to reproduce this in the latest RC (2.0.0-rc.6) so I am going to close this. Please let me know if you are still having the issue with steps to reproduce and I will reopen it. :)

**Closed by brandyscarney** 2017-01-24 23:56 UTC
Labels: platform:ios, v2
