### ISSUE TITLE
RC.0 detect changed and rebuild is very slow

### ISSUE THREAD

**Issue by izee** [driftyco/ionic#8629] opened 2016-10-11 07:40 UTC
debug with command `ionic serve`, the `bundle dev update` and `templateUpdate` is very slow.

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.0-201610041708
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS:
Node Version: v6.7.0

> [13:50:06]  bundle dev update started ...
> [13:50:52]  templateUpdate started ...
> [13:50:52]  bundle dev update started ...
> [13:50:52]  sass started ...
> [13:50:57]  sass finished in 4.82 s
> [13:50:57]  sass started ...
> CSS changed:  D:\Develop\Project\team.app\www\build\main.css
> CSS changed:  D:\Develop\Project\team.app\www\build\main.css
> [13:50:59]  sass finished in 2.76 s
> CSS changed:  D:\Develop\Project\team.app\www\build\main.css
> [13:51:20]  bundle dev update finished in 73.53 s
> [13:51:20]  sass started ...
> JS changed:   D:\Develop\Project\team.app\www\build\main.js
> [13:51:20]  sass finished in 12 ms
> [13:51:20]  bundle dev update started ...
> [13:51:28]  bundle dev update finished in 8.31 s
> [13:51:28]  sass started ...
> [13:51:28]  sass finished in 12 ms
> JS changed:   D:\Develop\Project\team.app\www\build\main.js
> JS changed:   D:\Develop\Project\team.app\www\build\main.js
> [13:53:10]  bundle dev update finished in 138.66 s
> [13:53:10]  sass started ...
> [13:53:10]  sass finished in 14 ms
> [13:53:10]  templateUpdate finished in 138.68 s
> [13:53:10]  templateUpdate started ...
> [13:53:10]  bundle dev update started ...
> [13:54:48]  bundle dev update finished in 98.07 s
> [13:54:48]  sass started ...
> [13:54:48]  sass finished in 11 ms
> [13:54:48]  templateUpdate finished in 98.08 s
> JS changed:   D:\Develop\Project\team.app\www\build\main.js
> [15:21:08]  bundle dev update started ...
> [15:21:25]  templateUpdate started ...
> [15:21:25]  bundle dev update started ...
> JS changed:   D:\Develop\Project\team.app\www\build\main.js
> [15:21:38]  bundle dev update finished in 30.03 s
> [15:21:38]  sass started ...
> [15:21:39]  sass finished in 733 ms
> [15:21:39]  bundle dev update started ...
> JS changed:   D:\Develop\Project\team.app\www\build\main.js
> [15:21:49]  bundle dev update finished in 10.63 s
> [15:21:49]  sass started ...
> [15:21:49]  sass finished in 16 ms
> JS changed:   D:\Develop\Project\team.app\www\build\main.js
> [15:23:38]  bundle dev update finished in 132.50 s
> [15:23:38]  sass started ...
> [15:23:38]  sass finished in 14 ms
> [15:23:38]  templateUpdate finished in 132.56 s
> [15:23:38]  templateUpdate started ...
> [15:23:38]  bundle dev update started ...
> [15:25:29]  bundle dev update finished in 110.91 s
> [15:25:29]  sass started ...
> [15:25:29]  sass finished in 11 ms
> [15:25:29]  templateUpdate finished in 110.92 s
> JS changed:   D:\Develop\Project\team.app\www\build\main.js

**Comment by alexandrevilain** [comment] 2016-10-11 07:51
Hello ! 

The same for me, 110 s for `templateUpdate`.

**Comment by graphicsxp** [comment] 2016-10-11 12:45
same here, takes forever....  it is faster to stop it and start a new build. That makes livereload useless

**Comment by cleever** [comment] 2016-10-11 13:02
@graphicsxp I do the same here. Stop and restart is faster then livereload.

**Comment by jgw96** [comment] 2016-10-11 15:58
Hello all, thanks for opening an issue with us! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic-app-scripts/issues/47. Thanks!

**Closed by jgw96** 2016-10-11 15:58 UTC
