### ISSUE TITLE
[PWA] Footer partially cropped when a web app is opened as a PWA

### ISSUE THREAD

**Issue by kael** [driftyco/ionic#10141] opened 2017-01-23 10:16 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

The PWA version of an app has its footer partially cropped, whereas the footer is correctly displayed on a website.

**Expected behavior:**

The footer of the PWA version should not be cropped and should be displayed identically to its page/web version.

**Steps to reproduce:**

Create an app using `ionic --start --v2`, run the app, open it in Chrome 55 Android, save it as a PWA to Homescreen, open the PWA.

**Related code:**
N.A

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.9.4
Xcode version: Not installed
```
![ionic-pwa-footer](https://cloud.githubusercontent.com/assets/2463/22199852/f3428082-e15c-11e6-96a8-f8156d192079.png)

**Comment by jgw96** [comment] 2017-01-25 21:31
Hello, thanks for using Ionic! Unfortunately I cannot reproduce this issue on any of my devices. What device are you experiencing this on?

**Comment by kael** [comment] 2017-01-27 02:07
Well, I've just tested with Chrome 56.0.2924.78 (beta) and I can't reproduce the bug.

With each browser, Chrome 55 and Chrome 56, I've added the web page to the Homescreen, and the footer of the PWA is displayed correctly with Chrome 56 but buggy with Chrome 55.

Using Asus Zenfone 2 Laser Z00ED with Android 6.0.1.

**Comment by jgw96** [comment] 2017-01-27 15:55
Hmm interesting enough i cannot reproduce with chrome stable, beta, dev or canary haha. I am going to close this one for now as it looks to be a chrome bug that has been fixed, but will reopen if i notice anything different. Thanks for using Ionic and have fun building PWA's!

**Closed by jgw96** 2017-01-27 15:55 UTC
Labels: footer, needs reply, v2
