### ISSUE TITLE
bug: RC3 list border top is missing

### ISSUE THREAD

**Issue by ThorConzales** [driftyco/ionic#9301] opened 2016-11-23 07:58 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When upgraded to RC3 then list or list items no longer have border top thus screwing up the existing app styling. If it is a bug please consider fixing it, if it is intended behavior please let us know if there is a proper way to replicate old styling without having to manually styling lists.</span>

![ionicborderbug](https://cloud.githubusercontent.com/assets/9930079/20554283/7f800f6c-b163-11e6-947e-802eb78e4fd9.png)

<span is-issue-template></span>

**Comment by infinnie** [comment] 2016-11-23 09:23
Dup #9261

**Comment by jgw96** [comment] 2016-11-23 17:28
Hello @ThorConzales ! I am going to close this one as a duplicate of the above linked issue. Thanks!

**Closed by jgw96** 2016-11-23 17:28 UTC
