### ISSUE TITLE
bug: Null on animation.js

### ISSUE THREAD

**Issue by nicolasemc** [driftyco/ionic#10528] opened 2017-02-22 12:10 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>When I try to use the navigation method popToRoot() or even push a page that is the same as the root page of the nav stack (after logout function) it gives me the following message:

Uncaught TypeError: Cannot read property 'raf' of null
    at animation.js:285

animation.js is located on node_modules/ionic-angular/animations</span>

<span is-issue-template></span>

**Comment by mhartington** [comment] 2017-02-22 14:58
Hi there! How can we replicate this? The issue template included a link to a V2 plunkr.
Please try to recreate this in a plunkr or some sort of demo. 
We need one in order to debug.

**Comment by williampaulo** [comment] 2017-02-24 20:48
I went through the same situation. The problem is the 'ngIf' directive. In my case, this was due the fact that when one press the logout button on the side menu, two things were actually happening: the application was trying to return to root while also trying to hide the side menu through the ngIf directive simultaneously. To fix this, I had to separate the actions in two steps: wait for the callback of popToRoot() method and then hide the side menu.

**Comment by jgw96** [comment] 2017-03-03 19:49
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-03-03 19:49 UTC
Labels: needs info, v2

**Comment by Vicky443** [comment] 2017-10-31 14:37
Hi , 
i have faced same issue, it seems if there any none Observable methods just above your 

" this.navctrl.setRoot(LoginPage) "

**Comment by jwz104** [comment] 2018-01-06 09:07
I also have this error. It is pretty easy to replicate. I show a certain HTML element with an `*ngIf`. The ngif checks if an item exists in localstorage. When I remove the item from localstorage I get the error.

HTML:
`<ion-menu [content]="content" *ngIf="authenticationService.isAuthenticated()">`

Method in service:
```
public isAuthenticated() {
  // Check if the user is authenticated based on the token in local storage.
  return (localStorage.getItem('token') != null);
}
```

Error:
```
animation.js:292 Uncaught TypeError: Cannot read property 'raf' of null
    at animation.js:292
```

Why do I get this error?

**Comment by arsenk01** [comment] 2018-02-19 08:56
Hi guys,

I just encountered the same issue and found the solution. So instead of using:
`<ion-menu [content]="content" *ngIf="authenticationService.isAuthenticated()">`
which will produce a problem when `isAuthenticated()` will change just use menu controller behavior.
Inside app.component.ts:
```
export class MyApp {
...
  constructor(
    private menu: MenuController,
    ...
  ) {
       this.menu.enable(false); // be default menu will not be available
  }
}
```
then lets say inside `Login` Component, after login:
@Component({
  selector: 'login',
  templateUrl: 'login.html'
})

export class LoginComponent  {
 ...

 public onLoginHandler() {
   this.menu.enable(true)
 }

 public logout() { 
   this.menu.enable(false)
 } 
}

**Comment by Akhouad** [comment] 2018-03-03 01:02
@arsenk01 Your solution works well. Thanks
