### ISSUE TITLE
perf: Header in item-class cuts g/j letters

### ISSUE THREAD

**Issue by cherry-wave** [driftyco/ionic#4931] opened 2016-01-08 20:26 UTC
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>desktop</span>  

<span ionic-description>I used the code from the card showcase and added a "g" and "j" to Marty's surname.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment] 2016-03-14 18:22
Hello! Thanks for opening an issue with us, we just need a little more info from you so that we can better help you with your issue. Would you mind posting a code sample, plunkr or codepen that we can use to reproduce your issue? Also, would you mind running `ionic info` and posting the output? Thanks again!

**Comment by jgw96** [comment] 2016-03-28 16:30
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to respond back if your still having the issue! Thanks again!

**Closed by jgw96** 2016-03-28 16:30 UTC
Labels: needs reply
