### ISSUE TITLE
Ion-img don't load in virtual scroll

### ISSUE THREAD

**Issue by michaschwab** [driftyco/ionic#11417] opened 2017-04-27 19:07 UTC
Hi there,
I'm having trouble with ion-img not loading in virtual scroll. After getting familiar with ionic's code, I don't understand how it is supposed to work.

**Ionic version:** 
[ ] **1.x**
[ x ] **2.x**
[ ] **3.x**

**I'm submitting a ...** 
[ x ] bug report
[ ] feature request
[ ] support request

The top images are loading correctly, but after scrolling a little bit, none of the images are being loaded and remain gray. After looking into the code, I verified that this is because the images that are supposed to load are detected incorrectly.

The code to detect relevant images is as follows:
```
if (img.bottom > viewableTop && img.top < viewableBottom + renderableBuffer) {
```
The img.bottom and img.top attributes are obtained by using `getBoundingClientRect()` on the image. However, this causes incorrect attributes for me, and I don't understand how it is supposed to be correct:

In virtual scroll, only relevant elements are created in the DOM. This means that <ion-img> elements further down are not created until the user scrolls down. But since getBoundingClientRect() detects coordinates relative to the window (e.g. see here: [http://javascript.info/coordinates](http://javascript.info/coordinates)), these attributes are not absolute, but relative to the scroll position when the <ion-img> elements are added to the DOM by virtualscroll.

For this reason, all my img.top values are less than 1000, no matter how far down the list I go. How is this supposed to work correctly? Am I doing something wrong, or is there a fundamental flaw in the design?!

Thank you!

**Ionic info:**
```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.8
Node Version: v7.5.0
Xcode version: Not installed
```

**Comment by jgw96** [comment] 2017-04-27 19:36
Hello, thanks for opening an issue with us! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/11326

**Closed by jgw96** 2017-04-27 19:36 UTC
