### ISSUE TITLE
RC2 Update Problem - Wrapper_NumberValueAccessor

### ISSUE THREAD

**Issue by vlados** [driftyco/ionic#9032] opened 2016-11-04 18:35 UTC
I followed the guide for upgrading to RC2, after some problems I copied the packages from ionic-conference-app and my app started working in browser. When I tried to build app for android I get:
```
20:22:58]  Error: Error at /Users/vlado/code/autoglass/inflex2/.tmp/pages/home/home.ngfactory.ts:340:37 
[20:22:58]  Module ''*'' has no exported member 'Wrapper_NumberValueAccessor'. 
[20:22:58]  Error at /Users/vlado/code/autoglass/inflex2/.tmp/pages/home/home.ngfactory.ts:348:37 
[20:22:58]  Module ''*'' has no exported member 'Wrapper_NumberValueAccessor'. 
[20:22:58]  ngc failed 
[20:22:58]  ionic-app-script task: "build" 
[20:22:58]  Error: Error 
```
In the code I have:
```
_NumberValueAccessor_7_4:import34.Wrapper_NumberValueAccessor;
```
This code points to:
```
import * as import34 from '../../node_modules/@angular/forms/src/directives/number_value_accessor.ngfactory';
```
But in this folder the file number_value_accessor.ngfactory is missing

**Comment by bytenik** [comment] 2016-11-05 02:33
I have the same issue. I have no idea what the cause is.

**Comment by chron0** [comment] 2016-11-05 18:19
Struck by the same, I could isolate it in my case by removing whole ion-grid sections out of the corresponding template. Can you guys verify that? I'm still trying to boil it down further...

**Comment by vlados** [comment] 2016-11-05 18:28
I think if you use input number you will stuck with it. You can change it to text while the ionic's team fix it.

**Comment by chron0** [comment] 2016-11-05 18:30
Yes, I've got input fields with number in those grids, currently working my way through, let me see if I can verify it...

**Comment by chron0** [comment] 2016-11-05 18:34
Confirmed:

```
[18:33:07]  Error: Error at /home/chrono/src/governess/governess-app/.tmp/pages/tasks/task.detail.ngfactory.ts:1146:37 
[18:33:07]  Module ''*'' has no exported member 'Wrapper_NumberValueAccessor'. 
```

as soon as I have 

```
<input type="number">
```
in the template.

**Comment by jgw96** [comment] 2016-11-07 10:18
Hello all! Thanks for using Ionic! This looks to be a bug in the NGC. Once i have confirmed I will update this issue.

**Comment by Jnig** [comment] 2016-11-10 14:36
Hi everyone! According to this https://forum.ionicframework.com/t/ngc-error-when-using-ion-input-type-number-rc2/69469/1 it's a bug in ngc which is fixed in version 2.1.2 (ionic is using 2.1.1)

**Comment by eampiart** [comment] 2016-11-15 07:45
Hey all! Is there any update on this? Or a workaround other than removing number inputs? When can we expect a new ionic version that uses a newer ngc?

**Comment by jgw96** [comment] 2016-11-17 17:32
Hello all! This is definitely an NGC bug in the version of NGC we are currently using. There were some breaking changes in 2.1.2 that we are currently working on resolving in our codebase. We are working hard on this at the moment, so the timeline is asap (: Sorry for the hassle!

**Comment by bytenik** [comment] 2016-11-27 01:54
Any updates? I'm still stuck on rc1 because of it.

**Comment by brandyscarney** [comment] 2017-01-25 00:27
I'm not able to reproduce this using the latest (2.0.0-rc.6). Please let me know if you are still having this issue and I will reopen, thanks!

**Closed by brandyscarney** 2017-01-25 00:27 UTC
Labels: v2
