### ISSUE TITLE
"Swiping" on a button triggers material ripple, but button doesn't trigger

### ISSUE THREAD

**Issue by wli** [driftyco/ionic#6585] opened 2016-05-20 02:17 UTC
#### Short description of the problem:
Normally, pressing on a button should:
1. Trigger the material ripple (for android)
2. Trigger the button `(click)` action

However, if you "swipe" from the button (start touching the screen at the button location, but drag a tiny bit away before releasing), this happens:
1. Material ripple triggers
2. Button `(click)` action does NOT trigger

#### What behavior are you expecting?
Material ripple should only trigger if the button `(click)` action triggers.

**Steps to reproduce:**
1. Create a button
2. Start touching the screen at the button location, but drag a tiny bit away before releasing
3. Observe material ripple, but no `(click)` action firing

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
This happens on tab buttons too. Can't trigger on desktop, and isn't an issue in ios since it's not running material design by default.

**Which Ionic Version?**
2.0.0-beta.7

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
```
Cordova CLI: 6.0.0
Ionic Framework Version: 2.0.0-beta.7
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
OS: Distributor ID:	Ubuntu Description:	Ubuntu 16.04 LTS 
Node Version: v5.8.0
```

**Comment by jgw96** [comment] 2016-05-20 15:16
Hey @wli ! Would you mind sharing a plunker or codepen that i can take a look at? Thanks!

**Comment by wli** [comment] 2016-05-20 16:31
@jgw96 unfortunately I can only repro on a device (not a website). do you still want a plunkr for it? It's literally any button (nav bar, tabs, buttons, etc).

**Comment by jgw96** [comment] 2016-05-20 16:34
Actually, i was able to reproduce on desktop with touch events enabled in chrome canary. We are looking into this now.

**Comment by wli** [comment] 2016-05-20 16:36
Awesome - thanks! Let me know if you need anything else, or to test a fix.

**Comment by jgw96** [comment] 2016-05-20 16:39
Hey @wli so after testing with some native android apps (gmail, inbox by gmail, hangouts) it looks like they have the same behavior. So for example, if you swipe across the fab button in hangouts, you can see that it fires the ripple. Would you mind testing that for me on your android device too please? After talking with my colleagues, since native material design has the same behavior, then we are not gonna consider this a bug. Would love to have your insight on this though (:

**Comment by wli** [comment] 2016-05-20 16:53
I tested this yesterday actually with the native apps, since I was really curious why our users were reporting a lot of false clicks (where they think they clicked via the ripple, but didn't actually register the click). Here are the biggest differences:

Native
- a "long" swipe-press results in a ripple, and no click
- a short swipe-press results in no ripple, and no click

Ionic
- a long swipe-press results in a delayed ripple (doesn't start until finger goes up), and no click
- a short swipe-press results in a ripple, and no click

I think the main pain point is that the short swipe-presses result in a ripple on ionic, but not native. These happen quite often, so it feels like the app is unresponsive.

**Comment by wli** [comment] 2016-05-20 17:13
@jgw96 if this is confusing, let me know and I can try to throw together a video later this weekend or something

**Comment by jgw96** [comment] 2016-05-20 17:38
@wli Nope, that makes perfect sense (: hmmm i will have to look more into this and discuss it with the team. Expect some feedback by monday (: Thanks for using Ionic by the way, id love to be able to see the app your working on if possible!

**Comment by brianbishop** [comment] 2016-05-22 01:02
In the [tutorial] template app, for v2, the demo app has a view with list of clickable rows

If a touch starts on Item1, it becomes highlighted. If the user slides down to the bottom of the list e.g. to Item10, and releases there, the ripple effect fires on Item1. It's a similar problem, and might be related

**Comment by wli** [comment] 2016-06-06 22:39
@jgw96 Happy Monday! Any progress on this? I've been patiently waiting for updates :)

I'd love to show you our app, but it's not set up for mass distribution yet. Hit me up on slack in a few weeks and we should be ready then.

**Comment by wli** [comment] 2016-06-06 23:41
@jgw96 Just updated to beta8 and this seems to be fixed! Can you confirm it was supposed to be fixed? I don't see anything in the release notes about this.

**Comment by jgw96** [comment] 2016-06-07 14:07
Hello @wli ! Im glad this was fixed for you! [this](https://github.com/driftyco/ionic/issues/6677) commit is gonna be the one that fixed this for you. I will close this issue for now, but if you have issues with it again feel free to comment and ill happily reopen! Thanks for using Ionic!

**Closed by jgw96** 2016-06-07 14:07 UTC
Labels: platform:android, platform:ios, v2
