### ISSUE TITLE
bug: iOS list scolling issue

### ISSUE THREAD

**Issue by ThorConzales** [driftyco/ionic#10201] opened 2017-01-27 07:52 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.0.0 final</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>10.2</span>  <span ionic-webview>webview</span>

<span ionic-description>When the list is still being scrolled and it hasn't stopped completely and if the person taps on one of the list items while the list is still in motion then it triggers a click event for the wrong list item. It seems to take the position where click occurred on the position before the scrolling started. So the only way to make sure person clicks on the correct item is to make sure the scrolling of the list has stopped completely. And it only seems to happen on iOS, works properly on Android.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment] 2017-01-27 08:13
Hello, thanks for using Ionic! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/9945.

**Closed by jgw96** 2017-01-27 08:13 UTC
