### ISSUE TITLE
bug: Ionic cutting last 2 characters of year only in android datetime

### ISSUE THREAD

**Issue by pawelfrydrych** [driftyco/ionic#9805] opened 2016-12-27 14:34 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Ionic is cutting last 2 characters of year in datetime. On iOS it's work perfect, but on Android and Mozilla Firefox responsive mode not.

And result is for example: 
22 06 20..

**Expected behavior:**

It should work normally

**Steps to reproduce:**

**Related code:**

```
<ion-item>
        <ion-label floating color="light">Date of birth</ion-label>
        <ion-datetime displayFormat="MMM DD, YYYY" [(ngModel)]="form.dateOfBirth" name="dateOfBirth"></ion-datetime>
</ion-item>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed


```

**Comment by infinnie** [comment] 2017-01-05 08:28
See #9879 for a screenshot on this problem.

**Comment by jgw96** [comment] 2017-01-10 22:13
Hey @pawelfrydrych , thanks for opening an issue with us! I am going to close this issue as a duplicate of #9879. Thanks for using Ionic!

**Closed by jgw96** 2017-01-10 22:13 UTC
Labels: needs:devicetesting, v2

**Comment by infinnie** [comment] 2017-01-11 00:44
@jgw96 _this_ is the original issue. #9879 just has an image for that!
