### ISSUE TITLE
bug: iOS 9 beta, max digest iterations reached

### ISSUE THREAD

**Issue by zarko-tg** [driftyco/ionic#4151] opened 2015-07-27 08:29 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>Steps to reproduce:
1. Create a simple app based on the sidemenu template (for example: ionic start -a smapp smapp sidemenu)
2. Add iOS platform, build and then run on an iPhone with iOS 9 beta (ver 4, build 13A4305g).
3. Open the app side menu and click for example on "Browse"

This will immediately output:
```
0     261349   error    Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []
http://errors.angularjs.org/1.3.13/$rootScope/infdig?p0=10&p1=%5B%5D
http://192.168.1.45:8100/lib/ionic/js/ionic.bundle.js:8890:32
$digest@http://192.168.1.45:8100/lib/ionic/js/ionic.bundle.js:23108:35
$apply@http://192.168.1.45:8100/lib/ionic/js/ionic.bundle.js:23333:31
http://192.168.1.45:8100/lib/ionic/js/ionic.bundle.js:20191:30
eventHandler@http://192.168.1.45:8100/lib/ionic/js/ionic.bundle.js:11841:25
dispatchEvent@[native code]
triggerMouseEvent@http://192.168.1.45:8100/lib/ionic/js/ionic.bundle.js:2865:20
tapClick@http://192.168.1.45:8100/lib/ionic/js/ionic.bundle.js:2854:20
tapTouchEnd@http://192.168.1.45:8100/lib/ionic/js/ionic.bundle.js:2977:13
1     261351   error    Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []
http://errors.angularjs.org/1.3.13/$rootScope/infdig?p0=10&p1=%5B%5D, http://192.168.1.45:8100/lib/ionic/js/ionic.bundle.js, Line: 23336
```

Using the side menu further results in an erratic and faulty behaviour.

Your system information:

Cordova CLI: 5.1.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.0.1
Ionic CLI Version: 1.6.1
Ionic App Lib Version: 0.3.3
ios-deploy version: 1.7.0 
ios-sim version: 4.1.1 
OS: Mac OS X Yosemite
Node Version: v0.12.7
Xcode version: Xcode 6.4 Build version 6E35b</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-07-27 08:29
Greetings @zarko-tg!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4151). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4151)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by zarko-tg** [comment] 2015-07-27 08:32
cc @mhartington

**Comment by mhartington** [comment] 2015-07-27 19:44
duplicate of #4082

**Closed by mhartington** 2015-07-27 19:44 UTC

**Comment by zarko-tg** [comment] 2015-09-10 08:06
Here's a video showing the basic problem with this particular app. It's a very simple app so the chances of things going wrong in a more complex one are much higher.
@mhartington 
https://www.youtube.com/watch?v=6H4TwUeaWA0

**Comment by mhartington** [comment] 2015-09-10 08:13
Please see #4082 and the patch at the end. Tear that out

**Comment by zarko-tg** [comment] 2015-09-10 08:17
Yep, I'm on it already and the patch appears to be working.
The video should make it clearer what the problem is/was for people that haven't been able to see it.
