### ISSUE TITLE
bug: Controller being called twice, and nav-bar disappears

### ISSUE THREAD

**Issue by manmetplok** [driftyco/ionic#3852] opened 2015-05-28 07:32 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When caching is disabled controllers are being initialized twice.

see also this issue: https://github.com/driftyco/ionic/issues/3620#issuecomment-106057528
and this one: http://forum.ionicframework.com/t/hidden-nav-bar-using-state-go-with-disabled-caching-beta-14/17686

pluckr:
http://plnkr.co/edit/X7zM82OvlUQvLjZq5au8?p=preview1

When clicking the refresh button, the controller is executed twice, and the nav-bar disappears</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-05-28 07:32
Greetings @manmetplok!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3852). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3852)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment] 2015-12-10 00:25
View caching will be overhauled in 2 but looking at 1.3 for this one

**Comment by 0x1ad2** [comment] 2015-12-15 13:41
@manmetplok I've forked your Plunk and provided a workaround for you http://plnkr.co/edit/mrv7KCiM4AzkuG6i9ElK?p=preview
*It's located in the controller.js file*

**Comment by ksgupta** [comment] 2016-05-09 09:28
Hi, I too am having this issue where nav-bar disappears and controller is being called twise when caching is disabled for the application. I saw this was marked for  milestone 1.3 and upgraded my ionic at v1.3 but this is still reproducible.

Can you please confirm if this is supposed to be fixed in v1.3?

**Comment by kristiantenfen** [comment] 2016-06-08 21:25
@ksgupta Not v1.3

**Comment by jgw96** [comment] 2016-06-21 18:58
Hello all! Thanks for opening an issue with us! I am going to close this one for now as their seems to be a workaround that @0x1ad2 posted. Thanks for using Ionic!

**Closed by jgw96** 2016-06-21 18:58 UTC
Labels: v1

**Comment by lambrospetrou** [comment] 2016-07-27 09:40
So there is no plan to fix this for version 1? We need to just manually call it in the afterEnter event?

**Comment by lambrospetrou** [comment] 2017-01-11 13:15
I realised that this workaround has issues when you want to override the ion-nav-bar with custom ion-nav-buttons for some pages! 
The ion-nav-bar defined in the index.html is used and the overrides in the page's ion-view do not modify the nav bar. Is there any workaround or more robust solution to this problem?

I know your target and focus is v2 but leaving issues open for the old but still wide-used version is not good.

Thanks

**Comment by Lauracec** [comment] 2017-03-09 18:30
So, like @lambrospetrou said, the workaround doesn't work every time. It would be great if this issue gets re-opened.

**Comment by Lauracec** [comment] 2017-03-09 21:08
Ok guys, I've worked on a pure Javascript solution, for my situation, and here it is. Hope it can help someone. 
_My situation: like what @lambrospetrou said, the workaround wasn't working if you had the ion-nav-bar overrided in some template, and I didn't wanted to use jQuery._

```
$scope.$on('$ionicView.enter', function(e) {
    $timeout(function() {
      showHeader();
    }, 1000);
    
    function showHeader() {
      // Having the nav-bar in your template, set an ID to it.
      var header = document.getElementById("header_id");
      if (header.classList) {
        if (header.classList.contains('hide')) {
          header.classList.remove('hide');
        }
      }
    }

  });
```
