### ISSUE TITLE
Ion-input placeholder flickers on scroll in iOS

### ISSUE THREAD

**Issue by Bouzmine** [driftyco/ionic#6746] opened 2016-06-03 13:22 UTC
#### Short description of the problem:
I have form in a modal and when I select an input and scrolling is needed, the placeholder flickers.

#### What behavior are you expecting?
The placeholder not to flicker.

**Steps to reproduce:**
1. Put a long form in a modal
2. Tap an input

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
This bug used to work in the browser, but since one of the nightlies, it only works in iOS. It also doesn't work if there's no scrolling.

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.7-201605271904
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.6
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v5.0.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment] 2016-06-03 15:27
Hello, thanks for opening an issue with us! Would you mind creating a plunker or repo that i can use to reproduce this issue? Thanks for using ionic!

**Comment by jgw96** [comment] 2016-06-09 14:17
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-06-09 14:17 UTC
Labels: modals, needs reply, platform:ios, v2

**Comment by Bouzmine** [comment] 2016-06-11 15:01
Hi,
Sorry for the delay, I didn't have the time to investigate this until now.

Here's a video of exactly what is happening : 
![bug flicker video-3](https://cloud.githubusercontent.com/assets/15067923/15985617/920e6f08-2fc1-11e6-88a3-d3e73c6096c8.gif)

And here is a repo you asked for : 
[https://github.com/Bouzmine/demo-bug-flicker](https://github.com/Bouzmine/demo-bug-flicker)

**Comment by Bouzmine** [comment] 2016-06-15 21:01
@jgw96 Could you please reopen this one too ?

**Comment by EralpB** [comment] 2016-11-25 10:31
I'm running into this issue, even single and simple text inputs have this problem..
