### ISSUE TITLE
ion-toggle elements within a form doesn't trigger the 'change' event.

### ISSUE THREAD

**Issue by jabas06** [driftyco/ionic#8690] opened 2016-10-14 00:02 UTC
#### Short description of the problem:
ion-toggle elements within a form doesn't trigger the change event on the form.

#### What behavior are you expecting?

Updating an ion-toggle should trigger the change event on the parent form.

**Steps to reproduce:**
1. Have an ion-toggle and an ion-input within a form
2. Enter some text on the input and the change event will be triggered when the input loses focus
3. Change the ion-toggle value. The change event is not triggered.

``` html
 <form [formGroup]="myForm" (change)="save()">
                <ion-item>
                    <ion-label floating>Name</ion-label>
                    <ion-input formControlName="name"></ion-input>
                </ion-item>
                <ion-item>
                    <ion-label stacked> Active</ion-label>
                    <ion-toggle formControlName="isActive"></ion-toggle>
                </ion-item>
</form>
```
 

**Which Ionic Version?** 2 rc1

**Comment by jgw96** [comment] 2016-10-14 15:01
Hello, thanks for using Ionic! Could you provide a repo that i can use to reproduce this issue?

**Comment by jgw96** [comment] 2016-10-17 00:07
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-10-17 00:07 UTC
Labels: needs reply, v2
