### ISSUE TITLE
in ios , menu not close when click out it if time deffrent is  less than 2500 millisecond between open and close

### ISSUE THREAD

**Issue by mashaly100200** [driftyco/ionic#5365] opened 2016-02-08 09:35 UTC
in ios , menu not close when click out it , it happened if time diff between open and close less than 2500 millisecond

although it work fine in android 

in tap-click.js    is there are bad effects if i change DISABLE_NATIVE_CLICK_AMOUNT   

from
var DISABLE_NATIVE_CLICK_AMOUNT = 2500;
to
var DISABLE_NATIVE_CLICK_AMOUNT = 0;

**Comment by jgw96** [comment] 2016-03-14 05:09
Thanks for opening an issue with us! We just need a little more info from you so that we can better help you with your issue. Would you mind posting a code sample, plunkr, or codepen so that we can reproduce your issue? Also if you could run `ionic info` and post the ouput here that would be great! Thanks again!

**Comment by jgw96** [comment] 2016-04-14 17:18
Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to respond back if your still having the issue! Thanks again!

**Closed by jgw96** 2016-04-14 17:18 UTC
Labels: menus
