### ISSUE TITLE
"Activated" class being added and removed directly when clicked anchor

### ISSUE THREAD

**Issue by 1BJK903** [driftyco/ionic#8723] opened 2016-10-15 22:23 UTC
Hi all,

I can't seem to find a solution for this. I have some tabs, in anchor tags and I can see that when I click on them, they get the class "activated" but they are actually deleted immediately after clicking..

My question: is this a bug? If not, how can I solve this?

` <a class="button filter-icon" ng-click="HereIFilter = 'Blabla'">`

**Comment by jgw96** [comment] 2016-10-16 21:43
Hello, thanks for opening an issue with us! Could you post a repo or gist that we can use to reproduce this issue?

**Comment by jgw96** [comment] 2016-10-25 15:30
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-10-25 15:30 UTC
Labels: needs reply, v2

**Comment by ddahan** [comment] 2017-08-29 17:24
Please let the issue open as @1BJK903 just wanted to know if it's a bug or not.
I was actually asking myself the same question.
Thanks.
