### ISSUE TITLE
perf: overflow-scroll=true freezes main page scroll

### ISSUE THREAD

**Issue by sohitri** [driftyco/ionic#6733] opened 2016-06-02 12:41 UTC
**Type**: <span ionic-type>perf</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>In my project, the view on first page have overflow-scroll=true. The next page contains a side menu which opens and shows a decision tree built using D3.js. After accessing it, if the user returns backs to the first page, the scroll freezes. Happens only in case of iOS. However, if I omit overflow-scroll directive, everything works fine. Is there any issue with D3.js and native scrolling in ionic for iOS plaform?</span>

<span is-issue-template></span>

**Comment by jgw96** [comment] 2016-06-02 16:53
Hello, thanks for opening an issue with us! Would you mind posting a plunker or repo that i can use to reproduce this issue? Thanks for using Ionic!

**Comment by jgw96** [comment] 2016-06-06 15:46
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-06-06 15:46 UTC
Labels: menus, needs reply, platform:ios, v1
