### ISSUE TITLE
Alerts in RTL apps appears LTR

### ISSUE THREAD

**Issue by theunreal** [driftyco/ionic#10147] opened 2017-01-23 16:16 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When creating a new alert, the alert is left to right, although the application is rtl (dir="rtl")

**Expected behavior:**
Alerts appear as from right to left

**Related code:**
Create any alert in rtl app
```
let alert = this.alertCtrl.create({
     title: 'Text from right to left',
     subTitle: 'shows as ltr',
     buttons: ['Verify']
   });
   alert.present();
```
*

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic 2 Rc.5
```

**Comment by mhartington** [comment] 2017-01-23 16:55
Quick check,  we could change this value to `start` instead of hard-coding it left.

https://github.com/driftyco/ionic/blob/3282c95e9b292417f41f9658e87572930cfb931e/src/components/alert/alert.md.scss#L24-L25

**Comment by mohamedsharaf** [comment] 2017-01-23 17:05
confirm https://github.com/driftyco/ionic/issues/9815

**Comment by jgw96** [comment] 2017-04-07 14:07
Hello, thanks for using Ionic! We really appreciate this feedback on RTL support. This is not currently high priority for us at the moment, but we are tracking it in #5035. Because of this I am going to close this issue as a duplicate of that issue and ask that you put your feedback on that issue. Please know that by me closing this issue I am not saying that your feedback is not important, or that RTL support is not important, but I am simply closing this issue as we like to keep our issues as organized as possible so things do not get lost in the weeds (which is better said than done haha).

**Closed by jgw96** 2017-04-07 14:07 UTC
Labels: css, v2
