### ISSUE TITLE
bug: ion-scroll only scrolls vertically or horizontally

### ISSUE THREAD

**Issue by ThorConzales** [driftyco/ionic#6001] opened 2016-03-31 14:41 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>Sometimes when scrolling around inside ion-scroll it only allows to scroll either vertically or horizontally.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment] 2016-03-31 15:47
Hello! Thanks for opening an issue with us! Are you setting the scrollX and scrollY to true? `<ion-scroll scrollX="true" scrollX="true"></ion-scroll>` If you do that then it enables scrolling both vertically and horizontally.

**Comment by ErkoKnoll** [comment] 2016-04-01 06:19
Hi, yes I'm setting them to true. Without them no scrolling is possible. The case is that half of the time it works as supposed, which is I can do free scrolling to any direction (360 degrees) but sometimes it locks only to either horizontal or vertical direction depending on the first initial vector. And sometimes even if I try to go diagonally it picks either horizontal or vertical vector, cant seem to figure out whats the exact case here. Good example here is that if I start with the initial vector of horizontal and keep my finger on the screen and suddenly change it to vertical or any other degree except 180 or 90 degrees (whatever represents the horizontal vector) it won't allow me to change direction, but locks me into horizontal scrolling mode. And that mode is locked in until the free sliding friction stops the motion.

**Comment by ErkoKnoll** [comment] 2016-05-04 07:23
Could you please consider moving it up in queue. It would be really nice if the scroller worked as supposed to like in Android.

Here is the screen recording: https://drive.google.com/file/d/0BxT1AJ0A_TYOVGZLQURSMU44WUU/view

And this is the code to reproduce with:
`
</ion-scroll>`

**Comment by bdoner** [comment] 2016-05-06 10:33
In the case where you have difficulties scrolling horizontal, could you try to scroll slightly vertical, and then see if horizontal works until you release?

Have you tried to add `swipeBackEnabled: false` in your @App decorators config?

If yes, I can say I'm experiencing the same issues with IOS.

**Comment by ErkoKnoll** [comment] 2016-05-09 05:40
If I scroll vertically and it is locked in vertical mode then I have to wait until vertical scrolling has ended before I can do horizontal like you said. However sometimes it works properly but it happens less frequent than locked mode scrolling.

And I do have swipeBackEnabled in set to false but in ion-nav element.

**Comment by jgw96** [comment] 2016-05-09 14:58
Hello @ErkoKnoll ! So after testing im thinking this is simply due to UIWebView having really crappy scroll events. We are currently working on making WkWebView the standard webview for ios ionic applications and i think this will fix this issue. I plan on doing some testing soon to confirm this and will let you know of my results. Thanks!

**Comment by jgw96** [comment] 2016-05-20 18:05
@ErkoKnoll So after testing with wkwebview this seems to be a uiwebview related issue.so it looks like something that will be fixed with wkwebview integration.

**Comment by Ionitron** [comment] 2016-08-24 18:01
Greetings @ThorConzales!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by jgw96** [comment] 2016-08-24 18:01
@ThorConzales is this still an issue with wkwebview?

**Comment by Ionitron** [comment] 2016-08-24 18:01
Greetings @ThorConzales!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment] 2016-08-24 18:01
Greetings @ThorConzales!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by ThorConzales** [comment] 2016-08-30 07:52
I did replace the standard ionic functionality with a third party library that also provides zooming capability and it works perfectly, so I cannot tell anymore.

**Comment by jgw96** [comment] 2016-09-01 16:09
Thanks for the info and thanks for using Ionic!

**Closed by jgw96** 2016-09-01 16:09 UTC
Labels: platform:ios, scroll, v2
