### ISSUE TITLE
How to pass navParams from child page to parent

### ISSUE THREAD

**Issue by gigocabrera** [driftyco/ionic#6536] opened 2016-05-15 13:53 UTC
#### Short description of the problem:

I know how to pass parameters from a parent page to a Child. But what I need is to pass parameters from a child page back to the parent. I cannot use `this.nav.push` because I will end up with 2 parent pages in the stack. Instead I just want to go back to the parent page and pass a parameter

Can something like this be implemented? Would it be possible?

```
goBack() {
    this.nav.pop(ParentPage, {
        firstname: "John",
        last-name: "Snow"
    });
}
```

**Other information:**  
This is in relation to this issue in the forums
https://forum.ionicframework.com/t/how-to-pass-navparams-from-child-page-to-parent/52078

**suggested workarounds:**
1) Service class, which may be an overkill for simple parameter passing needs
2) Use modal and pass data through the `dismiss()` method, which may not be the look and feel you want on your app

**Comment by jgw96** [comment] 2016-05-16 15:18
Hello! Thanks for opening an issue with us! I am going to close this as a duplicate of https://github.com/driftyco/ionic/issues/5724 . Feel free to comment over on that issue. Thanks for using Ionic!

**Closed by jgw96** 2016-05-16 15:18 UTC
Labels: modals, v2

**Comment by QCCS** [comment] 2017-12-14 01:56
some problem here
