### ISSUE TITLE
SinglePage to TabsPage not working properly on iOS

### ISSUE THREAD

**Issue by MrBokeh** [driftyco/ionic#7939] opened 2016-09-01 08:17 UTC
#### on Chrome, I can use code to control the single page (root page) to nav.push to TabsPage, but it doesn't work on iOS, I need to physically press a button to do this action instead.

**Steps to reproduce:**
1. the root page is set to a single page and the Single page use code to call nav.push to TabsPage
2. TabsPage constructor called but not pushed, it's on the background
3. Physically press a button to goto the TabsPage and now the tabs page constructor called the second time which mean now I have two tabspage.

**Which Ionic Version?** 2.11

**Run `ionic info` from terminal/cmd prompt:**

Your system information:

Cordova CLI: 6.3.0
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.36
Ionic App Lib Version: 2.0.0-beta.19
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.4.7
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment] 2016-09-01 15:53
Hello, thanks for opening an issue with us! Would you mind posting a repo or code snippet I can use to reproduce this issue? Thanks for using Ionic!

**Comment by jgw96** [comment] 2016-09-06 12:49
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-09-06 12:49 UTC
Labels: needs reply, platform:ios, v2
