### ISSUE TITLE
bug: ionic not allow to paste multiple time in a textarea!!!

### ISSUE THREAD

**Issue by Poojal123** [driftyco/ionic#4540] opened 2015-10-20 11:14 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.x</span>  <span ionic-webview>webview</span>

<span ionic-description>hiii,

when i am pasting some text to textarea it works first time..now when i try to paste some more text into same text area then it doen't behave properly.. that try to select the text instead of pasting...

pls ans as soon as possible...

i'll give u sample

<textarea  id="textarea" name="txtmsgpost"  class="textarea_single"></textarea>

try this on mobile it doesnt work...</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-10-20 11:14
Greetings @sharvari1!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4540). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4540)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment] 2015-10-22 16:35
Please provide example

**Comment by sharvari1** [comment] 2015-10-29 05:56
@mhartington 

extremely sry for the late reply

here is my codepen project

http://codepen.io/anon/pen/dYeazg

in textarea ot input box etc if i copy text from diff site and past it in textarrea first time it allow me to past. but i wanna again copy add past to same text area the it will not allowing me to past agin. it will go to selection mode or copy, cut, option will show..

pls help me. pls rply as early as possible

**Comment by sharvari1** [comment] 2015-10-29 05:59
here im attaching screen shot of bug.
for secon time pasting to same text area...
![screenshot_2015-10-29-11-16-13](https://cloud.githubusercontent.com/assets/8132240/10811279/3e6ff2b0-7e30-11e5-96bc-c5f5b94f82a6.png)

**Comment by jgw96** [comment] 2016-03-15 14:38
Hello! Thanks for opening an issue with us, we just need a little more info from you so that we can better help you with your issue. Would you mind posting a code sample, plunkr or codepen that we can use to reproduce your issue? Also, would you mind running `ionic info` and posting the output? Thanks again!

**Comment by jgw96** [comment] 2016-03-21 19:55
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!

**Closed by jgw96** 2016-03-21 19:55 UTC
Labels: platform:android, v1
