### ISSUE TITLE
bug: Navigation and history

### ISSUE THREAD

**Issue by Leftyx** [driftyco/ionic#4078] opened 2015-07-13 15:08 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>

I've found a few questions on StackOverflow about navigation, history and how it should work. 
Most people - and myself - struggle to understand how things are supposed to work.

There a [codepen](http://codepen.io/anon/pen/Kpepwx?editors=101) here where I am trying to figure why history doesn't always remember the last view rendered.  

Using the sequence: Home - Fact1 - Fact2 - Fact3 - Fact2

you can see the back button shows Fact1. I would expect Fact3.

Going through the code base I kind of figured out why that happens. It seems that $ionicHistory keeps track of all the views storing them in a collection. If the element is already in the collection, it is fetched using the info attached to it.

The view Fact2 was previously rendered and it's back view was Fact1.

If you try another sequence, though: Home - Fact1 - Fact2 - Home 

You notice that the back button now is **Fact2**. Home should be the root and it should not have any back button.
If I play the same sequence over and over: Home - Fact1 - Fact2 - Home - Fact1 - Fact2 - Home
etc etc I can see the collection views of **$ionicHistory.viewHistory()** grows indefinitely.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-07-13 15:08
Greetings @Leftyx!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4078). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4078)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by quanghoc** [comment] 2015-07-20 05:05
+1

**Comment by antoniocapelo** [comment] 2015-08-03 14:47
+1

**Comment by Ionitron** [comment] 2015-11-01 18:49
Greetings @Leftyx!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-11-01 18:49 UTC
Labels: ionitron:closed

**Comment by badhrin** [comment] 2015-11-19 14:35
Hi,

This issue is not closed. I am still having this issue as of Ionic CLI 1.7.10.
This is a major issue for me, due to which i am not able to use caching at all & have to use ugly workarounds. Appreciate if this can be resolved.

**Comment by Leftyx** [comment] 2015-11-19 15:27
Badhir,

nobody seem to be interested in navigation issues. There's not much we can do.

**Comment by sam0737** [comment] 2016-01-03 23:22
I have a sort of similar problem.
I generate a random number and push to Fact2 params to make sure it make a new view, instead of reusing the previous one. The view is cached based on name+params.

**Comment by ahmedrshdy** [comment] 2016-02-06 11:03
This is a nagging problem if you have nested views in a tab view. Please fix or suggest a workaround

**Comment by adir1** [comment] 2016-02-10 14:12
I am also having hard time with this one, and everyone on our team in fact. If the issue is simply caching, just add cache-view="false" to your ion-view.
However we did not find any way to force proper behavior of Back button? In some scenarios we want the user to go back to "beginning" if they click on Back button from within "wizard" like flow. So for example:
Tab.Home -> Tab.Page1 -> Tab.Page2
Now if they click "Back" on Page2, we want them to go to Tab.Home. Normally when already entering Page2 we know that back view needs changing, but is there a reliable way of changing back view?

**Comment by pawangjain** [comment] 2016-02-23 13:15
This issue seems to be OPEN still.

Someone Please fix or suggest a workaround

Thanks.

**Comment by nithinkrishnan** [comment] 2016-04-11 09:20
Wierd, unable to get a way through this :
If we have a side menu, all the pages we visit clicking on menus from side menu are considered as root with the menu option appearing in each page (but going further with navigation in that branch it gets replaced by back arrow). The wit is, on pressing back from the page visited from the side menu say 'side page 1', it goes back to home page say 'Dashboard', but now it will have the back button in left corner in the header, instead of the menu icon, which appears as if the page where a home page. 

Any idea how to go about this? :(

**Comment by volantes** [comment] 2016-07-16 16:20
My solution/workaround:

Create an additional state to traverse to that references the same url, templateUrl, and controller.

For example if I have:

`$stateProvider.state('fact2', {
    url: '/fact2/:factFilter',
    templateUrl: 'fact2.html',
    controller: 'Fact2Ctrl'
  })`

Then I also create a "fact2" duplicate with only a different state name

`$stateProvider.state('fact2_duplicate', {
    url: '/fact2/:factFilter',
    templateUrl: 'fact2.html',
    controller: 'Fact2Ctrl'
  })`

If I am receiving the funny transition behavior, I can call $state.go('fact2_duplicate') the history will be more inline to what I am expecting.
