### ISSUE TITLE
bug: Long dynamic header titles are cutoff

### ISSUE THREAD

**Issue by DavidFrahm** [driftyco/ionic#4661] opened 2015-11-23 22:42 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>In multiple Ionic apps where I need to set the view title dynamically, I use this markup:

```
<ion-view>
    <ion-nav-title ng-bind="category.name"></ion-nav-title>
    <ion-content>
    ...snip...
```

That works great until it encounters a view title that too long to fit in the bar (easier to test on smaller devices like iPhone 4/5).  With a long value, it displays just like one character and the ellipsis.

I fix it by adding this to my scss:

```
// Longer ion header titles intermittently have crazy large right values on iOS
.platform-ios,
.platform-browser {
  .title.title-center.header-item {
    right: 26px !important;
  }
}
```

This seems like it might just be an issue with the Angular lifecycle of things, and might not be a clean fix on the Ionic side. (Similar to the issue of why `view-title="{{category.name}}"` has issues.)</span>

<span is-issue-template></span>

**Comment by mhartington** [comment] 2015-11-23 22:43
Codepen demo please

**Comment by DavidFrahm** [comment] 2015-11-23 23:02
http://codepen.io/davidfrahm/pen/vNPoVa

Make the viewport really small, reload the page, then click the button to navigate to the view with long/broken title

**Comment by DavidFrahm** [comment] 2015-11-23 23:04
<img width="536" alt="ionic-issue-4661" src="https://cloud.githubusercontent.com/assets/889791/11352805/34e679c0-9204-11e5-845f-c1facf85fd2a.png">

**Comment by adamhughes86** [comment] 2016-02-10 17:18
Any news on this?

Same issue as #945 which was reopened. No feedback on that one either

**Comment by zanemcca** [comment] 2016-02-23 23:47
+1

**Comment by leizard** [comment] 2016-03-11 09:41
+1. I met the same problem

**Comment by thanhnh-infinity** [comment] 2016-03-12 04:38
+1 . Yes, this issue has no longer fixed completely for long time

**Comment by Louis-P** [comment] 2016-03-22 20:29
+1

**Comment by dilignt** [comment] 2016-03-24 10:33
+1

**Comment by jgw96** [comment] 2016-03-24 15:03
thanks @DavidFrahm for the codepen! We are definitely gonna have to take a look at this. It looks like the title is overflowing way too early, is that the issue you all are describing?

**Comment by DavidFrahm** [comment] 2016-03-24 21:59
@jgw96 Yes, that sounds like one way to look at it.  Honestly, it's been a long time and I've just become used to it and always use the CSS workaround in all my projects.

**Comment by taigeair** [comment] 2016-04-07 15:46
Happens for me too

**Comment by johnfakeacc** [comment] 2016-04-13 14:21
annoying..

**Comment by zanemcca** [comment] 2016-04-13 15:15
Here is my workaround.

```
//Hack to fix squashed title on iOS
// ionic issue #4661
.platform-ios {
  .title.title-center.header-item {
    left: 49px!important;
    right: 49px!important;
  }
}

.platform-android {
  .title.title-left.header-item {
    right: 68px!important;
  }
}
```

**Comment by johnfakeacc** [comment] 2016-04-13 15:17
Great thanks!

**Comment by Bouzmine** [comment] 2016-04-13 22:04
Only problem I find with this workaround is that long titles will overlap the "Back » button. Would there be a way to do like native, to make header title go to the left (screenshot 2).

**Comment by zanemcca** [comment] 2016-04-13 23:12
What screenshot? I am having no issue with back button overlap with this solution.

**Comment by danbucholtz** [comment] 2016-05-06 21:20
Hello everyone,

This fix will be in the [nightly build](http://code.ionicframework.com/#nightly) tonight.

Full disclosure - there are several fixes we could do make with the header, this is a start.  If you dynamically add buttons next to this, you may still run into problems.  That is a separate issue that we need to fix as well.

Please test and let me know how it goes.  The easiest way to test is to download the [nightly ionic.bundle.js](http://code.ionicframework.com/nightly/js/ionic.bundle.js) file and place it in your project's lib/ionic/js directory, and then make sure your html file is importing the file correctly.

If needed, we'll reopen this.

Thanks,
Dan

**Closed by danbucholtz** 2016-05-06 21:20 UTC
Labels: css, v1

**Comment by magaliegimenes** [comment] 2016-09-12 10:35
Hello, 
Thanks for this fix, I waited for it but in my case it does not work. So, I searched for what was happening and I found out that on the method  "self.titleTextWidth", if I comment the break inside the "for" loop (js/angular/controller/headerBarController.js, line 1154), it works (As the element retrieved is always the one in my previous page with the current code).
Maybe the cause of the problem is that I always have tabs at the bottom of my page and they are always here after navigation.
Thanks in advance.
Regards
Magalie

**Comment by sinedied** [comment] 2017-02-23 16:01
The issue is actually that it use the first element with the `nav-bar-title` class, but it can be the one hidden (cached) from the previous screen, used for animations. A proper fix is:
```js
      var children = angular.element(element).children();
      for ( var i = 0; i < children.length; i++ ) {
        var child = angular.element(children[i]);
        if ( child.hasClass('nav-bar-title') && !child.hasClass('hide') ) {
          element = children[i];
          break;
        }
      }
```
Thanks @magaliegimenes for the hint!

**Comment by mdanics** [comment] 2018-08-21 14:33
Facing this issue on Ionic 3.9.2 after using the SideMenu starter project
