### ISSUE TITLE
bug: App gets stuck on Splash Screen on some iPhones.

### ISSUE THREAD

**Issue by swapniljindal** [driftyco/ionic#5143] opened 2016-01-22 07:18 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>I am facing this issue where app, when run on an iOS device for the first time, runs smoothly but after force closing it, if I try to open it again, it gets stuck on the Splash Screen forever. It takes many tries of force closing and running to move past Splash Screen. In some cases, it took me more than 20 tries of Force Closing to move past Splash Screen.
If I uninstall and re-install again, it works. But again same issue after first run.
Moreover I am facing this issue only on iPhone 5 and 6. It works fine in the simulator and on 6s devices.

I have tested it on some devices. The results are :
IOS Version	iPhone version   Result
9.2.1	        5                         Gets Stuck
9.2 (13C75)	5                         Gets Stuck
9.2.1 ( 13D15)	6s                       Works
9.2 (13C75)	6                         Gets Stuck
9.2	                6                         Gets Stuck

I tried it on 3 different 6s phones and it works fine. Apart from that it gets stuck on the splash screen for iPhone 5 and 6.

My system info is:

Cordova CLI: 5.4.1
Ionic Version: 1.2.0
Ionic CLI Version: 1.7.12
Ionic App Lib Version: 0.6.5
ios-deploy version: 1.8.3 
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v4.2.3
Xcode version: Xcode 7.2 Build version 7C68 

Please help me out here.
Thanks</span>

<span is-issue-template></span>

**Comment by mhartington** [comment] 2016-02-03 22:50
Duplicate of #5324

Moving conversation over there

**Closed by mhartington** 2016-02-03 22:50 UTC
Labels: v1
