### ISSUE TITLE
Time input is not working as expected during initial focus

### ISSUE THREAD

**Issue by ImmanuelSamuel** [driftyco/ionic#5839] opened 2016-03-15 01:38 UTC
#### When time input field is clicked, the input moves up to the top of the screen as it does for other inputs but the time selector doesn't show up. I have to click it again for it to show up. Once the time input is in focus then clicking on it again brings up the pop-up immediately. I believe the problem is during the initial tap which brings it to focus.

**Steps to reproduce:**
1. I added the following code to one of pages in the tab.

```
<ion-input stacked-label>
        <ion-label>Time</ion-label>
        <input type="time" ngControl="time">
    </ion-input>
```

It would also be nice for the inputs to scroll back down to where they were after typing in any information.

**Comment by jgw96** [comment] 2016-03-16 15:20
Thanks for opening this issue! As this issue is a duplicate of https://github.com/driftyco/ionic/issues/5800 i will be closing this issue.

**Closed by jgw96** 2016-03-16 15:20 UTC

**Comment by EvanWillms** [comment] 2016-04-10 22:04
And #5800 is a duplicate of #5432.
