### ISSUE TITLE
source-map is not working in RC3

### ISSUE THREAD

**Issue by john5db** [driftyco/ionic#9243] opened 2016-11-19 18:58 UTC
**Ionic version:**  (check one with "x")
[X ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ X] bug report

**Current behavior:**
It is not showing source map files while debugging in chrome.

**Expected behavior:**
It should display files in chrome source tab so we can debug our code easily

**Steps to reproduce:**
add following config in package.json file
```
"config": {
    "ionic_source_map": "source-map"
  },
```
to enable source map .

**Other information:**
[Reference video of how to enable source map](https://www.youtube.com/watch?v=nCWCGS5hurY)
https://www.youtube.com/watch?v=nCWCGS5hurY

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.3.0
Xcode version: Not installed

```

**Comment by jgw96** [comment] 2016-11-22 18:12
Hello, thanks for using Ionic! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic-app-scripts/issues/431.

**Closed by jgw96** 2016-11-22 18:12 UTC
Labels: v2
