### ISSUE TITLE
Each click Tabs will reload the page

### ISSUE THREAD

**Issue by zhuzhiyu6839** [driftyco/ionic#11203] opened 2017-04-13 08:20 UTC
**# Each click Tabs will reload the page？why？**

my ionic version is 3.0.1

![6178d541-6aad-4f63-a706-174b372df74a](https://cloud.githubusercontent.com/assets/24268503/24995710/602effa6-2062-11e7-93fc-54cbbdb0b7e9.png)

#**Please look at the video**

[Uploading Problems MP4.zip…]()

**Comment by antoine92190** [comment] 2017-04-13 09:36
Duplicate of #11084

**Comment by jgw96** [comment] 2017-04-13 14:22
Hello all! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/11015

**Closed by jgw96** 2017-04-13 14:22 UTC
