### ISSUE TITLE
NavController - ionViewCanLeave throw an error with Android back button

### ISSUE THREAD

**Issue by TomDemulierChevret** [driftyco/ionic#10253] opened 2017-01-31 11:14 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When using the nav guard "ionViewCanLeave" the [documentation ](http://ionicframework.com/docs/v2/api/navigation/NavController/)states that the catch is already handled by Ionic for the back-button of the ion-navbar.
However, it's not done for the Android back-button (wich behave the same way as the ion-navbar back-button).
Therefore, when we use the back-button AND the nav(guard returns false, an error is thrown.

**Expected behavior:**
The catch of the Android back-button should be handled by the framework too, since its default behaviour is the same as the ion-navbar back-button.

**Steps to reproduce:**
Add the the following nav-gard to your page and then use the Android back-button.

**Related code:**

```
ionViewCanLeave(): boolean {
        return false;
    }
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.9.2
Xcode version: Not installed
```

**Comment by TomDemulierChevret** [comment] 2017-01-31 11:18
This issue is linked with this one : #10194 
Some nav changes are not properly catched.

**Comment by jgw96** [comment] 2017-01-31 15:12
Hello all! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/10194 as it is caused by the same underlying issue. Thanks for using Ionic!

**Closed by jgw96** 2017-01-31 15:12 UTC
