### ISSUE TITLE
bug: Vertical-only ion-scroll blocks side-menu

### ISSUE THREAD

**Issue by simplesmiler** [driftyco/ionic#3789] opened 2015-05-20 13:25 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Example: http://codepen.io/simplesmiler/pen/VLKLyg</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment] 2015-05-20 20:29
So it does. Thanks!

**Comment by paulking00** [comment] 2015-06-18 13:25
I am also running into this problem.
It becomes quite an issue when the `ion-scroll` is full page size when displaying a large list using `collection-repeat`.

Is there a way to disable event blocking in an `ion-scroll`?

e.g.
`<ion-scroll  direction="y"  enable-horizontal-swiping="true">`

**Comment by freddiescott** [comment] 2016-02-11 13:34
I am also running into a similar problem, reported in the closed issue above https://github.com/driftyco/ionic/issues/4027

I have multiple horizontal ion-scrollers, with blocks and things in them. I can easily scroll the ion-scrollers, but if I need to scroll vertically, I have to make sure to hold my finger on an area between the scrollers.

This bug only exists on iOS, the exact same code works on Android.

**Comment by jgw96** [comment] 2016-03-23 19:08
Hello! Are you all still experiencing this issue?

**Comment by jgw96** [comment] 2016-03-28 16:28
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to respond back if your still having the issue! Thanks again!

**Comment by freddiescott** [comment] 2016-03-29 05:14
Hi @jgw96,

I believe the problem is still present in the current version of ionic, due to this I have used another 3rd party component to give me the required functionality.

**Closed** 2016-05-05 16:17 UTC
Labels: ready, scroll, v1
