### ISSUE TITLE
bug: slidebox frozen when swiping past right edge on ios

### ISSUE THREAD

**Issue by calimeroteknik** [driftyco/ionic#4947] opened 2016-01-13 13:56 UTC
The slidebox can stop in an intermediate position and stay this way until the screen is touched again.
This happens when swiping past the right edge of the screen.

Here is a video where I reproduce the problem in the first seconds, then show the slidebox working normally apart from that: https://youtu.be/lDmGaBTmfl4

It does not happen on android, and I suspect that this is due to not handling the "swipe on right edge" cordova DOM event specific to ios.

**Comment by jgw96** [comment] 2016-03-14 16:57
Hello! Thanks for opening an issue with us, we just need a little more info from you so that we can better help you with your issue. Would you mind posting a code sample, plunkr or codepen that we can use to reproduce your issue? Also, would you mind running `ionic info` and posting the output? Thanks again!

**Comment by jgw96** [comment] 2016-03-21 17:07
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!

**Closed by jgw96** 2016-03-21 17:07 UTC
Labels: platform:ios, slidebox
