### ISSUE TITLE
bug: Lifecycle Events not fired, Pages not destroyed

### ISSUE THREAD

**Issue by runkelruebe** [driftyco/ionic#7529] opened 2016-08-03 08:21 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>My app is very simple. There is a HomePage. From there you can go into two other pages (both with this.nav.push();), on one there is a simple gallery where you can look at pictures, on the other page you take a picture and then pick a category for the thing on the picture. Once that is done, I do a this.nav.setroot(HomePage), Backbutton is disabled. In the HomePage I have a button that causes the app to upload all the pictures that haven't been uploaded yet. Once uploadig is finished, the uploader service fires an event. HomePage subscribes to that event (in the constructor).

The problem is: Once I've taken a couple of pictures and navigated back to the HomePage, the action defined in subscribe of the Homepage is fired multiple times.

To check if this comes from there simply being multiple instances of HomePage, I've added a random number to HomePage in the constructor that is logged to the console whenever there is any action going on the HomePage. It turns there are multiple instances of HomePage. That's why my app has been acting weird (to be precise: in the event subsciption a  Toast is presented, and That toast was shown a couple of times, depending on how many HomePages there were, this even prevented me from going to another Page until I've checked every single of the Toasts).
This means the pages are not destroyed.
The documentation says "They [pages] are destroyed when removed from the navigation stack (on pop() or setRoot())".
But apparently that is not correct as I am doing the setRoot() back to HomePage, and all the older HomePage pages are still alive and triggered by my custom events.

How come my pages aren't destroyed when I call setRoot()?

In an attempt to hotfix my issue, I tried to unsubscribe when certain lifecycle events are fired (ionViewWillLeave, ionViewDidLeave, ionViewWillUnload, ionViewDidUnload). This doesn't work. As a matter of fact, I've tested every single one of the lifecycle events, and not once was there anything fired (console.log etc).

ionic info

Your system information:

Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0-beta.7
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS: [Windows 10]
Node Version: v4.4.3</span>

<span is-issue-template></span>

**Comment by jgw96** [comment] 2016-08-03 14:50
Hello, thanks for opening an issue with us! Would you be able to provide a [plunker](http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview) that demonstrates this issue? Thanks for using Ionic!

**Comment by runkelruebe** [comment] 2016-08-04 11:05
OK, I did my [best here](http://plnkr.co/edit/CvIHljWfrHXHY53eEEEV) to demonstrate the structure of my app and added comments regarding what's going wrong.

**Comment by jgw96** [comment] 2016-08-05 19:32
Hello @runkelruebe ! Unfortunately it seems that your plunker has some syntax errors. Also unfortunately, i cannot seem to reproduce this issue with any of my tests. Would you mind fixing the plunker? Thanks !

**Comment by jgw96** [comment] 2016-08-09 16:55
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-08-09 16:55 UTC
Labels: needs reply, v2
