### ISSUE TITLE
bug: Menu open behind alert

### ISSUE THREAD

**Issue by FelixMarek** [driftyco/ionic#28067] opened 2023-08-28 13:21 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

If you have a screen with a menu, which can open via swipe and you have an open ion-alert dialog, you can still open the menu by swiping. 

So the menu opens behind the alert dialog backdrop. It is not touchable, but you can swipe it open or close.

### Expected Behavior

If an alert is open the menu could not be open or closed.

No interaction possible with the content behinde.

### Steps to Reproduce

1. Screen with menu
2. Open an ion-alert dialog
3. Swipe over the backdrop
4. The menu open/close

### Code Reproduction URL
https://github.com/FelixMarek/bug-report-menu-alert

_No response_

### Ionic Info

N/A

### Additional Information

In the past there was the same Issue: https://github.com/ionic-team/ionic-framework/issues/9046 and it was fixed

This fix is like the same, but for ion-modals: https://github.com/ionic-team/ionic-framework/pull/20546

**Comment by liamdebeasi** [comment] 2023-08-29 13:51
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/19410. The problem here is the menu gesture listener is added on the `document`. Please follow the linked thread for updates.

**Closed as not planned by liamdebeasi** 2023-08-29 13:51 UTC
Labels: triage
