### ISSUE TITLE
Ver 2 53 - kind of a breaking change - dev dependencies - typescript

### ISSUE THREAD

**Issue by alexbainbridge** [driftyco/ionic#5264] opened 2016-01-30 20:00 UTC
While its not an Ionic breaking change, it does break, if you don't change it

As per this change on the conference app on package.json 
https://github.com/driftyco/ionic-conference-app/commit/cebbaa67b9ffdf039bd01625286ab8d451a91a67

 "awesome-typescript-loader": "^0.15.9",
 "awesome-typescript-loader": "0.15.9",

 "typescript": "^1.7.5"
 "typescript": "1.7.5"

Might be worth adding to the breaking change log for those on Ionic 2..... before you get 101 questions about it :)

**Comment by tlancina** [comment] 2016-02-02 15:45
Thanks for the issue, are you saying this breaks if you do or don't remove the carets? Also what specifically is breaking?

**Comment by alexbainbridge** [comment] 2016-02-02 15:59
OK I just added the carets back (x2) and this is the error I get when doing ionic serve 

./app/app.js
Module build failed: Error: Emit skipped
    at State.emit (/Applications/MAMP/htdocs/TST/node_modules/awesome-typescript-loader/dist.babel/host.js:260:23)
    at transform (/Applications/MAMP/htdocs/TST/node_modules/awesome-typescript-loader/dist.babel/index.js:163:48)
    at _callee2$ (/Applications/MAMP/htdocs/TST/node_modules/awesome-typescript-loader/dist.babel/index.js:213:42)
    at tryCatch (/Applications/MAMP/htdocs/TST/node_modules/babel-regenerator-runtime/runtime.js:61:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/MAMP/htdocs/TST/node_modules/babel-regenerator-runtime/runtime.js:329:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/MAMP/htdocs/TST/node_modules/babel-regenerator-runtime/runtime.js:94:21)
    at fulfilled (/Applications/MAMP/htdocs/TST/node_modules/awesome-typescript-loader/dist.babel/index.js:11:32)
    at tryCatcher (/Applications/MAMP/htdocs/TST/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Applications/MAMP/htdocs/TST/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Applications/MAMP/htdocs/TST/node_modules/bluebird/js/main/promise.js:581:18)
    at Async._drainQueue (/Applications/MAMP/htdocs/TST/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/Applications/MAMP/htdocs/TST/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Applications/MAMP/htdocs/TST/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
 @ multi main (CLI v2.0.0-beta.15)

Cordova CLI: 5.4.1
Ionic Version: 2.0.0-alpha.53
Ionic CLI Version: 2.0.0-beta.15
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: Not installed
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v5.3.0
Xcode version: Xcode 7.2 Build version 7C68 

  "dependencies": {
    "angular2": "2.0.0-beta.1",
    "es6-promise": "3.0.2",
    "es6-shim": "0.33.13",
    "ionic-framework": "2.0.0-alpha.53",
    "ionicons": "3.0.0-alpha.3",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.0",
    "zone.js": "0.5.10"
  },
  "devDependencies": {
    "awesome-typescript-loader": "^0.15.9",
    "strip-sourcemap-loader": "0.0.1",
    "typescript": "^1.7.5"
  },

Yes I have checked that the NPM modules are as per the package.json (by running npm update) 

I noticed that you had moved the conf app to without carets (forcing an older version), so presumably you came across the same issue...... 

Moving to without carets (i.e. same as the conf app currently is), and doing an npm update (to roll back the modules to an older version), ionic serve works again...... 

I just thought hey, if I found this, perhaps someone else will, but beginning to think its just me :)

**Comment by alexbainbridge** [comment] 2016-02-02 16:12
Incidentally, I wasnt saying that this was necessarily an Ionic issue...... just that if others are going to run into it, might be worth mentioning on the change log, so they can apply the temporary fix (removal of carets), before a longer term solution is found

**Comment by tlancina** [comment] 2016-02-02 16:34
Awesome thanks! I just wasn't sure if it was the addition or removal of the carets that was causing the issue, if it was the latter I wanted to make sure we had compatible awesome-typescript-loader and typescript versions.

We actually removed the carets after getting burned pretty badly by some version drift in the CLI, so this is very helpful.

**Comment by tlancina** [comment] 2016-02-02 17:22
Hey @alexbainbridge I'm actually unable to reproduce this, could you confirm that cloning https://github.com/driftyco/ionic-conference-app, adding the carets, and running serve errors for you?

It looks like latest typescript package is 1.7.5, so the only effect the caret would have is to install awesome-typescript-loader 1.5.10. I'm trying to determine if this is a bug in the loader or if we need to change something in the project structure if it's erroring, thanks.

**Comment by alexbainbridge** [comment] 2016-02-02 17:42
Give me a few hours, will do this later tonight

**Comment by alexbainbridge** [comment] 2016-02-02 21:53
Dam, conference app works :) 

Right, now to work out the difference

**Comment by alexbainbridge** [comment] 2016-02-02 21:59
Actually, sorry, was being a numpty, didn't change the carets on conference install. When I did, similar error code. 

./app/app.js
Module build failed: Error: Emit skipped
    at State.emit (/Applications/MAMP/htdocs/ionic-conference-app/node_modules/awesome-typescript-loader/dist.babel/host.js:260:23)
    at transform (/Applications/MAMP/htdocs/ionic-conference-app/node_modules/awesome-typescript-loader/dist.babel/index.js:163:48)
    at _callee2$ (/Applications/MAMP/htdocs/ionic-conference-app/node_modules/awesome-typescript-loader/dist.babel/index.js:213:42)
    at tryCatch (/Applications/MAMP/htdocs/ionic-conference-app/node_modules/babel-regenerator-runtime/runtime.js:61:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/MAMP/htdocs/ionic-conference-app/node_modules/babel-regenerator-runtime/runtime.js:329:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/MAMP/htdocs/ionic-conference-app/node_modules/babel-regenerator-runtime/runtime.js:94:21)
    at fulfilled (/Applications/MAMP/htdocs/ionic-conference-app/node_modules/awesome-typescript-loader/dist.babel/index.js:11:32)
    at tryCatcher (/Applications/MAMP/htdocs/ionic-conference-app/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Applications/MAMP/htdocs/ionic-conference-app/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Applications/MAMP/htdocs/ionic-conference-app/node_modules/bluebird/js/main/promise.js:581:18)
    at Async._drainQueue (/Applications/MAMP/htdocs/ionic-conference-app/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/Applications/MAMP/htdocs/ionic-conference-app/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Applications/MAMP/htdocs/ionic-conference-app/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
 @ multi main (CLI v2.0.0-beta.15)

Your system information:

Cordova CLI: 5.4.1
Ionic Version: 2.0.0-alpha.54
Ionic CLI Version: 2.0.0-beta.15
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: Not installed
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v5.3.0
Xcode version: Xcode 7.2 Build version 7C68

**Comment by tlancina** [comment] 2016-02-02 22:09
Hey thanks for getting back, I'm still unable to repro on master or the typescript branch.  Could you try updating the CLI to beta.17 and tell me if it still errors please?

To be clear the steps are:
```
git clone git@github.com:driftyco/ionic-conference-app && cd ionic-conference-app
#edit package.json to have carets
npm install
ionic serve
```

My info (cordova and others don't show up because I'm using nvm):
```
Your system information:

Cordova CLI: Not installed
Ionic Version: 2.0.0-alpha.54
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v5.3.0
Xcode version: Xcode 7.2 Build version 7C68
```

Thanks!

**Comment by alexbainbridge** [comment] 2016-02-02 22:42
Updated to CLI 17 - no difference

Think found the issue..... you mentioned above that latest version of Typescript is 1.7.5 but I found 1.8.0
[Additionally fiddling with carets/versions on loader I have excluded that as the cause]

i.e 1.7.5 on Typescript works, 1.8.0 has an issue 

Are you on Typescript 1.8.0 ? 

npm outdated gives me.... (when caret used, but it hasn't been updated) 

Package                Current        Wanted        Latest  Location
typescript               1.7.5         1.8.0         1.7.5  ionic-conference-app

Not quite clear how it can want a version after the latest, but I am an NPM newbie (learning with Ionic 2) so I dunno

**Comment by tlancina** [comment] 2016-02-02 23:30
@alexbainbridge nice, I never knew about `npm outdated` :) So are you saying that `npm install` with the caret on typescript installs 1.8.0 for you?

Using npm 3.3.12 I do get 1.8.0 if I run `npm update`, which is also thoroughly confusing considering the docs say it should respect the latest tag (from https://docs.npmjs.com/cli/update): 

"This command will update all the packages listed to the latest version (specified by the tag config), respecting semver."

It also says: "NOTE: If a package has been upgraded to a version newer than latest, it will be downgraded."

I believe this is a bug in npm: https://github.com/npm/npm/issues/10298.  

Regardless of npm's quirks, I will take a look at possible issues with TypeScript 1.8 tomorrow.

**Comment by alexbainbridge** [comment] 2016-02-02 23:59
I use npm update rather than npm install. 

Yeah does seem that npm install keeps it on 1.7.5 even with the caret! Yes a mystery, but i guess also explains why other early v2 adopters not mentioning this, as most perhaps majority uses npm install. [Guess]

SO, as you say, think that explains why I have an error and you don't. So thats progress! 

Now, next layer of the onion, whats up with Typescript 1.8.0 :)

**Comment by tlancina** [comment] 2016-02-04 01:06
Finally tracked down the 1.8.0 issues, which thankfully look like they'll be resolved on TypeScript's end soon.  

Going to close this and track in https://github.com/driftyco/ionic/issues/5327.  Thanks for your help!

**Closed by tlancina** 2016-02-04 01:06 UTC
