### ISSUE TITLE
bug: Screen goes black: action sheet, modal.. etc

### ISSUE THREAD

**Issue by ihadeed** [driftyco/ionic#5430] opened 2016-02-12 00:34 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>When clicking a button to open an Action sheet or a modal, the screen goes black right away.

Console log would only output this (using Safari web inspector):
![image](https://cloud.githubusercontent.com/assets/13794420/12995590/7c7066bc-d0f6-11e5-904e-d7d1d260fccd.png)

</span>

<span is-issue-template></span>

**Comment by ihadeed** [comment] 2016-02-12 00:39
Also would like to add that displaying an alert sometimes makes the screen go black too .. .only on iOS

**Comment by brandyscarney** [comment] 2016-02-12 16:21
Can you please run `ionic info` from inside your project folder and give me the Ionic Version you are using? Also, what is the code you are using to call this?

**Comment by ihadeed** [comment] 2016-02-12 21:29
> Cordova CLI: 6.0.0
> Gulp version:  CLI version 3.9.1
> Gulp local:
> **Ionic Version: 2.0.0-beta.0**
> Ionic CLI Version: 2.0.0-beta.17
> Ionic App Lib Version: 2.0.0-beta.8
> OS:
> Node Version: v4.2.4

I'm creating an ActionSheet object inside a NavController.present() call ... do I have to create the action sheet then present it?

```
        this.navCtrl.present( // Presenting on the current nav controller
            ActionSheet.create({ // A new action sheet, defined by options below:
                title: 'Options',
                buttons: [
                    {
                        text: 'Advanced edit',
                        handler: () => {
                            let EditModal = Modal.create(EditTask, task);
                            this.navCtrl.present(EditModal); // Displays a modal, instance of EditTask class.
                            EditModal.onDismiss((data) => {
                                if(data){
                                    task = data;
                                    DB.updateTask(task).then(
                                        (res : any) => {
                                            task._rev = res.rev;
                                        },
                                        err => console.log(err)
                                    );
                                    this.refreshTasks();
                                }
                            });
                        }
                    },
                    {
                        text: 'Delete',
                        style: 'destructive',
                        handler: () => {
                            this.deleteTask(task); // Deletes a task
                        }
                    }
                ]
            })
        );
```

**Comment by brandyscarney** [comment] 2016-02-12 21:57
Hmmm no. I am able to see it working using the given code in Chrome, Safari and Firefox and an iPhone 6 simulator running iOS 9.2. Can you inspect the screen and see where the black div is coming from? Also, do you have these lines in your webpack.config:

https://github.com/driftyco/ionic-conference-app/commit/2ed59e6fd275c4616792c7b2e5aa9da4a20fb188#diff-11e9f7f953edc64ba14b0cc350ae7b9dL8

**Comment by ihadeed** [comment] 2016-02-12 22:09
I deleted the lines referring to web-animations from my webpack config file. I will try to inspect the emulator screen and I will get back to you.

**Comment by ihadeed** [comment] 2016-02-12 22:14
The black screen that I see is the <ion-nav> element with the class has-views. If I take out the background property from the CSS it just becomes a blank white screen instead.

**Comment by ihadeed** [comment] 2016-02-12 22:21
1. I click on the button that triggers the action sheet, it adds the element `<ion-action-sheet>` to the DOM and then it throws the error I posted in my initial post.
2. I click again on that button and the screen goes black without any changes in DOM.

**Comment by ihadeed** [comment] 2016-02-12 22:28
I provided you with access to the repository that contains my code. You can access it by following this URL: https://github.com/ihadeed/taskception

The function that triggers the ActionSheet is in [/app/pages/main/main.ts line 141](https://github.com/ihadeed/taskception/blob/master/app/pages/main/main.ts#L141)

Sorry if it's not so organized, I'm kind of a newbie to Github.

**Comment by brandyscarney** [comment] 2016-02-12 22:59
Okay thanks! I'm about to board a plane so I can take a look later tonight or maybe this weekend.

**Comment by ihadeed** [comment] 2016-02-12 23:05
I appreciate your help.

Have a safe trip.

**Comment by brandyscarney** [comment] 2016-02-13 17:10
Thank you! So I downloaded your repo, ran `npm install` and did an `ionic serve` - everything looked normal. Then, I ran `ionic run ios` and that also looks good. This is what my `ionic info` looks like:

```
Cordova CLI: 5.3.3
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic Version: 2.0.0-beta.0
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: Not installed
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v0.12.4
Xcode version: Xcode 7.2.1 Build version 7C1002
```

Could you try removing the `node_modules` folder and then doing a fresh `npm install`?

**Comment by ihadeed** [comment] 2016-02-13 19:22
My `ionic info` looks exactly the same except I have `Cordova CLI 6.0.0`

I just deleted the whole project and cloned it back from github, did `npm install` and `ionic state reset` and then ran `ionic run ios`... 

- The app refused to build, saying there was a file missing (sorry couldn't copy the error message)
- I ran `cordova platform rm ios` and `cordova platform add ios`
- I ran `ionic run ios` again and the application ran fine now .. I see the tutorial slider and I am able to add tasks
- I click on the `more` icon and the action sheet pops out
- However, when I clicked on `Advanced Edit` to open up the edit modal the app went black again ..


Also since you have tried the app, did you experience the issue I reported here: https://github.com/driftyco/ionic/issues/5432

**Comment by ihadeed** [comment] 2016-02-13 19:28
Just tried it on iPad 2 Simulator...
The action sheet doesn't show. I only see a backdrop.


![image](https://cloud.githubusercontent.com/assets/13794420/13029577/11c93e9c-d25e-11e5-9e76-d9ebd0054b62.png)

**Comment by adamdbradley** [comment] 2016-02-14 02:33
With the error `self.ele.animate is not a function` tells me something is outdated. `element.animate` is from the web animations API, which starting with alpha56, Ionic does not use.

**Comment by ihadeed** [comment] 2016-02-14 03:50
I developed the app with Ionic alpha56
When Ionic beta0 was released I did the following:
- Changed the Ionic version in my package.json
- Removed 3 lines in webconfig.that refere to webanimations
- Deleted my `node_modules`folder and ran `npm install`
- Ran a `ionic state reset` to reinstall and build platforms

Am I missing something?

**Comment by ihadeed** [comment] 2016-02-18 09:31
@adamdbradley @brandyscarney do you think the issue is from Ionic or something else? have you managed to reproduce the problem?

Thanks.

**Comment by adamdbradley** [comment] 2016-02-22 16:43
Be sure the `return false;` in the action sheet's handler. I think what's happening is that they click the button which opens your modal, but because there's no return false, an action sheet's button default is to also close the action sheet. But returning false prevents the default from closing the actionsheet.

This fix would have also helped out with this issue: https://github.com/driftyco/ionic/issues/5483

**Comment by danbucholtz** [comment] 2016-02-24 16:03
I see this issue pretty consistently when displaying modals in iOS.  I cannot come up with a concrete way to reproduce it yet, though.

**Comment by ihadeed** [comment] 2016-02-27 04:50
Here is what it looks like in Chrome:
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/13794420/13370851/8d4a0404-dce3-11e5-9a3e-b26b3c7be16d.gif)

And this is what it looks like in iOS simulator:
![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/13794420/13370852/8e7bcfc4-dce3-11e5-87fd-aa6bc1b08d12.gif)

**Comment by adamdbradley** [comment] 2016-02-28 02:52
I still haven't been able to reproduce this with the latest changes in master. Here's the test I've been using: https://github.com/driftyco/ionic/blob/2.0/ionic/components/action-sheet/test/basic/index.ts#L36

Does the button's handler return false? How can I update my test to replicate your issue?

**Comment by ihadeed** [comment] 2016-02-28 05:20
@adamdbradley you can checkout my repo here https://github.com/ihadeed/taskception/blob/master/app/pages/main/main.ts#L151

**Comment by brandyscarney** [comment] 2016-02-29 17:23
We're going to move this into beta.3 because we believe it will be fixed in the next release. Can you test against beta.2 when we release and see if it fixes it?

**Comment by ihadeed** [comment] 2016-02-29 17:55
@brandyscarney will do for sure.

I tested your repo version two days ago and it didn't make a difference. I will try again once you release beta 2.

Thanks for following up.

**Comment by ihadeed** [comment] 2016-03-02 22:19
Thank you @brandyscarney and @adamdbradley. The issue is fixed now after updating to beta.2

I appreciate your help!

**Comment by brandyscarney** [comment] 2016-03-02 22:26
@ihadeed Awesome! Glad it is working. :smile:

**Comment by ihadeed** [comment] 2016-03-05 14:08
@brandyscarney @adamdbradley 

FYI ..

Using `return false;` in the action sheet button handler still has issues. Everything works fine if I don't use it though. 

Here is a GIF demo:

![ezgif com-video-to-gif 2](https://cloud.githubusercontent.com/assets/13794420/13547947/b6d895dc-e2b1-11e5-839e-368ec0d51c82.gif)

**Comment by adamdbradley** [comment] 2016-03-05 19:07
Ok, i see the issue now. On it! Thanks!

**Comment by adamdbradley** [comment] 2016-03-05 19:35
Awesome, thanks for all the help, I think it should be fixed now. Thanks!

**Closed by adamdbradley** 2016-03-05 19:35 UTC
Labels: actionsheet, modals, v2
