### ISSUE TITLE
ion-slides missing output for onInit of underlying swiper

### ISSUE THREAD

**Issue by suau** [driftyco/ionic#10662] opened 2017-03-06 10:31 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request

**Current behavior:**
ion-slides removed the `options` input in RC-5 without exposing an alternative output for the `onInit` event of the underlying swiperjs instance, this is important to have, e.g. in some layout cases the sizes might be off, because it is rendering before layouting/sizing hasn't finished. This option would give us the opportunity to hide it until sizes has been properly set.

**Expected behavior:**
ion-slides should have a output/event-emitter for the `onInit` event of the underlying swiperjs instance.

```
Cordova CLI: 6.5.0 
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: macOS Sierra
Node Version: v6.10.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment] 2017-03-06 14:56
Hello, thanks for opening an issue with us. I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/10199

**Closed by jgw96** 2017-03-06 14:56 UTC

**Comment by suau** [comment] 2017-03-06 15:11
@jgw96 
Wrong duplicate and the issue persists, should be a duplicate of #10027
