### ISSUE TITLE
[Ionic2 beta 11] scrolling is rendered but not understood by browser

### ISSUE THREAD

**Issue by Isigiel** [driftyco/ionic#7617] opened 2016-08-09 07:49 UTC
#### Short description of the problem:
My newsfeed renders fine but chrome does not move the elemnt boundaries with the scrolled elements. Somehow all button clicks stay on the same height even with scrolling.
http://i.imgur.com/rnzAUnU.gifv
THis div demonstrates how the devtools don't scroll

#### What behavior are you expecting?
Normal scrolling

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
Even though I had some very weird update behaviour where one function would get a copy of the controller instance that is not reflected on the dom when changed, other errors where not shown in console or somewhere else.
 

**Which Ionic Version?** 2.beta.11

**Edit:** reverting the ionic version to beta 10 fixes all isues

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
I'm somehow not able to copy this so here's a screenshot http://i.imgur.com/bjVdoDR.png

**Comment by jgw96** [comment] 2016-08-09 15:45
Hello @Isigiel, thanks for opening an issue with us! ! Would you mind posting a repo that i can use to reproduce this issue? Thanks for using Ionic!

**Comment by Isigiel** [comment] 2016-08-09 17:09
Hey @jgw96,
sadly the code is closed source, but I made this gist with all the view code https://gist.github.com/Isigiel/68c99ccf0ab3b54402f89c2bdd6b8212.
I would also like to use a virtual repeat on that but that seems way not ready right now.

**Comment by jgw96** [comment] 2016-08-10 17:01
Hello @Isigiel ! Thanks for the gist! Would you mind removing the div that is surrounding your `ion-card`'s and giving this another try? Thanks!

**Comment by Isigiel** [comment] 2016-08-11 09:17
Sadly @jgw96 that didn't change a thing, the scrolling behaviour still doesn't update the _meta postitions_ ...

**Comment by jgw96** [comment] 2016-08-11 14:28
Hmm unfortunately I still cannot reproduce this in any of our tests or in any of my tests apps. Is their any way that you could post a minimal repo that I can use to reproduce this?

**Comment by Isigiel** [comment] 2016-08-11 15:45
Sadly there is loads of server stuff happeing which I really can't share also login is required to get the newsfeed. I will able to look into this again in around three weeks, so if the issue still happens with 12 (which might be released ;)) I'll try to reproduce it in a repo to share.
Thanks for your time so far though @jgw96

**Comment by jgw96** [comment] 2016-08-11 15:47
@Isigiel Sounds good and no problem! Also, instead of giving me access to the full app, it would actually be even more beneficial if the repo was a minimal example, preferably based on one of our starters, using pure ionic 2 code. Thanks for using Ionic!

**Comment by jgw96** [comment] 2016-08-11 17:56
Hello! I am going to be closing this issue for now since we cannot reproduce, but definitely feel free to comment if you still have this issue in beta.12 and can put together a reproducible example!

**Closed by jgw96** 2016-08-11 17:56 UTC
Labels: v2
