### ISSUE TITLE
The web page popped by ion-item has duplicate ino-nav-view,and the scroll doesn’t work

### ISSUE THREAD

**Issue by xinshouke** [driftyco/ionic#3625] opened 2015-04-27 14:13 UTC
I new a project as the sample chat, in the Chats page, click the item to popup ChatDetail web page,but there are two <ino-nav-view>..</ino-nav-view>.One is the first web page Chats, other one is Chatdetail.  It make the scroll doesn't work.But I refresh the page, the scroll  works well again! And the  html body have only one <ino-nav-view>,it's for Chatdetail.

**Comment by Ionitron** [comment] 2015-04-27 14:13
Greetings @xinshouke!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3625). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3625)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment] 2015-04-28 15:50
Greetings @xinshouke!

My sensors indicate that I require more information in order to assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this happen occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com), where many humans will be able to offer wisdom and advice.

Thank you for allowing me to assist you.

<span ionitron-needs-reply></span>

**Comment by Ionitron** [comment] 2015-08-09 22:54
Greetings @xinshouke!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-08-09 22:54 UTC
Labels: ionitron:closed
