### ISSUE TITLE
UWP uses iOS styling by default instead of WP styling

### ISSUE THREAD

**Issue by Bandito11** [driftyco/ionic#6220] opened 2016-04-18 16:56 UTC
**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
When I build a windows app using** ionic build windows** it doesn't use the **WP styling**, it uses the **iOS styling**. 

BUT when I use **ionic run windows** it uses the correct version of the scss.

#### What behavior are you expecting?
Open the win10 app and use the scss from wp not iOS

**Steps to reproduce:**
1. ionic build windows
2. install package via powershell on a win10 pc
3. just open the app in the start menu

**Which Ionic Version?** 1.x or 2.x
ionic 2.0.0-beta.25
ionic-angular: 2.0.0-beta.4

**Comment by Bandito11** [comment] 2016-04-18 17:54
Just deleted the package folder from the '../platform/windows and created a new one via **VS2015 **and it didn't work either. I have to use the **config** to force into **wp mode**.

**Comment by jgw96** [comment] 2016-04-19 14:54
Could you try ionic@nightly? I think there was a fix for this since beta.4 released. To use ionic nightly run `npm rm ionic-angular` and then run `npm install ionic-angular@nightly` and then try the app again. Thanks!

**Comment by Bandito11** [comment] 2016-04-19 18:06
Ok it works. But the textboxes don't go wp mode now, not even in my Chrome emulators when I `ionic serve` and it used to do it before. In other words the tipography and most of the styling I noticed is wp mode except for the textboxes.

**Comment by Bandito11** [comment] 2016-04-19 18:30
Ok the textbox styling of wp don't appear on any of my UWP apps but they appear on `ionic serve` Chrome browser lumia 520 chrome emulator.

**Comment by jgw96** [comment] 2016-04-19 18:36
@Bandito11 Thanks for the info!  So with nightly its better than with beta.4 but textbox styling is broken correct?

**Comment by Bandito11** [comment] 2016-04-19 18:40
That I noticed yes. Had to test it out in a short time because I have class. But everything looks wp aside from the textboxes in a UWP.

**Comment by jgw96** [comment] 2016-04-19 18:52
@Bandito11 alright thanks for the info! I'll look more into this

**Comment by jgw96** [comment] 2016-04-19 19:45
@Bandito11 Do you mind making a plunker that i can use to reproduce this issue?

**Comment by Bandito11** [comment] 2016-04-19 23:28
@jgw96 

I just saw another problem with the ion-buttons for Android and WIndows.


When I do this in both:

```
<ion-navbar *navbar hideBackButton="true" primary>    
    <ion-buttons start>
        <button menuToggle><ion-icon name="cog"></ion-icon></button>
    </ion-buttons>
    <ion-title>
        Store Name
    </ion-title>
    <ion-buttons end>
        <button (click)="logOut()">Log out</button>
    </ion-buttons>
</ion-navbar>
```

The ion-buttons don't get where they supposed to be.

I am expecting of the buttons being before the ion-title and after the ion-title respectively.

**Comment by Bandito11** [comment] 2016-04-19 23:29
@jgw96 : I'll check about that. Never done that before :/

**Comment by jgw96** [comment] 2016-04-20 18:56
@Bandito11 hey sorry should have shared this link to you earlier. Here is a plunker i made that you can use as a template for yours: http://plnkr.co/edit/sSFR9jbfTsxgAmrm9hUR?p=preview

**Comment by jgw96** [comment] 2016-05-10 15:52
Hello! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-05-10 15:52 UTC
Labels: menus, platform:ios, v2
