### ISSUE TITLE
bug: Upgraded project to Alpha51 doesn't show ionicons

### ISSUE THREAD

**Issue by lordgreg** [driftyco/ionic#5171] opened 2016-01-24 20:37 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I've recently upgraded my project to Ionic alpha 51. With that, I've also updated ionic config file and installed ionicons over npm as changelog stated (https://github.com/driftyco/ionic/blob/2.0/CHANGELOG.md).

Since then, I can't see ANY ionicons. I've also tried to create new Tabs project and copy all config files where icons are visible (tsconfig, ionic config, package.json and webpack.config.js) to my project, delete node_modules/ and remove www/build/ directory. The icons are still not visible. Log doesn't show any errors either.</span>

<span is-issue-template></span>

webpack.config.js
```
var path = require('path');


module.exports = {
  entry: [
    path.normalize('es6-shim/es6-shim.min'),
    'reflect-metadata',
    'web-animations.min',
    path.normalize('zone.js/dist/zone-microtask'),
    path.resolve('app/app')
  ],
  output: {
    path: path.resolve('www/build/js'),
    filename: 'app.bundle.js',
    pathinfo: false // show module paths in the bundle, handy for debugging
  },
  devtool: 'source-map',
  module: {
    loaders: [
      {
        test: /\.ts$/,
        loader: 'awesome-typescript',
        query: {
          'doTypeCheck': true,
        },
        include: path.resolve('app'),
        exclude: /node_modules/
      },
      {
        test: /\.js$/,
        include: path.resolve('node_modules/angular2'),
        loader: 'strip-sourcemap'
      }
    ],
    noParse: [
      /es6-shim/,
      /reflect-metadata/,
      /web-animations/,
      /zone\.js(\/|\\)dist(\/|\\)zone-microtask/
    ]
  },
  resolve: {
    alias: {
      'ionic': 'ionic-framework',
      'web-animations.min': path.normalize('ionic-framework/js/web-animations.min')
    },
    extensions: ["", ".js", ".ts"]
  }
};

```

ionic.config.js
```
module.exports = {
  proxies: null,

  paths: {
    html : {
      src: ['app/**/*.html'],
      dest: "www/build"
    },
    sass: {
      src: ['app/theme/app.+(ios|md).scss'],
      dest: 'www/build/css',
      include: [
        'node_modules/ionic-framework',
        'node_modules/ionicons/dist/scss'
      ]
    },
    fonts: {
      src: [
        'node_modules/ionic-framework/fonts/**/*.+(ttf|woff|woff2)',
        'node_modules/ionicons/dist/fonts/**/*.+(ttf|woff|woff2)'
       ],
      dest: "www/build/fonts"
    },
    watch: {
      sass: ['app/**/*.scss'],
      html: ['app/**/*.html'],
      livereload: [
        'www/build/**/*.html',
        'www/build/**/*.js',
        'www/build/**/*.css'
      ]
    }
  },

  autoPrefixerOptions: {
    browsers: [
      'last 2 versions',
      'iOS >= 7',
      'Android >= 4',
      'Explorer >= 10',
      'ExplorerMobile >= 11'
    ],
    cascade: false
  },

  // hooks execute before or after all project-related Ionic commands
  // (so not for start, docs, but serve, run, etc.) and take in the arguments
  // passed to the command as a parameter
  //
  // The format is 'before' or 'after' + commandName (uppercased)
  // ex: beforeServe, afterRun, beforePrepare, etc.
  hooks: {
    beforeServe: function(argv) {
      //console.log('beforeServe');
    }
  }
};
```

package.json
```
{
  "dependencies": {
    "angular2": "2.0.0-beta.1",
    "es6-promise": "3.0.2",
    "es6-shim": "0.33.13",
    "ionic-framework": "2.0.0-alpha.51",
    "ionicons": "3.0.0-alpha.3",
    "ng2-translate": "^1.4.1",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.0",
    "tslint": "^3.3.0",
    "zone.js": "0.5.10"
  },
  "devDependencies": {
    "awesome-typescript-loader": "0.15.9",
    "strip-sourcemap-loader": "0.0.1",
    "typescript": "1.7.5"
  },
  "name": "app",
  "description": "app: An Ionic project",
  "cordovaPlugins": [
    "cordova-plugin-device",
    "cordova-plugin-console",
    "cordova-plugin-whitelist",
    "cordova-plugin-splashscreen",
    "cordova-plugin-statusbar",
    "ionic-plugin-keyboard"
  ],
  "cordovaPlatforms": [
    "android"
  ]
}
```

tsconfig.json
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "noEmitOnError": false,
    "rootDir": ".",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true,
    "sourceRoot": "",
    "inlineSourceMap": false,
    "inlineSources": false
  },
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false
}
```

**Comment by wulfsolter** [comment] 2016-01-25 00:53
Dupe of https://github.com/driftyco/ionic/issues/5155 and https://github.com/driftyco/ionic/issues/5167

**Comment by mhartington** [comment] 2016-01-25 01:43
Closing as duplicate, will continue this over in https://github.com/driftyco/ionic/issues/5155

**Closed by mhartington** 2016-01-25 01:43 UTC
Labels: v2
