### ISSUE TITLE
Switching between pages with slides throws exception

### ISSUE THREAD

**Issue by Daskus1** [driftyco/ionic#11024] opened 2017-04-03 09:41 UTC
**Ionic version:**  (check one with "x")
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
When you switch quickly between two pages which have a few slides inside an exception is thrown and the whole app needs to be restarted.

**Expected behavior:**
Switching between pages with slides should not break the app.

**Steps to reproduce:**
This repo reproduces the issue: https://github.com/Daskus1/ionic-slides/
Just switch a few times, quickly, between 'Kittens' and 'Puppies' segment and the error should appear.

**Other information:**
```
TypeError: Cannot read property 'removeAttribute' of undefined
    at cleanupStyles (swiper.js:895)
    at destroySwiper (swiper.js:932)
    at Slides.ngOnDestroy (slides.js:1027)
    at Wrapper_Slides.ngOnDestroy (/IonicModule/Slides/wrapper.ngfactory.js:28)
    at View_HomePage4.destroyInternal (/AppModule/HomePage/component.ngfactory.js:542)
    at View_HomePage4.AppView.destroy (view.js:203)
    at View_HomePage4.DebugAppView.destroy (view.js:606)
    at ViewContainerRef_.remove (view_container_ref.js:282)
    at ViewContainerRef_.clear (view_container_ref.js:303)
    at SwitchView.destroy (ng_switch.js:31)
    at SwitchView.enforceState (ng_switch.js:42)
    at NgSwitchCase.ngDoCheck (ng_switch.js:233)
    at Wrapper_NgSwitchCase.ngDoCheck (/CommonModule/NgSwitchCase/wrapper.ngfactory.js:32)
    at CompiledTemplate.proxyViewClass.View_HomePage0.detectChangesInternal (/AppModule/HomePage/component.ngfactory.js:778)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (view.js:425)
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
 ordova CLI: 6.4.0
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.6.0
Xcode version: Not installed
```

**Comment by jgw96** [comment] 2017-04-03 19:01
Hello, thanks for using Ionic, we will look into this issue.

**Comment by jgw96** [comment] 2017-04-05 16:45
Hello, going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/10830

**Closed by jgw96** 2017-04-05 16:45 UTC
Labels: v2
