### ISSUE TITLE
Select not working (Android)

### ISSUE THREAD

**Issue by metalzombiegirl** [driftyco/ionic#8309] opened 2016-09-29 16:04 UTC
#### Handling of 'touchstart' input event was delayed for 2147483647 ms due to main thread being busy. Consider marking event handler as 'passive' to make the page more responive.  Ionic.bundle.js:7507

When the select is touched, the above warning is given and the select never opens up with the options.  The main browser I used is Chrome.

#### What behavior are you expecting?
Touch the select and the options should appear to be selected.

**Steps to reproduce:**
To reproduce, open the chrome developer tools and toggle the device toolbar. Clicking on the select box will now not expand the options.

**Please see http://stackoverflow.com/questions/39642248/how-can-i-get-ionic-select-box-working-on-android-again/39774861#39774861
 

**Which Ionic Version?** 1.3.1

#### Plunker that shows an example of your issue

**For Ionic 1 issues** - https://plnkr.co/edit/8L4ERxWROkflF1aPAcxk?p=preview

**Comment by jgw96** [comment] 2016-09-29 17:11
Hello, thanks for opening an issue with us! I am going to be closing this one as a duplicate of https://github.com/driftyco/ionic/issues/8181. Thanks for using Ionic!

**Closed by jgw96** 2016-09-29 17:11 UTC
