### ISSUE TITLE
Add the ability to include the Android box-shadow via data uri

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5084] opened 2016-01-18 23:37 UTC
_From @bensperry on September 28, 2015 14:51_

Sometimes Android uses a box-shadow beneath the navbar. For performance sake, let's try offering this ability with ionic as well, by means of a png (data uri).

I attached it here. Give it a try and let's test this s**t.

![header-box-shadow](https://cloud.githubusercontent.com/assets/519526/10138998/8b1e073c-65c6-11e5-8a01-b69779dd97e5.png)

_Copied from original issue: driftyco/ionic2#184_

**Comment by brandyscarney** [comment] 2016-03-29 19:44
Closing as a duplicate of https://github.com/driftyco/ionic/issues/5084 because I like that one more. :stuck_out_tongue:

**Closed by brandyscarney** 2016-03-29 19:44 UTC
Labels: P4: nice to have, v2
