### ISSUE TITLE
iOS css is clipping bottom pixel of characters

### ISSUE THREAD

**Issue by aparajita** [driftyco/ionic#5600] opened 2016-02-25 06:57 UTC
#### Short description of the problem:

In various components, e.g. list items, checkboxes, and text inputs, the height seems to be 1px too short, since the bottom pixel (or perhaps 2 including antialiasing) of the letter "g" is consistently cut off. You can see it for example in http://ionicframework.com/docs/v2/components/#card-list, look at the "g" in "Shopping" and "Dog Park".

This only happens with the iOS css, the Android css is fine.
#### What behavior are you expecting?

I expect to see the entire height of the character.

**Ionic Version**: 2.0

**Browser & Operating System**: Chrome 48.0.2564.116 on OS X 10.11.3

**Comment by brandyscarney** [comment] 2016-02-27 00:31
Seems this is caused by `overflow: hidden` on the `ion-label`. This is necessary though for `text-overflow: ellipsis` to work. Can't use `overflow-x` because of this: http://stackoverflow.com/a/11163865/3802466

I don't want to hardcode a line-height for this...so I'm going to see if I can change the `margin` to `padding`. Will continue to investigate. Thanks for the issue! :smile:

**Comment by alexbainbridge** [comment] 2016-04-21 19:12
Also currently selected select values on IOS (mentioning because not expressly in the list above) 
By currently selected I mean NOT the popup/modal, but the value "below" it in the base form

**Comment by simiansim** [comment] 2016-06-14 05:43
A **padding-bottom** value using **em** values on the **ion-label** might work for the card-list example.

Specifically:
`padding-bottom: 0.1em;`

EM padding is relative to the font size, rather than the dimensions of the element, which is a good thing here.

**Comment by jgw96** [comment] 2017-05-12 15:59
Hello all! I am going to close this issue as I cannot reproduce this in the latest version of ionic.

**Closed by jgw96** 2017-05-12 15:59 UTC
Labels: platform:ios, v2
