### ISSUE TITLE
bug: bug: ion-view view-title not being set correctly after $state.transitionTo()

### ISSUE THREAD

**Issue by mixersoft** [driftyco/ionic#3906] opened 2015-06-09 07:42 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>My nav bar titles are sometimes out of sync with the current view after a state transition. This is in a project which uses `ion-side-menu`.

When I transition from one menu-item to another, I often see the OLD value for `$scope.watch.viewTitle` in the navBar after `$ionicView.enter' is complete. I can set the viewTitle manually only from within a `$timeout`. Maybe a viewCaching issue?

```html
  <!-- using ionic start with 'sidemenu' project template -->
  <ion-view view-title="{{watch.viewTitle}}"> </ion-view>
```

```javascript
  // from the controller
  $scope.$on('$ionicView.enter', function() {
      $scope.watch.viewTitle = $state.params.title;
      console.log("$ionicView.enter, title=", $scope.watch.viewTitle);
      return $timeout(function() {
        // I need to call this from a $timeout for the viewTitle to reliable update
        return $ionicNavBarDelegate.title($scope.watch.viewTitle);
      });
    });

  $scope.$on('$stateChangeSuccess', function(event, toState, toParams, fromState, fromParams, error) {
      console.log("title=", $scope.watch.viewTitle);
      console.log("stateChangeSuccess complete");
    });
```
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-06-09 07:42
Greetings @mixersoft!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3906). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3906)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mixersoft** [comment] 2015-06-09 08:20
here is a codepen: http://codepen.io/anon/pen/VLbqWO?editors=101

Note: on further inspection, the problem seems to be cause when I set a $scope variable from inside the `$stateChangeSuccess` handler. see the comments in the codepen for more details

**Comment by sclearion** [comment] 2015-06-09 15:45
I looked at the codepen and saw your issue "nav bar titles are sometimes out of sync". I see you passing atoms in your state declarations 
```javascript 
url: "/check-in/:name"
```
but I dont see you using ```$stateParams``` to fetch the atom to process in your view. Instead you are relying on intermediary observers like ```$stateChangeSuccess```. I do the same thing you are trying to do but I use ```$stateParams```. IMHO, you need to adjust your convention

**Comment by mixersoft** [comment] 2015-06-13 13:58
Hi, thanks for commenting. But I'm not exactly clear on the difference - can you fork the codepen and give me an example?

**Comment by mrded** [comment] 2015-07-01 16:50
I have similar issue but with `$http`. 

How to reproduce: 

1. Create two views (`foo` & `bar`).
2. Make a link from view `foo` to view `bar`.
3. In the controller of view `bar` load a json via `$http` and put a result to `$scope.title`
4. In `bar` view set `<ion-view view-title="{{title}}">`

Result: When you open `foo` and click on `bar` link - you will not see new title, it will still empty.

If you do the same but with `$timeout` instead of `$http` - it works as expected.
Without any delays it works as well.

Please take a look my codepen example: http://codepen.io/mrded/pen/rVJjNp

**Comment by mrded** [comment] 2015-07-02 10:03
Actually using [`ion-nav-title`](http://ionicframework.com/docs/api/directive/ionNavTitle/) solves my problem:

    <ion-view>
      <ion-nav-title>{{title}}</ion-nav-title>
      <ion-content></ion-content>
    </ion-view>

**Comment by jgw96** [comment] 2016-03-23 19:11
Hello! Are you all still experiencing this issue?

**Comment by jgw96** [comment] 2016-03-28 16:28
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to respond back if your still having the issue! Thanks again!

**Closed by jgw96** 2016-03-28 16:28 UTC
Labels: navigation, needs reply, v1
