### ISSUE TITLE
Backslashes in HTML data attributes are wrongly removed in non-prod builds

### ISSUE THREAD

**Issue by imgx64** [driftyco/ionic#10228] opened 2017-01-29 07:22 UTC
**Ionic version:**
[x] **2.x**

**I'm submitting a ...**
[x] bug report

**Current behavior:**
When backslashes are present in an HTML data attribute (for example: `<div data-foo="\\bar">`), they get inconsistently escaped between prod (`npm run build --prod`) and non-prod (`ionic serve`) builds.

In prod builds, the tag at runtime has the correct attribute: `<div data-foo="\\bar">`

In non-prod builds, the tag at runtime has a single backslash only:  `<div data-foo="\bar">`

**Expected behavior:**
I expect the prod behavior to always happen. In other words, backslashes don't get removed.

**Steps to reproduce:**
Add `<div data-foo="\\bar">test</div>` to a page, run the app using ionic serve, and inspect the div.

For some reason, this does not happen on Plunker.

**Ionic info:**
```
 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed
```

**Comment by alexbainbridge** [comment] 2017-01-29 15:33
Try 3 backslashes..... https://github.com/driftyco/ionic-app-scripts/issues/524 might work for you

**Comment by jgw96** [comment] 2017-01-30 15:53
Hello all! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic-app-scripts/issues/524. Thanks for using Ionic.

**Closed by jgw96** 2017-01-30 15:53 UTC
