### ISSUE TITLE
Keyboard displays a white rectangle above

### ISSUE THREAD

**Issue by nikoTM** [driftyco/ionic#10728] opened 2017-03-10 14:45 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Keyboard displays a white rectangle above when visible. Which is probably meant to pad the keyboard height and should be at the very bottom.
![screenshot_1489155499](https://cloud.githubusercontent.com/assets/1929832/23799289/12541726-05b9-11e7-8250-131485ef3a0a.png)
![screenshot_1489155502](https://cloud.githubusercontent.com/assets/1929832/23799312/22503a60-05b9-11e7-97a3-40ff5278ece3.png)

**Expected behavior:**

Keyboard should not take additional space.

**Steps to reproduce:**

1. Clone this repository https://github.com/nikoTM/ionic-keyboard-bug
2. Add and emulate Android

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.9
Node Version: v7.7.2
Xcode version: Not installed

```

**Comment by nikoTM** [comment] 2017-03-10 15:29
Update: white rectangle seems to be `padding-bottom: 300px` on the scroll element. That is being added when the keyboard is visible.

**Comment by moberwasserlechner** [comment] 2017-03-10 17:51
I have the same issue but I'm able to reproduce it in chrome dev tools simulating a android device.

![untouched](https://cloud.githubusercontent.com/assets/1049938/23806484/25f52370-05c2-11e7-9686-1ca9529c4b89.png)

Whenever I focus a input field the content jump up because the padding-bottom is added.

![focus_field_padding_added](https://cloud.githubusercontent.com/assets/1049938/23806499/31239cc2-05c2-11e7-8c74-9cd4daa127d7.png)

```
 ordova CLI: 6.5.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.5
Xcode version: Not installed
```

**Comment by jgw96** [comment] 2017-03-13 11:31
Hello, thanks for opening an issue with us! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/10183.

**Closed by jgw96** 2017-03-13 11:31 UTC
