### ISSUE TITLE
bug: dropdown list issue on orientation change

### ISSUE THREAD

**Issue by joemalski** [driftyco/ionic#7099] opened 2016-06-28 14:33 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>This issue happens on IOS 9.3.2.   Click on your dropdown list (I used select with ng-repeat option), just keep the list open or pop up then tilt your device to change orientation and you will notice that the list that was open will be empty.  It is really a very odd behaviour.  Do you have any workaround on this issue?  Many thanks.</span>

<span is-issue-template></span>

**Comment by joemalski** [comment] 2016-06-28 14:59
The issue might not be from the dropdown itself but calling
$state.go($state.current, {}, {reload: true});  on orientation change.  I need the reload statement since I need to update some css classed depending upon the orientation of the device.

**Comment by jgw96** [comment] 2016-06-28 16:30
Hello, thanks for opening an issue with us! Would you be able to provide a plunker or repo that i could use to reproduce this issue? Also, does it only happen on ios or Android too? Thanks for using Ionic!

**Comment by jgw96** [comment] 2016-07-05 14:44
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-07-05 14:44 UTC
Labels: needs reply, platform:ios, v1
