### ISSUE TITLE
Ionic 2 menu opens from left instead of right (RTL)

### ISSUE THREAD

**Issue by theunreal** [driftyco/ionic#10074] opened 2017-01-17 16:21 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When a menu is toggled in RTL website, the menu is being toggled from the left side of the screen

**Expected behavior:**
Menu for RTL app should open up from the right side of the screen

**Steps to reproduce:**
Placing <ion-menu> on any rtl-based app (html dir="rtl")

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.47
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.2
Xcode version: Not installed
```

**Comment by jgw96** [comment] 2017-04-07 14:05
Hello, thanks for using Ionic! We really appreciate this feedback on RTL support. This is not currently high priority for us at the moment, but we are tracking it in #5035. Because of this I am going to close this issue as a duplicate of that issue and ask that you put your feedback on that issue. Please no that by me closing this issue I am not saying that your feedback is not important, or that RTL support is not important, but I am simply closing this issue as we like to keep our issues as organized as possible so things do not get lost in the weeds (which is better said than done haha).

**Closed by jgw96** 2017-04-07 14:05 UTC
Labels: v2
