### ISSUE TITLE
Changing detect stop works when handle a tab click event.

### ISSUE THREAD

**Issue by netsesame2** [driftyco/ionic#9811] opened 2016-12-28 05:27 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

Your system information:

ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.47
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v4.3.1
Xcode version: Not installed

**Current behavior:**

In an ionic's tabs based app, if we handle a button click from a tab button, change some states, ionic's changing detecting mechanism for the current page will stop working. Only thing we can do is exist and re-enter the view.

**Expected behavior:**

We hope it will be that, by clicking a tab button, change some states, the states will be updated in the binding views. 

**Steps to reproduce:**
1. start a new project demo with default tabs template.
2. add a button tab in tabs.html as:
>   <ion-tab tabTitle="" tabIcon="camera" (ionSelect)="takePhoto()">\</ion-tab>

3. Inject events into tabs.ts, and add a test method in tabs.ts:

> export class TabsPage {
> ...
>   constructor(private events: Events) {}
> 
>   takePhoto() {
>     this.events.publish("data:changed");
>   }
> }

4. Inject Events into home.ts, and subscribe to above event:
> export class HomePage {
>   datatest: string = "old";
> 
>   constructor(public navCtrl: NavController, public events: Events) {
>     events.subscribe("data:changed", this.change.bind(this));
>   }
> 
>   change() {
>     console.log("data changed!");
>     this.datatest = "new!";
>   }
> }

5. add a variable binding to anywhere in home.html:

>   <button ion-button (click)="change()">TEST\</button>
>   \<label>{{datatest}}\</label>

6. click the 'camera‘ tab, watch the home page. no update is happen. while the console print the expected value.
7. click the 'test' button on home page, no update is happen also.
8. re-enter the home page, repeat 7, update take effect.

**Comment by mhartington** [comment] 2017-01-04 20:18
The issue is the `bind(this)` it changes the scope of the call. So the console.log will be called since it's a global method, but the data biding wont update because it does not have access to this.

```
export class HomePage {
  datatest: string = "old";
  changeTime = 1;
  constructor(public navCtrl: NavController, public events: Events) {
    events.subscribe("data:changed", this.change);
  }

  change() {
    console.log("data changed!");
    this.datatest = `new ${this.changeTime++}`;
  }
}
```

This update fine without the `.bind(this)`

**Comment by mhartington** [comment] 2017-01-04 20:34
Spook too soon. Looks like you're right. Thanks for the heads up

**Comment by matthewfreedman** [comment] 2017-01-05 00:51
This looks like a duplicate of #9392. I am effected by the same issue.

**Comment by kelvindart** [comment] 2017-01-06 12:22
I believe so - if so, then @manucorporat has fixed it I believe - see: #9512 (but the rc.5 milestone was removed from #9392, so I do not know if it is destined for rc.5 or not).

**Comment by mhartington** [comment] 2017-01-06 19:13
Pulling down #9512 locally and applying it to my test seem to fix things!

**Comment by netsesame2** [comment] 2017-01-07 01:10
So, where can I  get this fix?

**Comment by mhartington** [comment] 2017-01-07 01:16
We'll cut a nightly release with this soon. It will be officially available in the next release

**Closed** 2017-01-09 18:04 UTC
Labels: v2

**Comment by brandyscarney** [comment] 2017-01-09 18:15
This will be in the next release, if you'd like to test it sooner please install the latest nightly:

```
npm install --save ionic-angular@nightly
```

Let us know if you see any problems. Thanks!

**Comment by netsesame2** [comment] 2017-01-10 02:17
The nightly version fix it perfectly. Thanks a lot.
