### ISSUE TITLE
bug: Deprecated warning on Chrome

### ISSUE THREAD

**Issue by 5amfung** [driftyco/ionic#4259] opened 2015-08-21 18:00 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Occasionally I see this warning on Chrome Version 45.0.2454.46 beta (64-bit) running on OSX 10.10.4.

'Touch.webkitRadiusX' is deprecated and will be removed in M47, around November 2015. Please use 'Touch.radiusX' instead. ionic.bundle.js:1162</span>

<span is-issue-template></span>

**Comment by kreck** [comment] 2015-09-02 09:03
+1

Additionally i see:
SVG's SMIL animations (<animate>, <set>, etc.) are deprecated and will be removed. Please use CSS animations or Web animations instead. ionic.bundle.js:12005

**Comment by gigocabrera** [comment] 2015-09-02 23:33
+1

**Comment by sebrojas14** [comment] 2015-09-03 05:32
That is now in chrome

**Comment by adam-back** [comment] 2015-09-03 18:53
This completely disables to propagation of click events on Google Maps when developing in the browser, using the app on a physical Android device, and iOS emulator. In short, it completely breaks my app.

**Comment by mhartington** [comment] 2015-09-03 18:56
Do you have an example of where I can see this? 
The SMIL animations we know about, but the webkitRadius is new to me.

**Comment by adam-back** [comment] 2015-09-03 19:27
Interestingly, the app works expectedly in Safari. It is working correctly in a coworker's Chrome.

For me, it works in Chrome, but only when I'm not emulating a device. Flow in video below (for some reason the GIF conversion really slowed stuff down):
- `ionic serve` (Chrome), app opens with console but no device emulation.
- Marker is clickable. Refresh screen. 
- Click different marker. Clickable.
- Start emulating iPhone 6 using Dev Tools. 
- Refresh page. Click marker, not clickable.
- Click second marker, not clickable
- Emulate Android. Refresh. Marker still not clickable.
![ionictoucherror](https://cloud.githubusercontent.com/assets/8163408/9668370/fa948112-5235-11e5-9e19-1b7a24ef2e48.gif)

**Comment by mhartington** [comment] 2015-09-03 19:35
Is this happening when on an actual device?

**Comment by adam-back** [comment] 2015-09-03 19:53
Yes, on Android. Haven't tested on iOS device yet. Works fine in Xcode.

**Comment by mhartington** [comment] 2015-09-03 20:04
Can you provide a minimal example that demos the problem

**Comment by adam-back** [comment] 2015-09-03 20:27
Found the issue rolling back through commits. This started when I included angular-material to add some styling. Found the [soluton](https://github.com/angular/material/issues/1808) in their issues:
```
app = angular.module('MyApp', ['ngMaterial'])
      .config(function( $mdGestureProvider ) {
          $mdGestureProvider.skipClickHijack();
      });
```

Thanks for your attentiveness @mhartington! You're a class-act!

**Comment by mhartington** [comment] 2015-09-03 20:42
Thanks for the nice words :grin:

So just to be clear, your issue was with angular material? Not with ionic?

**Comment by gigocabrera** [comment] 2015-09-03 20:45
I don't use angular material. I only use ionic. Let me prepare an example that you can look at

**Comment by gigocabrera** [comment] 2015-09-03 20:51
Tested in Chrome with Developer Tools
1) https://brilliant-inferno-1044.firebaseapp.com/
2) Login using gigo@test.com / 123
3) You will land on the Accounts screen, tap on the white area
On the console, you will see the warning:

SVG's SMIL animations (<animate>, <set>, etc.) are deprecated and will be removed. 
Please use CSS animations or Web animations instead.
ionic.bundle.js:1162 
'Touch.webkitRadiusX' is deprecated and will be removed in M47, around November 2015. 
Please use 'Touch.radiusX' instead.
ionic.bundle.js:1162 
'Touch.webkitRadiusY' is deprecated and will be removed in M47, around November 2015. 
Please use 'Touch.radiusY' instead.
ionic.bundle.js:1162 
'Touch.webkitRotationAngle' is deprecated and will be removed in M47, around November 2015. 
Please use 'Touch.rotationAngle' instead.
ionic.bundle.js:1162 
'Touch.webkitForce' is deprecated and will be removed in M47, around November 2015. 
Please use 'Touch.force' instead.

**Comment by actias** [comment] 2015-09-03 23:17
I can confirm we just started getting this about 2-3 days ago for some reason. The app seems to be working fine but the error came out of nowhere. We hadn't updated the framework or anything.

**Comment by mhartington** [comment] 2015-09-03 23:20
Alright, so we can confirm this issue. Thanks for letting us know all.

**Comment by aorylamballe** [comment] 2015-09-04 12:18
Hi,

it seems you can have this warning with the **sidemenu starter template**, when you open the side menu the first time in chrome desktop (I haven't tried on a mobile device). Chrome was recently updated, I guess that's one of the changes, adding a deprecation warning.

```
ionic.bundle.js:1162 'Touch.webkitRadiusX' is deprecated and will be removed in M47, around November 2015. Please use 'Touch.radiusX' instead.
ionic.bundle.js:1162 'Touch.webkitRadiusY' is deprecated and will be removed in M47, around November 2015. Please use 'Touch.radiusY' instead.
ionic.bundle.js:1162 'Touch.webkitRotationAngle' is deprecated and will be removed in M47, around November 2015. Please use 'Touch.rotationAngle' instead.
ionic.bundle.js:1162 'Touch.webkitForce' is deprecated and will be removed in M47, around November 2015. Please use 'Touch.force' instead.
```

**Comment by atans2468** [comment] 2015-09-08 00:04
I am getting this same issue and out of no where. My log is reading:

ionic.bundle.js:12005
SVG's SMIL animations (<animate>, <set>, etc.) are deprecated and will be removed. Please use CSS animations or Web animations instead.

and then:

ionic.bundle.js:21157
Error: permission_denied: Client doesn't have permission to access the desired data.
    at Error (native)
    at b.G (http://localhost:8100/js/firebase-web.js:121:36)
    at Object.G (http://localhost:8100/js/firebase-web.js:202:386)
    at http://localhost:8100/js/firebase-web.js:187:502
    at Ch.g.Id (http://localhost:8100/js/firebase-web.js:192:104)
    at qh.Id (http://localhost:8100/js/firebase-web.js:183:364)
    at ih.qh.Fa.Bh.t [as xg] (http://localhost:8100/js/firebase-web.js:181:281)
    at lh (http://localhost:8100/js/firebase-web.js:175:464)
    at WebSocket.ih.open.b.ua.onmessage (http://localhost:8100/js/firebase-web.js:174:245)(anonymous function) @ ionic.bundle.js:21157
FirebaseArray.$$error @ angularfire.js:414
(anonymous function) @ angularfire.js:701
(anonymous function) @ angularfire.js:1897
parent.$get.Scope.$eval @ ionic.bundle.js:24673
parent.$get.Scope.$digest @ ionic.bundle.js:24484
(anonymous function) @ ionic.bundle.js:24712
completeOutstandingRequest @ ionic.bundle.js:14221
(anonymous function) @ ionic.bundle.js:14493

**Comment by mhartington** [comment] 2015-09-08 00:11
Yes, we can confirm this too. No need to provide more info, we know where the issue is. Will get to this.

**Comment by actias** [comment] 2015-09-08 00:39
Thanks much for the quick response. Ionic has become the backbone for our company’s research apps. Thank you for all of your hard work.

**Comment by mike-nelson** [comment] 2015-09-08 02:55
We are seeing this issue too and keen to get the fix as soon as its available. (Seems like an unfair derecation warning, not giving people much time!)

Thanks

![screenshot](https://cloud.githubusercontent.com/assets/6793347/9725452/9263cab4-5639-11e5-8d5b-282f47a2ba73.png)

**Comment by vko-online** [comment] 2015-09-08 10:52
__Ionic__ should tight with Modernizr imho

**Comment by mhartington** [comment] 2015-09-08 16:58
@vko-online Modernizr would really be a good fit here. Not really needed.

**Comment by vko-online** [comment] 2015-09-08 17:15
@mhartington Agree, i don't think IE has Touch.msForce, so Modernizr not needed. Anyway those warnings make no sense in mobile browsers, as they are older than desktop versions imo.

**Comment by mhartington** [comment] 2015-09-08 17:17
Well, they make sense on android, since 5.0 updates the system webview separately from the OS. So that webview will be the same as desktop chrome

**Comment by vko-online** [comment] 2015-09-08 17:21
`Touch.webkitForce is deprecated` where can i find this usage in code? https://github.com/driftyco/ionic/search?utf8=%E2%9C%93&q=webkitForce no result

**Comment by mhartington** [comment] 2015-09-08 17:43
Hmm, yeah not seeing it either. Hmm, will test on chrome canary and maybe even build chromium to check it out.

**Comment by mike-nelson** [comment] 2015-09-08 20:33
You don't need Canary. We are seeing this warning appear on the production version of chrome (latest version, you may just need to update). 

Mike Nelson // CEO (and Developer)
beweb // p. 09 3077042 // m. 027 4403757

**Comment by mhartington** [comment] 2015-09-08 20:36
not for that, but to see if anything breaks in canary or chromium

**Comment by vko-online** [comment] 2015-09-08 21:32
Don't worry boys, all of this warnings are just browser internal things, we don't need to do anything. Here's demo.

Before we start
-  Make sure you have touch events enabled, go to [chrome://flags/](chrome://flags/) then select _enabled_ on __Enable touch events Mac, Windows, Linux, Chrome OS__ <sup>use CMD + F to search</sup> By default it's _auto_, which will not work
- Prepare sample, i used this
```function handleStart(evt) {
  evt.preventDefault();
  console.log(evt);
}``` and 
```var el = document.body;
  el.addEventListener("touchstart", handleStart, false);```

Result 
<img width="406" alt="screen shot 2015-09-09 at 3 25 54 am" src="https://cloud.githubusercontent.com/assets/4560099/9747973/0d18e726-56a3-11e5-9de3-c8e375f28272.png">

Now i see `webkitForce`, i guess chrome is built by modules, and some modules use old events. 
Don't worry imho

**Comment by atans2468** [comment] 2015-09-08 22:46
just to clarify is this just a fix for the Touch.webkitForce errors? because I am still getting the same errors that I noted above with ionic.bundle.js

**Comment by vko-online** [comment] 2015-09-09 02:35
@atans2468 it is not fix, it's just proof that those _warnings_ your receive in console are ignorable, it will not break your code, it has nothing to do with ionic i believe. And note: they are just _warnings_

**Comment by atans2468** [comment] 2015-09-09 02:46
hmmmm well I'm still having an unexplainable issue with the ionic.bundle.js file that is keeping anything in my app from submitting to firebase. Were you just referring to the webkit warnings or also the "SVG's SMIL animations....." warning, I'll attach an image so that you can see exactly what I'm seeing:

![screen shot 2015-09-08 at 7 45 33 pm](https://cloud.githubusercontent.com/assets/11624336/9752199/421e498e-5662-11e5-9acd-d9f48fe1568b.png)

**Comment by mhartington** [comment] 2015-09-09 14:08
SVG animations: Yes those are in ionics code, I will look into them and move them over to css.

As for the Touch warnings, I'm on @vko-online side, I don't think we have anything to worry about.

No need to keep commenting and. I know where the svg errors are coming from.

**Comment by TomaszWaszczyk** [comment] 2015-10-05 12:00
I have the same warning...

**Comment by omurbilgili** [comment] 2015-10-10 00:55
Same warning while using "$ionicHistory.goBack();"

**Comment by loian** [comment] 2015-10-23 08:18
Same warning in the tab application example: ionic.bundle.js:1162 'Touch.webkitRadiusX' is deprecated and will be removed in M47, around November 2015. Please use 'Touch.radiusX' instead.

It's a bit worrying, we are approaching november.

**Comment by cihadhoruzoglu** [comment] 2015-10-23 12:21
When do you plan to fix this error?

**Comment by mhartington** [comment] 2015-10-23 12:42
Again, I've said this before....

>As for the Touch warnings, we have anything to worry about.

If you look through Ionic and angular's source code, you won't find `Touch.webkitRadiusX` anywhere. 
This is just a generic warning that chrome is giving incase any framework is using that method. We  are all set :+1:  @cihadhoruzoglu  and @loian

**Comment by kugaevsky** [comment] 2015-10-27 01:10
+1

**Comment by mhartington** [comment] 2015-10-27 01:41
Again, nothing for us to do here. These are generic warnings inside of chrome in case anyone was using those prefixed APIs, which ionic is not.

**Comment by laidig** [comment] 2015-11-02 22:22
If there's nothing to worry about, how about closing this bug?
;)

**Closed** 2015-11-02 22:22 UTC
Labels: in progress

**Comment by stewartmccoy** [comment] 2015-11-10 05:00
@mhartington I just ran into this error when trying to call an ng-click on a button in ion-header-bar—and it's a problem for me because I'm using $state to route the user to another view and the click event is not propagating.

I'm following up on this thread because I'm unsure if the error is due the code I wrote, Ionic, or any dependencies.

This is the error, which you're familiar with: 

```
'webkitMovementX' is deprecated. Please use 'movementX' instead. ionic.bundle.js:1162
'webkitMovementY' is deprecated. Please use 'movementY' instead. ionic.bundle.js:1162
```

This is my markup:

```
<ion-header-bar class="bar-stable">
    <button class="button button-icon icon ion-person" ng-click="logUserOut()">
    </button>
    <h1 class="title">Title</h1>
</ion-header-bar>
```

When I click on the button, the logUserOut() never fires. I've tried putting a logging statement and nothing shows in the console. When I use this function as an ng-click elsewhere in the view, it works fine.

This is the code the function calls:

```
$scope.logUserOut = function() {
    $state.go('login');
  };
```

Appreciate any clarification you might provide on this issue :)

P.S. I'm building my first Ionic project for my bloc.io bootcamp capstone and I'm loving your framework and all the supporting tools (the marketplace is great). Keep up the great work!

**Comment by Yemolai** [comment] 2016-01-16 00:18
I'd like to add that I was having an issue with on-hold and getting these warnings. Found this issue post and did not helped me at all, but this error ocurred only testing my app on Samsung devices. After some search I've found that adding `overflow-scroll=false` at `<ion-content>` to solve the issue.
My specific issue was that on-hold was working for the default time but i was unable to let the user holding the button for longer than the default time for long-press, forcing the app to run on-release even if the user was still holding the button.

just adding here if someone have the same issue and search around here. :)

**Comment by isabelleaubron** [comment] 2016-02-05 10:40
I have the warning "SVG's SMIL animations....." when I add <ion-spinner> in $ionicLoading template

**Comment by brace110** [comment] 2016-03-03 14:41
Still getting the warnings,

this solves it:

        if (key == 'webkitMovementX' || key == 'webkitMovementY') {
          continue;
        }

Add the above code in Ionic.bundle.js on line 1173.
Final code see below. Use at own risk.

      extend: function extend(dest, src, merge) {
      for (var key in src) {
        if(dest[key] !== undefined && merge) {
          continue;
        }
        if (key == 'webkitMovementX' || key == 'webkitMovementY') {
          continue;
        }
        dest[key] = src[key];
      }
      return dest;
    }

**Comment by adeelzx** [comment] 2016-03-14 13:21
I am having the same warning when I am clicking on a button that has a functionality of popover menu in the navigation bar. Unfortunately popover functionality is not working at this place, don't know why. I have implemented the same functionality in other screen as well and its working fine with no warning. 
![not-working](https://cloud.githubusercontent.com/assets/7807615/13745583/e67e5596-ea14-11e5-92d7-374a0bbece18.png)



Above screen shows the warning and popover menu is not coming.
![working]
(https://cloud.githubusercontent.com/assets/7807615/13745594/eed07c24-ea14-11e5-99c1-1e4c8ce625fc.png)

In this screen everything is working with no errors/warning.
