### ISSUE TITLE
bug: Drag problems with when using side menus and tabs

### ISSUE THREAD

**Issue by roysaad** [driftyco/ionic#3740] opened 2015-05-15 09:03 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When an app has a side menu and tabs at the same time, ion-scrolls do not scroll correctly and range handles cannot be dragged smoothly.
Issue are not noticed in the first tab.

Check: http://play.ionic.io/app/81bb4cb75af7</span>

<span is-issue-template></span>

**Comment by roysaad** [comment] 2015-05-15 09:28
PS: Issue seems to disappear if I comment the following in <strong>ionic.bundle.js</strong>

  self.isDraggableTarget = function(e) {
    //Only restrict edge when sidemenu is closed and restriction is enabled
    var shouldOnlyAllowEdgeDrag = self.edgeThresholdEnabled && !self.isOpen();
    var startX = e.gesture.startEvent && e.gesture.startEvent.center &&
      e.gesture.startEvent.center.pageX;

    var dragIsWithinBounds = !shouldOnlyAllowEdgeDrag ||
      startX <= self.edgeThreshold ||
      startX >= self.content.element.offsetWidth - self.edgeThreshold;

    var backView = $ionicHistory.backView();
    var menuEnabled = enableMenuWithBackViews ? true : !backView;
    <span style="color:red">
/*  
    if (!menuEnabled) {
      var currentView = $ionicHistory.currentView() || {};
      return backView.historyId !== currentView.historyId;
    }
*/
</span>
    return ($scope.dragContent || self.isOpen()) &&
      dragIsWithinBounds &&
      !e.gesture.srcEvent.defaultPrevented &&
      menuEnabled &&
      !e.target.tagName.match(/input|textarea|select|object|embed/i) &&
      !e.target.isContentEditable &&
      !(e.target.dataset ? e.target.dataset.preventScroll : e.target.getAttribute('data-prevent-scroll') == 'true');
  };

**Comment by abailey-et** [comment] 2015-06-03 14:21
Will like to add that it works if the first landing page is the view with the input range. The problem is if you have an input range that is not the initial view loaded. Here's an example: http://play.ionic.io/app/7e802b9a8faf

**Comment by jgw96** [comment] 2016-05-05 16:16
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment] 2016-05-10 14:04
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-05-10 14:04 UTC
Labels: menus, needs reply, tabs, v1

**Comment by roysaad** [comment] 2016-05-10 14:14
I just tested it on ionic 1.3.0. There were no issues. Thank you for your efforts.
