### ISSUE TITLE
bug: Bug: Popover fast clicks --> app freezes

### ISSUE THREAD

**Issue by Arkantas** [driftyco/ionic#3503] opened 2015-04-10 12:42 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi there,

Here's a bug not so easy to reproduce I found in my app and other ones.

I have a button in my header that allows to open a Popover. When the popover appears, if I select an item too fast (then it hides the popover) the application freezes.

Let me know if you know any fix.

(*Bug found on Chrome and iOS*, I'm going to check about Android soon.)</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-04-10 12:42
Greetings @Arkantas!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3503). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3503)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Arkantas** [comment] 2015-04-10 12:50
You can avoid that freezing thanks to a timeout when you want to hide the popover though

**Comment by Ionitron** [comment] 2015-04-10 19:56
Greetings @Arkantas!

My sensors indicate that I require more information in order to assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this happen occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com), where many humans will be able to offer wisdom and advice.

Thank you for allowing me to assist you.

<span ionitron-needs-reply></span>

**Comment by Ionitron** [comment] 2015-04-16 13:42
Greetings @Arkantas!

My sensors indicate that I require more information in order to assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this happen occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com), where many humans will be able to offer wisdom and advice.

Thank you for allowing me to assist you.

<span ionitron-needs-reply></span>

**Comment by buunguyen** [comment] 2015-04-17 02:41
+1. I had this exact issue when using popover and had to switch to modal.

**Comment by ajoslin** [comment] 2015-04-17 16:32
This is fixed in the nightly builds. It's still annoyingly slow, though, because popovers (which are modals) have timeouts set to the default modal transition duration.

These timeouts could be changed, but it's very risky to do right before 1.0..

**Closed by ajoslin** 2015-04-17 16:32 UTC
Labels: needs reply
