### ISSUE TITLE
v2 beta.10: ion-header content not animating in

### ISSUE THREAD

**Issue by jasonwaters** [driftyco/ionic#7175] opened 2016-07-02 19:48 UTC
Hey ionic team! Congrats on the latest release. Ionic just keeps getting better and better!

I've had to make lots of changes with the beta 10 upgrade. One those changes was moving some content into ion-header so that it does not scroll with the rest of the content beneath. The problem I am facing is that my div within ion-header does not animate in with the other content like ion-navbar. Is this expected behavior?

Here's a view of what i'm talking about:

![static](https://cloud.githubusercontent.com/assets/427213/16542169/986acb26-405b-11e6-97be-dba999068d0e.gif)

Here's a code snippet of the header on my page:

```
<ion-header>
	<ion-navbar>
		<ion-title>Watering Detail</ion-title>
	</ion-navbar>
	<div class="header-container grey-header middle">
		<ion-icon name="blo-splash-check" class="middle"></ion-icon>
		<h2>{{cycle.start_time|mediumDateFormat}}</h2>
		<p>Watered <strong>{{cycle.num_zones}} {{'Zone'|pluralize:cycle.num_zones}}</strong> for {{cycle.duration_secs|durationTime}}</p>
	</div>
</ion-header>
```

**Comment by jgw96** [comment] 2016-07-05 14:58
Hey, thanks for the kind words! So we did a big layout refactor with beta.10, which is probably why you have had to make some changes. As far as this issue goes, this is expected behavior. `ion-header` does not actually animate at all with ios transitions, its more of just a "container" component, `ion-navbar` is where all the animation goes on. One thing you could try (warning: this is just an idea off the top of my head) is putting your div in an `ion-toolbar`. If im thinking correctly `ion-toolbar` should animate when the page is transitioned to. Hope this explains everything! Since this is expected behavior I will be closing this issue. Thanks again!

**Closed by jgw96** 2016-07-05 14:58 UTC
Labels: animation, header, v2
