### ISSUE TITLE
mousewheel scroll with infinite scroll hangs network request on Chrome

### ISSUE THREAD

**Issue by m59peacemaker** [driftyco/ionic#7811] opened 2016-08-21 18:43 UTC
On Chrome, mousewheel scrolling down a list with infinite scroll makes the network request to load more items very slow. I can't reproduce it any other way, but I suspect it is just that the mousewheel callback is blocking/hanging the browser to some degree and the network request is just too much for it to handle on top of that. Click/drag or thumb scrolling works just fine, though. I tested as far back as 1.0.0 to 1.3.1.

Here's a demo that reproduces: http://jsbin.com/nanokarupu/2/edit?html,js,output
Just mousewheel scroll down and note that the network request hangs, whereas when dragging to scroll, the network request is almost instant.

**Comment by m59peacemaker** [comment] 2016-08-21 19:57
It hangs less when on successive page reloads, but after closing the browser and returning, the hang is bad,

**Comment by jgw96** [comment] 2016-08-26 20:34
Hello! Thanks for opening an issue with us! I am testing in the latest chrome on my macbook and cannot seem to reproduce this issue unfortunately. What version of chrome are you testing with? Thanks!

**Comment by m59peacemaker** [comment] 2016-08-26 21:16
@jgw96 What a thing this is! I was trying to hack around this for days and finally managed to get something to work in my app, though the same hack wouldn't work on the jsbin demo. I tested on multiple Windows machines - all had the bug. Now, the bug has disappeared. Very strange, but good,  I guess?

**Comment by jgw96** [comment] 2016-08-26 21:25
Welcome to the world of computers haha! Sometimes they have a mind of their own. Glad its fixed though! Thanks for using Ionic!

**Comment by m59peacemaker** [comment] 2016-10-13 16:28
I just thought of this bug and checked back on it. The bug is still gone from my app, but the jsbin demo I posted still has it. Chrome on Windows 10.

**Comment by jgw96** [comment] 2016-10-14 19:02
Hello, thanks! I cannot reproduce this issue in the latest version of Chrome or Firefox in an actual app. Because this seems to be more of a JSbin issue I am going to close this one for now.

**Closed by jgw96** 2016-10-14 19:02 UTC
Labels: needs reply, v1
