### ISSUE TITLE
bug: Toggle buttons broken on iOS?

### ISSUE THREAD

**Issue by Codewyvern** [driftyco/ionic#3337] opened 2015-03-16 22:10 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>This issue is a very annoying one, it actually also happens on the ionic documentation page too, The ion-toggle looks and works as it should except for the fact that the input is accepted from anywhere in the document, If you slide the button to be on and then quickly tap somewhere else in the document the button toggles off! I spent a few hours convinced that there is a mistake somewhere in my personal code but after stripping out everything but ionic the issue still persists, I have a back button on my form and it toggles the toggle sliders off nearly every time!</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-03-16 22:10
Greetings @Codewyvern!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3337). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3337)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment] 2015-03-20 20:39
I'm having trouble reproducing this. Are you just seeing this on a device? If so, what device? Do you also see it in the desktop? What specific iOS version 8.1, 8.2?

**Comment by Codewyvern** [comment] 2015-03-26 13:34
This is happening on iOS 8.1.3 ipad air inside a webview and is still not working for me.
The smaller the webview width the bigger the problem becomes, to replicate can you try to toggle a toggle to the right and then quickly tap anywhere left of the toggle, do this a few times with a few toggles on the page and they start misbehaving.

**Comment by Ionitron** [comment] 2015-06-24 14:12
Greetings @Codewyvern!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-06-24 14:12 UTC
Labels: ionitron:closed, toggle
