### ISSUE TITLE
Testing vRC.0 using Karma

### ISSUE THREAD

**Issue by ivaro18** [driftyco/ionic#8430] opened 2016-10-03 11:52 UTC
#### Short description of the problem:
Getting 0/0 tests error.
I'm trying to test with Karma. Now the `.spec.ts` files won't be compiled to `.js` files. (Or at least not in `www/build/`). Now this is a problem since in the previous `karma.conf.js` you would refer to that directory. How would my `karma.conf.js` look like now?

#### What behavior are you expecting?
Expecting my tests to execute with a modified `karma.conf.js`

**Steps to reproduce:**
1.  Create a new ionic application.
2.  Install karma & jasmine
3.  Set up your `karma.conf.js` like you would in `beta.37`
4.  Run `karma start karma.conf.js --single-run`

**karma.conf.js**

```
module.exports = function(config) {
  config.set({
 
    // base path that will be used to resolve all patterns (eg. files, exclude)
    basePath: '',
 
 
    // frameworks to use
    // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
    frameworks: ['jasmine'],
    plugins: [
      require('karma-jasmine'),
      require('karma-phantomjs-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-htmlfile-reporter')
    ],
 
    // list of files / patterns to load in the browser
    files: [
      'node_modules/systemjs/dist/system.src.js',
      'node_modules/systemjs/dist/system-polyfills.js',
      'node_modules/es6-shim/es6-shim.js',        // TypeError: undefined is not a constructor (evaluating 'new exports.Map()')
      'node_modules/reflect-metadata/Reflect.js', // 'Uncaught reflect-metadata shim is required when using class decorators'
      'node_modules/zone.js/dist/zone.js',        // Zone.js dependencies (Zone undefined)
      'node_modules/zone.js/dist/jasmine-patch.js',
      'node_modules/zone.js/dist/async-test.js',
      'node_modules/zone.js/dist/fake-async-test.js',
      'app/**/*.spec.ts',
      {pattern: 'node_modules/reflect-metadata/Reflect.js.map', included: false, served: true}, // 404 on the same
      {pattern: 'www/build/**/*.html', included: false},
    ],
 
    // list of files to exclude
    exclude: [
      'node_modules/angular2/**/*_spec.js',
      'node_modules/ionic-angular/**/*spec*'
    ],
 
 
 
    // test results reporter to use
    // possible values: 'dots', 'progress'
    // available reporters: https://npmjs.org/browse/keyword/karma-reporter
    reporters: ['progress'],
 
 
    // web server port
    port: 9876,
 
 
    // enable / disable colors in the output (reporters and logs)
    colors: true,
 
    proxies: {
      '/build': '/base/www/build'
    },
 
    // level of logging
    // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
    logLevel: config.LOG_INFO,
 
 
    // enable / disable watching file and executing tests whenever any file changes
    autoWatch: true,
 
 
    // start these browsers
    // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
    browsers: ['PhantomJS'],
 
 
    // Continuous Integration mode
    // if true, Karma captures browsers, runs the tests and exits
    singleRun: false,
 
    // Concurrency level
    // how many browser should be started simultaneous
    concurrency: Infinity
  })
}
```

**package.json**
```
{
  "name": "ionic-hello-world",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "build": "ionic-app-scripts build",
    "watch": "ionic-app-scripts watch",
    "serve:before": "watch",
    "emulate:before": "build",
    "deploy:before": "build",
    "build:before": "build",
    "run:before": "build",
    "test": "karma start karma.conf.js",
    "test-once": "karma start karma.conf.js --single-run"
  },
  "dependencies": {
    "ionic-angular": "^2.0.0-rc.0",
    "ionicons": "^3.0.0",
    "@ionic/storage": "^1.0.3",
    "ionic-native": "^2.0.3",
     "angular2-in-memory-web-api": "0.0.20",
    "bootstrap": "^3.3.6",
    "systemjs": "^0.19.27",
    "core-js": "^2.4.1",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.12"
  },
  "devDependencies": {
    "@ionic/app-scripts": "latest",
    "phantomjs":"2.1.3",
    "jasmine-core": "^2.4.1",
    "karma": "^0.13.22",
    "karma-jasmine": "^1.0.2",
    "karma-cli":"^1.0.1",
    "karma-phantomjs-launcher": "1.0.2",
    "run-sequence": "1.1.5",
    "tsify": "0.16.0",
    "tslint": "^3.15.1",
     "concurrently": "^2.2.0",
    "lite-server": "^2.2.2",
    "typescript": "^2.0.3",
    "typings": "^1.3.2",
    "karma-htmlfile-reporter": "^0.3.4",
    "karma-jasmine-html-reporter": "^0.2.2"
  },
  "description": "newApp: An Ionic project",
  "cordovaPlugins": [
    "cordova-plugin-device",
    "cordova-plugin-console",
    "cordova-plugin-whitelist",
    "cordova-plugin-splashscreen",
    "cordova-plugin-statusbar",
    "ionic-plugin-keyboard"
  ],
  "cordovaPlatforms": []
}
```

**Other information:** 
Stacktraces: Na/n. --> just showing `Executed 0 of 0 ERROR (0 secs / 0 secs)`
 

**Which Ionic Version?** 
2.1.0

#### Plunker that shows an example of your issue

Can't be Plunker'd --> no `package.json` file in there/no `npm` commands available.

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
$ ionic info

Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS:
Node Version: v4.5.0

**Comment by masimakopoulos** [comment] 2016-10-03 13:15
There is a related discussion here https://github.com/driftyco/ionic-app-scripts/issues/51 if you are interested to follow.

**Comment by jgw96** [comment] 2016-10-03 14:09
Hello, thanks for opening an issue with us! I am going to consider this issue a duplicate of the above linked issue and ask that you add your findings to that issue. Thanks for using Ionic!

**Closed by jgw96** 2016-10-03 14:09 UTC
