### ISSUE TITLE
bug: iOS Native Scrolling with forms

### ISSUE THREAD

**Issue by saurabhgupta050890** [driftyco/ionic#4848] opened 2015-12-22 13:31 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>With ionic 1.2.0 native scrolling is default. For my current app its working fine on most screens on iOS but I also have ion-content with a long form. On these screens scrolling have erratic behavior. Whenever I try to scroll and touch a input element then it won't scroll but when touch any other components (for e.g divider) then it scrolls fine. I have tested it on iOS 9.1 and iOS 8. Also I have noticed that if input is disabled then it won't scroll at all and in case of normal input  it sometimes scrolls</span>

<span is-issue-template></span>

**Comment by mlynch** [comment] 2015-12-31 18:23
Duplicate of #4849 with fix ready for next release (hopefully today)

**Closed by mlynch** 2015-12-31 18:23 UTC
