### ISSUE TITLE
DateTime rtl view error 

### ISSUE THREAD

**Issue by mohamedsharaf** [driftyco/ionic#10878] opened 2017-03-22 19:52 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

ionic DateTime rtl view error 
min shows instead of hours should view in replace with each other
image attached
**Expected behavior:**

view in replace with each other

**Steps to reproduce:**
set platform to rtl 
then 
` <ion-datetime placeholder="{{ 'Date' | translate }}" pickerFormat="D MM YYYY h:m A"
                              displayFormat="D-MM-YYYY h:m A" [(ngModel)]="order.date" name="date"></ion-datetime>`

**Related code:**

```
 <ion-datetime placeholder="{{ 'Date' | translate }}" pickerFormat="D MM YYYY h:m A"
                              displayFormat="D-MM-YYYY h:m A" [(ngModel)]="order.date" name="date"></ion-datetime>
![dattime rtl error](https://cloud.githubusercontent.com/assets/895464/24217818/2abe3a24-0f52-11e7-9c8c-fc1c22bfd37f.png)
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
ordova CLI: 6.5.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.7.1
Xcode version: Not installed
```

**Comment by mohamedsharaf** [comment] 2017-03-22 19:53
![dattime rtl error](https://cloud.githubusercontent.com/assets/895464/24217906/6d0bb5aa-0f52-11e7-8fc4-fb62f9229642.png)

**Comment by jgw96** [comment] 2017-04-07 14:07
Hello, thanks for using Ionic! We really appreciate this feedback on RTL support. This is not currently high priority for us at the moment, but we are tracking it in #5035. Because of this I am going to close this issue as a duplicate of that issue and ask that you put your feedback on that issue. Please know that by me closing this issue I am not saying that your feedback is not important, or that RTL support is not important, but I am simply closing this issue as we like to keep our issues as organized as possible so things do not get lost in the weeds (which is better said than done haha).

**Closed by jgw96** 2017-04-07 14:07 UTC
Labels: v2
