### ISSUE TITLE
RC4: VirtualScroll disappears after data update, if has been scrolled before

### ISSUE THREAD

**Issue by masimplo** [driftyco/ionic#9722] opened 2016-12-20 10:21 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

In a virtual scroll list, if the data is updated (or the subscription to data removed and readded) and the list has been scrolled down a couple pages, the list becomes blank until the user scrolls down a bit.

**Expected behavior:**

When the data updates, the list should be updated and not disappear.

**Steps to reproduce:**

1. Have a virtual list that shows data coming from an observable.
2. Scroll down a couple pages
3. Send some new data through the observable.
4. The list disappears until the user manually scroll on the blank list.

**Other information:**

Here is a gif demonstrating this behaviour. I modified the conference app speakers page to use a virtual scroll list. Speakers list is appended every 5 sec (when the list disappears, I then scroll a bit and same thing happens after 5 sec where list is appended again) 
![](https://dl.dropboxusercontent.com/u/648840/vscroll.gif)
Here is the link to the fork of conference app https://github.com/masimplo/ionic-conference-app

In the original code I am also using [virtualTrackBy] but it makes no difference.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4-201612192257
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.9.0
ios-sim version: 5.0.8
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.2 Build version 8C38
```

**Comment by jgw96** [comment] 2016-12-21 19:15
Hello, thanks for opening an issue with us! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/8267.

**Comment by masimplo** [comment] 2016-12-21 19:55
@jgw96 This is not the exact same issue and has appeared in RC4 (didn't happen in RC3). In this issue I am describing the virtual scroll list disappears when new data is added to the list after you have scrolled a few "pages" down (not right after, but at any point after having scrolled, stopped and just starred at the list). From what I understand issue #8267 says that the list is not re-rendered when the user stops scrolling. 
If you have a deeper understanding that these two issues refer to the same cause, then find, otherwise please reopen.

**Comment by masimplo** [comment] 2017-01-04 09:18
I have identified the issue in the [renderVirtual function](https://github.com/driftyco/ionic/blob/master/src/components/virtual-scroll/virtual-scroll.ts#L454) of the VirtualScroll component. Problem is that the nodes array is not recalculated the ngDoCheck is fired, thus when you leave the page showing the virtual scroll and then go back the first nodes (which are not visible) are drawn instead of the ones that are inside the viewport.

Probably [adjustRendered](https://github.com/driftyco/ionic/blob/master/src/components/virtual-scroll/virtual-util.ts#L436) has to be called before calling [populateNodeData](https://github.com/driftyco/ionic/blob/master/src/components/virtual-scroll/virtual-scroll.ts#L464) to deal with this issue, with care for when virtual scroll is on the top position.

**Comment by lunedam-git** [comment] 2017-02-18 13:35
I get exactly the same issue as @masimplo when using virtual scroll when it's underlying data is updated. Seems to me that once the list has scrolled beyond the number of cells dictated by the bufferRatio, the list does not re-render cells beyond that buffer ratio - even if they should be visible in the viewport. Manually scrolling the list - just a tiny amount - causes the list to render the cells that should be in the viewport.

So it seems to start rendering at the top. At cell 0. Every time. Renders the number of cells dictated by the bufferRatio and then waits for a scroll action before rendering more. It should start rendering the cells based upon its scrollHeight at the instant when the data is updated, then using the approxItemHeight to calculate the actual cells to render so that they will be visible to the user in the viewport.

I have tried jury rigging a programatic scroll into my component that is triggered once the list is updated. This does work, but is hit and miss as it depends upon the client device capabilities as triggering the scroll before virtual list has finished rendering has no effect - so what works on desktop fails on mobile and what works on mobile just takes too long.

I also tried the solution from @masimplo and have to say that when I did it had no effect. Once the list had been scrolled beyond the number of cells dictated by bufferRatio, whenever the data was updated the list still failed to re-render the cells that should be in the viewport.

Unfortunately I'm not on the same level as @masimplo so not up to the task of attempting to provide a fix, but thought my notion regarding the bufferRatio and the number of cells that are rendered when data is updated may help ... although I have a nasty feeling I'm just saying what @masimplo has already said but with a lot less understanding ;-)

In the meantime I think I'm going to have to switch to using infinite scroll as the virtual list up and vanishing on my users whenever the data is updated is a big show stopper right now.

**Comment by pcsantana** [comment] 2017-02-22 19:19
Thank you @masimplo, after some tests worked great for me! 
But without the follow edition worked better.

`+        populateNodeData(data.topCell || 0, data.bottomCell, data.viewWidth, true, cells, records, nodes, this._itmTmp.viewContainer, this._itmTmp.templateRef, this._hdrTmp && this._hdrTmp.templateRef, this._ftrTmp && this._ftrTmp.templateRef, true);`

PS: I'm using infinite-scroll too.

**Comment by lunedam-git** [comment] 2017-03-14 12:29
This is really killing me as a relative newcomer, but can anyone help me to build the JS files from the Ionic repository TS?

I've tried this so many times I'm banging my head against a brick wall:

- clone drifty/ionic project into local/ionic
- cd local/ionic
- npm install
- make and commit my change (trying to add an eventemitter to virtualscroll)
- make sure I'm in local/ionic
- gulp build

The result is "Task 'build' is not in your gulpfile", but looking in scripts/gulp/tasks there is a task, 'build', which is the very first import in scripts/gulp/gulpfile.ts. Running 'gulp demos' is successful, so gulp seems to be OK.

Not a clue where I'm making my rookie mistake, but any insights or suggestions would be appreciated. Unless someone knows if there is already an event I can listen to in my page component that is fired when a child virtualScroll has finished rendering ... ?

**Closed** 2017-03-15 16:47 UTC
