### ISSUE TITLE
Ionic RC5: after Toast is closed the popover stop to work.

### ISSUE THREAD

**Issue by marcusvbp** [driftyco/ionic#10055] opened 2017-01-16 19:42 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Hi, after I updated my project to RC5, the popover works as expected. But after the app show a Toast message, the popover component don't open anymore (all popovers has this bug).

I make a video of this issue: https://www.youtube.com/watch?v=qU04pLt4sxg

**Comment by manucorporat** [comment] 2017-01-16 22:51
I can't reproduce it, I wonder if some of your code is causing this issue because toast + popover is working for me.

**Comment by marcusvbp** [comment] 2017-01-17 10:24
Hi, thank you for your reply. 

Later I will post the code here (I am on mobile phone)

**Comment by marcusvbp** [comment] 2017-01-17 17:39
Hello,

I put the relevant code here: https://bitbucket.org/snippets/marcusvbp/jpBjq

Thanks.

**Comment by Chris1234567899** [comment] 2017-01-18 04:24
Similar issue here, Happens to me after keyboard was opened.
Turns out the popover is actually opened but it is misplaced and outside of the device screen...

**Comment by unfg** [comment] 2017-01-18 09:52
i have the same issue. If some keyboard was showed once, popovers does not shows (have wrong size and position).

**Comment by unfg** [comment] 2017-01-18 10:02
it is a serious bug. popover does not work any more in RC5.

**Comment by unfg** [comment] 2017-01-18 11:40
I think, this issue is a duplicate of the https://github.com/driftyco/ionic/issues/10014 issue

**Comment by marcusvbp** [comment] 2017-01-18 14:17
thats right, it's related to keyboard, not the Toast Component.

**Comment by pwespi** [comment] 2017-01-18 15:43
A temporary fix that worked for me is in the project folder in node_modules\ionic-angular\components\popover\popover-transitions.js to replace `this.plt.width()` with `window.innerWidth` and `this.plt.height()` with `window.innerHeight` (they appear twice). Then run `ionic run android --prod` again.

**Comment by jgw96** [comment] 2017-01-18 17:20
Hello everyone! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/9727 for now. The underlying bug with measuring orientation and the height and width of the viewport are discussed there and are currently being fixed. Thanks!

**Closed by jgw96** 2017-01-18 17:20 UTC
Labels: v2

**Comment by Chris1234567899** [comment] 2017-01-18 19:33
A temporary workaround that helped me, is setting the popover position to absolute and define it.
Like this: add css class to popover

`let popover = this.popoverCtrl.create(ReportPopover,{data:this.data},{cssClass:"report-list"});
    popover.present();`

and in the css write something like:

`.report-list{
    .popover-content{
        width:80%;
        padding:5px;
        margin:auto!important;
        position:absolute;
        top:10%!important;
    }
}`

You have to write it in the popover-content class which overwrites the original.
Does not solve the bug but at least you can continue working meanwhile...
