### ISSUE TITLE
DatePicker really slow

### ISSUE THREAD

**Issue by Gp2mv3** [driftyco/ionic#8144] opened 2016-09-20 19:11 UTC
#### Short description of the problem:

I'm trying to use the DatePicker but it's really really slow. It's nearly not usable.
This slowness is present on desktop browsers (Chrome and Firefox) but also on Android (Nexus 5 and Huawei P9 lite) when the app is compiled. I didn't tried on iOS but I think it will also be the case.

More people have the same issue on the Forum: https://forum.ionicframework.com/t/datepicker-really-slow/61661

#### What behavior are you expecting?
The date picker is fast and smooth on Android, iOS and web browser.

**Steps to reproduce:**

My declaration of the DatePicker is: `<ion-datetime displayFormat="DD/MMM/YYYY HH:mm" [(ngModel)]="event.begin" [ngModelOptions]="{standalone: true}" [min]="minDate" [max]="maxDate" minuteValues="0,15,30,45" required></ion-datetime>` and it's in a form.

The issue is on Ionic 2.0 beta 11.

Your system information:

> Cordova CLI: You have been opted out of telemetry. To change this, run: cordova telemetry on.
> 6.3.1
> 
> Gulp version:  CLI version 3.9.1
> Gulp local:   Local version 3.9.1
> Ionic Framework Version: 2.0.0-beta.11
> Ionic CLI Version: 2.0.0-beta.32
> Ionic App Lib Version: 2.0.0-beta.18
> OS: Distributor ID:	Ubuntu Description:	Ubuntu 15.04 
> Node Version: v4.2.2

**Comment by jgw96** [comment] 2016-09-20 20:38
Hello, thanks for opening an issue with us! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/8096. Thanks for using Ionic!

**Closed by jgw96** 2016-09-20 20:38 UTC
Labels: performance, v2
