### ISSUE TITLE
bug: bug: Ionic view long title gets cutted when navigating back with ion-tabs

### ISSUE THREAD

**Issue by emanueltlantic** [driftyco/ionic#4477] opened 2015-10-06 14:44 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi I found a problem with view titles, when they are **bigger** than the window width.
It's present in this codepen:
http://codepen.io/anon/pen/wKdrpw

You have to shrink the preview window frame like this image.

![ionic-title-bug](https://cloud.githubusercontent.com/assets/7022182/10311993/17e9fb96-6c41-11e5-951d-2b1c5ce8a710.gif)
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-10-06 14:44
Greetings @emanueltlantic!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4477). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4477)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by AlexSwensen** [comment] 2015-10-07 19:21
This bug seems to relate to how caching is done. container that holds the title becomes "smaller" when its in its cached background state, and that value is not updated when its resumed. I have found that adding `cache: false`, to the offending `.state` gets rid of this issue.

modified codepen: http://codepen.io/AlexSwensen/pen/BoRXrx

**Comment by emanueltlantic** [comment] 2015-10-08 09:31
The problem is that I need cache in this page, so that wont't work for me... :(

**Comment by kylefox** [comment] 2015-11-02 23:48
I encountered this bug as well.

**Comment by jgw96** [comment] 2016-03-23 19:29
Hello! Are you still experiencing this issue?

**Comment by jgw96** [comment] 2016-03-24 15:24
Thanks for opening this issue with us! As this issue is a duplicate of https://github.com/driftyco/ionic/issues/4661#issuecomment-200779335 i will be closing this issue for now. But please feel free to move the conversation over to that issue. Thanks!

**Closed by jgw96** 2016-03-24 15:24 UTC
Labels: css, needs reply, v1
