### ISSUE TITLE
Ionic 2: How to iterate through json key, value pairs?

### ISSUE THREAD

**Issue by ungular** [driftyco/ionic#7720] opened 2016-08-14 20:23 UTC
I want to display in a grid (key, value) pairs of a json, but I found no way to do that:
- id=              1
- name=        AAA
- surname=   BBB

home.ts :
`public records:any = {'id': '1', 'name': 'AAA', 'surname': 'BBB'};`

pseudo home.html :
```
<ion-grid *ngFor="let entry[key, value] of records.entries">
  <ion-row>
    <ion-col>{{entry.key}}</ion-col>
    <ion-col>{{entry.value}}</ion-col>
  </ion-row>
</ion-grid>
```
exists here a solution to achieve this, making changes only in html code?

**Comment by cojj90** [comment] 2016-08-14 22:24
I think it is:

*ngFor="let entry of records"

**Comment by danbucholtz** [comment] 2016-08-15 04:37
Hi @ungular,

Since this is not a bug in the framework, we are going to close this issue.  Please take any requests for help to our [community help forum](https://forum.ionicframework.com/?utm_source=framework&utm_medium=navbar&utm_campaign=forum%20CTA).  Stackoverflow is also great!

Please let me know if you have any questions.

Thanks,
Dan

**Closed by danbucholtz** 2016-08-15 04:37 UTC
Labels: v2

**Comment by ungular** [comment] 2016-08-15 09:15
Hi @danbucholtz ,

Seems that does not exists such a feature in ionic or I'm wrong? If so then this is a change request.

@cojj90 , how to extract the key & value from json here: `<ion-col>{{entry.key}}</ion-col>` ? In this way does not work.  We can continue our investigation here: https://forum.ionicframework.com/t/ionic-2-how-to-iterate-through-json-key-value-pairs/60566?u=ungular
