### ISSUE TITLE
Ionic 1.2 + iOS ghost click

### ISSUE THREAD

**Issue by kinkaz** [driftyco/ionic#4993] opened 2016-01-18 07:52 UTC
This one is a try to re-open this issue : https://github.com/driftyco/ionic/issues/3649 

As this issue is closed, I don't know if my last comment on this issue will be noticed :

"I can reproduce this issue on iOS 9 (and I had this bug on previous versions).

When I click on a link (page A), if there is an input field on the next page (page B) at the exact spot of my link (page A), the field is focused and the keyboard opens. It's as if the click is still fired even after the transition to the next page happened.

I can solve this issue by deleting this line in my app config : $ionicConfigProvider.views.transition('none');

Is there a way to fix this ?

Thanks"

I don't want to have any transition in my app, and this issue still occurs in some pages in my app. For example, on input[type="submit"]. I use the $ionicScrollDelegate to scroll back to the top of the form if there are validation errors, but as the animated scroll is done, a field is focused (I think during this scroll).

**Comment by mlynch** [comment] 2016-02-03 22:54
@kinkaz is this a plain link or a button? Can I see the markup for your link?

**Comment by kinkaz** [comment] 2016-02-04 08:34
`<a class="item item-icon-left" href="#{{ menu.url }}" ng-repeat="menu in submenu">
        <i class="icon {{ menu.icon }}"></i> {{ menu.title }}
</a>`

Plain link. I have the "button" class on some links, I don't know if it makes a difference for you.

**Comment by kinkaz** [comment] 2016-02-04 14:59
Also note that this problem only occurs when using native scrolling.

If I set `$ionicConfigProvider.scrolling.jsScrolling(true);`, everything's fine (except it's js scrolling !)

**Comment by ananda-naphade** [comment] 2016-02-22 05:24
Use data-tap-disabled="true" on element.

http://ionicframework.com/docs/api/page/tap/

**Comment by mklilley** [comment] 2016-02-24 13:45
@kinkaz I have the same problem on iOS 9.2.1.  When I tap on an entry in the side menu which looks like this:

`<ion-item ng-repeat="item in menu.items" menu-close ui-sref="{{::item.sref}}" ui-sref-active="activated" >  <h2>{{::item.title}}</h2> </ion-item>`

They keyboard automatically pops up but the text area in the next view (which is at the same co-ordinates as the menu item) doesn't actually focus. If i try and tap off the text area a few times to try and get rid of the keyboard the app crashes. @ananda-naphade I tried your suggestion, it does work, but the problem then is there is a massive lag between tapping on the item an it doing anything. Presumably your fix causes a return of the 300ms problem?

I find a similar behaviour in the following scenario.  I tap on an input, the keyboard pops up and the input gets focussed and scrolled up so that it remains in view now the the keyboard is open. When i tap off the input below it (at some coordinates where the input originally was), the input loses focus and is moved back down to its original location, the keyboard is closed, but then the keyboard pops up again with nothing is in focus.   Again if i tap a few times anywhere off the input the app crashes. This seems like there are ghost clicks that are not being managed correctly.

**Comment by niagara18** [comment] 2016-03-23 15:22
Same problem here. We tryed to replace all `ng-click` by `on-tap`. Solved the problem partially but we got new ghost-clicks at other positions in code

**Comment by jgw96** [comment] 2016-08-09 18:38
Hello all! Since we switched to js scrolling by default for IOS a while ago, and this issue is only reproducible with native scrolling i will be closing this issue for now. Thanks for using ionic!

**Closed by jgw96** 2016-08-09 18:38 UTC
Labels: tap/click, v1
