### ISSUE TITLE
Loading overlay not presenting

### ISSUE THREAD

**Issue by TheBrockEllis** [driftyco/ionic#7615] opened 2016-08-08 23:06 UTC
#### Short description of the problem:
The Loading component does not display properly since moving to beta-11

#### What behavior are you expecting?
A loading dialog should display and never be dismissed

**Steps to reproduce:**
1. Create a blank Ionic 2 app `ionic start overlay-test --v2`
2. Replace the content of `app/pages/home/home.ts` with this:
```typescript
import {Component} from '@angular/core';
import {NavController, LoadingController} from 'ionic-angular';

@Component({
  templateUrl: 'build/pages/home/home.html'
})
export class HomePage {
  constructor(private navCtrl: NavController, private loading:LoadingController) {

  }

  ionViewDidEnter(){
    console.log("View did enter");
    let loading = this.loading.create();
    loading.present();
    console.log("This console log never sees the light of day. :-(");
  }
}
```
3. Run `ionic serve` and look at developer console

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
Output from browser developer console:

```
Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
plugin.js:34 Native: tried calling StatusBar.styleDefault, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator
home.ts:13 View did enter
```

**Which Ionic Version?** 1.x or 2.x
2.0.0-beta.11

#### Plunker that shows an example of your issue
I couldn't find a beta.11 plunker to use, so here's a test repo with the steps to recreate the issue already done: https://github.com/TheBrockEllis/Ionic2Beta11OverlayTest

```
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.36
Ionic App Lib Version: 2.0.0-beta.19
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v4.4.5
Xcode version: Xcode 7.3.1 Build version 7D1014
```

**Comment by jgw96** [comment] 2016-08-09 04:27
Hello! Thanks for opening an issue with us! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/7605. Thanks for using Ionic!

**Closed by jgw96** 2016-08-09 04:27 UTC
Labels: platform:ios, v2
