### ISSUE TITLE
bug: collection-repeat empty space between rows

### ISSUE THREAD

**Issue by doorty** [driftyco/ionic#4233] opened 2015-08-14 16:01 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When scrolling on a collection-repeat, there will be a break between some of the rows as you see in the image below (between "Task Name 116" and "Task Name 117"). Below is the code that is rendering this example.

```javascript
<ion-scroll class="arvak-scroll" ng-if="isAdmin">  
  <ion-list option-buttons="itemButtons" can-swipe="true">
    <ion-item class="arvak-builder-row row" collection-repeat="row in tableFields" item="fields" item-type="item item-icon-left" ng-click="goToView(row.id)" ng-tap="goToView(row.id)">
      <div class="arvak-builder-column " ng-repeat="field in row.fields" title="{{field.value}}">{{field.value}}</div>
    </ion-item>
  </ion-list>
</ion-scroll>  
```

<img width="406" alt="screen shot 2015-08-14 at 5 04 55 pm" src="https://cloud.githubusercontent.com/assets/451093/9278015/1696c330-42ae-11e5-9483-30a9608aaa1a.png">

I'm guessing this has something to do with the dynamic nature of inserting new rows for collection-repeat.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-08-14 16:01
Greetings @doorty!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4233). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4233)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment] 2015-11-12 17:02
Greetings @doorty!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-11-12 17:02 UTC
Labels: ionitron:closed

**Comment by arielbruno** [comment] 2016-08-06 22:08
add "display:block !important" to the ion-item tag

**Comment by ungular** [comment] 2016-08-27 19:30
ionic2 same issue https://github.com/driftyco/ionic/issues/7894:
<ion-list *ngFor="let a of [{name: 'AAA'},{name: 'BBB'}]">
        <ion-item>
            {{a.name}}
        </ion-item>
    </ion-list>

**Comment by GanuM** [comment] 2016-12-17 12:52
im also facing this problem

**Comment by shashankdevp** [comment] 2017-11-08 06:49
Facing same issue. When row and col Css classes are used within Ion-item tag, the issue is found. Has any one found a solution ?
