### ISSUE TITLE
ionViewDidLoad() not working in Modal

### ISSUE THREAD

**Issue by audan2009** [driftyco/ionic#8414] opened 2016-10-03 02:01 UTC
**Note: If you are having problems formatting your issue please refer to this article on using markdown in Github:**

https://guides.github.com/features/mastering-markdown/

**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:

ionViewDidLoad() not executing in Modal

#### What behavior are you expecting?

I'm expecting a log from the Push Page 'Hello Push Page'

**Steps to reproduce:**
1. Generated a blank app
2. Modified home page to:

    import { Component } from '@angular/core';

    import { NavController, ModalController } from 'ionic-angular';

    import { Push } from '../push/push';

    @Component({
      selector: 'page-home',
      templateUrl: 'home.html'
    })
    export class HomePage {

      constructor(public navCtrl: NavController, public modalCtrl: ModalController) {

    let createModal = this.modalCtrl.create(Push);

    createModal.onDidDismiss( data => {

    });

    createModal.present(createModal);

      }

    }

3. Push Page:

`
    import { Component } from '@angular/core';
    import { NavController } from 'ionic-angular';

    /*
      Generated class for the Push page.

      See http://ionicframework.com/docs/v2/components/#navigation for more info on
      Ionic pages and navigation.
    */
    @Component({
      selector: 'page-push',
      templateUrl: 'push.html'
    })
    export class Push {

      constructor(public navCtrl: NavController) {}

      ionViewDidLoad() {
        console.log('Hello Push Page');
      }

    }

`

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x

Ionic Framework Version: 2.0.0-rc.0

#### Plunker that shows an example of your issue

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.9.0 
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v6.7.0
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by comfortme** [comment] 2016-10-03 08:53
same issue here.

**Comment by fastf0rward** [comment] 2016-10-03 09:57
+1

**Comment by perdjurner** [comment] 2016-10-03 14:05
I have the same problem.

As a work-around until this is fixed I put my setup logic for the modal in the constructor instead.

**Comment by baltazaroliveira** [comment] 2016-10-03 16:33
+1

**Comment by jgw96** [comment] 2016-10-04 15:19
Hello all, i am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/8449. Thanks for using Ionic!

**Comment by aggiustino** [comment] 2016-10-04 15:25
+1

**Comment by manucorporat** [comment] 2016-10-04 15:56
@jgw96 I don't think it is the same issue. this issue is about `ionViewDidLoad` not being called at all.

**Comment by mattroth** [comment] 2016-10-05 12:30
Here is my work around:

*Function to Create Modal*
```

addFamilyMemberTapped() {
    let data = {initFormHack: true};
    let modal = this.modalCtrl.create(Profile, data);
    modal.onDidDismiss(data => {
      if (data.activeMember) {
        console.log("modal dismissed...");
      }
    });

    modal.present();
  }

```
*Page Loaded in Modal*
```

  constructor(private navParams: NavParams) {
    /**
     * HACK FOR BUG: https://github.com/driftyco/ionic/issues/8414
     */
    if (navParams.data['initFormHack']) {
      this.ionViewDidLoad();
    }
  }

```

**Comment by audan2009** [comment] 2016-10-06 02:20
@mattroth that work around didn't work for me.... I need to access nativeElement from a @ViewChild so my guess is that the elements are loaded yet...

**Comment by baltazaroliveira** [comment] 2016-10-06 07:58
My "workaround" is simple! :-) i have create a function and insert inside the constructor. Problem Solved!
When this issue is resolved i change the name of function to ionViewDidLoad.

**Comment by BlackFoks** [comment] 2016-10-06 18:41
I found that `ionViewDidEnter` works in modals so I added a workaround on top of it:

```js
  ionViewLoaded = false;
  ionViewDidEnter() {
    if (!this.ionViewLoaded) {
      this.ionViewLoaded = true;
      this.ionViewDidLoad();
    }
  }
```

Hope this will help someone.

**Closed** 2016-10-12 16:38 UTC
Labels: v2
