### ISSUE TITLE
infinite scroll EXCEPTION: TypeError: Cannot read property 'removeEventListener' of null when navigating away

### ISSUE THREAD

**Issue by alzalabany** [driftyco/ionic#5998] opened 2016-03-31 11:25 UTC
**Steps to reproduce and a minimal demo of the problem**
```

@Page({
	providers: [WallFactory],
	template: `
	<ion-navbar *navbar>
		<button menuToggle>
	    	<ion-icon name="menu"></ion-icon>
	  	</button>
		<ion-title> Class Wall </ion-title>
		  
	</ion-navbar>
	<ion-content>

	 <ion-card *ngFor="#post of posts;trackBy:post?.id">
	</ion-card>

	<ion-infinite-scroll (infinite)="doInfinite($event)">
	   <ion-infinite-scroll-content></ion-infinite-scroll-content>
	 </ion-infinite-scroll>
		
	</ion-content>
	`
})
export class WallPage {
	posts:Array<any>;
	page:number=1;

	constructor(private nav: NavController, navParams: NavParams) {
	}
	doInfinite(infiniteScroll) {
		this.page++;
		//do some stuff
				console.log('Finished getting next page, you have ',this.posts.length);
				infiniteScroll.complete();
	}

}

``````

**Current behavior**
When you leave page that contain ion-infinite-scroll it will raise an exception.

EXCEPTION: TypeError: Cannot read property 'removeEventListener' of null

TypeError: Cannot read property 'removeEventListener' of null
    at InfiniteScroll._scLsn (http://localhost:8100/build/js/app.bundle.js:41822:32)
    at InfiniteScroll._setListeners (http://localhost:8100/build/js/app.bundle.js:42486:37)
    at InfiniteScroll.ngOnDestroy (http://localhost:8100/build/js/app.bundle.js:42502:14)

using "ionic-angular@2.0.0-beta.3"

**Comment by iignatov** [comment] 2016-04-02 12:59
Hi @alzalabany, this is a [known issue (#5760)](https://github.com/driftyco/ionic/issues/5760) and will be fixed in `beta.4`.

**Comment by jgw96** [comment] 2016-04-03 20:29
Hello! As @iignatov stated above this is a known issue and is slated to be fixed in beta.4. Thanks for opening this issue with us but as it is a duplicate of issue #5760 i will be closing this one. Thanks again!

**Closed by jgw96** 2016-04-03 20:29 UTC
Labels: infinitescroll, menus
