### ISSUE TITLE
feat: Image preload

### ISSUE THREAD

**Issue by MatanYed** [driftyco/ionic#7854] opened 2016-08-24 22:44 UTC
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>An option to add preloader to ion-img will be great
You will add attrs like image ratio or exactly width and height and it will preload and it will be good ux</span>

<span is-issue-template></span>

**Comment by jianwwpro** [comment] 2016-08-25 01:17
agree

**Comment by gigocabrera** [comment] 2016-08-29 21:40
+1

**Comment by royipressburger** [comment] 2016-08-31 19:33
Anyone have a workaround untill this feature will be implemented?

**Comment by jgw96** [comment] 2016-09-01 15:42
Hello all! Currently when using `ion-img` with VirtualScroll it lazily loads images, is this what you all are looking for? Thanks for using Ionic!

**Comment by MatanYed** [comment] 2016-09-01 15:54
@jgw96 Actually no, i meant that if the image still didn't load in the app so show a spinner in the middle of the image. And additional option to this img is r
Img ratio attr, it will be nice to add ratio attr like 16:9 and have the spinner in the middle in time that the image is loading.
Of curse in addition lazy load will be great even without VirtualScroll, because at most of the times you wont use it

**Comment by jgw96** [comment] 2016-09-01 20:37
Hello all! I am going to be closing this issue as a duplicate of https://github.com/driftyco/ionic/issues/7533. Thanks for using Ionic!

**Closed by jgw96** 2016-09-01 20:37 UTC
Labels: feature, v2
