### ISSUE TITLE
App crashes/exits after several alert popup calls

### ISSUE THREAD

**Issue by barocsi** [driftyco/ionic#10266] opened 2017-02-01 09:23 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Popping up alert closes app/crashes with the image attached. The error message is iOS system alert.
![image](https://cloud.githubusercontent.com/assets/851560/22501220/1b4e7fe2-e868-11e6-83a2-7f95de144a38.png)

**Expected behavior:**
Don't crash/exit

**Steps to reproduce:**
Happens randomly on iOS 10.2.1, iPhone 7 after making several calls to a list that popup alert prompt.

**Related code:**
Crashes exactly at this call, the alert does not show up.
```
actionClicked(action: Action, command: Pin) {
        console.log('CarPage::Command Action Clicked', action);
        let alert = this.alertCtrl.create({
            title: (command.name ? command.name : command.default_name) + ":" + (action.name ? action.name : action.default_name),
            inputs: [
                {
                    name: 'pin',
                    placeholder: this.translateService.instant('CAR_PAGE.COMMAND_ALERT.CODE_PLACEHOLDER'),
                    type: 'password'
                }
            ],
            buttons: [
                {
                    text: this.translateService.instant('GENERIC.CANCEL'),
                    role: 'cancel',
                    handler: data => {
                        console.log('Cancel clicked');
                    }
                },
                {
                    text: this.translateService.instant('CAR_PAGE.COMMAND_ALERT.DO_ACTION'),
                    handler: data => {
                        if (data && data.pin != '')
                            this.sendSMS(data, action, command);
                    }
                }
            ]
        });
        alert.present(alert);
    }
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.3.0
Xcode version: Not installed
```

**Comment by jgw96** [comment] 2017-02-02 15:24
Hello, thanks for using Ionic! Unfortunately I cannot reproduce this issue, would you mind posting a repo i can use to reproduce this issue?

**Comment by barocsi** [comment] 2017-02-02 15:50
Thanks, thats not gonna happen. It's pretty random and hard to reproduce. I will give it a run next week and update this issue if managed to reproduce / acquire some stack trace or any relevant ouptut, or if not I will consider the 2.0.0 to fix this until then keep this open.

**Comment by jgw96** [comment] 2017-02-07 21:54
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-02-07 21:54 UTC
Labels: needs reply, v2

**Comment by barocsi** [comment] 2017-02-08 06:20
Just because I was not yet avle to make additions to the issue it does nit mean its resolved. This policy make a false assumption about the frameworks reliability. I told you that I will add more intel as soon I can get access to the devices causing the error.
