### ISSUE TITLE
Ionic tabs seems not to be aligned horizontally very well

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic#8932] opened 2016-10-27 15:45 UTC
_From @kluz116 on October 27, 2016 15:43_

Ionic tabs seems not to be aligned horizontally very well.... All components seems not to very aligned horizontally when i run this on my android phone.. But in the development browser, very thing is aligned very well.
![ionic2](https://cloud.githubusercontent.com/assets/9973896/19774256/2abd80c0-9c75-11e6-93cd-98fb1da5944f.jpg)
![ionic1](https://cloud.githubusercontent.com/assets/9973896/19774298/3d25eca2-9c75-11e6-81ee-58ee6eaea3a7.jpg)

_Copied from original issue: driftyco/ionic-preview-app#68_

**Comment by jgw96** [comment] 2016-10-27 18:44
Hello @kluz116, thanks for opening an issue with us! What version of Android is your device running?

**Comment by kluz116** [comment] 2016-10-27 18:58
Thanks Ionic team.
Am testing the app on android version Android 4.3
<https://developer.android.com/about/versions/android-4.3.html>  API Level
18 JELLY_BEAN_MR2
<https://developer.android.com/reference/android/os/Build.VERSION_CODES.html#JELLY_BEAN_MR2>
..........

Regards
Allan Musembya

**Comment by jgw96** [comment] 2016-10-31 15:03
@kluz116 If you try with crosswalk does it fix the issue?

**Comment by kluz116** [comment] 2016-10-31 15:40
Whats crosswalk??????? i have no idea of what you saying.

**Comment by jgw96** [comment] 2016-10-31 21:01
Ahh, i am very sorry, should have explained this earlier (:. Crosswalk gives you a modern, up to date chrome webview even on older Android devices that do not have a chrome webview out of the box (Android before 5.0). You can read how to install and use it [here(https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview#install). Thanks!

**Comment by jgw96** [comment] 2016-11-18 21:27
Hello all! As it seems it has been a while since there was any activity on this issue and I cannot reproduce this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-11-18 21:27 UTC
Labels: needs reply, v2
