### ISSUE TITLE
bug: Keyboard shows a white background when closing

### ISSUE THREAD

**Issue by VinceOPS** [driftyco/ionic#4798] opened 2015-12-16 01:34 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

**Ionic Version**: 1.1+, including 1.2.0

<span ionic-description>Hi there,

I am experiencing the issue reported here https://forum.ionicframework.com/t/white-background-shows-when-keyboard-closes-on-android/25258 and here https://github.com/driftyco/ionic/issues/4057.

**Platforms**: Android 4 to 6.
**Devices**: Nexus 5 on Android 6+, and few devices in the Android emulator, with Android 4.1 to Android 5.1.

My parameter `windowSoftInputMode` uses the default value (adjustResize) and my app is not in full screen.

The issue can be reproduced with any colored background, or any background using a picture.

I tried to play with adjustNothing and to manually push the content on my own, but the keyboard events don't seem to be propagated when using adjustNothing (+ it seems to be impossible to get the keyboard size without letting Android resize the webview).

Any help would be most welcome. Thanks!</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-12-16 01:34
Greetings @VinceOPS!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4798). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4798)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment] 2015-12-17 00:40
Thanks! Closing as duplicate of #4057 but your info helps

**Closed by mlynch** 2015-12-17 00:40 UTC

**Comment by VinceOPS** [comment] 2016-07-11 14:29
Hi @mlynch, still having the issue with up-to-date Ionic (last 1.3.x)  and Keyboard plugin... #4057 was closed but I'm still looking for a solution. Do you know if someone is currently working on this? Thanks!
