### ISSUE TITLE
bug: OpenLayers 3 lib is broken when ionic is loaded.

### ISSUE THREAD

**Issue by kulmegil** [driftyco/ionic#4664] opened 2015-11-24 09:49 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Here's a copy basic OpenLayers 3 example with Ionic added to external resources (it's not even bootstrapped into application)
http://jsfiddle.net/z5jywp7g/2/

Map controls will stop responding after few seconds. No JS errors though.
Remove ionic from deps to see working again.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-11-24 09:49
Greetings @kulmegil!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4664). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4664)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment] 2015-12-07 18:51
Thanks for the report! You need to add `data-tap-disabled` to the map and it works great then:

https://github.com/driftyco/ionic/blob/master/test/html/openLayers.html#L35

**Closed by mlynch** 2015-12-07 18:51 UTC

**Comment by xsgkaka** [comment] 2016-04-20 07:15
Why is there such a bug?  i use openlayers in my ionic app , when the map view is loaded first time the events in openlayers  is available ,but when the map view is loaded second time, the events in openlayers is not available.. . i add `data-tap-disabled` to the map div, then the problem is solved. but why?
