### ISSUE TITLE
Virtual Scroll update after scrolling stops

### ISSUE THREAD

**Issue by danbucholtz** [driftyco/ionic#8267] opened 2016-09-28 20:13 UTC
Make virtual scroll update the position and displayed elements when scrolling is done.

**Comment by danbucholtz** [comment] 2016-09-28 20:14
I am 90% done with this already, so assigning to RC.1

**Comment by AzzamAsghar** [comment] 2016-10-04 23:11
Can you please solve virtual scrolling going to top after change in dataset in this update????virtual scrolling is a tremendous feature especially when used with infinite scroll but this scrolling problem is just rendering it useless in many cases like in News Feed.

**Comment by danbucholtz** [comment] 2016-10-05 03:36
@AzzamAsghar,

Please file a separate issue for that problem. It won't be fixed with the change discussed in this issue.

Thanks,
Dan

**Comment by danbucholtz** [comment] 2016-10-05 03:36
Sorry, accidentally assigned you @manucorporat.

**Comment by zakton5** [comment] 2016-10-17 19:57
This issue mentions updating when scrolling is done, but I'm also seeing on iOS that the items do not render while a long scroll is still going. Is this being considered as well?

**Comment by Jumptidus** [comment] 2016-11-18 07:41
I really need this..............Please

**Comment by DavidTalamona** [comment] 2016-11-18 13:24
I just read an informative article about that problem: http://developer.telerik.com/featured/scroll-event-change-ios-8-big-deal/ - especially the part at "One caveat for Cordova developers".

Seems like it's a problem with the "old" webview used by Cordova and cannot be fixed until the "new" webview is acceptable as a replacement.
So @danbucholtz, is there anything the IONIC team could do about it? Don't think you're implementing custom scrolling, are you?
Think we all have to wait for Cordova to implement the WKWebView.

If I'm getting this right, then please add some not at the virtualScroll docs because that issue basically makes it useless for iOS.

**Comment by adamdbradley** [comment] 2016-11-18 22:09
@DavidTalamona Yes, we've built a plugin to use WKWebView: http://blog.ionic.io/cordova-ios-performance-improvements-drop-in-speed-with-wkwebview/

And Virtual Scroll adjusts for UIWebView since it doesn't fire scroll events during inertia. I'm working on this issue now, thanks.

**Comment by adamdbradley** [comment] 2016-11-19 21:52
@Jumptidus Can you explain more what the issue is and what you need fixed?

**Comment by Jumptidus** [comment] 2016-11-20 01:29
we use ionic for forums. need build a long list for posts.we choose virtualscroll but when I use ion-infinite update it .virtualscroll always scroll to top..

our user love scroll scroll scroll....so have a really long list cannot use ngfor. 

understand what i mean 

my English is poor.sorry

**Comment by faraazc** [comment] 2016-11-23 11:03
@mlynch @adamdbradley @jgw96 virtual scroll+infinite scroll is a basic requirement for any data driven apps. Please get this fixed as early as possible. Possibly before final release. on addition of new data in to the dataset scroll should not move to  top. I tried many tweaks but could not achieve. Please help us on this. Thanks in advance

**Comment by Jumptidus** [comment] 2016-12-06 03:27
Hi...
Will fix in rc4?
@adamdbradley

**Comment by jgw96** [comment] 2016-12-28 16:33
Hello all! So just to clear up some confusion here this issue is about the virtual scroll updating when scrolling has stopped to make sure that the page is not left with blank space that should have elements rendered in it. The issue that you guys are asking about here with the virtual scroll scrolling back to the top when updating it with data as you are scrolling is tracked here https://github.com/driftyco/ionic/issues/6423.

**Comment by jgw96** [comment] 2016-12-28 16:50
I am currently testing this issue (virtual scroll leaving white space and not rendering when you stop scrolling). On UiWebView, which was originally where the biggest issue was, I can confirm that it is fixed. Will post more of my findings as I test.

**Comment by jgw96** [comment] 2016-12-28 17:02
So from my testing with an iphone 5, Nexus 6, and chrome on the desktop i can confirm that this issue is not happening on the latest release (rc4). 🎉

**Comment by jgw96** [comment] 2016-12-28 17:08
Hello everyone! I am going to close this now as I cannot reproduce this issue in RC4, but if you still run into this issue please feel free to comment and I will happily reopen. Thanks for using Ionic!

**Closed by jgw96** 2016-12-28 17:08 UTC
Labels: v2, virtualscroll
