### ISSUE TITLE
Range component not styled in Chrome 49+

### ISSUE THREAD

**Issue by petehouston** [driftyco/ionic#5913] opened 2016-03-23 07:37 UTC
**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:

The range component doesn't render track color correctly on latest Google Chrome 49+

#### What behavior are you expecting?

The track color should be rendered correctly it used to

**Steps to reproduce:**
1. Update Google Chrome to latest version (49+)
2. Open the official Ionic component documentation
3. Navigate to range component section and see the preview.

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

It looks like Chrome has changed the way to render range input intentionally, https://bugs.chromium.org/p/chromium/issues/detail?id=582301#c6

**Which Ionic Version?** 1.x or 2.x

Happen in Ionic 1.x, and probably 2.x too.

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

```
Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.5
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v4.1.1
Xcode version: Xcode 7.2.1 Build version 7C1002
```

**Comment by jgw96** [comment] 2016-03-23 17:43
Hello thanks for opening an issue with us! I was able to confirm this in Chrome 51 Canary. Good catch!

**Comment by FLHerne** [comment] 2016-03-30 15:06
This is caused by a supposedly-WontFix [bug in Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=582301), for some reason they decided the pseudoelements used shouldn't exist.

I get the impression the change was made without looking at how -webkit-slider-thumb:before/after are actually used, since it's attracted half a dozen duplicate bug-reports already.

**Comment by petehouston** [comment] 2016-03-30 16:15
@FLHerne it is exactly **WontFix** as Chromium team notes on above link. Well, I guess it's gonna affect to Crosswalk soon. I'm looking for a hack or a solution to work around this range issue.

**Comment by danbucholtz** [comment] 2016-05-04 21:42
Hi @petehouston,

We probably will not fix this for V1.  We are creating a scroller from scratch for V2.

Thanks for letting us know about this.  I'll let you know if anything changes WRT to the slider.

Thanks,
Dan

**Closed by danbucholtz** 2016-05-04 21:42 UTC
Labels: platform:ios, range, v1
