### ISSUE TITLE
V#3 Scroll no work

### ISSUE THREAD

**Issue by marianobies** [driftyco/ionic#11140] opened 2017-04-09 20:05 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

The scroll does not work on the device and on the browser when it is clicked but it works with the mouse scroll.

Sorry for my bad English

**Ionic info:**

```
Your system information:

Cordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.5
Xcode version: Not installed
```

**Comment by darwiin** [comment] 2017-04-09 20:37
Have exactly the same issue. I was previously on ionic 2.0.0.

```
Your system information:

 Cordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v7.1.0
Xcode version: Not installed
```

**Comment by ConradoCarvalho** [comment] 2017-04-10 01:30
I think this is related to #11112 
One workaround is to remove the (tap) or (press) from the items and use only (click).
In my case it is not enough because I´m using press and tap together.

**Comment by marianobies** [comment] 2017-04-10 13:34
@ConradoCarvalho Is correct, remove the (press) and work !, thanks, with which I replaced the functionality of (press) is that I need to use it

**Comment by jgw96** [comment] 2017-04-10 14:40
Hello all! I am going to close this issue as a duplicate of #11112 .

**Closed by jgw96** 2017-04-10 14:40 UTC
