### ISSUE TITLE
bug: on input focus / keyboard up scroll content

### ISSUE THREAD

**Issue by jtushar53** [driftyco/ionic#7025] opened 2016-06-23 12:31 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>6.0</span>  <span ionic-webview>webview</span>

<span ionic-description>On input focus / keyboard up scroll content above keyboard automatically.

But when we type something screen goes up but not on focus.

currently doing this workaround as of now.

html
        <ion-input type="tel" (click)="scrollscreen()" [(ngModel)]="mobileno" ></ion-input>

ts

   @ViewChild(Content) content : Content;
 private keyboard: Keyboard;

  scrollscreen() {
    setTimeout(() => {
      if (this.keyboard.isOpen()) {
        this.content.scrollToBottom(400);
      }
    }, 500);
  }</span>

<span is-issue-template></span>

Ionic info
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.31
Ionic App Lib Version: 2.0.0-beta.17
OS: Windows 7 SP1
Node Version: v4.4.5

BTW, haven't tested on other devices .

**Comment by jgw96** [comment] 2016-06-23 18:25
Hello, thanks for opening an issue with us! I am going to close this as a duplicate of https://github.com/driftyco/ionic/issues/6229 and will be adding that it happens on android too to that issue. Thanks for using Ionic!

**Closed by jgw96** 2016-06-23 18:25 UTC
Labels: keyboard, platform:android, v2
