### ISSUE TITLE
bug: event.preventDefault() doesn't work in view lifecycle events

### ISSUE THREAD

**Issue by bastiss** [driftyco/ionic#3791] opened 2015-05-20 14:17 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi Ionic team,

the call to event.preventDefault() doesn't work in a view lifecycle event and a state change will be performed.
```
$scope.$on('$ionicView.beforeLeave', function (event) {
 event.preventDefault();
});
```
Will this be changed in future, or do i have to use a ui-router event (e.g. $stateChangeStart) to prevent a state change?

Thanks in advance for your answer.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-05-20 14:17
Greetings @bastiss!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3791). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3791)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment] 2015-05-20 20:32
@adamdbradley, was this the way transitions were intended to be cancelable?

**Comment by adamduren** [comment] 2016-01-26 14:40
I was curious about this as well. My use case is making sure to call a save method before transitioning in `beforeLeave()` to the back view which will then query for the updated data. Currently it's a race condition and sometimes displays the previous information. Any updates on this?

**Comment by p-syche** [comment] 2016-01-27 23:05
Any updates on this?

**Comment by dually8** [comment] 2016-02-18 16:06
@bastiss, even the $stateChangeStart doesn't prevent a state change.  Relevant plnkr http://plnkr.co/edit/Ov25xiUuEhVVH7ucKFAc?p=preview

**Comment by tschuegge** [comment] 2016-03-16 14:09
+1

**Comment by skotturi** [comment] 2016-05-05 02:29
+1

**Comment by jgw96** [comment] 2016-05-05 05:05
Hello all! We are currently doing alot of work with the lifecycle events for the next release. Be on the lookout for Ionic 1.3.1 soon, which will have these fixes. Thanks! Once 1.3.1 is released i will update this issue.

**Comment by skotturi** [comment] 2016-05-05 15:33
@jgw96 here's a codepen where a state change is prevented successfully using `$stateChangeStart` from a child-view, in this case 'Facts' shares the 'home-tab' ui-view with 'Home'

If you click on "Scientific Facts" and toggle the ion-toggle. Then clicking "< Home" in the nav-bar doesnt allow navigation. However, if you go to About and toggle, you can still navigate between tabs. 

I presume this is because `tabs.home` and `tabs.facts` share a nav stack, while `tabs.home` and `tabs.about` do not? 

http://codepen.io/skotturi/pen/yOGEJg?editors=1010

**Comment by jgw96** [comment] 2016-05-12 19:54
Hey @skotturi ! Would you be interested in doing some testing for the 1.3.1 RC? If so, [here](https://forum.ionicframework.com/t/ionic-1-3-1-release-candidate/51666) is a link on how to test it.

**Comment by jgw96** [comment] 2016-05-17 15:12
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-05-17 15:12 UTC
Labels: v1

**Comment by avivbeeri** [comment] 2016-05-26 11:29
Hello, I am experiencing this problem while trying to use $stateChangeStart in my Ionic app.
I call event.preventDefault() in the $stateChangeStart event handler, but the transition continues regardless.

There is some similarity between my project and the example posted by @skotturi, but my event handler is attached at the $rootScope instead.

**Comment by skotturi** [comment] 2016-06-01 22:01
@jgw96 Apologies for the delay, I've tested this on 1.3.1 and I'm still seeing the same issue. 

The codepen still accurately reflects the issue. To reproduce this: 
1. Click "Scientific Facts" in the state `tabs.home`
2. This will take you 'tabs.facts' which shares the `home-tab` view. 
3. Toggle "Thou shall not leave"
4. Click "< Home" in the nav-bar. Nav is prevented. 
5. Click "About" tab, nav is sort of prevented. The view goes white, however, the actual About page is not rendered (unless you previously have loaded the view in which case its rendered from cache). 

http://codepen.io/skotturi/pen/yOGEJg?editors=1010

**Comment by skotturi** [comment] 2016-08-24 21:38
@jgw96 Just wanted to follow up on this. 

Not sure if the plunkr above works as demo. 
If you drop the following snippet into any v1 app controller, inject `$state` into the ctrl, and add some `$scope.somethingImportantIsHappening = true`, the problem should be reproducible at that point. 

```javascript
    $scope.$on('$stateChangeStart', function (event, next, nextParams, fromState) {
                if (somethingImportantIsHappening) {
                    event.preventDefault();
                    // $state.go(fromState.name);           // tried this, doesn't work. 
                    window.location.assign('#/' + fromState.name);                // also doesn't work. 
                }
            });
```

Is there a way to achieve this in v1.3.1 with the changes to the life cycle events?

**Comment by rinogo** [comment] 2016-10-24 22:15
@jgw96, any updates on what the status is of this?  The Codepen provided by @skotturi seems to still demonstrate the problem.

I'd like to use this functionality to implement an "Unsaved changes" popup... What's the "second best" way accomplish this given that `event.preventDefault()` doesn't seem to work on lifecycle events?

**Comment by skotturi** [comment] 2017-01-11 18:24
@rinogo It's pretty hacky but the best way I've found to prevent navigation from the tabs is to hide the tabs all together... Mike has a code-pen on this unofficial hack: http://codepen.io/mhartington/pen/MwPRNp?editors=001

This works for me because I want to disable nav from a page with tabs at all times, not in a state dependent way like unsaved changes but maybe you can use `ng-attr-x` to apply the `hide-tab-bar` directive attribute.

**Comment by rinogo** [comment] 2017-01-11 18:37
@skotturi Thanks for sharing your solution!  It unfortunately doesn't really help in our situation as we actually *want* the user to be able to navigate away.  If there are unsaved changes when a user tries to navigate away from the view, we wanted to show a modal saying something like, "Unsaved changes - are you sure you want to leave?"  If the user taps "No", we should stay on the active view.  However, with Ionic in its current state, we have no way of canceling the navigation.

The solution we went with was to change the workflow a bit.  Instead, we say, "Unsaved changes, *would you live to save them*?"  In other words, the navigation occurs no matter what, but the user can choose whether or not to save their changes.

This still isn't really ideal (the modal actually shows up *after* the view has changed), but it is a decent compromise.

**Comment by rinogo** [comment] 2017-01-11 18:38
@skotturi Hopefully your solution and my workaround can help other devs with this problem until Ionic can issue a proper fix.
