### ISSUE TITLE
bug: Side menu closing has visual problem in Edge

### ISSUE THREAD

**Issue by mpaland** [driftyco/ionic#6955] opened 2016-06-17 21:07 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Run the following plunker in Edge browser on Windows:
http://plnkr.co/edit/nMWUDuqdPs6pxuhjQM2V?p=preview

Problem:
Open page 1 and on page 1 the side menu. When closing the side menu a black background can be seen on the right side upon the menu is fully closed. Seems to be a redraw/transotion issue.

This can only be observed in Edge browser, FF47 and Android are fine.</span>

<span is-issue-template></span>

**Comment by mpaland** [comment] 2016-06-28 11:23
This issue got worse in beta.10, especially the closing side menu on a tabs page makes visual problems in Edge now. There can always be content from other tab pages seen, when the menu slide is closing and the content of another tab is scrolled in. Upon the menu is closed, the page is refreshed and it's fine.
This can only be observed with the ios theme. I'm gonna make an updated plunker for this.

**Comment by manucorporat** [comment] 2016-07-13 23:42
@mpaland hi! can you record a quick video or gif? we don't have a windows machine right now :(

**Comment by mpaland** [comment] 2016-07-14 07:50
Sure, here it is.
![side-menu](https://cloud.githubusercontent.com/assets/763140/16831878/bc919386-49a7-11e6-8cb9-09ba2a3613ef.gif)
Problem is, that this behavior in Edge is the same like in the native Windows app. I guess they use the same rendering engine...

Perhaps you can setup a Windows VM (on your Mac or Linux machine)

**Comment by mpaland** [comment] 2016-08-12 07:05
This is still observable in beta 11, no change.

**Comment by elineopsommer** [comment] 2016-09-29 14:26
Any update on this? I have this issue too but on iOS

**Comment by manucorporat** [comment] 2016-10-11 01:38
@mpaland @elineopsommer I am so sorry, but I can't reproduce this bug without a windows machine.
I will try to get a VM working after RC1 is released :)

**Comment by manucorporat** [comment] 2016-10-11 01:39
@elineopsommer can you file a new issue?

**Comment by jgw96** [comment] 2017-04-07 16:13
Hello all! After further review I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/8710.

**Closed by jgw96** 2017-04-07 16:13 UTC
Labels: menus, platform:windows, v2
