### ISSUE TITLE
Selecting input shows jumping content and keyboard overlays input

### ISSUE THREAD

**Issue by e9li** [driftyco/ionic#11027] opened 2017-04-03 11:27 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Selecting input forces whole app to scroll up and down and sometimes keyboard overlays the sleected input field. this happes to me on all iOS devices with 10.3 and as I saw on ionic forum also in android. I didn't try it on minor iOS versions.

**Expected behavior:**
Not jumping up and down, just scrolling to the selected input.

**Steps to reproduce:**
It is a normal list with items as shown in the examples in the ionic docs inside a ion-card, nothing special. I also tried it without ion-card, same problem.

The same behavior I was in a fresh ionic app with only 1 page with input fields.

there is already an entry on ionic forum with videos and code snippets, please have a look at https://forum.ionicframework.com/t/form-jumps-when-an-input-is-selected/84254

**Comment by jgw96** [comment] 2017-04-03 18:55
Hello, thanks for using Ionic! This issue was caused by a regression in scroll events in Ionic 2.3.0. This issue has since been fixed and will be in the next release.

**Closed by jgw96** 2017-04-03 18:55 UTC

**Comment by e9li** [comment] 2017-04-03 19:04
Thanks for information. But when will be the next release? I have an app ready for the AppStore and the only problem is this issue, my client won't wait to long. Is there a work around?
