### ISSUE TITLE
bug: Can't load local image in template

### ISSUE THREAD

**Issue by Sturgelose** [driftyco/ionic#5530] opened 2016-02-19 13:55 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>If you try to load an image, picture or graphic from a local folder, there is no way to load it. You can create a folder for the pictures in <root>/app/images or in <root>/app/pages/.../images and this files are not copied to the output build in <root>/www/build.

I've been trying to tweak the ionic.config.js to copy the files but seems that it still doesn't work! 

Could you provide some guidelines on how to do so or at least enable by default to copy the images in a specific structured folder? 

There is no example or reference to follow in the demo conference-app.

Thanks a lot!</span>

<span is-issue-template></span>

**Comment by tlancina** [comment] 2016-02-19 17:18
Hey thanks for the issue, this should be in the next release of the CLI. I'm going to close it as duplicate of https://github.com/driftyco/ionic-cli/issues/745. 

For now the recommendaiton is to place static assets in `www`: https://github.com/driftyco/ionic-conference-app/tree/master/www/img.

**Closed by tlancina** 2016-02-19 17:18 UTC
Labels: build, v2
