### ISSUE TITLE
bug(ux): long clicking anywhere results in a text marker at top

### ISSUE THREAD

**Issue by AmitMY** [driftyco/ionic#11055] opened 2017-04-04 23:21 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
(this is iOS)
When long clicking anywhere in the page, it opens a text marker and shows it at the top, while marking no text.
Either mark the text, or don't show a window

**Expected behavior:**
Only possible to mark text, never show the marker on top when nothing to mark
Example for proper use:
![image](https://cloud.githubusercontent.com/assets/5757359/24683419/97547158-19a7-11e7-9e01-7279eb7ffbbf.png)

**Steps to reproduce:**
Open an app, and long text wherever. It will show some kind of text marker at the top, marking nothing

**Other information:**
I have a video showing the issue in one case, but I can't share it publicly. Is there a way to share it with devs only?

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
    Cordova CLI: 6.5.0
    Ionic Framework Version: 3.0.0-beta.3
    Ionic CLI Version: 3.0.0-beta.5
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Windows 10
    Node Version: v6.9.1
    Xcode version: Not installed
```

**Comment by jgw96** [comment] 2017-04-05 16:35
Hey, thanks for opening an issue with us! You can share the video to justin@ionic.io but if you can provide a repo we could use to reproduce the issue that would be even better (:

**Comment by Manduro** [comment] 2017-04-05 21:30
@AmitMY This has been the case with any Cordova app since iOS 9. A Cordova preference has been added to disable this 'bug'. It might interfere with text selection capabilities in your app though.

Add `<preference name="SuppressesLongPressGesture" value="true" />` to config.xml. More info on it [here](https://cordova.apache.org/docs/en/latest/config_ref/).

**Comment by AmitMY** [comment] 2017-04-05 22:16
@Manduro Thanks!
However, still, sometimes there is a need for a text selection, for example in paragraph elements. Leaving this open, because it might be fixed for that case

**Comment by AmitMY** [comment] 2017-04-07 12:10
@Manduro I used it, and it mostly worked, but then I discovered that if I swipe back from a specific page, and hold my finger, from then on every long press is showing the marker again, which I find extremely odd

**Comment by jgw96** [comment] 2017-04-14 15:58
Hello all! After reviewing further I am going to have to close this issue for now as it is actually a cordova issue. @AmitMY You can open an issue on the [cordova issue tracker](https://issues.apache.org/jira/browse/CB/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel) and they should be able to look into this. Thanks for using Ionic!

**Closed by jgw96** 2017-04-14 15:58 UTC
Labels: needs info, v2

**Comment by AmitMY** [comment] 2017-04-14 16:11
Done, thanks - https://issues.apache.org/jira/browse/CB-12660
