### ISSUE TITLE
Android keyboard blinking when refocus on another input

### ISSUE THREAD

**Issue by kinggolf** [driftyco/ionic#6140] opened 2016-04-12 19:30 UTC
#### Short description of the problem:
On Android phone in a data input form the keyboard blinks (quickly closes and opens) when moving from one text input to another.

#### What behavior are you expecting?
Keyboard should remain open.

**Steps to reproduce:**
1. Use github repo: https://github.com/kinggolf/keybd-blink.git
2. Load app and select 'Signup for Event', and Keyboard Blink Test is provided in a modal.
3. Tap top input & keyboard appears. Then tap another input & the keyboard will blink.
4. Issue is seen on both 'ionic run android --device' and 'ionic upload'

```
Cordova CLI: 6.1.0 (cordova-lib@undefined)
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.4
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
ios-deploy version: 1.8.5 
ios-sim version: 3.1.1 
OS: Mac OS X El Capitan
Node Version: v5.7.0
Xcode version: Xcode 7.3 Build version 7D175 
```

Dialog on Ionic Forum - https://forum.ionicframework.com/t/keyboard-blinks-on-changing-focus-from-one-input-field-to-another/47516
Notes from this dialog -
a) Tested on 2 Android devices - Nexus 5/Android 6.0.1 & LG G3/Android 5.0.1.
b) This happens only on ion-input, does not happen on normal input elements
c) No issue seen on iOS devices

Thank you.

**Comment by jgw96** [comment] 2016-04-12 20:03
Was able to reproduce this on my Nexus 7 2014 running Android 6.0.1.

**Comment by sava999** [comment] 2016-04-12 20:10
Hi @jgw96 I was able to reproduce this on Nexus 5 running Android 6.0.1.

**Comment by jgw96** [comment] 2016-04-12 20:13
@sava999 Thanks for the info!

**Comment by sava999** [comment] 2016-04-12 20:57
No problem, I just tested on Android 4.4.2 and everything is working fine. I don't have device with Android 5, so I am guessing that Android 5 and Android 6 are affected.

**Comment by jgw96** [comment] 2016-04-12 21:00
Heres the devices and versions i have tested this on, Nexus 6 running Android N dev preview, Nexus 7 2013 running android 6.0.1 and Moto x 2014 running Android 5.1 and i can reproduce this issue on every device so far.

**Comment by sava999** [comment] 2016-04-12 21:11
Thanks for info. If there is anything else I could do please let me know. And just to mention, I also tested on Android 4.1.1 and I wasn't able to reproduce this issue.

**Comment by sava999** [comment] 2016-05-07 17:35
@jgw96 Is this resolved? I can't reproduce issue in latest ionic version.

**Comment by jgw96** [comment] 2016-05-09 14:37
Hey @sava999 yep this was fixed as i cant reproduce it anymore either. Im gonna go ahead and close this issue, but if anyone else can still reproduce this on the latest version of Ionic please feel free to comment and ill reopen! Thanks everyone for using Ionic!

**Closed by jgw96** 2016-05-09 14:37 UTC
Labels: keyboard, modals, needs:devicetesting, platform:android, v2

**Comment by sava999** [comment] 2016-05-09 20:29
Thank you @jgw96 and keep up the good work.

**Comment by jgw96** [comment] 2016-05-09 20:32
@sava999 Thanks! I appreciate it!

**Comment by kinggolf** [comment] 2016-05-21 21:03
@jgw96 Just updated my app to Ionic2 Beta7 and this issue does not appear, as you guys previously reporter. Thx to Ionic team!!

**Comment by jgw96** [comment] 2016-05-23 07:54
@kinggolf Thanks! Awesome to hear its working for you. Thanks for using Ionic!
