### ISSUE TITLE
ion-scroll zoom does not work.

### ISSUE THREAD

**Issue by dowsanjack** [driftyco/ionic#5676] opened 2016-03-02 09:28 UTC
#### Short description of the problem:
`<ion-scroll zooming="true">` seems not to work.

#### What behavior are you expecting?
On pinchToZoom the scroll container should zoom in.

The behaviour sort, was working on 1.2.1(http://codepen.io/ankitjain11/pen/LNVVdL/), but not working on 1.2.4(http://codepen.io/ankitjain11/pen/QNbbxX)

**Ionic Version**: 1.2.4

**Browser & Operating System**: Tried on Android, Chrome. But should replicate in iOS as well.

**Run `ionic info` from terminal/cmd prompt:**

```
Your system information:

Cordova CLI: 5.4.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: Not installed
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v5.4.1
Xcode version: Xcode 6.3.2 Build version 6D2105


******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly suggested to install/upgrade the following:

 Install ios-deploy to deploy iOS applications to devices. `npm install -g ios-deploy` (may require sudo)

******************************************************
```

**Comment by jgw96** [comment] 2016-03-11 20:41
Thanks for submitting this issue! As this bug is a duplicate of issue #5790 i will be closing this one. Please feel free to continue the discussion over on that bug!

**Closed by jgw96** 2016-03-11 20:41 UTC
Labels: platform:android, platform:ios, v1
