### ISSUE TITLE
Scrolling issue in ios. 

### ISSUE THREAD

**Issue by imabasghar** [driftyco/ionic#6649] opened 2016-05-25 12:09 UTC
Using Ionic2
we are using the following markup for a page: 

```
<ion-content class="home-content">
    <img src='....' />
 </ion-content>
<ion-toolbar position="bottom" class="contact-us">
    ...
</ion-toolbar>
```

In android and desktop the scroll is fine, but when using  IPhone 6plus in the page's initial state, if we scroll up, the scroll becomes unresponsive. We have to wait for a few seconds and then we can scroll down. 

We digged deep into the html and css generated in app.ios.css and found out that the body's style position: fixed was messing this up. If we change the position: fixed to initial or relative the header and footer start to scroll as well .

**Comment by jgw96** [comment] 2016-05-25 14:27
Hello, thanks for opening an issue with us! Would you mind making a plunker or repo that i can pull and use to reproduce this? Thanks for using Ionic!

**Comment by imabasghar** [comment] 2016-05-26 05:32
Try the demo on this  [blog](http://coenraets.org/blog/2014/10/ionic-tutorial-and-sample-application/)  on an Iphone:
[Demo URL](http://coenraets.org/apps/ionic2-directory/)

You can use this [repo](https://github.com/ccoenraets/ionic2-employee-directory).

PS: This is not our repository. The demo and repo belongs to [him](https://github.com/ccoenraets)

**Comment by jgw96** [comment] 2016-05-26 14:22
Hello! So after testing this issue on my iphone5 I can't seem to reproduce it. Is the app that you're experiencing this with running Ionic 2 beta.7? Also, what version of iOS are you running?

**Comment by imabasghar** [comment] 2016-05-26 14:53
If you see the package.json in the repo, it says Ionic2 beta .7. I tried it on an IPhone 5s and the issue still remains. I am using Mobile Safari since I havent mentioned that, sorry about that.
Steps to re produce: 
1 - Open Page
2 - (Dont swipe upwards) Swipe downwards, and then swipe ur finger up or down. It becomes sticky. 
3- Remove your finger from the phone for 2 or 3 seconds.
4 - swipe upwards: scrolling is fine now

**Comment by manucorporat** [comment] 2016-06-09 08:15
@imabasghar ok! I have investigating and this is a duplicate of https://github.com/driftyco/ionic/issues/6755

I think there are not an easy fix for this issue on iOS, but it is definitively on my radar, it MUST be fixed.
I will close this issue as Duplicated, but please feel free to continue the discussion here: https://github.com/driftyco/ionic/issues/6755

**Closed by manucorporat** 2016-06-09 08:15 UTC
Labels: v2
