### ISSUE TITLE
[Ionic 2] Events API: Data gets wrapped in an array

### ISSUE THREAD

**Issue by FdezRomero** [driftyco/ionic#6459] opened 2016-05-06 16:07 UTC
#### Short description of the problem:
When publishing an event with data, the subscriber handler receives it wrapped in an array.

#### What behavior are you expecting?
To receive the event data as published, unmodified.

**Steps to reproduce:**
1. Subscribe to a topic and expect a data parameter: `this.events.subscribe('test', eventData => console.log(eventData));`
2. Publish an event with data: `this.events.publish('test', {message: 'Object test'});`
3. The object is received by the subscriber wrapped in an array: `[{message: 'Object test'}]`

```typescript
this.events.subscribe('test', eventData => console.log(eventData));

setTimeout(() => {
  this.events.publish('test', 'String test');
  this.events.publish('test', {message: 'Object test'});
}, 1000);
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 N/A

**Which Ionic Version?**
ionic-angular@2.0.0-beta.6

#### Plunker that shows an example of your issue
http://plnkr.co/edit/zqUCn0Brq5odwAyHFAAV?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.6-201604251507
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment] 2016-05-06 16:16
Hello! Thanks for opening an issue with us! I am going to be closing this as a duplicate of https://github.com/driftyco/ionic-site/issues/544. Feel free to comment on that issue and thanks for using Ionic!

**Closed by jgw96** 2016-05-06 16:16 UTC
Labels: platform:ios, v2

**Comment by phengsengvuthy** [comment] 2016-12-01 15:23
Hello Mr I passed data as the following above, but my result I got it was null? 

{ID: 1, Name: 'Hello'}; What I passed.
