### ISSUE TITLE
super template does not work

### ISSUE THREAD

**Issue by jdell64** [driftyco/ionic#11193] opened 2017-04-12 14:40 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
running the super template does not work out of the box.
```
Runtime Error
Cannot find module "ionic-native"
```

**Expected behavior:**
It should work.

**Steps to reproduce:**
`ionic start superApp super --v2`

**Comment by jgw96** [comment] 2017-04-12 18:59
Hello, thanks for opening an issue with us, I am going to close this as a duplicate of https://github.com/driftyco/ionic-starter-super/issues/88.

**Closed by jgw96** 2017-04-12 18:59 UTC

**Comment by jdell64** [comment] 2017-04-12 22:39
Sorry about that... I did do a search... I promise!
