### ISSUE TITLE
IONIC2 beta11:The checkbox can't be checked if it has property ‘ngModel’

### ISSUE THREAD

**Issue by NealBeat** [driftyco/ionic#8872] opened 2016-10-24 04:31 UTC
my version of ionic2 is beta11, I am using component 'checkbox' to make a class named 'mycheckbox',the following code shows that:
`<ion-item *ngFor="let el of item.uiConfig; let j = index;"> <ion-label>{{el.label}}</ion-label> <ion-checkbox [(ngModel)]="todo[i].checked" [value]="el.value" [checked]="el.checked" ></ion-checkbox> </ion-item>`

these segment could create a group of checkbox with the following configrations.

`uiConfig = [ {label:"label1",value:"value1",checked:false}, {label:"label2",value:"value2",checked:true}, {label:"label3",value:"value3",checked:false} ];`

the page is:

![qq 20161024100625](https://cloud.githubusercontent.com/assets/20578354/19633566/b7f389cc-99e5-11e6-856b-286f7141e972.png)

as you can see , my configration tried to make the second element checked. but it doesn't work. when i remove the property 'ngModel', it works!

![qq 20161024101112](https://cloud.githubusercontent.com/assets/20578354/19633558/ad5ba724-99e5-11e6-955b-87c3bfb1e4f9.png)

please check this and fix it!

**Comment by jgw96** [comment] 2016-10-24 15:53
Hello, thanks for using Ionic! Could you create a plunker I can use to reproduce this issue?

**Comment by NealBeat** [comment] 2016-10-25 06:36
if a checkbox in a component has the property ‘ngModel’，the initialize action 'check' will lose efficacy.

let's try the codes below,i create a component using the following template.
`<ion-checkbox [(ngModel)]="mymodel.checked"  [name]="mymodel.name" [value]="mymodel.value"  [checked]="mymodel.checked" ></ion-checkbox>`, 
the value of ‘mymodel.checked’ is true.
the selector of the component is 'mycheckbox', 
when i use it in a page `<mycheckbox config="mymodel"></mycheckbox>`
the view of the checkbox can not be checked.

then we change the codes,remove the property 'ngModel'.
`<ion-checkbox  [name]="mymodel.name" [value]="mymodel.value"  [checked]="mymodel.checked" ></ion-checkbox>`
you'll get a correct view with the checkbox checked.
that's it. thank you

**Comment by jgw96** [comment] 2016-10-25 15:08
@NealBeat thanks for the info! First, just a note, do you need the two way binding in this context that `[(ngModel)]` provides, or can you still achieve your use case with the binding to `value` on `ion-checkbox`? In Angular the less you can use `[(ngModel)]` the better your performance will be. On the bug here, it seems to be an Angular bug and not an Ionic bug. Ionic does not change anything with `[(ngModel)]` so it will work exactly the same on an Ionic component as it does in a plain Angular 2 component. Because of this I am going to close this issue for now. Thanks!

**Closed by jgw96** 2016-10-25 15:08 UTC
Labels: needs reply, v2
