### ISSUE TITLE
bug : back button can't work well

### ISSUE THREAD

**Issue by hxzAugustinus** [driftyco/ionic#8114] opened 2016-09-19 06:29 UTC
**Type**: bug

**Ionic Version**: 1.3.1

**Platform**:  android

see  this  demo gif:
<html>
<body>  <img   style="width:100px; "  src='https://raw.githubusercontent.com/hxzAugustinus/gitProject/master/pic/aaa.gif'>
</body>
<html>

Reproduction  operating steps：

A --> A1  , B-->**B1**-->B , A1-->A  ,  B-->**B1**

the first  time enter  **B1**  , the  back  button  appear truly , however the second time  **B1**   , you
will find that the back button  does't  appear . it's so  stranger!

**ionic info**  :

Cordova CLI: 6.0  
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 1.7.16
Ionic App Lib Version: 0.7.3
OS: Windows 7 SP1
Node Version: v4.4.7

**Comment by jgw96** [comment] 2016-09-28 18:07
Hello, thanks for using Ionic! Would you mind creating a repo that i can use to reproduce this issue? Also, i would double check your ui-router setup, most likely that is causing this issue.

**Comment by hxzAugustinus** [comment] 2016-09-29 09:35
[codepen example](http://codepen.io/hxz/pen/kkoWrx?editors=1010#0)

just  do  as  which  i  said the  steps:
A --> A1 , B-->B1-->B , A1-->A , B-->B1;

**Comment by loopezz** [comment] 2016-10-02 17:50
https://github.com/driftyco/ionic/issues/6875

**Comment by jgw96** [comment] 2016-10-03 01:07
Hello, thanks for the codepen! After reviewing this issue it seems to be a duplicate of #6875. Because of this I will be closing this issue for now. Thanks for using Ionic!

**Closed by jgw96** 2016-10-03 01:07 UTC
Labels: needs reply, platform:android, range, v1
