### ISSUE TITLE
Ionic 3.1.0 VirtualScroll not render well and don't reload if change segment

### ISSUE THREAD

**Issue by javico2609** [driftyco/ionic#11387] opened 2017-04-26 22:59 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[X ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Only work if scroll the view. If change the segment value not render again.

![image](https://cloud.githubusercontent.com/assets/12940555/25460524/44b3452c-2aba-11e7-8666-43284b9469a0.png)

**Expected behavior:**

![image](https://cloud.githubusercontent.com/assets/12940555/25460528/544294e8-2aba-11e7-82ef-9d42828ca808.png)

**Steps to reproduce:**

**Related code:**
[repository](https://github.com/javico2609/angular-mvd-meetup)
```
<ion-list [virtualScroll]="meetups" [headerFn]="headerMeetupFn" approxItemHeight="250px">

    <ion-item-divider *virtualHeader="let header">
      {{ header }}
    </ion-item-divider>

    <button ion-item *virtualItem="let event">
      <small item-left>{{ event.time | date:"jm" }}</small>
      <h2 class="event-group">{{ event.group.name }}</h2>
      <p text-wrap text-justify class="event-name">{{ event.name }}</p>    
      <h6 text-justify class="secondary-font"><ion-icon name="pin"></ion-icon>   
        <span *ngIf="!event.venue?.name">Undisclosed</span>
        <span *ngIf="event.venue?.name">{{event.venue?.name}}</span>
        <span *ngIf="!event.venue?.address_1"></span>
        <span *ngIf="event.venue?.address_1"> , {{event.venue?.address_1}}</span>
      </h6>
      <h6 text-justify class="secondary-font"><ion-icon name="md-walk"></ion-icon>
        <span> Distance: {{event.distance | distance}} </span>
      </h6>
      <h6 text-justify class="secondary-font">
        <span>{{ event.yes_rsvp_count }} {{ event.group.who}} going</span>
      </h6>
    </button>

  </ion-list>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```

    Cordova CLI: 6.5.0
    Ionic Framework Version: 3.1.0
    Ionic CLI Version: 3.0.0-beta7
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Windows 10
    Node Version: v7.7.3
    Xcode version: Not installed

```

**Comment by jgw96** [comment] 2017-04-27 20:21
Hello, thanks for opening an issue with us. I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/7734

**Closed by jgw96** 2017-04-27 20:21 UTC
