### ISSUE TITLE
virtualScroll within ion-card

### ISSUE THREAD

**Issue by voegtlel** [driftyco/ionic#11759] opened 2017-05-23 08:15 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[x] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When using the virtualScroll inside an ion-card, the viewport size calculation fails, since on startup the card has a size of one element and the size calculation seems to use its parent element.
When resizing the windows afterwards, the size of the ion-card is the full size, thus the virtualScroll will create all items (which makes it obsolete).

**Expected behavior:**
The scrollable viewport should be taken for computing the size instead.

**Steps to reproduce:**
http://plnkr.co/edit/5sFw3JtDbUvNPMe9TogD?p=preview

Tested with Chrome on Desktop.

**Related code:**

```
<ion-card>
  <ion-card-content>
    <ion-list [virtualScroll]="items" approxItemHeight="85px">
      <ion-item *virtualItem="let item">
        <ion-label>
          <h2>{{item.title}}</h2>
          <h3>{{item.subTitle}}</h3>
          <p>{{item.text}}</p>
        </ion-label>
      </ion-item>
    </ion-list>
  </ion-card-content>
</ion-card>
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
(I use meteor CLI, thus no `ionic info`). Plukr should be up-to-date and demonstrates the issue.

Used Packages:
```
"@angular/core": "^4.1.1",
"ionic-angular": "^3.2.0",
```

**Comment by jgw96** [comment] 2017-05-23 15:12
Hello, thanks for opening an issue with us! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/10317.

**Closed by jgw96** 2017-05-23 15:12 UTC
