### ISSUE TITLE
Searchbar cursor jumps when editing text

### ISSUE THREAD

**Issue by brentatproductops** [driftyco/ionic#6013] opened 2016-04-01 14:21 UTC
#### Short description of the problem:
When editing text within a Searchbar the cursor jumps to the end of the text that's being edited.

#### What behavior are you expecting?
When modifying text within the Searchbar the cursor stays where the editing is taking place instead of jumping.

**Steps to reproduce:**
1. Navigate here: http://ionicframework.com/docs/v2/api/components/searchbar/Searchbar/
2. Type "searchturm" into one of the Searchbars.
3. Delete "u" from the text and add "e", you should see the cursor jump to the end of the text at this point.

Also able to reproduce in my application with the following setup:
Cordova CLI: 5.4.1
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.22
Ionic App Lib Version: 2.0.0-beta.12
ios-deploy version: 1.8.5 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.3 Build version 7D175

**Comment by jgw96** [comment] 2016-04-01 14:27
Hello! As this issue is a duplicate of https://github.com/driftyco/ionic/issues/5942 I will be closing this issue. Please feel free to continue this conversation on that issue! Thanks!

**Closed by jgw96** 2016-04-01 14:27 UTC
Labels: platform:ios, v2
