### ISSUE TITLE
back button issue or pop issue

### ISSUE THREAD

**Issue by praveens96** [driftyco/ionic#7915] opened 2016-08-30 17:55 UTC
#### Short description of the problem:
i am trying to pop after doing a normal push and push with parameters. i am redirecting to root instead of back page and the view is partially loaded. not finding a way to resolve this.

#### What behavior are you expecting?
expected is it follows the history and go back one level but it is going to root

**Steps to reproduce:**
1. do a push
2. do a push with parameters
3. pop

just trying to use default back button.

**Which Ionic Version?** 1.x or 2.x
using beta 11 

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
ionic info:
Your system information:

Cordova CLI: 6.3.0
Ionic CLI Version: 2.0.0-beta.35
Ionic App Lib Version: 2.0.0-beta.19
ios-deploy version: Not installed
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.4.7
Xcode version: Xcode 7.3.1 Build version 7D1014 

******************************************************
 Dependency warning - for the CLI to run correctly,      
 it is highly recommended to install/upgrade the following:     

 Install ios-deploy to deploy iOS applications to devices.  `npm install -g ios-deploy` (may require sudo)

**Comment by jgw96** [comment] 2016-08-30 20:40
Hello, thanks for using Ionic! Would you mind sharing a code snippet or repo that I can use to reproduce this issue?

**Comment by mikewagz** [comment] 2016-08-30 23:16
I am also seeing this when attempting to use the Navbar built-in "back" functionality.  The animation stops halfway.  This is after a normal push:

```
this.navCtrl.push(ItemPage, {
      item_id: item.id,
    }, {animate: true, direction: 'forward', animation: "ios-transition"});
```

Also, the "back" animation is incorrect - it does a md-transition (drop/fade) instead of the ios-transition (slide in/out) that the page was pushed with.  

Thanks for looking into this!

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.8.6 
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v6.4.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by praveens96** [comment] 2016-08-31 04:42
i am also facing the issue same as @mikewagz . i tried overriding the back button functionality and tried getting the index of the view controller. 
while pushing index value is coming as 1 and 2. when popping value is decremented but view is not changing.

**Comment by vupeter** [comment] 2016-08-31 15:20
Having a similar problem to this but due to having (tap)="pushFunction()" run the push function twice: The result is the nav gets totally messed up and having two of the same pages pushed and the built-in back doesn't work after closing those two pages. This is on beta.11.

Happens only in ionic serve with (tap), it runs normally on android and (click) runs it normally.

**Comment by jgw96** [comment] 2016-09-01 14:46
Thanks for al the info everyone! Can someone post a minimal repo that I can reproduce this issue with?

**Comment by jgw96** [comment] 2016-09-06 12:48
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-09-06 12:48 UTC
Labels: needs reply, v2
