### ISSUE TITLE
Tapping on an already active tab causes the ionViewDidLoad of the tab to trigger again.

### ISSUE THREAD

**Issue by sunny061** [driftyco/ionic#11253] opened 2017-04-18 08:24 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I created a new ionic 3 project with the tabs layout. And after adding a console.log() inside the ionViewDidLoad of each tab .ts file, I noticed that tapping on an already active tab fires the ionViewDidLoad again. If the tab has params passed to it, they will be undefined when tapping on the active tab again.

**Expected behavior:**
Tapping on an already active tab should not fire the ionViewDidLoad of the tab as it is already in view and cached.

**Steps to reproduce:**
Create a new ionic project using the --v2 --tabs flags. Add the ionViewDidLoad function in the .ts files of any tab component. And then tap on the active tab should fire the ionViewDidLoad again.

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

insert the output from ionic info here
```
Cordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.1
ios-deploy version: 1.9.1
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v6.10.0
Xcode version: Xcode 8.3.1 Build version 8E1000a
```

**Comment by alexbainbridge** [comment] 2017-04-18 09:39
Also ionViewWill / Did Enter ..... however I prefer it this way, effectively its a page reload initiated by the user? i.e. by design

**Comment by sunny061** [comment] 2017-04-18 09:43
I have some data passed to the tab through rootParams. And when you tap on this active tab, it will reload but with the params being undefined.

e.g.
```
<ion-tab [root]="tabOne" [rootParams]="tabOneParams"></ion-tab>
```

**Comment by N4vros** [comment] 2017-04-19 07:37
Same issue, rootParams values are undefined when I click on an active tab.

**Comment by drptbl** [comment] 2017-04-19 08:53
Should be already fixed at `master` branch.
https://github.com/driftyco/ionic/pull/11084

**Comment by jgw96** [comment] 2017-04-19 13:56
Hello, everyone! The next release will have this fix. It is already fixed in master with the above PR @drptbl linked too.

**Closed by jgw96** 2017-04-19 13:56 UTC
