### ISSUE TITLE
Contacts plugin - Can't create after update.

### ISSUE THREAD

**Issue by Klerith** [driftyco/ionic#10900] opened 2017-03-23 23:35 UTC
**Ionic version:** 
[ ] **1.x**
[ X ] **2.x**

**I'm submitting a ...**
[ X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
After the new change of moving 'ionic-native' to  '@ionic-native/contacts', this plugin doesn't work or maybe I am missing something here ( I was using the previous version with no problems )

When I try to execute this line on runtime 
let contact: Contact = this.contacts.create();

I get this error, that basically, saids I can't call create of undefined.
![image](https://cloud.githubusercontent.com/assets/3438503/24274553/83779d1c-0fee-11e7-9659-6b5c1ea0bb0b.png)

**Expected behavior:**
Create a contact object with no issues.

**Steps to reproduce:**
Just follow the ionic Contacts tutorial

http://ionicframework.com/docs/v2/native/contacts/

**Related code:**

This is my app.module
```
@NgModule({
  declarations: [
    MyApp,
    HomePage,
    GuardadosPage,
    MapaPage,
    TabsPage
  ],
  imports: [
    IonicModule.forRoot(MyApp),
    AgmCoreModule.forRoot({
      apiKey: 'XXXXXXXXXX'
    })
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    HomePage,
    GuardadosPage,
    MapaPage,
    TabsPage
  ],
  providers: [
    StatusBar,
    SplashScreen,
    BarcodeScanner,
    InAppBrowser,
    Contacts,
    HistorialService,
    {provide: ErrorHandler, useClass: IonicErrorHandler}
  ]
})
export class AppModule {}
```

Also in my service, I am injecting the "Contacts" module.

I am kind of lost here.

Cordova CLI: 6.5.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.1
ios-sim version: 5.0.13

OS: macOS Sierra
Node Version: v6.9.5
Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by rapropos** [comment] 2017-03-24 00:00
Should probably be reassigned to ionic-native, but I suspect the problem is failure to adjust to the new injectable syntax:

### OLD: 
```
import {Plugin} from "ionic-native";

constructor() {
  Plugin.frobulate();
}
```

### NEW:
```
import {Plugin} from "@ionic-native/plugin";

constructor(plugin: Plugin) {
  plugin.frobulate();
}
```

**Comment by Klerith** [comment] 2017-03-24 00:04
I use the new syntax version using '@ionic-native/contacts'

But after running some test here, looks like it works on devices, but in the browsers crashes with that error.

**Comment by jgw96** [comment] 2017-03-24 18:37
This issue was moved to driftyco/ionic-native#1250

**Closed by jgw96** 2017-03-24 18:37 UTC
