### ISSUE TITLE
bug: $ionicLoading breaks Select/Copy/Paste on iOS

### ISSUE THREAD

**Issue by ackerdev** [driftyco/ionic#3793] opened 2015-05-20 19:07 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>$ionicLoading causes the popover for Select/Copy/Paste in an input to become unresponsive; tapping near the cursor in a text input will bring up the menu, but attempting to tap any of the options will not work, and the menu just stays open not responding to touch events.

It seems to be caused by the fact that the `.loading-container` element is hidden via `visibility: hidden`, and this seems to be blocking tap inputs to the floating menu. I'm currently using the following as a workaround:

```css
.loading-container:not(.visible) {
  display: none;
}
```
</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment] 2015-05-20 20:42
Could you put this in a codepen? Are you referring to an input in the loading screen content or on the page being covered?

**Comment by ackerdev** [comment] 2015-05-21 15:03
The input is on the page in an ion-content element, not within the loading screen template; upon further experimentation it seems to only happen when the template is an ion-spinner with the icon attribute.

I tried setting it up in a [codepen](http://codepen.io/anon/pen/vOXJKZ) but it's not useful unless you can at least make it fullscreen... but I don't even know if that will work, I couldn't test it, so it may need to be in a webview.

Just try to tap the textarea and try to Select All, and you should see it do nothing and leave the menu open.

**Comment by perrygovier** [comment] 2015-05-22 18:41
You can create a project from a codepen with 
`ionic start test http://codepen.io/anon/pen/vOXJKZ`

I can reproduce this, thanks. Will take a look.

**Comment by jgw96** [comment] 2016-05-24 15:49
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment] 2016-05-31 07:17
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-05-31 07:17 UTC
Labels: needs reply, platform:ios, ready, v1

**Comment by Hitman666** [comment] 2016-07-25 06:11
Hi jgw96,

I just stumbled upon this issue, and I can confirm it's still present. Did you guys find a solution for this in the end?

**Comment by markopavlovic** [comment] 2016-08-15 00:15
Hi guys, wasn't really using $ionicLoading, but was using a `ion-spinner` and I think the source of the problem comes from there. As soon as I remove `ion-spinner`, the select/paste functions work properly.

**Comment by Sorin-fratila** [comment] 2018-08-15 09:14
I am not using $ionicLoading and I am not using ion-spinner and I am still having this issue. Does anyone still experience this or has found a solution?
