### ISSUE TITLE
perf: SVG / IonicLoading / Ion-Refresher causing CPU usage when not shown

### ISSUE THREAD

**Issue by foxgeere** [driftyco/ionic#3954] opened 2015-06-18 15:28 UTC
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>The animated SVG / loading animations are used in ion-refresher or in the ionicLoading code. Once they have been displayed and then hidden again they still remain in the DOM animating and eat up CPU. After a while on Android devices it heats the phone up and runs the battery down very quickly, especially if you have loaded the animated SVG in multiple views / places while using the app.

It appears a fix is needed to ensure that the SVG is entirely destroyed once finished with. Even when it is technically not in the DOM it still uses up CPU time. This appears to be more of an issue on android devices.

On Android if you load a view that loads an animated SVG and then leave that view, the CPU remains high. 

On iPhone it sits the CPU at about 5% while on the view (even after the loader has finished / been removed) but returns to 0% when you leave the view.

Hopefully this helps someone trying to understand why their app ends up with decreasing performance, battery heating and odd CPU usage, especially on android devices.

I hope this issue has been submitted in the right way. We don't get have a fix other than trying to use an animated GIF or no animation at all instead of one of the animated SVGs.

It is also worth noting that if you simply have a pull-to-refresh tag at the top of the page it will cause this issue even if you have not yet done a pull to refresh.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-06-18 15:28
Greetings @foxgeere!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3954). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3954)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by foxgeere** [comment] 2015-06-18 15:33
Just did another check and happen to find this https://github.com/driftyco/ionic/issues/3583

Appears this may be a duplicate of that issue and hopefully fixed in an upcoming release.

**Comment by mhartington** [comment] 2015-06-18 16:03
Closing as it is a duplicate of #3583

**Closed** 2015-06-18 16:28 UTC
