### ISSUE TITLE
Can't resolve all parameters for provideLocationStrategy: (PlatformLocation, ?, Config).

### ISSUE THREAD

**Issue by h2qbkhn** [driftyco/ionic#8418] opened 2016-10-03 08:11 UTC
Hi everyone, 
I tried to update my project with Ionic2 RC0. I choose the way that guide me to modify my existing project. Now I'am having an error: 

metadata_resolver.js:499 Uncaught Error: Can't resolve all parameters for provideLocationStrategy: (PlatformLocation, ?, Config)
CompileMetadataResolver.getDependenciesMetadata	@	metadata_resolver.js:499
CompileMetadataResolver.getFactoryMetadata	@	metadata_resolver.js:411
CompileMetadataResolver.getProviderMetadata	@	metadata_resolver.js:595
(anonymous function)	@	metadata_resolver.js:539
CompileMetadataResolver.getProvidersMetadata	@	metadata_resolver.js:523
(anonymous function)	@	metadata_resolver.js:221
CompileMetadataResolver.getNgModuleMetadata	@	metadata_resolver.js:212
RuntimeCompiler._compileComponents	@	runtime_compiler.js:126
RuntimeCompiler._compileModuleAndComponents	@	runtime_compiler.js:64
RuntimeCompiler.compileModuleAsync	@	runtime_compiler.js:55
PlatformRef_._bootstrapModuleWithZone	@	application_ref.js:302
PlatformRef_.bootstrapModule	@	application_ref.js:284
(anonymous function)	@	main.dev.js:3
(anonymous function)	@	main.dev.js:3

Here is my app.module.ts : 

@NgModule({
    declarations: [
        MyApp,
        ConfigPage,
        SplashPage,
        MainPage,
        TimeAgoPipe, 
        DateFormatPipe,
        APP_DIRECTIVES
    ],
    imports: [
        IonicModule.forRoot(MyApp, {}), 
        TranslateModule.forRoot()
       
    ],
    bootstrap: [IonicApp],
    entryComponents: [
        MyApp,
        ConfigPage,
        SplashPage,
        MainPage,
        TimeAgoPipe, 
        DateFormatPipe,
        APP_DIRECTIVES
    ]
})
export class AppModule { }

Can anyone help me pls? 

Thanks

**Comment by chiccorusso** [comment] 2016-10-03 08:40
I fixed updating to the latest node (6.7.0) and npm (3.10.8).

**Comment by jgw96** [comment] 2016-10-03 14:26
Hello, thanks for using Ionic! Could you provide a repo that i can use to reproduce this issue? Thanks!

**Comment by jackiewung** [comment] 2016-10-04 01:40
Hi there, also receiving the same error. I can produce this error by running:
```
ionic start cutePuppyPics --v2
```

I also receive a bunch of missing components when I do this, including:
```
Cannot find module '@angular/core'
Cannot find module '@angular/platform-browser-dynamic'
lint failed:  Unable to find "tslint" command: null
```

When I install the missing modules manually, the errors go away, and it spins up a build and server that then gives the error posted above. Wondering if any of those missing modules errors are attributed to the posted error - perhaps I'm missing other modules, or running on the wrong npm/nvm? My nvm is currently at version 0.31.1.

**Comment by jgw96** [comment] 2016-10-04 15:13
Hello all! I am going to close this issue as the OP's issue is most likely caused by the same issue that @jackiewung ran into. With RC.0 we require NPM 3. Thanks!

**Closed by jgw96** 2016-10-04 15:13 UTC
Labels: needs reply, v2
