### ISSUE TITLE
bug: ion-nav-bar title style left and right not working

### ISSUE THREAD

**Issue by wallaceg** [driftyco/ionic#3538] opened 2015-04-16 18:11 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>Within nexus 5, styles (left and right) applied to a title are not working and the title text is appearing below the back button (ion-nav-back-button).</span>

<span is-issue-template></span>

**Comment by wallaceg** [comment] 2015-04-16 18:13
The code that applies the styling is from ionic.bundle.js on lines 6159 (Ionic, v1.0.0-beta.13)

**Comment by wallaceg** [comment] 2015-04-16 18:22
Debugging code, it gets on line <code>titleEl.style.left = margin + 'px';</code> and after but never renders it.
<pre>
<code>
if(align == 'center') {
          if(margin > 10) {
            titleEl.style.left = margin + 'px';
            titleEl.style.right = margin + 'px';
          }
          if(titleEl.offsetWidth < titleEl.scrollWidth) {
            if(rightWidth > 0) {
              titleEl.style.right = (rightWidth + 5) + 'px';
            }
          }
        } else if(align == 'left') {
          titleEl.classList.add('title-left');
          if(leftWidth > 0) {
            titleEl.style.left = (leftWidth + 15) + 'px';
          }
        } else if(align == 'right') {
          titleEl.classList.add('title-right');
          if(rightWidth > 0) {
            titleEl.style.right = (rightWidth + 15) + 'px';
          }
        }</code>
</pre>

**Comment by wallaceg** [comment] 2015-04-16 18:32
On view:
```html
<ion-nav-bar class='nav-title-slide'>
     <ion-nav-back-button class='button-icon ion-chevron-left'></ion-nav-back-button>
</ion-nav-bar>
```

**Comment by Ionitron** [comment] 2015-04-16 19:45
Greetings @wallaceg!

My sensors indicate that I require more information in order to assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this happen occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com), where many humans will be able to offer wisdom and advice.

Thank you for allowing me to assist you.

<span ionitron-needs-reply></span>

**Comment by Ionitron** [comment] 2015-05-16 20:17
Greetings @wallaceg!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-05-16 20:17 UTC
Labels: ionitron:closed
