### ISSUE TITLE
I have an issue regarding infinit scroll and this is going to be worse

### ISSUE THREAD

**Issue by ssharmass** [driftyco/ionic#4601] opened 2015-11-05 13:18 UTC
Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: observation in observationlists, Duplicate key: undefined:undefined, Duplicate value: undefined
http://errors.angularjs.org/1.3.13/ngRepeat/dupes?p0=observation%20in%20observationlists&p1=undefined%3Aundefined&p2=undefined
    at ionic.bundle.js:8890
    at ngRepeatAction (ionic.bundle.js:33279)
    at Object.$watchCollectionAction [as fn] (ionic.bundle.js:22937)
    at Scope.$digest (ionic.bundle.js:23070)
    at Scope.$apply (ionic.bundle.js:23333)
    at done (ionic.bundle.js:18486)
    at completeRequest (ionic.bundle.js:18676)
    at XMLHttpRequest.requestLoaded (ionic.bundle.js:18617)

**Comment by Ionitron** [comment] 2015-11-05 13:18
Greetings @ssharmass!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4601). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4601)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by jgw96** [comment] 2016-03-15 14:12
Hello! Thanks for opening an issue with us, we just need a little more info from you so that we can better help you with your issue. Would you mind posting a code sample, plunkr or codepen that we can use to reproduce your issue? Also, would you mind running `ionic info` and posting the output? Thanks again!

**Comment by jgw96** [comment] 2016-04-01 19:21
As it has been a little while since there was any activity on this issue I will be closing it for now, please feel free to reply if you are still experiencing this issue though!

**Closed by jgw96** 2016-04-01 19:21 UTC
