### ISSUE TITLE
bug: Custom component within ion-item ignored

### ISSUE THREAD

**Issue by Xenoage** [driftyco/ionic#7252] opened 2016-07-09 12:08 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When using a custom component within an `<ion-item>`, it is ignored on the using page:

```
<ion-list>
  <ion-item>
    <my-comp></mycomp> <!-- ignored -->
  </ion-item>
</ion-list>
```

(Where my-comp contains for example just `<ion-input type="text"></ion-input>`)

When I put the whole `<ion-item>` in the custom component, it works:

```
<ion-list>
  <my-comp></mycomp> <!-- now working -->
</ion-list></span>
```

(Where my-comp contains now for example `<ion-item><ion-input type="text"></ion-input></ion-item>`)

<span is-issue-template></span>

**Comment by brandyscarney** [comment] 2016-07-11 19:04
So custom components won't work inside of an `ion-item` because Items use Angular's content projection to place the elements inside of it. There is some more info on this here: http://ionicframework.com/docs/v2/api/components/item/Item/#item-placement

What is your wrapper component doing? Trying to understand the full use case here. Thanks!

**Comment by Xenoage** [comment] 2016-07-12 06:19
In my case I have created a reusable date input control, consisting of a text field and a clickable icon which opens a graphical date chooser. Full code:

```
<div>
  <ion-input #dateInput type="text" [ngModel]="date" (blur)="onDate(dateInput.value)"></ion-input>
  <ion-icon name="calendar" item-right (click)="pickDate()" class="rs-inputicon"></ion-icon>
</div>
```

My current workaround is, as already mentioned, to put the whole item into the custom component. Unfortunately, its usage is now more limited because of the added label.

```
<ion-item>
  <ion-label stacked>{{label}}</ion-label>
  <ion-input #dateInput type="text" [ngModel]="date" (blur)="onDate(dateInput.value)"></ion-input>
  <ion-icon name="calendar" item-right (click)="pickDate()" class="rs-inputicon"></ion-icon>
</ion-item>
```

**Comment by jgw96** [comment] 2016-07-25 21:38
related https://github.com/driftyco/ionic/issues/7425

**Comment by Richie765** [comment] 2016-10-01 19:35
I'm having the exact same problem as op.

The Item Placement of <ion-item> seriously limits the creation of custom form controls. Isn't there some kind of work-around to get an <ion-item> without the placement magic? Perhaps a <span> tag with a couple of styles or classes? Or couldn't an attribute be added to <ion-item> to turn of the Item Placement?

**Comment by Richie765** [comment] 2016-10-01 19:52
I had the same problem. Adding the `item-content` attribute solved the issue for me

```
<ion-list>
  <ion-item>
    <my-comp item-content></mycomp> <!-- no longer ignored -->
  </ion-item>
</ion-list>
```

**Comment by jgw96** [comment] 2017-05-18 16:58
Hello all, I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/6849.

**Closed by jgw96** 2017-05-18 16:58 UTC
Labels: v2
