### ISSUE TITLE
Transform Tabs bottom navigation to Left navigation on large screen, [Material Specs]

### ISSUE THREAD

**Issue by 5im0n** [driftyco/ionic#10326] opened 2017-02-06 10:32 UTC
**Ionic version:**
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**
[ ] bug report
[X] feature request :smiley:
[ ] support request =>

**Current behavior:**

When we are on large screen as tablet the tabs remain on the bottom of the view.

**Expected behavior:**

According to the Material design specs, bottom navigation becomes left navigation on large screen.
To my mind this behavior should be configurable.
https://material.io/guidelines/components/bottom-navigation.html#bottom-navigation-usage

![components_bottomnavigation_usage2](https://cloud.githubusercontent.com/assets/659811/22643553/4ccf6716-ec5f-11e6-8701-c6cc3316ff17.png)

**Related code:**

```
<ion-tabs>
  <ion-tab [root]="tab1Root"></ion-tab>
  <ion-tab [root]="tab2Root"></ion-tab>
  <ion-tab [root]="tab3Root"></ion-tab>
</ion-tabs>
```

**Comment by jgw96** [comment] 2017-02-06 17:18
Hello, thanks for using Ionic! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/7759.

**Closed by jgw96** 2017-02-06 17:18 UTC

**Comment by almothafar** [comment] 2017-02-08 09:44
@jgw96 I don't think it is a duplicate! it is really talking about the navigation, but in #7759 it is talking about center the tabs icon if the tabs was horizontally viewed, it is clear here he talking about making a navigation to left in large screen, also it could be an option to be added, I saw your reference to youtube it is one of material design concepts, that could be used, related to tabs: https://material.io/guidelines/components/tabs.html 

Look at this also: https://material.io/guidelines/layout/split-screen.html#split-screen-layout

**Comment by ahmedBassuoni** [comment] 2017-02-08 11:15
@jgw96 I failed to see the duplicate here, centering the Icons are not the same of changing the tab-bar layout from horizontal to vertical and moving its position from bottom to left !! Please re-open this one as its unique and very helpful feature for PWAs that's using ionic 2.

**Comment by FelschR** [comment] 2017-06-01 16:55
This is a must have for desktop and tablets!
