### ISSUE TITLE
feat: Prevent leaving page

### ISSUE THREAD

**Issue by MatanYed** [driftyco/ionic#7688] opened 2016-08-12 16:24 UTC
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I need option to prevent leaving some page, in ionViewWillLeave function need to put "event" or something and then preventDefault...</span>

<span is-issue-template></span>

**Comment by alexbainbridge** [comment] 2016-08-12 17:55
See https://github.com/driftyco/ionic/issues/6623

**Comment by jgw96** [comment] 2016-08-12 18:11
Hello @MatanYed ! I am going to be closing this as a duplicate of the issue @alexbainbridge linked to above. Thanks for using ionic! Oh and thanks @alexbainbridge !

**Closed by jgw96** 2016-08-12 18:11 UTC
Labels: feature, v2
