### ISSUE TITLE
bug: Problem with the tab history stack

### ISSUE THREAD

**Issue by JeroendeVin** [driftyco/ionic#6581] opened 2016-05-19 17:04 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I've encountered a problem with the tabs navigation history stack, which I'm able to reproduce on the codepen example I found on your site:
http://codepen.io/ionic/pen/odqCz
How to reproduce:
1. On the "home" tab, click the "scientific facts" button.
2. Switch to the "about" tab
3. In the about tab, click the "tabs nav stack" button.
4. The "tabs" image is shown, but note that there's a "back" button ("< about").
5. Click the back button on this view
6. Switch back to the "home" tab. There the "banging your head.." view is still shown, with a "back" button ("< home"). Click this button to go back.
7. Now switch to the "About" tab again and click the "tabs nav stack" button again: the back button ("< about") is gone.

I've posted the same issue (with a very basic project based on the "tabs" default template) on stackoverflow:
https://stackoverflow.com/questions/37303612/ionic-back-button-disappears-history-is-null-on-list-details-in-tabs</span>

<span is-issue-template></span>

**Comment by jgw96** [comment] 2016-05-19 21:32
Hello! Thanks for opening an issue with us! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/6527. Would you mind posting the information you have on that issue? Thanks for using Ionic!

**Closed by jgw96** 2016-05-19 21:32 UTC
Labels: navigation, v2
