### ISSUE TITLE
[ionic2][bug] - Content - Tries to tweak scroll element style even if its not there

### ISSUE THREAD

**Issue by graphefruit** [driftyco/ionic#10220] opened 2017-01-28 10:52 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

If you're using the refresher component to refresh data from server, and you are leaving the page while the refresher shows up, the issue gets thrown:
```
TypeError: Cannot read property 'style' of null
    at http://localhost:8100/build/main.js:12097:29
    at dispatch (http://localhost:8100/build/main.js:6761:9)
    at DomController._flush (http://localhost:8100/build/main.js:6731:13)
    at rafCallback (http://localhost:8100/build/main.js:6724:22)
 ```
This occurs because: `_refresher.complete()` call.
The function here tries to set the `style`, but the refresher component is already destroyed.

**Expected behavior:**

No exception, refresher gets destroyed on page leave.

**Steps to reproduce:**
1. Build a page with a refresher 
2. Swipe down to refresh
3. Now change page before you get data (or you take a dead end)
4. Error will pop up

**Related code:**
My code looks like:

```
public refreshFeed(_refresher: any) {
    this.__loadFeed(true).subscribe((data) => {
      this.__finalizeData(data);
      _refresher.complete();
    }, (err)=> {
      _refresher.complete();
    });
  }
```

Maybe this issue is because I'm not unsubscribing from my event aswell, but the refresher should not crash in my opinion at all - even when getting a callback.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.6
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.7.0
Xcode version: Not installed
```

Greetings 
Graphefruit

**Comment by jgw96** [comment] 2017-01-30 15:45
Thanks for opening an issue with us, we will take a look into this.

**Comment by graphefruit** [comment] 2017-02-08 09:07
I'd like to extend this bug:
If you have a slow internet connection and you change the page, while the refresher is loading, and went back, the refresher is still displaying and the user can't start a new refreshment.

The workaround is to store the refresher object
```
  ionViewWillLeave() {

    if ( this.refresher != null){
      this.refresher.complete();
    }
  }
```
But then the problem occures if you try to refresh again, the refresher will close instantly, after second try the refresher works normaly again (strange behaviour)

**Comment by jgw96** [comment] 2017-02-08 19:10
@graphefruit Would you be able to share a repo or plunker i can use to reproduce this issue? Unfortunately i cannot reproduce in my testing.

**Comment by graphefruit** [comment] 2017-02-09 09:30
Hello @jgw96  - I've found somewhere a Plnkr which I used, hopefully this one is ok for you:
First sample style issue: http://plnkr.co/edit/0BLOjhT8O2bz04tOSXNP
1. Pull down to refresh
2. Click now on "Push Page 2" 
3. Wait about 6 seconds and you'll see the style error in console.

While I created this plnkr I saw that this issue just exists if you're navigating from "root" to a new "root" page, if you push any pages then it work.

Second sample refresher closes instant: http://plnkr.co/edit/MXLm9GW2PBWhgB1BjZQA
1. Pull down to refresh
2. Click now on "Push Page 2"
3. Wait about 6 seconds and you'll see that "data loading finished"
4. Go back
5. Pull down to refresh again
6. The refresher will close instant after pulling down
6.1. But the refresher event will get fired (look console)
7. Pull down again - normal behaviour

Greetings
Graphefruit

**Comment by jgw96** [comment] 2017-02-09 16:00
Awesome, thanks for the detailed examples @graphefruit ! This is definitely helpful.

**Comment by jgw96** [comment] 2017-02-09 16:30
Hello @graphefruit so unfortunately I still cant seem to reproduce the "style error" I am following your steps perfectly in Desktop Chrome 56 (the latest stable version). What browser are you running into this issue on? Regarding the second bug, I can reproduce it with the plunker you made. Thanks!

**Comment by graphefruit** [comment] 2017-02-09 17:51
Hi @jgw96  sadly the plnkr reverted some changes (seems like I messed something up sorry)
I've created a new one now: http://plnkr.co/edit/tI8BSLQVsKUCPmVhwyOM?p=preview
1. Pull down to refresh
2. Click now on "Push Page 2"
3. Wait about 6 seconds and you'll see the style error in console.
```
Uncaught TypeError: Cannot read property 'style' of null
    at eval (content.ts:492)
    at dispatch (dom-controller.ts:154)
    at DomController._flush (dom-controller.ts:119)
    at rafCallback (dom-controller.ts:110)
```
Greetings
PS: I'm using Chrome 56 aswell.

**Comment by jgw96** [comment] 2017-02-09 18:45
ahhhhh perfect! Now i can reproduce this one as well. Plnkr is a little weird sometimes about saving changes.

**Comment by jgw96** [comment] 2017-02-13 17:42
Closing this issue as the above PR fixed it. Thanks!

**Closed by jgw96** 2017-02-13 17:42 UTC
Labels: v2
