### ISSUE TITLE
Content not receiving scroll event

### ISSUE THREAD

**Issue by mattbryan9** [driftyco/ionic#10179] opened 2017-01-26 09:42 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[] feature request
[] support request

**Current behavior:**

Content is not receiving the scroll event. Since the setters for many of its properties rely on this event to assign their values, the result is that while, for example `getContentDimensions` will successfully give us the correct `contentHeight` and `scrollTop` in the object it returns, we can't use `scrollToTop` because the instance members `scrollTop` and `contentHeight` are never set. When I put breakpoints in scroll-view.ts's `scrollCallback`, they are never hit, and when I add callbacks to `ionScroll` they are never called.

**Expected behavior:**

Content should always receive the scroll event when its contents are scrolled.

**Steps to reproduce:**

The Content that we have the issue with is a fullscreen Content inside of a Slider inside of a Content. However, when I try to reproduce the issue I cannot.

**Related code:**

This is the plunker I tried to reproduce the issue in--unsuccessfully, unfortunately.
http://plnkr.co/edit/9yHRflqnzFDWaXH3E5Fc?p=preview

**Other information:**

I can't be sure that this isn't a bug on our end since I'm unable to reproduce it, but since I can see that the Content has been scrolled when I use `getContentDimensions` it should definitely be receiving scroll events from the HTML. Unfortunately, I can't manually change the values of the properties I need to set to make `scrollToTop` work.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.6
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
ios-deploy version: 1.9.0
ios-sim version: 5.0.11
OS: macOS Sierra
Node Version: v4.5.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by lumitor2** [comment] 2017-01-26 10:02
I think I have similar problem after upgrade to 2.0.0. final. There is uncaught error which is called on scroll event.
`
Uncaught TypeError: Cannot read property 'ev' of null
    at Content._readDimensions (content.js:525)
    at dispatch (dom-controller.js:128)
    at DomController._flush (dom-controller.js:102)
    at rafCallback (dom-controller.js:95)
`
It's because this._scroll is not initialized in content.js file on line 525:
`
var scrollEvent = this._scroll.ev;
`
Maybe it's connected.

**Comment by ericcf** [comment] 2017-01-26 12:42
I'm seeing something similar in 2.0.0 final. I've set up a new app using the "blank" template, and followed the testing setup suggested by Josh Moroney in his blog. After running and successfully completing a single Component test using the `--single-run` flag with karma, I see:

```console
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  TypeError: null is not an object (evaluating 'this._scroll.ev')
  at webpack:///~/ionic-angular/components/content/content.js:525:0 <- src/test.ts:10518
```

I can see the same error in the console when I run the tests in Chrome.

**Comment by jgw96** [comment] 2017-01-26 19:22
Hello all! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/10186. Thanks for using Ionic!

**Closed by jgw96** 2017-01-26 19:22 UTC
