### ISSUE TITLE
ion-content scroll not working on mac laptop

### ISSUE THREAD

**Issue by awebdeveloper** [driftyco/ionic#5748] opened 2016-03-07 09:58 UTC
#### Short description of the problem:
Scroll on ion-content via trackpad doesn't work. I am on native scroll.  
Scroll works on 1.2.0 but not on 1.2.4
Not sure if it happens on other desktop and laptops.

#### What behavior are you expecting?
Scroll should work 

**Steps to reproduce:**
1.  Create a ion-content
2.  add data into this to cause scroll
3. now scroll

**Ionic Version**: 1.2.4

**Browser & Operating System**: Chrome on Mac 

**Run `ionic info` from terminal/cmd prompt:**

```
Cordova CLI: 5.2.0
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.9.1
Ionic CLI Version: 1.6.4
Ionic App Lib Version: 0.3.8
ios-deploy version: 1.7.0
ios-sim version: 3.1.1
OS: Mac OS X Yosemite
Node Version: v0.12.0
Xcode version: Xcode 7.2.1 Build version 7C1002
```

**Comment by gsanjeevkumar** [comment] 2016-03-07 14:12
I am using a closer to latest version see blow, but have the similar problem. Am I doing anything wrong ? @awebdeveloper did you get a solution yet. Did you try upgrading ?

> Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.2 
ios-sim version: 5.0.3 
OS: Mac OS X El Capitan
Node Version: v5.1.0
Xcode version: Xcode 7.2.1 Build version 7C1002

**Comment by awebdeveloper** [comment] 2016-04-04 14:35
nope hope anyone else has some update

**Comment by jgw96** [comment] 2016-04-04 14:39
Hello @awebdeveloper , im having an issue reproducing this on my Macbook. I am using chrome canary and scrolling seems to work fine for me. Would you mind creating a plunkr of your exact code? Im currently just following your steps you gave above with a simple ion-content with a list of random things in it, but it seems to scroll fine for me.

**Comment by jgw96** [comment] 2016-04-11 16:01
As it has been a little while since there was any activity on this issue I will be closing it for now, please feel free to reply if you are still experiencing this issue though!

**Closed by jgw96** 2016-04-11 16:01 UTC
Labels: needs reply, platform:ios, v1

**Comment by awebdeveloper** [comment] 2016-05-18 14:03
hi @jgw96 sorry for late reply.. looks like it's not entirely a ionic issue but may be with the way i have implemented it. I will share you the url and the login details if you could look into this. 

Or Atleast suggest me way to debug it

**Comment by jgw96** [comment] 2016-05-18 14:37
Hey, no problem! Actually, if you could just create a minimal example in a plunker or codepen demonstrating the issue then that would be great! Minimal examples are much easier to debug than a full blown app.

**Comment by awebdeveloper** [comment] 2016-05-18 18:35
sure. Looks like cards with overflow in body cause issue. I will share a plunkr soon
