### ISSUE TITLE
Add more Explicit Column Percentage Attributes to Grid

### ISSUE THREAD

**Issue by Iyashu5040** [driftyco/ionic#8825] opened 2016-10-20 16:27 UTC
Short description of the problem:
There are very few explicit column percentage attributes available for use with the Grid component.

What behaviour are you expecting?
I'm expecting at least all multiples of 20 and maybe even 10 to be available. Eg. width-20, width-40, width-60 and width-80. This would greatly increase the flexibility and usability of the Grid component.

I want to create three columns of 20-40-20 each but the width-40 attribute doesn't exist.

**Comment by brandyscarney** [comment] 2017-02-02 23:25
Thanks for the issue, I'm going to close this as a duplicate of https://github.com/driftyco/ionic/issues/7508

**Closed by brandyscarney** 2017-02-02 23:25 UTC
Labels: enhancement, v2
