### ISSUE TITLE
Multiple overlays of different types shown at once don't work correctly

### ISSUE THREAD

**Issue by Kobzol** [driftyco/ionic#7565] opened 2016-08-05 22:34 UTC
#### Short description of the problem:
If I show a toast and after its present completes I show an action sheet or loading, the second view will not work correctly (action sheet buttons will not close it and the loading will not close after its duration completes).

#### What behavior are you expecting?
That there can be multiple different overlays shown at the same time.

**Steps to reproduce:**
1. Create and show a Toast
2. Await the toast's present promise and then present an action sheet or loading

```javascript
let t = toastCtrl.create({ message: "test", duration: 2000 });
t.present().then(() => {
   let view = actionSheetCtrl.create({ title: "test", buttons: ["Btn 1", "Btn 2"] });
   // or let view = loadingCtrl.create({ content: "text", duration: 1000 });
   view.present();
});
```

**Which Ionic Version?** 1.x or 2.x
2.x (beta 11)

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.35
Ionic App Lib Version: 2.0.0-beta.19
OS:
Node Version: v6.2.0

**Comment by alexbainbridge** [comment] 2016-08-08 07:43
FYI When testing that this is addressed, I put two example situations (with code) on #7578 (that is now closed as a duplicate of this one)

Specifically toast related ........ toast then modal during a duration phase, toast the backbutton during a duration phase

Thanks!

**Comment by windwp** [comment] 2016-08-10 07:46
+1

**Comment by theteedog** [comment] 2016-08-10 07:54
+1

**Comment by intitec** [comment] 2016-08-10 11:55
+1 . Toast -> Alert.

**Comment by AcademyLime** [comment] 2016-08-10 14:05
+1

**Comment by jgw96** [comment] 2016-08-10 20:07
Note to self: <img width="754" alt="captura de tela 2016-08-06 as 23 12 46" src="https://cloud.githubusercontent.com/assets/70573/17460055/6af4db82-5c2b-11e6-9878-f1c733aefb6d.png">

**Comment by jgw96** [comment] 2016-08-10 20:08
@alexbainbridge would you mind trying `enableProdMode()` and seeing if that fixes the issue for you?

**Comment by alexbainbridge** [comment] 2016-08-10 20:19
@jgw96 Hey Justin

OK - so this is interesting. Production mode fixes toast then (while showing) backbutton / menu button (showing side menu). I have double checked this is broken when NOT production mode.

However toast showing (during a duration showing phase) - and then firing a modal..... that is still broken, in production mode.

So partially addressed - and maybe a hint as to where the problem is....... AND I guess I can manually dismiss the toast before showing any modals...... maybe!

**Comment by jgw96** [comment] 2016-08-10 20:20
@alexbainbridge Thanks for testing! Does opening a toast and then firing a modal cause the same error as the screenshot i posted above?

**Comment by jgw96** [comment] 2016-08-10 20:24
note to self: regarding the toast + other overlay component issue ive narrowed it down to changing an attribute on `ion-backdrop`.

**Comment by alexbainbridge** [comment] 2016-08-10 20:26
I have never got any errors in the console log for this..... just a showing/hiding what looks like in old school development is an infinite loop..... and a locked up UI

Is there any additional console logging mode you turn on ? I generally get errors when there is one, but not sure if you have an additional mode

**Comment by jgw96** [comment] 2016-08-10 20:42
@alexbainbridge Ahh, ok i think i know what the issue is their and its not gonna log anything to the console. Could you try setting `dismissOnPageChange` to true on your toast?
```
 let toast = this.toastCtrl.create({
   dismissOnPageChange: true
 })
```

**Comment by alexbainbridge** [comment] 2016-08-10 20:44
@jgw96 Sadly already do

I use this

`let toast = this.toast.create({ message: 'Saved successfully', dismissOnPageChange : true, duration: 1500 });`

**Comment by alexbainbridge** [comment] 2016-08-10 20:57
To clarify, I only get the issue during the duration phase (re code above), after the toast has self dismissed, all is good with navigation to modals etc

**Comment by jgw96** [comment] 2016-08-10 21:46
@alexbainbridge so the issue your describing is actually a separate issue that i am going to look into but the good news is that this issue is being fixed as we speak 😄 . I was able to track down the issue to a binding change issue and one of my teammates is working up a fix right now. Thanks for all the help debugging!

**Comment by AcademyLime** [comment] 2016-08-10 22:07
Thanks for looking into this. I was fighting with this same issue. :) https://github.com/AcademyLime/demo

**Comment by jgw96** [comment] 2016-08-11 15:36
Hello all! Happy to confirm that this has been fixed and will be in the beta.12 release!

**Closed by jgw96** 2016-08-11 15:36 UTC
Labels: v2

**Comment by ashutoshagg** [comment] 2016-08-12 07:15
@jgw96  We are facing the same issue after upgrading to Beta 11. Can we get any intermediate solution before Beta 12 is rolled out?
Thanks

**Comment by rodriguesgm** [comment] 2016-08-20 01:49
it would be good to have some workaround for beta11

**Comment by cwoll87** [comment] 2016-08-23 11:31
+1

**Comment by sergeyrolich** [comment] 2016-09-01 05:20
Someone found a possible temporary fix?

**Comment by devillex** [comment] 2016-09-13 09:05
Thanks for the confirmation @jgw96!

This does however seem like it will prevent a lot of users from upgrading to Ionic 2 Beta 11, or am I missing something?

**Comment by danielehrhardt** [comment] 2016-09-16 15:00
+1
no temp fix?

**Comment by windwp** [comment] 2016-09-17 02:36
if someone looking for a temp fix? just hide previous ViewController and add delay for next ViewController display

**Comment by saurabhvyas** [comment] 2016-09-25 16:27
+1
