### ISSUE TITLE
ionic modal dialog contents can be rendered outside the dialog box under certain conditions

### ISSUE THREAD

**Issue by hafezash** [driftyco/ionic#2577] opened 2014-11-18 19:54 UTC
- showing an ionic modal using fromTemplateUrl()
- template html contains a form, with a few input fields and a button
- overflow-scroll="false" on the ion-content component in the ion-modal-view
- when you click in one of the input fields, so that the keyboard is displayed, you can then drag-scroll the contents of the dialog up and outside the bounding box of the dialog. note - only when the keyboard is showing.

![ios simulator screen shot nov 18 2014 2 48 50 pm](https://cloud.githubusercontent.com/assets/7420357/5094897/ceb8726a-6f32-11e4-9111-ec38e0c82f14.png)

**Comment by AgDude** [comment] 2015-02-07 13:32
At a glance, this appears to be a duplicate of #2212

**Comment by mhartington** [comment] 2015-04-16 20:52
Fixed by https://github.com/driftyco/ionic/commit/1a4e36bcdcc395dbb395b7c72e7332dab330df15

**Closed by mhartington** 2015-04-16 20:52 UTC
Labels: modals
