### ISSUE TITLE
Other options of ion-slides after deprecating the options input properties

### ISSUE THREAD

**Issue by mmirzaee** [driftyco/ionic#9957] opened 2017-01-11 14:33 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Description:**
It seems options are now depricated in ion-slides (in nightly build of ionic 2) and just some of options like effect, pager, ... are available by passing it through input properties !   
what if we need to use slidesPerView, centeredSlides, ... and other options?
how can we handle it ?

my ionic info :
```
Cordova CLI: 6.3.1
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: OS X El Capitan
Node Version: v5.5.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment] 2017-01-11 17:01
Hello, thanks for using Ionic! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/9933.

**Closed by jgw96** 2017-01-11 17:01 UTC
