### ISSUE TITLE
Keyboard overlaps focused input

### ISSUE THREAD

**Issue by jalef** [driftyco/ionic#7402] opened 2016-07-22 11:39 UTC
#### Short description of the problem:
An edited input is overlapped by the keyboard that appears when edit starts.

#### What behavior are you expecting?
I expect that the input scrolls on top, or somewhere over the keyboard, so it is visible

**Steps to reproduce:**
1. Create a page with an input situated in a position above the height of the keyboard
2. Run it on android
3. Try to edit the input. 

**Which Ionic Version?** 1.x or 2.x

http://plnkr.co/edit/GFOUnEeitVpF6o8GSAxU?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS:
Node Version: v4.4.4

**Comment by jgw96** [comment] 2016-07-22 14:32
Hello, thanks for opening am issue with us! I will be closing this issue as a duplicate of https://github.com/driftyco/ionic/issues/7149. Thanks for using Ionic!

**Closed by jgw96** 2016-07-22 14:32 UTC
Labels: keyboard, platform:android

**Comment by masimakopoulos** [comment] 2016-07-22 21:00
@jgw96 is it the same issue? Because I am having the same issue, but not only on fields inside ion-footer as #7149 mentions, but any input field that is displayed where keyboard will show up. And since this is more generic than the other, I think it should receive some attention as well.

**Comment by jalef** [comment] 2016-07-25 09:25
@jgw96 Hello again
I agree with @masimakopoulos . 
Moreover,I would like to point out that  #7149 is labeled "platform:ios"

**Comment by radix21** [comment] 2017-10-24 17:19
It's happening the same when you put a form with ion-input inside of a ion-slide, when the input is touched then a padding-bottom from .scroll-content class overlaps the form and inputs.
