### ISSUE TITLE
Ionic 2/Beta 11: navPush generates "No directive found..." error

### ISSUE THREAD

**Issue by joshgarwood** [driftyco/ionic#7567] opened 2016-08-06 03:51 UTC
#### Short description of the problem:
After upgrading to Beta 11, I am getting an error when trying to navigate from one page to another using navPush from inside a component.  The error states: ```No Directive annotation found on function History(tripsSerivce, loading) ```  Where History is the page I'm trying to navigate to.  

This worked without an issue in Beta 10.  As well, this also works in Beta 11 if I instead use a (click) event, ie: 
```<a (click)="gotoPage()">go to page</a>
...
gotoPage() {
    this.nav.push(History);
}```

#### What behavior are you expecting?
I would expect to successfully navigate to the provided page.

**Steps to reproduce:**
1. Create a directive.  It can be as simple as possible.
2. In that directive, use navPush to navigate to another page
3. Note the error as described in above.

**Other information:** Error stacktrace:
zone.js:260 Uncaught EXCEPTION: Error in build/pages/trips/directives/trip.template.html:21:4
ORIGINAL EXCEPTION: No Directive annotation found on function History(tripsSerivce, loading) {
ORIGINAL STACKTRACE:
Error: No Directive annotation found on function History(tripsSerivce, loading) {
    at new BaseException (http://localhost:8100/build/js/app.bundle.js:4700:23)
    at DirectiveResolver.resolve (http://localhost:8100/build/js/app.bundle.js:11987:15)
    at CompileMetadataResolver.getDirectiveMetadata (http://localhost:8100/build/js/app.bundle.js:16893:51)
    at RuntimeCompiler._getCompiledHostTemplate (http://localhost:8100/build/js/app.bundle.js:20987:51)
    at RuntimeCompiler._getTransitiveCompiledTemplates (http://localhost:8100/build/js/app.bundle.js:21020:38)
    at RuntimeCompiler.compileComponentAsync (http://localhost:8100/build/js/app.bundle.js:20946:30)
    at RuntimeCompiler.resolveComponent (http://localhost:8100/build/js/app.bundle.js:20942:21)
    at Tab.NavControllerBase.loadPage (http://localhost:8100/build/js/app.bundle.js:67074:24)
    at Tab.loadPage (http://localhost:8100/build/js/app.bundle.js:78628:35)
    at Tab.NavControllerBase._render (http://localhost:8100/build/js/app.bundle.js:66725:18)
ERROR CONTEXT:
[object Object]


**Which Ionic Version?** Ionic 2, Beta 11

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
OS: Windows 8.1
Node Version: v0.12.2

**Comment by taljacobson** [comment] 2016-08-07 16:10
**Short description of the problem:**
having the same issue..
while trying to navigate to a subpage it would load the component logic but the view wont change,
a second click is needed for the template to change.
`this.navCtrl.push(WeatherComponent)`,
if i change the code to `this.navCtrl.setRoot(WeatherComponent)`,
logic and view are loaded on first click,
but history is lost

**home.ts - first page**
```javascript
import {Component } from '@angular/core';
import {NavController} from 'ionic-angular';
import { WeatherComponent } from "../weather/weather.component";

@Component({
  templateUrl: 'build/pages/home/home.html'
})
export class HomePage {
  constructor(private navCtrl: NavController) {
  }
  gotoWeather(){
    this.navCtrl.push(WeatherComponent) 
  }
}
```
**home.html**
```html
<ion-header>
  <ion-navbar>
    <ion-title>Home</ion-title>
  </ion-navbar>
</ion-header>
<ion-content padding class="home">
  <h2>Welcome to Ionic!</h2>
  <p>
    This starter project comes with simple tabs-based layout for apps
    that are going to primarily use a Tabbed UI.
  </p>
  <button type="button" block name="button" (click)="gotoWeather()">gotoWeather</button>
</ion-content>
```
**weather.component.ts**
```javascript
import { Component} from '@angular/core';
import {NavController} from 'ionic-angular';

@Component({
    selector: 'weather',
    template: 'templateUrl'
})
export class WeatherComponent {
  constructor(private navCtrl: NavController
  ) {
    console.log('component loaded...')
  }
}
```
**What behavior are you expecting?**

I would expect to successfully navigate to the provided page.

**Steps to reproduce:**
1. Create a directive. It can be as simple as possible.
2. In that directive, use navPush to navigate to another page
3. Note the error as described in above


**Which Ionic Version?** Ionic 2, Beta 11

Run `ionic info` from terminal/cmd prompt: (paste output below

Cordova CLI: 6.3.0
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.36
Ionic App Lib Version: 2.0.0-beta.19
OS: windows 10
Node Version: v4.4.7

**Comment by syclone** [comment] 2016-08-07 19:42
Same issue as explained above.

**Comment by jgw96** [comment] 2016-08-11 18:11
Hello all! Would anybody mind posting a repo that contains a very minimal example of this issue? Thanks for using Ionic!

**Comment by syclone** [comment] 2016-08-11 20:51
I noticed the error only occurred when the **[navPush]** is used with params. So, that led me to believe the issue was with how the params was being passed. In Beta 10 it was possible to pass params using **[navPush]**. I fixed this issue by using the directives for push and params separately.

Before, I had something like this: `<button [navPush]="[pushPage, {params}]">Go</button>`

Now, I changed it to `<button [navPush]="pushPage" [navParams]="params">Go</button>`

**Comment by taljacobson** [comment] 2016-08-12 16:02
found out my issue was with the subpage component metadata, 
this might be a bug or by design but if you place a component metedata selector, ie:
```javascript
@Component({
  selector: 'otherpage',
  templateUrl: 'build/pages/otherpage/otherpage.html'
})
```

without the selector it works like intended

 and try to redirect to it with `nav.push(componentWIthSelctor)` , it would not change the view, but will start the component.. 

https://github.com/taljacobson/ionicnaverror/tree/master

**Comment by jgw96** [comment] 2016-08-12 16:17
Hello @syclone ! So as our [docs](http://ionicframework.com/docs/v2/api/components/nav/NavPush/) show that is the correct way to use NavPush. While your original way of doing it worked in the past, it probably shouldn't have, sorry about that! @taljacobson Ahh ok so that would definitely be the issue. Components that are used as a page in Ionic 2 should not have a selector on them. SInce it looks like this issue has been solved for you all, and it has been 7 days since the op has posted i will be closing this issue. Thanks to everyone for using Ionic!

**Closed by jgw96** 2016-08-12 16:17 UTC
Labels: needs reply, v2
