### ISSUE TITLE
Losing characters in ion-input 

### ISSUE THREAD

**Issue by aspitrine** [driftyco/ionic#6060] opened 2016-04-06 15:19 UTC
#### Short description of the problem:
When I tap in ion-input quickly, I lost some characters.
![bug ionic](https://cloud.githubusercontent.com/assets/3731837/14321779/e177687c-fc1a-11e5-950a-4e8df39644bb.gif)

**Steps to reproduce:**
1. Tap inside ion-input quickly

```
<ion-input [(ngModel)]="models" type="text"></ion-input>
```

On Ionic 2.x

Your system information:

Cordova CLI: 6.0.0
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
ios-deploy version: 1.8.5
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v5.10.0
Xcode version: Xcode 7.3 Build version 7D175

**Comment by 0xE282B0** [comment] 2016-04-06 20:17
I've got the same Problem. It looks like the input switches between two values. If you use only two keys it looks like this:
![screen](https://cloud.githubusercontent.com/assets/4034494/14331135/33a5ff40-fc44-11e5-99ee-1ba1a1bed4a8.gif)

I'm using  ionic-angular 2.0.0-beta.3 too.
Any ideas?

**Comment by jgw96** [comment] 2016-04-06 20:30
Hello! Thanks for opening an issue with us! Im having an issue reproducing this. Would you guys mind making a codepen i could use to repro this issue? Thanks ! Also are you seeing this just on android? or in chrome too?

**Comment by jgw96** [comment] 2016-04-07 02:57
Does this only happen for you guys when an input has an `[(ngModel)]` on it ?

**Comment by aspitrine** [comment] 2016-04-07 08:31
It's a performance problem
http://plnkr.co/edit/yoYEOn6P4dnS31AMECKC
In device browser, we need less data to reproduce that.

**Comment by jgw96** [comment] 2016-04-07 14:31
Thanks for the plnkr! So I was able to reproduce this and it definitely seems to be a handy cap with the new ngModel. Also, by the way. If your binding to huge amounts of data like that, your probably trying to search through that array right? In that case you should use our <ion-searchbar>.

**Comment by aspitrine** [comment] 2016-04-07 14:40
The new ngModel works great with simple input
http://plnkr.co/edit/USqtSaWz8WPJNFRRmgwH?p=info

**Comment by jgw96** [comment] 2016-04-12 18:21
Closing this as a dupe of #5942 Thanks again!

**Closed by jgw96** 2016-04-12 18:21 UTC
Labels: needs reply, performance, v2
