### ISSUE TITLE
perf: Video controls are completely ignored. Provided solutions don't work.

### ISSUE THREAD

**Issue by dano2** [driftyco/ionic#3738] opened 2015-05-15 01:10 UTC
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.2</span>  <span ionic-webview>webview</span>

<span ionic-description>I'm trying to play (captured) video in a video tag. The play button and full screen button are ignored when tapped. I can only slide the slider, but can't see any video at all. How do I get the controls to work?

I followed the solution provided at the following link, but there's no change. Note the overflow-scroll="true" data-tap-disable="true" in the video tag.
https://github.com/driftyco/ionic/issues/1626

	<ion-view view-title="Home" class="pane" nav-view="active" style="-webkit-transition: 0ms; transition: 0ms; -webkit-transform: translate3d(0%, 0px, 0px);">
	    <ion-content padding="true" class="scroll-content ionic-scroll  has-header has-tabs-top">
	        <div class="scroll padding" style="-webkit-transform: translate3d(0px, -201px, 0px) scale(1);">
	        
	            
	            <video id="theVideo" width="240" height="160"  overflow-scroll="true" data-tap-disable="true" controls>
	                <source id="theSource" src="file:/storage/emulated/0/DCIM/100MEDIA/VIDEO0060.3gp">
	            </video>
	            

	        </div>
	        <div class="scroll-bar scroll-bar-v">
	            <div class="scroll-bar-indicator scroll-bar-fade-out" style="-webkit-transform: translate3d(0px, 134px, 0px) scaleY(1); height: 74px;"></div>
	        </div>
	    </ion-content>
	</ion-view></span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-05-15 01:10
Greetings @dano2!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3738). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3738)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment] 2015-05-15 15:53
Is this something you only see on specific versions of Android? I'm having trouble reproducing the issue, could you recreate this in a codepen?

**Comment by dano2** [comment] 2015-05-15 17:20
Hi perry. I'm having the issue on android 4.2. It seems the video controls are frozen if the video tag is placed within ion-content. The only solution that has worked for me is to put the video in an iframe, but that will require some session management pain. 

I followed the solution provided at the following in https://github.com/driftyco/ionic/issues/1626 , but there's no change. Note the overflow-scroll="true" data-tap-disable="true" in the video tag. Do you have any other suggestions by chance? 

Thanks

**Comment by perrygovier** [comment] 2015-05-18 16:01
Hmm, I'm not able to reproduce the problem. Is it a project you're able to share?

**Comment by Ionitron** [comment] 2015-06-17 16:22
Greetings @dano2!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment] 2015-06-17 16:22
Greetings @dano2!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-06-17 16:22 UTC
Labels: ionitron:closed
