### ISSUE TITLE
Fix Pull to Refresh (ion-refresher)

### ISSUE THREAD

**Issue by matiboy** [driftyco/ionic#5207] opened 2016-01-26 23:30 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>- SASS file for ion-refresher is not included
- Swipe events don't seem to trigger (tested on iOS emulator)

Followed the documentation here
http://ionicframework.com/docs/v2/api/components/scroll/Refresher/

Thanks!</span>

<span is-issue-template></span>

**Comment by brandyscarney** [comment] 2016-01-27 00:00
@adamdbradley `canOverscroll` was being set to `false` by default so PTR was never able to run, but I see some flickering on iOS and the `complete` function isn't being recognized.

**Comment by matiboy** [comment] 2016-01-27 00:32
@brandyscarney Thank you for being so responsive!
Related but different issue: in the docs, the `refresh` event seems to receive `$event` and `refresher`
```
<ion-refresher (starting)="doStarting()"
                 (refresh)="doRefresh($event, refresher)"
                 (pulling)="doPulling($event, amt)">
  </ion-refresher>
```

but it seems that only `refresher` is actually passed to `doRefresh`

**Comment by andrefedalto** [comment] 2016-02-09 10:59
I was having some unexpected behaviour with the pull to refresh so I tried the exact example of the docs in a new clean ionic2 project (Hello Ionic) running alpha56. I still have the following bugs:

1) doStarting() method is not being called. By the example from the docs I'd expect to see the "Pull started!" in the console but it never shows up.

2) the refresher (icon-refreshing) won't stay in the screen. As soon as the pull is released, the arrow icon changes to the ionic icon and disappear. Is this the expected behaviour? Or should the icon-refreshing be there until the .complete() method is called?

3) also as mentioned before (or in another issue), if you have a long list (bigger than the screen) and scroll down, when scrolling up the refresh is triggered. It should be trigged only on pulling from the top of your content.

Hope this helps :)

**Comment by sb8244** [comment] 2016-02-15 06:40
I made a duplicate, oops https://github.com/driftyco/ionic/issues/5456

Addressing @andrefedalto above. I've done some digging as well, and confirmed 1&2:

1. The code for activation has the `next()` commented out. Removing it triggers start:

```
    Refresher.prototype.activate = function () {
        //this.ele.classList.add('active');
        this.isActive = true;
        //this.starting.next();
    };
```

2. `setScrollLock` is being called which calls deactivate.

From what I see, It looks like this bit of code is being implemented still, although it comes off from the documentation as it working.

**Comment by brandyscarney** [comment] 2016-02-17 17:01
I added a few fixes for emitting events, including to emit the starting event now. These fixes should get in with the beta.1 release. Going to look into the other issues for the beta.2 release. Let me know if you find any more issues before then! :smile:

**Comment by brandyscarney** [comment] 2016-02-17 17:29
The event `(starting)` has been renamed to `(start)` as well.

**Comment by wangqianbo** [comment] 2016-02-18 08:46
`ptrThreshold` is set to `0` in class `Refresher`,  I think this is the reason  of the issue 2) which was addressed by @andrefedalto . 
`if (this.lastOverscroll > this.ptrThreshold) {
        this.startRefresh();
        this.scrollTo(this.ptrThreshold, this.scrollTime);`
Should the Refresher Component expose enough  attributes so we can control the feature of it?

**Comment by brandyscarney** [comment] 2016-02-22 23:00
Fixed most of the existing bugs:

1. Refresher will now display until the complete function is called
2. `start` event is now being emitted
3. API docs updated to show use cases
4. Sass variables were added to customize 

Remaining issues:

1. If you scroll down in the list and start to drag back up it pops to the top of the list, on release it will go back to your previous position
2. https://github.com/driftyco/ionic/issues/5485
3. https://github.com/driftyco/ionic/issues/5550

**Comment by adamdbradley** [comment] 2016-02-28 02:40
All of these have been addressed in this refactor: https://github.com/driftyco/ionic/commit/91df5f97eef9ed1d261e6642c2d9ab7e8cc4063c

Thanks

**Closed** 2016-03-01 16:50 UTC
Labels: bug, v2

**Comment by Barathwaja** [comment] 2016-09-02 03:06
#7914 Pull to refresh blank in v2

**Comment by jayzyaj** [comment] 2018-07-18 06:47
Hi there. I am having a problem with ion-slides. This is the [link](https://github.com/ionic-team/ionic/issues/14796)
