### ISSUE TITLE
Empty options in select element on Android 5.1

### ISSUE THREAD

**Issue by beylkhanovdamir** [driftyco/ionic#6024] opened 2016-04-02 14:04 UTC
Hi, I'm try to using default template for select list 
``
  <div class="list">
  <div class="item item-input item-select">
    <div class="input-label">
      Lightsaber
    </div>
    <select>
      <option>Blue</option>
      <option selected>Green</option>
      <option>Red</option>
    </select>
  </div>
  </div>
``
for testing on my tablet with Android 5.1
But in conclusion I see only empty options in select. See screenshot below 
![select](https://cloud.githubusercontent.com/assets/7656847/14226777/d3961b32-f8f4-11e5-91c3-ddcd185a791f.jpg)

How to fix this?

**Comment by jgw96** [comment] 2016-04-04 18:42
Hello! Thanks for opening an issue with us! Unfortunately, im having a little trouble reproducing this issue. I put your exact code into a fresh Ionic 1 tabs starter project and it seems to be working fine for me. I tested with these devices: Nexus 6 running Android N preview, Nexus 7 2013 running Android 6.0 and a Moto x 2014 running Android 5.1. Could you maybe make a repo or a codepen of your exact code so that i can use it to repro this issue ? Thanks!

**Comment by jgw96** [comment] 2016-04-11 16:02
As it has been a little while since there was any activity on this issue I will be closing it for now, please feel free to reply if you are still experiencing this issue though!

**Closed by jgw96** 2016-04-11 16:02 UTC
Labels: needs reply, platform:android, v1
