### ISSUE TITLE
Error with ionic serve

### ISSUE THREAD

**Issue by sveinl** [driftyco/ionic#6348] opened 2016-04-27 19:36 UTC
#### Short description of the problem:
When loading an app from ionic serve using parameter ?ionicplatform=ios (or android) you get an error:
`ReferenceError: ionic is not defined, http://localhost:8100/?ionicplatform=ios, Line: 90`

#### What behavior are you expecting?
No errors

**Steps to reproduce:**
1. create a new ionic app `ionic start test blank --v2 --ts`
2. Run ionic serve for that app `cd test`and `ionic serve`
3. Access the app in browser with parameter ?ionicplatform=ios
    `http://localhost:8100/?ionicplatform=ios`

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS: 
Node Version: v4.4.3

(The info seems to not see that my OS is Windows 10)

**Comment by jgw96** [comment] 2016-04-27 19:44
Hello! Thanks for opening an issue with us! I am going to be closing this as a dupe of https://github.com/driftyco/ionic-cli/issues/942 but feel free to comment on the other issue. Thanks!

**Closed by jgw96** 2016-04-27 19:44 UTC
Labels: platform:android, platform:ios
