### ISSUE TITLE
bug(input): readonly input trying to open the keyboard

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic#9608] opened 2016-12-12 21:41 UTC
**Ionic version:**  (check one with "x")
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
I have a screen which is meant to be read only. I use `ion-input`s to display the data, but I have set the `readonly` attribute on them. When pressing the `ion-input`, the keyboard tries to open and the screen moves around. 

Also not that having an `ion-icon` inside an `ion-item` with an `ion-input`, the icon click events do not fire.

Happens on both Android and iOS using the latest nightly.

![readonly issue](https://cloud.githubusercontent.com/assets/2852839/21117910/5036b132-c0c4-11e6-9c36-fb56b199a29b.gif)

**Related code:**

```
 <ion-item *ngIf='issue.Status === 2' class='service-provider'>
                        <ion-icon name='hammer' item-left></ion-icon>
                        <ion-label stacked>Assigned Service Provider</ion-label>
                        <ion-input class='first-input' type="text" readonly [value]='issue.ServiceProviderCompany'></ion-input>
                        <ion-input class='second-input' type="text" readonly [value]='issue.ServiceProviderContactPerson'></ion-input>
                        <ion-icon class="action-icon" name="mail" item-right (click)="sendMail(issue.ServiceProviderEmailAddress)"></ion-icon>
                        <ion-icon class="action-icon" name="call" item-right (click)="callNumber(issue.ServiceProviderContactNumber)"></ion-icon>
                    </ion-item>
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3-201612121605
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.9.0
ios-sim version: 5.0.10
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by jgw96** [comment] 2016-12-12 22:47
Hello, thanks for opening an issue with us! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/9070.

**Closed by jgw96** 2016-12-12 22:47 UTC
