### ISSUE TITLE
Tabs appear halfway down screen when cancelling searchbar on iOS

### ISSUE THREAD

**Issue by zmbc** [driftyco/ionic#7958] opened 2016-09-03 01:47 UTC
#### Short description of the problem:

I am having exactly [this](https://forum.ionicframework.com/t/search-bar-tabs-keyboard-ios-bug/44260) problem: after cancelling a search in an Ionic2 searchbar on a real iOS device, the tabs appear halfway down the screen (I think due to the keyboard).
#### What behavior are you expecting?

I expect the tabs to stay in the same place no matter what.

**Steps to reproduce:**
1. Have a searchbar in a tabbed app.
2. Open the app on an iOS device.
3. Cancel a search.

**Which Ionic Version?**
2

**Comment by jgw96** [comment] 2016-09-15 16:50
Hello, thanks for ope
Hello, thanks for opening an issue with us! Would you be able to provide a repo that demonstrates this issue? Thanks for using Ionic!

**Comment by zmbc** [comment] 2016-09-16 21:36
[Here's a repo.](https://github.com/zmbc/tabs-search-bug)

Pretty basic, it doesn't take much to reproduce this bug. Of course, you will need to view it on an actual iOS device to get the same keyboard behavior.

**Comment by zmbc** [comment] 2016-11-02 02:20
I'm still experiencing this on RC1, unfortunately.

**Comment by jgw96** [comment] 2016-11-02 04:14
Hello, thanks for the info. Unfortunately I cannot reproduce this issue at the moment, what version of iOS are you experiencing this issue on?

**Comment by netcell** [comment] 2016-11-02 04:21
I am also experiencing this on both ios 10.1 and 9.2, real device and emulator. When tap on the searchbar, the keyboard pops up all okay. When I tap cancel on the searchbar, the keyboard starts animated sliding down, showing the predictive bar, the tabs bar suddenly appears above the keyboard. When the keyboard completes its animation and disappear, the tabs bar returns to the bottom of the screen. I will provide a video.

**Comment by jgw96** [comment] 2016-11-02 15:42
@netcell Would you mind testing with our [conference app demo](https://github.com/driftyco/ionic-conference-app) and seeing if you get the same results? This is the app im testing with on iOS 10 and I cannot seem to reproduce the issue.

**Comment by jgw96** [comment] 2016-11-02 15:42
Oh, and a video would be great if possible? Thanks!

**Comment by netcell** [comment] 2016-11-02 18:54
Ok sure I will. Thank you.

**Comment by netcell** [comment] 2016-11-02 19:52
I don't see the same result on your conference app demo.

However, I do experience the problem with [this repo](https://github.com/netcell/Ionic2TabsKeyboardIssue) which is created by:
1. Create a project with `ionic start tabs --v2`
2. Edit `src/pages/home/home.html`: Insert at the end of `<ion-header>` tag the searchbar `<ion-searchbar showCancelButton></ion-searchbar>` as follow:
```html
<ion-header>
  <ion-navbar>
    <ion-title>Home</ion-title>
  </ion-navbar>
  <ion-searchbar showCancelButton></ion-searchbar>
</ion-header>
```

You can see the result running on iPhone 5 emulator in this [video](https://drive.google.com/open?id=0B1awQoR34AyrVDR2WmsyQ2FfRVk).

**Comment by netcell** [comment] 2016-11-04 09:11
Hi @jgw96, is the information I provided useful?

Do you know what differences between the two cause this issue?

Thanks a lot :D

**Comment by jgw96** [comment] 2016-12-05 16:43
Hello @netcell ! Sorry for the delay on this. Its possible that this issue is caused by uiwebview. If you install [our fork of the wkwebview plugin](https://github.com/driftyco/cordova-plugin-wkwebview-engine) do you still get this issue? Thanks!

**Comment by jgw96** [comment] 2017-01-25 19:30
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-01-25 19:30 UTC
Labels: keyboard, needs reply, platform:ios, searchbar, v2
