### ISSUE TITLE
 Cannot read property 'style' of null in ionic-angular/components/content/content.js:179:28

### ISSUE THREAD

**Issue by lpikora** [driftyco/ionic#9310] opened 2016-11-23 15:31 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
After closing modal using `this.viewCtrl.dismiss();` Runtime Error is thrown: `Cannot read property 'style' of null`.

**Error stack:**

```
Runtime Error
Cannot read property 'style' of null
Stack
TypeError: Cannot read property 'style' of null
    at Content.addScrollPadding (/home/lukas/TransportCaptain/transportcaptain_app/node_modules/ionic-angular/components/content/content.js:179:28)
    at eval (/home/lukas/TransportCaptain/transportcaptain_app/node_modules/ionic-angular/components/content/content.js:189:23)
    at eval (/home/lukas/TransportCaptain/transportcaptain_app/node_modules/ionic-angular/util/keyboard.js:39:21)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:14051)
    at e.runTask (http://localhost:8100/build/polyfills.js:3:11411)
    at invoke (http://localhost:8100/build/polyfills.js:3:15164)
Ionic Framework: 2.0.0-rc.3
Ionic Native: 2.2.3
Ionic App Scripts: 0.0.46
Angular Core: 2.1.1
Angular Compiler CLI: 2.1.1
Node: 7.1.0
OS Platform: Linux 4.4
Navigator Platform: Linux x86_64
User Agent: Mozilla/5.0 (Linux; Android 5.0; SM-G900P Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.23 Mobile Safari/537.36
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v7.1.0
Xcode version: Not installed
```

**Comment by jgw96** [comment] 2016-11-23 16:49
Hello! Unfortunately I cannot repro this error. Would you mind creating a plunker using the plunker link available in the issue template that I can use to repro this?

**Comment by Artfloriani** [comment] 2016-11-23 19:14
I am also getting this error but have no idea how to replicate it as it only happens randomly on my project. Only started after RC-3

**Comment by ramoncarreras** [comment] 2016-11-24 14:54
Same problem here since RC-3.

My system information:

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: 1.9.0
ios-sim version: 5.0.11
OS: macOS Sierra
Node Version: v7.1.0
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by Manduro** [comment] 2016-11-25 07:54
Getting this error as well. On iOS, not sure about Android. Can't reproduce it, it's happening inconsistently (race condition?).

**Comment by Fakkio** [comment] 2016-11-25 14:45
Same problem here since RC-3.

My system information:
Ionic Framework: 2.0.0-rc.3
Ionic Native: 2.2.3
Ionic App Scripts: 0.0.46
Angular Core: 2.1.1
Angular Compiler CLI: 2.1.1
Node: 6.9.1
OS Platform: Windows 10
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Linux; U; Android 4.0; en-us; GT-I9300 Build/IMM76D) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30

Screen:
![Screenshot](https://cloud.githubusercontent.com/assets/15056746/20628384/ec748382-b325-11e6-8fe8-f7c080e76dfe.PNG)

**Comment by jgw96** [comment] 2016-11-28 20:04
Hello all! Unfortunately I have not been able to reproduce this issue at all. Does anyone have a plunker or repo that i could use to reproduce this issue?

**Comment by lonwi** [comment] 2016-12-01 12:56
I have the same issue as well. It only happens from time to time and only started since RC3

`Uncaught TypeError: Cannot read property 'style' of null
    at Content.addScrollPadding (/node_modules/ionic-angular/components/content/content.js:179:28)
    at eval (/node_modules/ionic-angular/components/content/content.js:189:23)
    at eval (/node_modules/ionic-angular/util/keyboard.js:39:21)`


Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: 1.9.0 
ios-sim version: 5.0.12 
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62

**Comment by barocsi** [comment] 2016-12-02 14:43
Same issue, happens during ionic serve as well under rc3.

**Comment by eboukamza** [comment] 2016-12-02 16:14
Hi @jgw96,

I have created a reproducer in a github repo.

The project is based on ionic2-starter-sidemenu project.

Basically the problem is due to automatic scroll when the input receives focus.

You can follow the steps of the readme for reproduce the bug.

Please ask me if something is unclear.

ty

**Comment by nbcesar** [comment] 2016-12-02 22:41
Hey - same issue here. Only an issue when logging in (have an input) vs. already logged in. 

Also - Not an issue when deployed as a PWA.

**Comment by Manduro** [comment] 2016-12-06 14:29
I'm still seeing these errors using the latest nightly `2.0.0-rc.3-201612021933`.

**Comment by jgw96** [comment] 2016-12-06 18:45
Hello all! Thanks for opening this issue. After further review it seems this is a duplicate of this issue https://github.com/driftyco/ionic/issues/9278. Because of that I am going to close this one for now.

**Closed by jgw96** 2016-12-06 18:45 UTC
Labels: needs:devicetesting, v2

**Comment by eboukamza** [comment] 2016-12-16 15:54
Not reproduced in nightly ionic-angular@2.0.0-rc.3-201612142137. Maybe #9593 is solved too.
