### ISSUE TITLE
Slides are draggy

### ISSUE THREAD

**Issue by panuganti** [driftyco/ionic#6345] opened 2016-04-27 15:59 UTC
#### Short description of the problem:
I'm using Slides component. When it loads the first time, it works fine. However, when I open a Modal and then dismiss it (or just nav to another page and pop back), the performance of Slides is unresponsive. Sometimes, it is not just draggy but, for few seconds, completely unresponsive. 

#### What behavior are you expecting?
Improve performance of Slides

```
    <ion-slides #slides [options]="options" >
        <ion-slide *ngFor="#article of articles; #i = index">
            <ion-card>
                <div >
                    <img src="{{article.ImageUrl}}">
                    <ion-card-content>
                        <h2> <b>{{article.Heading}} </b> </h2>
                        <br>
                        <p align="justify">{{article.Snippet}}</p>
                    </ion-card-content>
                </div>
            </ion-card>
        </ion-slide>
    </ion-slides>
```

**Which Ionic Version?** 1.x or 2.x
2.xx.x.beta.6

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
 
Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS:
Node Version: v4.3.2

**Comment by jgw96** [comment] 2016-04-27 18:08
Hello! Thanks for opening an issue with us! Would you be able to provide a plunkr or codepen i could use to reproduce this issue? You can use this plunkr i made as a template: http://plnkr.co/edit/L8JN6w5mqwbMY2E14dbk?p=preview

**Comment by jgw96** [comment] 2016-05-03 15:26
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-05-03 15:26 UTC
Labels: needs reply, v2

**Comment by sk-aravind** [comment] 2016-08-23 09:56
i'm having this same issue. The slider becomes draggy and unresponsive. When there are no elements on the page it runs fine. But when there are other items on the page it starts to slow down alot.
