### ISSUE TITLE
ionic2 bug(ion-datetime):day values won't refresh after changing month values

### ISSUE THREAD

**Issue by Emeryao** [driftyco/ionic#6665] opened 2016-05-26 09:03 UTC
so there will be some strange values like `2016-02-31` 
see below
![image](https://cloud.githubusercontent.com/assets/3591899/15569406/4d646e58-2363-11e6-9aa6-0d3aa9d8bf59.png)

* ionic info
```
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.7
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS:Win10 x64
Node Version: v6.2.0
```

**Comment by jgw96** [comment] 2016-05-26 14:27
Hell, thanks for opening an issue with us. I am sorry but iIam not fully understanding the issue here. Would you mind explaining the issue a little more? Also, if you could make a plunker that demonstrates this issue that would be great! Thanks for using Ionic!

**Comment by Emeryao** [comment] 2016-05-27 04:09
hi @jgw96,  here is the steps to reproduce this issue:  

1. create a `ion-datetime` with the html below
```html
<ion-item>
  <ion-label>Date</ion-label>
  <ion-datetime displayFormat="YYYY-MM-DD"> </ion-datetime>
</ion-item>
```  
2. click the date on the page and the datetime picker popup like this: 
![image](https://cloud.githubusercontent.com/assets/3591899/15597385/075a2764-2402-11e6-9ffa-486ba1a09bfb.png)
3. scroll down the day value to `30`  
![image](https://cloud.githubusercontent.com/assets/3591899/15597410/35a27a22-2402-11e6-93f1-1eda3f1ce1c9.png)
4. scroll down the month value to `2` and the day value is still `30` 
![image](https://cloud.githubusercontent.com/assets/3591899/15597434/6f881102-2402-11e6-9c1a-d3b050c25b13.png)  
5. click the `DONE` button and then the date of `2016-02-30` applied and this is weird because Feb does not have the 30th.

So, I think this is a bug of the `ion-datetime`. The day value range should refresh after the month value changes.

**Comment by Emeryao** [comment] 2016-05-27 04:11
hi @jgw96,  here is the steps to reproduce this issue:  

1. create a `ion-datetime` with the html below
```html
<ion-item>
  <ion-label>Date</ion-label>
  <ion-datetime displayFormat="YYYY-MM-DD"> </ion-datetime>
</ion-item>
```  
2.click the date on the page and the datetime picker popup like this: 
![image](https://cloud.githubusercontent.com/assets/3591899/15597385/075a2764-2402-11e6-9ffa-486ba1a09bfb.png)
3. scroll down the day value to `30`  
![image](https://cloud.githubusercontent.com/assets/3591899/15597410/35a27a22-2402-11e6-93f1-1eda3f1ce1c9.png)
4. scroll down the month value to `2` and the day value is still `30` 
![image](https://cloud.githubusercontent.com/assets/3591899/15597434/6f881102-2402-11e6-9c1a-d3b050c25b13.png)  
5. click the `DONE` button then the date of `2016-02-30` applied and this is weird because Feb does not have the 30th.

So, I think this is a bug of the `ion-datetime`. The day value range should refresh after the month value changes.

**Comment by tpruthi** [comment] 2016-05-27 10:00
+1 facing same issue

**Comment by adamdbradley** [comment] 2016-06-01 13:58
This should be fixed in the nightly version. @jgw96 can you please verify that? Thanks

**Closed by adamdbradley** 2016-06-01 13:58 UTC
Labels: datetime, v2

**Comment by ggardiles** [comment] 2016-06-07 17:14
Hello, I have also been facing this issue.

The problem is whenever you change to a different month. The ion-datetime will keep the amount of days from the first month instead of updating for the new selected month.

If you go from january to february, you will see 31 days for february.
If you go from june to July you will see 30 days for July.

Is this issue fixed in the beta.8 release?

Thanks for the awesome work!!

**Comment by jgw96** [comment] 2016-06-07 17:22
@ggardiles Thanks! This issue is fixed in the beta.8 release. You can read the changelog [here](https://github.com/driftyco/ionic/blob/2.0/CHANGELOG.md) to see all the changes and updates. Thanks for using Ionic!
