### ISSUE TITLE
Excess padding above `ion-navar` when running on device

### ISSUE THREAD

**Issue by dmackerman** [driftyco/ionic#6171] opened 2016-04-14 16:04 UTC
#### Short description of the problem:
I'm seeing some additional padding on top of my `ion-navbar` that seems to be CSS related.

#### What behavior are you expecting?
No padding above the navbar to be present.

**Steps to reproduce:**
With the following code:

```html
<ion-navbar *navbar class="top-searchbar">
    <ion-searchbar
        placeholder="Search by Make, Model, VIN..."
        [debounce]="450"
        [(ngModel)]="searchInputValue"
        (input)="onSearchInput($event)"
        (clear)="onSearchCancel($event)"
        (cancel)="onSearchCancel($event)">
    </ion-searchbar>
</ion-navbar>
```

I believe that the culprit in terms of code is this:
```css
.platform-cordova.platform-ios ion-navbar,
.platform-cordova.platform-ios ion-app > ion-toolbar:first-child,
.platform-cordova.platform-ios ion-app > ion-toolbar:first-child ion-title,
.platform-cordova.platform-ios ion-app > ion-toolbar:first-child ion-segment,
.platform-cordova.platform-ios ion-menu > ion-toolbar:first-child,
.platform-cordova.platform-ios ion-menu > ion-toolbar:first-child ion-title,
.platform-cordova.platform-ios ion-menu > ion-toolbar:first-child ion-segment,
.platform-cordova.platform-ios ion-page.modal > ion-toolbar:first-child,
.platform-cordova.platform-ios ion-page.modal > ion-toolbar:first-child ion-title,
.platform-cordova.platform-ios ion-page.modal > ion-toolbar:first-child ion-segment {
    padding-top: 24px;
    height: 64px;
    min-height: 64px;
}
```

Removing these values fixes the issue.

**Which Ionic Version?** 
2.x

Screenshot:
![ds](https://dl.dropboxusercontent.com/spa/pkr1d5uhq1t8wz1/25hix6-z.png)

**Comment by adamdbradley** [comment] 2016-04-14 17:01
Thanks for the report. This update should help us better narrow in the padding css: https://github.com/driftyco/ionic/commit/44403d1d8718ef275483114fc865d0867a46ca31

**Comment by brandyscarney** [comment] 2016-04-14 18:31
@dmackerman Are you hiding the status bar in your app?

**Comment by dmackerman** [comment] 2016-04-14 18:34
@brandyscarney No we're not. I think I had messed with some `StatusBar` stuff thinking it would make a difference, but even with default styling I'm still seeing this.

**Comment by brandyscarney** [comment] 2016-04-14 18:42
@dmackerman Hmm what styles are you adding with `top-searchbar`? I'm just not able to reproduce this in the conference app:

![screen shot 2016-04-14 at 2 41 33 pm](https://cloud.githubusercontent.com/assets/6577830/14539592/067c233a-024f-11e6-8b39-e012d5d5984e.png)

**Comment by jgw96** [comment] 2016-04-14 18:59
Not able to repro with conference app here either. @dmackerman Could you make a plunker that reproduces this issue? Here is a template you can use to make your plunker from: http://plnkr.co/edit/TW20lftdc5s622pcJPkp?p=info

**Comment by christtrc** [comment] 2016-04-15 05:10
+1
![image](https://cloud.githubusercontent.com/assets/10356940/14551891/6c009c42-030b-11e6-9763-3e1e9ddc7408.png)

**Comment by dmackerman** [comment] 2016-04-15 20:37
@jgw96 A Plunkr won't demonstrate the issue, because this only happens when running inside Cordova. Applying the following CSS seems to fix my issue:

```css
.platform-cordova.platform-ios ion-navbar,
.platform-cordova.platform-ios ion-app > ion-toolbar:first-child,
.platform-cordova.platform-ios ion-app > ion-toolbar:first-child ion-title,
.platform-cordova.platform-ios ion-app > ion-toolbar:first-child ion-segment,
.platform-cordova.platform-ios ion-menu > ion-toolbar:first-child,
.platform-cordova.platform-ios ion-menu > ion-toolbar:first-child ion-title,
.platform-cordova.platform-ios ion-menu > ion-toolbar:first-child ion-segment,
.platform-cordova.platform-ios ion-page.modal > ion-toolbar:first-child,
.platform-cordova.platform-ios ion-page.modal > ion-toolbar:first-child ion-title,
.platform-cordova.platform-ios ion-page.modal > ion-toolbar:first-child ion-segment {
    padding-top: 0;
    height: 44px;
    min-height: 44px;
}

.platform-cordova.platform-ios ion-navbar ion-title, 
.platform-cordova.platform-ios ion-navbar ion-segment {
    padding-top: 0;
}
```

@brandyscarney the only styles that I was using on `.top-searchbar` were these:

```scss
.top-searchbar {
    .toolbar-background {
        border: 0;
    }
}
```

**Comment by jgw96** [comment] 2016-04-15 21:05
Hey @dmackerman ! Hmm im still having issues reproducing this issue ):. I am setting the StatusBar to styleDefault().

**Comment by brandyscarney** [comment] 2016-04-15 21:14
@dmackerman Interesting. So we made some changes to the way the status bar padding is applied and I have released a nightly version with these changes. (Nightly versions are a new thing :tada:)

Could you install the nightly version in your app:

```
npm install ionic-angular@nightly --save
npm install angular2@2.0.0-beta.15 --save
```

and then run the app and see if the problem still exists? If it does exist, can you try adding this to the `@App`'s `config`:

```
  config: {
    statusbarPadding: false
  }
```

I'm not sure why the status bar isn't showing for you at all. Feel free to message me on slack if it's easier. Thanks!

**Comment by brandyscarney** [comment] 2016-04-18 15:30
So this was being caused by the Status Bar changing to light text because `StatusBar.styleDefault()` was not being called in the `platform.ready`. This issue was created to fix it: https://github.com/driftyco/ionic/issues/6186

This should be fixed in the `beta.5` release but if you'd like to check for me please install the `nightly` version and let me know if you run into any issues: 

```
npm install ionic-angular@nightly --save
npm install angular2@2.0.0-beta.15 --save
```

Latest nightly at this time is: `2.0.0-beta.4-201604170622`

**Closed by brandyscarney** 2016-04-18 15:30 UTC
Labels: menus, modals, platform:ios
