### ISSUE TITLE
VirtualScroll failed to unregister scrollview's EventListener 

### ISSUE THREAD

**Issue by jccf091** [driftyco/ionic#6303] opened 2016-04-25 06:40 UTC
When VirtualScroll was destroyed, it tried to unregister scrollviews's event listeners. But the scrollview reference was setted to null. There will be a exception.
EXCEPTION: TypeError: null is not an object (evaluating '_this._el.removeEventListener')
Because the scrollview was belong to Content component. It called scrollview's destory function before virtualScroll.

Should we move remove event listener logic into scrollview's destory function?

```
insert any relevant code between the above and below backticks
<ion-navbar primary *navbar hideBackButton>
  <ion-title >Something</ion-title>
</ion-navbar>

 <ion-toolbar>
  <ion-searchbar
    [(ngModel)]="searchbarInput"
    [placeholder]="'Search'"
    [hideCancelButton]="shouldHideSearchBarCancelButton"
    [cancelButtonText]="Cancel">
  </ion-searchbar>
 </ion-toolbar>

<ion-content class="index-page">
  <ion-scroll>
    <ion-item-group [virtualScroll]="items" [headerFn]="getItemHeader">
    <ion-item-divider *virtualHeader="#header">
      {{ header }}
    </ion-item-divider>
    <button ion-item detail-none *virtualItem="#item" (click)="goToShowPage(item)">
      {{ item.name }}
    </button>
  </ion-item-group>  
  </ion-scroll>
</ion-content>
```
ionic: "2.0.0-beta.6",

**Comment by jccf091** [comment] 2016-04-25 07:58
workaround:
```
import { ViewChild } from 'angular2/core';
import { Content, VirtualScroll } from 'ionic-angular';
@Page({
  templateUrl: 'index.html',
})

export class IndexPage {
  @ViewChild(VirtualScroll) virtualScroll: VirtualScroll;
  constructor(
  ) {
  }

  ngOnInit() {
    console.debug('IndexPage OnInit');
  }

  onPageWillUnload() {
    console.debug('IndexPage onPageDidUnload');
  }

  ngOnDestroy() {
    console.debug('IndexPage ngOnDestroy');
    if (this.virtualScroll['_unreg']) {
      this.virtualScroll['_unreg']();
      this.virtualScroll['_unreg'] = null;
    }
  }
}
```

**Comment by ghenry22** [comment] 2016-06-03 03:14
This is exactly the error I get when first starting to scroll a virtualscroll list on ios with uiwebview.  This causes a big stutter in the scrolling.  As logged here #6104

**Comment by jgw96** [comment] 2016-06-03 14:27
Hello, thanks for opening an issue with us! @jccf091 What platforms are you seeing this issue on?

**Comment by ghenry22** [comment] 2016-06-04 03:36
I only see this symptom on iOS with uiwebview.  Android, browser and wkwebview on iOS all work fine for me.

**Comment by jgw96** [comment] 2016-06-06 13:43
Hello all! I am going to close this issue as a dupe of #6104 since this seems to be a symptom of the larger issue stated in that post. Thanks for using Ionic everyone!

**Closed** 2016-06-06 13:47 UTC
Labels: needs reply, v2, virtualscroll
