### ISSUE TITLE
Datetime not displayed properly for min/max attributes

### ISSUE THREAD

**Issue by vasanthm7** [driftyco/ionic#7558] opened 2016-08-05 12:52 UTC
#### Short description of the problem:
Datetime is not rendered properly when using min/max attributes.

#### What behavior are you expecting?
The Day, Month and year should be displayed properly when using min/max attributes.

For example, when providing min date as 2016-04-12, the date and month is not displayed on clicking the date selection. Once you scroll the date/month, it renders correctly. 

Once the user selects Done without changing anything, the date 2016-01-01 is saved in the model even though this is outside the range provided in min and max.

This is happening in browser and iOS 

**Which Ionic Version?** 1.x or 2.x
2.0.0-beta.10

#### Plunker that shows an example of your issue
https://plnkr.co/edit/PKNPDQoQiC0x20eGl2Z0?p=preview

Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
OS: Windows 7
Node Version: v5.8.0

**Comment by jgw96** [comment] 2016-08-05 18:44
Hello, thanks for opening an issue with us! I am going to be closing this issue as a duplicate of https://github.com/driftyco/ionic/issues/6850. Thanks for using Ionic!

**Closed by jgw96** 2016-08-05 18:44 UTC
Labels: range
