### ISSUE TITLE
i have a problem with focus input

### ISSUE THREAD

**Issue by buiphu** [driftyco/ionic#5895] opened 2016-03-21 07:45 UTC
i used  `this.name.focus();`
but it error **" Cannot read property 'focus' of undefined"**

how fix it

**Comment by jgw96** [comment] 2016-03-21 16:07
Hello! Thanks for opening an issue with us, we just need a little more info from you so that we can better help you with your issue. Would you mind posting a code sample, plunkr or codepen that we can use to reproduce your issue? Also, would you mind running `ionic info` and posting the output? Thanks again!

**Comment by jgw96** [comment] 2016-03-28 16:31
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to respond back if your still having the issue! Thanks again!

**Closed by jgw96** 2016-03-28 16:31 UTC
Labels: needs reply
