### ISSUE TITLE
Strange lines in ion-input: Why the bottom line of the list is tinted when the last input is highlighted?

### ISSUE THREAD

**Issue by menosprezzi** [driftyco/ionic#8454] opened 2016-10-03 22:45 UTC
See the [code](http://plnkr.co/edit/3gsMR7cwTaDOPN9fT5dZ?p=preview)

This happens in IOS and Android platforms.

**Comment by jgw96** [comment] 2016-10-04 14:25
Hello, thanks for using Ionic! Unfortunately it seems as if your code did not make it into the plunker (maybe you didnt hit freeze?). Also, could you post a screenshot of the issue you are seeing?

**Comment by jgw96** [comment] 2016-10-07 13:52
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-10-07 13:52 UTC
Labels: needs reply, v2

**Comment by menosprezzi** [comment] 2016-10-11 17:25
Ohhh sorry about that! I was busy this week... so take a look at here
why the bottom line is so strange? is this right?
![image](https://cloud.githubusercontent.com/assets/6165501/19280926/248564fc-8fbe-11e6-8136-dd330b4c5755.png)

**Comment by cmacdonnacha** [comment] 2017-08-15 13:51
Hey @jgw96 , can you re-open this issue as it still happens in version 3.7.0:

![image](https://user-images.githubusercontent.com/9777763/29318704-21f426c6-81c9-11e7-86db-4ee9883dc5cd.png)

It only ever happens for the last input in the list.

**Comment by mukulsoftwap** [comment] 2018-03-10 07:50
why close this issue its present in docs also https://ionicframework.com/docs/components/#floating-labels
i am also facing this issue i solved this by written our css but what is the benefit to use ionic if we fix this type of nonsense issues.

**Comment by brandyscarney** [comment] 2018-03-12 23:11
This is not a bug, it is by design. Please see the issue here: https://github.com/ionic-team/ionic/issues/5537

I have some ideas in mind on how to improve this as part of v4 though. If you have ideas for how we can make this more easily customizable please comment on that issue. Thanks!
