### ISSUE TITLE
Header in side-menu causes drawing issues

### ISSUE THREAD

**Issue by oliversalzburg** [driftyco/ionic#2122] opened 2014-09-01 15:33 UTC
I have a page layout that uses `ion-side-menus` and looks like this:
```
<ion-side-menus>
	<ion-side-menu side="left">

		<div class="bar bar-header bar-stable">
		</div>

		<ion-list class="content has-header">
			<ion-item menu-close class="ion-item-left" ng-href="#/info">
				<i class="icon ion-home"></i>
				Home
			</ion-item>
		</ion-list>
	</ion-side-menu>

	<ion-side-menu-content>
	</ion-side-menu-content>
</ion-side-menus>
```

This causes the contents of the `ion-list` not to be drawn on both Android and iOS (works fine on Chrome Desktop). Apparently the cause is the transformation applied to `bar` elements.

![](http://i.imgur.com/8VwHWy5.gif)

**Comment by mhartington** [comment] 2015-02-27 17:37
Just tested this with the nightly builds on iOS and Android.
Could not reproduce the issue. 
Closing for now, please test the nightly builds out.

**Closed by mhartington** 2015-02-27 17:37 UTC
Labels: css, menus

**Comment by hypery2k** [comment] 2015-04-20 14:12
can confirm that it works with rc3
