### ISSUE TITLE
tab badge will jump when badge number goes to 0 and from 0 to > 0

### ISSUE THREAD

**Issue by pencilcheck** [driftyco/ionic#2882] opened 2015-01-07 01:11 UTC
The relevant css:
```
.tab-item.has-badge {
  position: relative;
}

.tab-item .badge {
  position: absolute;
  top: 4%;
  right: 33%; // fallback
  right: calc(50% - 26px);
  padding: $tabs-badge-padding;
  height: auto;
  font-size: $tabs-badge-font-size;
  line-height: $tabs-badge-font-size + 4;
}
```

I found out that the fix is simply set the position relative regardless of whether has-badge is present or not
```
.tab-item {
  position: relative;
}
```

**Comment by Ionitron** [comment] 2015-01-07 01:11
Greetings, @pencilcheck!

We are now requiring all issues to be submitted through our custom issue form so that we have all of the information necessary to fix them as quickly as possible.

Your progress on this issue has been saved at the following url:

[link to Ionic issue form](http://ionicframework.com/submit-issue/#/?iid=2882)

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by rajatrocks** [comment] 2015-01-22 06:19
+1

**Comment by Ionitron** [comment] 2015-02-09 18:09
Greetings @pencilcheck!

My sensors indicate that I require more information in order to assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this happen occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com), where many humans will be able to offer wisdom and advice.

Thank you for allowing me to assist you.

<span ionitron-needs-reply></span>

**Comment by Ionitron** [comment] 2015-03-12 03:41
Greetings @pencilcheck!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment] 2015-03-12 03:41
Greetings @pencilcheck!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-03-12 03:41 UTC
Labels: ionitron:closed

**Comment by pencilcheck** [comment] 2015-03-12 03:43
Is it fixed?

**Comment by DNAngeluS** [comment] 2016-09-09 22:37
Thanks @pencilcheck your solution works like charm...

**Comment by jrobertustorres** [comment] 2017-11-08 16:31
saved my day!!
