### ISSUE TITLE
bug: directive within directive not working in v1.0.0-beta.14

### ISSUE THREAD

**Issue by kevendra** [driftyco/ionic#3156] opened 2015-02-20 03:46 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>directive within directive in ion-header-bar was working in v1.0.0-beta.11 but looks like it stop work after upgrade to v1.0.0-beta.14

#### ion-header-bar :
```html
<ion-view>
...
<div data-menu-right></div>
```

#### file: menu-right-directive.js
```javascript
angular.module(_DIRECTIVES_)
.directive('menuRight', function () {
  return {
    restrict:'AE',
    scope: {
    },
    templateUrl:'public/views/navigation/menu-right.html'
  };
});
```
#### file: menu-right.html
```html
<ion-nav-buttons side="right">
  test
</ion-nav-buttons>
```

**Comment by Ionitron** [comment] 2015-02-20 03:47
Greetings @kevendra!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3156). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3156)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment] 2015-02-27 16:21
Greetings @kevendra!

My sensors indicate that I require more information in order to assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this happen occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com), where many humans will be able to offer wisdom and advice.

Thank you for allowing me to assist you.

<span ionitron-needs-reply></span>

**Comment by Ionitron** [comment] 2015-03-29 18:13
Greetings @kevendra!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment] 2015-03-29 18:13
Greetings @kevendra!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-03-29 18:13 UTC
Labels: ionitron:closed
