### ISSUE TITLE
bug: ng-clickable items turn gray for some reason

### ISSUE THREAD

**Issue by mzarella** [driftyco/ionic#4014] opened 2015-06-30 19:33 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>When I put my finger on the display to scroll and it happens to land on a `<div class='item item-body' ng-click='showItem'>`, that item turns gray like it's being selected. It's parent is a `<div class='list card'>` and there are several cards on the screen. This can be confusing for the user. Has anyone else ran into this one?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-06-30 19:33
Greetings @mzarella!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4014). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4014)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by simplesmiler** [comment] 2015-07-13 09:23
May be related to https://github.com/driftyco/ionic/issues/3441.

**Comment by mhartington** [comment] 2015-07-14 15:37
Duplicate of #3441

**Closed by mhartington** 2015-07-14 15:37 UTC
