### ISSUE TITLE
bug: youtube events not getting called

### ISSUE THREAD

**Issue by antonymca** [driftyco/ionic#5461] opened 2016-02-15 15:42 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.0</span>  <span ionic-webview>webview</span>

<span ionic-description>'onStateChange': onPlayerStateChange event is not getting called when  youtube video is running.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment] 2016-03-16 20:13
Hello! Thanks for opening an issue with us, we just need a little more info from you so that we can better help you with your issue. Would you mind posting a code sample, plunkr or codepen that we can use to reproduce your issue? Also, would you mind running `ionic info` and posting the output? Thanks again!

**Comment by jgw96** [comment] 2016-04-12 21:25
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to respond back if your still having the issue! Thanks again!

**Closed by jgw96** 2016-04-12 21:25 UTC
Labels: related to external library, v1
