### ISSUE TITLE
Contents not scrollable with Tab control in iOS

### ISSUE THREAD

**Issue by horrychan** [driftyco/ionic#7555] opened 2016-08-05 12:05 UTC
When there are two tab pages embedded with contents long enough for vertical scrolling, the previous tab page can't be scrolled anymore.

**Steps to reproduce:**

1. Get the template via: ionic start cutePuppyPics --v2

2. Replace the content in home.html with a long list:

```
<ion-list>
    <ion-item>Terminator II</ion-item>
	<ion-item>Terminator II</ion-item>
	<ion-item>Terminator II</ion-item>
	<ion-item>Terminator II</ion-item>
	<ion-item>Terminator II</ion-item>
	<ion-item>Terminator II</ion-item>
	<ion-item>Terminator II</ion-item>
	<ion-item>Terminator II</ion-item>
	<ion-item>Terminator II</ion-item>
	<ion-item>Terminator II</ion-item>
    <ion-item>Terminator II</ion-item>
	<ion-item>Terminator II</ion-item>
	<ion-item>Terminator II</ion-item>
	<ion-item>Terminator II</ion-item>
	<ion-item>Terminator II</ion-item>
	<ion-item>Terminator II</ion-item>
	<ion-item>Terminator II</ion-item>
	<ion-item>Terminator II</ion-item>
	<ion-item>Terminator II</ion-item>
	<ion-item>Terminator II</ion-item>	
  </ion-list>
```

3. Do the same for  about.html.

4. Generate iOS project: ionic build ios

5. Run it in simulator. The list in Home tab is scrollable at first, but it can't be scrolled anymore after scrolling contents in About tab.

Version:

ionic-angular: 2.0.0-beta.10

with tho following package.json:

```
{
  "dependencies": {
    "@angular/common": "2.0.0-rc.3",
    "@angular/compiler": "2.0.0-rc.3",
    "@angular/core": "2.0.0-rc.3",
    "@angular/platform-browser": "2.0.0-rc.3",
    "@angular/platform-browser-dynamic": "2.0.0-rc.3",
    "@angular/http": "2.0.0-rc.3",
    "es6-shim": "^0.35.0",
    "ionic-angular": "2.0.0-beta.10",
    "ionic-native": "1.3.2",
    "ionicons": "3.0.0",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.6",
    "zone.js": "^0.6.12"
  },
  "devDependencies": {
    "del": "2.2.0",
    "gulp": "3.9.1",
    "gulp-watch": "4.3.5",
    "ionic-gulp-browserify-typescript": "2.0.0",
    "ionic-gulp-fonts-copy": "^1.0.0",
    "ionic-gulp-html-copy": "^1.0.0",
    "ionic-gulp-sass-build": "^1.0.0",
    "ionic-gulp-scripts-copy": "^2.0.0",
    "ionic-gulp-tslint": "^1.0.0",
    "tslint-ionic-rules": "^0.0.3",
    "run-sequence": "1.1.5"
  },
  "cordovaPlugins": [
    "cordova-plugin-whitelist",
    "cordova-plugin-console",
    "cordova-plugin-statusbar",
    "cordova-plugin-device",
    "cordova-plugin-splashscreen",
    "ionic-plugin-keyboard"
  ],
  "cordovaPlatforms": [
    "ios",
    {
      "platform": "ios",
      "version": "",
      "locator": "ios"
    }
  ],
  "name": "cutepuppypics",
  "description": "cutePuppyPics: An Ionic project"
}
```

**Comment by jgw96** [comment] 2016-08-05 17:12
Hello, thanks for opening an issue with us! Would you be able to provide a [plunker](http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview) that demonstrates this issue? Thanks for using Ionic!

**Comment by horrychan** [comment] 2016-08-05 18:42
Thanks for your reply, yes you can try this:

[plunker](http://plnkr.co/edit/YqSv0LzGOZMXNiStsQYN?p=preview)

indeed it runs fine on browser, but if have it running in iOS simulator, list on tab 1 won't be scrollable any more once you scrolled the list on tab 2.

**Comment by jgw96** [comment] 2016-08-09 17:30
Hello @horrychan. Thanks for using Ionic! Unfortunately i am not able to reproduce this issue with any of our tests, using your code, or any of my test apps. I am using the ios 9.3.2 simulator. Since i cannot seem to reproduce this issue i will be closing this issue for now, but will be keeping a look out for it and will happily reopen if i am able to reproduce.

**Closed by jgw96** 2016-08-09 17:30 UTC
Labels: v2
