### ISSUE TITLE
bug: ionic view-title is truncated.

### ISSUE THREAD

**Issue by lucifertran** [driftyco/ionic#3851] opened 2015-05-28 04:31 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.2</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi,

My issue is:
I have a tab -> click on one item and it navigate to the detail page with a back button. (the navigation is done by routeprovider which pass an item ID).
The first time click to go to detail page. all data is loaded from breeze service.
However, if we go back & click on the same item, it simply get data from cache, which just take fraction of second. This is when the title issue arise:

At first time: i use ion-view view-title = {{}}
==> the title could not be display.

then i change to use:
ion-nav-title
{{}}
/ion-nav-title
==> title displayed on the second time, but the word is truncated like "View Ti..."

I tried to use $ionicNavBarDelegate.title(title); how ever it did not work, still being truncated.
I even try to add delay 1 second to the add title method, but still no clue how to fix it.

Anyone who go through the same problem?
Please help me to look into this

Thanks a lot.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-05-28 04:31
Greetings @lucifertran!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3851). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3851)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by delta98** [comment] 2015-06-02 09:54
`.header .title` has a css property `text-overflow: ellipsis;` which will be truncating the text in the ion-nav-title directive. This is on purpose to prevent wrapping with long navigation titles. You can override the style in your own stylesheets.

**Comment by lucifertran** [comment] 2015-06-03 07:14
thanks delta98.

modifying the style is not quite right. The title only wrapped when opening data the second time (without getting data from server).
If i force the form to load data on the second time, the title display perfectly like the first time.
Therefore, should have any work around solution for this?

**Comment by wkrueger** [comment] 2015-07-09 23:17
Hello,
After some headache I've been able to reproduce it. In my case, the issue happens when the view title is changed dynamically. Say, the title begins empty or short, then is dynamically changed to a long title.

I see some issues on the portions below. There may be many ways of fixing it though.

```javascript
//$ionHeaderBar controller

self.updatePositions = function(titleEle, updateTitleLeft, updateTitleRight, buttonsLeft, buttonsRight, updateCss, showPreviousTitle) {

//...


    ionic.requestAnimationFrame(function() {
      if (titleEle && titleEle.offsetWidth + 10 < titleEle.scrollWidth) {
        var minRight = buttonsRight + 5;
        var testRight = $element[0].offsetWidth - titleLeft - self.titleTextWidth() - 20;
        updateTitleRight = testRight < minRight ? minRight : testRight;
        if (updateTitleRight !== titleRight) {
          titleEle.style.right = updateTitleRight + 'px';
          titleRight = updateTitleRight;

//...

self.titleTextWidth = function() {
	if (!titleTextWidth) {
	  var bounds = ionic.DomUtil.getTextBounds(getEle(TITLE));
	  titleTextWidth = Math.min(bounds && bounds.width || 30);
	}
	return titleTextWidth;
};
```
In `var testRight = $element[0].offsetWidth - titleLeft - self.titleTextWidth() - 20;`, `self.titleTextWidth()` always returns 30 (or your initial title size) since it is "memoized" on the first execution.

This leads to `testRight` to be really big and to override `minRight` previously calculated from measuring the elements.

*Workaround:* Set your initial title text to a big string.

```
<ion-nav-title ng-bind="thetitle">_________________________________________________</ion-nav-title>
```

**Comment by lucifertran** [comment] 2015-07-14 05:41
Thanks Will,
I've tried the workaround solution you mentioned, but still it does not work out. The title still generate differently on the next time.

**Comment by wkrueger** [comment] 2015-07-14 18:21
Notice that there are always 2 ion header bars, one of which is always hidden (used for the transition). You need to run align in visible header bar (or in both).

At first it took me a bit to notice that, since I was trying `document.querySelector`, which only returns the first one.

So, this is my ugly code to realign the bars (plus memoization removal)

```
            setTimeout(() => {
                var headerBarEls = document.querySelectorAll("ion-header-bar");
                for ( var it = 0 ; it < headerBarEls.length ; it++ ) {
                    var ctrl = angular.element(headerBarEls[it]).data().$ionHeaderBarController;
                    ctrl.align();
                }
            },500);
```

**Comment by jgw96** [comment] 2016-03-23 19:09
Hello! Are you all still experiencing this issue?

**Comment by wkrueger** [comment] 2016-03-23 20:35
I'm yet to upgrade the project to a newer version of ionic to check it... Project currently on "stand-by".

**Comment by jgw96** [comment] 2016-03-23 21:12
@wkrueger No Problem!

**Comment by jgw96** [comment] 2016-03-24 15:28
Thanks for opening this issue! As this issue is a duplicate of https://github.com/driftyco/ionic/issues/4661#issuecomment-200779335 i will be closing this issue but please feel free to move the conversation over there! Thanks again!

**Closed by jgw96** 2016-03-24 15:28 UTC
Labels: needs reply, v1
