### ISSUE TITLE
bug: Unable to reload ionic serve when js/html is saved

### ISSUE THREAD

**Issue by xawntan** [driftyco/ionic#8448] opened 2016-10-03 18:34 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Unable to reload ionic serve when js/html is saved.

I was told to contact the creator by the npm. 
Here is the npm log: http://pastebin.com/7yBRpiVJ
While here is my own cmd log: http://pastebin.com/TcPaUzDY</span>

<span is-issue-template></span>

**Comment by jgw96** [comment] 2016-10-04 14:09
Hello, thanks for opening an issue with us! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic-app-scripts/issues/87. Thanks!

**Closed by jgw96** 2016-10-04 14:09 UTC
