### ISSUE TITLE
Ionic 2 Black Screen on Chrome

### ISSUE THREAD

**Issue by Gabrielr47** [driftyco/ionic#8819] opened 2016-10-20 14:23 UTC
When I click the button to the menu screen gets black or white, tried to console, and is not shown any messages, I tried to upgrade to the latest version and the error persists, what to do?

**Ionic 2 info:**

Your system information:

> Cordova CLI: Not installed
> Gulp version:  CLI version 3.9.1
> Gulp local:  
> Ionic Framework Version: 2.0.0-rc.1
> Ionic CLI Version: 2.1.1
> Ionic App Lib Version: 2.1.1
> Ionic App Scripts Version: 0.0.36
> ios-deploy version: Not installed
> ios-sim version: 5.0.8 
> OS: Mac OS X Sierra
> Node Version: v4.6.1
> Xcode version: Xcode 8.0 Build version 8A218a 

![Image]
(https://s22.postimg.org/7ci4g8bld/Captura_de_Tela_2016_10_20_a_s_12_14_41.png)

to reproduce this bug I just run:

ionic start MyIonic2Project tutorial --v2
cd MyIonic2Project
ionic serve

In the browser:

![Image]
(http://i.imgur.com/BWWCrF8.gif)

**Comment by jgw96** [comment] 2016-10-20 16:05
Hello, thanks for using Ionic! Unfortunately I cannot reproduce this issue, do you mind posting a repo that we can use to reproduce this issue?

**Comment by Gabrielr47** [comment] 2016-10-20 21:18
Hi, thx for the faster feedback, to reproduce this you just need to download the tutorial version on ionic 2 docs, no code was changed.

**Comment by Alx101** [comment] 2016-10-21 06:47
I also receive this issue at times. It has even happened on the emulator (iOS). The trigger seems to be navigating quickly back and forth, eventually causing the screen to go black or white, essentially freezing the app.

**Comment by xx0r** [comment] 2016-10-22 08:39
I posted this in another, closed issue, but no I know better :) Here it is

I might be wrong, but I can replicate this only when there is a seemingly innocous directive **no-border** on **ion-navbar** 

OS: Win10 x64

1. ionic start sidemenu.starter --ts --v2 --teplate sidemenu
2. **ionic info**
```
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.36
OS:
Node Version: v6.6.0
```
3. edit **page2.html**
``<ion-navbar no-border>``

4. `ionic serve`

5. click couple of times on the items

6. click rapidly back

7. the screen goes black / white as soon as you reach the root page and click on the left icon

VIDEO:

![ionic-navbar-noborder](https://cloud.githubusercontent.com/assets/3314395/19618179/493797ba-9843-11e6-88c5-bcf81a027f47.gif)

**Comment by manucorporat** [comment] 2016-10-24 20:23
Can you guys try against nightly?

```
npm install ionic-angular@nightly --save
```

**Comment by ValterSantosMatos** [comment] 2016-10-25 07:12
Hi, I confirm I also have this issue in my app while debugging in chrome or while running the app in IOS test flight (in test flight is much more common).

**Comment by jgw96** [comment] 2016-10-25 15:10
Hello all! After doing some testing this morning with the latest nightly release I can confirm that I am not able to reproduce this issue in chrome or on the iOS 10 emulator. Because of this I am going to close this issue for now. Thanks!

**Closed by jgw96** 2016-10-25 15:10 UTC
Labels: needs reply, v2
