### ISSUE TITLE
navCtrl.push with option animate: false is calling constructor X times [DEVICE only]

### ISSUE THREAD

**Issue by radzik07** [driftyco/ionic#10135] opened 2017-01-22 19:06 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Device only (iPhone SE iOS 10)!
If animate option is set to true, the constructor is called once.
If animate option is set to false, the constructor is called 7 times, a fast "reloading" blinks are noticeable.

**Expected behavior:**
Animate: false doesn't make code execute more than once.

**Related code:**
File A:
`that.navCtrl.push(BookPage, { id: 33 }, { animate: false });`
File B:
```
constructor(public navCtrl: NavController, public navParams: NavParams, public modalCtrl: ModalController) {
		if(navParams.get('id')) {
			alert('constructor')
			this.loadBook(navParams.get('id'));
		}
	}
```

**Other information:**

Seems to work as expected in desktop browser.
Testing on iPhone SE.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0 
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v7.4.0
Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by mhartington** [comment] 2017-01-23 18:55
Hmm, cannot reproduce. Can you push a small demo to github to look at? Otherwise I will close this.

**Comment by mhartington** [comment] 2017-01-26 16:11
Hi, I'm going to be closing this. I have not been able to recreate this issue and no demo has been published. If this is still an issue, feel free to open a new issue.

**Closed by mhartington** 2017-01-26 16:11 UTC
Labels: needs reply, v2
