### ISSUE TITLE
Error page won't allow me to copy text

### ISSUE THREAD

**Issue by besi** [driftyco/ionic#10509] opened 2017-02-21 09:27 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
In case of an error I want to select some text from the browser, however the selection of text is disabled.

![screen shot 2017-02-21 at 10 25 08](https://cloud.githubusercontent.com/assets/160412/23158631/3598e9b0-f820-11e6-843f-2916a4425e88.png)

**Expected behavior:**

I want to be able to select text from the error message and paste that into Google to see how I can fix the problem.

**Comment by jgw96** [comment] 2017-03-27 07:23
Hello, thanks for using Ionic! Unfortunately I cannot reproduce this issue in the latest chrome and safari. Is this still an issue?

**Comment by jgw96** [comment] 2017-03-31 15:05
Hello! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-03-31 15:05 UTC
Labels: needs info, v2
