### ISSUE TITLE
<div (click)> and <span (click)> elements are not easy to click on mobile

### ISSUE THREAD

**Issue by Yagger** [driftyco/ionic#5258] opened 2016-01-30 11:38 UTC
When making `<div>` or `<span>` the clickable elements with (click), the actual experience clicking them on mobile device is not good. I tap element 3-4 times before click event fires. If I replace (click) with (tap) then click works well, but scrolling the list of tappable elements becomes impossible.

Try this for test:
```
<div style="width: 100%; height: 100px; background-color: green; display: block" (click)="goToNextPage()"></div>
<span style="width: 100%; height: 100px; background-color: blue; display: block" (click)="goToNextPage()"></span>
<a style="width: 100%; height: 100px; background-color: yellow; display: block" (click)="goToNextPage()"></a>
<button style="width: 100%; height: 100px; background-color: red; display: block" (click)="goToNextPage()"></button>
```
Upload to Ionic View, then start the app, and try to click/tap each element forth and back (implement next page to have the back button).

**Comment by jgw96** [comment] 2016-03-14 14:21
Hello! Thanks for opening this issue with us! As this issue seems to be a duplicate of https://github.com/driftyco/ionic/issues/5260 i will be closing this issue. Thanks again!

**Closed by jgw96** 2016-03-14 14:21 UTC
