### ISSUE TITLE
bug: $ionicScrollDelegate.anchorScroll throws exception: Cannot read property 'attributes' of null

### ISSUE THREAD

**Issue by mechon** [driftyco/ionic#4587] opened 2015-11-02 18:45 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>I'm encountering this issue, made a sample at [codepen](http://codepen.io/mechon/pen/YyjpyY?editors=101). Error is usually thrown when the container's ng-show value is toggled.

This is similar to #4155.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-11-02 18:45
Greetings @mechon!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4587). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4587)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by tiagoMaua** [comment] 2015-12-21 21:16
Hi!!

I had the same problem, and found that it was caused by $ location.hash (idElement);

The function $ location.hash () creates a map id's, even the id's being different pages, it is important that they are unique throughout the project.

I recommend the following use:

In HTML:

<div id="nameView-{{variableId}}> POINT </div>

And in controller function:

` this.scrollTo = function (targetPoint){

$location.hash( 'nameView-' + targetPoint);
$ionicScrollDelegate.anchorScroll(true);    

}`

This work to me!

**Comment by jgw96** [comment] 2016-03-15 14:24
Hello! Thanks for opening an issue with us! As it looks like this issue has already been solved i am going to be closing this issue for now, but feel free to reopen if needed!

**Closed by jgw96** 2016-03-15 14:24 UTC
