### ISSUE TITLE
Page disappears or not rendered after navCtrl.push()

### ISSUE THREAD

**Issue by thruthesky** [driftyco/ionic#8756] opened 2016-10-17 13:19 UTC
#### Page disappears or not rendered after navCtrl.push()

When I push another page inside HomePage constructor(), the page is not shown.

I want to show another page right after a page is loaded.

And this works in RC 0 but not in RC 1.

The symptom is, the page appears for a second and disappears immediately.

```
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
import { FirstPage } from '../first-page/first-page';
@Component({
  templateUrl: 'home.html'
})
export class HomePage {
  constructor(public navCtrl: NavController) {
    this.navCtrl.push( FirstPage ); // this does not work. page disappears or pages is not rendered.
    // setTimeout( () => this.navCtrl.push( FirstPage ), 100 ); // this is working
  }
  ionViewDidLoad() {
    // this.navCtrl.push( FirstPage ); // this does not work.
  }
}

```

I have tested it on Browser and Android. 

My ionic info :

```
Cordova CLI: 6.3.1
Gulp version:  CLI version 1.2.2
Gulp local:
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.36
OS:
Node Version: v6.7.0

```

My package json :

```

{
  "name": "ionic-hello-world",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "build": "ionic-app-scripts build",
    "watch": "ionic-app-scripts watch",
    "serve:before": "watch",
    "emulate:before": "build",
    "deploy:before": "build",
    "build:before": "build",
    "run:before": "build"
  },
  "dependencies": {
    "@angular/common": "^2.0.0",
    "@angular/compiler": "^2.0.0",
    "@angular/compiler-cli": "0.6.2",
    "@angular/core": "^2.0.0",
    "@angular/forms": "^2.0.0",
    "@angular/http": "^2.0.0",
    "@angular/platform-browser": "^2.0.0",
    "@angular/platform-browser-dynamic": "^2.0.0",
    "@angular/platform-server": "^2.0.0",
    "@ionic/storage": "^1.0.3",
    "ionic-angular": "^2.0.0-rc.1",
    "ionic-native": "^2.2.3",
    "ionicons": "^3.0.0",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "^0.6.21"
  },
  "devDependencies": {
    "@ionic/app-scripts": "^0.0.36",
    "typescript": "^2.0.3"
  },
  "description": "cat: An Ionic project",
  "cordovaPlugins": [
    "cordova-plugin-device",
    "cordova-plugin-console",
    "cordova-plugin-whitelist",
    "cordova-plugin-splashscreen",
    "cordova-plugin-statusbar",
    "ionic-plugin-keyboard"
  ],
  "cordovaPlatforms": []
}

```

**Comment by jgw96** [comment] 2016-10-17 16:03
Hello, thanks for using Ionic! So the page should be able to be opened with no problem in `ionViewDidLoad`, but it does seem that there is a bug in RC1. It is expected that the page would fail to open in the constructor as the constructor is called before the dom is ready.

**Comment by jgw96** [comment] 2016-10-17 16:04
@manucorporat I was easily able to reproduce this issue by just trying to push a page in `ionViewDidLoad`.

**Comment by manucorporat** [comment] 2016-10-17 22:23
@jgw96 have you tested against master?

**Comment by cquillen2003** [comment] 2016-10-19 01:05
I am having the same problem.  Is there a work around for this?

**Comment by thruthesky** [comment] 2016-10-19 12:26
@cquillen2003  The work around is ... that you can use setTimeout()...

````

setTimeout( () => {
    this.navCtrl.push( PageName );
    } , 400 );

````

**Comment by mohitjdn** [comment] 2016-10-21 15:14
I am having the same problem 
when i tried to push on next page using

 this.navCtrl.push( PageName ); is not working in RC1.

I have also tried with setTimeout function that given below is also not working.

setTimeout( () => {
    this.navCtrl.push(  PageName );
    } , 400 );

please suggest or help me to resolve same.

**Comment by manucorporat** [comment] 2016-10-21 15:29
I think this was already fixed in RC2, but I am not sure. The same issue can have many different root causes.

**Comment by manucorporat** [comment] 2016-10-24 20:25
Can you guys try against nightly?

```
npm install ionic-angular@nightly --save
```

**Comment by thruthesky** [comment] 2016-11-01 10:06
@manucorporat It's working fine now. Thank you.

**Closed** 2016-11-01 10:07 UTC
Labels: v2
