### ISSUE TITLE
I can't install ionic successfully

### ISSUE THREAD

**Issue by blackcater** [driftyco/ionic#6432] opened 2016-05-04 15:49 UTC
My nodejs version is 6.0.0. 
My npm version is 3.8.6

```
..........
In file included from ../src/libsass/src/values.hpp:4:
../src/libsass/src/ast.hpp:2082:18: warning: expression with side effects will be evaluated despite being used
      as an operand to 'typeid' [-Wpotentially-evaluated-expression]
      if (typeid(*(*this)[0]) == typeid(Type_Selector))
                 ^
The error is below
../src/libsass/src/ast.hpp:2101:21: warning: expression with side effects will be evaluated despite being used
      as an operand to 'typeid' [-Wpotentially-evaluated-expression]
             typeid(*(*this)[0]) == typeid(Parent_Selector);
                    ^
2 warnings generated.
.............
make: *** [Release/sass.a] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/ionic/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/ionic/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /usr/local/lib/node_modules/ionic/node_modules/node-sass
gyp ERR! node -v v6.0.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
Build failed
/usr/local/lib
└── (empty)

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "--registry=https://registry.npm.taobao.org" "install" "-g" "ionic"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.4.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.4.2 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/blackcater/npm-debug.log
npm ERR! code 1
FAIL
```

`if (typeid(*(*this)[0]) == typeid(Type_Selector))`. It occurred many times. I can't know how to deal with it!

Someone can help me? Thanks a lot!

**Comment by jgw96** [comment] 2016-05-04 15:57
Hello! Thanks for opening an issue with us! This issue is caused by theversion of node-sass that we are currently using not being compatible with Node 6. We are currently working on full Node v6 compatibility with the Ionic-cli. You can track that progress here: https://github.com/driftyco/ionic-cli/issues/960 . Also, feel free to put info about your bug on that issue so that the cli team can see it. I will be closing this issue as a duplicate of the linked issue. Thanks for using Ionic! (:

**Closed by jgw96** 2016-05-04 15:57 UTC
