### ISSUE TITLE
Screen flickering when using ion-select, popover, navpush and more...

### ISSUE THREAD

**Issue by TheBurgerShot** [driftyco/ionic#10819] opened 2017-03-17 14:23 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The screen flickers on iOS devices with several actions (screen transitions mostly).

When navigating to another screen with the push animation, the new page flashes full screen before entering the screen with the push animation.

When selecting an ion-select the screen appears flickering.

When selecting a popover appears, it appears flickering.

When scrolling through a list of ion-range items with buttons at min and max, the images flicker.

The flickering already occurs in a fresh installed application

![ionic2-flickering](https://cloud.githubusercontent.com/assets/5908466/24047119/14cb1f6a-0b25-11e7-8883-b9cde4bab1d5.gif)

![ionic2-flickering icons 2](https://cloud.githubusercontent.com/assets/5908466/24047237/60dfe278-0b25-11e7-9ed9-f2b02213fdba.gif)

**Expected behavior:**
No flickering, smooth animations like in an iOS Simulator

**Steps to reproduce:**
1. Add a navigation push to your application, a popover or a ion-item.
2. Run on an iOS device (in simulator the bug does not occur)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.0 
ios-sim version: 5.0.10 
OS: macOS Sierra
Node Version: v6.5.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by TheBurgerShot** [comment] 2017-03-21 15:36
I've found out that after factory resetting my device. This problem does not occur anymore. Still this problem occurred consistently before the factory reset so there must be something on somewhere still.

**Comment by jgw96** [comment] 2017-05-15 18:23
Hello! Since this cannot be reproduced anymore I am going to close this issue for now.

**Closed by jgw96** 2017-05-15 18:23 UTC
Labels: v2
