### ISSUE TITLE
Material Design tabs padding should trigger navigation

### ISSUE THREAD

**Issue by wli** [driftyco/ionic#6222] opened 2016-04-18 22:10 UTC
#### Short description of the problem:
When tapping on the padding of a material design tab, it does not trigger navigation.

#### What behavior are you expecting?
Tapping anywhere on the tab should trigger navigation.

**Steps to reproduce:**
1. Create some tabs
2. Use android or emulate in browser with an android user-agent
3. Click on the border and notice that navigation does not happen.

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 The material design button "fill" animation **does** trigger (I believe it's the `<ion-button-effect>` element), but the handler on the `a.tab-button` does not fire.

This is the padding in question (highlighted in yellow):
![image](https://cloud.githubusercontent.com/assets/649892/14621353/e13f3730-0576-11e6-9054-4dd06f648de6.png)

**Which Ionic Version?**
2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.1.1
Ionic Framework Version: 2.0.0-beta.4
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
ios-deploy version: 1.8.5 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.8.0
Xcode version: Xcode 7.3 Build version 7D175

**Comment by wli** [comment] 2016-04-18 22:11
Note: @Ionitron added the `platform:ios` tag, but this is **NOT** a problem in ios.

**Comment by jgw96** [comment] 2016-04-19 05:44
Hello @wli ! So i just did some testing for this issue and unfortunately am unable to reproduce it ): . I am testing with a Nexus 6 running Android N dev preview 2 and a Nexus 7 running Android 6.0.1. The only difference is that I am using Ionic nightly instead of beta.4. Would you mind installing ionic-angular@nightly (`npm rm ionic-angular && npm install ionic-angular@nightly`) and testing again? Thanks!

**Comment by JumBay** [comment] 2016-04-19 12:52
I still can reproduce it in the nightly, but you really need to click on the padding, easier to reproduce on a browser than on a device

**Comment by jgw96** [comment] 2016-04-19 14:34
hmmm, ive tried reproducing in the browser and on devices and do not seem to be having the issue. Which devices have you tested with? And im guessing your using chrome as your browser to test with?

**Comment by wli** [comment] 2016-04-19 17:26
@jgw96 Unfortunately I can still reproduce on nightly. I can repro in Chrome 50.0.2661.49 (using the Nexus 5X or 6P UA). I did note that I cannot reproduce if I don't override my UA to be a mobile phone. In addition, the lower edge corners seems to be the most likely to fail - the left/right padding seem to be okay now, so perhaps it's a different element causing the problem.


```
Cordova CLI: 6.0.0
Ionic Framework Version: 2.0.0-beta.4-201604170622
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
OS: Distributor ID:	Ubuntu Description:	Ubuntu 15.10 
Node Version: v5.8.0
```

**Comment by jgw96** [comment] 2016-04-19 17:33
@wli Hmm, so now the only thing different between our tests is that im using Chrome canary which is at version 52.0.2711.0. I made and attached a screencast showing my results of my test. This is of me emulating a nexus 5x in chrome canary. 
[Untitled Screencast.webm.zip](https://github.com/driftyco/ionic/files/226475/Untitled.Screencast.webm.zip)

**Comment by wli** [comment] 2016-04-19 18:45
Here's the repro on Chrome Canary 52.0.2712.1 With Nexus 5X UA: 
![webm](https://cloud.githubusercontent.com/assets/649892/14651263/099ca444-0624-11e6-9070-52e0e604fc65.gif)

**Comment by jgw96** [comment] 2016-04-19 18:51
@wli Hmmm, can you repro on a device too?

**Comment by wli** [comment] 2016-04-19 19:31
@jgw96 Yep, I can reproduce on a Nexus 6 running the nightly build referenced above.

**Comment by jgw96** [comment] 2016-04-19 19:35
@wli Gonna ask some of my teammates to test and see if they can reproduce cause i cannot reproduce it on any of my devices. Good choice of android device btw (;

**Comment by wli** [comment] 2016-05-26 22:45
FYI - still an issue in beta7, albeit it's much much harder to trigger it now than it was when I filed the bug. You really have to tap the corner. It could be related to https://github.com/driftyco/ionic/issues/6585 also.

**Comment by manucorporat** [comment] 2016-07-02 21:17
@jgw96 #6585 was fixed, do you think it fixed this one?

**Comment by jgw96** [comment] 2016-07-05 15:58
@manucorporat @wli i can confirm that this issue has been fixed with beta.10. Thanks for using Ionic everyone!

**Closed by jgw96** 2016-07-05 15:58 UTC
Labels: platform:android, tabs, v2
