### ISSUE TITLE
bug: Ionic app freeze after sharing text with SMS

### ISSUE THREAD

**Issue by liuborama** [driftyco/ionic#8179] opened 2016-09-23 02:24 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>In ionic app's input box,  press on the text and select All -> Share.
Click the Message icon, then you will go to the message screen.
Cancel or send something and you will come back to the ionic app.
After these . you can do nothing on you ionic app.  freeze.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment] 2016-09-23 15:58
Hello, thanks for using Ionic! Would you be able to provide a repo that i could use to reproduce this issue? Thanks!

**Comment by liuborama** [comment] 2016-09-26 00:43
Hi jgw96
Actually I just create a new ionic tab app with template( use: ionic start myApp tabs).
Then change the last tab with some input box, then you can reproduce this issue.
I just updated my test app at https://github.com/liuborama/ionic8179.
Thank you for your help.

**Comment by liuborama** [comment] 2016-09-30 02:06
Any update on the issues?

**Comment by jgw96** [comment] 2016-10-04 15:33
Hello, thanks for using Ionic! Because this seems to be an issue with custom functionality within your app and not something with the Ionic framework I am going to be closing this issue for now. Thanks!

**Closed by jgw96** 2016-10-04 15:33 UTC
Labels: v1

**Comment by liuborama** [comment] 2016-10-06 01:22
@jgw96 
Did you reproduce this issue? It's sample to reproduce in any ionic app with input.
I tested it can't reproduce in IOS10.
Maybe it's not ionic framework bug but cordova or ios bug.  
but I still not agree with you about it's my app issue. 
Anyway thank you for you answer.
