### ISSUE TITLE
bug: $ionicPopup: field value is not reflected in $scope

### ISSUE THREAD

**Issue by bicpi** [driftyco/ionic#3065] opened 2015-02-09 21:09 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>Using the CodePen from the docs: http://codepen.io/ionic/pen/zkmhJ

I think the the value of the popup input field for the wifi password should be reflected in the `$scope.data.wifi` variable. Extending the promise code to `console.log('Tapped!', res, $scope.data.wifi);` gives `undefined` for `$scope.data.wifi`.

in my application I want to make a scope variable editable using a popup input field but it doesn't work this way.

Is it a bug?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-02-09 21:09
Greetings @bicpi!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3065). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3065)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by olore** [comment] 2015-03-07 22:28
Looks like the problem is that the call to close() isn't passing a result with which to close it with. See http://codepen.io/anon/pen/raZwrP where I call close() within the timeout with $scope.data.wifi

    $timeout(function() {
      myPopup.close($scope.data.wifi); //close the popup after 3 seconds for some reason
    }, 3000);

**Comment by ajoslin** [comment] 2015-04-13 17:40
I don't understand the problem here? It looks like $scope.data.wifi is working, and so is the result passing through close.

**Comment by Ionitron** [comment] 2015-05-14 00:19
Greetings @bicpi!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment] 2015-05-14 00:19
Greetings @bicpi!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-05-14 00:19 UTC
Labels: ionitron:closed
