### ISSUE TITLE
bug: Button style messed up in header when modified

### ISSUE THREAD

**Issue by ErkoKnoll** [driftyco/ionic#6500] opened 2016-05-11 13:55 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>When button is placed in the header and when angular triggers view update it's style will become of the button like its not placed in the header.

Example code:
`
<ion-navbar *navbar>
    <ion-title></ion-title>
    <ion-buttons end>
        <button *ngIf="...">
            <ion-icon name="compass" style="font-size: 30px;"></ion-icon>
        </button>
`

Screenshot where compass icon has ngIf directive and it gets updated after creation.</span>
![buttonbug](https://cloud.githubusercontent.com/assets/9930079/15183331/3cdd9300-1799-11e6-81a3-90cb1ca71a45.png)
<span is-issue-template></span>

**Comment by brandyscarney** [comment] 2016-05-11 15:05
Thanks for the issue! This is a duplicate of https://github.com/driftyco/ionic/issues/5927 so I am going to close this. Please continue the discussion on that issue. :smile:

**Closed by brandyscarney** 2016-05-11 15:05 UTC
Labels: header, platform:android, v2
