### ISSUE TITLE
bug: TypeError: Cannot read property 'index' of undefin

### ISSUE THREAD

**Issue by msevestre** [driftyco/ionic#3359] opened 2015-03-20 02:38 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

**Version** : 1.0.0-rc.0

<span ionic-description>I haven't found a way to reproduce systemically the issue. That's why no codepen is available.

But I managed to get the crash on ios, android and desktop

```
TypeError: Cannot read property 'index' of undefined
    at Object.IonicModule.factory.register (http://localhost:8100/lib/ionic/js/ionic.bundle.js:42182:44)
    at IonicModule.controller.self.register (http://localhost:8100/lib/ionic/js/ionic.bundle.js:47153:38)
    at updateView (http://localhost:8100/lib/ionic/js/ionic.bundle.js:52331:23)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:52308:11
    at Scope.$get.Scope.$broadcast (http://localhost:8100/lib/ionic/js/ionic.bundle.js:22639:28)
    at $state.transitionTo.$state.transition.resolved.then.$state.transition (http://localhost:8100/lib/ionic/js/ionic.bundle.js:40109:22)
    at processQueue (http://localhost:8100/lib/ionic/js/ionic.bundle.js:21108:27)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:21124:27
    at Scope.$get.Scope.$eval (http://localhost:8100/lib/ionic/js/ionic.bundle.js:22320:28)
    at Scope.$get.Scope.$digest (http://localhost:8100/lib/ionic/js/ionic.bundle.js:22136:31) undefined
```

The actual line in code is this one

 `hist.cursor = viewHistory.currentView.index;`

Somehow, currentView is null and the index property is called resulting in the TypeError mentioned above.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-03-20 16:53
Greetings @msevestre!

My sensors indicate that I require more information in order to assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this happen occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com), where many humans will be able to offer wisdom and advice.

Thank you for allowing me to assist you.

<span ionitron-needs-reply></span>

**Comment by msevestre** [comment] 2015-03-20 18:59
Dear @Ionitron,
 
If only your sensors were a bit more up-to-date, you would see that I mentioned in the text of the very issue that I was not able to replicate the issue for a robot like you. 

The issue is there for sure, but appearing only occasionally. 

If I find a step by step workflow allowing you to reproduce the bug, I will for sure create a codepen replicating the issue

>Can you provide a detailed description of this issue?

Navigating in the application, I suddenly get the error described above. I have also attached the stack trace

>How would a robot go about replicating this issue?

If I can figure how a human can replicate the issue, then I am pretty sure that  I'll be able to answer that question

>On which platform does this happen occur? (iOS, Android, all, etc.)

ALL (this was also mentioned in the issue... these sensors of yours definitely need some tune up)

>On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)

Android 4.2, ios 7 and ios8. Chrome . I haven't tried anything else

>Is this an issue with the Ionic Framework or Ionic CLI?

Ionic framework. I have also highlighted the actual line of code causing the bug

**Comment by perrygovier** [comment] 2015-03-24 19:40
Sorry, but if we can't reproduce the issue, we can't really fix it.  We haven't seen it in any our tests, so it's likely there's an edge case in your app that we don't yet cover.  Can you offer us any more info? Does your state config use resolves? Can you share your code with us so we can set up breakpoints? We need more info.

**Comment by odytrice** [comment] 2015-04-17 20:41
I experienced this same bug as well.  Produced the exact same call stack. It happened when I clicked a Tab Button. After correcting some bugs with Angular-Cache, I refreshed and haven't seen it ever since. 

So yeah, @perrygovier there's no way to fix something you can't replicate. Just wanted to share my own experience because it may have nothing to do with ionic in particular.

**Comment by Ionitron** [comment] 2015-04-23 20:22
Greetings @msevestre!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment] 2015-04-23 20:22
Greetings @msevestre!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-04-23 20:22 UTC
Labels: ionitron:closed, navigation

**Comment by msevestre** [comment] 2015-10-06 18:37
the bug has disappeared completely. Thanks

**Comment by Screeze** [comment] 2016-02-27 21:44
I got a similar, also rarely reproducable error:

```
TypeError: Cannot read property 'index' of undefined
    at Object.register (ionic.bundle.js:51373)
    at self.register (ionic.bundle.js:56692)
    at updateView (ionic.bundle.js:62357)
    at ionic.bundle.js:62334
    at Scope.$broadcast (ionic.bundle.js:29477)
    at $state.transition.resolved.then.$state.transition (ionic.bundle.js:49321)
    at processQueue (ionic.bundle.js:27879)
    at ionic.bundle.js:27895
    at Scope.$eval (ionic.bundle.js:29158)
    at Scope.$digest (ionic.bundle.js:28969)(anonymous function) @ 

ionic.bundle.js:25642(anonymous function) @ ionic.bundle.js:22421Scope.$broadcast @ 
ionic.bundle.js:29479$state.transition.resolved.then.$state.transition @ 
ionic.bundle.js:49321processQueue @ ionic.bundle.js:27879(anonymous function) @ 
ionic.bundle.js:27895Scope.$eval @ ionic.bundle.js:29158Scope.$digest @ 
ionic.bundle.js:28969Scope.$apply @ ionic.bundle.js:29263(anonymous function) @ 
ionic.bundle.js:25398eventHandler @ ionic.bundle.js:16583triggerMouseEvent @ 
ionic.bundle.js:2948tapClick @ ionic.bundle.js:2937tapTouchEnd @ ionic.bundle.js:3064

```

My setup contains some views, one side-menu pointing to the views, and a tab control on one of the views.

I get this issue rarely - but sometimes when i navigate between the views using the sidemenu.
Interestingly: When the error occurs once, it seems to get fired every time I switch views, until I reload the app.

**Comment by blablapolicja** [comment] 2016-04-06 15:10
@Screeze +1
I don't use resolves

**Comment by corey-garvin** [comment] 2016-05-11 21:06
I get this error, too, occasionally.  
`hist.cursor = viewHistory.currentView.index;`

Trying to replicate is proving to be hard.

**Comment by thibaultponcelet** [comment] 2016-07-07 13:36
I have exactly the same problem on Ionic 1.3.1
```
ionic.bundle.js:26794 TypeError: Cannot read property 'viewId' of undefined
    at Object.register (http://localhost:8100/lib/ionic/js/ionic.bundle.js:54185:30)
    at self.register (http://localhost:8100/lib/ionic/js/ionic.bundle.js:59708:38)
    at updateView (http://localhost:8100/lib/ionic/js/ionic.bundle.js:65398:23)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:65375:11
    at Scope.$broadcast (http://localhost:8100/lib/ionic/js/ionic.bundle.js:30718:28)
    at $state.transition.resolved.then.$state.transition (http://localhost:8100/lib/ionic/js/ionic.bundle.js:52157:22)
    at processQueue (http://localhost:8100/lib/ionic/js/ionic.bundle.js:29127:28)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:29143:27
    at Scope.$eval (http://localhost:8100/lib/ionic/js/ionic.bundle.js:30395:28)
    at Scope.$digest (http://localhost:8100/lib/ionic/js/ionic.bundle.js:30211:31) undefined
```

It happens when I quickly click on tab links, I'm wondering if I'm not triggering two state changes at the same time?
