### ISSUE TITLE
bug: bug: error message on slide-box when using minified js

### ISSUE THREAD

**Issue by paishin** [driftyco/ionic#3136] opened 2015-02-18 13:41 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When revisiting a page where there is a slide-box I get the following error:

```
TypeError: Cannot read property 'scrollTo' of null
    at ionic.bundle.min.js:344
    at l.promise.then.E (ionic.bundle.min.js:131)
    at ionic.bundle.min.js:132
    at k.$get.k.$eval (ionic.bundle.min.js:143)
    at k.$get.k.$digest (ionic.bundle.min.js:140)
    at k.$get.k.$apply (ionic.bundle.min.js:143)
    at ionic.bundle.min.js:153
    at e (ionic.bundle.min.js:68)
    at ionic.bundle.min.js:72
```

there does not seem to have any bad effects and strangely it disappears when not using the min version</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-02-18 13:41
Greetings @paishin!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3136). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3136)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment] 2015-03-04 18:13
Greetings @paishin!

My sensors indicate that I require more information in order to assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this happen occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com), where many humans will be able to offer wisdom and advice.

Thank you for allowing me to assist you.

<span ionitron-needs-reply></span>

**Comment by paishin** [comment] 2015-03-04 19:17
Hey @Ionitron,

- There is no real issue with this as it causes no side effects, it just throws that error in the console but the app continues to function properly.

- Now, to replicate this issue I have found out that it only occurs when you have an abstract state as the parent and the slide box is in the child state. The first time you open the page with the slide-box no error is shown in the console, navigating to another child state and then back to the first page will give you the error...but only if you are using ionic.bundle.min.js, switching to the normal ionic.bundle.js does not produce the error.

- All platforms

- All

- Ionic Framework and specifically ionic.bundle.*min*.js 


I'll try to create a codepen later to show this error

**Comment by mhartington** [comment] 2015-03-13 20:41
Any luck on that codepen?

**Comment by Ionitron** [comment] 2015-04-12 22:32
Greetings @paishin!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment] 2015-04-12 22:32
Greetings @paishin!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-04-12 22:32 UTC
Labels: ionitron:closed

**Comment by mlynch** [comment] 2015-12-07 06:11
Thanks, this was fixed in a recent commit tonight. Will be in 1.2!
