### ISSUE TITLE
Tabs on Android 4.4.4 does not have active border

### ISSUE THREAD

**Issue by biesbjerg** [driftyco/ionic#7415] opened 2016-07-24 16:48 UTC
#### Short description of the problem:
Tabs on Android 4.4.4 does not have active border.

See screenshot:
![tabs](https://cloud.githubusercontent.com/assets/230182/17085062/155bb364-51cf-11e6-8c9e-4069beab5fc2.png)

Notice there's a hint of a blue border to the far left.

Expected:
![image](https://cloud.githubusercontent.com/assets/230182/17085071/55481e9a-51cf-11e6-8a66-31a023a216b2.png)

**Steps to reproduce:**
1. ionic start tabs --ts --v2
2. ionic run android
 

**Which Ionic Version?** 1.x or 2.x
2.0 beta 10

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.3.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.5
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v4.4.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment] 2016-08-04 21:02
Hello, thanks for opening an issue with us! Would you mind trying this with crosswalk? Thanks for using Ionic!

**Comment by biesbjerg** [comment] 2016-08-04 23:08
I'm on vacation at the moment so won't be able to test it with crosswalk. Anyway, isn't ionic 2 supposed to work on android 4.4+, even without crosswalk?

**Comment by jgw96** [comment] 2016-08-05 02:00
@biesbjerg No problem! You are correct, it is supposed to work on 4.4+ without crosswalk, I just wanted to make sure it was not a problem specific to the webview of your device. Sometimes, especially with older Android device before google got more strict about things, manufacturers would modify the webview (mainly samsung devices) which can cause really weird results. Since crosswalk is a completely stock chrome webview, just like a nexus device or most android devices running 5.0 and higher, it will help rule issues like that out.

**Comment by jgw96** [comment] 2016-08-09 15:47
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue and i will happily reopen. Thanks for using Ionic!

**Comment by biesbjerg** [comment] 2016-08-09 16:24
Did you close this by mistake?

**Comment by jgw96** [comment] 2016-08-09 16:33
Good catch, accidentally closed the wrong issue. Thanks!

**Comment by danbucholtz** [comment] 2016-08-09 19:48
@biesbjerg,

There is something strange going on here.  That's for sure.

Still looking into it.

Thanks,
Dan

**Comment by danbucholtz** [comment] 2016-08-09 19:54
I am seeing this issue even with cross walk in addition to vanilla 4.4.

Going to move this to Beta 12.

Thanks,
Dan

**Comment by jgw96** [comment] 2016-08-09 20:53
Hello all! So after doing a re-test of this with a moto g running 4.4.2 with crosswalk we can solidly say that we cannot reproduce this issue. @biesbjerg i recommend getting rid of your local branch of the conference app, re-cloning it, running `npm install`, running `ionic plugin add cordova-plugin-crosswalk-webview` to add crosswalk and then running `ionic run android`. Also we found that it is very important that you completely uninstall the conference app from your device first. Thanks for using Ionic!

**Closed by jgw96** 2016-08-09 20:53 UTC
Labels: css, platform:android, v2
