### ISSUE TITLE
[v2] SyntaxError: Unexpected Identifier when upgrading to v2.0.0 final (Serve Only)

### ISSUE THREAD

**Issue by Tyler-Darby** [driftyco/ionic#10262] opened 2017-02-01 01:21 UTC
**Ionic version:**  
v2

**I'm submitting a ...**
Bug Report

**Current behavior:**
<img width="1682" alt="screen shot 2017-01-31 at 8 18 18 pm" src="https://cloud.githubusercontent.com/assets/5661936/22491584/8ef5eb4a-e7f2-11e6-881b-31f364d2e723.png">

This error displays itself in Chrome on Ionic Serve. No stack trace, no file, nothing. This appears only in serve and not on device, and after updating to V2.0.0 final. No errors in the serve terminal window. 

The error is simply:
```Uncaught SyntaxError: Unexpected identifier```

**Ionic info:**

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.6 
OS: macOS Sierra
Node Version: v6.9.2
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by Tyler-Darby** [comment] 2017-02-01 18:25
Okay, a new error has appeared!

```
error_handler.js:47 EXCEPTION: [object Object]
ErrorHandler.handleError @ error_handler.js:47
IonicErrorHandler.handleError @ ionic-error-handler.js:56
next @ application_ref.js:272
schedulerFn @ async.js:82
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:74
NgZone.triggerError @ ng_zone.js:278
onHandleError @ ng_zone.js:257
t.handleError @ polyfills.js:3
e.runTask @ polyfills.js:3
invoke @ polyfills.js:3
e.args.(anonymous function) @ polyfills.js:2
```

Still not sure what this means or how to observe it, or if it is a result of something on my end or not.

**Comment by jgw96** [comment] 2017-02-02 15:15
Hello, thanks for using Ionic! Unfortunately i cannot reproduce this error, would you mind posting a plunker or repo i can use to reproduce this issue?

**Comment by Tyler-Darby** [comment] 2017-02-02 16:57
@jgw96 I've discovered it is not isolated to Chrome for me, rather to all browsers on serve. Safari and Firefox gave slightly more descriptive errors.

Safari:
```SyntaxError: Unexpected identifier 'Object'. Expected either a closing ']' or a ',' following an array element.```

Firefox:
```SyntaxError: missing ] after element list  polyfills.js:2:8```

I can't seem to recreate this in a plunkr and am not authorized to share the repo due to confidentiality purposes.

However I have scoured my code up and down and even gone as far as removing every component and service from my app other than the main page which is definitely error free, and it still persists. Not sure what to do.

**Comment by jgw96** [comment] 2017-02-03 15:30
Hmm, this is interesting. Does it happen when you start a brand new v2 app? What version of Ionic 2 is your app running? I cannot reproduce this is in any of our apps and the plunker uses the exact same polyfills as an app you start with the cli, so if the issue is in the polyfills it would happen in the plunker too.

**Comment by Tyler-Darby** [comment] 2017-02-03 16:07
@jgw96 Hmm. Nope, no issue on a brand new app. Could I take the polyfills from a new project and put them in my current app?

**Comment by jgw96** [comment] 2017-02-03 16:15
Yep you could, just look in `www/build` and you should see a `polyfills.js` file in the new app. Simply copy/paste that one over to `www/build` in the app your having the issue in

**Comment by Tyler-Darby** [comment] 2017-02-03 16:34
@jgw96 No dice. When I get home i'll try on my workstation there and see if it is for some reason my system. 

It's caused no issue with my app from what I can tell other than the annoying modal every time I make a change. The part that's really bugging me though is the fact that there's no stack trace. Obviously it's an issue with my project since a fresh one doesn't do it. Just really weird that it doesn't happen on device, only serve.

I'll update later this evening. Thanks!

**Comment by Tyler-Darby** [comment] 2017-02-04 19:43
@jgw96 Did some debugging in Chrome and found that this function from polyfills.js is the function seemingly causing the exception. It's executed immediately before the exception is called. 

```
function h(t, n, e, r) {
                function o(n) {
                    var e = n.data;
                    return e.args[0] = function() {
                        n.invoke.apply(this, arguments),
                        delete c[e.handleId]
                    }
                    ,
                    e.handleId = u.apply(t, e.args),
                    c[e.handleId] = n,
                    n
                }
                function i(t) {
                    return delete c[t.data.handleId],
                    a(t.data.handleId)
                }
                var u = null
                  , a = null;
                n += r,
                e += r;
                var c = {};
                u = l(t, n, function(e) {
                    return function(u, a) {
                        if ("function" == typeof a[0]) {
                            var c = Zone.current
                              , f = {
                                handleId: null,
                                isPeriodic: "Interval" === r,
                                delay: "Timeout" === r || "Interval" === r ? a[1] || 0 : null,
                                args: a
                            }
                              , s = c.scheduleMacroTask(n, a[0], f, o, i);
                            if (!s)
                                return s;
                            var l = s.data.handleId;
                            return l.ref && l.unref && (s.ref = l.ref.bind(l),
                            s.unref = l.unref.bind(l)),
                            s
                        }
                        return e.apply(t, a)
                    }
                }),
                a = l(t, e, function(n) {
                    return function(e, r) {
                        var o = "number" == typeof r[0] ? c[r[0]] : r[0];
                        o && "string" == typeof o.type ? (o.cancelFn && o.data.isPeriodic || 0 === o.runCount) && o.zone.cancelTask(o) : n.apply(t, r)
                    }
                })
            }

```

**Comment by jgw96** [comment] 2017-02-06 17:01
Hello @Tyler-Darby , thanks for all the info! So i just noticed from looking at the screenshot of chrome devtools that you posted that it looks like your using firebase in your app, is this assumption correct? Im asking because it could be possible that this is an error in firebase itself and not in Ionic or our polyfills. This would also explain why you cannot reproduce it in a fresh project. What action is happening in your app before the error happens? Im guessing a call to a firebase function? Also, because there is not repro case for this issue, I am going to close it for now and then once we get a repro case together I will re-open this issue. Again, thanks for all the info and thanks for working with me on this! (:

**Closed by jgw96** 2017-02-06 17:01 UTC
Labels: needs reply, v2

**Comment by Tyler-Darby** [comment] 2017-02-07 14:43
@jgw96 I finally resolved it. The issue was actually with Ionic Native apparently.

The call to `Splashscreen.hide()` in my `app.component.ts` was causing the issue. 

I assume this isn't expected behavior. Should I open up an issue in the ionic-native repo?
