### ISSUE TITLE
ion-item-sliding is buggy

### ISSUE THREAD

**Issue by kumaresan-cgvak** [driftyco/ionic#11224] opened 2017-04-14 12:59 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
View gets hanged/ struck after swiping a list item from the right to reveal buttons. It happens during the first swipe of the List Item alone. So, once of we navigate to another page and try after navigating back to the same page will work properly. it is really tricky. it happens after updating to the latest version of ionic. 

**Expected behavior:**
App Should not hang / struck. List view click events should work after swipe.

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.8.0
Xcode version: Xcode 8.3 Build version 8E162
```

**Comment by jgw96** [comment] 2017-04-14 15:21
Hello, thanks for using Ionic! Could you share a repo that we can use to reproduce this?

**Comment by jgw96** [comment] 2017-04-24 16:17
Hello! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-04-24 16:17 UTC
Labels: needs info, v3
