### ISSUE TITLE
copy: Error copying node_modules/ionic-angular/fonts to www/assets/fonts

### ISSUE THREAD

**Issue by thebasix** [driftyco/ionic#9370] opened 2016-11-27 13:32 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x ] **2.x**

Here ss: https://www.dropbox.com/s/5yzu9u2k4suh5sv/Screenshot%202016-11-27%2014.29.53.png?dl=0

```
Your system information:

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3-201611261840
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.9.1
Xcode version: Not installed
```

**Comment by divanvb** [comment] 2016-11-28 01:48
Same issue

**Comment by jvbianchi** [comment] 2016-11-28 13:26
In my case it started to happen when I updated "@ionic/app-scripts" to version 0.0.46.

Version 0.0.45 works fine.

**Comment by jgw96** [comment] 2016-11-28 17:14
Hello, thanks for opening an issue with us! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic-app-scripts/issues/475.

**Closed by jgw96** 2016-11-28 17:14 UTC
