### ISSUE TITLE
Property 'forChild' does not exist on type 'typeof IonicModule'.

### ISSUE THREAD

**Issue by ngohungphuc** [driftyco/ionic#11082] opened 2017-04-06 07:10 UTC
I'm using the ionic cli to generate the page using this command

> ionic generate page MyTeams

then i get this error

```
Typescript Error
Property 'forChild' does not exist on type 'typeof IonicModule'.
E:/Source Code/Study/Ionic/elite-schedule-app/src/pages/game/game.module.ts
imports: [
  IonicModule.forChild(Game),
],
```

Have anybody encounter with this error ?

**Comment by nadeemmdsol** [comment] 2017-04-06 07:29
I am also facing same issue.

**Comment by ngohungphuc** [comment] 2017-04-06 07:34
@nadeemmdsol  Yes after I'm installed ionic and cordova with this command
> npm install -g ionic cordova

I think they just update the source code

**Comment by nadeemmdsol** [comment] 2017-04-06 07:40
@ngohungphuc  you fixed this ?

**Comment by ngohungphuc** [comment] 2017-04-06 07:42
Still no way to fix this, the module file is generate automatic by ionic cli after we type 

>ionic generate page PageName

**Comment by ngohungphuc** [comment] 2017-04-06 07:43
@nadeemmdsol you can remove this line in the module file

```
imports: [
    IonicModule.forChild(Tournaments),
  ],
```

**Comment by nadeemmdsol** [comment] 2017-04-06 07:45
@ngohungphuc if i create page in Old Project. that works fine.
does not create module.ts file in page folder.
issue coming in new project.

BTW remove or comment that line works fine.

**Comment by ngohungphuc** [comment] 2017-04-06 07:49
Yes i know the scaffold project does not include the module in the page component folder.
The module only generate by new page command.
Hope someone can point out the issue for us

**Comment by nadeemmdsol** [comment] 2017-04-06 08:43
@ngohungphuc  read this. 
http://stackoverflow.com/questions/43248635/property-forchild-does-not-exist-on-type-typeof-ionicmodule/43249252#43249252

but the issue is why this new module is creating.before this was not happening.
Even in old project also working fine, no new module.ts page is creating.

**Comment by surajrao** [comment] 2017-04-06 09:49
https://docs.google.com/document/d/1vGokwMXPQItZmTHZQbTO4qwj_SQymFhRS_nJmiH0K3w/edit# it was introduced for lazy loading.. I think someone made a typo.. should IonicPageModule instead of IonicModule..

**Comment by rapropos** [comment] 2017-04-06 18:37
Dupe of #11076.

**Comment by brandyscarney** [comment] 2017-04-06 21:54
Thanks for the issue! Closing as a duplicate of https://github.com/driftyco/ionic/issues/11076 which has been moved here: https://github.com/driftyco/ionic-cli/issues/2070

**Closed by brandyscarney** 2017-04-06 21:54 UTC

**Comment by Zainab-Ally** [comment] 2017-04-07 14:31
I also tried to remove

imports: [
    IonicModule.forChild(Tournaments),
  ],

now it works
tanx to ngohungphuc

**Comment by ngohungphuc** [comment] 2017-04-07 14:35
@Zainab-Ally you can update ionic cli.Someone have fixed yesterday for this issue

**Comment by vjiayasree** [comment] 2017-04-10 07:26
tanq...for the solution

**Comment by suchigg** [comment] 2017-04-10 14:09
unfortunally, i have the same issue with updated ionic cli:

Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.8.5 
ios-sim version: 3.1.1 
OS: macOS Sierra
Node Version: v4.4.4
Xcode version: Xcode 8.3.1 Build version 8E1000a

Issue with ionic g component Component

**Comment by gahwa** [comment] 2017-04-10 20:11
Referencing the wrong Ionic module, IonicModule which does not have the forChild method. Change your import from IonicModule to IonicPageModule.

**Comment by KhairulAzmi21** [comment] 2017-04-13 07:57
When i run ionic g page <pagename> . 
it will generate 4files . 
file with .module.ts is the problem

**Comment by stcursi** [comment] 2017-04-13 16:05
Is there any way to avoid this "page.module.ts" when I put g page on the command line ? 

I hate it

**Comment by chikehenderson** [comment] 2017-04-16 12:27
I think the best solution at the moment is to use grunt.. any counter solution to that? it's pretty sickening having to keep find and replace..  etc..

**Comment by surajrao** [comment] 2017-04-18 14:34
check this driftyco/ionic#11077  Update ionic-angular . As mentioned :

it will be in the next Ionic release. You could also just copy/paste the change into node_modules/ionic-angular/templates.
