### ISSUE TITLE
Android perfomance (list scroll - ng-repeat)

### ISSUE THREAD

**Issue by zelphir** [driftyco/ionic#1322] opened 2014-05-09 15:06 UTC
I'm having performance issues on android devices (HTC ONE, HTC ONE M8, so top gamma) and android emulators (official one using GPU and x86 as cpu arch and genymotion).

Basically I have just a simple list of ten elements with an image (different images). On iOS is super fast and smooth (both simulator and iphone), on Android is super slow, buggy and randomly crashes the app (if I scroll too fast).

The images are 800x800px scaled with css width:100% to fit the list width.

**Comment by Ionitron** [comment] 2015-01-19 22:35
Greetings!

My sensors indicate a reply was requested, however, since we have not received one yet, this will be closed. If you are still experiencing this issue, please feel free to reopen it and include any information that may have been requested.

Thank you!

**Comment by arsenslyusarchuk** [comment] 2015-01-20 08:23
Actually Ionic was created to work fine on IOS but not on Andriod. Since andriod 4.4 (kitkat) it has really better and faster browser which speeds up Ionic very noticeable. But still it is funny that on IPhone4 it works smoothly while on nexus5 it lags.
In my case I have just refused from infinite scroll and created 'Show more' button.
So u can also try to remove some effects (I mean additional directives) from your app one by one to improve performance. Plus, for Ionic it's very important to follow the page structure, so read the docs carefully.

**Comment by arsenslyusarchuk** [comment] 2015-01-20 08:24
Ionic app takes from 50 to 150 mb of Ram. So maybe your lags are because of lack of RAM ?

**Comment by ajoslin** [comment] 2015-02-06 20:31
Have you guys tried crosswalk?

**Comment by Ionitron** [comment] 2015-02-07 05:30
Sorry, but his issue has become too vague and is not narrowed into one specific problem. The team recently removed JS scrolling for Android (testing requested: http://forum.ionicframework.com/t/native-scrolling-android-testers-wanted/17059), and made it easy to use Crosswalk from the CLI: http://ionicframework.com/blog/crosswalk-comes-to-ionic/

Additionally, there have many releases since this issue was created with performance improves, caches views, caches templates, and has had a pull to refresh overhaul. Since everyone's app is different, I'm going to close this topic. I'm not denying there aren't any issues, but please create any recreate an issue focused to specific and reproducible problem.

**Closed by Ionitron** 2015-02-07 05:30 UTC
Labels: android, ionitron:closed, scroll

**Comment by karneaud** [comment] 2015-02-24 15:05
Been having the same issue using .14-beta build ....built this trail demo http://kendallarneaud.me/mobile/android/AATT/version/0.0.2.3/ using `ion-content` `ion-infinite-scroll` and `ng-repeat` with at most 300 items loading 10 at a time. On an iPhone4 it crashes on a Android 4 tablet it is sluggish. So there is mos def something wrong with the framework. Looking through this issue i'm going to try some of your suggested workarounds and see if it helps

**Comment by Alexintosh** [comment] 2015-03-03 18:48
I'm having huge scroll problems too, just 30 items list with images. Actually using 
collection-repeater 
overflow-scroll="true"
PTR (seems better without) 
crosswalk
on
Cordova CLI: 4.3.0
Ionic Version: 1.0.0-beta.14
Ionic CLI Version: 1.3.11

**Comment by oaleynik** [comment] 2015-03-14 17:24
Crosswalk works way better for me. Tested on Xperia Z, Android KitKat 4.4.4

**Comment by karneaud** [comment] 2015-03-14 22:26
@Alexintosh what version test devices you use? although it gets buggy with Android 4.0 and iPhone 4 iOS 7 it was noted to work fine with iPhone 5s with iOS 8

**Comment by Alexintosh** [comment] 2015-03-19 15:13
I'm using Nexus 5 stock rom with android 5.0.1

**Comment by karneaud** [comment] 2015-03-19 17:08
Wow....that really is bad...i suggest a new framework

**Comment by 1424667164** [comment] 2015-10-11 06:13
...

**Comment by juan-orca** [comment] 2016-05-08 21:16
@Alexintosh I am on Nexus 5 as well and am having issues with ~10 items of images. However, my friend has the iphone6 and it works great on his
