### ISSUE TITLE
Cannot run unit tests

### ISSUE THREAD

**Issue by alan-agius4** [driftyco/ionic#8341] opened 2016-09-30 08:03 UTC
I am trying to create a Unit Test in your library for another PR I did #8340
![image](https://cloud.githubusercontent.com/assets/17563226/18984713/60dd6a80-86f4-11e6-83b2-6315a3ef8f1e.png)
#### Short description problem:

When I try to run gulp test I am getting an error

OS: Windows 7
Node: 6.1.0
NPM: 3.9.5

Also I think you should update "https://github.com/driftyco/ionic/blob/master/.github/CONTRIBUTING.md" as  gulp task "karma" doesn't exist any more, and it seems it was replaced with gulp test.

Thanks

**Comment by jgw96** [comment] 2016-09-30 16:44
Hello, thanks for using Ionic! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic-app-scripts/issues/51.

**Comment by alan-agius4** [comment] 2016-09-30 16:52
Just for clarity I am not trying to unit test an application but rather the actual ionic 2 repo

**Comment by jgw96** [comment] 2016-09-30 17:29
Ahh, sorry about that! Repoening

**Comment by DevVersion** [comment] 2017-01-11 17:11
Just ran into the same issue on windows - Created a PR to solve this issue.

**Closed** 2017-01-12 18:28 UTC
Labels: v2
