### ISSUE TITLE
Accidental clicks when scrolling

### ISSUE THREAD

**Issue by ptrwtts** [driftyco/ionic#2223] opened 2014-09-16 17:36 UTC
With momentum based scrolling, the user will often stop scrolling by "grabbing" the page to hold it in place and read something. However, in Ionic, their "grab" is counted as a "click". In a scrollview with lots of links (e.g. a Twitter feed), this causes lots of unintentional clicks. Most native apps (Twitter, Facebook, etc) ignore any clicks while the page is moving. Ionic should do the same.

If there is a way disable these clicks manually (e.g. by checking if the scrollview is moving, then ignoring clicks), that could be a temporary solution.

**Comment by adamdbradley** [comment] 2015-02-09 17:22
Duplicate of https://github.com/driftyco/ionic/issues/1438

**Closed by adamdbradley** 2015-02-09 17:22 UTC
Labels: ready, scroll, tap/click
