### ISSUE TITLE
bug: Android transitions break tap.js interceptions

### ISSUE THREAD

**Issue by marekkalnik** [driftyco/ionic#3649] opened 2015-04-30 19:05 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Codepen: http://codepen.io/marekkalnik/pen/dooRJK
Platform: iPhone 6 (device and emulator)

Symptoms: When the button "log in" is clicked, and the users switches page to the form the keyboard shows by itself.

The faulty line in my code seems to be the one that activates android transitions: 

     $ionicConfigProvider.views.transition('android');

When the debugger is activated in https://github.com/driftyco/ionic/blob/master/js/utils/tap.js#L336 the logged element is INPUT instead of SPAN, so my guess is that the "ghostclick" is fired after the transition and somehow triggers the focus of iOS keyboard listener despite being prevented.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-04-30 19:05
Greetings @marekkalnik!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3649). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3649)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by tlancina** [comment] 2015-05-01 18:52
Try adding a [click block](https://github.com/driftyco/ionic/blob/master/js/angular/service/clickBlock.js) when you log in, this is what we use for modals: https://github.com/driftyco/ionic/blob/master/js/angular/service/modal.js#L134.

Honestly it would be great if there was a way to stop these at the event level, but tap is a very fickle thing to mess with. @perrygovier would there be any issues with adding click block to all nav transitions?

**Comment by perrygovier** [comment] 2015-05-08 19:31
@tlancina, lets play with it after the 1.0

**Comment by tlancina** [comment] 2015-12-07 20:24
Hey is this still an issue? I'm unable to reproduce on the latest.

**Comment by kinkaz** [comment] 2016-01-15 15:56
I can reproduce this issue on iOS 9 (and I had this bug on previous versions).

When I click on a link (page A), if there is an input field on the next page (page B) at the exact spot of my link (page A), the field is focused and the keyboard opens. It's as if the click is still fired even after the transition to the next page happened.

I can solve this issue by deleting this line in my app config : $ionicConfigProvider.views.transition('none');

Is there a way to fix this ?

**Comment by Ionitron** [comment] 2016-01-18 18:34
Greetings @marekkalnik!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment] 2016-01-18 18:34
Greetings @marekkalnik!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by ananda-naphade** [comment] 2016-02-22 05:34
Use of data-tap-disabled="true" on element solve my problem.

http://ionicframework.com/docs/api/page/tap/

**Comment by jgw96** [comment] 2016-04-01 17:15
Hello! Are you still experiencing this issue?

**Comment by jgw96** [comment] 2016-04-06 14:40
Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to respond back if your still having the issue! Thanks again

**Closed by jgw96** 2016-04-06 14:40 UTC
Labels: needs reply
