### ISSUE TITLE
Shadow below ion-toolbar in sliding menu not displayed correctly

### ISSUE THREAD

**Issue by carstenbaumhoegger** [driftyco/ionic#10314] opened 2017-02-04 17:33 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I'm using a sliding side menu in one of my apps. When I'm opening the App with an Android phone, the shadow below the `ion-header` doesn't show while the menu is sliding out and is only displayed when the menu is revealed completely.

**Expected behavior:**
The shadow is always visible in the sliding process.

**Steps to reproduce:**
Create an App with a sliding menu and open it in Chrome on Android.
I used a Nexus 5X with Android 7.1.2 and Chrome 56

**Related code:**
I used this code to generate the menu.

```
<ion-menu [content]="content">
  <ion-header>
    <ion-toolbar>
      <ion-title>App title</ion-title>
    </ion-toolbar>
  </ion-header>

  <ion-content>
    ....
  </ion-content>

</ion-menu>

<!-- Disable swipe-to-go-back because it's poor UX to combine STGB with side menus -->
<ion-nav [root]="rootPage" #content swipeBackEnabled="false"></ion-nav>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
```
Cordova CLI: Not installed
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.9.4
Xcode version: Not installed

```

**Comment by jgw96** [comment] 2017-02-06 17:23
Hello, thanks for opening an issue with us! Unfortunately i cannot reproduce this with our [conf app demo](https://github.com/driftyco/ionic-conference-app) which uses a sidemenu. I am testing this on a Nexus 6 running Android 7.1.1 with the latest stable chrome webview (56). Could you post a repo i could use to reproduce this?

**Comment by carstenbaumhoegger** [comment] 2017-02-06 22:27
Hello @jgw96 
I can reproduce this behavior with the [Sidemenu-Starter](https://github.com/driftyco/ionic-starter-sidemenu) sample!
Simply follow these steps:

- run the sample with `ionic serve`
- open Page 1
- open Page 2
- now you notice a small (few px wide) dark shadow below the toolbar of Page Two
- open the menu --> shadow only shows, when menu is completely revealed

I use the Nexus 5X with Android 7.1.2 and Chrome 56, but on Android 7.1.1 I had the same behavior a few days ago.

I hope this description helps you to reproduce the issue!

Here are some screenshots:

notice the weird shadow in the top left below the toolbar
![weird shadow below toolbar](https://cloud.githubusercontent.com/assets/4333261/22668696/ecda97dc-ecc1-11e6-9a9e-e7461e435d44.png)

no shadow while revealing the menu
![menu not completely revealed without shadow](https://cloud.githubusercontent.com/assets/4333261/22668639/b280a34c-ecc1-11e6-87ad-1fa51a895112.png)

shadow appears when menu is completely revealed
![menu revealed with shadow](https://cloud.githubusercontent.com/assets/4333261/22668721/14d2186e-ecc2-11e6-9d9d-af955fbf43dd.png)

**Comment by jgw96** [comment] 2017-02-07 21:45
Ahh, i was misunderstanding which shadow you were talking about, sorry about that! Thanks for all the info and the screenshots. I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/6416.

**Closed by jgw96** 2017-02-07 21:45 UTC
Labels: needs reply, v2

**Comment by carstenbaumhoegger** [comment] 2017-02-08 09:49
Alright! Sorry that I didn't find that issue by myself 🙈

**Comment by armenbadalyan** [comment] 2017-04-21 16:51
I don't think these two issues are the same. [6416](https://github.com/driftyco/ionic/issues/6416) is about the little shadow being shown in the corner of the screen. This issue is about the side menu border flickering. And I can still reproduce it.

**Comment by carstenbaumhoegger** [comment] 2017-04-25 18:40
yes @armenbadalyan you are right. 
I think these two bugs are connected somehow, but I described the shadow flickering and not the grey square appearing below the toolbar.

**Comment by renjit00** [comment] 2017-09-21 16:32
Hi, 
Even i am facing the same issue in my chrome and Mobile device.how to fix issue please lead to resolve the issue. anybody can give the replay means its very grateful..

**Comment by untmat** [comment] 2017-10-18 19:25
I am still facing this issue (Ionic 3.3.0).

To fix it in the meantime, add this css to your side menu header:
```
background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAHBAMAAADzDtBxAAAAD1BMV…h/TXEAAAAaSURBVAjXYxCEAgY4UIICBmMogMsgFLtAAQCNSwXZKOdPxgAAAABJRU5ErkJggg==");
```

**Comment by jlcasasg** [comment] 2017-12-27 01:17
Hi! any solution?
