### ISSUE TITLE
bug: Modal called from tab breaks ion-segment

### ISSUE THREAD

**Issue by killerchip** [driftyco/ionic#6450] opened 2016-05-05 19:27 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>browser</span>

<span ionic-description>How to reproduce issue.

1. Create an app based on 'Tabs' template
2. Create modal page (with just a close button)
3. In Tab 1 page implement an ion-segment with 2 or more segments
4. Have one of the Tabs opening the modal (using (select) event)
5. While on Tab 1, click the tab that opens the modal (see step 4)
6. When closing the modal the ion-segment in Tab 1 page does not update its content when switching.

Code that reproduces the issue:
https://github.com/killerchip/ionic2-tab-modal-segment-bug</span>

<span is-issue-template></span>

**Comment by killerchip** [comment] 2016-07-21 19:50
Hello. May I kindly ask for a status update on this? Has it been confirmed as bug?

Thank you very much in advance.

**Comment by jgw96** [comment] 2016-07-21 19:58
Hello! Sorry for the delay on this, does it still happen for you with beta.10? Thanks for using Ionic!

**Comment by killerchip** [comment] 2016-07-21 20:13
Unfortunately, yes.

**Comment by jgw96** [comment] 2016-08-22 16:46
Hello! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/7769 as it will be fixed with that issue. Thanks for using Ionic!

**Closed by jgw96** 2016-08-22 16:46 UTC
Labels: modals, v2
