### ISSUE TITLE
Select no longer working on android devices

### ISSUE THREAD

**Issue by RobGordon406** [driftyco/ionic#8666] opened 2016-10-13 02:22 UTC
Using Ionic 1 (   ported to Meteor https://github.com/meteoric/meteor-ionic)
as of last week, on Android devices only (iOS functionality is still ok), select components can only be opened by clicking on the far edge of the label.
```
                          <label class="item item-input">
                            <span class="input-label">Physio</span>
                            <select class="selectPhysio">
                                   <option value="">None</option>
                                   <option value="">All</option>
                            </select>
                          </label>
```
As mentioned the functionality is fine for all IOS devices.

I have tried the workarounds such as Issue #836 (https://github.com/driftyco/ionic/issues/836) 
and (https://forum.ionicframework.com/t/select-not-working-on-android/1255/3) but to no avail.

However Issue #5792   Dropdown list "Tap" is not working on Blackberry does provide a solution.
If I comment out line  Line no: 2978 see below - then the issue is resolved.

Question? 
How do Implement this in Meteor?

```
function tapTouchEnd(e) {
  //console.log('touchend ' + Date.now());
  if (tapIgnoreEvent(e)) return;

  tapEnableTouchEvents();
  if (!tapHasPointerMoved(e)) {
    tapClick(e);

    if ((/^(select|option)$/i).test(e.target.tagName)) {
      //e.preventDefault();  // Line no: 2978, commented
    }
  }

  tapLastTouchTarget = e.target;
  tapTouchCancel();
}
```

**Comment by jgw96** [comment] 2016-10-13 19:57
Hello, thanks for using Ionic! I am going to close this one as a duplicate of https://github.com/driftyco/ionic/issues/8181.

**Closed by jgw96** 2016-10-13 19:57 UTC
