### ISSUE TITLE
Displays sidemenu ion-nav-bar as white (android), or grey (iOS) on transition to next view that contains an ion-nav-bar

### ISSUE THREAD

**Issue by mtpultz** [driftyco/ionic#8581] opened 2016-10-08 22:03 UTC
#### Short description of the problem:
Transitioning from a sidemenu view to another route that uses an ion-nav-bar the sidemenu disappears (and appears white) due to a transition in `_transition.scss` for caching?... Actually seems to be due to the addition of `.hide` to the ion-nav-bar of the sidemenu, which causes a "flash" of white during these routes (android). Unlike routes that don't contain an ion-nav-bar, which transition and maintain bar colour.  This occurs in Android, but also shows up in iOS, but instead of white the bar goes grey.

![image](https://cloud.githubusercontent.com/assets/599498/19216405/0f6a4bc4-8d6f-11e6-9114-e4221275c7c3.png)

@see https://codepen.io/mtpultz/pen/gwZPZg?editors=1000

#### What behavior are you expecting?
Consistent transition between views regardless of the use of ion-nav-bar as it is noticeable by users.  Seems like this could be solved using some sort of transition that fades the content of the sidemenu ion-nav-bar, but maintains the bar colour, then fade in next ion-nav-bar.

**Steps to reproduce:**
1. Create a sidemenu project with a list that routes to different views
2. One view have an ion-nav-bar
3. One view don't have an ion-nav-bar
4. Switch between sidemenu to with ion-nav-bar and sidemenu to without ion-nav-bar to observe differences

```
// See CodePen @see https://codepen.io/mtpultz/pen/gwZPZg?editors=1000
```

**Which Ionic Version?** 1.3.1

#### Plunker that shows an example of your issue
https://codepen.io/mtpultz/pen/gwZPZg?editors=1000

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.3.1
Gulp version:  CLI version 1.2.2
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS:
Node Version: v6.3.0

**Comment by jgw96** [comment] 2016-10-10 15:57
Hello, thanks for opening an issue with us! I am going to be closing this issue for now as it is a duplicate of https://github.com/driftyco/ionic/issues/8060.

**Closed by jgw96** 2016-10-10 15:57 UTC

**Comment by mtpultz** [comment] 2016-10-10 17:20
Hi @jgw96 I think if you read the issue then read the other and look at the examples and the version you'll find we aren't talking about the same thing.

**Comment by mtpultz** [comment] 2016-10-11 00:40
@jgw96 this issue seems to have been closed prematurely similar to the issue you linked.  

Reading all the posts down the issue you linked doesn't describe the ion-nav-bar being hidden on the out going view on the left when viewing the example in codepen I put together if the image wasn't enough.  Looking at my screen shot (or codepen) the left hand side ion-nav-bar looks white (when it should be red), and it isn't even there since `.hide` was immediately with no transition applied on route.

**Comment by mtpultz** [comment] 2016-10-14 20:22
@jgw96 I'm sure you're busy, but can you review this and confirm it is not the same issue so it at least sits open.

**Comment by mtpultz** [comment] 2016-11-07 22:08
@jgw96 I'm assuming this is never going to be reviewed? and Ionic isn't focused on any fixes for 1.3.x till everything on 2.x is finished, and even then since this hasn't been reopened, even with the solution you indicated not applying, it won't be investigated regardless.

**Comment by kensentell** [comment] 2016-12-27 16:14
@mtpultz Did you ever find a solution to this? I'm having the exact same issue and can't figure out a way around it.

**Comment by mtpultz** [comment] 2016-12-29 10:36
No, I ended up just frustrated with it after many attempts. After spending the following month talking to myself in this post trying to get it reopened and being ignored it is still an issue it is still a blemish in the application 3 mo that later.
