### ISSUE TITLE
Bug on nav ionic element on EMUI 3.1 (Android 5.1.1)

### ISSUE THREAD

**Issue by gtzinos** [driftyco/ionic#8210] opened 2016-09-26 09:27 UTC
Hello,
I used mdi icons (material icons) and i have a problem with device Android 5.1.1 - EMUI 3.1. The issue is that the icons aren't centered.

I have this code:

    <nav mfb-menu position="br" effect="slidein-spring" active-icon="ion-close-round" resting-icon="ion-plus-round" toggling-method="click">
		<button mfb-button class="blue" icon="mdi mdi-book-open-variant" ng-click="loadMobileContacts()" label=""></button>
		<button mfb-button icon="mdi mdi-account-circle" ui-sref="app.createclient" label=""></button>
    </nav>

Please check this print screen:

http://prntscr.com/cmff01

**Comment by jgw96** [comment] 2016-09-28 16:53
Hello, thanks for using Ionic! Is this with ionic? Are you using our buttons?

**Comment by gtzinos** [comment] 2016-09-30 07:06
Yes, are ionic elements. They are working fine on other devices except of EMUI 3.1  (Android version 5.1.1)

**Comment by jgw96** [comment] 2016-10-03 01:10
Hmm, i am unfortunately not able to reproduce this issue on my Moto X 2014 running stock Android 5.1.1. Most likely this is an issue with the webview of that specific huawei device. Unfortunately some device manufactures customize Android to the point of implementing changes in the webview which can cause weird issues such as this. Can you post a repo that I can use to reproduce this issue? Thanks!

**Comment by gtzinos** [comment] 2016-10-03 15:42
Please contact them for support ( http://emui.huawei.com/en/ )

**Comment by jgw96** [comment] 2016-10-17 16:27
Hello @gtzinos ! Does this issue also happen in the android emulator?

**Comment by gtzinos** [comment] 2016-10-20 11:40
I have tested on other devices but they were okay.

**Comment by jgw96** [comment] 2016-10-20 16:22
Hello, thanks for the info! Since this only seems to be reproducible on certain huawei devices i am going to close this issue for now and recommend that you use crosswalk. Crosswalk gives you the latest stock chrome webview no matter what device the app is running on.

**Closed by jgw96** 2016-10-20 16:22 UTC
Labels: menus, needs reply, platform:android

**Comment by gtzinos** [comment] 2016-10-20 17:53
You can't find a device or an emulator to reproduce the problem and you just close the issue ? Nice management !!!
