### ISSUE TITLE
Popover : Dismiss on backdrop click not working when the backdrop is Google Maps

### ISSUE THREAD

**Issue by Julieng50** [driftyco/ionic#11044] opened 2017-04-04 11:48 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Using Google Maps Cordova (native) + Popover, the click on backdrop does not dismiss the popover (the map is the background)

**Expected behavior:**
While popover is shown, a click on the map should close the popover.

**Steps to reproduce:**
Create a simple Google Maps native that takes 100% of height and width.
Create a popover in the navbar.
Click on the popover and try to close it by clicking on the map.
I know that the map is not an HTML element but is not there a way to close the popover anyway by clicking on the backdrop ?

Edit : I forgot to say that the backdrop is unusable, I cannot click on it

Thanks.

**Comment by jgw96** [comment] 2017-04-04 15:21
Hello, thanks for using Ionic! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/9318 as both of these issues are caused by the same underlying issue.

**Closed by jgw96** 2017-04-04 15:21 UTC

**Comment by Julieng50** [comment] 2017-04-05 09:21
Yes but the other issue has a solution.
To summarize, we could never use Popover with a map ?
