### ISSUE TITLE
Splash screen & icon are not generated at the right place

### ISSUE THREAD

**Issue by danielsawan** [driftyco/ionic#9270] opened 2016-11-21 19:07 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

At the end of the build the icon are copied to "/res" (cf http://i.imgur.com/2uWixRM.png) instead of "/platforms/android/res" (cf : http://i.imgur.com/yAyRf8A.png)

And then the splash screen and icon are the default cordova one.

**Expected behavior:**

At the end of the build the icon are copied to "/platforms/android/res" (cf : http://i.imgur.com/yAyRf8A.png)

**Steps to reproduce:**

on version 2.1.12 
1 - you generate new icon & splashscreen : ionic resources
2 - then build : ionic build android

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.0.0
Xcode version: Not installed
```

**Comment by rodriguesgm** [comment] 2016-11-22 00:21
having the same problem here

**Comment by rodriguesgm** [comment] 2016-11-22 00:30
as a workaround you can try this https://github.com/driftyco/ionic-cli/issues/1166

**Comment by danielsawan** [comment] 2016-11-22 12:38
@rodriguesgm try this

```
ionic platform rm android
ionic platform add android@latest
ionic resources
ionic build android
```

this worked for me

**Comment by rodriguesgm** [comment] 2016-11-22 21:32
@danielsawan it worked too. Not the push notification icon as the other solution, but the app icon and splash images were ok

**Comment by jgw96** [comment] 2016-11-23 17:54
Hello all! Thanks for using Ionic. So this was an issue with a cordova android release not long ago that has since been fixed by the cordova team. The fix here is to install the latest android cordova platform as @danielsawan showed above. Thanks!

**Closed by jgw96** 2016-11-23 17:54 UTC
Labels: v2

**Comment by rodriguesgm** [comment] 2016-11-25 00:18
@jgw96 the only problem is that even with the latest android, the icons for notifications are not working.
It seems the build is not copying the custom icon for notifications to the android res folder. If I manually create the folder drawable-hdpi, drawable-ldpi, etc... and add the icon inside of those folders, the notification icon appears correctly on the android bars.

This is the res structure generated on android platform folder
![structure-android](https://cloud.githubusercontent.com/assets/10141664/20611439/807976d6-b291-11e6-9db0-5eae6ae307ca.jpg)

This is my folder with the icon, splash icon and notifications icon
![structure](https://cloud.githubusercontent.com/assets/10141664/20611456/cb366670-b291-11e6-9b07-5a620392cd6e.jpg)

And this is the wrong behavior i'm having with the icons for noticications
![icon](https://cloud.githubusercontent.com/assets/10141664/20611459/db07dd40-b291-11e6-900a-6592ccc29df3.jpg)

So, I don't know if this is some issue of ionic buid, or from cordova android, or if it's not a bug and I should add a new configuration, because it was working before Ionic RC0.

any help?

**Comment by rodriguesgm** [comment] 2016-11-25 01:15
@jgw96 OK, just saw here my mistake... it was a task on gulp that copied the files.. since Ionic stopped using gulp I need to add some other config to copy those files... thanks and sorry
