### ISSUE TITLE
I need to tap twice to trigger the event

### ISSUE THREAD

**Issue by devfelipereis** [driftyco/ionic#11616] opened 2017-05-11 17:44 UTC
**Ionic version:** 
[x] **1.x**
[ ] **2.x**
[ ] **3.x**

**I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I need to tap twice(fast) to trigger the event(to open menu, any button in my screen, etc...).

**Expected behavior:**
One tap to trigger the event.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
ios-deploy version: Not installed
ios-sim version: Not installled
OS: macOS Sierra
Node Version: v7.9.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

It has the same behavior on emulator and device(iOS). On Android it's working fine.

**Comment by jgw96** [comment] 2017-05-11 17:55
Hello, thanks for using Ionic. Could you post a repo we could use to reproduce this?

**Comment by devfelipereis** [comment] 2017-05-11 18:01
Hello! It's a private project, I can not post any code here :/

**Comment by jgw96** [comment] 2017-05-11 18:37
Thats fine, no need to post a full project, in fact that would make triaging this issue hard. If you could just post a minimal repo that reproduces this issue that would be great!

**Comment by daveshirman** [comment] 2017-05-14 10:07
Add the `tappable` attribute to your element.  It's likely you've got the same problem I had, here's my blog post about it:

[http://www.codingandclimbing.co.uk/blog/ionic-2-fix-ios-side-menu-double-tap-bug](http://www.codingandclimbing.co.uk/blog/ionic-2-fix-ios-side-menu-double-tap-bug)

**Comment by jgw96** [comment] 2017-05-15 15:22
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic! 

PS: nice blog post @daveshirman !

**Closed by jgw96** 2017-05-15 15:22 UTC
Labels: needs info, v2

**Comment by patrickmcd** [comment] 2017-05-15 16:07
@daveshirman re: your blog post, I don't think suggesting `tappable` for `ion-item` is good advice.

Rather, those should be converted to `<button ion-item>`, while reserving `tappable` for out-of-the-ordinary use cases.

**Comment by daveshirman** [comment] 2017-05-15 16:13
But if you've got items that you need tap actions on that simply aren't
buttons then that's your only choice. I don't see what the issue is?

On 15 May 2017 5:08 pm, "Patrick McDonald" <notifications@github.com> wrote:

@daveshirman <https://github.com/daveshirman> re: your blog post, I don't
think suggesting tappable for ion-item is good advice.

Rather, those should be converted to <button ion-item>, while reserving
tappable for out-of-the-ordinary use cases.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/driftyco/ionic/issues/11616#issuecomment-301522818>,
or mute
the thread

**Comment by chandanch** [comment] 2017-05-15 16:14
For components that are clickable we must add the `tappable`attribute. Or you can also use the `tap` event.
