### ISSUE TITLE
bug: Only 1000 plugin calls?

### ISSUE THREAD

**Issue by jmaylin** [driftyco/ionic#3563] opened 2015-04-20 09:45 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>It seems that after about 1000 plugin calls, nothing happens (the memory usage keeps rising though). In a pure Cordova app, the bug doesn't occur.

I've opened an [issue](https://github.com/driftyco/ionic/issues/3522) few days earlier, and @tlancina told me that the bug was probably caused by [https://issues.apache.org/jira/browse/CB-8002](https://issues.apache.org/jira/browse/CB-8002). Except this bug has already been fixed.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-04-20 09:45
Greetings @jmaylin!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3563). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3563)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment] 2015-04-24 21:22
Ionic calls Cordova plugins automatically if they're available. Some a part of the watch cycle and get called often. Can you confirm what version of Cordova your project is using? Also, can you share a codepen or do you also see this in a blank starter project?

**Comment by jmaylin** [comment] 2015-04-27 20:01
@perrygovier I'm using Cordova 4.3.0

The codepen doesn't do much because we cannot use cordova in the browser. The only relevant part of the code was this:
```
$interval(function() {
	navigator.geolocation.getCurrentPosition(function(position) {
		console.log('Plugin call number', i);
	});
	i++;
}, 10);
```
Note: The use of the geolocation plugin is just an example.

**Comment by perrygovier** [comment] 2015-05-20 21:55
You can start a project based on a codepen with `ionic start myapp http://codepen.io/ionic/pen/odqCz`. 

I'm having trouble reproducing the issue. Could you share a sample project in some way to help us recreate it in a way we can inspect and debug?

**Comment by jmaylin** [comment] 2015-05-23 15:13
I've already created a codepen: [http://codepen.io/jmaylin/pen/vEoXzR](http://codepen.io/jmaylin/pen/vEoXzR), but the code needs to be executed on an actual phone if you want to see the bug (I've only tested on iPhones, not Android phones).

Note: My demo requires the installation of the geolocation plugin `cordova plugin add org.apache.cordova.geolocation`

**Comment by Ionitron** [comment] 2015-08-21 15:35
Greetings @jmaylin!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-08-21 15:35 UTC
Labels: ionitron:closed
