### ISSUE TITLE
bug: Can't open alert with many radio inputs in iOS

### ISSUE THREAD

**Issue by MatanYed** [driftyco/ionic#8121] opened 2016-09-19 14:35 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>Because there is no official number picker in ionic 2, i created my own number picker which is alert with radio inputs, example in ionic lab:
http://oi65.tinypic.com/33ndyzt.jpg

In my galaxy note 5 it's working fine, but in Ionic View - iphone 6 plus, it's not working at all and destroy the page structure(design) for 1-2 sec and back to normal.

Code:
```
	openAgeSelect(): void {
		this.translateService.get(['intro.steps.age.ageSelectTitle', 'global.alerts.okButton', 'global.alerts.cancelButton']).subscribe((translatedTexts) => {
			let agesInputs = [];
			for(let i = this.appSettings.validations.age.min; i <= this.appSettings.validations.age.max; i++) {
				let inputChecked = false;
				if(this.user.age === i) {
					inputChecked = true;
				}
				agesInputs.push({
					type: 'radio',
					label: i.toString(),
					value: i,
					checked: inputChecked
				});
			}

			let ageSelectAlert = this.alertCtrl.create({
				title: translatedTexts['intro.steps.age.ageSelectTitle'],
				inputs: agesInputs,
				buttons: [
					{
						text: translatedTexts['global.alerts.cancelButton']
					},
					{
						text: translatedTexts['global.alerts.okButton'],
						handler: age => {
							if(age && age >= this.appSettings.validations.age.min && age <= this.appSettings.validations.age.max) {
								this.user.age = age;
								this.goNextSlideWithDelay();
							}
						}
					}
				]
			});
			ageSelectAlert.present();
		});
	}
```
</span>

<span is-issue-template></span>

**Comment by jgw96** [comment] 2016-09-20 20:43
Hello, thanks for opening an issue with us! Would you be able to post a repo I can use to reproduce this issue? Thanks!

**Comment by jgw96** [comment] 2016-09-22 15:38
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-09-22 15:38 UTC
Labels: needs reply, v2
