### ISSUE TITLE
bug: Blank page after going back to tabbed page

### ISSUE THREAD

**Issue by bvesd** [driftyco/ionic#25249] opened 2022-05-06 14:30 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When you have an app using tabs, and a tab has a further link to another page, it will show a blank page when going back to the tab-page.

Main concern here is using a nested RouterOutlet as described in Ionic documentation

Side note:
if you do a refresh the issue goes away, clicking back shows the tab.
If you go to the url again, the issue reappears and it will once again show a white page.

Reproduce the main issue by:

opening this example app
go to tab 3
press 'PRESS ME' to go to another page outside the tabs / go outside the current RouterOutlet 'path'
press the back button
...
white page, not tab3 as expected

After some checking, it looks like Ionic adds an ion-page-invisible inline-CSS item to the ion-page

This happens in some sort of delay, because I do see the tab 3 heading animating into view, but then disappearing after the animation is done.

This issue sounds like the one that was fixed for Vue: https://github.com/ionic-team/ionic-framework/pull/25206

### Expected Behavior

When reproducing the steps mentioned, tab3 should be shown also on the first time you navigate back to it.

### Steps to Reproduce

Reproduce the main issue by:

opening this example app
go to tab 3
press 'PRESS ME' to go to another page outside the tabs / go outside the current RouterOutlet 'path'
press the back button
...
white page, not tab3 as expected

### Code Reproduction URL

https://github.com/bvesd/ionic-blank-page-issue

### Ionic Info

Ionic:

   Ionic CLI       : 6.18.1 (/home/me/.nvm/versions/node/v17.4.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.1.4

Capacitor:

   Capacitor CLI      : 3.4.3
   @capacitor/android : 3.4.3
   @capacitor/core    : 3.5.1
   @capacitor/ios     : 3.4.3

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v17.4.0 (/home/me/.nvm/versions/node/v17.4.0/bin/node)
   npm    : 8.4.0
   OS     : Linux 5.13

**Comment by liamdebeasi** [comment] 2022-05-17 20:31
Great question. It looks like Ionic React is incorrectly unmounting the tabs component after you go to `example/another-page`. When you go back, the tabs component is re-mounted. All pages are hidden by default, so the tabs component has `ion-page-invisible` set. The triple nested outlet usage here is not something the routing integration was designed for, so the router does not consider the new tabs view to be the entering view when going back. As a result, the tabs component remains hidden.

We recently shipped some new documentation that explains how to get the most out of nested outlets and tabs that you may find helpful:

[Shared URLs versus Nested URLs](https://ionicframework.com/docs/react/navigation#shared-urls-versus-nested-routes)
[Working with Tabs](https://ionicframework.com/docs/react/navigation#working-with-tabs)

----

Removing the extra `IonRouterOutlet` and `IonPage` usages fixed the issue on my end (see https://github.com/ionic-team/ionic-framework/issues/25249#issuecomment-1121263004). I am going to close this as this is not a bug in Ionic. Thanks!

**Closed as completed by liamdebeasi** 2022-05-17 20:31 UTC
Labels: triage
