### ISSUE TITLE
Feature Request - Autocomplete Dropdown

### ISSUE THREAD

**Issue by aggarwalankush** [driftyco/ionic#8498] opened 2016-10-05 04:33 UTC
Hi Ionic Team,

Thanks for the awesome open source contribution. We can implement somewhat working autocomplete dropdown by ourself but the native look and animations that you can provide would be far better than what we can achieve.

Would you consider implementing autocomplete dropdown as a component in Ionic itself?

-Thanks

**Comment by vaibsVB** [comment] 2016-10-05 06:45
+1

**Comment by manucorporat** [comment] 2016-10-05 11:34
Duplicate of #6921

I don't think we will add more features until 2.0 final is released. We are focusing all our efforts in bug fixing!

**Closed by manucorporat** 2016-10-05 11:34 UTC
