### ISSUE TITLE
Ionic 3 is creating new instances of providers instead of single shared instance

### ISSUE THREAD

**Issue by donaldruby** [driftyco/ionic#11361] opened 2017-04-25 19:23 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Ionic 3 is creating new instances of providers instead of single shared instance.

**Expected behavior:**
Expected behavior is a single shared provider is created. In Ionic 2, things are working as expected. Service is singleton. But in Ionic 3, which uses angular 4, it looks like every component is creating new instance of that class.

**Steps to reproduce:**
1. Define service as class :
```
@Injectable()
export class MyService {
 ...
}
```

2. In other components or pages, import that class with just import command.
```
import { MyService } from '../pages/services/myservice';
```
In constructor:
```
constructor(public _MyService: MyService)
```

3. In main app.module.ts,  add that class service as provider:
```
providers: [someOtherThings, MyService, someOtherThings]
```

**Ionic info:** 
```
Cordova CLI: 6.4.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.1 
ios-sim version: 5.0.3 
OS: macOS Sierra
Node Version: v4.3.0
Xcode version: Xcode 8.0 Build version 8A218a
```

**Comment by jgw96** [comment] 2017-04-25 19:45
Hello, thanks for using Ionic! Can you provide a minimal repo we could use to reproduce this issue, please?

**Comment by jgw96** [comment] 2017-05-01 17:23
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-05-01 17:23 UTC
Labels: needs info, v2
