### ISSUE TITLE
bug (ion-slides) undefined property error if switch fast between components containing ion-slides

### ISSUE THREAD

**Issue by twinssbc** [driftyco/ionic#11069] opened 2017-04-05 15:32 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I have a page containing two components and use ngSwitch to control the visibility of them. Both components contain ion-slides. If I switch between these two components very quickly, some undefined property error will be thrown to crash the app.

> Cannot read property 'length' of undefined

The error is thrown by below method in swiper.ts. I think the root cause is because the _slides property has been initialized.

```
function destroyLoop(s: Slides) {
  eachChild(s._wrapper, '.' + CLS.slide + '.' + CLS.slideDuplicate, ele => {
    ele.parentElement.removeChild(ele);
  });
  for (var i = 0; i < s._slides.length; i++) {
    s._slides[i].removeAttribute('data-swiper-slide-index');
  }
}
```

**Expected behavior:**
There should be no error thrown when performing cleanup in the destroyLoop method.

**Steps to reproduce:**
Switch between two components containing the ion-slides very quickly

**Related code:**

**Other information:**
[Error] EXCEPTION: Error in ./WeekViewComponent class WeekViewComponent - inline template:174:12 caused by: undefined is not an object (evaluating 's._slides.length')

destroyLoop@http://localhost:8100/build/main.js:28303:34
destroySwiper@http://localhost:8100/build/main.js:28508:20
ngOnDestroy@http://localhost:8100/build/main.js:44919:101
ngOnDestroy
destroyInternal
destroy@http://localhost:8100/build/main.js:99030:29
destroy@http://localhost:8100/build/main.js:99258:42
destroyInternal
destroy@http://localhost:8100/build/main.js:99030:29
destroy@http://localhost:8100/build/main.js:99258:42
remove@http://localhost:8100/build/main.js:55551:21
clear@http://localhost:8100/build/main.js:55566:24
destroy@http://localhost:8100/build/main.js:47252:37
enforceState@http://localhost:8100/build/main.js:47259:25
ngDoCheck@http://localhost:8100/build/main.js:47392:77
ngDoCheck
detectChangesInternal
detectChanges@http://localhost:8100/build/main.js:99175:35
detectChanges@http://localhost:8100/build/main.js:99268:48
detectChangesInternal
detectChanges@http://localhost:8100/build/main.js:99175:35
detectChanges@http://localhost:8100/build/main.js:99268:48
detectChangesInternal
detectChanges@http://localhost:8100/build/main.js:99175:35
detectChanges@http://localhost:8100/build/main.js:99268:48
detectChangesInNestedViews@http://localhost:8100/build/main.js:99360:50
detectChangesInternal
detectChanges@http://localhost:8100/build/main.js:99175:35
detectChanges@http://localhost:8100/build/main.js:99268:48
detectChangesInternal
detectChanges@http://localhost:8100/build/main.js:99175:35
detectChanges@http://localhost:8100/build/main.js:99268:48
detectChangesInternal
detectChanges@http://localhost:8100/build/main.js:99175:35
detectChanges@http://localhost:8100/build/main.js:99268:48
detectChangesInNestedViews@http://localhost:8100/build/main.js:99360:50
detectChangesInternal
detectChanges@http://localhost:8100/build/main.js:99175:35
detectChanges@http://localhost:8100/build/main.js:99268:48
detectChangesInternal
detectChanges@http://localhost:8100/build/main.js:99175:35
detectChanges@http://localhost:8100/build/main.js:99268:48
detectChangesInternal
detectChanges@http://localhost:8100/build/main.js:99175:35
detectChanges@http://localhost:8100/build/main.js:99268:48
detectChangesInNestedViews@http://localhost:8100/build/main.js:99360:50
detectChangesInternal
detectChanges@http://localhost:8100/build/main.js:99175:35
detectChanges@http://localhost:8100/build/main.js:99268:48
detectChangesInternal
detectChanges@http://localhost:8100/build/main.js:99175:35
detectChanges@http://localhost:8100/build/main.js:99268:48
detectChanges@http://localhost:8100/build/main.js:55713:33
forEach@[native code]
tick@http://localhost:8100/build/main.js:35457:45
http://localhost:8100/build/main.js:35398:109
onInvoke@http://localhost:8100/build/main.js:37602:43
run@http://localhost:8100/build/polyfills.js:3:6487
next@http://localhost:8100/build/main.js:35398:84
http://localhost:8100/build/main.js:36802:56
__tryOrUnsub@http://localhost:8100/build/main.js:1225:20
next@http://localhost:8100/build/main.js:1174:34
_next@http://localhost:8100/build/main.js:1127:30
next@http://localhost:8100/build/main.js:1091:23
next@http://localhost:8100/build/main.js:5010:29
emit@http://localhost:8100/build/main.js:36794:80
checkStable@http://localhost:8100/build/main.js:37570:44
onLeave@http://localhost:8100/build/main.js:37637:25
onInvokeTask@http://localhost:8100/build/main.js:37596:34
invokeTask@http://localhost:8100/build/polyfills.js:3:9671
runTask@http://localhost:8100/build/polyfills.js:3:7093
invoke@http://localhost:8100/build/polyfills.js:3:10843

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```
Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 1.2.1
Gulp local:  
Ionic Framework Version: 2.1.0
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.38
ios-deploy version: 1.9.0 
ios-sim version: 3.1.1 
OS: Mac OS X Sierra
Node Version: v4.4.2
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment] 2017-04-05 16:26
Hello, thanks for using Ionic! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/10830.

**Closed by jgw96** 2017-04-05 16:26 UTC
