### ISSUE TITLE
bug: Slide-box wrong number of bullets at the pager

### ISSUE THREAD

**Issue by yuda022** [driftyco/ionic#3646] opened 2015-04-30 10:19 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>hi,

I noticed unexpected behavior while using slide boxes.
I manage two slide boxes I navigate between. One has 2 slide elements and the other one has 5. 

While loading the second slide box, on the setup function, the two slides of the previous slide box are still counted though they have the ng-leave -active tag that means they will be deleted, but after they were already counted, so the second slide box appear to have 7 elements instead of 5.

![slidebox-issue](https://cloud.githubusercontent.com/assets/5606119/7410873/8dd7e972-ef3b-11e4-8dc8-8603c340207b.png)
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-04-30 10:19
Greetings @yuda022!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3646). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3646)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by gravitywp** [comment] 2015-05-06 02:22
.disable-animations{
    //Use this for transitions
    &.ng-enter,
    &.ng-leave,
    &.ng-animate{
        -webkit-transition: none !important;
        transition: none !important;
    }
    //Use this for keyframe animations
    &.ng-animate {
       -webkit-animation: none 0s;
       animation: none 0s;
    }
}
add this class to  ion-slide should disable default ngAnimation

**Comment by perrygovier** [comment] 2015-05-08 19:32
@yuda022, can you put this in a codepen for us to inspect?

**Comment by rossholdway** [comment] 2015-05-20 13:51
@kaikcreator created a codepen showing this in #3076. Adding the CSS does fix this issue (http://codepen.io/anon/pen/pJEJbb). 

Pull request at: https://github.com/driftyco/ionic/pull/3790

Thanks,
Ross

**Comment by yuda022** [comment] 2015-05-21 11:19
thank you very match.

yehuda amar.

**Comment by dreamershl** [comment] 2015-08-16 07:28
I encounter the similar issue. The following is what I figure out. hope it can help you for the fix. It seems the issue is caused by the closure variable "length". I believe once change the slide count function to use the element children length directly, the pager will be able to get the actual length. (at least the actual length at the calling time, instead of the pre-captured children length)

       this.slidesCount = this.count = function() { 

I am using the ng-repeat to adjust the slide count. The issue is the when the slides is changed, the pager will count those "ng-leave" elements too as stated above

![image](https://cloud.githubusercontent.com/assets/1271739/9292389/98cd22ba-4428-11e5-9da2-8d15c5c6e64b.png)

The following are fundings for this issue

1.   The Slide is using closure variable "length" instead of the latest element children length to report the number of slides
    
        slides = element.children;
        length = slides.length;

2.  I am using the following code to adjust slides


          < ion-slide ng-repeat="slide in slides">...</ion-slide>

         $scope.$on('modal.shown', function (event, modal){
               $scope.slides = ....
          });

3. How Ionic slide box display process cause the issue. 

   Although 'resize' is triggered before the 'shown' event, the handler of 'resize', using the 'timeout' is running after the 'shown' handler. Because of the ng-repeat animation process, when the "resize" handler is called, it will always capture the "ng-leave" elements.  

        ionic.views.Modal.prototype.show.call(self);

        $timeout(function() {
        if (!self._isShown) return;
        modalEl.addClass('ng-enter-active');
        ionic.trigger('resize');
        self.scope.$parent && self.scope.$parent.$broadcast(self.viewType + '.shown', self);
        self.el.classList.add('active');
        self.scope.$broadcast('$ionicHeader.align');
         }, 20);

**Comment by rossholdway** [comment] 2015-08-16 09:16
Hi dreamershl

Yes, I also came to the same conclusion, the elements inserted by nganimate are counted. The code in pull request #3790 fixes this issue.

I've been using the fix #3790 in production for awhile now it's been working great.

Thanks,
Ross

**Comment by dreamershl** [comment] 2015-08-16 09:23
:) sorry, didn't realize the fix is done. :+1:

**Comment by rossholdway** [comment] 2015-08-16 09:25
It just needs to be merged in to master now. I believe the target milestone has been updated to version 1.2 :)

**Closed** 2015-08-28 20:01 UTC
