### ISSUE TITLE
[RC0] tab.popToRoot causes black page

### ISSUE THREAD

**Issue by miloslavskacel** [driftyco/ionic#8562] opened 2016-10-07 13:20 UTC
In RC0, tab.popToRoot()
can be called only when there is at least one page pushed on the nav stack.
In beta 11 it was possible to call it even without having page pushed on the nav stack.

When tab.popToRoot() is called and there is no page pushed on nav stack, page is black.
![screen shot 2016-10-07 at 14 01 31](https://cloud.githubusercontent.com/assets/2547672/19190980/a710e26e-8ca0-11e6-99a5-29c3c7ae9242.png)

#### What behavior are you expecting?
tab.popToRoot() can be called in code below without IF statement

```
public ionChange(tab: Tab) {
    console.debug('ionChange tab:', tab.tabTitle, tab);
    if (tab._views.length > 1) {
      tab.popToRoot({ animate: false });  // it's OK to call popToRoot is there is some pushed page on the nav stack
    } else {
      // uncomment the below line to reproduce error
      // tab.popToRoot({ animate: false });  
      // page is black when popToRoot is called here
      // taping on tab About and then to Home results into the following error in console
    }
  }
```

**Steps to reproduce:**
1.  git clone https://github.com/miloslavskacel/tabs-nav.git
2.  npm install
3.  ionic serve
4. app works, Home page is displayed
![screen shot 2016-10-07 at 14 11 07](https://cloud.githubusercontent.com/assets/2547672/19191042/fdd0388e-8ca0-11e6-9d74-2409e783cb63.png)
5. uncomment tabs.ts:28
6. app does not work, Home page is black

**Other information:** 
https://github.com/driftyco/ionic/issues/8508
 
**Which Ionic Version?** 
2.RC0

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.6.0
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by jgw96** [comment] 2016-10-07 14:07
Hello, thanks for opening an issue with us! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/8508 as it seems to be caused by the same issue. Thanks!

**Closed by jgw96** 2016-10-07 14:07 UTC
