### ISSUE TITLE
Unable to use a "Hardware" keyboard on an ion-input (iOS simulator)

### ISSUE THREAD

**Issue by kelvindart** [driftyco/ionic#10254] opened 2017-01-31 11:48 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
I am unable to utilise the "hardware" keyboard when deploying to the iOS simulator which uses an `ion-input` (in this instance, the hardware is the MacBook's keyboard).

I gather this may well be related to the `ionic-plugin-keyboard` plugin.

If I uncheck this so the simulator is forced to use the software keyboard, I can focus and type, but this is somewhat painstaking. 🙂

But when I attempt to set focus by clicking, focus is immediately lost and I am unable to type.

**Expected behavior:**
To be able to use the hardware keyboard, and type without the `ion-input` losing focus.

**Steps to reproduce:**
1. Generate an Ionic v2 project: `ionic start -t blank -v IonInputTest && cd IonInputTest`
2. Run the project on an iOS simulator: `ionic emulate`
3. Ensure the hardware keyboard is connected: Hardware | Keyboard | Connect Hardware Keyboard.

**Related code:**
I added this to the bottom of `home.page` in the Ionic 2 blank starter app:

```
<ion-list>
  <ion-item>
    <ion-input></ion-input>
  </ion-item>
</ion-list>
```

**Other information:**
The input seems to momentarily focus - since if I hammer the mouse/keyboard then I can type a letter or two.

![Ion Input issue](https://s23.postimg.org/e0nmwrtyj/ioninput.gif)

**Ionic info:**

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.4
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment] 2017-01-31 15:10
Hello, thanks for opening an issue with us! Unfortunately I cannot reproduce this issues what version of the iOS sim are you using?

**Comment by kelvindart** [comment] 2017-02-01 00:29
Hi @jgw96 - hmm it seems like the latest one, 5.0.13. Is the input focusing fine for you?

**Comment by jesuscmd** [comment] 2017-02-01 17:22
I have the same problem, this is happening only in IOS version 9.3, I downloaded other (8.3) and worked fine, however I am worried about the behaviour in real devices with this versions.

**Comment by kelvindart** [comment] 2017-02-01 17:24
For me it works fine on physical devices. Just not the simulator...

**Comment by jgw96** [comment] 2017-02-03 15:35
So after testing i can confirm that on both iOS 9.3 and iOS 10.2 on both real iOS devices and the sim's are working fine for me on my machine. Now, i will state that the iOS sim is definitely buggy sometimes, so i would not be surprised if your sim was running into a bug on your machine. For example, the 9.3 sim has a habit of sometimes randomly pinning my cpu to 100% and eventually causing my mac to lock up, you will see me angrily tweet about this sometimes 😆 . Unfortunately though, this is not something that we can solve and instead is something apple would have to solve. Because of this I am going to close this issue for now.

**Closed by jgw96** 2017-02-03 15:35 UTC
Labels: needs reply, v2

**Comment by kelvindart** [comment] 2017-08-30 16:00
Omg - after nearly a year of pain and misery pressing each individual key on the iOS simulator, I have found out my issue related to this bug!

The issue was related to Hardware | Keyboard | Toggle Software Keyboard (⌘ + K) - my guess it was disabled. Weirdly, this isn't an issue in a Cordova, non-Ionic app.

There is a bug in the simulator menu since it does not show a tick next to the option, so you have no way of knowing whether it's enabled/disabled (it also appears disabled in the menu in some instances, unsure why). However, after enabling it via ⌘ + K, it became enabled - still no tick, but I can type!

![Keyboard menu](https://preview.ibb.co/merjhQ/Screen_Shot_2017_08_30_at_16_55_05.png)

**Comment by steve3d** [comment] 2017-12-20 12:20
confirmed about this with version 11.2 simulator, you still need to uncheck the `Connect Hardware Keyboard` to make ANY input field working.

**Comment by igimanaloto** [comment] 2018-03-03 23:49
@kelvindart's suggestion was right. Connect keyboard should be enabled from hardware menu.
When clicking on an input, the on-screen keyboard opens. When it is open, hitting cmd k once more enables keyboard typing to work!

I've removed floating labels from my forms as well. Using a floating label seems to remove the focus from the forms and as a result - typing using the keyboard doesn't work.

**Comment by Sampath-Lokuge** [comment] 2018-08-14 20:12
Thank you @kelvindart It works for me too.
