### ISSUE TITLE
bug: Tapping the navbar to scroll to top is broken in 1.2.1

### ISSUE THREAD

**Issue by lukemiles** [driftyco/ionic#4825] opened 2015-12-20 01:13 UTC
<span ionic-description>**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi there,

Great work by all at Drifty on Ionic -- I love it. After updating to 1.2.1 from 1.1, tapping the nav bar to scroll to top does not work anymore. [Here's the requisite codepen demonstrating the bug](http://codepen.io/ionic/pen/JsHjf). Scroll down a bit, tap the nav bar and on 1.1, it scrolls to top, but on 1.2.1 it doesn't.

Working on getting a new update to my app out and noticed this. Thanks again and happy holidays.

Luke</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-12-20 01:14
Greetings @lukemiles!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4825). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4825)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by lukemiles** [comment] 2015-12-20 01:16
@Ionitron :heart:

**Comment by xyxabcdiy** [comment] 2015-12-20 09:27
same problem here +1

**Comment by richardfriedman** [comment] 2015-12-21 16:31
The directive was commented out
https://github.com/driftyco/ionic/commit/cfa8042

Putting that line in fixes issue.

It looks like the intent was to allow native scrolling to kick-in, but still need to hookup the header 'tap' to scroll to top.

**Comment by mlynch** [comment] 2015-12-21 17:32
Hey, we removed that because it's non-standard and if you use the cordova-plugin-statusbar you'll get that for free, and it will actually work with the statusbar. 

I'm open to adding it back, but I'm not sure we should be doing it. I need to be convinced :stuck_out_tongue:

**Closed by mlynch** 2015-12-21 17:32 UTC

**Comment by richardfriedman** [comment] 2015-12-21 17:45
Don't disagree, anyone can implement by providing on-tap themselves.  
Would suggest updating the main doc page ion-header-bar and ion-nav-bar since the documented default is for this to happen. Guessing no-tap-scroll should just be removed?

My reasons for keeping are not strong enough 
- expected behavior in ionic apps (though not standard)
- browser platforms do not have mobile equivalent

**Comment by yanzhihong23** [comment] 2016-06-16 06:47
My resolution for browser platform: add a directive for class 'header-item'
~~~javascript
angular
  .module('app')
  .directive('headerItem', ['$ionicScrollDelegate', function($ionicScrollDelegate) {
    var directive = {
      restrict: 'C',
      link: function(scope, element, attr) {
        element.bind('click', function() {
          $ionicScrollDelegate.scrollTop(true);
        });
      }
    };

    return directive;
  }]);
~~~
