### ISSUE TITLE
Not render custom component inside <ion-item>

### ISSUE THREAD

**Issue by leandrogehlen** [driftyco/ionic#11515] opened 2017-05-05 00:16 UTC
**Ionic version:**  (check one with "x")
 [ ] **1.x**
 [ ] **2.x**
 [x] **3.x**

**I'm submitting a**
[x] bug report
[ ] feature request

**Current behavior:**
I'm trying to build a simple component:

```typescript
Component({
  selector: 'mycomp',
  template: '<ion-input type="text" (focus)="showModal()"></ion-input>'
})
export class MyComp  {

  constructor(    
    private modalCtrl: ModalController
  ) { }
  
  showModal() {
      let modal = this.modalCtrl.create(MyPage);      
      modal.present();
  }
} 
```

But when i try to use with `<ion-item>` the component is not rendered: 

```html
<ion-list>
  <ion-item>
    <ion-label color="primary">Label</ion-label>
    <mycomp></mycomp>
  </ion-item>
</ion-list>
```
The html result is : 
```html
<ion-list class="list list-md">
  <ion-item class="item item-block item-md item-mycomp item-input">
    <div class="item-inner">
        <div class="input-wrapper"><!--bindings={
          "ng-reflect-ng-if": "false"
         }--></div>
        <!--bindings={
         "ng-reflect-ng-if": "false"
        }--></div>
      <div class="button-effect">
    </div>
  </ion-item>
```

**Out of `<ion-item>` the component works**

**Comment by jgw96** [comment] 2017-05-05 14:16
Thanks, we will look into this issue.

**Comment by rapropos** [comment] 2017-05-05 19:12
What happens if you add an `item-content` attribute to the `<mycomp>` element?

**Comment by leandrogehlen** [comment] 2017-05-05 19:30
Show up, but not right way
![mycomp](https://cloud.githubusercontent.com/assets/1750751/25761130/25b9c626-31b0-11e7-9ef8-fbcd67eea21d.png)

**Comment by jgw96** [comment] 2017-05-18 15:47
Hello @leandrogehlen , I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/6849. Thanks for using Ionic and feel free to put any more info you have on that issue.

**Closed by jgw96** 2017-05-18 15:47 UTC
Labels: v2
