### ISSUE TITLE
Ionic Popover freezes after refreshing the page

### ISSUE THREAD

**Issue by amiral84** [driftyco/ionic#8582] opened 2016-10-09 07:41 UTC
Hi everyone,

I found very interesting problem regarding ionic popover component. I made a test in my project by having same code like in Ionic Framework website at [http://ionicframework.com/docs/api/service/$ionicPopover/](url) and first it works fine, but when I turn on the developer tools of Chrome on, open the mobile toolbar where you can see how it looks like in the mobile and change the mobile phone type and refresh the page, styles of ionic popover gets messy (losing style values) and logic of angular function breaks. 

What I mean with angular function breaks is for example if I would have `ng-click="closePopover()"` it simply won't work, nothing happens. Could this be a bug? If yes could you fix it as well?

Also I had similar kind of case with other project and funny thing in this case is that whenever I open the project with `ionic serve` first time everything works fine except on mobile phones and when I refresh the page of that popover in the Chrome developer tools same thing happens, angular function logic breaks.

**Comment by sarthakm1011** [comment] 2016-10-10 09:12
Hello , 
If event ng-click="closePopover()" is being executed when there is no popover it won't do anything.It is perfectly fine then but if it is being executed after ng-click="openPopover()" is executed then it should close that popover. If none of them is working then it must be a bug.

**Comment by amiral84** [comment] 2016-10-10 10:22
Hi @sarthakm1011. `ng-click="closePopover()` is not executed outside the popover. Meaning that when I open the popover it contains "X" icon which `ng-click="closePopover()"` is binded to.

**Comment by sarthakm1011** [comment] 2016-10-10 21:01
Yes it works only when a new window is opened . It's similar to a modal.

**Comment by amiral84** [comment] 2016-10-11 07:21
@sarthakm1011 no, what I mean is when I open a new window tab in browser it works for first time, but when you hit refresh again there it doesn't work. Also with mobiles when I prepare the project for example with android by using `cordova prepare android` and then build it in IntelliJ Idea to get the .apk file then it doesn't work at all in mobile. I have tested same with iPhones as well, same thing happens.

**Comment by amiral84** [comment] 2016-10-11 08:41
After long inspection in the DOM components of this component I found out that `<ion-popover-view>` messed up everything and it broke also the logic of the popover. Once I deleted it, everything worked fine.

So there is a bug in this component that should be fixed.

**Comment by tcunningham07** [comment] 2016-11-04 02:43
I ran into this issue as well.

I was able to fork from the Popover: Nightly codepen and replicate the issue. 
Link - [https://codepen.io/tcun/full/pNoRWV/](url)

To cause the issue, open the popover, then the modal (click 'Add Comment'). From there, exit the modal using the close button (submit does nothing).

After the modal is closed, nothing can be clicked until the pen is refreshed. If the <ion-popover-view> tags are removed from the popover template, the issue is resolved as @amiral84 has said previously.

**Comment by clintghosn** [comment] 2016-11-09 15:43
Any news on this? I am currently experiencing the exact same issue as described above by @tcunningham07

**Comment by ach** [comment] 2016-11-10 12:12
I'm having trouble with this as well. It occur when I open a modal from popover. A class popover-open exists in my document root which block entire GUI from clicks.

@tcunningham07 codepen demostrate the issue

**Comment by GabrielGMartinsBr** [comment] 2016-11-12 09:29
Here I solved it closing the popover and using a timeout before opening the modal, look
	

```
    	$scope.openModal = function(){
    		if(!$scope.modal) return;		
    		
    		// Call a function to close the popover
    		$scope.closePopover();		
    		
    		// Set a timeout to show the popover only in next cycle
    		$timeout(function(){
    			$scope.modal.show()
    		}, 0);
    	});
```

**Comment by jlamber4** [comment] 2016-11-23 22:51
I also have this problem, but in reverse. If I open a popover from within a modal - after closing the modal - the screen is unable to be clicked.

**Comment by jlamber4** [comment] 2016-11-23 22:56
I bandaided a fix by adding the following method to my modal

$scope.$on('popover.hidden', function() {
    $scope.popover.remove();
    $scope.popover = null;
    $('body').removeClass("popover-open");
  });

**Comment by ach** [comment] 2016-11-24 06:21
I think this relates to #9069. I reverted to v1.3.1, waiting for a solution in latest release.

**Comment by jgw96** [comment] 2017-01-13 21:52
This issue was moved to driftyco/ionic-v1#86

**Closed by jgw96** 2017-01-13 21:52 UTC
Labels: v1
