### ISSUE TITLE
Custom Error Handler cause exception in prod build.

### ISSUE THREAD

**Issue by royipressburger** [driftyco/ionic#11035] opened 2017-04-03 19:23 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When creating a custom error handler
`{provide: ErrorHandler, useClass: MyErrorHandler}`
Running the app in dev or in emulator has no problems.
But when building with `--prod` and running on device, I saw the app splash screen and then white screen.
After looking at the `logcat` I saw:
`Uncaught Error: No ErrorHandler. Is platform module (BrowserModule) included?`
this line just before the device ready event.

**Expected behavior:**

**Steps to reproduce:**
1. start an empty app with custom error handler
2. use this error handler as default `{provide: ErrorHandler, useClass: MyErrorHandler}`
3. build --prod
4. try to run

For Ionic 2 issues - http://plnkr.co/edit/z0DzVL?p=preview
-->

**Related code:**

My error handler:
```ts
import { ErrorHandler } from '@angular/core';

export default class MyErrorHandler extends ErrorHandler {
  constructor() {
    super(false);
  }
  
  handleError(err: any): void {
    if (err.rejection && err.rejection === "cordova_not_available") return;
    super.handleError(err);
    try {
      const devServer = (<any>window)['IonicDevServer'];
      if (devServer) {
        devServer.handleError(err);
      }
    } catch (e) {}
  }
}
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.3.1 
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.2.5
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.3 Build version 8E162
```

**Comment by jgw96** [comment] 2017-04-03 20:04
Hello, thanks for opening an issue with us, would you be able to share a repo we can use to reproduce this?

**Comment by jgw96** [comment] 2017-04-13 21:24
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-04-13 21:24 UTC
Labels: needs info, v2
