### ISSUE TITLE
ionic2 ion-slides not work with nested components with iOS < 10

### ISSUE THREAD

**Issue by v4le** [driftyco/ionic#10859] opened 2017-03-21 11:22 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
With ipad/iphone **devices** **with iOS lower than 10**, show multiple ion-slide, each one wrapped in a **nested component** not work: all the slides are overlapped. With ipad/iphone devices with iOS 10, all work correctly. With browser all work correctly.

**Expected behavior:**
I would aspect slides rendered correctly (one per page, with swipe between them).

**Steps to reproduce:**
I have created a plunker based on your template
http://plnkr.co/edit/cXcDwUqjdj8alOuXG5Kc?p=preview

**Related code:**

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.5
Xcode version: Xcode 8.2.1 Build version 8C1002

```

**Comment by jgw96** [comment] 2017-04-07 16:40
Hello, thanks for opening an issue with us. I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/10542.

**Closed by jgw96** 2017-04-07 16:40 UTC
Labels: slides, v2
