### ISSUE TITLE
iOS 64px header margin used also in landscape mode

### ISSUE THREAD

**Issue by atorger** [driftyco/ionic#6310] opened 2016-04-25 10:54 UTC
#### Short description of the problem:
The ionic.css adds space for the iOS status bar, but doesn't take into account that the status bar is hidden when the device is in landscape mode.

#### What behavior are you expecting?
@media screen and (orientation:portrait) => 64px margin
@media screen and (orientation:landscape) => default 44px margin

Cordova CLI: 6.1.1
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: Not installed
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v5.10.0
Xcode version: Xcode 7.3 Build version 7D175

**Comment by atorger** [comment] 2016-04-25 11:27
...but not on Ipads, as then the status bar is still there in landscape orientation!

**Comment by danbucholtz** [comment] 2016-05-06 04:21
Hi @atorger 😄 ,

I just tested an app on my iOS simulator and I see the status bar on an iPhone 6S when in landscape.  Is that what you're seeing?

Thanks,
Dan

**Comment by atorger** [comment] 2016-05-06 06:02
I run 9.3 Iphone-6s in the simulator, and then the native status bar is removed when the GUI is rotated to landscape orientation. Note that I mean the native status bar (carrier, clock and battery status), not ionic's status bar, and the problem is that when in landscape mode ionic's status bar still leaves space for the native one, despite that it's not visible.

**Comment by danbucholtz** [comment] 2016-05-06 13:17
Hmm, I am not seeing that for some reason.  Let me dig it and see what I can figure out.  Thanks @atorger!

Thanks,
Dan

**Comment by danbucholtz** [comment] 2016-05-06 14:12
@atorger, how are you hiding the status bar?

Thanks,
Dan

**Comment by atorger** [comment] 2016-05-06 14:41
I don't do anything (I don't have any status bar code in my app), I thought it was the default behavior of iOS, that is on smaller screens the status-bar is autohidden in landscape mode to avoid unreasonable low screen height.

I guess cordova could affect it somehow (using 6.1.1). My config.xml says

  <feature name="StatusBar">
    <param name="ios-package" value="CDVStatusBar" onload="true"/>
  </feature>

**Comment by jgw96** [comment] 2016-06-20 16:35
Hello @atorger, thanks for opening an issue with us. I am also having a hard time reproducing this issue. What version of ios are you running?

**Comment by jgw96** [comment] 2016-06-27 14:38
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-06-27 14:38 UTC
Labels: header, needs reply, platform:ios, v1

**Comment by yogeshwar238** [comment] 2017-11-21 06:21
Hi,
I am facing same issue with iPhone 6 with iOS 10.2. Also same app works fine on iPad Air2.
Anyone has fix?
