### ISSUE TITLE
When Segment in a header the navbar BackButton Don't working!!!on  IOS

### ISSUE THREAD

**Issue by fssgh** [driftyco/ionic#9146] opened 2016-11-14 01:08 UTC
#### Short description of the problem:
When Segment  in a header the navbar BackButton Don't working on  IOS !!!
#### What behavior are you expecting?
1.I think this problem is the CSS for IOS.
2.I hope your can help me  fix the problem or bug

**Steps to reproduce:**
1. Copy the code in a page canBack ;
2.buid app run in ios sim;
3.click the navbar BackButton is not working.

```
<ion-header>
  <ion-navbar>
      <ion-segment [(ngModel)]="myGroups">
      <ion-segment-button value="card1">
        card1
      </ion-segment-button>
      <ion-segment-button value="card2">
         card2
      </ion-segment-button>
    </ion-segment>
  </ion-navbar>
</ion-header>
<ion-content>
</ion-content>
```
**Which Ionic Version?** 
ionic:ionic2RC2
platform:IOS

**Comment by comfortme** [comment] 2016-11-14 05:20
hello
i had that problem too.
have an issue on https://github.com/driftyco/ionic/issues/7671

**Comment by fssgh** [comment] 2016-11-14 09:46
@comfortme  Can you solve it?

**Comment by comfortme** [comment] 2016-11-14 09:50
yes with a workaround.
i deleted the navbar, and used a toolbar with a back button instead.

**Comment by fssgh** [comment] 2016-11-14 11:31
@comfortme Can you share the code?

**Comment by comfortme** [comment] 2016-11-14 12:14
ok your header should look like that,

`<ion-header>
   <ion-toolbar>
      <ion-title hidden=true>IONIC</ion-title>
      <ion-buttons left>
			<button ion-button icon-only navPop><ion-icon name="arrow-back"></ion-icon></button>
		</ion-buttons>
      <ion-segment [(ngModel)]="segment_model">
         <ion-segment-button value="broadcast">
           button 1
         </ion-segment-button>
         <ion-segment-button value="suggestions">
           button 2
         </ion-segment-button>
      </ion-segment>
	</ion-toolbar>
</ion-header>`

**Comment by fssgh** [comment] 2016-11-14 12:29
@comfortme  thank you !

**Comment by brandyscarney** [comment] 2016-11-18 17:11
Thanks for the issue, closing as a duplicate of #7671

**Closed by brandyscarney** 2016-11-18 17:11 UTC
Labels: v2
