### ISSUE TITLE
Can't scroll (native) a container if i touch scroll on an input.

### ISSUE THREAD

**Issue by do-web** [driftyco/ionic#3385] opened 2015-03-23 17:36 UTC
Can scroll (native) a container if i touch scroll on an input on ios

**Comment by Ionitron** [comment] 2015-03-24 16:25
Greetings @do-web!

My sensors indicate that I require more information in order to assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this happen occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com), where many humans will be able to offer wisdom and advice.

Thank you for allowing me to assist you.

<span ionitron-needs-reply></span>

**Comment by Fayozjon** [comment] 2015-03-24 16:44
Ionitron

http://newculture.pl/option_dragon

24.03.2015, 19:26, "Ionitron" <notifications@github.com>:Greetings !

My sensors indicate that I require more information in order to assist you.


Can you provide a detailed description of this issue?
How would a robot go about replicating this issue?
On which platform does this happen occur? (iOS, Android, all, etc.)
On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
Is this an issue with the Ionic Framework or Ionic CLI?


Additionally, providing a  that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting , where many humans will be able to offer wisdom and advice.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment] 2015-04-23 20:22
Greetings @do-web!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-04-23 20:22 UTC
Labels: ionitron:closed

**Comment by alvaromb** [comment] 2015-07-10 10:31
This is still happening and it hasn't been fixed yet.
