### ISSUE TITLE
perf: Demo

### ISSUE THREAD

**Issue by jpmartinez91** [driftyco/ionic#5607] opened 2016-02-25 14:30 UTC
**Type**: <span ionic-type>perf</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>Prueba de todo esto</span>

<span is-issue-template></span>

**Comment by brandyscarney** [comment] 2016-02-25 18:17
Please provide more information, it is not clear what the issue is. Thanks.

**Comment by brandyscarney** [comment] 2016-02-29 17:10
Closing this as there isn't enough information. Please create a new issue with more information.

**Closed by brandyscarney** 2016-02-29 17:10 UTC
Labels: needs reply, platform:android, v2
