### ISSUE TITLE
ion-options while sliding don't get active while sliding few times.

### ISSUE THREAD

**Issue by jayeshanandani** [driftyco/ionic#9784] opened 2016-12-24 12:55 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ *] **2.x**

**I'm submitting a ...**  (check one with "x")
[* ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Sliding ion-options when done for few times result in ion-options not becoming active.However they are okay when slided again.

**Expected behavior:**

1. Buttons should always become active when slided.

**Steps to reproduce:**

1.) Create an app with ion-options in the sliding and deploy the app to android.
2.) Slide few times and you will be able to see white space which is created due to buttons not becoming active.
3.) Note this happens only on Android and not on web.

***Images output***

![bug](https://cloud.githubusercontent.com/assets/3860787/21467070/49b6a600-ca06-11e6-93f6-91525badcac4.png)
![bug2](https://cloud.githubusercontent.com/assets/3860787/21467071/49b832e0-ca06-11e6-89bf-0ac275245f5a.png)

**Comment by jgw96** [comment] 2017-01-10 22:18
Hey @jayeshanandani , would you mind trying the latest nightly and seeing if you can reproduce this issue with it? I cannot reproduce this issue on any of my test apps or in our e2e tests. To install the nightly you can run `npm install ionic-angular@nightly --save`. Thanks!

**Comment by jgw96** [comment] 2017-01-25 19:24
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-01-25 19:24 UTC
Labels: needs reply, v2

**Comment by masimplo** [comment] 2017-06-07 09:21
I have the exact same issue in ionic 3.1.1 (will try to reproduce in 3.3.3 also in a bit)

![screenshot 2017-06-07 11 50 20](https://user-images.githubusercontent.com/803983/26870494-cccb093e-4b78-11e7-8920-44263f9f5243.png)
![screenshot 2017-06-07 11 49 44](https://user-images.githubusercontent.com/803983/26870495-ccccf9ce-4b78-11e7-9078-32a485d16bcf.png)

active-options-left is not always applied thus showing a white bg instead of the buttons. This seems to be a race condition as it occurs more often (not always) in slower devices or when turning CPU slowdown on chrome to something big.

This happens inside a virtual scroll list that renders custom elements that have ion-item-sliding in their template (not sure if related, but pointing it out)

**Comment by masimplo** [comment] 2017-06-07 09:36
Managed to reproduce it on ionic-angular@3.3.0-201706052245
![screenshot 2017-06-07 12 33 34](https://user-images.githubusercontent.com/803983/26872049-db0f2624-4b7d-11e7-8ec0-9362af5c4ff1.png)
![screenshot 2017-06-07 12 33 26](https://user-images.githubusercontent.com/803983/26872050-db192020-4b7d-11e7-8ce1-596c5153bbc1.png)

@jgw96 could you please reopen this issue as it still applies to nightly?
