### ISSUE TITLE
Ionic 3.1.1 MAJOR MEMORY LEAK in the most basic ionic 3 app.

### ISSUE THREAD

**Issue by gitdisrupt** [driftyco/ionic#11570] opened 2017-05-09 07:58 UTC
**Ionic version:**  (check one with "x")
[X ] **3.1.1**
_running on iOS10_

**I'm submitting a ...**  (check one with "x")
[X ] bug report

**Current behavior:**
Scrolling creates a terrible memory leak.

**Expected behavior:**
Memory should be released after scrolling.

**Steps to reproduce:**

`ionic start scrollingtest blank`

**The ONLY modification made thereafter** was to add 10 paragraphs to the "home" page in src/pages/home/home.html, outlined below, albeit im only going to show 1 paragraph here:

```
<ion-content padding>
  The world is your oyster.
  <p>
    If you get lost, the <a href="http://ionicframework.com/docs/v2">docs</a> will be your guide.
  </p>
  <p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent convallis nisi at metus auctor, nec egestas mauris vestibulum. Curabitur id pretium massa. Vestibulum maximus sagittis imperdiet. Cras pretium dui a dolor scelerisque iaculis. Fusce convallis velit in mi ultrices, ac imperdiet arcu pulvinar. Sed ornare luctus nulla a suscipit. Praesent pulvinar quis quam ac tristique. Vivamus id nibh sed risus tincidunt hendrerit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse egestas sapien quis orci tempor finibus.
  </p>

<!-- note, i added the same paragraph 10 times in-order to test scrolling, just seems redundant to paste them all in this issue report -->
```
ok ... then run: `ionic build --prod`

Then open the ios app in xcode, and test run it on an actual device running iOS 10.

The app loads and displays the "home" page.

_While running, select the "debug navigator" tab, and then select "memory" to monitor memory usage._

Next, just scroll the page up and then down continuously and it adds approximately ~1.5mb of memory usage with every scroll.

That memory is **NEVER** released after scrolling has ended. Eventually the app will crash due to this issue.

Screen shot attached after scrolling up then down, then up etc etc approximately 30 times:
![test](https://cloud.githubusercontent.com/assets/5187647/25840895/b880eeb8-346b-11e7-9776-2741efda1b25.jpg)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 3.1.1
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.7
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.9.0
Xcode version: Xcode 8.3 Build version 8W120l
```
Note, i have tried a further test with the new WKWebView vs the UIWebView, and while initial memory usage is much lower, the memory increases during scrolling still persist.

**Comment by jgw96** [comment] 2017-05-09 19:14
https://drive.google.com/file/d/0Bzwe5hrqVKjhNU9aNlQ4a2RGTXc/view?usp=sharing
https://drive.google.com/file/d/0Bzwe5hrqVKjha01fcmxOMk1JSG8/view?usp=sharing

Hey, @gitdisrupt thanks for opening an issue with us. So in the two videos above you can see my testing of this issue. The first one is of our conference app and the second one is a blank app with a bunch of paragraphs added (as in your test). Also, the conference app test is with WK and the blank test is with UI. As you can see from those videos I am not able to reproduce any memory leaks. Would you be able to share a repo I could use to reproduce this issue? Thanks!

**Comment by gitdisrupt** [comment] 2017-05-09 21:24
I dont know how else to demonstrate other than to record an actual session, but i have created a repo of the exact example from my issue report here: https://github.com/gitdisrupt/Ionic3iOS10ScrollMemoryLeak.git

Did you run on an actual device running iOS10? Versions i have tested: 10.3.1 and 10.3.2

**Comment by ghenry22** [comment] 2017-05-11 02:02
I tried to replicate this issue in my project.  I have just updated to Ionic v3.2 rather than v3.1.1 but I cannot replicate the memory leak when scrolling. The attached image shows memory profiling in xcode when running on the simulator.

Immediately after launch I scrolled up and down around 30 times, no change to memory allocation at all.  I then moved to a page that has a big virtualscroll list.  Scrolled up and down maybe 30 times again.  This is the slight increase in memory usage you can see, but this memory usage is due to loading base64 images for all the items that are being scrolled.

I then changed to a page that has a long 500+ item list and scrolled up and down for about a minute and memory utilization stayed flat.  Note that this page does NOT have any images in the list items so no memory increase due to handling base64 encoded images in memory.

So the short version is, I can't reproduce a memory leak tied to scrolling on ionic v3.2

<img width="1414" alt="screen shot 2017-05-11 at 9 57 47 am" src="https://cloud.githubusercontent.com/assets/7463213/25928744/729225a4-3630-11e7-8e24-0f6becaca4b0.png">

**Comment by ghenry22** [comment] 2017-05-11 02:03
Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 3.2.0
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.7
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.10.3
Xcode version: Xcode 8.3.2 Build version 8E2002

**Comment by jgw96** [comment] 2017-05-11 18:35
I have followed up with @manucorporat on this issue and he is going to take a look. Unfortunately, no matter what I try I am not able to repro at the moment.

**Comment by gitdisrupt** [comment] 2017-05-12 23:42
As it relates to 3.1.1 ...

If you are not able to reproduce this behavior I have to assume that your system info does not match mine exactly and that the problem is specific to one or more of the versions i have installed.

I will also try 3.2 as soon as i have a chance.

**Comment by gitdisrupt** [comment] 2017-05-14 05:23
Any further info on this?

I was very careful not to change anything other than to add the paragraphs like noted above. The rest of all the code was generated by the ionic CLI... and still i see a huge memory problem.

Apple will most likely reject the app because of this problem.

**Comment by jgw96** [comment] 2017-05-15 15:18
@gitdisrupt Unfortunately we have not been able to reproduce this issue on our end. Would you mind checking your app on your device with [safari dev tools](https://webkit.org/blog/6425/memory-debugging-with-web-inspector/) instead of the memory tool in xcode? The reason I recommend this is because the xcode memory tools can be misleading in the fact that it's not actually measuring memory usage of the javascript heap of the app, instead, it is reading the memory used by the kernel / OS itself. So [as I kinda explained here](https://github.com/driftyco/ionic/issues/11446#issuecomment-299248309), the OS will not free up memory used by the JS virtual machine if it 1. thinks the action that used that memory is going to happen often and 2. thinks that it has plenty of memory to spare. So, while the JS heap memory will be shrinking every time the JS engine runs garbage collection, that does not mean that the memory that iOS has allocated to the browser will shrink, and, if iOS did start freeing up memory when it has plenty of memory available you would actually see performance issues. Also, it's important to remember that high memory usage does not === a memory leak and in fact operating systems are built to take the most advantage of the resources (in this case ram) available to it, especially on mobile devices.

**Comment by gitdisrupt** [comment] 2017-05-17 10:08
Ill give that a shot. Thanks for the detailed answer. And yes, i understand that it does not necessarily === a memory leak ... i only assumed it was a leak since it seemed GC was not clearing out the memory used in XCode.

**Comment by jgw96** [comment] 2017-05-17 14:23
Awesome, thanks @gitdisrupt! Yeah, XCode does not provide the best tools for hybrid apps, unfortunately, but safari dev tools are pretty decent and will be much more accurate for testing memory usage.

**Comment by jgw96** [comment] 2017-05-18 15:40
Hello @gitdisrupt, since we are not able to reproduce this issue I am going to close this issue for now. Thanks for using Ionic!

**Closed by jgw96** 2017-05-18 15:40 UTC
Labels: needs info, platform:ios, v2

**Comment by gitdisrupt** [comment] 2017-05-30 00:02
Ok so i can accept your note about XCode tools not really being the best for profiling a hybrid app, but as it related to this issue, there is no doubt a problem that still persists unfortunately.

After building and running the example above, and scrolling continuously for about an hour, the app crashes with the error: `Terminated due to memory issue`

I do not agree that this issue should be closed.

**Comment by kashban** [comment] 2017-06-07 08:42
We have this issue on an Android App too. Adds 2-3 MB of heap usage on every user action like tapping some GUI item until the App is almost unresponsive. 

My System info:

Cordova CLI: 6.5.0
Ionic Framework Version: 3.2.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.7
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed

This is a blocking issue for us and will most likely end in a project suspension because the customer will not accept this app performance!

**Comment by vitorsilvalima** [comment] 2017-07-16 06:32
Hi, my example app have also been experiencing the same issue of memory leak. I have used the infinity scroll in order to display items in the screen and the memory consumption is going a way to high when the user scrolls down. 
https://github.com/vitorsilvalima/ionic-tmdb

**Comment by kashban** [comment] 2017-08-14 06:10
In our case it turned out to have a different origin: Due to an unexperienced developer timers were started all over the place which invoked Angular's change detection several times a second. After sorting this out I found the performance to be ok and no memory leak has been seen on infinite scroll lists on our part.

**Comment by eomonteiro** [comment] 2018-02-22 17:35
refer: https://github.com/katzer/cordova-plugin-background-mode

Try
ionic cordova plugin add cordova-plugin-background-mode

**app.model.ts**
`import { BrowserModule } from '@angular/platform-browser';`

```
imports: [
 ...
BrowserModule
]
```

**app.components.ts**

```
constructor(
    ...
    public cordova: BrowserModule
  ) {

    document.addEventListener('deviceready', function () {     
      this.cordova.plugins.backgroundMode.on('activate', function () {
        this.cordova.plugins.backgroundMode.setEnabled(false);
      });
    }, false);
    ....
}
```

**Comment by alejandro-heredia-coderoad-com** [comment] 2018-04-04 02:11
I don't know if anyone else tried when creating a new blank Ionic project, at the moment of profiling in the Safari Developer Tools I see a 220MB memory usage for starters. How can this be? Is this normal?

![screen shot 2018-04-03 at 10 06 38 pm](https://user-images.githubusercontent.com/19911943/38284943-dd43939e-378b-11e8-8e17-046ab2d61bc0.jpg)
