### ISSUE TITLE
Error in prompt Alert using test on device. 

### ISSUE THREAD

**Issue by pimol** [driftyco/ionic#9135] opened 2016-11-12 13:10 UTC
With two inputs in an alert, if you develop using the device (Samsung S4mini), as soon as you start typing in the second field also this one is filled with the contents of the first field.

The problem is not present in ionic serve or emulator.

**Steps to reproduce:**
1. 
2. 
3. 

```
presentPrompt() {
    let alert = this.alertCtrl.create({
      title: 'Add',
      inputs: [{
        name: 'firstname',
        placeholder: 'First Name'
      },{
        name: 'lastname',
        placeholder: 'Family Name',
      }],
      buttons: [{
          text: 'Cancel',
          role: 'cancel',
          handler: data => {console.log('Cancel clicked')}
        },{
          text: 'Save',
          handler: data => {something}
        }]
    });
    alert.present();
```

Ionic Version 2.1.7

System information:
 ordova CLI: 6.3.1
Ionic CLI Version: 2.1.7
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.43
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v4.5.0
Xcode version: Not installed

![2016-11-12](https://cloud.githubusercontent.com/assets/22523298/20237595/5d653a9a-a8d7-11e6-9bef-a2089ecd2938.png)

![screenshot_2016-11-12-13-00-52 1](https://cloud.githubusercontent.com/assets/22523298/20238008/be1b5a7c-a8e1-11e6-820b-acd750f9d376.png)

**Comment by jgw96** [comment] 2016-11-14 16:45
Hello, thanks for using Ionic! Unfortunately I cannot reproduce this issue on any of my devices or on the Android simulator. What version of Android is your s4 mini running? Also, does this only happen on that specific device?

**Comment by jgw96** [comment] 2016-11-28 20:01
Hello @pimol ! Unfortunately I cannot reproduce this issue on any of my android devices running android 4.4.4 to 7.0. Because of this I am going to close this issue for now. Thanks!

**Closed by jgw96** 2016-11-28 20:01 UTC
Labels: needs reply, v2
