### ISSUE TITLE
item-reorder returning wrong indexes in some cases

### ISSUE THREAD

**Issue by estyles** [driftyco/ionic#8782] opened 2016-10-18 19:06 UTC
the (ionItemReorder) $event object returns the wrong 'to' index when dragging an item up or down, then while still dragging it, dropping it back to it's original place.

you would expect the 'from' and 'to' index to be the same value in this case, but instead it returns the 'from' index +1 or -1 depending on the last direction.

eg. dragging index 1 to index 3 then back up to index 1 and dropping it. will return, Object {from: 1, to: 2}
dragging index 3 to index 0 then back up to index 3 and dropping it. will return, Object {from: 3, to: 2}

you can also see the item is moved up or down while it should actually be remaining in place. 
eg. when using ionics reorderArray(); function

Example, 
http://plnkr.co/edit/590zKDfE071e63NYzhTK?p=preview

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS:
Node Version: v5.12.0

**Comment by jgw96** [comment] 2016-10-19 17:54
Hello, thanks for using Ionic! I am going to close this as a duplicate of https://github.com/driftyco/ionic/issues/7522.

**Closed by jgw96** 2016-10-19 17:54 UTC

**Comment by estyles** [comment] 2016-10-19 19:42
Hello, thanks for the reply, I dont think it is a duplicate, I think he is referring to the way animations on the list items don't always work. the two might be related but I doubt it.

I just fixed this bug by the way,
https://github.com/estyles/ionic/commit/4c8bbdf02d0676dcb65dd98fbfbf8767ffe0a82c

maybe you guys can figure out a better solution but this works great for me.

**Comment by estyles** [comment] 2016-10-20 00:26
nvm.. it still doenst work, just replaced it with some other problems, I'll look into it further tomorrow.
