### ISSUE TITLE
List items get tapped on scroll

### ISSUE THREAD

**Issue by danielcrk-cn** [driftyco/ionic#9108] opened 2016-11-10 11:45 UTC
#### Short description of the problem:
Unfortunately, this issue a hard to replicate at will, but it is happening a lot. When you have long lists and scroll thrugh them, items are often tapped, even tho user clearly moved the finger in a dragging motion.

I feels like this is happens happens more often when the lists are long and on slower devices.

I've really no idea how the tapping event is generated, but a wild guess is that the native "touchend" event is being used, together with cheching for scroll delta somehow, right? Somehow, it seems like the detection sometimes fails to detect that the page is actually scrolling.

**Which Ionic Version?** Ionic 2, since early alphas and up untill RC2.

Please ask if there's any way I can help reproduce and mitigate this issie. Like I wrote, I really think it is connected to performance, so try to create an overly long list to purposely make it slower, and you will see this issue.

**Comment by jgw96** [comment] 2016-11-18 21:10
Hello! Thanks for using Ionic! Unfortunately I am not able to reproduce this issue at this time. Could you make a plunker [here](http://plnkr.co/edit/GJte2b?p=preview) that I can use to reproduce this issue?

**Comment by jgw96** [comment] 2016-11-28 19:53
Hello @danielcrk-cn since i cannot reproduce this issue with the latest release of ionic 2 I am going to close this issue for now. Thanks!

**Closed by jgw96** 2016-11-28 19:53 UTC
Labels: needs reply, v2
