### ISSUE TITLE
Keyboard Enter/Next(TAB) key traversal of input fields for Android

### ISSUE THREAD

**Issue by mgersty** [driftyco/ionic#10990] opened 2017-03-30 20:45 UTC
Ionic version: (check one with "x")
[ ] 1.x
[x] 2.x

I'm submitting a ... (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

Current behavior:
With ionic keyboard plugin for Android, I'm not able to tab to the next general input field with the enter/next key. This is happening in default Ionic2 app created from scratch.

Expected behavior:
Traversal should be working in a default setup.

Steps to reproduce:

ionic start testapp --v2
create a simple login form (taken from ionic-conference-app)
run Android emulator
create form field with general ionic input fields
press TAB/Enter to switch to password field

Reproducible in emulator and device.

Other information:

Ionic info: (run ionic info from a terminal/cmd prompt and paste output below):

insert the output from ionic info here

Cordova CLI: 6.5.0
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
ios-deploy version: 1.9.1
ios-sim version: Not installed
OS: OS X El Capitan
Node Version: v7.7.1

**Comment by jgw96** [comment] 2017-03-30 21:31
Hello, thanks for using Ionic! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/9699.

**Closed by jgw96** 2017-03-30 21:31 UTC
