### ISSUE TITLE
When items in ion-list with *ngFor is scrolling, click one element wrapped with button tag, the responed item is not the one clicked

### ISSUE THREAD

**Issue by christtrc** [driftyco/ionic#6748] opened 2016-06-03 14:42 UTC
**Note: If you are having problems formatting your issue please refer to this article on using markdown in Github:**

#### Short description of the problem:
I have an `ion-list`, there are some `buttons` with `ion-item detail-none` attribute template with *ngFor. In iphone 5, 6s and 6p, when tap and scrolling, I click one button, the responsed content bind to the button is not the one i am clicking but some other when i begin scrolling.

#### What behavior are you expecting?
When scrolling `ion-list` with `button`s, The one as (click) event input is just the one current clicking.

**Steps to reproduce:**
1. generate one `ion-list` with `button`s.
2. in iphone 5/6p/6s, tap to scrolling and click one item.
3. some times the one clicked is not the one input to click event handler.

```
<ion-list>
    <button ion-item detail-none *ngFor="#item in items" (click)="processItem(item)">
        <img src="item.url"></img>
        <ion-row>......</ion-row>
    </button>
</ion-list>
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 If I use `div` or `ion-item`, the above behavior will gone, but I have to click twice to get response from the item I am clicking. I check the API http://ionicframework.com/docs/v2/api/components/item/Item/ and began to use `button`.

**Which Ionic Version?** 1.x or 2.x
2.0.0-beta.4

#### Plunker that shows an example of your issue
I only found the problem on iphone 5/ 6p/ 6s, can not reproduce in chrome or safari or android.

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

```
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.4
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v5.11.0
Xcode version: Xcode 7.3.1 Build version 7D1014
```

**Comment by jgw96** [comment] 2016-06-06 19:02
Hello, thanks for opening an issue with us! Would you mind posting a repo that i can pull and test on my device with? Im having some problems reproducing this issue. Thanks for using Ionic!

**Comment by christtrc** [comment] 2016-06-07 03:15
I create a repo: https://github.com/christtrc/ionic-app-6748.

I can reproduce it by using ios Simulator.

1. build it.
2. open xcode and run under iphone 6 simulator.
3. tap to scrolling and click 

The item current clicking is not the one "`click`" function out put(current clicking is title14, the output is title13).
![image](https://cloud.githubusercontent.com/assets/10356940/15844935/fde8db7e-2ca0-11e6-9510-673b1af02768.png)

**Comment by evgeniynet** [comment] 2016-06-07 08:43
same issue,
I fixed this with <a detail-none href=# ion-item (click)="itemTappedTL()">test</a>

**Comment by evgeniynet** [comment] 2016-06-07 08:44
sorry for formatting

same issue,
I fixed this with
`<a detail-none href=# ion-item (click)="itemTappedTL()">test</a>`

**Comment by christtrc** [comment] 2016-06-08 02:21
thanks @evgeniynet , I will try it!

**Comment by christtrc** [comment] 2016-06-08 02:29
@evgeniynet I just have a try in xcode simulator, but it still has the same problem.

**Comment by ghenry22** [comment] 2016-06-15 04:12
I have this issue in beta8.  Scroll a list and before the scroll stops tap an item.  The item selected is not the one you tapped.

**Comment by jgw96** [comment] 2016-09-28 19:10
Hello all, thanks for using Ionic! I am going to close this issue for now as I cannot reproduce with the latest rc.0 release. Thanks!

**Closed by jgw96** 2016-09-28 19:10 UTC
Labels: platform:ios, v2

**Comment by pshirsath** [comment] 2017-07-06 04:35
Hello,

**Same issue also getting me in ionic 1.**

Cordova CLI: 6.4.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic CLI Version: 1.4.0
Ionic App Lib Version: 0.0.16
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X Yosemite
Node Version: v5.0.0
Xcode version: Xcode 8.3.2 Build version 8E2002 


**If I removed  overflow-scroll="true" attribute  from ion-content then it is working fine.**

**Scroll a list and before the scroll stops tap an item or swipe it The item selected is not the one you tapped / swipped.**

I am getting this issue only for iOS For android it is working fine.
