### ISSUE TITLE
V2， use  navCtrl.push(..) in a modal page , there display dislocation

### ISSUE THREAD

**Issue by CK110** [driftyco/ionic#10348] opened 2017-02-08 09:19 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

use  navCtrl.push(..) in a modal page , there display dislocation。
![image](https://ww1.sinaimg.cn/large/006tNbRwgy1fcj6lneu0og30hu0wwnnq.gif )   

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment] 2017-02-08 17:25
Hello, thanks for opening an issue with us! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/8631

**Closed by jgw96** 2017-02-08 17:25 UTC
