### ISSUE TITLE
nav-decor always being displayed

### ISSUE THREAD

**Issue by alan-agius4** [driftyco/ionic#8252] opened 2016-09-28 15:10 UTC
#### Short description of the problem:
The nav-decor is always being displayed with a black background on iOS

#### What behavior are you expecting?
That the nav-decor doesn't have a black background

This can be re produced using the ionic starter

**Which Ionic Version?** 2

**Comment by manucorporat** [comment] 2016-09-30 21:59
@alan-agius4 @jgw96 sorry, I don't understand what's the problem

**Comment by alan-agius4** [comment] 2016-09-30 22:01
Justin is aware of the problem

**Comment by alan-agius4** [comment] 2016-10-01 08:33
@jgw96 is fully aware of the problem as I sent him some details over Slack.

**Comment by jgw96** [comment] 2016-10-04 15:49
Hello just to document the issue a little. The `nav-decor` component seems to always be displayed on iOS. This causes weird thing such as a small black "block" appearing when navigating on iOS sometimes.

**Comment by nakulgulati** [comment] 2016-10-05 06:58
`nav-decor` always being displayed, hides GoogleMaps despite the css: 
`ion-app._gmaps_cdv_ .nav-decor{
  background: transparent !important;
}`

The css doesn't seem to get applied, but unchecking and checking any of the style property from the safari inspector applies it and the maps are displayed.

I faced this issue on the iOS emulator but the code behaves as expected on the device.

**Comment by manucorporat** [comment] 2016-10-13 20:20
Can you provide a repo that reproduces this issue?

**Comment by nakulgulati** [comment] 2016-10-14 08:40
@manucorporat Link to the repo: https://github.com/nakulgulati/map-test

Also attaching a gif which demonstrates what I said in the previous comment for clarity. :)
![out](https://cloud.githubusercontent.com/assets/4583272/19381123/dcaf04ec-9217-11e6-8226-d0c0cf43fbcb.gif)

**Comment by alan-agius4** [comment] 2016-10-14 09:42
Found my issue

I had the below ``` html
<ion-content [attr.class]="options?.cssClass">
```
rather than 

``` html
<ion-content [ngClass]="options?.cssClass">
```

which resulted in `content-ios` class not being applied

**Comment by alan-agius4** [comment] 2016-10-14 10:58
@nakulgulati  Unchecking and checking the style property in the web inspector, will cause a re-paint which is most likely why it's working.

**Comment by nakulgulati** [comment] 2016-10-14 11:06
@alan-agius4 Yep that is exactly why it is working. The gif shows that the styles are loaded but not applied on nav-decor and hence causes it to bug.

**Comment by manucorporat** [comment] 2016-10-14 14:50
I tested the map-test:
![screen shot 2016-10-14 at 16 50 12](https://cloud.githubusercontent.com/assets/127379/19391787/5715b382-922e-11e6-9b35-9a80f9939e5c.png)

I works for me...

**Comment by manucorporat** [comment] 2016-10-14 14:57
ion-nav is and it has to be black, the whole time.
>What behavior are you expecting?
That the nav-decor doesn't have a black background
This can be re produced using the ionic starter

^this premise is wrong. nav-decor is using during transitions to have a fade to black effect.

I am going to close the issue and please create a new one following the issue template, explaining WHAT is failing in your app, nothing else.
Since this is issue is being hard to reproduce please provide a repo and the environment:
- Desktop? device? ios only? WKWebview? iOS Simulator?

**Closed by manucorporat** 2016-10-14 14:57 UTC
Labels: v2

**Comment by nakulgulati** [comment] 2016-10-14 15:45
@manucorporat Seems fair to close the issue. I was originally facing this issue when using Google Maps in a project and had spun up the test project then. Now the issue seems to have disappeared from the original project and still there in map-test for me.

I would look into in more and like you suggested, would open a new issue if required.

Thanks. :)

**Comment by wf9a5m75** [comment] 2017-07-06 01:34
This is the author of the cordova-googlemaps-plugin.

As of the google maps plugin `2.0.0-beta2-20170705-1715`, the plugin inserts the css automatically. 

```css
._gmaps_cdv_ .nav-decor {
    display: none !important;
    background-color: rgba(0,0,0,0) !important;
    background: rgba(0,0,0,0) !important;
}
```

This thread helps me to solve this issue. Thank you for discussing.
