### ISSUE TITLE
ion-side-menu 'drag to reveal' breaks with nested states

### ISSUE THREAD

**Issue by EduceHealth** [driftyco/ionic#2795] opened 2014-12-22 12:43 UTC
Demo code here: http://codepen.io/Grokling/pen/MYeNvB (using nightly build)

In a nutshell, I have nested states in my app. With my current setup, I can't drag to reveal the side menu after the second nested state has loaded. The menu still works, 'back' navigation still works, and using expose-aside-when works. This is a major breakage for my scenario. 

Tested on Chrome (linux and android)

**Comment by jeremyalan** [comment] 2015-03-07 17:05
This does not appear to be a bug in the framework, or if it was a few months ago, there's a work-around available now.  There's an attribute you can apply to the <ion-side-menus> element called 'enable-menu-with-back-views', which keeps the side menu functional when using nested states.

See documentation here: http://ionicframework.com/docs/api/directive/ionSideMenus/

I'm not a contributor to the core framework, I just stumbled across this issue recently, and found this little gem "hiding" in the documentation.  I thought someone on the team might see this, and close the issue, if necessary.

**Comment by mattchue** [comment] 2015-04-01 22:28
I'm experiencing this same issue, but the fix seems to have worked. Is this confirmed as the solution by the ionic team?

**Comment by Ionitron** [comment] 2015-06-30 23:07
Greetings @EduceHealth!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-06-30 23:07 UTC
Labels: ionitron:closed
