### ISSUE TITLE
[Blackberry10] Input not working on modal 

### ISSUE THREAD

**Issue by victorgutemberg** [driftyco/ionic#2104] opened 2014-08-29 13:45 UTC
Hi,

I tried to run the side menu example [1] on my BlackBerry Q10, but the inputs on the modal are not working. I tried other projects and got the same error.

The error is that when I type nothing happens with the input. 

[1] - https://github.com/driftyco/ionic-starter-sidemenu/

**Comment by Ionitron** [comment] 2015-01-30 21:09
Greetings @victorgutemberg!

I've closed this issue because my sensors indicated that perhaps it is no longer applicable--or may have already been fixed. However, if you are still experiencing this issue, please feel free to reopen it and provide the following information, so that I may assist you:

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this issue occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) which replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com). The humans there would be delighted to help you.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-01-30 21:09 UTC
Labels: blackberry, ionitron:closed, modals
