### ISSUE TITLE
bug: ion-content - memory issue

### ISSUE THREAD

**Issue by MarcBT** [driftyco/ionic#3937] opened 2015-06-13 14:10 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>
Using `<ion-content>` leads to memory issue (and crash on ios devices)

Hello everybody, we observe this issue when navigating between two pages containing an `<ion-content>`. After some investigation, we have found that replacing `<ion-content>` by a `<div>` element removes the memory issue. 
You can find a sample project illustrating the issue [here](https://github.com/MarcBT/ionic-memory-test).

When `<ion-content> ` is used :
- we obtain the following heap allocation profile with Chrome dev tools
![capture d ecran 2015-06-12 a 19 07 33](https://cloud.githubusercontent.com/assets/3440947/8144502/5415cb7c-11e2-11e5-9242-052f717e492e.png)
- analyzing memory with Xcode tools shows that memory is never freed, leading to application crash.

When we replace `<ion-content>` by a `<div>` element : 
- we obtain the following heap allocation profile
![capture d ecran 2015-06-12 a 19 07 22](https://cloud.githubusercontent.com/assets/3440947/8144515/bdabd1b2-11e2-11e5-9250-6c3742ca2990.png)
- memory is normally freed on ios device.

Can you confirm that you can reproduce the issue ? Do not hesitate to tell me if you need more info. 
Regards. </span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-06-13 14:10
Greetings @MarcBT!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3937). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3937)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by tohyongcheng** [comment] 2015-06-14 18:28
Hi, I have been facing similar issues that when pressing back and forth for pages with <ion-content>, the application crashes due to memory leaks. I'm reproducing the same error in my own production app. Hopefully we can resolve this asap as its quite a critical issue.

**Comment by tohyongcheng** [comment] 2015-06-14 18:29
#1096

**Comment by tohyongcheng** [comment] 2015-06-14 18:29
Could be related to #1096

**Comment by MarcBT** [comment] 2015-06-15 07:42
Hi, thanks for your answer and the confirmation of the issue. We also have this in production.
I have tried to examine the ion-content implementation but I am quite new with ionic and angular.
I hope that people with more experience with the framework will know how to approach and solve this issue.

**Comment by ghaiat** [comment] 2015-06-19 14:29
Hello  I m seeing the same issue here , when using ion-content and native-scrolling.
Switch to a div with css scrolling, fixes the issue, but then you cant use the ionicScrollDelegate which is useful.

**Comment by perrygovier** [comment] 2015-06-25 15:17
I believe this is related to #3985. will fix asap

**Comment by MarcBT** [comment] 2015-06-25 15:40
Hi @perrygovier ! Thanks for this good news !

**Comment by perrygovier** [comment] 2015-06-25 16:13
I fixed that leak in d6431a7b975995cf8a7b979bd1712ff098da07f8. Are you still seeing the leak? 

Note, it's very easy to create leaks in your own application code. Any use of `angular.element()` or jquery's element selector will leak.  @MarcBT's example looks clean, but for the others, be sure to check out what your app is doing too. Also, it's best to search for leaks using Chrome's heap profiler comparison in incognito mode. 

Let me know how this latest fix works, or if we still have some hunting to do.

**Comment by jskrzypek** [comment] 2015-06-26 17:58
@perrygovier Do you know if there any way to reduce the leakage from calls to `angular.element()`? we have some in some directives we use.

If you have links to any discussions of these leaks that'd be excellent as well, I haven't found much just by googling.

**Comment by MarcBT** [comment] 2015-07-02 08:39
@perrygovier 
Thanks and sorry for my late answer.
Fix works fine on the use case exemple on Chrome and memory is now freed on ios build.
Note that it is still possible to crash the use case exemple on an ios build when trying to jump quickly between the two pages. However, I suppose that it is not anymore related to ionic but to the way ios handles memory pressure to load the 1000 items (something we will avoid in a real use case).

**Comment by markharding** [comment] 2015-07-10 10:03
Android seems to perform much better than iOS for us. The tab transitions on iOS take 3-4 seconds.

**Comment by kiwinewt** [comment] 2015-08-06 22:20
@perrygovier - I tried the fix in d6431a7 in my v1.0.0 with no effect on memory use... Not sure if it's caused by the same thing though

**Comment by kiwinewt** [comment] 2015-08-06 22:32
It does appear to be much more of an issue when using <ion-side-menus> - having <ion-content> in them too

**Comment by perrygovier** [comment] 2015-08-07 15:58
@jskrzypek The big issue is the jQuery selector cache. When you use raw JS to remove an element, or remove a parent element, jQuery retains a reference to the original child element, so even though it's been removed from the DOM, a JS var still references it and it can't be GC'd. Removing the element using jQuery inside the directive's [$destroy event](http://stackoverflow.com/questions/14416894/provide-an-example-of-scopes-destroy-event) is a big step in the right direction.

**Comment by perrygovier** [comment] 2015-09-16 20:31
Closing since it appears the original issue has been resolved

**Closed by perrygovier** 2015-09-16 20:31 UTC
Labels: navigation
