### ISSUE TITLE
bug: No view transitions when going to/from tabs

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#2997] opened 2015-01-27 19:37 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Codepen http://codepen.io/mhartington/pen/zxdGKd

If you navigate to and from tabs, there are no view transitions. 
Also, the back button will not show either.</span>

<span is-issue-template></span>

**Comment by CoenWarmer** [comment] 2015-01-28 01:05
I think this Codepen describes the issue a bit better: http://codepen.io/squrler/pen/xbLbgV

**Comment by LanceEa** [comment] 2015-01-29 21:26
I'm seeing the same issue. My issue is the same as the exmaple in  @CoenWarmer codepen. Specifically the example of "non nested views". 

Off the top of my head I would think it has something to do with navigating to an "abstract" state since you are technically going to one of its children (aka the first tab).  

> An abstract state can have child states but can not get activated itself. An 'abstract' state is simply a state that can't be transitioned to. It is activated implicitly when one of its descendants are activated.
> --  Ui-Router Documentation
https://github.com/angular-ui/ui-router/wiki/Nested-States-%26-Nested-Views

**Comment by CoenWarmer** [comment] 2015-02-03 15:31
This used to work in all Ionic versions before beta 14, so in a way it's actually a regression which makes updating our apps especially difficult.

**Comment by CoenWarmer** [comment] 2015-02-10 10:23
Funny, just realized I noted this over a year ago: https://github.com/driftyco/ionic/issues/437

**Comment by adamdbradley** [comment] 2015-02-11 15:33
An abstract state isn't a view, but a container of views. Let's say you had 3 tabs, and you go to tab 1 page 1, then tab 1 page 2, then to tab 2 page 1. At tab 2 page 1 you should not have a back button because you switch histories to another tab. This is by design, and exactly how native apps works. If that back button did exist between tabs then it wouldn't know which "back" you mean. Should it go back a page in the same history? Or should it go back to another history?? Again, this is following native's design because there are multiple histories, not a linear one like a standard browser has.

As for the view transition, that too follow's native's default design pattern. However, I'm planning on making it easier to give it a transition if you want.

**Comment by CoenWarmer** [comment] 2015-02-11 19:58
The back button not appearing is less of a problem, since there are a couple of different ways to influence that when you really need one.

I'm just really looking for animations between states that may or may not have tabs. If it's easier to only enable that when the state with tabs only uses non-abstract states, that's great. Basically how it used to work in beta 13 :)

**Comment by CoenWarmer** [comment] 2015-02-18 13:01
Possible duplicate: https://github.com/driftyco/ionic/issues/3135

**Comment by CoenWarmer** [comment] 2015-02-24 22:58
It would be so, so nice if we could get some traction on this..... It's the one thing that's keeping three of our apps to be upgraded to beta 14... Pretty please? :)

**Comment by beauby** [comment] 2015-03-04 01:41
Adding the possibility to animate transitions between tabs would, indeed, be great. That, and the ability to swipe between tabs.

**Comment by CoenWarmer** [comment] 2015-03-04 07:06
@beauby you misunderstand: this issue is to describe the behavior where state 1 does not contain tabs, and state 2 does contain tabs. If you navigate from state 1 to state 2, in beta 14 there is no transition animation. You immediately are dumped to state 2.

This issue is not about having an animation between tabs on one state. That is not something that native UI frameworks use as default and so not something I expect ionic to support out of the box.

**Comment by PedroJusto** [comment] 2015-03-20 16:58
@beauby , @adamdbradley here is a very simple codepen demonstrating what @CoenWarmer is talking about. Like @CoenWarmer , I understand that there is no transition animation between tabs makes sense. An abstract state and his childs should be seen as one.

http://codepen.io/anon/pen/Qwzama
When navigating from HOME to OTHER-PAGE animation and back-button appears, but when navigating from OTHER-PAGE to TABS the animation and back-button is lost.

**Comment by CoenWarmer** [comment] 2015-03-28 11:05
Still an issue in the nightly... (rc1 >)

**Comment by hardywu** [comment] 2015-03-29 01:02
@adamdbradley  I do not have a full native app dev experience. But from years' experience of using native app, it tells that going from state 'tabs.home' to state 'login' does give users a back button.

Just wonder if this bug is ignored due to some misunderstanding.

**Comment by sgentile** [comment] 2015-04-06 20:26
same issue as above...

@beauby , @adamdbradley here is a very simple codepen demonstrating what @CoenWarmer is talking about. Like @CoenWarmer , I understand that there is no transition animation between tabs makes sense. An abstract state and his childs should be seen as one.
But if you transition from "STATE1"to another "STATE_WITH_TABS" ,it should have 'navigation' and in his tabs the back button should go back to "STATE1".

http://codepen.io/anon/pen/Qwzama
When navigating from HOME to OTHER-PAGE animation and back-button appears, but when navigating from OTHER-PAGE to TABS the animation and back-button is lost.

**Comment by sgentile** [comment] 2015-04-07 11:30
I should add, the issue I'm referring to is the 'back-button is lost'

**Comment by stefek99** [comment] 2015-04-10 12:24
+1

**'back-button is lost**

Yes, I've seen that I was really confused why is this happening.

Here is the example I used as a base in my project: http://codepen.io/gnomeontherun/pen/tbvdH?editors=101

* When I click on a tab - no back button.
* When I click on a link on the page - there is back button.
* When I click on a item in the side menu - no back button.

Short video: http://screencast.com/t/0gsoogJf

**Comment by rubocoptero** [comment] 2015-04-11 09:59
@sgentile that is exactly the same issue I'm facing right now!

+1

**Comment by colesobotka** [comment] 2015-05-03 02:16
I'm having a very similar problem, but not sure if it's the same as others.

I have two main states: 1) Tabs 2) options

All I want to be able to do is navigate from the Tabs state to the options state WITH an animation, but for the life of me I cannot force one. I can manually add the back button to the options page, but again, I'm missing all of the animations.

I also do not want to implement a "Hamburger" menu, but I guess I will if I have to. I think that navigating away from a tabbed interface and being able to go back is completely acceptable for UX. However, I agree that it's a bit odd to navigate TO a tabbed interface and have a back button included.

**Comment by yxwu25** [comment] 2015-05-04 06:41
+1

**Comment by JerryBels** [comment] 2015-05-04 12:58
+1

**Comment by kaumac** [comment] 2015-05-05 00:22
It seems theres a lot of issues in this issue (lost back button, no transitions when going to tabs view and no transition when through tabs)

What annoys me right now is the lack of transitions between tabs.

So +1 here

**Comment by JerryBels** [comment] 2015-05-05 13:22
In my case it's really an issue : 
- I have two tabs, which display a list of images
- When tapping on an image I change state, get out of the tabs to display the page dedicated to this image (comments, like, etc...)

No back button, no animation !

Here is a codepen very little modified from the original "tabs and navigation" : http://codepen.io/JerryBels/pen/qdOqMb

**Comment by itrethan** [comment] 2015-05-09 21:39
+1

**Comment by DongHongfei** [comment] 2015-05-10 01:16
+1

**Comment by michahell** [comment] 2015-05-12 21:25
+1 I think this issue has soo many different names / threads both here on github and ionic forum :( I hope this gets solved soon :(

**Comment by mhartington** [comment] 2015-05-12 21:31
This issue will be address post 1.0.
Right now, this is a limitation of ui-router and we will be addressing this.

**Comment by michahell** [comment] 2015-05-12 21:43
Ah, I suspected there was some deeper reason why this was not possible. thanks @mhartington for clearing that up!

**Comment by JerryBels** [comment] 2015-05-20 09:04
@mhartington thanks, I hope we'll see a solution soon enough !

**Comment by adamelevate** [comment] 2015-05-23 19:21
+1

**Comment by htc550605125** [comment] 2015-05-27 04:39
I have created a pull request but it failed on tests... It seems like that's "by design". Should I modify the tests?

**Comment by JerryBels** [comment] 2015-05-28 13:31
Referencing this issue in the forum : http://forum.ionicframework.com/t/back-button-with-nested-states/16017

Looks to me the same topic.

**Comment by sherlock221** [comment] 2015-05-30 13:50
+1 same

**Comment by zero7u** [comment] 2015-06-04 08:19
@JerryBels +1 same here!
Is it possible to control the history navigation and transitions by ourselves? optionally?

**Comment by dasgib** [comment] 2015-06-04 08:37
+1

I'm especially interested in the transition, rather than the history.

**Comment by nihgwu** [comment] 2015-06-05 10:25
is there a workaround solution?

**Comment by adamdbradley** [comment] 2015-06-08 14:47
Regarding transitions between a non-tabs view and a tabs view, in the current architecture this is challenge due to how the tabs are nested, and a tab is nested inside of tabs. A lot of the limitations are due to how the leaving view is the container for the entering view. The core structure to how transitions and animations works will updated in Ionic 2.0 to allow for any transition between any view. I'm going to change this milestone to 2.0.

**Comment by JerryBels** [comment] 2015-06-08 14:56
@adamdbradley thanks for passing by to keep us updated. I understand very well what you say, and that you don't want to work on something that will be solved with a future version. But, if I'm not wrong, Ionic 2.0 will be based on Angular 2.0, right ? There is two big problems for us with that, then : 

- Migrating to Angular 2.0 from a current Angular app is already known to be something that will be very hard, if even possible.
- It's not even close to release, let alone ready for production use... And we're speaking of production apps that currently lack the beauty and smoothness of native. At least I know that if no decent workaround is given here, I will have to look for a custom hacky solution.

Anyway, thanks again for your work for us :)

**Comment by michahell** [comment] 2015-06-08 15:12
Aha, that makes a lot of sense. I myself was thinking of the following approach:
1. create screenshot of current view that is going to be removed.
2. overlay the screenshot on top of all views (is this possible? maybe outside angular/ionic?)
3. animate the screenshot out when the next view (in this case the tabbed view) has loaded.

This maybe goes against standard conventions of using css / svg for animations, but it has solved
animation problems in the past for me with other frameworks and non-mobile applications...

I might be able to work on this next weekend!

**Comment by JerryBels** [comment] 2015-06-09 09:06
@michahell if you really do find a solution, please share it with us ? :)

**Comment by michahell** [comment] 2015-06-09 09:42
@JerryBels of course! I'll know this weekend ;)

**Comment by michael-levin** [comment] 2015-06-09 18:59
+1

**Comment by dellheng** [comment] 2015-06-11 05:38
+1

**Comment by ashishdasnurkar** [comment] 2015-06-13 13:27
+1 If I go from a simple no-tabs state to a tabs state the default tab view should show a back link to the previous state. Otherwise without giving a custom button within tabs view there is no way back for the ios user at least.

**Comment by zero7u** [comment] 2015-06-15 03:24
Is there a way to hide the tabs bar manually? Just like this demo: http://codepen.io/ionic/pen/mHtlC

**Comment by beauby** [comment] 2015-06-15 05:40
@zero7u Add `class="tabs-item-hide"` to `<ion-tabs>`.

**Comment by zero7u** [comment] 2015-06-15 06:37
@beauby Thanks! 
Base on this idea, I made a solution for my app, say something about it, please!
http://codepen.io/zero7u/pen/qdXZVW

**Comment by michahell** [comment] 2015-06-15 10:28
I haven't been able to spend time on my ionic project this weekend unfortunately, but what @zero7u made looks pretty good actually!

**Comment by evertoncorrea88** [comment] 2015-06-18 05:47
I'm having the same problem, but in the opposite direction. I have 2 states:
- State 1: 3 tabs and a button on the top header to State 2;
- State 2: a simple list.
There is no back button when I navigate from State 1 to State 2.

I was thinking to save the current link when I press the button and send this information to State 2, and in State 2 use this link to set the back button. Is that a valid work around or is there any easiest way?

**Comment by djangojack** [comment] 2015-06-27 16:27
+1

**Comment by thinkAjith** [comment] 2015-06-29 12:19
+1

**Comment by kabogo** [comment] 2015-07-08 07:49
+1

**Comment by jason-engage** [comment] 2015-07-12 21:42
I was able to do a workaround for this using the CSS Animate library, and some SASS.

Going from A Single Page View to a Tab Container View, the slide transition seems to work fine if you add ' nav-direction="back" ' on the back button in the Single Page View.

However, going from a Tab Container to a Single Page View seems to skip the sliding animation altogether. 

So I included 'animate.css' in the index.html and using a bit of css hacks I am able to have a nice slide from the tabs into the Single Page View. I'm using SASS btw, and a fairly simple view setup. Notice that I'm using the 'slideOutLeft' animation to hide it.

```
//ADD THIS TO YOUR SCSS file
//This first part makes sure the page slides
ion-view.main-container.pane {
    opacity:1!important;
    &[nav-view="cached"] {
        @include animation(slideOutLeft 400ms ease);
        display:block!important;
    }
    //This second part makes sure that the header slides too
    .a-tab-view-class.pane ion-nav-bar.hide {
        display:block!important;
    }
}
```
In the Tab View (that exists inside the tab container view), make sure you have a class (ie. 'a-tab-view-class') on the ion-view tag. And also make sure that you copy over the <ion-nav-bar> tag from the main index page, otherwise, you can't target the ion-nav-bar properly.

Like so:
```
<ion-view title="Your App Name" class="a-tab-view-class">

    <ion-nav-bar class="bar-positive">
        <ion-nav-buttons side="secondary">
            <button class="button icon ion-plus" ng-click="goSinglePage()">
            </button>
        </ion-nav-buttons>
    </ion-nav-bar>

   <ion-content>...</ion-content>
</ion-view>
```

**Comment by JerryBels** [comment] 2015-07-13 13:10
@jason-engage thanks for your help, but you state that 

    Going back from A Single Page View to a Tab Container View, the slide transition seems to work fine if you add ' nav-direction="back" ' on the back button in the Single Page View

For me, and as I understand here I'm far from being the only one, the said single page doesn't have a back button at all - it's not on the same nav stack. So your method can help provide the transition to the single page (I haven't tested it), but can't resolve the whole issue we're facing here.

Thanks anyway for sharing the possibility to use animate.css on ion-views !

**Comment by sgentile** [comment] 2015-07-13 13:17
Yes to JerryBels - this is the issue

**Comment by JerryBels** [comment] 2015-07-13 13:32
@michahell did you have time to work on a solution ? Since you said yo uwere going to look for one... What @zero7u  did is great, but there is a huge limitation to it : you have to set the state of your single page in the same ion-nav-view that the wanted tab is in - this isn't possible to use in a real life, complex application like the one I'm working on.

For exemple, I need to be able to reach an image from the tabbed view, but that image can be reached also from other places - forcing me to define multiple states for each view. Same goes with user profile, for the user that uploaded the image, or in a chatlist, or simply the userslist... I need to define a state for each of them, withresolve conditions, etc... It's very complicated and not really worth it.

We need a complete, working solution, and since @adamdbradley said they were not planning to do anything about it, we're a little on our own here !

**Comment by jason-engage** [comment] 2015-07-13 16:23
@JerryBels If you're trying to force transitions between tabbed views, then I have to agree with the ionic team that this is not a standard design pattern you see on any major apps. I think some people like me would like to see transitions between tabbed and single view, which seems to be a bug in ionic from my view.

But I'm pretty sure you could achieve tabbed-view transition effects with Animate.css and targeting the right tag attributes as they are added/removed during view changes. I don't think you can do it using ionicHistory or ionicConfig out of the box.

**Comment by jason-engage** [comment] 2015-07-13 22:55
@JerryBels Actually there is a simple way of getting transitions between tabs but you can't use the ion-tabs directive. You have to create your tab container using regular html and ionic css like so:

```
<ion-view class="tabs-container">

    <!-- Single UI VIEW -->
    <ion-nav-view name="tabview"></ion-nav-view>

    <!-- TABS -->
    <div class="tabs tabs-icon-top">
        <a class="tab-item" ng-click="goTab1()" ng-class="{ active : settings.isTab1}">
            <i class="icon ion-ios-flame"></i> Tab1
        </a>
        <a class="tab-item" ng-click="goTab2()" ng-class="{ active : settings.isTab2 }">
            <i class="icon ion-ios-location"></i> Tab2
        </a>
        <a class="tab-item" data-ng-click="goChat()" ng-class="{ active : settings.isTab3, 'has-badge' : settings.numberOfBadges != 0 }">
            <i class="icon ion-ios-chatboxes"></i> Tab3 <span class="badge badge-assertive" ng-if="settings.numberOfBages != 0">{{settings.numberOfBadges}}</span>
        </a>
        <a class="tab-item" ng-click="goTab4()" ng-class="{ active : settingsTab4}">
            <i class="icon ion-ios-people"></i> Tab4
        </a>
    </div>

</ion-view>
```

In your goTabX() functions, you'll need to add this code before changing the state:
```
$ionicConfig.views.transition('platform');
$state.go('tabview.tabX')
```

This works differently than the ion-tab directive which loads each tab view in separate views. Instead this way, you load each tab in the same view using the correct $states in $stateProvider.

You'll also need to keep track of which tab is active, and how many badges each one might have. I supplied some sample code for that.

I didn't provide all the code you need, but if you really need to get it working I can help you out further using this method.

**Comment by JerryBels** [comment] 2015-07-14 08:23
@jason-engage you are really, really kind to help like that, thank you.

But I'm afraid you really have it wrong : I don't want to induce a transition between tabs, I do want to do the exact same as you : going from a Single Page to a Tabbed Page, and from a Tabbed Page to a Single Page, with transitions and back buttons. In both cases, I (and others) don't have any transition (which can be fixed with a method like the one you used) nor back button (which is considerably more of an issue).

I also thought about using regular elements with classes instead of the directives, I will give it a shot today or tomorrow and update you guys.

**Comment by JerryBels** [comment] 2015-07-20 08:08
Okay, so, I had success implementing tabs with transitions and back buttons by getting rid of tabs directives and using instead my own states with tabs CSS only, like Jason shown above. ATM, and until tabs are production ready (cleaned from this huge bug, then) it's your best bet.

**Comment by roytan883** [comment] 2015-07-23 17:01
STUPID design: each tab has its own navi history.  No one want this feature, just give me ONE navi history for my app, is it HARD? 

People just want the simplest operations : go go go back back back, the tabs SHOULD NOT NOT NOT break it !!!

This is main reason i switch ionic to onsenui. 

After months, today i check it. The stupid design still exist !!!

**Comment by roytan883** [comment] 2015-07-23 17:11
If you struggle with ionic tabs navigation, just try "onsenui" tabs, simple and clean.

I have no idea why ionic team make a normal "tabs" component so complicated !!! why the tabs jump into pages navigation? Tabs just only works inside one page, that's all !!!

Does the ionic team ever read Android and IOS doc? Does the native tabs override the APP pages navigation ???

**Comment by danbucholtz** [comment] 2016-04-27 04:30
Hi everyone,

Following up on what @adamdbradley previously said, there are some very challenging limitations with ui-router and navigation/transitions in Ionic v1.  We're really sorry about that.  Many of these issues will be resolved by the improved navigation architecture in V2.  We won't be able to fix this in V1 unless we do significant refactoring.  If this is something the community really wants, we could reconsider.

Thanks,
Dan

**Closed by danbucholtz** 2016-04-27 04:30 UTC
Labels: navigation, v1
