### ISSUE TITLE
ionic2 pages overlapping because of z-index of LoadingController

### ISSUE THREAD

**Issue by rhuldip** [driftyco/ionic#8234] opened 2016-09-27 13:48 UTC
I am pushing pages by using navController.push(PageName).
But the issue is that the pages are overlapping.
I can see that there is some problem with z-index but how can i solve it.
Example-From Homepage whose z-index 9998, i am calling navController.push(nextPage) whose z-index is 9999.Everything works fine but now when i push navController.push(nextPage2),the nextPage is overlapping nextPage2.
nextPage2 z-index is 9998.
On further checking,i found that when the 2nd page is pushed its z-index was 1000,after that loadingcontroller is called and on loading controller dismiss the z-index of page is becoming 9998.
How can i correct this because i am having multiple pages and i can't set z-index of each page manually.
![screen shot 2016-09-27 at 4 02 25 pm](https://cloud.githubusercontent.com/assets/12796087/18876444/5e89cd64-84e7-11e6-848b-92afb54a1be1.png)

when i used debugger i found that it is having because of loadingController but how can i resolve it.
This is the code i am calling when i am pushing newsandalertoption component.

```
ionViewDidEnter()
{

this.getNewsAndAlertsObject = new GetNewsAndAlertsObject();
//alert("NewsalertoptionsPage="+this.navCtrl.length());
var myLoader =  this.commonUtility.getLoader('Getting News...');
myLoader.present();
this.getNewsAndAlertsObject.EID= "H122984";
this.getNewsAndAlertsObject.SBG ="HON CORP";
this.remedyService.getNewsAndAlerts(this.getNewsAndAlertsObject).subscribe(
  data =>{
      myLoader.dismiss().then(()=>{
        console.log("success in getMyRequest"+JSON.stringify(data));
        debugger
        this.myNewsAndAlertsData = data;
        debugger
      })
  },
  err =>{
      console.log("err block");
      myLoader.dismiss();
      console.log("Error in getMyRequest"+JSON.stringify(err));
      console.log("1");
      var errObj = err._body;
      console.log("2");
      errObj = JSON.parse(errObj);
      console.log("3");
      //alert("errObj = "+errObj);
      console.log("4");
      //alert("errObj1="+errObj.error);
      if(errObj.error != undefined)
      {
        console.log("undefined block");
        if(errObj.error == "invalid_token")
        {
          this.navCtrl.setRoot(LoginPage);
        }
        else
        {
          console.log("ivalid not block");
          var myAlert= this.commonUtility.getAlert("Network Error", "Please try again later");
          myAlert.present();
        }
      }
      else
      {
        console.log("major else block");
        var myAlert= this.commonUtility.getAlert("Network Error", "Please try again later");
        myAlert.present();
      }
  },
  () =>
  {
      console.log("Completion of getMyRequest");
      //this.myLoadingCtrl.dismiss();
  }
);
}
```

After the first debugger,the z-index is changing.

My commonUtility file which is giving me loader is-

```
import {LoadingController,AlertController} from "ionic-angular";
import { Injectable } from '@angular/core';

@Injectable()
export class CommonUtility
{
constructor(public loadingCtrl: LoadingController,public alertCtrl: AlertController)
{
console.log("Creating object for CommonUtility");
}
getLoader(content)
{
return this.loadingCtrl.create({
content: content
});
}
getAlert(alertTitle, alertSubTitle)
{
let popUp = this.alertCtrl.create({
title: alertTitle,
subTitle: alertSubTitle,
buttons: [
{
text:'Dismiss',
role:'cancel',
handler: () =>
{
console.log("alert box dismiss clicked");
popUp.dismiss();
}
}
]
});
popUp.present();
return popUp;
}
}
```

**Comment by frankpolkm** [comment] 2016-09-27 14:51
Same issue in my app, too. It is not always but very often when I switch tabs very quick.

**Comment by jgw96** [comment] 2016-09-28 16:32
Hello, thanks for using Ionic! Would you all be able to provide a repo that I can use to reproduce this issue? Thanks!

**Comment by jgw96** [comment] 2016-10-03 01:10
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-10-03 01:10 UTC
Labels: needs reply, v2

**Comment by roshandhabekar** [comment] 2017-01-24 11:32
have you found any solution for this please let me know.
