### ISSUE TITLE
ionic v2 left alignment button issue in the navbar of header

### ISSUE THREAD

**Issue by dragon28** [driftyco/ionic#8930] opened 2016-10-27 15:24 UTC
Hello :-)

Nodejs Version: v4.6.1
npm version: v3.10.9
ionic version: v2.1.1
OS: Linux 4.4.0-45-generic  Ubuntu (16.04 x64)

I tried to align the button to left hand-side by:

<ion-header>

```
  <ion-navbar color="primary">

    <ion-buttons start>
            <button>Back</button>
    </ion-buttons>

        <ion-title text-center>Test</ion-title>

  </ion-navbar>
```

</ion-header>

and not working. Moreover, the button should be on the left hand-side position and end on the opposite position which the right hand-side position.

Thanks

**Comment by jgw96** [comment] 2016-10-27 18:35
Hello, unfortunately I cannot reproduce this issue. Could you post a repo i can use to reproduce this issue? Also, could you post a screenshot of the issue?

**Comment by dragon28** [comment] 2016-10-29 15:43
Hello :-)

I have attached the screen capture picture.

Please refer to the link below for the repo which you required for testing

https://github.com/dragon28/Ionic2


![screenshot from 2016-10-29 23-09-06](https://cloud.githubusercontent.com/assets/4351285/19830541/bebcbbde-9e2c-11e6-8974-817223b0b8da.png)

**Comment by manucorporat** [comment] 2016-10-29 16:12
what version of ionic are you using? can you run `ionic info`?

**Comment by dragon28** [comment] 2016-10-30 10:44
Hello :-)

Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
OS: Distributor ID:	Ubuntu Description:	Ubuntu 16.04.1 LTS 
Node Version: v4.6.1


![screenshot from 2016-10-30 18-43-08](https://cloud.githubusercontent.com/assets/4351285/19836049/cc4a93f8-9ed0-11e6-928f-a8b2474db5cc.png)

**Comment by jgw96** [comment] 2016-10-31 21:12
Hello, thanks for using Ionic! This is actually expected behavior when ionic is using the Material design css (on desktop and Android). The reason for this is to follow the material design standards. On iOS the button will be on the left which matches the iOS design spec. Since this is expected behavior I am going to close this issue for now.

**Closed by jgw96** 2016-10-31 21:12 UTC
Labels: needs reply, v2
