### ISSUE TITLE
bug: iOS search-bar throws exception sometimes

### ISSUE THREAD

**Issue by ErkoKnoll** [driftyco/ionic#6177] opened 2016-04-15 06:07 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>Sometimes (not frequently) when typing into search bar in iOS it throws an exception and because of that everything else will be unresponsive.

Stack trace I was able to catch a while ago:</span>
Important part: `[Error] _Context {element: <ion-searchbar class="ng-untouched ng-valid searchbar-focused searchbar-left-aligned searchbar-has-v…, componentElement: <ion-page class="main-page show-page">, context: MainPage, locals: {}, injector: Injector, …}`

All of it:
`[Error] EXCEPTION: Expression 'isFocused in MainPage@13:8' has changed after it was checked. Previous value: 'true'. Current value: 'false' in [isFocused in MainPage@13:8]
logError
logGroup
call
(anonymous function)
_notifyOnError
onError
run
(anonymous function)
run
(anonymous function)
(anonymous function)
tryCatcher
next
_next
next
emit
(anonymous function)
run
_notifyOnTurnDone
(anonymous function)
run
(anonymous function)
run
zoneBoundFn
lib$es6$promise$$internal$$tryCatch
lib$es6$promise$$internal$$invokeCallback
lib$es6$promise$$internal$$publish
(anonymous function)
run
zoneBoundFn
lib$es6$promise$asap$$flush
[Error] ORIGINAL EXCEPTION: Expression 'isFocused in MainPage@13:8' has changed after it was checked. Previous value: 'true'. Current value: 'false'
logError
call
(anonymous function)
_notifyOnError
onError
run
(anonymous function)
run
(anonymous function)
(anonymous function)
tryCatcher
next
_next
next
emit
(anonymous function)
run
_notifyOnTurnDone
(anonymous function)
run
(anonymous function)
run
zoneBoundFn
lib$es6$promise$$internal$$tryCatch
lib$es6$promise$$internal$$invokeCallback
lib$es6$promise$$internal$$publish
(anonymous function)
run
zoneBoundFn
lib$es6$promise$asap$$flush
[Error] ORIGINAL STACKTRACE:
logError
call
(anonymous function)
_notifyOnError
onError
run
(anonymous function)
run
(anonymous function)
(anonymous function)
tryCatcher
next
_next
next
emit
(anonymous function)
run
_notifyOnTurnDone
(anonymous function)
run
(anonymous function)
run
zoneBoundFn
lib$es6$promise$$internal$$tryCatch
lib$es6$promise$$internal$$invokeCallback
lib$es6$promise$$internal$$publish
(anonymous function)
run
zoneBoundFn
lib$es6$promise$asap$$flush
[Error] BaseException@file:///var/mobile/Containers/Bundle/Application/18365831-499B-4642-9FD7-F96B626C2B10/Address%20Book.app/www/build/js/app.bundle.js:7879:33
ExpressionChangedAfterItHasBeenCheckedException@file:///var/mobile/Containers/Bundle/Application/18365831-499B-4642-9FD7-F96B626C2B10/Address%20Book.app/www/build/js/app.bundle.js:12765:21
throwOnChangeError@file:///var/mobile/Containers/Bundle/Application/18365831-499B-4642-9FD7-F96B626C2B10/Address%20Book.app/www/build/js/app.bundle.js:14534:80
detectChangesInRecordsInternal
detectChangesInRecords@file:///var/mobile/Containers/Bundle/Application/18365831-499B-4642-9FD7-F96B626C2B10/Address%20Book.app/www/build/js/app.bundle.js:14336:49
runDetectChanges@file:///var/mobile/Containers/Bundle/Application/18365831-499B-4642-9FD7-F96B626C2B10/Address%20Book.app/www/build/js/app.bundle.js:14313:37
_detectChangesInViewChildren@file:///var/mobile/Containers/Bundle/Application/18365831-499B-4642-9FD7-F96B626C2B10/Address%20Book.app/www/build/js/app.bundle.js:14420:35
runDetectChanges@file:///var/mobile/Containers/Bundle/Application/18365831-499B-4642-9FD7-F96B626C2B10/Address%20Book.app/www/build/js/app.bundle.js:14317:43
_detectChangesContentChildren@file:///var/mobile/Containers/Bundle/Application/18365831-499B-4642-9FD7-F96B626C2B10/Address%20Book.app/www/build/js/app.bundle.js:14413:35
runDetectChanges@file:///var/mobile/Containers/Bundle/Application/18365831-499B-4642-9FD7-F96B626C2B10/Address%20Book.app/www/build/js/app.bundle.js:14314:44
_detectChangesInViewChildren@file:///var/mobile/Containers/Bundle/Application/18365831-499B-4642-9FD7-F96B626C2B10/Address%20Book.app/www/build/js/app.bundle.js:14420:35
runDetectChanges@file:///var/mobile/Containers/Bundle/Application/18365831-499B-4642-9FD7-F96B626C2B10/Address%20Book.app/www/build/js/app.bundle.js:14317:43
_detectChangesInViewChildren@file:///var/mobile/Containers/Bundle/Application/18365831-499B-4642-9FD7-F96B626C2B10/Address%20Book.app/www/build/js/app.bundle.js:14420:35
runDetectChanges@file:///var/mobile/Containers/Bundle/Application/18365831-499B-4642-9FD7-F96B626C2B10/Address%20Book.app/www/build/js/app.bundle.js:14317:43
checkNoChanges@file:///var/mobile/Containers/Bundle/Application/18365831-499B-4642-9FD7-F96B626C2B10/Address%20Book.app/www/build/js/app.bundle.js:14305:35
checkNoChanges@file:///var/mobile/Containers/Bundle/Application/18365831-499B-4642-9FD7-F96B626C2B10/Address%20Book.app/www/build/js/app.bundle.js:14573:89
file:///var/mobile/Containers/Bundle/Application/18365831-499B-4642-9FD7-F96B626C2B10/Address%20Book.app/www/build/js/app.bundle.js:17578:103
forEach@[native code]
apply@[native code]
call@[native code]
call@[native code]
forEach@file:///var/mobile/Containers/Bundle/Application/18365831-499B-4642-9FD7-F96B626C2B10/Address%20Book.app/www/build/js/app.bundle.js:72:16880
tick@file:///var/mobile/Containers/Bundle/Application/18365831-499B-4642-9FD7-F96B626C2B10/Address%20Book.app/www/build/js/app.bundle.js:17578:50
file:///var/mobile/Containers/Bundle/Application/18365831-499B-4642-9FD7-F96B626C2B10/Address%20Book.app/www/build/js/app.bundle.js:17489:128
run@file:///var/mobile/Containers/Bundle/Application/18365831-499B-4642-9FD7-F96B626C2B10/Address%20Book.app/www/build/js/app.bundle.js:2270:30
file:///var/mobile/Containers/Bundle/Application/18365831-499B-4642-9FD7-F96B626C2B10/Address%20Book.app/www/build/js/app.bundle.js:17954:48
run@file:///var/mobile/Containers/Bundle/Application/18365831-499B-4642-9FD7-F96B626C2B10/Address%20Book.app/www/build/js/app.bundle.js:17902:44
file:///var/mobile/Containers/Bundle/Application/18365831-499B-4642-9FD7-F96B626C2B10/Address%20Book.app/www/build/js/app.bundle.js:17489:103
file:///var/mobile/Containers/Bundle/Application/18365831-499B-4642-9FD7-F96B626C2B10/Address%20Book.app/www/build/js/app.bundle.js:14844:57
tryCatcher@file:///var/mobile/Containers/Bundle/Application/18365831-499B-4642-9FD7-F96B626C2B10/Address%20Book.app/www/build/js/app.bundle.js:15422:37
next@file:///var/mobile/Containers/Bundle/Application/18365831-499B-4642-9FD7-F96B626C2B10/Address%20Book.app/www/build/js/app.bundle.js:15369:24
_next@file:///var/mobile/Containers/Bundle/Application/18365831-499B-4642-9FD7-F96B626C2B10/Address%20Book.app/www/build/js/app.bundle.js:15045:35
next@file:///var/mobile/Containers/Bundle/Application/18365831-499B-4642-9FD7-F96B626C2B10/Address%20Book.app/www/build/js/app.bundle.js:15008:20
emit@file:///var/mobile/Containers/Bundle/Application/18365831-499B-4642-9FD7-F96B626C2B10/Address%20Book.app/www/build/js/app.bundle.js:14833:81
file:///var/mobile/Containers/Bundle/Application/18365831-499B-4642-9FD7-F96B626C2B10/Address%20Book.app/www/build/js/app.bundle.js:17795:84
run@file:///var/mobile/Containers/Bundle/Application/18365831-499B-4642-9FD7-F96B626C2B10/Address%20Book.app/www/build/js/app.bundle.js:2270:30
_notifyOnTurnDone@file:///var/mobile/Containers/Bundle/Application/18365831-499B-4642-9FD7-F96B626C2B10/Address%20Book.app/www/build/js/app.bundle.js:17795:24
file:///var/mobile/Containers/Bundle/Application/18365831-499B-4642-9FD7-F96B626C2B10/Address%20Book.app/www/build/js/app.bundle.js:17968:62
run@file:///var/mobile/Containers/Bundle/Application/18365831-499B-4642-9FD7-F96B626C2B10/Address%20Book.app/www/build/js/app.bundle.js:17902:44
file:///var/mobile/Containers/Bundle/Application/18365831-499B-4642-9FD7-F96B626C2B10/Address%20Book.app/www/build/js/app.bundle.js:75262:44
run@file:///var/mobile/Containers/Bundle/Application/18365831-499B-4642-9FD7-F96B626C2B10/Address%20Book.app/www/build/js/app.bundle.js:2270:30
zoneBoundFn@file:///var/mobile/Containers/Bundle/Application/18365831-499B-4642-9FD7-F96B626C2B10/Address%20Book.app/www/build/js/app.bundle.js:2247:30
lib$es6$promise$$internal$$tryCatch@file:///var/mobile/Containers/Bundle/Application/18365831-499B-4642-9FD7-F96B626C2B10/Address%20Book.app/www/build/js/app.bundle.js:1495:26
lib$es6$promise$$internal$$invokeCallback@file:///var/mobile/Containers/Bundle/Application/18365831-499B-4642-9FD7-F96B626C2B10/Address%20Book.app/www/build/js/app.bundle.js:1507:54
lib$es6$promise$$internal$$publish@file:///var/mobile/Containers/Bundle/Application/18365831-499B-4642-9FD7-F96B626C2B10/Address%20Book.app/www/build/js/app.bundle.js:1478:54
file:///var/mobile/Containers/Bundle/Application/18365831-499B-4642-9FD7-F96B626C2B10/Address%20Book.app/www/build/js/app.bundle.js:1150:13
run@file:///var/mobile/Containers/Bundle/Application/18365831-499B-4642-9FD7-F96B626C2B10/Address%20Book.app/www/build/js/app.bundle.js:2270:30
zoneBoundFn@file:///var/mobile/Containers/Bundle/Application/18365831-499B-4642-9FD7-F96B626C2B10/Address%20Book.app/www/build/js/app.bundle.js:2247:30
lib$es6$promise$asap$$flush@file:///var/mobile/Containers/Bundle/Application/18365831-499B-4642-9FD7-F96B626C2B10/Address%20Book.app/www/build/js/app.bundle.js:1289:19
logError
call
(anonymous function)
_notifyOnError
onError
run
(anonymous function)
run
(anonymous function)
(anonymous function)
tryCatcher
next
_next
next
emit
(anonymous function)
run
_notifyOnTurnDone
(anonymous function)
run
(anonymous function)
run
zoneBoundFn
lib$es6$promise$$internal$$tryCatch
lib$es6$promise$$internal$$invokeCallback
lib$es6$promise$$internal$$publish
(anonymous function)
run
zoneBoundFn
lib$es6$promise$asap$$flush
[Error] ERROR CONTEXT:
logError
call
(anonymous function)
_notifyOnError
onError
run
(anonymous function)
run
(anonymous function)
(anonymous function)
tryCatcher
next
_next
next
emit
(anonymous function)
run
_notifyOnTurnDone
(anonymous function)
run
(anonymous function)
run
zoneBoundFn
lib$es6$promise$$internal$$tryCatch
lib$es6$promise$$internal$$invokeCallback
lib$es6$promise$$internal$$publish
(anonymous function)
run
zoneBoundFn
lib$es6$promise$asap$$flush
[Error] _Context {element: <ion-searchbar class="ng-untouched ng-valid searchbar-focused searchbar-left-aligned searchbar-has-v…, componentElement: <ion-page class="main-page show-page">, context: MainPage, locals: {}, injector: Injector, …}
logError
call
(anonymous function)
_notifyOnError
onError
run
(anonymous function)
run
(anonymous function)
(anonymous function)
tryCatcher
next
_next
next
emit
(anonymous function)
run
_notifyOnTurnDone
(anonymous function)
run
(anonymous function)
run
zoneBoundFn
lib$es6$promise$$internal$$tryCatch
lib$es6$promise$$internal$$invokeCallback
lib$es6$promise$$internal$$publish
(anonymous function)
run
zoneBoundFn
lib$es6$promise$asap$$flush
`

<span is-issue-template></span>

**Comment by jgw96** [comment] 2016-04-15 14:25
Hello! Thanks for opening an issue with us! Would you mind putting together a plunker that i can use to reproduce this issue with?

**Comment by ErkoKnoll** [comment] 2016-04-15 15:15
It is regular search bar, nothing special about it, as for reproducing it, I've only managed to trigger it  quite rarely. I will let you know if I manage to find a pattern or something. I recommend trying to understand why `Expression 'isFocused in MainPage@13:8' has changed after it was checked. Previous value: 'true'` might be thrown on search bar.

**Comment by jtushar53** [comment] 2016-05-02 13:18
Me too getting same error 

EXCEPTION: Expression 'value in UserconfigPage@6:0' has changed after it was checked. Previous value: 'khar'. Current value: 'Khar West' in [value in UserconfigPage@6:0] 

on (click) of searchbar item i'm changing model value

.html
<ion-searchbar [(ngModel)]="searchQuery" (input)="searchLocation($event)" placeholder="Enter Your Location" > </ion-searchbar>
<ion-list *ngIf="incompleteSearch">
  <ion-item *ngFor="#item of searchedPlaceslist" (click)="selectLocation(item)">
    {{ item.description }}
  </ion-item>
</ion-list>

.ts

        searchQuery = '';
	selectLocation(item) {
		this.searchQuery = item.description; <<<<<<<getting error over here
	}
	searchLocation(event) {
		if(event.value.length > 3) {
		  this.placesData.search(event.value).then(placeslist => {
			  this.searchedPlaceslist = placeslist.predictions;
		  });
		}
	}

But it is working in prodMode : true according to this https://github.com/angular/angular/issues/6005

Don't know what i am doing wrong

**Comment by jgw96** [comment] 2016-05-02 16:03
Hmmm i cant seem to reproduce this issue with any of my apps. If anyone finds a pattern to reproducing this issue i would love to know it!

**Comment by jtushar53** [comment] 2016-05-03 06:29
Hii,

here is the codepen  http://codepen.io/jtushar53/pen/pyQxyP ,

 in actual wheni'm trying to set value of searchBox

**Comment by jgw96** [comment] 2016-05-03 15:25
Hey @jtushar53 ! When you set the value of the searchbox dynamically like this it is expected that you would get this error. It is a feature of the angular 2 dev mode to throw this error when a change happens outside of change detection but it looks like its a little buggy in Angular 2 at the moment. You can read more about this here: https://github.com/angular/angular/issues/6005. Looks like the current workaround is to put your call inside a `zone.run()` (which you can see a good example of on that issue) to force change detection. Hope this helps you!

**Comment by michaelotte** [comment] 2016-05-03 22:03
prodMode just suppresses the error as angular is double checking for undetected changes only in devMode. It seems that when you dynamically assign a value to `this.searchQuery`, ion-searchbar immediately does something with the value that makes angular2 detect a second change.

Assigning a value to this.searchQuery is not the problem, it's the "thing" that ion-searchbar does afterwards. You can reproduce the error anywhere (on button click or setTimeout) except in the constructor, initializing searchQuery there seems to work.

My problem is that in the constructor routeParams (like url?q=searchterm) are not yet available so I have to do that later. Unfortunately `ngZone.runOutsideAngular` or `ngZone.run` didn't help.

**Comment by Ionitron** [comment] 2016-06-01 23:36
Greetings @ErkoKnoll!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment] 2016-06-01 23:36
Greetings @ErkoKnoll!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by brandyscarney** [comment] 2016-06-14 16:13
I made a few changes and the only way I've found to consistently reproduce this is to change the value in the `ngAfterViewInit`:

```
@Component({
  templateUrl: 'main.html'
})
class MyApp {
  customPlaceholder: number = 2;

  ngAfterViewInit() {
    this.customPlaceholder = 33;
  }
}
```

There are a few ways to fix this with Angular's change detection. We can wrap it in a `setTimeout` as a workaround:

```
ngAfterViewInit() {
  setTimeout(() => {
    this.customPlaceholder = 33;
  });
}
```

or we can manually trigger change detection:

```
import {Component, ChangeDetectorRef} from '@angular/core';

@Component({
  templateUrl: 'main.html'
})
class MyApp {
  customPlaceholder: number = 2;

  constructor(private changeDetectorRef: ChangeDetectorRef) {

  }

  ngAfterViewInit() {
    this.customPlaceholder = 33;
    this.changeDetectorRef.detectChanges();
  }
}
```

See issue https://github.com/angular/angular/issues/6005 for more information. I released a nightly version with some changes to the Searchbar, it can be installed in your project with the following command:

```
npm install --save ionic-angular@2.0.0-beta.8-201606131945
```

It shouldn't throw any errors when you change the value on a button click. Please let me know if there are any issues. Thanks!

**Closed by brandyscarney** 2016-06-14 16:13 UTC
Labels: v2

**Comment by michaelotte** [comment] 2016-06-15 10:13
Thanks, will check
