### ISSUE TITLE
Tabs - Error tabsHighlight: true -v2

### ISSUE THREAD

**Issue by EliuFlorez** [driftyco/ionic#8659] opened 2016-10-12 19:56 UTC
By establishing tabsHighlight: true settings tabs launches this error console:

tabs.js:172 Uncaught TypeError: Cannot read property 'select' of undefined

any idea or solution or maybe it's a bug. regards

**Comment by okonon** [comment] 2016-10-12 20:17
this should be fixed in RC1 
you could try the nightly build
https://github.com/driftyco/ionic/issues/8294

**Comment by jgw96** [comment] 2016-10-12 21:26
Hello all! Thanks for opening an issue with us! I am going to close this issue as a duplicate of #8294 .

**Closed by jgw96** 2016-10-12 21:26 UTC
