### ISSUE TITLE
Ionic 1.3 error related to Ionic View LifeCycle

### ISSUE THREAD

**Issue by jdnichollsc** [driftyco/ionic#6334] opened 2016-04-27 03:57 UTC
#### Short description of the problem:
beforeLeave, leave and afterLeave don't work with Ionic 1.3, using in this case abstact state and nested views

#### What behavior are you expecting?
Call these events in the respective order

Regards, Nicholls

**Comment by danbucholtz** [comment] 2016-04-27 04:22
Hi @jdnichollsc,

Can you provide a code pen showing your issue?

Thanks,
Dan

**Comment by jdnichollsc** [comment] 2016-04-27 05:16
Yes Sir @danbucholtz, see please: http://codepen.io/jdnichollsc/pen/VaGgVm?editors=1010

Thanks in advance, Nicholls

**Comment by dually8** [comment] 2016-04-29 15:26
Part of the problem is that you're using version 1.0.0 in the codepen `http://code.ionicframework.com/1.0.0/`.  If I change it to 1.3.0, the events fire beforeEnter > enter > afterEnter.  The leave events don't fire in the example.

**Comment by danbucholtz** [comment] 2016-04-29 16:42
@dually8, @jdnichollsc,

Yep.  I noticed that as well.  I am updating some code related to life cycle events as we speak.  Next week we should hopefully have a fix out in 1.3.1.

**Comment by jdnichollsc** [comment] 2016-04-30 06:04
@dually8 if you change the navigation from Gallery to Home doesn't work... with 1.0.0 or 1.3.0

**Comment by danbucholtz** [comment] 2016-05-04 21:23
This will be fixed in the nightly build tonight.

http://code.ionicframework.com/#nightly

Please test and let me know if this resolves your issue.  We added a ton of automated testing and fixed a ton of issues around life cycle events in the past few days.

Thanks,
Dan

**Closed by danbucholtz** 2016-05-04 21:23 UTC
Labels: v1

**Comment by lucasbeef** [comment] 2016-05-17 12:52
The events don't fire for me since 1.3.1
I had to revert back to 1.3.0 for it to work.

Anybody else experienced it ?

**Comment by jdnichollsc** [comment] 2016-05-18 00:51
Now works for me, thanks Sir @danbucholtz! :dancers:
Link updated: http://codepen.io/jdnichollsc/full/VaGgVm/

**Comment by lucasbeef** [comment] 2016-05-18 12:58
@danbucholtz Well, it's a mystery for me, I have basically the same code as in the codepen jdnichollsc provided. It works on 1.3.0 but not on 1.3.1. 

I have no exception, nothing in the console either. The events simply don't trigger.
I'd like to give you more intel, but I don't know where to look

**Comment by jdnichollsc** [comment] 2016-05-18 15:33
What is your codepen link? To review your code :)

**Comment by lucasbeef** [comment] 2016-05-24 10:05
Ok, I got it working !
I found out that the events wouldn't trigger because my template wasn't encapsulated in an <ion-view>. It used to work that way.

Sorry about that :confused:
And thank you ! It's really cool that you keep on improving and supporting V1 !

**Comment by jdnichollsc** [comment] 2016-05-24 13:39
Yes, thanks Ionic team for support Ionic 1.x! :dancers:
