### ISSUE TITLE
Bug with LoadingController when called inside ionViewDidEnter()

### ISSUE THREAD

**Issue by TiagoSilvaPereira** [driftyco/ionic#7876] opened 2016-08-25 19:32 UTC
Hi,

I have a issue with this function:

```
presentLoader() {
    this.loader = this.loadingCtrl.create({
      content: "Please wait...",
      duration: 3000
    });
    this.loader.present();
  }
```

When I call this function inside the ionViewDidEnter, i need envolve it in a setTimeout() to work properly (if I call only the preserntLoader, the function fails, and it does not show errors in the console):

```
ionViewDidEnter() {
    setTimeout( ()=> {
      this.presentLoader();
    }, 500);
  }
```

Thanks

**Comment by chrisbenseler** [comment] 2016-08-25 19:34
Same for me.

**Comment by jgw96** [comment] 2016-08-25 19:46
Hello! Thanks for opening an issue with us! Since this is a duplicate of https://github.com/driftyco/ionic/issues/7605 I am going to close this issue for now. Thanks for using Ionic!

**Closed by jgw96** 2016-08-25 19:46 UTC
