### ISSUE TITLE
bug: Open a form in modal and the keyboard pops up

### ISSUE THREAD

**Issue by pattyok** [driftyco/ionic#3569] opened 2015-04-20 16:40 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>I have a form in a modal. When I open the form sometimes (1 in 10 times) the keyboard pops up and it will only close if you then put your focus in a text field and then move out. 

If you just close the modal the keyboard stays open and does not shut until you change states.

Note: normal behavior (if the keyboard is activated by focusing on a text box) is that when the modal closes the keyboard also closes - it does not work this way when the keyboard is popped open on opening the modal.</span>

<span is-issue-template></span>

**Comment by tlancina** [comment] 2015-04-20 20:32
Are you using the latest Ionic (either rc3 or rc4)?

if you could post a codepen reproducing the issue I'll take a look, thanks!

**Comment by pattyok** [comment] 2015-04-20 21:58
Here is a codepen. http://codepen.io/pattyok/pen/ZGzPxx
I am on rc1. I only see it on the client, on ios.  Several others have reported this in the forums. It does not repro consistently, but I get it often enough to be troublesome.

**Comment by tlancina** [comment] 2015-04-21 01:28
Does it still happen with the latest Ionic? We refactored a lot of keyboard code, a fair amount of it dealing with modals.

**Comment by pattyok** [comment] 2015-04-21 16:58
We are on RC1...

**Comment by tlancina** [comment] 2015-04-21 17:24
Not sure what you'd like to happen, if it's fixed in the latest Ionic then there's no bug?

**Comment by tlancina** [comment] 2015-04-21 18:00
Ok I see it if I spam click the modal button :) Looks similar to why we added https://github.com/driftyco/ionic/commit/a416c66d8aede50fcf91cc569681a6d163e37cbc because the same thing was happening when closing the modal over the top of an input.  This looks like it's the reverse, you click on the button to open the modal and the ghost click (or whatever is causing it, still not sure) hits the input after the modal is opened.

Also I noticed you had an ion-view and ion-content wrapping your modal (maybe left there from editing the tabs project?), but it was doing some funky stuff so I removed them: http://codepen.io/tlancina/pen/xGxGoY.

**Closed** 2015-04-21 18:20 UTC

**Comment by tlancina** [comment] 2015-04-21 18:23
Should be fixed, thanks for the report! Let us know if you're still having issues.

**Comment by pattyok** [comment] 2015-04-22 16:34
I updated to rc4 and am still seeing the issue...

**Comment by tlancina** [comment] 2015-04-22 16:41
You'll need to use nightly, not rc4.
