### ISSUE TITLE
Maybe there is an infinite loop?

### ISSUE THREAD

**Issue by MrWoo** [driftyco/ionic#10010] opened 2017-01-13 02:55 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**  2.0.0-rc.5

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The code below maybe cause an infinite loop if ```trns``` has parent.

**Expected behavior:**

**Steps to reproduce:**

**Related code:**
nav-controller-base.ts   212-220
```
      while (trns) {
        if (trns.enteringView && (trns.enteringView._state !== ViewState.LOADED)) {
          // destroy the entering views and all of their hopes and dreams
          this._destroyView(trns.enteringView);
        }
        if (!trns.parent) {
          break;
        }
      }
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by mhartington** [comment] 2017-01-13 15:21
How could I test this out? Could you provide a demo or this?

**Comment by jsayol** [comment] 2017-01-13 18:42
Hey @mhartington I was looking over the code and that reject function is never called with a second argument (the `Transition`) so at the moment there is no way to reproduce this at all, since it can't happen.

That said, @MrWoo is right. The way the function is written, if at any moment it gets called with a `Transition` as its second argument and that transition has a parent, the app will get stuck on an infinite loop.

I see 2 ways to fix this:
1. Remove `trns` and all its associated code altogether, since it's not being used.
2. Change the loop so that it traverses the transition tree upwards, which is probably what was intended:
```ts
while (trns) {
  if (trns.enteringView && (trns.enteringView._state !== ViewState.LOADED)) {
    // destroy the entering views and all of their hopes and dreams
    this._destroyView(trns.enteringView);
  }
  trns = trns.parent;
}
```

**Comment by jgw96** [comment] 2017-05-02 15:13
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-05-02 15:13 UTC
Labels: needs info, needs reply, v2
