### ISSUE TITLE
bug: Ionic keyboard Go goes backward and open modal

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic#5650] opened 2016-02-29 15:53 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Having a modal in a form i open the modal, then return a value to the form, and tap on text input, keyboard pops out and when tap on `Go` key it opens the modal again when it should jump to next input or send the form, this **23 sec** video illustrates better the issue:
[Error Ionic 2 IOS keyboard 'Go' after modal](https://youtu.be/-kwymLo1yMc)

**Update 1:** Just tapping on any text input will open the modal, even if not already opened, just using a text input in the same form as the modal and tapping the `Go` key triggers the opening of the modal.
</span>

<span is-issue-template></span>

**Comment by jgw96** [comment] 2016-03-11 21:30
Thanks for submitting this issue! Would you mind running `ionic info` and pasting the output here? Also, if you have a codepen or code sample that we could use to repro this issue that would be great!

**Comment by Luchillo** [comment] 2016-03-11 21:55
Ionic info output:

```bash
ionic info

Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
ios-deploy version: 1.8.5 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v5.6.0
Xcode version: Xcode 7.2.1 Build version 7C1002
```
As for the plunkr it's imposible, this happens when you hit the back button on device, what won't do in plunkr as the back button (hardware one) doesn't exists.

**Comment by brandyscarney** [comment] 2016-04-02 17:18
@Luchillo If this is still an issue can you please provide some code that can be used to reproduce this. I understand it only happens on a device, but I'm having a hard time understanding what exactly is happening with the video. Could you please explain the exact steps for me? Sorry and thanks! :smile:

**Comment by Luchillo** [comment] 2016-04-03 04:23
What happens there is that when i hit the Go key ('Ir' in spanish) in the form it opens for some reason the modal even if i don't even open it (found out testing later), it shouldn't happen when i am in an input lower to the modal, usually the go key jumps to the next input or if in last sends the form?

**Comment by jgw96** [comment] 2016-05-05 17:12
Hello! Is this still an issue with the latest version of ionic? Thanks!

**Comment by Luchillo** [comment] 2016-05-05 19:14
I think it is however i can't check since i work around with a listener on the back button event.

**Comment by Luchillo** [comment] 2016-05-05 19:16
It is, idk how to overcome this one, i just tell people that they are not supposed to jump from field to field with the `Go` key.

**Comment by Luchillo** [comment] 2016-05-05 19:18
Sorry, just tested in Android and it doesn't happen, let me get back to you when i have tested IOS.

**Comment by jgw96** [comment] 2016-05-10 14:05
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-05-10 14:05 UTC
Labels: keyboard, modals, needs reply, v2
