### ISSUE TITLE
[RC5 and earlier] Slides component gets crazy with loaded data from server

### ISSUE THREAD

**Issue by yannbf** [driftyco/ionic#10064] opened 2017-01-17 03:29 UTC
**Ionic version:**  
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...** 
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

So I've noticed that the slider component gets completely crazy and doesn't conform to any of its configurations when it loads data from a server(or really any data that is not set instantly).
The exact same code running without a simple timeout works OK, but inside a timeout(hence mimicking a server) it gets all weird.

The slider should: Loop through the slides from either swipe direction.
The slider does: Loop only from the left to right, although it blinks from the last to first slide.

I've put a gif that shows the behavior and also a plunkr:
![slides](https://cloud.githubusercontent.com/assets/1671563/22005270/8b2a9776-dc40-11e6-8551-19055639c189.gif)

**Note: The plunkr uses RC1 so I adapted the [options] part, but it behaves the same in RC5.**
Plunkr:
https://plnkr.co/edit/79rFAbwcwTdIWidEQraD?p=preview 

**Other information:**
It's important to note that it was having this behavior prior to RC5.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.9.1
Xcode version: Not installed
```

**Comment by yannbf** [comment] 2017-02-01 01:07
So.. nobody experiencing the same issue?

**Comment by yannbf** [comment] 2017-02-01 03:14
Well, I got it working by adding `*ngIf="slides.length > 1"` to the parent component as @criswheatonshoutz suggested in another thread. Seems hackish though.

**Comment by jgw96** [comment] 2017-04-07 16:42
Hello, thanks for opening an issue with us. We are going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/6703.

**Closed by jgw96** 2017-04-07 16:42 UTC
Labels: slides, v2
