### ISSUE TITLE
config.mode = ios not working when building for browser

### ISSUE THREAD

**Issue by marcelgoya** [driftyco/ionic#11380] opened 2017-04-26 17:44 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The config.mode var is not working when I'm compiling the app for platform browser. I'm using the iOS style in my web app but it's using md by default. Setting the variable works when I'm running the app with ionic serve.

**Expected behavior:**
config.mode = 'ios' should set the default style accordingly

**Steps to reproduce:**
Set config.mode = 'ios' in your app config and compile for platform browser.

**Comment by jgw96** [comment] 2017-04-26 17:49
Hello, thanks for using Ionic! Could you please post how you're setting the mode config?

**Comment by jgw96** [comment] 2017-04-26 18:49
Hello! So if I'm thinking correctly here since your using the Cordova browser platform `isCordova` is `true` when you're running your app in the browser. Could you console.log that variable out and see if that's correct?

**Comment by marcelgoya** [comment] 2017-04-26 18:53
Hi @jgw96 , that is correct. I also tried setting the config.mode outside the if, so that the mode is always set to ios, but the effect is the same.

**Comment by jgw96** [comment] 2017-05-01 21:08
Hello @marcelgoya , unfortunately, i cannot reproduce your issue. Can you try just putting `mode: ios` in your actual config object and see if that works for you?

**Comment by jgw96** [comment] 2017-05-05 14:32
Hello! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-05-05 14:32 UTC
Labels: needs info, v2
