### ISSUE TITLE
bug: Android custom icon and splash images

### ISSUE THREAD

**Issue by doronnac** [driftyco/ionic#9387] opened 2016-11-28 12:30 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>6.0</span>  <span ionic-webview>webview</span>

<span ionic-description>Starting a project from scratch (ionic start), then adding custom icon and splash to the respective resources/android folder and subfolders, doesn't make any difference when building for android. icon and splash still remain the same default by Cordova.
I did not experience this behaviour until lately.</span>

<span is-issue-template></span>

**Comment by royipressburger** [comment] 2016-11-28 12:39
Did you run `ionic resources` inside the project folder?

**Comment by shairyar** [comment] 2016-11-28 13:57
I just created the splash images and icons using command `ionic resources` and all seems to work fine.

**Comment by doronnac** [comment] 2016-11-28 14:30
@shairyar Your url is broken

I have ran ionic resources and verified that both the icon and splash screens exist in their respective locations inside resources/android, and properly referenced in config.xml

**Comment by shairyar** [comment] 2016-11-28 14:56
@doronnac check the link now, i never had to make any reference in config.xml just ran the command by following the instruction in the link i shared and all went fine

**Comment by legendar** [comment] 2016-11-29 08:06
the same problem.
I have doing following:
```
ionic start myApp tabs
# also trying --v2 flag without success
cd myApp
ionic platform add android
# replace icon.png and splash.png here
ionic resources
ionic build android
```
then run generated APK on real device with Android 6.0.1
the default cordova icon/splash are present
I can confirm that `ionic resources` works fine but something went wrong when building APK


also trying following:
```
ionic start --v2 myApp3 tabs
ionic platform add android
ionic build android
```
the icons still default cordova, even not ionic.

**Comment by legendar** [comment] 2016-11-29 08:18
build log

```
myApp3 % ionic build android                                                                                                

> ionic-hello-world@ ionic:build /www/test/ionic2/myApp3
> ionic-app-scripts build

[10:14:09]  ionic-app-scripts 0.0.45 
[10:14:09]  build prod started ... 
[10:14:09]  clean started ... 
[10:14:09]  clean finished in 8 ms 
[10:14:09]  copy started ... 
[10:14:09]  ngc started ... 
[10:14:09]  copy finished in 90 ms 
[10:14:27]  ngc finished in 18.62 s 
[10:14:27]  webpack started ... 
[10:14:36]  webpack finished in 8.92 s 
[10:14:36]  uglifyjs started ... 
[10:14:36]  sass started ... 
[10:14:38]  sass finished in 1.79 s 
[10:14:38]  cleancss started ... 
[10:14:40]  cleancss finished in 1.48 s 
[10:14:55]  uglifyjs finished in 19.03 s 
[10:14:55]  build prod finished in 46.62 s 
ANDROID_HOME=/opt/android-sdk

JAVA_HOME=/usr/lib/jvm/java-8-openjdk

Subproject Path: CordovaLib

Incremental java compilation is an incubating feature.


:preBuild
 
UP-TO-DATE


:preDebugBuild
 
UP-TO-DATE


:checkDebugManifest


:CordovaLib:preBuild 
UP-TO-DATE


:CordovaLib:preDebugBuild
 UP-TO-DATE


:CordovaLib:checkDebugManifest


:CordovaLib:prepareDebugDependencies


:CordovaLib:compileDebugAidl
 
UP-TO-DATE


:CordovaLib:compileDebugNdk
 UP-TO-DATE
:CordovaLib:compileLint UP-TO-DATE
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugShaders UP-TO-DATE
:CordovaLib:compileDebugShaders 
UP-TO-DATE


:CordovaLib:generateDebugAssets 
UP-TO-DATE
:CordovaLib:mergeDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles UP-TO-DATE
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:compileDebugRenderscript UP-TO-DATE
:CordovaLib:generateDebugResValues UP-TO-DATE

:CordovaLib:generateDebugResources
 
UP-TO-DATE

:CordovaLib:packageDebugResources UP-TO-DATE
:CordovaLib:processDebugManifest UP-TO-DATE
:CordovaLib:generateDebugBuildConfig UP-TO-DATE

:CordovaLib:processDebugResources
 UP-TO-DATE
:CordovaLib:generateDebugSources
 
UP-TO-DATE


:CordovaLib:incrementalDebugJavaCompilationSafeguard
 
UP-TO-DATE

:CordovaLib:compileDebugJavaWithJavac
 UP-TO-DATE

:CordovaLib:processDebugJavaRes UP-TO-DATE

:CordovaLib:transformResourcesWithMergeJavaResForDebug UP-TO-DATE

:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug
 UP-TO-DATE
:CordovaLib:mergeDebugJniLibFolders UP-TO-DATE


:CordovaLib:transformNative_libsWithMergeJniLibsForDebug
 UP-TO-DATE
:CordovaLib:transformNative_libsWithSyncJniLibsForDebug
 
UP-TO-DATE


:CordovaLib:bundleDebug
 UP-TO-DATE
:prepareAndroidCordovaLibUnspecifiedDebugLibrary UP-TO-DATE
:prepareDebugDependencies


:compileDebugAidl
 UP-TO-DATE

:compileDebugRenderscript UP-TO-DATE


:generateDebugBuildConfig
 UP-TO-DATE
:generateDebugResValues 
UP-TO-DATE
:generateDebugResources UP-TO-DATE

:mergeDebugResources UP-TO-DATE
:processDebugManifest UP-TO-DATE
:processDebugResources UP-TO-DATE
:generateDebugSources UP-TO-DATE
:incrementalDebugJavaCompilationSafeguard
 UP-TO-DATE

:compileDebugJavaWithJavac
 
UP-TO-DATE

:compileDebugNdk UP-TO-DATE
:compileDebugSources UP-TO-DATE
:mergeDebugShaders UP-TO-DATE
:compileDebugShaders UP-TO-DATE
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets
 UP-TO-DATE

:transformClassesWithDexForDebug
 UP-TO-DATE
:mergeDebugJniLibFolders UP-TO-DATE
:transformNative_libsWithMergeJniLibsForDebug UP-TO-DATE
:processDebugJavaRes
 UP-TO-DATE
:transformResourcesWithMergeJavaResForDebug
 
UP-TO-DATE
:validateSigningDebug
:packageDebug
 
UP-TO-DATE
:assembleDebug UP-TO-DATE
:cdvBuildDebug UP-TO-DATE

BUILD SUCCESSFUL


Total time: 1.204 secs

Built the following apk(s): 
	/www/test/ionic2/myApp3/platforms/android/build/outputs/apk/android-debug.apk

```

**Comment by legendar** [comment] 2016-11-29 08:59
seems duplicate of: https://github.com/driftyco/ionic-cli/issues/1608
workaround is:
```
npm install -g cordova@6.3.1
ionic platform remove android
ionic platform add android
```

**Comment by doronnac** [comment] 2016-11-29 12:52
Cool. thanks!

Also my project was on android version 6.0.0, had to change it to 6.1.0 for some reason.
Easiest way - in config.xml:
<engine name="android" spec="~6.1.0"/>

**Comment by ZiFFeL1992** [comment] 2017-02-23 11:52
Can you close this? :)

**Comment by jgw96** [comment] 2017-03-27 07:36
Hello all, as it seems this issue has been fixed I am going to close this issue for now. Thanks for using Ionic!

**Closed by jgw96** 2017-03-27 07:36 UTC
Labels: v2
