### ISSUE TITLE
bug: Sourcemaps not working on "ionic run android"

### ISSUE THREAD

**Issue by pom421** [driftyco/ionic#7540] opened 2016-08-04 08:49 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>6.0</span>  <span ionic-webview>webview</span>

<span ionic-description>When i try to remote debug with chrome developer tools (chrome://inspect), i don't see the original file because the sourcemaps are not resolved. 

I just try with the tutorial : 
ionic start MyIonic2Project tutorial --v2
ionic run android

Then on chrome, chrome:inspect. On the Sources tab, my .ts files are not there... 
This a very important issue for me to consider using Ionic2 with Typescript. 

My environement :
- OS X 10.11
- ionic v2.0.0-beta.35
- cordova 6.3.0</span>

<span is-issue-template></span>

**Comment by jtushar53** [comment] 2016-08-04 09:52
Hi @pom421 
i think you should've have posted here https://github.com/driftyco/ionic-gulp-tasks 
check out this link  https://github.com/driftyco/ionic-gulp-tasks/issues/22, there is already a similar issue
may be you should use livereload on device

**Comment by pom421** [comment] 2016-08-04 12:57
Thanks @jtushar53 to redirect me to this issue.

ionic run android --livereload allows to remote debug the device.

**Comment by jgw96** [comment] 2016-08-04 20:16
Hello all! Thanks for opening an issue with us. I am going to be closing this issue as a duplicate of https://github.com/driftyco/ionic-gulp-tasks/issues/22. Thanks for using Ionic!

**Closed by jgw96** 2016-08-04 20:16 UTC
Labels: platform:android, v2

**Comment by rob3c** [comment] 2016-09-28 23:47
For those running into this with the new ionic-app-scripts build process in rc0, I just opened a similar issue there: https://github.com/driftyco/ionic-app-scripts/issues/32
