### ISSUE TITLE
ionic2 ion-tab click not working

### ISSUE THREAD

**Issue by elineopsommer** [driftyco/ionic#6511] opened 2016-05-12 09:52 UTC
#### Short description of the problem:

I have an project with tabs, but the (click)-event doesn't work and if I leave the attribute [root] away (not required because I want to show an action sheet), then the app crashes.

#### What behavior are you expecting?
Click on the tab and see the action sheet appear

```
<ion-tabs>
  <ion-tab tabTitle="Tab 1" tabIcon="pulse" (click)="presentActionSheet()"></ion-tab>
</ion-tabs>

presentActionSheet() {
        let actionSheet = ActionSheet.create({
            title: 'Modify your album', buttons: [{
                text: 'Destructive', role: 'destructive', handler: () => {
                    console.log('Destructive clicked');
                }
            }, {
                text: 'Archive', handler: () => {
                    console.log('Archive clicked');
                }
            }, {
                text: 'Cancel', role: 'cancel', handler: () => {
                    console.log('Cancel clicked');
                }
            }]
        });
        this.navController.present(actionSheet);
    }
```
 
**Which Ionic Version?** 2.x

#### Plunker that shows an example of your issue

http://plnkr.co/edit/arVf9wLxOCVUZNTyt8l3?p=preview

**Run `ionic info` from terminal/cmd prompt:** 

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v5.3.0
Xcode version: Xcode 7.2 Build version 7C68

**Comment by FourLeafClover** [comment] 2016-08-07 11:41
have this fixed? I also have the same problem.help!!!!

**Comment by jgw96** [comment] 2016-08-22 16:44
Hello! Thanks for opening an issue with us! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/7769 as it should be fixed in that issue. Thanks for using Ionic!

**Closed by jgw96** 2016-08-22 16:44 UTC
Labels: v2
