### ISSUE TITLE
RC-0: navigation failed to blank page

### ISSUE THREAD

**Issue by ecureuill** [driftyco/ionic#8373] opened 2016-09-30 23:14 UTC
#### Short description of the problem:

`navCtrl.push(...)` after a login attempt works only with Chrome developer tools (android device).
Otherwise, it goes to the redirect page, and quickly shows a blank page instead. 

It's the same behavior with `setRoot`

**UPDATE**
In a more simple scenery, with no redirect before login, still leads to blank page.
https://github.com/ecureuill/Ionic2RC-Auth0.git3

So  I guess it is not a bug specific to method `push()` or `setRoot`.
Could be a problem between ionic navigation and angular navigation?
**UPDATE**

#### What behavior are you expecting?

**Steps to reproduce:**
1. ionic serve
2. open Chrome developers tool (android device)
3. navigate (works)

1. ionic serve 
2. navigate (don't work)

```
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';

import { AuthService } from '../../providers/auth0'

import { HomePage } from '../home/home';


@Component({
	selector: 'page-login',
	templateUrl: 'login.html'
})
export class LoginPage {

	constructor(public navCtrl: NavController, private auth: AuthService) {
		this.redirectTo();
	}

	public get autenticado(): boolean {
		return this.auth.authenticated();
	}

	login() {
		this.auth.lock.show();
	}

	redirectTo() {
		if (this.auth.authenticated()) {
			this.navCtrl.push(HomePage);
		} else {
			this.auth.lock.on('authenticated', authResult => {
				this.navCtrl.push(HomePage);
			});
		}
	}
}
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 https://forum.ionicframework.com/t/page-coming-as-blank-after-login-in-ionic-2-rc0/65077

**Which Ionic Version?** 1.x or 2.x
2.0RC-0

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Distributor ID:	Debian Description:	Debian GNU/Linux 8.6 (jessie) 
Node Version: v4.5.0

**Comment by manucorporat** [comment] 2016-09-30 23:59
Try calling redirectTo() after the LoginPage has entered, with `ionViewDidEnter`.

**Comment by ecureuill** [comment] 2016-10-01 00:15
Same behaviour.
Bellow, more code details


**app.module.ts**
```
import { NgModule } from '@angular/core';
import { Storage } from '@ionic/storage';
import { IonicApp, IonicModule } from 'ionic-angular';
import { MyApp } from './app.component';

/* --------------- PAGES ------------------ */
import { HomePage } from '../pages/home/home';
import { LoginPage } from '../pages/login/login';
/* --------------- PROVIDERS ------------------ */
import { AuthService } from '../providers/auth0';
///JWT Config
import { AuthHttp, AuthConfig} from 'angular2-jwt';
import { Http } from '@angular/http';

 export function getAuthHttp(http) {
     return new AuthHttp(new AuthConfig({
       noJwtError: true
     }), http);
 }


@NgModule({
  declarations: [
    MyApp,
    LoginPage,
    HomePage
   ],
  imports: [
    IonicModule.forRoot(MyApp)
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    HomePage,
    LoginPage,
      ],
  providers: [
    Storage,
    AuthHttp,
    AuthService,
    {
      provide: AuthHttp,
      useFactory: getAuthHttp,
      deps:[Http]
    }
  ]
})
export class AppModule { }
```

**login.ts**
```
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
import { AuthService } from '../../providers/auth0'
import { HomePage } from '../home/home';


@Component({
	selector: 'page-login',
	templateUrl: 'login.html'
})
export class LoginPage {

	constructor(public navCtrl: NavController, public auth: AuthService) {
	}

	public get autenticado(): boolean {
		return this.auth.authenticated();
	}

	login() {
		this.auth.lock.show();
	}

	ionViewDidEnter() {
		this.redirectTo();

	}

	redirectTo() {
		if (this.auth.authenticated()) {
			this.navCtrl.setRoot(HomePage);
                        this.navCtrl.push(HomePage)
		} else {
			this.auth.lock.on('authenticated', authResult => {
				this.navCtrl.setRoot(HomePage);
			});
		}
	}
}
```

**login.html**
```
<ion-header>
    <ion-navbar>
        <ion-title>login</ion-title>
    </ion-navbar>
</ion-header>
<ion-content padding *ngIf="auth.authenticated()">
    <button ion-button (click)="redirectTo()" >Home</button>
    {{auth.authenticated()}}
</ion-content>
<ion-content padding *ngIf="!auth.authenticated()">
    <button ion-button (click)="login()">Login</button>
    {{auth.authenticated()}}
</ion-content>

```

**auth0.ts**
```
import {Storage} from '@ionic/storage';
import {AuthHttp, JwtHelper, tokenNotExpired} from 'angular2-jwt';
import {Injectable, NgZone} from '@angular/core';
import {Observable} from 'rxjs/Rx';

// Avoid name not found warnings
declare var Auth0: any;
declare var Auth0Lock: any;
// declare var faker = require('faker');

export class Auth0Vars {
  //application's clientId in Auth0.
    static AUTH0_CLIENT_ID = "...";
    static AUTH0_DOMAIN = "...";
}

@Injectable()
export class AuthService {

  jwtHelper: JwtHelper = new JwtHelper();

  auth0 = new Auth0({ clientID: Auth0Vars.AUTH0_CLIENT_ID, domain: Auth0Vars.AUTH0_DOMAIN });

  lock = new Auth0Lock(Auth0Vars.AUTH0_CLIENT_ID, Auth0Vars.AUTH0_DOMAIN
    , {
    redirect: false, //popup options
    autoclose: true,
    avatar: null,
    closable: false,
    rememberLastLogin: false,
    language: 'pt-br',
    theme: {
      primaryColor: 'green',
      logo: 'assets/img/logo.jpg',
      labeledSubmitButton: true //This option indicates whether or not the submit button
      // should have a label, and defaults to true. When set to false, an icon will be shown instead.
    },
    languageDictionary: {
      title: "Teeth"
    },
    }
  );

  local: Storage;
  refreshSubscription: any;
  user: Object;
  zoneImpl: NgZone;

  constructor(private authHttp: AuthHttp, zone: NgZone, local : Storage) {
    this.zoneImpl = zone;
    this.local = local;

    this.lock.show();

    // Check if there is a profile saved in local storage
    this.local.get('profile').then(profile => {
      this.user = JSON.parse(profile);
    }).catch(error => {
      console.log(error);
    });


    this.lock.on('authenticated', authResult => {
      this.local.set('id_token', authResult.idToken);

      // Fetch profile information
      this.lock.getProfile(authResult.idToken, (error, profile) => {
        if (error) {
          // TODO: tratar erro 
          console.error("erro ao retornar perfil", error);
          return;
        }

        profile.user_metadata = profile.user_metadata || {};
        this.local.set('profile', JSON.stringify(profile));
        this.user = profile;
      });

      this.lock.hide();

      this.local.set('refresh_token', authResult.refreshToken);
      this.zoneImpl.run(() => this.user = authResult.profile);
      // Schedule a token refresh
      this.scheduleRefresh();

    });

  }

  public authenticated() {
    // Check if there's an unexpired JWT
    return tokenNotExpired();
  }

  public login() {
    // Show the Auth0 Lock widget
    this.lock.show();
  }

  public logout() {
    this.local.remove('profile');
    this.local.remove('id_token');
    this.local.remove('refresh_token');
    this.zoneImpl.run(() => this.user = null);
    // Unschedule the token refresh
    this.unscheduleRefresh();
  }

  public scheduleRefresh() {
    // If the user is authenticated, use the token stream
    // provided by angular2-jwt and flatMap the token
    let source = this.authHttp.tokenStream.flatMap(
      token => {
        // The delay to generate in this case is the difference
        // between the expiry time and the issued at time
        let jwtIat = this.jwtHelper.decodeToken(token).iat;
        let jwtExp = this.jwtHelper.decodeToken(token).exp;
        let iat = new Date(0);
        let exp = new Date(0);

        let delay = (exp.setUTCSeconds(jwtExp) - iat.setUTCSeconds(jwtIat));

        return Observable.interval(delay);
      });

    this.refreshSubscription = source.subscribe(() => {
      this.getNewJwt();
    });
  }

  public startupTokenRefresh() {
    // If the user is authenticated, use the token stream
    // provided by angular2-jwt and flatMap the token
    if (this.authenticated()) {
      let source = this.authHttp.tokenStream.flatMap(
        token => {
          // Get the expiry time to generate
          // a delay in milliseconds
          let now: number = new Date().valueOf();
          let jwtExp: number = this.jwtHelper.decodeToken(token).exp;
          let exp: Date = new Date(0);
          exp.setUTCSeconds(jwtExp);
          let delay: number = exp.valueOf() - now;

          // Use the delay in a timer to
          // run the refresh at the proper time
          return Observable.timer(delay);
        });

      // Once the delay time from above is
      // reached, get a new JWT and schedule
      // additional refreshes
      source.subscribe(() => {
        this.getNewJwt();
        this.scheduleRefresh();
      });
    }
  }

  public unscheduleRefresh() {
    // Unsubscribe fromt the refresh
    if (this.refreshSubscription) {
      this.refreshSubscription.unsubscribe();
    }
  }

  public getNewJwt() {
    // Get a new JWT from Auth0 using the refresh token saved
    // in local storage
    this.local.get('refresh_token').then(token => {
      this.auth0.refreshToken(token, (err, delegationRequest) => {
        if (err) {
          alert(err);
        }
        this.local.set('id_token', delegationRequest.id_token);
      });
    }).catch(error => {
      console.log(error);
    });

  }
}

```

**Comment by fishgrind** [comment] 2016-10-01 01:22
having the same issue!

**Comment by fishgrind** [comment] 2016-10-02 03:26
another update:

if chrome dev tools device is set to an IOS device there is no problem. If it is set to an Android device the problem is also there in dev tools

**Comment by leommoore** [comment] 2016-10-02 20:50
I have the same problem. After a successful login I set the rootPage using:

```
this.navCtrl.setRoot(HomePage);
```

and this was giving me a white page of doom but was able to fix the issue by replacing:

```
<ion-nav id="nav" #content [root]="rootPage"></ion-nav>
```

with

```
<ion-nav id="nav" #content></ion-nav>
```
 on my home page.

**Comment by fishgrind** [comment] 2016-10-02 20:58
@leommoore i tried your solution,

unfortunately it doesnt work for me. Ik does however now show the navbar but thats it..

**Comment by ecureuill** [comment] 2016-10-03 20:26
Please, have a look in this 
https://github.com/ecureuill/Ionic2RC-Auth0.git3

After login, with no redirect, still lead to blank page.
So, problem is not specific to `.push`

**Comment by ecureuill** [comment] 2016-10-03 20:37
To try to figure out whats is the problem, Auth0 team [ask me about the navigation](https://auth0.com/forum/t/ionic2-rc0-blank-page-after-login/3871/4). Can someone help to answer this?

**Comment by jgw96** [comment] 2016-10-04 15:21
Hello all! Since this seems to be an Auth0 related issue and not a framework issue I am going to close this issue for now. Thanks!

**Comment by fishgrind** [comment] 2016-10-04 15:55
@jgw96 not really, my login page just posts to my own json api without using Auth0, I don't use any plugin for this, my login process sends and receives everything through http post and get.

after a succesfull login i go to the login page using: `this.navCtrl.setRoot(ProfilePage);`

This worked in beta11 and 10.

Also other pages where i set the root the same way work fine, those are all fired by a click though, that is the only difference.

The problem is only on android devices, google chrome, and in the chrome developer tools if you set the device to an android device, ios devices in developer tools work fine.

there is a workaround though. Wrapping the setRoot in a timeout fixes the problem.

`let _self = this
 setTimeout(function(){
        _self.navCtrl.setRoot(ProfilePage);
        console.log('timeout finished')
        }, 3000);`

So this is not an Auth0 problem but a framework related problem.

**Comment by ecureuill** [comment] 2016-10-04 17:26
If it'st necessary a timeout to works, maybe it's related to [8449](https://github.com/driftyco/ionic/issues/8449)

I try call my redirect method in `ngAfterViewInit` instead `ionViewDidEnter` and it's seems to work. Moreover, fix my problem of keep logged after login

@fishgrind  can you try this?

**Comment by candelibas** [comment] 2016-10-04 17:28
I'm kinda having same issue. I'm checking user auth(from firebase) with ngOnInit() and define rootPage on app.component.ts. When I run the app on my device, its just blank page without any console errors. Then if I switch different app and return my app. It works like before.

**Comment by fishgrind** [comment] 2016-10-04 17:33
@ecureuill 

unfortunately that isnt the issue as i am calling setRoot from a function after receiving data from the json api. But thanks for your input!

**Comment by reijosirila** [comment] 2016-10-05 18:56
If I use image on page, it works :)

**Comment by lain-me** [comment] 2016-10-05 19:03
After moving to RC0 I did not have this problem. But after I got info that one page is blank after opening, next I run it in with ionic serve and wow... even at startup it is blank. But I noticed a small flicker when I see login page, and after that nothing there. DOM elements seems to be just fine.

Used remove [root]="rootPage" from above and did work somehow, not sure if it solution or temporal effect. I do not use any side frameworks...

**Comment by reijosirila** [comment] 2016-10-05 19:06
it's really funny. DOM elements/page are there, i can inspect those. But they're not visible. All CSS opacity and everything seems OK, but just elements are not visible...

**Comment by ecureuill** [comment] 2016-10-05 20:39
Yes, I've noticed that.
After redirect to HomePage, it come back to LoginPage, and I guess that it is "blank" because content should be resized.

**Comment by reijosirila** [comment] 2016-10-06 07:23
Havent figured out how to reproduce it but... in my case..
<img width="1186" alt="screenshot 2016-10-06 01 57 59" src="https://cloud.githubusercontent.com/assets/685822/19143809/e50e3884-8bae-11e6-9fc9-08e02667c1b9.png">

**Comment by lain-me** [comment] 2016-10-06 07:54
Link to the same task which has assignee: https://github.com/driftyco/ionic/issues/8510

**Comment by lain-me** [comment] 2016-10-06 11:23
Update: 
I guess the problem is with some transition, because I have this problem only with nav.push, nav.pop but not with nav.setRoot works perfectly pages. Also it is strange that some pages have this issue all the time while others do not have (depends on items on the page?)

As a workaround I have impolemented setRoot pages and overwrittent backbutton actions:

```
      platform.ready().then(() => {
            platform.registerBackButtonAction(() => {
```

with inside code of such type:
```
if (this.nav.canGoBack() || this.nav.getActive() && this.nav.getActive().isOverlay
                ) {
                    Logger.log("Popping back");
                    this.nav.pop();
                }
                else if (this.nav.getActive() && this.nav.getActive().instance && this.nav.getActive().instance.isRootPage
                ) {
```
The instance is the Page class that you have at the moment and you can put there any property you want, so isRootPage is true/false for my home page. Thus you can intercept navigation and place pages from one place whatever you want, based on class properties.

**Comment by royipressburger** [comment] 2016-10-07 08:47
I can also confirm this issue:
Im using `ng2-ui-auth` and not auth0 as authentication service.

Im using ionic `Events` to know when the user is authenticated:

```js
    this.events.subscribe(AUTH_EVENTS.fail, (err) => {
      console.log(`Caught event: ${AUTH_EVENTS.fail}, with: ${err}`);
        this.nav.setRoot(ProviderSelectorPage)
    });
````

This cause a blank screen. setting timeout around the `setRoot` method solve the problem

**Comment by ts1812** [comment] 2016-10-07 12:56
I have the same issue here 
when running on android, on some pages, the page loads as white screen.
before RC everything worked great.
using chrome inspect i found the ion-page has no expected attribute show-page (which sets the 
opacity to 1) ,thus the page has opacity of 0!
this happens on 2 specific pages after nav.push
(those pages are more complex and has more data - though i don't see how its related)
I'm trying some css workaround....

**Comment by jgw96** [comment] 2016-10-07 16:23
Hello all! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/8510. Thanks!

**Closed by jgw96** 2016-10-07 16:23 UTC
Labels: v2

**Comment by lain-me** [comment] 2016-10-07 18:11
@ts1812 good finding. If you find workaround, please, inform here or at #8510

**Comment by ts1812** [comment] 2016-10-08 19:25
Thank you, I see you already fixed this.
Well I'm not that a github/ionic guru so How can I simply update my version ?:) 
thank you
