### ISSUE TITLE
the silides cannot autoplay

### ISSUE THREAD

**Issue by judypol** [driftyco/ionic#5500] opened 2016-02-18 09:25 UTC
I have used the ionic2 slides in my app,but it cannot autoplay,the code is below:
<div style="height: 100px;">
    <ion-slides loop="true" autoplay="true">
      <ion-slide style="background-color: green">
        <h2>Slide 1</h2>
      </ion-slide>

      <ion-slide style="background-color: blue">
        <h2>Slide 2</h2>
      </ion-slide>

      <ion-slide style="background-color: red">
        <h2>Slide 3</h2>
      </ion-slide>
    </ion-slides>
  </div>

**Comment by adamdbradley** [comment] 2016-02-18 14:48
Duplicate of #5504

**Closed by adamdbradley** 2016-02-18 14:48 UTC
Labels: v2
