### ISSUE TITLE
bug: Status bar overlap in iOS

### ISSUE THREAD

**Issue by ThorConzales** [driftyco/ionic#7679] opened 2016-08-12 08:20 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.0 beta 11</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi,

When opening a new page from ActionSheet then the page header is overlapping the iOS status bar, otherwise works fine.

Code that opens the page in action sheet:
`this._navController.push(Page).then(() => this._viewController.dismiss());`</span>

<span is-issue-template></span>

**Comment by jgw96** [comment] 2016-08-12 15:47
Hello! Thanks for opening an issue with us! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/7580 so feel free to follow that issue for the progress on this bug. Thanks for using Ionic!

**Closed by jgw96** 2016-08-12 15:47 UTC
Labels: actionsheet, header, platform:ios, v2
