### ISSUE TITLE
Page navs and overlays with tabs view will overlap with iOS statusbar

### ISSUE THREAD

**Issue by wli** [driftyco/ionic#6368] opened 2016-04-28 23:03 UTC
#### Short description of the problem:
Page navs and overlays with tabs view will overlap with iOS statusbar. This was fixed for other views (in https://github.com/driftyco/ionic/issues/6154), but doesn't work with tabs.

![screen shot 2016-04-28 at 3 58 40 pm](https://cloud.githubusercontent.com/assets/649892/14904019/2486303a-0d5a-11e6-9055-64a620167be0.png)

#### What behavior are you expecting?
It should not overlap.

**Steps to reproduce:**
1. From a tabs page, call `nav.push`

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
Originally addressed in https://github.com/driftyco/ionic/issues/6154 via https://github.com/driftyco/ionic/commit/f45ddf90878dd60a1e997aa3e1ec34e0575bcff2

![screen shot 2016-04-28 at 3 57 32 pm](https://cloud.githubusercontent.com/assets/649892/14904007/10f60c48-0d5a-11e6-8c6a-a4ab6ed66809.png)

As you can see, the new selector `ion-navbar-section.statusbar-padding > .toolbar` does not apply to the page inside the tab, since there is no `ion-navbar-section`.

Cleanest solution seems to be creating a new rule `ion-tab ion-navbar.statusbar-padding.toolbar`, but I will leave it up to the ionic team to decide (maybe @brandyscarney can chime in here)

**Which Ionic Version?** 2.0.0-beta.6

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.1.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.5 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.8.0
Xcode version: Xcode 7.3 Build version 7D175

**Comment by brandyscarney** [comment] 2016-04-29 03:49
Thanks for the issue! I'll look into this soon.

**Comment by brandyscarney** [comment] 2016-04-29 20:02
Hmm I am not able to reproduce this in our e2e test (https://github.com/driftyco/ionic/tree/2.0/ionic/components/app/test/cordova) or in the conference app (https://github.com/driftyco/ionic-conference-app/). Is there anything else going on besides navigating to a new page inside of tabs?

Here's a gif of what I see: http://g.recordit.co/BictqlhckJ.gif

**Comment by abuechler** [comment] 2016-04-29 20:09
@brandyscarney I noticed the same issue. When I run my app in the simulator, I don't see it, but I get it when running it on iPad 2/ iPhone 5 with Ionic View.

**Comment by brandyscarney** [comment] 2016-04-29 20:20
@abuechler Thank you for that info! I was able to reproduce it that way. :smile: I'll have to look into whether this issue is with the framework or the view app itself.

Please let me know if anyone has steps to reproduce it in a simulator or on a device outside of view. Thanks!

**Comment by brandyscarney** [comment] 2016-04-29 20:25
Also, @abuechler, as a temporary work around for it not working in view, you could set `statusbarPadding: true` in the config. This will show the padding when the platform is ios no matter where you view it though (including the browser):

```
@App({
  templateUrl: 'build/app.html',
  config: {
    platforms: {
      ios: {
        statusbarPadding: true
      }
    }
  }
})
```

**Comment by wli** [comment] 2016-04-29 21:49
@brandyscarney If it helps, I have `'tabSubPages': true` set in my app's config block.

**Comment by wli** [comment] 2016-04-29 21:50
I'm actually a bit unclear what that does - the documentation is a bit sparse on the subject: http://ionicframework.com/docs/v2/api/config/Config/

**Comment by abuechler** [comment] 2016-04-30 02:25
@brandyscarney Ok, that works. Thanks!

**Comment by brandyscarney** [comment] 2016-05-02 16:11
@wli The `tabSubPages` property hides the tabs section on child pages of the tab. Material Design does this by default, but iOS does not. I am able to see it now. Thank you! Will look into a fix. 

I agree we need to add more documentation behind the config properties. I think this is something we'll fix with this issue: https://github.com/driftyco/ionic-site/issues/585

**Comment by brandyscarney** [comment] 2016-05-02 16:32
@abuechler I created an issue for the Ionic View app not showing the status bar padding. This is something that will have to be resolved in the Ionic View app itself: https://github.com/driftyco/ionic-view-issues/issues/164

**Comment by brandyscarney** [comment] 2016-05-02 17:08
This will be fixed in the `beta.7` release. Thanks again for the issue!

**Closed by brandyscarney** 2016-05-02 17:08 UTC
Labels: platform:ios, v2

**Comment by EugeneSnihovsky** [comment] 2016-05-25 05:51
I have same issue on beta.7 release in ios emulator on ipad2 iphone5 and others.
I used custom navbar component with ion-navbar component

**Custom navbar component example:**
```html
<div #content>
    <ion-navbar *navbar>
        <button menuToggle end>
            <ion-icon name="menu"></ion-icon>
        </button>
        <ion-title>
            Dashboards
        </ion-title>
    </ion-navbar>
</div>
<ion-menu side="right" [content]="content">
    <ion-toolbar class="ion-menu-logo">
        <ion-title>Menu</ion-title>
    </ion-toolbar>
    <ion-content>
        <ion-list>
            <button class="ion-menu-button"
                    ion-item
                    menuClose
                    (click)="logOut()">
                <ion-icon item-left name="log-out"></ion-icon>
                Log out...
            </button>
        </ion-list>
    </ion-content>
</ion-menu>
```

```typescript
'use strict';

import {IONIC_DIRECTIVES} from 'ionic-angular/config/directives';
import {Component} from '@angular/core';
import {AuthService} from '../../../shared/services/$http/core';

@Component({
    selector: 'top-navbar',
    templateUrl: 'build/components/navigation/top-navbar/top-navbar.html',
    directives: [IONIC_DIRECTIVES]
})

export class TopNavBarComponent {
    constructor(
        private auth: AuthService
    ) {

    }
    public logOut() {
        var self = this;
        self.auth.logout();
    }
}
```
In CSS just change background:
```css
.toolbar-background {
      background: rgba(255,255,255,0.5);
    }
```

**Custom navbar component usage:**
Just add element to DOM @page template
```html
<top-navbar></top-navbar>

<ion-content>
    <h1>Dashboards page</h1>
</ion-content>
```
**Screen example**
![screen example](https://pp.vk.me/c626916/v626916167/d22a/IHUKjfysZn4.jpg "screen example")

**Ionic info:**
```
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Framework Version: 2.0.0-beta.7
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.5 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v5.6.0
Xcode version: Xcode 7.2.1 Build version 7C1002
```

**Comment by gxsjtu** [comment] 2016-08-23 02:07
in beta 11 and ios platform, if i set  tabsHideOnSubPages: true, navbar is still overlapped with status bar.
please check.
![img_0829](https://cloud.githubusercontent.com/assets/5119062/17877895/5b58fe4c-6919-11e6-944d-610f92f6e3c2.PNG)

**Comment by gurisko** [comment] 2016-09-15 16:13
I was also able to reproduce with `tabsHideOnSubPages: true` in ios simulator (not in Ionic View).
```Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v4.4.7
Xcode version: Xcode 8.0 Build version 8A218a
```

**Comment by kamok** [comment] 2017-03-09 15:01
Still issue still exists.

**Comment by brian14485** [comment] 2017-06-15 09:01
same

**Comment by lostdev** [comment] 2017-09-18 13:10
This is still an issue on iOS when setting , `tabsHideOnSubPages: true`.

Ionic info:
```
cli packages: (/Users/user131554/Downloads/mobile/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    ios-deploy : 1.9.2 
    ios-sim    : 6.0.0 
    Node       : v6.10.2
    npm        : 3.10.10 
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
```

**Comment by bangonkali** [comment] 2017-10-05 03:01
[Please check this out](https://forum.ionicframework.com/t/how-to-remove-space-at-the-top-of-navbar/44194/7).
