### ISSUE TITLE
bug: Ionic beta.1 multiple errors in log

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic#5560] opened 2016-02-22 20:15 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Here's the output most of the time of the logs:
```
Uncaught TypeError: Cannot read property 'getURL' of undefined(anonymous function) @ require-config.js:2
simSearch.js:2 Uncaught TypeError: reqC is not a function(anonymous function) @ simSearch.js:2
init.js:2 Uncaught TypeError: reqC is not a function(anonymous function) @ init.js:2
gmail_tooltip_check.js:2 Uncaught TypeError: Browser.addMessageHandlers is not a function(anonymous function) @ gmail_tooltip_check.js:2(anonymous function) @ gmail_tooltip_check.js:2
custom_tooltip_check.js:2 Uncaught TypeError: reqC is not a function(anonymous function) @ custom_tooltip_check.js:2
(index):29 DEPRECATION WARNING: 'enqueueTask' is no longer supported and will be removed in next major release. Use addTask/addRepeatingTask/addMicroTask
(index):29 DEPRECATION WARNING: 'dequeueTask' is no longer supported and will be removed in next major release. Use removeTask/removeRepeatingTask/removeMicroTask
(index):29 Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
frame_loader.js:2 Uncaught TypeError: Browser.addMessageHandlers is not a function(anonymous function) @ frame_loader.js:2
PdfTooltipCheck.js:2 Uncaught TypeError: Browser.addMessageHandlers is not a function
```

And from time to time when some http request fails i get: 
```
EXCEPTION: TypeError: Cannot read property 'nativeElement' of undefined
```
Which truly breaks my app.
</span>

<span is-issue-template></span>

**Comment by brandyscarney** [comment] 2016-02-22 20:25
Are you developing against the 2.0 branch? beta.2 hasn't been released yet.

**Comment by Luchillo** [comment] 2016-02-22 20:28
One of the logs for the last Exception about 'nativeElement' shows this:
```
TypeError: Cannot read property 'nativeElement' of undefined
    at new AlertPopOut (app.bundle.js:57437)
```
After inspecting i get the error is in the transition:
```js
var AlertPopOut = (function (_super) {
	    __extends(AlertPopOut, _super);
	    function AlertPopOut(enteringView, leavingView, opts) {
	        _super.call(this, opts);
	        var ele = leavingView.pageRef().nativeElement; :red_circle: // Here's the error shown by chrome dev tools
	        var backdrop = new animation_1.Animation(ele.querySelector('.backdrop'));
	        var wrapper = new animation_1.Animation(ele.querySelector('.alert-wrapper'));
	        wrapper.fromTo('opacity', '1', '0').fromTo('scale', '1', '0.9');
	        backdrop.fromTo('opacity', '0.3', '0');
	        this
	            .easing('ease-in-out')
	            .duration(200)
	            .add(backdrop)
	            .add(wrapper);
	    }
	    return AlertPopOut;
	})(transition_1.Transition);
	transition_1.Transition.register('alert-pop-out', AlertPopOut);
```

**Comment by Luchillo** [comment] 2016-02-22 20:35
@brandyscarney Sorry, typo, fixed title to beta.1

**Comment by mhartington** [comment] 2016-02-22 20:38
@Luchillo please describe how we could go about recreating this. While these logs are great, we still need to know what happened to get here.

```
ionic start tmp <template> --v2 --ts
```

Maybe a minimal repository that recreates the issue?

**Comment by Luchillo** [comment] 2016-02-22 20:42
Give me a minute, i'm updating cordova and ionic cli, cleaning cache and re-installing npm modules just in case.

**Comment by Luchillo** [comment] 2016-02-22 20:53
Update 1: Seems that all the errors except the last exception happens even with clean sidemenu starter when emulating ios device.

**Comment by brandyscarney** [comment] 2016-02-22 21:22
Do you have this extension by any chance? Or maybe another one: https://evernote.com/webclipper/?var=c

I found this issue, which is why I ask: https://discussion.evernote.com/topic/80637-if-chrome-is-the-device-mode-web-clipper-reblogged-output-js-error-on-the-console/

**Comment by tlancina** [comment] 2016-02-22 21:23
@Luchillo I'm unable to reproduce with either the JS or TS sidemenu starter.  I notice in the first error log that there are several scripts like `simSearch.js` and  `gmail_tooltip_check.js`.  If you are in Chrome, can you try running in a private window and tell us if the problem is still there.

**Comment by Luchillo** [comment] 2016-02-22 21:36
@brandyscarney Yes i have evernote webclipper, just uninstalled it and all errors but the exception did go away.

About the exception, it happens to me when 2 Alert instances get presented to the nav component before any of them get to close, the error happens when both are open and try to close one of them, working on make the issue being able to reproduce, is there a Plunker with ionic 2 setup?

**Comment by tlancina** [comment] 2016-02-22 22:12
Here's the tabs starter: http://plnkr.co/edit/497ow82ZkRMaJ6XZjieG?p=preview

**Comment by adamdbradley** [comment] 2016-02-22 23:00
@Luchillo Are you using master? I think i recently fixed this but it's not in a release yet. My test that I use is this: https://github.com/driftyco/ionic/blob/2.0/ionic/components/alert/test/basic/index.ts#L246

**Comment by Luchillo** [comment] 2016-02-22 23:01
Here's the closest i could get but at least it shows one of the errors that happens when Alerts overlaps:
http://plnkr.co/edit/ZFTiOtUqtQn3OcMhYySg?p=preview

**Comment by Luchillo** [comment] 2016-02-22 23:22
@adamdbradley I'm not using master, i'm using the one provided by npm, though from that test i think it has nothing to do with that, i stopped trying to close one alert before opening another, the plan here is to open multiple alerts, let them stack up and then, in the first one closing, trigger the dismiss for the other ones.

**Comment by mebibou** [comment] 2016-02-24 03:11
I have the same issue here, but it's not because I have multiple alerts open, simply because in one of the page I do:
````
ngOnInit() {
  this.getData().then(data => {
    this.data = data;
  }, alert => {
    this.nav.present(alert);
  });
}
````
When I test this on my android device, the error appears when dismissing the popup, and then the page where I was supposed to go and get the data never shows up and I remain on the previous page.

**Comment by mebibou** [comment] 2016-02-24 03:18
Note: if I do this in `onPageWillEnter` instead, same error, and if I do it on `onPageDidEnter`, then I don't have the error but I get stuck into an infinite loop of having the alert, dimissing, then `onPageDidEnter` gets called again and the alert appears, dismissing, etc.

**Comment by adamdbradley** [comment] 2016-03-07 04:47
I've made some fixes to alert and the nav controller which I hope solved this issue too. We'll be releasing beta3 soon, so once that's out would you be able to test it out and let us know if it's fixed? thanks

**Comment by mebibou** [comment] 2016-03-08 10:41
@adamdbradley it is even worse now, alert shows up before the new page is displayed, and then after dismissing nothing responds anymore

**Comment by iignatov** [comment] 2016-03-08 23:37
I'm experiencing the same issue:
```
EXCEPTION: TypeError: Cannot read property 'nativeElement' of undefined
```
**Steps to reproduce:**
1. Open: http://plnkr.co/edit/ecNEck8s4VB4RMpWki5k?p=preview
AND
2. Click the `Submit` button on the bottom.
OR
3. Enter invalid value in the textbox (shorter than 5 chars) and hit `Enter`.

> Notice that when clicking the top `Submit` button (the one in the navbar) everything works fine.

**Ionic Version**: 2.x

**Browser & Operating System**: Chrome


**Run `ionic info` from terminal/cmd prompt:**

```
Your system information:

Cordova CLI: 6.0.0
Ionic Version: 2.0.0-beta.1
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
OS: Windows 8.1
Node Version: v5.6.0
```

**Comment by iignatov** [comment] 2016-03-09 23:29
@adamdbradley I just tested with **beta3** and I can confirm the behavior reported by @mebibou. Now there's no exception in the console, i.e. the `TypeError` exception is not thrown anymore. However now there are other issues which could be observed in the [demo Plnkr environment](http://plnkr.co/edit/0tYMpJ7hP22btb5N9T30?p=preview) which I updated to use the latest Ionic 2 release: `ionic-angular@2.0.0-beta.3`.

**Steps to reproduce:**
1. Open: http://plnkr.co/edit/0tYMpJ7hP22btb5N9T30?p=preview
2. Click the `Submit` button on the bottom.
_(In this case the alert is shown but after dismissing it the UI remains inaccessible - visible but not usable.)_
3. Refresh the page (because the UI remains frozen after the previous step).
4. Enter invalid value in the textbox (shorter than 5 chars) and hit `Enter`.
_(In this case the alert is not even shown but the UI becomes inaccessible.)_

> Notice that when clicking the top `Submit` button (the one in the navbar) everything works fine.

**Ionic Version**: 2.x

**Browser & Operating System**: Chrome


**Run `ionic info` from terminal/cmd prompt:**

```
Your system information:

Cordova CLI: 6.0.0
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
OS: Windows 8.1
Node Version: v5.8.0
```

**Comment by iignatov** [comment] 2016-04-11 21:47
@Luchillo Are you still experiencing issues with the alerts? I had similar problems and they were resolved after the release of `beta.3`. I guess that the problems that you had might be resolved too and in such case this issue can be closed.

**Comment by jgw96** [comment] 2016-04-11 21:56
@iignatov Are you experiencing any issues with alerts with beta.4?

**Comment by iignatov** [comment] 2016-04-11 22:22
@jgw96 No, I don't experience any issues. With `beta.4` the alerts work fine for me. I tested the use-cases from the alert issues that I had (#5818 and #5821) and I can confirm that they are fixed in `beta.4`.

**Comment by jgw96** [comment] 2016-04-12 06:10
@iignatov Thanks for getting back to me! @Luchillo if you get a chance i would love for you to also test! In the meantime i will be closing this issue for now, as it seems to have been fixed.

**Closed by jgw96** 2016-04-12 06:10 UTC
Labels: alert, navigation, v2
