### ISSUE TITLE
iOS issue with header bar

### ISSUE THREAD

**Issue by danda1man** [driftyco/ionic#2875] opened 2015-01-06 02:33 UTC
![screen shot 2015-01-05 at 8 27 32 pm](https://cloud.githubusercontent.com/assets/852995/5623411/8045e718-9519-11e4-89db-0c6fafda03dd.png)

My html is very similar to this codepen you had posted in forums: http://codepen.io/mhartington/pen/fwyBh

Android does not have this, the .bar-header class sets top to 0.  If I remove the top 113px and it falls back to the 64 px, things look normal.  I still can't figure out where the has-tabs-top is coming from in the first place, but it's causing some havoc...

**Comment by gogoout** [comment] 2015-01-06 09:32
I had the same behaviour with you in both Ios and Android but I don't know if it's the same cause.
It turns out my cause is using html5 mode in $locationProvider.
The solution is therefore turn html5Mode off.
There is one releated issue here:{@link http://stackoverflow.com/questions/23276751/html5-mode-with-phonegap-and-angularjs/23278821#23278821}

**Comment by danda1man** [comment] 2015-01-06 15:34
Doesn't seem to cause any issues on android adding that...I will have to check at home on the iOS.  I would still appreciate if one of the devs could comment on if they have seen this before

**Comment by mhartington** [comment] 2015-02-09 23:46
Can you give the nightly builds a try? [This  was merged](https://github.com/driftyco/ionic/pull/3012) to fix that issue.

**Comment by russmatney** [comment] 2015-02-12 04:36
I was experiencing this on ios as well (only in the built app on an emulator/device, never in a local/emulator browser), and pulling in the latest nightly seems to have fixed it after rebuilding. Some other issues have popped up that i'm happier to be working through now, smaller ones that are reproducible in the browser (just a missing icon and a broken angular filter so far).

**Comment by russmatney** [comment] 2015-02-12 04:44
A quick follow up – the missing icon was just an ionicons icon name update (`ios7-paper` to `ios-paper`) and the broken filter was a bug i introduced myself when trying to fix the above spacing issue (i'd changed a `label.item` to a `ion-item` and isolated the scope).

**Comment by Ionitron** [comment] 2015-02-25 03:20
Greetings @danda1man!

I've closed this issue because my sensors indicated that perhaps it is no longer applicable--or may have already been fixed. However, if you are still experiencing this issue, please feel free to reopen it by creating a new one, and provide the following information, so that I may assist you:

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this issue occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) which replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com). The humans there would be delighted to help you.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-02-25 03:20 UTC
Labels: ionitron:closed

**Comment by danda1man** [comment] 2015-02-28 17:33
Sorry I forgot to check on this.  I can confirm that th nightly build fix this as well as some other issues with the header bars in ios.  Thanks!
