### ISSUE TITLE
Nav Bar back Button is not clickable.

### ISSUE THREAD

**Issue by THEDOWNCOUNTRY** [driftyco/ionic#9781] opened 2016-12-23 22:46 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ *] **2.x**

**I'm submitting a ...**  (check one with "x")
[* ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior: The back button is not not clickable when navigate to a new view.**

**Expected behavior: To navigate to the previous page or view with I it the back button from the navigation bar.. **

**Steps to reproduce:**

**Related code: import { Component, ViewChild  } from '@angular/core';
import { NavController } from 'ionic-angular';
import { Class1 } from '../../views/page1/page1';
import { Class2 } from '../../views/page2/page2';

@Component({
  selector: 'htmlfile',
  templateUrl: 'htmlfile.html'
})
export class htmlFileClass {

   @ViewChild('content') nav: NavController
   public rootPage = Games;
  pageViews: Array<{ title: string, component: any }>;

  constructor(

    public navCtrl: NavController

  ) {
    this.pageViews= [
      { title: 'Page Title 1', component: Class1 },
      { title: 'Page Title 2', component: Class2 }
    ];
  }

  openPage(view) {

    console.log(view);

    this.navCtrl.push(view.component, {
      title: view.title
    });
  }

}**

**Comment by THEDOWNCOUNTRY** [comment] 2016-12-26 20:19
The problem with this was that the 
ion-title {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  text-align: center;
} 

so it had cover the back button making it not receiving the click event from the user... after inspecting the html elements with chrome I fixed it with:

 ion-title {
    position: absolute;
    top: 0;
    left: 25%;
    width: 50%;
    height: 100%;
    text-align: center;
}

**Comment by jgw96** [comment] 2016-12-27 15:35
Hello, thanks for using Ionic! Unfortunately I cannot reproduce this issue, could you post a repo or plunkr that I can use to reproduce this issue please?

**Comment by jgw96** [comment] 2017-01-03 16:01
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-01-03 16:01 UTC
Labels: needs info, needs reply, v2
