### ISSUE TITLE
scrolling initially "janky" inside modal with virtual scroll.

### ISSUE THREAD

**Issue by MattDHill** [driftyco/ionic#6833] opened 2016-06-09 22:39 UTC
#### What behavior are you expecting? Scrolling animation should be smooth from the start.

**Steps to reproduce:**
1. check out this repo: https://github.com/MattDHill/VirtualScroll
2. run "ionic emulate ios"
3. click the "open modal" button
4. Try scrolling down

**Other information:**
Scrolling works fine in the browser. Issue occurs when running on iOS emulator or device. However, the issue may exist on Android as well, but I am not current set up to test that.

**Which Ionic Version?** 2 beta8

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Ionic Framework Version: 2.0.0-beta.8
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.4.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by ghenry22** [comment] 2016-06-28 04:49
this is not specific to the modal, I see it everywhere on iOS uiwebview.  This has been improved a lot in beta9.

beta9 still has some issues with scroll acceleration not being right on virtualscroll but the animation is much smoother.

**Comment by jgw96** [comment] 2016-12-29 21:11
Hello all! I am going to close this issue for now as I cannot reproduce this in RC4 either in a modal or a normal page. Thanks for using Ionic!

**Closed by jgw96** 2016-12-29 21:11 UTC
Labels: modals, platform:ios, v2, virtualscroll
