### ISSUE TITLE
Android: Popover RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by chack** [driftyco/ionic#7700] opened 2016-08-13 14:15 UTC
#### Short description of the problem:

On a Popover in Android (Genymotion Emulator) when I use a <ion-list> Radio Group with an imported Model I get following error:
RangeError: Maximum call stack size exceeded

In IOS everything works fine...

CODE:
```
<ion-list radio-group [(ngModel)]="suchService.sort" class="popover-page">
      <ion-item>
        <ion-label>Entfernung aufsteigend</ion-label>
        <ion-radio (click)="sortchange()"value=""></ion-radio>
      </ion-item>
      <ion-item>
        <ion-label>Neueste zuerst</ion-label>
        <ion-radio (click)="sortchange()"value="9"></ion-radio>
      </ion-item>
</ion-list>

....

sortchange(){
	  this.viewController.dismiss()
	  
  }
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 ERROR:

![bildschirmfoto 2016-08-13 um 16 12 44](https://cloud.githubusercontent.com/assets/130860/17643654/d219d390-6170-11e6-9275-bf605ae37768.png)

**Which Ionic Version?** 1.x or 2.x

2.0 Beta 11
#### Plunker that shows an example of your issue

**For Ionic 2 issues** - http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.36
Ionic App Lib Version: 2.0.0-beta.19
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.4.7
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by chack** [comment] 2016-08-13 14:22
I just saw following:
Android Emulator:
![bildschirmfoto 2016-08-13 um 16 21 02](https://cloud.githubusercontent.com/assets/130860/17643694/04abe22a-6172-11e6-87ec-a4cad3c026a7.png)

Webseite Emulator:
![bildschirmfoto 2016-08-13 um 16 21 10](https://cloud.githubusercontent.com/assets/130860/17643697/0c35d064-6172-11e6-970f-952cf56ef4af.png)

It seems as the List isn't binding to the model?

**Comment by chack** [comment] 2016-08-13 15:09
An empty Template results in:
![bildschirmfoto 2016-08-13 um 17 09 09](https://cloud.githubusercontent.com/assets/130860/17643922/ba0e2226-6178-11e6-87b1-a01d176227bb.png)

I don't use this Class? Where does it come from?

**Comment by jgw96** [comment] 2016-08-14 05:34
Hello! Thanks for opening an issue with us! I am going to be closing this issue as a duplicate of https://github.com/driftyco/ionic/issues/6918. Thanks for using Ionic!

**Closed by jgw96** 2016-08-14 05:34 UTC
Labels: platform:android, platform:ios, popover, radio, range, v2
