### ISSUE TITLE
bug: Tab navigation is broken

### ISSUE THREAD

**Issue by BetterTrader** [driftyco/ionic#4075] opened 2015-07-13 09:58 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>I think I found a bug but I'm unable to share a code here, since you'll need to run it locally and be able to open the app within an inner url:
Let's look at the regular tabs app - when you click "chats", choose a person and then click "chats" again - it goes back to the chats screen.
BUT - if you start the app fron an inner url ('#/tab/chats/0') and click "chats" - nothing will happen.
And not only that, but if you now navigate outside of the current view and click "chats" again - you'll be back at '#/tab/chats/0'

Anybody noticed that issue?
What can I do about it without using "ion-tab on-select"?</span>

<span is-issue-template></span>

**Comment by huttj** [comment] 2015-07-15 17:32
So, I don't think the issue is a big deal, since the app should never start on an inner URL.

However, I have a related issue that I wanted to report where opening a child state before the tab's main state makes it impossible to load the main state by clicking/tapping the tab. You have first navigate to the tab's main state for it to become the root entry in the tab's history.

So, essentially, I can't link to a child state from a main state without a hacky workaround.

[Here's an example.](http://codepen.io/anon/pen/KpeJZb)

Broken Path:
1. On the *Home* tab, click the **Tab Nav Stack** button. You'll go to the *Tab Nav Stack* page in the *About* view.
2. Click the *About* tab. Nothing happens.

Working Path:
1. Click the **About** tab.
2. Click the **Tab Nav Stack** button.
3. Click the **About** tab. You'll go back to the *About* tab.
4. Click the **Home** tab.
5. Click the **Tab Nav Stack** button.
6. Click the **About** tab. You'll go back to the *About* tab.

I should be able to click the *About* tab no matter what my history looks like and go to the *About* tab. As BetterTrader points out, this should probably clear the tab's history stack, too.

So, the tabs directive should initialize the history with the main state already registered. That way I can link to any child state and still be able to get back to the parent state.

**Comment by BetterTrader** [comment] 2015-07-19 06:31
We also want to use the app as a website, so that's indeed an issue

**Comment by webmutation** [comment] 2015-10-30 11:07
+1 Also facing this issue, worked around it, but navigation is certainly a big concern in Ionic 1.1

**Comment by jgw96** [comment] 2016-04-21 15:48
Hello all! Is this still an issue in the latest version of ionic 1 ? Thanks!

**Comment by jgw96** [comment] 2016-04-26 14:46
Hello! As it has been a little while since there was any activity on this issue I will be closing it. Thanks for using ionic!

**Comment by huttj** [comment] 2016-04-26 15:48
@jgw96: Apologies for the delayed reply on this one, but it looks like it's still an issue.

If you click through to [the example](http://codepen.io/anon/pen/KpeJZb) that I provided, and follow the repro steps, you'll see that it still sets the linked view as the root for the tab, ignoring the actual root, which only gets initialized if you navigate to it first.

This example uses the latest nightly build, so unless that isn't regularly refreshed, it looks like it hasn't been resolved.

**Comment by jgw96** [comment] 2017-01-13 20:42
This issue was moved to driftyco/ionic-v1#16

**Closed by jgw96** 2017-01-13 20:42 UTC
Labels: navigation, tabs, v1
