### ISSUE TITLE
Item divider "color" attribute doesn't work with RC0

### ISSUE THREAD

**Issue by smichelotti** [driftyco/ionic#8628] opened 2016-10-11 03:24 UTC
Before RC0, we could set the "secondary" attribute on an `<ion-item-divider>` and it would change the color like this:

```html
<ion-list>
    <ion-item-group *ngFor="let division of teams">
        <ion-item-divider secondary>{{division.divisionName}}</ion-item-divider>
        <button ion-item *ngFor="let team of division.divisionTeams" (click)="itemTapped($event, team)">
            {{team.name}}
        </button>
    </ion-item-group>
</ion-list>
```

Per the RC0 documentation, we now use a `color` attribute:
```html
<ion-list>
    <ion-item-group *ngFor="let division of teams">
        <ion-item-divider color="secondary">{{division.divisionName}}</ion-item-divider>
        <button ion-item *ngFor="let team of division.divisionTeams" (click)="itemTapped($event, team)">
            {{team.name}}
        </button>
    </ion-item-group>
</ion-list>
```

This no longer changes the color of the item divider correctly. Upon inspection in Chrome, the class attribute is getting: `"item item-md item-md-secondary"`, but the `.item-md-secondary` CSS is getting overridden. See screen shot.

![item-divider-color](https://cloud.githubusercontent.com/assets/1382246/19257814/af522c88-8f40-11e6-8854-33d8b08455ad.png)

Additionally, here is a Plunker that shows the problem: http://plnkr.co/edit/w6Xqqv?p=preview

**Comment by ekhmoi** [comment] 2016-10-11 09:14
duplicate of [#8376](https://github.com/driftyco/ionic/issues/8376)

**Comment by jgw96** [comment] 2016-10-11 15:56
Hello all! Thanks for opening an issue with us! I am going to close this issue as a duplicate of #8376 .

**Closed by jgw96** 2016-10-11 15:56 UTC
Labels: css, v2
