### ISSUE TITLE
The constructor will be repeated when the same tab is selected consecutively

### ISSUE THREAD

**Issue by ken1106** [driftyco/ionic#11332] opened 2017-04-23 13:57 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The constructor will be repeated when the same tab is selected consecutively.

**Expected behavior:**
Tabs's page's constructor only called once.

**Steps to reproduce:**

1. ionic start ionic2-tabs tabs --v2
2. add console log in constructor function
3. select the same tab consecutively

**Related code:**

```
ionic start ionic2-tabs tabs --v2
```

**Other information:**
![ionic-3-tabs](https://cloud.githubusercontent.com/assets/6749419/25314096/b72ee4c8-286f-11e7-8d51-8b459b4f139b.gif)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.0
ios-sim version: 5.0.10
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.3.2 Build version 8E2002
```

**Comment by aemr3** [comment] 2017-04-23 14:18
I have the same issue...

**Comment by antoine92190** [comment] 2017-04-24 11:34
Duplicate of #11015

**Comment by manucorporat** [comment] 2017-04-24 13:50
it is probably creating new instances of the same page, calling the constructor of the same instance several times is not possible

**Comment by jgw96** [comment] 2017-04-24 16:04
Hello, all! This has actually already been fixed by this PR https://github.com/driftyco/ionic/pull/11084 that I merged last week and will, therefore, be in the next release. Thanks for using Ionic!

**Closed by jgw96** 2017-04-24 16:04 UTC
