### ISSUE TITLE
Ionic2/Android 4.4.4 - Uncaught Cannot resolve all parameters for 'App'(?, ?, ?)

### ISSUE THREAD

**Issue by HamzaLJ** [driftyco/ionic#8044] opened 2016-09-10 20:00 UTC
Short description of the problem:
I am running my Ionic2 app under Android 4.4.4 on a real device; however, I am getting a white black screen, after inspecting the device I got the following error:

**Uncaught Cannot resolve all parameters for 'App'(?, ?, ?). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'App' is decorated with Injectable.** 

_I've tried to run it on Android 5.1, it worked fine!_

I've read some posts saying that in order to hide the error, I should use crosswalk, but I believe that Ionic2 support Android versions >= 4.4.4 So it should work without crosswalk!

My index.html:

```
<html dir="ltr" lang="en">

<head>
  <title>Ionic</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="format-detection" content="telephone=no">
  <meta name="msapplication-tap-highlight" content="no">

  <link ios-href="build/css/app.ios.css" rel="stylesheet">
  <link md-href="build/css/app.md.css" rel="stylesheet">
  <link wp-href="build/css/app.wp.css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
</head>

<body>
  <ion-app></ion-app>
  <!-- cordova.js required for cordova apps -->
  <script src="cordova.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.14.1/moment.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment-timezone/0.5.4/moment-timezone.js"></script>

  <script src="lib/polyfill.min.js"></script>

  <!-- Zone.js and Reflect-metadata  -->
  <script src="build/js/zone.js"></script>
  <script src="build/js/Reflect.js"></script>
  <!-- the bundle which is built from the app's source code -->
  <script src="build/js/app.bundle.js"></script>
  <!-- Polyfill needed for platforms without Promise and Collection support -->
 <script src="build/js/es6-shim.min.js"></script>
</body>
</html>
```

**Which Ionic Version?** 1.x or 2.x
2.0

Your system information:

Cordova CLI: 6.3.0
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.4.7
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by HamzaLJ** [comment] 2016-09-11 00:13
I was able to make it work with crosswalk, but unfortunately it does does render views really well, f_or example if I have a modal it shows it half of the dimensions of the screen, and does not show in full page_ without forgetting that it adds nearly 30MB to the APK, etc..
That's why I would like to go without crosswalk. Normally Ionic2 support Android 4.4, but it does not seem to be working as it raised the above error!

**Comment by jgw96** [comment] 2016-09-12 15:21
Hello, thanks for opening an issue with us! What device are you testing with Android 4.4.4? Do you run into the same issue with an Android 4.4.4 emulator?

**Comment by HamzaLJ** [comment] 2016-09-12 21:30
@jgw96 
I've tested on a Samsung Galaxy s4 with Android 4.4.4 and received that error.
I've also tried to run it on the emulator under 4.4.4 and receive the same error.

**Comment by jgw96** [comment] 2016-09-13 21:04
@HamzaLJ would you be able to create a minimal example that I can use to reproduce this issue? It seems to be working for me on the Android 4.4.4 emulator. I also cannot seem to reproduce any rendering issues with crosswalk. Thanks!

**Comment by jgw96** [comment] 2016-09-16 15:07
Hello! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-09-16 15:07 UTC
Labels: needs reply, v2
