### ISSUE TITLE
Ionic 2 - EXCEPTION: TypeError: undefined is not a function

### ISSUE THREAD

**Issue by HamzaLJ** [driftyco/ionic#8014] opened 2016-09-08 15:05 UTC
**Short description of the problem:**

I finished building my IONIC2 app, the iOS version works fine; however, when I try to run the same page on the Android Simulator an error, _I was able to get it when I inspected the running app on CHROME_:

           EXCEPTION: TypeError: undefined is not a function
          browser_adapter.js:77 EXCEPTION: TypeError: undefined is not a function
          browser_adapter.js:77 STACKTRACE:
          browser_adapter.js:77 TypeError: undefined is not a function
          at new DishesComponent (file:///android_asset/www/build/js/app.bundle.js:1746:49)
          at AppView._View_MenuPage2.createInternal (MenuPage.template.js:354:31)
          at AppView.create (file:///android_asset/www/build/js/app.bundle.js:33434:21)
          at TemplateRef_.createEmbeddedView (file:///android_asset/www/build/js/app.bundle.js:33335:14)
              at ViewContainerRef_.createEmbeddedView (file:///android_asset/www/build/js/app.bundle.js:33844:35)
              at NgFor._bulkInsert (file:///android_asset/www/build/js/app.bundle.js:4250:50)
              at NgFor._applyChanges (file:///android_asset/www/build/js/app.bundle.js:4206:14)
              at NgFor.ngDoCheck (file:///android_asset/www/build/js/app.bundle.js:4188:22)
              at AppView._View_MenuPage0.detectChangesInternal (MenuPage.template.js:225:42)
              at AppView.detectChanges (file:///android_asset/www/build/js/app.bundle.js:33581:14)

**Which Ionic Version?** 1.x or 2.x
**2.0**

_Unfortunately, I can't make a plunker because, it's a finished app and the page having the issue is really big._

For the records, the issue appears **ONLY** on the android emulator, when I run it on Chrome (MAC), everything is working fine. To emulate I am using **Android 5.1**

**Your system information:**

Cordova CLI: 6.3.0
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.4.7
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment] 2016-09-08 15:11
Hello, thanks for opening an issue with us! Does this also happen on a real Android device?

**Comment by HamzaLJ** [comment] 2016-09-08 15:13
I haven't tried that on the real device as I don't have one, but I guess it would be the same as I think the emulator renders elements the same way the device does (correct me if I am wrong).

**Comment by jgw96** [comment] 2016-09-08 16:16
Hmm unfortunately I cannot seem to reproduce this issue with any of my test apps. If you could come up with a minimal reproducible example repo that would be great! From looking at the error again it looks like there is an issue in your MenuPage component. Thanks!

**Comment by Malkiat-Singh** [comment] 2016-09-08 17:00
@HamzaLJ  This seems you trying to call function from template which is missing

**Comment by jgw96** [comment] 2016-09-08 18:09
Hello @HamzaLJ after reviewing this issue some more it does seem to be an issue coming from ionic but instead from your code. Because of this I am going to close this issue for now, but feel free to comment back if you find otherwise. Thanks for using Ionic!

**Closed by jgw96** 2016-09-08 18:09 UTC
Labels: v2

**Comment by HamzaLJ** [comment] 2016-09-08 19:02
@jgw96 I found the line that triggers the issue, but I can't solve it!
I'll share the lines that causing the issue:

**page1.html**

     <ion-slides id="dishes-content" class="dishes-slides" (ionWillChange)="onCategoryChanged($event.activeIndex)">
         <ion-slide *ngFor="let category of categories; let i = index">

         //When I remove the below line, the issue disappears!!
        //This is a directive imported from finalMenu
        <dishes [categoryValue]="category" [cart]="cart"></dishes>

      </ion-slide>
     </ion-slides>


**page1.js**

    @Component({
     templateUrl: 'build/pages/page1/page1.html',
     directives: [DishesComponent],
     queries: {
       sliders: new ViewChildren(Slides)
     }
     })


**finalmenu.js**

    @Component({
     selector: 'dishes',
     inputs: ['categoryValue', 'cart'],
     templateUrl: 'build/pages/finalmenu/finalmenu.html'
       })

**Comment by jgw96** [comment] 2016-09-08 19:29
Hmm, it looks like its definitely an issue with your custom component. Unfortunately since this is not an Ionic issue there is not much I can do but you can always ask around on our [forum](https://forum.ionicframework.com) and someone on there should be able to help. Thanks for using Ionic!

**Comment by dradud** [comment] 2017-06-04 08:48
Hi, I had the same problem. 
Resolved it by looking in the component template.
**Before:**
`@Component({
  templateUrl: 'level.html'
})`
**After:**
`@Component({
  templateUrl: 'edit-level.html'
})`
The templateUrl was the same as the page it comes from.
