### ISSUE TITLE
bug: bug: $ionicScrollDelegate.$getByHandle does not work on first load of controller

### ISSUE THREAD

**Issue by wesleycho** [driftyco/ionic#3293] opened 2015-03-11 22:29 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I attempted to upgrade Ionic from 1.0.0 beta 14 to 1.0.0 rc0, and I encountered a problem with $ionicScrollDelegate.$getByHandle not finding the delegate-handle - I get the error message
<pre>
Delegate for handle "name-of-view" could not find a corresponding element with delegate-handle="name-of-view"! resize() was not called!
Possible cause: If you are calling resize() immediately, and your element with delegate-handle="name-of-view" is a child of your controller, then your element may not be compiled yet. Put a $timeout around your call to resize() and try again.
</pre>

I am using the ion-content directive, so the scroll container is a child - this appears to be the cause of this problem as far as I can tell, since this message consistently fires.

I also have the call to $ionicScrollDelegate.$getByHandle wrapped inside a $timeout and the element definitely exists by that time, as exhibited from a console.log while I was debugging.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-03-11 22:29
Greetings @wesleycho!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3293). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3293)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment] 2015-03-16 16:44
So when you wrap it in a `$timeout`, it works as expected? It working before RC 0 may have been a race condition.

**Comment by wesleycho** [comment] 2015-03-16 16:56
It does not work as expected, in a $timeout or without.

**Comment by dani-inside** [comment] 2015-05-06 08:31
Having the same issue, the element cannot be found, neither in a $timeout nor without $timeout. Any news on this one?

**Comment by perrygovier** [comment] 2015-05-07 16:26
Can you put together a codepen demonstrating the issue?

**Comment by dani-inside** [comment] 2015-05-12 09:35
I could solve the problem now, it was caused by me: I didn't place the delegate-handler attribute on the scroll container but on the element I wanted to scroll to. I guess that is intended to be like that.

**Comment by Ionitron** [comment] 2015-06-06 20:25
Greetings @wesleycho!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment] 2015-06-06 20:25
Greetings @wesleycho!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-06-06 20:25 UTC
Labels: ionitron:closed, scroll
