### ISSUE TITLE
bug: RepeatController render items calculation is wrong

### ISSUE THREAD

**Issue by dreamershl** [driftyco/ionic#3409] opened 2015-03-26 07:54 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>RepeatController render item calculation doesn't cater for the invisible list. when the scrollValue and  scrollValueEnd are 0, it will treat all the items as visible items. Same issue as the previous version

      var scrollValue = view.getScrollValue();
      var scrollValueEnd = scrollValue + view.scrollPrimarySize;

When scrollView is invisible, the __clientHeight & __clientWidth will 0. Then the scrollValueEnd will be 0 too. Then the following code will come out the full range of the data items for renderStartIndex=0 & renderEndIndex=data.length -1

       view.updateRenderRange(scrollValue, scrollValueEnd);</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-04-17 19:53
Greetings @dreamershl!

My sensors indicate that I require more information in order to assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this happen occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com), where many humans will be able to offer wisdom and advice.

Thank you for allowing me to assist you.

<span ionitron-needs-reply></span>

**Comment by Ionitron** [comment] 2015-05-17 23:46
Greetings @dreamershl!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment] 2015-05-17 23:46
Greetings @dreamershl!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-05-17 23:46 UTC
Labels: ionitron:closed
