### ISSUE TITLE
bug: bug: Ion spinner not spinning in Windows Phone 8.1

### ISSUE THREAD

**Issue by VeldMuijz** [driftyco/ionic#3480] opened 2015-04-07 15:08 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi,
I'm creating an app for Windows Phone 8.1, Android and iOS.
The spinner directive doesn't show a spinning spinner in WP8.1 just a static image.

The spinning css look like it uses css animations that are supported by Internet Explorere 11 and I don't know where else to look.

Spinners do work on Android and iOS.

[CodePen.io example](http://codepen.io/VeldMuijz/pen/ogRyva)

Example gif (left is windows, right is android):
![github example spinner](https://cloud.githubusercontent.com/assets/1394439/7026214/ba5fe666-dd48-11e4-8dd7-bdcaeda14565.gif)
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-04-07 15:08
Greetings @VeldMuijz!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3480). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3480)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment] 2015-04-14 20:36
Thanks @VeldMuijz, we'll look in to it

**Closed** 2015-04-21 22:13 UTC
Labels: animation, wp8

**Comment by perrygovier** [comment] 2015-04-21 22:18
@VeldMuijz the problem is that IE doesn't support smil animations. since the android spinner uses a timing function instead of smil animation, I set that to be the default spinner on windows phone.  That's not a great solution, but it's what we're going to do for now. You can add CSS animations to some of the spinners to get them looking right as well. Something like: 
```sass
.platform-windowsphone8 {
  .spinner-ios,
  .spinner-ios-small,
  .spinner-circles,
  .spinner-crescent{
    svg {
      animation:spin 1250ms linear infinite;
    }
  }
  .spinner-spiral svg{
    animation:spin 750ms linear infinite;
  }
}
@-webkit-keyframes spin {
  from { -webkit-transform: rotate(0deg) }
  to { -webkit-transform: rotate(360deg) }
}
@keyframes spin
{
  from { transform:rotate(0deg); }
  to { transform:rotate(360deg); }
}
```

but the animation isn't perfect so we don't plan on adding it to the core

**Comment by jdnichollsc** [comment] 2016-01-11 19:08
@perrygovier please, add in the Ionic website a page of tips to use Ionic Framework. This info is very useful! :)
