### ISSUE TITLE
bug: List reorder button styling

### ISSUE THREAD

**Issue by markdegrootnl** [driftyco/ionic#3714] opened 2015-05-13 08:51 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>The list reorder button can't be styled. When I add a class like .button-positive, the .item-reorder .button.icon class still overwrites the color and background.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-05-13 08:51
Greetings @markdegrootnl!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3714). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3714)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment] 2015-05-13 16:20
so it is... good catch
http://codepen.io/perrygovier/pen/xGVdqQ

**Comment by jgw96** [comment] 2016-06-21 18:53
Hello all! I am going to close this as as it being by design. Thanks for using Ionic!

**Closed by jgw96** 2016-06-21 18:53 UTC
Labels: css, list, ready, v1
