### ISSUE TITLE
materializecss android native back button is not working

### ISSUE THREAD

**Issue by gauravshegokar** [driftyco/ionic#5514] opened 2016-02-18 21:32 UTC
added materializecss to app, everything is working fine. but the problem is with the back button of android. It gets buffered, when i go to another view then back button is processed. If i clicked multiple times on back button all that is executed when i change view.
app is running on latest ionic version.

**Comment by jgw96** [comment] 2016-03-14 04:15
Thanks for submitting an issue with us! Would you mind sharing a code sample so that we can easily reproduce your issue? Also are you currently using Ionic v1 or Ionic 2? Thanks again!

**Comment by jgw96** [comment] 2016-03-18 15:22
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!

**Closed by jgw96** 2016-03-18 15:22 UTC
Labels: platform:android, related to external library
