### ISSUE TITLE
bug: Focus input problem, page becomes blank [1.2.3]

### ISSUE THREAD

**Issue by privetr** [driftyco/ionic#4892] opened 2016-01-03 11:17 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>The problem is maybe relative to the #4888 but I'm not sure.

When I focus on a simple input text on a Android device, the keyboard shows up, but the rest of the page becomes white, and we can't see the input anymore (It's like if there was the normal Keyboard, and above a white div with the same size of the Keyboard)

You can see the difference on the two attached images.
At the first focus there is the bug, and then we can't scroll anymore...
This seems to be VERY urgent...</span>

<span is-issue-template></span>

**Comment by privetr** [comment] 2016-01-03 11:18
![screenshot_20160103-115206](https://cloud.githubusercontent.com/assets/8597289/12078466/07888e34-b214-11e5-81d1-fb43706456a6.png)
![Uploading Screenshot_20160103-115214.png…]()

**Comment by mlynch** [comment] 2016-01-03 16:08
Duplicate of #4888 but thank you for the additional information. Any chance you have some sample code, or even just the code for your form? Will try to fix today.

**Closed by mlynch** 2016-01-03 16:08 UTC

**Comment by mlynch** [comment] 2016-01-03 16:18
I'm having some trouble reproducing this on 5 with 1.2.3. Can you tell me more about the structure of your app?

**Comment by privetr** [comment] 2016-01-03 17:35
Indeed, I could not reproduce it when starting with Ionic Blank template (using 1.2.3 version)

But can't fix the problem in my app... I'm using <ion-nav-view> but I don't know if it comes from it...

Here is my index.html main code : 

<body>
    <ion-nav-view></ion-nav-view>
  </body>

And for example my home.html page (where the problem happens)

<ion-header-bar class="bar-positive" align-title="center">
    <h1 class="title">
        <img class="title-image" src="img/logo.png" width="100" height="25" /> 
    </h1>
</ion-header-bar>

<div class="bar bar-subheader bar-positive">
    <h2 class="title">Accueil</h2>
</div>

<ion-nav-view>
    <ion-view view-title="ETP Greffe Pulmonaire - Accueil"  hide-back-button="true">

        
        <ion-content class="has-header has-subheader has-footer">


            <div class="col">
                <form class="simple-form" name="formConnexion" ng-submit="vm.doLogin()" style="padding-top: 40px">
                    <div class="row">
                        <div class="col col-33 col-offset-33">
                            <div class="list">
                              <label class="item item-input" style="border-color: #D9004D">
                                <input type="password" ng-model="vm.password" placeholder="Mot de passe">
                              </label>
                            </div>
                        </div>
                    </div>

                    <div class="row" style="margin-top:20px;">
                        <button type="submit" class="button button-positive col-33 col-offset-33">
                            <i class="icon ion-log-in"></i> Connexion
                        </button>
                    </div>
                </form>
            </div>
        </ion-content>

    </ion-view>
</ion-nav-view>

Is there something wrong ? I had not the problem before :( I can't test on IOS at the moment...

**Comment by mlynch** [comment] 2016-01-03 18:43
Hmmm. Are you testing in an emulator or a device (and if so, which one?). On genymotion and stock emulator, 5.1, I can't get the issue to happen with your snippet. Trying to dig deeper...

**Comment by privetr** [comment] 2016-01-03 18:46
I am using a nexus 6 device. I will look for it harder tomorrowland night...

**Comment by privetr** [comment] 2016-01-04 19:56
The problem appeared on version 1.2.2 in the ionic.bundle.min.js file.
With 1.2.1 I don't have the problem.
I does not come from the css (I am currently using the 1.2.4 css version).

**Comment by privetr** [comment] 2016-01-05 08:00
@mlynch As mentioned in #4888 , adding overflow-scroll="false" in ion-content fixes the problem.
But I think it is not the right solution, because for me native scrolling is the main evolution of Ionic 1.2...

**Comment by privetr** [comment] 2016-01-17 17:00
In the end, I did not try enough... Even overflow-scroll="false" did not fix it. I still encounter the problem on all inputs, on both Android and Ios version, not all the time, but most of time. 
I really regret I updated my app to Ionic 1.2.....

**Comment by anasbud** [comment] 2016-04-06 08:53
A bit late to the party, but did you find a solution ?

**Comment by privetr** [comment] 2016-07-11 12:13
I still have the problem on Ionic 1.3.1 version
Nobody else has got the problem ??? The app is unusable...
