### ISSUE TITLE
V2 - Select doesn't select the default value if it's a number

### ISSUE THREAD

**Issue by JumBay** [driftyco/ionic#5617] opened 2016-02-26 01:58 UTC
#### Short description of the problem:
Create a simple select where values are numbers, set the default value to one of them, it's not working

**Steps to reproduce:**

```ts
@Page({
    templateUrl: 'build/pages/page1/page1.html',
})
export class Page1 {
    playerId:number = 0;
    players = [
        {
            id: 0,
            name: 'None'
        },
        {
            id: 1,
            name: 'Foo'
        },
        {
            id: 2,
            name: 'Bar'
        }
    ];
}
`````

```html

  <ion-item>
    <ion-label>Players</ion-label>

    <ion-select [(ngModel)]="playerId">
        <ion-option
                *ngFor="#player of players" value="{{player.id}}"
                checked="{{player.id == playerId ? 'true' : 'false'}}">
            {{player.name}}
        </ion-option>
    </ion-select>
  </ion-item>

```

if playerId is set as a string, it works: 
```ts 
playerId:string = '0';
```

**Ionic Version**: 2.x

**Browser & Operating System**: iOS / Android / Chrome

**ionic info: **

```
Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Version: 2.0.0-beta.1
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: 1.8.5
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v5.6.0
Xcode version: Xcode 7.2.1 Build version 7C1002
```

**Comment by brandyscarney** [comment] 2016-02-26 22:10
Thanks for the descriptive issue! This is a duplicate of #5495. It will be fixed with the next release (beta.2). :smile:

**Closed by brandyscarney** 2016-02-26 22:10 UTC
Labels: platform:android, platform:ios, select, v2
