### ISSUE TITLE
Ionic Cloud more than one user logging in at once fails

### ISSUE THREAD

**Issue by nicksmithr** [driftyco/ionic#10682] opened 2017-03-07 16:30 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When more than one user tries to authenticate with Instagram at the same time, an error occurs with one or more of the users: "message": "Invalid state parameter provided" 

See Ionic Cloud number 182

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
https://github.com/driftyco/ionic-cloud/issues/182
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic Cloud Issues 182
```

I have posted on Ionic Cloud and Cloud Issues, would be great to hear back as it's been 2 days now and I've got 150 angry beta testers.

**Comment by wbhob** [comment] 2017-03-07 16:58
Please post at https://github.com/driftyco/ionic-cloud-issues

**Comment by jgw96** [comment] 2017-03-07 17:12
Thanks for opening an issue with us! Going to close this as a duplicate of https://github.com/driftyco/ionic-cloud/issues/182

**Closed by jgw96** 2017-03-07 17:12 UTC
