### ISSUE TITLE
strange flashing under [at least] two distinct circumstances

### ISSUE THREAD

**Issue by MattDHill** [driftyco/ionic#6857] opened 2016-06-10 23:00 UTC
#### Short description of the problem:

**This is new behavior since the update to beta8.**

1. Screen "flashes" just prior to pushing to another view. This happens if and only if (1) selecting from a list element in the current component that exceeds the viewable screen area (thus enabling scroll content), **and** (2) the target component depends on multiple providers that have dependencies of their own. (See demo).

2. Screen also "flashes" just prior to presenting an ActionSheet. This happens if and only if: selecting from a list element that exceeds the viewable screen area (thus enabling scroll content).

#### What behavior are you expecting? There should be no flash.

**Steps to reproduce:**
1. Check out this repo: https://github.com/MattDHill/listFlash
2. Run "ionic emulate iOS"
3. Click list item in "nav" tab to see navigation flashing.
4. Click list item in "action" tab to see action sheet flashing.

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

It has been very difficult to pin down this bug. I still am not quite certain what exactly is causing the flashing during navigation. To reproduce, the list must **definitely** exceed the viewable screen area, but it's tough to nail down the second part. I _think_ it happens when the target view depends on multiple providers that _also_ depend on providers.
 

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Ionic Framework Version: 2.0.0-beta.8
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.4.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment] 2016-06-13 15:16
Hello, thanks for opening an issue with us! Does this only happen on ios, or on chrome and android too? Thanks for using Ionic!

**Comment by MattDHill** [comment] 2016-06-13 15:35
Hi! I'm not sure if this happens on Andoid emulator or device as I don't have the ability to test that atm. But it works fine in the browser, both Chrome and Safari.

**Comment by F1ow** [comment] 2016-06-13 17:00
Having the same issue on ios but on Android for me.

**Comment by jgw96** [comment] 2016-06-16 15:51
Note: after some testing this seems to be isolated to ios. I cant seem to reproduce on any of my Android devices.

**Comment by danbucholtz** [comment] 2016-06-17 15:12
Hi @MattDHill,

I'm not sure what I'm supposed to be seeing, but here's how it looks on my iPhone.

https://drive.google.com/open?id=0B7Xofj71-_MbM0dONFA3ZUlLcFE

ActionSheet opening looks correct as well.  Note:  I did comment out your getLocation function so it looks like this:

```
getLocation() {
    /*let loading = Loading.create({
      content: 'Loading...'
    });
    this.nav.present(loading);

    this.locationService.getLocation()
      .subscribe(
        data => {
          this.location = data.location
        },
        err => {
          loading.dismiss()
          console.warn(err)
          alert("Error. Please try again later.")
        },
        () => {
          loading.dismiss()
        }
      );
      */
  }
```

**Comment by danbucholtz** [comment] 2016-06-17 15:15
I do see the ActionSheet flashing issue with UIWebView via Cordova.  I don't see it in Safari (WKWebView) so that's good news.  I don't see the Nav flashing issue in either.  I'll get started on the action sheet issue for now.

**Comment by MattDHill** [comment] 2016-06-20 15:56
Hi, thanks for the followup. I have upgraded to Beta 9 and am still experiencing the flashing for (1) the list items (2) the action sheet and also (3) the ion-select component.

Here is a clip of the flashing when clicking on a list item. This is the *exact* same code as before, just with Beta 9 installed.
https://drive.google.com/open?id=0ByUf-mXWw8KcdUFUcFotWmhub2c

I assume the flashing in all three scenarios have the same underlying cause, so solving one will likely solve them all. Thanks again.

**Comment by danbucholtz** [comment] 2016-06-20 16:01
Hi @MattDHill,

Okay cool, I will take a look again.  I must have been doing something differently than you are in the video.

Thanks,
Dan

**Comment by F1ow** [comment] 2016-06-20 16:05
Hi @MattDHill this occurs only if the viewport can scrolling!

**Comment by jgw96** [comment] 2016-06-20 16:06
This seems to be related: https://github.com/driftyco/ionic/issues/6943

**Comment by jgw96** [comment] 2016-06-27 16:26
Hello @MattDHill can you reproduce this with a blank starter with scrolling content? I have been doing some testing on this and cant seem to reproduce on my iphone 5 or any of my Android devices.

**Comment by danbucholtz** [comment] 2016-06-27 17:12
I can definitely reproduce this, @jgw96.

Thanks,
Dan

**Comment by F1ow** [comment] 2016-06-27 17:13
Hi, here we go - follow the readme. 
https://github.com/F1ow/ionic-alert-flicker

happens only on ios devices in my case

**Comment by jgw96** [comment] 2016-06-28 21:02
Hello all! I just did some testing with our latest beta and am glad to report that i only see flashing with the action-sheet component now. I will be closing this issue and opening a new issue focused on the action sheet. I will link that new issue to this issue so that you guys can follow it. Thanks for using Ionic everyone!

**Comment by F1ow** [comment] 2016-06-29 10:06
Hi @jgw96 unfortunately I still have this issue with beta.10! Select and Alert component flicker.

**Comment by jgw96** [comment] 2016-06-29 15:26
@F1ow hmm i will definitely take another look at this. I am going to be testing an overlay component presentation refactor today that has the potential to fix this issue. I will get back to you with my findings. Thanks!

**Comment by jgw96** [comment] 2016-06-29 22:26
@F1ow alright, so after testing that overlay component refactor, i can confirm that this is fixed for good now. I will see if we can get a nightly release out with some directions on how to use the refactored overlay component api's soon so that you can try yourself. Thanks for being patient with me on this!

**Comment by MattDHill** [comment] 2016-09-20 15:09
@jgw96 this flashing suddenly just reappeared on iOS after updating to iOS 10. Action menus, navigating, even clicking a toggle. Please reopen.

**Comment by MattDHill** [comment] 2016-10-03 15:23
Hey guys. @jgw96, @danbucholtz. Any update on this. This flashing is still happening after upgrading to rc0. Happens for (at least) alerts, toggles and page navigation. Can you confirm you are seeing this as well?

**Comment by Chuckv01** [comment] 2016-10-04 21:43
I am seeing the screen flickering happen as on well RC0. Seems to happen 50% of the time.

**Comment by MattDHill** [comment] 2016-10-06 22:03
Hey everyone, it would be great to see this in the RC1 milestones.

**Comment by danbucholtz** [comment] 2016-10-07 17:44
@MattDHill, can you reproduce in RC0?

**Comment by MattDHill** [comment] 2016-10-09 21:08
@danbucholtz sure thing. Here is a repo demonstrating the issue when presenting both loading and alert components. But it also happens with action menus. This re-appreared after the iOS 10 update. Thanks for your help.

https://github.com/MattDHill/ScreenBlink

**Comment by danbucholtz** [comment] 2016-10-10 15:15
@MattDHill, Not sure if this will be RC 1 but I just showed the team videos of the flashing and we agree it is something we need to resolve ASAP.

Thanks,
Dan

**Comment by MattDHill** [comment] 2016-10-10 21:54
Ok thanks. I'll keep my fingers crossed. While this is not a functional issue, it does make some basic actions look very amateur. You guys are awesome.

**Comment by manucorporat** [comment] 2016-10-11 01:34
In the meantime, workaround:
```
IonicModule.forRoot(MyApp,  {
canDisableScroll: false
});
```

**Comment by MattDHill** [comment] 2016-10-11 15:19
Thanks @manucorporat!

**Comment by manucorporat** [comment] 2016-10-20 20:18
This should be fixed in next release RC2! Please feel free to reopen if the problem persist

**Closed by manucorporat** 2016-10-20 20:18 UTC
Labels: needs:devicetesting, platform:ios, v2

**Comment by zefrench** [comment] 2016-10-22 19:26
Thanks @manucorporat!
