### ISSUE TITLE
bug: on-scroll-complete not reliably fired 

### ISSUE THREAD

**Issue by stefanmdt** [driftyco/ionic#3450] opened 2015-04-01 17:07 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>browser</span>

<span ionic-description>I've created a plunker to show the issue: http://plnkr.co/edit/Uplv0wqBStgkQLujjJdN?p=preview

I could reproduce it on iPhone and iPad Safari browser, but on iPhone it was easier. You just have to scroll up and down in different ways. The item text changes for one second when the handler is called. Sometimes the scrollbar does not disappear and the event is not fired. </span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-04-01 17:07
Greetings @stefanmdt!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3450). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3450)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment] 2015-04-01 20:30
I'm having trouble reproducing this. Is it possible the scrolling didn't come to a complete stop before you started again? iOS has a _very_ slow scroll decay rate.

**Comment by stefanmdt** [comment] 2015-04-02 07:54
I'll try to record a screencast and find out how to reproduce it more reliable ...

**Comment by stefanmdt** [comment] 2015-04-02 08:07
Here is the screencast directly from iPhone 5: https://www.dropbox.com/s/fyvucv7tg4ki1da/on-scroll-complete.mov?dl=0

**Comment by daco** [comment] 2015-04-17 11:24
I've got the same problem. Sometimes (1 in 20 or so) the event is not fired. In ios 8.

**Comment by MoeHadla** [comment] 2015-04-25 14:30
Device: iphone (ios)

I am going to add some further information to possibly get us closer to the issue here.

I have a bug that I presume relates to this issue (instead of me going ahead and opening another issue)

Try this:

- Add 2 ion-contents of 50% width (width does not matter as long as they are next to each other).
Note: Give them some decent hi=eight for finger scroll space.

- Add items inside an on-scroll-complete functions for each. (Just log something or change text as above)

- start scrolling on one of the ion-contents downwards and in the direction of the other scroll. Let your finger exit the first content to the second one.

If done correctly, you should notice that the on-scroll-complete of the first scroll did not fire at all.

I need help with this issue please.

Thanks.

**Comment by bodinaren** [comment] 2015-07-09 09:51
I'd like to add to this issue as I just ran into this on Android as well (and browser). It's unreliable, but I found it quite easy to reproduce. I've made this most simple of codepen: http://codepen.io/bodinaren/pen/ZGoWKE

The most reliable way I found to reproduce the bug is by scrolling from and past the content edges (e.g. be on top and keep scrolling up). Preferable you should scroll fast (click/touch, move, release in quick succession).

It seems to me to be limited to when there's no "smooth scrolling" effect (keeps scrolling after release).

**Comment by stefankp** [comment] 2015-07-24 09:01
I encountered the same bug on iOS (iPhone and simulator).

The `on-scroll-complete` event is not triggered every time the scrolling is complete (at least visually). This also means that the scrollbar does not fade out.

**Comment by tusharbhatta** [comment] 2015-11-16 14:07
I'm facing same issue on android lollipop. Any update on this please?

**Comment by toostn** [comment] 2016-01-01 16:10
I also had issues with on-scroll-complete not being triggered and nailed down the issue to `scrollView.js:2042` where a check is made if the velocity is high enough to result in deceleration. There was no else-block if this condition isn't true. When I added a call to `self.__scrollingComplete();` if the deceleration check fails, everything works as expected.

I haven't yet found any unwanted effects caused by this change, but since the doTouchEnd function is very complex I think it would be great if the original author had a look at this solution.

Line 2035-2053 of my patched `scrollView.js` (2045-2047 added by me):
```
2035           // How much velocity is required to start the deceleration
2036           var minVelocityToStartDeceleration = self.options.paging || self.options.snapping ? self.options.decelVelocityThresholdPaging : self.options.decelVelocityThre     shold;
2037
2038           // Verify that we have enough velocity to start deceleration
2039           if (Math.abs(self.__decelerationVelocityX) > minVelocityToStartDeceleration || Math.abs(self.__decelerationVelocityY) > minVelocityToStartDeceleration) {
2040
2041             // Deactivate pull-to-refresh when decelerating
2042             if (!self.__refreshActive) {
2043               self.__startDeceleration(timeStamp);
2044             }
2045           } else {
2046             self.__scrollingComplete();
2047           }
2048         } else {
2049           self.__scrollingComplete();
2050         }
2051       } else if ((timeStamp - self.__lastTouchMove) > 100) {
2052         self.__scrollingComplete();
2053       }
```

**Comment by toostn** [comment] 2016-01-01 16:15
Also, the easiest way to reproduce the issue is to scrub the scrollable content shortly up and down, like you were trying to get rid of a stain on the glass of the phone. It is pretty hard to trigger when using a mouse.

**Comment by rolandoldengarm** [comment] 2016-01-19 02:33
On Android, the event never fires at all. The onScroll event fires without a problem, but the onScrollComplete event never does fire.

**Comment by lucasbeef** [comment] 2016-01-24 14:02
+1 : it also never fires for me on Android

**Comment by bodinaren** [comment] 2016-01-24 15:47
I'm just guessing here, but I believe this event will not fire on Android anymore when you're using native scrolling, which is default since version 1.2.0. Does this match your experiences?

**Comment by lucasbeef** [comment] 2016-01-24 19:50
Yes, I'm using native scrolling

**Comment by blefebvre** [comment] 2016-02-27 05:03
I am able to reliably reproduce this issue when I set `overflow-scroll="true"` on `ion-content`. To demonstrate, I put together a small app based on the blank template to alert the value of `scrollTop` when `on-scroll-complete` fires. With overflow-scroll="false":
![overflow-scroll_false](https://cloud.githubusercontent.com/assets/1048207/13370857/a7af3fc6-dce3-11e5-9d80-467152c42f01.gif)
Observe how the popup no longer appears when overflow-scroll="true":
![overflow-scroll_true](https://cloud.githubusercontent.com/assets/1048207/13370864/fe6f1d40-dce3-11e5-8532-698fd5bfbae7.gif)

You can reproduce this issue with the following app: https://github.com/blefebvre/ion-content-scroll-issue/

**Comment by jgw96** [comment] 2016-04-27 18:39
Hello all! Are you all still having this issue with the latest version of ionic? 1.3.0

**Comment by jgw96** [comment] 2016-05-02 16:14
Hello! Since it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if your still having this issue though!

**Closed by jgw96** 2016-05-02 16:14 UTC
Labels: needs reply, platform:ios, scroll, v1

**Comment by dongdh** [comment] 2016-05-06 13:30
Well, not working on android Samsung 6s with latest ionic 1.3.0. event is not triggered att all for android native scrolling, have to set jsscroll to true.

**Comment by cozzbie** [comment] 2016-07-26 09:05
Still doesn't trigger... ionic 1.7.16

**Comment by panlina** [comment] 2017-04-04 10:04
The issue still exists. And I think [@toostn 's comment](https://github.com/driftyco/ionic/issues/3450#issuecomment-168314410) is convincing. After looking into the source, I'm quite sure that the author just forget to call scroll complete handler when touch ends with a low velocity.
Can the team take a look?
