### ISSUE TITLE
Strange problem with popover doesn't open on Android after update to Ionic 2.0.0-rc.5

### ISSUE THREAD

**Issue by pdrosos** [driftyco/ionic#10014] opened 2017-01-13 06:40 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[2] **2.0.0-rc.5

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I have a strange problem with popover since I upgraded to ionic 2 rc.5. Problem is on Android 6 and 7 only, it seems it doesn't affect iOS 10.1.1. It's hard to reproduce outside my app, so will explain it as good as I can. 

I have a standard button inside ion-header, which opens popover menu:
```
<ion-header>
    <ion-navbar>
        <ion-title text-center>
            Some Page
        </ion-title>

        <ion-buttons end>
            <button ion-button icon-only (click)="presentPopoverMenuClick($event)">
                <ion-icon name="more"></ion-icon>
            </button>
        </ion-buttons>
    </ion-navbar>
</ion-header>
```
Nothing special in the popover page too:
```
<ion-list inset>
    <ion-item>
        <a (click)="onSettingsClick()">
            <ion-icon name="settings"></ion-icon>
            Settings
        </a>
    </ion-item>
    <ion-item>
        <a (click)="onLogoutClick()">
            <ion-icon name="icon-clear"></ion-icon>
            Logout
        </a>
    </ion-item>
</ion-list>
```
When I install the app, open it and immediately click on the button, which must open the popover menu, it's not opened.
I have put a console.log(); inside the `presentPopoverMenuClick` function and noticed that the click event is fired very slowly (after 4-5 sec), popover object is created, but popover never shows. 
Also click is not always fired, some clicks just do not trigger it.

I have such popover menu on all pages and it's not opened from anywhere. But if I open the app, wait for around 10 seconds and click on the button, popover appears and starts appearing everywhere and even after app restart... If I click immediately and popover doesn't open, the waiting time doesn't help, it continues to not open anywhere since I restart the app and wait these seconds. After that on next restarts it opens normally again.
Any idea how is that possible and what can cause it? Everything was fine with Ionic 2.0.0-rc.4. 

I commented everything in the page where I test - and left only the header and empty ion-content. Still happens, this waiting time is probably a little less, but problem is definitely there. 
I could debug more, please someone gives me more ideas how.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.5-201701121905
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: macOS Sierra
Node Version: v7.1.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by ThorConzales** [comment] 2017-01-13 11:52
I have similar problem on Android but before the keyboard is opened it works as intended but once the keyboard has been opened popover is not being popped any longer.

**Comment by sebestenyb** [comment] 2017-01-16 21:48
Have a similar issue with RC5.
Popover doesn't show up at all on the device.
It works in the browser.
If I remote debug it, the popover is in the DOM, but it's invisible, looks like the content has zero height and width.
Downgrading to RC4 works.

Cheers, Sebi

**Comment by pe1o2pl** [comment] 2017-01-17 13:39
Exactly the same problem with RC5 as @ThorConzales, in the browser everything works fine, on Android after using keyboard popover stopped showing at all

**Comment by pwespi** [comment] 2017-01-17 23:38
I have the same problem as @ThorConzales and @pe1o2pl that the popover doesn't show after using the keyboard on Android with RC5. Actually the popover does open, but its position is wrong so that it is outside of the viewable area. It probably has something to do with the changes made to popover-transitions.ts between RC4 and RC5.

**Comment by unfg** [comment] 2017-01-18 11:39
i have the same problem.

**Comment by tmzblue** [comment] 2017-01-19 01:26
We're targeting all platforms and we noticed this bug after upgrading to RC5, specially on android/desktop browsers.
On android, popovers will stop working if the software keyboard is called by any input in the page (like @ThorConzales mentioned).
On desktop browsers if you open a popover, close it, then resize the window (minimizing/manipulating the window size), subsequent popovers will start showing in weird/wrong positions (but still visible, sometimes clipped).
It's worth mentioning this issue is likely to be linked to the window:resize event.

**Comment by themastersoda** [comment] 2017-01-20 12:30
@tmzblue is right, popover only appears while there was no keyboard open. Once it has been opened, popover stops working on android. And since keyboard open action triggers window resize, it must be related to coordinates resetting or something similar.

**Comment by itrethan** [comment] 2017-01-22 00:35
I am surprised this is not a part of RC6 fix, this bug is a user facing issue. People are using popover for entry menu of features. I think it deserve to be fixed in next release.

**Comment by pe1o2pl** [comment] 2017-01-23 11:25
Too bad this bug won't be fixed in next release, fingers crossed it will. Temporary I have changed css style for my popovers adding this:

```
.popover-temporary-common {
  .popover-content {
    position:static;
  }
}
```
All popovers appear in the middle of the screen

**Comment by themastersoda** [comment] 2017-01-23 11:45
Where have you seen stated that this won't be fixed in RC6? Do tickets get selected for upcoming versions or something?

**Comment by YasirPanjsheri** [comment] 2017-01-23 11:52
where can I check the issues that are assigned to be fixed in RC6 ??

**Comment by pwespi** [comment] 2017-01-23 22:03
Apparently the underlying bug is the same as in #9727, which is a RC6 milestone, so it probably will be fixed.
RC6 milestones can be found here: https://github.com/driftyco/ionic/milestone/48.
Some temporary solutions are also being discussed in #10055.

**Comment by brandyscarney** [comment] 2017-01-24 19:39
This will be fixed in the next release, please install the latest nightly if you'd like to try it out sooner:

```
npm install --save --save-exact ionic-angular@nightly
```

**Closed by brandyscarney** 2017-01-24 19:39 UTC
Labels: v2
