### ISSUE TITLE
ion-content does not move when header height changes

### ISSUE THREAD

**Issue by zmbc** [driftyco/ionic#7780] opened 2016-08-18 22:14 UTC
#### Short description of the problem:

When the height of the header shrinks (for example, because something in it has an `*ngIf`), the ion-content stays in the same place, leaving a gap between header and content. Conversely, when it grows, it can cover content.

#### What behavior are you expecting?

I would expect the content of the page to move down/up so it is always right under the header.

**Steps to reproduce:**
1. Make any header that can change size dynamically.
2. Put content in an ion-content.
3. Change size of header.

**Which Ionic Version?**

Ionic 2.0.0-beta.11

#### Plunker that shows an example of your issue
http://plnkr.co/edit/FsDZV9KTtise1HQ5FsU7?p=preview

**Comment by jgw96** [comment] 2016-08-19 08:07
Hello! Thanks for opening an issue with us! I am going to be closing this issue as a duplicate of https://github.com/driftyco/ionic/issues/7706. Thanks for using Ionic!

**Closed by jgw96** 2016-08-19 08:07 UTC
Labels: header, v2
