### ISSUE TITLE
bug: enable-menu-with-back-views="true" goes back and opens menu

### ISSUE THREAD

**Issue by wilsonhobbs** [driftyco/ionic#4180] opened 2015-08-03 16:38 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>While using `enable-menu-with-back-views="true"` I have found that swiping back to the previous state both opens the side menu and goes to the previous state. This could be fixed by seeing the start position of the swipe, and if it starts fairly close to the edge, it goes back and if it starts in the middle-ish it will open the menu.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-08-03 16:38
Greetings @wilsonhobbs!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4180). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4180)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment] 2015-08-13 15:48
Confirmed. Temporary fix is to either disable swipe to go back, or set `enable-menu-with-back-views` to false.

**Comment by Ionitron** [comment] 2015-11-11 19:25
Greetings @wilsonhobbs!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-11-11 19:25 UTC
Labels: ionitron:closed
