### ISSUE TITLE
Ionic 2: White screen of death when calling nav.setRoot() from app.module.ts

### ISSUE THREAD

**Issue by daveshirman** [driftyco/ionic#10297] opened 2017-02-03 09:59 UTC
**Ionic version:**  (check one with "x")
[2] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
Call `nav.SetRoot()` from app.module.ts, white screen of death, see gif.

**Expected behavior:**
Normal navigation occurs

**Steps to reproduce:**
This is a well known bug that keeps being closed/marked as fixed.  This is NOT fixed.  It is a critical problem in the nav code of the framework.

This really needs to be addressed before apps can be deemed production ready.

See gif:

![f49337e8-e8ae-11e6-9ccc-df77e93abd7b](https://cloud.githubusercontent.com/assets/14280030/22586924/33e409a6-e9f7-11e6-972e-c2dcdfa1c428.gif)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: OS X El Capitan
Node Version: v4.3.0
Xcode version: Xcode 8.1 Build version 8B62```

**Comment by jgw96** [comment] 2017-02-03 15:21
Hello, thanks for using Ionic! Sorry your having this issue, would you be able to post a repo or a plunker that we can use to reproduce this?

**Comment by daveshirman** [comment] 2017-02-03 16:37
Here's a plunkr:

http://plnkr.co/edit/fYpX4KikzWFRo7repnkG?p=preview

But it doesn't happen on rc2, which the plunkr is based on.

The gif above is from ionic serve on 2.0.0

**Comment by lumitor2** [comment] 2017-02-06 17:11
Hello, I have same problem with 2.0.0 version.
I go through nav.canGoBack() and after nav.pop() there is only blank screen.

**Comment by daveshirman** [comment] 2017-02-06 19:34
Update: I have found the issue.  There is a situation where calling `setRoot()`, THEN calling `popToRoot()` causes the white screen.

Commenting out the `popToRoot()` and just using `setRoot()` fixes this issue.

Is this expected behaviour?

**Comment by lumitor2** [comment] 2017-02-07 08:56
I have white screen after `setRoot()` and simply `pop()` afterwards..

**Comment by jgw96** [comment] 2017-02-09 21:57
Hello @daveshirman , thanks for updating the plunker and sorry it has taken me a few days to get back to you (: So yeah, this is going to be whats causing the issue. In this case when you run `setRoot` it will go ahead and navigate your app to the root page. With you calling `popToRoot` right after this it breaks the nav stack. Because this was user error I am going to close this for now.

**Closed by jgw96** 2017-02-09 21:57 UTC
Labels: needs:devicetesting, v2

**Comment by lumitor2** [comment] 2017-02-09 22:00
But I have white screen after `setRoot()` -> `push()` -> `pop()`. I think, that there is a bug..

**Comment by daveshirman** [comment] 2017-02-10 09:15
@jgw96 I don't think it should be possible for popToRoot() to pop ALL the pages off the stack, that's ludicrous!

See @lumitor2 's issue too, which is clearly related.
