### ISSUE TITLE
Button click firing twice iOS

### ISSUE THREAD

**Issue by danielflippance** [driftyco/ionic#11367] opened 2017-04-26 07:08 UTC
I'm seeing a similar issue to https://github.com/driftyco/ionic/issues/10520 and https://github.com/driftyco/ionic/issues/5127. As requested I have created a git repo with a working app that reproduces the error. The repo also has 2 videos showing the issue in use.
https://github.com/danielflippance/ionic2-button-issue

**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
See https://github.com/danielflippance/ionic2-button-issue

**Steps to Reproduce**

See Video 1 in the repo:

- The app has one button which when clicked will show an alert
- Click the button and click to close the alert
- Then click the button again
- The alert is shown a first time. Click to close it
- The alert is shown a second time.

Please note that after clicking the button the first time and closing the alert, if you click anywhere else on the app except for on the button, the alert is again shown, but this time only once - See Video 2 in the repo:

- Click the button and click to close the alert
- Then click anywhere EXCEPT on the button
- The alert is shown again even though the button was not clicked.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
$ ionic info

Your system information:

Cordova CLI: 6.5.0 
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: OS X El Capitan
Node Version: v4.5.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by chandanch** [comment] 2017-04-26 08:53
I was not able to reproduce this issue on iOS 9.3 and iOS 10.3.1. 
Can you upgrade to **3.0.1** and see if the issue still persist?

**Comment by sunilkconsultant** [comment] 2017-04-26 09:50
@chandanch - npm install -g ionic@latest is not upgrading to ionic 3.0.1 how did you manage to please share? I can reproduce the same issue, with below config:

Cordova CLI: 6.5.0 
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: macOS Sierra
Node Version: v6.10.1
Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by astec** [comment] 2017-04-26 14:11
@sunilkconsultant update you `package.json` and run `npm install`.

**Comment by danielflippance** [comment] 2017-04-26 17:40
I upgraded to Ionic 3 following the Steps to Upgrade for 3.0.0 and 3.1.0 listed [here](https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#steps-to-upgrade), deleted node_modules and ran `npm install` and `npm update` but am still seeing the same issue. iPad iOS is 10.2.1

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 3.1.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.4
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: OS X El Capitan
Node Version: v4.5.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

package.json is now:

```
{
  "name": "company-mobile-app",
  "author": "Company",
  "homepage": "http://www.company.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "4.0.2",
    "@angular/compiler": "4.0.2",
    "@angular/compiler-cli": "4.0.2",
    "@angular/core": "4.0.2",
    "@angular/forms": "4.0.2",
    "@angular/http": "4.0.2",
    "@angular/platform-browser": "4.0.2",
    "@angular/platform-browser-dynamic": "4.0.2",
    "@angular/platform-server": "4.0.2",
    "@ionic-native/core": "3.4.2",
    "@ionic/storage": "2.0.1",
    "compare-versions": "^3.0.0",
    "ionic-angular": "3.1.0",
    "ionic-native": "^2.9.0",
    "ionicons": "3.0.0",
    "portfinder": "^1.0.13",
    "reflect-metadata": "^0.1.10",
    "rxjs": "5.1.1",
    "setimmediate": "^1.0.5",
    "sw-toolbox": "3.4.0",
    "zone.js": "^0.8.5"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.3.4",
    "rollup-plugin-replace": "^1.1.1",
    "typescript": "~2.2.1"
  },
  "cordovaPlugins": [
    "cordova-plugin-whitelist",
    "cordova-plugin-console"
  ],
  "cordovaPlatforms": [
    "ios",
    {
      "platform": "ios",
      "version": "",
      "locator": "ios"
    }
  ],
  "description": "Company Mobile App",
  "config": {
    "ionic_rollup": "./config/rollup.config.js"
  }
}
```

**Comment by chandanch** [comment] 2017-04-28 08:22
@sunilkconsultant Does the issue still persist?

**Comment by danielflippance** [comment] 2017-04-28 17:21
Yes it does persist. I'm currently in the process of trying with Node v6.10.0

**Comment by jgw96** [comment] 2017-05-04 15:21
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-05-04 15:21 UTC
Labels: needs info, v2

**Comment by danielflippance** [comment] 2017-05-04 17:39
I'm still seeing the double firing, however the app is handling the bug gracefully so I have not investigated it further. It is still happening for sure though.
