### ISSUE TITLE
[RC1] [ionic2] Click event not getting triggered if its in a *ngIf condition

### ISSUE THREAD

**Issue by marutifh** [driftyco/ionic#8892] opened 2016-10-25 08:27 UTC
Hi,

If I am biding a click event to an element which is under a if condition in DOM, the events associated with same element are not getting triggered in Android devices, same thing works fine in iOS devices. I have a created a sample git repo to reproduce the same. Please check the `home.htm`l and `home.ts` for the code.
sample code : 

home.html

```
      <ion-searchbar placeholder="Search" [(ngModel)]="myInput" (ionInput)="search($event)" (ionBlur)="onBlur($event)" (ionCancel)="onCancel($event)"> </ion-searchbar>
      <ion-list *ngIf="!isSearchOn">
        <ion-item *ngFor="let emp of selectedEmployees">
            <p>{{emp}}</p>
        </ion-item>
      </ion-list>
      <ion-list *ngIf="isSearchOn">
        <ion-item *ngFor="let emp of employees" tappable (click)="itemTapped($event, emp)">
            <p>{{emp}}</p>
        </ion-item>
      </ion-list>
```

home.ts

```
    import { Component } from '@angular/core';

    import { NavController } from 'ionic-angular';

    @Component({
      selector: 'page-home',
      templateUrl: 'home.html'
    })
    export class HomePage {
      public selectedEmployees: any = [];
      public employees: any = [];
      public isSearchOn: any = false;
      public myInput:any ="";
      constructor(public navCtrl: NavController) {
          this.selectedEmployees = [];
          this.employees = ["dummy","care","me","try","we"];
      }
      search(event) {
        let q = this.myInput;
        if (q.trim() == '') {
          this.isSearchOn = false;
          return;
        }
        this.isSearchOn = true;
      }
      onCancel(event) {
        this.isSearchOn = false;
      }
      onBlur(event) {
        this.myInput = "";
        this.isSearchOn = false;

      }
      itemTapped(event, employee) {
        debugger
        this.selectedEmployees.push(employee);
        this.isSearchOn = false;
        console.log(employee);
      }
    }
```

itemTapped event is never getting called!
Sorry if its confusing!
[GIT LINK](https://github.com/marutifh/sampleApp)

**Comment by jgw96** [comment] 2016-10-25 19:11
Hello, thanks for using Ionic! Unfortunately I cannot reproduce this issue on any of my Android devices. Which version of Android are you testing with?

**Comment by marutifh** [comment] 2016-10-25 19:21
I tested this with Android 4.4.4, 5.1.1, 6.0.1 versions, if needed I can post a video as well!

**Comment by jgw96** [comment] 2016-10-27 18:51
Hmm, I am testing with 5.1.1, 6.0.1 and 7.0 and it seems to be working great for me. A video might help!

**Comment by jgw96** [comment] 2016-10-31 21:17
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-10-31 21:17 UTC
Labels: needs reply, v2
