### ISSUE TITLE
ionic back and broswer back have different behaviors

### ISSUE THREAD

**Issue by izee** [driftyco/ionic#11629] opened 2017-05-12 10:04 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[ x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**
1.enable deep link
2.transition back to a page by ionic back button and browser back button respectively.
3.watch the page's constructor and ionViewDidLoad
4.ionic back execute constructor and ionViewDidLoad once time.
5.browser back execute constructor and ionViewDidLoad everytime.

**Comment by jgw96** [comment] 2017-05-12 14:28
Thanks for opening an issue with us, we will look into this.

**Comment by shawnlan** [comment] 2017-05-17 01:15
I think it is related to https://github.com/driftyco/ionic/issues/11698.

**Comment by jgw96** [comment] 2017-05-18 15:45
Hello, thanks for opening an issue with us. I am going to close this as a duplicate of https://github.com/driftyco/ionic/issues/11698.

**Closed by jgw96** 2017-05-18 15:45 UTC
Labels: v2
