### ISSUE TITLE
bug: iOSswipe cause white screen with actionsheet back

### ISSUE THREAD

**Issue by alexcywu** [driftyco/ionic#3253] opened 2015-03-08 05:22 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>After using actionsheet to go to the new state, using the new "iOS swipe to go back" will cause white screen.</span>

<span is-issue-template></span>

**Comment by sebvst** [comment] 2015-03-08 10:42
There is a similar behavior when you swipe to go back and have caching disabled.

**Comment by hanford** [comment] 2015-03-09 21:32
+1

**Comment by Ionitron** [comment] 2015-03-11 04:02
Greetings @alexcywu!

My sensors indicate that I require more information in order to assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this happen occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com), where many humans will be able to offer wisdom and advice.

Thank you for allowing me to assist you.

<span ionitron-needs-reply></span>

**Comment by Ionitron** [comment] 2015-04-10 04:40
Greetings @alexcywu!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment] 2015-04-10 04:40
Greetings @alexcywu!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-04-10 04:40 UTC
Labels: ionitron:closed
