### ISSUE TITLE
bug: Text input requires one more tap to get soft keyboard on Android v4.4 Ionic v1.3.16 (Intermitent)

### ISSUE THREAD

**Issue by ParitoshVaidya** [driftyco/ionic#3377] opened 2015-03-23 09:58 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>Getting this issue on Moto e (1st Gen.) Android 4.4 Ionic v 1.3.16 Will let you know about other devices. This issue occurs if last input is directly selected for edit purpose. Having same issue on two different forms.  </span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-03-23 09:58
Greetings @ParitoshVaidya!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3377). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3377)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by ParitoshVaidya** [comment] 2015-03-23 10:32
Having same issue on Samsung Galaxy Grand Android v4.2.2, Samsung Trend Android v4.1.2

**Comment by Ionitron** [comment] 2015-03-24 17:44
Greetings @ParitoshVaidya!

My sensors indicate that I require more information in order to assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this happen occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com), where many humans will be able to offer wisdom and advice.

Thank you for allowing me to assist you.

<span ionitron-needs-reply></span>

**Comment by ParitoshVaidya** [comment] 2015-03-25 08:29
This is intermittent behavior, occurs for last field on the form. One in the following (or multiple) issue(s) occurs most of the times.

Input field does not get focus on first tap. I require to tap on it once again.
Input field does not update while typing. If tapped once again, typed text gets displayed.
Input field hides behind soft keyboard. After starting typing it becomes visible with 2nd issue.
Any idea why this is happening? I added these issues to github as well.

Also found that these issues were on github, and are closed an year before.

I am able to reproduce the issue on Moto e (1st Gen.) Android v4.4, Samsung Galaxy Grand Android v4.2.2, Samsung Trend Android v4.1.2

**Comment by perrygovier** [comment] 2015-05-20 22:29
Is this any input? Could you share a sample project, just so we're looking at the same thing?

**Comment by Ionitron** [comment] 2015-06-20 08:28
Greetings @ParitoshVaidya!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment] 2015-06-20 08:28
Greetings @ParitoshVaidya!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-06-20 08:28 UTC
Labels: ionitron:closed
