### ISSUE TITLE
Transition of navbar back button not working

### ISSUE THREAD

**Issue by olixis** [driftyco/ionic#10097] opened 2017-01-19 05:40 UTC
**Ionic version:**
[ ] 1.x
**[x] 2.x RC5**

**[x] bug report**
[ ] feature request
[ ] support request 

**Current behavior:**

There is no transition ocurring after pressing the navbar back button, or a custom "pop" button or the native hardware back button on the android phone.

**It works with 'ionic serve' but not when 'ran as an apk'**

**Expected behavior:**
It should make a transition back to the last page on the navcontroller stack.

**Steps to reproduce:**
Click on the navbar back button in 'native mode'

**Related code:**

```
      <ion-navbar hideBackButton="true">
        <button (click)="back()" ion-button icon-left clear small>
        <ion-icon name="arrow-back"></ion-icon>
        <div> Voltar</div>
        </button>
      </ion-navbar>

----
    public back = (url) => this.navCtrl.pop();
```

**Other information:**
![ezgif com-resize](https://cloud.githubusercontent.com/assets/7017544/22094929/407ceee0-ddf8-11e6-82e6-bb3861d607e9.gif)

Zenfone 2

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.4.0
Xcode version: Not installed
```

**Comment by jgw96** [comment] 2017-01-19 15:51
Hello, thanks for using Ionic! Unfortunately I cannot reproduce this issue on any of my devices. Would you mind posting a plunker or a repo we can use to reproduce this?

**Comment by olixis** [comment] 2017-01-19 17:05
Sure, https://github.com/olixis/varacast

**Comment by mhartington** [comment] 2017-01-19 21:05
Looked at your code, you header markup was off a bit. Try this.

```
<ion-header>

  <ion-navbar hideBackButton="true">
    <ion-buttons left>
      <button (click)="back()" ion-button icon-left clear small>
    <ion-icon name="arrow-back"></ion-icon>
    </button>
    </ion-buttons>
    <ion-title> Voltar</ion-title>
  </ion-navbar>

</ion-header>
```

**Comment by olixis** [comment] 2017-01-20 04:24
> Looked at your code, you header markup was off a bit. Try this.

Did not work, same behavior :(

**Comment by olixis** [comment] 2017-01-20 04:25
Maybe it's because it is the only screen on the stack of the navctrl and when it is popped it goes to the rootpage, but it should animate, shouldn't it ?

**Comment by mhartington** [comment] 2017-01-20 15:05
It appears to be animating fine with the modification I have made to the the header.

![issue-10097](https://cloud.githubusercontent.com/assets/2835826/22153994/b1e914b4-def7-11e6-9b42-3fbbdeed0ccf.gif)


Modifying the animation for push is fine, but if it's on android, it's doing the correct animation for the platform.

**Comment by olixis** [comment] 2017-01-20 19:08
Did you use a emulator or a physical device? what android version? Still not woking here :(... Did you do any other change?

**Comment by mhartington** [comment] 2017-01-20 19:51
Both emulated and real device.
Clear node_modules, `npm install` again.
Maybe there's a glitch. 
Going to close this for now since I'm not able to replicate.

**Closed by mhartington** 2017-01-20 19:51 UTC
Labels: needs reply, v2

**Comment by olixis** [comment] 2017-01-20 23:10
Other prople having the same problem, please consider re-opening : 

https://forum.ionicframework.com/t/how-to-set-page-transition-of-navbar-back-button/57178/8
