### ISSUE TITLE
bug: Cannot use gestures on ionic directives

### ISSUE THREAD

**Issue by Zorgatone** [driftyco/ionic#3390] opened 2015-03-24 12:11 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Events like on-hold won't trigger on ionic directives like ion-tab, ion-list etc..
Tested on Ionic version 1.0.0-beta.14
```
<ion-tabs>
    <ion-tab on-hold="onHold()">
    </ion-tab>
</ion-tabs>
```
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-03-24 12:11
Greetings @Zorgatone!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3390). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3390)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment] 2015-03-24 15:51
Gestures do work on most directives
http://codepen.io/shprink/pen/txliu?editors=101

Tabs are special though. You can put a gesture on `<ion-tabs>` but since they contain the view as well, everything will get a gesture listener.  Individual `<ion-tab>`s are actually not displayed, there's some DOM manipulation that goes on, so you'll want to add listeners to the individual `.tab-item` elements after the template is parsed and linked.

Let me know if you can reproduce this in an element other than `<ion-tab>`

**Comment by Fayozjon** [comment] 2015-03-24 17:00
Zorgatone

http://medgorodok.org.ua/dragon-mmcis

24.03.2015, 15:11, "Zorgatone" <notifications@github.com>:Events like on-hold won't trigger on ionic directives like ion-tab etc..

<ion-tabs>
    <ion-tab on-hold="onHold()">
    </ion-tab>
</ion-tabs>

**Comment by Zorgatone** [comment] 2015-03-25 09:12
No I haven't found other elements with the issue but looking over the net I saw some guys that had similar issues with ion-item.
If feels so odd that the ng-click works on the tab correctly.
I understand the ion-tab behaviour now, I guess I'm forced to assign the event manually.

**Comment by mnewmedia** [comment] 2015-06-10 14:00
For me ´$ionicGestures´ only works in a directive if i manually refresh the page where it's being used. Or if i add ´$ionicGestures´ as a dependecy to the controller even it's already as a dependency in the directive.

**Comment by Ionitron** [comment] 2015-09-08 16:27
Greetings @Zorgatone!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-09-08 16:27 UTC
Labels: ionitron:closed, tabs
