### ISSUE TITLE
ion-backdrop - App-Freeze Modal + Loading

### ISSUE THREAD

**Issue by nickwinger** [driftyco/ionic#7699] opened 2016-08-13 12:07 UTC
Hi,

i'm sorry to say that in beta 11 there are still issues with the modals (transitions i guess).
My app shows a Loading with every ajax request. Now it often happens, that when there is another Modal open, e.g. Alert, and the Loading appears/disappears that the App freezes. No more clicking can be done.
That's because the ion-backdrop is overlaying everything including the Alert, so the OK-Button cannot be clicked. For the user it looks like the App freezes.
The ion-backdrop is surrounded by the ion-loading, but the Loading spinner is not visible anymore.
There is just the Alert-Modal which cannot be closed anymore.
The ion-alert also has a ion-backdrop inside.
Somehow the loading and it's ion-backdrop are not removed.
Even if i manually delete the ion-loading from the DOM, the Alert does not close anymore clicking the dismiss button. Seems like something inside the framework is stuck.

For me this is a major issue.
I still cannot use the Loading with Ajax-Calls because the whole app has to be closed and re-opened when this thing with another Modal happens.

**Comment by jgw96** [comment] 2016-08-14 05:26
Hello! Thanks for opening an issue with us! Would you mind checking your console for any errors? This sounds very similar to a different issue that has already been fixed and will be in the beta.12 release. Thanks for using Ionic!

**Comment by nickwinger** [comment] 2016-08-14 08:28
Hello.
@jgw96 there is no error or exception in the console.
I also would love to make a Plunker so you can see it, but there is no Plunker for beta 11.
Can you share a Plunker-Template for beta 11 ?

**Comment by gustavohenke** [comment] 2016-08-15 03:23
Hi everyone,
I'm not sure if my problem is the same as yours... I create a loading while some request executes in the background. When the request finishes, I show an alert. Then I can't close the alert anymore without reloading the app.

**Comment by nickwinger** [comment] 2016-08-15 07:01
A quicknote: If i do setTimeout(() => modal.present(), 500); it works, but this is hacky.
There is a timing (transition?) issue closing/opening modals (e.g. Loading / Alert).

**Comment by jgw96** [comment] 2016-08-15 14:40
@nickwinger Hey! Unfortunately because of an ongoing issue with npmcdn i am not able to provide a beta.11 plunker at this time, but if you could share a repo that shows a minimal example of the issue that would be great. Thanks for using Ionic!

**Comment by nickwinger** [comment] 2016-08-15 16:09
@jgw96 i have made a sample i could upload but the code is not much, i can post here:
`let loading = this.loadingCtrl.create({
      content: 'Communicating with Server'
    });
    loading.present();

    setTimeout(() => {
      let alert = this.alertCtrl.create({
        title: 'Opened before loading got dismissed',
        message: 'When loading gets dismissed you cannot click/close me',
        buttons: [
          {
            text: 'Close',
            handler: () => {
              alert.dismiss();
            }
          }]
      });
      alert.present();
    }, 500);

    // Simulate ajax call
    setTimeout(() => {
      loading.dismiss();
    }, 1000);`

You have to wait at least one second. When the loading dismisses you cannot close the alert.

**Comment by jgw96** [comment] 2016-08-15 18:31
Hello @nickwinger ! Thanks for the code sample, helps me understand the exact issue before i give a wrong solution 😄 . So the issue here is that you have a loading component and an alert component open at the same time. Our overlay components work much like the native android and ios sdk's handle overlay components (and they will be even more similar with coming updates) in that you should not have multiple overlay components open at the same time. The solution here would be do your loading first, dismiss the loading component, and then open the alert, or the other way around. Thanks for using Ionic!

**Comment by nickwinger** [comment] 2016-08-15 18:48
@jgw96 
The Code i provided was not a real world example.
The real world example would be that i have 2 Ajax-Calls. The first one automatically opens an Alert and does not know that there is a second one.
There are also other issues i will try to reproduce not only this one.
As i said in the beginning, the Problem is that the ion-backdrop INSIDE the closed loading does not get dismissed.
In my opinion this is a bug.
How would i know if a loading is open ? I think the alert.present method should know it and not create an inconsistent state of the app where nothing works anymore.
Is there a method "isAModalOpen()" with a promise so i know when to open the Alert. As said already the Alert gets opened from another Logic that does not know anything about a Loading.

I cannot understand why you closed this major issue and i'm sorry about that...
I know that developers don't like bugs, but closing them so soon is not productive.

**Comment by jgw96** [comment] 2016-08-15 19:00
Hello! Thanks for the info and I am sorry you were not happy with me closing the issue! So the issue with the messed up backdrop is actually caused by trying to open two overlay components at the same time, which we do not support. When the transition runs to close the loading component it does not complete successfully, which means that the backdrop never animates away. Also, we definitely understand that you should not be able to create a "broken" state in the app by presenting two overlay components at the same time. Because of this, as one of the updates i mentioned above we are currently working on changing our overlay components to work as a "queue" where if your present multiple overlay components at the same time the last one you presented will show first, and then it will work down the list. This is exactly how ios and android handle overlay's and should make it impossible to run into this broken state again. Hope this explains everything better!

**Comment by nickwinger** [comment] 2016-08-15 19:08
@jgw96 Thanks for clearing this up. I hope the new system will work the way i use it.
I run into this problem all the time. As i mentioned, i heavily use the Loading for all Ajax calls, so the user does know someting is going on and does not click multiple times on a submit button.
However the app does respond to some ajax calls with Modals opening and so overlapping happens all the time. It even happens, when the Loading does not get dismissed fast enough...
I think the Loading is the best way to test it as many people will use it with Ajax calls i guess.

**Comment by jgw96** [comment] 2016-08-15 20:14
@nickwinger Sorry its causing issues for you at the moment, thats why were beta 😄 . Thanks for using Ionic and thanks for the feedback! Note to self: revisit this issue when beta.12 hits.

**Closed by jgw96** 2016-08-15 20:14 UTC
Labels: v2
