### ISSUE TITLE
Ionic 2.0.0 app stuck on splash screen

### ISSUE THREAD

**Issue by SadamChami** [driftyco/ionic#10570] opened 2017-02-27 04:30 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
In Samsung S3 ( 4.3 ) application is not starting. Its was stuck on splash screen. Not even Start webview to inspect through chrome inspector. Its working fine in Samsung S4(5.0), Sony M2(5.0), iOS. But when in add crosswalk, it works fine. But the problem is, adding crosswalk, increase the app size by 22MB. Is there any way to run ionic 2 project without adding crosswalk ? Or if i had to add crosswalk, which devices i have to add that.

**Expected behavior:**
App should start without crosswalk browser.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.5
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by graphefruit** [comment] 2017-02-27 10:46
@SadamChami

Ionic won't run on Android phones below 4.4, so if you want to support 4.3 you need to add crosswalk.
If needed you can provide 2 versions, one with crosswalk for (4.1 to 4.3) and one without (4.4 and up)

So after that is not a bug please close this issue.
Thanks
Graphefruit

**Comment by jgw96** [comment] 2017-02-27 19:48
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Closed by jgw96** 2017-02-27 19:48 UTC

**Comment by datacomp** [comment] 2017-06-27 13:51
Hi,
I am also getting the same issue of splash screen stuck, but on ionic 3.4.0. 
I have tried many solutions but got no luck. Please help me out in this.

**Comment by juanjoseadan** [comment] 2017-11-15 21:00
Having the same issue with Ionic 3.7.0.

P. S. I tried to configure the Splash Screen Auto Hide in the config.xml without success, our team is getting very disappointed with this

**Comment by dudanogueira** [comment] 2018-01-01 21:52
Same here. Will get more information tomorrow as I'll get my hands on a device with this behaviour. running the latest stack: 

cli packages: (/usr/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.4
    Cordova Platforms  : android 6.3.0 browser 5.0.1
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.2.5
    Node              : v6.12.2
    npm               : 3.10.10 
    OS                : Linux 4.4

Environment Variables:

    ANDROID_HOME : /home/dudanogueira/Android/Sdk

Misc:

    backend : pro

**Comment by dudanogueira** [comment] 2018-01-01 21:52
the device in question os android 5.1
