### ISSUE TITLE
bug: LoadingController not working on first tab

### ISSUE THREAD

**Issue by sjaanus** [driftyco/ionic#8027] opened 2016-09-09 08:25 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>When creating a basic tabs project, I want to use LoadingController to show loader until everything is initialized.

Problem is that, the loader is never shown on the first tab. I put the same code to other tab and works perfectly.

This is the code I am using to show loader.

```
 let loading = this.loadingController.create({
            content: 'Please wait...'
        });
        console.log("creating loader");
        loading.present();

        setTimeout(() => {
            loading.dismiss();
        }, 5000);
```

This is the full code.
https://github.com/sjaanus/ionic2-loading-controller</span>

<span is-issue-template></span>

**Comment by jgw96** [comment] 2016-09-09 14:41
Hello, thanks for opening an issue with us! I am going to be closing this one as a duplicate of https://github.com/driftyco/ionic/issues/7605. Thanks for using Ionic!

**Closed by jgw96** 2016-09-09 14:41 UTC
Labels: v2
