### ISSUE TITLE
(Bug) Keyboard pops when sliding an item of a 'sliding list' while searchbar has focus

### ISSUE THREAD

**Issue by devarg** [driftyco/ionic#7005] opened 2016-06-22 01:48 UTC
#### Short description of the problem:
If you have a search-bar that is focused (cursor blinking) and right down you have a sliding list. Sliding an item of the list while the cursor blinks on the searchbar makes the keyboard pop as if you were clicking on it to add some input. (this happens on Android but not on the browser)

#### What behavior are you expecting?
Keyboard should not be fired if it is not clicked.

**Steps to reproduce:**
1. Create a view like the one specified with 'Example'.
2. Click on the searchbar input (keyboard pops)
3. Optionally add some input
3. Press back button (Keyboard closes)
4. Slide an item to the left to see the options.

**Example**
```
<ion-content padding>
    <ion-grid>
        <ion-row>
            <ion-col width-90>
                <ion-searchbar [ngFormControl]="searchInput"></ion-searchbar>
            </ion-col>
        </ion-row>
    </ion-grid>
<ion-list>
  <ion-item-sliding *ngFor="let item of ['item a', 'item b', 'item c']">
    <ion-item>
        <h2>{{item}}</h2>
        <p> Item description</p>
    </ion-item>
    <ion-item-options>
        <button light>
        <ion-icon name="pin"></ion-icon>
        Details
      </button>
      <button default>
        <ion-icon name="pin"></ion-icon>
        Details
      </button>
      <button secondary>
        <ion-icon name="pin"></ion-icon>
        Lookup
      </button>
    </ion-item-options>
  </ion-item-sliding>
</ion-list>

</ion-content>
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
I could not figure out a resolution to this, but made this workaround.

`import {Keyboard} from 'ionic-angular';`
`constructor(private _keyboard: Keyboard){}`
on the html I listen to touchend (when my keyboard fires)
`<ion-item (touchend)="preventKeyboard()">`
and then close it right away doing this
```
preventKeyboard(){
        this._keyboard.close();
    }
```
If you put a lot of attention you can see the keyboard trying to go up but close() pushes it quickly down, and solves this to me for now.  But I hope it gets a better solution.

I also thought about listening to Keyboard 'onClose' and programatically bluring the input searchbar so if the cursor is not there I'm pretty sure the keyboard won't jump in.

 

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.31
Ionic App Lib Version: 2.0.0-beta.17
OS: Windows 8.1
Node Version: v6.0.0

**Comment by devarg** [comment] 2016-09-20 18:51
Will there be any updates on this? Thanks!

**Comment by jgw96** [comment] 2016-09-20 21:28
Hello, thanks for opening an issue with us! I cannot seem to reproduce this issue with beta.12 on my Nexus 6 running Android 7.0, my Nexus 7 running Android 6.0.1 and a Moto X running Android 5.1.1. Because of this I am going to be closing this issue for now. Thanks for using Ionic!

**Closed by jgw96** 2016-09-20 21:28 UTC
Labels: keyboard, platform:android, v2
