### ISSUE TITLE
Forbidden upload (403) (CLI v2.1.17)

### ISSUE THREAD

**Issue by ptmagalhaes** [driftyco/ionic#9888] opened 2017-01-05 12:50 UTC
Ionic version: (check one with "x")
[ ] 1.x
[x] 2.x

I'm submitting a ... (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

Current behavior:

Expected behavior:

When i try IONIC UPLOAD
Uploading app....
An error occurred uploading the build: Forbidden upload (403)

Forbidden upload (403) (CLI v2.1.17)

Steps to reproduce:

Related code:

insert any relevant code here
Mac-mini-de-teste:schedule Devign$ ionic upload
Uploading app....
An error occurred uploading the build: Forbidden upload (403)

Forbidden upload (403) (CLI v2.1.17)

Other information:

Ionic info: (run ionic info from a terminal/cmd prompt and paste output below):

insert the output from ionic info here
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.9.0
ios-sim version: 5.0.13
OS: OS X El Capitan
Node Version: v7.3.0
Xcode version: Xcode 8.2 Build version 8C23

**Comment by wbhob** [comment] 2017-01-05 15:21
`ionic login` first.

**Comment by jgw96** [comment] 2017-01-05 17:53
Closing this as a duplicate of https://github.com/driftyco/ionic/issues/9887

**Closed by jgw96** 2017-01-05 17:53 UTC
