### ISSUE TITLE
ion-label floating direction rtl , the label come almost in the middle not at the right.

### ISSUE THREAD

**Issue by joesleiman** [driftyco/ionic#11627] opened 2017-05-12 08:23 UTC
**Ionic version:** 
3.0.1

**I'm submitting a bug report*  

**Current behavior:**
the label  comes in the center. not right

**Expected behavior:**
the label should appear in the right side.
**Steps to reproduce:**
```
<ion-item>
     <ion-label floating style="direction:rtl;">joe</ion-label>
     <ion-input></ion-input>
</ion-item>
```

css: direction : rtl;

**Comment by brandyscarney** [comment] 2017-05-12 16:35
Could you try updating to the latest version of Ionic: `3.2.0`? There have been a lot of `rtl` improvements. I am not able to reproduce this on latest:

![screen shot 2017-05-12 at 12 34 03 pm](https://cloud.githubusercontent.com/assets/6577830/26007624/61cca25a-370f-11e7-8b18-35c754867e65.png)

cc @AmitMY

**Comment by AmitMY** [comment] 2017-05-12 16:39
@joesleiman The reason for this is that you use "direction: rtl"
you should instead, on the item itself (preferably on the entire html, but if that what you need so the item) add `dir="rtl"`

Here is the relevant fix: https://github.com/driftyco/ionic/pull/11324

**Comment by joesleiman** [comment] 2017-05-12 17:28
@brandyscarbey  Same issue on latest ionic version 3.2.0
@amitmy : yes i discovered this . It's fine now

**Comment by joesleiman** [comment] 2017-05-12 17:33
I don't want to add dir="rtl" on html tag because the back button still same icon . I mean pointing to the left like this < . I need it to be >

**Comment by AmitMY** [comment] 2017-05-12 19:20
@joesleiman RTL support is WIP.
This one fixes the arrow for the input - https://github.com/driftyco/ionic/pull/11351 - and will be merged when required changes are met.

**Comment by joesleiman** [comment] 2017-05-12 19:26
Hope they merge it soon.
You know something about the menu in rtl direction. It open from left to right . I think it is also solved but need to merge. Thankss

**Comment by AmitMY** [comment] 2017-05-12 19:31
@joesleiman since 3.1.0, if not specifying the menu side, and having `dir="rtl"` at the beginning of the doc it would open from the right.

The animation itself, and having it be changeable in run-time, is still open https://github.com/driftyco/ionic/pull/11336

If your app is RTL only, and you want to make it always open from the right, for now, add `[side]="'right'"` and it will work.

**Comment by manucorporat** [comment] 2017-05-12 19:36
fixed in 3.2.1, but RTL support continues improving
cc @AmitMY

**Closed by manucorporat** 2017-05-12 19:36 UTC
Labels: rtl, v3

**Comment by joesleiman** [comment] 2017-05-12 20:07
@amitmy no my app is ltr and rtl . 
@Manucorporat is there a 3.2.1 version . I know the last version is 3.2.0

**Comment by joesleiman** [comment] 2017-05-12 20:09
@amitmy i put dir='rtl' at the begining and the menu still open from the left side but the menu button is moved to the right .

**Comment by AmitMY** [comment] 2017-05-12 20:15
@joesleiman yep, that open PR fixes it. I can't give an estimate to when it will be merged. @manucorporat might be able.

**Comment by joesleiman** [comment] 2017-05-12 20:25
Ok just another issue that i faced. Im using the google map from ionic native plugin. I noticed that if i change the background color of the page where the map is , the map disappear from the page. 
And if i have an ion- select above the map , then i click on select a modal or pop up appear but i can't click on any option since they are above the map.
Also there a delay when i scroll the page . The map take time to start scroll.
Thanks in advance for everyone.

**Comment by AmitMY** [comment] 2017-05-12 20:35
It seems like a different issue.. Please create an issue with ionic-native for the maps issue.

**Comment by joesleiman** [comment] 2017-05-12 20:38
Ok thank you...
