### ISSUE TITLE
Popover appears to assume it will be invoked from NavBar

### ISSUE THREAD

**Issue by emgould** [driftyco/ionic#10636] opened 2017-03-03 15:18 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: 

**Current behavior:**
I invoke a popover from a parent element that is NOT that nav bar.  From a card for example.  When doing so the popover aligns itself over the icon that invoked it and the arrow does not display but is actually in the middle of the page ( and yes the event is being passed in properly )

**Expected behavior:**
I would expect  the popover to render with arrow underneath whatever element I attached it to.

**Steps to reproduce:**
Create an ion-card with an ion-card-header that has a button to invoke a popover

**Comment by brandyscarney** [comment] 2017-03-03 15:56
Thanks for the issue! Could you provide some code, a repository, or a plunker that we can use to reproduce this? I'm not able to reproduce it in our tests:

<img width="300" src="https://cloud.githubusercontent.com/assets/6577830/23557935/cdbd9632-ffff-11e6-8793-a06ae93271ca.png"><img width="300" src="https://cloud.githubusercontent.com/assets/6577830/23557938/cecebef2-ffff-11e6-9f4c-60db8ec271db.png">

**Comment by jgw96** [comment] 2017-03-08 17:50
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-03-08 17:50 UTC
Labels: needs info, v2
