### ISSUE TITLE
CLI truncates some content on node v6

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [driftyco/ionic#6501] opened 2016-05-11 15:22 UTC
Run `ionic`without params likely has some fall-through to some loop over console logs. Those logs will be truncated. This is due to a libuv change in node core, that won't be fixed. There are a lot of similar tickets and I assume there will be fixes in `yargs` and similar.

Ref: https://github.com/yargs/yargs/issues/497, https://github.com/nodejs/node/issues/6456

Possible fix not using process.exit() and respective handlers. https://github.com/yargs/yargs/pull/498

**Comment by jgw96** [comment] 2016-05-11 15:34
Hello! Thanks for the awesome info! Would you mind posting this information over on https://github.com/driftyco/ionic-cli/issues/960 ? I am also going to close this issue as a dupe of https://github.com/driftyco/ionic-cli/issues/960 . Thanks again, this is really useful!

**Closed by jgw96** 2016-05-11 15:34 UTC
