### ISSUE TITLE
Problem with declaration only [min] attribute. Required two attributes min, max to work

### ISSUE THREAD

**Issue by edyrkaj** [driftyco/ionic#9748] opened 2016-12-21 16:48 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by brandyscarney** [comment] 2016-12-21 17:28
Please fill out the template provided with more information: current behavior, expected behavior, steps to reproduce, example code, etc. We need more information in order to understand your issue. Thanks!

**Comment by jgw96** [comment] 2016-12-27 16:01
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-12-27 16:01 UTC
Labels: needs info, needs reply, v2
