### ISSUE TITLE
ion-slides missing lazyLoading, lazyLoadingInPrevNext and grabCursor options of swiperjs

### ISSUE THREAD

**Issue by suau** [driftyco/ionic#10663] opened 2017-03-06 10:36 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request

**Current behavior:**
`ion-slides` removed the `options` input in RC-5 without exposing alternative attributes for `lazyLoading`, `lazyLoadingInPrevNext` and `grabCursor`

**Expected behavior:**
expose `lazyLoading` , `lazyLoadingInPrevNext` and `grabCursor` attributes

```
Cordova CLI: 6.5.0 
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: macOS Sierra
Node Version: v6.10.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment] 2017-03-06 14:59
Hello, thanks for using Ionic. I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/10199.

**Closed by jgw96** 2017-03-06 14:59 UTC

**Comment by suau** [comment] 2017-03-06 15:13
@jgw96 it's not a duplicate as these options are not (yet) exposed by the new `ion-slides` implementation, #10199 is closed but the issue persists
