### ISSUE TITLE
Closing side menu doesn't respond well

### ISSUE THREAD

**Issue by shawnlan** [driftyco/ionic#10811] opened 2017-03-16 18:48 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

Tested on iPad (iOS 10) with Ionic 2.2.0. Looks like if you try to close the menu too soon after it opens, it doesn't close. Wait for a few seconds then close will work.

And there seems a 300ms delay when closing the menu. Please check.

**Comment by kamok** [comment] 2017-03-16 19:23
Since you're testing on device, did you try to build with the `--prod` flag? It should help with the speed. Building with and without `--prod` should see a measurable difference in file size, boot up speed, and transition speed.

**Comment by shawnlan** [comment] 2017-03-16 19:31
No difference. I don't think that's the issue. Other transitions are fine.

**Comment by jgw96** [comment] 2017-04-07 16:09
Hello all! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/9716

**Closed by jgw96** 2017-04-07 16:09 UTC
Labels: v2
