### ISSUE TITLE
bug: JrCrop Plugin, Pinch to Zoom stops working since rc.2

### ISSUE THREAD

**Issue by akreienbring** [driftyco/ionic#3445] opened 2015-03-31 19:18 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>Hello,
I just noticed that after updating to rc.2 the pinch to zoom stops working in the JRCrop Plugin.
https://github.com/JrSchild/jr-crop

Reverting to rc.1 solves the problem.

Most likely the problem is related to this part of the JRCrop code:
```
 ionic.onGesture('touch transform drag dragstart dragend', function(e) {
  switch (e.type) {
    case 'touch':
      self.last_scale = self.scale;
      break;
    case 'drag':
      self.posX = self.last_posX + e.gesture.deltaX - transforming_correctX;
      self.posY = self.last_posY + e.gesture.deltaY - transforming_correctY;
      setPosWithinBoundaries();
    break;
    case 'transform':
      self.scale = Math.max(scaleMin, Math.min(self.last_scale * e.gesture.scale, scaleMax));
      setPosWithinBoundaries();
      break;
    case 'dragend':
      self.last_posX = self.posX;
      self.last_posY = self.posY;
      break;
   case 'dragstart':
      self.last_scale = self.scale;
      // After scaling, hammerjs needs time to reset the deltaX and deltaY values,
      // when the user drags the image before this is done the image will jump.
      // This is an attempt to fix that.
      if (e.gesture.deltaX > 1 || e.gesture.deltaX < -1) {
        transforming_correctX = e.gesture.deltaX;
        transforming_correctY = e.gesture.deltaY;
      } else {
        transforming_correctX = 0;
        transforming_correctY = 0;
      }
      break;
  }
  self.setImageTransform();
}, self.options.modal.el);
````

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-03-31 19:18
Greetings @akreienbring!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3445). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3445)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment] 2015-03-31 19:54
Greetings @akreienbring!

My sensors indicate that I require more information in order to assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this happen occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com), where many humans will be able to offer wisdom and advice.

Thank you for allowing me to assist you.

<span ionitron-needs-reply></span>

**Comment by akreienbring** [comment] 2015-04-01 18:08
What I found out so far:
with rc.2 the 'transform' event in the code above get's never fired. In rc.2 it does.

**Comment by perrygovier** [comment] 2015-04-01 20:18
This looks to be specifically related to the JRCrop lib, so I'm going to close the Ionic issue, but We can keep the conversation going on JR Crop

**Closed by perrygovier** 2015-04-01 20:18 UTC
