### ISSUE TITLE
Input focus scroll up above keyboard

### ISSUE THREAD

**Issue by sridharan31** [driftyco/ionic#8560] opened 2016-10-07 12:37 UTC
When I focus an which is positioned lower than the height of the keyboard, the input is getting hidden by the keyboard when I type its come above to keyboard

I am expecting the input to get scrolled up above the keyboard when i focus the input. someone suguest call this method in app.ts
[![enter image description here][1]][1]
    
    declare var cordova:any;
    declare var window:any;

    platform.ready().then(() => {
          // Okay, so the platform is ready and our plugins are available.
          // Here you can do any higher level native things you might need.
          StatusBar.styleDefault();
    
          if (window.cordova && window.cordova.plugins.Keyboard) {
            // This requires installation of https://github.com/driftyco/ionic-plugin-keyboard
            // and can only affect native compiled Ionic2 apps (not webserved).
            cordova.plugins.Keyboard.disableScroll(false);
          }
        });

in my console shows cordova objects but not working when i focus on input the page scroll up not working android device, any solution? i'am stuck on it

i referred [link][2]
Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
Node Version: v6.2.1

  [1]: http://i.stack.imgur.com/5u3JB.gif
  [2]: https://forum.ionicframework.com/t/disable-scroll-ionic2-ios9-not-working/44847/5

**Comment by jgw96** [comment] 2016-10-07 14:22
Hello, thanks for opening an issue with us! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/6228.

**Closed by jgw96** 2016-10-07 14:22 UTC
