### ISSUE TITLE
Use of navCtrl.setRoot more than 10 times freezes the app

### ISSUE THREAD

**Issue by EugeneSnihovsky** [driftyco/ionic#5718] opened 2016-03-04 15:33 UTC
#### Short description of the problem:
Simple project with two pages and buttons that redirect on each other with navCtrl.setRoot(PageName).
On 11 click on android device app freezes forever.
On 11 click on chrome I see black screen and can do nothing.

#### What behavior are you expecting?
I want to navigate in my app from page to page with navCtrl.setRoot infinite times.

**Steps to reproduce:**
1. git clone -b ER-1_freeze_after_multi_navigation https://github.com/EugeneSnihovsky/ionic2-for-errors.git
2. cd ionic2-for-errors
3. npm install
4. ionic serve
5. Navigate from home to settings page more than 10 times.

##### Page code (second page similar)
```
'use strict';
import {NavController} from 'ionic-framework/ionic';
import {SettingsPage} from '../../main/settings/settings.page';


import {Page} from 'ionic-framework/ionic';

@Page({
    templateUrl: 'build/components/main/home/home.html'
})

export class HomePage {
    private navCtrl: any;
    constructor(navCtrl: NavController) {
        var self = this;
        self.navCtrl = navCtrl;
    }

    open(name) {
        this.navCtrl.setRoot(SettingsPage);
    }
}
```

**Ionic Version**: 2.x

**Browser & Operating System**: Android / Chrome

**Run `ionic info` from terminal/cmd prompt:**

```
Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Version: 2.0.0-beta.1
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
OS: Distributor ID:     LinuxMint Description:  Linux Mint 17.2 Rafaela 
Node Version: v5.3.0

```

**Comment by privetr** [comment] 2016-03-04 21:16
Same problem here, but whatever number of navigation pages.

Using this.nav.push when I close an Alert, or using this.nav.setRoot causes black screens on Chrome (most of time).

```
ionic info

Your system information:

Cordova CLI: 5.0.0
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic Version: 2.0.0-alpha.57
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
OS:
Node Version: v4.2.6
```

**Comment by adamdbradley** [comment] 2016-03-06 16:35
Thanks for the report! What really helped was "Navigate from home to settings page more than 10 times.", and the `10` helped figure out what the issue was. Should be fixed in the next release, thanks!

**Closed by adamdbradley** 2016-03-06 16:35 UTC
Labels: navigation, platform:android, v2
