### ISSUE TITLE
Ionic Segmented Control not showing properly

### ISSUE THREAD

**Issue by YuvarajManickam** [driftyco/ionic#8606] opened 2016-10-10 09:56 UTC
**Note: If you are having problems formatting your issue please refer to this article on using markdown in Github:**

https://guides.github.com/features/mastering-markdown/

**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

**Note: for Ionic-Native related issues you can open up an issues on the Ionic-Native repo**

https://github.com/driftyco/ionic-native

#### Short description of the problem:
Am new to Ionic framework hybrid application development from native iOS development. I gone through the Ionic framework document to use "Segment Control" and tried myself. But, the segmented control not showing properly. How can I design a Segmented control looks like native iOS and Android? Can you please help me to handle Segmented Control actions? 

#### What behavior are you expecting?
Expecting the segmented control looks like native iOS and Android. 

**Steps to reproduce:**
1. 
2. 
3. 

```
<ion-segment ng-model="pet">
  <ion-segment-button value="kittens">
    Kittens
  </ion-segment-button>
  <ion-segment-button value="puppies">
    Puppies
  </ion-segment-button>
</ion-segment>
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x
Using Ionic V 1.

#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

**For Ionic 2 issues** - http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

![screen shot 2016-10-10 at 3 04 47 pm](https://cloud.githubusercontent.com/assets/2003339/19232523/d49275ea-8efd-11e6-8ca9-726f606adc8d.png)

**Comment by jgw96** [comment] 2016-10-10 16:36
Hello, thanks for using Ionic! Would you be able to provide a repo that we can use to reproduce this issue with?

**Comment by manucorporat** [comment] 2016-10-10 18:11
@jgw96 v2?

**Comment by jgw96** [comment] 2016-10-17 00:06
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-10-17 00:06 UTC
Labels: needs reply, v2
