### ISSUE TITLE
ion-tabs getting cut off for 5 or more tabs

### ISSUE THREAD

**Issue by Lindstrom1989** [driftyco/ionic#6446] opened 2016-05-05 16:04 UTC
Ion tabs get cut off on smaller devices in ios like iphone 5 if you have more than 4 tabs (The app store has 5 tabs). You can also see this in browser with ios styling.

"angular2": "2.0.0-beta.15",
    "angular2-google-maps": "^0.9.0",
    "es6-promise": "3.0.2",
    "es6-shim": "^0.35.0",
    "firebase": "^2.4.2",
    "ionic-angular": "2.0.0-beta.6",
    "ionic-native": "^1.1.1",
    "ionicons": "3.0.0-alpha.3",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.2",
    "zone.js": "0.6.10"

**Comment by jgw96** [comment] 2016-05-05 16:07
Hello! Would you mind trying with the latest nightly? To use nightly simply run `npm install ionic-angular@nightly`. I believe that this issue was fixed and will make it into the beta.7 release, but it should already be in the latest nightly.

**Comment by jgw96** [comment] 2016-05-09 18:59
I can confirm that it looks like this is fixed in nightly. Thanks!

**Closed by jgw96** 2016-05-09 18:59 UTC
Labels: needs reply, platform:ios, v2
