### ISSUE TITLE
modal is not correctly show in android device

### ISSUE THREAD

**Issue by jyj545** [driftyco/ionic#9630] opened 2016-12-14 07:58 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

modal is Invisible on chrome debug galaxy s5、nexus 5x、nexus 6p  ,but its correct on iphone device.

**Expected behavior:**

show modal correctly

**Steps to reproduce:**

**Related code:**

```
    //open modal
    openPresaleModal() {
        let Modal = this.modalCtrl.create(PreSaleModalContentPage, { PresaleHistory: helper.getHistoryRec("PresaleHistory") });
        Modal.present();
        Modal.onDidDismiss(data => {
            console.log(data);
            if (data.queryString != "" && data.queryString != null) {
                this.updateData(data.queryString);
                this.value = data.queryString;
            }
        });
    }
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment] 2016-12-14 23:00
Hey, thanks for opening an issue with us! Would you mind providing a repo I can use to reproduce this? I cant seem to reproduce this on any of my android devices.

**Comment by jyj545** [comment] 2016-12-15 06:20
<ion-searchbar placeholder="企业名称 项目名称" value={{value}} (ionFocus)="openPresaleModal()"></ion-searchbar>
this function is awake from a searchbar,and when i focused the searchbar,i want just show my modal,not the keyboard.

**Comment by jgw96** [comment] 2016-12-15 21:42
Hello @jyj545 ! Thanks for the info. I am working on how this could be done as we speak, but i would like to say that this is not a supported use case for searchbar at the moment. You may be better off using a button here. First, if you use a button it will not require any custom logic to stop the searchbar from being focused. Second, from a user experience perspective, tapping a searchbar and then having a modal pop up may be confusing to the user who was expecting to be able to use that searchbar to type and search something.

**Comment by jyj545** [comment] 2016-12-16 04:01
thanks for your advise,i saw some app was doing this for show a modal with a searchbar and history search recodes,then they can touch the recodes to trigger a searching,so i followed what those apps doing.
And im trying your advise to use a pic which looks like a searchbar,and through chick the pic ,user can open the modal,THS A LOT.

**Comment by jyj545** [comment] 2016-12-16 08:19
for my test,the Modal is not correctly presented in android device below android 5.1.1.  its looks like unviseable but clickable.

**Comment by jgw96** [comment] 2017-01-20 16:00
Hello @jyj545 unfortunately i cannot reproduce this modal issue on any of my Android or iOS devices. Are you still having this issue in RC5?

**Comment by jgw96** [comment] 2017-01-24 15:48
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-01-24 15:48 UTC
Labels: needs reply, v2

**Comment by jyj545** [comment] 2017-02-08 01:08
it seems likely not present any more,thanks for your efforts!
