### ISSUE TITLE
ion-select is inoperable when used on a modal fired from ionViewDidEnter

### ISSUE THREAD

**Issue by kelvindart** [driftyco/ionic#7992] opened 2016-09-06 14:23 UTC
#### Git URL:
https://github.com/kelvindart/ionic-modal-select

#### Short description of the problem:
When using an `ion-select` on a modal page which is launched via `ionViewDidEnter()` with `modal.fireOtherLifecycles = false;` (which fixes another issue with the modal displaying a second time after initially dismissing it), stops the `ion-select` from being usable; you can tap it to open it but you cannot change the options nor can you cancel/confirm the selected choice.

#7839 describes using the fireOtherLifecycles property to overcome the problem with the modal appearing twice.

#### What behavior are you expecting?
To be able to use the `ion-select` normally. When selecting an item, it should visibly select that item and the select box should be closed when selecting "OK" or "Cancel".

**Steps to reproduce:**
1. Clone the repository: `git clone https://github.com/kelvindart/ionic-modal-select && cd ionic-modal-select`
2. Run it on the iOS emulator: `ionic emulate ios`
3. Open the select box when the modal appears.

If you comment out the following line in `home.ts:22`: 
```javascript
    modal.fireOtherLifecycles = false;
```
The `ion-select` works, but then the modal displays twice, once again after dismissing it initially.

**Other information:**
 N/A

**Which Ionic Version?**
ionic@2.0.0-beta.11

**Run `ionic info` from terminal/cmd prompt:**
Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: Not installed
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.5.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by kelvindart** [comment] 2016-09-20 23:01
Hey @jgw96 - just curious, is this fixed in beta 12?

**Comment by jgw96** [comment] 2016-09-22 15:42
Hello! After testing this issue a few moments ago I can confirm that it looks like this issue is fixed in beta.12! 🎉  Thanks for using Ionic!

**Closed by jgw96** 2016-09-22 15:42 UTC
Labels: select, v2

**Comment by kelvindart** [comment] 2016-09-22 15:56
This makes me SO happy 😀. Gahhh - I'm too excited for beta.12 already!
