### ISSUE TITLE
feat: $state.reload() and view caching

### ISSUE THREAD

**Issue by herrerodani** [driftyco/ionic#2917] opened 2015-01-12 13:39 UTC
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>$state.reload() doesn't work when view caching is on.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-01-12 13:39
Greetings, @herrerodani!

We are now requiring all issues to be submitted through our custom issue form so that we have all of the information necessary to fix them as quickly as possible.

Your progress on this issue has been saved at the following url:

[link to Ionic issue form](http://ionicframework.com/submit-issue/#/?iid=2917)

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by bleuscyther** [comment] 2015-01-19 03:12
yes

**Comment by lancetw** [comment] 2015-02-13 21:14
+1

**Comment by mhartington** [comment] 2015-02-23 20:27
Codepen example?

**Comment by Ionitron** [comment] 2015-02-27 21:13
Greetings @herrerodani!

My sensors indicate that I require more information in order to assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this happen occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com), where many humans will be able to offer wisdom and advice.

Thank you for allowing me to assist you.

<span ionitron-needs-reply></span>

**Comment by Ionitron** [comment] 2015-03-29 21:32
Greetings @herrerodani!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-03-29 21:32 UTC
Labels: ionitron:closed
