### ISSUE TITLE
ionic emulate ios stuck on splash screen

### ISSUE THREAD

**Issue by wargun02** [driftyco/ionic#6369] opened 2016-04-29 02:53 UTC
I notice a very consistent behaviour when it comes to emulating on iOS, it was stuck in the splash screen after ionic emulate iOS and I can't even get the app running, not even going into the code section of $ionicPlatform.ready( function () {...});

I'm running on Mac OSX El Capitan 10.11.4 (with Xcode and xcode-select installed)

Steps to reproduce:
1) ionic start EmulatorCrash
2) cd EmulatorCrash
3) ionic platform rm ios
4) ionic platform add ios
5) ionic build ios
6) ionic emulate ios -cls --target=iPhone-6s-Plus

This will run the iPhone-6s-Plus emulator but will be stuck in the splash screen.

**Comment by ghenry22** [comment] 2016-05-01 20:34
try updating ios-sim and ios-deploy from npm, I had the same problem with was resolved by updating those 2

**Comment by wargun02** [comment] 2016-05-02 03:16
updated both ios-sim and ios-deploy with:
```
sudo npm update -g ios-sim
sudo npm update -g ios-deploy
```

Run the steps to reproduce. Same problem...

Here's what I have when I executed "ionic info"
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Version: 1.3.0
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.11.0
Xcode version: Xcode 7.3 Build version 7D175

**Comment by jgw96** [comment] 2016-05-02 14:59
Hello @wargun02 ! Thanks for opening an issue with us! Are you only having this issue when using the ios simulator? Or does it also happen on a device?

**Comment by wargun02** [comment] 2016-05-03 00:25
Its with the simulator. Please read the steps to reproduce above. 

I have no iPhone 6s Plus to check on this, the closes I could try is on my iPad Air (which I have yet to check).

**Comment by wargun02** [comment] 2016-05-03 05:08
I have found the issue. This is all due to the fact that the raw startup project structure doesn't have
```
<allow-navigation href="*" />
```
in the config.xml. I wouldn't know if this is the right place to report this bug or should this be reported in https://github.com/driftyco/ionic-app-base

To remedy, just go through the steps to reproduce and before hitting on ionic build ios, just insert the
```
<allow-navigation href="*" />
```
to the config.xml file.

**Comment by jgw96** [comment] 2016-05-03 14:39
Hey! Glad you found the issue! Can you report this to app-base please? Thanks for using Ionic!

**Comment by jgw96** [comment] 2016-05-04 16:19
Hey! Im gonna go ahead and close this issue as it is not a bug with the ionic framework directly. Thanks for using Ionic!

**Closed by jgw96** 2016-05-04 16:19 UTC
Labels: platform:ios, v1

**Comment by wargun02** [comment] 2016-05-04 22:30
jgw96. Thanks for attending to this, you may close this issue.

I have tried to submit this issue to app-base, but they've disabled the "issues" for that repo. So, perhaps I'll just leave this issue reporting to anyone from ionic who's in-charged to app-base.
