### ISSUE TITLE
bug: Ionic doesnt undrstnd stndrd html tags like <xmp>

### ISSUE THREAD

**Issue by nikhilknoldus** [driftyco/ionic#7804] opened 2016-08-20 19:04 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>browser</span>

Ionic not understanding standard html tags like < xmp >, < code > and < pre >, i have to show code snippet in ionic app, that is a combination of html and anuglarjs but i can't show it up even after escaping it, none of the tag is working in ionic but in standard html code.

**Comment by nikhilknoldus** [comment] 2016-08-22 04:52
Hey @jgw96 Justin can you please have a look here. Thanks

**Comment by jgw96** [comment] 2016-08-22 15:22
Hello! Thanks for opening an issue with us! Would you mind sharing a code snippet of what your template looks like? Thanks for using Ionic!

**Comment by nikhilknoldus** [comment] 2016-08-23 04:58
Thanks for replying, Yes sure, Here is a very simple code that contains in-line AngularJs code: 
`<ul>
	<li *ngFor="let bikePart of bikeParts
	    <h2>{{bikePart.name | uppercase}}</h2>
	    <p>{{bikePart.description}}</p>
	    <p *ngIf="bikePart.inStock > 0">{{bikePart.inStock}}</p>
	    <p *ngIf="bikePart.inStock === 0">out of stock</p>
	    <p>{{bikePart.price | currency:EUR':true}}</p>
	</li>
</ul>`

Now as we do in simple html we can use any of the tag to show this snippet on ui tags are:
< xmp >
< pre >
< code >

In Html when i put this code inside < xmp > i can see it as it is without compiling, but when i do same in ionic template, application starts finding properties and doesn't work.

That's why i said Ionic isn't supporting these standard html tags.

I hope you will consider it, because you can check on google app store i have published an app (AngularJs 2 - Nikhil Kumar) where in it lots of code snippets were required to show, anyhow i managed to show but thats not a feasible solution.
 
Thanks !!

**Comment by jgw96** [comment] 2016-08-23 16:23
Hello! Thanks for the info. Does the xmp tag work for you in a plain Angular 2 app? Also, the pre tag and code tag seem to be working fine for me In Ionic 2, is it mainly the xmp tag your having trouble with?

**Comment by nikhilknoldus** [comment] 2016-08-24 04:44
All three tags are working for me in Plain Html+AngularJs but none of three working in ionic, i can show you working examples where these tags are not working in ionic but in Html, if you have installed the app that i referenced earlier (goo.gl/6qEAYn) you can see i have buttons there when user clicks an InAppBrowsers opens with some code snippets that page is complete html page and every tag is working there but not in Ionic. Hope you understand. Thanks. waiting for your prompt reply.

**Comment by nikhilknoldus** [comment] 2016-08-29 05:07
Hey @jgw96 @bensperry  can you have a look here please.

**Comment by jgw96** [comment] 2016-08-29 13:43
Hello @nikhilknoldus ! I am currently looking more into this issue. `<code>` and `<pre>` seem to work fine for me, but I can confirm that `<xmp>` is not.  Thanks!

**Comment by nikhilknoldus** [comment] 2016-08-30 04:37
@jgw96  Hey thanks  Justin, for considering my issue into Ionic.

**Comment by nikhilknoldus** [comment] 2016-09-21 07:41
Hello @jgw96 Justin ! can you show me the example for `<code>` and `<pre>` that is working for you, example code should contain angularjs tags inside html. Thanks !!

**Comment by nikhilknoldus** [comment] 2016-11-25 10:25
Hey @jgw96 , I tried the 
`code` `pre` and `xmp` in the latest version of Ionic, but these are not working man.

**Comment by jgw96** [comment] 2017-01-19 17:15
Hello! So the reason that `xmp` was not working in my test was that it has been deprecated in chrome. Because the `code` tag and the `pre` tag were working in my testing, and those are the recommended replacements for the `xmp` tag I am going to close this issue for now. If you could make a plunker that shows the `code` and `pre` tags not working then i will happily reopen this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-01-19 17:15 UTC
Labels: v2
