### ISSUE TITLE
Virtual Scroll with not set height for elements makes app crash.

### ISSUE THREAD

**Issue by SegoleneM** [driftyco/ionic#6421] opened 2016-05-04 08:16 UTC
#### Short description of the problem:
Virtual Scroll with not set height for elements makes app crash.

#### What behavior are you expecting?
The app not to crash

**Steps to reproduce:**
1. Use the following code: 
```
import {Page} from 'ionic-angular';
@Page({
  template: `
  <ion-navbar *navbar>
  <ion-title>Tab 1</ion-title>
</ion-navbar>

<ion-content>
  <ion-list [virtualScroll]="items">

    <ion-item *virtualItem="#item">
      {{item}}
    </ion-item>

  </ion-list>
</ion-content>

  `
})
export class Page1 {
  public items = [];
  constructor() {
    for (let i = 0; i < 1000; i++) {
      this.items.push(i)
    }
  }
}

```
2. Use the scroll

**Which Ionic Version?**  2.x

**Comment by jgw96** [comment] 2016-05-04 14:29
Hello! Thanks for opening an issue with us! We have been able to reproduce this and are looking into it.

**Comment by jgw96** [comment] 2016-05-04 14:36
Hello! Thanks for opening an issue with us! We have been able to reproduce this when using divs instead of an ion-list and ion-item, but your code above should work fine. Would you mind making a plunker or codepen that we can use to reproduce this issue with an ion list and ion item? Thanks!

**Comment by jgw96** [comment] 2016-05-10 14:09
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-05-10 14:09 UTC
Labels: needs reply, v2, virtualscroll
