### ISSUE TITLE
New ion-img has images unloaded 

### ISSUE THREAD

**Issue by shakirthow** [driftyco/ionic#10487] opened 2017-02-17 21:02 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Create a virtualScroll list with each list having a <ion-img> element. Now scroll to the bottom of the list. then add another element. (say like a chat window). The ion-img in the new list element has the image unloaded. After some testing using chrome debugger I can see the image is showing when I scroll to the top of the page. 

**Expected behavior:**
The new element show load the image when in view port 

**Steps to reproduce:**
Create a virtualScroll list with each list having a <ion-img> element. Now scroll to the bottom of the list. then add another element. (say like a chat window).

**Comment by justas-kuizinas** [comment] 2017-02-19 23:57
At the moment there are a lot of problems with virtual scroll, maybe anyone can suggest alternative?

**Comment by jgw96** [comment] 2017-02-21 16:37
Hello all, closing this issue as a duplicate of https://github.com/driftyco/ionic/issues/10241.

**Closed by jgw96** 2017-02-21 16:37 UTC
