### ISSUE TITLE
bug: [Bug] Modal header overlaps content

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic#8494] opened 2016-10-04 22:29 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Some of our users have manifested issues where the Modal's header overlaps the content which ends up hidding a searchbar in this specific case.

After checking the customer's pc through Team Viewer, our app, browser and data are in the same state and the only difference between them and us is that the content in ours have some top margin while theirs not.

It should technically be the same since both Chrome versions are the same and up to date, as well as the app version they have.

Note: Ionic 2.0-beta.11, can't update to RC.0 since would have to make a full rewrite due to the `SqlStorage` being deprecated (will probably copy SqlStorage only to keep it working for now).

Last note: This happens 3 times, 1 with a customer with an Android device, one of our own dev team in his IOS device and to the same first customer mentioned in the web deployed version of the app.

</span>

<span is-issue-template></span>

**Comment by jgw96** [comment] 2016-10-07 16:49
Hello, thanks for opening an issue with us! Can you make a quick test and see if this happens in RC.0 too?

**Comment by Luchillo** [comment] 2016-10-07 17:01
No sr i can't, i've been struggling the last week trying to transition from Webpack to Rollup, since my project uses like 6~8 external libs, Rollup has been hell in earth to make it work, to be honest i'm transitioning to RC.0 just because the new Router and this issue.

Hell even @danbucholtz is helping me with it in the Ionic forums in [this](https://forum.ionicframework.com/t/how-to-rollup-pollyfils/66108/8) thread.

**Comment by jgw96** [comment] 2016-10-07 17:06
Thanks for the info! I am going to go ahead and close this issue as a duplicate of https://github.com/driftyco/ionic/issues/8556 as this gets to the root of the issue. Thanks!

**Closed by jgw96** 2016-10-07 17:06 UTC
Labels: needs reply, v2
