### ISSUE TITLE
input type date and time blur if keyboard is open on iPad

### ISSUE THREAD

**Issue by mikey0000** [driftyco/ionic#2857] opened 2015-01-05 01:48 UTC
reproducible in 1.0.0 b13

select a normal text field then select a date or time field and watch as the native ios selector shows then hides again.

**Comment by drewrygh** [comment] 2015-01-05 05:19
Does this still happen after updating to beta 14, or a nightly build?

**Comment by mikey0000** [comment] 2015-01-05 05:23
Yes,  it does. I did check that actually. 

On January 5, 2015 6:20:09 PM GMT+13:00, Drew Rygh <notifications@github.com> wrote:
>Does this still happen after updating to beta 14, or a nightly build?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/driftyco/ionic/issues/2857#issuecomment-68669443

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by badams** [comment] 2015-02-28 06:45
@adamdbradley has there been any progress on this issue? anyone know of a work around?

**Comment by mikey0000** [comment] 2015-02-28 07:28
Yes, look at my fork, I made a pull request with the fix.

**Comment by badams** [comment] 2015-03-01 19:42
Thanks @mikey0000, just looking at your patch, does that cover select fields? because this issue is occurring on those fields too.

**Comment by mikey0000** [comment] 2015-03-01 19:53
Ahh, good question, I don't think so, but it shouldn't be hard to add to what I've done. Its pretty straightforward. Yell at me if you can't do it yourself after having a go.

**Comment by tlancina** [comment] 2015-03-02 17:58
Hey I'm working on select/date issues with tap and the keyboard right now.  Do you have any code that could reproduce this? I'm unable to reproduce the issue.

**Comment by mikey0000** [comment] 2015-03-02 23:14
try this one, should reproduce the issue, but haven't checked in a while. https://github.com/mikey0000/steroids-repro-template

**Comment by tlancina** [comment] 2015-03-02 23:16
Thanks! Taking a look now

**Comment by tlancina** [comment] 2015-03-02 23:36
What version of iOS is this? Still unable to reproduce, if someone could post a codepen I'll take a look.

**Comment by mikey0000** [comment] 2015-03-03 00:14
@tlancina sorry that it didn't work, we were testing on iPads and iOS 8. I unfortunately am no longer working on the project which required this so am unable to create a reproduction can anyone else in this thread still produce it? @badams

**Comment by tlancina** [comment] 2015-03-03 00:19
@mikey0000 ah thanks, I was only looking on iPhone, I see it now.  I don't think the Ionic keyboard code accounts for date and select being popovers on iPad.

**Comment by mikey0000** [comment] 2015-03-03 00:24
@tlancina brilliant, yeah I started to have a sneaking suspicion it was iPad only.

**Comment by tlancina** [comment] 2015-03-06 21:14
Pretty sure this is the same as: https://github.com/driftyco/ionic-plugins-keyboard/issues/71, caused by https://github.com/driftyco/ionic/blob/master/js/utils/keyboard.js#L104.

I'm working on refactoring our existing keyboard code, which is a slow process because of all the quirks between Android and iOS and the heavy testing involved.  This * should * be fixed in the next release (not rc0), but I'll keep everyone updated/close this once it happens.

**Comment by tcrammond** [comment] 2015-04-22 07:57
Hi,

@tlancina Is there any update on this being patched? We are having the same issue on iPads here.

**Comment by tlancina** [comment] 2015-04-22 15:34
@tcrammond are you still seeing this in nightly?

**Comment by tcrammond** [comment] 2015-04-27 07:28
Seems OK in rc4, we were on rc2 before.

Thanks @tlancina

**Comment by tlancina** [comment] 2015-04-28 01:26
Great! Going to close this then.

**Closed by tlancina** 2015-04-28 01:26 UTC
Labels: iOS, keyboard/focus
