### ISSUE TITLE
ion-slides confuses swiping when multiple instances are on a page (desktop)

### ISSUE THREAD

**Issue by suau** [driftyco/ionic#10664] opened 2017-03-06 10:52 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request

**Current behavior:**
when there are multiple `ion-slides` on a page, over-swiping (bounce) one slider will bug out the other sliders. They'll start swiping too and then turn unresponsive.
This seems to be desktop only (maybe touch vs click events)

**Expected behavior:**
multiple `ion-slides` per page should work properly without being coupled in any way.

**Steps to reproduce:**
I reproduced this on:
- Chrome for Mac 56.0.2924.87 (64-bit)
- Safari Version 10.0.3 (12602.4.8)

http://plnkr.co/edit/Bm89QtZXvFgp91KNe2FR?p=preview

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: macOS Sierra
Node Version: v6.10.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment] 2017-03-06 14:53
Thanks for opening an issue, we will look into this.

**Comment by dewiikaaa** [comment] 2017-04-13 04:33
@jgw96 I got same problem. that issue still not solved yet?

**Comment by jgw96** [comment] 2017-04-24 16:40
Hello, all! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/10542

**Closed by jgw96** 2017-04-24 16:40 UTC
Labels: slides, v2

**Comment by suau** [comment] 2017-04-24 17:12
@jgw96 I'm not sure this is the same issue, as #10542 is about nested sliders, but this one is about any sliders.

**Comment by uzumakinaruto123** [comment] 2017-08-11 05:08
@suau  is correct. @jgw96  Issue is not about nested slides here! This should be re-opened.  Currently It's impossible to use multiple slides components on same page( not nested ).

```
ionic info

cli packages: (D:\sumeet\projects\angel-bytes\angelBytes\node_modules)

    @ionic/cli-plugin-cordova       : 1.6.2
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 6.5.0

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.1.2
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 25.3.1
    Node              : v7.1.0
    OS                : Windows 7
    npm               : 3.10.9
```

**Comment by leonardopaiva** [comment] 2017-09-13 14:18
same problem here, please fix it... i have to disable the drag on desktop.
