### ISSUE TITLE
ionic2: Second tabs has no buttons for navigation under android platform with version less than 5.

### ISSUE THREAD

**Issue by raceyi** [driftyco/ionic#7837] opened 2016-08-23 13:21 UTC
#### Short description of the problem:
What I did is  moving from the first tabs page to second tabs page by calling this.app.getRootNav().push(SecondTabsPage);  
The second tabs page has no buttons for navigation at the bottom of page under android device with 4.4.2.  
ios and android device with version equal to or more than 5 work fine.

this.app.getRootNav().setRoot(SecondTabsPage) works.  
But I have to use push for back button under Android.
Any workaround? 

#### What behavior are you expecting?

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc) 

**Which Ionic Version?
2.x

**Comment by jgw96** [comment] 2016-08-23 14:35
Hello! Thanks for opening an issue with us! Would you be able to post a repo that shows a minimal example of this issue? Thanks for using Ionic!

**Comment by raceyi** [comment] 2016-08-24 10:33
Please check https://github.com/raceyi/ionic2_tabs. It is quite urgent for me. Hope this help you.

**Comment by jgw96** [comment] 2016-08-24 16:08
Hello! Does this issue https://github.com/driftyco/ionic/issues/7604 look like the same issue you are having?

**Comment by raceyi** [comment] 2016-08-24 22:34
Yes, it does. Have you reproduced this issue successfully?

**Comment by raceyi** [comment] 2016-08-24 23:15
Yes, it does. 

For my app, it works fine once I added  cordova-plugin-crosswalk-webview. 

But the sample app in  https://github.com/raceyi/ionic2_tabs still doesn't work.

Any other dependency except cordova-plugin-crosswalk-webview?

**Comment by raceyi** [comment] 2016-08-25 07:52
It frustrated me. I tested it with other phone. It still doesn't work with cordova-plugin-crosswalk-webview. Also Adding crosswalk-webview plugin makes app too slow. But previous version doesn't have this problem.

**Comment by jgw96** [comment] 2016-08-25 16:46
Hmmm, im sorry you are still having trouble with this issue. Since this issue seems to be a duplicate of #7604 i will be closing this issue. As you can see that issue is marked for beta.12 so this issue should be fixed with that release. Thanks for using Ionic!

**Closed by jgw96** 2016-08-25 16:46 UTC
Labels: v2
