### ISSUE TITLE
bug: range slider min/max with ng-model doesnt work

### ISSUE THREAD

**Issue by amitksaini78** [driftyco/ionic#1948] opened 2014-08-07 17:16 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Basically, take range input min, max and value with ng-model=user.value:
   $scope.user= {
    min:'0',
    max:'20000',
    value:'10000'
}

Steps to reproduce:

1. make a normal slider with hard coded min="0" and max="100" ng-model="user.value". it works :)

2. make a configurable slider with min="{{user.min}}" max="user.max" value= "{{user.value}}" ng-model="user.value"

Does not work :(
now remove the ng-model, it works :)

http://codepen.io/anon/pen/kqAlv

Not sure where to park this bug. Is it a ionic/angular issue?

But before you throw away this bug as not my problem consider this: Having configurable min and max with ng-model is a basic requirement of a slider!

The problem is described here in detail:
http://forum.ionicframework.com/t/how-to-make-ionic-range-slider-min-and-max-configurable-instead-of-hard-coded-0-and-100/7800</span>

<span is-issue-template></span>

**Comment by kelle62819** [comment] 2015-01-06 11:42
This appears to be an issue with angular not supporting input type="range".  I tried a pure angular project without anything ionic and the issue is still there.

**Comment by JWGmeligMeyling** [comment] 2015-02-28 12:28
Can confirm this issue

**Comment by JWGmeligMeyling** [comment] 2015-02-28 12:56
I use these directives to resolve the issue:
```js
.directive('ngMin', function() {
  return {
    restrict : 'A',
    require : ['ngModel'],
    compile: function($element, $attr) {
      return function linkDateTimeSelect(scope, element, attrs, controllers) {
        var ngModelController = controllers[0];
        scope.$watch($attr.ngMin, function watchNgMin(value) {
          element.attr('min', value);
          ngModelController.$render();
        })
      }
    }
  }
})
.directive('ngMax', function() {
  return {
    restrict : 'A',
    require : ['ngModel'],
    compile: function($element, $attr) {
      return function linkDateTimeSelect(scope, element, attrs, controllers) {
        var ngModelController = controllers[0];
        scope.$watch($attr.ngMax, function watchNgMax(value) {
          element.attr('max', value);
          ngModelController.$render();
        })
      }
    }
  }
})
```

**Comment by JavierAbrego** [comment] 2015-04-18 11:05
@JWGmeligMeyling the directives that you proposed solved my problem, thanks!

**Comment by JWGmeligMeyling** [comment] 2015-04-18 11:17
@JavierAbrego No problem :blush: Sad that this issue is still around. But I think this is more an Angular issue than an Ionic issue.

**Comment by devtosystems** [comment] 2015-06-07 06:43
Thanks @JWGmeligMeyling , Help me also!!! :+1: :+1: :+1:

**Comment by gregor-srdic** [comment] 2015-06-09 14:38
Thank you, helped me as well!!!

**Comment by ikarus-balsero** [comment] 2015-09-16 14:51
Thank you so much!!

**Comment by JWGmeligMeyling** [comment] 2015-09-16 16:03
This issue should not have been closed by @Ionitron ....
@perrygovier would my solution above be accepted as PR?

**Comment by perrygovier** [comment] 2015-09-16 18:36
I'll take another look

**Comment by perrygovier** [comment] 2015-09-16 20:39
This appears to be fixed in current versions of Angular, no? Not seeing any issues in http://codepen.io/mhartington/pen/mFtji?editors=101

**Comment by JWGmeligMeyling** [comment] 2015-09-16 20:47
Seems this is indeed fixes as of 1.3.0-rc.1 with https://github.com/angular/angular.js/commit/7b273a2c978d5f5ef374f5335afab0ca7d8cfd4d (issue https://github.com/angular/angular.js/issues/2404). Codepin was not updated yet.
This issue can now be closed :smile:

**Comment by Ionitron** [comment] 2015-10-16 21:30
Greetings @amitksaini78!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-10-16 21:30 UTC
Labels: ionitron:closed, range

**Comment by seb-bizeul** [comment] 2016-01-12 08:26
The issue is still there. I' m using Ionic cli 2.0.0-beta.12.

**Comment by Mimateam** [comment] 2016-03-14 00:05
Yeap, we can also confirm issue is still here. Using Ionic 1.2.4 and Angular v1.4.3.

This code doesnt work:
`<input type="range" name="data-freq" min="{{dataFreqMin}}" max="{{dataFreqMax}}" value="{{dataFreq}}" ng-model="dataFreq" ng-change="dragDataFreq(dataFreq)">`

And this one does:
`<input type="range" name="data-freq" min="{{dataFreqMin}}" max="1000" value="{{dataFreq}}" ng-model="dataFreq" ng-change="dragDataFreq(dataFreq)">`

[(Exactly the same issue as http://codepen.io/mhartington/pen/mFtji)]

**Comment by DanielePalombo** [comment] 2016-04-09 15:30
+1

**Comment by amoraes** [comment] 2016-04-13 13:12
Struggling with the same issue here...
Ionic 1.2.4 and Angular v1.4.3 too.

**Comment by joaotocilo** [comment] 2016-04-20 13:02
@Mimateam try use _**ng-max / ng-min**_ instead _**max / min**_. It's works for me

`<input type="range" name="data-freq" ng-min="dataFreqMin" ng-max="dataFreqMax" value="{{dataFreq}}" ng-model="dataFreq" ng-change="dragDataFreq(dataFreq)">`

**Comment by blackstylle** [comment] 2016-05-12 12:01
+1 same problem with Ionic 1.2.4 and 1.3

**Comment by vTrip** [comment] 2016-06-30 04:37
+1
my issue is that the slider has the correct value but does not show the correct value on the slide as it always has an initial position of '0'

Using both value and ng-model

When removing ng-model, problem is solved however I do not get real time update of value when the user drags.

Ionic 1.3.1

**Comment by skotturi** [comment] 2016-07-18 06:11
+1 

Still seeing this in angular 1.5.3 (ionic 1.3.1). 

```
           <input type="range"
                   min="{{minPointsCorrection}}"
                   max="{{maxPointsCorrection}}"
                   value="{{estimatedPoints}}"
                   name="estimatedPointsCorrection"
                   ng-model="activity.estimatedPoints">
```

yields an initial position: 
![image](https://cloud.githubusercontent.com/assets/4960284/16906908/4a7aff5c-4c73-11e6-9a6d-05f5798cc142.png)

where the estimatedPoints is exactly in the middle of the min & max. 
Removing `ng-model` doesn't fix it for me. 

Seems related to: https://github.com/angular/angular.js/issues/6726
which was just picked up by Martin on angular 1 core team 12 days ago.

**Comment by AnthStep** [comment] 2016-12-07 01:17
worked for me 

<input type="range" ng-model="val" id="input" min={{min}} step={{step}} />

in controller: 
angular.element(document.querySelector("#input")).attr("max", $scope.max)
