### ISSUE TITLE
Weird square appearing on Android devices

### ISSUE THREAD

**Issue by bgoetzmann** [driftyco/ionic#7549] opened 2016-08-04 20:34 UTC
This [link](https://forum.ionicframework.com/t/an-annoying-little-square-on-android-devices/59529) describes the problem of a weird square appearing on Android devices, with Ionic 2 applications, and how to reproduce it using a starter application.

**Comment by jgw96** [comment] 2016-08-04 20:37
Hello, thanks for opening an issue with us! I am going to be closing this issue as a duplicate of https://github.com/driftyco/ionic/issues/6416. Thanks for using Ionic!

**Closed by jgw96** 2016-08-04 20:37 UTC
Labels: platform:android, v2
