### ISSUE TITLE
ion-select buttons 'cancel' and 'ok' disappears in landscape mode

### ISSUE THREAD

**Issue by chandanch** [driftyco/ionic#11022] opened 2017-04-03 06:15 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The 'cancel' and 'ok' buttons for ion-select is hidden when the orientation in phone is changed to landscape mode. This happens if there are more than 4 items in the list.
**Expected behavior:**
The 'cancel and 'ok' buttons must appear even in the landscape mode and must be fixed similar to the item label with a capability to scroll only the items in the select list.

**Steps to reproduce:**
1. Create an ion-select component and add 5 to 6 items to the select list
2. Run the app in chrome browser and open the developer tools
3. Click on the 'toogle device toolbar'.
4. In the browser window select  iphone 5.
5. Click on the 'rotate' button to change the orientation to landscape.

Refer to this plunker: http://plnkr.co/edit/UMCVVJ?p=preview 

Refer to this screenshot: https://ibb.co/eyQgfa 

**Other information:**: 
Refer to this on forum [75868](https://forum.ionicframework.com/t/ion-select-in-landscape-orientation-mode/75868)
**Ionic info:**:

```
Cordova CLI: 6.5.0 
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
ios-deploy version: Not installed
ios-sim version: 5.0.8 
OS: macOS Sierra
Node Version: v6.10.1
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment] 2017-04-03 18:54
Hello, thanks for opening an issue with us. I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/6326 as that issue and this issue are caused by the same underlying bug.

**Closed by jgw96** 2017-04-03 18:54 UTC
