### ISSUE TITLE
bug: high performance on collection-repeat with defined objects

### ISSUE THREAD

**Issue by machei** [driftyco/ionic#4142] opened 2015-07-24 13:55 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>As topic as topic. Why 4 called times per row for getting double first name? Object-defined isn't friendly for directive collection-repeat?

Link: http://codepen.io/machei/full/dogOro/</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-07-24 13:56
Greetings @machei!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4142). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4142)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment] 2015-07-27 20:20
The example you are pointing to is from beta9. Please update the codepen to the latest and check to see if the issue is still there.

**Comment by machei** [comment] 2015-07-28 01:15
My codepen has been updated to the latest version 1.0.1. So 3 replies per one first name - seems that is more double than prevouis. Not good.

 http://codepen.io/machei/full/dogOro/

**Comment by mhartington** [comment] 2015-07-28 14:41
The error is just with the way data is being returned in that codepen, not with collection repeat.

http://codepen.io/mhartington/pen/XbyjyR

**Comment by machei** [comment] 2015-07-28 15:03
U are wrong with code but nothing isnt relating to object-defined. Need fix for improviving performance, should be only one called access to variable in purpose to reading value.

http://codepen.io/machei/full/aOQmMV/ -> Please, replaced object-defined method with your codepen and look at console.

Please. reopen issue.

**Comment by jgw96** [comment] 2016-06-21 19:11
Hello all! I will be closing this for now as i am not seeing any performance issues on any of my devices, including my old Moto X 2014 and Nexus 7 2013. Thanks for using Ionic!

**Closed by jgw96** 2016-06-21 19:11 UTC
Labels: collection-repeat, v1
