### ISSUE TITLE
swipeBackEnabled="true" opens menu and pops a page simultaneously

### ISSUE THREAD

**Issue by callodacity** [driftyco/ionic#6508] opened 2016-05-12 05:44 UTC
#### Short description of the problem:
Not exactly sure if this is intended or not, but I looked through the open and closed issues and I didn't find anything that came close...

**Problem**
When `swipeBackEnabled="true"` on `<ion-nav>`,
swiping back _goes back one page, **and** opens the sidemenu_.
(Happens in _both_ iOS and Android)

#### What behavior are you expecting?
I would expect that either:
- if there are pages on the nav stack, that it goes back one page (equivalent of `nav.pop()`). If there are no pages (e.g. on root page) the sidemenu would open; or
- regardless of the amount of pages on the stack, it would open the sidemenu. 

However, I think that the intended design _is not_ for both to happen at the same time!!

**Steps to reproduce:**
1. `ionic start test sidemenu --ts --v2`
2. `cd test && ionic serve --lab`
3. change `swipeBackEnabled="false"` to `swipeBackEnabled="true"` in `app.html`
4. go to the list page, put more than one page on the stack (clicking on items), and then attempt to swipe back one page.

**Here's the Plunker**
http://plnkr.co/edit/LZ8z52vixMr5lIDbPLg6?p=preview
This Plunker demonstrates an Android (Material Design) template, I would recommend looking at iOS as well as the issue it much easier to see with iOS's swipe back animation.

**Which Ionic Version?**  2.x

    Cordova CLI: 6.1.1
    Ionic Framework Version: 2.0.0-beta.6
    Ionic CLI Version: 2.0.0-beta.25
    Ionic App Lib Version: 2.0.0-beta.15
    ios-deploy version: 1.8.6
    ios-sim version: 5.0.8
    OS: Mac OS X El Capitan
    Node Version: v4.4.3
    Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by Manduro** [comment] 2016-05-13 15:34
Duplicate of #5575

**Comment by brandyscarney** [comment] 2016-05-13 17:55
Thanks @Manduro. Closing as a duplicate of #5575, but thanks for the issue @callodacity!

**Closed by brandyscarney** 2016-05-13 17:55 UTC
Labels: menus, v2
