### ISSUE TITLE
Multirow textarea resizes when scrolling

### ISSUE THREAD

**Issue by moberg** [driftyco/ionic#2619] opened 2014-11-27 01:44 UTC
When scrolling a view with a multi row textarea, the text area changes height while scrolling. After scrolling the original height is restored. This happens in the Chrome device emulator (emulating iPhone) and on iOS devices. 

Example of the resizing:
https://www.youtube.com/watch?v=iMYaScyFL74

Codepen: http://codepen.io/moberg/pen/myyYMJ

It seems like this is caused by that the text area is cloned and the clone doesn't have the "rows" property:
http://forum.ionicframework.com/uploads/default/7480/ebacc8d0d243712c.png

**Comment by bassettsj** [comment] 2015-01-07 22:26
I am also having the same issue, not necessarily with having the `[rows]` attribute copied but with inline style declarations that are added with angular-elastic.

**Comment by adamdbradley** [comment] 2015-02-11 17:05
Duplicate of #1934, but working on a solution. Thanks

**Closed by adamdbradley** 2015-02-11 17:05 UTC
Labels: css, iOS, keyboard/focus
