### ISSUE TITLE
Ionic ion-input showing white screen when input field is clicked and keyboard comes.Issue in real devices as well as simulator.Here is my html page for which i am facing this issue.

### ISSUE THREAD

**Issue by rhuldip** [driftyco/ionic#8012] opened 2016-09-08 09:59 UTC
```
<ion-header>
  <ion-navbar>
    <button menuToggle>
      <ion-icon name="menu"></ion-icon>
    </button>
    <ion-title>Hello Ionic</ion-title>
  </ion-navbar>
</ion-header>


<ion-content padding class="getting-started">
<ion-scroll scrollY="true" style="height:100%;background-color:#efefef">
  <h3>Welcome to your first Ionic app!</h3>

  <p>
    This starter project is our way of helping you get a functional app running in record time.
  </p>
  <p>
    Follow along on the tutorial section of the Ionic docs!
  </p>
  <p>
    <button primary menuToggle>Toggle Menu</button>
  </p>
  
    <ion-input type="text" class="newRequestOtherTextBox" placeholder="Create Activity Entry" ></ion-input>
    <ion-input type="text" class="newRequestOtherTextBox" placeholder="Create Activity Entry" ></ion-input>
    <ion-input type="text" class="newRequestOtherTextBox" placeholder="Create Activity Entry" ></ion-input>
    <ion-input type="text" class="newRequestOtherTextBox" placeholder="Create Activity Entry" ></ion-input>
    <ion-input type="text" class="newRequestOtherTextBox" placeholder="Create Activity Entry" ></ion-input>
    <ion-input type="text" class="newRequestOtherTextBox" placeholder="Create Activity Entry" ></ion-input>
  </ion-scroll>
</ion-content>

```

**Comment by rhuldip** [comment] 2016-09-08 10:02
I can see similar issue for ionic 1 but no solution for ionic 2...[https://github.com/driftyco/ionic/issues/4849](url)

**Comment by jgw96** [comment] 2016-09-08 16:24
Hello, thanks for opening an issue with us! As this issue is a duplicate of https://github.com/driftyco/ionic/issues/6229 I am going to close this issue for now. Thanks for using Ionic!

**Closed by jgw96** 2016-09-08 16:24 UTC
Labels: header, keyboard, menus
