### ISSUE TITLE
Alert input's label not showing

### ISSUE THREAD

**Issue by dheran** [driftyco/ionic#6354] opened 2016-04-28 07:16 UTC
**Ionic 2**

http://ionicframework.com/docs/v2/api/components/alert/Alert/#create
```

inputs: [
                {
                    name: 'data',
                    placeholder: 'Enter here',
                    type: 'text',
                    label: 'Data',
                    id: 'myid'
                },
            ],
```

**Comment by jgw96** [comment] 2016-04-28 15:41
Hello @dheran ! Would you be able to provide a plunker of codepen that i can use to reproduce this issue with the same code your using?

**Comment by jgw96** [comment] 2016-05-04 15:10
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-05-04 15:10 UTC
Labels: alert, needs reply, v2

**Comment by AmalBouhniz** [comment] 2017-03-09 14:59
Hi all! I have the same issue as @dheran, alert input's label is not showing using alertController. Apparently, i cannot use label for input text, only for radio/checkbox inputs. Is there anyway that i can add label for my alert input? Thanks in advance.

**Comment by ronchimar** [comment] 2018-02-12 14:25
Same issue here...

**Comment by hdlopesrocha** [comment] 2018-03-02 14:29
Why was this closed? 
I have the same problem.

**Comment by wormling** [comment] 2018-03-02 14:33
Same problem but just used ModalController instead.
