### ISSUE TITLE
Menu, ion-navbar and ion-header bugs

### ISSUE THREAD

**Issue by lordgreg** [driftyco/ionic#7170] opened 2016-07-02 16:01 UTC
#### Short description of the problem:
Problem 1: Having ion-navbar with attribute `primary`, `secondary`, `danger`,... inside menu template, doesn't show proper background color because `opacity: 0` is set for `ion-navbar.toolbar`.

Problem 2: Puting ion-navbar inside ion-header as the docs now state, breaks all the things. 

#### What behavior are you expecting?
Both things to work?

#### to reproduce the Problem 2, just remove the comments for ion-header.
```
<ion-menu [content]="mycontent">
  <!--<ion-header>-->
    <ion-navbar danger>
      <ion-title>
        Page Title
      </ion-title>
    </ion-navbar>
  <!--</ion-header>-->

  <ion-content light>
    <ion-list>
      <ion-item>
        header
      </ion-item>
      <ion-item>
        yolo molo
      </ion-item>
    </ion-list>
  </ion-content>
</ion-menu>

<ion-nav #mycontent [root]="rootPage"></ion-nav>
```

**Which Ionic Version?** 1.x or 2.x
Ionic 2 beta10

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

```
Your system information:

You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.2.0

Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.31
Ionic App Lib Version: 2.0.0-beta.17
OS:
Node Version: v5.9.1
```

**Comment by SebastianGiro** [comment] 2016-07-03 01:03
Im having the same problems with beta10 and ion-header bugs

Most of all, the ion-header sometimes (with tabs and segments) dont do the correct margins between ion-content ion-tabs ion-segments

**Comment by manucorporat** [comment] 2016-07-03 08:40
Problem 2 looks like a duplicate of https://github.com/driftyco/ionic/issues/7138

**Comment by jgw96** [comment] 2016-07-05 15:20
@lordgreg would you mind making a plunker that demonstrates this issue? Thanks!

**Comment by lordgreg** [comment] 2016-07-05 20:59
@jgw96 done.

http://plnkr.co/edit/tyiZYO7MJXvGZQTccOaC?p=preview

Just open the menu (app.ts) and check the ion-menu navbar color and title. Happy bugfixing :+1:

**Comment by brandyscarney** [comment] 2016-07-07 19:50
Yes, problem 2 is a duplicate of #7138. It will be fixed in the `beta 11` release.

For problem 1 - why are you using a navbar in a menu? Could you explain the use case for this over using a toolbar?

**Comment by lordgreg** [comment] 2016-07-07 20:05
@brandyscarney thank you for your feedback. I am not sure about the navbar/toolbar usage, probably because I'm used to calling top part navbar. Didn't payed too much attention in that matter..

**Comment by brandyscarney** [comment] 2016-07-07 20:21
@lordgreg Yeah so the `ion-navbar` should really only be used for navigation. It adds things like the back button and animation between views. An `ion-toolbar` should be used in a menu. :) We can add some more documentation on this to make it more clear.

**Comment by lordgreg** [comment] 2016-07-07 20:23
Thank you for your explanation. Hopefully, one day we'll have menu navigation as the ios has, clicking menu item will navigate menu's stack and main content's stack, but that's nothing to discuss in this thread. As I am concerned, this issue can be closed :+1:

**Comment by brandyscarney** [comment] 2016-07-08 01:18
I think the navigation in the menu is something that does need to be handled. This will need to be added for https://github.com/driftyco/ionic/issues/6793. I created an issue to add some documentation for when to use navbar/toolbar though: https://github.com/driftyco/ionic-site/issues/685

Thanks for the issue!

**Closed by brandyscarney** 2016-07-08 01:18 UTC
Labels: header, menus, v2
