### ISSUE TITLE
TypeError: o.split is not a function. (In 'o.split(" ")', 'o.split' is undefined)

### ISSUE THREAD

**Issue by KevinBeckers** [driftyco/ionic#7981] opened 2016-09-05 15:31 UTC
TypeError: o.split is not a function. (In 'o.split(" ")', 'o.split' is undefined)

I wil get this error on every click on for example ng-click or <a menu-toggle="right">
It appears only when I use 'ionic.service.core', 'ionic.service.analytics'

I am using ionic 2.

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
ios-deploy version: 1.8.6
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v5.6.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment] 2016-09-06 12:42
Hello! Thanks for using Ionic! Would you be able to share a repo or code snippet I can use to reproduce this issue? Thanks for using Ionic!

**Comment by jgw96** [comment] 2016-09-09 14:52
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-09-09 14:52 UTC
Labels: needs reply, v2

**Comment by LehmanHe** [comment] 2016-09-20 07:51
I get a similar bug:
EXCEPTION: Error: Uncaught (in promise): TypeError: this.invoiceData.split is not a function

ionic info:
Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: Not installed
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.4.7
Xcode version: Xcode 8.0 Build version 8A218a
