### ISSUE TITLE
Icon and splashscreen cannot be customized after upgrade RC5

### ISSUE THREAD

**Issue by iraychen** [driftyco/ionic#10065] opened 2017-01-17 06:32 UTC
When I upgraded to the RC5 version, I found that the icon and splashscreen could not be customized. 
I using ：**ionic platform add android** ，the default version is 6.0.0。Use the splashscreen plugin is no useful。

Finally, the creation of the Android platform to select the latest version was found to be able to use：**ionic platform add android@latest**。

Ionic version:
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.2.0
Xcode version: Not installed

**Comment by infinnie** [comment] 2017-01-17 06:34
#10056

**Comment by brandyscarney** [comment] 2017-01-17 17:16
Closing as a duplicate of #10056, thanks!

**Closed by brandyscarney** 2017-01-17 17:16 UTC
