### ISSUE TITLE
ionic2: ion-slides zoom notworking

### ISSUE THREAD

**Issue by emps** [driftyco/ionic#5459] opened 2016-02-15 12:55 UTC
```
<ion-content class="picture">
    <ion-slides loop="false" autoplay="false" pager="false" zoom="1" zoomDuration="1" zoomMax="10">
        <ion-slide style="background-color: black" >
            <img src="{{picture.url.m}}"/>
        </ion-slide>
    </ion-slides>
</ion-content>
```
zoom not working any can help, thanks, ( i have tried many variants )

**Comment by brandyscarney** [comment] 2016-02-16 16:06
Thanks for the issue! This is a duplicate of https://github.com/driftyco/ionic/issues/5039

**Closed by brandyscarney** 2016-02-16 16:06 UTC
Labels: v2

**Comment by cukorlyon87** [comment] 2017-09-11 08:57
Hi ionic team,

Please, any news about this? We are waiting a lot of time and we need this feature, please tell me something, because your college told that you are working in this, but we are 11th September... and it is not working... thanks.
