### ISSUE TITLE
How to use ionic spinner from class.I need to make a web service call.For example when user click in login,i will call web service  at that time i need to start the spinner.If the user is valid i need to move the user to next page and then load all data in second page and then stop the spinner.In Ionic 1,i used to do this-

### ISSUE THREAD

**Issue by rhuldip** [driftyco/ionic#7718] opened 2016-08-14 19:34 UTC
`StartSpin: function ()
		{
          $ionicLoading.show({
			  template: '<ion-spinner class="spinner-calm"></ion-spinner>',
			  animation: 'fade-in',
                showBackdrop: true,
			});
		},
		//StopSpin
		StopSpin:function ()
		{
			  $ionicLoading.hide();
		}

**Comment by danbucholtz** [comment] 2016-08-15 04:38
Hi @rhuldip,

Since this is not a bug in the framework, we are going to close this issue.  Please take any requests for help to our [community help forum](https://forum.ionicframework.com/?utm_source=framework&utm_medium=navbar&utm_campaign=forum%20CTA).  Stackoverflow is also great!

Please let me know if you have any questions.

Thanks,
Dan

**Closed by danbucholtz** 2016-08-15 04:38 UTC
Labels: animation, v2

**Comment by rhuldip** [comment] 2016-08-16 06:12
Hi danbucholtz,

This is an issue with documentation,no proper documentation is present to control spinner from back end.

Thanks,
R Deep
