### ISSUE TITLE
strange small grey rectangle below top menu

### ISSUE THREAD

**Issue by zeroonea** [driftyco/ionic#8384] opened 2016-10-01 09:40 UTC
There is a strange small grey rectangle below top menu.
1. Start fresh ionic 2 tutorial app
2. Open menu
3. Tap My First List
4. You will see it like picture: https://i.imgur.com/gQYTF8A.jpg

**Comment by manucorporat** [comment] 2016-10-01 10:46
Can you run `ionic info` and post the results?

**Comment by zeroonea** [comment] 2016-10-01 17:57
Sure

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS:
Node Version: v6.7.0

**Comment by brandyscarney** [comment] 2016-10-03 15:47
Hmmm looks like this issue popped back up again: https://github.com/driftyco/ionic/issues/6416

**Comment by edismooth** [comment] 2016-10-13 11:36
I've got the same issue in ionic2 RC0. #6416 solution doesn't work.

**Comment by unfg** [comment] 2016-10-17 11:50
I also have the same problem in ionic2 RC0.

**Comment by laserus** [comment] 2016-10-19 08:08
Yes, that is exactly the same as in #6416

**Comment by unfg** [comment] 2016-10-19 08:24
I have this problem, when i create page with ModalController.

**Comment by jbw91** [comment] 2016-10-20 05:33
I have this issue as well in RC0.

**Comment by brandyscarney** [comment] 2017-01-24 23:57
Closing as a duplicate of #6416

**Closed by brandyscarney** 2017-01-24 23:57 UTC
Labels: v2
