### ISSUE TITLE
Center titles on material design

### ISSUE THREAD

**Issue by slippyC** [driftyco/ionic#5490] opened 2016-02-17 18:51 UTC
This is easily reproducible.  

Whenever you push() a new view if you click back button it will not fire.  I think it is a bubbling issue.  If you click right outside the actual arrow back button, right above or below it will fire.  It seems if the `ion-icon` embed within the button is not bubbling up to button.  
### Expected behavior

When clicking on back icon, it should go back instead of clicking above or below.
### App configuration

**Ionic Version**
Newest beta v2

**Operating systems**
(Android 5.0 Chrome)
(Linux Chrome)
### Development Computer configuration

Chrome Linux
WebStorm

**Comment by adamdbradley** [comment] 2016-02-17 20:21
That very well could be the problem with events not bubbling up, but I'm actually having troubles reproducing the issue. Could you try add `pointer-events: none;` to `.back-button-icon`? So it'd be:

```
.back-button-icon {
    pointer-events: none;
}
```

Could you try adding that to your app, and see if it fixes this issue, and still works in chrome and with a mouse? Thanks

**Comment by slippyC** [comment] 2016-02-17 21:54
Yea, I'll try it when it get home from work tonight...

**Comment by slippyC** [comment] 2016-02-18 05:08
Alright, here's the situation.  If I emulate Android in Chrome on Linux then I still get the same problem.  If I just let browser, as I normally would, it works.  It looks as if it is same as it would be in IOS in chrome without emulator on Linux.  There is no back text by back button on Android, where it is on Linux Chrome and iOS. Which is the way it is probably suppose to be.  

I will do a little more research.  I ended up staying out a lot later than I anticipated.  I was on-site doing work at a local restaurant here and one of my friends showed up.  It was end of day and, well, we had a few brews and a couple or 3 bourbons and coke.  

If you emulate any of the Nexus or Android based OSes in Chrome, you will have to click below or above the back arrow icon.  If you click directly on button, it shouldn't be going back.  Or at least that is what's happening on my end.  

Like I said, I've had a couple and about to eat me a lil something I got going in the oven.  I'll look more into over the next day or so.  Try and have a good night and will holllar back probably tomorrow night.

**Comment by slippyC** [comment] 2016-02-18 19:02
Figured out what is causing it. 

What is happening is in `ion-navbar` when you have an `ion-title` within it, it is overlaying the middle part of that back button.  `<div class="toolbar-title"></div>` That is getting inserted is going across the entire `ion-navbar`.  Easy fix would be to have a different z-index or something.

**Comment by adamdbradley** [comment] 2016-02-22 16:56
Is this happening with the iOS look on Android? For Material Design, the title should be to the right of the back button, not over it. But with iOS the title does go over the back button, which is why I ask. I haven't been able to reproduce this issue. Is there anything you've changed about the default setup?

**Comment by slippyC** [comment] 2016-02-22 19:40
iOS works fine.  

The title is to the right  of button on Android.  It is centered on the navbar.  The deal is the title's div tag goes pretty much all the way across the navbar.  Which happens to overlay the back button.  You could either have title added before the back button in code or you can just use a higher z-index than the title.  

![nav-title](https://cloud.githubusercontent.com/assets/7526138/13230138/d5acc24a-d969-11e5-918f-196ec2a98bb9.png)

**Comment by adamdbradley** [comment] 2016-02-23 03:14
How are you centering the toolbar-title? By default the title should be aligned left, next to the back button.

**Comment by slippyC** [comment] 2016-02-23 13:52
I'm not aligning it.  That is how it does out of box.  I think you are thinking about the "back" beside the button on iOS.  There is no "back" by arrow on Android.  The title centers on iOS as well.

**Comment by slippyC** [comment] 2016-02-23 14:21
Ahhh, I see what you are saying.  I removed '<ion-title>' and it does go right of button that way.  Hmm, I think I would rather have it centered. I guess I'll just have to keep using the z-index higher than '<ion-title>` if I want it that way.

My bad, if it is intended that way...

**Comment by adamdbradley** [comment] 2016-02-23 15:01
Yeah we're sticking to how the platform looks, but I agree it should be easier to center the title if you want it centered. Where I'm confused is how the title is centering itself on your app, I'm not able to replicate that in any of our e2e apps.

**Comment by slippyC** [comment] 2016-02-23 15:27
The `<ion-title>` is centering it, which in-turn is making that overlay.  From looking at some different tutorials it was used that way and I assumed that was the correct way to do.  If the correct way to do a `<ion-navbar>` is not using `<ion-title>` then it works as expected.  If it is encouraged to use `<ion-title>` within an `<ion-navbar>` then it isn't working as it should.  

Mainly, the question you are asking is why it is centering and overlaying.  It is because of the `<ion-title>` though.

**Comment by slippyC** [comment] 2016-02-23 21:49
One other thing...

Thanks for your help!!!!!

**Comment by jgw96** [comment] 2017-05-02 16:01
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-05-02 16:01 UTC
Labels: header, v2
