### ISSUE TITLE
TypeError: null is not an object (evaluating 'content.offsetX') iOS/Cordova

### ISSUE THREAD

**Issue by gdjennings** [driftyco/ionic#3205] opened 2015-03-01 05:48 UTC
Seeing this error regularly.
    [Error] TypeError: null is not an object (evaluating 'content.offsetX')
        (anonymous function) (ionic-angular.js, line 10530)
        (anonymous function) (ionic.js, line 208)

Doesn't appear to have an noticeable side-effect. Replacing context.offsetX with this.offsetX gets rid of the TypeError

**Comment by Ionitron** [comment] 2015-03-01 05:48
Greetings @gdjennings!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3205). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3205)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment] 2015-03-13 21:18
Duplicate of #3206

**Closed by mhartington** 2015-03-13 21:18 UTC

**Comment by drkhannah** [comment] 2015-03-23 20:01
I'm getting this too, someone please answer

**Comment by mhartington** [comment] 2015-03-23 20:03
Please provide a demo in the original issue, #3206

**Comment by drkhannah** [comment] 2015-03-23 20:33
my project is huge i can't throw it in a demo, I'm not setting context.offsetX, i think its happening because of my left drawer navigation, happens when i click a link in the left drawer to navigate to that view
