### ISSUE TITLE
NavController.remove() doesnt work as expected.

### ISSUE THREAD

**Issue by NoNameProvided** [driftyco/ionic#8442] opened 2016-10-03 15:50 UTC
#### Short description of the problem:

The `NavController.remove` function doesnt work as docs states. It cant remove pages in some cases when it should be able to.

#### What behavior are you expecting?

`NavController.remove` works as docs states and remove pages from the stack the correct way.

**Steps to reproduce:**

For testing you will have to expose the `NavController` in the last page with `console.log`. (In the constructor add `console.log(this.nav)`);

We will use this code snippet to list the stack, because no built in options exist for it now at the moment. 

```js
[
(temp1.getByIndex(0))?temp1.getByIndex(0).instance:null,
(temp1.getByIndex(1))?temp1.getByIndex(1).instance:null,
(temp1.getByIndex(2))?temp1.getByIndex(2).instance:null,
(temp1.getByIndex(3))?temp1.getByIndex(3).instance:null,
(temp1.getByIndex(4))?temp1.getByIndex(4).instance:null,
(temp1.getByIndex(5))?temp1.getByIndex(5).instance:null,
]
```

1. Push 5 pages to the stack. (The fifth element in the above snipets, confirms our stack is 5 element long.)
2. In the last page run the code snippet above to check the stack
3. Run the following code in the console: `temp1.remove(temp1.length() - 2, 2)`
5. Check the stack with the snippet above, and notice that only the last element was removed from the stack not the last 2. 

Note: This seems not to work only if I try to remove the last 2 page. With the last 1 or 3 it works well. So `temp1.remove(temp1.length() - 1, 1)` and `temp1.remove(temp1.length() - 2, 2)` produces the same result.

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
```
Cordova CLI: 6.3.1
Gulp version:  CLI version 1.2.2
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.3.1
Xcode version: Xcode 8.0 Build version 8A218a 
```

**Comment by rodriguesgm** [comment] 2016-10-07 01:37
same problem for me here.
I have this code that worked on Beta11 but in RC0 it's not working anymore. 

`this.nav.push(MyNextPage, params).then(() => {
  this.nav.remove(this.nav.getActive().index - 1, 1);
});`

I tried to remove the nav.remove from inside the promise but it didn't work either

**Comment by NoNameProvided** [comment] 2016-10-07 15:39
Do we have any official hint how to handle this in the meantime? 

Our navigation is heavily based on this function. We have pretty hard time figuring out how to solve this efficiently without making big modifications to our current navigation.

**Comment by mlynch** [comment] 2016-10-09 00:07
@rodriguesgm can you explain the effect you are going for there? You want to push a new page and then once that's pushed, remove the page you just came from?

I just tested this and the case of removing `1` works for me, digging deeper.

**Comment by mlynch** [comment] 2016-10-09 00:30
Weird, this does appear to only break for me once the stack is >= 5. Anyone have a test project to share? I'm not seeing any issues when stack < 5.

**Comment by mlynch** [comment] 2016-10-09 00:46
I found the issue, fixing

**Comment by mlynch** [comment] 2016-10-09 01:23
Thanks for the info everyone, this is fixed and will be in the next release.

**Closed** 2016-10-09 01:22 UTC
Labels: v2

**Comment by jourdan-jobox** [comment] 2016-10-14 00:41
Hi @mlynch, thanks for the fix! Been trying to debug this for a couple hours, glad to see this issue has been resolved.

Would love for it to be released very soon however :) :) :)

**Comment by numerized** [comment] 2017-06-15 11:29
There's a regression on this ?

I have still this issue

**Comment by ThalesMatoso** [comment] 2017-07-05 21:25
There's a regression on this ?

I have still this issue

this.navCtrl.remove not work

**Comment by renanmoraes** [comment] 2017-07-06 12:03
There's a regression on this ?

I have still this issue

this.navCtrl.remove not work

**Comment by manuvalentim** [comment] 2017-07-06 12:08
I have the same problem.

this.navCtrl.remove not work

**Comment by NoNameProvided** [comment] 2017-07-06 12:45
If you provide some step you did to debug the problem, and cc a team member, maybe it will be checked sooner.

**Comment by renanmoraes** [comment] 2017-07-06 13:13
Problem solved [https://github.com/ionic-team/ionic/issues/12238](#12238)

**Comment by supryin** [comment] 2017-08-06 16:31
I am still facing this issue. Ionic-angular 3.5.3.
isTransitioning is still true after remove

**Comment by numerized** [comment] 2017-08-07 13:33
me too.

**Comment by ma77hi4s** [comment] 2017-10-17 07:32
Not sure, if it's the same problem, but it looks like this...
Removing from nav stack does not work on production/release builds.
On debug builds it works as expected...

Working with ionic-angular 3.7.1

**Comment by JeongJun-Lee** [comment] 2018-05-23 19:00
This issue is still at ionic-angular@3.9.2. Please reopen it.
