### ISSUE TITLE
expose-aside-when="large" doesn't work if side="right" 

### ISSUE THREAD

**Issue by Jarek300** [driftyco/ionic#2767] opened 2014-12-19 10:03 UTC
The exposed menu is on the right but if you click/tap any item, menu moves to the left and becomes empty. Menu doesn't move to the left it the clicked menu item doesn't have the attribute 'menu-close'.

**Comment by Ionitron** [comment] 2015-03-30 23:30
Greetings @Jarek300!

My sensors indicate that I require more information in order to assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this happen occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com), where many humans will be able to offer wisdom and advice.

Thank you for allowing me to assist you.

<span ionitron-needs-reply></span>

**Comment by Jarek300** [comment] 2015-04-02 09:09
Hello!

 

I don’t use this layout anymore.

 

But I’ve found in my SVN version from December that exposes the problem. Serve it with ‘ionic serve’,  open in Google Chrome and click  ‘App diagrams’, ‘User diagrams’ or ‘Alarms. Right side menu disappears.

 

Btw. My  few colleges that use Windows Phone or Internet Explorer grumble and put pressure that we can’t use Ionic because it doesn’t support their system. The main problem is that ion-popover-view doesn’t work on their system. Doesn’t work literally , you click it and nothing happens.

 

Jarosław JASIŃSKI

mailto:jja@askom.com.pl
ASKOM Spółka z o.o. <http://www.askom.com.pl/>

**Comment by perrygovier** [comment] 2015-05-20 23:18
Is this still an issue then?

**Comment by Ionitron** [comment] 2015-06-20 08:29
Greetings @Jarek300!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment] 2015-06-20 08:29
Greetings @Jarek300!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-06-20 08:29 UTC
Labels: ionitron:closed
