### ISSUE TITLE
dynamically change menu side direction when change document direction

### ISSUE THREAD

**Issue by BahgatMashaly** [driftyco/ionic#9526] opened 2016-12-07 07:25 UTC
how to dynamically change menu side direction when change document direction?
i tried to change it manually by this code but  it doesn't  work
<ion-menu [content]="content" [side]="platform.isRTL()==true?'right':'left'">

also when use this code 
<ion-menu [content]="content" [side]="direction" >
it doesn't work when change "direction" variable
 

thanks in advance.

**Comment by mashaly100200** [comment] 2016-12-11 11:45
the problem  related to to two files the first is  "/node_modules/ionic-angular/components/menu/menu.js"
in the function

 Menu.prototype._getType = function () {
         if (!this._type) {
            this._type = MenuController.create(this.type, this, this._platform);
            if (this._config.get('animate') === false) {
                this._type.ani.duration(0);
            }
         }
        return this._type;
    };



we can comment “if condition” but it will create type every time so we can keep if condition and  reset  this._type  when change menu side direction  “i don’t know how do do this”



the second file is
 “node_modules/ionic-angular/components/menu/menu.scss”
in this code

ion-menu[side=right] > .menu-inner {
  right: 0;
  left: auto;
}
 
we should mack it dynamic >>  disable it when change direction to “ltr”  and reenable it when change direction to “rtl”


hope to fix it in the next version

**Comment by mashaly100200** [comment] 2016-12-11 12:34
to solve css issue we can use this cod

this.menu.getMenus()[0].setElementAttribute("side","left")
or
this.menu.getMenus()[0].setElementAttribute("side","right")

note:
0 means the app have one menu

**Comment by AmitMY** [comment] 2017-04-07 10:50
@brandyscarney I see you are tagged here. Is this in the visible future roadmap? (it's important adding the middle eastern locales)

**Comment by jgw96** [comment] 2017-04-07 14:06
Hello, thanks for using Ionic! We really appreciate this feedback on RTL support. This is not currently high priority for us at the moment, but we are tracking it in #5035. Because of this I am going to close this issue as a duplicate of that issue and ask that you put your feedback on that issue. Please know that by me closing this issue I am not saying that your feedback is not important, or that RTL support is not important, but I am simply closing this issue as we like to keep our issues as organized as possible so things do not get lost in the weeds (which is better said than done haha).

**Closed by jgw96** 2017-04-07 14:06 UTC
Labels: v2
