### ISSUE TITLE
bug: Scroll bars are gone

### ISSUE THREAD

**Issue by animungo** [driftyco/ionic#4065] opened 2015-07-09 20:07 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.x</span>  <span ionic-webview>webview</span>

<span ionic-description>The scroll bars are gone, when using native scrolling.</span>

<span is-issue-template></span>

**Comment by animungo** [comment] 2015-07-09 20:43
probably related to #4066

**Comment by mhartington** [comment] 2015-07-14 18:50
Confirmed.

**Comment by zarko-tg** [comment] 2015-08-18 12:32
Any news?

**Comment by jgw96** [comment] 2016-05-12 20:18
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment] 2016-05-17 14:19
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-05-17 14:19 UTC
Labels: needs reply, ready, v1
