### ISSUE TITLE
VirtualScroll + InfiniteScroll scrolls top when reaching list bottom

### ISSUE THREAD

**Issue by oktav777** [driftyco/ionic#6423] opened 2016-05-04 09:52 UTC
#### Short description of the problem:

When the bottom of virtual list is reached, infinite scroll is triggered, items are loaded and displayed all ok, but after that the scroll jumps straight to top.

Tested in:
- Opera/Chrome via ionic serve
- Nexus 4 Android 5.1
- Samsung Galaxy S5 Android 5.1

New to Ionic, don't know are they supposed to work together at all? Tried simple ion-list + infiniteScroll and works fine.
#### What behavior are you expecting?

The scroll should not jump to top when infinite scroll is triggered.

Also you can see an image flicker when scrolling. Don't know how correctly to explain it, but sometimes when u scroll and an image comes in viewport, it displays an image that don't belong to item, after some time, the correct image is displayed, and this change(flicker) is visible.

**Which Ionic Version?**  2.x
#### Plunker that shows an example of your issue

http://plnkr.co/edit/jNJBgEqPJlxttsHTRdmR?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.1.1
Gulp version:  CLI version 0.4.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS:
Node Version: v4.2.1

**Comment by InfinityOne** [comment] 2016-05-04 12:25
[Somehow connected with this](https://github.com/driftyco/ionic/blob/2.0/ionic/components/virtual-scroll/virtual-scroll.ts#L370)

**Comment by jgw96** [comment] 2016-05-04 14:46
Hello! Thanks for opening an issue with us! Virtualscroll is meant to increase scrolling performance with large lists as it only renders enough data to fill the viewport as you scroll. InfiniteScroll allows you to do an action once a user scrolls to the bottom of a list. Most devs normally use this for loading more data once a user scrolls through the page. It is not recommended that you use them together, so that is why you are seeing issues. VirtualScroll should be used if you have a large list that you need a user to scroll through (like maybe a list of all the employees at a big company). It will help keep your app's scrolling smooth even on low end phones. I would use infintescroll for something like search results where when the user scrolls to the bottom It would pull the next "page" of results. Hope this all makes sense!

**Comment by InfinityOne** [comment] 2016-05-05 06:14
@jgw96 Thanks for answer! I saw [this](https://www.raymondcamden.com/2016/04/25/an-example-of-virtualscroll-and-infinite-scroll-in-ionic-2/) article, and i thought it will be a legit way to do it. I will use ion-cards with infiniteScroll then. But how do I deal with the situation when a user scrolls down alot meaning that with the time the app will have a big list loaded? I did that, and after ~400 items(big cards with a big image) the scroll doesn't fell so smooth already. Should i write something custom? I will really appreciate your suggestion, i'm new to app developing.

**Comment by jgw96** [comment] 2016-05-05 14:48
@InfinityOne Ahh ok, i will work my way through that article today or tonight and update this post with my results (: What devices are you testing with if you don't mind me asking? So to ensure performant scrolling with huge lists i would probably not use ion-card's. Although ion-card's are beautiful and for "average" size lists they work fine, once you get to 100's of items in your lists you can start to see performance issues on older android devices. Ion-card's use the `box-shadow` css property to give them the "elevated/floating" look. Unfortunately this can cause the webview to do alot of repaints which can kill performance. I would use just standard `ion-item`s if i was gonna have a list with 100's of entries as they do not have any `box-shadow` styling. Hope this helps you!

**Comment by InfinityOne** [comment] 2016-05-06 08:07
@jgw96 Switched to `ion-item` and tested with ~1000 items loaded with infiniteScroll on iPhone 6s & 5s. Works fine, smooth scrolling, no problem. Tested on Galaxy S5 & Nexus 4 (both on Android 5.1), after 100 items even with `ion-item` scroll is dying slowly, as I load more items. Will lock for are more performant Android device to test.

**Comment by dudafreitasrj** [comment] 2016-06-02 19:55
I have the same problem. I'm using ion-card and after 20 items, notice that the scroll is slow. There are other solutions with the union of infiniteScroll and virtualScroll.

Now I am in doubt whether I use cards with pagination or smaller items with infiniteScroll.

**Comment by malvarezhcr** [comment] 2016-07-18 19:58
@dudafreitasrj  did you try setting the approxItemHeight input to the virtual scroll? it helps because the default height is 40px http://ionicframework.com/docs/v2/api/components/virtual-scroll/VirtualScroll/#input-properties

**Comment by royipressburger** [comment] 2016-07-19 05:18
@jgw96 Im having a hard time to understand why vritualscroll and infinitscroll aren't meant to be used together? For me it look like very common use case. Think about News feed (like in facebook). You wouldn't like to load all the feed because that will take ages and probably kill you server, so you need inifinitscroll. You also don't want to display all the item above the current view of the user because he might have scroll down so much that he already viewed 1000 items. 

And second question regarding the `ion-card`, removing the shadow-box property will increase the performance?

**Comment by InfinityOne** [comment] 2016-07-19 06:40
@royipressburger I don't understand too, why `virtualScroll` and `infiniteScroll` can't work together. When I saw this 2 components, I thought that there will be very easy to do something like social network's feed.

> You also don't want to display all the item above the current view of the user because he might have scroll down so much that he already viewed 1000 items.

Absolutely agree with you!


I believe that there is a problem right now with `virtualScroll` that Ionic team can't solve. That's why it can't work with `infiniteScroll`. Hope that in near future, they will fix it, and `virtualScroll` + `infiniteScroll` will become **base** of any other Ionic2 app. Let's just understand that this is still **beta**, and devs still have a lot of work. But they should hear us and understand that this 2 components need to work together, to deliver an 'as close as possible native feeling' to the app. Mobile users are used already with such kind of scrolling, replacing this for example with pagination, in 2016, looks lame, in my opinion.

**Comment by shlomiassaf** [comment] 2016-08-15 20:47
Also related to #6342.

This is really a great feature, if virtualScroll can update it's dataset and calculate a new transformation matrix upon insert of new records.

**Comment by daviddk** [comment] 2016-08-18 09:21
+1 on this issue, and pull to refresh not working correctly for VirtualScroll. 

After getting data a few times with infinite scroll, a list can become quite long and cause lots of perfomance issues, VirtualScroll & Infinite scroll together would make sense to me.

**Comment by risleylima** [comment] 2016-08-30 16:18
+1 on this issue

**Comment by DomiR** [comment] 2016-09-08 21:51
Yes, virtual scroll is not very well implemented. 

The scrolling to top part ist caused by: https://github.com/driftyco/ionic/blob/de12a4e9057e2f77536911b2ae891a7d81dba04c/src/components/virtual-scroll/virtual-scroll.ts#L378-L382

I've implemented a quick fix, but needs tests. I'm also only using this for inserting new elements. Restoring the position should probably also consider, elements could have been removed.

**Comment by DomiR** [comment] 2016-09-08 22:35
Update: This will not work on iOS, as the scroll positions are calculated differently. Maybe we can use content.getTop() instead of nativeElement.scrollTop but it gives me slightly different values which messes up the positions.

**Comment by Screeze** [comment] 2016-09-18 21:00
+1

I also face the same issue and I also think virtual list and endless scrolling fit perfectly together. I'm also interested in any workaround or fix which works cross-browser, since jumping to top is really not acceptable. I think this will be a major issue for many ioni2 apps...

**Comment by priedthirdeye** [comment] 2016-10-02 11:52
+1

**Comment by lujakob** [comment] 2016-10-04 19:04
An idea: If trying to combine infiniteScroll and virtualScroll to load more data on arriving at the bottom, you could save the scrollTop value of the content before loading more data and scroll back to this value manually after loading it. See https://github.com/driftyco/ionic/issues/8037#issuecomment-251479768 for more info.

**Comment by AzzamAsghar** [comment] 2016-10-05 18:10
Just tried a solution here #8037  need some comments about performance.

**Comment by naveedahmed1** [comment] 2016-11-16 14:19
Any update on this?

**Comment by OmarHassan25** [comment] 2016-11-20 08:21
Any updates on this?

**Comment by faraazc** [comment] 2016-11-23 09:48
vritualscroll + infinitscroll is a basic feature. Ionic should fix this in high priority. Feeds are the basic features for many apps. please fix this or provide a viable solution. jumping to top is really not acceptable. I think this will be a major issue for many ionic 2 apps @brandyscarney @adamdbradley @mlynch @jgw96

**Comment by csbok** [comment] 2016-11-30 17:46
+1

**Comment by mhartington** [comment] 2016-11-30 18:13
Hey yall! Sorry for the radio silence on our end, not cool 😶 

We've been looking at this issue quite a lot and have made quite a bit of work on this with whats in master. There's still a bit of work to be done, but it's being taken care of and will be resolved. Thanks for the patience.

**Comment by lujakob** [comment] 2016-12-01 10:09
I have a basic solution for two way infinite scrolling that supports a replacement of list data if anybody is interested. I described it here and have a demo on a github repo. https://github.com/driftyco/ionic/issues/8037#issuecomment-263934994

**Comment by naveedahmed1** [comment] 2016-12-01 19:16
@adamdbradley should we expect it to be resolved in next release?

@lujakob does your solution works with virtualScroll ?

**Comment by lujakob** [comment] 2016-12-06 15:19
@naveedahmed1 I tested a lot of stuff and in the end came to give up on virtual scroll because it never satisfied me. (on scrolling many times I had empty/white areas, because displaying/rendering list items somewhat delayed) So my implementation is meant to work without virtual scroll.

**Comment by axelauvinen** [comment] 2016-12-07 14:47
+1

**Comment by YasirPanjsheri** [comment] 2017-01-04 04:58
@lujakob Hi , I tried your solution... but in the component `addScrollListener` does not exist anymore in `Content` in RC 4.... whats the work around for this? 
Also, have they fixed the issue for ion-infinite + virtual scroll.... is it a milestone for RC 5 ?

**Comment by YasirPanjsheri** [comment] 2017-01-04 10:19
@lujakob Hi , I tried your solution... but in the component `addScrollListener` does not exist anymore in `Content` in RC 4.... 
Have they fixed the issue for ion-infinite + virtual scroll.... is it a milestone for RC 5 ?

UPDATE: I replaced `addScrollListener` with `ionScroll.subscribe`
Also your in the url where you get the content `url + ?start=` is there another way we can detect the `currentOffset` the API url that Im working on does not have this

**Comment by lujakob** [comment] 2017-01-05 11:59
@YasirPanjsheri correct, in the upgrade to RC4 the Content component code change from addScrollListener to an Observable. Also there is currently a bug in Ionic's scrollTo function that I'm using in the content.utils.js (a duration of 0 ms is not working, so I changed it to 1 ms). I refactored my repository and it's working again. 

Regarding the url + ?start= : it doesn't matter how you name the parameters in the endpoint you request. But you need to be able to get your list data paginated ( = get chunks of the data )

**Comment by faraazc** [comment] 2017-01-09 15:12
@adambradley can we expect this in RC.5.?. THANKS

**Comment by justas-kuizinas** [comment] 2017-01-16 19:04
Can we expect this in 2017 to be fixed? Thanks.

**Comment by Spartanace1024** [comment] 2017-02-03 20:46
Has this issue been resolved yet? Thanks in advance!

**Comment by francischodge** [comment] 2017-02-06 06:55
@mhartington Indeed radio silence is not cool. Could you please give us a rough estimate, or at least status? This is really a framework-breaking issue, and I'd be a shame for this to go a full year unresolved.

**Comment by mhartington** [comment] 2017-02-06 16:33
As we have stated in other issue with a similar topic, we are aware of this issue and will address it.  We have not forgotten it, but we are currently focusing on build/speed related issue at the moment. 
Pull requests are always welcome if people can fix the issue before we get to it though.

Locking for now.

**Comment by manucorporat** [comment] 2017-03-15 18:04
This should be fixed now in 2.3, please feel free to reopen it, if it didnt!

**Closed by manucorporat** 2017-03-15 18:04 UTC
Labels: infinitescroll, v2, virtualscroll
