### ISSUE TITLE
feat: Need to detect menu close event

### ISSUE THREAD

**Issue by ErkoKnoll** [driftyco/ionic#5864] opened 2016-03-17 06:58 UTC
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I haven't found a way to detect when menu closes. I checked MenuController and Menu classes but didn't notice any public event that is fired when menu is closed. Would be nice if there was an event for that.
Currently I'm doing it the following way and it is rather dirty:
`let previouslyOpened = false;

            setInterval(() => {
                let opened = menuController.isOpen();
                if (previouslyOpened && !opened) {
                    //Closed
                }
                previouslyOpened = opened;
            }, 500);`
</span>

<span is-issue-template></span>

**Comment by brandyscarney** [comment] 2016-03-21 19:20
Thanks for the issue, this is a duplicate of https://github.com/driftyco/ionic/issues/5163. Please add any feedback on that issue. :smile:

**Closed by brandyscarney** 2016-03-21 19:20 UTC
Labels: feature, menus, v2
