### ISSUE TITLE
bug: IOS native scroll bug

### ISSUE THREAD

**Issue by kyocn** [driftyco/ionic#4804] opened 2015-12-17 03:04 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Sometimes native scrolling can not scroll , if both  "height: 100%;" and "-webkit-transform: translate3d(0, 0, 0);" in .overflow-scroll .scroll ,so why?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-12-17 03:04
Greetings @kyocn!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4804). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4804)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment] 2015-12-17 03:05
@kyocn what platform/device? I'm assuming iOS and only in Safari?

**Comment by mlynch** [comment] 2015-12-17 15:17
Need more info, not sure what the issue is here

**Closed** 2015-12-17 15:17 UTC
