### ISSUE TITLE
Back button doesnt work on Lenovo Devices

### ISSUE THREAD

**Issue by naveedahmed1** [driftyco/ionic#9853] opened 2017-01-03 15:11 UTC
**Ionic version:**  (check one with "x")
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report

**Current behavior:**
The users of my app are reporting the the back button doesn't work on Lenovo devices.

Below are the details of the sample device:
Device Lenovo P70 (P70-A) 
Manufacturer Lenovo Mobile 
Device type Phone 
Device language English 
CPU make Mediatek 
CPU model MT6572 
Native platform armeabi-v7a, armeabi 
RAM (MB) 2048 
Screen size 720 × 1280 
Screen density (dpi) 320 
OpenGL ES version 3.0 
OS Android 5.1

Can it be fixed?

**Comment by jgw96** [comment] 2017-01-03 15:33
Hello, thanks for using Ionic! Do you have any more info on this issue? For example, are they trying to close a page with the back button, or a modal or some other component? Also, is this specific to just lenovo devices or do you also get the same issue with another android device?

**Comment by naveedahmed1** [comment] 2017-01-03 16:12
Thank you for your reply. The user reported that when they open a page and click back button to go back, it doesn't work.

**Comment by jgw96** [comment] 2017-01-03 18:07
Hmm ok, thanks for the info. I cannot reproduce this issue on any of my android devices running android 5.1.1, 6.0.1 and 7.0. I also cannot seem to reproduce this with Android 4.4.4 and 4.4.2 running in the emulator. Unfortunately without a good repro case there is not much we can do about this at the moment. Because of that I am going to close this issue for now but if it happens on other devices and you have a good repro case then just comment and ill happily reopen. Thanks!

**Closed by jgw96** 2017-01-03 18:07 UTC
Labels: needs reply, v2
