### ISSUE TITLE
[Bug] Click Block Does not function, resulting in Black Screen

### ISSUE THREAD

**Issue by curtisblanchette** [driftyco/ionic#8885] opened 2016-10-24 22:41 UTC
#### Short description of the problem:
Clicking the back button repeatedly can cause the navigation stack to accidentally pop the rootPage off of the DOM. resulting in a black screen.

#### What behavior are you expecting?
The click block element should function as expected, adding the class of 'click-block-active' when the back button is interacted with. Removing this class once the transition has completed.

I say this is a click-block issue since the back button shouldn't be able to be clicked more than once. It seems like multiple back clicks causes root page to be popped off the stack.

**Steps to reproduce:**
1. create a new ionic v2 start tabs project
2. create a button on a tab page that transitions to a subpage with a back button
3. add a bunch of images to the *subpage* so that their is heavy content
4. click the back button as fast as possible before the transition completes

*Please note that this is not easily reproduced. You must be patient and hammer on the back button*

Notice the root tab page will be removed from the DOM resulting in a black screen.
![screen shot 2016-10-24 at 3 54 34 pm](https://cloud.githubusercontent.com/assets/6607883/19666909/3342a0ce-9a02-11e6-821b-738b916f1bb6.png)
```
<ion-tab role="tabpanel" tabicon="information-circle" tabtitle="About" ng-reflect-root="function AboutPage(navCtrl) {
        this.navCtrl = navCtrl;
        this.subPage = SubPage;
    }" ng-reflect-tab-title="About" ng-reflect-tab-icon="information-circle" id="tabpanel-t0-1" aria-labelledby="tab-t0-1" aria-hidden="false" class="show-tab">
   <div></div>
   ** page is missing from here **
   <div class="nav-decor"></div>
</ion-tab>
```

Not 100% but this could be related to 
[8410](https://github.com/driftyco/ionic/pull/8410)

System information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.36
ios-deploy version: 1.9.0
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v6.8.0
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by curtisblanchette** [comment] 2016-10-25 17:40
@manucorporat Thanks for taking on this issue.

Back button listeners appear to be piling up. Perhaps they aren't being removed after the view is destroyed. Causing multiple nav.pop's to occur?

**Comment by jgw96** [comment] 2016-10-25 19:08
Hello, thanks for opening an issue with us! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/8881.

**Closed by jgw96** 2016-10-25 19:08 UTC
