### ISSUE TITLE
feat: Vertical Grid

### ISSUE THREAD

**Issue by danielfpedro** [driftyco/ionic#3518] opened 2015-04-13 15:17 UTC
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I think in mobile apps thats a common task.
An example is tinder.. they have the profile picture something like 70% height and the action buttons 30% height and the view has no scroll. 
@mhartington  tried to help me at [this post from ionic forum][1] and worked with littles bugs so I think this could be a feature because now is more like a hack.
I think could be something like that:

    <div class="col-vertical">
        <div class="row-70">
        </div>
        <div class="row-30">
        </div>
    </div>

</span>

<span is-issue-template></span>

[1]: http://forum.ionicframework.com/t/set-height-in-percentage-of-an-element-inside-ion-content/6315/6

**Comment by perrygovier** [comment] 2015-04-13 21:40
Hey @danielfpedro, we wont be adding new issues before the 1.0 release. Ionic v2 will be using flexbox, so this should be less of an issue. 
[I created a post on our Trello board](https://trello.com/c/QlfJToNc/89-vertical-grid) for 1.0 feature consideration though. We weigh our decision based on votes, so encourage others to vote as well.

Closing for now though since it's not a bug w/ the framework

**Closed by perrygovier** 2015-04-13 21:40 UTC
