### ISSUE TITLE
ionic 3 - sidemenu scroll not working on a real phone

### ISSUE THREAD

**Issue by javico2609** [driftyco/ionic#11050] opened 2017-04-04 15:44 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

the sidemenu scroll on ionic 3 beta work fine if run on my local browser but on my phone ( android and ios) the scroll not work i try to slide up and down and don't work and don't see the others elements.

ionic 2.3 the scroll work fine
![ionic 2 3](https://cloud.githubusercontent.com/assets/12940555/24665332/729361cc-1933-11e7-889c-037eec7add6a.jpg)

ionic 3 scroll not work
![ionic 3](https://cloud.githubusercontent.com/assets/12940555/24665361/8e81fe52-1933-11e7-9ecc-274d3daeae5c.jpg)

**Expected behavior:**
work sidemenu scroll fine like ionic 2.3

**Steps to reproduce:**

**Related code:**

```
<ion-header>
  <ion-toolbar>
    Title
  </ion-toolbar>
</ion-header>

<ion-content no-bounce>
  <ion-searchbar [(ngModel)]="menuFilterKey" [showCancelButton]="true" 
    (ionInput)="onFilter($event)"
    (ionCancel)="onCancel($event)">
  </ion-searchbar>
  <ion-list>
    <button ion-item *ngFor="let p of pages" (tap)="openPage(p)" [ngClass]="{ 'actineMenu': isActive(p) }"> 
        <i item-left [class]="p.icon" aria-hidden="true" ion-text></i>
        {{ p.title | translate }}
        <ion-badge item-right color="secondary" *ngIf="p.badge">{{p.badge}}</ion-badge>
    </button>
  </ion-list>
</ion-content>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
    Cordova CLI: 6.5.0
    Ionic Framework Version: 3.0.0-beta.3
    Ionic CLI Version: 3.0.0-beta.5
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Windows 10
    Node Version: v7.7.3
    Xcode version: Not installed
```

**Comment by jgw96** [comment] 2017-04-04 19:16
Hello, thanks for using Ionic! Unfortunately i cannot reproduce this issue on my devices (nexus 6 and an iphone 5). Would you mind sharing a repo we can use to reproduce this issue?

**Comment by javierg-infocorp** [comment] 2017-04-04 19:21
ok, Unfortunately i cannot share the original repo but i going to create a new one an share with your team, king regards

**Comment by jgw96** [comment] 2017-04-04 19:51
Thanks!

**Comment by javico2609** [comment] 2017-04-05 02:38
hello, i share the repo using dropbox it's a clean solution but have the problem with scroll on simenu and height header on ios, I hope it helps

**Comment by javico2609** [comment] 2017-04-05 19:33
Only the scroll works if you touch with you finger the right border of the menu

**Comment by jun1362008** [comment] 2017-04-07 04:07
@javico2609 Hello! I also met this bug, but it works when I remove the no-bounce attribute in ion-content

**Comment by javico2609** [comment] 2017-04-07 12:23
hi, first i thinking was the ionic 3 update but a test an remove (tap) event an everything work fine

**Comment by jgw96** [comment] 2017-04-07 16:01
Hello @javico2609 , sorry if im misunderstanding, but are you saying that this issue is now fixed or its still broken?

**Comment by jgw96** [comment] 2017-04-07 16:02
Hello, after further review I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/11112.

**Closed by jgw96** 2017-04-07 16:02 UTC
Labels: needs info, v3

**Comment by javico2609** [comment] 2017-04-07 17:04
its still broken, it is work if only remove all (tap) event from application.

**Comment by bhumin3i** [comment] 2017-12-27 14:00
still have same problem anyone please help
