### ISSUE TITLE
Zoom on image in Ionic 2.(pinch)

### ISSUE THREAD

**Issue by klochko7** [driftyco/ionic#9152] opened 2016-11-14 15:54 UTC
Has anyone managed to get an image zoom working in Ionic 2 by fingers up-down ? (pinch) Is it possible to reach by native methods ?

**Comment by jgw96** [comment] 2016-11-14 17:04
Hello, thanks for using Ionic! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/9150.

**Closed by jgw96** 2016-11-14 17:04 UTC

**Comment by klochko7** [comment] 2016-11-15 08:50
jgw96, Is it possible in Ionic 2 zoom on image (pinch) ? I do not understand.
