### ISSUE TITLE
ion-checkbox and ion-toggle not working inside ion-grid column

### ISSUE THREAD

**Issue by rglaspey** [driftyco/ionic#7607] opened 2016-08-08 17:32 UTC
#### Short description of the problem:
When trying to add a toggle or checkbox (with label) to a column in an ion-grid I just get empty list items.

the grid is embedded in a ion-list-item

#### What behavior are you expecting?
I expected to see the checkbox and label rendered correctly.

**Steps to reproduce:**
1. Add the below grid to ion-list-item and run.
2. 
3. 

insert any relevant code between the above and below backticks
```<ion-grid>
                <ion-row>
                    <ion-col width-10>

                    </ion-col>
                    <ion-col width-50>
                        <ion-badge style="background-color: red;">NA</ion-badge>
                    </ion-col>
                    <ion-col text-center>
                        <ion-item>
                            <ion-label>Pepperoni</ion-label>
                            <ion-checkbox></ion-checkbox>
                        </ion-item>
                    </ion-col>
                    <ion-col width-10 text-right>
                        0/10
                    </ion-col>
                </ion-row>
            </ion-grid>
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x
v2

**Comment by jgw96** [comment] 2016-08-08 17:38
Hello, thanks for opening an issue with us! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/7503. Thanks for using Ionic!

**Closed by jgw96** 2016-08-08 17:38 UTC
Labels: checkbox, toggle

**Comment by harding13** [comment] 2017-06-12 07:52
Sorry for re-open this post but i don't understand the solution of this issue

**Comment by jeansaigne** [comment] 2017-09-14 11:54
Hello,
you should definitly re-open this issue @jgw96 , because it's clearly not a duplicate of the thread you linked. The solution you give in this thread is removing the "ion-item-group", but did you see any "ion-item-group" here...no, and i'm facing the exact same problem.

**Comment by adnansenyurt** [comment] 2017-12-18 14:34
This should be opened again I'm having the same problem and it is not related to driftyco#7503
