### ISSUE TITLE
UI Crash

### ISSUE THREAD

**Issue by Blackscr33n** [driftyco/ionic#10616] opened 2017-03-02 08:07 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

UI crashes on drag&drop & Sliding-Item with no error see screenshot:
UI doesn't react anymore on touches or other gestures.

![image uploaded from ios 1](https://cloud.githubusercontent.com/assets/6410789/23498108/5a304e3c-ff26-11e6-89a4-a215e9e6f5fd.jpg)

**Expected behavior:**

UI doesn't crash.
Drag&Drop still works.
**Steps to reproduce:**

While dragging, swipe to-left and you will see the UI crashing.

```
Cordova CLI: 6.3.1 
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: OS X El Capitan
Node Version: v6.9.1
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by manucorporat** [comment] 2017-03-03 23:38
Will take a look soon :)

**Comment by jgw96** [comment] 2017-03-08 17:51
Hello @Blackscr33n , unfortunately i cannot reproduce this issue, would you mind sharing a repo or plunker we can use to reproduce this issue?

**Comment by jgw96** [comment] 2017-03-13 16:16
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-03-13 16:16 UTC
Labels: needs info, v2
