### ISSUE TITLE
Background rectangle shown on pages without scroll

### ISSUE THREAD

**Issue by mola10** [driftyco/ionic#9104] opened 2016-11-10 09:54 UTC
Hey guys,

I have an issue, when page does not contains ion-footer **and** ion-content it too short to have a scroll, I see a weird black rectangle in top left corner. I believe it's part of background control or something like this.

Here is the screenshot:
http://image.prntscr.com/image/c123de50e07043b08da65c24444f424e.png

Here is my code:
app.html

```
<ion-menu [content]="app">
    <ion-header>
        <ion-toolbar>
            <profile-card></profile-card>
        </ion-toolbar>
    </ion-header>
    <ion-content>

        <ion-list>
            <button menuClose ion-item detail-none no-lines (click)="onDashboardMenuClick()">
                <ion-icon item-left name="calendar"></ion-icon>
                Dashboard
            </button>            
        </ion-list>

        <ion-list class='sign-out-block'>
            <button menuClose ion-item detail-none (click)="onSignOutBtnClick()">
                <ion-icon item-left name="log-out"></ion-icon>
                Sign out
            </button>
        </ion-list>

    </ion-content>
</ion-menu>

<ion-nav #app [root]="rootPage"></ion-nav>
```

dashboard.html:

```
<ion-header no-shadow>
    <ion-navbar>
        <button menuToggle ion-button>
          <ion-icon name="menu"></ion-icon>
        </button>

        <ion-segment [(ngModel)]="segment">
            <ion-segment-button value="all">
                All
            </ion-segment-button>
            <ion-segment-button value="favorites">
                History
            </ion-segment-button>
        </ion-segment>
    </ion-navbar>
</ion-header>

<ion-content>

    <ion-list *ngIf="segment == 'all'">
        <ion-item-group>
            <ion-item-divider sticky>
                <ion-label>
                    12 November
                </ion-label>
            </ion-item-divider>
            <ion-item-sliding track='tooling'>

                <button ion-item>
                    <h3>text</h3>
                    <p>
                        10.00 A.M &mdash; 11.30 A.M: <b>Canceled</b>
                    </p>
                </button>
                <ion-item-options>
                    <button ion-button color="danger">
                        Cancel
                    </button>
                </ion-item-options>
            </ion-item-sliding>
        </ion-item-group>

    </ion-list>

</ion-content>
```

Steps to reproduce:
1. Page should not contain any footer
2. Page should not have a scroll control
3. You should check it on mobile device or in chrome developers tools mobile device mode

ionic version
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS:
Node Version: v6.7.0

**Comment by brandyscarney** [comment] 2016-11-10 17:33
Thanks for the issue. Closing as a duplicate of https://github.com/driftyco/ionic/issues/6416. :)

**Closed by brandyscarney** 2016-11-10 17:33 UTC
