### ISSUE TITLE
 hide-nav-bar="true" is not working 

### ISSUE THREAD

**Issue by Josephdias92** [driftyco/ionic#4630] opened 2015-11-13 07:21 UTC
hide-nav-bar="true" is not hiding the nav bar 
<ion-view  hide-nav-bar="true">
    <ion-content padding="true">
        <form class="list">
            <ion-list>
                <label class="item item-input item-floating-label">
                    <span class="input-label">Phone Number</span>
                    <input type="text" placeholder="Phone Number">
                </label>
                <label class="item item-input item-floating-label">
                    <span class="input-label">Date Of Birth</span>
                    <input type="text" placeholder="Date Of Birth">
                </label>
                <label class="item item-input">
                    <select>
                        <option>Select Gender</option>
                        <option>Male</option>
                        <option >Female</option>
                    </select>
                </label>
            </ion-list>
            <button class="button button-positive button-block ">Sign up</button>
        </form>
    </ion-content>
</ion-view>

i tried adding adding has-header="false" didnt work

**Comment by Ionitron** [comment] 2015-11-13 07:21
Greetings @Josephdias92!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4630). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4630)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by jgw96** [comment] 2016-03-14 21:09
Hello! Thanks for opening an issue with us, we just need a little more info from you so that we can better help you with your issue. Would you mind posting a code sample, plunkr or codepen that we can use to reproduce your issue? Also, would you mind running `ionic info` and posting the output? Thanks again!

**Comment by jgw96** [comment] 2016-03-21 19:51
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!

**Closed by jgw96** 2016-03-21 19:51 UTC
