### ISSUE TITLE
bug: ion-datatime min value not working as expected

### ISSUE THREAD

**Issue by delley123** [driftyco/ionic#7683] opened 2016-08-12 11:39 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>When using this code to set a datetime min value:
`<ion-datetime displayFormat="MMM DD, YYYY HH:mm" min="2016-08-12T12:00" [(ngModel)]="timeStarts"></ion-datetime>`

I would expect that the selectors would be set as following:
Aug 12 2016 12 00

But instead they are set like this (please note that Month is completly missing)
01 2016 00 00

Bug? is that how it should work?</span>

Also note I have not tested this on any of the others platorms.

<span is-issue-template></span>

**Comment by jgw96** [comment] 2016-08-12 18:24
Hello! Thanks for opening an issue with us! I am going to be closing this issue as a duplicate of https://github.com/driftyco/ionic/issues/6850. Thanks for using Ionic!

**Closed by jgw96** 2016-08-12 18:24 UTC
Labels: v2

**Comment by delley123** [comment] 2016-08-15 07:23
Cheers! Will be watching that issue for progress.
