### ISSUE TITLE
Update plunker template for v2 issues to use latest RC0

### ISSUE THREAD

**Issue by okonon** [driftyco/ionic#8651] opened 2016-10-12 15:55 UTC
I was wondering if you guys could update plunker issue template to latest rc.0 so we can provide you code when submitting issues?

**For Ionic 2 issues** - http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview

**Comment by jgw96** [comment] 2016-10-12 20:42
Hello, thanks for opening an issue with us! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/8521

**Closed by jgw96** 2016-10-12 20:42 UTC
