### ISSUE TITLE
bug: Sliding List buttons not show up in RTL direction

### ISSUE THREAD

**Issue by bhnmzm** [driftyco/ionic#8107] opened 2016-09-17 15:28 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi,
I have a problem with Sliding List.
It work correctly when my app direction is LTR but when I change it to RTL , the option buttons not show up.

Best Regards
</span>

<span is-issue-template></span>

**Comment by behnamazimi** [comment] 2016-09-17 20:03
I found a solution which is available [here](https://forum.ionicframework.com/t/sliding-list-not-work-in-rtl-mode/59946/5?u=behnamazimi)

**Comment by jgw96** [comment] 2017-04-07 14:05
Hello, thanks for using Ionic! We really appreciate this feedback on RTL support. This is not currently high priority for us at the moment, but we are tracking it in #5035. Because of this I am going to close this issue as a duplicate of that issue and ask that you put your feedback on that issue. Please no that by me closing this issue I am not saying that your feedback is not important, or that RTL support is not important, but I am simply closing this issue as we like to keep our issues as organized as possible so things do not get lost in the weeds (which is better said than done haha).

**Closed by jgw96** 2017-04-07 14:05 UTC
Labels: v2
