### ISSUE TITLE
<ion-list> not rendering on screen when cordova added

### ISSUE THREAD

**Issue by dheran** [driftyco/ionic#6180] opened 2016-04-15 15:23 UTC
** Ionic v2 **

**How to replicate the issue:**
Step 1: visit this plunker http://plnkr.co/edit/w5qUFI?p=preview
(note: cordova.js has been linked, so you will get some alerts while loading. Press cancel for all alerts)
Step 2: Launch the preview
Step 3: Once puppy list got loaded, click on any puppy you like.
Step 4: It will open the detail page
Step 5: Now go back
Step 6: You can notice the bug. Puppies list is not getting rendered on screen this time. now when you click kittens segment button and then click puppies, now list got loaded.
I've checked this in both android mobile and pc browser.

It works fine either when I removed cordova.js from index.html  or remove setTimeout from home.ts for initializing puppies array. I use setTimeout because I'm using Promise for making http request in my application.

**Comment by dheeran1** [comment] 2016-04-18 04:39
@adamdbradley @brandyscarney @jgw96 Hey there, Did you got chance to look into this issue?

**Comment by jgw96** [comment] 2016-04-19 05:18
Hey @dheeran1 ! So if your using a promise in your application to retrieve data and then display it you are gonna have to use `NgZone.run()` to trigger change detection. Here is an example of how you would do this 👍 

```
import {NgZone} from "angular2/core";
import {Page} from "ionic-angular";

@Page({
     template: "something using *ngFor"
 })
class AwesomeExample {
    
    items: any[];
    
    constructor(private _zone: NgZone) {
        fetch("awesomeapi.json").then((response) => {
             return response.json()
        }).then((data) => {
            this._zone.run(() => {
                this.items = data;
            })
        })
     }
}
```
This should fix your issue. If you would like to read more about NgZone and zones in angular2 and Ionic 2 here are some good links : https://angular.io/docs/js/latest/api/core/NgZone-class.html, http://blog.thoughtram.io/angular/2016/02/01/zones-in-angular-2.html. Thanks for using Ionic!

**Comment by dheeran1** [comment] 2016-04-19 06:00
@jgw96  thanks for your reply. I'll check that for promise and let you know. meanwhile what is the workaround for `setTimeout` in given plunkr sample above.

**Comment by jgw96** [comment] 2016-04-19 07:19
@dheeran1 Hey! Soo i took your plunker and updated it to make it work and give you a demo of `NgZone`. Sorry i should have done this earlier (: haha. I also changed your setTimeout to a ES6 arrow function(https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions) so that you would be able to use `this` without having the `ref` variable you had made. Arrow functions allows `this` to bind lexically, which means you dont have to do anything like `let self = this` or anything like that. ES6 is awesome!

**Comment by biesbjerg** [comment] 2016-04-19 11:20
@jgw96: setTimeout (and friends) are patched by NgZone and run automatically.

> We don’t have to do anything special to tell the framework that a change has happened. No ng-click, no $timeout, $scope.$apply().
If you’ve read our article on understanding Zones, you know that this works obviously because Angular takes advantage of Zones. Zones monkey-patches global asynchronous operations such as setTimeout() and addEventListener(), which is why Angular can easily find out, when to update the DOM.

http://blog.thoughtram.io/angular/2016/02/01/zones-in-angular-2.html

**Comment by dheeran1** [comment] 2016-04-19 12:18
@jgw96 Thanks, Glad you did that and it works :-)
But I'm confused, why this happens only after linking cordova?

**Comment by jgw96** [comment] 2016-04-19 14:32
@dheran No problem at all! Yeah, so weve noticed some really weird issues caused by cordova that causes change detection not to be triggered by async operations. Currently the workaround for it is using `NgZone.run()` as i used in your plunker, but eventually when we narrow down the issue more and when the cordova team fixes this issue you will not have to do this.

**Comment by dheran** [comment] 2016-04-19 15:34
Another weird thing is, it will work fine if setTimeout delay was reduced to less than 500ms

**Comment by jgw96** [comment] 2016-04-22 21:21
@dheran are you still having this issue with the latest version of Ionic 2 (beta.6)?

**Comment by jgw96** [comment] 2016-04-27 15:02
Hello! As it has been a little while since there was any activity on this issue i will be closing it for now. Thanks for using Ionic!

**Closed by jgw96** 2016-04-27 15:02 UTC
Labels: alert, needs reply, platform:android, v2

**Comment by dheran** [comment] 2016-04-28 05:59
@jgw96 do you mean without using ngzone?

**Comment by jgw96** [comment] 2016-04-28 14:46
@dheran hey! yep without NgZone usage.

**Comment by dheran** [comment] 2016-04-29 07:29
It's not working without ngzone. Is it working for you? Can you please update the plunk you shared earlier above?
