### ISSUE TITLE
ion-footer with component which contains only is hiding the content area. 

### ISSUE THREAD

**Issue by nes16** [driftyco/ionic#7637] opened 2016-08-10 11:38 UTC
I have a keypad like component, which i put it in footer. 
The content scroll size is not adjusting for footer area.

If i have footer like static ion-component like 
<ion-list>
<ion-item>
<h1>Footer</h1>
</ion-item>
<ion-item>
<h1>Footer</h1>
</ion-item>
</ion-list>

then the content adjust automatically.

#### What behavior are you expecting?
The content should shrink.  

Ionic 2 plunker:
http://plnkr.co/edit/gIQtXCiJwUVxr7fZwZOp?p=preview

**Comment by jgw96** [comment] 2016-08-10 14:49
Hello! Thanks for opening an issue with us! So i just tried to use your plunker that you made to reproduce this issue, but it seems there are some bugs with your component that are stopping the page from being able to be opened. Would you mind reviewing your plunker? Thanks for using Ionic!

**Comment by nes16** [comment] 2016-08-10 15:08
Thanks. let me check.

**Comment by nes16** [comment] 2016-08-10 15:23
I can open the page, by clicking on thanks button. Inspected the page in separate window and no error messages.

**Comment by nes16** [comment] 2016-08-10 15:34
http://plnkr.co/edit/gIQtXCiJwUVxr7fZwZOp?p=preview

**Comment by jgw96** [comment] 2016-08-10 16:56
Hey! Weirdly its working for me now, not sure why it wasn't before, sorry about that! So the issue seems to be the css with your directive. I made a plunker [here](http://plnkr.co/edit/GyB16x97GDmZLhUaR79C?p=preview) with just some plain html and can confirm that the scrolling content adjusts accordingly. So, since this issue seems to be an issue with your directive and not an issue with Ionic i am going to be closing for now. Thanks for using Ionic!

**Closed by jgw96** 2016-08-10 16:56 UTC
Labels: footer, v2
