### ISSUE TITLE
bug: scrollbar disappeared on Android's native scrolling

### ISSUE THREAD

**Issue by cheneywan** [driftyco/ionic#4772] opened 2015-12-14 05:24 UTC

**Comment by mlynch** [comment] 2015-12-14 15:56
Seems to happen intermittently. I'm considering this an issue with overflow scrolling on Android and not a regression per say. Will track.

**Comment by roysG** [comment] 2015-12-31 11:24
I can also say that since i updated to 1.2.1 suddenly to scroll is gone.

I am using in  <ion-scroll

**Comment by jgw96** [comment] 2016-04-01 19:30
Hello (: Are you still experiencing this issue with the latest version of ionic?

**Comment by jgw96** [comment] 2016-04-06 14:43
Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to respond back if your still having the issue! Thanks again!

**Closed by jgw96** 2016-04-06 14:43 UTC
Labels: needs reply, scroll, v1

**Comment by neslinesli93** [comment] 2016-05-18 08:52
Same issue here, happening only on my device, which is equipped with Android Kitkat.
Unfortunately I only have kitkat devices with me, so I can't test with Android 5/6
