### ISSUE TITLE
bug: '$ionicView.enter' and '$ionicView.leave' are triggered with wrong order with nested views

### ISSUE THREAD

**Issue by fabienvauchelles** [driftyco/ionic#3433] opened 2015-03-30 16:14 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Example:

```
root
|- viewParent - ParentController
  |- viewChildA - ChildAController
  |- viewChildB - ChildBController
|- otherView - OtherController
```

I'm on viewChildA

When a go on viewChildB, I have:
ChildAController.leave()
ParentController.leave()
ParentController.enter()
ChildBController.enter()
ParentController.enter().

I should have only:
ChildAController.leave()
ChildBController.enter()
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-03-30 16:14
Greetings @fabienvauchelles!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3433). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3433)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment] 2015-03-30 21:33
Greetings @fabienvauchelles!

My sensors indicate that I require more information in order to assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this happen occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com), where many humans will be able to offer wisdom and advice.

Thank you for allowing me to assist you.

<span ionitron-needs-reply></span>

**Comment by fabienvauchelles** [comment] 2015-03-31 08:06
Example here: http://codepen.io/anon/pen/ogVryG

**Comment by fabienvauchelles** [comment] 2015-03-31 08:07
On every platform

**Comment by fabienvauchelles** [comment] 2015-03-31 08:25
Workaround to trigger the event in the right order :

```
    angular
        .module('myApp')
        .run(Config);

    function Config($rootScope) {
        $rootScope.$on('$stateChangeSuccess', function(ev, toState, toParams, fromState, fromParams) {
            var srcPath = fromState.name;
            var dstPath = toState.name;

            var idx = similarIndex(srcPath, dstPath);
            var commonPath = srcPath.slice(0, idx);


            // Leave
            var leavePaths = [];

            var srcDiff = srcPath.slice(idx);
            var split = srcDiff.split('.');
            createPaths(leavePaths, commonPath, split, split.length, false);

            leavePaths.forEach(triggerLeave);



            // Enter
            var enterPaths = [];

            var dstDiff = dstPath.slice(idx);
            var split = dstDiff.split('.');
            createPaths(enterPaths, commonPath, split, split.length, true);

            enterPaths.forEach(triggerEnter);


            ////////////

            function createPaths(target, prefix, parts, idx, reverse) {
                var sub = parts.slice(0, idx);
                var path = prefix + sub.join('.');

                if (path.length > 0) {
                    if (reverse) {
                        target.unshift(path);
                    } else {
                        target.push(path);
                    }
                }

                if (idx > 1) {
                    createPaths(target, prefix, parts, idx - 1, reverse);
                }
            }

            function similarIndex(stringA, stringB) {
                var max = Math.min(stringA.length, stringB.length);

                for (var i = 0; i < max; ++i) {
                    var c1 = stringA.charAt(i);
                    var c2 = stringB.charAt(i);

                    if (c1 != c2) {
                        return i;
                    }
                }

                return max;
            }

            function triggerLeave(path) {
                $rootScope.$broadcast('route:leave', path);
            }

            function triggerEnter(path) {
                $rootScope.$broadcast('route:enter', path);
            }
        });
    }

    angular
        .module("myApp")
        .controller('MyRouteController', MyRouteController);

    function MyRouteController($scope) {
        enter();
        $scope.$on('route:enter', function(ev, path) {
            if ( path !== 'myparent.myroute' ) return;

            enter();
        });

        $scope.$on('route:leave', function(ev, path) {
            if ( path !== 'myparent.myroute' ) return;

            leave();
        });

        function enter() { // Init stuff }
        function leave() { // Leave stuff }
```

**Comment by ygotthilf** [comment] 2015-03-31 08:26
+1

**Comment by jmaynier** [comment] 2015-04-28 17:19
+1

**Comment by adamdbradley** [comment] 2015-06-08 16:24
Due to the nature of nested ion-nav-views and the UI router, this is a challenge to change and have it work for every scenario. If the workaround is a solution that works for the case where you need to have an exact order, then I'd recommend that solution instead.

**Closed by adamdbradley** 2015-06-08 16:24 UTC
Labels: navigation

**Comment by fabienvauchelles** [comment] 2015-06-08 17:19
Hello Adam,

Finally, I have to deactivate by config the cache of templates.

If you forecast to remove the switch, it could be a huge problem in complex application.

Thanks,
Fabien.

**Comment by fhackenberger** [comment] 2016-03-12 17:08
A simple workaround is:
```
$scope.$on('$ionicView.afterEnter', function(ev) {
	if(ev.targetScope !== $scope)
		return;
	// Your code which should only run once
});
```
