### ISSUE TITLE
perf: Ionic pull to refresh with native scrolling using card class lag in version 1.0 (latest) on android native scrolling enabled.

### ISSUE THREAD

**Issue by abeninskibede** [driftyco/ionic#3835] opened 2015-05-26 17:57 UTC
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.0</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi guys,

* Running latest version of ionic 1.0
* I have an android 5.0 HTC one M8.
* I'm running the ionic app and I have a view of 15 items initially loaded.
* JS scrolling is disabled (native scrolling enabled)
* using ng-repeat
* using card css class

Evey time I pull down to refresh, the ionic refresher appears but it's animation is really laggy (it spins with lag and content that is moved down lags).
Once the animation completes there is no lag.
I am able to scroll down and up with no lag at all. Infinite scroll is also enabled (ion-infinite-scroll) and is working just fine.
How to get rid of this laggy animation?
There is no lag when using collection-repeat but I'm aiming for the native scrolling.

Just noticed that the lag is caused by the **card** css class.</span>

I tried with 3 items staticly and the issue still happens:

```
<ion-refresher
            pulling-text="Pull to refresh..."
            on-refresh="refresh()">
</ion-refresher>

<div class="card">a</div>
<div class="card">b</div>
<div class="card">c</div>
```

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-05-26 17:57
Greetings @abeninskibede!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3835). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3835)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by MichaelMcClenaghan** [comment] 2015-05-28 13:18
I am also getting this with a very similar layout.

Ionic 1.0.0
Android 5.0 on OnePlus One
2 items in an ng-repeat with the card class

**Comment by neilgoldman305** [comment] 2015-06-02 19:54
+1. You don't even need to actually trigger the refresh, just pulling down on the scroll to show the arrow and text will cause it to lag.

Ionic 1.0.0
Android 4.4 on LG G3
10-30 items in an ng-repeat with card class.

**Comment by neilgoldman305** [comment] 2015-06-02 23:57
So, one of the times It happens is when *box-shadow* and *border-radius* are used together. If you record a timeline with Chrome on the device, the *CompositorTileWorker* thread spends a ton of time doing *"Rasterize Paint"* whenever these are both on.

Try out this Ionic Play on your phone:
http://play.ionic.io/m/989cc596483b

Disabling either the shadows or radius fixes the lag for me.

Here is another example without using the card class. Just the values for box-shadow and border-radius, to show it's not being caused by further interactions with the card class.

http://play.ionic.io/m/bef5b9b77b6f

That can't be all there is though. I've removed the card class from the elements in our app, and the lag is still present. As far as I can see, we don't have any shadows or border-radius applied to anything, or anything else too expensive to rasterize (and we force *ionic.Platform.setGrade('b')* for all devices).

As far as I can tell, it's spending a ton of time recalculating styles, but I'm not sure why yet.

**Comment by MichaelMcClenaghan** [comment] 2015-06-10 15:39
I managed to get it to go away!  I changed my list from using ng-repeat to collection-repeat, and the lag is gone!  Not sure exactly why the issue is gone for us now...

**Comment by abeninskibede** [comment] 2015-06-10 17:18
Not an option for me because collection-repeat enables js scrolling and it's not an option for me because js scrolling is lagging.

**Comment by neilgoldman305** [comment] 2015-06-10 18:27
Yeah, collection-repeat forces JS scrolling on the container, so that's why it makes the issue seem to disappear.

**Comment by pantonis** [comment] 2015-07-08 04:16
Have the same problem here. Android 5.1 on LG G4 native scrolling enabled with cards css and refresh is way too laggy.

Any suggestions?

**Comment by animungo** [comment] 2015-07-09 19:43
+1

**Comment by jason-au** [comment] 2015-08-26 18:22
+1 same problem here. Samsung Note 4 running Android 5.0.1

**Comment by kjellivar** [comment] 2015-08-27 09:09
+1 same problem here. Sony Xperia Z1 with Android 5.0.2

**Comment by mhartington** [comment] 2015-08-27 13:01
Any example? Codepen, plunkr?

**Comment by kjellivar** [comment] 2015-08-27 13:14
@mhartington : It is present in the example from @neilgoldman305 
http://play.ionic.io/app/989cc596483b

(I see it uses Ionic 1.0, but I experience same behaviour in 1.1.0)

**Comment by mhartington** [comment] 2015-08-27 21:34
Okay, so tested this out and saw some lag too on a nexus 5 running android 5.1.
Switching out the cards for just items got rid of the lag.
Changing the cards box-shadow to a simple border got rid of the lag as well.

This makes a lot of sense since box-shadows are really expensive and cause a lot of repaints. 

http://nerds.airbnb.com/box-shadows-are-expensive-to-paint/

This is an issue even with native scrolling.
Hmm, could you all try adding this to your css.

```css
.card {
  -webkit-transform: translate3d(0, 0, 0);
  transform: translate3d(0, 0, 0);
}
```

The old null-transform hack helped for me here.

**Comment by jason-au** [comment] 2015-08-28 02:50
The null-transform hack seems to have helped for me. Thanks Mike!

**Comment by kjellivar** [comment] 2015-08-28 08:00
That did the trick for me as well. Thanks @mhartington!

**Comment by mhartington** [comment] 2015-08-28 12:31
Ok, so this has nothing to do with PTR and native scrolling, but just that box-shadows aren't hardware accelerated and cause a lot of repaints. 

Closing for now.

**Closed by mhartington** 2015-08-28 12:31 UTC
Labels: needs reply

**Comment by mohamed-ahmed** [comment] 2016-04-04 22:27
I'm getting the same issue without using cards (just ion-items), and using ng-repeat, and only on Android devices. What might fix it in that case?

**Comment by kldoon** [comment] 2016-04-13 10:47
I am getting the same issue using the collection-repeat without any card items, android 5.0+

**Comment by Corvi2** [comment] 2016-04-22 13:48
i'm also very unhappy with the performance of ion-refresher. i'm showing ion-items with text and an avatar image below the refresher.
