### ISSUE TITLE
$ionicSlides.slideChangeEnd does no fire at all - related to #6550

### ISSUE THREAD

**Issue by konsultaner** [driftyco/ionic#7822] opened 2016-08-22 12:41 UTC
#### Short description of the problem:
The slider does not recognize a slider change event if you keep sliding the last slide. It is very easy to reproduce.

#### What behavior are you expecting?
The slider should fire the change event when it hase calm down.

**Steps to reproduce:**
1. The slider should have two slides, the slider must not loop
2. Slide from the first to the second slide and prevent it from transitioning to the final position, by continuing to swipe a couple of times
3. Let it transition to the final position of the second slide
4. No event is fired.

Ionic Version: 1.3.1

**Comment by jgw96** [comment] 2016-08-22 15:15
Hello! Thanks for opening an issue with us! I am going to be closing this as a duplicate of #6550. Thanks for using Ionic!

**Closed by jgw96** 2016-08-22 15:15 UTC
Labels: range, v1
