### ISSUE TITLE
Ionic v2 : Input item inside <ion-slide> scrolls page to top on click 

### ISSUE THREAD

**Issue by uzumakinaruto123** [driftyco/ionic#9421] opened 2016-11-30 08:14 UTC
**Ionic version:**  (check one with "x")
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report

**Current behavior:**

Clicking any` ion-input` field inside `ion-slide` , **scrolls the page to top**. It does not even focus the input. `ion-datetime` inside slide works correctly. 

**Expected behavior:**

When any input field inside ion-slide is clicked , it should only focus the input for typing. 

**Steps to reproduce:**

1. Add some scrollable content to any page .
2. add ion-slides  at bottom.(or anywhere after scrolling some distance).
3. Add `ion-input`  (as in related code below)
4. serve/run project. scroll down and click input field inside the slide.

**Related code:**

```
<ion-slides>
     <ion-slide>
            <ion-list>
                <ion-item>
                     <ion-label fixed>Username</ion-label>
                     <ion-input type="text" value=""></ion-input>
                </ion-item>
           </ion-list>
     </ion-slide>
</ion-slides>
```

**Other information:**

PS :- If only input field is placed without slides , then it works correctly by making space for keyboard and focusing it.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

 cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v4.1.0
Xcode version: Not installed
```

**Comment by jgw96** [comment] 2016-11-30 14:55
Hello, thanks for opening an issue with us! Would you be able to install the latest nightly (run `npm install ionic-angular@nightly --save) and give this another try? We have implemented a good amount of fixes around scrolling and input focusing in the latest nightly that should fix this issue. Thanks again!

**Comment by uzumakinaruto123** [comment] 2016-11-30 16:26
@jgw96  Wow ! great. It worked. But , now everytime while clicking the input the ion-label blinks for a second.

**Comment by uzumakinaruto123** [comment] 2016-12-01 06:08
And , now i feel scroll is bit laggy and sometimes it does not respond touch and freezes. Previous scroll felt much better.

**Comment by jgw96** [comment] 2016-12-05 16:02
Interesting find, unfortunately I am not able to reproduce this on my machine. Would you be able to post a repo I can use to reproduce this issue?

**Comment by uzumakinaruto123** [comment] 2016-12-06 11:49
Scroll is fine. just feels different. regarding label issue , I am testing it on multiple pages , on every page its the same.

**Comment by jgw96** [comment] 2017-01-26 20:54
Hello all! Because i cannot reproduce this issue and because it has been a while since there was any activity on this issue I am going to close this one for now. Thanks!

**Closed by jgw96** 2017-01-26 20:54 UTC
Labels: needs reply, v2

**Comment by jirehnimes** [comment] 2018-01-21 06:43
Almost same problem here but my ion-slide is the scrollable with inputs inside it. Then whenever focusing on an input it scrolls the ion-slide to top. I already tried installing ionic-angular@nightly but didn't fixed the problem.
