### ISSUE TITLE
Cursor remains stuck on original position after scroll

### ISSUE THREAD

**Issue by kunj77** [driftyco/ionic#4946] opened 2016-01-13 09:02 UTC
I am building an application using ionic. I have a template with several input fields. When user hits on an input field I want to scroll the field to the top. I tried using

```javascript
$ionicScrollDelegate.scrollTo(node.offsetLeft, node.offsetTop, true);
```

This scrolls the page up for me. However, it does not update the cursor position. The page scrolls up and the cursor remains stuck at the position before the scroll. If I start typing some text, the cursor moves to the desired input field and starts typing there. So I guess the cursor has not lost context but its position is not updated. Any ideas on what could work in this case?

**Comment by kunj77** [comment] 2016-01-21 11:35
Can someone please help me this? I have been stuck since quite some time.

**Comment by mlynch** [comment] 2016-02-03 23:00
@kunj77 what version of Ionic?

**Comment by kjt1212** [comment] 2016-02-04 07:22
Version 1.7.12

**Comment by kjt1212** [comment] 2016-03-01 09:49
@mlynch any update? were you able to reproduce this?

**Comment by jgw96** [comment] 2016-03-14 16:58
Hello! Thanks for opening an issue with us, we just need a little more info from you so that we can better help you with your issue. Would you mind posting a code sample, plunkr or codepen that we can use to reproduce your issue? Also, would you mind running `ionic info` and posting the output? Thanks again!

**Comment by jgw96** [comment] 2016-03-21 18:14
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!

**Closed by jgw96** 2016-03-21 18:14 UTC
Labels: scroll
