### ISSUE TITLE
Error when running "ionic platform" on windows 10

### ISSUE THREAD

**Issue by trinhvanhuy** [driftyco/ionic#6737] opened 2016-06-02 15:10 UTC
Hello,
  I'm working on a project that have to work well on iOS, Android and Windows 10 Mobile
  The application has no problem with iOS and Android ( buid on Mac OSX ) but when i try to build the application in windows 10 , when trying to run "ionic platform add windows" it give me this error   :  

```
ionic platform
Caught exception:
 TypeError: Cannot read property 'slice' of undefined
    at Object.run (C:\Users\TRINH Van Huy\AppData\Roaming\npm\node_modules\ionic\lib\ionic\platform.js:35:32)
    at Promise.apply (C:\Users\TRINH Van Huy\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:1078:26)
    at Promise.promise.promiseDispatch (C:\Users\TRINH Van Huy\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:741:41)
    at C:\Users\TRINH Van Huy\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:1304:14
    at flush (C:\Users\TRINH Van Huy\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:108:17)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
```

( but  "cordova platform add windows" worked as expected )

OS : Windows 10
ionic-cli : v2.0.0-beta.26
cordova-cli : v6.2.0

ionic version 2.x

Thanks in advance

**Comment by jgw96** [comment] 2016-06-02 16:04
Hello! Thanks for opening an issue with us! I will be closing this issue as a dupe of https://github.com/driftyco/ionic/issues/6735. Thanks for using Ionic!

**Closed by jgw96** 2016-06-02 16:04 UTC
Labels: platform:android, platform:ios, v2

**Comment by trinhvanhuy** [comment] 2016-06-03 11:30
Thanks so much
It's worked
