### ISSUE TITLE
VirtualScroll bug with async data

### ISSUE THREAD

**Issue by osamasoliman** [driftyco/ionic#11717] opened 2017-05-18 14:59 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

`Cannot read property 'length' of null`
when loading data to virtualScroll asynchronously 

**Expected behavior:**
it should wait for data to come then display it

**Steps to reproduce:**
please clone this repo it's super starter just changed displaying array to be observable with a timeout and added virtualScroll with async pipe instead of *ngFor
https://github.com/osamasoliman/VirtualScrollAsyncIsuue

**Related code:**

```
setTimeout(()=>{
      this.currentItems = Observable.of(this.items.query());
},1000)
<ion-list [virtualScroll]="currentItems | async">
    <ion-item-sliding *virtualItem="let item">
    </ion-item-sliding>
</ion-list>
```

**Other information:**
[http://i.imgur.com/qNAwpBa.png](url)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.1.2
    Ionic CLI        : 3.1.2

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-ionic-angular : 1.1.2
    Ionic Framework                 : ionic-angular 3.2.1

System:

    Node       : v7.9.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by jgw96** [comment] 2017-05-18 15:34
Hello, thanks for using Ionic. I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/11439.

**Closed by jgw96** 2017-05-18 15:34 UTC
