### ISSUE TITLE
Sidemenu item wont click during menutoggle 

### ISSUE THREAD

**Issue by kabus202** [driftyco/ionic#10268] opened 2017-02-01 10:41 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When clicking on menutoggle, during opening sidemenu clicking on a menu item will not work. On a browser it's acceptable. But on iOS it feels like the sidemenu is broken (delay of +-500ms).

**Expected behavior:**
After opening the sidemenu able to directly click a link. 

**Steps to reproduce:**

just download the sidemenu template 

**Related code:**

![feb -01-2017 11-38-19](https://cloud.githubusercontent.com/assets/5297717/22503655/05eac2a4-e873-11e6-8a17-4a8a3908a539.gif)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.4
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment] 2017-02-02 15:31
Hello, thanks for using Ionic! Unfortunately i cannot reproduce this issue, would you be able to post a repo i can use to reproduce this? Also are you using the iOS sim to reproduce this issue or an actual device?

**Comment by jgw96** [comment] 2017-02-06 16:56
Hello all! As it seems it has been a while since there was any activity on this issue and i cannot reproduce it i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-02-06 16:56 UTC
Labels: needs reply, v2
