### ISSUE TITLE
Ionic icons are not showing up in the screen

### ISSUE THREAD

**Issue by forethoughtde** [driftyco/ionic#9792] opened 2016-12-25 12:27 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X ] **2.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I am facing difficulties in showing ion-icon in the screen. The following is the HTML code which I use; 
```
<ion-item>
<button ion-button icon-only clear small color="twitter">
      <ion-icon name="logo-twitter"></ion-icon>
    </button>
            <ion-label color="primary">Title</ion-label>
            <ion-input type="text"></ion-input>
        </ion-item>
```
For some reasons, ion-icon does not show up in the screen. 
**Expected behavior:**
Use the above snippet in your app to observe the behaviour.

**Comment by jgw96** [comment] 2016-12-27 15:46
Hello, thanks for using ionic! Unfortunately I cannot seem to reproduce this issue. I made this plunker http://plnkr.co/edit/z0DzVL?p=preview  that demonstrates it working. Could you make a plunker that I can use to reproduce this issue? Thanks!

**Comment by nextbigtech** [comment] 2016-12-31 13:57
I have the same problem..i tried this..  https://github.com/driftyco/ionic-preview-app/tree/master/src/pages/cards/image

dont know if I missed something. I am on ionic 2.

**Comment by jgw96** [comment] 2017-01-10 22:16
Hey @forethoughtde and @nextbigtech , unfortunately i cannot reproduce this issue with either the preview app, the conf app or in that plunker i posted above. Could you guys post a repo i can use to reproduce this issue? Thanks!

**Comment by jgw96** [comment] 2017-01-20 15:59
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-01-20 15:59 UTC
Labels: needs reply, v2

**Comment by ag14774** [comment] 2017-08-09 13:10
Still having this issue with ionic v. 3.7.0
This code:
```html
    <ion-col>
      <button ion-button icon-left clear small>
        <ion-icon name="thumbs-up"></ion-icon>
        <div>{{story.numofvotes}} Likes</div>
      </button>
    </ion-col>
```
generates this (right click->inspect):
![deepinscreenshot_select-area_20170809160649](https://user-images.githubusercontent.com/10788242/29123071-269ca730-7d1d-11e7-85e0-b42d2f8b77bb.png)


Adding `class="ion-md-thumbs-up"` to the ion-icon tag fixes the issue but I don't think that is the correct way to do it

**Comment by bharat-tiwari** [comment] 2018-02-27 22:48
I am getting the same issue

**Comment by zgluis** [comment] 2018-03-01 13:24
I found my problem, I was overriding ionicons with this:

```
* {
  font-family: "my-cool-font" !important;
}
```

**Comment by suvsah** [comment] 2018-03-08 14:48
I guess the same issue is in Ionic Creator app viewer too!!!

**Comment by tickylum** [comment] 2018-03-08 20:38
@suvsah I have the same problem too! The icons are showing fine when I do "ionic serve", but when I build an apk, the icons (everywhere... like tabs and buttons with images) are showing with a small X in a box... Can't get it to work!! :(
If anyone knows which references are missing, please guide us here?

**Comment by MujtabaJ** [comment] 2018-05-25 06:12
Dears
I have found a solution for this problem when we are adding user defined css class in ionic tag where we are going to show icons at that time the inner class will differ and icons are not show as usual.
