### ISSUE TITLE
bug: $ionicPopup 'scope' option won't accept Object

### ISSUE THREAD

**Issue by AzMoo** [driftyco/ionic#4178] opened 2015-08-03 02:43 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>If I try and call $ionicPopup passing an object to scope it fails with the error: 

TypeError: (options.scope || $rootScope).$new is not a function

Replicate with: 

```javascript
$ionicPopup.alert({
	title: 'stuff',
	templateUrl: 'mytemplate.html',
	scope: {
		foo: 'bar'
	}
});
```

Error is here: https://github.com/driftyco/ionic/blob/master/js/angular/service/popup.js#L286

Fix should be just to replace that line with code similar to the following from modal.js (https://github.com/driftyco/ionic/blob/master/js/angular/service/modal.js#L266)

```javascript
var scope = options.scope && options.scope.$new() || $rootScope.$new(true);
```

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-08-03 02:43
Greetings @AzMoo!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4178). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4178)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment] 2015-08-12 03:06
Thanks, will look at this.

**Comment by nicoabie** [comment] 2015-12-15 17:58
It is not a bug [the doc](http://ionicframework.com/docs/api/service/$ionicPopup/) says that scope should be a scope object
```scope: null, // Scope (optional). A scope to link to the popup content.``` 
and not a plain object as @AzMoo is trying to use.

**Comment by jgw96** [comment] 2016-04-12 20:25
Hello! @AzMoo Please feel free to comment on this issue if your still running into the issue, but it looks like @nicoabie is correct and that it should be a scope object. Thanks!

**Closed by jgw96** 2016-04-12 20:25 UTC
Labels: alert, ready, v1
