### ISSUE TITLE
Proposal: ionic start in current working directory

### ISSUE THREAD

**Issue by slezica** [driftyco/ionic#3801] opened 2015-05-21 19:01 UTC
Right now, `ionic start .` is interpreted as "create a project named `.`".

    $ mkdir project; cd project
    $ ionic start .
    Please name your Ionic project something meaningful other than '.'

Instead, `ionic start .` could take the project name from the current working directory

    $ mkdir project; cd project
    $ ionic start .
    Creating Ionic app in folder /home/me/project

I don't think this behaviour is surprising, but the user could be asked to approve if `ionic` is running in an interactive shell (`ionic start` is not a command that you repeatedly run):

    $ ionic start .
    Create project in current directory? [Y/n]

**Comment by Ionitron** [comment] 2015-05-21 19:01
Greetings @slezica!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3801). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3801)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment] 2015-05-22 19:30
Turning an existing directory in to an ionic project opens a bigger can of worms than the benefits weigh. Sorry, not this time around.

**Closed by perrygovier** 2015-05-22 19:30 UTC

**Comment by Cheezmeister** [comment] 2015-10-25 01:55
What kind of worms, exactly?

**Comment by nycynik** [comment] 2017-10-12 14:31
I think the README should probably be changed then, to say, start with `ionic start proj tabs` then cd into that directory, and then do git add remote, git push.  

I think the problem is people make the repo, check it out (or just `git init`) and then try to run the ionic start command, and it fails, or it makes another folder in their project, and they are confused.
