### ISSUE TITLE
bug: Back Button in IOS fire 2 times

### ISSUE THREAD

**Issue by baltazaroliveira** [driftyco/ionic#3640] opened 2015-04-29 09:47 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>I have created a Ionic App with 3 views.

In Chrome, Android, Safari works as expected.

The last view in Chrome, Android, Safari. (All OK)

In IOS the view stays like that (the "title" stays Back), when click in the button it goes 2 views back...

Link in Forum
http://forum.ionicframework.com/t/back-button-fire-2-times-ios-only/21764

Any solution?

Thanks
Baltazar</span>

<span is-issue-template></span>

**Comment by Keats** [comment] 2015-05-06 09:29
We have the same issue roughly, on one view (view C) the back button goes back 2 views back (view A) on iOS only, works fine on browsers and android where they go back to view B.
There is no code in the view B that could transition to view A (I commented out the only $state.go).

Is there a way to see where the stateChangeStart event is starting from ? (back button etc)

**Comment by perrygovier** [comment] 2015-05-20 21:39
I don't see this in my apps. Could you share a codepen that reproduces the issue?

**Comment by baltazaroliveira** [comment] 2015-05-21 08:16
In Chrome, Android, Safari works as expected.

If i create a CodePen will work OK. In IOS don´t do the "default"

**Comment by calimeroteknik** [comment] 2015-05-27 13:46
It also happens in Android actually, but you need to be really fast.
If you tap the button like a maniac, sometimes it goes back two views. I'm sure, because the previous view does not have a back button, I disabled it.

**Comment by calendee** [comment] 2015-05-29 11:18
Seeing this as well - except not on the back button.  I have some instances where buttons in a subheader fire twice.  In one instance, this button triggers an `$ionicHistory.goBack()`.   Because the button fires twice, the go back is done twice.  

I'm overcoming this with a debounce function to only go back one time.

Sample : FYI : The button is associated with a form ng-submit event, so, the click is handled by ng-submit method.
```
<ion-header-bar align-title="left" class="bar-subheader bar-form-controls">
  <div class="button-bar">
    <button class="button button-icon button-balanced" ng-class="{ 'ion-checkmark-circled' : cCtrl.editing, 'ion-ios-compose' : !cCtrl.editing }">
      <span ng-show="cCtrl.editing">Save</span>
      <span ng-show="!cCtrl.editing">Edit</span>
    </button>
    <a class="button button-icon button-assertive" ng-class="{ 'ion-ios-trash' : !cCtrl.editing, 'ion-close-circled' : cCtrl.editing }" ng-click="cCtrl.destructiveAction(contactForm)">
      <span ng-show="!cCtrl.editing">Delete</span>
      <span ng-show="cCtrl.editing">Cancel</span>
    </a>
  </div>
</ion-header-bar>
```

**Comment by jgw96** [comment] 2016-03-23 19:05
Hello! Are you all still experiencing this issue?

**Comment by baltazaroliveira** [comment] 2016-03-24 08:49
I don´t have a Iphone right now to do that test.

I hope that someone give that confirmation if the bug still exists or not.

**Comment by jgw96** [comment] 2016-03-24 14:42
@baltazaroliveira no problem! If you get a chance to test feel free to post your findings!

**Comment by mubasshir** [comment] 2016-03-26 14:00
I'm facing same issue in Android and as well as on iOS? any possible solution or can we override back button function?

**Comment by jgw96** [comment] 2016-04-25 21:33
@mubasshir Thanks for the info! Unfortunately im having trouble reproducing this issue with any of my apps. Would you mind putting together a plunker or a codepen that demonstrates this issue? Thanks!

**Comment by jgw96** [comment] 2016-05-02 16:14
Hello! As it has been a little while since there was any activity on this issue i will be closing it for now. Feel free to comment though!

**Closed by jgw96** 2016-05-02 16:14 UTC
Labels: navigation, needs reply, v1

**Comment by LeVadim** [comment] 2016-06-05 15:36
Same issue with go back button. It fires twice!!

**Comment by tejit2004** [comment] 2016-08-22 13:33
Hi Guys, sometimes it fires twise both in android and iOS.

**Comment by andrezap** [comment] 2016-09-20 00:06
Im have this issue, ionic 2.11

**Comment by shashankdevp** [comment] 2016-11-28 09:51
I am also facing the same issue but only on IOS. Its like when I press the back button it fires twice making it go two view back. 

When I added a timeout in my custom back method it started working as excepted. So I feel it some kind of a timeout issue. Can any one provide a better solution.

**Comment by JHLIV** [comment] 2017-01-04 19:19
Hi!
I faced the same issue with button tags in general with ng-click. For some searon if you use the button tag with no type specified it triggers the ngClick function twice.

to solve this just had to put type="button" in each <button> tag.

Fortunately if you set this attribute in the <ion-nav-back-button> directive it is transferred to the <button> tag.

**Comment by tpflueger** [comment] 2017-01-08 22:18
@JHLIV So glad to find your response, I just recently noticed this. Thanks for the fix!

**Comment by calimeroteknik** [comment] 2017-01-10 16:48
@jgw96 you closed this even though the bug has still been present for all that time.
A workaround has been found, maybe it's time to fix ionic itself using it?
