### ISSUE TITLE
Error when using gestures in ionic 2

### ISSUE THREAD

**Issue by jvoigt** [driftyco/ionic#5751] opened 2016-03-07 12:45 UTC
#### Short description of the problem:
When using Gestures Exceptions is raised
via `<ion-content home on-pan="hello()">`
```
EXCEPTION: RangeError: Maximum call stack size exceeded
app.bundle.js:34050 EXCEPTION: RangeError: Maximum call stack size exceededBrowserDomAdapter.logError @ app.bundle.js:34050BrowserDomAdapter.logGroup @ app.bundle.js:34060ExceptionHandler.call @ app.bundle.js:7828(anonymous function) @ app.bundle.js:17008NgZone._notifyOnError @ app.bundle.js:17667collection_1.StringMapWrapper.merge.onError @ app.bundle.js:17562Zone.run @ app.bundle.js:2262(anonymous function) @ app.bundle.js:17580NgZone.run @ app.bundle.js:17528handler @ app.bundle.js:33036(anonymous function) @ app.bundle.js:33036Zone.run @ app.bundle.js:2258(anonymous function) @ app.bundle.js:17580NgZone.run @ app.bundle.js:17528handler @ app.bundle.js:33036(anonymous function) @ app.bundle.js:33036Zone.run @ app.bundle.js:2258(anonymous function) @ app.bundle.js:17580NgZone.run @ app.bundle.js:17528handler @ app.bundle.js:33036(anonymous function) @ app.bundle.js:33036Zone.run @ app.bundle.js:2258(anonymous function) @ app.bundle.js:17580NgZone.run @ app.bundle.js:17528handler @ app.bundle.js:33036(anonymous function) @ app.bundle.js:33036Zone.run @ app.bundle.js:2258(anonymous function) @ app.bundle.js:17580NgZone.run @ app.bundle.js:17528handler @ app.bundle.js:33036(anonymous function) @ app.bundle.js:33036Zone.run @ app.bundle.js:2258(anonymous function) @ app.bundle.js:17580NgZone.run @ app.bundle.js:17528handler @ app.bundle.js:33036(anonymous function) @ app.bundle.js:33036Zone.run @ app.bundle.js:2258(anonymous function) @ app.bundle.js:17580NgZone.run @ app.bundle.js:17528handler @ app.bundle.js:33036(anonymous function) @ app.bundle.js:33036Zone.run @ app.bundle.js:2258(anonymous function) @ app.bundle.js:17580NgZone.run @ app.bundle.js:17528handler @ app.bundle.js:33036(anonymous function) @ app.bundle.js:33036Zone.run @ app.bundle.js:2258(anonymous function) @ app.bundle.js:17580NgZone.run @ app.bundle.js:17528handler @ app.bundle.js:33036(anonymous function) @ app.bundle.js:33036Zone.run @ app.bundle.js:2258(anonymous function) @ app.bundle.js:17580NgZone.run @ app.bundle.js:17528handler @ app.bundle.js:33036(anonymous function) @ app.bundle.js:33036Zone.run @ app.bundle.js:2258(anonymous function) @ app.bundle.js:17580NgZone.run @ app.bundle.js:17528handler @ app.bundle.js:33036(anonymous function) @ app.bundle.js:33036Zone.run @ app.bundle.js:2258(anonymous function) @ app.bundle.js:17580NgZone.run @ app.bundle.js:17528handler @ app.bundle.js:33036(anonymous function) @ app.bundle.js:33036Zone.run @ app.bundle.js:2258(anonymous function) @ app.bundle.js:17580NgZone.run @ app.bundle.js:17528handler @ app.bundle.js:33036(anonymous function) @ app.bundle.js:33036Zone.run @ app.bundle.js:2258(anonymous function) @ app.bundle.js:17580NgZone.run @ app.bundle.js:17528handler @ app.bundle.js:33036(anonymous function) @ app.bundle.js:33036Zone.run @ app.bundle.js:2258(anonymous function) @ app.bundle.js:17580NgZone.run @ app.bundle.js:17528handler @ app.bundle.js:33036Manager.emit @ app.bundle.js:45378emit @ app.bundle.js:44508Recognizer.emit @ app.bundle.js:44514inherit.emit @ app.bundle.js:44773Recognizer.tryEmit @ app.bundle.js:44531Recognizer.recognize @ app.bundle.js:44572Manager.recognize @ app.bundle.js:45254inputHandler @ app.bundle.js:43698MTEhandler @ app.bundle.js:44121Input.domHandler @ app.bundle.js:43621Zone.run @ app.bundle.js:2258zoneBoundFn @ app.bundle.js:2235
app.bundle.js:34050 STACKTRACE:BrowserDomAdapter.logError @ app.bundle.js:34050ExceptionHandler.call @ app.bundle.js:7830(anonymous function) @ app.bundle.js:17008NgZone._notifyOnError @ app.bundle.js:17667collection_1.StringMapWrapper.merge.onError @ app.bundle.js:17562Zone.run @ app.bundle.js:2262(anonymous function) @ app.bundle.js:17580NgZone.run @ app.bundle.js:17528handler @ app.bundle.js:33036(anonymous function) @ app.bundle.js:33036Zone.run @ app.bundle.js:2258(anonymous function) @ app.bundle.js:17580NgZone.run @ app.bundle.js:17528handler @ app.bundle.js:33036(anonymous function) @ app.bundle.js:33036Zone.run @ app.bundle.js:2258(anonymous function) @ app.bundle.js:17580NgZone.run @ app.bundle.js:17528handler @ app.bundle.js:33036(anonymous function) @ app.bundle.js:33036Zone.run @ app.bundle.js:2258(anonymous function) @ app.bundle.js:17580NgZone.run @ app.bundle.js:17528handler @ app.bundle.js:33036(anonymous function) @ app.bundle.js:33036Zone.run @ app.bundle.js:2258(anonymous function) @ app.bundle.js:17580NgZone.run @ app.bundle.js:17528handler @ app.bundle.js:33036(anonymous function) @ app.bundle.js:33036Zone.run @ app.bundle.js:2258(anonymous function) @ app.bundle.js:17580NgZone.run @ app.bundle.js:17528handler @ app.bundle.js:33036(anonymous function) @ app.bundle.js:33036Zone.run @ app.bundle.js:2258(anonymous function) @ app.bundle.js:17580NgZone.run @ app.bundle.js:17528handler @ app.bundle.js:33036(anonymous function) @ app.bundle.js:33036Zone.run @ app.bundle.js:2258(anonymous function) @ app.bundle.js:17580NgZone.run @ app.bundle.js:17528handler @ app.bundle.js:33036(anonymous function) @ app.bundle.js:33036Zone.run @ app.bundle.js:2258(anonymous function) @ app.bundle.js:17580NgZone.run @ app.bundle.js:17528handler @ app.bundle.js:33036(anonymous function) @ app.bundle.js:33036Zone.run @ app.bundle.js:2258(anonymous function) @ app.bundle.js:17580NgZone.run @ app.bundle.js:17528handler @ app.bundle.js:33036(anonymous function) @ app.bundle.js:33036Zone.run @ app.bundle.js:2258(anonymous function) @ app.bundle.js:17580NgZone.run @ app.bundle.js:17528handler @ app.bundle.js:33036(anonymous function) @ app.bundle.js:33036Zone.run @ app.bundle.js:2258(anonymous function) @ app.bundle.js:17580NgZone.run @ app.bundle.js:17528handler @ app.bundle.js:33036(anonymous function) @ app.bundle.js:33036Zone.run @ app.bundle.js:2258(anonymous function) @ app.bundle.js:17580NgZone.run @ app.bundle.js:17528handler @ app.bundle.js:33036(anonymous function) @ app.bundle.js:33036Zone.run @ app.bundle.js:2258(anonymous function) @ app.bundle.js:17580NgZone.run @ app.bundle.js:17528handler @ app.bundle.js:33036(anonymous function) @ app.bundle.js:33036Zone.run @ app.bundle.js:2258(anonymous function) @ app.bundle.js:17580NgZone.run @ app.bundle.js:17528handler @ app.bundle.js:33036Manager.emit @ app.bundle.js:45378emit @ app.bundle.js:44508Recognizer.emit @ app.bundle.js:44514inherit.emit @ app.bundle.js:44773Recognizer.tryEmit @ app.bundle.js:44531Recognizer.recognize @ app.bundle.js:44572Manager.recognize @ app.bundle.js:45254inputHandler @ app.bundle.js:43698MTEhandler @ app.bundle.js:44121Input.domHandler @ app.bundle.js:43621Zone.run @ app.bundle.js:2258zoneBoundFn @ app.bundle.js:2235
app.bundle.js:34050 RangeError: Maximum call stack size exceeded
    at RangeError.get stack (native)
    at NgZone._notifyOnError (http://localhost:8100/build/js/app.bundle.js:17658:50)
    at Zone.collection_1.StringMapWrapper.merge.onError (http://localhost:8100/build/js/app.bundle.js:17562:126)
    at Zone.run (http://localhost:8100/build/js/app.bundle.js:2262:24)
    at Zone.run (http://localhost:8100/build/js/app.bundle.js:17580:43)
    at NgZone.run (http://localhost:8100/build/js/app.bundle.js:17528:41)
    at handler (http://localhost:8100/build/js/app.bundle.js:33036:55)
    at http://localhost:8100/build/js/app.bundle.js:33036:73
    at Zone.run (http://localhost:8100/build/js/app.bundle.js:2258:25)
    at Zone.run (http://localhost:8100/build/js/app.bundle.js:17580:43)

```

**Ionic Version**:CLI v2.0.0-beta.17

**Browser & Operating System**: Chrome

```
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
OS:
Node Version: v5.6.0

```

**Comment by jvoigt** [comment] 2016-03-07 12:58
Possible Workaround: use Hammer.js directly
no Imports needed
Somewhere in the Page Class:
```
        let myElement = document.getElementById('home-content');
        let hammertime = new Hammer(myElement);
        hammertime.on('pan', (data)=> {
            console.log("PAN",data);
        });
```

**Comment by adamdbradley** [comment] 2016-03-07 13:15
Duplicate of #5663 

It looks like it's a ng2 bug, but there's a PR ready to be merged.

**Closed by adamdbradley** 2016-03-07 13:15 UTC
Labels: range, v2
