### ISSUE TITLE
Ionic 2 Android 4.4

### ISSUE THREAD

**Issue by John0x** [driftyco/ionic#9007] opened 2016-11-03 12:49 UTC
#### Short description of the problem:
The Tabbar does not correctly work on Android 4.4.4. It apperas under the header bar (the header bar is in top of it).

**Steps to reproduce:**
1. Create a tabbed template with ionic

**Which Ionic Version?** 1.x or 2.x
Newest (2 rc1)

**Comment by jgw96** [comment] 2016-11-07 10:26
Hello, would you mind posting a screenshot of what you are seeing? Thanks!

**Comment by John0x** [comment] 2016-11-07 10:28
@jgw96 there is not really much to show. On a page which has a header navbar and a tab component the header of the tab component will not be shown since it is rendered beneath the header navbar.

**Comment by thanzen** [comment] 2016-11-10 18:16
![screenshot_2016-11-10-10-11-17](https://cloud.githubusercontent.com/assets/1901357/20188671/98df1f8c-a72e-11e6-9b05-2b3f95108022.jpeg)
Your system information:

Cordova CLI: 6.4.0
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
OS: Windows 7 SP1
Node Version: v6.7.0

**Comment by dragonahao** [comment] 2016-11-17 13:29
It occurred in UC-Browser

**Comment by jgw96** [comment] 2016-11-18 21:20
Hello all! Does this still occur in rc3? Also, are you all able to repro this in the Android 4.4.4 simulator? I am not able to unfortunately.

**Comment by jgw96** [comment] 2016-12-13 08:07
Hello! Because i am not able to reproduce this issue I am going to close this one for now. Thanks and feel free to comment if you are still having this issue!

**Closed by jgw96** 2016-12-13 08:07 UTC
Labels: needs reply, v2
