### ISSUE TITLE
URGENT: VirtualScroll is now broken on latest 2.3.0 version

### ISSUE THREAD

**Issue by Sh1d0w** [driftyco/ionic#10907] opened 2017-03-24 13:56 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Version 2.2.0 of ionic-angular was working just fine with data coming from observable source and async pipe. Updating to ionic-angular 2.3.0 makes the same virtual scroll to not render at all

**Expected behavior:**
Virtual scroll should work just like in version 2.2.0 when the data is passed via async pipe (observable)

**Steps to reproduce:**

**Related code:**

```
<ion-list [virtualScroll]="items | async">

  <ion-item *virtualItem="let item">
    {{ item }}
  </ion-item>

</ion-list>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

    Cordova CLI: 6.4.0 
    Ionic Framework Version: 2.3.0
    Ionic CLI Version: 3.0.0-beta.4
    ios-deploy version: 1.9.0 
    ios-sim version: 5.0.13 
    OS: macOS Sierra
    Node Version: v7.7.3
    Xcode version: Xcode 8.2.1 Build version 8C1002

```

**Comment by Sh1d0w** [comment] 2017-03-24 14:00
I think one of those commits broke it:

https://github.com/driftyco/ionic/commit/999efac
https://github.com/driftyco/ionic/commit/51c398d

cc @manucorporat

**Comment by Ross-Rawlins** [comment] 2017-03-26 12:47
I also added a bug on this.

**Comment by Microsmsm** [comment] 2017-03-28 14:08
I also have this problem

**Comment by DiegoGuimaDev** [comment] 2017-03-30 01:31
i also have this problem too...

**Comment by jgw96** [comment] 2017-04-04 19:12
Hello all, I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/10971.

**Closed by jgw96** 2017-04-04 19:12 UTC
Labels: v2
