### ISSUE TITLE
feat: tsconfig.json target es6 for async/await

### ISSUE THREAD

**Issue by danbucholtz** [driftyco/ionic#5394] opened 2016-02-10 19:44 UTC
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I have been trying to enable await/async in my typescript project by modifying the tsconfig.json compilerOptions' target to be es6.

When I run "ionic serve", I am seeing the following errors:

ERROR in [default] /Users/bucholda/Dev/b3-audit-app-v2/node_modules/angular2/typings/es6-shim/es6-shim.d.ts:6:13
Duplicate identifier 'PropertyKey'.

ERROR in [default] /Users/bucholda/Dev/b3-audit-app-v2/node_modules/angular2/typings/es6-shim/es6-shim.d.ts:9:4
Duplicate identifier 'done'.

ERROR in [default] /Users/bucholda/Dev/b3-audit-app-v2/node_modules/angular2/typings/es6-shim/es6-shim.d.ts:10:4
Duplicate identifier 'value'.

ERROR in [default] /Users/bucholda/Dev/b3-audit-app-v2/node_modules/angular2/typings/es6-shim/es6-shim.d.ts:248:4
Duplicate identifier 'EPSILON'.

ERROR in [default] /Users/bucholda/Dev/b3-audit-app-v2/node_modules/angular2/typings/es6-shim/es6-shim.d.ts:283:4
Duplicate identifier 'MAX_SAFE_INTEGER'.

ERROR in [default] /Users/bucholda/Dev/b3-audit-app-v2/node_modules/angular2/typings/es6-shim/es6-shim.d.ts:290:4
Duplicate identifier 'MIN_SAFE_INTEGER'.

ERROR in [default] /Users/bucholda/Dev/b3-audit-app-v2/node_modules/angular2/typings/es6-shim/es6-shim.d.ts:346:4
Duplicate identifier 'flags'.

ERROR in [default] /Users/bucholda/Dev/b3-audit-app-v2/node_modules/angular2/typings/es6-shim/es6-shim.d.ts:498:4
Duplicate identifier 'prototype'.

ERROR in [default] /Users/bucholda/Dev/b3-audit-app-v2/node_modules/angular2/typings/es6-shim/es6-shim.d.ts:561:4
Duplicate identifier 'size'.

ERROR in [default] /Users/bucholda/Dev/b3-audit-app-v2/node_modules/angular2/typings/es6-shim/es6-shim.d.ts:570:4
Duplicate identifier 'prototype'.

ERROR in [default] /Users/bucholda/Dev/b3-audit-app-v2/node_modules/angular2/typings/es6-shim/es6-shim.d.ts:581:4
Duplicate identifier 'size'.

ERROR in [default] /Users/bucholda/Dev/b3-audit-app-v2/node_modules/angular2/typings/es6-shim/es6-shim.d.ts:590:4
Duplicate identifier 'prototype'.

ERROR in [default] /Users/bucholda/Dev/b3-audit-app-v2/node_modules/angular2/typings/es6-shim/es6-shim.d.ts:605:4
Duplicate identifier 'prototype'.

ERROR in [default] /Users/bucholda/Dev/b3-audit-app-v2/node_modules/angular2/typings/es6-shim/es6-shim.d.ts:619:4
Duplicate identifier 'prototype'.

ERROR in [default] /Users/bucholda/Dev/b3-audit-app-v2/node_modules/typescript/lib/lib.es6.d.ts:3841:13
Duplicate identifier 'PropertyKey'.

ERROR in [default] /Users/bucholda/Dev/b3-audit-app-v2/node_modules/typescript/lib/lib.es6.d.ts:4061:4
Duplicate identifier 'EPSILON'.

ERROR in [default] /Users/bucholda/Dev/b3-audit-app-v2/node_modules/typescript/lib/lib.es6.d.ts:4096:4
Duplicate identifier 'MAX_SAFE_INTEGER'.

ERROR in [default] /Users/bucholda/Dev/b3-audit-app-v2/node_modules/typescript/lib/lib.es6.d.ts:4103:4
Duplicate identifier 'MIN_SAFE_INTEGER'.

ERROR in [default] /Users/bucholda/Dev/b3-audit-app-v2/node_modules/typescript/lib/lib.es6.d.ts:4389:4
Duplicate identifier 'done'.

ERROR in [default] /Users/bucholda/Dev/b3-audit-app-v2/node_modules/typescript/lib/lib.es6.d.ts:4390:4
Duplicate identifier 'value'.

ERROR in [default] /Users/bucholda/Dev/b3-audit-app-v2/node_modules/typescript/lib/lib.es6.d.ts:4619:4
Duplicate identifier 'flags'.

ERROR in [default] /Users/bucholda/Dev/b3-audit-app-v2/node_modules/typescript/lib/lib.es6.d.ts:4647:4
Duplicate identifier 'size'.

ERROR in [default] /Users/bucholda/Dev/b3-audit-app-v2/node_modules/typescript/lib/lib.es6.d.ts:4657:4
Duplicate identifier 'prototype'.

ERROR in [default] /Users/bucholda/Dev/b3-audit-app-v2/node_modules/typescript/lib/lib.es6.d.ts:4674:4
Duplicate identifier 'prototype'.

ERROR in [default] /Users/bucholda/Dev/b3-audit-app-v2/node_modules/typescript/lib/lib.es6.d.ts:4686:4
Duplicate identifier 'size'.

ERROR in [default] /Users/bucholda/Dev/b3-audit-app-v2/node_modules/typescript/lib/lib.es6.d.ts:4696:4
Duplicate identifier 'prototype'.

ERROR in [default] /Users/bucholda/Dev/b3-audit-app-v2/node_modules/typescript/lib/lib.es6.d.ts:4712:4
Duplicate identifier 'prototype'.

ERROR in [default] /Users/bucholda/Dev/b3-audit-app-v2/node_modules/typescript/lib/lib.es6.d.ts:5099:4
Duplicate identifier 'prototype'.

** I recognize that by setting the target to es6, we will need to do another transpilation step to use es5.  I was thinking a second loader in the webpack config for babel would work.  I am not sure - haven't crossed that bridge yet.</span>

<span is-issue-template></span>

**Comment by tlancina** [comment] 2016-02-10 20:21
Changing that property alone on a new starter project doesn't reproduce the error for me, I just get runtime errors about unsupported ES6 features.

It looks from the errors like Angular 2 is being included twice, do you have symlinks to any of your npm packages?

**Comment by danbucholtz** [comment] 2016-02-10 20:30
I should note that I see this with a typescript project vs a JS project that is just using typescript compiler for transpiling.

Steps to reproduce:
1.  ionic start my-super-project-name --v2 --ts -t sidemenu
2.  ionic serve

** things work **

3.  cancel ionic-serve
4.  Modify tsconfig.json compilerOptions' target to es6
5.  ionic serve

** error happens **

**Comment by tlancina** [comment] 2016-02-10 20:36
Excellent, thanks for the reproduction case.  Taking a look now.

**Comment by tlancina** [comment] 2016-02-10 20:47
I'm wondering if this is an issue with Angular2 typings: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/5015.

**Comment by tlancina** [comment] 2016-02-10 21:00
So it looks like when TypeScript targets ES6 it includes its own type definitions in `lib.es6.d.ts`, which clash with the ones Angular 2 ships with in `typings/es6-shim/es6-shim.d.ts`.

I'm going to close this as a duplicate of: https://github.com/angular/angular/issues/6572, since there isn't much Ionic can do about it.

As a workaround, you can remove the reference to the ES6 definitions in `node_modules/angular2/typings/zone/zone.d.ts` (this looks like the only place, at least for the starters, where Angular references their ES6 typings).

**Closed by tlancina** 2016-02-10 21:00 UTC
Labels: feature, v2
