### ISSUE TITLE
templateUpdate not updating

### ISSUE THREAD

**Issue by abetsagaral** [driftyco/ionic#8641] opened 2016-10-12 09:10 UTC
after editing some html elements from /pages/mypage.html, it takes too long to load the page.

templateUpdate started ...
templateUpdate started ...

Cordova CLI: 6.3.1
Gulp version:  CLI version 1.2.2
Gulp local:  
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0-beta.2
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.8.6 
ios-sim version: 1.9.0 
OS: Mac OS X El Capitan
Node Version: v3.3.1
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment] 2016-10-12 20:45
Hello, thanks for using Ionic! I am going to close this as a duplicate of https://github.com/driftyco/ionic-app-scripts/issues/47.

**Closed by jgw96** 2016-10-12 20:45 UTC
