### ISSUE TITLE
Ionic 2 Keyboard hides the input field

### ISSUE THREAD

**Issue by REPTILEHAUS** [driftyco/ionic#10392] opened 2017-02-10 13:01 UTC
Coming across this issue with an ion-input in the ion-footer of my app. when I click on the input to start typing the iphone keyboard goes up over it essentially hiding it. Exact same issue highlighted here https://github.com/driftyco/ionic/issues/5432 and I have a temporary fix with this snippet  https://gist.github.com/Manduro/bc121fd39f21558df2a952b39e907754 however if you have a submit button in the footer you have to click it twice in order to post the forms data so its not perfect but stil pretty good any idea when an official fix will be out ?

**Comment by jgw96** [comment] 2017-02-10 21:30
Hello, thanks for using Ionic! Unfortunately we do not have a fix for this at the moment as it is an issue in UiWebView itself. We are currently working on a workaround. I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/5432.

**Closed by jgw96** 2017-02-10 21:30 UTC
