### ISSUE TITLE
bug: Empty ion-navbar-section is displayed when shouldn

### ISSUE THREAD

**Issue by ErkoKnoll** [driftyco/ionic#5775] opened 2016-03-09 09:13 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x beta1</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>When the page that is used inside a tab does not have navbar section, but has simple ion-content then empty ion-navbar-section is added anyway which is taking up space. Also attached an image for better understanding. Desired behavior is to hide that navbar section for all tabbed pages.</span>

![navbarbug](https://cloud.githubusercontent.com/assets/9930079/13630440/07f2433a-e5e8-11e5-8bc7-2b8882095946.png)

<span is-issue-template></span>

**Comment by brandyscarney** [comment] 2016-03-09 16:29
Thanks for the issue! This is a duplicate of this issue: https://github.com/driftyco/ionic/issues/5556

**Closed by brandyscarney** 2016-03-09 16:29 UTC
Labels: platform:android, v2
