### ISSUE TITLE
Ionic v1.2.4, ".ng-enter-stagger" fails after $ionicModal instantiated.

### ISSUE THREAD

**Issue by rajnandan1** [driftyco/ionic#6033] opened 2016-04-03 20:48 UTC
I updated my ionic lib to 1.2.4, and I am using the latest animate.css with the following properties to animate ng-repeat

```
.chat-item.ng-enter {
    -webkit-animation: fadeInLeft 1s;
    animation: fadeInLeft 1s;
}
.chat-item.ng-enter-stagger {
  -webkit-animation-delay:200ms;
  animation-delay:200ms;

  /* override to make sure it's not inherited from other styles */
  -webkit-animation-duration:0;
  animation-duration:0;
}
```
the animation works fine at first, but suppose I instantiate $ionicModal, it stops working. I tested the same with ionic v1.1.1 and it works fine

**Comment by jgw96** [comment] 2016-04-04 20:34
Hello! Thanks for opening an issue with us! Would you be able to provide a plunkr or codepen for us to use to reproduce this issue?

**Comment by jgw96** [comment] 2016-04-11 16:02
As it has been a little while since there was any activity on this issue I will be closing it for now, please feel free to reply if you are still experiencing this issue though!

**Closed by jgw96** 2016-04-11 16:02 UTC
Labels: animation, modals, needs reply, related to external library, v1
