### ISSUE TITLE
feat: Show left side menu at start

### ISSUE THREAD

**Issue by sgg90** [driftyco/ionic#3499] opened 2015-04-10 10:06 UTC
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi,

When I enter on the "list" state I would like to see the side left template opened and then close it choosing something from my list and show it on the side menu content. Is there a way to show the left side menu at start or force it to be shown?

Thank you!!

States:
```
.state( routeNames.user, 
		{
			url: stateUrls.user,
			abstract : true,
			views:
			{
				'mainContent' :
				{
					templateUrl: "templates/side-menu.html"
				}
			}
		})
		.state( routeNames.list, 
		{
			url: stateUrls.list,
			abstract : true,
			views: 
			{
				'homeMenuLeft' :
				{
					templateUrl: "templates/sources.html",
					controller: "SourcesController"
				},
				'homeMenuContent' :
				{
					templateUrl: "templates/list.html",
					controller: "ListController"
				}
			}
		})
```

View:
```
<ion-side-menus>
	<ion-side-menu-content edge-drag-threshold="true">
	  <ion-nav-view name="homeMenuContent"> </ion-nav-view>
	</ion-side-menu-content>
	<ion-side-menu expose-aside-when="large">
		<ion-nav-view name="homeMenuLeft"> </ion-nav-view>
	</ion-side-menu>
</ion-side-menus>
```
P.S: Also, when the side left is opened and I click on a popOver it closes the side menu automatically without been spected.

P.S.S: the directive edge-drag-threshold="true" works only on browser, when I build it (on android) I can open the left menu from all the screen.

Thank you!!!
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-04-10 10:06
Greetings @sgg90!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3499). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3499)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment] 2015-04-10 20:08
Greetings @sgg90!

My sensors indicate that I require more information in order to assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this happen occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com), where many humans will be able to offer wisdom and advice.

Thank you for allowing me to assist you.

<span ionitron-needs-reply></span>

**Comment by Ionitron** [comment] 2015-05-11 09:29
Greetings @sgg90!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-05-11 09:29 UTC
Labels: ionitron:closed
