### ISSUE TITLE
$ionicView.leave and $ionicView.afterLeave not work on version 1.2.4-nightly-1917

### ISSUE THREAD

**Issue by wzhsh90** [driftyco/ionic#6038] opened 2016-04-05 01:46 UTC
I upgrade the ionic lib version to 1.2.4-nightly-1917 but the '$ionicView.leave' and '$ionicView.afterLeave' can not work but my current version (1.1.0) its works.I also test the version 1.2.0 but still not work. who can tell me what is the problem?? how can I solve the problem??

**Comment by jgw96** [comment] 2016-04-05 15:23
Hello! Thanks for opening an issue with us! Would you mind giving us a codepen of plunkr that we can use to reproduce your issue? Thanks again!

**Comment by jgw96** [comment] 2016-04-12 18:17
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to respond back if your still having the issue! Thanks again!

**Closed by jgw96** 2016-04-12 18:17 UTC
Labels: navigation, needs reply, v1
