### ISSUE TITLE
Blank page on Android in the version of ionic2.0.0 RC.3  

### ISSUE THREAD

**Issue by 982964399** [driftyco/ionic#9326] opened 2016-11-24 06:22 UTC
Ionic works in "ionic serve" but not in Android.
The page can show in "ionic serve".And It cann't show in android,but I can see "IonicAlert" when it shown.
![222](https://cloud.githubusercontent.com/assets/14900806/20619674/bd9ce792-b330-11e6-8bfb-5447931521ff.png)

**Comment by 982964399** [comment] 2016-11-28 07:03
I have fixed the issue : 
It occurs when "$colors"'s  length reach 20;
I think it is a bug.

![bug](https://cloud.githubusercontent.com/assets/14900806/20658993/bb0eac70-b57b-11e6-8a78-bf5bcdfa70b0.jpg)

**Comment by jgw96** [comment] 2016-11-28 16:16
Hello, thanks for opening an issue with us! Unfortunately I cannot reproduce this issue. What device and version of Android are you seeing this issue on?

**Comment by 982964399** [comment] 2016-11-28 16:30
I have fixed the issue :
It occurs when "$colors"'s length over 20;
I think it is a bug.

**Comment by edismooth** [comment] 2016-12-01 10:25
I've got the same issue. Ionic creates css code:
http://pastebin.com/nYN81QrH
But only on Android, on iOS it is ok.
Like @982964399 - it happens only on big $colors variable.

**Comment by ozexpert** [comment] 2016-12-01 17:30
Same issue here.

**Comment by ozexpert** [comment] 2016-12-03 18:23
This is really blocking my development. Works fine in iOS. Android i get blank screen. 
Browser it's fine. @jgw96

**Comment by iron9light** [comment] 2016-12-03 21:19
I have the same issue with RC3. RC2 works fine.
OnePlus X - android 6.0.1

**Comment by jgw96** [comment] 2016-12-05 16:21
Hello all! After further investigation this is actually a build issue. I am going to close this as a duplicate of https://github.com/driftyco/ionic-app-scripts/issues/506. Thanks!

**Closed by jgw96** 2016-12-05 16:21 UTC
Labels: v2
