### ISSUE TITLE
[Ionic 2] issue with input blur when tapping outside input on iOS

### ISSUE THREAD

**Issue by danielcrk-cn** [driftyco/ionic#6410] opened 2016-05-03 07:33 UTC
This feature was introduced in beta.5 and i love the idea, but right now, the blur happens on the touchstart event (I would guess) rather that on the click event. This makes it impossible to scroll to scroll the view while the keyboard is up. 

If the blur instead happens on a proper click event (or you manually do a check the user actually taped for at least a minimum amount of time and the tap position hasn't changed to much), this would provide a much better (and expected, i think) behaviour.

**Comment by jgw96** [comment] 2016-05-03 21:20
Hello! Thanks for opening an issue with us! Would you mind providing a plunker or codepen that we can use to reproduce this issue? Thanks!

**Comment by jgw96** [comment] 2016-05-10 14:09
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-05-10 14:09 UTC
Labels: needs reply, v2
