### ISSUE TITLE
bug: Android loading spinner stuck

### ISSUE THREAD

**Issue by ErkoKnoll** [driftyco/ionic#6167] opened 2016-04-14 12:47 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>It used to work just fine until few weeks ago. I didn't do any upgrade on my part, probably only Chrome was updated on the device.

Now, for most of the time the spinner is stuck like following:
![ionicspinnerbug](https://cloud.githubusercontent.com/assets/9930079/14528478/43bdf3a0-0258-11e6-90e8-39303194175b.png)

However, when screen is mirrored to chrome dev tools via remote inspect then it works there.</span>

Chrome version on device: 49.0.2623.105

<span is-issue-template></span>

**Comment by brandyscarney** [comment] 2016-04-14 16:45
I think this is related to https://github.com/driftyco/ionic/issues/5936. Are you using the `<spinner>` element or something else?

**Comment by ErkoKnoll** [comment] 2016-04-15 05:56
Yes, it is definitely related to the same problem. And yes, I'm only using <ion-spinner></ion-spinner>.

**Comment by dheeran1** [comment] 2016-04-18 05:09
+1, Same here

**Comment by bachvtuan** [comment] 2016-04-24 07:11
Hi. I'm using android 6.0 and get this issue too. Exactly is black circle 
Please fix. it look ridiculous. :)

**Comment by iignatov** [comment] 2016-05-09 20:57
It seems that the issue was caused by a bug in WebView  - see https://github.com/driftyco/ionic/issues/5936#issuecomment-216768996 - and it works fine after updating the **Android System WebView** to the latest version. //cc: @jgw96

**Comment by jgw96** [comment] 2016-05-09 21:07
Testing now on Android 6.0.1 and Android N dev preview 2. Will report findings here (:

**Comment by jgw96** [comment] 2016-05-09 21:12
Awesome, seems to be working for me now on the above mentioned versions of Android. I am going to go ahead and close this issue for now. If your still experiencing this issue then most likely you need to update your Android System WebView. You can check for updates for this component of Android on the Google Play Store on your device. Thanks everyone!

**Closed by jgw96** 2016-05-09 21:12 UTC
Labels: platform:android, v2
