### ISSUE TITLE
Slides v2 beta10 does not work on android

### ISSUE THREAD

**Issue by ValterSantosMatos** [driftyco/ionic#7192] opened 2016-07-04 10:10 UTC
#### Slides v2 beta10 does not work on android (unable to swipe)

Expect to see 3 swiper-pagination-bullets on the bottom and be able to swipe between the screens.
Worked in beta 9, works if emulate IOS device.

**Steps to reproduce:**
Just check the Plunker.

**Which Ionic Version?** 2.10

#### Plunker that shows an example of your issue
http://plnkr.co/edit/gW6ckkR5cZ4G8e3EbiRh?p=preview

**Comment by mangonecristian** [comment] 2016-07-05 03:17
Same here. It works after a window resize.

**Comment by schankam** [comment] 2016-07-06 08:04
Also got the bug on Android (working fine on iOS). Looks like it does not work when using ion-slides inside an ion-content...

**Comment by jgw96** [comment] 2016-07-06 14:26
Hello all, thanks for opening an issue with us! I will be closing this issue as a duplicate of https://github.com/driftyco/ionic/issues/7089. Thanks for using Ionic!

**Closed by jgw96** 2016-07-06 14:26 UTC
Labels: platform:android, platform:ios, slidebox, v2

**Comment by barocsi** [comment] 2016-07-19 08:28
It's even closed in #7089  wher it should not be. It also present in simple chrome browsers.
