### ISSUE TITLE
bug: anchorScroll throws exceptoin : Cannot read property 'attributes' of null

### ISSUE THREAD

**Issue by ptarjan** [driftyco/ionic#4155] opened 2015-07-27 22:33 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>On line 160: https://github.com/driftyco/ionic/blob/master/js/angular/controller/scrollController.js#L160 it reads the attributes property, but on the line before `curElm.offsetParent` returns `null` for me. `curElm` is being set correctly by the `doucment.getElementById` above, it just does't have an `offsetParent` attribute. And the DOM spec seems to not have it either (in current browser). Is there a missing `angular.element` somewhere here?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-07-27 22:33
Greetings @ptarjan!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4155). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4155)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment] 2015-07-29 16:42
Do you have an example of this not working?

**Comment by gerisztein** [comment] 2015-08-04 16:53
I'd experienced the same issue.

**Comment by mhartington** [comment] 2015-08-11 17:18
Do you have an example of this not working?

**Comment by ptarjan** [comment] 2015-08-11 20:49
Yes, I think it is because of this line on https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetParent

"This property will return null on Webkit if the element is hidden (the style.display of this element or any ancestor is "none") or if the style.position of the element itself is set to "fixed"."

So make an element that is display none or position fixed that you want to scroll to and test on Safari.

**Comment by mhartington** [comment] 2015-08-11 20:55
Again..
>Do you have an example of this not working?

**Comment by JoeyHoutenbos** [comment] 2015-08-18 12:51
Seems this only occurs in Chrome on desktop. I do not have this problem on mobile (using Crosswalk)..

**Comment by ptarjan** [comment] 2015-09-09 18:43
I've been consistently running into this on my Chrome Desktop as @JoeyHoutenbos mentioned.

Here is my stacktrace:

```
type          : angular
message       : Cannot read property 'attributes' of null
name          : TypeError
stack         : TypeError: Cannot read property 'attributes' of null
    at  /source/ionic-angular.js:7115:0
    at processQueue /source/angular.js:14567:0
    at  /source/angular.js:14583:0
    at completeOutstandingRequest /source/angular.js:5394:0
    at  /source/angular.js:5666:0
url           : #/profile/yscgPGKH15#manager
host          : localhost:8100
localtime     : 1441823345924
```

To reproduce just do this

```
$location.hash('something');
    // The $timeout is to stop the alert that angular throws "Cannot read property 'getScrollMax' of null"
    $timeout(function() {
      $ionicScrollDelegate.anchorScroll(true);
    }, 1);
```

**Comment by ptarjan** [comment] 2015-09-09 18:49
I should note that I am getting on device (iOS in this case) as well but with a different message (probably due to minification)

    null is not an object (evaluating 'r.attributes')

**Comment by ptarjan** [comment] 2015-09-23 06:15
ping?

**Comment by mhartington** [comment] 2015-09-23 15:16
Again..
>Do you have an example of this not working?


Codepen, plunkr, jsbin.

**Comment by Ionitron** [comment] 2015-10-23 17:03
Greetings @ptarjan!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment] 2015-10-23 17:03
Greetings @ptarjan!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-10-23 17:03 UTC
Labels: ionitron:closed

**Comment by ElodieC** [comment] 2015-11-02 13:26
I had the same issue. This was due to the ion-view being cached multiple times because I used `$stateParams` to scroll to right anchor. 

The workaround is to use a service to save the anchor to scroll to instead of a `$stateParams`.

**Comment by mechon** [comment] 2015-11-02 18:24
I'm also encountering this issue, made a sample at [codepen](http://codepen.io/mechon/pen/YyjpyY?editors=101). Error is usually thrown when the container's ng-show value is toggled.

**Comment by tiagoMaua** [comment] 2015-12-21 21:13
Hi!!

  I had the same problem, and found that it was caused by $ location.hash (idElement);

  The function $ location.hash () creates a map id's, even the id's being different pages, it is important that they are unique throughout the project.

  I recommend the following use:

In HTML:

<div id="nameView-{{variableId}}>  POINT </div>

And in controller function:

this.scrollTo = function (targetPoint){

    $location.hash( 'nameView-' + targetPoint);
    $ionicScrollDelegate.anchorScroll(true);    

}

This work to me!

**Comment by rgarcia4Crew** [comment] 2016-03-23 14:03
> The function $ location.hash () creates a map id's, even the id's being different pages, **it is important that they are unique throughout the project**.

That's it, that's the key. Thanks @tiagoMaua

**Comment by Taewa** [comment] 2016-04-01 09:30
The key was making a unique id. Its working for me. 
Thanks @ElodieC @tiagoMaua

**Comment by Freundschaft** [comment] 2016-08-24 11:32
the reason is that the id has to be unique and using cached views, this cannot be guaranteed, so the id would need to be removed if the caching kicks in, or am I mistaken?

**Comment by opensourceexpert** [comment] 2017-02-21 10:16
hi, 
after the navigation from scroll page to other, page, when i com back to the scroll and i try to scroll the items, its giving the 

TypeError: Cannot read property 'attributes' of null     
 please help me thank you.

**Comment by cgs** [comment] 2017-02-23 19:25
I had unique ids, but for me the issue was caching. Turned off the cache for the related page and it works:

`
    .state('app.glossary', {
      url: "/glossary?scroll",
      cache: false,
      views: {
        'menuContent': {
            controller: "GlossaryCtrl",
            templateUrl: "templates/glossary.html"
        }
      }
    })
`
