### ISSUE TITLE
DatePipe doesn't work on ios simulator and iPhone 6 plus

### ISSUE THREAD

**Issue by DenysYefimenko** [driftyco/ionic#5807] opened 2016-03-11 10:18 UTC
I have simple template with `{{ someVariableOfDateType | date:'medium' }}` or any other DatePipe format parameter. This works fine in chrome but in iOS simulator or on the device the date doesn't show up at all. If I remove filter then date is visible in simulator/device/browser. This also results in some strange behavior of `ion-list` if I choose to place specified code into `ion-item`.

Ionic Version: 2.x

**Comment by jgw96** [comment] 2016-03-11 17:52
Hello! Thanks for submitting an issue to us! We just need a little more info from you so that we can help your more effectively. Would you mind telling us what version of IOS your experiencing the issue on? Also if you could, can you run `ionic info` and paste the output here please?

**Comment by DenysYefimenko** [comment] 2016-03-11 18:12
```
Cordova CLI: 6.0.0
Ionic Version: 2.0.0-beta.2
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
ios-deploy version: 1.8.5 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v5.6.0
Xcode version: Xcode 7.3 Build version 7D111g 

iOS version: 9.2.1
```
I found in [https://github.com/angular/angular/blob/master/modules/angular2/src/common/pipes/date_pipe.ts] that
` * - this pipe uses the Internationalization API. Therefore it is only reliable in Chrome and Opera`
Is my guess correct that I have to fallback to using custom filter in my app? As when I use DatePipe not only it doesn't work but rest of the page is not getting rendered...

**Comment by alexbainbridge** [comment] 2016-03-11 19:23
Chances are this is the solution https://github.com/driftyco/ionic/issues/5710

**Comment by jgw96** [comment] 2016-03-11 19:37
@alexbainbridge agreed, good catch. I will be closing this issue as it is a dupe of #5710. Feel free to continue the discussion on this issue over there! Please feel free to reopen this issue if you feel it is not a duplicate of the other.

**Closed by jgw96** 2016-03-11 19:37 UTC
Labels: Angular Pipe, platform:ios, v2
