### ISSUE TITLE
How to import/require a npm module

### ISSUE THREAD

**Issue by glaucocustodio** [driftyco/ionic#8274] opened 2016-09-28 23:11 UTC
#### Short description of the problem:
I have an app running at `2.0.0-beta.11` version and now I am migrating to `2.0.0-rc.0`.

I am importing my installed modules like `PouchDB` (that was installed via `npm installl pouchdb`) through `let PouchDB = require('pouchdb');` however the same code does not work on the rc version, I just get `require is not defined` (I already have `typings` installed).

I know a lot of changes were made from a version to another (Angular 2.0 final, TypeScript 2) etc and I would like to know how I should proceed now.

I read that on TS 2 I should import using the new ES syntax like `import * as PouchDB from 'pouchdb'` but this way (and alternatives) I just get `Cannot find module 'pouchdb'`.

Thank you for the great work, you are amazing.

#### What behavior are you expecting?
Be able to import a npm module installed at `node_modules`.

**Steps to reproduce:**
1. Start a brand new ionic 2 rc app
2. Install any npm module
3. Try to import it 

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: Not installed
Gulp version:  CLI version 1.2.2
Gulp local:
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X Yosemite
Node Version: v5.2.0
Xcode version: Xcode 7.2 Build version 7C68

**Comment by calebkiage** [comment] 2016-09-29 01:14
I also wonder how to do this especially for pouchdb. I had to reference it manually into my index.html file and add the declaration `declare var PouchDB: any` on all the pages I used it on.  :-/
I noticed that this issue doesn't affect all node modules. For example lodash and momentjs work fine when you import them.

**Comment by ramonornela** [comment] 2016-09-29 02:43
See https://github.com/driftyco/ionic-third-party-lib-example

**Comment by danbucholtz** [comment] 2016-09-29 03:05
I am going to write a blog on this very subject shortly.

Here are a few key points:

1.  Make sure `allowSyntheticDefaultImports` is set to true in the `tsconfig.json` compilerOptions.

2.  Install the library (lodash is this example)
```
npm install lodash --save --save-exact
```

3.  Install type definitions
```
npm install @types/lodash --save-dev  --save-exact
```

4.  If a type definition is not found the library, we'll have to create a `declarations.d.ts` file in `/src`, so `${PROJECT_ROOT}/src/declarations.d.ts`

5.  Enter a shorthand module declaration in the `${PROJECT_ROOT}/src/declarations.d.ts` file

```
declare module 'lodash'
```

6.  In the page/component/directive/pipe, import the library like this:

```
import lodash from 'lodash'

ionViewDidEnter() {
   lodash.capitalize('hurray, the lib works!');
}
```

This pattern should work for the vast majority of libraries out there. If the library is newer and written in `es2015/Typescript`, often times you can import libraries like this:

```
import { someFunction } from 'someLib'
```

This method above is more desirable because excess code can be removed via `tree-shaking`.

Thanks,
Dan

**Comment by morious** [comment] 2016-09-29 03:06
AS far as I know ionic now uses npm@types instead of typings.
I migrated away from typings using npm@types and changed my import declarations, to this syntax:
import PouchDB from 'pouchdb'

**Comment by danbucholtz** [comment] 2016-09-29 03:50
@Morious said in a different thread:

```
I am trying to use an npm package that has no corresponding typings file, hence I cannot use an 'import' statement that later most likely participates in the bundling process.

I could not find a documentation to what is the recommended approach by ionic given the new build process in RC0.

The quickest thing I could think of would be to use a 'declare var' statement and an npm task to copy the js file to the www folder.

What approach would you recommend to this?
```

**Comment by danbucholtz** [comment] 2016-09-29 03:53
I would create a `declarations.d.ts` file in /src, so `${PROJECT_ROOT}/src/declarations.d.ts`.

I would create an `implicit any` type definition for the module by entering the following:

```
declare module 'myLibraryWithoutTypes'
```

I would then go to my page/component/whatever, and import the library like this:

```
import myLib from 'myLibraryWithoutTypes'

...

ionViewDidEnter() {
   myLib.someAwesomeFunction();
}
```

**Comment by morious** [comment] 2016-09-29 04:08
@danbucholtz ,
Thanks for the quick response. 
I tried your approach a few posts up and when it did not work I figured it would be worth a new thread. :)

this is the error i am getting:
 Error: Module ...\node_modules\rollup-plugin-node-resolve\src\empty.js does not export __moduleExports (imported by commonjs-proxy:...\node_modules\paper\dist\node\window.js)

It is not so clear but I think it is caused by an empty module declaration?
WDYT?

**Comment by danbucholtz** [comment] 2016-09-29 04:10
What does your `import` statement look like?

Do you have `allowSyntheticDefaultImports` set to true in your `tsconfig.json`'s `compilerOptions`?

Thanks,
Dan

**Comment by allangomessl** [comment] 2016-09-29 05:12
this error occurs to me

### Could not resolve 'pouchdb'

```
[02:08:39]  typescript compiler ready in 3.99 s
[02:08:39]  bundle dev started ...
[02:08:43]  Error: Could not resolve 'pouchdb' from /Users/allan/dev/lov/.tmp/app/utils/repository/LocalRepository.js
    at Error (native)
    at /Users/allan/dev/lov/node_modules/rollup-plugin-node-resolve/dist/rollup-plugin-node-resolve.cjs.js:78:21
    at /Users/allan/dev/lov/node_modules/browser-resolve/index.js:265:24
    at /Users/allan/dev/lov/node_modules/resolve/lib/async.js:46:14
    at process (/Users/allan/dev/lov/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/allan/dev/lov/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/allan/dev/lov/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/allan/dev/lov/node_modules/resolve/lib/async.js:92:31)
    at /Users/allan/dev/lov/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by manuelroth** [comment] 2016-09-29 09:22
I get exactly the same error as @allangomessl. 

1. `allowSyntheticDefaultImports ` is set to true
2. Installed pouchdb: `npm install pouchdb --save --save-exact`
3. Installed typings: `npm install @types/pouchdb --save-dev  --save-exact`
4. Imported like this in my provider: `import * as PouchDB from 'pouchdb';`

Would really appreciate any help on this.

**Comment by workfluo** [comment] 2016-09-29 10:08
Dan,
Please don't forget to mention to update Node and Npm.
Or there is a risk of error in case of "npm install @types/lodash --save-dev  --save-exact " because of write-rights.

(I lost a day on this)

**Comment by cambronjay** [comment] 2016-09-29 12:07
I found that rollup changes the way things are imported. 
What it used to be: import * as io from 'socket.io-client';
What it is now: import io from 'socket.io-client';
Now I did this after following the changelog instructions and updating everything. Be sure to uninstall the old ionic and then reinstall it. At the end of the day I found it better to just remake the app in a new project rather than try to upgrade it. Afterall, ionic was in beta and now is in rc!

**Comment by glaucocustodio** [comment] 2016-09-29 12:30
I've followed all your steps @danbucholtz and this way I just get:

`Error: Could not resolve 'pouchdb-node' from /Users/foo/myapp/node_modules/pouchdb/src/pouchdb.js`.

Have you tried to import `PouchDB` specifically?

It seems that many people are facing issues when importing modules. A blog post/tutorial would be nice given that it does not to seem to be that simple.

Thank you again.

**Comment by morious** [comment] 2016-09-29 12:44
@danbucholtz ,
I am trying to use paper-js.
So my import looks like that:
```
declare module 'paper'

...

import paper from 'paper'
```

Thx!

**Comment by nicopeeters** [comment] 2016-09-29 14:34
I'm also getting the same error as @manuelroth when importing PouchDB. I performed the same steps described. Help is much appreciated.

**Comment by danbucholtz** [comment] 2016-09-29 14:56
I am seeing the same thing with `pouch`. I am looking into it.  Nolan is a good friend of Ionic so we'll get it resolved.

Thanks,
Dan

**Comment by danbucholtz** [comment] 2016-09-29 17:48
I have submitted a PR to Pouch.

https://github.com/pouchdb/pouchdb/pull/5737/files

There is another issue further down in the pouch dependency stack (I think) that I am still working on.  I'll have an update soon.

Thanks,
Dan

**Comment by EliuFlorez** [comment] 2016-09-30 13:52
A small temporary solution to firebase: https://forum.ionicframework.com/t/ionic-2-rc-0-and-firebase-not-angularfire/65018/7

**Comment by danbucholtz** [comment] 2016-09-30 14:43
@EliuFlorez,

Nice! I don't love the fix because it's complicated, but it works until firebase and associated libs get updated. Thanks so much for looking into this!

Thanks,
Dan

**Comment by jgw96** [comment] 2016-09-30 17:28
Hello all! I am going to close this issue for now in favor of https://github.com/driftyco/ionic/issues/8356 since the creator of PouchDB is involved with that one. Thanks for using Ionic!

**Closed by jgw96** 2016-09-30 17:28 UTC

**Comment by alexbainbridge** [comment] 2016-10-01 20:02
@jgw96 Although the recent discussion was about Pouch (which is on the new issue) there is a general issue with rollup on external npm modules

Any place where that should be discussed? 

I have the same "could not resolve" issue in rollup - on a different library, so we probably need a non-library specific solution?

**Comment by danbucholtz** [comment] 2016-10-01 20:20
@alexbainbridge, what library are you having trouble with?

Thanks,
Dan

**Comment by alexbainbridge** [comment] 2016-10-01 20:42
@danbucholtz 

https://github.com/Kinvey/angular2-sdk

But pull from Github not NPM as they are fixing as we go and their latest changes are not in NPM as a release yet.

> [20:02:08]  Error: Could not resolve 'kinvey-angular2-sdk' from /Applications/MAMP/htdocs/ionic-conference-app/.tmp/pages/about/about.js
>     at Error (native)
>     at /Applications/MAMP/htdocs/ionic-conference-app/node_modules/rollup-plugin-node-resolve/dist/rollup-plugin-node-resolve.cjs.js:78:21
>     at /Applications/MAMP/htdocs/ionic-conference-app/node_modules/browser-resolve/index.js:265:24
>     at /Applications/MAMP/htdocs/ionic-conference-app/node_modules/resolve/lib/async.js:46:14
>     at process (/Applications/MAMP/htdocs/ionic-conference-app/node_modules/resolve/lib/async.js:173:43)
>     at ondir (/Applications/MAMP/htdocs/ionic-conference-app/node_modules/resolve/lib/async.js:188:17)
>     at load (/Applications/MAMP/htdocs/ionic-conference-app/node_modules/resolve/lib/async.js:69:43)
>     at onex (/Applications/MAMP/htdocs/ionic-conference-app/node_modules/resolve/lib/async.js:92:31)
>     at /Applications/MAMP/htdocs/ionic-conference-app/node_modules/resolve/lib/async.js:22:47
>     at FSReqWrap.oncomplete (fs.js:123:15)

Is what I am getting when I put that library in the conference app (which is working fine without this library)

i.e. pretty much the same "could not resolve" problem

Thanks!

**Comment by danbucholtz** [comment] 2016-10-02 02:36
@alexbainbridge,

Is there a type definition for the library? What does your import statement look like?

Typically, Rollup (our bundler) likes

`import { something } from 'someLib'`

- or -

`import someLibInstance from 'someLib'`

Thanks,
Dan

**Comment by iRoachie** [comment] 2016-10-02 02:38
Hey @danbucholtz I know you guys closed the pouchdb section. But is there any workaround currently to use pouchdb?

**Comment by danbucholtz** [comment] 2016-10-02 02:54
Yes.  @jgw96, can you share when you get a chance?

Thanks,
Dan

**Comment by alexbainbridge** [comment] 2016-10-03 14:51
@danbucholtz 

Currently trying as 
import Kinvey from 'kinvey-angular2-sdk';

I have created a fork of the Ionic conference app with my adjustments, and documented here in the forum so as not to distract this Github issue with the discussion
https://forum.ionicframework.com/t/kinvey-backend-rc0-typings-or-rollup-issue-help/65573

It could equally be a typings issue or a rollup issue. Certainly an issue :)

Thanks for any input - been stuck on this for a month now - bit depressing really!

**Comment by danbucholtz** [comment] 2016-10-05 19:40
All,

We've posted some docs on the subject. Note: They match a version of `@ionic/app-scripts` that will be dropped in the next day or so. 95% of the concepts still apply.

http://ionicframework.com/docs/v2/resources/third-party-libs/
http://ionicframework.com/docs/v2/resources/app-scripts/

[Here's](https://github.com/danbucholtz/ionic-rollup-angularfire2) an example with AngularFire2.
[Here](https://github.com/danbucholtz/ionic-third-party-lib-mega-test/blob/master/package.json) is a project I implemented that has every library in it that Ionic users have reported trouble with. Most of the libraries worked, but a couple did not. [Here](https://docs.google.com/spreadsheets/d/124VhzYm5gHrBowWAUolfOsVBNTcxTELWauAjKKWAUBQ/edit?usp=sharing) is the summary of the findings.

Please let me know how everything goes.

Thanks,
Dan

**Comment by manuelroth** [comment] 2016-10-06 08:00
Awesome, thanks for fixing this pouchdb works now again.

**Comment by iRoachie** [comment] 2016-10-08 03:28
@danbucholtz I followed the steps above, but didn't work for pouch. Cloning your repo gave the error:

`
Error running ionic app script "watch": Error:
Dev builds no longer use the ".tmp" directory. Please update your rollup config's
entry to use your "src" directory's "main.dev.ts" TypeScript file.
For example, the entry for dev builds should be: "src/app/main.dev.ts"
`

**Comment by danbucholtz** [comment] 2016-10-09 03:03
@iRoachie,

I updated my repo to the latest in the past day or so. We changed the `rollup.config.js` file slightly, and removed a plugin.  Go ahead and pull.  Or just look [here](https://github.com/danbucholtz/ionic-third-party-lib-mega-test/blob/master/scripts/rollup.config.js). 

Thanks,
Dan

**Comment by iRoachie** [comment] 2016-10-09 05:29
@danbucholtz Error running ionic app script "watch": Error:
Dev builds no longer use the ".tmp" directory. Please update your rollup config's
entry to use your "src" directory's "main.dev.ts" TypeScript file.

**Comment by danbucholtz** [comment] 2016-10-09 18:19
@iRoachie, go ahead and try again. I had to update it to point to a `.ts` file instead of a `.js` file.

Thanks,
Dan

**Comment by iRoachie** [comment] 2016-10-09 19:27
@danbucholtz Works great now! Thanks!, appreciate the work put in. 
A link to your repo could probably be put in the documentation on the main website. http://ionicframework.com/docs/v2/resources/third-party-libs/
