### ISSUE TITLE
feat: Possibility to swipe between tabs

### ISSUE THREAD

**Issue by lordgreg** [driftyco/ionic#5322] opened 2016-02-03 18:59 UTC
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I know that the current state of TabPage is stalling because of ng2 routing and what not. However, when this is going to be done, it would be really nice to have an option to Swipe between content of Tabs just like it is in most/all native apps with Tabs.

Thank you for your feedback. :)</span>

<span is-issue-template></span>

**Comment by brandyscarney** [comment] 2016-02-03 19:17
Thanks but this is a duplicate of https://github.com/driftyco/ionic/issues/5101

**Closed by brandyscarney** 2016-02-03 19:17 UTC
Labels: feature, v2
