### ISSUE TITLE
bug: After resolve in state back button / bad history

### ISSUE THREAD

**Issue by chrisschaub** [driftyco/ionic#3699] opened 2015-05-11 13:27 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When I use resolve in a $state with ui-router, the promise returns and the controller is fired if resolve or not if reject. Great. But, the history / back button seems to be corrupted. It shows the back button on the "resolve" route when it should not.

To reproduce:
1. Create a sidemenu project.
2. Create a $state router with two paths, one needs a resolve. Both are in the left sidemenu.
3. In your resolving factory service, implement a promise with resolve/reject. 
4. When you click the resolve menu link , when it resolves successfully, it will take you to the page, but with a back button which is incorrect.

My resolve in the $state config looks like
...
      resolve: {
        'hasData': ['hasDataService', '$ionicHistory', function resolveControllerHasData(hasDataService, $ionicHistory) {
          return hasDataService.appHasData();
        }]
      }
....

Thanks for any help.</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment] 2015-05-11 15:56
Hey @chrisschaub, your description is pretty straight forward, but could you provide an codepen example so we're looking at the same thing?

**Comment by chrisschaub** [comment] 2015-05-11 16:22
I'll try, but this bug is killing me and I'm slamming on a deadline. Thanks for the reply!

**Comment by perrygovier** [comment] 2015-05-13 15:16
Why no, thank you :)

**Comment by pavax** [comment] 2015-06-01 07:02
Hy @perrygovier,  I'm also struggling around with that bug. Here is a Plunker based on the ionic-starter-side-menu that shows the described behaviour in different ionic versions:

**ionic 1.0.0 BETA 1 (works) **
http://plnkr.co/edit/y6lE2Af6PoGxmuGb4kTu?p=preview

**ionic 1.0.0  (works not) **
http://plnkr.co/edit/orJT13V5txYSH144vtND?p=preview

How to reproduce:

1. Go to the 'Playlist' or 'Search' Menu Content
2. Click on Browse (this is the state that has a resolve that takes more than 1 sec)
3. An alert should show up and the browse-state is now loaded
 => The Back button is now shown all of a sudden


If you reduce the $timeout value in the resolve to 0 (or anything under ~ 300ms) everything works.... Unfortunately my server can not respond that fast all the time :)

**Comment by pavax** [comment] 2015-06-05 22:04
The last working version seems to be 1.0.0-beta.13.

1.0.0-beta.13 (working):
http://plnkr.co/edit/70q913JX3AhTC8vuGymj?p=preview

1.0.0-beta.14 (not-working):
http://plnkr.co/edit/G60ahN9wGbLXbQGIApWr?p=preview

**Comment by Ionitron** [comment] 2015-06-12 16:38
Greetings @chrisschaub!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-06-12 16:38 UTC
Labels: ionitron:closed

**Comment by talamaska** [comment] 2015-08-29 20:31
you bot should not close unresolved issues, this is quite annoying issue and is appearing after the official release like it was noted. Please take care of fixing it, instead of closing it automatically after certain time, just because "a reply was requested, but we have not received one yet"
and actually there was.
