### ISSUE TITLE
Virtual Scroll: Can't remove or hide an item in virtual scroll without reset virtual scroll

### ISSUE THREAD

**Issue by jeromeXoo** [driftyco/ionic#7024] opened 2016-06-23 12:25 UTC
#### Short description of the problem:

It is not possible to remove or hide a virtual scroll item without refreshing virtual scroll and losing scroll position.

I tried the following solutions:
- splice on datasource => reset the virtual scroll, lost scroll position, but item disappears (no blank space)
- hiding item, [hidden]='true' => the next item does not go up in the list (so there is a blank space)
- display:none; => the next item does not go up in the list (so there is a blank space)
#### What behavior are you expecting?

To be able to remove or hide an item in the virtual scroll:
- Maintain the position of the scroll (thus without refreshing the virtual scroll?)
- Visually: The space of the object must be removed.

The goal is to remove / hide an item in the list, without losing the position in the scroll.

Ionic V2 beta 9

Plunker (the virtual scroll has display problem in the plunker):
http://plnkr.co/edit/drNjfw?p=preview
**2016/06/29 (update)**: plunker updated with beta 10

Cordova CLI: 6.2.0
Gulp version:  CLI version 1.2.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS:
Node Version: v4.4.5

**Comment by jeromeXoo** [comment] 2016-06-23 14:33
I guess the "translate3d" on the list item are the source of the problem (eg: transform: translate3d(0px, 230px, 0px);).

Is the solution would be to recalculate the translate3d for each items in the viewport?

**Comment by jeromeXoo** [comment] 2016-06-24 16:04
Perhaps, a property "hide" on the virtual item to hide it, and recalculate the position of following items in the list (I know it's not easy)

**Comment by jeromeXoo** [comment] 2016-06-28 17:31
Is there any chance that it will be included in a future release?
If it is not possible, I will have to use an alternative to the virtual scroll.
Thanks for letting me know.

**Comment by DomiR** [comment] 2016-09-08 21:59
Related to https://github.com/driftyco/ionic/issues/6423

**Comment by jgw96** [comment] 2016-12-28 16:30
Hello everyone! Thanks for using Ionic! We have been hard at work lately with virtualscroll. The issue here is that when you update the virtualscroll with data after it has already been rendered the measurements that virtual scroll uses to lazily render elements then become wrong. When this happens the virtual scroll has to re-render itself entirely, therefore making it look like it has jumped back to the beginning of the list. We are well aware of this issue and hope to have a solution for it soon. Also, just to keep our issues concise and not have duplicates  I am going to close this one as a duplicate of https://github.com/driftyco/ionic/issues/6423 . You can track the status of this issue over on that issue. Also, feel free to put any findings you may have on that issue. Thanks again everyone!

**Closed by jgw96** 2016-12-28 16:30 UTC
Labels: v2, virtualscroll
