### ISSUE TITLE
ion-content scrollbar issue on Android

### ISSUE THREAD

**Issue by sinedied** [driftyco/ionic#4928] opened 2016-01-08 14:06 UTC
I just have setup a basic side menu app from the template, and have a strange issue only on Android: there is content overflow which cause a scrollbar and obviously enable scrolling, where it should not.

Here is a screen from `ionic serve --lab` (the issue is replicated on real device):

![image](https://cloud.githubusercontent.com/assets/593151/12199524/fb26729c-b618-11e5-9f4f-86e700929328.png)

When I look at the HTML, it see an extra `<div class="scroll">...</div>` under the `<ion-content>` directive, that is not there on the iOS version. It seems the issue lies with this extra `div`, as it is offset of about 10px from the top of the ion-content box and the overflowing content that cause the scroll is the same size.

The issue is present in version `1.2.4`.

**Comment by mlynch** [comment] 2016-01-08 19:18
Yea the native scroll view area is more sensitive to overflows and such. And you must have a mouse connected so you're seeing it. Will be fixed in a later release with flexbox sizing.

**Comment by MT--** [comment] 2016-02-15 17:14
What kind of workaround has been found? I will post one soon unless someone has already dealt with this in Ionic 1 (1.7).

**Comment by jclalala** [comment] 2016-02-18 05:19
Setting the following works for me. Which is the same as a global overflow-scroll="false":
$ionicConfigProvider.scrolling.jsScrolling(true);

**Comment by sinedied** [comment] 2016-02-18 07:35
This is not really a workaround, as it completely disable scrolling, which is not desired in my case.

**Comment by shashankdevp** [comment] 2016-02-26 07:41
Actually have the same issue where scrollbar is shown, even if there is no data to scroll. I am using Ionic, v1.2.4 for my application. I am running it on the real device.

Is there any solution for this as it looks bad on the mobile phone.

**Comment by DeeM297** [comment] 2016-03-25 00:52
Hello,

I am having the same issue. Just installed from sidemenu template and I am getting this scroll bar on the Android side. 

Are there any workarounds?

Is it coming from the template? How to solve this?

Thanks,

**Comment by DeeM297** [comment] 2016-04-02 17:51
My scroll bar disappeared!!

So the solution I have found is to rename my "index.html" to "main.html" and create a new index.html with the following code.

`<!doctype html>
<html>
  <head>
   <title>the title</title>
   <script>
     window.location='./main.html';
   </script>
  <body>
  </body>
</html>`

**Comment by cesar-oyarzun-m** [comment] 2016-04-13 20:55
Hi the solution fro this is 

    /* FIX scroll issue */
    .overflow-scroll {
      overflow-y: auto;
    }

**Comment by jgw96** [comment] 2016-04-13 21:15
Hello all! I am unfortunately having an issue reproducing this issue. Can somebody make a codepen or plunkr that reproduces this issue? Thanks! Also, heres what my test looks like:
![screen shot 2016-04-13 at 4 13 59 pm](https://cloud.githubusercontent.com/assets/8823093/14509623/e5284388-0192-11e6-8eb4-f547c8967993.png)

**Comment by sinedied** [comment] 2016-04-14 06:30
Is the content view on the right scrollable? As it should not.
What's your browser?

If you use Safari, it does not show scrollbars, so the issue with not be visible at a glance like this, but with Chrome your should reproduce the same behavior I posted.

**Comment by jgw96** [comment] 2016-04-14 14:25
Hey @sinedied ! Thanks for getting back to me. So no, neither of the views are scrollable and I'm using the latest chrome canary. Your using chrome too I'm guessing?

**Comment by sinedied** [comment] 2016-04-14 14:57
Yes, the original screen shot was made on chrome. 
I will put a codepen for you in a few days (I'm taking some days off ;) )

**Comment by jgw96** [comment] 2016-04-14 14:59
No problem and thanks! I would love to be able to solve the issue, but it's kinda hard to when I can't reproduce it haha (: so a codepen demonstrating the issue would be great.

**Comment by jgw96** [comment] 2016-04-14 15:00
Oh and also, I tried on my Android devices (Nexus 6, Nexus 7 and a moto x 2014) and could not reproduce there either

**Comment by cesar-oyarzun-m** [comment] 2016-04-14 15:03
@jgw96 what version of ionic you're testing, also did you check the DOM if you have the '<div class='sroll'>'

**Comment by brnewby602** [comment] 2016-04-14 16:02
I'm new to ionic and am running into the same issue.  When running ionic serve -l, ios looks fine but android has the scroll bar greyed out on the content area.   If it helps at all, it seems if I remove the overflow-scroll class using chrome dev tools, it appears that it resolves the issue, but I don't know if there are unintended consequences by doing so?

<ion-content class="has-header has-tabs pane scroll-content ionic-scroll **overflow-scroll**" data-tap-disabled="true" nav-view="active" style="transform: translate3d(0%, 0px, 0px);">
   <div class="scroll">
      <ui-gmap-google-map ......>
   </div>
</ion-content>

I can try and create a codepen if that would be of more use.

**Comment by jgw96** [comment] 2016-04-14 16:13
@cesar-oyarzun-m I am using ionic 1.2.4 and i do see the `<div class="scroll">` in my dom. I still cannot seem to reproduce the issue though. Im using chrome canary which is chrome version 52 and is two version ahead of chrome stable. 
![screen shot 2016-04-14 at 11 12 01 am](https://cloud.githubusercontent.com/assets/8823093/14535110/efe320a0-0231-11e6-942d-3c5192f57542.png)

**Comment by jgw96** [comment] 2016-04-14 16:15
@brnewby602 It would be awesome if you could create a plunker or a codepen! Here is a plunker you can use as a template: http://plnkr.co/edit/jnOrQRtE8rN2WCXDQYQY?p=info

**Comment by cesar-oyarzun-m** [comment] 2016-04-14 16:15
@jgw96 I think you need to try on real device I think maybe they have different chrome renders.

**Comment by jgw96** [comment] 2016-04-14 16:20
@cesar-oyarzun-m I have tried on three different Android devices (Nexus 6 running the Androd N dev preview, Nexus 7 2013 running Android 6.0.1 and a Moto X 2014 running Android 5.1) and unfortunately could not reproduce the issue on any of my devices. Could you make a plunker that shows the issue that i can use to reproduce the issue?

**Comment by brnewby602** [comment] 2016-04-14 17:31
@jgw96 Trying to get a plunkr that actually renders a live preview.  If I get it working I'll add the link

**Comment by jgw96** [comment] 2016-04-14 18:59
@brnewby602 here is a template i made you can use to make your plunker: http://plnkr.co/edit/jnOrQRtE8rN2WCXDQYQY?p=info

**Comment by jgw96** [comment] 2016-04-19 07:48
Hello! Gonna go ahead and close this issue for now, as i cant seem to reproduce it, but if you get together a plunkr that reproduces that ill happily reopen. Thanks again!

**Comment by sinedied** [comment] 2016-04-19 09:53
I can still reproduce it using my starter kit: https://github.com/angular-starter-kit/starter-kit/tree/mobile

I'll try to reproduce it in your plunker

**Comment by GitGump** [comment] 2016-05-12 06:52
@jgw96 hi there, try it on Android 5.0 or older version like 4.4, you can see the issue.

**Comment by jgw96** [comment] 2016-05-12 15:01
Hello @GitGump ! Ive tried it on Android 5.1, 6.0.1 and the Android N Dev preview and couldn't seem to reproduce it. Can you still reproduce this issue? Even with 1.3.0?

**Comment by GitGump** [comment] 2016-05-13 09:09
@jgw96 Yeah! And it seems that the issue can reproduce only on older Android versions(4.4.2 or older), I updated ionic to 1.2.4 recently and got this problem.

**Comment by neslinesli93** [comment] 2016-05-18 09:13
I use android kitkat and I can reproduce the issue

**Comment by tinderangler** [comment] 2016-05-19 18:49
Same for me, it started with Ionic 1.2.x

**Comment by wheelertom** [comment] 2016-05-24 20:15
I'm also seeing this issue with the v2 beta.  Just started happening.

**Comment by jgw96** [comment] 2016-05-24 20:57
@wheelertom What version of Android are you seeing this on?

**Comment by wheelertom** [comment] 2016-05-26 23:11
@jgw96 -- I haven't been able to get my Android emulator working.  I'm only seeing this in the browser view.  In the iOS emulator it's not a problem.

**Comment by jgw96** [comment] 2016-05-27 06:21
@wheelertom I am currently testing on a Nexus 7 running Android 6.0.1, a Moto X 2014 running Android 5.1.1 and a Nexus 6 running the Android N beta.3 dev preview and i cant seem to reproduce this issue with any of my Ionic 2 beta.7 apps. Could you post a plunker that i could use to reproduce this issue? Thanks for using Ionic!

**Comment by sinedied** [comment] 2016-05-29 08:51
Are you planning to look into a fix for the v1, or will this be only fixed in v2?

**Comment by tinderangler** [comment] 2016-05-30 07:31
@jgw96 This issue only affects Android < 5 as far as I can say from my tests. On modern devices (which you test on) you'll not see it.

**Comment by reekhof** [comment] 2016-06-08 13:02
I experience the same issue. It happens on Android 4.4.2 (devices tested: samsung galaxy s4, samsung tab 3) and on android 5.0 (devices tested: lenovo tablet).

**Comment by pas** [comment] 2016-06-24 11:05
I can reproduce this with the genymotion emulator with Android 4.4.4 and 5.0. Will you fix it on Ionic 1?

**Comment by bob1457** [comment] 2016-07-02 07:39
I am using ionic 1.7.15, unfortunately I am experiencing the same issue and any of the above workaround seems not working at all. I am using browser with Chrome Version 51.0.2704.103 m (64-bit), and I am also using Visual Studio 2015 and Ripple emulator. Any progress to resolve the issue?

**Comment by nobesio** [comment] 2016-07-07 15:12
It's happening to me as well. Here is my ionic info:
`Your system information:
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 1.7.16
Ionic App Lib Version: 0.7.3
ios-deploy version: 1.8.6 
ios-sim version: 3.0.0 
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.3.1 Build version 7D1014 
`

Here is a screenshot of the issue:
![screen shot 2016-07-07 at 12 04 46 pm](https://cloud.githubusercontent.com/assets/9274069/16658074/55ee6724-443b-11e6-90d9-176ff2366670.png)

I can not scroll using by pressing and dragging an element in the list. I can only scroll by using the mouse wheel or by using the scroll bar. In iOS everything seems to work fine. This is only happening in android.

**Comment by woraphol-j** [comment] 2016-07-09 09:47
This issue is quite obvious and has been around for quite some time now.  I run my app on Android 4.4.2 and face the scrollbar issue whether it is ionic 1 or 2. Note that on Android 5> or iOS, this does not happen. Nonetheless, android 4.4 still make up a majority of user base (30% up I think) so please take a look at this issue.

**Comment by lightbeard** [comment] 2016-07-20 22:13
+1

The latest Visual Studio templates show this both with the emulator and a real android device.

  Microsoft Visual Studio Community 2015
  Version 14.0.25422.01 Update 3
  Ionic Pack   1.0.20

**Comment by loursbourg** [comment] 2016-07-30 18:30
For those who are still facing this issue, open cmd and run this:
```
ionic platform remove android
ionic platform add android
```

**Comment by nutellacrack** [comment] 2016-10-18 20:55
+1

Same for me (Android 4.4.2)

**Comment by mflmartin** [comment] 2016-11-05 00:08
👍  +1
Still Happening in android 4.4.2.

Annoying  :(

**Comment by rafaelcamargo** [comment] 2016-12-03 13:33
+1
Using Android 4.4.4 and also facing this issue.

**Comment by zarkiel** [comment] 2016-12-10 02:09
+1 Still Happening :(

**Comment by ceciliassis** [comment] 2016-12-12 23:10
Still Happening. For every view.

**Closed** 2017-01-17 15:13 UTC
Labels: scroll, v1

**Comment by balicekt** [comment] 2017-05-06 18:11
+1 Still Happening
