### ISSUE TITLE
bug: Tapping a card in native scroll in iOS selects another

### ISSUE THREAD

**Issue by alejandromagnorsky** [driftyco/ionic#4862] opened 2015-12-24 01:02 UTC
Type: bug

Platform: ios 8+ webview

version: 1.2.1

I have a list of cards with images and texts and when the user taps the card it opens the details of it. 
If the user taps while the view is still moving due to the scroll action performed, then it opens the previous card instead of the one tapped.
Note that switching to jsScrolling fixes this, so it only happens on iOS and native scroll.

**Comment by Ionitron** [comment] 2015-12-24 01:02
Greetings @alejandromagnorsky!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4862). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4862)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment] 2015-12-24 03:36
Okay, can confirm and will get this fix out as quickly as possible in 1.2.2

**Comment by mlynch** [comment] 2015-12-24 04:59
You know, actually, I can't reproduce this. What I was seeing was just a delay in the scroll render and tap but in practice it behaves normally on the device.

Do you have any sample code I could test? Thanks.

**Comment by andreialecu** [comment] 2015-12-26 01:03
Am actually seeing something similar sometimes with phantom clicks happening on elements that should be out of view. Hard to reproduce but it tends to happen when moving through ion-lists with links on them only when scrolling, without an intention to click.

**Comment by jgw96** [comment] 2016-03-14 18:55
Hello! Thanks for opening an issue with us, we just need a little more info from you so that we can better help you with your issue. Would you mind posting a code sample, plunkr or codepen that we can use to reproduce your issue? Also, would you mind running `ionic info` and posting the output? Thanks again!

**Comment by alejandromagnorsky** [comment] 2016-03-14 22:36
It's fixed already in version 1.2.4. Thanks!

**Comment by jgw96** [comment] 2016-03-15 21:36
No problem!

**Closed by jgw96** 2016-03-15 21:36 UTC
