### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by tomasbedrich** [driftyco/ionic#8271] opened 2016-09-28 22:26 UTC
#### Short description of the problem:
Cannot build a fresh app. There are multiple errors in the build process (see bellow).

**Steps to reproduce:**
1. `ionic start --v2 myProject`
2. `cd myProject`
3. `ionic serve`

**Build log:**
```
...
[00:20:13]  src/app/app.component.ts(1,27): error TS2307: Cannot find module '@angular/core'.
[00:20:13]  src/app/app.module.ts(1,26): error TS2307: Cannot find module '@angular/core'.
[00:20:13]  src/app/main.dev.ts(1,40): error TS2307: Cannot find module '@angular/platform-browser-dynamic'.
[00:20:13]  src/pages/about/about.ts(1,27): error TS2307: Cannot find module '@angular/core'.
[00:20:13]  src/pages/contact/contact.ts(1,27): error TS2307: Cannot find module '@angular/core'.
[00:20:13]  src/pages/home/home.ts(1,27): error TS2307: Cannot find module '@angular/core'.
[00:20:13]  src/pages/tabs/tabs.ts(1,27): error TS2307: Cannot find module '@angular/core'.
[00:20:13]  typescript compiler ready in 4.38 s
[00:20:13]  bundle dev started ...
[00:20:13]  Error: Could not resolve '@angular/platform-browser-dynamic' from /Users/ricoo/ownCloud/work/fxe/myProject/.tmp/app/main.dev.js
    at Error (native)
    at /Users/ricoo/ownCloud/work/fxe/myProject/node_modules/@ionic/app-scripts/node_modules/rollup-plugin-node-resolve/dist/rollup-plugin-node-resolve.cjs.js:78:21
    at /Users/ricoo/ownCloud/work/fxe/myProject/node_modules/@ionic/app-scripts/node_modules/rollup-plugin-node-resolve/node_modules/browser-resolve/index.js:265:24
    at /Users/ricoo/ownCloud/work/fxe/myProject/node_modules/@ionic/app-scripts/node_modules/rollup-plugin-node-resolve/node_modules/resolve/lib/async.js:46:14
    at process (/Users/ricoo/ownCloud/work/fxe/myProject/node_modules/@ionic/app-scripts/node_modules/rollup-plugin-node-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/ricoo/ownCloud/work/fxe/myProject/node_modules/@ionic/app-scripts/node_modules/rollup-plugin-node-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/ricoo/ownCloud/work/fxe/myProject/node_modules/@ionic/app-scripts/node_modules/rollup-plugin-node-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/ricoo/ownCloud/work/fxe/myProject/node_modules/@ionic/app-scripts/node_modules/rollup-plugin-node-resolve/node_modules/resolve/lib/async.js:92:31)
    at /Users/ricoo/ownCloud/work/fxe/myProject/node_modules/@ionic/app-scripts/node_modules/rollup-plugin-node-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)

[00:20:13]  sass started ...
[00:20:13]  sass failed:  Cannot generate Sass files without first bundling JavaScript files in order to know all used modules. Please build JS files first.

[00:20:13]  build dev failed:  Build failed
...
``` 

**Which Ionic Version?** 2.0.0-rc.0

**Run `ionic info` from terminal/cmd prompt:**

```
Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.8.5 
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v4.4.7
Xcode version: Xcode 8.0 Build version 8A218a 
```

**Comment by brandyscarney** [comment] 2016-09-28 23:14
Please update npm to `npm 3.x`. You can follow the instructions here: https://docs.npmjs.com/getting-started/installing-node#updating-npm

Let me know if that fixes it for you!

**Comment by tomasbedrich** [comment] 2016-09-28 23:56
This indeed fixed the problem. Thank you!

I will close the issue, but maybe it is worth mentioning it somewhere in a CHANGELOG, because `beta.11` worked with the `npm 2.x`.

**Comment by brandyscarney** [comment] 2016-09-29 00:02
Thanks! We added it earlier but let me know if you think there is a better place for us to put it: https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#steps-to-upgrade-to-rc0

**Comment by tomasbedrich** [comment] 2016-09-29 00:18
You are the best. 😉

**Comment by arkeds** [comment] 2016-09-29 10:42
I have a the same build error.

Your system information:

```
Cordova CLI: 6.3.0
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0-beta.3
Ionic App Lib Version: 2.1.0-beta.1
OS: Distributor ID:	LinuxMint Description:	Linux Mint 17.3 Rosa 
Node Version: v6.7.0

npm version: 3.10.8

```
Here is my node_modules files:
`@ionic  ionic-angular  ionic-native  ionicons  typescript`

The '@angular/core' files are located in node_modules/ionic-angular/node_modules/@angular.
So I tried moving it to the main node_modules directory, the errors were gone but page is blank

**Comment by Aristona** [comment] 2016-09-29 10:51
@brandyscarney I'm having the same issue although I updated everything.

```
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.0.0-beta.20
OS: Windows 8.1
Node Version: v6.7.0
```

It is also same on my Vagrant box.

This is the error I am getting:

```
Running 'serve:before' npm script before serve
> cutepuppypics@ watch C:\www\games\minequiz-new
> ionic-app-scripts watch
[13:50:32]  ionic-app-scripts 0.0.23
[13:50:32]  watch started ...
[13:50:32]  build dev started ...
[13:50:32]  clean started ...
[13:50:32]  clean finished in 11 ms
[13:50:32]  copy started ...
[13:50:32]  typescript compiler started ...
[13:50:33]  lint started ...
[13:50:33]

(node:4440) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): false

[13:50:33]  copy finished in 75 ms
[13:50:36]  src/app/app.component.ts(1,27): error TS2307: Cannot find module '@angular/core'.
[13:50:36]  src/app/app.module.ts(1,26): error TS2307: Cannot find module '@angular/core'.
[13:50:36]  src/app/main.dev.ts(1,40): error TS2307: Cannot find module '@angular/platform-browser-dynamic'.
[13:50:36]  src/pages/about/about.ts(1,27): error TS2307: Cannot find module '@angular/core'.
src/pages/contact/contact.ts(1,27): error TS2307: Cannot find module '@angular/core'.
[13:50:36]  src/pages/home/home.ts(1,27): error TS2307: Cannot find module '@angular/core'.
[13:50:36]  src/pages/tabs/tabs.ts(1,27): error TS2307: Cannot find module '@angular/core'.
[13:50:36]  typescript compiler ready in 3.44 s
[13:50:36]  bundle dev started ...
[13:50:36]  Error: Could not resolve '@angular/platform-browser-dynamic' from C:\www\games\minequiz-new\.tmp\app\main.dev.js
    at Error (native)
    at C:\www\games\minequiz-new\node_modules\@ionic\app-scripts\node_modules\rollup-plugin-node-resolve\dist\rollup-plugin-node-resolve.cjs.js:78:21
    at C:\www\games\minequiz-new\node_modules\@ionic\app-scripts\node_modules\rollup-plugin-node-resolve\node_modules\browser-resolve\index.js:265:24
    at C:\www\games\minequiz-new\node_modules\@ionic\app-scripts\node_modules\rollup-plugin-node-resolve\node_modules\resolve\lib\async.js:46:14
    at process (C:\www\games\minequiz-new\node_modules\@ionic\app-scripts\node_modules\rollup-plugin-node-resolve\node_modules\resolve\lib\async.js:173:43)
    at ondir (C:\www\games\minequiz-new\node_modules\@ionic\app-scripts\node_modules\rollup-plugin-node-resolve\node_modules\resolve\lib\async.js:188:17)
    at load (C:\www\games\minequiz-new\node_modules\@ionic\app-scripts\node_modules\rollup-plugin-node-resolve\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\www\games\minequiz-new\node_modules\@ionic\app-scripts\node_modules\rollup-plugin-node-resolve\node_modules\resolve\lib\async.js:92:31)
    at C:\www\games\minequiz-new\node_modules\@ionic\app-scripts\node_modules\rollup-plugin-node-resolve\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)

[13:50:36]  sass started ...
[13:50:36]  sass failed:  Cannot generate Sass files without first bundling JavaScript files in order to know all used modules. Please build JS files first.

[13:50:36]  build dev failed:  Build failed
[13:50:36]

[13:50:36]  watch ready in 3.69 s
Running live reload server: http://192.168.2.37:35729
Watching: www/**/*, !www/lib/**/*
√ Running dev server:  http://192.168.2.37:8100
Ionic server commands, enter:
  restart or r to restart the client app from the root
  goto or g and a url to have the app navigate to the given url
  consolelogs or c to enable/disable console log output
  serverlogs or s to enable/disable server log output
  quit or q to shutdown the server and exit
```

Any ideas?

**Comment by brandyscarney** [comment] 2016-09-29 12:07
@Aristona can you run `npm -v` so I can see the exact version?

**Comment by JoshWilliams92** [comment] 2016-09-29 13:28
I was having the exact same issue and updated npm version with "npm install npm -g"

**Comment by agustin107** [comment] 2016-09-29 17:39
I have the same problem, and I've fix that removing `node_modules` folder, uninstalling ionic global module and re-install again, and update `npm`.

Regards.

**Comment by abrahamstalin** [comment] 2016-09-30 00:51
I have the same problem, any ideas?

ionic v 2.1.0
npm v 3.10.8
node v 4.4.7

**Comment by Aristona** [comment] 2016-09-30 05:53
@brandyscarney 3.10.8

**Comment by svennerberg** [comment] 2016-09-30 08:33
I have the same problem. Tried the things @agustin107 suggested, but no joy.

ionic v2.1.0
npm v3.10.8
node v5.7.1

**Comment by davgc** [comment] 2016-09-30 09:15
Same as svennerberg, no luck after update npm to 3.x on older 2.0RC projects but if you re-start a new fresh project it works like a charm! thanx!

**Comment by loicknuchel** [comment] 2016-09-30 12:22
Hi, I've got the same problem and soled it upgrading npm to v3.
Maybe the getting started http://ionicframework.com/docs/v2/getting-started/installation/ could have the minimum version requirements (npm, node, cordova...)

**Comment by e-oz** [comment] 2016-09-30 13:40
```
Your system information:

Cordova CLI: 6.3.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: Not installed
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.3.0
Xcode version: Xcode 8.0 Build version 8A218a 
```
and error:

```
> ionic-app-scripts watch
[16:29:15]  ionic-app-scripts 0.0.23
[16:29:15]  watch started ...
[16:29:15]  build dev started ...
[16:29:15]  clean started ...
[16:29:15]  clean finished in 15 ms
[16:29:15]  copy started ...
[16:29:15]  typescript compiler started ...
[16:29:15]  lint started ...
[16:29:15]  copy finished in 113 ms
[16:29:17]  lint finished in 1.93 s
[16:29:19]  typescript compiler ready in 4.18 s
[16:29:19]  bundle dev started ...
[16:29:19]  Error: Could not resolve entry (./.tmp/app/main.dev.js)
    at .../node_modules/rollup/dist/rollup.js:8602:28
    at process._tickCallback (internal/process/next_tick.js:103:7)

[16:29:19]  sass started ...
[16:29:19]  sass failed:  Cannot generate Sass files without first bundling JavaScript files in order to know all used modules. Please build JS files first.

[16:29:19]  build dev failed:  Build failed
```

**Comment by mwymann** [comment] 2016-09-30 14:29
+1

**Comment by e-oz** [comment] 2016-09-30 14:58
I found how to fix this issue (at least for my app, but maybe will be useful for somebody else).
I had `components`, `services`, `interfaces` folders inside the `app` folder. After moving them one level up (to `src`) and changing `import`s, build passed successfully.

**Comment by abrahamstalin** [comment] 2016-09-30 15:00
update nodejs to 6.7.0, and finally works.

Thanks very much, see you later.

**Comment by jgw96** [comment] 2016-09-30 15:55
Hello all! Thanks for opening an issue with us! Since it seems like these errors are either caused by running npm 2 or missing something in the process of updating your app I am going to close this issue for now. Thanks for using Ionic!

**Closed by jgw96** 2016-09-30 15:55 UTC

**Comment by e-oz** [comment] 2016-09-30 16:15
@jgw96 in my case nothing was missed and everything was up to date. Please consider to mention in docs that Ionic can't work anymore with apps structure when `components` folder is inside of `app`.

**Comment by rept** [comment] 2016-09-30 22:24
@jgw96 I still have this issue:

Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.0.0-beta.20
OS: Mac OS X El Capitan
Node Version: v6.7.0
npm: 3.10.3

Started new project after updating to latest version of Ionic (project has new folder structure).

[00:18:40]  Error: Could not resolve '@angular/platform-browser-dynamic' from /listApp3/.tmp/app/main.dev.js

Updated npm, node, ... any other ideas?

**Comment by tomasbedrich** [comment] 2016-09-30 23:23
Not sure if it helps, but I have done `npm cache clean` before creating a new project.

**Comment by rept** [comment] 2016-10-01 07:55
@tomasbedrich did npm cache clean and then created new blank project and now it works!

**Comment by johnofkorea** [comment] 2016-10-01 17:00
@tomasbedrich Thank you so much! You just helped me out! Wow!

**Comment by koo9** [comment] 2016-10-02 18:38
install the latest nodejs 6.7 but ionic info shows:

Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.0.0-beta.20
OS: Windows 8.1
Node Version: v0.12.2
npm 2.7.4. 

getting the same error with rc0.

**Comment by koo9** [comment] 2016-10-02 18:52
C:\Users\dev>npm install npm -g
C:\Users\dev\AppData\Roaming\npm\npm -> C:\Users\dev\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
npm@3.10.8 C:\Users\dev\AppData\Roaming\npm\node_modules\npm

C:\Users\dev>npm -version
2.7.4

C:\Users\dev>npm cache clean

C:\Users\dev>npm -v
2.7.4

**Comment by koo9** [comment] 2016-10-03 03:43
after pulling half head of hair, finally narrow down the cause then found this step to update npm to the latest. [http://stackoverflow.com/questions/20711240/how-to-completely-remove-node-js-from-windows](url)

follow the steps in the solution to remove npm then reinstall nodejs then update will work as expected. 
now finally got RC0 to compile the project.

**Comment by BaHXeLiSiHg** [comment] 2016-10-03 09:19
> I found how to fix this issue (at least for my app, but maybe will be useful for somebody else).
I had components, services, interfaces folders inside the app folder. After moving them one level up (to src) and changing imports, build passed successfully.

had same situation, all my custom components were inside ./app folder...

moved them out, inside ./src folder, in the same level with ,/app folder and this fixed build error

**Comment by royipressburger** [comment] 2016-10-04 20:11
Im also getting this error. Installing again node did not help. Anyone have any ideas?

ionic info: 
```
Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v6.7.0
Xcode version: Xcode 8.0 Build version 8A218a 
```

Also tried with node version of 5.10 and npm 3.8. Same error

**Comment by Martin-Andersen** [comment] 2016-10-09 08:41
deleted the broken app updated npm and created a new app and everything is working.
Looking forward to take Ionic for a spin. I have an existing jquery mobile app I want to convert.

**Comment by nolazybits** [comment] 2016-10-11 08:15
@e-oz Thank you thank you thank you!!!
I had the same problem (same error regarding the /.tmp/app/main.dev.js)

@here Is there no way to actually have the structure we like, even if it means changing few configs. If so which ones and how please.

**Comment by ranneyd** [comment] 2016-11-06 04:56
Though not entirely related to OP's post, but if it helps someone like me who stumbles across this thread it's worth it:

I had this issue while trying to build with Visual Studio 2015. The solution was opening up command prompt, navigating to the directory of my project and running npm install manually. That worked like a charm.
