### ISSUE TITLE
Keyboard issue on iOS

### ISSUE THREAD

**Issue by ix-xerri** [driftyco/ionic#10403] opened 2017-02-11 17:03 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

There seems to be an issue when developing an input text in the footer on iOS. The issues are 2:
- The styling is not as good as android.
- You have to start typing before the screen scroll to the bottom. Unless you type the display will show the top view of the page.

This is the code for the input field on a simple chat application

```
<ion-footer>
  <ion-toolbar>
    <ion-row>
      <ion-col width-10>
          <ion-spinner *ngIf="!chats"></ion-spinner>
      </ion-col>
      
      <ion-col width-70 [hidden]="!chats">
          <ion-input type="text"  placeholder="Enter Message"
              [(ngModel)]="message">
          </ion-input>
      </ion-col>
      <ion-col width-20 [hidden]="!chats">
          <button ion-button full (click)="sendMessage()"><ion-icon name="send"></ion-icon></button>
      </ion-col>
    </ion-row>    
  </ion-toolbar>
</ion-footer>
```

If I remove the margin from .button-ios it is correctly displayed.

**Comment by jgw96** [comment] 2017-02-13 15:55
Hello, I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/9199

**Closed by jgw96** 2017-02-13 15:55 UTC
