### ISSUE TITLE
After upgrade to 2.3 build not work and freeze in first step.

### ISSUE THREAD

**Issue by jafaripur** [driftyco/ionic#10941] opened 2017-03-28 10:35 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
After upgrading to latest ionic version the build not work and freeze in first step

**Expected behavior:**
Build application

**Steps to reproduce:**
Run ionic build command in console:

```
ionic build android --release
```

**Other information:**
No warning or error in building just freeze.
In installing the packages the also this error occurred in npm console:
```
UNMET PEER DEPENDENCY typescript@2.0.9
npm WARN @ionic/app-scripts@1.2.2 requires a peer of typescript@~2.2.1 but none was installed.
```

I used the packages of app-base-2 repository.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.2.2
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.10.0
Xcode version: Not installed
```
```
> Test@ ionic:build /home/test-mobile
> ionic-app-scripts build --prod "--release"
```

**Comment by clucani** [comment] 2017-03-28 11:53
Same issue here. 

Cordova CLI: 6.5.0
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.2.2
ios-deploy version: 1.8.4
ios-sim version: 4.1.1
OS: macOS Sierra
Node Version: v6.9.5
Xcode version: Xcode 8.1 Build version 8B62

I can replicate by 

```
ionic start --v2 test sidemenu
cd test
rm -rf node_modules
npm install
```

**Comment by Ladeiras** [comment] 2017-03-28 13:18
Same here trying to build any ionic project:

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.2.2
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.9
Node Version: v7.7.4
Xcode version: Not installed

**Comment by bharathirajatut** [comment] 2017-03-28 13:25
Please go to node_modules/@ionic/app-scripts/package.json and change the   "typescript": "~2.2.1" to   "typescript": "*"

**Before**
  "name": "@ionic/app-scripts",
  "optionalDependencies": {},
  "peerDependencies": {
    "@angular/core": "*",
    "@angular/compiler": "*",
    "@angular/compiler-cli": "*",
    "@angular/tsc-wrapped": "*",
    "rxjs": "*",
    "sw-toolbox": "*",
    "typescript": "~2.2.1",
    "zone.js": "*"
  }

**After**

"name": "@ionic/app-scripts",
  "optionalDependencies": {},
  "peerDependencies": {
    "@angular/core": "*",
    "@angular/compiler": "*",
    "@angular/compiler-cli": "*",
    "@angular/tsc-wrapped": "*",
    "rxjs": "*",
    "sw-toolbox": "*",
    "typescript": "*",
    "zone.js": "*"
  },

**Comment by Ladeiras** [comment] 2017-03-28 14:00
It appears to be an [app-scripts issue](https://github.com/driftyco/ionic-app-scripts/issues/838).
Reverted to **@ionic/app-scripts@1.1.4** on my Linux machine.

**Comment by esmiralha** [comment] 2017-03-28 14:22
Same probem here.

**Comment by jgw96** [comment] 2017-03-28 17:12
Hello all, thanks for opening an issue with us! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic-app-scripts/issues/838

**Closed by jgw96** 2017-03-28 17:12 UTC
