### ISSUE TITLE
bug: (ionView): White screen when going back in history to a view with cache-view="false"

### ISSUE THREAD

**Issue by RomanMinkin** [driftyco/ionic#3216] opened 2015-03-03 03:37 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>White screen appears when going back in history to a view with `cache-view="false"` with new `swipe-to-go-back` gesture from `master`

```html
<ion-view view-title="Test" cache-view="false"></ion-view>
```

Happens on `iOS Emulator` and actual `iOS` (iPhone 5S) on new `swipe-to-go-back` form `master`
Does not happen in `Chrome Mobile Emulator` on `$ionicHistory.goBack()`

Please let me know if you need any additional info...

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-03-03 03:37
Greetings @RomanMinkin!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3216). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3216)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by hanford** [comment] 2015-03-09 00:34
+1

**Comment by harry81** [comment] 2015-03-17 14:45
+1

**Comment by calendee** [comment] 2015-03-18 11:08
Confirming this as well.  If the parent view is not cached, swiping back results in a white screen (with nav-bar if one exists).  Happens if cache is disabled in view or routing.

**Comment by josephfinlayson** [comment] 2015-03-25 09:54
+1

**Comment by calendee** [comment] 2015-03-26 18:56
Related / duplicate of https://github.com/driftyco/ionic/issues/2650

**Comment by daco** [comment] 2015-04-16 11:36
+1

**Comment by BrezelBob** [comment] 2015-04-23 12:49
+1

**Comment by alvaromb** [comment] 2015-04-30 14:20
+1 but I guess it's not simple to solve this if we're not caching the back views.

**Comment by josephfinlayson** [comment] 2015-04-30 14:48
It could be done by checking if the $ionicHistory.backView is cached and then cancelling the gesture if it isn't

**Comment by FMCorz** [comment] 2015-05-21 07:27
+1.

**Comment by fantasybei** [comment] 2015-07-01 07:45
+1 i meet the same problem. really annoying

**Comment by do-web** [comment] 2015-07-04 12:55
+1 when this bug is solved!?

**Comment by boshmaf** [comment] 2015-07-06 20:22
+1

**Comment by pooyaj** [comment] 2015-07-06 20:24
+1

**Comment by quanghoc** [comment] 2015-07-12 04:48
+1

**Comment by jackyon** [comment] 2015-07-23 07:46
+1

**Comment by vianneyniji** [comment] 2015-08-21 08:18
+1

**Comment by mbdrian** [comment] 2015-10-19 12:17
+1

**Comment by borodatych** [comment] 2015-11-25 11:34
+1

**Comment by brunomonteiro3** [comment] 2015-11-26 19:31
+1

**Comment by Peege151** [comment] 2015-12-09 02:00
+1 any progress on this? Disabling swipe to go back as of now...

**Comment by tschuegge** [comment] 2016-01-05 12:14
the same in 1.2

**Comment by mastermark5** [comment] 2016-01-12 16:16
+1 Still not working in 1.2.4

**Comment by kumaro** [comment] 2016-01-18 16:32
+1

**Comment by floofydoug** [comment] 2016-01-20 18:22
+1, i have to disable swipe to go back with `$ionicConfigProvider.views.swipeBackEnabled(false);` for now.

**Comment by balicekt** [comment] 2016-01-20 20:52
+1

**Comment by pluswave** [comment] 2016-01-22 07:59
+1

**Comment by kocsmy** [comment] 2016-01-22 13:09
+99

**Comment by mgoubert** [comment] 2016-01-22 15:26
+1

**Comment by mhartington** [comment] 2016-01-22 15:32
This is caused by caching being disabled. There is big benefit of caching you views, and an edge case like this isn't something we want to support. 

If you're worried about data not being updated, you can use the view lifecycle events to make sure data is up to date.

**Closed by mhartington** 2016-01-22 15:32 UTC
