### ISSUE TITLE
TypeError: Cannot read property 'options' of null

### ISSUE THREAD

**Issue by okonon** [driftyco/ionic#5177] opened 2016-01-25 04:52 UTC
I am getting a strange error on one of the scrollviews. I can't figure out what is causing it.
`TypeError: Cannot read property 'options' of null`

I think it is released to #2562 

Here is my info:
```
Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.2.4
Ionic CLI Version: 2.0.0-beta.12
Ionic App Lib Version: 2.0.0-beta.6
ios-deploy version: 1.8.3 
ios-sim version: 4.1.1 
OS: Mac OS X El Capitan
Node Version: v4.2.3
Xcode version: Xcode 7.2 Build version 7C68
```

**Comment by softBarbarian** [comment] 2016-01-28 20:20
Anybody having same issue out there?

**Comment by softBarbarian** [comment] 2016-02-16 14:49
...crickets...

**Comment by jgw96** [comment] 2016-03-14 16:15
Hello! Thanks for opening an issue with us, we just need a little more info from you so that we can better help you with your issue. Would you mind posting a code sample, plunkr or codepen that we can use to reproduce your issue? Thanks again!

**Comment by jgw96** [comment] 2016-03-22 19:22
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to respond back if your still having the issue! Thanks again!

**Closed by jgw96** 2016-03-22 19:22 UTC
Labels: scroll, v1

**Comment by Edulopez** [comment] 2017-02-07 01:38
I'm having the issue. any clues?

**Comment by tlkiong** [comment] 2017-03-16 12:46
Me too. Hmm.

For me, what I did was: 

Under app.js `$urlRouterProvider.otherwise('/route')`

once the `routeController` is loaded, the first thing I do is check for a certain criteria (eg: isLoggedIn). If yes, then will redirect the user to another view. Both the `route` view & the `other` view uses tabbed view.

**Comment by ShanuSaini** [comment] 2017-07-13 11:56
Hi Everyone,

Changing $state.go('dashboard-parent', {}, {reload: true, notify:true});
Or $state.go('dashboard-parent', null, {reload: true, notify:true});
to $state.go('dashboard-parent', {reload: true, notify:true});

Did the trick for me, Hope this helps
