### ISSUE TITLE
ionic2 - Platform.ready not fired - crosswalk

### ISSUE THREAD

**Issue by graphefruit** [driftyco/ionic#9059] opened 2016-11-06 21:15 UTC
#### Short description of the problem:
When building app on android with crosswalk plugin installed, the platform.ready is not executed/fired

#### What behavior are you expecting?
platform.ready gets triggered like without crosswalk

**Steps to reproduce:**
1. ionic start test --v2
2. ionic plugin add cordova-plugin-crosswalk-webview
3. 
```
 platform.ready().then(() => {
      console.log("platform ready fired");
});
```
4. ionic platform add android
5. ionic build android
6. Change on step 3 will never be triggered.

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

```
Native: deviceready did not fire within 2000ms. This can happen when plugins are in an inconsistent state. Try removing plugins from plugins/ and reinstalling them.
cordova.js:1223 deviceready has not fired after 5 seconds.
cordova.js:1216 Channel not fired: onCordovaInfoReady

```

**Which Ionic Version?** 2. RC 2

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
```

Your system information:

Cordova CLI: 6.4.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.39
OS:
Node Version: v6.7.0

```
Greetings 
Graphefruit

**Comment by jlno** [comment] 2016-11-06 23:35
+1

**Comment by ataraxus** [comment] 2016-11-07 09:03
i'm experiencing this also 


```
Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.39
OS: Windows 7 SP1
Node Version: v6.9.1

```

**Comment by jgw96** [comment] 2016-11-07 09:53
Hello, thanks for opening an issue with us! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/8984.

**Closed by jgw96** 2016-11-07 09:53 UTC
