### ISSUE TITLE
Split panel is not sizing content in menu when starting out smaller

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic#10518] opened 2017-02-21 20:14 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
1. Switch to the `split-panel` branch
2. Run `gulp e2e.watch`
3. Navigate to http://localhost:8000/dist/e2e/split-panel/basic/
4. Start out with a small screen where the side menu is not being displayed, if you start out with a large enough screen that it automatically shows you will need to refresh once smaller in order to reproduce
5. Open the side menu, notice that the content is behind the header
6. Drag the screen larger to where the menu appears, notice it is still behind the header
7. Refresh the page and notice it is resized properly

**Other information:**
Here's a gif example:

http://g.recordit.co/YmglWOLOgC.gif

**Comment by manucorporat** [comment] 2017-02-23 18:39
@brandyscarney should be fixed now!

**Comment by jgw96** [comment] 2017-02-27 22:37
Closing this as i could not reproduce with the latest of the split-panel branch.

**Closed by jgw96** 2017-02-27 22:37 UTC
Labels: v2
