### ISSUE TITLE
NavController can be swipe back while Loading is shown

### ISSUE THREAD

**Issue by thiphariel** [driftyco/ionic#6117] opened 2016-04-11 12:32 UTC
#### Short description of the problem: 
If you present a loader (even a modal after some tests...) on your controller, and you tap it, you will be able to swipe back your controller, which is not a wanted behaviour, I guess.

#### What behavior are you expecting?
To not be able to swipe during present modal / loader on controller.

**Steps to reproduce:**
1. Present a loading service on your nav controller
2. Tap on the loading content
3. Swipe back you controller
4. Make a sad face :(

```
// Show loader
let progress = '0%';
let loading = Loading.create({
     content: 'Téléchargement : ' + progress
});
this.nav.present(loading);
```

**Which Ionic Version?** 
ionic 2.0.0-beta.4

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.4
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
ios-deploy version: 1.8.5 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.10.1
Xcode version: Xcode 7.3 Build version 7D175 

If you need more informations, feel free to ask.

**Comment by jgw96** [comment] 2016-04-11 15:52
Hello! Thanks for opening an issue with us! As this issue is a duplicate of issue #6099 i will be closing this issue. Feel free to continue the conversation over on the other issue. Thanks again!

**Closed by jgw96** 2016-04-11 15:52 UTC
