### ISSUE TITLE
Popover issue on android

### ISSUE THREAD

**Issue by paschaldev** [driftyco/ionic#7247] opened 2016-07-09 02:09 UTC
There is a problem with ionic 2 popover and my current android device. I HAVE ANOT TRIED ON ANOTHER DEVICE BUT I GUESS IT SHOULD BE SAME...

The backdrop click that dismisses popover worked perfectly fine on desktop during development but freezes d app on an android device after generating apk. 

Also, on desktop, my popover contains ion items that links to other pages, when an item is clicked, after nav.push displays d page, I hooked into d promise and dismissed d modal with view controller.dismiss... Works fine on desktop, when I navigate back, I dont see d popover which is what I want but on android device, the popover doesnt dismiss.

Android version if the device is 5.1

**Comment by paschaldev** [comment] 2016-07-09 02:14
*Android version of the device is 5.1

**Comment by tomgallagher** [comment] 2016-07-09 07:44
+1 popover working fine in browser, not after package build and alpha deploy to Android KitKat device.
The popover won't dismiss.

**Comment by paschaldev** [comment] 2016-07-09 08:59
@tom you had d same experience right?

**Comment by tomgallagher** [comment] 2016-07-09 11:31
Yes. I have the problem in alpha testing on Google Play store. Popover does not dismiss as it should.                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the O2 network.                                                                                                                                                                                                                From: Ezeugwu PaschalSent: Saturday, 9 July 2016 10:00To: driftyco/ionicReply To: driftyco/ionicCc: Pathfinder; CommentSubject: Re: [driftyco/ionic] Popover issue on android (#7247)@tom you had d same experience right?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by jgw96** [comment] 2016-07-12 04:08
Hello, thanks for opening an issue with us. Could you create a repo that has a minimal example of this issue that i can use to reproduce? Thanks for using Ionic!

**Comment by vuhung3990** [comment] 2016-07-12 04:18
i have same problem

**Comment by tomgallagher** [comment] 2016-07-13 09:44
Hi I'm debugging Android device in Chrome and this is the error log for the popover.

EXCEPTION: Error in ./PopoverCmp class PopoverCmp - inline template:0:14 browser_adapter.js:86
EXCEPTION: Error in ./PopoverCmp class PopoverCmp - inline template:0:14 browser_adapter.js:77
ORIGINAL EXCEPTION: RangeError: Maximum call stack size exceeded browser_adapter.js:77
ORIGINAL STACKTRACE: browser_adapter.js:77
RangeError: Maximum call stack size exceeded
    at Object (<anonymous>)
    at Object.re.ToObject (file:///android_asset/www/build/js/es6-shim.min.js?ionicCachebuster=2199:10:4937)
    at Function.keys (file:///android_asset/www/build/js/es6-shim.min.js?ionicCachebuster=2199:10:24378)
    at _baseExtend (file:///android_asset/www/build/js/app.bundle.js?ionicCachebuster=2199:78388:27)
    at _baseExtend (file:///android_asset/www/build/js/app.bundle.js?ionicCachebuster=2199:78398:26)
    at _baseExtend (file:///android_asset/www/build/js/app.bundle.js?ionicCachebuster=2199:78398:26)
    at _baseExtend (file:///android_asset/www/build/js/app.bundle.js?ionicCachebuster=2199:78398:26)
    at _baseExtend (file:///android_asset/www/build/js/app.bundle.js?ionicCachebuster=2199:78398:26)
    at _baseExtend (file:///android_asset/www/build/js/app.bundle.js?ionicCachebuster=2199:78398:26)
    at _baseExtend (file:///android_asset/www/build/js/app.bundle.js?ionicCachebuster=2199:78398:26) browser_adapter.js:77
ERROR CONTEXT: browser_adapter.js:77
DebugContext {_view: _View_PopoverCmp0, _nodeIndex: 0, _tplRow: 0, _tplCol: 14}
_nodeIndex: 0
_staticNodeInfo: (...)
_tplCol: 14
_tplRow: 0
_view: _View_PopoverCmp0
component: (...)
componentRenderElement: (...)
context: (...)
injector: (...)
providerTokens: (...)
references: (...)
renderNode: (...)
source: (...)
__proto__: DebugContext

**Comment by jgw96** [comment] 2016-07-13 14:26
Hello all, im gonna close this issue as a duplicate of https://github.com/driftyco/ionic/issues/6918. Thanks for using Ionic!

**Closed by jgw96** 2016-07-13 14:26 UTC
Labels: needs reply, platform:android, popover, v2
