### ISSUE TITLE
Ionic2 - Build fails because of custom pipe

### ISSUE THREAD

**Issue by graphefruit** [driftyco/ionic#9045] opened 2016-11-05 11:22 UTC
#### Short description of the problem:
ionic build android fails because of a pipe inside template.
ionic serve works fine

#### What behavior are you expecting?
ionic build android should not fail and build the project normaly

**Steps to reproduce:**
1. Create custom pipe
`import { Pipe, PipeTransform } from '@angular/core';
@Pipe({name: 'keys'})
export class KeysPipe implements PipeTransform {
  transform(value, args:string[]) : any {
    let keys = [];
    for (let key in value) {
      keys.push(key);
    }
    return keys;
  }
}
`
2. Add pipe to app.module.ts
2.1. `import {KeysPipe} from '../pipes/keys';`
2.2 `@NgModule({
  declarations: [KeysPipe]})`
3. Create custom page 
```
<ion-content>
  <ion-card *ngFor="let key of keys | keys"></ion-card>
</ion-content>
```
4.Create object with keys
`keys = {"Entry1":1, "Entry2":2}`

5. ionic platform add android
6. ionic build android
7. 
```
[12:15:18]  Error: Error at
            C:/Users//.tmp/pages/info/licences/licences.ngfactory.ts:271:47
[12:15:18]  Supplied parameters do not match any signature of call target.
[12:15:18]  ngc failed
[12:15:18]  ionic-app-script task: "build"
[12:15:18]  Error: Error

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@ build: `ionic-app-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic-hello-world@ build script 'ionic-app-scripts build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-hello-world
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic-hello-world
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Documents\npm-debug.log
Caught exception:
 undefined
```

If you remove the | keys pipe now everything works fine. It looks like the pipe isn't realized
 

**Which Ionic Version?** 2 RC1

**Related** Related link is found here: https://forum.ionicframework.com/t/ionic-build-when-using-a-custom-pipe-supplied-parameters-do-not-match-any-signature-of-call-target/65420

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
```
--------------------------------
--------------------------------

Your system information:

Cordova CLI: 6.4.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.39
OS:
Node Version: v6.7.0


--------------------------------
```

Greetings
Graphefruit

**Comment by ghenry22** [comment] 2016-11-05 14:47
Put a ? After value and after args which makes them optional values to typescript that should fix your error.

**Comment by graphefruit** [comment] 2016-11-05 16:30
@ghenry22 True it fixes the problem, but its weird that ionic serve is working but ionic build not, it should have the same problem or am I missing something?

**Comment by ghenry22** [comment] 2016-11-06 00:48
I'm not sure I don't use ionic serve that much, maybe one is treated as a dev build and one as production so it's less strict.


Gaven






On Sun, Nov 6, 2016 at 12:31 AM +0800, "graphefruit" <notifications@github.com> wrote:












@ghenry22 True it fixes the problem, but its weird that ionic serve is working but ionic build not, it should have the same problem or am I missing something?

**Comment by alan-agius4** [comment] 2016-11-06 17:35
Ionic `build` uses `ngc` while `serve` doesn't. 

`ngc` is a bit more strict and does checks on the templates as well while `tsc` doesn't

**Comment by jgw96** [comment] 2016-11-07 10:09
Hello all! As @alan-agius4 posted NGC, which `ionic build` uses to do AoT compile of the templates in your app is very strict. `ionic serve` does not use NGC which is why you do not get the same error with that command. We are currently working with the Angular team (which built the NGC) to get it to provide better error messages. Since this is expected behavior and @ghenry22 's solution is the correct one I will be closing this issue for now. Thanks!

**Closed by jgw96** 2016-11-07 10:09 UTC
