### ISSUE TITLE
[v2] Loading component throws exception

### ISSUE THREAD

**Issue by biesbjerg** [driftyco/ionic#6299] opened 2016-04-24 21:22 UTC
#### Short description of the problem:
The following code throws an error on load. It seems to only happen when using `dismissOnPageChange`-option.
```
	public onPageDidEnter() {
		let loading = Loading.create({
			content: 'Loading...',
			dismissOnPageChange: true
		});
		this._navController.present(loading);
	}
```

Check console in this plunker: http://plnkr.co/edit/nx6Su33A1yX1QmBTs2bP?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
```
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.5
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v4.4.2
Xcode version: Xcode 7.3 Build version 7D175
```

Stack trace when running in emulator:
```
2     650369   error    EXCEPTION: TypeError: undefined is not an object (evaluating 'leavingView.pageRef().nativeElement')
3     650370   error    STACKTRACE:
4     650371   error    LoadingPopOut@http://10.0.0.210:8100/build/js/app.bundle.js:42873:40
createTransition@http://10.0.0.210:8100/build/js/app.bundle.js:62870:35
http://10.0.0.210:8100/build/js/app.bundle.js:45366:74
invoke@http://10.0.0.210:8100/build/js/angular2-polyfills.js:390:34
run@http://10.0.0.210:8100/build/js/angular2-polyfills.js:283:50
runOuter@http://10.0.0.210:8100/build/js/app.bundle.js:28724:74
runOutsideAngular@http://10.0.0.210:8100/build/js/app.bundle.js:28642:88
_beforeTrans@http://10.0.0.210:8100/build/js/app.bundle.js:45356:37
_postRender@http://10.0.0.210:8100/build/js/app.bundle.js:45338:26
_render@http://10.0.0.210:8100/build/js/app.bundle.js:45254:29
_transition@http://10.0.0.210:8100/build/js/app.bundle.js:45226:21
remove@http://10.0.0.210:8100/build/js/app.bundle.js:45087:29
dismiss@http://10.0.0.210:8100/build/js/app.bundle.js:46679:32
http://10.0.0.210:8100/build/js/app.bundle.js:45515:37
forEach@[native code]
_transFinish@http://10.0.0.210:8100/build/js/app.bundle.js:45513:44
http://10.0.0.210:8100/build/js/app.bundle.js:45227:31
http://10.0.0.210:8100/build/js/app.bundle.js:45440:21
invoke@http://10.0.0.210:8100/build/js/angular2-polyfills.js:390:34
onInvoke@http://10.0.0.210:8100/build/js/app.bundle.js:28691:47
invoke@http://10.0.0.210:8100/build/js/angular2-polyfills.js:389:43
runGuarded@http://10.0.0.210:8100/build/js/angular2-polyfills.js:297:54
runInner@http://10.0.0.210:8100/build/js/app.bundle.js:28722:81
run@http://10.0.0.210:8100/build/js/app.bundle.js:28629:74
_afterTrans@http://10.0.0.210:8100/build/js/app.bundle.js:45411:23
http://10.0.0.210:8100/build/js/app.bundle.js:45387:34
_didFinish@http://10.0.0.210:8100/build/js/app.bundle.js:37518:26
play@http://10.0.0.210:8100/build/js/app.bundle.js:37192:28
http://10.0.0.210:8100/build/js/app.bundle.js:45398:36
invoke@http://10.0.0.210:8100/build/js/angular2-polyfills.js:390:34
run@http://10.0.0.210:8100/build/js/angular2-polyfills.js:283:50
runOuter@http://10.0.0.210:8100/build/js/app.bundle.js:28724:74
runOutsideAngular@http://10.0.0.210:8100/build/js/app.bundle.js:28642:88
_beforeTrans@http://10.0.0.210:8100/build/js/app.bundle.js:45356:37
_postRender@http://10.0.0.210:8100/build/js/app.bundle.js:45338:26
http://10.0.0.210:8100/build/js/app.bundle.js:45268:42
http://10.0.0.210:8100/build/js/app.bundle.js:55568:31
http://10.0.0.210:8100/build/js/app.bundle.js:55123:21
invoke@http://10.0.0.210:8100/build/js/angular2-polyfills.js:390:34
onInvoke@http://10.0.0.210:8100/build/js/app.bundle.js:28691:47
invoke@http://10.0.0.210:8100/build/js/angular2-polyfills.js:389:43
run@http://10.0.0.210:8100/build/js/angular2-polyfills.js:283:50
http://10.0.0.210:8100/build/js/angular2-polyfills.js:635:61
invokeTask@http://10.0.0.210:8100/build/js/angular2-polyfills.js:423:43
onInvokeTask@http://10.0.0.210:8100/build/js/app.bundle.js:28682:51
invokeTask@http://10.0.0.210:8100/build/js/angular2-polyfills.js:422:55
runTask@http://10.0.0.210:8100/build/js/angular2-polyfills.js:320:58
drainMicroTaskQueue@http://10.0.0.210:8100/build/js/angular2-polyfills.js:541:43
g@http://10.0.0.210:8100/build/js/es6-shim.min.js:11:1947
http://10.0.0.210:8100/build/js/es6-shim.min.js:11:1877
promiseReactionJob@[native code]
```

**Comment by iignatov** [comment] 2016-04-24 21:29
It seems related to #6209.

**Comment by biesbjerg** [comment] 2016-04-24 21:34
Ah, I missed that one. It seems like the same issue, yes.

**Comment by jgw96** [comment] 2016-04-25 14:42
Hey guys! I will be closing this issue as a dupe of #6209 . Thanks for using ionic! And feel free to chime in on the other issue.

**Closed by jgw96** 2016-04-25 14:42 UTC
Labels: platform:ios
