### ISSUE TITLE
ionic popup inside ionic slider not working

### ISSUE THREAD

**Issue by vaidyanathanas** [driftyco/ionic#4921] opened 2016-01-07 09:04 UTC
ionic popup inside ionic slider not working. ionic popup is displayed in backward of ionic slider. Where ionic slider is inside ionic modal. please help.

**Comment by Ionitron** [comment] 2016-01-08 01:23
Greetings @vaidyanathanas!

My sensors indicate that I require more information in order to assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this happen occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using Ionic, I recommended visiting [the forum](http://forum.ionicframework.com), where many humans will be able to offer wisdom and advice.

Thank you for allowing me to assist you.

<span ionitron-needs-reply></span>

**Comment by vaidyanathanas** [comment] 2016-01-19 12:01
Issue is in android. it is mainly display problem.  i am using a modal that popup inside that there is ionic slider and in ionic slider there is button. when i click on that button ionic popup is shown behind this slider and modal. i dont know how to use codepen. it multi page application.

**Comment by jgw96** [comment] 2016-03-14 18:31
Hello, thanks for opening an issue with us! Would you be able to provide a repo we can pull and test to be able to reproduce your issue?

**Comment by jgw96** [comment] 2016-04-14 17:05
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to respond back if your still having the issue! Thanks again!

**Closed by jgw96** 2016-04-14 17:05 UTC
Labels: popover, slidebox
