### ISSUE TITLE
bug: Icon and text not rendered in line in button element on FF

### ISSUE THREAD

**Issue by mpaland** [driftyco/ionic#6695] opened 2016-05-30 09:28 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Icon and text are not rendered in line in a list on FF 46. No problem in Edge Browser.
Example is the actual conference app in Firefox.
The sidemenu is an item button list with the icon positioned left.

This is how it looks like in **FF**:
![button icon](https://cloud.githubusercontent.com/assets/763140/15645614/c42fe37a-2659-11e6-8a8c-6cec30fc684d.PNG)

... and (correct) in **Edge**:
![button icon edge](https://cloud.githubusercontent.com/assets/763140/15645963/8c7dacf8-265b-11e6-8fc6-5184d06b922b.PNG)

Placing the icon on the right side (item-right) the problem goes away.

Tests with actual beta7</span>

<span is-issue-template></span>

**Comment by manucorporat** [comment] 2016-05-30 15:55
Duplicate of https://github.com/driftyco/ionic/issues/5622

**Closed** 2016-05-30 15:58 UTC
Labels: duplicate, menus, v2
