### ISSUE TITLE
White box in toolbar area (android)

### ISSUE THREAD

**Issue by dheran** [driftyco/ionic#7951] opened 2016-09-02 07:25 UTC
ionic 2 - Android L

Hope screenshots explains better

![screenshot_2016-09-01-12-17-31](https://cloud.githubusercontent.com/assets/15922996/18195996/73df46e2-710c-11e6-8009-7c9e9780df92.png)

![screenshot_2016-08-31-12-09-43](https://cloud.githubusercontent.com/assets/15922996/18196019/9a48e810-710c-11e6-82b0-94c54c4964c6.png)

**Comment by jgw96** [comment] 2016-09-02 18:10
Hello, thanks for opening an issue with us! Would you mind posting a repo I can use to reproduce this issue? Thanks!

**Comment by dheran** [comment] 2016-09-04 14:06
this is not occurring in browsers and in all the devices. This occurs randomly on a particular device

**Comment by jgw96** [comment] 2016-09-06 12:56
Hello, unfortunately I cannot seem to reproduce with any of my test devices or on the Android emulator. It is possible that this is a bug in the webview of this particular device and would most likely be solved by using Crosswalk, would you mind giving crosswalk a try? If you could narrow it down to a reproduce able that would be great!

**Comment by dheran** [comment] 2016-09-08 06:41
I'm not sure whether Android L needs crosswalk :-(

**Comment by jgw96** [comment] 2016-09-08 13:00
Stock Android 5 should not need crosswalk as it uses a chrome based webview that is updated independently from the OS, but in some cases Android device manufacturers implement their own webviews or modify the webview in some way. Is this a samsung device that you are having the issue on?

**Comment by jgw96** [comment] 2016-09-12 15:57
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-09-12 15:57 UTC
Labels: needs reply, platform:android, v2
