### ISSUE TITLE
nav bar: changing bar-* class does not update underlying header bar class

### ISSUE THREAD

**Issue by Morriz** [driftyco/ionic#3013] opened 2015-01-31 12:47 UTC
The ion-nav-bar directive should be listening to changes to it's bar-* class, and update it's children accordingly. The delegate should also offer a method to set the bar class programmatically.

I would create it if I had a better grasp on your code. Maybe later.

**Comment by Ionitron** [comment] 2015-01-31 12:48
Greetings @Morriz!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3013). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3013)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

**Comment by Ionitron** [comment] 2015-03-30 23:34
Greetings @Morriz!

My sensors indicate that I require more information in order to assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this happen occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com), where many humans will be able to offer wisdom and advice.

Thank you for allowing me to assist you.

<span ionitron-needs-reply></span>

**Comment by Ionitron** [comment] 2015-04-30 07:16
Greetings @Morriz!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-04-30 07:16 UTC
Labels: ionitron:closed
