### ISSUE TITLE
Bug div scroll to all screen

### ISSUE THREAD

**Issue by cesar-oyarzun-m** [driftyco/ionic#6073] opened 2016-04-07 15:12 UTC
Hi,

I'm using ionic version = '1.2.4-nightly-2775'; on android 5.1.1 and all the screen has visible scroll. I have inspect the DOM and I see and extra div with class srcoll.

This is my html
    
    <ion-view view-title="Beacon List">
    <ion-header-bar class="bar bar-subheader bar-dark">
        <h1 class="title">
        </h1>
        <div class="buttons">
            <button  class="button button-balanced" ng-class="scanning? 'button-assertive':button-balanced" </button>
        </div>
    </ion-header-bar>
    <ion-content >

        <ion-list>
            <ion-item  ng-repeat="beacon in beacons">
                <div expclick="getBeaconDetails($event, beacon)">
                    <h2 ng-show="beacon.proximityUuid">{{beacon.proximityUuid}} ({{beacon.manufacturer}})</h2>
                    <p ng-show="beacon.idBeacon">{{beacon.idBeacon}} ({{beacon.manufacturer}})</p>
                    <p ng-show="beacon.major">Major: {{beacon.major}} Minor: {{beacon.minor}}</p>
                    <p>RSSI: {{beacon.rssi}}</p>
                    <p ng-show="beacon.distance">Distance: {{beacon.distance | number : 2}}</p>
                    <p ng-show="beacon.uuid">UUID: {{beacon.uuid}}</p>
                </div>
            </ion-item>
        </ion-list>
    </ion-content>
</ion-view>

<img width="922" alt="screen shot 2016-04-07 at 11 09 14 am" src="https://cloud.githubusercontent.com/assets/7967891/14356048/404cf0ec-fcb1-11e5-91f5-fbfb60ca4c73.png">

**Comment by jgw96** [comment] 2016-04-07 18:30
Hello! Thanks for opening an issue with us! Sorry, i am slightly unsure of what the issue is. Are you seeing scrollbars on your app?

**Comment by cesar-oyarzun-m** [comment] 2016-04-07 18:44
yeah @jgw96 all the screens has scroll even if the screen is empty, I fixed it just by overriding the style to auto instead of scroll.

    /* FIX scroll issue */
    .overflow-scroll {
      overflow-y: auto;
    }

**Comment by cesar-oyarzun-m** [comment] 2016-04-13 20:50
@jgw96 I have other issue related to the extra div scroll, it doesn't have a height set, so if I have a child with css like height:90% it doesn't work because the parent doesn't have a height. Do you know how can I do a work around for this?

**Comment by jgw96** [comment] 2016-04-13 21:04
Thanks for the info! I am currently testing this issue. Also since this issue is a duplicate of #4928 i am going to go ahead and close this issue. Lastly, would you mind opening a new issue for the bug you stated in the last message? Thanks again!

**Closed by jgw96** 2016-04-13 21:04 UTC
Labels: scroll, v1
