### ISSUE TITLE
Blank scroll area were added when ion-textarea gets focused on Android 

### ISSUE THREAD

**Issue by dheeran1** [driftyco/ionic#6052] opened 2016-04-06 08:13 UTC
** Ionic v2 **

Scroll area not going even after closing the andorid keyboard.

**Comment by dylanvdmerwe** [comment] 2016-04-06 13:16
Isn't this a dup of https://github.com/driftyco/ionic/issues/5810 and https://github.com/driftyco/ionic/issues/5536

**Comment by adamdbradley** [comment] 2016-04-06 14:09
Yes this is a duplicate of #5536

**Closed by adamdbradley** 2016-04-06 14:09 UTC
Labels: keyboard, platform:android, v2

**Comment by EvanWillms** [comment] 2016-04-10 23:05
And a dup of #5432
