### ISSUE TITLE
cordova and plugins not available during development on device iOS/Android

### ISSUE THREAD

**Issue by gabrielmuresan** [driftyco/ionic#9277] opened 2016-11-22 08:50 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I can't use ANY cordova plugins during development anymore. (no splash screen, no sqlite, nothing)
**Expected behavior:**
Before updating everything worked as expected (i was working with rc2)

**Steps to reproduce:**
`ionic start test-app --v2`
`cd test-app`
`ionic plugin add cordova-sqlite-storage`

>> following tutorial: http://ionicframework.com/docs/v2/native/sqlite/
open src/app/app.compontent.ts
`import { SQLite } from 'ionic-native';`
modify platform.ready()
```
platform.ready().then(() => {
      let db = new SQLite();
      db.openDatabase({
        name: 'data.db',
        location: 'default' // the location field is required
      }).then(() => {
        db.executeSql('create table danceMoves(name VARCHAR(32))', {}).then(() => {

        }, (err) => {
          console.error('Unable to execute sql: ', err);
        });
      }, (err) => {
        console.error('Unable to open database: ', err);
      });
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      StatusBar.styleDefault();
      Splashscreen.hide();
    });
```

`ionic emulate ios -lc --target="iPhone-6"`

ERROR:
`ReferenceError: Can't find variable: sqlitePlugin`

cordova.js content ON DEVICE using safari inspector
`// mock cordova file during development`

```
Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: macOS Sierra
Node Version: v6.2.2
Xcode version: Xcode 8.1 Build version 8B62
```

Error is the same on android.

What can I do? this is driving me crazy.

**Comment by biesbjerg** [comment] 2016-11-22 08:57
Are you using livereload? This has be been reported: https://github.com/driftyco/ionic/issues/9263

**Comment by gabrielmuresan** [comment] 2016-11-22 09:03
Thank you! I used search before posting using the keyworkd `cordova` and nothing came up.

**Comment by biesbjerg** [comment] 2016-11-22 09:18
Let's hope it gets fixed soon! It's very time consuming testing cordova stuff without livereload. I've tried to fix it myself in ionic-cli and app-scripts, but I did not manage to get it working.

**Comment by jgw96** [comment] 2016-11-22 17:27
Hello, thanks for using Ionic! I am going to close this one as a duplicate of https://github.com/driftyco/ionic/issues/9263.

**Closed by jgw96** 2016-11-22 17:27 UTC
