### ISSUE TITLE
ion-search has delay on touch/focus on iOS

### ISSUE THREAD

**Issue by gregblass** [driftyco/ionic#6028] opened 2016-04-02 22:46 UTC
#### Short description of the problem:
The ion-search bar has a delay when tapping/focus on iOS

#### What behavior are you expecting?
It should open the keyboard instantly without a delay so the user has a native-like experience.

**Steps to reproduce:**
1. Create a new Ionic 2 tabs application and replace an ion-title with an ion-searchbar on any tab
2. Open app in iOS emulator or a physical iOS device
3. Tap the search bar

```
<ion-navbar *navbar>
  <ion-searchbar></ion-searchbar>
</ion-navbar>
``` 

**Which Ionic Version?** 1.x or 2.x
2

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Your system information:

Cordova CLI: 6.1.0 (cordova-lib@undefined)
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.23
Ionic App Lib Version: 2.0.0-beta.13
ios-deploy version: 1.8.3 
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v5.8.0
Xcode version: Xcode 7.2.1 Build version 7C1002

**Comment by jgw96** [comment] 2016-04-05 17:06
Hello! As this issue is related to issue #6023 i will be closing this one for now, thanks though!

**Comment by gregblass** [comment] 2016-04-05 17:10
In my opinion, they're really two separate issues. One is the animation being choppy - but even with the animation disabled, there is a tap delay. Personally I'd keep them both open as they are separate issues.

**Comment by jgw96** [comment] 2016-04-05 18:17
Ahh ok, sorry misunderstood this originally as the tap delay being due to the animation being choppy, sorry about that (:

**Comment by manucorporat** [comment] 2016-09-20 19:30
@gregblass is this still a problem? I can't reproduce this problem anymore, it works pretty fast to me

**Comment by jgw96** [comment] 2016-09-20 20:41
Hello all! I am going to close this issue for now as I cannot reproduce on beta.12. Thanks for using Ionic!

**Closed by jgw96** 2016-09-20 20:41 UTC
Labels: keyboard, platform:ios, searchbar, v2

**Comment by romanrast** [comment] 2017-02-25 23:06
Seeing this problem on Ionic v2.0. When using a nomral input as like
`<ion-item>
    <ion-input placeholder="Clear Input" clearInput></ion-input>
  </ion-item>`
it works fine as expected. But using ion-searchbar with or without animation shows a delay. Also closing the keyboard shows a white background flashing up where the keyboard was. Gonna update to Ionic 2.0.1 and let you know if this issue still excists. Meantime going with a simple input and doing some css styling seems the best solution. Please fix it ;) thx!

**Comment by romanrast** [comment] 2017-02-25 23:40
Version 2.0.1 no change, still showing the delay.
