### ISSUE TITLE
bug: ion-scroll zooming not working

### ISSUE THREAD

**Issue by ErkoKnoll** [driftyco/ionic#5707] opened 2016-03-04 08:19 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x beta2</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>When using the following code it will display the image and allows scrolling but zooming does not seem to work:
`<ion-content>
    <ion-scroll scrollX="true" scrollY="true" zoom="true" maxZoom="3" style="width: 100%; height: 100%;">
        <div style="width: 4500px; height: 2498px; background-image: url(https://upload.wikimedia.org/wikipedia/commons/1/13/Wallpaper-world-map-2006-large.JPG);"></div>
    </ion-scroll>
</ion-content>`
</span>

<span is-issue-template></span>

**Comment by jgw96** [comment] 2016-03-11 20:13
Thanks for submitting this bug! As it is a duplicate of #5701 I will be closing this for now. Please feel free to continue the discussion over there!

**Closed by jgw96** 2016-03-11 20:13 UTC
Labels: platform:android, scroll, v2
