### ISSUE TITLE
feat: add id to alert buttons in ion-select

### ISSUE THREAD

**Issue by maudvd** [driftyco/ionic#28204] opened 2023-09-20 14:08 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

For testing purposes, we are adding ids to components with which users may interact in our app.

When creating an ion-alert, I can add an id to each alert button. But when creating an ion-select, i can only set the text of the buttons in the alert. I cannot set an id for the buttons.

Is it possible to add the option in the ion-select interfaceOptions to set an id for the ok and cancel button ?

### Describe the Use Case

For testing purposes.

**Comment by liamdebeasi** [comment] 2023-09-20 15:08
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/22917. The issue mentions `aria-label`, but the underlying problem is the same.

**Closed as not planned by liamdebeasi** 2023-09-20 15:08 UTC
Labels: triage
