### ISSUE TITLE
[RC1]ionic serve build error

### ISSUE THREAD

**Issue by six006** [driftyco/ionic#8699] opened 2016-10-14 10:41 UTC
Ionic2 RC1 using command 'ionic serve' return the error

[18:34:26]  copy finished in 9.91 s
(node:131600) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rej
ection id: 1): Error: Could not resolve './app.module' from D:\Javascript\ionic-
conference-app-master\src\app\main.dev.ts

Cordova CLI: Not installed
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Windows 7 SP1
Node Version: v6.8.0

**Comment by six006** [comment] 2016-10-14 10:50
using the latest "@ionic/app-scripts": "^0.0.33" solve the error

**Comment by azakusilo** [comment] 2016-10-14 12:21
How to do this?

**Comment by basvdijk** [comment] 2016-10-14 13:57
Change the line describing `@ionic/app-scripts` in your `package.json`, throw away your `node_modules` folder and run `npm install`

**Comment by azakusilo** [comment] 2016-10-14 14:22
Thank you

**Comment by jgw96** [comment] 2016-10-14 15:12
Hello all! Thanks for opening an issue with us! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic-app-scripts/issues/166.

**Closed by jgw96** 2016-10-14 15:12 UTC
