### ISSUE TITLE
Ion-input does not expose all input events.

### ISSUE THREAD

**Issue by nanexcool** [driftyco/ionic#5814] opened 2016-03-11 18:23 UTC
#### Short description of the problem:

Ion-Input does not expose all input events from a regular HTML input.

#### What behavior are you expecting?

I tested an ion-input with
```js
<ion-input (blur)="onBlur($event)" (focus)="onFocus($event)" type="text"></ion-input>
```

and didn't get any results.

But this works:
```js
<input (blur)="onBlur($event)" (focus)="onFocus($event)" type="text" />
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

Posting an issue here as per requested by mhartington
https://forum.ionicframework.com/t/ion-input-event-list/46165
 

**Which Ionic Version?** 1.x or 2.x

Tested with v2, specifically 2.0.0-beta.2

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.2
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
OS: Distributor ID:	Ubuntu Description:	Ubuntu 15.10 
Node Version: v4.3.2

**Comment by brandyscarney** [comment] 2016-03-11 20:16
Thank you for the issue! This is a duplicate of https://github.com/driftyco/ionic/issues/5487 so I am going to close this one. Please continue the discussion there. :smile:

**Closed by brandyscarney** 2016-03-11 20:16 UTC
Labels: v2
