### ISSUE TITLE
Infinite scroll with tabs quick switch causes continuous calls

### ISSUE THREAD

**Issue by epelc** [driftyco/ionic#2296] opened 2014-09-26 04:50 UTC
Currently I have two tabs and both have infinite scrolling lists in them. They both work perfectly fine and disable when there isn't more data to pull except if when the app starts you quickly switch from one tab to the other. Then the first tab will just keep calling the infinite scroll function until it runs out of data. Normally it only calls this when you scroll down to the bottom so I guess it isn't recalculating the height of the old tab or something. Also if you switch back to the first tab it will continue to call the infinite scroll until there isn't anymore data even if your at the top of the list.

I'm pretty sure this is a bug and not on my end. But I might be able to set a second ng-if on my infinite scroll that I set when I switch tabs to fix this for now.

**Comment by Ionitron** [comment] 2015-01-19 01:24
Greetings, @epelc!

My sensors indicate that this issue has been inactive for a while.
Due to this, the issue will be closed in 7 days.

If you believe the issue has not been fixed, please add a comment.
This will notify us so we can assist you, and will prevent the issue from being automatically closed.
Feel free to include the following information about the issue, so that we may assist you:

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- What platform does this happen on? (iOS, Android, all, etc.)
- What platform versions does this happen on? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework, or Ionic CLI?

Thank you for allowing me to assist you.

**Comment by perrygovier** [comment] 2015-02-23 21:46
@epelc, I'm having trouble reproducing this? Are you able to provide a codepen or example?

**Comment by Ionitron** [comment] 2015-03-26 00:28
Greetings @epelc!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment] 2015-03-26 00:28
Greetings @epelc!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-03-26 00:28 UTC
Labels: ionitron:closed, scroll

**Comment by mizrachiran** [comment] 2016-02-12 14:18
I experience the same issue.
When navigating to another state while loading (before the scroll.infiniteScrollComplete was fired), infinite scroll keeps calling in loop and doesn't stop.

Any workaround \ update on this?

**Comment by rishidotanand** [comment] 2016-02-26 05:59
This problem is causing my project to not be released.. is there any workaround for this??
