### ISSUE TITLE
update existing code to rc4 can't resolve input focusing & keyboard issue

### ISSUE THREAD

**Issue by ykonstant** [driftyco/ionic#9881] opened 2017-01-05 06:42 UTC
I have rc3 project, and update to rc4 as described:-
https://github.com/driftyco/ionic/blob/master/CHANGELOG.md
and also update package.json file
but it can't resolve this issue,

**Comment by dylanvdmerwe** [comment] 2017-01-05 10:48
Hi @ykonstant, you'll need to give much more information than that. Can you please create a reproducible plunkr to demonstrate the issue you are having? Also can you paste the output from `ionic info`.

**Comment by jgw96** [comment] 2017-01-05 17:44
Hey @ykonstant ! Thanks for opening an issue with us! Would you be able to provide a plunker or repo i can use to reproduce this issue? Even some sample code would help (:

**Comment by ykonstant** [comment] 2017-01-06 10:42
Hello jgw96
thanks for reply

I have a simple form
<ion-header color="green" class="custom">
    <ion-navbar color="green">
        <ion-title>Sign Up</ion-title>
    </ion-navbar>
    <div class="caret"></div>
</ion-header>

<ion-content no-bounce padding color="dark" class="dark-bg gray">
    <div class="login-form ">
        <div style="height: 8px;height: 2.5vw;"></div>
        <form [formGroup]="signupForm" (ngSubmit)="formSubmit()" novalidate>
            <div class="profilearea" [ngStyle]="{'background-image': 'url(' + base64Image + ')'}" [style.background-size]="base64Image == 'assets/icon/user-icon1.png' ? 'auto 70%' : ''" (click)="takePicture()"></div>

            <div style="height: 16px;height: 5.125vw;"></div>
            <ion-grid class="custom">
                <ion-row>
                    <ion-col width-50>
                        <ion-item class="custom">
                            <ion-input type="text" formControlName="first_name" placeholder="First Name"></ion-input>
                        </ion-item>
                    </ion-col>
                    <ion-col width-50>
                        <ion-item class="custom">
                            <ion-input type="text" formControlName="last_name" placeholder="Last Name"></ion-input>
                        </ion-item>
                    </ion-col>
                </ion-row>
            </ion-grid>
            <div style="height: 10px; height: 3.125vw;"></div>
            <ion-item class="custom">
                <ion-input type="tel" formControlName="phone" placeholder="Phone"></ion-input>
            </ion-item>
            <div style="height: 10px; height: 3.125vw;"></div>
            <ion-item class="custom">
                <ion-input type="text" formControlName="address" placeholder="Address"></ion-input>
            </ion-item>
            <div style="height: 10px; height: 3.125vw;"></div>
            <ion-item class="custom">
                <ion-input type="email" formControlName="email" placeholder="Email"></ion-input>
            </ion-item>
            <div style="height: 10px; height: 3.125vw;"></div>
            <ion-item class="custom">
                <ion-input type="email" formControlName="paypal_email" placeholder="Paypal email address"></ion-input>
            </ion-item>
            <div style="height: 10px; height: 3.125vw;"></div>
            <ion-item class="custom">
                <ion-input type="password" formControlName="password" placeholder="Password"></ion-input>
            </ion-item>
            <div style="height: 10px; height: 3.125vw;"></div>
            <ion-item class="transparent-bg trasparent-border gray padnone font10">
                <ion-label>Upgrade to Pro <span color="green" ion-text>(Learn More)</span></ion-label>
                <ion-toggle formControlName="type" color="green"></ion-toggle>
            </ion-item>

            <div style="height: 10px; height: 3.125vw;"></div>

            <div class="login-btn">
                <button ion-button color="green" type="submit" id="login-button4" small block class="custom ">
                    Sign Up
                </button>
                <div style="height: 10px; height: 3.125vw;"></div>
                <div text-center *ngIf="formData == undefined">Already registered? Please, <a (click)="login()" color="green" ion-text>Sign In</a>
                </div>

            </div>
        </form>
    </div>
</ion-content>

Here is my ts file

import {Component} from '@angular/core';
import {FormBuilder, Validators} from '@angular/forms';
import {NavController, AlertController, NavParams} from 'ionic-angular';
import { Camera } from 'ionic-native';

// Provider
import { BasicService } from '../../providers/basic-service';
import { UserData } from '../../providers/user-data';

// Page
import { LoginPage } from '../login/login';
import { DashboardPage } from '../dashboard/dashboard';
import { ProaccountPage } from '../proaccount/proaccount';

@Component({
    selector: 'page-signup',
    templateUrl: 'signup.html'
})
export class SignupPage {
    signupForm;
    formData;
    public base64Image: string = 'assets/icon/user-icon1.png';
    public upload_image = 1;
    public form_image = '';

    constructor(public navCtrl: NavController, public builder:FormBuilder, public alertCtrl:AlertController, public bs:BasicService, private navParams: NavParams, public userData: UserData) {
        this.formData = navParams.get('data');
        if(this.formData != undefined) {
            this.base64Image = this.formData.picture.data.url;
            this.form_image = this.formData.picture.data.url;
            this.upload_image = 0;
            this.signupForm = builder.group({
                'first_name': [this.formData.first_name, Validators.compose([Validators.required, Validators.pattern('[^ ][a-zA-Z ]*')])],
                'last_name': [this.formData.last_name, Validators.compose([Validators.required, Validators.pattern('[^ ][a-zA-Z ]*')])],
                'phone': ['', Validators.compose([Validators.required, Validators.pattern('[0-9]*')])],
                'address': ['', Validators.compose([Validators.required])],
                'email': [this.formData.email, Validators.compose([Validators.required, Validators.pattern('([a-zA-Z0-9_.]{1}[a-zA-Z0-9_.]*)((@[a-zA-Z]{2}[a-zA-Z]*)[\\\.]([a-zA-Z]{2}|[a-zA-Z]{3}))([\\\.]([a-zA-Z]{2}|[a-zA-Z]{3}))?')])],
                'paypal_email': [this.formData.paypal_email, Validators.compose([Validators.required, Validators.pattern('([a-zA-Z0-9_.]{1}[a-zA-Z0-9_.]*)((@[a-zA-Z]{2}[a-zA-Z]*)[\\\.]([a-zA-Z]{2}|[a-zA-Z]{3}))([\\\.]([a-zA-Z]{2}|[a-zA-Z]{3}))?')])],
                'password': ['', Validators.compose([Validators.required, Validators.minLength(8), Validators.maxLength(20)])],
                'type': [0]
            })
        } else {
            this.signupForm = builder.group({
                'first_name': ['', Validators.compose([Validators.required, Validators.pattern('[^ ][a-zA-Z ]*')])],
                'last_name': ['', Validators.compose([Validators.required, Validators.pattern('[^ ][a-zA-Z ]*')])],
                'phone': ['', Validators.compose([Validators.required, Validators.pattern('[0-9]*')])],
                'address': ['', Validators.compose([Validators.required])],
                'email': ['', Validators.compose([Validators.required, Validators.pattern('([a-zA-Z0-9_.]{1}[a-zA-Z0-9_.]*)((@[a-zA-Z]{2}[a-zA-Z]*)[\\\.]([a-zA-Z]{2}|[a-zA-Z]{3}))([\\\.]([a-zA-Z]{2}|[a-zA-Z]{3}))?')])],
                'paypal_email': ['', Validators.compose([Validators.required, Validators.pattern('([a-zA-Z0-9_.]{1}[a-zA-Z0-9_.]*)((@[a-zA-Z]{2}[a-zA-Z]*)[\\\.]([a-zA-Z]{2}|[a-zA-Z]{3}))([\\\.]([a-zA-Z]{2}|[a-zA-Z]{3}))?')])],
                'password': ['', Validators.compose([Validators.required, Validators.minLength(8), Validators.maxLength(20)])],
                'type': [0]
            })
        }
    }

    login() {
        if(this.navCtrl.getPrevious(this.navCtrl.getActive()).name == 'LoginPage') {
            this.navCtrl.pop();
        } else {
            this.navCtrl.push(LoginPage, {});
        }
    }

    formSubmit() {
        // this.navCtrl.push(ProaccountPage);
        var validation_message = {
            'first_name': {
                'required': 'First Name is required field.',
                'pattern': 'First Name contain alphabets & word spacing.'
            },
            'last_name': {
                'required': 'Last Name is required field.',
                'pattern': 'Last Name contain alphabets & word spacing.'
            },
            'phone': {
                'required': 'Phone is required field.',
                'pattern': 'Phone contain only numeric value.'
            },
            'address': {
                'required': 'Address is required field.'
            },
            'email': {
                'required': 'Email is required field.',
                'pattern': 'Please enter valid email.',
                'checkEmail': 'Email already exist.'
            },
            'paypal_email': {
                'required': 'Paypal Email is required field.',
                'pattern': 'Please enter valid Paypal Email.',
            },
            'password': {
                'required': 'Password is required field.',
                'minlength': 'Password length must be between 8 to 20.',
                'maxlength': 'Password length must be between 8 to 20.'
            }
        }
        if (this.bs.validation(this.signupForm, validation_message)) {
            this.bs.hitApi('check_email', 'POST', {'email': this.signupForm.value.email})
                .subscribe(emailChecked => {
                    if(emailChecked.replyCode == 'success') {

                        if(this.formData != undefined) {
                            let submitData = this.signupForm.value;
                            submitData.fbid = this.formData.id;
                            submitData.picture = this.form_image;
                            submitData.upload_image = this.upload_image;
                            submitData.register = 1;
                            submitData.device_type = this.bs.deviceType;
                            submitData.udid = this.userData.device_token;
                            if(submitData.type) {
                                this.navCtrl.push(ProaccountPage, {data: submitData});
                            } else {
                                this.bs.hitApi('fblogin', 'POST', submitData)
                                    .subscribe(user => {
                                        user.data.password = submitData.password;
                                        this.userData.login(user.data);
                                        this.navCtrl.setRoot(DashboardPage);
                                        // this.navCtrl.setRoot(LoginPage);
                                    }, err => {
                                        console.log(err);
                                    })
                            }
                        } else {
                            let submitData = this.signupForm.value;
                            submitData.picture = this.form_image;
                            submitData.device_type = this.bs.deviceType;
                            submitData.udid = this.userData.device_token;
                            if(submitData.type) {
                                this.navCtrl.push(ProaccountPage, {data: submitData});
                            } else {
                                this.bs.hitApi('sign_up', 'POST', submitData)
                                    .subscribe(user => {
                                        console.log(user);
                                        user.data.password = submitData.password;
                                        this.userData.login(user.data);
                                        this.navCtrl.setRoot(DashboardPage);
                                        // this.navCtrl.setRoot(LoginPage);
                                    }, err => {
                                        console.log(err);
                                    })
                            }
                        }
                    } else {
                        this.bs.showAlert(emailChecked.replyMsg);
                    }
                }, err => {
                    console.log(err);
                });
        }
    }

    takePicture() {
        this.bs.showLoader();
        Camera.getPicture({
            destinationType: Camera.DestinationType.DATA_URL,
            sourceType: Camera.PictureSourceType.SAVEDPHOTOALBUM,
            targetWidth: 500,
            targetHeight: 500,
            quality: 100
        }).then((imageData) => {
            this.bs.hideLoader();
            this.upload_image = 1;
            this.form_image = imageData;
            this.base64Image = "data:image/jpeg;base64," + imageData;
        }, (err) => {
            this.bs.hideLoader();
            console.log(err);
        });
    }
}

Now when a alert pop up is shown
after that click on ok button behind alert textarea is focused

**Comment by jgw96** [comment] 2017-01-25 19:31
Hello all! This issue was fixed in RC.5. Because of this I am going to be closing this issue for now.

**Closed by jgw96** 2017-01-25 19:31 UTC
Labels: needs reply, v2
