### ISSUE TITLE
bug: ion-option-button does not work with touch on Windows 10

### ISSUE THREAD

**Issue by raymens** [driftyco/ionic#4911] opened 2016-01-06 13:01 UTC
They display fine when using Android (emulators) but I can't slide the list items using a W10M phone.
So far I know W10M doesn't use any slide-to-execute-an-action anyway, so maybe it's better to change this to: long-click open sliding menu at location for Windows?

Using ionic 1.2.1.

**Update:**
So it seems it works using a mouse but not using touch. Related forum link (not started by me): https://forum.ionicframework.com/t/ion-option-button-not-working-on-windows-10-touchscreen-mouse-works/39892

**Comment by jgw96** [comment] 2016-03-14 18:34
Hello! Thanks for opening an issue with us, we just need a little more info from you so that we can better help you with your issue. Would you mind posting a code sample, plunkr or codepen that we can use to reproduce your issue? Also, would you mind running `ionic info` and posting the output? Thanks again!

**Comment by jgw96** [comment] 2016-05-09 21:51
Hello! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-05-09 21:51 UTC
Labels: platform:windows, v1

**Comment by SatyaG7** [comment] 2017-12-11 08:36
ion-option-button does not work with touch on Windows 10 but its work with mouse click.
 
ordova CLI: 7.0.0
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
OS: Windows 10
Node Version: v6.11.5

I was changed getCenter function in ionic.bundle.js but no use. Thanks!!
@raymens is it work??
