### ISSUE TITLE
Ionic 2, Blank screen on Android 4.4.2

### ISSUE THREAD

**Issue by nicksmithr** [driftyco/ionic#10756] opened 2017-03-13 11:45 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Everything runs in the console, but white screen on app launch.

**Expected behavior:**

It is expected not to have a white screen..

**Steps to reproduce:**

Run any project with Ionic@latest on Android 4.4.2. No plunker is necessary because it seems to occur with any project.

**Related code:**
```

    "@angular/common": "2.4.8",
    "@angular/compiler": "2.4.8",
    "@angular/compiler-cli": "2.4.8",
    "@angular/core": "2.4.8",
    "@angular/forms": "2.4.8",
    "@angular/http": "2.4.8",
    "@angular/platform-browser": "2.4.8",
    "@angular/platform-browser-dynamic": "2.4.8",
    "@angular/platform-server": "2.4.8",
    "@ionic/cloud-angular": "^0.11.0",
    "@ionic/storage": "^2.0.0",
    "angularfire2": "^2.0.0-beta.8",
    "firebase": "^3.7.1",
    "ionic-angular": "2.2.0",
    "ionic-native": "^2.4.1",
    "ionicons": "3.0.0",
    "rxjs": "5.0.1",
    "sw-toolbox": "3.4.0",
    "zone.js": "0.7.2"

cordova platform android 6.1


Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```

Cordova CLI: 6.5.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.0
ios-sim version: 5.0.8
OS: macOS Sierra
Node Version: v7.2.0```

**Comment by chandanch** [comment] 2017-03-14 04:35
Can you try installing the [Conference app](https://github.com/driftyco/ionic-conference-app) and run it android device with 4.4.2.

If the problem still persist install [crosswalk](https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview).  

For more information refer to this thread on [forum](https://forum.ionicframework.com/t/ionic2-app-show-blank-screen-on-android-device-4-2-2-using-run-command-and-ionicview/39405).

or this: https://github.com/driftyco/ionic/issues/6281

**Comment by jgw96** [comment] 2017-03-15 13:56
Hello, thanks for opening an issue with us. Closing this as a duplicate of https://github.com/driftyco/ionic/issues/6281.

**Closed by jgw96** 2017-03-15 13:56 UTC

**Comment by PremkumarAgrawal** [comment] 2018-05-17 09:53
Hello All there at IONIC Forum,

I have resolved the issue by using the below link [https://ionic.zone/debug/remote-debug-your-app#android](https://ionic.zone/debug/remote-debug-your-app#android)
and debugging the app as mentioned in it.

Thanks for your support.

**Comment by tamiryan** [comment] 2018-05-28 09:10
#PremkumarAgrawa can you please let me know how you solved this issue? Thanks in advance.
