### ISSUE TITLE
Range input do no clear input focus before -- Keyboard is brought up

### ISSUE THREAD

**Issue by apavillet** [driftyco/ionic#2854] opened 2015-01-04 22:37 UTC
On a phone if you focus an input and then a range the keyboard shows up and the input is still focused.

Tested and verified on Android

**Comment by Ionitron** [comment] 2015-01-05 13:09
Greetings, @apavillet!

My sensors indicate that more information is required so that I may assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- What platform does this happen on? (iOS, Android, all, etc.)
- What platform versions does this happen on? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework, or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) which replicates the issue is extremely helpful.

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com).

Thank you for allowing me to assist you.

**Comment by apavillet** [comment] 2015-01-05 14:37
Replication : focus an input text, the keyboard shows up. Use a range then the keyboard still shows and the input is focused.

This happens on Android ( 4.4 at least ), did not test on iOs.
Please note this does not happens on browser but only in app

**Comment by jgw96** [comment] 2016-04-29 16:42
Hello @apavillet Thanks for opening an issue with us! Are you still having this issue with the latest version of ionic 1? 1.3.0?

**Comment by jgw96** [comment] 2016-05-04 15:06
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-05-04 15:06 UTC
Labels: needs reply, tap/click, v1
