### ISSUE TITLE
Virtual Scroll only rendering 4 items after rendering empty list

### ISSUE THREAD

**Issue by corran2go** [driftyco/ionic#10237] opened 2017-01-30 08:30 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X ] **2.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I'm using a virtualScroll to display items which can be filtered. After the filter has returned an empty list the next attempt to render all items results in only 4 items to be rendered and added to the DOM.

**Expected behavior:**
Clearing a filtered virtualScroll list should always render all items.

**Steps to reproduce:**
I've debugged the issue and traced it to this line of code
https://github.com/driftyco/ionic/blob/master/src/components/virtual-scroll/virtual-util.ts#L78

stopAtHeight is 0 so the function returns after processedTotal reaches 4 which skips all other items in the collection

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.9.4
Xcode version: Not installed
```

**Comment by jgw96** [comment] 2017-01-30 16:03
Hello, thanks for using Ionic! We will look into this issue.

**Comment by mtycholaz** [comment] 2017-01-31 21:00
@corran2go Out of curiosity, what was your debugging process to find this issue? Stepped through the un-minified code I assume?

**Comment by jgw96** [comment] 2017-01-31 22:00
Hello everyone! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/9722. Thanks for using Ionic!

**Closed by jgw96** 2017-01-31 22:00 UTC
Labels: v2, virtualscroll

**Comment by corran2go** [comment] 2017-02-03 08:12
@jgw96 this might be related but in my case there is no way to display more than 4 items even when scrolling down. The height of the list is set correctly but additional items are added to the DOM when scrolling.

**Comment by corran2go** [comment] 2017-02-03 08:15
@mtycholaz right, just ```ionic serve``` and then choose the source file in DEV tools under **node_modules/ionic-angluar** and set your breakpoint

**Comment by JamesLeeTrigg** [comment] 2017-02-03 14:29
having the same problem

**Comment by andrewsduarte3** [comment] 2018-08-17 14:42
This post at ionic forum may help you guys
 https://forum.ionicframework.com/t/ionic-2-virtualscroll-items-overlapping-on-first-render/89230/11 (Daveshirman answer)
I tried this out and works fine, but don't give me the performance that I was expecting... I'll try something else
