### ISSUE TITLE
bug: iOS search bar caret position bug

### ISSUE THREAD

**Issue by ThorConzales** [driftyco/ionic#10202] opened 2017-01-27 08:17 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.0.0 final</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>10.2</span>  <span ionic-webview>webview</span>

<span ionic-description>Sometimes when you type into a search bar and do some additional things such as pop a new screen and return to the screen where search bar is and tap on search bar again then the caret position will be set to beginning of the word rather than the end even if you tap on the tail of the word in position wise. I don't have a proper way to reproduce it since it seems to be random so far and it works properly on Android.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment] 2017-01-27 08:22
Hello! Unfortunately there is not much we can do for an issue that has no repro case, would you be able to post more info and a repo we can use to reproduce this issue? Also, does this happen on a normal input on a plain webpage on that iOS device, or only with our searchbar component?

**Comment by jgw96** [comment] 2017-01-30 20:42
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-01-30 20:42 UTC
Labels: needs reply, v2
