### ISSUE TITLE
Ionic Serve Issue

### ISSUE THREAD

**Issue by eholland7080** [driftyco/ionic#9365] opened 2016-11-26 15:35 UTC
When I run ionic serve --lab my project loads and opens fine in my browser but I receive the following in my terminal:

Erics-MacBook-Pro:chit-demo ericholland$ ionic serve --lab

ionic-hello-world@ ionic:serve /Users/ericholland/Documents/work/development/mobile/hybrid/ionic/chit-demo
ionic-app-scripts serve "--lab"
[08:16:52] ionic-app-scripts 0.0.45
[08:16:52] watch started ...
[08:16:52] build dev started ...
[08:16:52] clean started ...
[08:16:52] clean finished in 4 ms
[08:16:52] copy started ...
[08:16:52] transpile started ...
[08:16:55] transpile finished in 2.19 s
[08:16:55] webpack started ...
[08:16:55] copy finished in 2.37 s
[08:16:59] webpack finished in 4.44 s
[08:16:59] sass started ...
[08:17:00] sass finished in 1.10 s
[08:17:00] build dev finished in 7.75 s
[08:17:00] watch ready in 7.78 s
[08:17:00] dev server running: http://localhost:8100/

express deprecated res.sendfile: Use res.sendFile instead node_modules/@ionic/app-scripts/dist/dev-server/http-server.js:26:20

Environment
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.9.0
ios-sim version: 5.0.11
OS: macOS Sierra
Node Version: v6.1.0
Xcode version: Xcode 8.1 Build version 8B62

Contents of ~/.ionic/ionic.config
{
"ank": "bf9665da-c317-4a36-9d8a-990c6b902d43",
"accountPrompt": "y"
}

Scripts section of package.json
"scripts": {
"ionic:build": "ionic-app-scripts build",
"ionic:serve": "ionic-app-scripts serve"
},

Thanks everyone
Eric

**Comment by jgw96** [comment] 2016-11-28 17:12
Hello, thanks for opening an issue with us! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic-app-scripts/issues/478.

**Closed by jgw96** 2016-11-28 17:12 UTC

**Comment by eholland7080** [comment] 2016-11-28 17:20
Thanks jgw96
