### ISSUE TITLE
bug: keyboard-attach broken when connect/disconnect iPhone

### ISSUE THREAD

**Issue by JonathanAquino** [driftyco/ionic#2242] opened 2014-09-19 05:33 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>ion-footer-bar (with keyboard-attach) in a modal disappears when you connect your iPhone to your computer's USB, then appears at the top of the screen when you disconnect your iPhone from your computer's USB. See screenshots mentioned below.

To repro:
1. Create a blank Ionic starter project.
2. In index.html, make the body the following:

    <script>
      angular.module('starter')
      .run(function ($rootScope, $ionicModal) {
        $ionicModal.fromTemplateUrl('modal.html', {
          scope: $rootScope
        }).then(function (modal) {
          modal.show();
        });
      });
    </script>

3. Create a file called modal.html with the following:

```
<ion-modal-view>
  <ion-header-bar>
    <h1 class="title">Hello, world!</h1>
  </ion-header-bar>
  <ion-content>
    <textarea>This is the textarea.</textarea>
  </ion-content>
  <ion-footer-bar keyboard-attach>
    <a class="button button-clear">
      <i class="icon ion-location"></i>
    </a>
  </ion-footer-bar>
</ion-modal-view>
```

4. With your iPhone disconnected from your computer's USB, click the textarea to show the keyboard.
 See screenshot: http://monosnap.com/image/lhqfndWn8A0NwTmpwyY02hMzQOaB3f

5. Connect your iPhone to your computer's USB.
// Expected: The ion-footer-bar does not disappear.
// Actual: The ion-footer-bar does disappear.
See screenshot: http://monosnap.com/image/SsxRqOOeGFGl9a9Kw4BuvGLaEVVInT

6. Disconnect your iPhone from your computer's USB.
// Expected: The ion-footer-bar does not appear in a strange location.
// Actual: The ion-footer-bar appears at the top of the screen.
See screenshot: http://monosnap.com/image/PZ9XQmWg5zVHA1Z6dm4sgr8Eh4UNnu</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-01-19 01:24
Greetings, @JonathanAquino!

My sensors indicate that this issue has been inactive for a while.
Due to this, the issue will be closed in 7 days.

If you believe the issue has not been fixed, please add a comment.
This will notify us so we can assist you, and will prevent the issue from being automatically closed.
Feel free to include the following information about the issue, so that we may assist you:

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- What platform does this happen on? (iOS, Android, all, etc.)
- What platform versions does this happen on? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework, or Ionic CLI?

Thank you for allowing me to assist you.

**Comment by tlancina** [comment] 2015-04-13 18:24
Yeah this is a tricky one, it seems that when the in-call or connection status bar appears, the native UIView will automatically resize.  So if the keyboard is up, the view will shrink and elements with 100% height (like the modal) will be shrunk as well.  The problem is, I can't think of a good way to detect this without a plugin observing didChangeStatusBarFrame.

**Comment by jgw96** [comment] 2016-04-29 16:35
Hello all! I am going to be closing this issue as it has been a while since there was any activity on it. If anyone is opposed feel free to comment/reopen. Thanks for using ionic!

**Closed by jgw96** 2016-04-29 16:35 UTC
Labels: keyboard, platform:ios, v1
