### ISSUE TITLE
bug: ion-label breaks page when in sub ngFor iteration

### ISSUE THREAD

**Issue by milesholt** [driftyco/ionic#5605] opened 2016-02-25 12:16 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>After looking at various examples and reading through the documentation, it appears, after a series of tests, as though this could be a bug.

Similar to the documentation, if I write this:

```
<ion-list>
   <ion-item *ngFor="#item of items">
           <ion-label>item.label</ion-label>
           <ion-input type="text" [(ngModel)]="item.value"></ion-input>
   </ion-item>
</ion-list>
```

This works fine, but if another nested iteration is required, such as:

```
<ion-list>
      <ion-item *ngFor="#item of items">
       
            Item {{ item.id }}

            <ion-list>
                  <ion-item *ngFor="#detail of item.details">
                        <ion-label>detail.label</ion-label>
                        <ion-input type="text" [(ngModel)]="detail.value"></ion-input>  
                  </ion-item>  
           </ion-list>
  
     </ion-item>
</ion-list>
```

then the list just appears as a series of blank list items, with no content. Inspecting the HTML confirms that there is no data present.

However, if I remove just the 'ion-label' element, then the list appears correctly. 

So it seems as though the 'ion-label' element is causing the page to break, but only when placed within a nested iteration.

Thanks</span>

<span is-issue-template></span>

**Comment by jgw96** [comment] 2016-03-11 22:08
Thanks for submitting this issue and thanks for the code samples! Would you mind running `ionic info` and pasting the output here?

**Comment by jgw96** [comment] 2016-03-21 16:50
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!

**Comment by milesholt** [comment] 2016-04-07 11:18
Hi, sorry for the late response! 
 
Here is the info. I've updated to the latest version of Ionic 2 Beta but still seeing the issue -

Cordova CLI: 6.1.1
Ionic Framework Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
ios-deploy version: 1.8.5 
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v0.12.2
Xcode version: Xcode 7.0.1 Build version 7A1001

**Comment by milesholt** [comment] 2016-04-07 11:26
It appears I'm not allowed to reopen this issue, so could this be reopened by yourselves? Thanks

**Comment by adamdbradley** [comment] 2016-06-28 21:44
Because you're placing ion-labels within an ion-list that's nested within an ion-item, the top most ion-item is correctly pulling out the ion-label for content projection on the top level ion-item. I would recommend no nesting an ion-list within another ion-item when using an ngFor like this. Sorry for not having a better answer, but I believe this would be expected behavior for Angular 2.

**Closed by adamdbradley** 2016-06-28 21:44 UTC
Labels: list, v2

**Comment by EazyAndy** [comment] 2017-09-27 04:08
Having a nested list within a list seems like a reasonably routine requirement. Whats the best way to achieve this? I have a list showing activities, and each of those has a varying number of steps. I need to show a lable and checkbox for each of those steps. How to show the label with this current projection bug?
