### ISSUE TITLE
bug: closeMenu directive affect the next view even when the view dosen't need to change

### ISSUE THREAD

**Issue by sharvit** [driftyco/ionic#4145] opened 2015-07-25 07:14 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi :)

The first very problematic use-case is when the SideMenu contain a link to the current view.
At this use-case the SideMenu will close and the view will not change.
BUT!!
After i click on a link inside my current view, it make the next view as a RootView and i don't have a back button.

This bug will happen for all elements that contain MenuClose and not change the next view.
``` html
<ion-side-menu side="left">
  <ion-content>
    <ion-list>
      <!-- Close the menu but the next view (whatever it will be) going to be to RootView -->
      <ion-item menu-close>
        Close The Menu
      </ion-item>
      <!-- Close the menu but the next view (whatever it will be) going to be to RootView -->
      <ion-item  menu-close href="#/current-view">
        Link to my current view
      </ion-item>
      <!-- The only use-case it will work well -->
      <ion-item menu-close href="#/another-view">
        Work Well
      </ion-item>
    </ion-list>
  </ion-content>
</ion-side-menu>
```

The problem is here:
https://github.com/driftyco/ionic/blob/master/js/angular/directive/menuClose.js#L1

Need to check that the view are actually going to change before setting the next view as the root view.

Thank you for this amazing platform :+1: </span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-07-25 07:14
Greetings @sharvit!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4145). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4145)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by stan-kondrat** [comment] 2015-07-27 12:12
same https://github.com/driftyco/ionic/issues/4038

**Comment by mhartington** [comment] 2015-07-29 16:40
Closing as a duplicate of #4132

**Closed by mhartington** 2015-07-29 16:40 UTC
