### ISSUE TITLE
ion-refresher doesn't work with virtualScroll and shows empty screen

### ISSUE THREAD

**Issue by naveedahmed1** [driftyco/ionic#11600] opened 2017-05-10 20:07 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
ion-refresher doesn't work with virtualScroll, when we pull down to refresh, and call complete, it clears the screen and doesn't show anything. 

**Expected behavior:**
It should't update the list with new contents.

**Comment by jgw96** [comment] 2017-05-11 13:57
Hello, thanks for opening an issue with us. I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/9765

**Closed by jgw96** 2017-05-11 13:57 UTC

**Comment by naveedahmed1** [comment] 2017-05-11 14:04
Just to add, if I explicitly set my list to an empty array before updating it it works.
