### ISSUE TITLE
Page reload endlessly when opening Chrome DevTools

### ISSUE THREAD

**Issue by bgadiel** [driftyco/ionic#7589] opened 2016-08-07 16:31 UTC
Hi,
I installed _sidemenu_ starter template.
When I run 'ionic serve' and open Chrome WebTools - the page reloads endlessly with error on the console:
_Uncaught TypeError: Cannot convert undefined or null to object: inspector.js_

**Steps to reproduce:**
1. `ionic start myApp sidemenu`
2. `ionic serve`
3. Open Chrome DevTools

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Your system information:

You have been opted out of telemetry. To change this, run: cordova telemetry on.

6.3.0

Gulp version:  CLI version 3.9.1
Gulp local:
Ionic CLI Version: 1.7.16
Ionic App Lib Version: 0.7.3
OS: Windows 7 SP1
Node Version: v4.4.7

**Comment by jgw96** [comment] 2016-08-09 17:14
Hello! Thanks for opening an issue with us! Unfortunately i cannot reproduce this issue at the moment. It looks as if this may be an issue caused by an error with one of your dependencies. Since this does not seem to be an issue with the framework i will be closing this issue for now, but i will be on the lookout for this bug and will happily reopen if i see it. Thanks for using Ionic!

**Closed by jgw96** 2016-08-09 17:14 UTC
Labels: menus, v2

**Comment by bgadiel** [comment] 2016-08-09 17:19
I just figured this out:
It is caused by one of my Chrome Angular extensions I have installed.
Once I removed it, it works perfectly.

Thanks.

בתאריך 9 באוג׳ 2016 8:15 אחה״צ,‏ "Justin Willis" <notifications@github.com>
כתב:
