### ISSUE TITLE
How to use nav options in ionic 2.I need to use flip animation when i push another page into my nav controller.How can this be achieved in ionic 2.Any example please.

### ISSUE THREAD

**Issue by rhuldip** [driftyco/ionic#7719] opened 2016-08-14 19:51 UTC
**Note: If you are having problems formatting your issue please refer to this article on using markdown in Github:**

https://guides.github.com/features/mastering-markdown/

**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### What behavior are you expecting?

**Steps to reproduce:**
1. 
2. 
3. 

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x

#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

**For Ionic 2 issues** - http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by joshgarwood** [comment] 2016-08-15 02:20
Hi @rhuldip , I believe this question would be better suited for the ionic forums: https://forum.ionicframework.com

Github Issues are meant to be filed as bugs for the Ionic team to fix, rather than help/suggestions on actually using the framework.  I think you'll get more responses if you post in the forums.

**Comment by danbucholtz** [comment] 2016-08-15 04:38
Thanks @joshgarwood 😄 , you're correct.

Since this is not a bug in the framework, we are going to close this issue.  Please take any requests for help to our [community help forum](https://forum.ionicframework.com/?utm_source=framework&utm_medium=navbar&utm_campaign=forum%20CTA).  Stackoverflow is also great!

Please let me know if you have any questions.

Thanks,
Dan

**Closed by danbucholtz** 2016-08-15 04:38 UTC
Labels: animation, v2
