### ISSUE TITLE
Sass compiler issue while starting ionic2-app-base project. CSS not generated

### ISSUE THREAD

**Issue by dheran** [driftyco/ionic#6260] opened 2016-04-21 06:55 UTC
**Ionic 2**

Same issue happening in existing projects with updated node modules.

Error message:
>  ? node_modules\ionic-angular\components.core.scss
Error: Import directives may not be used within control directives or mixins.
        on line 34 of node_modules/ionic-angular/components.core.scss
>>   @import "fonts/ionicons";
   --^

**Comment by zMADCATz** [comment] 2016-04-21 08:06
#6258

**Comment by zMADCATz** [comment] 2016-04-21 08:08
Ref #6258

**Comment by vinothyada** [comment] 2016-04-21 08:38
same error for me , not yet resolved tell me some solution for this

**Comment by entomb** [comment] 2016-04-21 10:29
Same problem. apparently `ionic-gulp-sass-build` is using `gulp-sass@^2.2.0` and version `2.3.0` introduced this breaking change.

according to the node-sass team, its not a bug but a misuse of the sass language
more info here: https://github.com/dlmanning/gulp-sass/issues/470 and https://github.com/sass/node-sass/issues/1459

**Comment by jgw96** [comment] 2016-04-21 14:39
Hey guys! Thanks for opening an issue with us. Im gonna close this issue as a duplicate of #6258.

**Closed by jgw96** 2016-04-21 14:39 UTC
Labels: v2
