### ISSUE TITLE
when pull to refresh, ionic recognizes any click as another pull to refresh 

### ISSUE THREAD

**Issue by HassanBK** [driftyco/ionic#8244] opened 2016-09-28 08:01 UTC
The scenario as the following:

- do pull to refresh

- click on any clickable item

- the application will call pull to refresh one more time and it will call the click function also.

The scenario works on ios not android.

**Comment by HassanBK** [comment] 2016-09-29 06:26
@jgw96  this is not related to v2, it's related to v1.|

**Comment by yazantahhan** [comment] 2016-09-29 06:53
Same issue happens here.
I found same of [https://github.com/driftyco/ionic/issues/3874](this issue) that is closed before 1 year ago.
I updated @FMCorz link provided with latest ionic version 1.3.1 and still occurs.
You can check it [http://play.ionic.io/app/e96b1e95b135](here).
Thank you.

**Comment by jgw96** [comment] 2016-10-04 16:53
Hello @HassanBK ! Thanks for using Ionic! Most likely this is caused by js scrolling being turned on in iOS. Can you try [turning js scrolling off](http://ionicframework.com/docs/api/provider/$ionicConfigProvider/) and trying again? Thanks!

**Comment by jgw96** [comment] 2016-10-07 13:41
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-10-07 13:41 UTC
Labels: needs reply, platform:ios, v1
