### ISSUE TITLE
bug: Input range => Frozen slider on Internet Explorer 11 

### ISSUE THREAD

**Issue by kyro38** [driftyco/ionic#3853] opened 2015-05-28 13:47 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Here is a demo : http://codepen.io/anon/pen/OPdJRq </span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-05-28 13:47
Greetings @kyro38!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3853). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3853)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment] 2015-05-29 17:18
Hmm, it works on a touch screen, so this maybe related to touch/pointer events

**Comment by bitflower** [comment] 2015-07-27 09:12
It also works with the keyboard cursor keys (after selecting the range with the mouse)

**Comment by bitflower** [comment] 2015-07-27 10:52
It works in IE11 when we remove the e.preventDefault(); inside tapMouseDown (talking ionic.bundle.js).

The question is if this is better targetted with IE 11 in mind or with type=range in mind. If I understand correctly this function handles the focus of text fields and the keyboard being shown. So we could exclude the type=range here similiar to the select|option exclude in the if:

    if ((!ionic.tap.isTextInput(e.target) || tapLastTouchTarget !== e.target) && !(/^(select|option)$/i).test(e.target.tagName)) {
          e.preventDefault();
    }

**Comment by mhartington** [comment] 2015-07-27 20:37
I'm going to let @perrygovier Take a look at this. He's been working scrolling/touch events so he'd know best

**Comment by anubhavgupta** [comment] 2015-08-24 12:10
I am also facing the same issue with range input on IE 11.
For the time being the only solution seams to be is to set element.contentEditable = true for the range input element.

**Comment by 5im0n** [comment] 2015-12-04 09:44
The problem is also present in Edge :persevere:
Before waiting for the 1.2 milestone, the workaround of @anubhavgupta works great

```html
<div class="item range">
  <i class="icon ion-volume-low"></i>
  <input type="range" name="volume" contenteditable="true">
  <i class="icon ion-volume-high"></i>
</div>
```

**Comment by mlynch** [comment] 2015-12-08 05:22
Okay, a few discoveries: First, we can't preventDefault in `tapMouseDown` if it's a range (at least on IE). However, range styles are totally borked in Edge, so that needs to be fixed as well.

**Comment by mlynch** [comment] 2015-12-08 05:35
Should be fixed now, and range styles were fixed. Thanks!

**Closed** 2015-12-08 05:35 UTC
Labels: platform:windows, wp8

**Comment by cmellinas** [comment] 2015-12-18 18:02
Hi @mlynch,

When you say : 'we can't preventDefault in tapMouseDown if it's a range (at least on IE). '

I used the following workaround : https://forum.ionicframework.com/t/range-slider-not-movable-in-internet-explorer/19592/4

The fix was to only add && e.target.type !== 'range' at the end of the if condition 

It's weird but the range works well on my computer on IE10 & IE11 only with this condition (even if I don't understand why the method isTextInput is bypassed by IE)
