### ISSUE TITLE
bug: NavPush Constructs @Page each Time. NeverDestroyed

### ISSUE THREAD

**Issue by Barryrowe** [driftyco/ionic#5507] opened 2016-02-18 16:30 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When an @Page component is navigated too via a NavController.push or .setRoot, a new Instance of the component is created (it's constructor() fires).  However, when the page is navigated away from, it is never destroyed (onPageWillUnload and onPageDidUnload never fire). The next time you navigate to the same type of component, another new instance is created, rather than re-using the instance that has never been disposed.

If the intention is that a new instance should be created each time, it needs to be disposed properly, or there is a memory leak issue.

If the intention is that a single instance should be created and re-used when the type is navigated too, then this is currently broken.</span>

<span is-issue-template></span>

**Comment by Barryrowe** [comment] 2016-02-18 16:31
This was confirmed in alpha.54 and beta.0

**Comment by Barryrowe** [comment] 2016-02-18 16:41
It appears this might just be onPageWillUnload/onPageDidUnload not firing.  If I add the OnDestroy ng2 hook, and implement ngOnDestroy, that does get called.

**Comment by adamdbradley** [comment] 2016-02-18 16:44
The onPageWillUnload/DidUnload is probably a bug and I'll look into it. However, if you got to Page1, then push to Page2, then **push** to Page1 again, it will create a new instance of Page1, and this is by design and similar to how native apps works. If you want to use the same instance then you would pop back to the first instance of Page1.

As for the lifecycles i'll take a look, thanks for the report.

**Comment by Barryrowe** [comment] 2016-02-18 16:50
Thanks, that makes sense. It does look like it's just not firing the Unload events.

For anyone running into this that needs the "Will/DidUnload" hooks, you can do the following instead for now:

```Javascript
import {OnDestroy} from "angular2/core";

@Page(...)
export class MyPage{
//...
  ngOnDestroy(){
   //do your unload logic here (unsubscribe from streams, etc.)
  }
}
```

**Comment by adamdbradley** [comment] 2016-02-18 17:06
Should be fixed in the next release, thanks!

**Closed by adamdbradley** 2016-02-18 17:06 UTC
Labels: v2
