### ISSUE TITLE
Scrolling issue in Ionic 2 Starter Tutorial template

### ISSUE THREAD

**Issue by JacksonKearl** [driftyco/ionic#7669] opened 2016-08-11 17:18 UTC
#### Short description of the problem:

The ion-content in the side menu in the ionic2-starter-tutorial does not properly scroll on Safari or Android 4.4.4. It does work properly on Chrome. 

If you add a `overflow-y: auto` to the `ion-content`, then in Safari dev tools disable then enable it, scrolling works properly. But, this only works if you manually add the style via dev tools after load. Adding the style in code does nothing. 
#### What behavior are you expecting?

Normal Scrolling

**Steps to reproduce:**
1. clone https://github.com/JacksonKearl/ionic-2-testing, which is the same as https://github.com/driftyco/ionic2-starter-tutorial but with more items in the side menu. 
2. ionic serve 
3. open side menu, items will not be scrollable until adding the aforementioned `overflow-y: auto`

**Which Ionic Version?**  2.x
#### Plunker that shows an example of your issue

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.3.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.36
Ionic App Lib Version: 2.0.0-beta.19
ios-deploy version: 1.8.4
ios-sim version: 5.0.1
OS: Mac OS X El Capitan
Node Version: v6.3.1
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment] 2016-12-29 21:32
Hello, thanks for using Ionic! I cannot reproduce this with our latest release. Because of this I am going to close this issue for now, thanks!

**Closed by jgw96** 2016-12-29 21:32 UTC
Labels: menus, needs:devicetesting, platform:ios, v2
