### ISSUE TITLE
Collection-repeat image recycling while loading

### ISSUE THREAD

**Issue by udfalkso** [driftyco/ionic#1742] opened 2014-07-07 16:31 UTC
I've noticed that while scrolling, if the image to be displayed has not yet downloaded, the user will be shown the last image that existed in that recycled node's "spot" until the new one loads.

It's misleading behavior and can be a bit confusing for the user. More preferable would be for later items to somehow be reset to initial conditions so the user sees an empty container while the image loads.

I've set up this codepen which reproduces the problem:
http://codepen.io/udfalkso/pen/aojet5

You'll have to throttle your internet connection somehow to consistently see the issue in action. Either on a mobile device without wifi or with SpeedLimit.prefPane. Scroll down quickly and you'll see that the images from up-top are repeated for some time until the new images load on top of them.

I hope this was clear. Any solutions? Thanks!

**Comment by jfitz0** [comment] 2015-01-24 23:56
Also have this same issue.
Would be a really nice addition to this feature to be able to clear the iamge src or set a loader image when the element gets cloned and inserted into the dom.

**Comment by ajoslin** [comment] 2015-02-09 16:21
I'm going to try to implement something similar to @dhcar's solution.

**Comment by ajoslin** [comment] 2015-02-09 23:00
So I found a way that works: every time we change an item's data, we refresh its images by simply removing the image from the dom and adding it back.

When the element is instantiated:

![screen shot 2015-02-09 at 3 59 33 pm](https://cloud.githubusercontent.com/assets/1265995/6117810/b1a5ee04-b074-11e4-9f41-56f6aa5d509f.png)

Then we refresh its images whenever the data changes: 

![screen shot 2015-02-09 at 4 00 10 pm](https://cloud.githubusercontent.com/assets/1265995/6117816/c076ffe0-b074-11e4-9cf3-6a5f7bb37e3b.png)

We should definitely not always do this. How does an attribute called `force-refresh-images="true"` sound?

**Comment by jfitz0** [comment] 2015-02-10 05:26
An attribute called force-refresh-images="true" sounds good!

**Comment by dhcar** [comment] 2015-02-10 16:06
force-refresh-images="true" has my blessing!

**Comment by ajoslin** [comment] 2015-02-10 16:44
Could you guys test this out? There are now two new attributes: collection-buffer-size and collection-refresh-images.

Read the nightly docs for an explanation: http://ionicframework.com/docs/nightly/api/directive/collectionRepeat

**Comment by ajoslin** [comment] 2015-02-10 16:45
Additionally, doing this revealed an opportunity for some huge optimizations to collection-repeat! Those are comings oon.

**Comment by asterism612** [comment] 2015-02-10 23:26
nice~!
work fine.
i love you ajoslin :)

**Comment by anwaramoon** [comment] 2015-03-30 20:02
I have also noticed another issue that if new item does not have an image url than collection repeat directive does not remove old image and it keep the old image. For instance, in below example if few items in the collection do not have imageUrl defined than collection repeat does not remove old image.

 <img  ng-src="{{album.imageUrl }}" />

I will try to create a codepen for this.

**Comment by JerryBels** [comment] 2015-05-14 10:40
Hey guys, don't know if it's implemented in RC5, but it doesn't seems to work for me.

	<ion-list>
		<ion-item class="photoListItem" collection-repeat="media in mediasData | filter:filterNew | filter:filterAlbum | orderBy:'date_creation' : true track by date_creation" item-width="imageDimensions + 5" item-height="imageDimensions + 5" force-refresh-images="true">
			<img ng-src="{{media.$mediaUrl}}" ui-sref="app.photo({mediaId : media.$id})">
		</ion-item>
	</ion-list>

Any idea why ?

**Comment by JerryBels** [comment] 2015-05-18 11:50
Bump

**Comment by JerryBels** [comment] 2015-05-20 09:03
Bump

**Comment by perrygovier** [comment] 2015-05-20 22:44
@JerryBels, are you seeing this still a problem in 1.0?

**Comment by JerryBels** [comment] 2015-05-21 11:41
@perrygovier yes, still occurs with 1.0.0. I recorded it in video for you to see : 

https://www.youtube.com/watch?v=0ZaeD2nlKoA

No comments about the photos of our office :p 

The CDN delivering the photos is very fast so you see the bug very slightly but it's even more pronounced when running on a bad 3G connection.

**Comment by JerryBels** [comment] 2015-05-26 09:07
@perrygovier anything else I can do to help track down the issue ?

**Comment by RobbinHabermehl** [comment] 2015-05-26 14:02
I can confirm the existence of this problem in v1.0.0.

Unfortunately that's not all as I've encountered a lot of difficulties combining `collectionRepeat` with my custom caching directive. In short, this directive downloads an image to the file system and then sets the path to this image as `src` attribute. The problem is that the first item gets copied by `collectionRepeat` before the linking phase, i.e. the caching, completes. Therefore the `src` attribute never gets set, leaving the first image blank.

There's no easy way to resolve this due to the isolated nature of `collectionRepeat`. For now I've created a workaround by watching the first item of a collection with a directive, once it changes it applies the `src` manually:

```
angular.module('app').directive('collectionRepeatFirstImageFix', function($compile, $timeout) {
  return {
    link: function(scope, iElement) {
      var renderImage = function() {
        var firstImage = iElement[0].querySelector('[collection-repeat] img');
        if (!firstImage || !window.cordova) {
          return;
        }
        // Put logic here
        firstImage.onerror = function() {
          firstImage.src = '';
          $timeout(renderImage, 100);
        };
        firstImage.src = 'file:///path/to/image.jpg';
      };
      scope.$watch(function() {
        return scope.collection && scope.collection[0] ? scope.collection[0]._id : null;
      }, function() {
        $timeout(renderImage);
      });
    },
    scope: {
      collection: '=collectionRepeatFirstImageFix'
    }
  };
});
```

HTML:

```
<ion-list collection-repeat-first-image-fix="images">
  <ion-item
    collection-repeat="image in images"
    force-refresh-images="true">
    <img cache-src="{{ image.url }}">
  </ion-item>
</ion-list>
```

**Comment by Ionitron** [comment] 2015-06-20 08:29
Greetings @udfalkso!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-06-20 08:29 UTC
Labels: ionitron:closed

**Comment by JerryBels** [comment] 2015-06-21 11:56
@Ionitron @perrygovier as you can see with the last comments, the issue is still here... Do I need to open a new issue and reference this one in it or can you reopen this ?

**Comment by Yuripetusko** [comment] 2015-07-06 09:47
force-refresh-images doesn't work for me

**Comment by valiantvu** [comment] 2015-08-31 22:21
I am also still seeing duplicated images with force-refresh-images. Did anyone else figure out a workaround?

**Comment by mhartington** [comment] 2015-08-31 22:23
Please provide a codepen exmaple in a new issue.

**Comment by alireza-nouri** [comment] 2015-09-30 15:12
Its not working!
None of these solutions.

**Comment by marfago** [comment] 2015-10-31 09:44
Same issue for me.

**Comment by yianpuodiaotu** [comment] 2016-02-25 12:01
Tks all, @ajoslin's method resolved my problem.

**Comment by miparnisari** [comment] 2016-06-08 16:53
I'm having a similar issue in which the first time I open the view the images are not shown. If I scroll down and then up again the images are shown. What could be the issue? 

```
<div class="list" ng-controller="ctrl">
            <div class="item item-avatar" collection-repeat="contact in contacts | orderBy: title" ng-click="selectContact(contact)">
              <ion-item>
                <custom-avatar from="contact"></custom-avatar>
                <h2>{{contact.title}}</h2>
                <p>{{contact.subtitle}}</p>
              </ion-item>
            </div>
          </div>
```

**Comment by jdnichollsc** [comment] 2017-05-08 21:40
same issue for here
