### ISSUE TITLE
feat: ion-select should auto-scroll

### ISSUE THREAD

**Issue by lannierose** [driftyco/ionic#8688] opened 2016-10-13 22:14 UTC
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I put this on the forum here: https://forum.ionicframework.com/t/ion-select-as-alert-should-auto-scroll-to-selection/66473?u=lannie  
but I guess I should file it as an issue so ...

I have an ion-select with more options than can be viewed at once in the alert box, so it scrolls, which is fine. But it seems to me that the currently selected option should be visible when the alert pops up, in other words, it should auto-scroll to reveal the checked option.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment] 2016-10-14 14:57
Hello, thanks for using Ionic! I am going to close this as a duplicate of https://github.com/driftyco/ionic/issues/6356.

**Closed by jgw96** 2016-10-14 14:57 UTC
