### ISSUE TITLE
Popover disappears in landscape mode

### ISSUE THREAD

**Issue by szuzul** [driftyco/ionic#2355] opened 2014-10-07 15:44 UTC
Ionic pop over doesn't show up in landscape mode properly on android 4.1.2.  On 4.0, 4.4.2 and Ios 7 works fine. It behaves like the top header is still on the position where it was in portrait mode.. see the images:
![portrait](https://cloud.githubusercontent.com/assets/1090963/4545138/a7fbcf48-4e38-11e4-96e9-598241d8b3da.jpg)
![landscape](https://cloud.githubusercontent.com/assets/1090963/4545148/b1f9a358-4e38-11e4-8e3f-a0d31f40c94d.jpg)

Code

 $ionicPopover.fromTemplateUrl('templates/popover.html', {
            scope: $scope
        }).then(function (popover) {
            $scope.popover = popover;
        });
        $scope.openPopover = function ($event) {
            $scope.popover.show($event);
        };
        $scope.closePopover = function () {
            $scope.popover.hide();
        };
        //Cleanup the popover when we're done with it!
        $scope.$on('$destroy', function () {
            $scope.popover.remove();
        });
        // Execute action on hide popover
        $scope.$on('popover.hidden', function () {
            // Execute action
        });
        // Execute action on remove popover
        $scope.$on('popover.removed', function () {
            // Execute action
        });
 
         <ion-popover-view>
            <ion-header-bar>
                <h1 class="title">My Popover Title</h1>
            </ion-header-bar>
            <ion-content>
                Hello!
            </ion-content>
        </ion-popover-view> 

      
        <ion-view>
         <ion-nav-buttons side="left">
           <button ng-click="openPopover($event)" class="button button-icon icon ion-plane"></button>
        </ion-nav-buttons>
       </ion-view>

**Comment by mhartington** [comment] 2015-02-04 17:18
@szuzul any luck on that codepen? I wasn't able to reproduce this issue with the nightly builds and without this PR https://github.com/driftyco/ionic/pull/2647

**Comment by Ionitron** [comment] 2015-02-25 03:23
Greetings @szuzul!

I've closed this issue because my sensors indicated that perhaps it is no longer applicable--or may have already been fixed. However, if you are still experiencing this issue, please feel free to reopen it by creating a new one, and provide the following information, so that I may assist you:

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this issue occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) which replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com). The humans there would be delighted to help you.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-02-25 03:23 UTC
Labels: android, ionitron:closed, popover
