### ISSUE TITLE
Ionic2 tabs: after click on tab with (ionSelect) previous tab get lost

### ISSUE THREAD

**Issue by arsenslyusarchuk** [driftyco/ionic#7582] opened 2016-08-07 08:22 UTC
#### Short description of the problem:
Hello. I'm using tabs for navigation in my app. Currently I have 2 tabs - "Receipts" with list of items and "More".
Last tab "More" should open ActionSheet with some actions like "Logout", "About" etc.
To do this, I'm using (ionSelect) event on this tab.
After dismissing ActionSheet, "Receipts" page becomes unresponsive. By that I mean that user can still do all actions (edit item name, delete, etc), but they won't display on UI - every item will remain the same (with same name or won't disappear after delete)

Looks like technically, Ionic switches you to tab even if it has  (ionSelect) event instead of usual navigation. I found that because when clicking "More" ionViewDidLeave event is fired on "Receipts" page

```
<ion-tabs #myTabs class="nav-tabs" preloadTabs="false" >
  <ion-tab tabIcon="list-box" tabTitle="Receipts" [root]="receiptsRoot"></ion-tab>
  <!-- <ion-tab tabIcon="more" tabTitle="More" [root]="menuRoot"></ion-tab> -->
  <ion-tab tabIcon="more" tabTitle="More" (ionSelect)="showMenu()"></ion-tab>
</ion-tabs>
```

Your system information:

Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v4.4.7

**Comment by jgw96** [comment] 2016-08-18 18:37
closing this one as a duplicate of https://github.com/driftyco/ionic/issues/7769

**Closed by jgw96** 2016-08-18 18:37 UTC
Labels: v2
