### ISSUE TITLE
Loading on dismissOnPageChange: true

### ISSUE THREAD

**Issue by rafaelss95** [driftyco/ionic#8517] opened 2016-10-05 19:31 UTC
I'm using Loading and I have the following code:

```
let loading = this.loadingCtrl.create({
    content: 'Loading page...',
    dismissOnPageChange: true
  });

  loading.present().then(() => {
    modal.present();
  });

```

In beta.11 the above code works really fine and now after migrated to rc.0, the loading isn't dismissing on page change.

Thanks in advance.

**Comment by rafaelss95** [comment] 2016-10-13 22:25
Hello, any news on this issue? I just updated my app to RC.1 and, unfortunately, it still doesn't work :(

**Comment by manucorporat** [comment] 2016-10-13 22:34
Please, can you provide a full source code so I can reproduce?

**Comment by rafaelss95** [comment] 2016-10-13 22:42
Well, it's a simple page that I'm passing an `object` to a modal page. The code is the following:

**MainPage.ts**

```
openModal(obj?: any): void {
  let modal = this.modalCtrl.create(ModalPage, {
    param: obj
  });
  let loading = this.loadingCtrl.create({
    content: 'Loading',
    dismissOnPageChange: true
  });

  loading.present().then(() => {
    modal.present();
  });

  modal.onDidDismiss(data => {
    ...
  });
}
```

**ModalPage.ts**

```
constructor(
  public navParams: NavParams,
  public viewCtrl: ViewController) {
  let param = this.navParams.get('param');
  ...
}

onDismiss(data?: any): void {
    this.viewCtrl.dismiss(data);
}
```

**Comment by jgw96** [comment] 2016-10-31 21:36
Hello @rafaelss95, is this still an issue with the latest version of Ionic ?

**Comment by rafaelss95** [comment] 2016-11-01 01:56
Hello @jgw96, well I don't know if it's an issue or an expected behavior, as I mentioned in my previous comment. It just happens in modal. So my question is, the `dismissOnPageChange` should work when you call a **modal** also? If yes, so there's an issue, if no, it's ok.

**Comment by jgw96** [comment] 2017-02-06 19:31
Hello all, closing this for now. We have discussed this internally and have decided that since modals are not really a navigation change that `dismissOnPageChange` should not work with modals. Thanks for using Ionic!

**Closed by jgw96** 2017-02-06 19:31 UTC
Labels: needs reply, v2
