### ISSUE TITLE
Storage: TypeError: Cannot read property 'db' of null

### ISSUE THREAD

**Issue by feifeiwoye** [driftyco/ionic#8279] opened 2016-09-29 04:08 UTC
version:rc0

**Comment by ramonornela** [comment] 2016-09-29 11:29
Related #8269

**Comment by jgw96** [comment] 2016-09-29 14:28
Hello, thanks for using Ionic! I am going to be closing this issue as a duplicate of #8269.

**Closed by jgw96** 2016-09-29 14:28 UTC
