### ISSUE TITLE
Update of www/assets folder

### ISSUE THREAD

**Issue by hadrien-toma** [driftyco/ionic#8925] opened 2016-10-27 09:01 UTC
#### Short description of the problem:
It seems that the built assets folder (www/assets) is not updated from the source folder (src/assets) when building.

#### What behavior are you expecting?
I would like to have the assets folder updated. For the moment, to have it working I have to do:
```
rm -rf ./www/assets/html
ionic serve
```

**Which Ionic Version?** 2.0.0-rc.1

**Comment by zyxins** [comment] 2016-10-27 09:14
+1

**Comment by oborudko** [comment] 2016-10-27 10:04
+1

**Comment by ghenry22** [comment] 2016-10-27 11:51
Also noticed this one with rc1

**Comment by EugeneNews** [comment] 2016-10-27 13:09
+1

**Comment by jgw96** [comment] 2016-10-27 18:19
Hello, thanks for opening an issue with us! I am going to close this as a duplicate of https://github.com/driftyco/ionic-cli/issues/1599.

**Closed by jgw96** 2016-10-27 18:19 UTC
