### ISSUE TITLE
bug: View caching and getElementById

### ISSUE THREAD

**Issue by craig-at-rsg** [driftyco/ionic#3670] opened 2015-05-06 13:58 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>I'm using Google javascript maps in my Ionic app, and they stopped working when I upgraded to 1.0RC5 from an earlier 1.0 beta. When I turn off caching for this view then the maps work again, but I'd like to use caching.  

I'm using REST style URLs in my app, so the link for my page with the map looks like '#/page/{{item.id}}'. With caching on, the maps load fine on the first of these pages I open, and they continue to work if I reopen the page with that id, but they have an empty div instead of a map for pages with other ids. 

I can see my map-creation function completes without error in both cases. Here's the bit in my controller that I assume is at issue:
    map = new google.maps.Map(document.getElementById("map"), mapOptions)

Is the div returned by this getElementById call not the one being shown? Or is something else going on?

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-05-06 13:58
Greetings @craig-at-rsg!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3670). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3670)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment] 2015-05-07 20:30
Greetings @craig-at-rsg!

My sensors indicate that I require more information in order to assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this happen occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com), where many humans will be able to offer wisdom and advice.

Thank you for allowing me to assist you.

<span ionitron-needs-reply></span>

**Comment by craig-at-rsg** [comment] 2015-05-08 14:22
This sample shows the bug on both android and ios, just click back and forth between the links. The console will log that the text in the div is being replaced, but it won't be replaced for the 2nd link.

```
angular.module('starter', ['ionic'])
    .config(function ($stateProvider) {
        $stateProvider
            .state('page', {
                url: '/page/:param',
                template: "<div id='container'>Text not replaced</div><a href='#/page/cached'>Works</a><br /><a href='#/page/other'>Doesn't</a>",
                controller: 'PageController'
            });
    })
.controller('PageController', ['$scope', function ($scope) {
	   $scope.$on('$ionicView.enter', function() {
           console.log('Replacing text');
        document.getElementById("container").textContent = 'Text replaced';
           console.log('Replaced text');
       });
    }])
.run(['$state', '$ionicPlatform', function($state, $ionicPlatform) {
  $ionicPlatform.ready(function() {
      $state.go('page', {param: 'cached'});
  });
}]);
```

**Comment by perrygovier** [comment] 2015-05-08 16:25
You want to get the element of the active page. With cached views, getElementById will always yield inconsistent results because other pages still exist in the DOM (they're just hidden). Try this selector instead.

`document.querySelector('[nav-view="active"] #map')`

If you're still having trouble, this is better a discussion for the forums than an issue with Ionic.

**Closed by perrygovier** 2015-05-08 16:25 UTC
