### ISSUE TITLE
ion-slides loop with dynamic content doesn't behave correctly

### ISSUE THREAD

**Issue by MariusWiik** [driftyco/ionic#11138] opened 2017-04-09 13:15 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X ] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When initialSlide is set to 1, the first slide presented is 2 (the second slide). So I guess initialSlide counts from 0, but getActiveIndex() counts from 1.

With three slides and loop="true" you can still slide to slide 0 or slide 4 and get a blank slide. Sliding again will give make the slider skip a slide:
Slide 3 -> Slide 4 (blank) -> Slide 2 (skipped 1).
The same will happen the other way. 

**Expected behavior:**
The loop should go like 1->2->3->1->etc, OR 0->1->2->0 depending on how you count. 

**Steps to reproduce:**

Create blank project and create three slides with images which are bound to a variable. 
See plunkr: http://plnkr.co/edit/RezOKP2Rb01hMB60KbM8?p=preview

However, not binding the sources to a variable will make the slides work as they should:
http://plnkr.co/edit/r6L91UqQ3jQbSL12NDUD?p=preview
But it still shows the wrong indexes in getActiveIndex

**Other information:**

```
Cordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.0
ios-sim version: 5.0.10
OS: macOS Sierra
Node Version: v7.7.4
Xcode version: Xcode 8.3 Build version 8E162
```

**Comment by jgw96** [comment] 2017-04-10 15:18
Hello, thanks for using Ionic! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/10784.

**Closed by jgw96** 2017-04-10 15:18 UTC
