### ISSUE TITLE
ion-slides  zoom="true" DOES not zooming image

### ISSUE THREAD

**Issue by bimal72** [driftyco/ionic#10107] opened 2017-01-20 05:15 UTC
If I write simple code like ..
```
<ion-slides  (ionSlideDidChange)="onImageChanged()"   zoom="true"   pager="false" loop="false" initialSlide="initialSlide">
    <ion-slide *ngFor="let message of imageMessages">            
     <img   [hidden]="hideSlides" [src]="message.image" class="slide-image"/>
    </ion-slide>
</ion-slides>
```
it does not zoom the image at all...

but if I write (wrap image in swiper-zoom-container div)
```
<ion-slides  (ionSlideDidChange)="onImageChanged()"  zoom="true"    pager="false" loop="false" initialSlide="initialSlide">
    <ion-slide *ngFor="let message of imageMessages">
        <div class="swiper-zoom-container"><img   [hidden]="hideSlides" [src]="message.image" class="slide-image"/></div>
    </ion-slide>
</ion-slides>
```
It seems working but somehow it throes an error ...
```
 Unable to preventDefault inside passive event listener invocation.
```
and hence it again back to original size immediately when I lift my fingers

**Comment by mhartington** [comment] 2017-01-20 15:38
Duplicate of #5039

**Closed by mhartington** 2017-01-20 15:38 UTC
Labels: v2
