### ISSUE TITLE
Screen flash when showing popup in iOS 10

### ISSUE THREAD

**Issue by tuongaz** [driftyco/ionic#8050] opened 2016-09-12 06:25 UTC
### Short description of the problem:
It seems that there's a white screen appears before a popup showing. Here's the Conference app running on iOS 10.

[https://cl.ly/2E2b1b1o2u2O](https://cl.ly/2E2b1b1o2u2O)

#### What behavior are you expecting?
There shouldn't any white screen.

**Steps to reproduce:**
1. Install the Conference app on iOS 10.
2. Go to the About page.
3. Select the Location

**Which Ionic Version?** 1.x or 2.x
2.x

**Comment by jwenzler** [comment] 2016-09-28 04:50
I am also seeing this issue.  It happens on popover and action sheet so far that I have noticed. It's quite jarring for the users.

**Comment by jgw96** [comment] 2016-09-28 16:12
Hello, thanks for using Ionic! I am happy to report that I can no longer reproduce this issue with rc.0. Because of this I will be closing this issue for now.

**Closed by jgw96** 2016-09-28 16:12 UTC
Labels: alert, platform:ios, v2
