### ISSUE TITLE
navCtrl pop animation bug

### ISSUE THREAD

**Issue by mariopacio** [driftyco/ionic#10116] opened 2017-01-20 19:47 UTC
**Ionic version:**  (check one with "x")
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

Hi all, i found these error (not working):

```
this.navCtrl.push(Page, {}, {
   direction: 'back',
   animation: 'ios-transition',
});
```
this.navCtrl.push == animation **WORKING**

```
this.navCtrl.pop({
   animate: true,
   direction: 'back',
   animation: 'ios-transition',
});
```
this.navCtrl.pop == animation **NOT WORKING**

Mário Pácio
Brazil

**Comment by mhartington** [comment] 2017-01-20 20:45
Can you throw together a plunkr of this. The issue template has a link to a plunkr where you should recreate the issue.

http://plnkr.co/edit/z0DzVL?p=preview

**Comment by olixis** [comment] 2017-01-22 06:09
Same as #10097 ??? Ir esse closed

**Comment by mhartington** [comment] 2017-01-23 15:56
I'm not able to replicate using RC5 stable.

![nav-pop](https://cloud.githubusercontent.com/assets/2835826/22211132/1cb087a0-e15a-11e6-8ad4-9e75f052d65a.gif)


![nav-pop-2](https://cloud.githubusercontent.com/assets/2835826/22211213/5afd8fda-e15a-11e6-8aa7-82c064129e7a.gif)


One gif show just setting the navOptions on nav.pop, and the other sets nav.push and nav.pop.
In both examples, the animation are behaving as expected.

**Comment by jgw96** [comment] 2017-01-25 19:23
@olixis would you mind trying this with [2.0 stable](https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#200-2017-01-25) ? I also cannot reproduce this issue.

**Comment by olixis** [comment] 2017-01-25 23:06
@jgw96 , going to try it with 2.0 final and report back

**Comment by mhartington** [comment] 2017-01-26 14:10
I have not been able to reproduce with both 2.0 stable, or rc5

**Comment by jgw96** [comment] 2017-01-30 20:44
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-01-30 20:44 UTC
Labels: needs reply, v2
