### ISSUE TITLE
Ionic Css issue with galaxy s3 android 4.3

### ISSUE THREAD

**Issue by abunour22** [driftyco/ionic#8931] opened 2016-10-27 15:38 UTC
#### Short description of the problem:

I have issue with galaxy s3 android 4.3 with css
and also i can not debug my app with inspect with chrome developer tools
Its showing device but not the app !!
so what is missing ?!

#### What behavior are you expecting?
![screenshot_2016-10-27-18-34-28](https://cloud.githubusercontent.com/assets/5248013/19774037/682ed6a8-9c74-11e6-97f8-ffd42791e3d2.png)

#### What result in Samsung Galaxy S3 4.3?
![0a0f0ca3-55fe-4e67-8363-817ef704840b](https://cloud.githubusercontent.com/assets/5248013/19772611/7353fec8-9c6f-11e6-996f-1f394bd6428c.jpg)

**Which Ionic Version?** 1.x or 2.x
v2

**Comment by jgw96** [comment] 2016-10-27 18:42
Hello, thanks for using Ionic! Could you post the markup and css for your bottom toolbar?

**Comment by abunour22** [comment] 2016-10-27 19:06
**Sure, i'm using ion-footer-bar inside ion-side-menu-content**

```
<ion-side-menu-content drag-content="false">
        <ion-nav-bar class="bar-positive" align-title="center">
            <ion-nav-buttons side="left">
                <button class="button button-icon button-clear ion-navicon" menu-toggle="left"> </button>
        </ion-nav-bar>
        <ion-nav-view name="menuContent"></ion-nav-view>
        <ion-footer-bar class="bar-stable bar bar-footer fixed-menu-bar disable-user-behavior" ng-hide="keyboardOpen" ng-hide="hideTabs" align-title="center">
            <div class="bar bar-footer fixed-menu-bar bar-dark">
                <button class="button icon ion-home"></button>
                <button class="button icon ion-search"></button>
                <button class="button bar-cadet  icon ion-location"></button>
                <button data-icon="D">
                    <i id="cartCount" class="badge badge-light header-badge"></i>
                </button>
                <button class="button icon ion-person"></button>
            </div>
        </ion-footer-bar>
</ion-side-menu-content>
```

**This is CSS**

```

.bar {
    display: -webkit-box;
    display: -webkit-flex;
    display: -moz-box;
    display: -moz-flex;
    display: -ms-flexbox;
    display: flex;
    -webkit-transform: translate3d(0, 0, 0);
    transform: translate3d(0, 0, 0);
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    position: absolute;
    right: 0;
    left: 0;
    z-index: 9;
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
    padding: 5px;
    width: 100%;
    height: 50px;
    border-width: 0;
    border-style: solid;
    border-top: 1px solid transparent;
    border-bottom: 1px solid #ddd;
    background-color: white;
    /* border-width: 1px will actually create 2 device pixels on retina */
    /* this nifty trick sets an actual 1px border on hi-res displays */
    background-size: 0;
}

.bar .button,
.bar button {
    z-index: 1;
    padding: 0 8px;
    min-width: initial;
    min-height: 31px;
    font-weight: 400;
    *font-size: 13px;
    font-size: 15px;
    line-height: 32px;
}

.bar.fixed-menu-bar {
    height: 50px;
    padding: 0;
}

.bar.fixed-menu-bar .button {
    width: 20%;
    border-radius: 0;
}

ion-footer-bar .header-badge {
    top: 8px !important;
    left: 37px !important;
    padding: 0px 5px;
    font-size: 0.7em;
    line-height: 15px;
}

.bar-footer {
    bottom: 0;
    border-top-width: 1px;
    border-bottom-width: 0;
    background-position: top;
    height: 50px;
}

```

**Comment by jgw96** [comment] 2016-10-27 19:09
Hmm, after review this looks to be caused by flexbox. The webview on Android 4.3 includes the old version of the flexbox syntax which did not include all the functionality of the new version of flexbox. Do you have an Android device running a newer version of Android? If so does it work on that device?

**Comment by abunour22** [comment] 2016-10-27 19:13
Yes it's working and the screenshot of what i expecting to see is running on Galaxy Note 2 Version 4.4

So what i can do to makes it run on the old version ?!

**Comment by jgw96** [comment] 2016-10-27 19:16
I would recommend using crosswalk so that the Android 4.3 device will be running a new stock Chrome based webview (like Android devices running 5.0 and up). Be aware though that Crosswalk does make your apk larger as it includes the webview in the apk itself. I am going to close this issue for now as crosswalk will solve this issue. Thanks!

**Closed by jgw96** 2016-10-27 19:16 UTC
Labels: needs reply, v2
