### ISSUE TITLE
checkboxes in virtualScroll-list

### ISSUE THREAD

**Issue by robinhesse** [driftyco/ionic#9904] opened 2017-01-07 01:06 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When using virtualScroll for a list of ion-checkbox the checkbox is not active after click.
One has to scroll a little bit to make it active.

**Expected behavior:**
The checkbox should be active on click, immediately.

**Steps to reproduce:**
Build a virtualScroll-list of checkboxes with more elements than the display contains(maybe it reproduces also with less elements) and click them.

**Related code:**
<ion-list [virtualScroll]="datapointsList2">
  <ion-item *virtualItem="let item">
     <ion-label>{{item.DPNAME}}</ion-label>
     <ion-checkbox [(ngModel)]="checkItems[item.DPNAME]"></ion-checkbox>
    </ion-item>
  </ion-list>

**Other information:**
I think there is a problem with rendering.

**Comment by mhartington** [comment] 2017-01-09 15:13
Duplicate of https://github.com/driftyco/ionic/issues/9856

**Closed by mhartington** 2017-01-09 15:13 UTC
