### ISSUE TITLE
Feature request: Support Content.scrollToBottom()

### ISSUE THREAD

**Issue by ceefour** [driftyco/ionic#5907] opened 2016-03-22 19:44 UTC
#### Short description of the problem:

`Content.scrollToBottom()` is needed

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

People want this: https://forum.ionicframework.com/t/ionic2-scroll-bottom/45041
 
**Which Ionic Version?**

2.x

**Comment by brandyscarney** [comment] 2016-03-23 17:55
Thanks for the issue! I am going to close this as a duplicate of #5810 since that issue is asking for the same thing. :smile:

**Closed by brandyscarney** 2016-03-23 17:55 UTC
Labels: feature, v2

**Comment by lisaiceland** [comment] 2017-04-17 16:32
Hi:
This is NOT working on current build. Any ideas? Plz help. Thnx.
