### ISSUE TITLE
Click a tab again when it's active and on the root page, the root page is reloaded without passing rootParams

### ISSUE THREAD

**Issue by shawnlan** [driftyco/ionic#11127] opened 2017-04-07 22:18 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request

If you set up `rootParams` for a tab like the following:

`<ion-tabs>
 <ion-tab [root]="chatRoot" [rootParams]="chatParams" tabTitle="Chat" tabIcon="chat"></ion-tab>
</ion-tabs>`

When the tab is active and is on the root page, clicking the tab will reload the root page, but `rootParams` isn't passed. Thus the page isn't showing correctly.

**Comment by youssmak** [comment] 2017-04-08 21:49
This is related to https://github.com/driftyco/ionic/issues/11123 and https://github.com/driftyco/ionic/issues/11015

**Comment by jgw96** [comment] 2017-04-12 14:18
Hello all! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/11015. Thanks for using Ionic.

**Closed by jgw96** 2017-04-12 14:18 UTC
