### ISSUE TITLE
bug: Missing navbar and statusbar on iOS PLUS devices

### ISSUE THREAD

**Issue by Duffycola** [driftyco/ionic#4509] opened 2015-10-13 11:23 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>browser</span>

<span ionic-description>I have just checked out the latest nightly build  v1.1.0-nightly-1583 (cce78aa0cc) and noticed that the navigation bar is completely missing on PLUS devices. The issue does not affect regular devices (6, 6S).

The problem is reproducible using the default template:

ionic start myApp
cd myApp
bower install driftyco/ionic-bower#master
ionic build ios
open platforms/ios/myApp.xcodeproj
=> Emulate on 6 PLUS or 6S PLUS</span>

<span is-issue-template></span>

**Comment by Duffycola** [comment] 2015-10-13 11:26
<img width="487" alt="screen shot 2015-10-13 at 12 23 53" src="https://cloud.githubusercontent.com/assets/1650328/10453595/5b20778c-71a5-11e5-9fc9-de3b056fbab0.png">
<img width="733" alt="screen shot 2015-10-13 at 12 24 06" src="https://cloud.githubusercontent.com/assets/1650328/10453596/5b220958-71a5-11e5-8db6-fed218144d1b.png">

**Comment by perrygovier** [comment] 2015-10-23 14:14
Hey @Duffycola, does using the nightly build help? 
http://code.ionicframework.com/nightly/js/ionic.bundle.js

**Comment by Duffycola** [comment] 2015-10-23 21:37
Hi Perry, thanks for the reply.
Nope, I tested it using the v1.1.0-nightly-1583 build. It appears that the "nightly" build is 29 days old (see also https://github.com/driftyco/ionic-bower) ;-)
If there's a different location where I could get a bundle of a more recent version (say master branch or ios9-patch branch) I could give you more feedback.
Cheers,
Ed

**Comment by mhartington** [comment] 2015-10-27 19:11
Gave this a try on ios 6 plus and 6S plus using the latest bits, all looked well. The only thing that could be an the issue is the default zoom on the ios simulator. @Duffycola could you try pressing `cmd-3` when the simulator is running?

**Comment by Duffycola** [comment] 2015-10-27 20:51
@mhartington: Oh yeah, I pressed cmd-3 and cmd-2 and everything was fine. I then scaled back to original and realised that you can actually scroll up and see the status bar. So indeed it is just the fact that the iOS plus display height is larger than the available screen of my retina macbook and thus the simulator gets scaled down. Sorry for the confusion. How lame!

**Comment by mhartington** [comment] 2015-10-27 21:00
All good :+1: 

Closing

**Closed by mhartington** 2015-10-27 21:00 UTC
Labels: iOS
