### ISSUE TITLE
Refresher components visible ontop of the content!

### ISSUE THREAD

**Issue by digaus** [driftyco/ionic#10688] opened 2017-03-08 08:04 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Refresher components are visible ontop of the content on pull down.

**Expected behavior:**

Refresher components should only be fully visible when pulled down completely.

**Steps to reproduce:**

1. Install latest nighly version
2. Start project
3. Place refresher component

**Related code:**

```
insert any relevant code here
```

**Other information:**
![Screenshot](https://cloud.githubusercontent.com/assets/15358538/23695150/11c5741c-03de-11e7-8250-4266568118bd.png)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
ordova CLI: 6.5.0
Ionic Framework Version: 2.1.0-201703061537
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.3
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.10.0
Xcode version: Not installed

```

**Comment by jgw96** [comment] 2017-03-08 17:25
Thanks for opening an issue with us. Unless im not understanding the issue correctly, this is how refresher has always worked. Is the behavior different when you do not use nightly in your app?

**Comment by digaus** [comment] 2017-03-08 17:34
The orange line is the beginning of the content. Normaly the text of the refresher is behind the content and only visible when you pull down far enough ... here the text is visible even when it is behind the content. Normal behaviour can be seen in the refresher V2 docs

**Comment by jgw96** [comment] 2017-03-16 14:48
Hmm interesting, unfortunately i cant reproduce this in my test app. Would you mind sharing a repo or plunker that reproduces the issue? Thanks

**Comment by tmvnk** [comment] 2017-03-16 17:46
Had the same issue on a specific page. Solved this by adding 
    z-index: 99999;
    background-color: white;

**Comment by jgw96** [comment] 2017-03-30 17:01
Hello all! As it seems it has been a while since there was any activity on this issue and we can unfortunately not reproduce this on our end, i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-03-30 17:01 UTC
Labels: needs info, v2
