### ISSUE TITLE
Keyboard Height (iOS Safari iPad - no cordova) 

### ISSUE THREAD

**Issue by mrjasonroy** [driftyco/ionic#6255] opened 2016-04-20 22:07 UTC
#### Short description of the problem:
Keyboard is jumping and covering the inputs in version 1.2.4 (and others). It works the first time the keyboard opens, but, covers number 2 and beyond.

#### What behavior are you expecting?

The keyboard should not cover.

**Steps to reproduce:**
1. Place code in ionic view
2. Keyboard height registers as 206, covers elements. Looks like this is set for the iPhone, not the iPad.

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

It seems like changing this line of code  
This fixes it, iPads are a bit different.
```
  if (ionic.Platform.isIOS()) {
    if (ionic.keyboard.isLandscape) {
      if(ionic.Platform.isIPad()) {
        return 395;
      }
      return 206;
    }
    if (!ionic.Platform.isWebView()) {
      return 216;
    }
    return 260;
  }
```
**Which Ionic Version?** 1.x or 2.x

1.2.4

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: Not installed
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Version: 1.2.4
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v4.2.6
Xcode version: Xcode 7.2.1 Build version 7C1002

**Comment by jgw96** [comment] 2016-04-21 05:42
Hey! Sorry your still having this issue! Would you be able to make a plunker of your code that i can use to reproduce this issue? Thanks!

**Comment by jgw96** [comment] 2016-04-26 14:49
Hello! As it has been a little while since there was any activity on this issue I will be closing it. Thanks for using ionic!

**Closed by jgw96** 2016-04-26 14:49 UTC
Labels: keyboard, needs reply, platform:ios, v1
