### ISSUE TITLE
[feature request] exposeWhenAside for sidemenu

### ISSUE THREAD

**Issue by okonon** [driftyco/ionic#10197] opened 2017-01-26 21:28 UTC
**Ionic version:** 
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...** 
[ ] bug report
[ x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Currently if Ionic2 WPA app sidemenu on widescreen is collapsed. 

**Expected behavior:**

When Ionic2 WPA with sidemenu is served on wide screens the menu should be configurable to be always shown (this feature existed on Ionic1 `exposeAsideWhen`

**Comment by jgw96** [comment] 2017-01-27 15:44
Hello, thanks for using Ionic! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/6793.

**Closed by jgw96** 2017-01-27 15:44 UTC
Labels: feature, platform: desktop/tablet, v2

**Comment by okonon** [comment] 2017-01-27 17:31
@jgw96 are they same features? 
i am confused why would Max say this than in #6793 
> mlynch commented on Oct 5, 2016
This isn't a side menu feature, it's part of the NavController where previous pages are rendered in a menu style side-by-side.
