### ISSUE TITLE
bug: Ionic Css 1.2.4 Issue

### ISSUE THREAD

**Issue by AnkB** [driftyco/ionic#5107] opened 2016-01-20 18:32 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi, I am updating my ionic css from from 1.0 to 1.2.4 and as a result of that my app shows a blank screen. Any idea why its happing. Thanks</span>

<span is-issue-template></span>

**Comment by mhartington** [comment] 2016-01-20 18:36
Are there any errors in the console logs? We need more information.

**Comment by AnkB** [comment] 2016-01-20 19:09
There is no such error mentioning css not found. It just not blank screen, but I noticed that my default controller is being called each time. As I mentioned  if I use css version v1.0.0-beta.1 its working fine. above that I tired 1.2.4, 1.2.3, 1.1.1 all showing blank screen.

**Comment by AnkB** [comment] 2016-01-20 22:25
One solution I have found to include both css of different version. But there might be an right solution for this.

**Comment by mhartington** [comment] 2016-01-20 22:27
Beta1  is really old, a lots changed since then.

Have you checked the change log and updated your app?

Does it work in the browser?

**Comment by AnkB** [comment] 2016-01-21 14:53
Actually I was not aware of the version when started the my project. I got the sample project from the Material Design from the ionic market. This version come with that package. 
Browser also showing white blank screen.

**Comment by mhartington** [comment] 2016-01-21 15:26
Can you please provide a demo or some example that reproduces the issue. I still need more information than "there's a blank screen"

**Comment by devilankur18** [comment] 2016-01-29 02:50
I am also getting a blank screen after upgrading to ionic 1.2.4 from 1.2.1. I just changed the js and css files. Am I supposed to make any changes in the code as well ?

**Comment by devilankur18** [comment] 2016-01-29 04:27
I have debugged the code and found the issue is related to ion slider. My old code was using `ion-slides` which no longer working.


```
  <ion-slides  slider="slider" class="sliderBox">
      <ion-slide-page>
        <div class="intro-page">
          <div class="logo-title">Smugglr</div>
          <div class="row">
            <div class="col col-90 heading">
              <h1 class="">Smugglr puts you in touch with a curated set of experts</h1>
            </div>
          </div>
          <div class="artwork col col-100">
            <img src="img/artwork-smugglr-icon.png" width="42%">
          </div>
          <div class="actionBtn col col-100">
            <button ng-click="facebook()" class="button button-block">
              Sign in with Facebook
            </button>
          </div>
        </div>
      </ion-slide-page>
      <ion-slide-page>
        <div class="intro-page intro-nxt">
          <div class="logo-title">Smugglr</div>
          <div class="row">
            <div class="col col-90 heading">
              <h1 class="">Ask questions and get instant answers across various topics</h1>
            </div>
          </div>
          <div class="artwork col col-100">
            <img src="img/iPhone-wireframe.png" class="feature-2">
          </div>
        </div>
        <div class="actionBtn col col-100">
          <button ng-click="facebook()" class="button button-block">
            Sign in with Facebook
          </button>
        </div>
      </ion-slide-page>
      <ion-slide-page>
        <div class="intro-page intro-nxt">
          <div class="logo-title">Smugglr</div>
          <div class="row">
            <div class="col col-90 heading">
              <h1 class="">If you happen to like an answer, add that expert to your smugglr network</h1>
            </div>
          </div>
          <div class="artwork col col-100">
            <img src="img/iPhone-wireframe.png" class="feature-2">
          </div>
        </div>
        <div class="actionBtn col col-100">
          <button ng-click="facebook()" class="button button-block">
            Sign in with Facebook
          </button>
        </div>
      </ion-slide-page>
    </ion-slides>
```

**Comment by jgw96** [comment] 2016-03-14 16:35
@AnkB were you also using <ion-slides/> ?

**Comment by jgw96** [comment] 2016-04-14 17:12
Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to respond back if your still having the issue! Thanks again!

**Closed by jgw96** 2016-04-14 17:12 UTC
Labels: slides, v1
