### ISSUE TITLE
Native: tried calling StatusBar.styleDefault, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator

### ISSUE THREAD

**Issue by kluz116** [driftyco/ionic#8878] opened 2016-10-24 14:45 UTC
**Note: If you are having problems formatting your issue please refer to this article on using markdown in Github:**

https://guides.github.com/features/mastering-markdown/

**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

**Note: for Ionic-Native related issues you can open up an issues on the Ionic-Native repo**

https://github.com/driftyco/ionic-native

#### What behavior are you expecting?

**Steps to reproduce:**
1. 
2. 
3. 

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x

#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

**For Ionic 2 issues** - http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by jgw96** [comment] 2016-10-24 16:02
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!

**Closed by jgw96** 2016-10-24 16:02 UTC

**Comment by chefren** [comment] 2018-02-05 03:10
It can still happen, it seems the cause are version incompatibilities:
- New Issue [1380](https://github.com/ionic-team/ionic-app-scripts/issues/1380)
- Previous related issue: [467](https://github.com/ionic-team/ionic-app-scripts/issues/467)
- Related [workaround](https://stackoverflow.com/a/48266685/1736679)
