### ISSUE TITLE
bug: the element under contentEditable can't be edited

### ISSUE THREAD

**Issue by qinyang912** [driftyco/ionic#3089] opened 2015-02-12 07:07 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>version v1.0.0-beta.14
I check the code in ionic.bundle.js line 2652,the code didn't deal with the condition when the ele.contentEditable === 'inherit'</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-02-12 07:07
Greetings @qinyang912!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3089). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3089)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment] 2015-02-12 15:25
Greetings @qinyang912!

I'm sorry, but my sensors indicate that this issue may no longer apply to recent versions of Ionic.

If you are still experiencing this issue, please feel free to reopen it by creating a new issue and provide the following information, so that I may assist you:

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com). There are many humans there who can offer sage advice.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-02-12 15:25 UTC
Labels: ionitron:closed

**Comment by lhrossi** [comment] 2016-12-09 13:17
Hi, I'm having the same issue, this is happening on version 1.3.2 of Ionic bundle, this is the latest version of the Ionic 1, but I don't know if still being supported, just in case  I create a codepen for it: [http://codepen.io/lhrossi/pen/XNBbpm](http://codepen.io/lhrossi/pen/XNBbpm). If it still being supported this issue can be reopened?
