### ISSUE TITLE
Empty space after keyboard close

### ISSUE THREAD

**Issue by zikosichi** [driftyco/ionic#5678] opened 2016-03-02 11:02 UTC
#### Short description of the problem:
I have a simple form. Initially, everything is ok, but when I focus on any input and then blur, at the bottom appears big empty space.

![screenshot_20160302-145823](https://cloud.githubusercontent.com/assets/16005795/13458594/8a904604-e087-11e5-90b2-1019513f27b9.png)
![screenshot_20160302-145830](https://cloud.githubusercontent.com/assets/16005795/13458595/8a914388-e087-11e5-96ed-cac3cf709cf4.png)
![screenshot_20160302-145849](https://cloud.githubusercontent.com/assets/16005795/13458596/8a93acf4-e087-11e5-8ac6-831623a3d462.png)

**Ionic Version**: 2.x

iOS / Android / Chrome

**Comment by weupagency** [comment] 2016-03-03 13:08
Hi !

To fix that problem you just have to add the following code in your .scss file :
```
scroll-content {
	position:relative;
}
```

**Comment by kalcheat** [comment] 2016-03-07 12:47
i have the same issue.

 If i add 

`scroll-content {
  position:relative;
}`

and the form is longer than one page, i loose the ability to scroll :/

**Comment by jgw96** [comment] 2016-03-11 20:34
Thanks for submitting this issue! As this bug is a duplicate of issue #5800 i will be closing this one. Please feel free to continue the conversation on this issue over there. Thanks Again!

**Closed by jgw96** 2016-03-11 20:34 UTC
Labels: keyboard, platform:android, platform:ios, v2

**Comment by EvanWillms** [comment] 2016-04-10 21:32
This looks like another report of #5432.

@zikosichi & @kalcheat, I've posted some notes about the temporary workaround I'm currently using to prevent the extra whitespace from developing at:
https://forum.ionicframework.com/t/disable-scroll-ionic2-ios9-not-working/44847/5?u=evanwillms

**Comment by hidemo** [comment] 2018-05-16 19:45
https://engineerphilosophy.com/ionic-3-issues-input-scrolling-keyboard-issues-for-forms/
