### ISSUE TITLE
bug: overflow-scroll IONIC 1.2 bleeding edge

### ISSUE THREAD

**Issue by efuturetoday** [driftyco/ionic#4774] opened 2015-12-14 08:39 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hello Developer Team of Ionic,
i experienced a bug i think and want to report it as fast as possible just before the official release of Ionic 1.2 in the stable channel.
Iam using  1.2.0-nightly-1829 with the sidemenu starter example and added a view:
```
<ion-view view-title="TestView">
  <ion-content>
    <div class="card">
      <div class="item item-text-wrap">
        This is a basic Card which contains an item that has wrapping text.
      </div>
    </div>
  </ion-content>
</ion-view>
```

i experienced that overflow-scrolling is the default setting now and i get a scroll issue for now: you can scroll the page even when your screen size is larger than the content (no scroll needed).
Now the strange if i add a 
```
<h2>TestPage</h2>
```
before the ionic card, the bug disappears...
Maybe need some investigation.

Greetings from Cologne!</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-12-14 08:39
Greetings @efuturetoday!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4774). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4774)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by efuturetoday** [comment] 2015-12-14 08:52
Update: the reason is the <code>margin-top</code> attribute. When your first Element in the <code>ion-view</code> has a top margin the window can scroll down the amount of the margin.
So its a bug or a feature? In jsScroll this should not happen?

**Comment by FLHerne** [comment] 2015-12-14 14:55
Removing the 'height: 100%' attribute from ".overflow-scroll .scroll" resolves this, and doesn't cause any other problems that I've noticed yet.

For some reason the <div class="scroll"> has the same top margin as its first child, so setting 100% height prevents it from scrolling properly.

**Comment by mlynch** [comment] 2015-12-14 15:18
Will review for 1.2.1

**Comment by mlynch** [comment] 2015-12-15 02:54
@efuturetoday @FLHerne are you guys referring to the whole entire browser frame? Are you testing in iOS Safari or in an app shell (Cordova)?

If so, try master, just pushed a fix for the mobile browser case

**Comment by FLHerne** [comment] 2015-12-15 10:17
Testing with Chrome (Android), Firefox & Chromium (desktop).

5875ebc doesn't change anything for me, nor 3d866a0 with it reverted.

Screenshots attached - the page can be scrolled between those two positions (the distance being the top margin of the card element) even though the content easily fits without scrolling.

![notscrolled](https://cloud.githubusercontent.com/assets/4886504/11807895/d2956624-a314-11e5-83fa-2c3157333902.png)
![scrolled](https://cloud.githubusercontent.com/assets/4886504/11807901/d9cee190-a314-11e5-9628-257a6c00cf75.png)

**Comment by mlynch** [comment] 2015-12-15 21:16
I see and can reproduce.

**Comment by FLHerne** [comment] 2015-12-16 12:56
This also affects ion-scroll elements, not only ion-content.

**Comment by mlynch** [comment] 2015-12-17 03:31
Pushing to 1.3 since it's not a regression in 1.2 but exposes a limitation in our layout. I think the solution going forward is to switch to flexbox style layout

**Comment by jgw96** [comment] 2016-05-12 19:45
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-05-12 19:45 UTC
Labels: scroll, v1
