### ISSUE TITLE
v2 : ion-navbar does not show back button in ion-tabs page

### ISSUE THREAD

**Issue by fdelayen** [driftyco/ionic#7364] opened 2016-07-19 15:22 UTC
#### Short description of the problem:
Since v2 beta 10 ion-navbar does not show back button in ion-tabs page. 

#### What behavior are you expecting?
If there is a possibility to go back to another view from an ion-tabs base page, it should display the back button and not the menu button.

**Steps to reproduce:**
1. Create a simple app : A left menu, a simple page that push an ion-tabs page with the following toolbar :
```
<ion-navbar>
  <button menuToggle="left">
    <ion-icon name="menu"></ion-icon>
  </button>
</ion-navbar>
```
2. Navigate to it and it will show a menu button that does not allow to go back. (it triggers the menu)

**Which Ionic Version?** v2 beta 10

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Your system information:

Cordova CLI: You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.2.0

Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
OS: Distributor ID:	Ubuntu Description:	Ubuntu 16.04 LTS 
Node Version: v6.3.0

**Comment by jgw96** [comment] 2016-07-19 15:58
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue?  Just from looking at your code I think the issue is that your `ion-navbar is not wrapped in an `ion-header`. In beta.10 we did a layout refactor that changed the way navbar worked slightly. Here is an example of the correct way to use a navbar now.
```
<ion-header>
  <ion-navbar> 
    <button menuToggle="left">
      <ion-icon name="menu"></ion-icon>
    </button>
  </ion-navbar>
</ion-header>
```
I would also recommend checking out our [changelog](https://github.com/driftyco/ionic/blob/master/CHANGELOG.md) for all the details of the beta.10 release. Thanks for using Ionic!

**Comment by fdelayen** [comment] 2016-07-20 08:24
I know about the changelog and did place the navbar in an ion-header. I'll provide a plunkr !

**Comment by fdelayen** [comment] 2016-07-20 09:37
There you go : [http://plnkr.co/edit/qpffipbbbCK4kjvy6yFX?p=preview](http://plnkr.co/edit/qpffipbbbCK4kjvy6yFX?p=preview)

What to expect ?
1. In the Page 1 : If you click the open tabs button and then click the menu button it will not pop but open the menu.
2. In the Tab page : If you click the thanks button and then click the menu, it will pop.

I think it should pop for these two use cases not only for the second one... (it's what it was doing in beta 9)

**Comment by mpaland** [comment] 2016-07-21 11:09
As far as I see, the structure of your example is a bit unlucky.
Please try to set ```this.rootPage = TabsPage``` in app.ts
Then I have no problem with the back button in your plunkr.

**Comment by zakton5** [comment] 2016-07-26 19:48
That's the thing @mpaland, the tabs page isn't necessarily always going to be the root of an application. I myself have this same issue. My root page is a list, and then when I click an item I push a tabs page onto the nav stack because each item has a LOT of content that needs to be displayed in different categories, which is why I use tabs. It's really the best for my situation. Ionic 2 should have support for non-root tab pages

**Comment by jgw96** [comment] 2016-07-26 20:23
Hello @zakton5 ! At this time we do not support tabs being anything other than the root page, although that could definitely change in the future. For your use case I would recommend checking out [segments](http://ionicframework.com/docs/v2/components/#segment). Thanks for using Ionic!

**Comment by fdelayen** [comment] 2016-07-27 13:23
Thank you @zakton5 @jgw96 @mpaland for your answers.
I have the same structure as zakton, my root page is a list of things, and when I click on this thing, I have many informations to display in categories so it definitely cannot be my root page and using segments is a bit tricky and we will need a lot of refactoring :disappointed:

**Comment by mpaland** [comment] 2016-07-27 13:42
The problem I see is how do you leave (navigate backward) from a tabs page? A back button might be a bit confusing, likewise using the hardware back button.
I would consider using a segment control on sub pages as @jgw96 already pointed out.

**Comment by fdelayen** [comment] 2016-07-27 15:26
Well... I think that when there is no more backward history for a tab page, it should go to what was there before tabs. Does that make sense ?
We will try out segments to see how we can work with it, thanks ! :wink:

**Comment by jgw96** [comment] 2016-07-27 15:41
Hello all! I am going to be closing this issue as we only plan on supporting tabs as the root page at this time and using segments should fix the issue here. @fdelayen If you have any issues using segments feel free to hit up our [forum](https://forum.ionicframework.com/). Thanks for using Ionic!

**Closed by jgw96** 2016-07-27 15:41 UTC
Labels: menus, v2

**Comment by fdelayen** [comment] 2016-07-28 14:43
Just an update on the fly...
Segments or really not designed for this use case and if emulate tabs with segments is a good idea technically, the visual design doesn't fit at all (try with icons in, it's... just ugly).
I will either patch your tabs or apply tabs theme on segments... no choice. :disappointed:

**Comment by zakton5** [comment] 2016-07-28 15:11
I must agree with @fdelayen. They just do not look good like tabs do. Beyond that, having to combine the HTML from each of the old tab pages into the template for the segments makes it much less manageable.

**Comment by mordka** [comment] 2016-08-26 13:44
If anynone's interested in having the back button and using tabs here's a simple css hack:
```
//tab1.html (root page)
 <ion-navbar text-center primary class="force-back-button">```
//css
.force-back-button .back-button {
  display: inline-block;
}
```

Would be nice to have `hideBackButton="false"` directive working on nav-bar [(docs)](http://ionicframework.com/docs/v2/api/components/navbar/Navbar/#input-properties) .

**Comment by 64jcl** [comment] 2016-12-08 15:03
Yep, that will make the back button visible. But in the current release of Ionic2 pressing it will display a black page and not the page that was used to push in the new page with the tabs in. And you are still stuck at the tabs page.

**Comment by 64jcl** [comment] 2016-12-08 15:08
Come to think of it, the reason why I get a black page might be because I push the page with the tabs from a side menu that is initialized on the App and not from a page so the nav control that the menu gets is possibly not the current pages nav...

**Comment by mjwheatley** [comment] 2017-02-21 16:57
I just saw @jgw96 closing comment to try using segments instead, but I did find a solution building on @mordka answer.

I found this StackOverflow answer about overriding the back button click http://stackoverflow.com/questions/38906715/ionic-2-generated-back-button-click-event

So by using css to force the back button to be displayed you can override the back button click event and dismiss the parent (Tabs) view controller using:

`this.nav.parent.viewCtrl.dismiss();`

In your TabPage.ts
```
import {OnInit, ViewChild} from '@angular/core';
import {NavController, Navbar} from 'ionic-angular';

export class TabPage implements OnInit {
    @ViewChild(Navbar) navBar:Navbar;

    constructor(public nav:NavController) {
    }

    ngOnInit() {
    }

    ionViewDidLoad() {
        this.navBar.backButtonClick = (e:UIEvent) => {
            console.log("Back button clicked");
            this.nav.parent.viewCtrl.dismiss();
        };
    }
```

**Comment by Diones** [comment] 2017-03-09 23:46
@mjwheatley Works perfectly!! Thank you!

@mordka you too! thank you!

**Comment by ferminako** [comment] 2017-03-13 15:25
great !

**Comment by MattHirdler** [comment] 2017-06-08 08:01
This is obviously something that many people have run into. I would suggest reconsidering support for 'non-root' tab pages.

**Comment by eolant** [comment] 2017-06-21 23:55
@mjwheatley I have a small addition to anyone who might have the same problem as I did:
In Ionic 3.10 default tabs template doesn't have navbar component and it makes `navBar` `undefined`. So code from TabPage.ts have to go to child components.
E.g. my home.ts looks like this:
`import { Component, ViewChild } from '@angular/core';
import { NavController, Navbar } from 'ionic-angular';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {
  @ViewChild(Navbar) navBar: Navbar;

  constructor(public navCtrl: NavController) {

  }

  ionViewDidLoad() {
    this.navBar.backButtonClick = (e: UIEvent) => {
      console.log("Back button clicked");
      this.navCtrl.parent.viewCtrl.dismiss();
    };
  }

}`

**Comment by philipwalter** [comment] 2017-08-15 14:55
Thanks to all who provided this solution.  Works like a charm!  I disagree with others who don't see this configuration as useful.  A list of buttons that each takes you to a tabs-based detail page for the corresponding entity is very intuitive for what we are trying to do.  Having a back-button on the tabs-based detail page to return to the list makes perfect sense to our users.  Furthermore, tabs-based navigation on the detail pages is highly preferable to segments, so thanks again to those who provided the workaround!

**Comment by iverveinc** [comment] 2017-08-21 10:58
I am getting "Property backButtonClick does not exists on type Navbar" error.

Can Anyone help me with this.

**Comment by ayozebarrera** [comment] 2017-09-12 16:12
Thanks @eolant! 💪

**Comment by erickdebrito** [comment] 2017-10-17 19:59
Good Afternoon guys,
I tried to do it the same way as @eolent, but it is giving error "the navigation stack needs a root page"
