### ISSUE TITLE
!!! Scroll Events Not Working Properly on iOS

### ISSUE THREAD

**Issue by flexmarkets** [driftyco/ionic#11002] opened 2017-03-31 15:02 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

The problem is, that there are only scroll events emitted, when the user touches the screen and doesn't release the finger while scrolling.

If the user releases the finger and lets the content scroll, then the content scrolls as expected, but there are just events emitted, when the user scrolls while holding the finger on the screen. 

After releasing the finger, there aren't any events emitted as on Android or the Computer. There's just one last event emitted, when the scrolling stops.

And because of this, it's impossible to have a smooth transition of css properties, that should change based on the scroll position of the content (done with JavaScript).

**Expected behavior:**

There should also be events emitted, when the user releases his finger and the content scrolls automatically because of momentum.

**Steps to reproduce:**

Use the related code and test it with the Ionic View app on with the iOS Simulator.

**Related code:**

```

    // On iOS, there are only events emitted, 
    // when the user touches the screen while scrolling.


    this.content.ionScroll.subscribe( () => {
    	console.log('Scrolling' + "\n");
    });

```

**Comment by jgw96** [comment] 2017-03-31 15:13
Hello, thanks for opening an issue with us! This is due to a regression in 2.3.0 with scroll events. This has since been fixed and will be in the next release.

**Closed by jgw96** 2017-03-31 15:13 UTC

**Comment by flexmarkets** [comment] 2017-04-01 05:55
When will the next release be released?
