### ISSUE TITLE
scrolling does not work only in ios

### ISSUE THREAD

**Issue by xiaofanwu** [driftyco/ionic#6510] opened 2016-05-12 09:50 UTC
#### Short description of the problem:
I am currently facing a problem where scrolling does not work at all only in IOS. It only works if I scroll from the edge side, but I want to be able to scroll in the form. Here is a video of the issue. http://sendvid.com/i0n283rl

#### What behavior are you expecting?
I am expecting to be able to scroll through without having to go the side to scroll down. 

**Steps to reproduce:**
1. Ionic start tabs tabs to create a tab basic ionic app
2. Add the code that is below to any of the tabs
3. There is the behavior.

```
insert any relevant code between the above and below backticks
```<ion-view title="Create Event">
    <ion-nav-buttons side="right">
        <button class="button button-clear" ng-click="logout()">Logout
        </button>
    </ion-nav-buttons>


    <ion-nav-buttons side="left">
        <button class="button button-icon button-clear ion-email-unread" ng-if="exists" ng-click="openEvent()"></button>
    </ion-nav-buttons>

    <!--    <ion-scroll overflow-scroll="true" padding="true" class="has-header">-->
    <!--    <ion-scroll direction="y" style="right: 0;bottom: 0;left: 0;position: absolute;" class="has-header has-subheader">-->
    <ion-content overflow-scroll="true" padding="true">

        <div class="list">
            <form novalidate name="eventForm" id="eventForm" ng-model="eventForm" ng-submit="submitForm(formName.$valid)" class="simple-form">

                <label class="item item-input item-select item-stacked-label">
                    <span class="input-label">
        <b>Event Type</b>
    </span>
                    <div>
                        <br>
                        <select ng-model="user.eventType" required>
                            <option>Instant Hangout</option>
                            <option selected>Group Event</option>
                            <option>Alum Club</option>
                        </select>
                    </div>
                </label>


                <label class="item item-input item-stacked-label">
                    <span class="input-label"><b>Name of the Event</b></span>
                    <input ng-model="user.nameOfEvent" type="text" placeholder="Name,type,and dates are required" required>
                </label>

                <label class="item item-input item-stacked-label">
                    <span class="input-label"><b>Description</b></span>
                    <input ng-model="user.description" type="text" placeholder="Describe the event">
                </label>

                <label class="item item-input item-stacked-label">
                    <span class="input-label"><b>Address</b></span>
                    <input type="text" ng-autocomplete ng-model="user.address" options="options" details="details" placeholder="Your address" ng-focus="disableTap()" />

                    <!--                    ng-focus="disableTap()"-->
                </label>

                <label class="item item-input item-stacked-label">
                    <span class="input-label"><b>Contact Email</b></span>
                    <input ng-model="user.email" type="text" placeholder="ex: alumnae@wellesley.edu">
                </label>
                <!--                             ng-init = "user.email='User did not enter anything'"-->

                <label class="item item-input item-stacked-label">
                    <span class="input-label"><b>Contact Number</b></span>
                    <input ng-model="user.phone" type="tel">
                </label>



                <label class="item item-input item-stacked-label">
                    <span class="input-label">Date</span>
                    <input ng-model="user.date" type="date" required>
                </label>
                <label class="item item-input item-stacked-label">
                    <span class="input-label">Time</span>
                    <input ng-model="user.time" id="myTime" type="time">
                </label>


                <label class="item item-input item-select item-stacked-label">
                    <span class="input-label">
        <b>Please specify time zone</b>
    </span>




                    <div>
                        <br>
                        <select ng-model="user.timeZone">
                            <option>EST</option>
                            <option>PST</option>
                            <option>etc..</option>

                        </select>
                    </div>
                </label>


                <label class="item item-input item-select item-stacked-label">
                    <span class="input-label">
        <b>Invite Alumnae Within A...</b>
    </span>
                    <div>
                        <br>
                        <select ng-init="user.radius='25 mile radius'" ng-model="user.radius">
                            <option>1 mile radius</option>
                            <option>5 mile radius</option>
                            <option selected>25 mile radius</option>
                            <option>50 mile radius</option>
                            <option>75 miles</option>
                        </select>
                    </div>
                </label>

                <label class="item item-input item-stacked-label">
                    <span class="input-label">
       
    </span>


                    <div>
                        <img ng-src="data:image/jpeg;base64,{{showPic}}" width="100%" />
                    </div>

                    <center>
                        <div>
                            <button class="button button-small button-positive" ng-click="openModal()">upload a photo</button>
                        </div>


                    </center>
                </label>





                <input class="button button-block button-positive" type="submit" value="Create the Event" ng-click="update(user)" ng-disabled="eventForm.$invalid" />
            </form>
        </div>


    </ion-content>
</ion-view>


**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 
https://forum.ionicframework.com/t/can-not-scroll-through-form-at-all/51799

**Which Ionic Version?** 1.x or 2.x
I just downloaded the latest ionic version.

**Comment by jgw96** [comment] 2016-09-09 18:25
Hello! Are you still having this issue? Thanks!

**Comment by jgw96** [comment] 2016-09-12 15:57
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-09-12 15:57 UTC
Labels: needs reply, v1

**Comment by enayetn** [comment] 2017-02-08 15:53
@jgw96 Hello, I am experiencing what I think is a similar issue. I've put up a codepen here so you can see the problem: https://codepen.io/enayetn/pen/egLbjY

The relevant markup is below:

`<ion-scroll direction="x" class="item"> <!-- Content here --> </ion-scroll>`

From what I can tell, trying to scroll within the ion-scroll area in the Y direction prevents me from scrolling the page. 

GIF reproduction of what I'm seeing (would expect to be able to scroll in the Y direction regardless of where my cursor is)

https://i.gyazo.com/e898c7d810071ae119121f0c90403b6a.mp4
