### ISSUE TITLE
ION-Content Scroll is not Refreshing After Close the Keybaord

### ISSUE THREAD

**Issue by hrpatidar** [driftyco/ionic#5764] opened 2016-03-08 01:32 UTC
ion-content scroll is not reset or refreshing after close the keyboard. **Having incorrect content size on the all screens.** I have attached screenshot of the device. Please check it. 

Expected: It should be having proper scroll as per content height of the screens.

**Steps:**
1. Tap on input field --> keyboard opens
2. Tap on app back button from top nav bar --> keyboard closed and back to list screen(Could be any screen).
3. On list screen keyboard is closed but the content is not having correct scroll --> there is some free space at the end of the ion-content. the free space is similar to keyboard height. Please help me out. I have updated the IONIC version as well with 1.2.4. But still facing. 

![screen shot 2016-03-08 at 6 29 18 am](https://cloud.githubusercontent.com/assets/7664377/13589296/ceee0ab0-e4fc-11e5-8cc8-7e918206e917.png)

If I have tap on any input field again --> open the keyboard --> tap on free area of screen -> close the keyboard properly --> Now I am not getting incorrect content size. 
So It might be the keyboard is not refreshing the ionic content view.

**I have also added the below code for closing the keyboard on every state change success event. But it is also does not reset the view. It is just closing the keyboard. But screen contains incorrect size of page. Added keyboard height as well.
cordova.plugins.Keyboard.close();**

**Ionic Version**: 1.2.4

**Browser & Operating System**: iOS / Android

**Comment by jgw96** [comment] 2016-03-11 19:08
Thanks for opening an issue with us! We appreciate the detailed info! Would you mind running `ionic info` and pasting the output here please? That will help us with debugging this issue.

**Comment by hrpatidar** [comment] 2016-03-12 02:54
Please let me know, How can I get this IONIC info?

**Comment by jgw96** [comment] 2016-03-15 21:53
@hrpatidar Thanks for asking! Simply open your terminal (cmd if your on windows), navigate to your ionic project and then run ionic info. Hopefullly this helps you

**Comment by AdrianTeh** [comment] 2016-03-20 03:08
Same thing happening here:

"name": "ionic-plugin-keyboard",
"version": "2.0.1",

Cordova CLI: 6.0.0
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
ios-deploy version: 1.8.5
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v4.3.0
Xcode version: Xcode 7.2.1 Build version 7C1002

**Comment by jgw96** [comment] 2016-03-21 14:17
This issue is related to https://github.com/driftyco/ionic/issues/5810

**Comment by jgw96** [comment] 2016-03-21 14:19
Thanks for opening an issue with us! As this bug is a duplicate of https://github.com/driftyco/ionic/issues/5432 i am going to close this issue. Please feel free to continue the conversation over there!

**Closed by jgw96** 2016-03-21 14:19 UTC
Labels: keyboard, scroll, v1
