### ISSUE TITLE
Tap vs Click in Ionic 3.x

### ISSUE THREAD

**Issue by vazad28** [driftyco/ionic#10935] opened 2017-03-27 17:14 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The click event on a button or non button element, has a lag nearly a second long before the "click=()" event is executed. If I use "tap=()", the event registration is nearly instantaneous.

**Expected behavior:**
No click event delay irrespective or using "click" or "tap" event in the response time for registration of the event

**Steps to reproduce:**
Use "click" event and "tap" for same action to note the difference

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.0-beta.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.2.1
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.2.0
Xcode version: Xcode 8.2 Build version 8C38

**Comment by jgw96** [comment] 2017-03-27 19:10
Hello, thanks for opening an issue with us! Would you mind sharing a repo we can use to reproduce this? Also, what device are you testing on when you run into this issue?

**Comment by vazad28** [comment] 2017-03-27 23:27
I will try to create a repo. I have tested it in iphone 5s and also on emulator. I just created a test app using the instruction posted here
[https://docs.google.com/document/d/1vGokwMXPQItZmTHZQbTO4qwj_SQymFhRS_nJmiH0K3w/edit#heading=h.2k1n0klvkce3](url) and i find the same lag with click.

**Comment by vazad28** [comment] 2017-03-27 23:32
here is the repo

https://github.com/vazad28/testv3

**Comment by Sh1d0w** [comment] 2017-03-28 04:25
If you want instant clicks on non-button elements you have to add `tappable` attributes to that element, otherwise it has a delay of 300ms. For example:

```
<div tappable (click)="someHandler()">Click me</div>
```

This is well explained here https://ionicframework.com/docs/v2/troubleshooting/#click-delays

You have to read the docs.

**Comment by vazad28** [comment] 2017-03-28 04:27
"The click event on a button **or non button element**,......"

**Comment by jgw96** [comment] 2017-03-28 17:03
Hello @vazad28 , unfortunately i cannot reproduce this issue with your repo on either an Iphone 5 running the latest ios 10 or a 1st generation moto g running android 4.4.4. Because of this I am going to close this issue for now, but if you could provide another repo or a chrome timeline that shows the delay then i will happily reopen this issue (:

**Comment by vazad28** [comment] 2017-03-28 17:07
Wish I could send you a screen recording I made to show the delay.Anyways its too early for 3 so i will see if anyone else share the same observation. Thanks for looking into it. Appreciated.

**Comment by DeanmvSG** [comment] 2017-03-29 21:17
I'm not going crazy then! 

I have the same issue as well with an app I am building. It was working perfectly on V2 (clicking in a list or a tab would do the click instantly, since upgrading the same project to V3 there is a noticeable lag to every click. 

I'll see if I can produce a slimmed down demo repo for testing tomorrow. Just to note this only happens when running the the app on an actual device (iPhone 6S) for me, running it through serve seems to work fine

**Comment by DeanmvSG** [comment] 2017-03-30 09:56
Hey @jgw96 I've created a repo over [here](https://github.com/DeanmvSG/Ionic3ClickBug) with a demo of the bug that @vazad28 mentioned.  The app has two pages in it with the same code from one of the Ionic demos

The first page "Click" uses the `(click)` function to navigate to the detail page, the second page "Tap" uses the `(tap)` function to navigate to the detail page.  From my testing on a simulator (iPhone SE iOS 10.3) and a real device (iPhone 6s iOS 10.3), the `(click)` functions have a noticeable delay compared to the `(tap)` functions.

I've doen a small screen recording of it as well which should visualise the error, you should be able to see that when clicking on a list item in the Click page the list item "flashes" twice before navigating, whereas the Tap page navigates basically immediately.

Hope that helps!

![ionicclickbug](https://cloud.githubusercontent.com/assets/15265711/24498797/81ac984a-1537-11e7-8a50-c4612579a00e.gif)

**Comment by vazad28** [comment] 2017-03-31 20:19
I wish this can be re-opened because this is a persistent issue in spite of multiple recent updates in appscript and ionic3 itself.

**Comment by manucorporat** [comment] 2017-04-06 16:03
This will be fixed in 3.0.1

**Comment by manucorporat** [comment] 2017-04-06 16:09
Fixed: https://github.com/driftyco/ionic/commit/59f9737d9b4d3de3b862b47b0af79344bf0268c1

**Closed by manucorporat** 2017-04-06 16:09 UTC
Labels: needs info, v3

**Comment by tscislo-lingaro** [comment] 2017-04-13 10:24
I'm testing this wit 3.0.1 on iPhone 6s with iOS 10 and there is still a noticeable delay in (click) handling, (tap) looks ok.

**Comment by tscislo-lingaro** [comment] 2017-04-13 10:24
Can this be reopened?
