### ISSUE TITLE
Feature request (ionic v2):  support icon and badge in ion-segment-button

### ISSUE THREAD

**Issue by jmarginier** [driftyco/ionic#6957] opened 2016-06-18 09:52 UTC
**Short description of the problem:**

Using an icon in "ion-segment-button" breaks the CSS. Moreover, it would be convenient to have a badge system like tabs (cf #6636).

Code example : 

```
<ion-segment light [(ngModel)]="curSegment">
        <ion-segment-button value="toAccept">
            <ion-icon item-left name="flash"></ion-icon>//bad render
            toAccept
            <ion-badge danger item-right>{{challengesToAccept.length}}</ion-badge> //bad render
        </ion-segment-button>
    </ion-segment>
```

**Which Ionic Version?** 2.x beta 8
Tested under android and browser.
![test](https://cloud.githubusercontent.com/assets/5184546/16170203/25bb83ce-354b-11e6-928c-741e124e5b72.png)

**Comment by dylanvdmerwe** [comment] 2016-06-18 13:29
Similar to https://github.com/driftyco/ionic/issues/6636

**Comment by jgw96** [comment] 2016-06-20 14:31
Hello @jmarginier , thanks for opening an issue with us! I will be closing this issue as a duplicate of the issue @dylanvdmerwe linked too, but please feel free to post any feedback or info you have on that issue. Thanks for using Ionic!

**Closed by jgw96** 2016-06-20 14:31 UTC
Labels: platform:android, v2

**Comment by sndjones007** [comment] 2016-08-01 21:47
+1

**Comment by mansi241** [comment] 2018-03-21 07:35
You can do so by : 
<ion-segment-button value="any_value" >
          Notification 
          <ion-badge color="secondary" style="vertical-align:top;" item-right>10</ion-badge>
 </ion-segment-button>

**Comment by mansi241** [comment] 2018-03-21 07:38
You can do so by : 
```
 <ion-segment-button value="any_value" >
          Notification 
         <ion-badge color="secondary" style="vertical-align:top;" item-right>10</ion-badge>
 </ion-segment-button>
```
