### ISSUE TITLE
Ionic RC2 : The pinch gesture2 it's not working

### ISSUE THREAD

**Issue by bibounet** [driftyco/ionic#9150] opened 2016-11-14 14:54 UTC
The pinch gesture2 it's not working on my ionic RC2 app

both HTML container failed with pinch :

```
<ion-scroll (pinch)="pinchEvent($event)" (pan)="panEvent($event)" scrollX="true" scrollY="true" zoom="true" >
<div (pinch)="pinchEvent($event)" (pan)="panEvent($event)">
```
With my APK build,on Chrome inspect tool, I got the (pan) fired events but no (pinch) :

```
panEvent(event) {
    console.log(event); // OK
}
pinchEvent(event) {
    console.log(event); // KO !
}

```
https://forum.ionicframework.com/t/pinch-gesture-is-not-working/69564
https://forum.ionicframework.com/t/pinch-gesture-broken-with-rc0/66509

**Comment by jgw96** [comment] 2016-11-18 20:53
Hello! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/9066. Thanks!

**Closed by jgw96** 2016-11-18 20:53 UTC
Labels: v2
