### ISSUE TITLE
Disabled toggle components still show animation and also fire events.

### ISSUE THREAD

**Issue by epetre** [driftyco/ionic#7559] opened 2016-08-05 15:59 UTC
#### Short description of the problem:
Disabled toggle components still show animation and also fire events.

#### What behavior are you expecting?
It should not react to user clicks and movements

**Steps to reproduce:**
1. add disable attribute to any toggle
2. you can still click it and it fires events too

**Ionic Version 2 (Latest)**

**Comment by jgw96** [comment] 2016-08-05 18:37
Hello! Thanks for opening an issue with us! Unfortunately i cannot seem to reproduce this issue. Would you mind sharing a plunker that reproduces this issue? Thanks for using Ionic!

**Comment by jgw96** [comment] 2016-08-09 15:51
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-08-09 15:51 UTC
Labels: animation, needs reply, v2

**Comment by epetre** [comment] 2016-08-10 04:25
it's just a disabled toggle. Simply click on it and it will still animate. I will look into building a plunker, just have to find one that is bootstrapped for ionic2.
