### ISSUE TITLE
Screen orientation issue

### ISSUE THREAD

**Issue by ubaidseth** [driftyco/ionic#7756] opened 2016-08-17 16:23 UTC
#### Short description of the problem:

I'm mainly coding for my iPad.

When I start up Ionic View from the app store to view my project, it only shows Portrait. It used to show landscape but after the update it's now restricted to Landscape.

But now the real problem is --> so is my project. 

Any way around this?

#### What behavior are you expecting?

Screen locks to portrait mode.

**Steps to reproduce:**
1. Download Ionic View from the App Store
2. Login
3. View app

**Which Ionic Version?** 1.x or 2.x

Ionic 1 - Latest

**Comment by jgw96** [comment] 2016-08-17 18:22
Hello, thanks for opening an issue with us! I will be closing this issue as a duplicate of https://github.com/driftyco/ionic-view-issues/issues/179. Thanks for using Ionic!

**Closed by jgw96** 2016-08-17 18:22 UTC
Labels: platform:ios, v1
