### ISSUE TITLE
bug: SwipeToGoBack and ionic.activator problem

### ISSUE THREAD

**Issue by AlexYankee** [driftyco/ionic#3424] opened 2015-03-27 17:42 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>8ebde73d0b8afac1bf1c1787c90a72a28a88bc3a added kind of threshold check for swipe2goback activation and now all things which was previously activating by activator not activating when clicking < 45px, but receiving click.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-03-27 17:42
Greetings @AlexYankee!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3424). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3424)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment] 2015-03-30 22:14
Duplicate of #3348 and fixed in 36df50863853dcf4faee77cbf40c93c4556c11c1

**Closed by perrygovier** 2015-03-30 22:14 UTC
