### ISSUE TITLE
Modal content won't scroll

### ISSUE THREAD

**Issue by tones411** [driftyco/ionic#7166] opened 2016-07-02 04:00 UTC
#### Short description of the problem:
Content that would normally scroll in a regular view does not scroll when displayed in a Modal.

#### What behavior are you expecting?
I would expect it to scroll just like it does in a regular view.

**Steps to reproduce:**
1. Show a page in a modal
2. On the modal page, have enough content that it would need to scroll.

**home.ts**
```
...
var modal = Modal.create(Categories, {});
this.nav.present(modal);
...
```

**categories.html**
```
<ion-header>
	<ion-navbar>
		<ion-title>Categories</ion-title>
		<ion-buttons end (click)="Categories_Done($event)">
			<button style="margin-right:10px;">
				DONE
			</button>
		</ion-buttons>
	</ion-navbar>
</ion-header>

<ion-content class="categories">
	<ion-card>
		<ion-list>
			<ion-item *ngFor="let category of categories; #i=index;">
				<ion-label>{{category.name}}</ion-label>
				<ion-checkbox [(ngModel)]="category.selected"></ion-checkbox>
			</ion-item>
		</ion-list>
	</ion-card>
</ion-content>
```

**Which Ionic Version?** 1.x or 2.x
2 beta 10

**Comment by manucorporat** [comment] 2016-07-02 09:45
Could you create an Plunker to demonstrate it? You can use this template it:  http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview

**Comment by tones411** [comment] 2016-07-02 14:32
I cannot get Modal or ModalController to work in Plunker.

Please see home.ts in my example:
http://plnkr.co/edit/5KwNyvIouGU6VfIPkVga?p=preview

**Comment by manucorporat** [comment] 2016-07-02 14:54
@tones411 
1. 
```
	goToPage1() {
	  this.nav.push(Page1);
	  
	  var page1Modal = ModalController.create(Page1, {});
	  this.nav.present(Page1);
	}
```

1. `ModalController` is not part of beta10, but nightly. It will be available in beta 11.
2. You are passing `Page1` to `this.nav.present` instead of `page1Modal`.

The correct code would be:
```
	goToPage1() {	  
	  var page1Modal = Modal.create(Page1, {});
	  this.nav.present(page1Modal);
	}
```

and next version it will be:
```
        constructor(private modalCtrl: ModalController) {}
	goToPage1() {	  
	  var page1Modal = this.modalCtrl.create(Page1, {});
	  this.nav.present(page1Modal);
	}
```

**Comment by manucorporat** [comment] 2016-07-02 14:57
I can't reproduce your issue with the fixed plunker either, the modal is scrolling to me.

**Comment by tones411** [comment] 2016-07-02 15:29
Interesting. I cannot reproduce the issue in the fixed Plunker. However, when trying to use ModalController in my local workspace, the ModalController class does not exist. But from my other bug report you saw that I am on Ionic 2 beta 10. Is it possible that the plunker example has an even later version than what I have?

**Comment by manucorporat** [comment] 2016-07-02 15:38
@tones411 right! but ModalController is not part of beta 10! :) it is available in nightly.
Try to install the latest nightly build and test ModalController.

I am going to close this bug report, but please feel free to open a new one if you find the root of the problem, could your issue be related with: https://github.com/driftyco/ionic/issues/7117

**Closed by manucorporat** 2016-07-02 15:38 UTC
Labels: modals, v2

**Comment by tones411** [comment] 2016-07-02 16:12
Okay, that makes sense.

1) How can I update to Nightly?
2) Do the docs always represent Nightly, and if not, what do they represent? I guess I assumed that the docs on this page http://ionicframework.com/docs/v2/api/components/modal/ModalController/ would work for Ionic 2 beta 10.

**Comment by manucorporat** [comment] 2016-07-02 16:22
@tones411
1) How can I update to Nightly? try this:
```
npm install ionic-angular@nightly 
```
you may have to upgrade angular 2 dependencies as well (not sure) and clean up node_modules

2)Yes, default represents nightly:
<img width="511" alt="screen shot 2016-07-02 at 18 15 38" src="https://cloud.githubusercontent.com/assets/127379/16541367/126a15a6-4081-11e6-8d68-fce6d51554d2.png">

I just opened an issue in `ionic-site` to prevent this confusing again: https://github.com/driftyco/ionic-site/issues/680 :D

**Comment by tones411** [comment] 2016-07-02 16:31
1) Will give it a try.

2) Thanks. It took me a little bit to find that screen with the menu drop-down for versions. The one I was on didn't have that drop-down.

**Comment by tones411** [comment] 2016-07-02 16:35
1) If I find bugs in 2 beta 10, is it best to just confirm it first in 2 Nightly before reporting it?
2) Is there a group I can join to know what the breaking changes are in each nightly? (I have been following the beta path and following the upgrade steps and watching for those breaking changes, but it seems like I might be safer to stay on Nightly?)

**Comment by manucorporat** [comment] 2016-07-02 17:15
>1) If I find bugs in 2 beta 10, is it best to just confirm it first in 2 Nightly before reporting it?

No, it's ok! we appreciate all the bug reports, maybe just confirm it is not a duplicate.

2) Is there a group I can join to know what the breaking changes are in each nightly? 

Try the slack group, http://blog.ionic.io/join-ionic-worldwide-slack/ or the forum!

Nop, it is always safer to stay in a beta release. nightly usually contains good hot fixes but it can contain WIP code.

**Comment by cyanbluefire** [comment] 2017-02-06 03:49
thank you!

**Comment by davidtweaver** [comment] 2017-02-27 11:26
Hello, I'm using the Ionic 2.0.0 Final and am experiencing this bug (on Android and iOS). I can't scroll inside a modal, but the background scrolls instead.

My modal HTML looks like this

`
<ion-content padding>
	<ion-scroll scrollY="true">
		

		<p class="muted">Please tick the actions which you will follow up on. These will be carried through to the final care plan report.</p>
		<br>
		<ion-list>
		<ul>
			
				<ion-item>
					<li *ngFor="let acCategory of qModel.actionCategory; let i = index">
						<input id="'check'+i" type="checkbox" name="isActive" [(ngModel)]="qModel.actionCategory[i].toggle">
						<label for="'check'+i" class="checkbox"> 
							{{ acCategory.carePlanAction }}
							{{ qModel.actionCategory.toggle }}
						</label>
					</li>

				</ion-item>
			

		</ul>
		</ion-list>
		<button class="btn btn-default btn-icon btn-cancel" (click)="dismiss()">cancel</button>
		<button class="btn btn-icon btn-confirm pull-right" (click)="generateAnswer()">submit</button>
	
	</ion-scroll>
</ion-content>` 

Do you have any ideas what I might be doing wrong?

**Comment by datzash2003** [comment] 2017-07-25 23:17
@davidtweaver any update on this issue? Did you find any fix? I'm facing the same problem with the scroll inside modal on ionic 2. Any help is appreciated!

**Comment by Anujmoglix** [comment] 2018-02-27 09:36
Is that issue exists now ?
