### ISSUE TITLE
Ionic 2: Navigation with Angular 2 Router

### ISSUE THREAD

**Issue by menthena** [driftyco/ionic#5540] opened 2016-02-20 21:46 UTC
#### Short description of the problem:
Can't seem to make nav work with Angular 2 Router. Is there a specific reason that this happens? I am creating a cross-platform app and getting the following error:

```
EXCEPTION: TypeError: Cannot read property 'componentType' of undefined
```

and the function that does give the error: 

```
    value: function getPathRecognizerByComponent(componentType) {
    // given a componentType, figure out the best PathRecognizer to use
    var rules = this['_parentRouter'].registry._rules;
    var pathRecognizer = null;
    rules.forEach(function (rule) {
        pathRecognizer = rule.matchers.find(function (matcherPathRecognizer) {
            **return matcherPathRecognizer.handler**.componentType === componentType;
        });
    });
    return pathRecognizer;
}
```

It is fine when I comment out @RouteConfig. 

Thanks

**Comment by brandyscarney** [comment] 2016-03-01 18:42
Could you compare your code with the example here: https://github.com/driftyco/ionic/tree/2.0/ionic/components/nav/test/routing

Also, can you give some sample code for us to reproduce the problem?

**Comment by jgw96** [comment] 2016-03-22 14:32
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to respond back if your still having the issue! Thanks again!

**Closed by jgw96** 2016-03-22 14:32 UTC
Labels: navigation, v2

**Comment by mumairofficial** [comment] 2017-01-25 19:23
Can we still angular 2 router module with in ionic 2 or is there alternative to this?

**Comment by amimiimen** [comment] 2017-05-07 16:37
when using segments, I want to switch to another component without putting all code in the same page?
