### ISSUE TITLE
bug: Tabs + deep linking (not working/example?)

### ISSUE THREAD

**Issue by uofmmike** [driftyco/ionic#8971] opened 2016-10-31 22:57 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Looking to create deep linking with tabs, I don't believe the feature is working at this moment in time.

File: https://github.com/driftyco/ionic/blob/master/src/navigation/deep-linker.ts

Using tabs starter:
```
@NgModule({
  declarations: [
    MyApp,
    AboutPage,
    ContactPage,
    HomePage,
    TabsPage
  ],
  imports: [
    IonicModule.forRoot(MyApp, {}, {
     links: [
      { component: HomePage, name: 'Home', segment: 'home' },
      { component: AboutPage, name: 'About', segment: 'about' },
      { component: ContactPage, name: 'Contact', segment: 'contact' }
    ]
  })
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    AboutPage,
    ContactPage,
    HomePage,
    TabsPage
  ],
  providers: []
})
```

Can't launch the individual tabs with the tab bar.
```
<ion-tab [root]="tab2Root" tabTitle="About" tabIcon="information-circle" tabUrlPath="'/about'"></ion-tab>
```
nav to http://localhost:8100/#/about 
launches the about page, without the tab bar

also, navigating in from the root: http://localhost:8100
launches http://localhost:8100/#/about/about, which when reloaded does not resolve with the tab bar either. 

Thanks guys! Happy to create a codepen as well if needed (assumed it would have to be tested in a local browser to function).</span>

<span is-issue-template></span>

**Comment by jgw96** [comment] 2016-11-01 15:03
Hello, thanks for opening an issue with us! Note to team: i can repro this issue easily with [my pwa demo of the conf app](https://jgw96.github.io/ionic-conference-app/www/#/).

**Comment by uofmmike** [comment] 2016-11-01 15:12
@jgw96 Need any more info from me here?

**Comment by jgw96** [comment] 2016-11-01 15:32
Not at the moment, thanks!

**Comment by jgw96** [comment] 2016-11-18 21:26
Hello! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/9183. Thanks!

**Closed by jgw96** 2016-11-18 21:26 UTC
Labels: v2
