### ISSUE TITLE
V2 generator should generate TypeScript for a TypeScript project

### ISSUE THREAD

**Issue by skolade** [driftyco/ionic#5758] opened 2016-03-07 17:52 UTC
#### Short description of the problem:
First, Thanks to all the contributor of this amazing project, so excited to be learning and playing with Ionic2. My apology, I do not see this mentioned in the issue, but please fell free to close if this is a duplicate!
When generating pages or provider with Ionic2, it will be nice if the file that the code generate correspond with the project type that is typescript. 

#### What behavior are you expecting?

**Steps to reproduce:**
1. From terminal inside an Ionic2 typescript project
2. run, Ionic -g provide (providerName)
3. The generated file is not typescript type!

```
insert any relevant code between the above and below backticks
```

**Ionic Version**: 1.x / 2.x

**Browser & Operating System**: iOS / Android / Chrome

**Run `ionic info` from terminal/cmd prompt:**

```
paste output from `ionic info` here
```
➜  Adeleke ionic g provider rendition
√ Create app/providers/rendition/rendition.js

**Comment by tlancina** [comment] 2016-03-07 18:17
Thanks for the issue, this has been requested a lot and is on our roadmap. I'm going to close this as a duplicate of https://github.com/driftyco/ionic-cli/issues/753, so please track it there, thanks!

**Closed by tlancina** 2016-03-07 18:17 UTC
Labels: platform:android, platform:ios, v2
