### ISSUE TITLE
bug: ion-refresher has unexpected behaviour in nested ion-content

### ISSUE THREAD

**Issue by elaval** [driftyco/ionic#4713] opened 2015-12-05 14:47 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I have a refresher inside a content, which is inside a slide-box, which is inside another content:
-ion-content
--ion-slidebox
---ion-slide
----ion-content
-----ion-refresher 
------ion-list

When I pull to refresh, I expect a sequence of messages that communicate the progress (changing refreshing-text in the ion-refresher).  For example: "message 1", "message 2", "message 3", "message 4". But messages are not always displayed correctly (sometimes it just displays one or two message, sometimes all of them).  
Example in codepen - http://codepen.io/elaval/pen/BjaxEp

If the refresher is placed in the outmost ion-content y works perfectly (the messages always display correctly, but that´s not the location where I need it, since I need to trigger the refresh when I pull down the the list items):
-ion-content
--ion-refresher 
--ion-slidebox
---ion-slide
----ion-content
-----ion-list
Example in codeine - http://codepen.io/elaval/pen/gPOzNw

Images of right behaviour (refresher in outer ion-content)
![ptr right](https://cloud.githubusercontent.com/assets/68602/11608310/b401e0d4-9b5d-11e5-96f6-c1f86441ef84.png)

Images of wrong behaviour (refresher in inner ion-content)
![ptr wrong](https://cloud.githubusercontent.com/assets/68602/11608318/c6ac102e-9b5d-11e5-836f-cb367ea39906.png)

The wrong behaviour is not consistent (sometimes works well, sometimes works wrong).  In my real project (which was a more complex Javascript code) it almost always behaves wrong, which makes me think it is some issue related with data structures & memory (or handles that end up pointing to the wrong object).

----------------
I created a variation of the  codepen, were I create a dummy variable with a large array (to simulate use of memory in the browser).  Now the abnormal behaviour is much more frequent:

http://codepen.io/elaval/pen/pgoKQY/

  </span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-12-05 14:47
Greetings @elaval!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4713). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4713)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by elaval** [comment] 2015-12-06 09:30
My hypothesis is that since the refresher is instantiated multiple times inside the slide box, there might be some conflict with the multiple instances running simultaneously (but not sure about the specific cause).

**Comment by jgw96** [comment] 2016-03-14 20:07
Hello! Thanks for opening an issue with us, we just need a little more info from you so that we can better help you with your issue. Would you mind posting a code sample, plunkr or codepen that we can use to reproduce your issue? Also, would you mind running `ionic info` and posting the output? Thanks again!

**Comment by jgw96** [comment] 2016-04-14 16:58
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to respond back if your still having the issue! Thanks again!

**Closed by jgw96** 2016-04-14 16:58 UTC
Labels: performance, refresher

**Comment by jetwitaussi** [comment] 2016-07-21 13:32
still have this issue with ionic v1.7.16
