### ISSUE TITLE
[v2] [RFC] Events parameters are weird

### ISSUE THREAD

**Issue by biesbjerg** [driftyco/ionic#6227] opened 2016-04-19 09:10 UTC
Hi guys!

Maybe there's something I don't get, but I think the way parameters are handled by `Events` is a bit strange.

If you publish an event with a payload, subscribed listeners always receive the payloads wrapped in an array.

```
events.subscribe('my-event', (payload1, payload2) => {
    console.log(payload1); // ['some value']
    console.log(payload2); // undefined
});

events.publish('my-event', 'some value', 'some other value');
```

Wouldn't it make more sense to just send the actual payloads by supporting multiple arguments?
```
events.subscribe('my-event', (payload1, payload2) => {
    console.log(payload1); // 'some value'
    console.log(payload2); // 'some other value'
});

events.publish('my-event', 'some value', 'some other value');
```

I've made a plunker to demonstrate current behavior: http://plnkr.co/edit/ztq0RZy8E7IYhlKVOb0V?p=preview

**Comment by wli** [comment] 2016-04-19 23:49
@biesbjerg The ionic team addressed this here: https://github.com/driftyco/ionic-site/issues/544

They're in favor of leaving it as it is.

**Comment by jgw96** [comment] 2016-04-25 21:14
Hello, thanks for opening an issue with us! I am closing this as a dupe of driftyco/ionic-site#544

**Closed by jgw96** 2016-04-25 21:14 UTC
Labels: range
