### ISSUE TITLE
bug: Ionic Setup Sass Command Removes Ref To Styles.css

### ISSUE THREAD

**Issue by saniyusuf** [driftyco/ionic#3568] opened 2015-04-20 16:05 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>There is a new Ionic CLI command that come of you may not know about. It is "Ionic Setup Sass". This command does the npm install and actually sets up the Ionic SASS and overwrites your INDEX.HTML file for you such that it uses the generated css style-sheet from the SASS operation.

The problem is this command also removes the reference to the styles.css where your own custom styles live in. In an ideal world, the command should add the reference to the SASS processed ionic.app.css file without removing your referenced styles.css. Also make sense to add the file reference before your styles.css reference to ensure your custom styles are given precedence.
The problem is this command also removes the reference to the styles.css where your own custom styles live in. In an ideal world, the command should add the reference to the SASS processed ionic.app.css file  without removing your referenced styles.css. Also make sense to add the file reference before  your styles.css reference to ensure your custom styles are given precedence.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-04-20 16:06
Greetings @saniyusuf!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3568). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3568)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment] 2015-04-20 22:02
Hey @saniyusuf, this is intentional.  Once you setup SASS, it's intended that you'll edit the `scss/ionic.app.scss` file, optionally adding new imports if necessary so that SASS combines everything to maximize how efficient your output CSS can be.  It may be preferred to copy your `styles.css` file to `scss/styles.sass` and then import it in `ionic.app.scss`, but that's up to the developer's preference. For smaller apps, I edit the `ionic.app.scss` file directly.

**Comment by perrygovier** [comment] 2015-04-20 22:07
Closing since this is intended behavior. I've brought it up to @jbavari though. Maybe we can communicate this intended use of SCSS better. 

Thanks and thanks for repping us in London!  Sounds like some of us will be in your neck of the woods in Oct for AngularConnect.

**Closed by perrygovier** 2015-04-20 22:07 UTC
