### ISSUE TITLE
bug: Collection-repeat dynamic grid

### ISSUE THREAD

**Issue by knightfox1337** [driftyco/ionic#2099] opened 2014-08-28 11:07 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Trying to display a grid of images, allowing user to change them by selecting how many images per row. The collection-item-height and the collection-item-width need to change once the grid has been updated.
I have looked at $ionicScrollDelegate.resize() which doesn't help. I have also looked at the nightly builds which does work the way I wish but the function I place inside collection-item-height/width is continuously called causing performance issues. Wonder if any one can point me in the right direction.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-02-04 15:59
Greetings @knightfox1337!

I've closed this issue because my sensors indicated that perhaps it is no longer applicable--or may have already been fixed. However, if you are still experiencing this issue, please feel free to reopen it by creating a new one, and provide the following information, so that I may assist you:

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this issue occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) which replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com). The humans there would be delighted to help you.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-02-04 15:59 UTC
Labels: list
