### ISSUE TITLE
Ionic 2 RC1: Android hardware back button does not dismiss modal window

### ISSUE THREAD

**Issue by daveshirman** [driftyco/ionic#8751] opened 2016-10-17 08:46 UTC
#### Short description of the problem:
The hardware button in Android is not dismissing modal windows since RC 1

This case needs reopening: #7572

#### What behavior are you expecting?
Modals to be dismissed.

**Steps to reproduce:**
1. Open an app which then opens a modal window on the stack.
2. Open the modal.
3. Press hardware back button and notice that the window is still there (note the app will exit if there was no other prior navigation from the root page).

**Comment by comfortme** [comment] 2016-10-17 11:49
possible dup. of https://github.com/driftyco/ionic/issues/8692

**Comment by jgw96** [comment] 2016-10-17 15:38
Hello @daveshirman , thanks for opening an issue with us! I am going to close this issue as a duplicate of #8692 .

**Closed by jgw96** 2016-10-17 15:38 UTC

**Comment by LwaziV** [comment] 2017-05-16 14:02
Hello @jgw96 , has this issue been solved yet for RC 1 , i'm struggling with this hardware backbutton. thanks
