### ISSUE TITLE
bug: ionic 1.0 / Native scrolling for Android makes keyboard hide input field

### ISSUE THREAD

**Issue by mica16** [driftyco/ionic#3727] opened 2015-05-14 09:17 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>Using ionic 1.0 release and a basic form, when clicking on an input field, the keyboard is opened and hides all the input field. There's no automatic scroll.

It's annoying since the user can't even scroll at all (the screen is locked) to show the field.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-05-14 09:17
Greetings @mica16!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3727). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3727)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by lastikas** [comment] 2015-05-15 19:34
This is really an issue.

The keyboardFocusIn function in keyboard.js disables touch events after the keyboard is shown causing the scroll to 'freeze'
It would be nice not to do that, a possibility I tested was to involve the 'offending' block in a if statement like this: 

```javascript
  if (!ionic.DomUtil.getParentOrSelfWithClass(self.el, 'overflow-scroll')) {
    // any showing part of the document that isn't within the scroll the user
    // could touchmove and cause some ugly changes to the app, so disable
    // any touchmove events while the keyboard is open using e.preventDefault()
    if (window.navigator.msPointerEnabled) {
      document.addEventListener("MSPointerMove", keyboardPreventDefault, false);
    } else {
      document.addEventListener('touchmove', keyboardPreventDefault, false);
    }
  }
```

But this only solves the frozen scroll problem. There's still the auto scroll to the focused input problem.
This happens because the scrollChildIntoView is assigned to NOOP, which does nothing, as seen in scrollViewNative.js in the __initEventHandlers function

```javascript
     // should be unnecessary in native scrolling, but keep in case bugs show up
     self.scrollChildIntoView = NOOP;
```
I'm trying to come up with something but it's kinda tricky

In my opinion this is a major issue that renders native scroll impossible to use in production right now

**Comment by felquis** [comment] 2015-05-15 20:34
:+1: There's also a post in the forum http://forum.ionicframework.com/t/keyboard-issue-with-ionic-v1-0-0/24907

**Comment by mathiasmuller4sh** [comment] 2015-05-22 08:14
Same issue with android L 5.1.1

**Comment by Leftyx** [comment] 2015-05-26 16:01
Same issue here with android 5.1 (Nexus 5).

**Comment by tobbbe** [comment] 2015-06-09 15:39
Any solution to this? Will it be fixed in 1.0.1? I dont want to remove native scrolling because its too good :)

**Comment by felquis** [comment] 2015-06-09 16:10
Tobbe which version are you using?
Em 09/06/2015 12:40, "Tobbe" <notifications@github.com> escreveu:

**Comment by mica16** [comment] 2015-06-09 16:12
@felquis 1.0.0 has the bug

**Comment by tobbbe** [comment] 2015-06-09 16:13
Yup I'm on 1.0.0

**Comment by mica16** [comment] 2015-06-09 16:18
Native scrolling is the best feature on the 1.0.0.
Can't use it because of this critical bug ;)

**Comment by felquis** [comment] 2015-06-09 16:23
Thanks, is this still in the nightly build?  :/
Em 09/06/2015 13:13, "Tobbe" <notifications@github.com> escreveu:

**Comment by perrygovier** [comment] 2015-06-12 21:04
@tlancina, you were looking in to something like this, right?

**Comment by tlancina** [comment] 2015-06-15 13:56
Keyboard stuff relies heavily on JS scrolling, if you guys disable the Ionic keyboard code with ionic.keyboard.disable() do you still have issues?

**Comment by mica16** [comment] 2015-06-15 13:58
@tlancina I will test it right now and let you know :)

**Comment by mica16** [comment] 2015-06-15 14:40
I tested with ```ionic.keyboard.disable();``` as suggested.
Same result => doesn't solve the issue

**Comment by jacargentina** [comment] 2015-06-15 16:58
I'have an urgency for this to be solved too: if i can help somehow?

**Comment by mica16** [comment] 2015-06-15 17:00
@jacargentina I've not found a fix or workaround yet...

**Comment by jacargentina** [comment] 2015-06-15 17:36
Hope this helps: debugging it seems that **scrollChildIntoView** is invoked, but it's neved executed for a given input

**Comment by jacargentina** [comment] 2015-06-15 17:50
ionic.views.ScrollNative does this:
    self.scrollChildIntoView = NOOP;

I'm not aware on the differences on behaviour of having jsScrolling(true) vs. jsScrolling(false), but i think maybe in this case **scrollChildIntoView** should do the needed work?

**Comment by jacargentina** [comment] 2015-06-15 18:19
#3393 is a duplicate of this

**Comment by lastikas** [comment] 2015-06-15 19:04
I haven't had the time to follow this and the forum' thread for a while now

Please test this fix suggestion, and let me know if it solves the problem without causing others
http://forum.ionicframework.com/t/keyboard-issue-with-ionic-v1-0-0/24907/16?u=lastikas

**Comment by jacargentina** [comment] 2015-06-15 20:18
@lastikas It works, but have 2 little things to make it nicer:

1. The input is not visible until you press a key after the initial focus
2. When pressing that first input key, there is a ugly visual effect which makes all the view to be "crushed" by some ms. and then it goes back to normal

**Comment by tlancina** [comment] 2015-06-15 20:23
If someone wants to post a minimal test case on codepen I'll take a look. scrollChildIntoView shouldn't be called if `keyboard.disable()` is used, and the web view should just scroll the input into view.

**Comment by mica16** [comment] 2015-06-15 22:48
@tlancina Actually, when you set `ionic.keyboard.disable()`, you can scroll while you have the keyboard opens. That's good but that's not the point of the issue.  
What we would like is to prevent input text to be hidden by the keyboard.
An automatic scroll should happen so that the input remains visible, so that we can control what we type.

**Comment by jacargentina** [comment] 2015-06-16 12:45
@lastikas I think your code is very close to be the solution to this; if you had some time to fix the 2 observations i made before would be super!

**Comment by felquis** [comment] 2015-06-16 15:03
@tlancina I made a codepen http://codepen.io/felquis/pen/aOyYEZ/ --> to open in your phone http://s.codepen.io/felquis/debug/aOyYEZ

I also created a repository git@github.com:felquis/scroll-bug-3727.git

How to reproduce: 
1 - Open app
2 - Scroll I little
3 - Click in any lego item
4 - Here is the form, scroll a little
5 - Now click to focus an input
6 - The scroll is lost, you can't scroll, and the keyboard isn't open.
7 - To be able to scroll, focus the first input and leave the first input
8 - Now you can scroll again

Hope it help you.

**Closed** 2015-06-18 22:00 UTC
Labels: scroll

**Comment by vasumahesh1** [comment] 2015-06-19 12:25
Hey Guys,

So is this fixed? How can I get these changes on my current project? - Sorry a bit noob here and facing this issue.

**Comment by mica16** [comment] 2015-06-19 12:28
bower install ionic   :) 

Make sure your bower.json targets master branch.

**Comment by felquis** [comment] 2015-06-19 13:07
I testes it yesterday, there's a 1s delay on Android to start scroll to
input. Something huge happens on touchend, and it take almost 1s to start
scroll.

Also there's some warnings "forced synchronous renderings"

But it's fixed. And works fine.

I tried to save de timeline recorded with DevTools, but looks like there's
a bug I'm unable to save and make a detailed report about performance in
this case.
Em 19/06/2015 09:29, "Michael AZERHAD" <notifications@github.com> escreveu:

**Comment by tlancina** [comment] 2015-06-19 14:03
@felquis if it's an older Android device that's normal, since the actual web view doesn't report its correct size right away (and by right away I mean it takes upwards of 1s on some older devices) once the keyboard has opened.  That "something huge" is quite possibly just the keyboard appearing.

Thanks for profiling it, there is so much stuff happening it's a challenge to adjust for the keyboard coming up and still get scrolling at 60fps in a way that will work reliably and quickly across devices.

If you're seeing significant lag on a modern Android device let me know or open a new issue with what device you're seeing it on and a simple codepen reproducing it and I'll take a look.

**Comment by felquis** [comment] 2015-06-19 16:03
Thanks @tlancina, I use Android 4.4.4, Moto X G1, chromium 33. It is probably faster in modern webviews :)
