### ISSUE TITLE
Unable to select checkboxes in iOS 10

### ISSUE THREAD

**Issue by cocowalla** [driftyco/ionic#11675] opened 2017-05-15 13:18 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Unable to select `ion-checkbox` components in iOS 10. The selected state does not change, and there is no feedback of any kind, or any console logs that may help.

**Expected behavior:**
Tapping an `ion-checkbox` should toggle the selected state.

**Steps to reproduce:**
Try the following code on iOS 10 (haven't got any devices with iOS < 10 to test on, so unsure if this is limited to 10).

**Related code:**

```
<ion-label>Test</ion-label>
<ion-checkbox></ion-checkbox>
```

**Other information:**
Tried upgrading to `ionic-angular` 3.2.1, and all Angular deps to 4.1.0 - same issue.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic Framework Version: 3.1.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.7
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v5.11.1
Xcode version: Not installed
```

**Comment by jgw96** [comment] 2017-05-15 15:42
Hello, thanks for using Ionic. Unfortunately, we cannot reproduce this issue, would you mind posting a minimal repo or plunker we could use to reproduce this? Thanks!

**Comment by cocowalla** [comment] 2017-05-15 20:49
I just spun up a new Ionic app using the sidemenu template, set dependencies to the same version as my app, implemented `OnInit`, displayed a `Loading` - everything I can think of that my app might do - and I can't reproduce there either.

Do you have any idea where I should be looking to find out why this is happening?

**Comment by chandanch** [comment] 2017-05-16 03:24
I'm not able to reproduce this issue on iOS 10

**Comment by cocowalla** [comment] 2017-05-17 09:51
I have the app using 3 modules, Angular 2 style: `CoreModule`, `SharedModule` and `AppModule`. I was doing `IonicModule.forRoot(MyApp)` in `CoreModule` as well as in `AppModule` - removing this from `CoreModule` has fixed this issue.

This is *weird* though. Any idea why this would cause the problem?

**Comment by jgw96** [comment] 2017-05-17 15:00
@cocowalla , while this is admittedly a little weird, it does make sense as in this case you would be setting the root twice to the same page, which is not something you would want to do. I am going to close this issue for now.

**Closed by jgw96** 2017-05-17 15:00 UTC
Labels: needs info, v3

**Comment by cocowalla** [comment] 2017-05-17 18:34
> it does make sense

I think it would make sense for something to go wrong, sure. But everything was OK on Android, and the only thing wrong on iOS was not being able to select checkboxes - is there no way a meaningful error could be raised if you try to set the root more than once to the same page?

**Comment by IvanLencina** [comment] 2017-10-30 19:15
@cocowalla  I was facing the same issue with in my case, we were calling two times `IonicModule.forRoot`  : 

```
IonicModule.forRoot(MyApp, {
    activator: 'highlight', //Pressing effect buttons
    iconMode: 'md',
    menuType: 'overlay',
    modalEnter: 'modal-slide-in',
    modalLeave: 'modal-slide-out',
    mode: 'md',
    pageTransition: 'md',
    swipeBackEnabled: true
}),
IonicModule.forRoot(MyApp, {
    scrollAssist: false,
    autoFocusAssist: false
}),
```

On Android it was working but not on IOS. 
Thank you!! thanks to your comment, I checked my app.module and I could find this, otherwise I would not have imagined why this was happening
