### ISSUE TITLE
Flickering when using $ionicScrollDelegate.$getByHandle('').scrollTo()

### ISSUE THREAD

**Issue by seasonstar** [driftyco/ionic#4863] opened 2015-12-24 09:09 UTC
Type: bug

Platform: iOS 9.2

After upgraded to Ionic 1.2.1,  I got flickering and bad animation when clicked a in ion-scroll. 
And the scrollbar-x="false" does not work. 

here is the code:
html:
ion-scroll direction="x" scrollbar-x="false" id="category-scroll" delegate-handle="cateScroll"

controller.js:
$ionicScrollDelegate.$getByHandle('cateScroll').scrollTo(Math.abs(leftStr), 0, true)

When I downgrade to Ionic 1.1.1, everything works fine.

**Comment by Ionitron** [comment] 2015-12-24 09:09
Greetings @seasonstar!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4863). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4863)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment] 2015-12-30 04:16
Do you have a demo? Just tried this and not able to reproduce the flickering, etc.

**Comment by seasonstar** [comment] 2016-01-05 14:29
It works fine at Ionic 1.2.4. The problem has been solved.

**Closed** 2016-01-05 14:30 UTC
