### ISSUE TITLE
ion-header position is wrong when page is pushed from a modal

### ISSUE THREAD

**Issue by tmvnk** [driftyco/ionic#10444] opened 2017-02-14 23:07 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.01**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Push a page from a modal page with this.nav.push(NotificationsPage) and page has a header without padding. Display under the native iOS statusbar.

<img width="321" alt="48e88c44-f2ff-11e6-8abc-f8f1dc718815" src="https://cloud.githubusercontent.com/assets/5411385/22953816/148b49b4-f313-11e6-8a7b-7567f08d08de.png">

**Expected behavior:**
Push a page from a modal page with this.nav.push(NotificationsPage) and page has normal header. With the iOS statusbar not mixing with the Ionic header.

**Steps to reproduce:**
Open a Modal and then Push a new Page from the Modal.

**Related code:**

**Other information:**
iOS only.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

insert the output from ionic info here
Cordova CLI: 6.5.0
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.1
ios-sim version: 5.0.6
OS: macOS Sierra
Node Version: v7.5.0
Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by jgw96** [comment] 2017-02-15 13:44
Hello, thanks for using Ionic! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/8151. Thanks for using Ionic!

**Closed by jgw96** 2017-02-15 13:44 UTC
