### ISSUE TITLE
v2 - floating labels don't display in iOS/Safari in Beta.4

### ISSUE THREAD

**Issue by jasonwaters** [driftyco/ionic#6109] opened 2016-04-10 22:37 UTC
see this discussion thread in the forum: https://forum.ionicframework.com/t/ios-floating-labels-not-shown-after-upgrade-to-beta-4/48838/4

@brandyscarney

**Comment by thiphariel** [comment] 2016-04-11 12:54
I'm just adding that it's not only floating, but ```stacked```are not displayed neither.

**Comment by brandyscarney** [comment] 2016-04-11 14:25
Thanks for the issue! This will be fixed with the release of 2.0.0-beta.5.

As a temporary workaround until then, you can add the following css to your app (after the Ionic import):

```
ion-label[stacked],
ion-label[floating] {
  flex-basis: auto;
}
```

For example, you could have a global Sass file at `theme/app.global.scss` containing the above css, and then import that file in your `theme/app.core.scss` file:

```
// App Shared Imports
// --------------------------------------------------
// These are the various page imports which make up this app.
// By default each design mode includes these shared imports.
// App Shared Sass variables belong in app.variables.scss.

@import "./app.global";
```

I'll add this to the forum post, as well. :smile:

**Closed by brandyscarney** 2016-04-11 14:25 UTC
Labels: bug

**Comment by thiphariel** [comment] 2016-04-11 14:27
Thanks for the tempo fix !
Le lun. 11 avr. 2016 à 16:26, Brandy Carney <notifications@github.com> a
écrit :

**Comment by mattlanham** [comment] 2016-04-12 19:16
👍

**Comment by keithdmoore** [comment] 2016-04-12 23:53
:+1:

**Comment by jasonwaters** [comment] 2016-04-21 20:59
I hate to be the bearer of bad news, but it looks like this is not fixed in beta.5.  Instead the labels appear blurred out:

![labels](https://cloud.githubusercontent.com/assets/427213/14724143/9faa007c-07d1-11e6-9bb4-770409674ab7.gif)

**Comment by brandyscarney** [comment] 2016-04-21 21:21
@jasonwaters I created a new issue for this, it's being caused by something other than this issue. Thanks for bringing it up, I'll add more here: https://github.com/driftyco/ionic/issues/6272
