### ISSUE TITLE
bug: "ionic" scroll doesn't work inside ion-content

### ISSUE THREAD

**Issue by e-oz** [driftyco/ionic#4539] opened 2015-10-19 18:01 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Not sure how it's not found yet:
http://codepen.io/evgeniyoz/pen/ojpvyx?editors=100

It's critical bug for some of your users.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-10-19 18:01
Greetings @e-oz!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4539). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4539)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment] 2015-10-19 20:21
That's not really how you should be doing things though. 
One the ion-content has been rendered, if you change the content, you need to call `$ionicScrollDelegate.resize()`, which we've documented here 
http://ionicframework.com/docs/api/service/$ionicScrollDelegate/

Plus, you shouldn't be putting a ui-view inside of a ion-content. The ion-content should be a child of the view.

Closing this as it's not an issue with the framework.

**Closed by mhartington** 2015-10-19 20:21 UTC

**Comment by e-oz** [comment] 2015-10-19 20:33
> you shouldn't be putting a ui-view inside of a ion-content. The ion-content should be a child of the view

Worth to document.

Do you really think developers can predict all events which will change size of the rendered content and put ".resize()" patches for each of them?

"Cool" way to fix bugs.

**Comment by e-oz** [comment] 2015-10-19 20:35
And think about pages with multiple ui-views, where ion-content really expected to be a parent frame, not only nested.

**Comment by mhartington** [comment] 2015-10-19 20:49
That not the purpose of ion-content

>The ionContent directive provides an easy to use content area that can be configured to use Ionic's custom Scroll View, or the built in overflow scrolling of the browser.

>If there is any dynamic content inside the ion-content, be sure to call .resize() with $ionicScrollDelegate after the content has been added.

The ion-content is not intended to load views, but be a child of the ion-view. 

And, no dev's can't predict all the time data will change and the scroll view will need to be updated. Which is why we update the scroll view periodically from inside the directive. But cases like this, the developer needs to call the resize method themselves, since it's such a specific use case. 

I will note that the second scroll view does resize if you try to scroll around inside of it, the ion-content does resize.

This is not an issue with ionic, but just how the demo is setup. If you remove the ion-content inside the main area and just add them to the template, the problem is fixed.

http://codepen.io/mhartington/pen/XmVbXy?editors=101

**Comment by e-oz** [comment] 2015-10-19 21:08
Thanks for detailed explanation.
My app consist from few nested mini-apps, so I was using ion-content inside each of such app. Workaround is even easier - just add  `overflow-scroll="true"` and problem solved. Issue wasn't found during testing, because sometimes forms becomes very long not because some content was loaded, but just because user added too much data into a form and you can't predict when to .resize(). So this issue was "found" on the conference (where this app was supposed to be used), on Saturday and I spend around 3 hours to just find why the heck autoscroll="true" doesn't work, why .scrollTop = 0 doesn't work, why anchorScroll() doesn't work...
I still disagree it's not Ionic issue, but I don't see any point in arguing about it.
Thanks for codepen also, I'll get rid of ion-content as you did it in example.

**Comment by ruckus** [comment] 2017-05-18 17:02
I'm having this same issue with Ionic2. I'm fetching dynamic content and need to have my `ion-scroll` container resize itself. In Ionic1 I could call the scroll delegate `resize()` but this appears to no longer be available in Ionic2 and the `IonScroll` class itself lacks a method.

How to solve this problem with Ionic2?
