### ISSUE TITLE
Modal not visible on Chrome Desktop using md Theme

### ISSUE THREAD

**Issue by waybackrider** [driftyco/ionic#7391] opened 2016-07-21 14:26 UTC
Showing a Modal in Chrome Desktop (other Browsers as well as Android working well) in not visible but clickable. 
The cause is the .modal-wrapper CSS Class in modal.md.scss and the setting:

`opacity: .01;`

Changing to

`opacity: 1;`

fixes this Problem.
Whats the Reason for .01 ?

**Comment by jgw96** [comment] 2016-07-21 14:33
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by brandyscarney** [comment] 2016-07-21 18:54
This seems to be the same issue as https://github.com/driftyco/ionic-site/issues/690 but I haven't been able to reproduce it.

**Comment by waybackrider** [comment] 2016-07-25 14:20
So, after some research i am able to create a reproduceable Scenario, its very special and i think it's completey Chrome related, if you care anyway, here are the steps and Code in Plunker:

http://plnkr.co/edit/C3bwohfgXQfOdb5BJgGr

First of all, it can't be reproduced directly in Plunker, so you have to make a project on disk using this code and "ionic serve"

Then: 
1. Click on one of the Test-Items -> Modal comes up, Click on one of the Detail-Items, Modal closes, ok.
2. Enable Dev-Toolbar in Chrome, enable Device-Toolbar and choose e.g IPad. Click the same Items, it still works!
3. Refresh the Page (thats key), try to click the Items, no Modals shown anymore (or opacity: 1 not set anymore)

If you enable Device-Mode before browsing the Page, its even the same.

Chrome-Version tested: 52.0.2743.82 m (64-bit)

**Comment by jgw96** [comment] 2016-07-25 20:04
Hello @waybackrider . After trying this myself I am unfortunately having issues reproducing this issue. Could you make a screencast of the issue you are seeing? Also would you mind trying in safari and see if you can reproduce the issue there too? Thanks!

**Comment by waybackrider** [comment] 2016-07-26 06:58
Hi @jgw96, i forgot to save the Plunker so the closing of Modal was missing, but its not relevant.
As this issue only concernes MD-Design i have to exlipitly browse it using `/?ionicmode=md`, in IOS-Mode everything is working fine!
Let me know if it helps, if not i'm trying to make a screencast

**Comment by waybackrider** [comment] 2016-07-26 07:13
by the way, i was also able to reproduce it on Safari on MacOS, only with MD-Design!

**Comment by jgw96** [comment] 2016-07-26 14:14
@waybackrider does this happen when the app is deployed to a device?

**Comment by waybackrider** [comment] 2016-07-26 14:36
@jgw96 no, ist entirely Desktop-related! But quite annoying for dev/testing, helpfully the workaround works.

**Comment by jgw96** [comment] 2016-07-28 20:55
Hello @waybackrider could you try platform=android instead of ionicmode=md and see if that works for you? Thanks!

**Comment by MrBokeh** [comment] 2016-08-06 10:23
I can confirm that ionic 2 modal has issue with transparency on Web with the latest beta 11 (which works fine on iOS like beta 10). It was working before until i update typescript, cordova and ionic which mean the newer versions has a glitch.

Here is my ionic info:
```
Cordova CLI: 6.3.0
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.36
Ionic App Lib Version: 2.0.0-beta.19
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.4.7
Xcode version: Xcode 7.3.1 Build version 7D1014 
```

**Comment by jgw96** [comment] 2016-12-29 21:27
Hello @MrBokeh ,  I can confirm that this has been fixed as of RC4, I am going to close this issue for now. Thanks for using Ionic!

**Closed by jgw96** 2016-12-29 21:27 UTC
Labels: v2
