### ISSUE TITLE
bug: "TypeError: Cannot read property 'scrollTo' of null" in 1.1.1

### ISSUE THREAD

**Issue by mobidev111** [driftyco/ionic#4665] opened 2015-11-24 15:06 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Ionic: 1.1.1

simplified sample:
```
<ion-view>

  <!-- content -->
  <ion-pane scroll="false">
  </ion-pane>

</ion-view>
```

fails with: 
```
"TypeError: Cannot read property 'scrollTo' of null"
```

at:
```
  self.scrollTop = function(shouldAnimate) {
    self.resize().then(function() {
      scrollView.scrollTo(0, 0, !!shouldAnimate);
    });
  };
```

--> solution: check for scrollview to be not null or prevent the root cause of this exception</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-11-24 15:06
Greetings @mobidev111!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4665). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4665)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mobidev111** [comment] 2015-11-24 15:10
probably related:
https://github.com/driftyco/ionic/issues/3136

**Comment by petehouston** [comment] 2015-11-25 17:19
Cannot reproduce this. Could you elaborate?

**Comment by mlynch** [comment] 2015-12-07 06:11
This was fixed in a recent commit today. Will be live in 1.2 Thanks!

**Closed by mlynch** 2015-12-07 06:11 UTC
