### ISSUE TITLE
bug: ionicLoading button can't be clicked in modal

### ISSUE THREAD

**Issue by clawish** [driftyco/ionic#3615] opened 2015-04-25 10:14 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Please take a look at [this codepen](http://codepen.io/clawish/pen/vOEOxe?editors=101) and proceed as follows to reproduce this bug (which is bothering me very much, since I need the functionality):

1. Click showModal
2. Click showLoad()
3. Try to click on Cancel, see it does not react.

**It does not react: This is the bug I am reporting hereby.**

Now the strange part comes, start the codepen over and proceed as follows:

1. Click showModal
2. Click showSecondModal()
3. Click hideSecondModal()
4. Click showLoad()
5. Click Cancel and see **it does work now**

What the heck happens in the first case, and how can I fix the button to react without the need to show/hide the second modal?!
Thank you for your fix (and your eventual workaround)!</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-04-25 10:15
Greetings @clawish!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3615). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3615)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment] 2015-05-08 20:47
So situation 1 is actually the intended behavior. Situation 2 is an error with multiple modals and backdrops messing with our click block. This would require a rework of our backdrop and modals, which is slated for post 1.0.

**Comment by jgw96** [comment] 2016-04-29 18:28
Hello all! Going to close this issue as it has been a while since there was any activity on it. Thanks for using Ionic and feel free to comment if your still having this issue and i will reopen.

**Closed by jgw96** 2016-04-29 18:28 UTC
Labels: v1

**Comment by xfally** [comment] 2016-07-01 04:38
@mhartington You said "So situation 1 is actually the intended behavior", but if so, how can i implement the scene below:
1. Open one photo browser (ionModalView + ionSlideBox), which can slide one by one.
2. When browser one page (ionSlide), start to show loading animation ($ionicLoading) and request photo from remote server.
3. If gotten, automatically hide loading and show photo.
4. If wait for too long, user can click "Cancel" button to hide loading and stop the request.
Expecting your reply and many thanks!
