### ISSUE TITLE
Issue with VirtualScroll and Images Popping In and Out

### ISSUE THREAD

**Issue by thomascrown** [driftyco/ionic#6567] opened 2016-05-18 16:10 UTC
Implemented a simple VirtualScroll setup:

In my home.html:

```
<ion-navbar *navbar>
  <ion-title>Test 2</ion-title>
  <ion-buttons end>
    <ion-row>
      <ion-col width-50><button>Test</button></ion-col>
      <ion-col width-50><button menuToggle><ion-icon name="menu"></ion-icon></button></ion-col>
    </ion-row>
  </ion-buttons>
</ion-navbar>
<ion-content style="background:transparent; z-index:5;">
    <ion-list [virtualScroll]="items" [bufferRatio]="4" [approxItemHeight]="'500px'" [approxItemWidth]="'100%'" [approxHeaderHeight]="'0px'" [approxFooterHeight]="'0px'">
      <ion-item *virtualItem="#item">
        <ion-row>
          <ion-col width-50><ion-img [src]="item.avatarUrl" style="height:100px;"></ion-img></ion-col>
          <ion-col width-50><ion-img [src]="item.avatarUrl" style="height:100px;"></ion-img></ion-col>
        </ion-row>
      </ion-item> 
    </ion-list>
</ion-content>
```
And in home.ts I create the list like this:

```
for(let i = 0; i < 2000; i++){
            let item = {
                title: 'Title',
                avatarUrl: 'url_for_random_img'+i,
                body: 'body'
            };
        
            this.items.push(item);
}
```

**First Problem:**
When the page loads, all the images are initially blank. They don't load until you start scrolling. Shouldn't the default behaviour be that it displays the first set?

**Second Problem:**
Once you start scrolling, and images have loaded, scrolling back up over previously loaded images seems to load a small portion of the image, making it look like the image partially loaded and then errored. Only when scrolling stops does it instantly repalace this partially loaded image with the rest of the image. Since it happens so fast, I'm assuming that VirtualScroll knows it has an image there, but stops loading because you are still scrolling... Any way to change this? switching the entire photo in shouldn't be too taxing on the resources...

There is also some slight lag in getting new photos... perhaps previous calls are not being cancelled when they are no longer in view?

Here is a video of what Im talking about: https://www.dropbox.com/s/35vqxqmeh1wadwu/ionic2.0.0-beta25-VirtualScroll%20Issue%201.mp4?dl=0

Replicated this on both android and ionic serve through chrome...

Cordova CLI: 6.0.0
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS:
Node Version: v4.2.6

**Comment by ghenry22** [comment] 2016-06-01 05:12
ion-img actually seems completely broken in beta7.  No long loads any images outside of the initial view port for me.

**Comment by adamdbradley** [comment] 2016-06-10 16:57
This should be fixed in the next release. A large part of the problem is how ion-img didn't have overflow hidden on it.

**Closed by adamdbradley** 2016-06-10 16:57 UTC
Labels: v2, virtualscroll
