### ISSUE TITLE
Native IOS select list layout issue

### ISSUE THREAD

**Issue by trankevin** [driftyco/ionic#6640] opened 2016-05-24 14:48 UTC
I've got a regular multiple select list and the native select list that pops up in IOS looks like this the screenshots below. Any idea how to fix or why this is happening?

*Multiple select*
![screen shot 2016-05-24 at 10 39 19 am](https://cloud.githubusercontent.com/assets/7633905/15508017/dbad1012-219b-11e6-8d78-436a32ae6767.png)

*Single Select*
![screen shot 2016-05-24 at 10 39 32 am](https://cloud.githubusercontent.com/assets/7633905/15508016/dbaa8dc4-219b-11e6-96d5-2dc4dd4734ec.png)

**Comment by jgw96** [comment] 2016-05-24 15:13
Hello! Thanks for opening an issue with us! Sorry, but I'm a little confused, is this an issue with the ion select element?

**Comment by trankevin** [comment] 2016-05-24 15:28
Hey, I do not think that it's an issue with the select element but possibly how the select is being handled by either ionic or ios? I am not using v2 of ionic so i'm actually not using the ion-select element just a regular html select, if there's a difference. I believe it's the native select list that pops up when i select the HTML select in my app. 

Hopefully that explains my issue a bit better, thanks!

**Comment by jgw96** [comment] 2016-05-24 15:38
Ahh, ok now i understand perfectly. Thanks for clearing that up! So, does this happen with a select element on a regular webpage? Or even just a plain angular app running in cordova?

**Comment by trankevin** [comment] 2016-05-24 15:41
This happens when running a regular angular ionic app on IOS emulators and actual devices. Does not happen with android as it has a different select popup.

**Comment by jgw96** [comment] 2016-05-24 15:47
So, just to be sure, it only happens with an ionic app? A select element in a regular webpage in safari is fine?

**Comment by trankevin** [comment] 2016-05-24 15:49
Only in an ionic app on IOS :)

**Comment by jgw96** [comment] 2016-05-24 15:59
@trankevin could you throw this into a plunker i could test please? Thanks!

**Comment by trankevin** [comment] 2016-05-24 16:38
@jgw96 It's part of a full ionic app .. I could possibly pull out just the select list but the issue is only on IOS devices and emulators so don't think it would show up on a webpage. Was more wondering if this issue has ever come up before or if it's possible to style the native ios select list?  ( I couldn't find anything ) Might not even be an issue with ionic but figured I'd ask anyways.

**Comment by jgw96** [comment] 2016-05-24 16:44
Hmm, im having trouble reproducing with my iphone 5. As far as i know it is impossible to style the native select list as it is a native component and not an html component. Which version of ios are you running?

**Comment by trankevin** [comment] 2016-05-24 16:49
@jgw96 Ah weird.. I don't think my I've got anything crazy in my select lists either. I'm running ios 9.0 btw.  I appreciate you trying it out! I think I'll try setting up a test project and see if I get the same issue.

**Comment by jgw96** [comment] 2016-05-24 18:12
No problem! (: Alright awesome, tell me what you find please!

**Comment by jgw96** [comment] 2016-05-31 07:18
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-05-31 07:18 UTC
Labels: needs reply, platform:ios, v1

**Comment by fenglu09** [comment] 2016-10-08 03:13
@trankevin  I face the same issues too. And I finally found that, it was caused by the css style.
In ionic css, `.item-select select` class set `direction:rtl`. If I set the `direction` to others, the select style will change.

**Comment by OBatistaE** [comment] 2017-10-06 11:50
I'm having the same issue. Please help me. Thanks in advance.
