### ISSUE TITLE
ionic popover items have no tap effect with ng-click

### ISSUE THREAD

**Issue by PureSpider** [driftyco/ionic#2968] opened 2015-01-20 16:59 UTC
However, with ng-href and ui-sref they do.

**Comment by Ionitron** [comment] 2015-02-07 05:31
Greetings @PureSpider!

My sensors indicate that I require more information in order to assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this happen occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com), where many humans will be able to offer wisdom and advice.

Thank you for allowing me to assist you.

**Comment by PureSpider** [comment] 2015-02-17 09:39
Here is a codepen showcasing the issue on android (seems to work fine on iOS): http://codepen.io/anon/pen/QwmLJZ
The lighter background is missing from the item with ng-click and it has no tap effect.

**Comment by perrygovier** [comment] 2015-04-01 16:15
Ah, ok. So it's a display thing, not that the event isn't firing. Thanks. 
Note to self: the activated class isn't being applied to elements in the android popver style that have ng-click attributes.

**Comment by adam-back** [comment] 2015-06-30 19:52
@perrygovier, did we ever get the grey background issue fixed with ng-click?

**Comment by jgw96** [comment] 2016-05-17 14:56
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by PureSpider** [comment] 2016-06-07 06:38
If the codepen is still relevant (assuming the URLs didn't change) then yes, it's still an issue.

**Comment by cristiammercado** [comment] 2016-12-20 03:26
What happened with this issue?

**Comment by jgw96** [comment] 2017-01-13 20:35
This issue was moved to driftyco/ionic-v1#3

**Closed by jgw96** 2017-01-13 20:35 UTC
Labels: css, platform:android, popover, v1
