### ISSUE TITLE
bug: $ionicmodal broke ion-view with map

### ISSUE THREAD

**Issue by thiagoaos** [driftyco/ionic#3233] opened 2015-03-04 21:21 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>http://codepen.io/thiagoaos/pen/RNBJWE

When i go with another page (page1), open a modal (login) and go back to map page, the map view broke (resize to a smaller sizer). If i don´t open a modal work fine, or if i open a modal in map page works fine too.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-03-04 21:21
Greetings @thiagoaos!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3233). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3233)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by thiagoaos** [comment] 2015-03-05 20:07
I change ionic modal to a regular page and the error not happend. But, when i navigate so many times happened again.

So, i think, Ionic is resizing the map div in some time.

Then i added the code below in init of the controller and fix.

$scope.$on('$ionicView.afterEnter', function(){
  if ( angular.isDefined( $scope.map ) ) {
    google.maps.event.trigger($scope.map, 'resize');
  }
});

but this feel ugly :(

Is there ionic bug? Why change the view size?

**Comment by orthodoc** [comment] 2015-03-11 14:54
+1
I am having the same problem as well.
Like @thiagoaos says, the map view is absent only if a modal is opened, and not otherwise.

**Comment by orthodoc** [comment] 2015-03-11 20:59
I was able to get it to work by adding cache-view="false" to the ion-view in the map view html file.

Not caching defeats the purpose of maintaining the navigation history, though!

**Comment by mhartington** [comment] 2015-03-12 17:40
Alright, seeing this as well. Doesn't appear in beta 14, will pass this to @adamdbradley 

http://codepen.io/mhartington/pen/YPJLvV

**Comment by orthodoc** [comment] 2015-03-19 18:17
The same behaviour persists with the 1.0.0-rc1 release as well.

**Comment by adamdbradley** [comment] 2015-03-24 19:02
Might be related: https://github.com/driftyco/ionic/commit/4f6d02cfcb2e47e199310ddd8d956b942b1e5443#diff-7b97c82fcd0b68ad5aa66de0811e7b76R151

If you comment out `ionic.trigger('resize');` it works again.

**Comment by orthodoc** [comment] 2015-03-26 18:32
@adamdbradley, I did comment out that line and removed the cache-view="false", but it didn't go away for me. Same page, one with map and the other one after opening a modal. Am using ionic rc-1, angular-leaflet and google map tiles. As far as titles go, neither are displayed!

<img src="https://cloud.githubusercontent.com/assets/302414/6853675/8f0570b0-d412-11e4-9eaf-6d776db8f3d5.png" width=300px alt="map display error">

**Comment by winstef** [comment] 2015-03-27 05:04
@adamdbradley indeed, comenting out ``` ionic.trigger('resize'); ``` did the trick for me.

**Comment by orthodoc** [comment] 2015-04-01 16:16
Possible duplicate of #3383

**Comment by valdrinkoshi** [comment] 2015-08-25 07:22
confirming the fix suggested by @adamdbradley, removing ionic.trigger('resize'); solves the issue!
I've also tried to set the leaflet map property "trackResize" to false, but that didn't help.

**Comment by valdrinkoshi** [comment] 2015-08-25 07:26
I found a fix that doesn't require to modify the ionic code: just trigger <code>ionic.trigger('resize')</code> onBeforeEnter of the view containing your map.

**Comment by mhartington** [comment] 2015-08-25 14:59
Closing since it looks like there is a solution

**Closed** 2015-08-25 14:59 UTC

**Comment by bmatto** [comment] 2015-09-20 23:51
I am having this issue, however in my case it's not a map it's a chart rendered on a canvas.  The resize event is triggering some internal redraw on the cached view, which in my case is causing an error on the cart, and subsequently the chart is no longer rendered :(.

The "fix" here does in fact redraw the chart - however i'm still seeing those pesky errors in my console whenever a modal pops up.

**Comment by MrHakala** [comment] 2016-02-09 20:31
Any other suggestions for work arounds? None of the above work for me.

**Comment by rgecy** [comment] 2016-05-10 20:54
@mhartington Just because a work-around is found does not solve the issue.  It did not fix it for me completely.  It creates an awkward experience redrawing the map, and if any infowindows are open they are not displayed properly either. My app is very much dependent on the google maps to perform correctly.

Its been very frustarting. I removed the modal completely and works great without it.  But would love to have that feature back in as well.

I think this needs to be looked at much closer!

Robert

**Comment by BioPhoton** [comment] 2016-05-22 07:55
Think too, that this is not solved yet!!! 
The current workaround is not clean at all. My Maps having lots of markers and routes which is not optimal together with this bug.

Please take a closer look at this problem.
THX!!!

**Comment by adamwlarson** [comment] 2016-06-04 02:43
I am having a similar issue but after opening up the camera the map seems to resize to an odd size. Forcing a resize event afterEnter does fix the issue for me, but it causes an unnecessary transition.

Another way to recreate it is to get the bug mentioned in issue  #6715 unfortunately the fix suggested in that bug does not solve this issue in when it happens without opening the keyboard, but I would be willing to bet it is a similar issue, and if we can track down the cause of all of these it will solve a lot of our issues.

**Comment by kperdomo** [comment] 2016-11-04 09:50
Still happening in 2.0.0. Not only with modals, but popovers and popups show the same problem.

Triggering resize on afterEnter event fixes most of the issues, at least the map can be navigated through again. Still, if you get back to a map view where a info window for a marker was being displayed, it appears all messed up (see attached image).

![captura de pantalla 2016-11-04 a las 9 48 23](https://cloud.githubusercontent.com/assets/23257099/20001428/08a1127c-a274-11e6-8a60-865ee00bea5c.png)

**Comment by jefftanz** [comment] 2017-05-22 01:44
This issue is not fixed. Still happens with google map on a modal window. Has anyone solved this?
