### ISSUE TITLE
Ionic 2 + Electron

### ISSUE THREAD

**Issue by ssreekanth** [driftyco/ionic#9050] opened 2016-11-05 16:05 UTC
Documentation talks about support for Electron here at  
http://ionicframework.com/docs/overview/#browser-support

However, I do not see any documentation or any boilerplate for Electron app using Ionic 2.

Hoping to get help from Ionic 2 team.

**Comment by spiraljacobs** [comment] 2016-11-07 09:02
Agreed.  Would really, really appreciate information on Electron support and how to develop dual apps in Ionic2.  Support seemed very promising with their announcement of first class Electron support for Beta 7, but there's been basically no mention since.  Not exactly first class support...

**Comment by jgw96** [comment] 2016-11-07 09:56
Hello all! Sorry for the confusion here. While it is totally possible right now to build an Electron app with Ionic 2, we do not currently have a build process set up for it so it requires a little bit of setup on the developer's end. After we get Ionic 2 stable out we will be looking into providing more infrastructure around using Electron with Ionic 2.

**Comment by spiraljacobs** [comment] 2016-11-07 10:04
Thanks so much for an answer, @jgw96 !  Understandable.  I currently have an Electron application that I'd like to port over to Ionic2, so any information would be fantastic.
Thanks again!

**Comment by chron0** [comment] 2016-11-19 09:49
I have something working here, it may serve others or the ionic team to save time as well:

https://github.com/apollo-ng/governess/blob/master/governess-app/electron.js
https://github.com/apollo-ng/governess/commit/13f60f8156131492c498c892703016ba25aebf1f

**Comment by ssreekanth** [comment] 2016-11-19 23:21
@chron0 I tried building app from your repo. However, when I run it, app just shows white blank page and there are no errors thrown in console too. Not sure, what worked for you.

Could you let us know the steps to build/run your app? Also, Have you tried `require('electron')` in renderer process of the electron app?

**Comment by chron0** [comment] 2016-11-20 07:29
Where exactly do you get a blank page? It works here and I was hoping an ionic2 app would be pretty much contained/constraint by its package.json. It lints/compiles without a problem here. As for electron, I do have a system wide instance of electron available (due to atom) - don't know if it makes a difference since electron should be bundled/used locally from package.json

From left to right: 

  * Dev Server/Browser
  * Electron dev (needs ionic serve running)
  * Electron build

![screenshot_2016-11-20_07-19-16](https://cloud.githubusercontent.com/assets/3270028/20461309/abf05ab2-aef1-11e6-94b4-cfddd618039b.png)

As stated in README.md:

### Run in Electron wrapper

    $ npm run electron

### Electron Build

#### Linux

    $ npm run electron-dist-linux-x64

**Comment by thierce** [comment] 2016-12-29 18:17
I am able to get an Ionic2 app in Electron working, briefly outlined here:
https://forum.ionicframework.com/t/embed-ionic-2-app-in-electron-for-desktop-application/74123

However, getting IPC to work has been a nightmare.
If there is any further on IPC implementation - I would love to hear about it.

**Comment by jgw96** [comment] 2017-02-03 15:28
Hello all! I am going to close this issue now as i cannot reproduce this anymore. For an example of Ionic 2 working in electron check out [this example](https://github.com/jgw96/electron-quick-start) i made of the conference app running in electron. The instructions on how to run it are in the readme

**Closed by jgw96** 2017-02-03 15:28 UTC
Labels: v2

**Comment by ssreekanth** [comment] 2017-02-12 17:57
@jgw96 Thank you for providing an example. Appreciate it. However, I'm still not able to use electron/node modules in renderer (ionic app) code. I have followed the instructions  from http://ionicframework.com/docs/v2/resources/third-party-libs/, but no luck.

With the following code after installing the library and its type definition,
```
import {remote} from 'electron';
..
..
console.log(remote.process.versions.electron);
```
I see the following error in console
```
Uncaught TypeError: fs.existsSync is not a function
```
Hope you have a solution for this one too.. Awaiting your response..

**Comment by ssreekanth** [comment] 2017-02-21 06:35
@jgw96 did you get a chance to look into my previous comment?

**Comment by CoreyCole** [comment] 2017-02-23 15:40
@ssreekanth [This](https://github.com/fossasia/loklak_webclient/issues/13) looks like a similar issue, maybe try upgrading your node modules like they did [here](https://github.com/fossasia/loklak_webclient/commit/80dc3799f0bf1f9927b01cfea3f6c879a6132cba)

**Comment by orlyapps** [comment] 2017-07-06 15:13
@ssreekanth you found a solution?

**Comment by atd-schubert** [comment] 2017-11-11 15:13
I made a workaround with these lines and write a service for IPC in Angular / Ionic:

*providers/ipc.ts*

```typescript
import { Injectable, EventEmitter } from '@angular/core';
function unimplemented(...args: any[]) {
    console.error(new Error("This function is not implemented"));
}
let ipcRenderer = {
    on: unimplemented,
    send: unimplemented,
};

eval(`try {ipcRenderer = require("electron").ipcRenderer;} catch(err) {console.warn(err);}`);

export interface IIpcEventEmitter {
    args: any[];
}

@Injectable()
export class IpcService {
    public ipc = ipcRenderer;

    observe(name: string): EventEmitter<IIpcEventEmitter> {
        const eventEmitter: EventEmitter<IIpcEventEmitter> = new EventEmitter();
        this.ipc.on(name, (...args) => {
            eventEmitter.emit({ args });
        });
        return eventEmitter;
    };

    send(name: string, ...args: any[]) {
        this.ipc.send.apply(this.ipc, [name, ...args]);
    }
}

```
