### ISSUE TITLE
showWhen doesn't work in browser unless platform is explicitly specified

### ISSUE THREAD

**Issue by Ulydev** [driftyco/ionic#9011] opened 2016-11-03 15:18 UTC
Hello, I'm encountering an issue with Ionic **2.1.1**.

The **showWhen** attribute works in the browser only when the platform is specified in the url (*/?ionicplatform=*), although the default theme is Material Design.

This is the line that doesn't work:
```
<ion-icon name="md-close" showWhen="android,windows"></ion-icon>
```

Without platform in URL (not working):
![Not working](http://img4.hostingpics.net/pics/415489issuenotworking.png)

With platform in URL (working, close button shows up):
![Working](http://img4.hostingpics.net/pics/842579issueworking.png)

Demo Plunker: http://plnkr.co/edit/YVSIZB3biHVBuTbDEmGN?p=preview

It's not a big deal, but I'm not sure whether this is intentional or not. Anyways, I'll have a look at it. Thanks!

**Comment by Ulydev** [comment] 2016-11-03 16:00
Ok, after reading the documentation in detail it seems like I have mixed up **mode** and **platform**. What I was looking for was a way to show an icon on one **mode** and a label on another.

It would be great to add mode checking to **showWhen**, e.g. showWhen="md"

**Comment by Ulydev** [comment] 2016-11-03 16:41
Fixed in https://github.com/driftyco/ionic/pull/9013

**Comment by brandyscarney** [comment] 2017-05-05 15:05
Thanks for the issue! I'm going to close this as a duplicate of https://github.com/driftyco/ionic/issues/6525 🙂

**Closed by brandyscarney** 2017-05-05 15:05 UTC
Labels: v2
