### ISSUE TITLE
bug: setting `can-swipe-back` to false disables side-menu swiping

### ISSUE THREAD

**Issue by RobbinHabermehl** [driftyco/ionic#3606] opened 2015-04-24 10:56 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I just upgraded Ionic to v1.0.0-rc.4 in order to utilize the newly introduced [`can-swipe-back`](http://ionicframework.com/docs/api/directive/ionView/#api) directive for `ion-view`. I've applied this directive on my home view and set it to `false`. When returning to the home view after navigating in the app this properly prevents the user from swiping back to the previous view. Unfortunately it also introduces an undesired side-effect: swiping to open and close the side-menu isn't functioning any longer. Upon launch this issue doesn't occur, just when returning to home view.

I've tried to reproduce this issue using the "[Side menu and Navigation](http://codepen.io/ionic/pen/QwamEW)" CodePen, but unfortunately I haven't succeeded.</span>

<span is-issue-template></span>

**Edit**:
For the time being I've created a workaround by clearing the app's history:

```
$scope.$on('$ionicView.enter', function() {
  $ionicHistory.clearHistory();
});
```

**Comment by Ionitron** [comment] 2015-04-24 10:56
Greetings @RobbinHabermehl!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3606). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3606)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment] 2015-04-24 21:50
Hey @RobbinHabermehl sorry, but if we can't reproduce the issue here, it's pretty difficult to fix. Do you have a project or anything you can share with us?

**Comment by Ionitron** [comment] 2015-05-24 22:00
Greetings @RobbinHabermehl!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-05-24 22:00 UTC
Labels: ionitron:closed
