### ISSUE TITLE
Fonts not copying with @ionic/app-scripts: 0.0.46

### ISSUE THREAD

**Issue by Bandito11** [driftyco/ionic#9454] opened 2016-12-02 05:27 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

This is on Windows 10 using this @ionic/app-scripts: 0.0.46 on ionic 2.1.13 on ionic rc3:

I run ionic serve this message appears
```

 copy: Error copying "D:\Projects\agri-app\node_modules\ionicons\dist\fonts" to
            "D:\Projects\agri-app\www\assets\fonts"
```

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```
This appears everytime i run ionic serve

>   copy: Error copying "D:\Projects\agri-app\node_modules\ionicons\dist\fonts" to
>          "D:\Projects\agri-app\www\assets\fonts" 

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```
I don't see anything when I run it with ionic serve --info that I didn't see before

**Comment by ataraxus** [comment] 2016-12-02 10:41
this is a duplicate of: https://github.com/driftyco/ionic-app-scripts/issues/448

**Comment by jgw96** [comment] 2016-12-02 15:43
This issue was moved to driftyco/ionic-app-scripts#504

**Closed by jgw96** 2016-12-02 15:43 UTC
