### ISSUE TITLE
FAB button does not scroll in ion-content if button is in sub component

### ISSUE THREAD

**Issue by mburger81** [driftyco/ionic#9288] opened 2016-11-22 16:25 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I create a FAB button at the bottom and the right in TestComponent which has some text and a lot of <br> to create a scrollable side. The FAB button but does not scroll down with the scroll view as expected for the button. If i declare the FAB button in the same Component where the ion-content is anything works, but if I load a subcomponent in the ion-content in this case <test></test> for TestComponent where is my FAB button, the FAB button does not scroll

**Expected behavior:**
I hope this is not expected so and not by design. The FAB button always has to scroll into his ion-content also if it is in a subcomponent.

**Steps to reproduce:**
I created a plnkr for you
https://plnkr.co/edit/U8QJ0A?p=preview

and here is a screenshot

at the beginning:
![image](https://cloud.githubusercontent.com/assets/3778892/20531926/939aab82-b0d8-11e6-9554-c1b3ade8e107.png)

after scrolling:
![image](https://cloud.githubusercontent.com/assets/3778892/20531914/896e5bcc-b0d8-11e6-9205-369489b617cf.png)

**Comment by jgw96** [comment] 2016-11-23 17:47
Hello! Thanks for opening an issue with us. I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/9279 as that issue and this issue is caused by the same underlying bug.

**Closed by jgw96** 2016-11-23 17:47 UTC
Labels: v2
