### ISSUE TITLE
virtualScroll ion-item slow click event response time.

### ISSUE THREAD

**Issue by jccf091** [driftyco/ionic#6159] opened 2016-04-14 03:31 UTC
**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
virtualScroll ion-item slow click event response time.

#### What behavior are you expecting?
ion-item click event will be call goToShowPage function immediately.
Instead, I got log after few seconds.

**Steps to reproduce:**
1. click item 
2. wait for 2~3 seconds for it to call goToShowPage function

sometimes the item will not response to the click event.

```
insert any relevant code between the above and below backticks
<ion-list [virtualScroll]="items" [headerFn]="myHeaderFn">

  <ion-item-divider *virtualHeader="#header">
    Header: 
  </ion-item>

  <ion-item *virtualItem="#item" (click)="goToShowPage(item)">
    Item: {{ item.name}}
  </ion-item>

</ion-list>

```

**Other information:**
Below code solve the click event issue.
But there is a exception when the page was unloaded.
EXCEPTION: TypeError: null is not an object (evaluating '_this._el.removeEventListener')
```
  <ion-item-group [virtualScroll]="items" [headerFn]="getItemHeader">
    <ion-item-divider *virtualHeader="#header">
      {{ header }}
    </ion-item-divider>
    <button ion-item detail-none *virtualItem="#item" (click)="goToShowPage(item)">
      {{ item.name }}
    </button>
  </ion-item-group>
```

**Which Ionic Version?** Ionic Version: 2.0.0-beta.4

Cordova CLI: 6.1.1
Ionic Version: 2.0.0-beta.4
Ionic CLI Version: 2.0.0-beta.23
Ionic App Lib Version: 2.0.0-beta.13
ios-deploy version: 1.8.5 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.9.1
Xcode version: Xcode 7.3 Build version 7D175

**Comment by biesbjerg** [comment] 2016-04-14 08:36
+1.

I see the same thing. 

My list has thumbnails to the left, if I tap them, it is registered immediately every time. However tapping anywhere else in the list item often doesn't work or it takes several seconds to respond.

I noticed this on my iOS device. Browser works fine.

**Comment by jgw96** [comment] 2016-04-14 14:39
Hey guys! So I'm thinking that this issue is called by the dreaded 300ms click delay on the iOS uiwebview. Currently we are using JavaScript to remove that 300ms delay, but it only works on elements that are traditionally clickable, such as buttons and inputs. To fix this issue I would recommend using this syntax:

`<button ion-item>click me</button>` 
That is gonna cause the ion-item to be clickable which will allow for our 300ms click delay fix on iOS (which we hope to fix permanently with wkwebview support) and for accessibility purposes screen readers will now know that that element is clickable when with just a plain ion-item they wouldn't. Thanks again! I'll go ahead and close this as this should fix the issue, but feel free to comment if it doesn't and I'll happily reopen!

**Comment by biesbjerg** [comment] 2016-04-14 15:05
This is not a 300ms delay. It is sommetider severo secoonds. Also it doesn't explain why the tap event is not always registered. Please reopen this ticket.

**Comment by biesbjerg** [comment] 2016-04-14 15:06
Sometimes several seconds*

Sorry, not able to edit comment on mobile

**Comment by jgw96** [comment] 2016-04-14 15:28
@biesbjerg Thanks for the info! Would you be able to make a codepen or plunker that demonstrates this issue please?

**Comment by biesbjerg** [comment] 2016-04-14 15:37
The code to reproduce is available in the first post of this issue. It only happens for me in the emulator or on iOS simulator, so a plunker wouldn't be of any help(?)

**Comment by biesbjerg** [comment] 2016-04-14 15:46
I meant that it happens in the simulator OR on iOS device. :-)

**Comment by jccf091** [comment] 2016-04-15 03:22
By the way, there is a exception when the page was unloaded.
EXCEPTION: TypeError: null is not an object (evaluating '_this._el.removeEventListener')

**Comment by biesbjerg** [comment] 2016-04-16 11:10
I've created a video that shows the issue in the simulator. http://cl.ly/0o0n3X3y3F0f/Screen%20Recording.mov

For completeness sake, here's my template:

```
<ion-navbar *navbar>
	<ion-title>Purchases</ion-title>
</ion-navbar>

<ion-content class="product-list">

	<ion-list [virtualScroll]="products">
		<a ion-item *virtualItem="#product" (click)="openProductDetails(product)">
			<h2 (click)="log('h2')">{{product.title}}</h2>
		</a>
	</ion-list>

</ion-content>
```

It also happens if I use ngFor instead of virtual scroll.

**Comment by biesbjerg** [comment] 2016-04-16 12:51
#6192 solves the ignored click events for me, although I can't explain why.

**Comment by jgw96** [comment] 2016-05-05 16:48
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment] 2016-05-10 14:08
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-05-10 14:08 UTC
Labels: needs reply, needs:devicetesting, platform:ios, v2, virtualscroll

**Comment by dtruel** [comment] 2016-08-03 17:59
Hi I'm still having this issue with this info:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.35
Ionic App Lib Version: 2.0.0-beta.19
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.3.1
Xcode version: Xcode 7.3 Build version 7D175 

I don't get the activated class.  Also, I opened up the inspector, and found that the list still doesn't receive clicks for 3 seconds.

**Comment by jadgsam** [comment] 2017-06-02 17:08
Hi,
I am still getting this delay with ion-item but not with button ion-item

global packages:

    @ionic/cli-utils : 1.3.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.3.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.3.0
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Cordova Platforms               : ios 4.4.0
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v7.5.0
    OS         : OS X El Capitan
    Xcode      : Xcode 8.2.1 Build version 8C1002 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13
