### ISSUE TITLE
Bug: VirtualScroll escapes NgZone

### ISSUE THREAD

**Issue by ihadeed** [driftyco/ionic#10832] opened 2017-03-18 20:24 UTC
**Ionic version:**  2.x

**I'm submitting a ...** bug report

**Current behavior:**
Opening a page from `VirtualScroll` causes the child page to escape NgZone. 

**Steps to reproduce:**
- Create a method that pushes a new page, e.g.: 
```ts
openPage(page) {
  this.navCtrl.push(page);
}
```
- Call that method from a `virtualScroll` item

See plunker example here: http://plnkr.co/edit/upZqGYgmYjf0LIJbTeQY?p=preview

**Comment by frederikschubert** [comment] 2017-03-18 23:51
Duplicate of https://github.com/driftyco/ionic/issues/10451

**Comment by manucorporat** [comment] 2017-03-19 15:24
can you provide an example that shows something not actually working because of this?

**Comment by frederikschubert** [comment] 2017-03-19 15:31
The change detection does not work as expected for components that are created outside the angular zone. Events and changes of properties that are decorated with `@Input()` do not trigger a change detection cycle anymore. This breaks components that rely on the standard change detection behavior.

**Comment by ihadeed** [comment] 2017-03-19 17:12
@manucorporat 

The example shows that the child page that was opened from a virtual scroll item, is not in Angular zone. Which means that change detection will not function at all. You will need to wrap everything with `this.ngZone.run()` in order to trigger change detection.

I haven't looked at the source code of Virtual Scroll, but I'm guessing there's a piece of code there that's causing the click event handler to be invoked outside of Angular zone.

**Comment by brandyscarney** [comment] 2017-03-22 20:07
I'm going to close this as a duplicate of https://github.com/driftyco/ionic/issues/10451 but please feel free to continue the discussion here. Thanks!

**Closed by brandyscarney** 2017-03-22 20:07 UTC
