### ISSUE TITLE
perf: Collection repeat seems to be leaking

### ISSUE THREAD

**Issue by concertcoder** [driftyco/ionic#4754] opened 2015-12-10 21:20 UTC
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>https://github.com/driftyco/ionic/issues/3999

I noticed collection repeat was leaking memory.  I saw this other issue - can someone comment on this?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-12-10 21:20
Greetings @concertcoder!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4754). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4754)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by jgw96** [comment] 2016-03-14 20:02
Hello! Thanks for opening an issue with us, we just need a little more info from you so that we can better help you with your issue. Would you mind posting a code sample, plunkr or codepen that we can use to reproduce your issue? Also, would you mind running `ionic info` and posting the output? Thanks again!

**Comment by jgw96** [comment] 2016-04-01 19:42
As it has been a little while since there was any activity on this issue I will be closing it for now, please feel free to reply if you are still experiencing this issue though! Thanks again!

**Closed by jgw96** 2016-04-01 19:42 UTC
Labels: v1
