### ISSUE TITLE
bug: Platform.ready() never fires when using Crosswalk

### ISSUE THREAD

**Issue by AviateX14** [driftyco/ionic#8984] opened 2016-11-01 21:52 UTC
**Type**: bug

**Ionic Version**:  2.x

**Platform**: android 4.1 webview

Having to support a specific API level, 16, Ionic 2 doesn't render properly at all on that, so I installed Crosswalk (latest: 2.1.0) which got the app to render, howver, as a side effect, the platform.ready() never fires, take for example the default app code of:

initializeApp() {
    this.platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      StatusBar.hide();
      //Splashscreen.hide();
    });
  }

When using Crosswalk, the StatusBar is never hidden, this happens during live reload debugging and when the app is packaged & installed on the device. When running in live reload, the console reports that the device ready is not firing.

My installed plugins are:

```
cordova-plugin-console 1.0.4 "Console"                                                                                                                                                                        
cordova-plugin-crosswalk-webview 2.1.0 "Crosswalk WebView Engine"                                                                                                                                             
cordova-plugin-device 1.1.3 "Device"                                                                                                                                                                          
cordova-plugin-splashscreen 4.0.0 "Splashscreen"                                                                                                                                                              
cordova-plugin-statusbar 2.2.0 "StatusBar"                                                                                                                                                                    
cordova-plugin-whitelist 1.3.0 "Whitelist"                                                                                                                                                                    
cordova-sqlite-storage 1.4.8 "Cordova sqlite storage plugin"                                                                                                                                                  
ionic-plugin-keyboard 2.2.1 "Keyboard"                               
```                                                                                                    
----
          
Cordova version is: 6.4.0
Ionic version is: 2.1.4

Could you suggest a method of either fixing this or an alternate method of backwards supporting Android 4.1.1?

Regards,

Joe

**Comment by AviateX14** [comment] 2016-11-01 22:25
Just as an added comment, I'm testing the same build on an S7 with the latest android release, and seeing the same results as in the 4.1 device, device ready never fires.

**Comment by jgw96** [comment] 2016-11-02 04:15
Hello, unfortunately I cannot seem to reproduce this on any of my Android devices. Would you mind posting a repo or zipping up your project and linking to it here so that i can reproduce? Thanks!

**Comment by dylanvdmerwe** [comment] 2016-11-02 11:36
I'm having the same issue with my apps. Crosswalk never fires the device ready method. Nothing being output that gives any indication that something is wrong. Tested on Nexus 5 running Android 6.1 and some other Android devices.

**Comment by ivandroid** [comment] 2016-11-02 21:28
Same here with the following conf:

Ionic: 1.3.2
Ionic CLI: latest
Cordova: latest 
Android: 5.0
Device: LG G2

**Comment by DrGanmon** [comment] 2016-11-03 08:47
Try Cordova 6.3.1 it will fix that problem ;)

**Comment by dylanvdmerwe** [comment] 2016-11-03 08:49
```

**Comment by ivandroid** [comment] 2016-11-03 09:36
Cordova@6.3.1 didn't fix the problem.

**Comment by jgw96** [comment] 2016-11-03 14:54
@dylanvdmerwe Are you also using crosswalk 21 ?

**Comment by dylanvdmerwe** [comment] 2016-11-03 14:56
@jgw96 yeah the latest one https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/releases/tag/2.1.0

**Comment by jgw96** [comment] 2016-11-03 16:38
So it looks like the current workaround for this issue is to add crosswalk, and then remove the android cordova platform and add the android cordova platform. Also, just to be transparent, this is starting to look like either a cli issue, or an issue with the crosswalk plugin so this issue may get moved to the cli repo after some more review. Also, how is everyone here installing crosswalk? Using the instructions on the repo that @dylanvdmerwe linked to in the above message?

**Comment by graphefruit** [comment] 2016-11-07 15:22
@jgw96 I've tried this trick to remove and add android it didn't work on my side yesterday evening for about 2 hours without any affect, even grabbing the newest starter-project and installing crosswalk caused this problem.

I need crosswalk because I get the support for android 4.1 to 4.3, my last app had a share rate about 20-25% in this section (sadly =( )

**Comment by AviateX14** [comment] 2016-11-23 15:57
Just to jump back in here (I forgot I'd raised this in all honesty) - I tried the above, downgrade to Cordova 6.3.1 and then reset the platform sate and add android back in, it didn't work, however, I then insatlled again, npm install -g cordova@latest, did a build (no platform reset) and it worked on all devices I tested on, one Android 6 and one Android 4.1.

**Comment by graphefruit** [comment] 2016-11-25 10:11
@jgw96 I don't know what platform.ready() realy does, but would it be possible to just listen to `window.load` or set an timeout `setTimeout(func,2000)` with 2000 secs or something like this.

Could there be any other side problems when using platform without platform.ready has been fired?
Thanks in advance
Graphefruit

**Comment by dylanvdmerwe** [comment] 2016-11-29 08:24
@AviateX14 so do you think this is a Cordova issue?

**Comment by AviateX14** [comment] 2016-11-29 17:06
@dylanvdmerwe I can't 100℅ say but, yes, it seems to be a Cordova issue. It is quite possible that 6.3.1 has a dependency for crosswalk that isn't present in 6.4.0, that would explain why downgrading and upgrading works. However, an alternate cause might simply be a bug in the platform add routine, which could be Ionic or Cordova. Of course, it could even be an issue with Crosswalk itself that just happens to have been patched recently and coincided with my full platform reset. There's 101 possibilities, I'm not nearly familiar enough with any of this to comment with any authority, these are just the thoughts that spring to mind.

**Comment by dylanvdmerwe** [comment] 2016-12-12 20:15
Using latest version of crosswalk `2.2.0` and cordova android platform `6.1.0` and everything is working again. Can this issue be closed?

**Comment by graphefruit** [comment] 2016-12-12 20:20
I gonna Check it out tomorrow on my side aswell

**Comment by nicoabie** [comment] 2017-01-06 15:42
@dylanvdmerwe confirmed, it works with version 2.2.0 of crosswalk. The thing is that version 2.1.0 is listed as the latest as of now.

**Comment by jgw96** [comment] 2017-01-19 17:26
Hello all! Because this seemed to be a Crosswalk issue and because i cannot reproduce it with the latest version of Crosswalk I am going to close this issue for now. Thanks!

**Closed by jgw96** 2017-01-19 17:26 UTC
Labels: needs reply, v2
