### ISSUE TITLE
Hardware Buttons management

### ISSUE THREAD

**Issue by EmmanuelFRANCOIS** [driftyco/ionic#8630] opened 2016-10-11 09:43 UTC
#### Short description of the problem:

I strongly believe that Ionic 2 should have a default minimum hardware Buttons management feature, which should implement following behaviours:

#### What behavior are you expecting?

Hardware back button
-------------------------------------------------------------------------------------------
1. If user is on homepage, pressing hardware back button should:
     - exit application     =>OK
     - optionnally require confirmation from user (alert)     => To be implemented

2. If sidemenu is opened, pressing hardware back button should:
     - close sidemenu     => To be implemented

3. if an alert is opened, pressing hardware back button should:
     - act as if user clicked on one of the buttons (optionnaly configured) => To be implemented

4. if a popover is opened, pressing hardware back button should:
     - close popover     => ok

5. If we are in a tabbed view, pressing hardware back button should:
     - pop the tabbed views, including tabbed container     => sometimes work, sometimes go back to previous tabbed view, depending on device (android versions: 4.1.2 and 5.1)

6. if not in above cases: pressing hardware back button should:
     - pop to previous view     => OK

Hardware Menu button
--------------------------------------------------------------------------------------------
When user press hardware menu button:
1. if a sidemenu exists: toggle sidemenu
2. if no sidemenu but a contextual menu exist: toggle contextual menu
3. if no menu: do nothing
Currently, harware menu button is not managed.

My opinion is that these cases should be managed by default, and that developers should only have to manage cases specific to their app/project.
This is non sense that each developer has to implement these features by himself: time lost!

Please feel free to add any other case I have not listed here.

**Which Ionic Version?** 2.0 RC0

**Comment by jgw96** [comment] 2016-10-11 16:00
Hello, thanks for opening an issue with us! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/7611.

**Closed by jgw96** 2016-10-11 16:00 UTC
