### ISSUE TITLE
After auth0 login, setRoot doesn't seem to call this.content.resize() (?) so top and bottom margins are never set

### ISSUE THREAD

**Issue by danxfisher** [driftyco/ionic#11303] opened 2017-04-21 06:21 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
1. I set the rootPage to my login page (auth0)
2. Once the login is successful, I change the rootPage to my TabsPage (`this.navCtrl.setRoot(TabsPage,{});`)
3. It seems like this.content.resize() doesn't run and my scroll-content doesn't have the top and bottom margins so it is partially hidden by the header and tab footer.

However, once I click a tab and then return to the home page tab (default view of TabsPage), the margins appear.

**Expected behavior:**
1. I set the rootPage to my login page (auth0)
2. Once the login is successful, I change the rootPage to my TabsPage (`this.navCtrl.setRoot(TabsPage,{});`)
3. Default tab page appears with correct top and bottom margins

**Related code:**

app.component.ts:
```
...
export class MyApp {

  // the root nav is a child of the root app component
  // @ViewChild(Nav) gets a reference to the app's root nav
  @ViewChild(Nav) nav: Nav;

  rootPage = LoginPage;
...
```

login.ts:
```
...
events.subscribe('user:authenticated', () => {
        this.navCtrl.setRoot(TabsPage,{});
...
```

Default home page on initial load:
```
<div class="scroll-content">...</div>
```

Default home page after clicking a different tab then returning to default home page:
```
<div class="scroll-content" style="margin-top: 108px; margin-bottom: 48px;">...</div>
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.4
Xcode version: Not installed
```

**Comment by jgw96** [comment] 2017-04-21 16:03
Hello, thanks for opening an issue with us. Could you post a minimal repo we could use to reproduce this issue?

**Comment by jgw96** [comment] 2017-04-26 18:26
Hello! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-04-26 18:26 UTC
Labels: needs info, v2
