### ISSUE TITLE
Popover causes wrong rendering on screen rotation and keyboard open

### ISSUE THREAD

**Issue by alessiodm** [driftyco/ionic#2254] opened 2014-09-21 21:06 UTC
Details:
* iPhone 5s
* iOS 7
* Safari
* Ionic 1.0.0-beta.12

Open a popover with a text-area, focus on the text-area (the keyboard opens), rotate the phone in such a way the screen automatically rotates.

**Comment by Ionitron** [comment] 2015-01-19 01:24
Greetings, @alessiodm!

My sensors indicate that this issue has been inactive for a while.
Due to this, the issue will be closed in 7 days.

If you believe the issue has not been fixed, please add a comment.
This will notify us so we can assist you, and will prevent the issue from being automatically closed.
Feel free to include the following information about the issue, so that we may assist you:

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- What platform does this happen on? (iOS, Android, all, etc.)
- What platform versions does this happen on? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework, or Ionic CLI?

Thank you for allowing me to assist you.

**Comment by alessiodm** [comment] 2015-01-19 10:14
Thank you @Ionitron :) I'll try to reproduce the issue on the beta-14 and I'll update this.

**Comment by perrygovier** [comment] 2015-03-30 23:32
Hey @alessiodm it's been a while without any way to reproduce the bug. I'm going to close this issue, but feel free to resubmit if you can put together something we can test again. 

Cheers

**Closed by perrygovier** 2015-03-30 23:32 UTC
