### ISSUE TITLE
3.0.0-beta3 Can't navigate with lazy loaded routes

### ISSUE THREAD

**Issue by Sh1d0w** [driftyco/ionic#10959] opened 2017-03-29 08:23 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Followed the steps to upgrade to v3. Pushing a page with nav.push produces the following error

```
ERROR
TypeError: Array.prototype.map callback must be a function
map
webpackAsyncContext — src async:114
loadAndCompile — ng-module-loader.js:54
load — module-loader.js:32
getNavLinkComponent — deep-linker.js:168
getComponent — nav-util.js:14
push — nav-controller-base.js:81
previewTimesheet — month-review.ts:469
(anonymous function)
callWithDebugContext — core.es5.js:13060
(anonymous function) — platform-browser.es5.js:2674
onInvokeTask — core.es5.js:4136
runTask — polyfills.js:3:10401
invoke — polyfills.js:3:16178
```

**Expected behavior:**
To be able to navigate properly

**Related code:**

```
this.nav.push('SomePage')
```

```
Your system information:

    Cordova CLI: 6.4.0 
    Ionic Framework Version: 3.0.0-beta.3
    Ionic CLI Version: 3.0.0-beta.4
    ios-deploy version: 1.9.0 
    ios-sim version: 5.0.13 
    OS: macOS Sierra
    Node Version: v7.7.3
    Xcode version: Xcode 8.3 Build version 8E162
```

**Comment by Sh1d0w** [comment] 2017-03-29 08:32
Possible the problem lies in the compiler since the function it tries to map is `__webpack_require__.e`

https://www.google.bg/search?safe=off&q=__webpack_require__.e+is+not+a+function&oq=__webpack_require__.e+is+not+a+function&gs_l=serp.3..0i10i19k1.44159.44307.0.44527.2.2.0.0.0.0.168.305.0j2.2.0....0...1c.1.64.serp..0.2.305...0i7i30k1.jOtBeXBL2E4

**Comment by Manduro** [comment] 2017-03-29 11:52
https://github.com/driftyco/ionic-app-scripts/issues/848

**Comment by jgw96** [comment] 2017-03-29 14:12
Hello, thanks for opening an issue with us. I am going to close this issue as a duplicate of driftyco/ionic-app-scripts#848

**Closed by jgw96** 2017-03-29 14:12 UTC
