### ISSUE TITLE
bug(3.1.0): Tab icon highlight not working properly

### ISSUE THREAD

**Issue by themastersoda** [driftyco/ionic#11406] opened 2017-04-27 12:19 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[X] **3.1.0**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

**Current behavior:**

Clicking on tabs does not highlight currently active tab icon. Highlight under tab behaves properly though.

**Expected behavior:**

Current active tab should be highlighted as well as have its icon highlighted as well.

**Steps to reproduce:**

I have 5 tabs in my TabsPage. Issue appears on android platform. Here's the config that I use:
```
{
  platforms: {
    android: {
      tabsHideOnSubPages: true,
      tabsHighlight: true,
      tabsPlacement: 'top'
    },
    ios: {
      tabsHideOnSubPages: true
    }
  },
  tabsHighlight: true,
  tabsPlacement: 'bottom'
})
```

**Other information:**

Seems to be an off by one issue or changes not detecting properly.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.3.0
Xcode version: Not installed
```

**Comment by jgw96** [comment] 2017-04-27 14:52
Hello, thanks for using Ionic! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/10915

**Closed by jgw96** 2017-04-27 14:52 UTC
Labels: v2
