### ISSUE TITLE
bug: ion-radio directive does not work under v1.1.1

### ISSUE THREAD

**Issue by RafaPolit** [driftyco/ionic#4649] opened 2015-11-20 14:13 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>
## General Description
There appears to be two problems:
* Ion-view directive is not working as expected.  General behavior is that If you implement ion-view elements and select one of them, it does not show any checkmark nor grey background.  This behavior is true for desktop browsers, mobile browsers and within ionic-view.
* Using the css-components you can get it to work, but under iOS9 and ionic-view there is a digest cycle missing which does not show correct feedback of which option is select after the first selection is made (that is, changing selections after the first selection is made 'laggs behind' and shows always one selection behind.

## Temporary fix
As this has been reported and documented in many cases, I was able to temporarily solve the issues of both the directive and the iOS incompatibility with the ion-radio-fix approach described here:
https://gist.github.com/mlynch/064d27912b511a63caa3

## Fix not included in 1.1.1
Apparently this fix was supposed to be included in V1.1.1, but didn't make it to the release.

Thanks in advance,
Rafa.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-11-20 14:13
Greetings @RafaPolit!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4649). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4649)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment] 2015-11-23 15:21
Please provide a demo in the form of a codeine or git repo for us to test against. We have not seen any issues on our tests.

The ion-radio fix did make it into the 1.1.1 release, https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#bug-fixes

**Comment by mlynch** [comment] 2015-12-07 02:48
Closing, can't reproduce.

**Closed by mlynch** 2015-12-07 02:48 UTC

**Comment by RafaPolit** [comment] 2015-12-07 16:11
Sorry for the mess.  If it is of any help, our Ionic project started a while back when the CSS files were on  a different location and never updated the reference on the index.  Therefore the updates have been 'successful' only in theory, because the CSS was not being updated.

I can confirm in fact that the fix have made it to 1.1.1.  Sorry.
