### ISSUE TITLE
Add description to Fab button

### ISSUE THREAD

**Issue by speedfl** [driftyco/ionic#9084] opened 2016-11-08 22:48 UTC
#### Short description of the problem:
No description on fab button.

#### What behavior are you expecting?
New inputs in fabbutton to specify a description.
The idea would be to have the same as messenger (facebook) when click on +. 
Because here Fabs can only contains logo which need to be really explicit (social etc)
With a little text content close to each button we could have a description

**Steps to reproduce:**
1. Ionic blank page
2. Insert fab

**Which Ionic Version?** 1.x or 2.x
2

**Comment by jgw96** [comment] 2016-11-09 15:50
Hello, thanks for using Ionic! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/8425.

**Closed by jgw96** 2016-11-09 15:50 UTC
