### ISSUE TITLE
Range color is not applied anymore

### ISSUE THREAD

**Issue by tsurrel** [driftyco/ionic#6822] opened 2016-06-09 09:35 UTC
As reported on [the forum](https://guides.github.com/features/mastering-markdown/), the color normally applied to the left part of the range bar is no longer working. This can be seen with Firefox or Chrome on the [documentation page](http://ionicframework.com/docs/components/#range). The color is no longer present on Android (5.1.1), I have not tested on iOS.

Ionic v1.3.1

**Comment by jgw96** [comment] 2016-06-09 15:28
Hello, thanks for opening an issue with us! I am going to be closing this issue as a duplicate of https://github.com/driftyco/ionic/issues/5913 . Thanks for using Ionic!

**Closed by jgw96** 2016-06-09 15:28 UTC
Labels: platform:android, platform:ios, range, v1
