### ISSUE TITLE
Ionic2 - Problem when having 2 ion-datetime fields

### ISSUE THREAD

**Issue by ohadbp** [driftyco/ionic#7008] opened 2016-06-22 03:32 UTC
#### Short description of the problem:
In my page i have 2 ion-datetime components without ion-item. When i click on either one of them it's always the button of the later one that is 'clicked'

Problem also occur if both components are within the same ion-item.

**Steps to reproduce:**
You can see an example in this [plunker](http://plnkr.co/edit/Tr9yWzXJqwSMZce41J50?p=info)
Click on the 1-mar-2016 field and the picker will open with 1-jun-2016 data.

Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.31
Ionic App Lib Version: 2.0.0-beta.17
ios-deploy version: 1.8.4
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v4.2.4
Xcode version: Xcode 7.3 Build version 7D175

**Comment by jgw96** [comment] 2016-06-22 04:04
Hello, thanks for opening an issue with us! We actually are already aware of this issue and plan to have a fix for it soon. I will keep this issue open to track the progress of this bug. Thanks for using Ionic!

**Comment by jgw96** [comment] 2016-07-20 16:06
@ohadbp is this still an issue in beta.10?

**Comment by Ionitron** [comment] 2016-07-23 12:18
Greetings @ohadbp!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment] 2016-07-23 12:18
Greetings @ohadbp!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by ome89** [comment] 2016-07-26 17:33
@ohadbp 

I have encountered the same issue while implementing from and to date range. Is it resolved for you ? How did you fix/resolve the issue ?

**Comment by laserus** [comment] 2016-08-24 08:39
@jgw96 yes, it is still an issue

**Comment by jgw96** [comment] 2016-09-01 20:26
Hello all, as this issue will be fixed here https://github.com/driftyco/ionic/issues/7476 i am going to close this issue for now. Thanks!

**Closed by jgw96** 2016-09-01 20:26 UTC
Labels: datetime, ionitron:closed, v2

**Comment by Joaos92** [comment] 2017-04-11 12:21
Just had this issue today, the problem is the ion date time picker has a hidden button with position absolute.

This solves the problem: style="position: relative"

<div class="row center-center" style="position: relative">
                <div>De:</div>
                <ion-datetime displayFormat="DD/MM/YYYY" pickerFormat="DD MM YYYY" [(ngModel)]="calendar.start_at"></ion-datetime>
            </div>

**Comment by karthikvt** [comment] 2017-09-07 07:00
Hi I just used an ion-datetime picker. When I click the screen ion-datetime picker is seen. So i customize the height of the ion-datetime picker as  follows

  .item-cover{
        width: initial;
        height: initial;
  }

But when i used this iOS has an responsive issue.

Can i set the height as fixed one?
