### ISSUE TITLE
bug: Page do not reload

### ISSUE THREAD

**Issue by gio82** [driftyco/ionic#2772] opened 2014-12-19 11:43 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Beta 14
At the moment I'm testing it on iOS simulator

When I first load states `main.first` and `main.second` all works fine.
If I go back only the `nav-bar` reloads his content. The `ion-content` remain last one loaded.

Here some of my code:

app.js

```
.state('main', {
      url: "/main",
      abstract: true,
      templateUrl: "templates/main.html",
      controller: 'MainCtrl'
    })
    .state('main.first', {
      url: "/first",
      views: {
        'main-first': {
          templateUrl: "templates/main-first.html",
          controller: 'MainFirstCtrl'
        }
      }
    })
    .state('main.second', {
      url: "/second",
      views: {
        'main-second': {
          templateUrl: "templates/main-second.html",
          controller: 'MainSecondCtrl'
        }
      }
    })
    ...
```

main.html:

```
<ion-view>
  <ion-nav-view name="main-first"></ion-nav-view>
  <ion-nav-view name="main-second"></ion-nav-view>
</ion-view>
```</span>

<span is-issue-template></span>

**Comment by gio82** [comment] 2015-01-01 10:31
Here for you guys: http://codepen.io/anon/pen/gbLPoP

BTW: Happy new year!! :)

**Comment by mhartington** [comment] 2015-01-20 03:16
The issue is with how the abstract view is set up. You should only have one ion-nav-view in there. 

http://codepen.io/mhartington/pen/ZYKypw

You could even go as far as remove the abstract state.
http://codepen.io/mhartington/pen/mymwOW

Closing this.

**Closed** 2015-01-20 03:16 UTC
Labels: navigation

**Comment by gio82** [comment] 2015-01-20 06:50
Oh, ok!
Thanks for your help and sorry.
