### ISSUE TITLE
bug: Nav-bar sometimes disappears after destroying and re-launching the app

### ISSUE THREAD

**Issue by mrozlukasz** [driftyco/ionic#3483] opened 2015-04-08 08:04 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>
# Tabs seed 
I wrote an app based on tabs seed. The nav-bar seems to disappear sometimes after I close my app and relaunch it. 

# Steps
1. I launch my app, login and display the dashboard screen.
2. Close the app or reinstall it with (ionic run ios; ionic run android)
3. Sometimes app opens but without nav-bar (it's hidden)

I use $state.go with dashboard cache disabled. The issue is random and it happens on both platforms.
This is production showstopper for me. I try to find some workaround but the FIX is needed here. To be more precise, the nav bar gets the hide class and the whole ion-view is repositioned like it was no nav-bar.

# Additional info
```javascript
"cordovaPlugins": [
    "org.apache.cordova.device",
    "org.apache.cordova.console",
    "com.ionic.keyboard",
    "org.apache.cordova.splashscreen",
    "org.apache.cordova.inappbrowser",
    "./engine/cordova-crosswalk-engine-c0.6.2",
    "org.apache.cordova.statusbar",
    "uk.co.workingedge.phonegap.plugin.launchnavigator",
    "org.apache.cordova.geolocation",
    {
      "id": "org.crosswalk.engine",
      "locator": "./engine/cordova-crosswalk-engine-c0.6.2"
    }
  ]
```
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-04-08 08:04
Greetings @mrozlukasz!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3483). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3483)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by vsubramanian** [comment] 2015-04-09 14:04
Our app has the same issue as this. Which version of ionic are you using? We've noticed that in ionic beta-14 the issue is not present, but we can reliably reproduce it with rc1 and rc2 on a device by killing and relaunching the app. Also using `$state.go` to redirect to a user's dashboard when re-opening the app.

**Comment by mrozlukasz** [comment] 2015-04-10 10:18
I found some workaround, but it's not ideal for all apps. I replaced the ion-nav-bar with fixed ion-header-bar from http://ionicframework.com/docs/api/directive/ionHeaderBar/ and it does not disappear. It was possible because my app was not using any features from nav-bar like history. Happily the app can go to production, but IMHO the bug is a critical issue for ionic stable release.

**Comment by perrygovier** [comment] 2015-04-14 20:12
@mrozlukasz do you see this in an app using the tab seed by initially? Can you share a project that reproduces the error so we can inspect it?

**Comment by mrozlukasz** [comment] 2015-04-15 07:47
@perrygovier the seed app is working fine. I've noticed that ion-nav-title/ion-nav-buttons used among multiple tabs causes the issue somehow. I'll try to separate the code/edit the tabs seed for you in about 36 hours (got some other things to do). Thanks.

**Comment by iver56** [comment] 2015-05-02 12:39
I'm just going to leave this video here, in case it helps:
http://iver.io/stuff/ag/WP_20150411_001.mp4

Here's what I do:
I'm inside Chrome and tapping a deep link to open the app and then using the back button to close the app. Then I click the deep link again.
OS: Android 4.1

The back button tap that closes the app is actually calling `navigator.app.exitApp();`

**Comment by Ionitron** [comment] 2015-05-16 20:17
Greetings @mrozlukasz!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-05-16 20:17 UTC
Labels: ionitron:closed

**Comment by rajatrocks** [comment] 2015-05-18 16:33
I noticed that when I deleted and reinstalled my app on device, on first load the navbar would be gone. On all subsequent loads it would be fine. Turns out that in some of my controller code that ran at startup, it was trying to access an object that didn't exist yet, that was throwing a silent JS error which then screwed up the navbars for some reason (by preventing a call to self.createHeaderBar with isActive= true). On subsequent loads that object did exist, and therefore no problem. Fixing the bug fixed the navbar issue. 

Remote debugging with Chrome and an Android phone is great. You can see stuff in the console that was logged out before you even opened Developer Tools. Unlike Safari's debugging, where catching startup problems is pretty much impossible.

**Comment by hswolf** [comment] 2015-10-14 15:07
I found that these code will make this kind of problem fly away
```javascript
$scope.$on('$ionicView.enter', function(e) {
    $ionicNavBarDelegate.showBar(true);
});
```

**Comment by balicekt** [comment] 2016-01-18 10:34
Thanks @hswolf  this figured out my issue!!!

**Comment by obedm503** [comment] 2016-02-15 22:52
problem with this solution is that the nav-bar appears empty, no title, no back button, no side menu button

**Comment by jorgevaldivia** [comment] 2016-05-19 20:39
I'll throw in my 2 cents here. I was having this exact same problem until I realized that I had multiple `ion-nav-bar` elements defined in my app. I had one defined at the root level template and two or three others scattered around the child templates (probably from copy and pasting). The problem went away once I removed the `ion-nav-bar`s from the child templates.

**Comment by Paul-Lo** [comment] 2016-06-26 16:09
@hswolf solved my problem.

**Comment by Medkhalil97** [comment] 2017-02-24 14:24
@hswolf can you please tell me where i should past that code ?

**Comment by jacprada** [comment] 2017-03-03 14:33
@Medkhalil97 just paste it in the controller associated with that view. :)

**Comment by edeortuzar** [comment] 2017-04-12 11:03
Thanks @hswolf!!!
