### ISSUE TITLE
bug(tabs) - Clicking the active tab refreshes reloads the page. Clicking again forces a black screen to appear

### ISSUE THREAD

**Issue by zakton5** [driftyco/ionic#11174] opened 2017-04-11 17:35 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
When I click on the active tab, that tabs page is refreshed. I'm not sure if it goes back to the root of the tab stack or not, but its worth looking into. After the tab is refreshed, and I click on the active tab a second time, it appears as though a `pop` occurs because the root page slides off to the right, leaving a black and empty screen.
This is only on ionic 3. I rolled back to ionic 2 to verify.

**Expected behavior:**
Clicking the active tab should do absolutely nothing.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.1-201704062237
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.10.1
Xcode version: Xcode 8.3.1 Build version 8E1000a

**Comment by vintage** [comment] 2017-04-11 18:55
Duplicate of https://github.com/driftyco/ionic/issues/11127

**Comment by zakton5** [comment] 2017-04-11 19:26
Thank you @vintage

**Closed** 2017-04-11 20:15 UTC
