### ISSUE TITLE
Allow text selection on elements other then input

### ISSUE THREAD

**Issue by caraffa** [driftyco/ionic#7045] opened 2016-06-24 19:35 UTC
Same situation as with issue #5612. (I have areas in my app where I want to be able to select text. Instead of preventing text selection for anything except for a text input there should be an option to define selectable text. Working on a pull request now.)
I need text to be selectable not only on input fields.
Apparently there's no trivial way to do this.

**Comment by jgw96** [comment] 2016-06-27 17:07
Hello! Thanks for opening an issue with us! I am going to be closing this issue as a duplicate of https://github.com/driftyco/ionic/issues/5198 . Thanks for using Ionic!

**Closed by jgw96** 2016-06-27 17:07 UTC
Labels: v2
