### ISSUE TITLE
bug: Ionic emulate Ios fails to run The session does not open my app

### ISSUE THREAD

**Issue by YonasBerhe** [driftyco/ionic#4052] opened 2015-07-07 22:06 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>browser</span>

<span ionic-description>Ionic emulate ios failed on Mac OS Yosemite. Their have some cases were the ios device emulated, but shortly after the terminal console shoots up the error message below.

** BUILD SUCCEEDED **
No target specified for emulator. Deploying to iPhone-6 simulator An error was encountered processing the command (code=146): Invalid device state An error was encountered processing the command (code=146): Exception encountered connecting to CoreSimulatorBridge: Unable to connect to CoreSimulatorBridge ENOENT, no such file or directory '/Users/yay/Library/Logs/CoreSimulator/2CAA2C39-7F22-4AF2-BBDE-86609188F37C/system.log' Error code 1 for command: ios-sim with args: launch,/Users/yay/code/myApp/platforms/ios/build/emulator/myApp.app,--devicetypeid,com.apple.CoreSimulator.SimDeviceType.iPhone-6,--stderr,/Users/yay/code/myApp/platforms/ios/cordova/console.log,--stdout,/Users/yay/code/myApp/platforms/ios/cordova/console.log,--exit Error: /Users/yay/code/myApp/platforms/ios/cordova/run: Command failed with exit code 2 at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:134:23) at ChildProcess.emit (events.js:110:17) at maybeClose (child_process.js:1015:16) at Process.ChildProcess._handle.onexit (child_process.js:1087:5)</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-07-07 22:06
Greetings @YonasBerhe!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4052). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4052)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by iamthemovie** [comment] 2015-07-12 22:17
This is a permissions issue:

running sudo ionic start require you to build / emulate with sudo to remove/build files which doesn't work when emulating.

Don't use sudo for creating or emulating.

**Comment by bferreirainfo** [comment] 2015-07-17 21:16
i have that same problem, if i don't use sudo like you suggest, i get "rm: could not remove file (code EACCES):" on all files. Xcode 6.4, last node/npm. But as u say this is a sudo problem, so how to resolve this dilema?

**Comment by iamthemovie** [comment] 2015-07-17 21:30
It's because you created the ionic project using Sudo.

**Comment by iamthemovie** [comment] 2015-07-17 21:31
Recursively chown that folder to your user.

**Comment by bferreirainfo** [comment] 2015-07-18 02:51
Thank you for your answer! But sorry english isn't my native languagem, i dont quite understand. My projet was created on a windowns system, with android platform, and right now i fork this project on a mac via github. There is a solution? what is "Recursively chown that folder to your user." Thank you again, my startup depend on that problem  =)

**Comment by bferreirainfo** [comment] 2015-07-18 13:44
i tested creating a project without sudo and emulate with and without sudo, and got the same erros.

Withou sudo: rm: could not remove file (code EACCES):
With sudo:  Invalid device state An error was encountered processing the command (code=146): Exception encountered connecting to CoreSimulatorBridge: Unable to connect to CoreSimulatorBridge ENOENT, no such file or directory '/Users/yay/Library/Logs/CoreSimulator/2CAA2C39-7F22-4AF2-BBDE-86609188F37C/system.log' Error

**Comment by code4jhon** [comment] 2015-08-05 22:58
Indeed it was a permission issue thanks @iamthemovie

**Comment by rajkotecha** [comment] 2015-09-13 15:30
the following worked for me:

//remove **with** sudo
`sudo ionic platform remove ios`

//add iOS back **without** sudo
`ionic platform add ios`

//worked for me
`ionic emulate ios`

**Comment by lionel22** [comment] 2015-09-23 20:45
amazing !!!!!
it work for me

**Comment by mhartington** [comment] 2015-09-23 20:58
So you shouldn't ever have to run the ionic command with sudo, ever.
Since the cli is installed globally already, the current user has access to all it's commands. The only time this could be an issue with with nvm and not having a globally available version of node

**Comment by zamankazi** [comment] 2015-10-21 15:25
Worked like a charm. Indeed it was a permission problem.

**Comment by liuwenzhuang** [comment] 2015-11-09 03:57
@rajkotecha Thx, you save my day!

**Comment by zvineyard** [comment] 2015-11-17 22:52
@rajkotecha's fix also worked for me.

**Comment by craigm26** [comment] 2015-11-23 22:50
I'm having the problem but I can't seem to diagnose how to fix the permission issue. 

when I do 

ionic platform add ios

I get a error to fetch platform.. 
...operation ont permitted, utime "somepath/package/.npmignore

Do I need to eliminate a line in this file?

**Comment by dimkk** [comment] 2015-11-29 03:47
craigm26  sudo chown -Rv [USERNAME] /Users/[USERNAME] - helped me!

**Comment by mlynch** [comment] 2015-12-07 04:50
If you're still having issues, can you post over here? https://github.com/driftyco/ionic-cli

Also, just in case, try installing the beta: `npm install -g ionic@beta`

**Closed by mlynch** 2015-12-07 04:50 UTC

**Comment by craigm26** [comment] 2015-12-07 04:59
Thanks guys/gals

**Comment by ifelere** [comment] 2015-12-11 13:46
sudo chown -Rv [USERNAME] /Users/[USERNAME] helped me too!

**Comment by vallal7** [comment] 2015-12-14 19:16
I had access error for update-notifier-cordova.json; and this is what that worked for me:
sudo chown [USERNAME]:admin /Users/[USERNAME]/.config/configstore/update-notifier-cordova.json

**Comment by carbondesign** [comment] 2015-12-30 20:36
to get the reomve/add mentioned above to work I had to delete the .cordova/lib/npm_cache/cordova-ios folder...then all was well

**Comment by zzsanduo** [comment] 2016-01-31 09:47
I had the issue too. Even though I create project without sudo, I cannot add platform ios successfully with the permission error.
And this worked for me too:
sudo chown [USERNAME]:admin /Users/[USERNAME]/.config/configstore/update-notifier-cordova.json

Thank you

**Comment by omefire** [comment] 2016-03-17 04:34
+1

**Comment by deianmotov** [comment] 2016-06-30 08:51
I can confirm, for me helped what zzsanduo suggested:
sudo chown [USERNAME]:admin /Users/[USERNAME]/.config/configstore/update-notifier-cordova.json

**Comment by mlynch** [comment] 2016-10-18 18:35
Thanks everyone for the tips here. One other thing: if you're using tmux, you'll need to open a new terminal outside of tmux before the emulate command can run. There was some hack you could use to get around this in the past but I don't have that tip handy anymore and couldn't find it after a cursory google search

**Comment by brunogyn88** [comment] 2017-01-18 17:03
this work for me
chown -R $(whoami) /project_folder

ionic run ios (whitout sudo)

(y)

**Comment by 0x62** [comment] 2017-03-03 10:38
@mlynch This fixed it, I tried everything to do with permissions. I've now found a few messages noting the issue with tmux, but wasn't even something I'd considered initially.

**Comment by heyjohnny** [comment] 2017-05-09 18:14
Yep, thank you craigm26, sudo chown -Rv [USERNAME] /Users/[USERNAME] did the trick.

**Comment by renjithvk** [comment] 2017-12-20 08:38
@rajkotecha Thanks!

### SOLVED
I'd added ios platform with sudo. That why it happened. Now I do it **without sudo**, it works well.

1. Remove platform
`$ ionic cordova platform rm ios`

2. Add platform
`$ ionic cordova platform add ios`

3. Emulate
`$ ionic cordova run ios`
