### ISSUE TITLE
DatePicker no default value and misses months for future "max" year on 1st drop down

### ISSUE THREAD

**Issue by astec** [driftyco/ionic#10710] opened 2017-03-09 12:59 UTC
**Ionic version:**  (check one with "x")
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[x] feature request

**Current behavior:**

If `max` attribute specified into future for example "2020-12-31" the date picker would display:

- Day: {1}
- Month: {unselected but list starts with today's month, currently March}
- Year - {the max one, for this example 2020}.

If I scroll the year to 2019 and back to 2020 all 12 months are shown as expected.

**Expected behavior:**

Regards bug: I expect either max year with all 12 months (_or up to the last allowed by max_) or a current year to be selected by default (or first allowed by min property) 

**Regards feature request**: I suggest we have additional property **defaultValue**.

**Reasoning**: I want some of my date fields to be optional so I can't fill the value before the picker clicked but once user opens drop down I want a specific date to be preselected, specifically I need today or tomorrow but could be any arbitrary date. Also for optional fields would be nice to have some way to clear the field from previously entered value.

**Steps to reproduce:**
See plunker: http://plnkr.co/edit/H7eMFjSDrj8VbsUo0bDW?p=preview

**Related code:**

```
<ion-list>
    <ion-item>
			<ion-label>Due on</ion-label>
			<ion-datetime
			  displayFormat="D MMMM YYYY"
			  pickerFormat="D MMMM YYYY"
			  min="2017-03-08"
			  max="2020-12-31"
			  ></ion-datetime>
    </ion-item>
  </ion-list>
</
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.1 
ios-sim version: 5.0.11 
OS: OS X El Capitan
Node Version: v6.7.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by rapropos** [comment] 2017-03-09 22:22
Looks like a partial dupe of [9846](https://github.com/driftyco/ionic/issues/9846) to me.

**Comment by jgw96** [comment] 2017-03-13 11:19
Thanks for opening an issue with us, going to merge this with #9846.

**Closed by jgw96** 2017-03-13 11:19 UTC
