### ISSUE TITLE
Back button issue

### ISSUE THREAD

**Issue by kraskoshnyy** [driftyco/ionic#6875] opened 2016-06-13 08:05 UTC
#### Short description of the problem:

Back button becomes hidden, looks like some problems with ionicHistory
#### What behavior are you expecting?

Click on the button should change state to previous

**Steps to reproduce:**
1. You need at least two tabs. where you have "sub pages"
2. Click on first tab, then subpage and click back
3. Do the same with second tab
4. Go to first tab
5. The same with second tab
6. Repeat #2
7. No back button on sub page on tab 2 & 1

Attached images

**Which Ionic Version?** 1.x or 2.x
1.3.1
![screen shot 2016-06-13 at 1 02 15 am](https://cloud.githubusercontent.com/assets/10145395/16000728/dd182ca4-3102-11e6-8599-57bee7846af1.png)
![screen shot 2016-06-13 at 1 02 25 am](https://cloud.githubusercontent.com/assets/10145395/16000726/dd033484-3102-11e6-858c-24da4744229a.png)
![screen shot 2016-06-13 at 1 02 37 am](https://cloud.githubusercontent.com/assets/10145395/16000727/dd0e3a50-3102-11e6-8095-2743bf07321a.png)

**Comment by kraskoshnyy** [comment] 2016-06-14 05:09
So confirmed, the problem with backView:
This code answer viewHistory before actions:

Object
backView: View {viewId: "ion9", index: 0, historyId: "ion5", backViewId: "ion7", forwardViewId: "ion10", …}
currentView: View {viewId: "ion10", index: 1, historyId: "ion5", backViewId: "ion9", forwardViewId: null, …}
forwardView: null
histories: {root: Object, ion3: Object, ion4: Object, ion5: Object}
views: {ion2: View, ion6: View, ion7: View, ion8: View, ion9: View, …}


After:

backView: null
currentView: View {viewId: "ion10", index: 1, historyId: "ion5", backViewId: null, forwardViewId: null, …}
forwardView: null
histories: {root: Object, ion3: Object, ion4: Object, ion5: Object}
views: {ion2: View, ion6: View, ion7: View, ion8: View, ion9: View, …}

**Comment by chmln** [comment] 2016-06-16 19:13
+1

**Comment by LightZam** [comment] 2016-06-17 06:46
+1

**Comment by LightZam** [comment] 2016-07-15 01:12
any solution?
or anyone has workaround solution?
or anyone can confirm which version work fine

**Comment by kraskoshnyy** [comment] 2016-07-15 02:14
I fixed this way, I keep history in $rootScope.appScope.viewBack

  $scope.$on("$ionicView.beforeEnter", function(event, viewData){
    viewData.enableBack = true;
    if($ionicHistory.backView() != null) {
      $rootScope.appScope.viewBack[$state.current.name] = $ionicHistory.backView();
    }
    else if(typeof $rootScope.appScope.viewBack[$state.current.name] != undefined) {
      $ionicHistory.viewHistory().backView = $rootScope.appScope.viewBack[$state.current.name];
    }
  });

Works perfectly for me

**Comment by LightZam** [comment] 2016-07-15 05:52
@kraskoshnyy thanks, i will try it

and more , i had confirm the version.

ionic lib 1.3.0 works fine, the bug comes out with 1.3.1

**Comment by gzfgeh** [comment] 2016-08-24 06:05
what is this "appScope"?  Cannot read property 'viewBack' of undefined

**Comment by Focushift** [comment] 2016-08-28 08:50
Have same problem with Back button when navigating between 3 views. If I check $ionicHistory.viewHistory().currentView when coming from 3 to 2 view, backView becomes null.
Here my ugly code that helps to solve problem and later adds another:
        $rootScope.$on('$stateChangeSuccess', function () {
                if ($ionicHistory.viewHistory().currentView.stateId == 'garage' || $ionicHistory.viewHistory().currentView.stateId == 'login') {
                        var s = {};
                        s.back = $ionicHistory.viewHistory().currentView;
                        s.view = $ionicHistory.viewHistory().views[s.back.viewId];
                        StoreService.storeData('apphistory', s);
                }
                if ($ionicHistory.viewHistory().histories.ion1.cursor > 0) {
                    setTimeout(function () {
                        console.log(angular.copy($ionicHistory.viewHistory()));
                        if ($ionicHistory.viewHistory().currentView.index == 0) {
                            try {
                                angular.element(document.querySelectorAll("[nav-bar]")[0].childNodes[0].childNodes[0]).addClass('hide');
                                angular.element(document.querySelectorAll("[nav-bar]")[0].childNodes[1].childNodes[0]).addClass('hide');
                            } catch (e) { }
                        }
                        if ($ionicHistory.viewHistory().backView == null && $ionicHistory.viewHistory().histories.ion1.cursor > 1) {
                            console.log('alert');
                            var s = angular.copy(StoreService.getData('apphistory'));
                            $ionicHistory.viewHistory().backView = s.back;
                            $ionicHistory.viewHistory().views[s.back.viewId] = s.view;
                            $ionicHistory.viewHistory().currentView.backViewId = s.back.viewId;
                            $ionicHistory.viewHistory().views[$ionicHistory.viewHistory().currentView.viewId].backViewId = s.back.viewId;
                            var ar = angular.copy($ionicHistory.viewHistory().histories.ion1.stack);
                            $ionicHistory.viewHistory().histories.ion1.stack = [];
                            $ionicHistory.viewHistory().histories.ion1.stack.push(s.back);
                            $ionicHistory.viewHistory().histories.ion1.stack.push(ar[0]);
                            $ionicHistory.viewHistory().histories.ion1.cursor--;
                            console.log($ionicHistory.viewHistory());
                            angular.element(document.querySelectorAll("[nav-bar='active']")[0].childNodes[0].childNodes[0]).removeClass('hide');
                        }
                    }, 300);
                } else setTimeout(function () { console.log(angular.copy($ionicHistory.viewHistory())); }, 300);
        });

**Comment by DrJonnie** [comment] 2016-09-01 07:09
Hi,

in my opinion this bug is really a show stopper. And the ionic team should investigate ASAP.

**Comment by loopezz** [comment] 2016-09-15 11:15
+1

**Comment by oguzserdar** [comment] 2016-09-28 21:08
+1

**Comment by jpost** [comment] 2016-09-29 14:32
+1

**Comment by Focushift** [comment] 2016-09-30 14:22
Commented that block, not helps.

**Comment by DrJonnie** [comment] 2016-11-07 11:52
Hi, does anybody know whether there is some progress on this bug?
Ionic 1.3.2 is out, can anybody confirm wheteher this bug still exists?

**Comment by AlDrag** [comment] 2016-11-25 04:13
Has this still not been fixed? I am still having massive issues with this. Is it fixed in V2 at least?

**Comment by oguzserdar** [comment] 2016-11-25 09:55
It's not a problem in V2.

**Comment by DrJonnie** [comment] 2016-11-29 08:32
Personally, I'm a little bit disappointed. I understand that the Ionic dev team is primarily focused
on the v2 release, but vs is still not ready for production use. Therefore I can not understand
that this primary navigation BUG ist still not resolved and that since to v1 releases!

**Comment by AlDrag** [comment] 2016-12-04 22:38
I agree DrJonnie. But maybe we can try contribute to helping the problem through a pull request? :) Just need to find the cause of the bug.

**Comment by gabrielbazan7** [comment] 2016-12-22 20:50
Just send a PR to Bitpay/Copay Wallet ionic project solving this issue. Feel free to take a look: https://github.com/bitpay/copay/pull/5333 
And tell me if it works, please. 

Here is the code.

```
$rootScope.$on('$stateChangeStart', function(event, toState, toParams, fromState, fromParams) {
      $log.debug('Route change from:', fromState.name || '-', ' to:', toState.name);
      $log.debug('            toParams:' + JSON.stringify(toParams || {}));
      $log.debug('            fromParams:' + JSON.stringify(fromParams || {}));

      //Solves Ionic back button issue
      if (!$rootScope.viewBack) $rootScope.viewBack = [toState.name];
      else $rootScope.viewBack.push(toState.name);
      if ($ionicHistory.backView() != null) {
        $rootScope.viewBack[toState.name] = $ionicHistory.viewHistory().backView;
      } else if (typeof $rootScope.viewBack[toState.name] != undefined) {
        $ionicHistory.viewHistory().backView = $rootScope.viewBack[toState.name];
      }
    });
```

**Comment by jgw96** [comment] 2017-01-13 22:44
This issue was moved to driftyco/ionic-v1#122

**Closed by jgw96** 2017-01-13 22:44 UTC
Labels: v1
