### ISSUE TITLE
 ionic1.3.1 nonsupport  lifeCircle？

### ISSUE THREAD

**Issue by favoriteMyself** [driftyco/ionic#7655] opened 2016-08-11 05:55 UTC
My project is OK when i lead into ionic1.2.1,but it,s wrong when i lead into ionic 1.3.1 replaced.I find  '$ionicView.beforeEnter' is not work sometimes！Why？I hope someone can ask me please,much Thanks.

**Comment by jgw96** [comment] 2016-08-11 14:08
Hello, thanks for opening an issue with us! Would you be able to provide more info about your issue and maybe a repo that I can test with? Thanks!

**Comment by danbucholtz** [comment] 2016-08-11 18:08
Hi @favoriteMyself,

Is your template a container?  I have seen several people have issues where their template contains siblings vs a clear parent.  Please give that a shot and let us know how it goes.  If you can reproduce the issue with a codepen (http://codepen.io/ionic/pen/Qwpxer) I'll do my best to help you out.

Thanks,
Dan

**Comment by jgw96** [comment] 2016-08-14 05:28
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-08-14 05:28 UTC
Labels: needs reply, v1
