### ISSUE TITLE
Can't override value in ionic.bundle.js (Swiper). How to override or update it?

### ISSUE THREAD

**Issue by 1BJK903** [driftyco/ionic#9786] opened 2016-12-24 14:25 UTC
Hi all,

I have a rather odd issue. I am using Swiper and I can't get the options of the Swiper slider to work. So what I did was, checking out **_ionic.bundle.js_**. I noticed it's using Swiper 3.2.7...

So, what I also noticed in ionic.bundle.js, is this:

```
        var defaults = {
            // autoplay
            autoplay: false,
```

But: Swiper documentation says it's not a boolean, but a number (you can see that [here](http://idangero.us/swiper/api/). So in my options, in my app.js, I have:

```
  $scope.options = {
    autoplay: 2500,
    loop: false,
    speed: 1000,
    slidesPerView: 1,
    centeredSlides: true
  }
```

But this doesn't work! Instead, it uses the "false" from ionic-bundle.js. So I can't seem to override it.

My question: how is this even possible and how do I change this? When I change the value "false" in ionic.bundle.js to "2500" for example, the autoplay suddenly works! 

**So now I know the issue is right there, but how do I fix it?** I don't want to _hardcode_ it, but instead, override the value or at least change ionic.bundle.js to use Swiper 3.4.1, which is the latest version.

Can someone help me please?

PS: this is the reason for this bug, I assume: https://github.com/driftyco/ionic/issues/9783

**Comment by jgw96** [comment] 2016-12-27 15:39
Hello, thanks for using Ionic! Since this seems to be caused by the same issue described in https://github.com/driftyco/ionic/issues/9783 I am going to close this issue as a duplicate of that one. Thanks!

**Closed by jgw96** 2016-12-27 15:39 UTC

**Comment by 1BJK903** [comment] 2017-02-25 19:24
Thanks, but will someone solve this issue? 3 months later and we still have not solution! I can't go live like this @jgw96. The problem is caused by an Ionic update and we can't fix it, while it was working before!

Could you guys check this please? I have no clue whether Ionic is trying to solve this at all, now...
