### ISSUE TITLE
ion-input with floating label changes size when scrolling

### ISSUE THREAD

**Issue by superkew** [driftyco/ionic#7827] opened 2016-08-22 15:33 UTC
**Note: If you are having problems formatting your issue please refer to this article on using markdown in Github:**

https://guides.github.com/features/mastering-markdown/

**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
If a text input has a floating label attached, and is selected. Then when scrolling the input doubles in size while scrolling using touch or while auto scrolling when the soft keyboard appears.

#### What behavior are you expecting?
Text input to stay the same size

**Steps to reproduce:**
1. Create new ionic tabs app in v2
2. Added inputs to home page with floating labels
3. Run in emulator
4. Select input and then use touch to scroll the page while input is highlighted.

```
<ion-list>
    <ion-item>
      <ion-label floating>Input 1</ion-label>
      <ion-input type="text"></ion-input>
    </ion-item>
    <ion-item>
      <ion-label floating>Input 2</ion-label>
      <ion-input type="text"></ion-input>
    </ion-item>
    <ion-item>
      <ion-label floating>Input 3</ion-label>
      <ion-input type="text"></ion-input>
    </ion-item>
    <ion-item>
      <ion-label floating>Input 4</ion-label>
      <ion-input type="text"></ion-input>
    </ion-item>
    <ion-item>
      <ion-label floating>Input 5</ion-label>
      <ion-input type="text"></ion-input>
    </ion-item>
    <ion-item>
      <ion-label floating>Input 6</ion-label>
      <ion-input type="text"></ion-input>
    </ion-item>
    <ion-item>
      <ion-label floating>Input 7</ion-label>
      <ion-input type="text"></ion-input>
    </ion-item>
  </ion-list>
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x
2.0.0-beta.11

#### Plunker that shows an example of your issue

Video of issue: https://drive.google.com/open?id=0B6FOaQgEXtnzaEo4YWJ2THU4eEU 

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.3.0

Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.36
Ionic App Lib Version: 2.0.0-beta.19
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v4.4.7
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment] 2016-08-22 16:13
Hello! Thanks for opening an issue with us! I am going to be closing this issue as a duplicate of https://github.com/driftyco/ionic/issues/7318. Thanks for using Ionic!

**Closed by jgw96** 2016-08-22 16:13 UTC
Labels: keyboard, platform:ios
