### ISSUE TITLE
When using rtl direction in html tag, the margin between range component and its labels disappears

### ISSUE THREAD

**Issue by loolooii** [driftyco/ionic#7488] opened 2016-07-31 09:01 UTC
#### Short description of the problem:
When in `rtl` mode, there is no margin between range and its labels, hence the icons on both sides are partially not visible.

#### What behavior are you expecting?
I expect there to be a small margin as it's the case when in `ltr` mode.

**Steps to reproduce:**
1. Add `dir="rtl"` to `<html>` tag in `index.html`
2. Create a `ion-list` with an `ion-item` which contains an `ion-range`

```
<ion-list>
    <ion-item>
        <ion-range [(ngModel)]="brightness">
            <ion-icon range-left small name="sunny"></ion-icon>
            <ion-icon range-right name="sunny"></ion-icon>
        </ion-range>
    </ion-item>
  </ion-list>
```

**Which Ionic Version?** 
2.0.0-beta.35

#### Plunker that shows an example of your issue

**For Ionic 2 issues** - http://plnkr.co/edit/CO97zOelgbiGbBmhfuYa?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

```
Cordova CLI: 6.3.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.35
Ionic App Lib Version: 2.0.0-beta.19
ios-deploy version: Not installed
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.4.1
Xcode version: Xcode 7.3.1 Build version 7D1014
```

**Comment by loolooii** [comment] 2016-07-31 09:04
Actually it's not only on iOS. The same problem exists in web and Android.

**Comment by jgw96** [comment] 2016-08-09 18:13
Hello! Thanks for opening an issue with us! I am going to be closing this issue as a duplicate of https://github.com/driftyco/ionic/issues/5035. Feel free to post about any issues with RTL to that issue. Thanks for using Ionic!

**Closed by jgw96** 2016-08-09 18:13 UTC
Labels: platform:ios, range, v2
