### ISSUE TITLE
Navigating in Modal ignores status bar

### ISSUE THREAD

**Issue by wbhob** [driftyco/ionic#10460] opened 2017-02-15 23:54 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When using `[navPush]` inside a modal, the page it transitions to ignores the header bar for iOS (tested in Ionic Lab, not native). That is, the nested page's header bar overlaps the native status bar.
**Expected behavior:**

The header bar should be below the status bar like on normal pages.

**Steps to reproduce:**

1. Open a page in a modal
2. Open another page using [navPush].
3. See the issue.
**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0
ios-sim version: 5.0.12
OS: macOS Sierra
Node Version: v6.9.4
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment] 2017-02-16 15:28
Hello, thanks for using Ionic! I am going to close this one as a duplicate of https://github.com/driftyco/ionic/issues/8151.

**Closed by jgw96** 2017-02-16 15:28 UTC
