### ISSUE TITLE
Tabs don't work emulator

### ISSUE THREAD

**Issue by johndiego** [driftyco/ionic#9178] opened 2016-11-15 19:58 UTC
#### Short description of the problem:

tabs primary don't working in emulator just  in browser!

My code
```
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
import { Transbordo } from '../../pages/transbordo/transbordo' ;
import { Volumes } from '../../pages/volumes/volumes';
import { Ocorrencias } from '../../pages/ocorrencias/ocorrencias';

@Component({
  selector: 'principal-transbordo',
  templateUrl: 'principal-transbordo.html'
})
export class PrincipalTransbordo {

  volumes = Volumes;
  ocorrencias = Ocorrencias;
  transbordo = Transbordo;

  constructor(public navCtrl: NavController) {}

  ionViewDidLoad() {

  }

}

```
####  my template
```
<ion-tabs [selectedIndex]="1" color="primary" >
  <ion-tab [root]="ocorrencias" tabTitle="Ocorrencias"></ion-tab>
  <ion-tab [root]="transbordo" tabTitle="Transbordo"></ion-tab>
  <ion-tab [root]="volumes" tabTitle="Volumes"></ion-tab>
</ion-tabs>

```
#### In my phone cel don't apply color primary,  How solved this?

![image](https://cloud.githubusercontent.com/assets/18476845/20320388/d7fd6434-ab58-11e6-9852-a0fdadea8ca3.png)

**Comment by mhartington** [comment] 2016-11-16 00:33
What version of ionic is this? I'm not able to replicate using the latest RC

**Comment by johndiego** [comment] 2016-11-16 20:31
#### Hi mhartington  thanks for repply
```
john@john-Inspiron-5547:~/Desktop/Projetos/rte$ ionic -v
2.1.8
```

**Comment by brandyscarney** [comment] 2016-11-18 19:32
@johndiego Could you run `ionic info` and then paste the output from that please? Thanks!

**Comment by johndiego** [comment] 2016-11-18 23:40
```
Cordova CLI: 6.4.0 
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.9.1
Xcode version: Not installed


```

**Comment by jgw96** [comment] 2016-12-05 16:26
Hello @johndiego are you still having this issue? I unfortunately cannot reproduce this on my devices. Im testing on Android 5.1.1, Android 6.0.1 and Android 7.0.

**Comment by johndiego** [comment] 2016-12-05 20:40
@jgw96 

The same problem happens!

**Comment by jgw96** [comment] 2017-01-20 16:03
Hello @johndiego are you still having this issue with RC5? I cannot reproduce this with the 4.4.4 or 4.4.2 emulator.

**Comment by jgw96** [comment] 2017-01-25 15:32
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-01-25 15:32 UTC
Labels: needs reply, v2
