### ISSUE TITLE
bug: rc0 popup showing scrollbars on android 4.4 >

### ISSUE THREAD

**Issue by nickh364** [driftyco/ionic#3300] opened 2015-03-12 13:51 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>ionic popup is showing scrollbars on rc0 on 4.4 and 5.0.
Tested on 4.1, 4.2, 4.3, 4.4, 5.0

rc0 codepin - http://codepen.io/nickh364/pen/emPNmJ
beta 14 codepin - http://codepen.io/nickh364/pen/bNmdey</span>

<span is-issue-template></span>

**Comment by TobiMarg** [comment] 2015-03-14 14:32
Same problem here on firefox.
But seems to be a Duplicate of #3204

**Comment by perrygovier** [comment] 2015-03-16 16:37
closing as duplicate. please continue the discussion on #3204

**Closed by perrygovier** 2015-03-16 16:37 UTC
