### ISSUE TITLE
PWA ServiceWorker don’t work with Ionic 2

### ISSUE THREAD

**Issue by wgbn** [driftyco/ionic#8978] opened 2016-11-01 13:17 UTC
Hello everyone. I am having great difficulty in operating the ServiceWorker with ionic 2.
I start a new project with ionic this:

`$ Ionic start pwa-project blank --v2`

The default structure created by the ionic me two important folders:
    - src
    - www

In both there are the files:
- Index.html (where I have to uncomment the call to service-worker)
- Manifest.json (which set up the data from my app)
- Service-worker.js (the my service worker itself)

The logic for developers in ionc is not touching anything in the **www** folder and only work in the **src** folder. And I did, ran the `$ ionic serve` and started to edit my html, service-worker and manifest, all in the **src** folder. But I noticed that the changes are not reflected on the same files in the **www** folder.
Restarted the `$ ionic serve` and nothing happened.

All right, then I proceeded to edit these three files directly in the **www** folder to Activate from my service-worker.

This time I came across another problem. The service-worker does not run.
The script invokes the service-worker in the index.html file prints to the console the success message **"service worker installed"** confirming that it was installed, but I wrote some `console.log()` in my service-worker of events and these events are not fired, and I can not say why.

    console.log ( '[SERVICE WORKER] Install');
    console.log ( '[SERVICE WORKER] Activate');
    console.log ( '[SERVICE WORKER] Fetch');

None of these is displayed on the console, which makes me believe that the service-worker for some reason, is not running.

In Chrome DevTools, Application pane, appears that the service-worker is installed and enabled.

Has anyone experienced this problem? Managed to solve?

PS .: When I create a project in vanilla javascript everything works fine, the service-worker is installed, running and messages are usually displayed on the console, which makes me believe that there is any interference Ionic (v2).

My Ionic info is:

    Cordova CLI: 6.3.1
    Gulp version:  CLI version 3.9.1
    Gulp local:   Local version 3.9.1
    Ionic CLI Version: 2.1.4
    Ionic App Lib Version: 2.1.2
    OS: Distributor ID:	elementary OS Description:	elementary OS Freya 
    Node Version: v5.12.0

**Comment by jgw96** [comment] 2016-11-01 14:33
Hello, thanks for using Ionic! Sorry you are having an issue with using service workers in your project! So first, to solve the changes not getting reflected to the service worker that is in the www folder, can you make sure that your running the latest version of `ionic-app-scripts` ? You can do this by running `npm install @ionic/app-scripts@latest --save-dev`. The latest version of app-scripts has fixed this issue. Second, most likely you are not seeing your logs because the service worker hasn't been restarted with your changes. To fix this you can go to the application tab of chrome dev tools, unregister the running service worker in the service workers tab, and then when you refresh the page the new one with your changes should be installed.

**Comment by jgw96** [comment] 2016-11-18 21:24
Hello! As it seems it has been a while since there was any activity on this issue and i cannot reproduce the issue I will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-11-18 21:24 UTC
Labels: needs reply, v2
