### ISSUE TITLE
[RC0] Toast z-index issue

### ISSUE THREAD

**Issue by flyhuang** [driftyco/ionic#8597] opened 2016-10-10 05:11 UTC
#### Short description of the problem:
Toast doesn't show, z-index is incorrect when present it. 

#### What behavior are you expecting?
Toast should show when present it.

Ionic Version: 2.0.0-rc.0

**Steps to reproduce:**
1. present a modal on a page
2. push a page on this modal
3. present a Toast

**Code :**
1.present a modal
```
let loginModel = this.modalCtrl.create(LoginPage);
loginModel.present();
```
2.push a page on this modal
```
this.navCtrl.push(RegisterPage);
```
3.present a Toast
```
let _toastConfig = {
    message: errMsg,
    duration: 3000,
    position: "bottom"
};
let toast = this.toastCtrl.create(_toastConfig);
toast.present();
```

**Comment by jgw96** [comment] 2016-10-10 16:26
Hello, thanks for opening an issue with us! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/8573.

**Comment by manucorporat** [comment] 2016-10-10 17:16
@jgw96 I have been working in new e2e tests for modals, and I will leave this issue open as I am not sure they are the same issue.

**Comment by flyhuang** [comment] 2016-10-14 03:42
![test](https://cloud.githubusercontent.com/assets/1689430/19375057/f6767ab4-9202-11e6-8b5b-15d035332cdd.png)

ionic 2.0.0-rc.1, this issue is still here.

**Comment by manucorporat** [comment] 2016-10-18 00:02
If you want to push a page inside a modal, you have to provide a ion-nav, since a modal does not their own navigation stack by default. See https://github.com/driftyco/ionic/issues/7580#issuecomment-253733293

**Closed by manucorporat** 2016-10-18 00:02 UTC
Labels: modals, v2
