### ISSUE TITLE
PopoverController#create crashes when given a frozen data object

### ISSUE THREAD

**Issue by Polyergic** [driftyco/ionic#11479] opened 2017-05-02 14:38 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

We have a model that is intended to be immutable, so it freezes the arrays returned by getter methods.  Passing this frozen object as the data for a popover fails:

let data = this.model.getFrozenArray();
let popover = this.popoverCtrl.create( this.popoverPage, data );

The second line fails with exception "TypeError: Can't add property component, object is not extensible"

**Expected behavior:**

It should create the popover just like it does if the data is not frozen

**Steps to reproduce:**

See above

**Related code:**

```
let data = this.model.getFrozenArray();
let popover = this.popoverCtrl.create( this.popoverPage, data );
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.5.0
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.6
ios-deploy version: 1.9.1
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v7.0.0
Xcode version: Xcode 8.3.2 Build version 8E2002
```

**Comment by jgw96** [comment] 2017-05-02 14:48
Hello, thanks for using Ionic. Could you post a minimal repo we can use to reproduce this issue?

**Comment by jgw96** [comment] 2017-05-08 15:57
Hello! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-05-08 15:57 UTC
Labels: needs info, v2

**Comment by Polyergic** [comment] 2017-05-31 18:40
See http://plnkr.co/edit/nKFE2WgEI15SGL9cxw9A?p=preview

The "Click Me" button throws an exception (which you can see in the console).  If you don't `Object.freeze` the data passed to `popoverController.create` it works as expected.
