### ISSUE TITLE
ion-select broken in --prod build

### ISSUE THREAD

**Issue by towardmay** [driftyco/ionic#11476] opened 2017-05-02 11:47 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[ x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
ion-select does not show alert / action-sheet or popup if you build the app with --prod option.
The same app works perfectly and select options are shows if built without --prod option
You can test it in vanilla single page app by adding a simple ion-select

Same behaviour in Android and iOS devices

**Expected behavior:**
-- prod is really important for us since it reduces the app startup time to 3 seconds instead of 7-8 seconds.
We should be able to build for production release without breaking the functionality. If something works in dev, we should be able to see the same behaviour prod. 

**Steps to reproduce:**
You can test it in vanilla single page app by adding a simple ion-select

**Related code:**

```
insert any relevant code here
   <ion-item>
       <ion-label>Toppings</ion-label>
       <ion-select [(ngModel)]="unit" interface="popover">
          <ion-option value="1">1</ion-option>
          <ion-option value="2">2</ion-option>
          <ion-option value="3">3</ion-option>
       </ion-select>
   </ion-item>
```

**Other information:**

Seems like the issue with the build scripts.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 3.1.0
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.6
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: OS X El Capitan
Node Version: v6.10.1
Xcode version: Xcode 8.2.1 Build version 8C1002

```

**Comment by jgw96** [comment] 2017-05-02 14:30
Hello, thanks for using Ionic! Unfortunately we cannot reproduce this issue, would you mind posting a minimal repo we could use to reproduce this issue?

**Comment by fmendoza** [comment] 2017-05-02 14:43
I have an APK build with --prod and the ion-select is working good but I notice that the LoadingController is not showing. Without --prod flag is working.

**Comment by towardmay** [comment] 2017-05-02 22:05
Thanks for looking in to this. I have created a repo with an sample app to demonstrate the issue.
https://github.com/towardmay/ion-select

I have also added readme with the steps I took. Here is a copy:
1. Updated node version v6.10.3
2. npm install -g cordova ionic
3. ionic start super-app tabs
4. ionic platform add android
5. 
(a) ionic emulate android (works, you see the select and you can tap and options open up)
(b) ionic emulate android --prod (Breaks! select shown but no option popup)
(c) ionic build android --prod then Copy the debug apk to a physical device (Breaks! select shown but no option popup)

I hope you can reproduce. It seems to be a blocker for us.

**Comment by rapropos** [comment] 2017-05-02 23:34
I suspect `Alert` is being dead-stripped. A workaround that seems to solve the issue given @towardmay 's repo is to add an `AlertController` parameter to the `HomePage` constructor. I don't believe it has to be actively used in code, just having it get found by DI seemed to be enough to make the select pop properly.

**Comment by towardmay** [comment] 2017-05-03 00:33
Hi @rapropos, spot on!
All release documents point to --prod so I wasn't even aware of aot. --aot does not create this issue and startup time is the same as with --prob.

I also tested by adding AlertController (with --prod) and that also worked if the page is pre loaded; did not work if the page is lazy loaded. 

I will just go ahead of time now and we are good.

**Comment by rapropos** [comment] 2017-05-03 00:51
In my testing, putting the phantom `AlertController` in the constructor of the app component will make selects work in lazily loaded pages, for whatever that's worth.

**Comment by fmendoza** [comment] 2017-05-03 13:25
In my case I injected LoadingController in my app component and now it's working with --prod

Thanks you.

**Comment by WangRongda** [comment] 2017-05-04 09:34
I solve it when I import AlertControl/ActionSheetControl/PopoverCtrl .

**Comment by D3K0** [comment] 2017-05-04 11:04
same problem here, if i build with the --prod tag the ion-select doesn't work for ios, did you solve the problem?

**Comment by tkem** [comment] 2017-05-04 12:55
Same issue here - clicking an `ion-select` triggers an error with ionic-angular 3.1.1 when built using `--prod`; this problem does not occur with ionic-angular 3.0.1.
```
Runtime Error
Uncaught (in promise): Error: No component factory found for t. Did you add it to @NgModule.entryComponents? Error: No component factory found for t. Did you add it to @NgModule.entryComponents? at d (http://10.1.10.198:8100/build/polyfills.js:3:3991) at K (http://10.1.10.198:8100/build/main.js:1:8760) at t.resolveComponentFactory (http://10.1.10.198:8100/build/main.js:2:30804) at t.resolveComponentFactory (http://10.1.10.198:8100/build/main.js:2:31195) at t.resolveComponent (http://10.1.10.198:8100/build/main.js:9:16694) at e._viewInit (http://10.1.10.198:8100/build/main.js:16:26469) at http://10.1.10.198:8100/build/main.js:16:23789 at t.invoke (http://10.1.10.198:8100/build/polyfills.js:3:11562) at Object.onInvoke (http://10.1.10.198:8100/build/main.js:3:5523) at t.invoke (http://10.1.10.198:8100/build/polyfills.js:3:11502) at n.run (http://10.1.10.198:8100/build/polyfills.js:3:6468) at http://10.1.10.198:8100/build/polyfills.js:3:3767 at t.invokeTask (http://10.1.10.198:8100/build/polyfills.js:3:12256) at Object.onInvokeTask (http://10.1.10.198:8100/build/main.js:3:5423) at t.invokeTask (http://10.1.10.198:8100/build/polyfills.js:3:12177)
Stack
Error: Uncaught (in promise): Error: No component factory found for t. Did you add it to @NgModule.entryComponents?
Error: No component factory found for t. Did you add it to @NgModule.entryComponents?
    at d (http://10.1.10.198:8100/build/polyfills.js:3:3991)
    at K (http://10.1.10.198:8100/build/main.js:1:8760)
    at t.resolveComponentFactory (http://10.1.10.198:8100/build/main.js:2:30804)
    at t.resolveComponentFactory (http://10.1.10.198:8100/build/main.js:2:31195)
    at t.resolveComponent (http://10.1.10.198:8100/build/main.js:9:16694)
    at e._viewInit (http://10.1.10.198:8100/build/main.js:16:26469)
    at http://10.1.10.198:8100/build/main.js:16:23789
    at t.invoke (http://10.1.10.198:8100/build/polyfills.js:3:11562)
    at Object.onInvoke (http://10.1.10.198:8100/build/main.js:3:5523)
    at t.invoke (http://10.1.10.198:8100/build/polyfills.js:3:11502)
    at n.run (http://10.1.10.198:8100/build/polyfills.js:3:6468)
    at http://10.1.10.198:8100/build/polyfills.js:3:3767
    at t.invokeTask (http://10.1.10.198:8100/build/polyfills.js:3:12256)
    at Object.onInvokeTask (http://10.1.10.198:8100/build/main.js:3:5423)
    at t.invokeTask (http://10.1.10.198:8100/build/polyfills.js:3:12177)
    at d (http://10.1.10.198:8100/build/polyfills.js:3:3991)
    at l (http://10.1.10.198:8100/build/polyfills.js:3:3244)
    at Object.reject (http://10.1.10.198:8100/build/polyfills.js:3:2600)
    at e._fireError (http://10.1.10.198:8100/build/main.js:16:23433)
    at e._failed (http://10.1.10.198:8100/build/main.js:16:23344)
    at http://10.1.10.198:8100/build/main.js:16:24099
    at t.invoke (http://10.1.10.198:8100/build/polyfills.js:3:11562)
    at Object.onInvoke (http://10.1.10.198:8100/build/main.js:3:5523)
    at t.invoke (http://10.1.10.198:8100/build/polyfills.js:3:11502)
    at n.run (http://10.1.10.198:8100/build/polyfills.js:3:6468)
    at http://10.1.10.198:8100/build/polyfills.js:3:3767
    at t.invokeTask (http://10.1.10.198:8100/build/polyfills.js:3:12256)
    at Object.onInvokeTask (http://10.1.10.198:8100/build/main.js:3:5423)
    at t.invokeTask (http://10.1.10.198:8100/build/polyfills.js:3:12177)
    at n.runTask (http://10.1.10.198:8100/build/polyfills.js:3:7153)
Ionic Framework: 3.1.1
Ionic App Scripts: 1.3.6
Angular Core: 4.0.2
Angular Compiler CLI: 4.0.2
Node: 5.12.0
OS Platform: Linux 3.2
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Linux; Android 4.4.2; Nexus 4 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Mobile Safari/537.36
```

**Comment by rapropos** [comment] 2017-05-04 19:31
I suspect the root cause of this is [app-scripts #936](https://github.com/driftyco/ionic-app-scripts/issues/936).

**Comment by towardmay** [comment] 2017-05-05 00:15
Following app-scripts #936 .. it should be fixed in 1.3.7 scripts
In the mean time, you can add this to your package json and you should be able to use --prod. 
`"config": { "ionic_manual_treeshaking": false}, `

I have tested this and works well. However, it will not remove unused code if any.

**Comment by tkem** [comment] 2017-05-05 09:55
I just upgraded to ionic-app-scripts 1.3.7, and this indeed does seem to fix this problem.

**Comment by jgw96** [comment] 2017-05-05 14:30
Nice! As this is fixed in the latest version of app-scripts I am going to close this issue for now. Thanks everyone!

**Closed by jgw96** 2017-05-05 14:30 UTC
Labels: needs info, v2
