### ISSUE TITLE
Ionic 2 iOS flash/redraw when changing between tabs

### ISSUE THREAD

**Issue by ctcampbell** [driftyco/ionic#5888] opened 2016-03-19 02:32 UTC
#### Short description of the problem:

When switching between tabs on iOS the content within each ion-content appears to be redrawn entirely, causing a brief flash where the content is not visible

#### What behavior are you expecting?

Immediate redraw so that the transition does not appear jerky. This works as expected on Android and in Safari on OSX.

**Steps to reproduce:**
1. make a tabs app
2. fill two tabs with a number of items from an ngFor
3. switch between the tabs

**Which Ionic Version?**

2.0.0 beta 3

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
ios-deploy version: 1.8.5 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v4.2.2
Xcode version: Xcode 7.2.1 Build version 7C1002

**Comment by jgw96** [comment] 2016-03-21 18:40
Hello! Thanks for opening an issue with us! Would you be able to provide a screencast of this? Im having a hard time reproducing it. Thanks!

**Comment by ctcampbell** [comment] 2016-03-21 19:01
Sure, you can see the effect here https://dl.dropboxusercontent.com/u/2459380/flash.mov

**Comment by mhartington** [comment] 2016-03-23 14:20
Moving the conversation over to #3907 

@ctcampbell would you be able to provide a minimal example of this? 
Using the tabs starter I'm not able to replicate this on iOS.

**Comment by mhartington** [comment] 2016-03-23 14:26
Related to ionic2, not v1

**Comment by ctcampbell** [comment] 2016-03-23 19:49
I do get this behaviour on Ionic 1 as well, it's just much more pronounced on ionic 2. A minimal example might be difficult as my app is dependant on a backend API and credentials. I'll see if I can get something together.

**Comment by mhartington** [comment] 2016-03-23 20:03
For sure, just want to keep v1 and v2 related issue separate :grin:

**Comment by ctcampbell** [comment] 2016-03-31 23:16
An update, on ionic 1 I only get this when native scrolling is enabled. Trying to get a simple example together, should have something soon.

**Comment by jgw96** [comment] 2016-04-21 16:09
@ctcampbell Hey! Were you ever able to get that example together using the latest version of Ionic 2 (beta.5)?

**Comment by jgw96** [comment] 2016-04-26 14:47
Hello! As it has been a little while since there was any activity on this issue I will be closing it. Thanks for using ionic!

**Closed by jgw96** 2016-04-26 14:47 UTC
Labels: needs reply, needs:devicetesting, platform:android, platform:ios, v2

**Comment by juergengunz** [comment] 2016-10-25 08:22
Is there a fix for iOS for this issue on v1 now ?
