### ISSUE TITLE
Ionic serve performing dissapointingly very slowly

### ISSUE THREAD

**Issue by mbaaro** [driftyco/ionic#8518] opened 2016-10-05 19:37 UTC
I have recently upgraded to ionic2 rc0 but unfortunately when i do an ionic serve it takes very long (close to five minutes) before my app appears on the browser. This get even worse when i make changes to my code and the changes take very wrong again before they are reflected on the app. This sometimes leads to the computer freezing.
I had been working with ionic2@beta and never experienced this issue. Please someone help.

ionic cli -v 2.1
node -v  5.12.0
npm -v  3.10.7

**Comment by danbucholtz** [comment] 2016-10-05 20:53
Can you run:

```
npm install @ionic/app-scripts@latest
```

We have released some fixes.

Thanks,
Dan

**Comment by mbaaro** [comment] 2016-10-05 20:55
Thank you let me give it a try

**Comment by danbucholtz** [comment] 2016-10-05 20:55
I'm going to close this issue since it's a duplicate of https://github.com/driftyco/ionic/issues/8518. Can we track this there?

Thanks,
Dan

**Closed by danbucholtz** 2016-10-05 20:55 UTC

**Comment by mbaaro** [comment] 2016-10-05 20:57
Sure

**Comment by lygstate** [comment] 2016-12-18 03:06
@danbucholtz duplicate of What?
