### ISSUE TITLE
ion-datetime cannot handle min and max properly

### ISSUE THREAD

**Issue by NoNameProvided** [driftyco/ionic#7946] opened 2016-09-01 20:03 UTC
#### Short description of the problem:

DateTime is empty (on iOS) when a min max is set within the same year.

#### What behavior are you expecting?

DateTime respects the min and max attributes and show the dates in the allowed range.

**Steps to reproduce:**
1. Open the date-picker
2. Realize it works totally incorrectly. 

```html
<ion-item>
  <ion-label>Date</ion-label>
  <ion-datetime displayFormat="DD MMMM" min="2017-01-15" max="2017-10-17" [(ngModel)]="myDate">
  </ion-datetime>
</ion-item>
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 
No error in the console.

**Which Ionic Version?** 2.x

#### Plunker that shows an example of your issue

http://plnkr.co/edit/FAvwZdWaiYnx9Qif8LK4?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

```
ordova CLI: 6.3.1
Gulp version:  CLI version 1.2.2
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.3.1
Xcode version: Xcode 7.3.1 Build version 7D1014 
```

**Comment by jgw96** [comment] 2016-09-01 20:29
Hello, thanks for opening an issue with us! I am going to be closing this issue as a duplicate of https://github.com/driftyco/ionic/issues/6850.

**Closed by jgw96** 2016-09-01 20:29 UTC
Labels: platform:ios, range

**Comment by NoNameProvided** [comment] 2016-09-02 07:24
@jgw96 the two is not the same, my problem is that setting min max simply kill the date picker usually, and no value is present, or only a part of the value.
