### ISSUE TITLE
Cannot hide NavBar with tabs on ionic 2 (sidemenu is okay)

### ISSUE THREAD

**Issue by MrBokeh** [driftyco/ionic#6096] opened 2016-04-09 01:54 UTC
#### Short description of the problem:
Cannogt hide NavBar with tabs on ionic 2 (sidemenu is okay)

#### What behavior are you expecting?
Remove navbar section should be able to hide the NavBar on pages with tabs setup on ionic 2

**Steps to reproduce:**
Only a few steps as below to create the MVP and reproduce the problem, you will see the screen did turn landscape for 50ms and then change back:
Install ionic 2 (http://ionicframework.com/docs/v2/getting-started/installation/): 
`npm install -g ionic@beta`

Create a project (http://ionicframework.com/docs/v2/getting-started/tutorial/):
`ionic start MyIonic2TabsProject tabs --v2`

Remove this on a page:
```
<ion-navbar *navbar>
  <ion-title>Yo</ion-title>
</ion-navbar>
```

Run
`ionic build ios`
then this if you don't have an iPhone plugged in:
`ionic emulate ios`
or this if you have an iPhone plugged in:
`ionic run ios`

**Which Ionic Version?**
**Ionic Version**: 2.0.0-beta.4

**Browser & Operating System**: iOS

#### Plunker that shows an example of your issue
**For Ionic 2 issues** - http://plnkr.co/edit/TW20lftdc5s622pcJPkp?p=info

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.1.1
Ionic Framework Version: 2.0.0-beta.4
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
ios-deploy version: 1.8.5 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v5.9.0
Xcode version: Xcode 7.3 Build version 7D175

**Comment by dendrochronology** [comment] 2016-05-31 20:55
Just adding `hide-nav-bar="true"` to a view element in the v1 tabs example works fine, but no dice in v2. Googling turned up pages of folks having the same issue, with lots of hacks that I can't get to work, at least not in iOS.

**Comment by brandyscarney** [comment] 2016-06-02 03:22
I'm going to close this as a duplicate of https://github.com/driftyco/ionic/issues/5164 but please continue the discussion there. Thanks!

**Closed by brandyscarney** 2016-06-02 03:22 UTC
Labels: v2

**Comment by brandyscarney** [comment] 2016-06-02 03:24
Actually found issue #5556 on it, too so we'll track progress on those.
