### ISSUE TITLE
Page Transition Animation Feature Between Tabs

### ISSUE THREAD

**Issue by maxnathaniel** [driftyco/ionic#4903] opened 2016-01-05 01:11 UTC
Dear Ionic Team,

Was the Page Transition Animation Feature between Tabs removed?

I've read in some posts from the Ionic Forum as well as in this GitHub Repo Issues that it had indeed been removed. 

One of the posts I came across is cited below: 
https://forum.ionicframework.com/t/ui-router-question-related-to-tabs/555

**"it's not often seen in most native tab ux. We mostly see transitions on "back" and "forward" buttons, but not tabs."**

However, based on the Android Apps I have, most of them page transition animations between tabs.

Examples are as follows

1. Google Play Store
2. Facebook
3. Airbnb
4. Coursera 
5. ForkHub
6. ESPN

If it is not removed, can someone point me to the documentation on how to implement it? if not, can the feature be added back into the Ionic Framework? Thank you.

**Comment by ghostgrass** [comment] 2016-01-12 08:55
+1. actually, most of apps have the requirement of cross tab transitions.
hope some good solutions could come

**Comment by szuzul** [comment] 2016-01-16 07:41
You can achieve this with slide-box component but then your scope will stay undestroyed

**Comment by jonmc12** [comment] 2016-02-03 23:24
You guys may want to check out the [ionic native transitions plugin](https://github.com/shprink/ionic-native-transitions).

**Comment by jgw96** [comment] 2016-03-14 18:39
this issue is related to this one https://github.com/driftyco/ionic/issues/5101

**Comment by jgw96** [comment] 2016-04-19 07:45
Gonna close this issue as a duplicate of #5101. If anyone objects just tell me!

**Closed by jgw96** 2016-04-19 07:45 UTC
Labels: animation, feature
