### ISSUE TITLE
bug: menu-close not always setting nextViewOptions

### ISSUE THREAD

**Issue by ackerdev** [driftyco/ionic#3745] opened 2015-05-15 19:19 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When a specific state in my application is transitioned to via the side-menu, the view occasionally (maybe 50% of the time) animates in and causes the nav-bar's menu-toggle button to be hidden, despite the side-menu item having the menu-close directive. It seems like this may be caused by the presence of a `resolve` for this state, whereas all other states in the application have no resolves; it is the only state in the application that demonstrates this behavior.

It seems that the menu-close directive is not consistently setting nextViewOptions on states with resolves, explaining why both the view animates in and the menu-toggle button hides, as it was not set as the historyRoot.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-05-15 19:19
Greetings @ackerdev!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3745). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3745)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by ackerdev** [comment] 2015-05-15 19:36
I think I've found the culprit: https://github.com/driftyco/ionic/blob/master/js/angular/directive/menuClose.js#L36

The view options can potentially expire before a resolve completes. I'm not sure the reasoning behind this; is it possible to remove this timeout completely? Removing this seems to fix the problem entirely.

**Comment by perrygovier** [comment] 2015-05-18 16:05
I'm not entirely sure. 300ms is the length of most animated transitions. 
You're right though, and that means this is a dupe of #3027. 
Lets continue the discussion there.

**Closed by perrygovier** 2015-05-18 16:05 UTC
