### ISSUE TITLE
ionic2 rc2 start very slow on Android

### ISSUE THREAD

**Issue by tunxiaoqing** [driftyco/ionic#9165] opened 2016-11-15 07:27 UTC
My app start need 25s+ on Android .The log as follow.How can I make it faster?Android version is 5.1

11-15 13:41:47.064 4293-4293/com.ionicframework.testapp2345195 W/linker: /system/lib64/libfilterUtils.so: unused DT entry: type 0x6ffffffe arg 0x808
11-15 13:41:47.064 4293-4293/com.ionicframework.testapp2345195 W/linker: /system/lib64/libfilterUtils.so: unused DT entry: type 0x6fffffff arg 0x2
11-15 13:41:47.085 4293-4293/com.ionicframework.testapp2345195 I/System.out: guang 开始加载url。。。。。。
11-15 13:41:47.130 4293-4293/com.ionicframework.testapp2345195 I/WebViewFactory: Loading com.android.webview version 1.0 (code 400002)
11-15 13:41:47.145 4293-4293/com.ionicframework.testapp2345195 I/LibraryLoader: Time to load native libraries: 6 ms (timestamps 1038-1044)
11-15 13:41:47.145 4293-4293/com.ionicframework.testapp2345195 I/LibraryLoader: Expected native library version number "",actual native library version number ""
11-15 13:41:47.162 4293-4293/com.ionicframework.testapp2345195 I/LibraryLoader: Expected native library version number "",actual native library version number ""
11-15 13:41:47.163 4293-4293/com.ionicframework.testapp2345195 I/chromium: [INFO:library_loader_hooks.cc(108)] Chromium logging enabled: level = 0, default verbosity = 0
11-15 13:41:47.178 4293-4293/com.ionicframework.testapp2345195 I/BrowserStartupController: Initializing chromium process, singleProcess=true
11-15 13:41:47.179 4293-4293/com.ionicframework.testapp2345195 W/aoc: Attempt to remove local handle scope entry from IRT, ignoring
11-15 13:41:47.194 4293-4377/com.ionicframework.testapp2345195 W/AudioManagerAndroid: Requires BLUETOOTH permission
11-15 13:41:47.197 4293-4293/com.ionicframework.testapp2345195 W/chromium: [WARNING:resource_bundle.cc(304)] locale_file_path.empty()
11-15 13:41:47.198 4293-4293/com.ionicframework.testapp2345195 I/chromium: [INFO:aw_browser_main_parts.cc(63)] Load from apk succesful, fd=39 off=1382828 len=3242
11-15 13:41:47.198 4293-4293/com.ionicframework.testapp2345195 I/chromium: [INFO:aw_browser_main_parts.cc(76)] Loading webviewchromium.pak from, fd:40 off:239276 len:1143506
11-15 13:41:47.255 4293-4293/com.ionicframework.testapp2345195 E/GED: Failed to get GED Log Buf, err(0)
11-15 13:41:47.307 4293-4293/com.ionicframework.testapp2345195 E/ProxyChangeListener: [getProperty] propertyValue is isEmpty .
11-15 13:41:47.307 4293-4293/com.ionicframework.testapp2345195 E/ProxyChangeListener: [getProperty] final: http.proxyHost = null
11-15 13:41:47.307 4293-4293/com.ionicframework.testapp2345195 E/ProxyChangeListener: [getProperty] propertyValue is isEmpty .
11-15 13:41:47.307 4293-4293/com.ionicframework.testapp2345195 E/ProxyChangeListener: [getProperty] final: https.proxyHost = null
11-15 13:41:47.330 4293-4293/com.ionicframework.testapp2345195 W/chromium: [WARNING:data_reduction_proxy_settings.cc(328)] SPDY proxy OFF at startup
11-15 13:41:47.345 4293-4293/com.ionicframework.testapp2345195 W/aoc: Attempt to remove local handle scope entry from IRT, ignoring
11-15 13:41:47.350 4293-4293/com.ionicframework.testapp2345195 W/AwContents: onDetachedFromWindow called when already detached. Ignoring
11-15 13:41:47.378 4293-4293/com.ionicframework.testapp2345195 W/aoc: Attempt to remove local handle scope entry from IRT, ignoring
11-15 13:41:47.378 4293-4293/com.ionicframework.testapp2345195 W/aoc: Attempt to remove local handle scope entry from IRT, ignoring
11-15 13:41:47.417 4293-4460/com.ionicframework.testapp2345195 E/MPlugin: Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport
11-15 13:41:47.437 4293-4460/com.ionicframework.testapp2345195 W/WebKit: ResourceFetcher::requestResource, type = 0, policy = 3, url = file:///android_asset/www/index.html
11-15 13:41:47.440 4293-4460/com.ionicframework.testapp2345195 I/chromium: [INFO:SkFontConfigParser_android.cpp(187)] ---- Font alias target DINPro (NOT FOUND)
11-15 13:41:47.440 4293-4460/com.ionicframework.testapp2345195 I/chromium: [INFO:SkFontConfigParser_android.cpp(187)] ---- Font alias target DINPro (NOT FOUND)
11-15 13:41:47.440 4293-4460/com.ionicframework.testapp2345195 I/chromium: [INFO:SkFontConfigParser_android.cpp(187)] ---- Font alias target DINPro (NOT FOUND)
11-15 13:41:47.448 4293-4464/com.ionicframework.testapp2345195 I/OpenGLRenderer: Initialized EGL, version 1.4
11-15 13:41:47.485 4293-4464/com.ionicframework.testapp2345195 W/MALI: glDrawArrays:714: [MALI] glDrawArrays takes more than 5ms here. Total elapse time(us): 10759
11-15 13:41:47.511 4293-4464/com.ionicframework.testapp2345195 W/MALI: glDrawArrays:714: [MALI] glDrawArrays takes more than 5ms here. Total elapse time(us): 17036
11-15 13:41:47.539 4293-4460/com.ionicframework.testapp2345195 I/chromium: [INFO:SkFontConfigParser_android.cpp(187)] ---- Font alias target DINPro (NOT FOUND)
11-15 13:41:47.539 4293-4460/com.ionicframework.testapp2345195 I/chromium: [INFO:SkFontConfigParser_android.cpp(187)] ---- Font alias target DINPro (NOT FOUND)
11-15 13:41:47.539 4293-4460/com.ionicframework.testapp2345195 I/chromium: [INFO:SkFontConfigParser_android.cpp(187)] ---- Font alias target DINPro (NOT FOUND)
11-15 13:41:47.606 4293-4293/com.ionicframework.testapp2345195 W/BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 4293
11-15 13:41:47.637 4293-4460/com.ionicframework.testapp2345195 W/WebKit: ResourceFetcher::requestResource, type = 3, policy = 3, url = file:///android_asset/www/cordova.js
11-15 13:41:47.638 4293-4460/com.ionicframework.testapp2345195 W/WebKit: ResourceFetcher::requestResource, type = 2, policy = 3, url = file:///android_asset/www/build/main.css
11-15 13:41:47.638 4293-4460/com.ionicframework.testapp2345195 W/WebKit: ResourceFetcher::requestResource, type = 3, policy = 3, url = file:///android_asset/www/build/polyfills.js
11-15 13:41:47.638 4293-4460/com.ionicframework.testapp2345195 W/WebKit: ResourceFetcher::requestResource, type = 3, policy = 3, url = file:///android_asset/www/build/main.js
11-15 13:41:47.769 4293-4460/com.ionicframework.testapp2345195 W/WebKit: ResourceFetcher::determineRevalidationPolicy, 1002, resource = 0x1027be0500, url = file:///android_asset/www/build/main.css, m_isReload = 0, shouldReload = 0
11-15 13:41:47.769 4293-4460/com.ionicframework.testapp2345195 W/WebKit: ResourceFetcher::requestResource, type = 2, policy = 0, url = file:///android_asset/www/build/main.css
11-15 13:41:47.769 4293-4460/com.ionicframework.testapp2345195 W/WebKit: ResourceFetcher::determineRevalidationPolicy, 1002, resource = 0x1027be0a00, url = file:///android_asset/www/build/polyfills.js, m_isReload = 0, shouldReload = 0
11-15 13:41:47.769 4293-4460/com.ionicframework.testapp2345195 W/WebKit: ResourceFetcher::requestResource, type = 3, policy = 0, url = file:///android_asset/www/build/polyfills.js
11-15 13:41:47.783 4293-4460/com.ionicframework.testapp2345195 W/WebKit: ResourceFetcher::requestResource, type = 3, policy = 3, url = file:///android_asset/www/cordova_plugins.js
11-15 13:41:48.521 4293-4460/com.ionicframework.testapp2345195 W/WebKit: ResourceFetcher::determineRevalidationPolicy, 1002, resource = 0x1027be0f00, url = file:///android_asset/www/build/main.js, m_isReload = 0, shouldReload = 0
11-15 13:41:48.521 4293-4460/com.ionicframework.testapp2345195 W/WebKit: ResourceFetcher::requestResource, type = 3, policy = 0, url = file:///android_asset/www/build/main.js
11-15 13:41:48.543 4293-4460/com.ionicframework.testapp2345195 W/WebKit: ResourceFetcher::requestResource, type = 4, policy = 3, url = file:///android_asset/www/assets/fonts/ionicons.woff2?v=3.0.0-alpha.3
11-15 13:41:48.543 4293-4460/com.ionicframework.testapp2345195 W/WebKit: ResourceFetcher::requestResource, type = 4, policy = 3, url = file:///android_asset/www/assets/fonts/ionicons.woff?v=3.0.0-alpha.3
11-15 13:41:48.543 4293-4460/com.ionicframework.testapp2345195 W/WebKit: ResourceFetcher::requestResource, type = 4, policy = 3, url = file:///android_asset/www/assets/fonts/ionicons.ttf?v=3.0.0-alpha.3
11-15 13:41:48.570 4293-4460/com.ionicframework.testapp2345195 W/WebKit: ResourceFetcher::requestResource, type = 3, policy = 3, url = file:///android_asset/www/plugins/cordova-plugin-device/www/device.js
11-15 13:41:48.571 4293-4460/com.ionicframework.testapp2345195 W/WebKit: ResourceFetcher::requestResource, type = 3, policy = 3, url = file:///android_asset/www/plugins/cordova-plugin-splashscreen/www/splashscreen.js
11-15 13:41:48.572 4293-4460/com.ionicframework.testapp2345195 W/WebKit: ResourceFetcher::requestResource, type = 3, policy = 3, url = file:///android_asset/www/plugins/cordova-plugin-statusbar/www/statusbar.js
11-15 13:41:48.573 4293-4460/com.ionicframework.testapp2345195 W/WebKit: ResourceFetcher::requestResource, type = 3, policy = 3, url = file:///android_asset/www/plugins/ionic-plugin-keyboard/www/android/keyboard.js
11-15 13:42:09.334 4293-4293/com.ionicframework.testapp2345195 I/chromium: [INFO:CONSOLE(1947)] "Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.", source: file:///android_asset/www/build/main.js (1947)
11-15 13:42:09.348 4293-4293/com.ionicframework.testapp2345195 W/chromium: [WARNING:aw_password_handler_delegate_impl.cc(208)] IsSavePasswordEnabled ret is 
11-15 13:42:09.349 4293-4293/com.ionicframework.testapp2345195 W/chromium: [WARNING:password_handler.cc(198)] OnPasswordFormsRendered IsEnabledSavePassword is false
11-15 13:42:09.352 4293-4293/com.ionicframework.testapp2345195 I/chromium: [INFO:CONSOLE(1185)] "deviceready has not fired after 5 seconds.", source: file:///android_asset/www/cordova.js (1185)
11-15 13:42:09.354 4293-4293/com.ionicframework.testapp2345195 I/chromium: [INFO:CONSOLE(4232)] "Native: deviceready did not fire within 2000ms. This can happen when plugins are in an inconsistent state. Try removing plugins from plugins/ and reinstalling them.", source: file:///android_asset/www/build/main.js (4232)
11-15 13:42:09.358 4293-4293/com.ionicframework.testapp2345195 I/chromium: [INFO:CONSOLE(4227)] "DEVICE READY FIRED AFTER", source: file:///android_asset/www/build/main.js (4227)
11-15 13:42:09.365 4293-4293/com.ionicframework.testapp2345195 I/chromium: [INFO:CONSOLE(84626)] "platform加载完毕", source: file:///android_asset/www/build/main.js (84626)
11-15 13:42:12.290 4293-4293/com.ionicframework.testapp2345195 I/chromium: [INFO:CONSOLE(3645)] "home的测试", source: file:///android_asset/www/build/main.js (3645)
11-15 13:42:12.292 4293-4293/com.ionicframework.testapp2345195 I/chromium: [INFO:CONSOLE(85665)] "管理员界面标示4", source: file:///android_asset/www/build/main.js (85665)
11-15 13:42:12.294 4293-4293/com.ionicframework.testapp2345195 I/chromium: [INFO:CONSOLE(7135)] "golbalinstances： 1479188532293", source: file:///android_asset/www/build/main.js (7135)

**Comment by tunxiaoqing** [comment] 2016-11-15 11:21
Look at this as follow,I want to konw which part cost too mush time.
![image](https://cloud.githubusercontent.com/assets/16894961/20303940/bcdb1a2e-ab68-11e6-9135-c46ab062e7c4.png)

**Comment by jgw96** [comment] 2016-11-15 19:06
Hello, thanks for opening an issue with us! What version of Android are you running on? Also, do you have a link to the app your having issues with? Id love to try it on my end!

**Comment by dylanvdmerwe** [comment] 2016-11-16 18:42
Maybe it's related to the plugins installed?

**Comment by jgw96** [comment] 2016-12-01 15:44
Hello @tunxiaoqing , are you still running into this issue?

**Comment by jgw96** [comment] 2016-12-09 21:22
Helo @tunxiaoqing ! Because i cannot reproduce this issue I am going to close this issue for now. Thanks for using Ionic!

**Closed by jgw96** 2016-12-09 21:22 UTC
Labels: v2
