### ISSUE TITLE
Error when using slideTo and initialSlide triggers events

### ISSUE THREAD

**Issue by mbakker96** [driftyco/ionic#10386] opened 2017-02-10 10:20 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The app crashed when using the `this.slides.slideTo(1, 0, false)` in `ngAfterContentInit()` and when I use `this.slides.initialSlide = 1` then it goes to the second second element but it also triggers the events and that is what I not want.

**Expected behavior:**
Slide goes to second element without triggering the events.

**Related code:**
error when I'm using `this.slides.slideTo()`
``` 
message: "Error in ./MainPage class MainPage - inline template:19:4 caused by: undefined is not an object (evaluating 's._snapGrid.length')"
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v6.9.5
Xcode version: Xcode 8.3 Build version 8W109m
```

**Comment by jgw96** [comment] 2017-02-10 19:20
Hello, thanks for opening an issue with us! Instead of using `ngAfterContentInit` can you use `ionViewDidEnter` instead and see if that works?

**Comment by mbakker96** [comment] 2017-02-17 08:24
hi, 

sorry for my late reply! `ionViewDidEnter` does not work because it is not triggered. Can that be because it is a component?

**Comment by jgw96** [comment] 2017-02-17 17:39
ahhh, sorry, did not realize this was not a page but a component. Can you provide a repo or plunkr that i can use to reproduce this?

**Comment by jgw96** [comment] 2017-02-21 21:08
Hello! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-02-21 21:08 UTC
Labels: needs reply, v2
