### ISSUE TITLE
feat: Hide header while scrolling list down

### ISSUE THREAD

**Issue by jtushar53** [driftyco/ionic#7088] opened 2016-06-28 08:06 UTC
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Hide header while scrolling list down and show while scrolling up if fullscreen on ion-content is enable</span>

<span is-issue-template></span>

**Comment by manucorporat** [comment] 2016-06-28 09:15
Duplicate of https://github.com/driftyco/ionic/issues/6690

**Closed by manucorporat** 2016-06-28 09:15 UTC
Labels: feature, header, v2
