### ISSUE TITLE
Bug: Cannot remove back view twice in a row

### ISSUE THREAD

**Issue by manmartinez** [driftyco/ionic#7493] opened 2016-08-01 02:35 UTC
#### Short description of the problem:
When using `$ionicHistory`, calling `removeBackView` more than one time subsequently results in an error and only removes the first backView from the current history

#### What behavior are you expecting?
If I call `removeBackView` twice in a row I expect it to:

1. Remove the previous two views
2. Update the cursor on the current history appropriately.

**Steps to reproduce:**
1. Call `$ionicHistory.removeBackView()`
2. Call `$ionicHistory.removeBackView()` again

**Other information:**
This bug is due to a typo on the history service, that prevents the service from updating the current history's cursor appropriately, [line 640](https://github.com/driftyco/ionic/blob/v1.3.1/js/angular/service/history.js#L640) should be:

```js
currentHistory.cursor -= 1;
```

**Which Ionic Version?** 1.3.1

**Comment by jgw96** [comment] 2016-08-01 15:20
Hello, thanks for opening an issue with us! Would you be able to provide a [plunker](http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview) that demonstrates this issue? Thanks for using Ionic!

**Comment by manmartinez** [comment] 2016-08-01 21:15
Hi @jgw96 Thanks for getting back at me, unfortunately I don't have much time on my hands to do the plunker, it doesn't seem trivial to do as it'd have to allow the user to navigate to a couple of views and then try to remove them if it's absolutely necessary to look into this issue I'll try to find some time during the week to make it but can't promise anything :(

**Comment by jgw96** [comment] 2016-08-09 18:30
Hello! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you get some time and are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-08-09 18:30 UTC
Labels: v1

**Comment by psharbau-cmu** [comment] 2016-12-14 15:39
This is an issue still.  Not sure why closed?  Easy to reproduce, go three views in, try to remove two back views.

**Comment by psharbau-cmu** [comment] 2016-12-14 16:01
Alright, here is the bug.  In ionic-angular.js, there is the removeBackView function.  The last line of that is `currentHistory.currentCursor += -1;`  That just needs to be changed to `currentHistory.cursor += -1;`, or even better, `currentHistory.cursor -= 1;`

**Comment by FraBastiano** [comment] 2017-03-17 11:07
Until the bug will not be fixed you ca use this workaround in you code:

```
var viewHistory = $ionicHistory.viewHistory();
var currentHistory = viewHistory.histories[$ionicHistory.currentHistoryId()];
$ionicHistory.removeBackView();
currentHistory.cursor -= 1;
```
