### ISSUE TITLE
Alert Breaking If Being Called Too Quick 

### ISSUE THREAD

**Issue by saniyusuf** [driftyco/ionic#8150] opened 2016-09-21 00:55 UTC
Imagine my scenario. I have a ToDo application where I use the AlertController to enter a todo. Now after a Todo is added I implemented a feature that allows a toast to be called to show that the ToDo ahs been added. 

The smart thing which I did was place the code of the ToastController within the Dismiss promise of the AlertController instance that way only after the AlertController has dismissed will the toast be created and shown. The problem is it works fine but if I try to Add a Todo very quickly after the Toast is still showing, the App breaks with a very weird error which I can provide. However, if I wait for say 1 second or 2 before clicking everything works as planned.

**Comment by mhartington** [comment] 2016-09-21 00:59
Can you provide any way to reproduce this?

**Comment by saniyusuf** [comment] 2016-09-21 01:15
@mikehamil10 How about this I can push a Github for a project of this that you can pull and see in action. Or would you like to see the code first maybe a smaller gist?

**Comment by rcjsuen** [comment] 2016-09-21 09:35
@sanisyusuf If you could provide a project that fully reproduces the problem, I think that would be great. Providing your error stack trace would also be very helpful.

What operating system and platform are you on? Are you testing this on a device or a browser?

**Comment by saniyusuf** [comment] 2016-09-22 03:59
@mhartington I have invited you as a collaborator to the private repository where you can pull and reproduce

**Comment by mhartington** [comment] 2016-09-22 14:44
![sani](https://cloud.githubusercontent.com/assets/2835826/18752680/2792739a-80b1-11e6-8cd5-a65936ca7e5c.gif)

The only thing I did change was in how the alert was being closed. As mention in [this blog post](http://blog.ionic.io/screencast-ionic-&-async/) if an alert need to be programmatically controlled, you should add `return false` to prevent the button from auto closing it. This way when we all `alert.dismiss().then` we can know that our code is handling it. 


Over all though, nothing appears too out of place. It looks like it's working as intended.

**Comment by saniyusuf** [comment] 2016-09-22 15:04
@mhartington how fast did you try to add a todo. It is about pace so if you try to add the ToDo very quickly then you'd see the error. The stack trace is found in this GIST. 

<script src="https://gist.github.com/saniyusuf/970b041590603c0e01cb8d93c4b92214.js"></script>

**Comment by mhartington** [comment] 2016-09-22 15:17
can you try enabling angular2 productionMode?

```
ionicBootstrap(MyApp, [Todo], {
  prodMode: true
});
```

**Comment by mhartington** [comment] 2016-09-22 15:23
Also, https://github.com/driftyco/ionic/issues/7565

This has been fixed in master, and will be part of the next release. 

@saniyusuf can you jump on slack, would like to chat about changes that you should be aware of.

**Comment by jgw96** [comment] 2016-09-28 17:51
Hello all! I am going to close this issue now as RC.0 is officially out. Thanks for using Ionic!

**Closed by jgw96** 2016-09-28 17:51 UTC
Labels: alert
