### ISSUE TITLE
Can't get debugging work with RC0 and VS 2015

### ISSUE THREAD

**Issue by Rainson12** [driftyco/ionic#8553] opened 2016-10-07 07:59 UTC
Hey,
I am trying hardly to get the new RC0 Version work in VS 2015 (enterprise update 3) with the installed Cordova tools. I also installed the npm task runner extension to bind the ionic 2 task to the build event. But no matter what i do it seems to ignore the breakpoints. I created a new project (ionic start demo --v2 ). I tried debugging in Ripple as well as on device but nothing works. Im running on the ionic-app-scripts version 30. The build process runs through without any issues. I never had any debugging issues with Beta 11. Looking forward to any suggestions

**Comment by jgw96** [comment] 2016-10-07 14:41
Hello, thanks for opening an issue with us! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic-app-scripts/issues/110.

**Closed by jgw96** 2016-10-07 14:41 UTC
