### ISSUE TITLE
Ionic 2: Pushing Tabs page to nav stack does not give back button in header

### ISSUE THREAD

**Issue by daveshirman** [driftyco/ionic#9389] opened 2016-11-28 13:14 UTC
**Ionic version:**  (check one with "x")
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
If you have a tabs page that is pushed onto the nav stack, you don't get a back button in the header.

**Note**: I'm currently using 1 page and a segment control to simulate tabs.  Obviously this is not ideal. So I tried switching the architecture over to a Tabs page with individual pages underneath.  

**E.G.**

 - Jobs Page -> select view building of a job item -> push **BuildingTabsPage**.
 - **BuildingTabsPage** (3 tabs: details, history, comments): no back button is in header.

**Expected behavior:**
When pushing a **Tabs** page to the nav stack, show the back button.  I.e. don't automatically make it a root page with a menu button.

**Other information:**
If this is not possible, provide a way to use a segment control, but make it LOOK like tabs so that the page can be split up accordingly.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Davids-Air:apphazard-app daveshirman$ ionic info

Your system information:

Cordova CLI: 6.2.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: OS X El Capitan
Node Version: v4.3.0
Xcode version: Xcode 8.1 Build version 8B62

```

**Comment by brandyscarney** [comment] 2016-11-28 20:41
Thanks for the issue. I am going to close this as a duplicate of https://github.com/driftyco/ionic/issues/5351.

**Closed by brandyscarney** 2016-11-28 20:41 UTC
