### ISSUE TITLE
ion-tab and Ion Icons platforms exchange

### ISSUE THREAD

**Issue by BugsBunnyBR** [driftyco/ionic#6046] opened 2016-04-05 15:01 UTC
#### Short description of the problem:
While trying to customize the `tabIcon` element, I found out that, if I use tabIcon="md-help", it will work on Android, but not on IOS. I tried tabIcon="ios-briefcase" and some others and it works on both platforms.

#### What behavior are you expecting?
The "md-help" icon should be displayed as the tabIcon in any platform. Or in a broader way, being able to set my own icons.

**Steps to reproduce:**
1. start a new Ionic v2 project with tabs starter
2. change one tabs icon to use "md-help"
3. run ionic serve and set the browser to use iphone

```
<ion-tabs>
  <ion-tab [root]="tab1Root" tabTitle="Tab 1" tabIcon="pulse"></ion-tab>
  <ion-tab [root]="tab2Root" tabTitle="Tab 2" tabIcon="chatbubbles"></ion-tab>
  <ion-tab [root]="tab3Root" tabTitle="Tab 3" tabIcon="md-help"></ion-tab>
</ion-tabs>

```

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

 ionic info 
WARN: ionic.config.js has been deprecated, you can remove it. 

Your system information:

Cordova CLI: 6.1.0 (cordova-lib@undefined)
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.23
Ionic App Lib Version: 2.0.0-beta.13
OS: Distributor ID:     Ubuntu Description:     Ubuntu 15.10 
Node Version: v5.8.0

******************************************************
 Dependency warning - for the CLI to run correctly,      
 it is highly recommended to install/upgrade the following:     

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************

**Comment by jgw96** [comment] 2016-10-04 15:56
Hello, thanks for opening an issue with us. Since https://github.com/driftyco/ionic/issues/8435 is the root cause of this issue I am going to consider this a duplicate and close this issue for now. Thanks!

**Closed by jgw96** 2016-10-04 15:56 UTC
Labels: platform:android, platform:ios, v2
