### ISSUE TITLE
Responsive grid system for various screen sizes

### ISSUE THREAD

**Issue by mikewagz** [driftyco/ionic#10043] opened 2017-01-15 23:35 UTC
**Ionic version:**  (check one with "x")
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] feature request

**Current behavior:**

Currently the grid system works well for a static layout.

**Expected behavior:**

Ideally the grid system would be responsive (a la Bootstrap) to accommodate various mobile device screen sizes and rotations. For example, on a phone in portrait orientation, three `<col width-33>` images in a row look great.  

When I flip it to landscape, however, it looks disproportioned.  In this example, it would be great to have five columns in the row to take advantage of this orientation (ie `<col width-sm-33 width-md-20>`).  

When viewing on a tablet in landscape, maybe I'd want ten images in a row (ie `width-lg-10`).

Any chance we can get this functionality built-in to Ionic 2?

**Comment by ghenry22** [comment] 2017-01-16 02:24
instead of a static percentage of screen width for items it would be handy to be able to set a min-width and max-width (or height) for items in the grid, this provides an envelope that the items can be scaled within which is know to be legible.

Then have the grid fit as many items as possible to a row and wrap, scaling items as required to properly fill the space on the row within the defined min and max.

**Comment by dylanvdmerwe** [comment] 2017-01-16 09:27
I think ionic's grid system still requires enhancements one day. They should take a look at implementing something similar to a bootstrap 4 type of grid system one day.

**Comment by brandyscarney** [comment] 2017-01-17 17:59
Thanks for the issue, I'm going to close as a duplicate of https://github.com/driftyco/ionic/issues/6050. Could you toss some upvotes on that issue? :)

**Closed by brandyscarney** 2017-01-17 17:59 UTC
Labels: v2
