### ISSUE TITLE
Launch is too slow in IONIC 2!

### ISSUE THREAD

**Issue by jbertrand992** [driftyco/ionic#10792] opened 2017-03-15 17:42 UTC
**Ionic version:**  (check one with "x")
[] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Expected behavior:**
My app takes 10 seconds to launch, is it normal? how can I speed up it?

**Comment by vicenterusso** [comment] 2017-03-15 19:05
@jbertrand992 try to build with --release and --prod flags.

**Comment by jgw96** [comment] 2017-03-16 14:22
Helllo @jbertrand992 ! This is something that we are working very very hard on, in fact the 3.0.0 release of Ionic is going to be 95% about making load time faster through code splitting, tree shaking and using Angular 4 which generates smaller AOT code. As @vicenterusso mentions above one thing you need to be sure is to build with the `--prod` flag. I am going to close this as a duplicate of https://github.com/driftyco/ionic-app-scripts/issues/670#issuecomment-274528358.

**Closed by jgw96** 2017-03-16 14:22 UTC
