### ISSUE TITLE
Events.publish returns Array, not Object

### ISSUE THREAD

**Issue by ciesielskico** [driftyco/ionic#6487] opened 2016-05-10 11:40 UTC
#### Short description of the problem:
`Events.publish` returns Array of length 1, not Object

#### What behavior are you expecting?
`console.log(user)` shows that user is an Array of length 1 with the actual Object inside.
Expected behavior is single Object.
I know the solution is to just use result[0], but the docs make it seem like the return would be an Object.

**Steps to reproduce:**
1. Subscribe to 'user:loggedin' event in MainPage
2. Login through auth.provider
3. Publish 'user:loggedin' event in auth.provider after successful login with user-details
4. See that Event-Result is Array, not Object.

```
// authProvider.ts
setLoggedIn(user) {
    console.log('set logged in');
    this.email = user.email;
    this.firstName = user.firstName;
    this.profileImageURL = user.profileImageURL;

    this.events.publish('user:loggedin', user);
  }


// MainPage.ts
this.events.subscribe('user:loggedin', (user) => {
        console.log('user:loggedin event', user);
        this.firstName = user.firstName;
        this.email = user.email;
        this.profileImageURL = user.profileImageURL;
      });
```

**Which Ionic Version?** 1.x or 2.x
Ionic 2.0.0-beta.25

Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS:
Node Version: v5.7.0

**Comment by jgw96** [comment] 2016-05-10 14:41
Hello, thanks for opening an issue with us! You can read more about why the Events.publish returns an array here: https://github.com/driftyco/ionic-site/issues/544, which i am going to close this as a dupe of. Please feel free to comment on that issue!

**Closed by jgw96** 2016-05-10 14:41 UTC
Labels: v2
