### ISSUE TITLE
backbutton is acting crazy

### ISSUE THREAD

**Issue by andrezap** [driftyco/ionic#8120] opened 2016-09-19 13:36 UTC
Hi,

I updated my app to 2.11 and I'm having some issues with the back button. When I press sometimes it backs two pages and sometimes t acts like a push and not a pop. This issue happens when I press the device button or the screen button (navbar).

**Comment by jgw96** [comment] 2016-09-20 18:45
Hello, thanks for opening an issue with us! Can you please post a minimal repo that i can use to reproduce this issue? Thanks for using Ionic!

**Comment by movrack** [comment] 2016-09-21 21:38
To be confirmed, but it look like the problem of @Troknus here : https://github.com/driftyco/ionic/issues/5883#issuecomment-242363406

> I have the same problem with beta 11.
Navigation seems to work well until this.nav.setRoot(xxx) is called. After that, navigation works randomly... When pushing a new page, sometimes nothing happens : the view stay on the current page instead of the new one. **When poping, navigation seems other times to pop twice.**
Everything seems to be correct with the NavController object and everything fires normally. But it seems there is confusion in the DOM : values of z-index properties for ion-page tags are wrong in these cases, so that the wrong page stays above.

**Comment by rcjsuen** [comment] 2016-09-22 03:41
The Z-indices calculation gets wrong sometimes. See also issue #8042.

**Comment by jgw96** [comment] 2016-10-17 16:37
Hello all! Is this still an issue with RC1? Thanks!

**Comment by jgw96** [comment] 2016-10-20 16:16
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-10-20 16:16 UTC
Labels: needs reply, v2

**Comment by andrezap** [comment] 2016-10-20 17:34
Hey, sorry! I totally forgot about this issue, but I updated my app and everything its ok now.
