### ISSUE TITLE
Ionic DateTime 12 AM reverts to 1 AM in picker

### ISSUE THREAD

**Issue by LordOfTheBots** [driftyco/ionic#11665] opened 2017-05-15 06:14 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[ x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[  x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When using `<ion-datetime>`, if a time between 12:00 AM and 12:59 AM is chosen within the picker, when the picker is reopened the hour will default to 1 instead of 12.

**Expected behavior:**
When the picker is reopened the hour should default to 12, which is the value that was chosen.

**Steps to reproduce:**

Reproducible within [Ionic docs](https://ionicframework.com/docs/api/components/datetime/DateTime/). Change one of the example times to 12:xx AM, close and reopen picker.  Time will now show 1:xx AM. 

**Related code:**

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
`Cordova CLI: 6.5.0
Ionic Framework Version: 3.1.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.5
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.8.0
Xcode version: Not installed`

**Comment by jgw96** [comment] 2017-05-15 16:17
Hello, thanks for using Ionic. I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/11154.

**Closed by jgw96** 2017-05-15 16:17 UTC
Labels: v2
