### ISSUE TITLE
bug: CLI cannot generate pages

### ISSUE THREAD

**Issue by jwhubert91** [driftyco/ionic#8254] opened 2016-09-28 15:27 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>First of all, other than some npm issues that I think have largely been fixed, I have loved using Ionic.
I'm having issues now automatically generating pages in my new Ionic v2 project. ionic start appName --v2 works perfectly to generate the folder, then ionic platform add android works perfectly to add the missing platform, but when I input:

ionic g page pageName

Terminal gives me this error:

No ionic-angular package found, do you have Ionic installed? (CLI v2.0.0-beta.37)

Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v6.6.0
Xcode version: Xcode 7.3.1 Build version 7D1014 

The most frustrating thing about this is that it was working just YESTERDAY! So I'm really not sure what happened.</span>

<span is-issue-template></span>

**Comment by jwhubert91** [comment] 2016-09-28 15:31
... Using "ls" in the terminal shows this project is missing the 'app' file normally generated with a new Ionic project. Any ideas why this would happen?

**Comment by jwhubert91** [comment] 2016-09-28 15:59
Update: I've tried creating projects with other layouts: blank and slidemenu- both types of projects generate without the app folder.

**Comment by PeterSenyszyn** [comment] 2016-09-28 16:08
I can confirm this is happening with the latest Ionic beta. When I run ionic start ProjectName --v2, it creates the project without the "app" folder. I'm still however able to ionic serve, which is really unusual.

**Comment by jgw96** [comment] 2016-09-28 16:14
Hello, thanks for using Ionic! Would you all mind uninstalling the beta version of the cli by running `npm uninstall -g ionic`, installing the latest stable version of the cli (npm install -g ionic) and trying again? Thanks!

**Comment by PeterSenyszyn** [comment] 2016-09-28 16:23
Sorry if I'm hijacking this issue, but I'm having the same issue. I did as you instructed (`npm uninstall -g ionic`) (`npm install -g ionic`), and ran `ionic start TestProject --v2`. The project was created fine, but the directory is completely missing the app folder that contains all of the project code.

**Comment by herbzi** [comment] 2016-09-28 16:29
I think the src folder contains the project code now and also the index.html.

**Comment by jgw96** [comment] 2016-09-28 18:15
@PeterSenyszyn That is part of the new directory structure for RC.0, which was released yesterday!  Our new [docs](http://ionicframework.com/docs/v2/), [changelog](https://github.com/driftyco/ionic/blob/master/CHANGELOG.md) and [blog](http://blog.ionic.io/announcing-the-ionic-2-release-candidate/) are now live!

**Comment by PeterSenyszyn** [comment] 2016-09-28 19:04
@jgw96 Wow, what a pleaseant surprise! Thanks a lot! And great job to to everybody on the team :)

**Comment by jgw96** [comment] 2016-09-28 19:46
Thanks @PeterSenyszyn we greatly appreciate it! Also @jwhubert91 I am going to close this issue for now as with the latest ionic cli I cannot reproduce this issue. You can follow the instructions in my [above comment](https://github.com/driftyco/ionic/issues/8254#issuecomment-250216734) for how to install it. Thanks!

**Closed by jgw96** 2016-09-28 19:46 UTC
Labels: needs reply, v2

**Comment by jwhubert91** [comment] 2016-09-28 22:23
Thanks Drifty team for getting this resolved so quickly and keeping up with
the docs.
