### ISSUE TITLE
bug(platform): Ipad pro not detected properly

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic#10209] opened 2017-01-27 15:29 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I have the following code:

```
            if (this.platformService.is('android') && this.platformService.is('tablet'))
                return 'androidtablet';
            else if (this.platformService.is('android'))
                return 'android';
            else if (this.platformService.is('ipad'))
                return 'ipad';
            else if (this.platformService.is('ios'))
                return 'iphone';
            else
                return 'web'; // unknown?
```

When digging through my logs, I found the following which seemed odd:
![pasted_image_at_2017_01_24_10_21_pm](https://cloud.githubusercontent.com/assets/2852839/22376197/b90e0c54-e4b5-11e6-9b64-f805b1962292.png)

This particular app is _only_ able to be run on iPads. The `Platform` user agent detection logic is not correct for the latest iPads it seems.  

Note in the screenshot how all the iPad models 6,7 and 6,8 show up as iPhone whereas they are all running on iPad devices. 

**Expected behavior:**
Check the `Platform` user agent detection logic on the latest iPad devices. 

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0
ios-sim version: 5.0.10
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment] 2017-01-27 19:54
So here is my findings so far: On the latest iPad simulator running 10.2 I am not able to repro this issue. I am adding new unit tests to cover this area a little better just to be 100% sure and to prevent this from breaking in the future. If you can, could you post a repo i could use to reproduce this issue?

**Comment by jgw96** [comment] 2017-01-27 19:58
Removing this from the milestone at the moment since it is not currently reproducible, but @dylanvdmerwe let me know when you are able to do more testing with your device and ill take another look. Thanks!

**Comment by dylanvdmerwe** [comment] 2017-01-31 20:03
My iPad (model 5,3) user agent is: 
>Mozilla/5.0 (iPad; CPU OS 10_2_1 like Mac OS X) AppleWebKit/602.4.6 (KHTML, like Gecko) Mobile/14D27 (4302333408)

Note that this seems to be correctly identified as an iPad. 

It's for model 6,7 that seems to be having a problem.

**Comment by jgw96** [comment] 2017-01-31 22:04
Hmm from some searching on the web it looks like the ipad model 6,7 is the iPad pro. Doing a quick test with the ipad pro simulator. Thanks for the UA @dylanvdmerwe

**Comment by jgw96** [comment] 2017-01-31 22:41
Finally figured out the issue here. I can confirm that this seems to be specific to the iPad pro at the time. It is possible that this also affects other large tablets but im not aware of any other tablets as big as the iPad pro. The biggest Android tablet i know of is the Google Pixel c, but it is only a 10.2 inch screen and the nexus 10, which is a 10 inch screen, works fine.

**Comment by brandyscarney** [comment] 2017-02-02 21:20
This will be fixed in the next release. Released a nightly for this:

```
npm install --save --save-exact ionic-angular@2.0.0-201702022113
```

Let me know if you see any issues, @dylanvdmerwe :)

**Closed by brandyscarney** 2017-02-02 21:20 UTC
Labels: v2
