### ISSUE TITLE
click event not fire with very very small movement

### ISSUE THREAD

**Issue by mashaly100200** [driftyco/ionic#5364] opened 2016-02-08 09:10 UTC
hi ionic team

some time click event not fire if there is very very small movement , this behavior is not in native apps

**Comment by jgw96** [comment] 2016-03-14 05:11
Hello! Thanks for opening an issue with us, but we need a little more info regarding your issue so that we can better help you with it. Would you be able to provide some steps we can follow to reproduce your issue? Also, if you could provide a code sample, plunkr or codepen that we can use to reproduce your issue that would be great! And finally if you could run `ionic info` and post the output here that would be awesome. Thanks again!

**Comment by jgw96** [comment] 2016-03-21 19:08
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!

**Closed by jgw96** 2016-03-21 19:08 UTC
Labels: tap/click
