### ISSUE TITLE
Clicking multiple times on a tab shows black screen

### ISSUE THREAD

**Issue by cmaart** [driftyco/ionic#11078] opened 2017-04-05 19:53 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.0.0**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Click multiple times on a tab to refresh the tab (is this behaviour new? It didn't do this before and I actually would like to turn it off). The view for the tab goes black and broken from this point on.

**Expected behavior:**
Tab shouldn't reload automatically, should not show black screen obvs, shouldn't do anything really.

**Steps to reproduce:**
ionic start myApp tabs --v2
Click multiple times on a tab.

Before (after starting the app): 
![image](https://cloud.githubusercontent.com/assets/4008452/24724081/2440c24a-1a4a-11e7-9119-8db1c6779c34.png)

After (clicking the Home tab multiple times relatively fast):
![image](https://cloud.githubusercontent.com/assets/4008452/24724104/3a67041c-1a4a-11e7-9d6d-bc4f09b53c01.png)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
Your system information:

 ordova CLI: 6.5.0
Ionic Framework Version: 3.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.7.0
Xcode version: Not installed

**Comment by jgw96** [comment] 2017-04-05 20:47
Hello, thanks for using Ionic! We will look into this.

**Comment by youssmak** [comment] 2017-04-07 07:49
same here, seems an important issue.

**Comment by cmaart** [comment] 2017-04-07 07:59
Absolutely

**Comment by rossholdway** [comment] 2017-04-07 12:10
I'm not able to break the page by tapping on tab multiple times running v3.0.1, but can confirm that tapping on the active tab again does cause the page to reload. As far as I can tell, this didn't happen in v2. There is also another issue / duplicate here #11015

**Comment by jgw96** [comment] 2017-04-07 16:03
Hello everyone, after further review I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/11015.

**Closed by jgw96** 2017-04-07 16:03 UTC
Labels: v2
