### ISSUE TITLE
Phonegap Barcode Scanner Plugin iOS doesn't work with Ionic 1.2.4

### ISSUE THREAD

**Issue by hasLoren** [driftyco/ionic#6110] opened 2016-04-11 00:29 UTC
I am consoling errors in the terminal. When I try to bring up the barcode scanner (phonegap-plugin-barcodescanner) with my app using Ionic 1.2.4, it freezes and throws this error in the console for iOS and Android.

`461469 error Error: Can't find variable: cordovascan@http://192..............`

The code following documentation from http://ionicframework.com/docs/1.0.0-rc.0/api/utility/ionic.Platform/:

I updated our code to tell it to only run this stuff  if `ionic.Platform.isWebView()` is true. Beforehand, the plugin was working with an older version of Ionic. After changing this according to Ionic's documentation, the barcode scanner now does not work. How can I tell if this plugin will be compatible with Ionic 1.2.4? Does this error mean that I just have to find another barcode scanner plugin for my app?

```
(function (root) {  
  'use strict';
  root.Application.controller('AppCtrl', [
    '$scope',
    '$ionicPlatform',
    function ($scope, $ionicPlatform) {
      $ionicPlatform.ready(function() {
         if (ionic.Platform.isWebView()) {
          networkRegistry.register({
                // do some stuff
      });
    }
  ]);
})(this);
```

ionic info:
Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.11
Ionic App Lib Version: 0.6.5
ios-deploy version: 1.8.3 
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v4.2.3
Xcode version: Xcode 7.2 Build version 7C68

**Comment by jgw96** [comment] 2016-04-11 14:01
Hello! Thanks for opening an issue with us! Would you be able to provide a codepen that we can use to export and test this issue on our devices? You can use this template i made (http://plnkr.co/edit/jnOrQRtE8rN2WCXDQYQY?p=info) to make it. Thanks again!

**Comment by hasLoren** [comment] 2016-04-11 20:08
It's not able to be produced in webview/browser. it has to do with an issue on iOS and potentially android devices.

**Comment by dually8** [comment] 2016-04-11 20:37
Though I'm using a fork of the phonegap barcode scanner, I'm not able to reproduce this myself.  I've explicitly added Cordova iOS 4.1.1.  Below is my ionic info and package.json.

> Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 1.2.4-nightly-1917
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
ios-deploy version: 1.8.5 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.2.3
Xcode version: Xcode 7.3 Build version 7D175 

```
{
  "name": "test",
  "version": "1.0.0",
  "description": "asdf",
  "dependencies": {
    "chromedriver": "^2.21.2",
    "gulp": "^3.9.1",
    "gulp-concat": "^2.6.0",
    "gulp-cssnano": "^2.1.0",
    "gulp-rename": "^1.2.2",
    "gulp-sass": "^2.1.1"
  },
  "devDependencies": {
    "bower": "^1.7.7",
    "gulp-ignore": "^2.0.1",
    "gulp-phantomcss": "^0.1.1",
    "gulp-sourcemaps": "^1.6.0",
    "gulp-tslint": "^4.3.1",
    "gulp-typescript": "^2.11.0",
    "gulp-util": "^3.0.7",
    "jasmine-core": "^2.3.4",
    "jasmine-reporters": "^2.1.1",
    "karma": "^0.13.19",
    "karma-chrome-launcher": "^0.2.1",
    "karma-cordova-launcher": "0.0.9",
    "karma-jasmine": "^0.3.6",
    "karma-ng-html2js-preprocessor": "^0.2.0",
    "karma-phantomjs-launcher": "^1.0.0",
    "karma-spec-reporter": "0.0.24",
    "phantomjs": "^2.1.3",
    "protractor-jasmine2-html-reporter": "0.0.6",
    "shelljs": "^0.6.0",
    "tslint": "^3.3.0",
    "typescript": "^1.7.5"
  },
  "cordovaPlugins": [
    "cordova-plugin-console",
    "cordova-plugin-app-version",
    "cordova-plugin-device",
    "cordova-plugin-dialogs",
    "cordova-plugin-statusbar",
    "cordova-plugin-inappbrowser",
    "cordova-plugin-camera",
    "cordova-plugin-media-capture",
    "cordova-plugin-file",
    "cordova-plugin-geolocation",
    "cordova-plugin-file-transfer",
    "cordova-plugin-network-information",
    "cordova-plugin-certificates",
    "cordova-plugin-whitelist",
    "cordova-plugin-x-toast",
    "cordova-plugin-transport-security",
    {
      "locator": "https://github.com/dually8/BarcodeScanner.git",
      "id": "phonegap-plugin-barcodescanner"
    },
    {
      "locator": "https://github.com/litehelpers/Cordova-sqlite-enterprise-free",
      "id": "cordova-sqlite-evfree"
    },
    "ionic-plugin-keyboard"
  ],
  "cordovaPlatforms": [
    "android",
    {
      "platform": "ios",
      "version": "4.1.1",
      "locator": "ios@4.1.1"
    }
  ]
}
```

PS: If you have an updated cordova cli, I think it automatically adds the latest iOS version.  You might have to remove it and re-add it.  Not 100% sure.

PSS: Insert shameless plug for my fork of the barcode scanner [here](https://github.com/dually8/BarcodeScannerExample).

**Comment by jgw96** [comment] 2016-04-11 21:30
So, I have tested on my android devices (Nexus 7 2013 running Android 6.0.1 (latest stable public release), Nexus 6 running the Android N dev preview, and a moto x 2014 running android 5.1) and have not been able to reproduce any issue. Would you be able to provide a git repo of you code that i could pull down and use to test on my devices with instead of a codepen? Thanks again!

**Comment by hasLoren** [comment] 2016-04-11 22:18
It's a private repo that can't be shared.. Also, it has to be on a device
because it only happens when `ionic.Platform.isWebView())` is false.

I tried adding and removing ios with `ionic platform remove ios` and `ionic
platform add ios' which doesn't do anything.

**Comment by hasLoren** [comment] 2016-04-11 22:47
```
  "name": "test",
  "version": "1.0.0",
  "description": "test",
  "scripts": {
    "xcode": "open platforms/ios/*.xcodeproj"
  },
  "dependencies": {
    "gulp": "^3.8.11",
    "gulp-concat": "^2.2.0",
    "gulp-minify-css": "^0.3.0",
    "gulp-rename": "^1.2.0",
    "lodash.defaults": "^3.0.0"
  },
  "devDependencies": {
    "bower": "^1.3.3",
    "gulp-autoprefixer": "^2.0.0",
    "gulp-cached": "^1.0.1",
    "gulp-debug": "^1.0.1",
    "gulp-less": "^3.0.0",
    "gulp-remember": "^0.3.0",
    "gulp-sass": "^2.1.0",
    "gulp-sourcemaps": "^1.3.0",
    "gulp-util": "^2.2.14",
    "less-plugin-autoprefix": "^1.1.0",
    "require-dir": "^0.1.0",
    "shelljs": "^0.3.0",
    "xcode": "0.6.2"
  },
  "cordovaPlugins": [
    "https://github.com/EddyVerbruggen/LaunchMyApp-PhoneGap-Plugin.git",
    "https://github.com/whiteoctober/cordova-plugin-app-version.git",
    "org.apache.cordova.console",
    "com.verso.cordova.clipboard",
    "nl.x-services.plugins.socialsharing",
    "nl.x-services.plugins.toast",
    "org.apache.cordova.inappbrowser",
    "org.apache.cordova.device",
    "./engine/cordova-crosswalk-engine-c0.7.1",
    "org.apache.cordova.splashscreen",
    "cordova-plugin-crosswalk-webview",
    "cordova-plugin-splashscreen",
    "com.phonegap.plugins.barcodescanner",
    "cordova-plugin-statusbar"
  ],
  "cordovaPlatforms": [
    "ios",
    "android"
  ]
}
```

**Comment by dually8** [comment] 2016-04-12 18:53
The Cordova plugins might need to be updated due to the new plugin naming conventions. http://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html

**Comment by hasLoren** [comment] 2016-04-18 18:16
Could it potentially be our environment, plugins, or other dependencies
that are clashing? Seems weird that QR scanner wont work with Ionic 1.2.4

**Comment by jgw96** [comment] 2016-04-19 17:14
@hasLoren Have you gotten a chance to try @dually8 's fork of that plugin?

**Comment by dually8** [comment] 2016-04-20 14:55
And also make sure your plugins have no ```.``` (periods) in them.  Due to the new naming convention, you shouldn't see any dots unless you're installing a plugin locally (e.g ```./somefolder/someplugin```)  Things like `org.apache.cordova.console` should now be `cordova-plugin-console`.

**Comment by jgw96** [comment] 2016-04-25 16:34
Hello! I am going to close this issue for now as it has been a little while since there was any activity. Thanks for using ionic!

**Closed by jgw96** 2016-04-25 16:34 UTC
Labels: needs reply, needs:devicetesting, v1

**Comment by hasLoren** [comment] 2016-04-25 19:58
I tried changing the namespace and it still didn't help. Still getting the
same error that it can't find cordova

**Comment by jgw96** [comment] 2016-04-25 20:02
@hasLoren Sorry your still having this issue. Would you mind opening an issue over on the ionic-cli repo (https://github.com/driftyco/ionic-cli) describing this issue please?
