### ISSUE TITLE
ion-label not displaying on iOS

### ISSUE THREAD

**Issue by mattlanham** [driftyco/ionic#6135] opened 2016-04-12 18:01 UTC
When I run my project on iOS the labels are not displaying. However, if I run it on web, they display as expected. It affects all versions of the ion-label such as floating, stacked etc, none of them seem to display correctly on iOS at all

Here's the code from my login page which is affected:

```
<ion-content padding class="login">
    <ion-list>

        <ion-item>
            <ion-label floating>Username</ion-label>
            <ion-input [(ngModel)]="username" type="text"></ion-input>
        </ion-item>

        <ion-item>
            <ion-label floating>Password</ion-label>
            <ion-input [(ngModel)]="password" type="password"></ion-input>
        </ion-item>

    </ion-list>

    <div padding>
        <button block (click)="login()">Sign In</button>
    </div>

</ion-content>
```

Here's a screenshot of how it displays:
![simulator screen shot 12 apr 2016 18 59 47](https://cloud.githubusercontent.com/assets/43322/14470356/f29bf1de-00e0-11e6-9b14-9dcba88f5e9a.png)

`ionic info`:
```
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.4
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
ios-deploy version: 1.8.5 
ios-sim version: 3.1.1 
OS: Mac OS X El Capitan
Node Version: v4.2.3
Xcode version: Xcode 7.3 Build version 7D175
```

**Comment by brandyscarney** [comment] 2016-04-12 19:11
This is a duplicate of https://github.com/driftyco/ionic/issues/6109. It has been fixed and will be released with beta.5. Please see my comment on that issue for a temporary workaround. Thanks! :smile:

**Closed by brandyscarney** 2016-04-12 19:11 UTC
Labels: platform:ios
