### ISSUE TITLE
bug: Dynamic content when ng-repeat used for ion-slide-page

### ISSUE THREAD

**Issue by ilkkanisula** [driftyco/ionic#4764] opened 2015-12-11 17:20 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Ionic v1.2 has new ion-slides directive and I wrote small app creating dynamic ion-slide-page entries from angular array from scope. Dynamic array content doesn't seem to update correctly in repeater. I produced example as a code pen. If you click on "click me" in first visible slide nothing happens. If you switch slide and click the second delete function is called, slide is switched but the slide is not removed from dom.

See this codepen for details: http://codepen.io/ilkkanisula/details/yeNmZg/</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-12-11 17:20
Greetings @ilkkanisula!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4764). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4764)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment] 2015-12-14 17:52
Can reproduce. Happening because of the loop update. Need to find a different way

**Comment by mlynch** [comment] 2015-12-14 20:01
Fixed in master, can you try it and let me know how it works for you? Thanks.

**Closed** 2015-12-14 20:00 UTC
