### ISSUE TITLE
Focus problem with iOS 9.3.2

### ISSUE THREAD

**Issue by rodrigosilvape** [driftyco/ionic#6727] opened 2016-06-01 20:28 UTC
Hello friends. I would appreciate your help.

I have a problem found in version 9.3.2 of iOS.

When you click a text field any keyboard is open and overlaps the field. You can not scroll the page with the keyboard open.

You've found something?

**$ ionic info**
Cordova CLI: 6.2.0
Ionic Framework Version: 1.0.0
Ionic CLI Version: 1.7.15
Ionic App Lib Version: 0.7.2
ios-deploy version: Not installed
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v4.2.4
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment] 2016-06-01 20:37
Hello! Thanks for opening an issue with us! Would you mind creating a plunker or Github repo that i can use to reproduce this issue? Thanks for using Ionic!

**Comment by rodrigosilvape** [comment] 2016-06-01 20:53
I tried to simulate on other platforms, but can not in any way. It's very specific to iOS. It would be a viable Plunker?

**Comment by jgw96** [comment] 2016-06-01 21:03
It sure would! I just need to see the exact code you are using that reproduces it and then I can pull down the plunker and run it on my iphone.

**Comment by jgw96** [comment] 2016-06-06 15:35
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-06-06 15:35 UTC
Labels: keyboard, needs reply, platform:ios, v1
