### ISSUE TITLE
bug: Overflow Scroll Div - can't scroll on ionic rc0

### ISSUE THREAD

**Issue by do-web** [driftyco/ionic#3298] opened 2015-03-12 12:16 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>In beta 14 all works fine but now i can't scroll.

        <div class="content-wrap" style="height: 264px;overflow:scroll;-webkit-overflow-scrolling: touch;">
            <div class="content-scroll" style="height: 1000px">
<div>....Content....</div>
                </div>
        </div>

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-03-12 12:16
Greetings @do-web!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3298). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3298)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment] 2015-03-12 15:42
hey @do-web is your app by chance a side menu project?

**Comment by realityfilter** [comment] 2015-03-12 20:10
I noticed the same problem. Our app is not a side menu project.

**Comment by realityfilter** [comment] 2015-03-12 20:27
I think this is a duplicate of issue 3228. Reverting the changes of commit a5881eaeba7d12d016fe3712c77261e75e863cf3 solves this issue.

**Comment by do-web** [comment] 2015-03-12 22:41
no its just a simple div container that i have created

**Comment by vgmcglaughlin** [comment] 2015-03-13 11:37
@do-web it seems like it could still be the same underlying issue even if you don't use ion-content. I would check if your scroll event hits the `ev.srcEvent.preventDefault();` line added in commit a5881eaeba7d12d016fe3712c77261e75e863cf3 (in which case it is a duplicate of issue #3228).

**Comment by perrygovier** [comment] 2015-03-16 16:40
Closing this as a duplicate, that commit needs to be refactored. It broke too much.

**Closed by perrygovier** 2015-03-16 16:40 UTC
Labels: scroll
