### ISSUE TITLE
ionic v3 super template fail with ionic-native

### ISSUE THREAD

**Issue by peterennis** [driftyco/ionic#11231] opened 2017-04-15 01:37 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
New install ionic and cordova
Choose super template
Fail

**Expected behavior:**
Success

**Steps to reproduce:**
Use the super template

-->

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

NOTE: Warning about Cordova version is false.
![capture027](https://cloud.githubusercontent.com/assets/140737/25059708/2fd14a92-2140-11e7-846d-50d5d2a88af9.PNG)
![capture026](https://cloud.githubusercontent.com/assets/140737/25059710/2fd43c8e-2140-11e7-9baa-1aeb8e84761b.PNG)
![capture025](https://cloud.githubusercontent.com/assets/140737/25059707/2fcf80ae-2140-11e7-94c9-48cbaf716b1b.PNG)
![capture024](https://cloud.githubusercontent.com/assets/140737/25059709/2fd32722-2140-11e7-94d1-1215d79733ef.PNG)

```
Your system information:

 You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.5.0

Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.10.2
Xcode version: Not installed


******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************
```

Package.json
```
{
  "name": "ionic-hello-world",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "4.0.0",
    "@angular/compiler": "4.0.0",
    "@angular/compiler-cli": "4.0.0",
    "@angular/core": "4.0.0",
    "@angular/forms": "4.0.0",
    "@angular/http": "4.0.0",
    "@angular/platform-browser": "4.0.0",
    "@angular/platform-browser-dynamic": "4.0.0",
    "@ionic-native/core": "3.4.2",
    "@ionic-native/splash-screen": "3.4.2",
    "@ionic-native/status-bar": "3.4.2",
    "@ionic/storage": "2.0.1",
    "ionic-angular": "3.0.1",
    "ionicons": "3.0.0",
    "rxjs": "5.1.1",
    "sw-toolbox": "3.4.0",
    "zone.js": "^0.8.4",
    "ng2-translate": "^5.0.0"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.3.0",
    "typescript": "~2.2.1"
  },
  "cordovaPlugins": [
    "cordova-plugin-device",
    "cordova-plugin-whitelist",
    "cordova-plugin-console",
    "cordova-plugin-statusbar",
    "cordova-plugin-splashscreen",
    "ionic-plugin-keyboard"
  ],
  "cordovaPlatforms": [],
  "description": "aesuper: An Ionic project"
}

```

NOTE: "ng2-translate": "^5.0.0"
This requires updating to 6.0.1 and some changes

Ref: https://github.com/driftyco/ionic-app-scripts/issues/891

Ref: https://github.com/ngx-translate/core/issues/507

Note: It is now ngx-translate

Looks like this template was not given any TLC or something else is weird...

**Comment by piotrowski** [comment] 2017-04-15 11:49
What are the commands to create the project you use?

**Comment by peterennis** [comment] 2017-04-15 22:10
Windows 10

ionic start aetheme super --v2
cd aetheme
ionic serve --browser chrome
ionic info

The original test was done on a PC at work with a new install.
This is done at home on my personal dev system.
Same error. Screen captures below:

![capture056](https://cloud.githubusercontent.com/assets/140737/25067074/73a24962-21ed-11e7-9be2-448eff488f81.png)
![capture057](https://cloud.githubusercontent.com/assets/140737/25067076/797711ba-21ed-11e7-8e04-951cbf3746fb.png)
![capture058](https://cloud.githubusercontent.com/assets/140737/25067078/7e62fdec-21ed-11e7-832c-8bf2c1d8be96.png)

**Comment by peterennis** [comment] 2017-04-15 22:41
Upgrade to node 6.10.2 and still the same error.

![capture059](https://cloud.githubusercontent.com/assets/140737/25067241/f813dce8-21f1-11e7-9ffa-4012305abc1f.png)

**Comment by piotrowski** [comment] 2017-04-16 11:37
Ok, the "super" starter seems to not have been updated for the use of Ionic Native 3, which is now standard in the App Base used to create new apps. This issue is tracked here: https://github.com/driftyco/ionic-starter-super/issues/88 (and also a PR linked that fixes the issue)

**Comment by peterennis** [comment] 2017-04-16 19:43
PR link https://github.com/driftyco/ionic-starter-super/pull/84, Thanks.

**Comment by peterennis** [comment] 2017-04-17 02:55
@piotrowski, Have a look at this:
https://github.com/driftyco/ionic-starter-super/pull/95
The PR your referenced does not work as it does not take care of ngx-translate and some other issues.

**Comment by jgw96** [comment] 2017-04-17 14:51
Hello all! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic-starter-super/issues/86

**Closed by jgw96** 2017-04-17 14:51 UTC
