### ISSUE TITLE
bug: Fixed fab z-index issue

### ISSUE THREAD

**Issue by MatanYed** [driftyco/ionic#7687] opened 2016-08-12 13:31 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>ion-item is above fab fixed button, only fix it with z-index (already tried)

picture:
https://s10.postimg.org/55cjnicc9/ionic_2_fab_fixed_problem.png</span>

<span is-issue-template></span>

**Comment by jgw96** [comment] 2016-08-12 15:24
Hello, thanks for opening an issue with us! Would you mind posting the html that makes up your page? Thanks for using Ionic!

**Comment by jgw96** [comment] 2016-08-12 15:25
Note to team: this will most likely be fixed here https://github.com/driftyco/ionic/issues/7505

**Comment by jgw96** [comment] 2016-08-17 20:57
Hello all! Closing this as a duplicate of #7448 . Thanks for using Ionic!

**Closed by jgw96** 2016-08-17 20:57 UTC
Labels: v2
