### ISSUE TITLE
Ionic 2 buttons stop working on device ios

### ISSUE THREAD

**Issue by heldertb** [driftyco/ionic#9408] opened 2016-11-29 16:27 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When running the app on device using 'ionic run ios --device -lcs' not a single button works, even the tab bar buttons
tried using
```
ionic state reset
```
but nothing seems to fix it

Some extra info:
I'm just casually programming an app, and somehow my buttons just stopped working on my iPhone, all of them. But when I run it in the browser the buttons work fine as expected. No errors are displaying in the console, and my code compiles just fine.
I have another test project to check if this is a problem with my code, Ionic, or my device, and it seems to work on the starter project. But not on my further developed one.
I'm having the same behaviour on an emulator.

**Expected behavior:**
All buttons should work

**Steps to reproduce:**
Run the app on device with livereload.

**Related code:**

html:
```
<button (click)="onPress()" ion-button full>Do something</button>
```
ts:
```
onPress = function() {
    this.navCtrl.parent.select(1);
}
```

**Comment by heldertb** [comment] 2016-11-30 12:19
After hours and hours of searching what was going wrong, I found the bug!
It appears that disabling scrolling causes the app to malfunction.
The bugging code:

`
import { Component } from '@angular/core';
import { NavController, App } from 'ionic-angular';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  constructor(public navCtrl: NavController, public app: App) {
  }

  ngAfterViewInit(){
    this.app.setScrollDisabled(true);
  }

  onPress = function() {
    this.navCtrl.parent.select(1);
  }

}
`

So when deleting the `this.app.setScrollDisabled(true);` the buttons start working again.
Hope this helps people in the future, and that this bug can be fixed

**Comment by Blackscr33n** [comment] 2016-11-30 13:40
Happens also to me on iOS but i never disabled the scroll.
It happens if I push from a page where a sidemenu is, then go back and then I open the Sidemenu and I cant click any menu-element. But this happens not everytime. Sometimes it works, sometimes not.
I need to fix this until friday :/

**Comment by manucorporat** [comment] 2016-11-30 13:43
Can you guys try against nightly?

```
npm install ionic-angular@nightly --save
```

**Comment by Blackscr33n** [comment] 2016-11-30 13:58
@manucorporat seems to work, I tried it about 50 times to reproduce the bug and it worked everytime.
I will let other people test it too.

Has nothing to do with this bug, I think, but:
When I navigate back and the actual page seems to be active, there is about 1 second where the new page can't be clicked, I think because the other page is still over the new one.

**Comment by manucorporat** [comment] 2016-11-30 14:03
@Blackscr33n Thanks!

Ionic has mechanisms to disable any click during transitions, I will look into it. We might be blocking events for too long.

I will close this issue for the moment, but people feel free to reopen it if you think the issue was not fixed!

**Comment by heldertb** [comment] 2016-11-30 14:07
@manucorporat Great work, thanx!

**Closed** 2016-11-30 14:07 UTC
Labels: v2

**Comment by Blackscr33n** [comment] 2016-12-01 13:31
@manucorporat I got a bug which I think is related to the nightly build.
Clicking on top of the screen causing a 
> Error: Uncaught (in promise): undefined

and the screen seems to get rerendered (it flicker).
On RC3 I don't have the error in the console but the "flicker" is still there but weaker then on the nightly

Hope it is okey that I post this here? Or should I create a new issue?

**Comment by cperezvinsite** [comment] 2017-05-16 17:18
I Have a similar issue, i'm working with oauth, then I open the in app browser to use google, then when I return I can't touch any element on the page, neither buttons nor inputs, the safari debbuger doesn't read my touch. I think the problem is when the in app browser close the ionic app can't enable the touch mechanisms
