### ISSUE TITLE
bug: navigatiing to tabs missing back button & animation

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic#3135] opened 2015-02-18 10:40 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>We often have occasions when we need to navigate to a tab page from another link. This popular use case does not seem to be supported in ionic which is problematic.

 1. When navigating to a tab page, there is no way to go back (using a standard platform-specific ion-nav-back-button) to the previous page. 
 2. When navigating to the above mentioned tab page, there is no animation. It just throws you into the tab page which I don't believe is correct. 

I understand this has something to do with histories, but it can't be insurmountable. Tab screens are not always the starting point for apps, and as such you need to be able to go back out of them should there be something in the navigation stack.

A codepen to illustrate the example: http://codepen.io/squrler/pen/xbLbgV

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-02-18 10:40
Greetings @dylanvdmerwe!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3135). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3135)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by dylanvdmerwe** [comment] 2015-02-18 12:58
A work around for now: http://plnkr.co/edit/v3xTq1WVksSNWTU82OjL?p=preview

However the custom back button looks really bad.

**Comment by CoenWarmer** [comment] 2015-02-18 13:01
This is a duplicate of: https://github.com/driftyco/ionic/issues/2997 (your issue uses my Codepen ;)

**Comment by mhartington** [comment] 2015-02-24 22:04
duplicate of https://github.com/driftyco/ionic/issues/2997

**Closed by mhartington** 2015-02-24 22:04 UTC

**Comment by syed-haroon** [comment] 2016-01-21 19:39
Please try this:
```<ion-view>
  <ion-pane>
    <ion-tabs class="tabs-top">
      <ion-tab title="Home">
        <!--Tab content goes here-->
      </ion-tab>
      <ion-tab title="About">
        <!--Tab content goes here-->
      </ion-tab>
    </ion-tabs>
  </ion-pane>
</ion-view>```

**Comment by chenjin0624** [comment] 2016-07-22 03:39
perfect solution to this problem:
This is actually a big bug, so I'm trying to solve this problem.
in tabs's ion-tab directive add on-deselect="onTabDeselected()" and onTabDeselected function add $ionicHistory.clearHistory();

example:
html:
  <ion-tabs class="tabs-icon-top tabs-color-active-positive">

    <ion-tab title="Status" icon-off="ion-ios-pulse" icon-on="ion-ios-pulse-strong" href="#/tab/dash" on-select="onTabSelected()" on-deselect="onTabDeselected()">
      <ion-nav-view name="tab-dash"></ion-nav-view>
    </ion-tab>

    
    <ion-tab title="Chats" icon-off="ion-ios-chatboxes-outline" icon-on="ion-ios-chatboxes" href="#/tab/chats" on-select="onTabSelected()" on-deselect="onTabDeselected()">
      <ion-nav-view name="tab-chats"></ion-nav-view>
    </ion-tab>

    
    <ion-tab title="Account" icon-off="ion-ios-gear-outline" icon-on="ion-ios-gear" href="#/tab/account" on-select="onTabSelected()" on-deselect="onTabDeselected()">
      <ion-nav-view name="tab-account"></ion-nav-view>
    </ion-tab>
  </ion-tabs>

js:
.controller('TabCtrl', function($scope, $rootScope, $ionicHistory) {
  
  $scope.onTabSelected = function(){

    console.log('onTabSelected');

    $ionicHistory.clearHistory();
  }

  $scope.onTabDeselected = function(){
    console.log('onTabDeselected');
    $ionicHistory.clearHistory();
  }
})

**Comment by chenjin0624** [comment] 2016-07-22 03:42
also solution to this problem for duplicate of #2997, only test for tabs application type.
