### ISSUE TITLE
bug: Adding *ngIf to the button breaks Thumbnail List

### ISSUE THREAD

**Issue by vvl** [driftyco/ionic#5332] opened 2016-02-04 18:32 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I took the example for Thumbnail List form the Ionic web site (http://ionicframework.com/docs/v2/components/#thumbnail-list) and added an *ngIf attribute on the <button> element inside the list. As soon, as the condition attribute is added, the list is not displayed correctly anymore.

Here is a picture showing the bug: https://dl.dropboxusercontent.com/u/14863975/ngIf-on-button-in-thumbnail-list.png

Here is the source code: http://codepen.io/anon/pen/WrgYYy</span>

<span is-issue-template></span>

**Comment by brandyscarney** [comment] 2016-02-05 00:13
This is a duplicate of #5060 but thank you for the issue!

**Closed by brandyscarney** 2016-02-05 00:13 UTC
Labels: v2
