### ISSUE TITLE
'nav-decor' hides GoogleMap

### ISSUE THREAD

**Issue by ZiFFeL1992** [driftyco/ionic#7205] opened 2016-07-05 09:50 UTC
#### Short description of the problem:
Since this commit: https://github.com/driftyco/ionic/commit/7842991c1a0771639df5e7c7df0eed47549c5a00

There is a black layer between the touchable transparent layer and the map while using https://github.com/mapsplugin/cordova-plugin-googlemaps plugin on iOS platform.

#### What behavior are you expecting?
See the map. Workaround:

 ```
 ionViewWillEnter(): void {
    document.getElementsByClassName('nav-decor')[2].className += ' hide';
    document.getElementsByClassName('nav-decor')[3].className += ' hide';
  }

  ionViewWillLeave(): void {
    document.getElementsByClassName('nav-decor')[2].className = 'nav-decor';
    document.getElementsByClassName('nav-decor')[3].className = 'nav-decor';
  }
```

I have a tabs template with 3 tabs.
 

**Which Ionic Version?** 1.x or 2.x
2.0.0-beta.10

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

```
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v4.3.0
Xcode version: Xcode 8.0 Build version 8S128d
```

**Comment by jgw96** [comment] 2016-07-05 15:52
Hello, thanks for opening an issue with us! Would you be able to provide a repo that demonstrates this issue? Thanks for using Ionic!

**Comment by lthh89vt** [comment] 2016-07-07 04:36
I'm having exact same issue.

nav-decor created a black layer on top of the map.

My way to fix it is using css
```
ion-app._gmaps_cdv_ .nav-decor {
    background-color: rgba(0,0,0,0);
}
```

**Comment by ZiFFeL1992** [comment] 2016-07-07 09:08
That way is better than mine, I'll provide an example of the bug later today :)

**Comment by jgw96** [comment] 2016-07-13 15:14
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-07-13 15:14 UTC
Labels: platform:ios, v2

**Comment by ZiFFeL1992** [comment] 2016-07-18 15:31
This still an 'issue' after updating my app to latest nightly.

Demo: https://drive.google.com/file/d/0B5rCifUQQ0c4R1ZvTFIzOXZRQVU/view?usp=sharing
If I remove from safari nav-decor layer I can see the map.

I'll keep disabled the transitioning shadow on maps, that seems to be the best solution.

**Comment by tgensol** [comment] 2016-07-31 02:26
Same for me with the last nightly.

I used the solution by @lthh89vt , and it is working great !

**Comment by pekastel** [comment] 2016-07-31 19:12
+1 for the @lthh89vt solution!  It's working for me too.

**Comment by kaikcreator** [comment] 2016-08-06 14:31
Same issue still afecting with ionic 2.0.0 beta 11, and solved with trick from @lthh89vt 

@jgw96: as this is not caused by the plugin but by the nav-decor layer that ionic adds, shouldn't this issue be left open until it is solved?  Maybe @lthh89vt solution must be included in ionic CSS.

**Comment by infinitysky** [comment] 2016-08-14 02:59
Hi all, this problem still affect on my project.

Here is my development environment:
Cordova CLI: 6.3.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.8.6 
ios-sim version: 3.1.1 
OS: Mac OS X El Capitan
Node Version: v4.4.3
Xcode version: Xcode 7.3 Build version 7D175 


I have to enable the scss code for `nav-decor`
```css
ion-app._gmaps_cdv_ .nav-decor{
  background-color: transparent !important;
}
```

I have to say yes it works for me temporarily. However, on my project, I have got multiple tabs then it cause the following problem:
After I boot up the application, It looks OK.
![snip20160814_4](https://cloud.githubusercontent.com/assets/1997572/17646832/29a750da-621e-11e6-9c84-09728724b885.png)

However, once I am going to other tab and back. It shows me this screen.

Other screen:
![snip20160814_5](https://cloud.githubusercontent.com/assets/1997572/17646834/5cb16812-621e-11e6-8cd4-7a516d76ca1d.png)

back to map:
![snip20160814_6](https://cloud.githubusercontent.com/assets/1997572/17646835/6a3defd2-621e-11e6-9023-e7e9608dc938.png)

These two screens have been puts together, and the google map is missing....


Anybody have ideas to help me gets out of this "hole" please?

**Comment by DavidTalamona** [comment] 2016-11-16 21:20
The issue still exists in 2.0.0.rc2 and I think it should still be fixed cause people like me keep running into this and it took me a while to find the CSS hack above.

@jgw96 please re-open this ticket here because I did not find another one that's open and trackable.

**Comment by kodeine** [comment] 2016-11-20 04:55
@jgw96 
i am facing the same issue on iOS. Can someone please make this a priority?

**Comment by tgensol** [comment] 2016-11-20 09:37
+1

**Comment by EralpB** [comment] 2016-12-06 18:27
+5

**Comment by dimitri320** [comment] 2017-02-28 21:12
Same here, and none of the CSS tricks work for me. The map still doesn't show.
I am however getting API Requests recorded on the Google Console, so the calls are being made, but the map is not being displayed.

**Comment by lukeb2014** [comment] 2017-03-28 22:20
Getting the same issue.
Map on iOS causes black background instead, CSS tricks didn't work.

**Comment by kaikcreator** [comment] 2017-03-29 10:43
Try display none, it works for me:

```
ion-app._gmaps_cdv_ .nav-decor{
    display: none !important;
}
```

**Comment by dominikstrasser** [comment] 2017-03-29 12:00
Fyi: For me the Map only works in "pages" not in modals. So maybe try to set your "map-page" as root page and don't `modalCtrl.create(..).present()` it...

**Comment by lukeb2014** [comment] 2017-03-30 17:11
I added that css @kaikcreator and it didn't work. However, the code is correct as when I open safari inspector and set nav-decor to `display: none` it works. I probably need to clean and rebuild and it'll work fine, or I need to adjust the css element. Thanks!

**Comment by hamdiceylan** [comment] 2017-04-15 14:10
app.scss

ion-app._gmaps_cdv_ .nav-decor{
  background-color: transparent !important;
}

worked for me

**Comment by szankelDvag** [comment] 2017-04-28 13:12
I have the same issue:

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.0 
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v7.6.0
Xcode version: Xcode 8.3.2 Build version 8E2002

Ionic native 3.5

I also have the issue on Android. We are trying to display the map in a small container on the page and the cordova js is walking up the DOM making any parents black.

Can somebody help?

**Comment by joesleiman** [comment] 2017-05-05 13:10
app.scss : 
ion-app._gmaps_cdv_ .nav-decor{
    background: none !important;
}
solved my issue

**Comment by dominikstrasser** [comment] 2017-05-05 14:36
fyi - if you see the map but you can't interact (click, drag, zoom, ...) then use
```
ion-app.gmaps_cdv .nav-decor{
   display: none !important;
}
```
at least this works for me ;)

**Comment by petivagyok16** [comment] 2017-05-15 14:09
Had same issue on android, in chrome. CSS tricks solved it.

**Comment by wuilmerj24** [comment] 2017-06-06 04:40
Greetings I added both app.css, as in the home.css and it does not work for me. Here I leave the repo for you to review

**Comment by Stukongeluk** [comment] 2017-06-08 08:08
Well after adding:
```css
ion-app.gmaps_cdv .nav-decor{
   display: none !important;
}
```
The map loads, but I can't navigate to other pages for some reason anymore.
Using a side-menu here to navigate. Without the css code, the apps works perfectly except the page which has Google maps.
This problem only exists on a iOS device or emulator.

**Comment by jsanta** [comment] 2017-06-09 23:43
@Stukongeluk Just faced the same problem with the sidemenu.
Try something like this on your constructor:
```
constructor(private geolocation: Geolocation,
    private googleMaps: GoogleMaps,
    public navCtrl: NavController,
    public navParams: NavParams,
    public menuController: MenuController) {

    // https://forum.ionicframework.com/t/google-maps-making-sidemenu-unusable/69237/22
    let leftMenu = menuController.get(); //  menuController.get('left');

    if (leftMenu) {
      leftMenu.ionOpen.subscribe(() => {
        console.log('Menu opened');
        if (this.map) {
          this.map.setClickable(false);
        }
      });

      leftMenu.ionClose.subscribe(() => {
        console.log('Menu closed');
        if (this.map) {
          this.map.setClickable(true);
        }
      });
    }
  }
```

**Comment by jsanta** [comment] 2017-06-10 00:30
Still an issue on latest Ionic (v3.3.0)

```
    Cordova Platforms               : android 6.1.2 ios 4.3.1
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v8.0.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002
    ios-deploy : 1.9.1
    ios-sim    : 5.0.6
```

**Workaround**:
On your map's page scss file add the following at the end (after the `page-map {}`block:
```css
.ios page-map.ion-page.show-page ~ .nav-decor {
    display: none!important;
}
```
(supposing your map page is called *map*)

Tried all CSS workarounds mentioned before, but none worked for me, so I figured this out debugging using Safari.
Now I'm struggling with a navigation issue, but that's another story.

**Comment by MMokhtari** [comment] 2017-06-11 18:51
I have the same issue the map is shown but you can't do any thing ,like there is another layer on top of it only on ios ,
@jsanta  did u manage to solve it ?

**Comment by Hanzofm** [comment] 2017-06-20 13:14
Hi,
Same problem with IOS.

I've already tried 

ion-app.gmaps_cdv .nav-decor{
   display: none !important;
}
And the other versions and then I have no black screen but the layout of the maps is not showing. The event of MAP_READY is fired and on android same code is working correctly

Like this

http://i66.tinypic.com/2j2sxau.png

Any idea?

**Comment by jsanta** [comment] 2017-06-20 14:06
@MMokhtari Solved the problem using the code I included. Try to debug your app using the code inspector in Safari. 
Also try not to mix solutions.

And beware of the sidemenu isopen/isclosed observable, you can have a memory leak because of not unsubscribing to these events.

**Comment by efstathiosntonas** [comment] 2017-06-27 10:18
@Hanzofm I used @jsanta solution, keep in mind that the css code must be outside of page-map, example:

```
.ios page-map.ion-page.show-page ~ .nav-decor {
  display: none !important;
}
page-map {
  #map {
    height: 100%;
  }
}

```

**Comment by jorgemejia** [comment] 2017-06-30 20:46
My solution was, do not initialize the map on the constructor, initialize it on the ionViewDidLoad.
```

ionViewDidLoad() {
    console.log('ionViewDidLoad Maps');
    setTimeout(()=>{
        this.loadMap();
    }, 1000)

  }
```

**Comment by soulmecca** [comment] 2017-07-01 03:36
In my case, it was background not display. 

.ios .ion-page.show-page ~ .nav-decor {
  background: none;
}

**Comment by frozenxis** [comment] 2017-07-03 22:09
i got the black screen. pulling my hair for about 3h now...

> global packages:
> 
>     @ionic/cli-utils : 1.4.0
>     Cordova CLI      : 7.0.1
>     Ionic CLI        : 3.4.0
> 
> local packages:
> 
>     @ionic/app-scripts              : 1.3.7
>     @ionic/cli-plugin-cordova       : 1.4.0
>     @ionic/cli-plugin-ionic-angular : 1.3.1
>     Cordova Platforms               : ios 4.4.0
>     Ionic Framework                 : ionic-angular 3.4.2
> 
> System:
> 
>     Node       : v7.10.0
>     OS         : macOS Sierra
>     Xcode      : Xcode 8.3.3 Build version 8E3004b
>     ios-deploy : 1.9.1
>     ios-sim    : 6.0.0
>     npm        : 5.0.4

**i just followed the official ionic docs**... why can't this be sufficient? why do i have to spend hours and hours on forums and stackoverflow... 

i love you Ionic but you don't love me back!

**Comment by wf9a5m75** [comment] 2017-07-06 01:34
This is the author of the cordova-googlemaps-plugin.

As of the google maps plugin `2.0.0-beta2-20170705-1715`, the plugin inserts the css automatically. 

```css
._gmaps_cdv_ .nav-decor {
    display: none !important;
    background-color: rgba(0,0,0,0) !important;
    background: rgba(0,0,0,0) !important;
}
```

This thread helps me to solve this issue. Thank you for discussing.

**Comment by andaGS** [comment] 2017-08-22 06:40
its not work,my ios still black screen, please help me 
thre is my css:
  ion-app._gmaps_cdv_ .nav-decor{
    background-color: transparent !important;

      }
   page-belanja-map {
        #map {
          width: 100%;
          height: 60%;
        }
      }
