### ISSUE TITLE
RC0 iOS 10 Select Bug

### ISSUE THREAD

**Issue by Chuckv01** [driftyco/ionic#8496] opened 2016-10-05 00:38 UTC
#### Short description of the problem:

On iOS 10 when buttons on a select are pressed the click is propagated to inputs behind the select. This causes the keyboard to appear right after the select is dismissed.

It only seems to happen when these config options for scrollAssist & autoFocusAssist are in place:

```
    IonicModule.forRoot(MyApp, {
      scrollAssist: false,
      autoFocusAssist: false
    }),
```
#### What behavior are you expecting?

The click would not be registered on inputs behind the select button.

**Steps to reproduce:**
# Step 1:

![1](https://cloud.githubusercontent.com/assets/1181306/19097362/f83cd840-8a58-11e6-9e24-8d67b2d2f25b.PNG)
# Step 2:

![img_0031](https://cloud.githubusercontent.com/assets/1181306/19097373/19236b6e-8a59-11e6-959e-f53f38c0807a.PNG)

RC0
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.7.0
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by jgw96** [comment] 2017-05-18 17:55
Hello all! Because i cannot reproduce this issue anymore in the latest version of Ionic, I am going to close this issue for now. Thanks for using Ionic and feel free to comment if you are still having this issue on the latest version of Ionic.

**Closed by jgw96** 2017-05-18 17:55 UTC
Labels: v2
