### ISSUE TITLE
Ionic3 IOS in device multiple click on tab with black screen

### ISSUE THREAD

**Issue by Bennygx** [driftyco/ionic#11165] opened 2017-04-11 10:41 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Apparently this only occur on IOS device with Ionic3. 
I have tried with my own project and also the official Ionic3 project files, both result in black screen after multiple click on tabs.
[screenshot of the issue](https://cdn-enterprise.discourse.org/ionicframework/uploads/default/optimized/3X/b/a/ba2af75db899f3c125c2f577cf159404dbb67abe_1_272x500.png)

**Steps to reproduce:**
Note on virtual device after about 20-40 clicks the black screen would result in black screen, in real device is about 4-5 clicks on tab would result in black screen. 

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.2
Xcode version: Not installed
```

**Comment by jgw96** [comment] 2017-04-11 14:21
Hello, thanks for opening an issue with us. I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/11015

**Closed by jgw96** 2017-04-11 14:21 UTC
