### ISSUE TITLE
bug: iOS 9 html file select

### ISSUE THREAD

**Issue by mihail-petkov** [driftyco/ionic#4420] opened 2015-09-24 09:08 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>I have `<input type="file" accept="image/*" />`

It shows only a cancel button which is not able to be selected and will not go away until you close the app and re launch.

![Image]
(http://s7.postimg.org/t5mrua7uz/IMG_3628.png)</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-09-24 09:08
Greetings @mihail-petkov!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4420). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4420)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Zorgatone** [comment] 2015-10-09 07:54
I think you may need a cordova plugin to do that. maybe?

**Comment by jgw96** [comment] 2016-03-15 15:50
Hello! Thanks for opening an issue with us, we just need a little more info from you so that we can better help you with your issue. Would you mind posting a code sample, plunkr or codepen that we can use to reproduce your issue? Also, would you mind running `ionic info` and posting the output? Thanks again!

**Comment by jgw96** [comment] 2016-03-21 19:57
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!

**Closed by jgw96** 2016-03-21 19:57 UTC
Labels: v1
