### ISSUE TITLE
Hard back button on <ion-select> does not close pop up (Android)

### ISSUE THREAD

**Issue by Ronald-13** [driftyco/ionic#10217] opened 2017-01-28 04:27 UTC
When you press the hard back button on ion-select, the pop up does not close, instead it changes the background page. The same issue is seen even for DatePicker. when the pop ups are triggered from html, there is no way we can close it, unless we press "cancel"/"ok" button, or if we touch around the pop up screen. Since android users like to use the hard back button, it is of utmost importance to fix this issue.

**Comment by jgw96** [comment] 2017-01-30 15:35
Hello, thanks for opening an issue with us! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/10168 because it is caused by the same underlying issue. Thanks for using Ionic!

**Closed by jgw96** 2017-01-30 15:35 UTC
