### ISSUE TITLE
Problem changed between two views

### ISSUE THREAD

**Issue by hernangiraldo89** [driftyco/ionic#11132] opened 2017-04-08 15:59 UTC
**Ionic version:**  (check one with "x")
[ X] **1.x**
[ ] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I have changed from one view to another. When I do this, the app generated a horizontal scroll with two views, previous and new.

**Expected behavior:**
Show only the new view.

**Steps to reproduce:**
Nothing special. Only passed between two views.

**Related code:**
First view:
```javascript
.state('private.dashboard', {
                url : '/dashboard',
                views : {
                   'private' : {
                        templateUrl : 'private/dashboard/dashboard.html'
                    }
                }
            })
```

Second view:
```javascript
.state('public.login', {
                url : '/login',
                views : {
                    'public' : {
                        templateUrl : 'public/login/login.html'
                    }
                }
            })
```

![captura de pantalla 2017-04-08 a las 10 41 12 a m](https://cloud.githubusercontent.com/assets/8507433/24830371/67558082-1c4a-11e7-9b91-99d72b2fc51e.png)

**Comment by jgw96** [comment] 2017-04-10 14:29
Hello, thanks for opening an issue with us. Could you share a repo we can use to reproduce this issue?

**Comment by hernangiraldo89** [comment] 2017-04-10 15:04
In this moment I'm working in a project for a client, the repo is private and I'm unauthorized to shared it.
I know this is a problem, but I reported this issue to know if an other person  had the same problem and could solved.
I would be very grateful if anyone could help me.

**Comment by jgw96** [comment] 2017-04-14 15:38
Hello @hernangiraldo89. You do not have to share the actual repo, in fact it would be more ideal if you could share a minimal reproducible example repo that does not include all the code in your app, but only the minimal amount of code required to reproduce the issue. Sorry i was not more clear with this earlier.

**Comment by jgw96** [comment] 2017-04-24 16:16
Hello! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-04-24 16:16 UTC
Labels: needs info, v2
