### ISSUE TITLE
Ionic2: Skip initial emit of ionChange on checkbox with [(ngModel)]

### ISSUE THREAD

**Issue by tbmk** [driftyco/ionic#7835] opened 2016-08-23 10:44 UTC
In Ionic 2 using a checkbox with [(ngModel)] and an ionChange event causes this event to be fired when the initial value through ngModel is loaded when initializing the page. There should be an ability to only register an actual change of the bound value, without being fired when the page is loading.

```html
<ion-checkbox [(ngModel)]="myModel" (ionChange)="doSomethingWhenModelActuallyChanges()">
</ion-checkbox>
```

**Comment by jgw96** [comment] 2016-08-23 14:22
Hello, thanks for opening an issue with us! As this seems to be the same issue as #7806 just with a different component i am going to close this issue as a duplicate of that issue. Thanks for using ionic!

**Closed by jgw96** 2016-08-23 14:22 UTC
Labels: checkbox, v2
