### ISSUE TITLE
Ionic 2 scroll freezes in iOS Safari.

### ISSUE THREAD

**Issue by jodybrewster** [driftyco/ionic#10454] opened 2017-02-15 16:38 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x** & the recent RC versions

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Scroll freezes in iOS wkWebView and Safari. See video here... https://youtu.be/OtSY6v9ftKU

**Expected behavior:**
Scroll shouldn't freeze 

**Steps to reproduce:**
I can recreate this issue on any ion-content view on iOS 10 in platform browser or ios. What you can do is once you have enough content to scroll vertically, you can scroll the content to the bottom of the view, tap once on the bottom of the screen, then start scrolling like crazy. It immediately goes into an unresponsive frozen like state. This is a little hard to reproduce and its gotten better with releases. But its still there.  It also seems to happen more when going out of safari and coming back in then immediately scrolling.

**Related code:**

All ion-content views with scrolling

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Cordova CLI: 6.5.0
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0
ios-sim version: 5.0.12
OS: macOS Sierra
Node Version: v7.3.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jodybrewster** [comment] 2017-02-15 16:39
BTW, I can help track down the bug and fix it so I'm also looking for some ideas as to where to look to fix it.

**Comment by jgw96** [comment] 2017-02-15 18:46
Hmm, this is an interesting issue. If you use [our fork of the wkwebview plugin](https://github.com/driftyco/cordova-plugin-wkwebview-engine) do you run into the same issue? UiWebView has alot of weird scrolling edge cases that we are constantly battling with but wkwebview is much more stable in this area.

**Comment by jgw96** [comment] 2017-02-21 21:08
Hello! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-02-21 21:08 UTC
Labels: needs reply, v2

**Comment by jodybrewster** [comment] 2017-02-24 21:52
@jgw96 hey man, thanks for the help.  Definitely not finished, this is an ongoing issue over here.  Is there any point where they turn off scrolling?  I read somewhere its been added for jank?  I'd like to optimize it or turn it off.  Cause I can get it into this state every time... https://www.youtube.com/watch?v=OtSY6v9ftKU

**Comment by jodybrewster** [comment] 2017-02-24 22:05
@jgw96 Hey some more color as I'm diving into the Ionic code, I have a custom app where we have a custom wkWebView wrapper.  Is it possible that I'm missing something like the stopScroll code in the wkwebview plugin?  What does that do anyway?  Is there a chat where I can talk to someone about this?

**Comment by teknekale** [comment] 2017-04-06 12:06
Hi @jgw96, I have a similar issue.
I have an web-app with ionic (so no native app o what so ever) and I'm doing this test on Safari (latest iOS, iPhone 6). 

When I have a long page the inertial scrolling is working fine and when reaching the bottom it will bounce a bit further and then smoothly going back into place (normal and correct behaviour). Then if I'm in the bottom (or the top) of the page and I try to scroll further to the bottom it won't do anything (normal and correct behaviour), but if I quickly scroll to the top (or the bottom) after that I will have a stuck behaviour till I release the scrolling. Starting to scrolling again to the top (or the bottom) now it will work fine.

I can reproduce this every time I want, only on iPhone, not on Android.

**Comment by ivanwonder** [comment] 2017-04-07 12:05
@jgw96 I think this problem happen because the body use the style `position: fixed`, and I don't know why ionic choose to use `fixed` rather than the `absolute`. @teknekale @jodybrewster you can try, it becomes better after I replace it with the `absolute`. btw,  when reaching the bottom, you must wait till the page bounce back and then continue scroll the content.

**Comment by markholland** [comment] 2017-04-08 18:45
We're having the same issue, easily reproducible in iOS safari with the conference app. Happens both at top and bottom of a scrollable list.

**Comment by manucorporat** [comment] 2017-04-08 19:14
This only happen in Safari because the focus of the scrolling events goes to the <body> tag instead of `ion-content`.

Fortunately this does not happen when building the app with Cordova and WK!

**Comment by markholland** [comment] 2017-04-08 19:18
@manucorporat so no workaround when using ionic only as a web app?

**Comment by gregor-srdic** [comment] 2017-04-22 15:12
I also encountered this issue when running my ionic app in safari or chrome browser on iOs. But it seems to me the issue affects any action elements (i.e. buttons) which also sometimes stop responding :S

**Comment by johnhny** [comment] 2017-04-22 22:11
I also encounter similar issues on iOS (safari and chrome). I use a ion-navbar and below an iframe (width/height 100%) inside ion-content.

The page within the iframe jumps back to the top after one full "viewport-scroll"... if I scroll down again the scroll freezes..

Anybody any luck to get around these iframe issues on iOS?

Thank you,
Arno

**Comment by tomwey** [comment] 2017-06-07 10:06
@markholland I also encounter similar issues on iOS safari，how to resolve the issue?

**Comment by kaldr** [comment] 2017-06-28 05:42
I tried chrome on ios devices, it happened too. Maybe Chrome on ios is also safari browser core.
Although my solution will cause losing the bouncing effect, you can try it.
ionic Content component has a method called 'enableJsScroll', which will disable the native scroll of safari.
```typescript
import {Platform,Content} from 'ionic-angluar'
export class MyPage{
    @ViewChild(Content) content: Content
    ngOnInit() {
	if (this.platform.is('mobileweb') && this.platform.is('ios')) {
		this.content.enableJsScroll()
	}
    }
    constructor(private platform:Platform){}
}
```

**Comment by doender** [comment] 2017-07-14 20:49
I'm having the same problem: scroll freezes on iOS with wkwebview like in @jodybrewster's video. Did you ever manage to solve this?

**Comment by toddmillernyc** [comment] 2017-09-04 20:44
I am also experiencing this in iOS chrome and Safai.  My app is based off of the Conference template.  Seems to happens when I navigate back from a page off the root.

**Comment by AntoineFemolant** [comment] 2018-01-15 15:37
Hello,

Thank you @kaldr! It seems to be a workaround with an acceptable scroll.

However I see two regressions in long scroll page:
- On iOS9 WebApp: elements appear jerkily.
- Much more serious: using next button on keyboard several times brokes the page. I can't go to the top of the page and the bottom of the page is no longer at the bottom of the screen.

Have you got these problems?

TIA.

Antoine F
