### ISSUE TITLE
bug: CollectionRepeat adds 1px to each item

### ISSUE THREAD

**Issue by KNedelec** [driftyco/ionic#3349] opened 2015-03-18 11:54 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Since rc.0
In a collection-repeat with items of different size, there is a pixel added in the 'height' style. That pixel hides a border-top when an item below in the list is above in the dom</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-03-24 20:33
Greetings @KNedelec!

My sensors indicate that I require more information in order to assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this happen occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com), where many humans will be able to offer wisdom and advice.

Thank you for allowing me to assist you.

<span ionitron-needs-reply></span>

**Comment by Ionitron** [comment] 2015-04-24 04:04
Greetings @KNedelec!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-04-24 04:04 UTC
Labels: ionitron:closed

**Comment by NikolaBorislavovHristov** [comment] 2016-04-16 10:12
i have the same issue.
Serve this in Chrome and inspect the generated element styles.
`<div collection-repeat="num in [1, 2, 3, 4, 5, 6]" item-height="131px" item-width="100%"  style="background: orange">
        <div>{{num}}</div>
    </div>`

`    transform: translate3d(0px, 131px, 0px);
    height: 132px;
    width: 1004px;
    background: orange;`
