### ISSUE TITLE
bug: CSS is wrong with Crosswalk

### ISSUE THREAD

**Issue by do-web** [driftyco/ionic#3765] opened 2015-05-18 12:55 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>I use crosswalk, is then added to the body tag.

But the styles are wrong for crosswalk for example:

.platform-android .popover {
  margin-top: -32px;
  background-color: #fafafa;
  box-shadow: 0 2px 6px rgba(0, 0, 0, 0.35);
}

with crosswalk this style does not work.

How can i disable for android the bodytag classes?

Please add special style for crosswalk.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-05-18 12:55
Greetings @do-web!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3765). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3765)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment] 2015-05-18 19:17
I'm having trouble reproducing the problem. When I use crosswalk, the `platform-android` class is applied just fine. Is there anything special about your project that would prevent that from happening? like are you customizing the build process at all?

**Comment by do-web** [comment] 2015-05-21 10:22
yes it is applied fine but the style ist wrong, for crosswalk margin-top: 0px; is working otherwise the popover header is out of the view. No there is nothing special.

**Comment by Ionitron** [comment] 2015-08-19 14:03
Greetings @do-web!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2015-08-19 14:03 UTC
Labels: ionitron:closed
