### ISSUE TITLE
[rc2] Splash screen not working in android

### ISSUE THREAD

**Issue by jlno** [driftyco/ionic#9060] opened 2016-11-06 23:40 UTC
`ionic start myApp --v2`
`ionic platform add android`
`ionic resources`
`ionic run android`

Splash screen is not shown.

**Comment by ghenry22** [comment] 2016-11-07 06:04
I think it's actually the cordova android 6.0 platform that causes this.  Ionic resource generator needs to be updated to put resources in the right place and make sure that they are used for the latest android cordova platform.

I also noticed that when the new platform is installed it creates it's own "res" folder in the root of the project and copies some files into it but they don't seem to be used.

**Comment by jgw96** [comment] 2016-11-07 10:00
@jlno Are you using cordova android 6.0?

**Comment by eweap** [comment] 2016-11-07 10:11
@jgw96 I'm having the same problem with android 6.0, i think it's a duplicate with driftyco/ionic-cli#1608

**Comment by jlno** [comment] 2016-11-07 10:32
@jgw96 cordova 6.4.0

**Comment by jonatastrafaniuc** [comment] 2016-11-08 12:43
The same problem here. App icon also does not work.

**Comment by JulienPalard** [comment] 2016-11-08 15:35
Same problem here:

Works with: ionic 2.0.0 + cordova 6.3.1
Does not work with: ionic 2.1.0 + cordova 6.4

**Comment by NeoLSN** [comment] 2016-11-09 06:12
Same issue here.

**Comment by ghenry22** [comment] 2016-11-09 12:05
Upgrade to android platform 6.1.0 and this should be fixed, just updated my project, reran ionic resources and then build and all good.

**Comment by workfluo** [comment] 2016-11-09 13:24
> Upgrade to android platform 6.1.0
How to do this?

**Comment by workfluo** [comment] 2016-11-09 13:54
No need for me:
My solution with a config like:
Cordova CLI: 6.4.0 + Ionic Framework Version: 2.0.0-rc.2 + Ionic CLI Version: 2.1.4;
is basically:
after the Command $ionic resource,
in config.xml for all the
<splash src="resources/android/splash/drawable-land-ldpi-screen.png" density="land-ldpi"/>
REPLACE "density" by "qualifier"
AND
in
REPLACE value="screen" by value="splash"

**Comment by ghenry22** [comment] 2016-11-09 15:36
Ionic platform remove android
Ionic platform add android@6.1.0

**Comment by jgw96** [comment] 2016-11-09 15:44
Hello all! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic-cli/issues/1638. This was a regression in `cordova-android` that has been fixed by the cordova team and released in 6.1.0. You can use the commands @ghenry22 posted above to update cordova-android platform.

**Closed by jgw96** 2016-11-09 15:44 UTC
Labels: needs reply, v2

**Comment by mflmartin** [comment] 2016-11-14 14:02
Doesn't work. Even after installing android@6.1.0 Just shows a blank screen now, .
 
Does it work for someone?

**Comment by ghenry22** [comment] 2016-11-14 14:22
If you remove and add the platform the plugins should automatically remove and as well, I didnt need any extra steps but you never know, I have seen Cordova plugin. Issues resolved before by a simple remove/add

**Comment by florentsuc** [comment] 2016-11-18 10:52
If you still have the problem, check out my comment: https://github.com/driftyco/ionic-cli/issues/1608#issuecomment-261503645

**Comment by chrisbenseler** [comment] 2016-12-16 14:20
@JulienPalard same problem for me with corodva6.4.0. Downgrade to 6.3.1, everything is ok.
