### ISSUE TITLE
virtualScroll shows no data when array is asynchronously populated (v2)

### ISSUE THREAD

**Issue by agates** [driftyco/ionic#6125] opened 2016-04-11 21:38 UTC
virtualScroll doesn't display any data when using an Observable + async pipe until a page resize.

Once the page is resized the data appears to be displayed properly.

Here's an example of what I'm trying to do:
``` Typescript
import {Page} from 'ionic-angular';
import {DataService} from './service';
import {Observable} from "rxjs/Observable";


@Page({
    templateUrl: `
    <ion-content padding>
        <div [virtualScroll]="data | async">
            <ion-card *virtualItem="#d">
                <ion-card-header><b>{{d.header}}</b></ion-card-header>
                <ion-card-content>
                    {{d.description}}<br>
                    {{d.date}}
                </ion-card-content>
            </ion-card>
        </div>
    </ion-content>`
})
export class DataPage {
    data:Observable<any[]>;

    constructor(private _dataService:DataService) {
        this.data = this._dataService.getData();
    }
}
```

I'm running ionic v2 beta 4.

**Comment by adamdbradley** [comment] 2016-04-12 03:51
Thanks, we'll take a look. I'll close this one since it's a duplicate of #6124

**Closed by adamdbradley** 2016-04-12 03:51 UTC
Labels: header, virtualscroll
