### ISSUE TITLE
bug:$digest already in progress when click quickly -- only iOS

### ISSUE THREAD

**Issue by mljsgto222** [driftyco/ionic#6634] opened 2016-05-24 10:13 UTC
**type**: bug
**Platform**: iOS 9.3 webview and safari

if the user click element quickly when use ng-click or ionicGesture only on iOS, this error  `$digest already in progress` in ionic 1.3.0.

And I found this issus in this code:
`scope.$apply(function() {
        clickHandler(scope, {$event: (event)});
 });`
[https://github.com/driftyco/ionic/blob/master/js/angular/directive/ngClick.js#L21](url)

After I replaced the $apply with $applyAsync or $timeout, this issue is resolved

**Comment by jgw96** [comment] 2016-07-18 19:30
Hello! After reviewing this issue it seems that this is actually an Angular issue. Because of this I will be closing this issue for now. Thanks for using Ionic!

**Closed by jgw96** 2016-07-18 19:30 UTC
Labels: platform:ios, v1

**Comment by jskrepnek** [comment] 2016-08-02 19:58
@jgw96 Can you link to the Angular issue that you mentioned?

**Comment by VinceOPS** [comment] 2017-08-24 23:11
The issue is not with Angular but with the complete drop of Ionic v1 support.
The issue still exists with ionic v1.3.3 on iOS 10+ (10.1, 10.2, 10.3).

For anyone arriving here and having the same issue, [here's my patch](https://github.com/VinceOPS/ionic/commit/45b27b8837356b7a3f21d39db77f7e10aee3abf5) (for what it's worth).
