### ISSUE TITLE
bug: ngIf statement in ion-icon element breaks position

### ISSUE THREAD

**Issue by lordgreg** [driftyco/ionic#5636] opened 2016-02-28 00:51 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Having `ion-icon` element with ngIf statement and `item-right` directive, breaks internet.

Example (parts taken from ionic2 preview pages):
```
  <ion-list>
    <ion-list-header>
      Busters
    </ion-list-header>

    <ion-item-sliding>
      <ion-item>
        <ion-avatar item-left>
          <img src="https://github.com/driftyco/ionic-preview-app/blob/master/app/img/avatar-samwise.jpg?raw=true">
        </ion-avatar>
        <ion-icon item-right primary
          *ngIf="true" 
          name="checkmark-circle"></ion-icon>
        <h2>This item has ngIf on ion-icon</h2>
        <p>Back off man, I'm a scientist.</p>
      </ion-item>
      <ion-item-options>
        <button light>
          <ion-icon name="ios-more"></ion-icon>
          More
        </button>
        <button primary>
          <ion-icon name="text"></ion-icon>
          Text
        </button>
      </ion-item-options>
    </ion-item-sliding>
    
    <ion-item-sliding>
      <ion-item>
        <ion-avatar item-left>
          <img src="./img/venkman.jpg">
        </ion-avatar>
        <ion-icon item-right primary
          name="checkmark-circle"></ion-icon>
        <h2>This item doesn't have ngIf on ion-icon</h2>
        <p>Back off man, I'm a scientist.</p>
      </ion-item>
      <ion-item-options>
        <button light>
          <ion-icon name="ios-more"></ion-icon>
          More
        </button>
        <button primary>
          <ion-icon name="text"></ion-icon>
          Text
        </button>
      </ion-item-options>
    </ion-item-sliding>
  </ion-list>
```
</span>

<span is-issue-template></span>

**Comment by ZiFFeL1992** [comment] 2016-02-28 15:19
This also happends with buttons:

```
<ion-item>
  <h2>tittle</h2>
  <p>subtitle</p>
  <button *ngIf="contidition" item-right outline>
    <icon...>
    some text
  </button>
</ion-item>
```

The button moves to the left, but if I remove the ngIf tag, the button gets place to the correct position.

**Comment by brandyscarney** [comment] 2016-02-29 17:07
Thanks for the issue, this is a duplicate of https://github.com/driftyco/ionic/issues/5060 and is reported on the Angular repo here: https://github.com/angular/angular/issues/5363

**Closed by brandyscarney** 2016-02-29 17:07 UTC
Labels: header, platform:ios, v2
