### ISSUE TITLE
TABS broken 1.3.1

### ISSUE THREAD

**Issue by emps** [driftyco/ionic#6527] opened 2016-05-14 09:51 UTC
v1.3.1

tabs titles are not working,
back button for specific tab stays with all tabs

**Comment by emps** [comment] 2016-05-14 16:42
example of tabs with ui-view in inside home tab
http://codepen.io/emps/pen/bpJMEr?editors=1010

1) tab title broken in home tab where i added ui-view (i have 2 views in my app in 1 tab switching between them with segment)
2) go to facts tab and enter "Tabs Stack Nav" and press "Home" tab u see back button stays in the Nav

3*) i notice also playing too much with tabs navs back button disapears and then no back button to main tabs

same code with 1.3.0 works ok

**Comment by J-who** [comment] 2016-05-15 04:20
Yeah I'm also experiencing this as well.

**Comment by emps** [comment] 2016-05-15 23:17
any team devs around to look for this issue ?

**Comment by zMADCATz** [comment] 2016-05-16 04:13
same here need fix ;)

**Comment by danbucholtz** [comment] 2016-05-16 14:35
Can you explain your issue a little more?  I am not seeing the issues with tabs here.

http://codepen.io/ionic/pen/odqCz

Thanks,
Dan

**Comment by emps** [comment] 2016-05-16 16:20
i have provided http://codepen.io/emps/pen/bpJMEr?editors=1010

1) 
whattodo: go to About tab and press Nav Tabs Stack and then go to Home tab
issue: Back button of About tab history stays with Home tab
cause: added ui-view inside Home tab (im using views inside the tab)

2)
whattodo: just look at the nav
issue: Home title isnt presented with Home Tab
cause: added ui-view inside Home tab (im using views inside the tab)

i must ui-view inside my tab cause im using diffrent views

**Comment by Manduro** [comment] 2016-05-17 12:05
Confirmed here as well

**Comment by shyamal890** [comment] 2016-05-18 19:33
@emps @danbucholtz  Add https://github.com/driftyco/ionic/issues/6529 too, to the list of **Tab Bugs**

**Comment by emps** [comment] 2016-05-19 07:47
good morning is there fix comming for this issue ?

**Comment by danbucholtz** [comment] 2016-05-19 14:48
Hi @emps,

Yes, I'll take a look at this.

Thanks,
Dan

**Comment by barocsi** [comment] 2016-06-06 22:57
+1 its like 1 thing fixed 3 messed up...

**Comment by danbucholtz** [comment] 2016-06-07 03:09
Hi @emps,

I am looking at this right now.

Nested states in ui-router are not supported in v1.  The issue is `tabs.home.uiview`.  Once I remove this unsupported state, the title shows up as expected.

I'll take a look at the history issue.  Unfortunately, history issues are very complicated with ui-router.  Basically all of the issues with 1.x and navigation will go away in Ionic 2.

Thanks,
Dan

**Comment by danbucholtz** [comment] 2016-06-07 03:15
Hi @emps,

Just took a lot at the back-button issue.  It seems like it is due to the nested state as well.  Once I remove that, the issue goes away.

At this time, I don't think we're going to make any changes to the framework.  I'm really sorry you're seeing an issue here.  I will be the first to admit our nested state management is not where we'd like it to be.  ui-router has been a definite challenge for us.

Thank you for using Ionic.  Please check out V2 when you get a chance.  Most, if not all, of these complicated nav issues are resolved by implementing our own navigation system.

Thanks,
Dan

**Closed by danbucholtz** 2016-06-07 03:15 UTC
Labels: v1

**Comment by danbucholtz** [comment] 2016-06-07 03:58
Hi @emps - there are work arounds for this issue.  I'll come up with something and let you know.  Abstract states require an `ion-nav-view` in Ionic.  I'll update with a zip when I have something for you.

**Comment by danbucholtz** [comment] 2016-06-07 04:20
Here is a sample project and specific commit that shows how to make your project work.

https://github.com/danbucholtz/emps-nested-state-example/commit/3cf8c5328f48aaf64ab760b889c92a4909443d16

Thanks,
Dan

**Comment by barocsi** [comment] 2016-06-07 07:13
I might have a different issue, I am setting a title={{navTitle}} variable from within a controller. When the tab changes, the title changes. However on the very first load of the app, the title is the title defined for the controller is displayed then after a flicker ion-view title defined for the nav view is displayed.
```html
<ion-view title="Tabs /* after a flicker this is displayed and not the controller defined title*/" left-buttons="leftButtons">
  <div class="tabs-striped tabs-color-white">
    <ion-tabs class="tabs-default bt-tabs-bottom tabs-icon-top">

      <ion-tab title="MY STUFF" icon="ion-images" ng-click="myPostsClicked()">
        <ion-nav-view name="posts-tab"></ion-nav-view>
      </ion-tab> 
  </div>
</ion-view>

**Comment by barocsi** [comment] 2016-06-07 08:09
In 1.3.1 needed to remove the wrapping ion-view, that fixed.

**Comment by emps** [comment] 2016-06-07 09:28
ok thanks @danbucholtz i will look in ur example thanks a lot

**Comment by Manduro** [comment] 2016-06-08 10:05
@danbucholtz Here is another tab use-case that worked in 1.3.0, but is broken in 1.3.1. I've tried lots of other state/view setups, but none of them do what it does here. If this bug is not going to be fixed, what would be your proposed solution for this tab use-case?
http://codepen.io/anon/pen/rLOQgo

**Comment by katche70** [comment] 2016-08-16 15:02
How to solve this issue? same here after upgrading to 1.3.1

**Comment by emps** [comment] 2016-08-16 16:04
use ng-show/hide with ng-templates.... this how i pass it
