### ISSUE TITLE
ionic 2: ionic resources --icon not update my ionic logo app

### ISSUE THREAD

**Issue by adirzoari** [driftyco/ionic#10079] opened 2017-01-17 20:57 UTC
I'm trying to update my ionic 2 app logo with the command

> ionic resources --icon
I did a new logo and it i see it create the logo in other sizes after this command but when i move the apk app to my phone, it still the default logo.

I already tried to delete the platform folder and it didn't helped me.

**Comment by brandyscarney** [comment] 2017-01-17 21:24
Closing as a duplicate of https://github.com/driftyco/ionic-cli/issues/1857, thanks!

**Closed by brandyscarney** 2017-01-17 21:24 UTC
