### ISSUE TITLE
Replacing the root of a tab component (potential bug)

### ISSUE THREAD

**Issue by morious** [driftyco/ionic#8722] opened 2016-10-15 20:14 UTC
Hi,
I have a tabs component with two tabs in it.
In the component constructor I am setting the variables that are bound the root of each tab as in the tabs documentation here:
http://ionicframework.com/docs/v2/api/components/tabs/Tabs/
What I am trying to do is later, replace the component that is assigned to the second tab using:
```
this.tabs.getByIndex(1).setRoot(MyOtherComponent);
```
The result behavior is that the tab content disappears.
Could be a bug, but I am not sure if my approach is correct...
Any advise on how to accomplish what I am trying to do?
Thanks!

**Comment by jgw96** [comment] 2016-10-16 21:45
Hello, thanks for opening an issue with us! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/8682.

**Closed by jgw96** 2016-10-16 21:45 UTC

**Comment by morious** [comment] 2016-10-17 01:08
To add more color to this issues.
When binding to local variables that represent a tab, ex:
```
this.tab2 = MyOtherComponent
```
there was no affect at all.

I do see an improvement in RC1, but only for the first set operation...when the tab is set back to the previous component the operation fails.

```
this.tab2 = Comp1; //works

this.tab2 = Comp2; //works as expected

this.tab2 = Comp1; //setting back to previous component is not not working.
```

I hope that helps.
