### ISSUE TITLE
bug: Bug in Tab Navigation - (back button not visible)

### ISSUE THREAD

**Issue by DrJonnie** [driftyco/ionic#7816] opened 2016-08-22 08:49 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi all,

in the current ionic verion 1.3.1 the back navigation seems to be broken. The back button is not visible on subpages of an tab after some navigation steps.

The bug is replicable with the following steps:

CodePen 1.3.1
https://codepen.io/DrJonnie/pen/qNwJBK

1. click button "Scientific Facts"
2. click back button "< Home"
3. click tab "About"
4. click button "Tabs Nav Stack"
5. click back button "< About"
6. click tab "Home"
7. click button "Scientific Facts"
8. click back button "< Home"
9. click tab "About"
10. click button "Tabs Nav Stack"

>>> BUG:   Back Buttton "< About" is not shown!

With version 1.3.0 the back button "< About" is shown correctly:

CodePen 1.3.0
https://codepen.io/DrJonnie/pen/yJARyg</span>

<span is-issue-template></span>

**Comment by jgw96** [comment] 2016-08-22 16:02
Hello! Thanks for opening an issue with us! I am going to be closing this issue as a duplicate of https://github.com/driftyco/ionic/issues/6875. Thanks for using Ionic!

**Closed by jgw96** 2016-08-22 16:02 UTC
Labels: navigation, v1
