### ISSUE TITLE
bug: Main view flickering after touch ends on side menu opening

### ISSUE THREAD

**Issue by brendandebeasi** [driftyco/ionic#4840] opened 2015-12-22 01:28 UTC
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>I recently upgraded to 1.2.1 and began having a problem where the main view would flicker white for several MS after touch end of swiping to open the menu. 
(the animation of the menu is smooth, the GIF just makes it look janky"
![flicker](https://cloud.githubusercontent.com/assets/1968286/11945766/1899154c-a808-11e5-8c7b-0d89ecdd91d8.gif)

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment] 2015-12-22 01:28
Greetings @brendandebeasi!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4840). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4840)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by brendandebeasi** [comment] 2015-12-22 18:14
I experienced this bug on iOS 9.2. It was not present when being viewed through ionic serve or ionic view. Additionally I revered to ionic lib 1.1.1 which resolved the issue. I believe this is a problem with 1.2.1

**Comment by mlynch** [comment] 2015-12-22 18:33
Hmm, not able to reproduce. Do you have any example code to share?

**Comment by brendandebeasi** [comment] 2015-12-22 18:39
I'm not doing anything unusual with the view as far as I can tell.

Routes:
```
angular.module('app.routes', [])

    .config(function($stateProvider, $urlRouterProvider) {

        $stateProvider

            .state('login', {
                url: '/login',
                templateUrl: 'templates/login.html',
                controller: 'AppCtrl'
            })

            .state('run', {
                url: '/app',
                abstract: true,
                templateUrl: 'templates/menu.html',
                controller: 'AppCtrl',
                onEnter: function($state, Auth){

                    if(!Auth.isLoggedIn()){
                        $state.go('login');
                    }
                }
            })

            .state('run.loans', {
                url: '/loans',
                views: {
                    'menuContent': {
                        templateUrl: 'templates/loans.html',
                        controller: 'LoansCtrl'
                    }
                }
            })

            .state('run.privacy', {
                url: '/privacy',
                views: {
                    'menuContent': {
                        templateUrl: 'templates/privacy.html',
                        controller: 'PrivacyCtrl'
                    }
                }
            })

            .state('run.terms', {
                url: '/terms',
                views: {
                    'menuContent': {
                        templateUrl: 'templates/terms.html',
                        controller: 'TermsCtrl'
                    }
                }
            })

            .state('run.support', {
                url: '/support',
                views: {
                    'menuContent': {
                        templateUrl: 'templates/support.html',
                        controller: 'SupportCtrl'
                    }
                }
            })

        ;

        // if none of the above states are matched, use this as the fallback
        $urlRouterProvider.otherwise('/login');
    });
```

menu.html
```
<ion-side-menus enable-menu-with-back-views="true">
    <ion-side-menu-content>
        <ion-nav-bar>
            <!--<ion-nav-back-button>-->
            <!--</ion-nav-back-button>-->

            <ion-nav-buttons side="right">
                <button class="button button-icon button-clear ion-navicon" menu-toggle="right">
                </button>
            </ion-nav-buttons>
        </ion-nav-bar>


        <!--<ion-header-bar align-title="left" ng-bind-html="headerImage"></ion-header-bar>-->
        <ion-nav-view name="menuContent">

        </ion-nav-view>
    </ion-side-menu-content>

    <ion-side-menu side="right">
        <ion-content scroll="false" class="side-menu-contain">
            <ul class="list">
                <a ui-sref="run.loans"
                   ui-sref-active="active"
                   class="item item-icon-right"
                   menu-close>
                    Loans
                    <i class="icon ion-ios-arrow-right"></i>
                </a>
                <a ui-sref="run.privacy"
                   ui-sref-active="active"
                   class="item item-icon-right"
                   menu-close>
                    Privacy Policy
                    <i class="icon ion-ios-arrow-right"></i>
                </a>
                <a ui-sref="run.terms"
                   ui-sref-active="active"
                   class="item item-icon-right"
                   menu-close>
                    Terms of Service
                    <i class="icon ion-ios-arrow-right"></i>
                </a>
                <a ui-sref="run.support"
                   ui-sref-active="active"
                   class="item item-icon-right"
                   menu-close>
                    Support
                    <i class="icon ion-ios-arrow-right"></i>
                </a>
                <a ng-click="logout()"
                   ui-sref-active="active"
                   class="item item-icon-right"
                   menu-close>
                    Logout
                    <i class="icon ion-ios-arrow-right"></i>
                </a>
            </ul>
        </ion-content>
    </ion-side-menu>
</ion-side-menus>
```

**Comment by lehtiton** [comment] 2016-01-04 09:11
I experienced exactly this same issue when updated today my ionic lib from 1.1.0 to 1.2.1. Everything seems to be fine with desktop browser but I'm facing this same very annoying flickering when testing with iPhone 6 Plus (iOS 9.1).

I found out that this is something related to ion-scroll functionality. I do not face this issue with views having <ion-content scroll="false">. But when the scroll is not set to false it is flickering. And if I drag the side menu open slowly, the flickering happens right after releasing the drag.

Any news on this? Any workaround found?

**Comment by brycecammo** [comment] 2016-01-04 10:18
I too was experience this issue after updating to `1.2.1`. I just updated to the latest nightly build (`1.2.4-nightly-1917`) and it seems to be fixed.

**Comment by lehtiton** [comment] 2016-01-04 13:08
Thanks, that 1.2.4 nightly build solved my case as well! By the way, do you happen to know that what is the official way for updating the nightly build? Is there a CLI command like "ionic update 1.2.4-nightly-1917" or do I need to work with bower?

**Comment by brendandebeasi** [comment] 2016-01-07 02:18
@lehtiton I checked the ionic-cli source and you can pass an argument --version with the version number. For your purposes you would use ionic lib update --version nightly

**Comment by mlynch** [comment] 2016-01-07 02:38
Did 1.2.4 fix this? I did add some code to fix this. Closing since it seems to resolve the issue.

**Closed by mlynch** 2016-01-07 02:38 UTC

**Comment by brendandebeasi** [comment] 2016-01-07 02:39
@mlynch Thank you :+1:

**Comment by lehtiton** [comment] 2016-01-07 06:57
@mlynch Yes, the nightly seems to fix the issue indeed, thanks. And @brendandebeasi thanks for helping with ionic lib update.

**Comment by zaniniii** [comment] 2016-03-07 00:34
Thank you :+1:
