### ISSUE TITLE
Navigation history to a Tabs page doesn’t work 

### ISSUE THREAD

**Issue by guillaume-roy** [driftyco/ionic#6011] opened 2016-04-01 12:58 UTC
Hello,

The navigation history doesn't work in a tabs page.

I have a root page who displays a basic ion-list with a FAB button.
When i click on the FAB button to create a new item, i perform a : 
`this.nav.push(CreatePage, { myParams });`

The CreatePage is a TabPage like this :

```
@Page({
  template: `
    <ion-tabs [selectedIndex]="selectedTab">
      <ion-tab tabTitle="A" [root]="ATab" [rootParams]="{ myParams }"></ion-tab>
      <ion-tab tabTitle="B" [root]="BTab" [rootParams]="{ myParams  }"></ion-tab>
      <ion-tab tabTitle="C" [root]="Tab" [rootParams]="{ myParams  }"></ion-tab>
    </ion-tabs>`
})
export class CreatePage {
// [...]
}
```

No matter of the tab where i am, if i tap on the back button on my Android device, the entire app closes and i get back to my home screen instead of returning to my ion-list page.

I have the same behavior if i open a modal from a tab page. When i tap on back button, i go back to the home screen.

Here is the code of a tab page :

```
@Page({
  templateUrl: 'build/pages/create-page/a-tab.html'
})
export class ATab {
// [...]
}
```

```
<ion-navbar *navbar secondary>
  <ion-buttons start>
    <button (click)="cancel()">
      <ion-icon name="close"></ion-icon>
    </button>
  </ion-buttons>
  <ion-title>Create</ion-title>
  <ion-buttons end>
    <button (click)="save()">
      <ion-icon name="checkmark"></ion-icon>
    </button>
  </ion-buttons>
</ion-navbar>

<ion-content>
<!-- ... -->
</ion-content>
```

Also, when i go to the create page, the navbar never shows the back icon on Android or my web browser (using ionic serve).

Windows 10
Cordova CLI: 6.1.0 (cordova-lib@undefined)
Gulp version: CLI version 3.9.1
Gulp local: Local version 3.9.1
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.23
Ionic App Lib Version: 2.0.0-beta.13
OS:
Node Version: v4.2.3

**Comment by royipressburger** [comment] 2016-04-01 13:37
Im not a big expert but is there a chance that when you load the `CreatePage` the `[root]="ATab"` cause the nav stack to be empty? maybe the `[root]="ATab"` is like writing `this.nav.setRoot(..)` so when u go back u go to an empty stack?

**Comment by guillaume-roy** [comment] 2016-04-01 13:42
Yes it seems that is something like that.

But according to the doc (http://ionicframework.com/docs/v2/components/#tabs), i have to use `[root]`.

**Comment by jgw96** [comment] 2016-04-01 14:14
Hello, thanks for opening an issue with us! We really appreciate it! The reason your back button on your Android device is not working is because we have not yet implemented support for it in Ionic 2, although it is on the roadmap! (: . Now, the second issue with the back button does look like a bug to me. I will have to do some testing to see if I can reproduce it with your code. Thanks again!

**Comment by jgw96** [comment] 2016-05-27 06:51
Hello all! This should be fixed in the latest version of Ionic 2 (beta.7). Thanks for using Ionic!

**Closed by jgw96** 2016-05-27 06:51 UTC
Labels: modals, navigation, needs:devicetesting, platform:android, v2
