### ISSUE TITLE
RC0 ionic emulate ios -lc not working

### ISSUE THREAD

**Issue by richardshergold** [driftyco/ionic#8463] opened 2016-10-04 08:33 UTC
with RC0 the command:

ionic emulate ios -lc

doesn't appear to work for me (the app hangs on loading screen)

ionic emulate ios works ok but appears not to with the -lc flags added

**Comment by olavocneto** [comment] 2016-10-04 13:58
https://forum.ionicframework.com/t/rc0-livereload-android-not-working/65045/10

**Comment by jgw96** [comment] 2016-10-04 14:51
Hello, thanks for opening an issue with us! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic-cli/issues/1436. Thanks!

**Closed by jgw96** 2016-10-04 14:51 UTC
