### ISSUE TITLE
bug: ToastController not found in Ionic2-Beta32

### ISSUE THREAD

**Issue by nottinhill** [driftyco/ionic#7633] opened 2016-08-10 01:00 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I am using latest Ionic 2 beta at the time of writing. I wanted to import from ionic-angular package the `ToastContoller` module.

http://ionicframework.com/docs/v2/api/components/toast/ToastController/1

Unfortunately my IDE tells me:

```TS2305:Module ..../ionic-angular/index" has no exported member 'ToastController'.```</span>

<span is-issue-template></span>

**Comment by jtushar53** [comment] 2016-08-10 05:42
ToastController is available from ionic beta11, please check ```ionic info``` for version of ionic. beta 32 is of ionic cli and not ionic. also upgrade ionic-cli by using ```npm install -g ionic@beta```

you can upgrade your project with ionic beta 11 from here https://github.com/driftyco/ionic/blob/master/CHANGELOG.md, check for Steps to Upgrade

**Comment by shenmingxuanyi** [comment] 2016-08-10 06:29
please update the new version to npm server

**Comment by jgw96** [comment] 2016-08-10 14:59
Hello all! Thanks for opening an issue with us! Unfortunately, i cannot reproduce this issue with beta.11 and vscode. I would definitely check that you upgraded correctly by giving our [changelog](https://github.com/driftyco/ionic/blob/master/CHANGELOG.md) a quick read. Thanks for using Ionic!

**Comment by jgw96** [comment] 2016-08-10 15:51
@nottinhill After reviewing this issue i have come to the conclusion that most likely it is just intellisense in your ide is not properly updating for you. I sometimes experience this with vscode and simply have to close and open the project a few times to get it to update. Since this isnt really an Ionic issue but is more of an issue with your particular ide and its typescript support i am going to be closing this issue for now. Thanks for using ionic!

**Closed by jgw96** 2016-08-10 15:51 UTC
Labels: needs reply, v2
